DGtal: LibBoard::Dot Struct Reference
LibBoard::Dot Struct Reference
#include <Board/Shapes.h>
Public Member Functions
Dot (double x, double y, DGtal::Color color, double lineWidth, int depth=-1)
const std::string & name () const
Point center () const
Dot & rotate (double angle, const Point &center)
Dot rotated (double angle, const Point &center) const
Dot & rotate (double angle)
Dot rotated (double angle) const
Dot & translate (double dx, double dy)
Dot translated (double dx, double dy) const
Shape & scale (double sx, double sy)
Shape & scale (double s)
Dot scaled (double sx, double sy) const
Dot scaled (double s) const
void scaleAll (double s)
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
Rect boundingBox () const
Dot * clone () const
Public Member Functions inherited from LibBoard::Shape
Shape (DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, LineStyle style, const LineCap cap, const LineJoin join, int depth)
virtual ~Shape ()
bool filled () const
Shape & rotateDeg (double angle, const Point &center)
Shape & rotateDeg (double angle)
Rect bbox ()
Shape & operator-- ()
Shape & operator++ ()
int depth () const
virtual void depth (int)
virtual void shiftDepth (int shift)
const DGtal::Color & penColor () const
const DGtal::Color & fillColor () const
Protected Attributes
double _x
double _y
Protected Attributes inherited from LibBoard::Shape
int _depth
DGtal::Color _penColor
DGtal::Color _fillColor
double _lineWidth
LineStyle _lineStyle
LineCap _lineCap
LineJoin _lineJoin
Static Private Attributes
static const std::string _name
Additional Inherited Members
Public Types inherited from LibBoard::Shape
enum LineCap { ButtCap = 0, RoundCap, SquareCap }
enum LineJoin { MiterJoin = 0, RoundJoin, BevelJoin }
enum LineStyle {
SolidStyle = 0, DashStyle, DotStyle, DashDotStyle,
DashDotDotStyle, DashDotDotDotStyle
}
Protected Member Functions inherited from LibBoard::Shape
std::string svgProperties (const TransformSVG &transform) const
std::string postscriptProperties () const
void setCairoDashStyle (cairo_t *cr, LineStyle type) const
std::string tikzProperties (const TransformTikZ &transform) const
Detailed Description
A line between two points.
The dot structure. This primitive ha been reported as "missing" by Manuel Peinado from Spain. Manuel also suggested that rendering a dot consists in drawing a line from a point to the same point with a roundcap style.
Definition at line 398 of file Board/Shapes.h.
Constructor & Destructor Documentation
LibBoard::Dot::Dot (double x, double y, DGtal::Color color, double lineWidth, int depth = -1) inline
Referenced by clone(), rotated(), and translated().
Member Function Documentation
Rect LibBoard::Dot::boundingBox () const virtual
Returns the bounding box of the figure.
Returns
The rectangle of the bounding box.
Implements LibBoard::Shape.
Definition at line 380 of file Shapes.cpp.
References _x, and _y.
 {
     return Rect( _x, _y, 0.0, 0.0 );
 }
Point LibBoard::Dot::center () const virtual
Returns the gravity center of the shape.
Returns
The center of the shape.
Implements LibBoard::Shape.
Definition at line 219 of file Shapes.cpp.
References _x, and _y.
                   {
     return Point( _x, _y );
 }
Dot * LibBoard::Dot::clone () const virtual
Return a copy of the shape.
Returns
copye of the shape.
Implements LibBoard::Shape.
Definition at line 386 of file Shapes.cpp.
References Dot().
                  {
     return new Dot(*this);
 }
void LibBoard::Dot::flushCairo (cairo_t * cr, const TransformCairo & transform) const virtual
Writes the cairo code of the shape in a cairo drawing context according to a transform.
Parameters
cr The cairo drawing context.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 349 of file Shapes.cpp.
References LibBoard::Shape::_lineCap, LibBoard::Shape::_lineJoin, LibBoard::Shape::_lineStyle, LibBoard::Shape::_lineWidth, LibBoard::Shape::_penColor, _x, _y, DGtal::Color::blue(), DGtal::Color::green(), LibBoard::Transform::mapX(), LibBoard::TransformCairo::mapY(), DGtal::Color::red(), and LibBoard::Shape::setCairoDashStyle().
 {
     cairo_save (cr);
       cairo_set_source_rgba (cr, _penColor.red()/255.0, _penColor.green()/255.0, _penColor.blue()/255.0, 1.);
       cairo_move_to (cr, transform.mapX( _x ), transform.mapY( _y ));
       cairo_line_to (cr, transform.mapX( _x ), transform.mapY( _y ));
       cairo_set_line_width (cr, _lineWidth);
       cairo_set_line_cap (cr, cairoLineCap[_lineCap]);
       cairo_set_line_join (cr, cairoLineJoin[_lineJoin]);
       setCairoDashStyle (cr, _lineStyle);
       cairo_stroke (cr);
     cairo_restore (cr);
 }
void LibBoard::Dot::flushFIG (std::ostream & stream, const TransformFIG & transform, std::map< DGtal::Color, int > & colormap) const virtual
Writes the FIG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
colormap A colormap.
Implements LibBoard::Shape.
Definition at line 309 of file Shapes.cpp.
References LibBoard::Shape::_depth, LibBoard::Shape::_lineCap, LibBoard::Shape::_lineJoin, LibBoard::Shape::_lineWidth, LibBoard::Shape::_penColor, _x, _y, LibBoard::TransformFIG::mapDepth(), LibBoard::TransformFIG::mapWidth(), LibBoard::Transform::mapX(), LibBoard::TransformFIG::mapY(), and DGtal::Color::valid().
 {
     stream << "2 1 0 ";
     // Thickness
     stream << ( _penColor.valid()?transform.mapWidth( _lineWidth ):0 ) << " ";
     // Pen color
     stream << colormap[ _penColor ] << " ";
     // Fill color
     stream << "0 ";
     // Depth
     stream << transform.mapDepth( _depth ) << " ";
     // Pen style
     stream <<  "-1 ";
     // Area fill, style val, join style, cap style, radius, f_arrow, b_arrow
     stream << "-1 0.000 " << _lineJoin << " " << _lineCap << " -1 0 0 ";
     // Number of points
     stream << "2\n";
     stream << "         ";
     stream << static_cast<int>( transform.mapX( _x ) ) << " "
     << static_cast<int>( transform.mapY( _y ) ) << " "
     << static_cast<int>( transform.mapX( _x ) ) << " "
     << static_cast<int>( transform.mapY( _y ) ) << std::endl;
 }
void LibBoard::Dot::flushPostscript (std::ostream & stream, const TransformEPS & transform) const virtual
Writes the EPS code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 294 of file Shapes.cpp.
References LibBoard::Shape::_penColor, _x, _y, LibBoard::Transform::mapX(), LibBoard::TransformEPS::mapY(), DGtal::Color::postscript(), and LibBoard::Shape::postscriptProperties().
 {
     stream << "\n% Dot\n";
     stream << postscriptProperties() << " "
     << "n "
     << transform.mapX( _x ) << " "
     << transform.mapY( _y ) << " "
     << "m "
     << transform.mapX( _x ) << " "
     << transform.mapY( _y ) << " "
     << "l " << _penColor.postscript() << " srgb stroke" << std::endl;
 }
void LibBoard::Dot::flushSVG (std::ostream & stream, const TransformSVG & transform) const virtual
Writes the SVG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 336 of file Shapes.cpp.
References _x, _y, LibBoard::Transform::mapX(), LibBoard::TransformSVG::mapY(), and LibBoard::Shape::svgProperties().
 {
     stream << "<line x1=\"" << transform.mapX( _x ) << "\""
     << " y1=\"" << transform.mapY( _y ) << "\""
     << " x2=\"" << transform.mapX( _x ) << "\""
     << " y2=\"" << transform.mapY( _y ) << "\""
     << svgProperties( transform )
     << " />" << std::endl;
 }
void LibBoard::Dot::flushTikZ (std::ostream & stream, const TransformTikZ & transform) const virtual
Writes the TikZ code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 371 of file Shapes.cpp.
 {
   // FIXME: unimplemented
   stream << "% FIXME: Dot::flushTikZ unimplemented" << std::endl;
 }
const std::string & LibBoard::Dot::name () const virtual
Returns the generic name of the shape (e.g., Circle, Rectangle, etc.)
Returns
object name
Reimplemented from LibBoard::Shape.
Definition at line 213 of file Shapes.cpp.
References _name.
 {
     return _name;
 }
Dot & LibBoard::Dot::rotate (double angle, const Point & center) virtual
Rotates the dot around a given center of rotation.
Parameters
angle The rotation angle.
center The center of rotation.
Returns
A reference to the Dot itself.
Implements LibBoard::Shape.
Definition at line 224 of file Shapes.cpp.
References _x, _y, LibBoard::Point::get(), and LibBoard::Point::rotate().
 {
     Point( _x, _y ).rotate( angle, rotCenter ).get( _x, _y );
     return *this;
 }
Dot & LibBoard::Dot::rotate (double angle) virtual
Rotates the dot around its center (actually does nothing!).
Parameters
angle The rotation angle.
Returns
A reference to the Dot itself.
Implements LibBoard::Shape.
Definition at line 237 of file Shapes.cpp.
 {
     return *this;
 }
Dot LibBoard::Dot::rotated (double angle, const Point & center) const
Returns a rotated copy of the dot around a given rotation center.
Parameters
angle Th rotation angle.
center The center of rotation.
Returns
A rotated copy of the Dot.
Definition at line 231 of file Shapes.cpp.
References Dot().
 {
     return Dot(*this).rotate( angle, rotCenter );
 }
Dot LibBoard::Dot::rotated (double angle) const
Returns a copy of the dot rotated around its center (i.e. left unchanged!)
Parameters
angle The rotation angle.
Returns
A copy of the dot.
Definition at line 243 of file Shapes.cpp.
 {
     return *this;
 }
Shape & LibBoard::Dot::scale (double sx, double sy) virtual
Scale the shape along the x an y axis.
Parameters
sx The scale factor along the x axis.
sy The scale factor along the y axis.
Returns
The shape itself.
Implements LibBoard::Shape.
Definition at line 263 of file Shapes.cpp.
 {
     return *this;
 }
Shape & LibBoard::Dot::scale (double s) virtual
Scale the shape along both axis.
Parameters
s The scale factor along both axis.
Returns
The shape itself.
Implements LibBoard::Shape.
Definition at line 269 of file Shapes.cpp.
 {
     return *this;
 }
void LibBoard::Dot::scaleAll (double s) virtual
Scales all the values (positions, dimensions, etc.) associated with the shape.
Parameters
s The scaling factor.
Implements LibBoard::Shape.
Definition at line 287 of file Shapes.cpp.
References _x, and _y.
 {
     _x *= s;
     _y *= s;
 }
Dot LibBoard::Dot::scaled (double sx, double sy) const
Returns a scaled copy of the dot, i.e. the dot itself. (Dots are not actually scaled since their diameters is given by the line width.)
Parameters
sx The scale factor around the x axis.
sy The scale factor around the y axis.
Returns
A scaled copy of the Dot, i.e. the Dot itself.
Definition at line 275 of file Shapes.cpp.
 {
     return *this;
 }
Dot LibBoard::Dot::scaled (double s) const
Definition at line 281 of file Shapes.cpp.
 {
     return *this;
 }
Dot & LibBoard::Dot::translate (double dx, double dy) virtual
Parameters
dx dx
dy dy
Returns
a Dot
Implements LibBoard::Shape.
Definition at line 249 of file Shapes.cpp.
References _x, and _y.
 {
     _x += dx;
     _y += dy;
     return *this;
 }
Dot LibBoard::Dot::translated (double dx, double dy) const
Returns a translated copy of the dot.
Parameters
dx Shift of the first coordinate.
dy Shift of the second coordinate.
Returns
A copy of the Dot, translated.
Definition at line 257 of file Shapes.cpp.
References Dot().
 {
     return Dot(*this).translate( dx, dy );
 }
Field Documentation
const std::string LibBoard::Dot::_name static private
The generic name of the shape.
Definition at line 521 of file Board/Shapes.h.
Referenced by name().
double LibBoard::Dot::_x protected
First coordinate of the dot.
Definition at line 524 of file Board/Shapes.h.
Referenced by boundingBox(), center(), flushCairo(), flushFIG(), flushPostscript(), flushSVG(), rotate(), scaleAll(), and translate().
double LibBoard::Dot::_y protected
Second coordinate of the dot.
Definition at line 525 of file Board/Shapes.h.
Referenced by boundingBox(), center(), flushCairo(), flushFIG(), flushPostscript(), flushSVG(), rotate(), scaleAll(), and translate().
The documentation for this struct was generated from the following files:
Board/Shapes.h
Shapes.cpp