DGtal: LibBoard::Line Struct Reference
LibBoard::Line Struct Reference
#include <Board/Shapes.h>
Public Member Functions
Line (double x1, double y1, double x2, double y2, DGtal::Color color, double lineWidth, const LineStyle style=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
const std::string & name () const
Point center () const
Line & rotate (double angle, const Point &center)
Line rotated (double angle, const Point &center) const
Line & rotate (double angle)
Line rotated (double angle) const
Line & translate (double dx, double dy)
Line translated (double dx, double dy) const
Shape & scale (double sx, double sy)
Shape & scale (double s)
Line scaled (double sx, double sy) const
Line scaled (double s) const
void scaleAll (double s)
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
Rect boundingBox () const
Line * clone () const
Public Member Functions inherited from LibBoard::Shape
Shape (DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, LineStyle style, const LineCap cap, const LineJoin join, int depth)
virtual ~Shape ()
bool filled () const
Shape & rotateDeg (double angle, const Point &center)
Shape & rotateDeg (double angle)
Rect bbox ()
Shape & operator-- ()
Shape & operator++ ()
int depth () const
virtual void depth (int)
virtual void shiftDepth (int shift)
const DGtal::Color & penColor () const
const DGtal::Color & fillColor () const
Protected Attributes
double _x1
double _y1
double _x2
double _y2
Protected Attributes inherited from LibBoard::Shape
int _depth
DGtal::Color _penColor
DGtal::Color _fillColor
double _lineWidth
LineStyle _lineStyle
LineCap _lineCap
LineJoin _lineJoin
Static Private Attributes
static const std::string _name
Additional Inherited Members
Public Types inherited from LibBoard::Shape
enum LineCap { ButtCap = 0, RoundCap, SquareCap }
enum LineJoin { MiterJoin = 0, RoundJoin, BevelJoin }
enum LineStyle {
SolidStyle = 0, DashStyle, DotStyle, DashDotStyle,
DashDotDotStyle, DashDotDotDotStyle
}
Protected Member Functions inherited from LibBoard::Shape
std::string svgProperties (const TransformSVG &transform) const
std::string postscriptProperties () const
void setCairoDashStyle (cairo_t *cr, LineStyle type) const
std::string tikzProperties (const TransformTikZ &transform) const
Detailed Description
A line between two points.
The line structure.
Definition at line 534 of file Board/Shapes.h.
Constructor & Destructor Documentation
LibBoard::Line::Line (double x1, double y1, double x2, double y2, DGtal::Color color, double lineWidth, const LineStyle style = SolidStyle, const LineCap cap = ButtCap, const LineJoin join = MiterJoin, int depth = -1) inline
Constructs a line.
Parameters
x1 First coordinate of the start point.
y1 Second coordinate of the start point.
x2 First coordinate of the end point.
y2 Second coordinate of the end point.
color The color of the line.
lineWidth The line thickness.
style The line style.
cap The line cap.
join The line join.
depth The depth of the line.
Referenced by clone().
Member Function Documentation
Rect LibBoard::Line::boundingBox () const virtual
Returns the bounding box of the figure.
Returns
The rectangle of the bounding box.
Implements LibBoard::Shape.
Definition at line 605 of file Shapes.cpp.
References _x1, _x2, _y1, _y2, LibBoard::Rect::height, LibBoard::Rect::left, LibBoard::Rect::top, and LibBoard::Rect::width.
 {
     Rect rect;
     if ( _x1 > _x2 ) {
         rect.width = _x1 - _x2;
         rect.left = _x2;
     } else {
         rect.width = _x2 - _x1;
         rect.left = _x1;
     }
     if ( _y1 > _y2 ) {
         rect.top = _y1;
         rect.height = _y1 - _y2;
     } else {
         rect.top = _y2;
         rect.height = _y2 - _y1;
     }
     return rect;
 }
Point LibBoard::Line::center () const virtual
Returns the gravity center of the shape.
Returns
The center of the shape.
Implements LibBoard::Shape.
Definition at line 403 of file Shapes.cpp.
References _x1, _x2, _y1, and _y2.
Referenced by rotate(), rotated(), LibBoard::Arrow::rotated(), scale(), scaled(), and LibBoard::Arrow::scaled().
                    {
     return 0.5 * Point( _x1 + _x2, _y1 + _y2 );
 }
Line * LibBoard::Line::clone () const virtual
Return a copy of the shape.
Returns
copye of the shape.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Arrow.
Definition at line 510 of file Shapes.cpp.
References Line().
                   {
     return new Line(*this);
 }
void LibBoard::Line::flushCairo (cairo_t * cr, const TransformCairo & transform) const virtual
Writes the cairo code of the shape in a cairo drawing context according to a transform.
Parameters
cr The cairo drawing context.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Arrow.
Definition at line 572 of file Shapes.cpp.
References LibBoard::Shape::_lineCap, LibBoard::Shape::_lineJoin, LibBoard::Shape::_lineStyle, LibBoard::Shape::_lineWidth, LibBoard::Shape::_penColor, _x1, _x2, _y1, _y2, DGtal::Color::blue(), DGtal::Color::green(), LibBoard::Transform::mapX(), LibBoard::TransformCairo::mapY(), DGtal::Color::red(), and LibBoard::Shape::setCairoDashStyle().
 {
     cairo_save (cr);
       cairo_set_source_rgba (cr, _penColor.red()/255.0, _penColor.green()/255.0, _penColor.blue()/255.0, 1.);
       cairo_move_to (cr, transform.mapX( _x1 ), transform.mapY( _y1 ));
       cairo_line_to (cr, transform.mapX( _x2 ), transform.mapY( _y2 ));
       cairo_set_line_width (cr, _lineWidth);
       cairo_set_line_cap (cr, cairoLineCap[_lineCap]);
       cairo_set_line_join (cr, cairoLineJoin[_lineJoin]);
       setCairoDashStyle (cr, _lineStyle);
       cairo_stroke (cr);
     cairo_restore (cr);
 }
void LibBoard::Line::flushFIG (std::ostream & stream, const TransformFIG & transform, std::map< DGtal::Color, int > & colormap) const virtual
Writes the FIG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
colormap A colormap.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Arrow.
Definition at line 530 of file Shapes.cpp.
References LibBoard::Shape::_depth, LibBoard::Shape::_lineCap, LibBoard::Shape::_lineJoin, LibBoard::Shape::_lineStyle, LibBoard::Shape::_lineWidth, LibBoard::Shape::_penColor, _x1, _x2, _y1, _y2, LibBoard::TransformFIG::mapDepth(), LibBoard::TransformFIG::mapWidth(), LibBoard::Transform::mapX(), LibBoard::TransformFIG::mapY(), and DGtal::Color::valid().
 {
     stream << "2 1 ";
     // Line style
     stream << _lineStyle << " ";
     // Thickness
     stream << ( _penColor.valid()?transform.mapWidth( _lineWidth ):0 ) << " ";
     // Pen color
     stream << colormap[ _penColor ] << " ";
     // Fill color
     stream << "0 ";
     // Depth
     stream << transform.mapDepth( _depth ) << " ";
     // Pen style
     stream <<  "-1 ";
     // Area fill, style val, join style, cap style, radius, f_arrow, b_arrow
     stream << "-1 " << (_lineStyle?"4.000 ":"0.000 ") << _lineJoin << " " << _lineCap << " -1 0 0 ";
     // Number of points
     stream << "2\n";
     stream << "         ";
     stream << static_cast<int>( transform.mapX( _x1 ) ) << " "
     << static_cast<int>( transform.mapY( _y1 ) ) << " "
     << static_cast<int>( transform.mapX( _x2 ) ) << " "
     << static_cast<int>( transform.mapY( _y2 ) ) << std::endl;
 }
void LibBoard::Line::flushPostscript (std::ostream & stream, const TransformEPS & transform) const virtual
Writes the EPS code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Arrow.
Definition at line 515 of file Shapes.cpp.
References LibBoard::Shape::_penColor, _x1, _x2, _y1, _y2, LibBoard::Transform::mapX(), LibBoard::TransformEPS::mapY(), DGtal::Color::postscript(), and LibBoard::Shape::postscriptProperties().
 {
     stream << "\n% Line\n";
     stream << postscriptProperties() << " "
     << "n "
     << transform.mapX( _x1 ) << " "
     << transform.mapY( _y1 ) << " "
     << "m "
     << transform.mapX( _x2 ) << " "
     << transform.mapY( _y2 ) << " "
     << "l " << _penColor.postscript() << " srgb stroke" << std::endl;
 }
void LibBoard::Line::flushSVG (std::ostream & stream, const TransformSVG & transform) const virtual
Writes the SVG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Arrow.
Definition at line 559 of file Shapes.cpp.
References _x1, _x2, _y1, _y2, LibBoard::Transform::mapX(), LibBoard::TransformSVG::mapY(), and LibBoard::Shape::svgProperties().
 {
     stream << "<line x1=\"" << transform.mapX( _x1 ) << "\""
     << " y1=\"" << transform.mapY( _y1 ) << "\""
     << " x2=\"" << transform.mapX( _x2 ) << "\""
     << " y2=\"" << transform.mapY( _y2 ) << "\""
     << svgProperties( transform )
     << " />" << std::endl;
 }
void LibBoard::Line::flushTikZ (std::ostream & stream, const TransformTikZ & transform) const virtual
Writes the TikZ code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Arrow.
Definition at line 594 of file Shapes.cpp.
References _x1, _x2, _y1, _y2, LibBoard::Transform::mapX(), LibBoard::TransformSVG::mapY(), and LibBoard::Shape::tikzProperties().
 {
     stream << "\\path[" << tikzProperties(transform) << "] ("
     << transform.mapX( _x1 ) << ',' << transform.mapY( _y1 )
     << ") -- ("
     << transform.mapX( _x2 ) << ',' << transform.mapY( _y2 )
     << ");" << std::endl;
 }
const std::string & LibBoard::Line::name () const virtual
Returns the generic name of the shape (e.g., Circle, Rectangle, etc.)
Returns
object name
Reimplemented from LibBoard::Shape.
Reimplemented in LibBoard::Arrow.
Definition at line 397 of file Shapes.cpp.
References _name.
 {
     return _name;
 }
Line & LibBoard::Line::rotate (double angle, const Point & center) virtual
Rotate the shape around a given center of rotation.
Parameters
angle The rotation angle in radian.
center The center of rotation.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Definition at line 408 of file Shapes.cpp.
References _x1, _x2, _y1, _y2, LibBoard::Point::get(), and LibBoard::Point::rotate().
Referenced by rotate().
 {
     Point( _x1, _y1 ).rotate( angle, rotCenter ).get( _x1, _y1 );
     Point( _x2, _y2 ).rotate( angle, rotCenter ).get( _x2, _y2 );
     return *this;
 }
Line & LibBoard::Line::rotate (double angle) virtual
Rotate the shape around its center.
Parameters
angle The rotation angle in radian.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Definition at line 416 of file Shapes.cpp.
References center(), and rotate().
 {
     return Line::rotate( angle, center() );
 }
Line LibBoard::Line::rotated (double angle, const Point & center) const
Returns a copy of the line, rotated around a given rotation center.
Parameters
angle The rotation angle.
center The center of rotation.
Returns
The rotated copy of the line.
Definition at line 422 of file Shapes.cpp.
References _x1, _x2, _y1, _y2, LibBoard::Point::get(), and LibBoard::Point::rotate().
 {
     Line res(*this);
     Point( _x1, _y1 ).rotate( angle, rotCenter ).get( res._x1, res._y1 );
     Point( _x2, _y2 ).rotate( angle, rotCenter ).get( res._x2, res._y2 );
     return res;
 }
Line LibBoard::Line::rotated (double angle) const
Returns a copy of the line, rotated around its center.
Parameters
angle The angle of rotation.
Returns
A copy of the lines, rotated around its center by the given angle.
Definition at line 431 of file Shapes.cpp.
References _x1, _x2, _y1, _y2, center(), LibBoard::Point::get(), and LibBoard::Point::rotate().
 {
     Line res(*this);
     Point c = center();
     Point( _x1, _y1 ).rotate( angle, c ).get( res._x1, res._y1 );
     Point( _x2, _y2 ).rotate( angle, c ).get( res._x2, res._y2 );
     return res;
 }
Shape & LibBoard::Line::scale (double sx, double sy) virtual
Scale the shape along the x an y axis.
Parameters
sx The scale factor along the x axis.
sy The scale factor along the y axis.
Returns
The shape itself.
Implements LibBoard::Shape.
Definition at line 462 of file Shapes.cpp.
References _x1, _x2, _y1, _y2, center(), translate(), LibBoard::Point::x, and LibBoard::Point::y.
Referenced by scale().
 {
     Point c = center();
     _x1 *= sx;
     _x2 *= sx;
     _y1 *= sy;
     _y2 *= sy;
     Point delta = c - center();
     translate( delta.x, delta.y );
     return *this;
 }
Shape & LibBoard::Line::scale (double s) virtual
Scale the shape along both axis.
Parameters
s The scale factor along both axis.
Returns
The shape itself.
Implements LibBoard::Shape.
Definition at line 475 of file Shapes.cpp.
References scale().
 {
     scale( s, s );
     return (*this);
 }
void LibBoard::Line::scaleAll (double s) virtual
Scales all the values (positions, dimensions, etc.) associated with the shape.
Parameters
s The scaling factor.
Implements LibBoard::Shape.
Definition at line 501 of file Shapes.cpp.
References _x1, _x2, _y1, and _y2.
 {
     _x1 *= s;
     _y1 *= s;
     _x2 *= s;
     _y2 *= s;
 }
Line LibBoard::Line::scaled (double sx, double sy) const
Returns a scaled copy of the line.
Parameters
sx Scale factor along the x axis.
sy Scale factor along the y axis.
Returns
A scaled copy of the line.
Definition at line 482 of file Shapes.cpp.
References _x1, _x2, _y1, _y2, center(), translate(), LibBoard::Point::x, and LibBoard::Point::y.
Referenced by scaled().
 {
     Line res(*this);
     Point c = center();
     res._x1 *= sx;
     res._x2 *= sx;
     res._y1 *= sy;
     res._y2 *= sy;
     Point delta = c - res.center();
     return res.translate( delta.x, delta.y );
 }
Line LibBoard::Line::scaled (double s) const
Definition at line 495 of file Shapes.cpp.
References scaled().
 {
     return Line::scaled( s , s );
 }
Line & LibBoard::Line::translate (double dx, double dy) virtual
Translate the shape by a given offset.
Parameters
dx The x offset.
dy The y offset.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Definition at line 441 of file Shapes.cpp.
References _x1, _x2, _y1, and _y2.
Referenced by scale(), scaled(), and LibBoard::Arrow::scaled().
 {
     _x1 += dx;
     _x2 += dx;
     _y1 += dy;
     _y2 += dy;
     return *this;
 }
Line LibBoard::Line::translated (double dx, double dy) const
Returns a translated copy of the line.
Parameters
dx The shift along the x axis.
dy The shift along the y axis.
Returns
A translated copy of the line.
Definition at line 451 of file Shapes.cpp.
References _x1, _x2, _y1, and _y2.
 {
     Line res(*this);
     res._x1 += dx;
     res._x2 += dx;
     res._y1 += dy;
     res._y2 += dy;
     return *this;
 }
Field Documentation
const std::string LibBoard::Line::_name static private
The generic name of the shape.
Definition at line 649 of file Board/Shapes.h.
Referenced by name().
double LibBoard::Line::_x1 protected
First coordinate of the start point.
Definition at line 652 of file Board/Shapes.h.
Referenced by boundingBox(), center(), flushCairo(), LibBoard::Arrow::flushCairo(), flushFIG(), LibBoard::Arrow::flushFIG(), flushPostscript(), LibBoard::Arrow::flushPostscript(), flushSVG(), LibBoard::Arrow::flushSVG(), flushTikZ(), LibBoard::Arrow::flushTikZ(), rotate(), rotated(), LibBoard::Arrow::rotated(), scale(), scaleAll(), scaled(), LibBoard::Arrow::scaled(), translate(), translated(), and LibBoard::Arrow::translated().
double LibBoard::Line::_x2 protected
First coordinate of the end point.
Definition at line 654 of file Board/Shapes.h.
Referenced by boundingBox(), center(), flushCairo(), LibBoard::Arrow::flushCairo(), flushFIG(), LibBoard::Arrow::flushFIG(), flushPostscript(), LibBoard::Arrow::flushPostscript(), flushSVG(), LibBoard::Arrow::flushSVG(), flushTikZ(), LibBoard::Arrow::flushTikZ(), rotate(), rotated(), LibBoard::Arrow::rotated(), scale(), scaleAll(), scaled(), LibBoard::Arrow::scaled(), translate(), translated(), and LibBoard::Arrow::translated().
double LibBoard::Line::_y1 protected
Second coordinate of the start point.
Definition at line 653 of file Board/Shapes.h.
Referenced by boundingBox(), center(), flushCairo(), LibBoard::Arrow::flushCairo(), flushFIG(), LibBoard::Arrow::flushFIG(), flushPostscript(), LibBoard::Arrow::flushPostscript(), flushSVG(), LibBoard::Arrow::flushSVG(), flushTikZ(), LibBoard::Arrow::flushTikZ(), rotate(), rotated(), LibBoard::Arrow::rotated(), scale(), scaleAll(), scaled(), LibBoard::Arrow::scaled(), translate(), translated(), and LibBoard::Arrow::translated().
double LibBoard::Line::_y2 protected
Second coordinate of the end point.
Definition at line 655 of file Board/Shapes.h.
Referenced by boundingBox(), center(), flushCairo(), LibBoard::Arrow::flushCairo(), flushFIG(), LibBoard::Arrow::flushFIG(), flushPostscript(), LibBoard::Arrow::flushPostscript(), flushSVG(), LibBoard::Arrow::flushSVG(), flushTikZ(), LibBoard::Arrow::flushTikZ(), rotate(), rotated(), LibBoard::Arrow::rotated(), scale(), scaleAll(), scaled(), LibBoard::Arrow::scaled(), translate(), translated(), and LibBoard::Arrow::translated().
The documentation for this struct was generated from the following files:
Board/Shapes.h
Shapes.cpp