DGtal: LibBoard::TransformCairo Struct Reference
LibBoard::TransformCairo Struct Reference
#include <Board/Transforms.h>
Public Member Functions
double rounded (double x) const
double mapY (double y) const
double mapWidth (double width) const
void setBoundingBox (const Rect &rect, const double pageWidth, const double pageHeight, const double margin)
Public Member Functions inherited from LibBoard::Transform
Transform ()
virtual ~Transform ()
virtual double mapX (double x) const
virtual void apply (double &x, double &y) const
virtual double scale (double x) const
Additional Inherited Members
Static Public Member Functions inherited from LibBoard::Transform
static double round (const double &x)
Protected Attributes inherited from LibBoard::Transform
double _scale
double _deltaX
double _deltaY
double _height
Detailed Description
Structure representing a scaling and translation suitable for an Cairo output.
The TransformCairo structure.
Definition at line 112 of file Transforms.h.
Member Function Documentation
double LibBoard::TransformCairo::mapWidth (double width) const
Definition at line 240 of file Transforms.cpp.
References LibBoard::Transform::round().
 {
   // return Transform::round( 1000 * width / ppmm ) / 1000.0;
   return Transform::round( 1000 * width  / ppmm  ) / 1000.0;
 }
double LibBoard::TransformCairo::mapY (double y) const virtual
Implements LibBoard::Transform.
Definition at line 234 of file Transforms.cpp.
References LibBoard::Transform::_deltaY, LibBoard::Transform::_height, LibBoard::Transform::_scale, and rounded().
Referenced by LibBoard::Dot::flushCairo(), LibBoard::Line::flushCairo(), LibBoard::Arrow::flushCairo(), LibBoard::Rectangle::flushCairo(), LibBoard::Image::flushCairo(), LibBoard::QuadraticBezierCurve::flushCairo(), LibBoard::Ellipse::flushCairo(), LibBoard::Circle::flushCairo(), LibBoard::Arc::flushCairo(), and LibBoard::Path::flushCairoPoints().
 {
   return rounded( _height - ( y * _scale + _deltaY ) );
 }
double LibBoard::TransformCairo::rounded (double x) const virtual
Reimplemented from LibBoard::Transform.
Definition at line 228 of file Transforms.cpp.
References LibBoard::Transform::round().
Referenced by mapY().
 {
   return Transform::round( 100*x ) / 100.0f;
 }
void LibBoard::TransformCairo::setBoundingBox (const Rect & rect, const double pageWidth, const double pageHeight, const double margin) virtual
Implements LibBoard::Transform.
Definition at line 247 of file Transforms.cpp.
References LibBoard::Transform::_deltaX, LibBoard::Transform::_deltaY, LibBoard::Transform::_height, LibBoard::Transform::_scale, LibBoard::Rect::height, LibBoard::Rect::left, LibBoard::Rect::top, and LibBoard::Rect::width.
Referenced by LibBoard::Board::saveCairo().
 {
   if ( pageWidth <= 0 || pageHeight <= 0 ) {
     _scale = 1.0f;
     // _deltaX = 0.5 * 210 * ppmm - ( rect.left + 0.5 * rect.width );
     _deltaX = - rect.left;
     // _deltaY = 0.5 * 297 * ppmm - ( rect.top - 0.5 * rect.height );
     _deltaY = - ( rect.top - rect.height );
     // _height = 297 * fig_ppmm;
     _height = rect.height;
   } else {
     const double w = pageWidth - 2 * margin;
     const double h = pageHeight - 2 * margin;
     if ( rect.height / rect.width > ( h / w ) ) {
       _scale = h * ppmm / rect.height;
     } else {
       _scale = w * ppmm / rect.width;
     }
     _deltaX = 0.5 * pageWidth * ppmm - _scale * ( rect.left + 0.5 * rect.width );
     _deltaY = 0.5 * pageHeight * ppmm - _scale * ( rect.top - 0.5 * rect.height );
     _height = pageHeight * ppmm;
   }
 }
The documentation for this struct was generated from the following files:
Transforms.h
Transforms.cpp