DGtal: LibBoard::Arrow Struct Reference
LibBoard::Arrow Struct Reference
#include <Board/Shapes.h>
Public Member Functions
Arrow (double x1, double y1, double x2, double y2, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle style=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
const std::string & name () const
Arrow rotated (double angle, const Point &center) const
Arrow rotated (double angle) const
Arrow translated (double dx, double dy) const
Arrow scaled (double sx, double sy) const
Arrow scaled (double s) const
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
Arrow * clone () const
Public Member Functions inherited from LibBoard::Line
Line (double x1, double y1, double x2, double y2, DGtal::Color color, double lineWidth, const LineStyle style=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
Point center () const
Line & rotate (double angle, const Point &center)
Line rotated (double angle, const Point &center) const
Line & rotate (double angle)
Line rotated (double angle) const
Line & translate (double dx, double dy)
Line translated (double dx, double dy) const
Shape & scale (double sx, double sy)
Shape & scale (double s)
Line scaled (double sx, double sy) const
Line scaled (double s) const
void scaleAll (double s)
Rect boundingBox () const
Public Member Functions inherited from LibBoard::Shape
Shape (DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, LineStyle style, const LineCap cap, const LineJoin join, int depth)
virtual ~Shape ()
bool filled () const
Shape & rotateDeg (double angle, const Point &center)
Shape & rotateDeg (double angle)
Rect bbox ()
Shape & operator-- ()
Shape & operator++ ()
int depth () const
virtual void depth (int)
virtual void shiftDepth (int shift)
const DGtal::Color & penColor () const
const DGtal::Color & fillColor () const
Static Private Attributes
static const std::string _name
Additional Inherited Members
Public Types inherited from LibBoard::Shape
enum LineCap { ButtCap = 0, RoundCap, SquareCap }
enum LineJoin { MiterJoin = 0, RoundJoin, BevelJoin }
enum LineStyle {
SolidStyle = 0, DashStyle, DotStyle, DashDotStyle,
DashDotDotStyle, DashDotDotDotStyle
}
Protected Member Functions inherited from LibBoard::Shape
std::string svgProperties (const TransformSVG &transform) const
std::string postscriptProperties () const
void setCairoDashStyle (cairo_t *cr, LineStyle type) const
std::string tikzProperties (const TransformTikZ &transform) const
Protected Attributes inherited from LibBoard::Line
double _x1
double _y1
double _x2
double _y2
Protected Attributes inherited from LibBoard::Shape
int _depth
DGtal::Color _penColor
DGtal::Color _fillColor
double _lineWidth
LineStyle _lineStyle
LineCap _lineCap
LineJoin _lineJoin
Detailed Description
A line between two points with an arrow at one extremity.
The arrow structure.
Definition at line 665 of file Board/Shapes.h.
Constructor & Destructor Documentation
LibBoard::Arrow::Arrow (double x1, double y1, double x2, double y2, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle style = SolidStyle, const LineCap cap = ButtCap, const LineJoin join = MiterJoin, int depth = -1) inline
Constructs an arrow.
Parameters
x1 First coordinate of the start point.
y1 Second coordinate of the start point.
x2 First coordinate of the end point.
y2 Second coordinate of the end point.
penColor The color of the line.
fillColor The fill color of the sharp end.
lineWidth The line thickness.
style Line style.
cap Line cap.
join Line join.
depth The depth of the line.
Referenced by clone().
Member Function Documentation
Arrow * LibBoard::Arrow::clone () const virtual
Return a copy of the shape.
Returns
copye of the shape.
Reimplemented from LibBoard::Line.
Definition at line 789 of file Shapes.cpp.
References Arrow().
                    {
     return new Arrow(*this);
 }
void LibBoard::Arrow::flushCairo (cairo_t * cr, const TransformCairo & transform) const virtual
Writes the cairo code of the shape in a cairo drawing context according to a transform.
Parameters
cr The cairo drawing context.
transform A 2D transform to be applied.
Reimplemented from LibBoard::Line.
Definition at line 934 of file Shapes.cpp.
References LibBoard::Shape::_fillColor, LibBoard::Shape::_lineCap, LibBoard::Shape::_lineJoin, LibBoard::Shape::_lineStyle, LibBoard::Shape::_lineWidth, LibBoard::Shape::_penColor, LibBoard::Line::_x1, LibBoard::Line::_x2, LibBoard::Line::_y1, LibBoard::Line::_y2, DGtal::Color::blue(), LibBoard::Shape::ButtCap, LibBoard::Shape::filled(), DGtal::Color::green(), LibBoard::Transform::mapX(), LibBoard::TransformCairo::mapY(), LibBoard::Shape::MiterJoin, DGtal::Color::None, DGtal::Color::red(), LibBoard::Transform::scale(), LibBoard::Shape::setCairoDashStyle(), and LibBoard::Shape::SolidStyle.
 {
     double dx = _x1 - _x2;
     double dy = _y1 - _y2;
     double norm = sqrt( dx*dx + dy*dy );
     dx /= norm;
     dy /= norm;
     dx *= 10 * _lineWidth;
     dy *= 10 * _lineWidth;
     //   double back_x = 0.8 * dx + _x2;
     //   double back_y = 0.8 * dy + _y2;
     double ndx1 = dx*cos(0.3)-dy*sin(0.3);
     double ndy1 = dx*sin(0.3)+dy*cos(0.3);
     double ndx2 = dx*cos(-0.3)-dy*sin(-0.3);
     double ndy2 = dx*sin(-0.3)+dy*cos(-0.3);
     cairo_save (cr);
       // The line
       cairo_set_source_rgba (cr, _penColor.red()/255.0, _penColor.green()/255.0, _penColor.blue()/255.0, 1.);
       cairo_move_to (cr, transform.mapX( _x1 ), transform.mapY( _y1 ));
       cairo_line_to (cr, transform.mapX( _x2 + ( dx * cos(0.3) ) ), transform.mapY( _y2 + ( dy * cos(0.3) ) ));
       cairo_set_line_width (cr, _lineWidth);
       cairo_set_line_cap (cr, cairoLineCap[_lineCap]);
       cairo_set_line_join (cr, cairoLineJoin[_lineJoin]);
       setCairoDashStyle (cr, _lineStyle);
       cairo_stroke (cr);
       // The arrow
       cairo_set_source_rgba (cr, _fillColor.red()/255.0, _fillColor.green()/255.0, _fillColor.blue()/255.0, 1.);
       cairo_move_to (cr, transform.mapX( _x2 ) + transform.scale( ndx1 ), transform.mapY( _y2 ) - transform.scale( ndy1 ));
       cairo_line_to (cr, transform.mapX( _x2 ), transform.mapY( _y2 ));
       cairo_line_to (cr, transform.mapX( _x2 ) + transform.scale( ndx2 ), transform.mapY( _y2 ) - transform.scale( ndy2 ));
       cairo_close_path (cr);
       if ( filled() )
       {
   if ( _penColor != DGtal::Color::None )
     cairo_fill_preserve (cr);
   else
     cairo_fill (cr);
       }
       //
       if ( _penColor != DGtal::Color::None )
       {
   cairo_set_source_rgba (cr, _penColor.red()/255.0, _penColor.green()/255.0, _penColor.blue()/255.0, 1.);
   cairo_set_line_width (cr, _lineWidth);
   cairo_set_line_cap (cr, cairoLineCap[ButtCap]);
   cairo_set_line_join (cr, cairoLineJoin[MiterJoin]);
   setCairoDashStyle (cr, SolidStyle);
   cairo_stroke (cr);
       }
     cairo_restore (cr);
 }
void LibBoard::Arrow::flushFIG (std::ostream & stream, const TransformFIG & transform, std::map< DGtal::Color, int > & colormap) const virtual
Writes the FIG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
colormap A colormap.
Reimplemented from LibBoard::Line.
Definition at line 848 of file Shapes.cpp.
References LibBoard::Shape::_depth, LibBoard::Shape::_lineCap, LibBoard::Shape::_lineJoin, LibBoard::Shape::_lineStyle, LibBoard::Shape::_lineWidth, LibBoard::Shape::_penColor, LibBoard::Line::_x1, LibBoard::Line::_x2, LibBoard::Line::_y1, LibBoard::Line::_y2, LibBoard::Shape::filled(), LibBoard::TransformFIG::mapDepth(), LibBoard::TransformFIG::mapWidth(), LibBoard::Transform::mapX(), LibBoard::TransformFIG::mapY(), and DGtal::Color::valid().
 {
     stream << "2 1 ";
     // Line style
     stream << _lineStyle << " ";
     // Thickness
     stream << ( _penColor.valid()?transform.mapWidth( _lineWidth ):0 ) << " ";
     // Pen color
     stream << colormap[ _penColor ] << " ";
     // Fill color
     stream << colormap[ _penColor ] << " ";
     // Depth
     stream << transform.mapDepth( _depth ) << " ";
     // Pen style
     stream <<  "-1 ";
     // Area fill, style val, join style, cap style, radius, f_arrow, b_arrow
     stream << "-1 " << (_lineStyle?"4.000 ":"0.000 ") << _lineJoin << " " << _lineCap << " -1 1 0 ";
     // Number of points
     stream << "2\n";
     if ( filled() )
         stream << "       1 1 1.00 60.00 120.00\n";
     else
         stream << "       1 0 1.00 60.00 120.00\n";
     stream << "         ";
     stream << static_cast<int>( transform.mapX( _x1 ) ) << " "
     << static_cast<int>( transform.mapY( _y1 ) ) << " "
     << static_cast<int>( transform.mapX( _x2 ) ) << " "
     << static_cast<int>( transform.mapY( _y2 ) ) << std::endl;
 }
void LibBoard::Arrow::flushPostscript (std::ostream & stream, const TransformEPS & transform) const virtual
Writes the EPS code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Reimplemented from LibBoard::Line.
Definition at line 794 of file Shapes.cpp.
References LibBoard::Shape::_lineWidth, LibBoard::Shape::_penColor, LibBoard::Line::_x1, LibBoard::Line::_x2, LibBoard::Line::_y1, LibBoard::Line::_y2, LibBoard::Shape::filled(), LibBoard::Transform::mapX(), LibBoard::TransformEPS::mapY(), DGtal::Color::postscript(), LibBoard::Shape::postscriptProperties(), and LibBoard::Transform::scale().
 {
     double dx = _x1 - _x2;
     double dy = _y1 - _y2;
     double norm = sqrt( dx*dx + dy*dy );
     dx /= norm;
     dy /= norm;
     dx *= 10*_lineWidth;
     dy *= 10*_lineWidth;
     //   double back_x = 0.8 * dx + _x2;
     //   double back_y = 0.8 * dy + _y2;
     double ndx1 = dx*cos(0.3)-dy*sin(0.3);
     double ndy1 = dx*sin(0.3)+dy*cos(0.3);
     double ndx2 = dx*cos(-0.3)-dy*sin(-0.3);
     double ndy2 = dx*sin(-0.3)+dy*cos(-0.3);
     stream << "\n% Arrow\n";
     stream << _penColor.postscript() << " srgb "
     << postscriptProperties() << " "
     << "n "
     << transform.mapX( _x1 ) << " "
     << transform.mapY( _y1 ) << " "
     << "m "
     << transform.mapX( _x2 + ( dx * cos(0.3) ) ) << " "
     << transform.mapY( _y2 + ( dy * cos(0.3) ) ) << " "
     << "l stroke" << std::endl;
     if ( filled() ) {
         stream << "n "
         << transform.mapX( _x2 ) + transform.scale( ndx1 ) << " "
         << transform.mapY( _y2 ) + transform.scale( ndy1 ) << " "
         << "m "
         << transform.mapX( _x2 ) << " "
         << transform.mapY( _y2 ) << " l "
         << transform.mapX( _x2 ) + transform.scale( ndx2 ) << " "
         << transform.mapY( _y2 ) + transform.scale( ndy2 ) << " ";
         stream  << "l cp " << _penColor.postscript() << " srgb  fill" << std::endl;
     }
     stream << "n "
     << transform.mapX( _x2 ) + transform.scale( ndx1 ) << " "
     << transform.mapY( _y2 ) + transform.scale( ndy1 ) << " "
     << "m "
     << transform.mapX( _x2 ) << " "
     << transform.mapY( _y2 ) << " l "
     << transform.mapX( _x2 ) + transform.scale( ndx2 ) << " "
     << transform.mapY( _y2 ) + transform.scale( ndy2 ) << " l"
     << " " << _penColor.postscript() << " srgb cp [] 0 sd stroke" << std::endl;
 }
void LibBoard::Arrow::flushSVG (std::ostream & stream, const TransformSVG & transform) const virtual
Writes the SVG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Reimplemented from LibBoard::Line.
Definition at line 881 of file Shapes.cpp.
References LibBoard::Shape::_fillColor, LibBoard::Shape::_lineStyle, LibBoard::Shape::_lineWidth, LibBoard::Shape::_penColor, LibBoard::Line::_x1, LibBoard::Line::_x2, LibBoard::Line::_y1, LibBoard::Line::_y2, LibBoard::TransformSVG::mapWidth(), LibBoard::Transform::mapX(), LibBoard::TransformSVG::mapY(), LibBoard::Transform::scale(), LibBoard::Shape::SolidStyle, DGtal::Color::svg(), and DGtal::Color::svgAlpha().
 {
     double dx = _x1 - _x2;
     double dy = _y1 - _y2;
     double norm = sqrt( dx*dx + dy*dy );
     dx /= norm;
     dy /= norm;
     dx *= 10 * _lineWidth;
     dy *= 10 * _lineWidth;
     //   double back_x = 0.8 * dx + _x2;
     //   double back_y = 0.8 * dy + _y2;
     double ndx1 = dx*cos(0.3)-dy*sin(0.3);
     double ndy1 = dx*sin(0.3)+dy*cos(0.3);
     double ndx2 = dx*cos(-0.3)-dy*sin(-0.3);
     double ndy2 = dx*sin(-0.3)+dy*cos(-0.3);
     stream << "<g>" << std::endl;
     // The line
     stream << " <path "
     << "d=\"M " << transform.mapX( _x1 ) << " " << transform.mapY( _y1 )
     << " L " << transform.mapX( _x2 + ( dx * cos(0.3) ) )
     << " " << transform.mapY( _y2 + ( dy * cos(0.3) ) ) << " z\""
     << " fill=\"none\" stroke=\"" << _penColor.svg() << "\""
     << _penColor.svgAlpha( " stroke" );
     if ( _lineStyle != SolidStyle )
         stream << " style=\"" <<   xFigDashStylesSVG[ _lineStyle ] << '"';
     stream << " stroke-width=\"" << transform.mapWidth( _lineWidth ) << "mm\" />";
     // The arrow
     stream << " <polygon";
     stream << " fill=\"" << _fillColor.svg() << "\"";
     stream << " stroke=\"" << _penColor.svg() << "\""
     << " stroke-width=\"" << transform.mapWidth( /* 0.33 * */ _lineWidth ) << "mm\""
     << " style=\"stroke-linecap:butt;stroke-linejoin:miter\""
     << _fillColor.svgAlpha( " fill" )
     << _penColor.svgAlpha( " stroke" )
     << " points=\""
     << transform.mapX( _x2 ) + transform.scale( ndx1 ) << ","
     << transform.mapY( _y2 ) - transform.scale( ndy1 ) << " "
     << transform.mapX( _x2 ) << ","
     << transform.mapY( _y2 ) << " "
     << transform.mapX( _x2 ) + transform.scale( ndx2 ) << ","
     << transform.mapY( _y2 ) - transform.scale( ndy2 ) << " "
     << transform.mapX( _x2 ) + transform.scale( ndx1 ) << ","
     << transform.mapY( _y2 ) - transform.scale( ndy1 ) << "\" />" << std::endl;
     stream << "</g>" << std::endl;
 }
void LibBoard::Arrow::flushTikZ (std::ostream & stream, const TransformTikZ & transform) const virtual
Writes the TikZ code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Reimplemented from LibBoard::Line.
Definition at line 1003 of file Shapes.cpp.
References LibBoard::Line::_x1, LibBoard::Line::_x2, LibBoard::Line::_y1, LibBoard::Line::_y2, LibBoard::Transform::mapX(), LibBoard::TransformSVG::mapY(), and LibBoard::Shape::tikzProperties().
 {
     //stream << "\\path[-triangle 45," << tikzProperties(transform) << "] (" // Requires \usetikzlibrary{arrows}
     stream << "\\path[-latex," << tikzProperties(transform) << "] ("
     << transform.mapX( _x1 ) << ',' << transform.mapY( _y1 )
     << ") -- ("
     << transform.mapX( _x2 ) << ',' << transform.mapY( _y2 )
     << ");" << std::endl;
 }
const std::string & LibBoard::Arrow::name () const virtual
Returns the generic name of the shape (e.g., Circle, Rectangle, etc.)
Returns
object name
Reimplemented from LibBoard::Line.
Definition at line 734 of file Shapes.cpp.
References _name.
 {
     return _name;
 }
Arrow LibBoard::Arrow::rotated (double angle, const Point & center) const
Returns a copy of the arrow, rotated around a given rotation center.
Parameters
angle The rotation angle.
center The center of rotation.
Returns
The rotated copy of the line.
Definition at line 740 of file Shapes.cpp.
References LibBoard::Line::_x1, LibBoard::Line::_x2, LibBoard::Line::_y1, LibBoard::Line::_y2, LibBoard::Point::get(), and LibBoard::Point::rotate().
 {
     Arrow res(*this);
     Point( _x1, _y1 ).rotate( angle, rotCenter ).get( res._x1, res._y1 );
     Point( _x2, _y2 ).rotate( angle, rotCenter ).get( res._x2, res._y2 );
     return res;
 }
Arrow LibBoard::Arrow::rotated (double angle) const
Returns a copy of the arrow, rotated around its center.
Parameters
angle The angle of rotation.
Returns
A copy of the lines, rotated around its center by the given angle.
Definition at line 749 of file Shapes.cpp.
References LibBoard::Line::_x1, LibBoard::Line::_x2, LibBoard::Line::_y1, LibBoard::Line::_y2, LibBoard::Line::center(), LibBoard::Point::get(), and LibBoard::Point::rotate().
 {
     Arrow res(*this);
     Point c = center();
     Point( _x1, _y1 ).rotate( angle, c ).get( res._x1, res._y1 );
     Point( _x2, _y2 ).rotate( angle, c ).get( res._x2, res._y2 );
     return res;
 }
Arrow LibBoard::Arrow::scaled (double sx, double sy) const
Returns a scaled copy of the arrow.
Parameters
sx Scale factor along the x axis.
sy Scale factor along the y axis.
Returns
A scaled copy of the arrow.
Definition at line 770 of file Shapes.cpp.
References LibBoard::Line::_x1, LibBoard::Line::_x2, LibBoard::Line::_y1, LibBoard::Line::_y2, LibBoard::Line::center(), LibBoard::Line::translate(), LibBoard::Point::x, and LibBoard::Point::y.
Referenced by scaled().
 {
     Arrow res(*this);
     Point c = center();
     res._x1 *= sx;
     res._x2 *= sx;
     res._y1 *= sy;
     res._y2 *= sy;
     Point delta = c - res.center();
     return static_cast<Arrow &>( res.translate( delta.x, delta.y ) );
 }
Arrow LibBoard::Arrow::scaled (double s) const
Definition at line 783 of file Shapes.cpp.
References scaled().
 {
     return Arrow::scaled( s, s );
 }
Arrow LibBoard::Arrow::translated (double dx, double dy) const
Returns a translated copy of the arrow.
Parameters
dx The shift along the x axis.
dy The shift along the y axis.
Returns
A translated copy of the line.
Definition at line 759 of file Shapes.cpp.
References LibBoard::Line::_x1, LibBoard::Line::_x2, LibBoard::Line::_y1, and LibBoard::Line::_y2.
 {
     Arrow res(*this);
     res._x1 += dx;
     res._x2 += dx;
     res._y1 += dy;
     res._y2 += dy;
     return res;
 }
Field Documentation
const std::string LibBoard::Arrow::_name static private
The generic name of the shape.
Definition at line 758 of file Board/Shapes.h.
Referenced by name().
The documentation for this struct was generated from the following files:
Board/Shapes.h
Shapes.cpp