DGtal: DGtal::GenericReader< TContainer, 2, TValue > Struct Template Reference
DGtal::GenericReader< TContainer, 2, TValue > Struct Template Reference
#include <DGtal/io/readers/GenericReader.h>
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CImage< TContainer >))
Static Public Member Functions
static TContainer import (const std::string &filename, unsigned int x=0, unsigned int y=0) throw (DGtal::IOException)
template<typename TFunctor >
static TContainer importWithColorFunctor (const std::string &filename, const TFunctor &aFunctor, unsigned int x=0, unsigned int y=0) throw (DGtal::IOException)
template<typename TFunctor >
static TContainer importWithValueFunctor (const std::string &filename, const TFunctor &aFunctor, unsigned int x=0, unsigned int y=0) throw (DGtal::IOException)
Detailed Description
template<typename TContainer, typename TValue>
struct DGtal::GenericReader< TContainer, 2, TValue >
GenericReader Template partial specialisation for volume images of dimension 2
Definition at line 309 of file GenericReader.h.
Member Function Documentation
template<typename TContainer , typename TValue > DGtal::GenericReader< TContainer, 2, TValue >::BOOST_CONCEPT_ASSERT ((concepts::CImage< TContainer >))
template<typename TContainer , typename TValue > static TContainer DGtal::GenericReader< TContainer, 2, TValue >::import (const std::string & filename, unsigned int x = 0, unsigned int y = 0) throw (DGtal::IOException) static
Import a volume image file. For the special format h5 (you need to set WITH_HDF5 of cmake build), the default parameter datasetName needs to be updated according to the dimension if the image.
Parameters
filename the image filename to be imported.
x specify the x image size to be used with raw format.
y specify the y image size to be used with raw format.
template<typename TContainer , typename TValue > template<typename TFunctor > static TContainer DGtal::GenericReader< TContainer, 2, TValue >::importWithColorFunctor (const std::string & filename, const TFunctor & aFunctor, unsigned int x = 0, unsigned int y = 0) throw (DGtal::IOException) inline static
Import an image file by specifying a color encoder functor (used only for color image format ppm, (gif, jpeg, ... if the magick image lib is installed) .
Template Parameters
TFunctor The type of the functor (should verify the concept CUnaryFunctor<TFunctor, TContainer::Value, DGtal::Color >).
Parameters
filename the image filename to be imported.
aFunctor an ColorRGBEncoder. The type of the functor (should verify the concept CUnaryFunctor<TFunctor, TContainer::Value, DGtal::Color >).
x specify the x image size to be used with raw format.
y specify the y image size to be used with raw format.
Definition at line 341 of file GenericReader.h.
References DGtal::GenericReader< TContainer, Tdim, TValue >::BOOST_CONCEPT_ASSERT(), DGtal::Trace::error(), DGtal::MagickReader< TImageContainer, TFunctor >::importImage(), DGtal::PPMReader< TImageContainer, TFunctor >::importPPM(), and DGtal::trace.
       {
         BOOST_CONCEPT_ASSERT((  concepts::CUnaryFunctor<TFunctor, DGtal::Color, typename TContainer::Value> )) ;
         DGtal::IOException dgtalio;
         //Getting image extension
         const std::string extension = filename.substr( filename.find_last_of(".") + 1 );
         if ( extension == "ppm" )
           {
             return PPMReader<TContainer, TFunctor>::importPPM(filename, aFunctor);
           }
         else if ( extension == "raw" )
           {
             ASSERT( x != 0 && y != 0 );
             typename TContainer::Point const pt (x,y);
             return RawReader< TContainer, TFunctor >::template importRaw<DGtal::Color>( filename, pt, aFunctor);
           }
         else if ( extension == "gif" || extension == "jpg" || extension == "png" || extension == "jpeg" || extension == "bmp" )
           {
 #ifdef WITH_MAGICK
             MagickReader<TContainer, TFunctor> reader;
             return reader.importImage( filename, aFunctor );
 #else
             trace.error() << "Extension " << extension<< " not yet implemented in DGtal but you can add Magick option to deal with this image type." << std::endl;
             throw dgtalio;
 #endif
           }
         trace.error() << "Extension " << extension<< " in 2D, not yet implemented in DGtal GenericReader." << std::endl;
         throw dgtalio;
       }
template<typename TContainer , typename TValue > template<typename TFunctor > static TContainer DGtal::GenericReader< TContainer, 2, TValue >::importWithValueFunctor (const std::string & filename, const TFunctor & aFunctor, unsigned int x = 0, unsigned int y = 0) throw (DGtal::IOException) inline static
Import an image file by specifying a value functor used for grayscale image.
Template Parameters
TFunctor The type of the functor (should verify the concept CUnaryFunctor<TFunctor, unsigned char, TContainer::Value >).
Parameters
filename the image filename to be imported.
aFunctor to transform input unsigned char of image value into the given image type. image.
x specify the x image size to be used with raw format.
y specify the y image size to be used with raw format.
Definition at line 389 of file GenericReader.h.
References DGtal::GenericReader< TContainer, Tdim, TValue >::BOOST_CONCEPT_ASSERT(), DGtal::Trace::error(), DGtal::HDF5Reader< TImageContainer, TFunctor >::importHDF5(), DGtal::PGMReader< TImageContainer, TFunctor >::importPGM(), DGtal::RawReader< TImageContainer, TFunctor >::importRaw8(), and DGtal::trace.
       {
         BOOST_CONCEPT_ASSERT((  concepts::CUnaryFunctor<TFunctor, unsigned char, typename TContainer::Value > )) ;
         DGtal::IOException dgtalio;
         //Getting image extension
         const std::string extension = filename.substr( filename.find_last_of(".") + 1 );
         if ( extension == "raw" )
           {
             ASSERT( x!= 0 && y != 0);
             typename TContainer::Point const pt (x,y);
             return RawReader< TContainer, TFunctor >::importRaw8( filename, pt, aFunctor  );
           }
         else if ( extension == "pgm" )
           {
             return PGMReader<TContainer, TFunctor>::importPGM(filename, aFunctor);
           }
 #ifdef WITH_HDF5
         if (extension=="h5")
           return HDF5Reader<TContainer, TFunctor>::importHDF5(filename, "image8bit", aFunctor);
 #endif
         trace.error() << "Extension " << extension<< " not yet implemented in DGtal GenericReader." << std::endl;
         throw dgtalio;
       }
The documentation for this struct was generated from the following file:
GenericReader.h