DGtal: DGtal::TraceWriter Class Reference
DGtal::TraceWriter Class Reference abstract
#include <base/TraceWriter.h>
Public Member Functions
void selfDisplay (std::ostream &out) const
bool isValid () const
virtual std::string prefixWarning ()=0
virtual std::string prefixInfo ()=0
virtual std::string prefixError ()=0
virtual std::string prefixEmphase ()=0
virtual std::string postfixReset ()=0
std::ostream & outputStream ()
Protected Member Functions
TraceWriter (std::ostream &aoutputStream)
Protected Attributes
std::ostream & myOutputStream
Private Member Functions
TraceWriter (const TraceWriter &other)
TraceWriter & operator= (const TraceWriter &other)
Detailed Description
Virtual Class to implement trace writers.
Description of class 'TraceWriter'
Aim:
See also
testTrace.cpp
Definition at line 57 of file TraceWriter.h.
Constructor & Destructor Documentation
DGtal::TraceWriter::TraceWriter (std::ostream & aoutputStream) inline protected
Constructor. Forbidden by default (protected to avoid g++ warnings).
Definition at line 103 of file TraceWriter.h.
References DGtal::operator<<(), and operator=().
 : myOutputStream(aoutputStream) {};
DGtal::TraceWriter::TraceWriter (const TraceWriter & other) private
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
Member Function Documentation
bool DGtal::TraceWriter::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
TraceWriter& DGtal::TraceWriter::operator= (const TraceWriter & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
Referenced by TraceWriter().
std::ostream& DGtal::TraceWriter::outputStream () inline
Definition at line 84 of file TraceWriter.h.
References myOutputStream.
 {return myOutputStream;};
virtual std::string DGtal::TraceWriter::postfixReset () pure virtual
Implemented in DGtal::TraceWriterTerm, and DGtal::TraceWriterFile.
virtual std::string DGtal::TraceWriter::prefixEmphase () pure virtual
Implemented in DGtal::TraceWriterTerm, and DGtal::TraceWriterFile.
virtual std::string DGtal::TraceWriter::prefixError () pure virtual
Implemented in DGtal::TraceWriterTerm, and DGtal::TraceWriterFile.
virtual std::string DGtal::TraceWriter::prefixInfo () pure virtual
Implemented in DGtal::TraceWriterTerm, and DGtal::TraceWriterFile.
virtual std::string DGtal::TraceWriter::prefixWarning () pure virtual
Implemented in DGtal::TraceWriterTerm, and DGtal::TraceWriterFile.
void DGtal::TraceWriter::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Field Documentation
std::ostream& DGtal::TraceWriter::myOutputStream protected
Reference to the output stream.
Definition at line 84 of file TraceWriter.h.
Referenced by outputStream().
The documentation for this class was generated from the following file:
TraceWriter.h