DGtal: DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer > Class Template Reference
DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer > Class Template Reference
#include <geometry/volumes/distance/VoronoiMap.h>
Public Types
typedef TSpace Space
typedef TPointPredicate PointPredicate
typedef TImageContainer::Domain Domain
typedef TSeparableMetric SeparableMetric
typedef DGtal::int64_t IntegerLong
typedef Space::Vector Vector
typedef Space::Point Point
typedef Space::Dimension Dimension
typedef Space::Size Size
typedef Space::Point::Coordinate Abscissa
typedef TImageContainer OutputImage
typedef Vector Value
typedef OutputImage::ConstRange ConstRange
typedef VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer > Self
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CSpace< TSpace >))
BOOST_CONCEPT_ASSERT ((concepts::CPointPredicate< TPointPredicate >))
BOOST_CONCEPT_ASSERT ((concepts::CSeparableMetric< TSeparableMetric >))
BOOST_STATIC_ASSERT ((boost::is_same< typename TSpace::Point, typename TPointPredicate::Point >::value))
BOOST_STATIC_ASSERT ((boost::is_same< TSpace, typename TImageContainer::Domain::Space >::value))
BOOST_STATIC_ASSERT ((boost::is_same< typename TSpace::Vector, typename TImageContainer::Value >::value))
BOOST_STATIC_ASSERT ((boost::is_same< HyperRectDomain< TSpace >, typename TImageContainer::Domain >::value))
VoronoiMap (ConstAlias< Domain > aDomain, ConstAlias< PointPredicate > predicate, ConstAlias< SeparableMetric > aMetric)
~VoronoiMap ()
Self & operator= (const Self &aOtherVoronoiMap)
const Domain & domain () const
ConstRange constRange () const
Value operator() (const Point &aPoint) const
const SeparableMetric * metric () const
void selfDisplay (std::ostream &out) const
Protected Member Functions
VoronoiMap ()
Protected Attributes
const SeparableMetric * myMetricPtr
CountedPtr< OutputImage > myImagePtr
Private Member Functions
void compute ()
void computeOtherSteps (const Dimension dim) const
void computeOtherStep1D (const Point &row, const Size dim) const
Private Attributes
const Domain * myDomainPtr
const PointPredicate * myPointPredicatePtr
Point myLowerBoundCopy
Point myUpperBoundCopy
Point myInfinity
Detailed Description
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>>
class DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >
Aim: Implementation of the linear in time Voronoi map construction.
Description of template class 'VoronoiMap'
The algorithm uses a sperable process to construct Voronoi maps which has been described in [43] [18]
Given a domain and a point predicate, an instance returns, for each point in the domain, the closest point for which the predicate if false. Following Computational Geometry terminoliogy, points for which the predicate is false are "sites" for the Voronoi map construction. If a point is equi-distant to two sites (e.g. if the digital point belong to a Voronoi cell boundary in the Euclidean space), this Voronoi map construction will only keep one of them.
The metric is specified by a model of CSeparableMetric (for instance, any instance of ExactPredicateLpSeparableMetric or InexactPredicateLpSeparableMetric). If the separable metric has a complexity of O(h) for its "hiddenBy" predicate, the overall Voronoi construction algorithm is in \(O(h.d.n^d)\) for \(n^d\) domains (see class constructor). For Euclidean the \(l_2\) metric, the overall computation is in \(O(d.n^d)\), which is optimal.
If DGtal has been built with OpenMP support (WITH_OPENMP flag set to "true"), the computation is done in parallel (multithreaded) in an optimal way: on p processors, expected runtime is in \(O(h.d.n^d / p)\).
This class is a model of CConstImage.
Template Parameters
TSpace type of Digital Space (model of CSpace).
TPointPredicate point predicate returning true for points from which we compute the distance (model of concepts::CPointPredicate)
TSeparableMetric a model of CSeparableMetric
TImageContainer any model of CImage to store the VoronoiMap (default: ImageContainerBySTLVector). The space of the image container and the TSpace should match. Furthermore the container value type must be TSpace::Vector. Lastly, the domain of the container must be HyperRectDomain.
Examples:
geometry/volumes/distance/voronoimap2D.cpp.
Definition at line 113 of file VoronoiMap.h.
Member Typedef Documentation
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> typedef Space::Point::Coordinate DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::Abscissa
Definition at line 156 of file VoronoiMap.h.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> typedef OutputImage::ConstRange DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::ConstRange
Definition of the image value type.
Definition at line 164 of file VoronoiMap.h.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> typedef Space::Dimension DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::Dimension
Definition at line 154 of file VoronoiMap.h.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> typedef TImageContainer::Domain DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::Domain
Definition of the underlying domain type.
Definition at line 144 of file VoronoiMap.h.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> typedef DGtal::int64_t DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::IntegerLong
Large integer type for SeparableMetricHelper construction.
Definition at line 150 of file VoronoiMap.h.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> typedef TImageContainer DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::OutputImage
Type of resulting image.
Definition at line 159 of file VoronoiMap.h.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> typedef Space::Point DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::Point
Definition at line 153 of file VoronoiMap.h.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> typedef TPointPredicate DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::PointPredicate
Copy of the point predicate type.
Definition at line 141 of file VoronoiMap.h.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> typedef VoronoiMap<TSpace, TPointPredicate, TSeparableMetric,TImageContainer> DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::Self
Self type.
Definition at line 168 of file VoronoiMap.h.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> typedef TSeparableMetric DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::SeparableMetric
Definition of the separable metric type.
Definition at line 147 of file VoronoiMap.h.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> typedef Space::Size DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::Size
Definition at line 155 of file VoronoiMap.h.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> typedef TSpace DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::Space
Copy of the space type.
Definition at line 138 of file VoronoiMap.h.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> typedef Vector DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::Value
Definition of the image value type.
Definition at line 161 of file VoronoiMap.h.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> typedef Space::Vector DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::Vector
Definition at line 152 of file VoronoiMap.h.
Constructor & Destructor Documentation
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::VoronoiMap (ConstAlias< Domain > aDomain, ConstAlias< PointPredicate > predicate, ConstAlias< SeparableMetric > aMetric)
Constructor.
This constructor computes the Voronoi Map of a set of point sites using a SeparableMetric metric. The method associates to each point satisfying the foreground predicate, the closest site for which the predicate is false. This algorithm is \(O(h.d.|domain size|)\) if the separable metric "hiddenBy" predicate is in \(O(h)$\).
Parameters
aDomain a pointer to the (hyper-rectangular) domain on which the computation is performed.
predicate a pointer to the point predicate to define the Voronoi sites (false points).
aMetric a pointer to the separable metric instance.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::~VoronoiMap ()
Default destructor
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::VoronoiMap () protected
Default Constructor.
Referenced by DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::metric().
Member Function Documentation
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::BOOST_CONCEPT_ASSERT ((concepts::CSpace< TSpace >))
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::BOOST_CONCEPT_ASSERT ((concepts::CPointPredicate< TPointPredicate >))
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::BOOST_CONCEPT_ASSERT ((concepts::CSeparableMetric< TSeparableMetric >))
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::BOOST_STATIC_ASSERT ((boost::is_same< typename TSpace::Point, typename TPointPredicate::Point >::value))
Both Space points and PointPredicate points must be the same.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::BOOST_STATIC_ASSERT ((boost::is_same< TSpace, typename TImageContainer::Domain::Space >::value))
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::BOOST_STATIC_ASSERT ((boost::is_same< typename TSpace::Vector, typename TImageContainer::Value >::value))
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::BOOST_STATIC_ASSERT ((boost::is_same< HyperRectDomain< TSpace >, typename TImageContainer::Domain >::value))
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> void DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::compute () private
Compute the Voronoi Map of a set of point sites using a SeparableMetric metric. The method associates to each point satisfying the foreground predicate, the closest site for which the predicate is false. This algorithm is O(h.d.|domain size|).
Referenced by DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::metric().
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> void DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::computeOtherStep1D (const Point & row, const Size dim) const private
Given a voronoi map valid at dimension dim-1, this method updates the map to make it consistent at dimension dim along the 1D span starting at row along the dimension dim.
Parameters
[in] row starting point of the 1D process.
[in] dim dimension of the update.
Referenced by DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::metric().
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> void DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::computeOtherSteps (const Dimension dim) const private
Compute the other steps of the separable Voronoi map.
Parameters
[in] dim the dimension to process
Referenced by DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::metric().
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> ConstRange DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::constRange () const inline
Returns a const range on the Voronoi map values.
Returns
a const range
Definition at line 223 of file VoronoiMap.h.
References DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::myImagePtr.
     {
       return myImagePtr->constRange();
     }
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> const Domain& DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::domain () const inline
Returns a reference (const) to the Voronoi map domain.
Returns
a domain
Definition at line 213 of file VoronoiMap.h.
References DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::myDomainPtr.
Referenced by DGtal::DistanceTransformation< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::domain().
     {
       return *myDomainPtr;
     }
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> const SeparableMetric* DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::metric () const inline
Returns
Returns an alias to the underlying metric.
Definition at line 242 of file VoronoiMap.h.
References DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::compute(), DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::computeOtherStep1D(), DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::computeOtherSteps(), DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::myMetricPtr, DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::selfDisplay(), and DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::VoronoiMap().
Referenced by DGtal::DistanceTransformation< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::metric().
     {
       return myMetricPtr;
     }
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> Value DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::operator() (const Point & aPoint) const inline
Access to a Voronoi value (a.k.a. vector to the closest site) at a point.
Parameters
aPoint the point to probe.
Definition at line 234 of file VoronoiMap.h.
References DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::myImagePtr.
     {
       return myImagePtr->operator()(aPoint);
     }
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> Self& DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::operator= (const Self & aOtherVoronoiMap)
Assignment operator from another Voronoi map.
Parameters
aOtherVoronoiMap another instance of Self
Returns
a reference to Self
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> void DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::selfDisplay (std::ostream & out) const
Self Display method.
Parameters
out output stream
Referenced by DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::metric(), and DGtal::DistanceTransformation< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::selfDisplay().
Field Documentation
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> const Domain* DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::myDomainPtr private
Pointer to the computation domain.
Definition at line 298 of file VoronoiMap.h.
Referenced by DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::domain().
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> CountedPtr<OutputImage> DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::myImagePtr protected
Voronoi map image.
Definition at line 318 of file VoronoiMap.h.
Referenced by DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::constRange(), DGtal::DistanceTransformation< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::getVoronoiVector(), DGtal::DistanceTransformation< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::operator()(), and DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::operator()().
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> Point DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::myInfinity private
Value to act as a +infinity value.
Definition at line 310 of file VoronoiMap.h.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> Point DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::myLowerBoundCopy private
Copy of the image lower bound.
Definition at line 304 of file VoronoiMap.h.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> const SeparableMetric* DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::myMetricPtr protected
Pointer to the separable metric instance.
Definition at line 315 of file VoronoiMap.h.
Referenced by DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::metric(), and DGtal::DistanceTransformation< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::operator()().
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> const PointPredicate* DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::myPointPredicatePtr private
Pointer to the point predicate.
Definition at line 301 of file VoronoiMap.h.
template<typename TSpace, typename TPointPredicate, typename TSeparableMetric, typename TImageContainer = ImageContainerBySTLVector<HyperRectDomain<TSpace>, typename TSpace::Vector>> Point DGtal::VoronoiMap< TSpace, TPointPredicate, TSeparableMetric, TImageContainer >::myUpperBoundCopy private
Copy of the image lower bound.
Definition at line 307 of file VoronoiMap.h.
The documentation for this class was generated from the following file:
VoronoiMap.h