DGtal: LibBoard::MessageStream Class Reference
LibBoard::MessageStream Class Reference
#include </Users/davidcoeurjolly/Sources/DGtal/src/Board/Tools.h>
Public Member Functions
MessageStream (std::ostream &out, const char *prefix)
template<typename T >
MessageStream operator<< (const T &v)
Private Attributes
std::ostream & _out
const char * _prefix
Detailed Description
A "prefixable" message stream
Definition at line 29 of file Tools.h.
Constructor & Destructor Documentation
LibBoard::MessageStream::MessageStream (std::ostream & out, const char * prefix) inline
Definition at line 46 of file Tools.h.
Referenced by operator<<().
     : _out( out ),
       _prefix( prefix )
   {
   }
Member Function Documentation
template<typename T > MessageStream LibBoard::MessageStream::operator<< (const T & v) inline
Definition at line 53 of file Tools.h.
References _out, _prefix, MessageStream(), LibBoard::secured_ctime(), and LibBoard::secured_strncpy().
   {
     if ( _prefix )
       _out << _prefix << v;
     else
       _out << v;
     return MessageStream( _out, 0 );
   }
Field Documentation
std::ostream& LibBoard::MessageStream::_out private
Definition at line 38 of file Tools.h.
Referenced by operator<<().
const char* LibBoard::MessageStream::_prefix private
Definition at line 39 of file Tools.h.
Referenced by operator<<().
The documentation for this class was generated from the following file:
Tools.h