DGtal: DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator Struct Reference
DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator Struct Reference
#include <geometry/curves/OneBalancedWordComputer.h>
Public Types
typedef BidirectionalCategory iterator_category
typedef Point value_type
typedef Index difference_type
typedef Point * pointer
typedef Point & reference
Public Member Functions
ConstPointIterator ()
ConstPointIterator (const OneBalancedWordComputer *dss, Index ind, Point pt)
~ConstPointIterator ()
bool operator== (const ConstPointIterator other) const
bool operator!= (const ConstPointIterator other) const
Index operator- (const ConstPointIterator other) const
ConstPointIterator & operator= (const ConstPointIterator &other)
Point operator* () const
ConstPointIterator & operator++ ()
ConstPointIterator operator++ (int)
ConstPointIterator & operator-- ()
ConstPointIterator operator-- (int)
void next ()
void prev ()
const OneBalancedWordComputer * getDSS () const
Index getIndex () const
Data Fields
const OneBalancedWordComputer * myDSS
Index i
Point p
Detailed Description
template<typename TConstIterator, typename TInteger>
struct DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator
Iterator on the points of the DSS
Definition at line 248 of file OneBalancedWordComputer.h.
Member Typedef Documentation
template<typename TConstIterator, typename TInteger> typedef Index DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::difference_type
Definition at line 253 of file OneBalancedWordComputer.h.
template<typename TConstIterator, typename TInteger> typedef BidirectionalCategory DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::iterator_category
Definition at line 251 of file OneBalancedWordComputer.h.
template<typename TConstIterator, typename TInteger> typedef Point* DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::pointer
Definition at line 254 of file OneBalancedWordComputer.h.
template<typename TConstIterator, typename TInteger> typedef Point& DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::reference
Definition at line 255 of file OneBalancedWordComputer.h.
template<typename TConstIterator, typename TInteger> typedef Point DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::value_type
Definition at line 252 of file OneBalancedWordComputer.h.
Constructor & Destructor Documentation
template<typename TConstIterator, typename TInteger> DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::ConstPointIterator () inline
Default constructor, does nothing
Definition at line 264 of file OneBalancedWordComputer.h.
           {}
template<typename TConstIterator, typename TInteger> DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::ConstPointIterator (const OneBalancedWordComputer * dss, Index ind, Point pt) inline
Initialization constructor.
Parameters
dss OneBalancedWordComputer on which the iterator is defined.
ind Index of the first letter.
pt starting point of the iterator.
Definition at line 273 of file OneBalancedWordComputer.h.
                                                                                          :
             myDSS(dss), i(ind), p(pt)
           {}
template<typename TConstIterator, typename TInteger> DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::~ConstPointIterator () inline
Destructor. Does nothing.
Definition at line 280 of file OneBalancedWordComputer.h.
 {}
Member Function Documentation
template<typename TConstIterator, typename TInteger> const OneBalancedWordComputer* DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::getDSS () const inline
Definition at line 363 of file OneBalancedWordComputer.h.
             {
               return myDSS;
             }
template<typename TConstIterator, typename TInteger> Index DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::getIndex () const inline
Definition at line 370 of file OneBalancedWordComputer.h.
References DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::back(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::begin(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::computeLeaningPoints(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::defaultMoves(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::end(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::extendBack(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::extendFront(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::front(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::getA(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::getArithmeticalDescription(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::getB(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::getMu(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::getOmega(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::getReverse(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::getSelf(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::CodeHandler< TIterator, iterator_type >::init(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::isExtendableBack(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::isExtendableFront(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::isValid(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::Lf(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::Ll(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::longestChristoffelPrefix(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::OneBalancedWordComputer(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::operator!=(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::operator=(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::operator==(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::pointBegin(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::pointEnd(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::remainder(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::retractBack(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::retractFront(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::selfDisplay(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::setPosition(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::translate(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::Uf(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::Ul(), and DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::~OneBalancedWordComputer().
             {
               return i;
             }
template<typename TConstIterator, typename TInteger> void DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::next () inline
Definition at line 348 of file OneBalancedWordComputer.h.
References DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::getCode(), and DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::myDisplacements.
             {
               p += myDSS->myDisplacements( myDSS->getCode( i ) );
               ++i;
             }
template<typename TConstIterator, typename TInteger> bool DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::operator!= (const ConstPointIterator other) const inline
Definition at line 289 of file OneBalancedWordComputer.h.
References DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::i.
             {
               return i != other.i;
             }
template<typename TConstIterator, typename TInteger> Point DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::operator* () const inline
Definition at line 311 of file OneBalancedWordComputer.h.
             {
               return p;
             }
template<typename TConstIterator, typename TInteger> ConstPointIterator& DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::operator++ () inline
Definition at line 317 of file OneBalancedWordComputer.h.
             {
               next();
               return *this;
             }
template<typename TConstIterator, typename TInteger> ConstPointIterator DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::operator++ (int) inline
Definition at line 324 of file OneBalancedWordComputer.h.
             {
               ConstPointIterator it = *this;
               next();
               return it;
             }
template<typename TConstIterator, typename TInteger> Index DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::operator- (const ConstPointIterator other) const inline
Definition at line 294 of file OneBalancedWordComputer.h.
References DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::i.
             {
               return i - other.i;
             }
template<typename TConstIterator, typename TInteger> ConstPointIterator& DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::operator-- () inline
Definition at line 333 of file OneBalancedWordComputer.h.
             {
               prev();
               return *this;
             }
template<typename TConstIterator, typename TInteger> ConstPointIterator DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::operator-- (int) inline
Definition at line 340 of file OneBalancedWordComputer.h.
             {
               ConstPointIterator it = *this;
               prev();
               return it;
             }
template<typename TConstIterator, typename TInteger> ConstPointIterator& DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::operator= (const ConstPointIterator & other) inline
Copy operator
Definition at line 303 of file OneBalancedWordComputer.h.
References DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::i, DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::myDSS, and DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::p.
             {
               i = other.i;
               myDSS = other.myDSS;
               p = other.p;
               return *this;
             }
template<typename TConstIterator, typename TInteger> bool DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::operator== (const ConstPointIterator other) const inline
Comparaison operators.
Definition at line 285 of file OneBalancedWordComputer.h.
References DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::i.
             {
               return i == other.i;
             }
template<typename TConstIterator, typename TInteger> void DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::prev () inline
Definition at line 355 of file OneBalancedWordComputer.h.
References DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::getCode(), and DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::myDisplacements.
             {
               --i;
               p -= myDSS->myDisplacements( myDSS->getCode( i ) );
             }
Field Documentation
template<typename TConstIterator, typename TInteger> Index DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::i
Definition at line 258 of file OneBalancedWordComputer.h.
Referenced by DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::operator!=(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::operator-(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::operator=(), and DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::operator==().
template<typename TConstIterator, typename TInteger> const OneBalancedWordComputer* DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::myDSS
Definition at line 257 of file OneBalancedWordComputer.h.
Referenced by DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::operator=().
template<typename TConstIterator, typename TInteger> Point DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::p
Definition at line 259 of file OneBalancedWordComputer.h.
Referenced by DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::ConstPointIterator::operator=().
The documentation for this struct was generated from the following file:
OneBalancedWordComputer.h