DGtal: DGtal::CConstBidirectionalRangeFromPoint< T > Struct Template Reference
DGtal::CConstBidirectionalRangeFromPoint< T > Struct Template Reference
DGtal Concepts
#include <base/CConstBidirectionalRangeFromPoint.h>
Public Types
typedef T::Point Point
Public Types inherited from DGtal::CConstBidirectionalRange< T >
typedef T::ConstReverseIterator ConstReverseIterator
Public Types inherited from DGtal::CConstSinglePassRange< T >
typedef T::ConstIterator ConstIterator
Public Member Functions
BOOST_CONCEPT_USAGE (CConstBidirectionalRangeFromPoint)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::CConstBidirectionalRange< T >
BOOST_CONCEPT_ASSERT ((boost_concepts::SinglePassIteratorConcept< ConstReverseIterator >))
BOOST_CONCEPT_USAGE (CConstBidirectionalRange)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::CConstSinglePassRange< T >
BOOST_CONCEPT_ASSERT ((boost_concepts::SinglePassIteratorConcept< ConstIterator >))
BOOST_CONCEPT_USAGE (CConstSinglePassRange)
void checkConstConstraints () const
Private Attributes
T myX
Point myPoint
T::ConstReverseIterator myB
Detailed Description
template<typename T>
struct DGtal::CConstBidirectionalRangeFromPoint< T >
Aim: refined concept of const bidirectional range with a begin() method from a point.
DescriptionDescription of concept 'CConstBidirectionalRangeFromPoint'
Refinement of CConstBidirectionalRange
Associated types :
Notation
X : A type that is a model of CConstBidirectionalRangeFromPoint
x, y : object of type X
Point: A type of Point
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
reverse begin rbegin(const Point &aPoint) aPoint of type Point ConstIterator Returns a const reverse iterator on the range first element
Invariants
Models
ImageContainerBySTLVector::Range
Notes
Template Parameters
T the type that should be a model of CConstBidirectionalRangeFromPoint.
Definition at line 90 of file CConstBidirectionalRangeFromPoint.h.
Member Typedef Documentation
template<typename T > typedef T::Point DGtal::CConstBidirectionalRangeFromPoint< T >::Point
Definition at line 95 of file CConstBidirectionalRangeFromPoint.h.
Member Function Documentation
template<typename T > DGtal::CConstBidirectionalRangeFromPoint< T >::BOOST_CONCEPT_USAGE (CConstBidirectionalRangeFromPoint< T >) inline
Definition at line 98 of file CConstBidirectionalRangeFromPoint.h.
References DGtal::CConstBidirectionalRangeFromPoint< T >::checkConstConstraints().
     {
  checkConstConstraints();
     }
template<typename T > void DGtal::CConstBidirectionalRangeFromPoint< T >::checkConstConstraints () const inline
Definition at line 102 of file CConstBidirectionalRangeFromPoint.h.
References DGtal::CConstBidirectionalRangeFromPoint< T >::myB, DGtal::CConstBidirectionalRangeFromPoint< T >::myPoint, DGtal::CConstBidirectionalRangeFromPoint< T >::myX, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::CConstBidirectionalRangeFromPoint< T >::BOOST_CONCEPT_USAGE().
     {
  // const method dummyConst should take parameter myA of type A and return
  // something of type B
       concepts::ConceptUtils::sameType( myB, myX.rbegin( myPoint ) );
     }
Field Documentation
template<typename T > T::ConstReverseIterator DGtal::CConstBidirectionalRangeFromPoint< T >::myB private
Definition at line 112 of file CConstBidirectionalRangeFromPoint.h.
Referenced by DGtal::CConstBidirectionalRangeFromPoint< T >::checkConstConstraints().
template<typename T > Point DGtal::CConstBidirectionalRangeFromPoint< T >::myPoint private
Definition at line 111 of file CConstBidirectionalRangeFromPoint.h.
Referenced by DGtal::CConstBidirectionalRangeFromPoint< T >::checkConstConstraints().
template<typename T > T DGtal::CConstBidirectionalRangeFromPoint< T >::myX private
Definition at line 110 of file CConstBidirectionalRangeFromPoint.h.
Referenced by DGtal::CConstBidirectionalRangeFromPoint< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CConstBidirectionalRangeFromPoint.h