DGtal: DGtal::Object< TDigitalTopology, TDigitalSet >::Edge Struct Reference
DGtal::Object< TDigitalTopology, TDigitalSet >::Edge Struct Reference
#include <topology/Object.h>
Public Member Functions
Edge (const Vertex &v1, const Vertex &v2)
bool operator== (const Edge &other) const
bool operator< (const Edge &other) const
Data Fields
Vertex vertices [2]
Detailed Description
template<typename TDigitalTopology, typename TDigitalSet>
struct DGtal::Object< TDigitalTopology, TDigitalSet >::Edge
Definition at line 127 of file Object.h.
Constructor & Destructor Documentation
template<typename TDigitalTopology, typename TDigitalSet> DGtal::Object< TDigitalTopology, TDigitalSet >::Edge::Edge (const Vertex & v1, const Vertex & v2) inline
Constructor from vertices.
Parameters
v1 the first vertex.
v2 the second vertex.
Definition at line 136 of file Object.h.
         {
           if ( v1 <= v2 )
             {
               vertices[ 0 ] = v1;
               vertices[ 1 ] = v2;
             }
           else
             {
               vertices[ 0 ] = v2;
               vertices[ 1 ] = v1;
             }
         }
Member Function Documentation
template<typename TDigitalTopology, typename TDigitalSet> bool DGtal::Object< TDigitalTopology, TDigitalSet >::Edge::operator< (const Edge & other) const inline
Definition at line 154 of file Object.h.
References DGtal::Object< TDigitalTopology, TDigitalSet >::adjacency(), DGtal::Object< TDigitalTopology, TDigitalSet >::begin(), DGtal::Object< TDigitalTopology, TDigitalSet >::bestCapacity(), DGtal::Object< TDigitalTopology, TDigitalSet >::border(), DGtal::Object< TDigitalTopology, TDigitalSet >::computeConnectedness(), DGtal::Object< TDigitalTopology, TDigitalSet >::connectedness(), DGtal::Object< TDigitalTopology, TDigitalSet >::degree(), DGtal::Object< TDigitalTopology, TDigitalSet >::domain(), DGtal::Object< TDigitalTopology, TDigitalSet >::domainPointer(), DGtal::Object< TDigitalTopology, TDigitalSet >::end(), DGtal::Object< TDigitalTopology, TDigitalSet >::geodesicNeighborhood(), DGtal::Object< TDigitalTopology, TDigitalSet >::geodesicNeighborhoodInComplement(), DGtal::Object< TDigitalTopology, TDigitalSet >::isSimple(), DGtal::Object< TDigitalTopology, TDigitalSet >::isValid(), DGtal::Object< TDigitalTopology, TDigitalSet >::neighborhood(), DGtal::Object< TDigitalTopology, TDigitalSet >::neighborhoodSize(), DGtal::Object< TDigitalTopology, TDigitalSet >::Object(), DGtal::Object< TDigitalTopology, TDigitalSet >::operator=(), DGtal::Object< TDigitalTopology, TDigitalSet >::pointSet(), DGtal::Object< TDigitalTopology, TDigitalSet >::properNeighborhood(), DGtal::Object< TDigitalTopology, TDigitalSet >::properNeighborhoodSize(), DGtal::Object< TDigitalTopology, TDigitalSet >::selfDisplay(), DGtal::Object< TDigitalTopology, TDigitalSet >::size(), DGtal::Object< TDigitalTopology, TDigitalSet >::topology(), DGtal::UNKNOWN, DGtal::Object< TDigitalTopology, TDigitalSet >::Edge::vertices, DGtal::Object< TDigitalTopology, TDigitalSet >::writeComponents(), DGtal::Object< TDigitalTopology, TDigitalSet >::writeNeighbors(), and DGtal::Object< TDigitalTopology, TDigitalSet >::~Object().
         {
           return ( vertices[ 0 ] < other.vertices[ 0 ] )
             || ( ( vertices[ 0 ] == other.vertices[ 0 ] )
                 && ( vertices[ 1 ] < other.vertices[ 1 ] ) );
         }
template<typename TDigitalTopology, typename TDigitalSet> bool DGtal::Object< TDigitalTopology, TDigitalSet >::Edge::operator== (const Edge & other) const inline
Definition at line 149 of file Object.h.
References DGtal::Object< TDigitalTopology, TDigitalSet >::Edge::vertices.
         {
           return ( vertices[ 0 ] == other.vertices[ 0 ] )
             && ( vertices[ 1 ] == other.vertices[ 1 ] );
         }
Field Documentation
template<typename TDigitalTopology, typename TDigitalSet> Vertex DGtal::Object< TDigitalTopology, TDigitalSet >::Edge::vertices[2]
Definition at line 129 of file Object.h.
Referenced by DGtal::Object< TDigitalTopology, TDigitalSet >::Edge::operator<(), and DGtal::Object< TDigitalTopology, TDigitalSet >::Edge::operator==().
The documentation for this struct was generated from the following file:
Object.h