DGtal: DGtal::CConstBidirectionalRange< T > Struct Template Reference
DGtal::CConstBidirectionalRange< T > Struct Template Reference
DGtal Concepts
#include <base/CConstBidirectionalRange.h>
Public Types
typedef T::ConstReverseIterator ConstReverseIterator
Public Types inherited from DGtal::CConstSinglePassRange< T >
typedef T::ConstIterator ConstIterator
Public Member Functions
BOOST_CONCEPT_ASSERT ((boost_concepts::SinglePassIteratorConcept< ConstReverseIterator >))
BOOST_CONCEPT_USAGE (CConstBidirectionalRange)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::CConstSinglePassRange< T >
BOOST_CONCEPT_ASSERT ((boost_concepts::SinglePassIteratorConcept< ConstIterator >))
BOOST_CONCEPT_USAGE (CConstSinglePassRange)
void checkConstConstraints () const
Private Attributes
T i
ConstReverseIterator it
Detailed Description
template<typename T>
struct DGtal::CConstBidirectionalRange< T >
Aim: Defines the concept describing a bidirectional const range.
Description of concept 'CConstBidirectionalRange'
Refinement of
CConstSinglePassRange
Provided types :
ConstReverseIterator: the const reverse iterator type, a model of const iterator concept.
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
rbegin of range x.rbegin() ConstReverseIterator returns a reverse forward iterator on the beginning of the range
rend of range x.rend() ConstReverseIterator returns a reverse forward iterator after the end of the range
Invariants
Models
Notes
Template Parameters
T the type that is checked. T should be a model of CConstBidirectionalRange.
Definition at line 85 of file CConstBidirectionalRange.h.
Member Typedef Documentation
template<typename T > typedef T::ConstReverseIterator DGtal::CConstBidirectionalRange< T >::ConstReverseIterator
Definition at line 89 of file CConstBidirectionalRange.h.
Member Function Documentation
template<typename T > DGtal::CConstBidirectionalRange< T >::BOOST_CONCEPT_ASSERT ((boost_concepts::SinglePassIteratorConcept< ConstReverseIterator >))
template<typename T > DGtal::CConstBidirectionalRange< T >::BOOST_CONCEPT_USAGE (CConstBidirectionalRange< T >) inline
Definition at line 93 of file CConstBidirectionalRange.h.
References DGtal::CConstBidirectionalRange< T >::checkConstConstraints().
   {
     checkConstConstraints();
   }
template<typename T > void DGtal::CConstBidirectionalRange< T >::checkConstConstraints () const inline
Definition at line 97 of file CConstBidirectionalRange.h.
References DGtal::CConstBidirectionalRange< T >::i, DGtal::CConstBidirectionalRange< T >::it, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::CConstBidirectionalRange< T >::BOOST_CONCEPT_USAGE().
   {
     concepts::ConceptUtils::sameType( it, i.rbegin() );
     concepts::ConceptUtils::sameType( it, i.rend() );
   }
Field Documentation
template<typename T > T DGtal::CConstBidirectionalRange< T >::i private
Definition at line 104 of file CConstBidirectionalRange.h.
Referenced by DGtal::CConstBidirectionalRange< T >::checkConstConstraints().
template<typename T > ConstReverseIterator DGtal::CConstBidirectionalRange< T >::it private
Definition at line 105 of file CConstBidirectionalRange.h.
Referenced by DGtal::CConstBidirectionalRange< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CConstBidirectionalRange.h