DGtal: DGtal::HyperRectDomain_subIterator< TPoint > Class Template Reference
DGtal::HyperRectDomain_subIterator< TPoint > Class Template Reference
#include <DGtal/kernel/domains/HyperRectDomain_Iterator.h>
Public Types
typedef std::bidirectional_iterator_tag iterator_category
typedef TPoint value_type
typedef ptrdiff_t difference_type
typedef TPoint * pointer
typedef TPoint & reference
typedef TPoint::Dimension Dimension
Public Member Functions
HyperRectDomain_subIterator (const TPoint &p, const TPoint &lower, const TPoint &upper, std::initializer_list< Dimension > subDomain)
HyperRectDomain_subIterator (const TPoint &p, const TPoint &lower, const TPoint &upper, const std::vector< Dimension > &subDomain)
const TPoint & operator* () const
TPoint & operator* ()
bool operator== (const HyperRectDomain_subIterator< TPoint > &it) const
bool operator!= (const HyperRectDomain_subIterator< TPoint > &aIt) const
void nextSubDomainOrder ()
HyperRectDomain_subIterator< TPoint > & operator++ ()
HyperRectDomain_subIterator< TPoint > operator++ (int)
void prevSubDomainOrder ()
HyperRectDomain_subIterator< TPoint > & operator-- ()
HyperRectDomain_subIterator< TPoint > operator-- (int)
Private Attributes
TPoint myPoint
TPoint mylower
TPoint myupper
std::vector< Dimension > mySubDomain
Detailed Description
template<typename TPoint>
class DGtal::HyperRectDomain_subIterator< TPoint >
Description of class 'HyperRectDomain_subIterator'
Aim:
Definition at line 321 of file HyperRectDomain_Iterator.h.
Member Typedef Documentation
difference_type
template<typename TPoint> typedef ptrdiff_t DGtal::HyperRectDomain_subIterator< TPoint >::difference_type
Definition at line 326 of file HyperRectDomain_Iterator.h.
Dimension
template<typename TPoint> typedef TPoint::Dimension DGtal::HyperRectDomain_subIterator< TPoint >::Dimension
Definition at line 329 of file HyperRectDomain_Iterator.h.
iterator_category
template<typename TPoint> typedef std::bidirectional_iterator_tag DGtal::HyperRectDomain_subIterator< TPoint >::iterator_category
Definition at line 324 of file HyperRectDomain_Iterator.h.
pointer
template<typename TPoint> typedef TPoint* DGtal::HyperRectDomain_subIterator< TPoint >::pointer
Definition at line 327 of file HyperRectDomain_Iterator.h.
reference
template<typename TPoint> typedef TPoint& DGtal::HyperRectDomain_subIterator< TPoint >::reference
Definition at line 328 of file HyperRectDomain_Iterator.h.
value_type
template<typename TPoint> typedef TPoint DGtal::HyperRectDomain_subIterator< TPoint >::value_type
Todo:
construct a RANDOM-ACCESS iterator
Definition at line 325 of file HyperRectDomain_Iterator.h.
Constructor & Destructor Documentation
HyperRectDomain_subIterator() [1/2]
template<typename TPoint> DGtal::HyperRectDomain_subIterator< TPoint >::HyperRectDomain_subIterator (const TPoint & p, const TPoint & lower, const TPoint & upper, std::initializer_list< Dimension > subDomain) inline
Definition at line 331 of file HyperRectDomain_Iterator.h.
References lower(), DGtal::HyperRectDomain_subIterator< TPoint >::mySubDomain, and upper().
       : myPoint( p ), mylower( lower ), myupper( upper )
       {
         ASSERT_MSG( // For an empty domain, lower = upper + diag(1) so that begin() == end().
             lower.isLower(upper) || lower == upper + TPoint::diagonal(0).partialCopy( TPoint::diagonal(1), subDomain),
             "The lower bound must be lower than the upper bound or, for an empty domain, be equal to the upper bound + diagonal(1)."
             );
         ASSERT_MSG(
             ( lower.isLower(p) && p.isLower(upper) ) || p == lower || p == upper,
             "The point must be inside the domain or be equal to one of his bound."
         );
         ASSERT_MSG(
             subDomain.size() <= TPoint::dimension,
             "The sub-range cannot have more dimensions than the ambiant space."
         );
         mySubDomain.reserve( subDomain.size() );
         for ( const unsigned int *c = subDomain.begin();
             c != subDomain.end(); ++c )
           {
             ASSERT_MSG(
                 *c <= TPoint::dimension,
                 "Invalid dimension in the sub-range."
             );
             mySubDomain.push_back( *c );
           }
         // TODO: check the validity of the subDomain ?
       }
HyperRectDomain_subIterator() [2/2]
template<typename TPoint> DGtal::HyperRectDomain_subIterator< TPoint >::HyperRectDomain_subIterator (const TPoint & p, const TPoint & lower, const TPoint & upper, const std::vector< Dimension > & subDomain) inline
Definition at line 366 of file HyperRectDomain_Iterator.h.
References lower(), DGtal::HyperRectDomain_subIterator< TPoint >::mySubDomain, and upper().
       : myPoint( p ), mylower( lower ), myupper( upper )
       {
         ASSERT_MSG( // For an empty domain, lower = upper + diag(1) so that begin() == end().
             lower.isLower(upper) || lower == upper + TPoint::diagonal(0).partialCopy( TPoint::diagonal(1), subDomain ),
             "The lower bound must be lower than the upper bound or, for an empty domain, be equal to the upper bound + diagonal(1)."
         );
         ASSERT_MSG(
             ( lower.isLower(p) && p.isLower(upper) ) || p == lower || p == upper,
             "The point must be inside the domain or be equal to one of his bound."
         );
         ASSERT_MSG(
             subDomain.size() <= TPoint::dimension,
             "The sub-range cannot have more dimensions than the ambiant space."
         );
         mySubDomain.reserve( subDomain.size() );
         for ( typename std::vector<Dimension>::const_iterator it = subDomain.begin();
             it != subDomain.end(); ++it )
           {
             ASSERT_MSG(
                 *it <= TPoint::dimension,
                 "Invalid dimension in the sub-range."
             );
             mySubDomain.push_back( *it );
           }
         // TODO: check the validity of the subDomain ?
       }
Member Function Documentation
nextSubDomainOrder()
template<typename TPoint> void DGtal::HyperRectDomain_subIterator< TPoint >::nextSubDomainOrder () inline
Implements the next() method to scan the domain points dimension by dimension (by using the subDomain order given by the user).
Definition at line 447 of file HyperRectDomain_Iterator.h.
References DGtal::HyperRectDomain_subIterator< TPoint >::mylower, DGtal::HyperRectDomain_subIterator< TPoint >::myPoint, DGtal::HyperRectDomain_subIterator< TPoint >::mySubDomain, and DGtal::HyperRectDomain_subIterator< TPoint >::myupper.
Referenced by DGtal::HyperRectDomain_subIterator< TPoint >::operator++().
       {
         ASSERT( mySubDomain.size() > 0 );
         ++myPoint[ mySubDomain[0] ];
         if ( mySubDomain.size() > 1 &&
             myPoint[ mySubDomain[0] ] >
             myupper[ mySubDomain[0] ] )
           {
             Dimension current_pos = 0;
             do
               {
                 myPoint[ mySubDomain[current_pos] ] =
                   mylower[ mySubDomain[current_pos] ];
                 ++current_pos;
                 if ( current_pos < mySubDomain.size() )
                   ++myPoint[ mySubDomain[current_pos] ];
               }
             while (( current_pos + 1 < mySubDomain.size() ) &&
                 ( myPoint[ mySubDomain[current_pos] ]  >
                   myupper[ mySubDomain[current_pos] ] ) );
           }
       }
operator!=()
template<typename TPoint> bool DGtal::HyperRectDomain_subIterator< TPoint >::operator!= (const HyperRectDomain_subIterator< TPoint > & aIt) const inline
Operator !=
Definition at line 438 of file HyperRectDomain_Iterator.h.
References DGtal::HyperRectDomain_subIterator< TPoint >::operator==().
       {
         return !operator==(aIt);
       }
operator*() [1/2]
template<typename TPoint> const TPoint& DGtal::HyperRectDomain_subIterator< TPoint >::operator* () const inline
Definition at line 401 of file HyperRectDomain_Iterator.h.
References DGtal::HyperRectDomain_subIterator< TPoint >::mylower, DGtal::HyperRectDomain_subIterator< TPoint >::myPoint, and DGtal::HyperRectDomain_subIterator< TPoint >::myupper.
       {
         ASSERT_MSG( // we must be between [begin,end]
             mylower.isLower(myPoint) && myPoint.isLower(myupper),
             "The iterator points outside the domain."
         );
         return myPoint;
       }
operator*() [2/2]
template<typename TPoint> TPoint& DGtal::HyperRectDomain_subIterator< TPoint >::operator* () inline
Definition at line 411 of file HyperRectDomain_Iterator.h.
References DGtal::HyperRectDomain_subIterator< TPoint >::mylower, DGtal::HyperRectDomain_subIterator< TPoint >::myPoint, and DGtal::HyperRectDomain_subIterator< TPoint >::myupper.
       {
         ASSERT_MSG( // we must be between [begin,end]
             mylower.isLower(myPoint) && myPoint.isLower(myupper),
             "The iterator points outside the domain."
         );
         return myPoint;
       }
operator++() [1/2]
template<typename TPoint> HyperRectDomain_subIterator<TPoint>& DGtal::HyperRectDomain_subIterator< TPoint >::operator++ () inline
Operator ++ (++it)
Definition at line 474 of file HyperRectDomain_Iterator.h.
References DGtal::HyperRectDomain_subIterator< TPoint >::nextSubDomainOrder().
       {
         nextSubDomainOrder();
         return *this;
       }
operator++() [2/2]
template<typename TPoint> HyperRectDomain_subIterator<TPoint> DGtal::HyperRectDomain_subIterator< TPoint >::operator++ (int) inline
Operator ++ (it++)
Definition at line 484 of file HyperRectDomain_Iterator.h.
References DGtal::HyperRectDomain_subIterator< TPoint >::nextSubDomainOrder().
       {
         HyperRectDomain_subIterator<TPoint> tmp = *this;
         nextSubDomainOrder();
         return tmp;
       }
operator--() [1/2]
template<typename TPoint> HyperRectDomain_subIterator<TPoint>& DGtal::HyperRectDomain_subIterator< TPoint >::operator-- () inline
Operator – (–it)
Definition at line 523 of file HyperRectDomain_Iterator.h.
References DGtal::HyperRectDomain_subIterator< TPoint >::prevSubDomainOrder().
       {
         prevSubDomainOrder();
         return *this;
       }
operator--() [2/2]
template<typename TPoint> HyperRectDomain_subIterator<TPoint> DGtal::HyperRectDomain_subIterator< TPoint >::operator-- (int) inline
Operator – (it–)
Definition at line 532 of file HyperRectDomain_Iterator.h.
References DGtal::HyperRectDomain_subIterator< TPoint >::prevSubDomainOrder().
       {
         HyperRectDomain_subIterator<TPoint> tmp = *this;
         prevSubDomainOrder();
         return tmp;
       }
operator==()
template<typename TPoint> bool DGtal::HyperRectDomain_subIterator< TPoint >::operator== (const HyperRectDomain_subIterator< TPoint > & it) const inline
Operator ==
Definition at line 425 of file HyperRectDomain_Iterator.h.
References DGtal::HyperRectDomain_subIterator< TPoint >::myPoint, and DGtal::HyperRectDomain_subIterator< TPoint >::mySubDomain.
Referenced by DGtal::HyperRectDomain_subIterator< TPoint >::operator!=().
       {
         for (unsigned int i=0; i<mySubDomain.size(); ++i)
           if ( myPoint[mySubDomain[i]]!=it.myPoint[mySubDomain[i]])
             return false;
         return true;
       }
prevSubDomainOrder()
template<typename TPoint> void DGtal::HyperRectDomain_subIterator< TPoint >::prevSubDomainOrder () inline
Implements the prev() method to scan the domain points dimension by dimension (subDomain order).
Definition at line 495 of file HyperRectDomain_Iterator.h.
References DGtal::HyperRectDomain_subIterator< TPoint >::mylower, DGtal::HyperRectDomain_subIterator< TPoint >::myPoint, DGtal::HyperRectDomain_subIterator< TPoint >::mySubDomain, and DGtal::HyperRectDomain_subIterator< TPoint >::myupper.
Referenced by DGtal::HyperRectDomain_subIterator< TPoint >::operator--().
       {
         ASSERT( mySubDomain.size() > 0 );
         --myPoint[ mySubDomain[0] ];
         if (  mySubDomain.size() > 1 &&
             myPoint[ mySubDomain[0] ]  <
             mylower[ mySubDomain[0] ] )
           {
             Dimension current_pos = 0;
             do
               {
                 myPoint[ mySubDomain[current_pos] ] =
                   myupper[ mySubDomain[current_pos] ];
                 ++current_pos;
                 if ( current_pos < mySubDomain.size() )
                   --myPoint[ mySubDomain[current_pos] ];
               }
             while (( current_pos + 1 < mySubDomain.size() ) &&
                 ( myPoint[ mySubDomain[current_pos] ]  <
                   mylower[ mySubDomain[current_pos] ] ) );
           }
       }
Field Documentation
mylower
template<typename TPoint> TPoint DGtal::HyperRectDomain_subIterator< TPoint >::mylower private
Copies of the Domain limits.
Definition at line 543 of file HyperRectDomain_Iterator.h.
Referenced by DGtal::HyperRectDomain_subIterator< TPoint >::nextSubDomainOrder(), DGtal::HyperRectDomain_subIterator< TPoint >::operator*(), and DGtal::HyperRectDomain_subIterator< TPoint >::prevSubDomainOrder().
myPoint
template<typename TPoint> TPoint DGtal::HyperRectDomain_subIterator< TPoint >::myPoint private
Current Point in the domain.
Definition at line 541 of file HyperRectDomain_Iterator.h.
Referenced by DGtal::HyperRectDomain_subIterator< TPoint >::nextSubDomainOrder(), DGtal::HyperRectDomain_subIterator< TPoint >::operator*(), DGtal::HyperRectDomain_subIterator< TPoint >::operator==(), and DGtal::HyperRectDomain_subIterator< TPoint >::prevSubDomainOrder().
mySubDomain
template<typename TPoint> std::vector<Dimension> DGtal::HyperRectDomain_subIterator< TPoint >::mySubDomain private
Vector of subDomain on dimension, to fix the order in which dimensions are considered.
Definition at line 546 of file HyperRectDomain_Iterator.h.
Referenced by DGtal::HyperRectDomain_subIterator< TPoint >::HyperRectDomain_subIterator(), DGtal::HyperRectDomain_subIterator< TPoint >::nextSubDomainOrder(), DGtal::HyperRectDomain_subIterator< TPoint >::operator==(), and DGtal::HyperRectDomain_subIterator< TPoint >::prevSubDomainOrder().
myupper
template<typename TPoint> TPoint DGtal::HyperRectDomain_subIterator< TPoint >::myupper private
Definition at line 543 of file HyperRectDomain_Iterator.h.
Referenced by DGtal::HyperRectDomain_subIterator< TPoint >::nextSubDomainOrder(), DGtal::HyperRectDomain_subIterator< TPoint >::operator*(), and DGtal::HyperRectDomain_subIterator< TPoint >::prevSubDomainOrder().
The documentation for this class was generated from the following file:
HyperRectDomain_Iterator.h