DGtal: DGtal Namespace Reference
DGtal Namespace Reference
Namespaces
concepts
deprecated
detail
experimental
functions
functors
Z2i
Z3i
Data Structures
class AccFlower2D
struct AddTextureImage2DWithFunctor
struct AddTextureImage3DWithFunctor
class Alias
class AlphaThickSegmentComputer
struct AngleComputer
class AngleLinearMinimizer
class AngleLinearMinimizerByAdaptiveStepGradientDescent
class AngleLinearMinimizerByGradientDescent
class AngleLinearMinimizerByRelaxation
class ArithDSSIterator
class ArithmeticalDSL
struct ArithmeticalDSLKernel
struct ArithmeticalDSLKernel< TCoordinate, 4 >
class ArithmeticalDSS
class ArithmeticalDSSComputer
class ArithmeticalDSSFactory
class ArrayImageAdapter< TArrayIterator, HyperRectDomain< TSpace > >
class ArrayImageIterator
struct AssociativeCategory
class Astroid2D
struct ATu0v1
struct ATu2v0
class AvnaimEtAl2x2DetSignComputer
class BackInsertionSequenceToStackAdapter
class Ball2D
class Ball3D
struct BidirectionalCategory
struct BidirectionalSegmentComputer
class BinomialConvolver
class BinomialConvolverEstimator
struct Bits
class BLUELocalLengthEstimator
class Board2D
class Board3D
class Board3DTo2D
struct Board3DTo2DFactory
class BreadthFirstVisitor
struct C2x2DetComputer
struct CameraDirection
struct CameraPosition
struct CameraUpVector
struct CameraZNearFar
struct CanonicCellEmbedder
struct CanonicDigitalSurfaceEmbedder
struct CanonicEmbedder
struct CanonicSCellEmbedder
struct CBidirectionalIteratorArchetype
struct CConstBidirectionalIteratorArchetype
struct CForwardIteratorArchetype
class ChordGenericNaivePlaneComputer
class ChordGenericStandardPlaneComputer
class ChordNaivePlaneComputer
class CircleFrom2Points
class CircleFrom3Points
class Circulator
struct CirculatorType
struct ClippingPlane
class Clock
class Clone
struct ClosedIntegerHalfPlane
class COBAGenericNaivePlaneComputer
class COBAGenericStandardPlaneComputer
class COBANaivePlaneComputer
struct ColMajorStorage
class Color
class ColorBrightnessColorMap
struct CompareLocalEstimators
class ConnectivityException
class ConstAlias
class ConstImageAdapter
class ConstIteratorAdapter
class ConstRangeAdapter
class ConstRangeFromPointAdapter
struct ContainerCategory
struct ContainerTraits
struct ContainerTraits< boost::unordered_map< Value, T, Hash, Pred, Alloc > >
struct ContainerTraits< boost::unordered_multimap< Value, T, Hash, Pred, Alloc > >
struct ContainerTraits< boost::unordered_multiset< Value, Hash, Pred, Alloc > >
struct ContainerTraits< boost::unordered_set< Value, Hash, Pred, Alloc > >
struct ContainerTraits< CubicalComplex< TKSpace, TCellContainer > >
struct ContainerTraits< std::array< T, N > >
struct ContainerTraits< std::deque< T, Alloc > >
struct ContainerTraits< std::forward_list< T, Alloc > >
struct ContainerTraits< std::list< T, Alloc > >
struct ContainerTraits< std::map< Key, T, Compare, Alloc > >
struct ContainerTraits< std::multimap< Key, T, Compare, Alloc > >
struct ContainerTraits< std::multiset< T, Compare, Alloc > >
struct ContainerTraits< std::set< T, Compare, Alloc > >
struct ContainerTraits< std::unordered_map< Key, T, Hash, Pred, Alloc > >
struct ContainerTraits< std::unordered_multimap< Key, T, Hash, Pred, Alloc > >
struct ContainerTraits< std::unordered_multiset< Key, Hash, Pred, Alloc > >
struct ContainerTraits< std::unordered_set< Key, Hash, Pred, Alloc > >
struct ContainerTraits< std::vector< T, Alloc > >
class ContourHelper
class CountedConstPtrOrConstPtr
class CountedPtr
class CountedPtrOrPtr
class CowPtr
struct CSinglePassIteratorArchetype
struct CubicalCellData
class CubicalComplex
struct CurvatureFromBinomialConvolverFunctor
class CurvatureFromDCAEstimator
class CurvatureFromDSSEstimator
class CurvatureFromDSSLengthEstimator
struct CustomColors
struct CustomColors3D
struct CustomFillColor
struct CustomPen
struct CustomPenColor
struct CustomStyle
struct CustomStyle3D
struct DECImage2D
class DefaultConstImageRange
class DefaultImageRange
class DepthFirstVisitor
struct DicomReader
class DigitalMetricAdapter
class DigitalSetBoundary
class DigitalSetByAssociativeContainer
class DigitalSetBySTLSet
class DigitalSetBySTLVector
struct DigitalSetConverter
class DigitalSetDomain
class DigitalSetFromMap
class DigitalSetInserter
struct DigitalSetSelector
class DigitalShapesCSG
class DigitalSurface
class DigitalSurface2DSlice
class DigitalSurfaceConvolver
class DigitalSurfaceConvolver< TFunctor, TKernelFunctor, TKSpace, TDigitalKernel, 2 >
class DigitalSurfaceConvolver< TFunctor, TKernelFunctor, TKSpace, TDigitalKernel, 3 >
class DigitalSurfaceEmbedderWithNormalVectorEstimator
class DigitalSurfaceEmbedderWithNormalVectorEstimatorGradientMap
class DigitalTopology
struct DigitalTopologyTraits
struct DigitalTopologyTraits< MetricAdjacency< TSpace, 1 >, MetricAdjacency< TSpace, 2 >, 2 >
struct DigitalTopologyTraits< MetricAdjacency< TSpace, 1 >, MetricAdjacency< TSpace, 2 >, 3 >
struct DigitalTopologyTraits< MetricAdjacency< TSpace, 1 >, MetricAdjacency< TSpace, 3 >, 3 >
struct DigitalTopologyTraits< MetricAdjacency< TSpace, 2 >, MetricAdjacency< TSpace, 1 >, 2 >
struct DigitalTopologyTraits< MetricAdjacency< TSpace, 2 >, MetricAdjacency< TSpace, 1 >, 3 >
struct DigitalTopologyTraits< MetricAdjacency< TSpace, 3 >, MetricAdjacency< TSpace, 1 >, 3 >
class DiscreteExteriorCalculus
class DiscreteExteriorCalculusFactory
class DiscreteExteriorCalculusSolver
struct Display2DFactory
class Display3D
struct Display3DFactory
class DistanceBreadthFirstVisitor
class DistanceFromDCAEstimator
class DistanceFunctorFromPoint
class DistanceTransformation
class DomainAdjacency
struct DrawableWithBoard2D
struct DrawableWithBoard3DTo2D
struct DrawableWithDisplay3D
struct DrawWithBoard3DTo2DModifier
struct DrawWithBoardModifier
struct DrawWithDisplay3DModifier
struct DrawWithViewer3DModifier
class DSLSubsegment
class DSSLengthEstimator
struct DummyObject
struct DynamicBidirectionalSegmentComputer
struct DynamicSegmentComputer
class EigenDecomposition
struct EigenLinearAlgebraBackend
class Ellipse2D
class EstimatorCache
class EuclideanShapesCSG
class ExactPredicateLpPowerSeparableMetric
class ExactPredicateLpPowerSeparableMetric< TSpace, 2, TPromoted >
class ExactPredicateLpSeparableMetric
class ExactPredicateLpSeparableMetric< TSpace, 2, TRawValue >
class Expander
class ExplicitDigitalSurface
class Filtered2x2DetComputer
class Flower2D
class FMM
struct ForwardCategory
struct ForwardSegmentComputer
class FP
class FPLengthEstimator
class FrechetShortcut
class FreemanChain
class FrontInsertionSequenceToStackAdapter
class FunctorOnCells
class GaussDigitizer
struct GenericReader
struct GenericReader< TContainer, 2, DGtal::uint32_t >
struct GenericReader< TContainer, 2, TValue >
struct GenericReader< TContainer, 3, DGtal::uint32_t >
struct GenericReader< TContainer, 3, DGtal::uint64_t >
struct GenericReader< TContainer, 3, TValue >
struct GenericWriter
struct GenericWriter< TContainer, 2, DGtal::Color, TFunctor >
struct GenericWriter< TContainer, 2, TValue, HueShadeColorMap< TValue > >
struct GenericWriter< TContainer, 2, TValue, TFunctor >
struct GenericWriter< TContainer, 2, unsigned char, TFunctor >
struct GenericWriter< TContainer, 3, DGtal::uint64_t, TFunctor >
struct GenericWriter< TContainer, 3, TValue, TFunctor >
struct GenericWriter< TContainer, 3, unsigned char, TFunctor >
class GradientColorMap
class GraphVisitorRange
class GrayscaleColorMap
class GreedySegmentation
class GridCurve
struct H5DSpecializations
struct H5DSpecializations< TImageFactory, DGtal::int32_t >
struct H5DSpecializations< TImageFactory, DGtal::int64_t >
struct H5DSpecializations< TImageFactory, DGtal::uint8_t >
struct H5DSpecializations< TImageFactory, double >
class HalfEdgeDataStructure
struct HDF5Reader
struct HDF5Writer
class Histogram
class HueShadeColorMap
class HyperRectDomain
class HyperRectDomain_Iterator
class HyperRectDomain_subIterator
class Image
class ImageAdapter
class ImageCache
class ImageCacheReadPolicyFIFO
class ImageCacheReadPolicyLAST
class ImageCacheWritePolicyWB
class ImageCacheWritePolicyWT
class ImageContainerByITKImage
class ImageContainerBySTLMap
class ImageContainerBySTLVector
class ImageFactoryFromHDF5
class ImageFactoryFromImage
struct ImageFromSet
class ImageLinearCellEmbedder
struct ImageSelector
class ImageToConstantFunctor
class ImplicitBall
class ImplicitDigitalSurface
class ImplicitFunctionDiff1LinearCellEmbedder
class ImplicitFunctionDiff1LinearCellEmbedderGradientMap
class ImplicitFunctionLinearCellEmbedder
class ImplicitHyperCube
class ImplicitNorm1Ball
class ImplicitPolynomial3Shape
class ImplicitRoundedHyperCube
class IndexedDigitalSurface
class IndexedListWithBlocks
class InexactPredicateLpSeparableMetric
class InfiniteNumberException
class InGeneralizedDiskOfGivenRadius
class InHalfPlaneBy2x2DetComputer
class InHalfPlaneBySimple3x3Matrix
class InputException
class InputIteratorWithRankOnSequence
class IntegerComputer
class IntegerSequenceIterator
class IntegralInvariantCovarianceEstimator
class IntegralInvariantVolumeEstimator
struct IntersectionTargetTrait
class IOException
struct IsAssociativeContainer
struct IsCirculator
struct IsContainer
struct IsMultipleAssociativeContainer
struct IsOrderedAssociativeContainer
struct IsPairAssociativeContainer
struct IsSequenceContainer
struct IsSimpleAssociativeContainer
struct IsUniqueAssociativeContainer
struct IsUnorderedAssociativeContainer
class IteratorAdapter
struct IteratorCirculatorTraits
struct IteratorCirculatorTraits< T * >
struct IteratorCirculatorTraits< T const * >
struct IteratorCirculatorType
class IteratorCompletion
class IteratorCompletionTraits
class IteratorCompletionTraits< ArrayImageAdapter< TArrayIterator, TDomain > >
struct IteratorType
struct ITKIOTrait
struct ITKIOTrait< bool >
struct ITKReader
struct ITKWriter
class IVector
class IVector< T, TAlloc, true >
class KanungoNoise
class KForm
struct KhalimskyCell
struct KhalimskyPreCell
class KhalimskyPreSpaceND
class KhalimskySpaceND
class KhalimskySpaceNDHelper
class L1LengthEstimator
class L1LocalDistance
class L2FirstOrderLocalDistance
class L2FirstOrderLocalDistanceFromCells
class L2SecondOrderLocalDistance
class LabelledMap
class Labels
class LambdaMST2D
class LambdaMST2DEstimator
class LambdaMST3D
class LambdaMST3DEstimator
class LatticePolytope2D
class Lemniscate2D
class LighterSternBrocot
class LightExplicitDigitalSurface
class LightImplicitDigitalSurface
class LightSternBrocot
struct LinearAlgebra
struct Linearizer
struct Linearizer< HyperRectDomain< TSpace >, TStorageOrder >
class LinearOperator
class LInfLocalDistance
class LocalEstimatorFromSurfelFunctorAdapter
class LOG2
class LOG2< 1 >
class LOG2< 2 >
struct LongvolReader
struct LongvolWriter
struct MagickReader
struct MagickWriter
struct MapAssociativeCategory
class MeaningfulScaleAnalysis
class Measure
class MeasureOfStraightLines
class MelkmanConvexHull
class MemoryException
class Mesh
class MeshHelpers
struct MeshReader
class MeshVoxelizer
struct MeshWriter
class MetricAdjacency
class MLPLengthEstimator
class ModuloComputer
class Morton
class MostCenteredMaximalSegmentEstimator
class MPolynomial
class MPolynomial< 0, TRing, TAlloc >
class MPolynomialDerivativeComputer
class MPolynomialDerivativeComputer< 0, 0, Ring, Alloc >
class MPolynomialDerivativeComputer< 0, n, Ring, Alloc >
class MPolynomialDerivativeComputer< N, 0, Ring, Alloc >
class MPolynomialEvaluator
class MPolynomialEvaluator< 1, TRing, TAlloc, TX >
class MPolynomialEvaluatorImpl
class MPolynomialEvaluatorImpl< 1, TRing, TOwner, TAlloc, TX >
struct MPolynomialGrammar
class MPolynomialReader
struct MultimapAssociativeCategory
struct MultipleAssociativeCategory
struct MultisetAssociativeCategory
class MultiStatistics
class Naive3DDSSComputer
class NaiveDSL
class NaiveDSS8
class NaiveDSS8Computer
struct Negate
struct Negate< TagFalse >
struct Negate< TagTrue >
class NGon2D
class NormalFromDCAEstimator
class NormalVectorEstimatorLinearCellEmbedder
struct NotContainerCategory
struct NumberTraits
struct NumberTraits< double >
struct NumberTraits< float >
struct NumberTraits< int16_t >
struct NumberTraits< int32_t >
struct NumberTraits< int64_t >
struct NumberTraits< int8_t >
struct NumberTraits< long double >
struct NumberTraits< uint16_t >
struct NumberTraits< uint32_t >
struct NumberTraits< uint64_t >
struct NumberTraits< uint8_t >
class Object
class OneBalancedWordComputer
class OneItemOutputIterator
struct OpInSTLContainers
struct OpInSTLContainers< Container, std::reverse_iterator< typename Container::iterator > >
struct OppositeDuality
struct OppositeDuality< DUAL >
struct OppositeDuality< PRIMAL >
class OrderedAlphabet
struct OrderedAssociativeCategory
class OrderedLinearRegression
class OutputIteratorAdapter
class OwningOrAliasingPtr
struct PairAssociativeCategory
class ParallelStrip
class ParametricShapeArcLengthFunctor
class ParametricShapeCurvatureFunctor
class ParametricShapeTangentFunctor
class ParDirCollapse
class Pattern
struct PGMReader
struct PGMWriter
struct PointListReader
class PointVector
class PolygonalSurface
class POW
class POW< X, 0 >
class POW< X, 1 >
class PowerMap
struct PPMReader
struct PPMWriter
class PreCellDirectionIterator
class PredicateFromOrientationFunctor2
class Preimage2D
class Profile
struct promote_trait
struct promote_trait< int32_t, int64_t >
struct RandomAccessCategory
class RandomColorMap
struct RawReader
struct RawWriter
struct RayIntersectionPredicate
class RealFFT< HyperRectDomain< TSpace >, T >
struct ReducedMedialAxis
struct RegularBinner
class RegularPointEmbedder
class ReverseDistanceTransformation
class ReverseIterator
class RosenProffittLocalLengthEstimator
struct RowMajorStorage
class SaturatedSegmentation
struct SegmentComputerTraits
class SeparableMetricAdapter
struct SequenceCategory
struct SetAssociativeCategory
struct SetFromImage
struct SetMode
struct SetMode3D
struct SetName3D
class SetOfSurfels
struct SetSelectCallback3D
class SetValueIterator
class Shapes
class Signal
struct SignalData
struct SignedKhalimskyCell
struct SignedKhalimskyPreCell
class Simple2x2DetComputer
struct SimpleAssociativeCategory
class SimpleConstRange
class SimpleDistanceColorMap
class SimpleIncremental2x2DetComputer
class SimpleLinearRegression
class SimpleMatrix
struct SimpleMatrixSpecializations
struct SimpleMatrixSpecializations< TMatrix, 1, 1 >
struct SimpleMatrixSpecializations< TMatrix, 2, 2 >
struct SimpleMatrixSpecializations< TMatrix, 3, 3 >
class SimpleRandomAccessConstRangeFromPoint
class SimpleRandomAccessRangeFromPoint
class SpaceND
class SpatialCubicalSubdivision
class SpeedExtrapolator
class SphericalAccumulator
class StabbingCircleComputer
class StabbingLineComputer
class StandardDSL
class StandardDSLQ0
class StandardDSS4
class StandardDSS4Computer
class StandardDSS6Computer
class StarShaped2D
class StarShaped3D
class Statistic
struct StdMapRebinder
class SternBrocot
class STLMapToVertexMapAdapter
class StraightLineFrom2Points
struct Style2DFactory
class Surfaces
class SurfelAdjacency
class SurfelNeighborhood
struct TableReader
struct TagFalse
struct TagTrue
struct TagUnknown
class TangentAngleFromDSSEstimator
struct TangentFromBinomialConvolverFunctor
class TangentFromDCAEstimator
class TangentFromDSS2DFunctor
class TangentFromDSS3DFunctor
class TangentFromDSSEstimator
class TangentVectorFromDSSEstimator
class TickedColorMap
class TiledImage
class TiledImageBidirectionalConstRangeFromPoint
class TiledImageBidirectionalRangeFromPoint
struct ToDGtalCategory
struct ToDGtalCategory< boost::bidirectional_traversal_tag >
struct ToDGtalCategory< boost::forward_traversal_tag >
struct ToDGtalCategory< boost::iterators::detail::iterator_category_with_traversal< std::input_iterator_tag, boost::bidirectional_traversal_tag > >
struct ToDGtalCategory< boost::iterators::detail::iterator_category_with_traversal< std::input_iterator_tag, boost::forward_traversal_tag > >
struct ToDGtalCategory< boost::iterators::detail::iterator_category_with_traversal< std::input_iterator_tag, boost::random_access_traversal_tag > >
struct ToDGtalCategory< boost::random_access_traversal_tag >
struct ToDGtalCategory< std::bidirectional_iterator_tag >
struct ToDGtalCategory< std::forward_iterator_tag >
struct ToDGtalCategory< std::random_access_iterator_tag >
class Trace
class TraceWriter
class TraceWriterFile
class TraceWriterTerm
struct TransformedPrism
struct Translate2DDomain
class TriangulatedSurface
class TrueDigitalSurfaceLocalEstimator
class TrueGlobalEstimatorOnPoints
class TrueLocalEstimatorOnPoints
class TwoStepLocalLengthEstimator
class UmbrellaComputer
struct UniqueAssociativeCategory
struct UnorderedAssociativeCategory
struct UnorderedMapAssociativeCategory
struct UnorderedMultimapAssociativeCategory
struct UnorderedMultisetAssociativeCategory
struct UnorderedSetAssociativeCategory
struct Update2DDomainPosition
struct UpdateImage3DEmbedding
struct UpdateImageData
struct UpdateImagePosition
struct UpdateLastImagePosition
class VCMDigitalSurfaceLocalEstimator
class VectorField
class Viewer3D
struct Viewer3DFactory
struct VolReader
struct VolWriter
class VoronoiCovarianceMeasure
class VoronoiCovarianceMeasureOnDigitalSurface
class VoronoiMap
class VoxelComplex
class Warning_promote_trait_not_specialized_for_this_case
class Xe_kComputer
class Xe_kComputer< 0, Ring, Alloc >
Typedefs
typedef boost::uint8_t uint8_t
typedef boost::uint16_t uint16_t
typedef boost::uint32_t uint32_t
typedef boost::uint64_t uint64_t
typedef boost::int8_t int8_t
typedef boost::int16_t int16_t
typedef boost::int32_t int32_t
typedef boost::int64_t int64_t
typedef mpz_class BigInteger
typedef DGtal::uint32_t Dimension
typedef unsigned int Order
using NeighborhoodConfiguration = uint32_t
Enumerations
enum Orientation { INSIDE = 0, ON = 1, OUTSIDE = 2 }
enum Closest { ClosestFIRST = 0, ClosestSECOND = 1, ClosestBOTH = 2 }
enum Duality { PRIMAL = 0, DUAL = 1 }
enum Surfel2PointEmbedding { Pointels = 0, InnerSpel = 1, OuterSpel = 2 }
enum ImageIterability { HIGH_ITER_IMAGE = 0, LOW_ITER_I = 1 }
enum ImageBelongTestability { HIGH_BEL_I = 0, LOW_BEL_I = 2 }
enum ImageSpecificContainer { NORMAL_CONTAINER_I = 0, VTKIMAGEDATA_CONTAINER_I = 4 }
enum DomainDrawMode { GRID = 0, PAVING = 1 }
enum ColorGradientPreset {
CMAP_CUSTOM = 0, CMAP_GRAYSCALE, CMAP_SPRING, CMAP_SUMMER,
CMAP_AUTUMN, CMAP_WINTER, CMAP_COOL, CMAP_COPPER,
CMAP_HOT, CMAP_JET
}
enum BoundEnum { BOUNDED = 0, UNBOUNDED = 1, BOUND_UNKNOWN = 2 }
enum SignEnum { SIGNED = 0, UNSIGNED = 1, SIGN_UNKNOWN = 2 }
enum DigitalSetSize { SMALL_DS = 0, MEDIUM_DS = 1, BIG_DS = 2, WHOLE_DS = 3 }
enum DigitalSetVariability { LOW_VAR_DS = 0, HIGH_VAR_DS = 4 }
enum DigitalSetIterability { LOW_ITER_DS = 0, HIGH_ITER_DS = 8 }
enum DigitalSetBelongTestability { LOW_BEL_DS = 0, HIGH_BEL_DS = 16 }
enum DigitalTopologyProperties { UNKNOWN_DT = 0, NOT_JORDAN_DT = 1, JORDAN_DT = 2 }
enum Connectedness { DISCONNECTED = 0, CONNECTED = 1, UNKNOWN = 2 }
Functions
std::ostream & operator<< (std::ostream &out, const ATu0v1< TKSpace, TLinearAlgebra > &object)
std::ostream & operator<< (std::ostream &out, const ATu2v0< TKSpace, TLinearAlgebra > &object)
template<typename TSpace >
std::ostream & operator<< (std::ostream &out, const ClosedIntegerHalfPlane< TSpace > &object)
template<typename TInteger >
std::ostream & operator<< (std::ostream &out, const IntegerComputer< TInteger > &object)
template<typename TSpace , typename TSequence >
std::ostream & operator<< (std::ostream &out, const LatticePolytope2D< TSpace, TSequence > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const ModuloComputer< T > &object)
template<typename TFraction >
std::ostream & operator<< (std::ostream &out, const Pattern< TFraction > &object)
template<typename TFraction >
std::ostream & operator<< (std::ostream &out, const StandardDSLQ0< TFraction > &object)
void assert_failed (const std::string &expr, const std::string &function, const std::string &file, long int line)
void assert_failed_message (const std::string &expr, const std::string &message, const std::string &function, const std::string &file, long int line)
void fatal_error_failed (const std::string &expr, const std::string &function, const std::string &file, long int line)
void fatal_error_failed_message (const std::string &expr, const std::string &message, const std::string &function, const std::string &file, long int line)
template<typename TSequence >
std::ostream & operator<< (std::ostream &out, const BackInsertionSequenceToStackAdapter< TSequence > &object)
template<typename TSequence >
BackInsertionSequenceToStackAdapter< TSequence > backStack (TSequence &aSequence)
template<typename TIterator >
Circulator< TIterator > operator+ (typename IteratorCirculatorTraits< TIterator >::Difference d, Circulator< TIterator > &object)
std::ostream & operator<< (std::ostream &out, const Clock &object)
Trace trace (traceWriterTerm)
template<typename TIterator , typename TFunctor , typename TReturnType >
std::ostream & operator<< (std::ostream &out, const ConstRangeAdapter< TIterator, TFunctor, TReturnType > &object)
template<typename A , typename B >
std::ostream & operator<< (std::ostream &out, const std::pair< A, B > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const CountedConstPtrOrConstPtr< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const CountedPtr< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const CountedPtrOrPtr< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const CowPtr< T > &object)
template<typename TSequence >
std::ostream & operator<< (std::ostream &out, const FrontInsertionSequenceToStackAdapter< TSequence > &object)
template<typename TSequence >
FrontInsertionSequenceToStackAdapter< TSequence > frontStack (TSequence &aSequence)
template<typename TValue , unsigned int N, unsigned int M>
std::ostream & operator<< (std::ostream &out, const IndexedListWithBlocks< TValue, N, M > &object)
template<typename TSequence , typename TRank >
std::ostream & operator<< (std::ostream &out, const InputIteratorWithRankOnSequence< TSequence, TRank > &object)
template<typename IC >
bool isEmpty (const IC &itb, const IC &ite)
template<typename IC >
bool isNotEmpty (const IC &itb, const IC &ite)
template<typename IC >
void advanceIterator (IC &ic, typename IteratorCirculatorTraits< IC >::Difference n)
template<typename IC >
IteratorCirculatorTraits< IC >::Difference rangeSize (const IC &itb, const IC &ite)
template<typename IC >
IteratorCirculatorTraits< IC >::Difference subRangeSize (const IC &itb, const IC &ite)
template<typename IC >
IC rangeMiddle (const IC &itb, const IC &ite)
template<typename IC >
IC subRangeMiddle (const IC &itb, const IC &ite)
template<typename TData , unsigned int L, typename TWord , unsigned int N, unsigned int M>
std::ostream & operator<< (std::ostream &out, const LabelledMap< TData, L, TWord, N, M > &object)
template<unsigned int L, typename TWord >
std::ostream & operator<< (std::ostream &out, const Labels< L, TWord > &object)
std::ostream & operator<< (std::ostream &out, const OrderedAlphabet &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const OwningOrAliasingPtr< T > &object)
std::ostream & operator<< (std::ostream &out, const Trace &object)
std::ostream & operator<< (std::ostream &out, const TraceWriter &object)
std::ostream & operator<< (std::ostream &out, const TraceWriterFile &object)
std::ostream & operator<< (std::ostream &out, const TraceWriterTerm &object)
template<Dimension dim, typename TInteger >
size_t hash_value (const KhalimskyCell< dim, TInteger > &cell)
template<Dimension dimEmbedded, Dimension dimAmbient, typename TLinearAlgebraBackend , typename TInteger >
std::ostream & operator<< (std::ostream &out, const DiscreteExteriorCalculus< dimEmbedded, dimAmbient, TLinearAlgebraBackend, TInteger > &object)
template<typename C , typename S , Order order_in, Duality duality_in, Order order_out, Duality duality_out>
std::ostream & operator<< (std::ostream &out, const DiscreteExteriorCalculusSolver< C, S, order_in, duality_in, order_out, duality_out > &object)
std::ostream & operator<< (std::ostream &out, const Duality &object)
template<typename Calculus , Order order, Duality duality>
std::ostream & operator<< (std::ostream &out, const KForm< Calculus, order, duality > &object)
template<typename Calculus , Order order, Duality duality>
KForm< Calculus, order, duality > operator+ (const KForm< Calculus, order, duality > &form_a, const KForm< Calculus, order, duality > &form_b)
template<typename Calculus , Order order, Duality duality>
KForm< Calculus, order, duality > operator- (const KForm< Calculus, order, duality > &form_a, const KForm< Calculus, order, duality > &form_b)
template<typename Calculus , Order order, Duality duality>
KForm< Calculus, order, duality > operator* (const typename Calculus::Scalar &scalar, const KForm< Calculus, order, duality > &form)
template<typename Calculus , Order order, Duality duality>
KForm< Calculus, order, duality > operator- (const KForm< Calculus, order, duality > &form)
template<typename Calculus , Order order_in, Duality duality_in, Order order_out, Duality duality_out>
std::ostream & operator<< (std::ostream &out, const LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > &object)
template<typename Calculus , Order order_in, Duality duality_in, Order order_out, Duality duality_out>
LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > operator+ (const LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > &linear_operator_a, const LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > &linear_operator_b)
template<typename Calculus , Order order_in, Duality duality_in, Order order_out, Duality duality_out>
LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > operator- (const LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > &linear_operator_a, const LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > &linear_operator_b)
template<typename Calculus , Order order_in, Duality duality_in, Order order_out, Duality duality_out>
LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > operator* (const typename Calculus::Scalar &scalar, const LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > &linear_operator)
template<typename Calculus , Order order_in, Duality duality_in, Order order_fold, Duality duality_fold, Order order_out, Duality duality_out>
LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > operator* (const LinearOperator< Calculus, order_fold, duality_fold, order_out, duality_out > &operator_left, const LinearOperator< Calculus, order_in, duality_in, order_fold, duality_fold > &operator_right)
template<typename Calculus , Order order_in, Duality duality_in, Order order_out, Duality duality_out>
KForm< Calculus, order_out, duality_out > operator* (const LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > &linear_operator, const KForm< Calculus, order_in, duality_in > &input_form)
template<typename Calculus , Order order_in, Duality duality_in, Order order_out, Duality duality_out>
LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > operator- (const LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > &linear_operator)
template<typename Calculus , Duality duality>
std::ostream & operator<< (std::ostream &out, const VectorField< Calculus, duality > &object)
template<typename Calculus , Duality duality>
VectorField< Calculus, duality > operator+ (const VectorField< Calculus, duality > &vector_field_a, const VectorField< Calculus, duality > &vector_field_b)
template<typename Calculus , Duality duality>
VectorField< Calculus, duality > operator- (const VectorField< Calculus, duality > &vector_field_a, const VectorField< Calculus, duality > &vector_field_b)
template<typename Calculus , Duality duality>
VectorField< Calculus, duality > operator* (const typename Calculus::Scalar &scalar, const VectorField< Calculus, duality > &vector_field)
template<typename Calculus , Duality duality>
VectorField< Calculus, duality > operator- (const VectorField< Calculus, duality > &vector_field)
template<typename TInputPoint , typename TConstIterator >
std::ostream & operator<< (std::ostream &out, const AlphaThickSegmentComputer< TInputPoint, TConstIterator > &object)
template<typename TCoordinate , typename TInteger , unsigned short adjacency>
std::ostream & operator<< (std::ostream &out, const ArithmeticalDSL< TCoordinate, TInteger, adjacency > &object)
template<typename TCoordinate , typename TInteger , unsigned short adjacency>
std::ostream & operator<< (std::ostream &out, const ArithmeticalDSS< TCoordinate, TInteger, adjacency > &object)
template<typename TIterator , typename TInteger , unsigned short adjacency>
std::ostream & operator<< (std::ostream &out, const ArithmeticalDSSComputer< TIterator, TInteger, adjacency > &object)
template<typename TConstIteratorOnPoints , typename TValue >
std::ostream & operator<< (std::ostream &out, const BinomialConvolver< TConstIteratorOnPoints, TValue > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const BLUELocalLengthEstimator< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const DSSLengthEstimator< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const FPLengthEstimator< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const L1LengthEstimator< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const MLPLengthEstimator< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const RosenProffittLocalLengthEstimator< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const TwoStepLocalLengthEstimator< T > &object)
template<typename TIterator , typename TInteger , int connectivity>
std::ostream & operator<< (std::ostream &out, const FP< TIterator, TInteger, connectivity > &object)
template<typename TIterator , typename TInteger >
std::ostream & operator<< (std::ostream &out, const FrechetShortcut< TIterator, TInteger > &object)
template<typename TInteger >
std::ostream & operator<< (std::ostream &out, const FreemanChain< TInteger > &object)
template<typename SegmentComputer >
std::ostream & operator<< (std::ostream &out, const GreedySegmentation< SegmentComputer > &object)
template<typename TKSpace >
std::ostream & operator<< (std::ostream &out, const GridCurve< TKSpace > &object)
template<typename TConstIterator , typename TInteger >
std::ostream & operator<< (std::ostream &out, const OneBalancedWordComputer< TConstIterator, TInteger > &object)
template<typename SegmentComputer >
std::ostream & operator<< (std::ostream &out, const SaturatedSegmentation< SegmentComputer > &object)
template<typename IC >
IC getMiddleIterator (const IC &itb, const IC &ite, RandomAccessCategory)
template<typename IC >
IC getMiddleIterator (const IC &itb, const IC &ite, BidirectionalCategory)
template<typename IC >
IC getMiddleIterator (const IC &itb, const IC &ite, ForwardCategory)
template<typename IC >
IC getMiddleIterator (const IC &itb, const IC &ite)
template<typename SC >
void maximalExtension (SC &s, const typename SC::ConstIterator &end, IteratorType)
template<typename SC >
void maximalExtension (SC &s, const typename SC::ConstIterator &, CirculatorType)
template<typename SC >
void maximalExtension (SC &s, const typename SC::ConstIterator &end)
template<typename SC >
void oppositeEndMaximalExtension (SC &s, const typename SC::ConstIterator &begin, IteratorType)
template<typename SC >
void oppositeEndMaximalExtension (SC &s, const typename SC::ConstIterator &begin, CirculatorType)
template<typename SC >
void oppositeEndMaximalExtension (SC &s, const typename SC::ConstIterator &begin)
template<typename SC >
bool maximalSymmetricExtension (SC &s, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end, IteratorType)
template<typename SC >
bool maximalSymmetricExtension (SC &s, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end, CirculatorType)
template<typename SC >
bool maximalSymmetricExtension (SC &s, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end)
template<typename SC >
void maximalRetraction (SC &s, const typename SC::ConstIterator &end)
template<typename SC >
void oppositeEndMaximalRetraction (SC &s, const typename SC::ConstIterator &begin)
template<typename SC >
void longestSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &end, IteratorType)
template<typename SC >
void longestSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &end, CirculatorType)
template<typename SC >
void longestSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &end)
template<typename SC >
void firstMaximalSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end, DGtal::ForwardSegmentComputer)
template<typename SC >
void firstMaximalSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end, DGtal::BidirectionalSegmentComputer)
template<typename SC >
void firstMaximalSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end, DGtal::DynamicSegmentComputer)
template<typename SC >
void firstMaximalSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end, DGtal::DynamicBidirectionalSegmentComputer)
template<typename SC >
void firstMaximalSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end)
template<typename SC >
void mostCenteredMaximalSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end, DGtal::ForwardSegmentComputer)
template<typename SC >
void mostCenteredMaximalSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end, DGtal::BidirectionalSegmentComputer)
template<typename SC >
void mostCenteredMaximalSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end, DGtal::DynamicSegmentComputer)
template<typename SC >
void mostCenteredMaximalSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end, DGtal::DynamicBidirectionalSegmentComputer)
template<typename SC >
void mostCenteredMaximalSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end)
template<typename SC >
void lastMaximalSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end, DGtal::ForwardSegmentComputer)
template<typename SC >
void lastMaximalSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end, BidirectionalSegmentComputer)
template<typename SC >
void lastMaximalSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end, DGtal::DynamicSegmentComputer)
template<typename SC >
void lastMaximalSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end, DGtal::DynamicBidirectionalSegmentComputer)
template<typename SC >
void lastMaximalSegment (SC &s, const typename SC::ConstIterator &i, const typename SC::ConstIterator &begin, const typename SC::ConstIterator &end)
template<typename SC >
void nextMaximalSegment (SC &s, const typename SC::ConstIterator &end, DGtal::ForwardSegmentComputer)
template<typename SC >
void nextMaximalSegment (SC &s, const typename SC::ConstIterator &end, DGtal::BidirectionalSegmentComputer)
template<typename SC >
void nextMaximalSegment (SC &s, const typename SC::ConstIterator &end, DGtal::DynamicSegmentComputer)
template<typename SC >
void nextMaximalSegment (SC &s, const typename SC::ConstIterator &end, DGtal::DynamicBidirectionalSegmentComputer)
template<typename SC >
void nextMaximalSegment (SC &s, const typename SC::ConstIterator &end)
template<typename SC >
void previousMaximalSegment (SC &s, const typename SC::ConstIterator &begin, DGtal::ForwardSegmentComputer)
template<typename SC >
void previousMaximalSegment (SC &s, const typename SC::ConstIterator &begin, DGtal::BidirectionalSegmentComputer)
template<typename SC >
void previousMaximalSegment (SC &s, const typename SC::ConstIterator &begin, DGtal::DynamicSegmentComputer)
template<typename SC >
void previousMaximalSegment (SC &s, const typename SC::ConstIterator &end, DGtal::DynamicBidirectionalSegmentComputer)
template<typename SC >
void previousMaximalSegment (SC &s, const typename SC::ConstIterator &begin)
template<typename TConstIterator >
std::ostream & operator<< (std::ostream &out, const StabbingCircleComputer< TConstIterator > &object)
template<typename TConstIterator >
std::ostream & operator<< (std::ostream &out, const StabbingLineComputer< TConstIterator > &object)
template<typename TIterator , typename TInteger , int connectivity>
std::ostream & operator<< (std::ostream &out, const StandardDSS6Computer< TIterator, TInteger, connectivity > &object)
std::ostream & operator<< (std::ostream &out, const ContourHelper &object)
template<typename TSpace , typename TInputPoint , typename TInternalScalar >
std::ostream & operator<< (std::ostream &out, const ChordGenericNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar > &object)
template<typename TSpace , typename TInputPoint , typename TInternalScalar >
std::ostream & operator<< (std::ostream &out, const ChordGenericStandardPlaneComputer< TSpace, TInputPoint, TInternalScalar > &object)
template<typename TSpace , typename TInputPoint , typename TInternalScalar >
std::ostream & operator<< (std::ostream &out, const ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar > &object)
template<typename TSpace , typename TInternalInteger >
std::ostream & operator<< (std::ostream &out, const COBAGenericNaivePlaneComputer< TSpace, TInternalInteger > &object)
template<typename TSpace , typename TInternalInteger >
std::ostream & operator<< (std::ostream &out, const COBAGenericStandardPlaneComputer< TSpace, TInternalInteger > &object)
template<typename TSpace , typename TInternalInteger >
std::ostream & operator<< (std::ostream &out, const COBANaivePlaneComputer< TSpace, TInternalInteger > &object)
template<typename TF , typename TKF , typename TKS , typename TDK , Dimension dimension>
std::ostream & operator<< (std::ostream &out, const DGtal::DigitalSurfaceConvolver< TF, TKF, TKS, TDK, dimension > &object)
template<typename TF , typename TKF , typename TKS , typename TDK >
std::ostream & operator<< (std::ostream &out, const DGtal::DigitalSurfaceConvolver< TF, TKF, TKS, TDK, 2 > &object)
template<typename TF , typename TKF , typename TKS , typename TDK >
std::ostream & operator<< (std::ostream &out, const DGtal::DigitalSurfaceConvolver< TF, TKF, TKS, TDK, 3 > &object)
template<typename TDigitalSurfaceEmbedder , typename TNormalVectorEstimator >
std::ostream & operator<< (std::ostream &out, const DigitalSurfaceEmbedderWithNormalVectorEstimator< TDigitalSurfaceEmbedder, TNormalVectorEstimator > &object)
template<typename T , typename TC >
std::ostream & operator<< (std::ostream &out, const EstimatorCache< T, TC > &object)
template<typename TKSpace , typename TPointPredicate , typename TCovarianceMatrixFunctor >
std::ostream & operator<< (std::ostream &out, const IntegralInvariantCovarianceEstimator< TKSpace, TPointPredicate, TCovarianceMatrixFunctor > &object)
template<typename TKSpace , typename TPointPredicate >
std::ostream & operator<< (std::ostream &out, const DGtal::deprecated::IntegralInvariantNormalVectorEstimator< TKSpace, TPointPredicate > &object)
template<typename TKSpace , typename TPointPredicate , typename TVolumeFunctor >
std::ostream & operator<< (std::ostream &out, const IntegralInvariantVolumeEstimator< TKSpace, TPointPredicate, TVolumeFunctor > &object)
template<typename TD , typename TV , typename TF , typename TC >
std::ostream & operator<< (std::ostream &out, const LocalEstimatorFromSurfelFunctorAdapter< TD, TV, TF, TC > &object)
template<typename TDigitalSurface , typename TNormalVectorEstimator , typename TEmbedder >
std::ostream & operator<< (std::ostream &out, const NormalVectorEstimatorLinearCellEmbedder< TDigitalSurface, TNormalVectorEstimator, TEmbedder > &object)
template<typename TKSpace , typename TShape , typename TGeometricFunctor >
std::ostream & operator<< (std::ostream &out, const TrueDigitalSurfaceLocalEstimator< TKSpace, TShape, TGeometricFunctor > &object)
template<typename TDigitalSurfaceContainer , typename TSeparableMetric , typename TKernelFunction , typename TVCMGeometricFunctor >
std::ostream & operator<< (std::ostream &out, const VCMDigitalSurfaceLocalEstimator< TDigitalSurfaceContainer, TSeparableMetric, TKernelFunction, TVCMGeometricFunctor > &object)
template<typename TDigitalSurfaceContainer , typename TSeparableMetric , typename TKernelFunction >
std::ostream & operator<< (std::ostream &out, const VoronoiCovarianceMeasureOnDigitalSurface< TDigitalSurfaceContainer, TSeparableMetric, TKernelFunction > &object)
template<typename TF , typename TKS >
std::ostream & operator<< (std::ostream &out, const FunctorOnCells< TF, TKS > &object)
template<typename TSpace , bool muIncluded, bool muPlusNuIncluded>
std::ostream & operator<< (std::ostream &out, const ParallelStrip< TSpace, muIncluded, muPlusNuIncluded > &object)
template<typename TInteger >
std::ostream & operator<< (std::ostream &out, const AvnaimEtAl2x2DetSignComputer< TInteger > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const Filtered2x2DetComputer< T > &object)
template<typename TPoint , typename TDetComputer >
std::ostream & operator<< (std::ostream &out, const InGeneralizedDiskOfGivenRadius< TPoint, TDetComputer > &object)
template<typename TPoint , typename TDetComputer >
std::ostream & operator<< (std::ostream &out, const InHalfPlaneBy2x2DetComputer< TPoint, TDetComputer > &object)
template<typename TPoint , typename TInteger >
std::ostream & operator<< (std::ostream &out, const InHalfPlaneBySimple3x3Matrix< TPoint, TInteger > &object)
template<typename TOrientationFunctor , bool acceptNeg, bool acceptZero>
std::ostream & operator<< (std::ostream &out, const PredicateFromOrientationFunctor2< TOrientationFunctor, acceptNeg, acceptZero > &object)
template<typename TI , typename TO >
std::ostream & operator<< (std::ostream &out, const Simple2x2DetComputer< TI, TO > &object)
template<typename TI , typename TO >
std::ostream & operator<< (std::ostream &out, const SimpleIncremental2x2DetComputer< TI, TO > &object)
template<typename TPoint , typename TOrientationFunctor >
std::ostream & operator<< (std::ostream &out, const MelkmanConvexHull< TPoint, TOrientationFunctor > &object)
template<typename Shape >
std::ostream & operator<< (std::ostream &out, const Preimage2D< Shape > &object)
template<typename TSpace >
std::ostream & operator<< (std::ostream &out, const SpatialCubicalSubdivision< TSpace > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const SphericalAccumulator< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const experimental::ChamferNorm2D< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const DigitalMetricAdapter< T > &object)
template<typename S , typename P , typename TSep >
std::ostream & operator<< (std::ostream &out, const DistanceTransformation< S, P, TSep > &object)
template<typename T , DGtal::uint32_t p, typename P >
std::ostream & operator<< (std::ostream &out, const ExactPredicateLpPowerSeparableMetric< T, p, P > &object)
template<typename T , DGtal::uint32_t p, typename P >
std::ostream & operator<< (std::ostream &out, const ExactPredicateLpSeparableMetric< T, p, P > &object)
template<typename TImage , typename TSet , typename TPointPredicate , typename TPointFunctor >
std::ostream & operator<< (std::ostream &out, const FMM< TImage, TSet, TPointPredicate, TPointFunctor > &object)
template<typename T , typename V >
std::ostream & operator<< (std::ostream &out, const InexactPredicateLpSeparableMetric< T, V > &object)
template<typename W , typename Sep , typename Image >
std::ostream & operator<< (std::ostream &out, const PowerMap< W, Sep, Image > &object)
template<typename W , typename TSep >
std::ostream & operator<< (std::ostream &out, const ReverseDistanceTransformation< W, TSep > &object)
template<typename TM >
std::ostream & operator<< (std::ostream &out, const SeparableMetricAdapter< TM > &object)
template<typename S , typename P , typename Sep , typename TI >
std::ostream & operator<< (std::ostream &out, const VoronoiMap< S, P, Sep, TI > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const Measure< T > &object)
template<typename TSpace , typename TSeparableMetric >
std::ostream & operator<< (std::ostream &out, const VoronoiCovarianceMeasure< TSpace, TSeparableMetric > &object)
template<typename TO , typename TD , typename TS >
std::ostream & operator<< (std::ostream &out, const KanungoNoise< TO, TD, TS > &object)
template<typename TGraph , typename TMarkSet >
std::ostream & operator<< (std::ostream &out, const BreadthFirstVisitor< TGraph, TMarkSet > &object)
template<typename TGraph , typename TMarkSet >
std::ostream & operator<< (std::ostream &out, const DepthFirstVisitor< TGraph, TMarkSet > &object)
template<typename TGraph , typename TVertexFunctor , typename TMarkSet >
std::ostream & operator<< (std::ostream &out, const DistanceBreadthFirstVisitor< TGraph, TVertexFunctor, TMarkSet > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const Expander< T > &object)
template<typename TGraphVisitor >
std::ostream & operator<< (std::ostream &out, const GraphVisitorRange< TGraphVisitor > &object)
template<typename TArrayIterator , typename TDomain >
std::ostream & operator<< (std::ostream &out, const ArrayImageAdapter< TArrayIterator, TDomain > &object)
template<typename TArrayIterator , typename TDomain >
ArrayImageAdapter< TArrayIterator, TDomain > makeArrayImageAdapterFromIterator (TArrayIterator anArrayIterator, TDomain const &aFullDomain, TDomain const &aViewDomain)
template<typename TArrayIterator , typename TDomain >
ArrayImageAdapter< TArrayIterator, TDomain > makeArrayImageAdapterFromIterator (TArrayIterator anArrayIterator, TDomain const &aFullDomain)
template<typename TImage , typename TDomain = typename TImage::Domain>
ArrayImageAdapter< decltype(((TImage *) nullptr) ->begin()), TDomain > makeArrayImageAdapterFromImage (TImage &anImage, TDomain const &aViewDomain)
template<typename TImage , typename TDomain = typename TImage::Domain>
ArrayImageAdapter< decltype(((TImage *) nullptr) ->begin()), TDomain > makeArrayImageAdapterFromImage (TImage &anImage)
template<typename TIterableClass >
std::ostream & operator<< (std::ostream &out, const ArrayImageIterator< TIterableClass > &object)
template<typename TImageContainer , typename TNewDomain , typename TFunctorD , typename TNewValue , typename TFunctorV >
std::ostream & operator<< (std::ostream &out, const ConstImageAdapter< TImageContainer, TNewDomain, TFunctorD, TNewValue, TFunctorV > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const Image< T > &object)
template<typename TImageContainer , typename TNewDomain , typename TFunctorD , typename TNewValue , typename TFunctorV , typename TFunctorVm1 >
std::ostream & operator<< (std::ostream &out, const ImageAdapter< TImageContainer, TNewDomain, TFunctorD, TNewValue, TFunctorV, TFunctorVm1 > &object)
template<typename TImageContainer , typename TImageFactory , typename TReadPolicy , typename TWritePolicy >
std::ostream & operator<< (std::ostream &out, const ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy > &object)
template<typename T , typename TV >
std::ostream & operator<< (std::ostream &out, const ImageContainerByITKImage< T, TV > &object)
template<typename TDomain , typename TValue >
std::ostream & operator<< (std::ostream &out, const ImageContainerBySTLMap< TDomain, TValue > &object)
template<typename Domain , typename V >
std::ostream & operator<< (std::ostream &out, const ImageContainerBySTLVector< Domain, V > &object)
template<typename TImageContainer >
std::ostream & operator<< (std::ostream &out, const ImageFactoryFromHDF5< TImageContainer > &object)
template<typename TImageContainer >
std::ostream & operator<< (std::ostream &out, const ImageFactoryFromImage< TImageContainer > &object)
template<typename I , typename O , typename P >
void setFromPointsRangeAndPredicate (const I &itb, const I &ite, const O &ito, const P &aPred)
template<typename I , typename O , typename F >
void setFromPointsRangeAndFunctor (const I &itb, const I &ite, const O &ito, const F &aFunctor, const typename F::Value &aThreshold=0)
template<typename I , typename O >
void setFromImage (const I &aImg, const O &ito, const typename I::Value &aThreshold=0)
template<typename I , typename O >
void setFromImage (const I &aImg, const O &ito, const typename I::Value &low, const typename I::Value &up)
template<typename It , typename Im >
void imageFromRangeAndValue (const It &itb, const It &ite, Im &aImg, const typename Im::Value &aValue=0)
template<typename R , typename I >
void imageFromRangeAndValue (const R &aRange, I &aImg, const typename I::Value &aValue=0)
template<typename I , typename F >
void imageFromFunctor (I &aImg, const F &aFun)
template<typename I1 , typename I2 >
void imageFromImage (I1 &aImg1, const I2 &aImg2)
template<typename I , typename S >
bool insertAndSetValue (I &aImg, S &aSet, const typename I::Point &aPoint, const typename I::Value &aValue)
template<typename I , typename S >
bool insertAndAlwaysSetValue (I &aImg, S &aSet, const typename I::Point &aPoint, const typename I::Value &aValue)
template<typename I , typename S >
bool findAndGetValue (const I &aImg, const S &aSet, const typename I::Point &aPoint, typename I::Value &aValue)
template<typename TKSpace , typename TImage , typename TEmbedder >
std::ostream & operator<< (std::ostream &out, const ImageLinearCellEmbedder< TKSpace, TImage, TEmbedder > &object)
template<typename TImageContainer , typename TImageFactory , typename TImageCacheReadPolicy , typename TImageCacheWritePolicy >
std::ostream & operator<< (std::ostream &out, const TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy > &object)
std::ostream & operator<< (std::ostream &out, const Board2D &object)
template<typename Space , typename KSpace >
std::ostream & operator<< (std::ostream &out, const Board3D< Space, KSpace > &object)
template<typename Space , typename KSpace >
std::ostream & operator<< (std::ostream &out, const Board3DTo2D< Space, KSpace > &object)
Color operator* (const double coeff, const Color &aColor)
std::ostream & operator<< (std::ostream &out, const Color &aColor)
template<typename PValue , int PDefaultColor>
std::ostream & operator<< (std::ostream &out, const ColorBrightnessColorMap< PValue, PDefaultColor > &object)
template<typename PValue , int PDefaultPreset, int PDefaultFirstColor, int PDefaultLastColor>
std::ostream & operator<< (std::ostream &out, const GradientColorMap< PValue, PDefaultPreset, PDefaultFirstColor, PDefaultLastColor > &object)
template<typename PValue >
std::ostream & operator<< (std::ostream &out, const GrayscaleColorMap< PValue > &object)
template<typename PValue , int DefaultCycles>
std::ostream & operator<< (std::ostream &out, const HueShadeColorMap< PValue, DefaultCycles > &object)
std::ostream & operator<< (std::ostream &out, const RandomColorMap &object)
template<typename TValue , typename CMAP >
std::ostream & operator<< (std::ostream &out, const TickedColorMap< TValue, CMAP > &object)
template<typename Space , typename KSpace >
std::ostream & operator<< (std::ostream &out, const DGtal::Display3D< Space, KSpace > &object)
template<typename Space , typename KSpace >
void operator>> (const Display3D< Space, KSpace > &aDisplay3D, DGtal::Mesh< typename Display3D< Space, KSpace >::RealPoint > &aMesh)
template<typename Space , typename KSpace >
void operator>> (const Display3D< Space, KSpace > &aDisplay3D, std::string aFilename)
template<typename TPoint >
bool operator<< (Mesh< TPoint > &mesh, const std::string &filename)
template<int n, typename TRing , typename TAlloc , typename TIterator >
std::ostream & operator<< (std::ostream &out, const MPolynomialReader< n, TRing, TAlloc, TIterator > &object)
template<int n, typename TRing , class TAlloc >
std::istream & operator>> (std::istream &in, MPolynomial< n, TRing, TAlloc > &aMPolynomial)
template<typename Word >
FILE * raw_reader_read_word (FILE *fin, Word &aValue)
template<typename TSpace , typename TKSpace >
std::ostream & operator<< (std::ostream &out, const Viewer3D< TSpace, TKSpace > &object)
template<typename TImageContainer >
bool operator>> (const TImageContainer &aContainer, const std::string &aFilename)
template<typename TPoint >
bool operator>> (Mesh< TPoint > &aMesh, const std::string &aFilename)
template<typename TPoint >
bool operator>> (Mesh< TPoint > &aMesh, std::ostream &out)
template<typename Word >
std::ostream & raw_writer_write_word (std::ostream &outs, Word value)
template<typename TSpace >
std::ostream & operator<< (std::ostream &out, const CanonicEmbedder< TSpace > &object)
template<typename TSpace >
std::ostream & operator<< (std::ostream &out, const HyperRectDomain< TSpace > &object)
template<Dimension dim, typename Container >
std::bitset< dim > setDimensionsIn (const Container &dimensions)
template<Dimension dim, typename Container >
std::bitset< dim > setDimensionsNotIn (const Container &dimensions)
template<Dimension dim, typename Component , typename TC >
std::ostream & operator<< (std::ostream &out, const PointVector< dim, Component, TC > &object)
template<Dimension dim, typename Component , typename Container >
PointVector< dim, Component, Container > operator* (Component coeff, const PointVector< dim, Component, Container > &aVector)
template<typename TSpace >
std::ostream & operator<< (std::ostream &out, const RegularPointEmbedder< TSpace > &object)
template<typename Domain , typename Container >
std::ostream & operator<< (std::ostream &out, const DigitalSetByAssociativeContainer< Domain, Container > &object)
template<typename Domain , typename Compare >
std::ostream & operator<< (std::ostream &out, const DigitalSetBySTLSet< Domain, Compare > &object)
template<typename Domain >
std::ostream & operator<< (std::ostream &out, const DigitalSetBySTLVector< Domain > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const DigitalSetDomain< T > &object)
template<typename TMapImage >
std::ostream & operator<< (std::ostream &out, const DigitalSetFromMap< TMapImage > &object)
std::ostream & operator<< (std::ostream &out, const AngleLinearMinimizer &object)
template<typename TQuantity , typename TBinner >
std::ostream & operator<< (std::ostream &out, const Histogram< TQuantity, TBinner > &object)
std::ostream & operator<< (std::ostream &os, const Eigen::ComputationInfo &info)
template<typename T , DGtal::Dimension M, DGtal::Dimension N>
std::ostream & operator<< (std::ostream &out, const SimpleMatrix< T, M, N > &object)
template<typename TComponent , DGtal::Dimension TM, DGtal::Dimension TN>
SimpleMatrix< TComponent, TM, TN > operator* (const TComponent &scalar, const SimpleMatrix< TComponent, TM, TN > &matrix)
template<typename TProfile >
std::ostream & operator<< (std::ostream &out, const MeaningfulScaleAnalysis< TProfile > &object)
std::ostream & operator<< (std::ostream &out, const MeasureOfStraightLines &object)
template<typename TRing , typename TAlloc >
void euclidDiv (const MPolynomial< 1, TRing, TAlloc > &f, const MPolynomial< 1, TRing, TAlloc > &g, MPolynomial< 1, TRing, TAlloc > &q, MPolynomial< 1, TRing, TAlloc > &r)
template<int N, typename TRing , class TAlloc >
std::ostream & operator<< (std::ostream &out, const MPolynomial< N, TRing, TAlloc > &object)
template<int n, typename Ring , typename Alloc >
MPolynomial< n, Ring, Alloc > Xe_k (unsigned int k, unsigned int e)
template<int n, typename Ring >
MPolynomial< n, Ring, std::allocator< Ring > > Xe_k (unsigned int k, unsigned int e)
template<typename Ring , typename Alloc >
MPolynomial< 1, Ring, Alloc > mmonomial (unsigned int e)
template<typename Ring , typename Alloc >
MPolynomial< 2, Ring, Alloc > mmonomial (unsigned int e, unsigned int f)
template<typename Ring , typename Alloc >
MPolynomial< 3, Ring, Alloc > mmonomial (unsigned int e, unsigned int f, unsigned int g)
template<typename Ring , typename Alloc >
MPolynomial< 4, Ring, Alloc > mmonomial (unsigned int e, unsigned int f, unsigned int g, unsigned int h)
template<typename Ring >
MPolynomial< 1, Ring, std::allocator< Ring > > mmonomial (unsigned int e)
template<typename Ring >
MPolynomial< 2, Ring, std::allocator< Ring > > mmonomial (unsigned int e, unsigned int f)
template<typename Ring >
MPolynomial< 3, Ring, std::allocator< Ring > > mmonomial (unsigned int e, unsigned int f, unsigned int g)
template<typename Ring >
MPolynomial< 4, Ring, std::allocator< Ring > > mmonomial (unsigned int e, unsigned int f, unsigned int g, unsigned int h)
template<int N, int n, typename Ring , typename Alloc >
MPolynomial< n, Ring, Alloc > derivative (const MPolynomial< n, Ring, Alloc > &p)
template<int N, int n, typename Ring >
MPolynomial< n, Ring, std::allocator< Ring > > derivative (const MPolynomial< n, Ring, std::allocator< Ring > > &p)
template<typename Ring , typename Alloc >
void euclidDiv (const MPolynomial< 1, Ring, Alloc > &f, const MPolynomial< 1, Ring, Alloc > &g, MPolynomial< 1, Ring, Alloc > &q, MPolynomial< 1, Ring, Alloc > &r)
template<typename Ring >
void euclidDiv (const MPolynomial< 1, Ring, std::allocator< Ring > > &f, const MPolynomial< 1, Ring, std::allocator< Ring > > &g, MPolynomial< 1, Ring, std::allocator< Ring > > &q, MPolynomial< 1, Ring, std::allocator< Ring > > &r)
template<typename Ring , typename Alloc >
MPolynomial< 1, Ring, Alloc > gcd (const MPolynomial< 1, Ring, Alloc > &f, const MPolynomial< 1, Ring, Alloc > &g)
template<typename Ring >
MPolynomial< 1, Ring, std::allocator< Ring > > gcd (const MPolynomial< 1, Ring, std::allocator< Ring > > &f, const MPolynomial< 1, Ring, std::allocator< Ring > > &g)
std::ostream & operator<< (std::ostream &out, const MultiStatistics &object)
std::ostream & operator<< (std::ostream &that_stream, const OrderedLinearRegression &that_object_to_display)
template<typename TValueFunctor , typename TValue >
std::ostream & operator<< (std::ostream &out, const Profile< TValueFunctor, TValue > &object)
template<class TDomain , typename T >
std::ostream & operator<< (std::ostream &out, const RealFFT< TDomain, T > &object)
template<typename TValue >
std::ostream & operator<< (std::ostream &out, const Signal< TValue > &object)
std::ostream & operator<< (std::ostream &that_stream, const SimpleLinearRegression &that_object_to_display)
template<typename TQuantity >
std::ostream & operator<< (std::ostream &thatStream, const Statistic< TQuantity > &that_object_to_display)
template<typename ShapeA , typename ShapeB >
std::ostream & operator<< (std::ostream &out, const deprecated::DigitalShapesUnion< ShapeA, ShapeB > &object)
template<typename ShapeA , typename ShapeB >
std::ostream & operator<< (std::ostream &out, const deprecated::DigitalShapesIntersection< ShapeA, ShapeB > &object)
template<typename ShapeA , typename ShapeB >
std::ostream & operator<< (std::ostream &out, const deprecated::DigitalShapesMinus< ShapeA, ShapeB > &object)
template<typename ShapeA , typename ShapeB >
std::ostream & operator<< (std::ostream &out, const deprecated::EuclideanShapesUnion< ShapeA, ShapeB > &object)
template<typename ShapeA , typename ShapeB >
std::ostream & operator<< (std::ostream &out, const deprecated::EuclideanShapesIntersection< ShapeA, ShapeB > &object)
template<typename ShapeA , typename ShapeB >
std::ostream & operator<< (std::ostream &out, const deprecated::EuclideanShapesMinus< ShapeA, ShapeB > &object)
template<typename TPoint >
std::ostream & operator<< (std::ostream &out, const CircleFrom2Points< TPoint > &object)
template<typename TPoint >
std::ostream & operator<< (std::ostream &out, const CircleFrom3Points< TPoint > &object)
template<typename TSurface , bool isUpward, bool isClosed>
std::ostream & operator<< (std::ostream &out, const DGtal::functors::Point2ShapePredicate< TSurface, isUpward, isClosed > &object)
template<typename TPoint >
std::ostream & operator<< (std::ostream &out, const StraightLineFrom2Points< TPoint > &object)
template<typename TSpace , typename TEuclideanShape >
std::ostream & operator<< (std::ostream &out, const GaussDigitizer< TSpace, TEuclideanShape > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const ImplicitBall< T > &object)
template<typename TKSpace , typename TImplicitFunctionDiff1 , typename TEmbedder >
std::ostream & operator<< (std::ostream &out, const ImplicitFunctionDiff1LinearCellEmbedder< TKSpace, TImplicitFunctionDiff1, TEmbedder > &object)
template<typename TKSpace , typename TImplicitFunction , typename TEmbedder >
std::ostream & operator<< (std::ostream &out, const ImplicitFunctionLinearCellEmbedder< TKSpace, TImplicitFunction, TEmbedder > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const ImplicitHyperCube< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const ImplicitNorm1Ball< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const ImplicitPolynomial3Shape< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const ImplicitRoundedHyperCube< T > &object)
template<typename TPoint >
std::ostream & operator<< (std::ostream &out, const Mesh< TPoint > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const AccFlower2D< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const Astroid2D< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const Ball2D< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const Ball3D< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const Ellipse2D< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const Flower2D< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const Lemniscate2D< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const NGon2D< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const StarShaped2D< T > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const StarShaped3D< T > &object)
template<typename TPoint >
std::ostream & operator<< (std::ostream &out, const PolygonalSurface< TPoint > &object)
template<typename TDomain >
std::ostream & operator<< (std::ostream &out, const Shapes< TDomain > &object)
template<typename TPoint >
std::ostream & operator<< (std::ostream &out, const TriangulatedSurface< TPoint > &object)
template<typename TKSpace >
std::ostream & operator<< (std::ostream &out, const CanonicCellEmbedder< TKSpace > &object)
template<typename TDigitalSurface >
std::ostream & operator<< (std::ostream &out, const CanonicDigitalSurfaceEmbedder< TDigitalSurface > &object)
template<typename TKSpace >
std::ostream & operator<< (std::ostream &out, const CanonicSCellEmbedder< TKSpace > &object)
template<typename TKSpace , typename TCellContainer >
std::ostream & operator<< (std::ostream &out, const CubicalComplex< TKSpace, TCellContainer > &object)
template<typename TKSpace , typename TDigitalSet >
std::ostream & operator<< (std::ostream &out, const DigitalSetBoundary< TKSpace, TDigitalSet > &object)
template<typename TDigitalSurfaceContainer >
std::ostream & operator<< (std::ostream &out, const DigitalSurface< TDigitalSurfaceContainer > &object)
template<typename TDigitalSurfaceTracker >
std::ostream & operator<< (std::ostream &out, const DigitalSurface2DSlice< TDigitalSurfaceTracker > &object)
template<typename TForegroundAdjacency , typename TBackgroundAdjacency >
std::ostream & operator<< (std::ostream &out, const DigitalTopology< TForegroundAdjacency, TBackgroundAdjacency > &object)
template<typename TDomain , typename TAdjacency >
std::ostream & operator<< (std::ostream &out, const DomainAdjacency< TDomain, TAdjacency > &object)
template<typename TKSpace , typename TSurfelPredicate >
std::ostream & operator<< (std::ostream &out, const ExplicitDigitalSurface< TKSpace, TSurfelPredicate > &object)
std::ostream & operator<< (std::ostream &out, const HalfEdgeDataStructure &object)
template<typename TKSpace , typename TImage >
std::ostream & operator<< (std::ostream &out, const DGtal::functors::BoundaryPredicate< TKSpace, TImage > &object)
template<typename TKSpace , typename TImage >
std::ostream & operator<< (std::ostream &out, const DGtal::functors::FrontierPredicate< TKSpace, TImage > &object)
template<typename TKSpace >
std::ostream & operator<< (std::ostream &out, const Surfaces< TKSpace > &object)
template<typename TKSpace , typename TPointPredicate >
std::ostream & operator<< (std::ostream &out, const ImplicitDigitalSurface< TKSpace, TPointPredicate > &object)
template<typename TDigitalSurfaceContainer >
std::ostream & operator<< (std::ostream &out, const IndexedDigitalSurface< TDigitalSurfaceContainer > &object)
template<Dimension dim, typename TInteger >
std::ostream & operator<< (std::ostream &out, const KhalimskyPreCell< dim, TInteger > &object)
template<Dimension dim, typename TInteger >
std::ostream & operator<< (std::ostream &out, const SignedKhalimskyPreCell< dim, TInteger > &object)
template<Dimension dim, typename TInteger >
std::ostream & operator<< (std::ostream &out, const KhalimskyPreSpaceND< dim, TInteger > &object)
template<Dimension dim, typename TInteger >
std::ostream & operator<< (std::ostream &out, const KhalimskyCell< dim, TInteger > &object)
template<Dimension dim, typename TInteger >
std::ostream & operator<< (std::ostream &out, const SignedKhalimskyCell< dim, TInteger > &object)
template<Dimension dim, typename TInteger >
std::ostream & operator<< (std::ostream &out, const KhalimskySpaceND< dim, TInteger > &object)
template<typename TKSpace , typename TSurfelPredicate >
std::ostream & operator<< (std::ostream &out, const LightExplicitDigitalSurface< TKSpace, TSurfelPredicate > &object)
template<typename TKSpace , typename TPointPredicate >
std::ostream & operator<< (std::ostream &out, const LightImplicitDigitalSurface< TKSpace, TPointPredicate > &object)
template<typename TSpace , Dimension maxNorm1>
std::ostream & operator<< (std::ostream &out, const MetricAdjacency< TSpace, maxNorm1, TSpace::dimension > &object)
template<typename TDigitalTopology , typename TDigitalSet >
std::ostream & operator<< (std::ostream &out, const Object< TDigitalTopology, TDigitalSet > &object)
template<typename TKSpace , typename TSurfelSet >
std::ostream & operator<< (std::ostream &out, const SetOfSurfels< TKSpace, TSurfelSet > &object)
template<Dimension dim>
std::ostream & operator<< (std::ostream &out, const SurfelAdjacency< dim > &object)
template<typename T >
std::ostream & operator<< (std::ostream &out, const SurfelNeighborhood< T > &object)
template<typename TDigitalSurfaceTracker >
std::ostream & operator<< (std::ostream &out, const UmbrellaComputer< TDigitalSurfaceTracker > &object)
template<typename TKSpace , typename TObject , typename TCellContainer >
std::ostream & operator<< (std::ostream &out, const VoxelComplex< TKSpace, TObject, TCellContainer > &object)
template<typename KSpace , typename PointPredicate >
bool testImplicitDigitalSurface (const KSpace &K, const PointPredicate &pp, const typename KSpace::Surfel &bel)
template<typename KSpace , typename PointPredicate >
bool testLightImplicitDigitalSurface (const KSpace &K, const PointPredicate &pp, const typename KSpace::Surfel &bel)
Variables
Trace trace
TraceWriterTerm traceWriterTerm (std::cerr)
static std::size_t const HALF_EDGE_INVALID_INDEX = boost::integer_traits<std::size_t>::const_max
Detailed Description
DGtal is the top-level namespace which contains all DGtal functions and types.
[PrivateMembers]
for embedding
DGtal Global variables
This macro is necessary for using spirit/phoenix functions 'at' during the construction of the semantic tree. This macro is necessary for using spirit/phoenix functions 'at' during the construction of the semantic tree. This macro is necessary for using spirit/phoenix functions 'at' during the construction of the semantic tree.
[IteratorCompletionTraits]
Typedef Documentation
typedef mpz_class DGtal::BigInteger
Multi-precision integer with GMP implementation.
Definition at line 79 of file BasicTypes.h.
typedef DGtal::uint32_t DGtal::Dimension
Global static type to represent the dimension in DGtal
Definition at line 120 of file Common.h.
typedef boost::int16_t DGtal::int16_t
signed 16-bit integer.
Definition at line 70 of file BasicTypes.h.
typedef boost::int32_t DGtal::int32_t
signed 32-bit integer.
Definition at line 72 of file BasicTypes.h.
typedef boost::int64_t DGtal::int64_t
signed 94-bit integer.
Definition at line 74 of file BasicTypes.h.
typedef boost::int8_t DGtal::int8_t
signed 8-bit integer.
Definition at line 68 of file BasicTypes.h.
using DGtal::NeighborhoodConfiguration = typedef uint32_t
Definition at line 43 of file NeighborhoodConfigurationsHelper.h.
typedef unsigned int DGtal::Order
Aim: Order is used as template parameter for DEC classes.
Description of 'Order'
Definition at line 87 of file Duality.h.
typedef boost::uint16_t DGtal::uint16_t
unsigned 16-bit integer.
Definition at line 61 of file BasicTypes.h.
typedef boost::uint32_t DGtal::uint32_t
unsigned 32-bit integer.
Examples:
topology/cubical-complex-collapse.cpp.
Definition at line 63 of file BasicTypes.h.
typedef boost::uint64_t DGtal::uint64_t
unsigned 64-bit integer.
Definition at line 65 of file BasicTypes.h.
typedef boost::uint8_t DGtal::uint8_t
unsigned 8-bit integer.
Definition at line 59 of file BasicTypes.h.
Enumeration Type Documentation
enum DGtal::BoundEnum
Enumerator
BOUNDED
UNBOUNDED
BOUND_UNKNOWN
Definition at line 53 of file NumberTraits.h.
 {BOUNDED = 0, UNBOUNDED = 1, BOUND_UNKNOWN = 2};
enum DGtal::Closest
Global enum definition for closest point test (geometry/volumes/distance/..).
Enumerator
ClosestFIRST
ClosestSECOND
ClosestBOTH
Definition at line 130 of file Common.h.
 { ClosestFIRST = 0, ClosestSECOND = 1, ClosestBOTH = 2};
enum DGtal::ColorGradientPreset
Enumerator
CMAP_CUSTOM
CMAP_GRAYSCALE
CMAP_SPRING
CMAP_SUMMER
CMAP_AUTUMN
CMAP_WINTER
CMAP_COOL
CMAP_COPPER
CMAP_HOT
CMAP_JET
Definition at line 60 of file GradientColorMap.h.
                            { CMAP_CUSTOM = 0,
            CMAP_GRAYSCALE,
            CMAP_SPRING,
            CMAP_SUMMER,
            CMAP_AUTUMN,
            CMAP_WINTER,
            CMAP_COOL,
            CMAP_COPPER,
            CMAP_HOT,
            CMAP_JET };
enum DGtal::Connectedness
Kinds of connectedness for an object or a graph.
Enumerator
DISCONNECTED
CONNECTED
UNKNOWN
Definition at line 50 of file Topology.h.
     {
       DISCONNECTED = 0, CONNECTED = 1, UNKNOWN = 2
     };
enum DGtal::DigitalSetBelongTestability
Enumerator
LOW_BEL_DS
HIGH_BEL_DS
Definition at line 63 of file DigitalSetSelector.h.
 { LOW_BEL_DS = 0, HIGH_BEL_DS = 16 };
enum DGtal::DigitalSetIterability
Enumerator
LOW_ITER_DS
HIGH_ITER_DS
Definition at line 62 of file DigitalSetSelector.h.
 { LOW_ITER_DS = 0, HIGH_ITER_DS = 8 };
enum DGtal::DigitalSetSize
Enumerator
SMALL_DS
MEDIUM_DS
BIG_DS
WHOLE_DS
Definition at line 60 of file DigitalSetSelector.h.
 { SMALL_DS = 0, MEDIUM_DS = 1, BIG_DS = 2, WHOLE_DS = 3 };
enum DGtal::DigitalSetVariability
Enumerator
LOW_VAR_DS
HIGH_VAR_DS
Definition at line 61 of file DigitalSetSelector.h.
 { LOW_VAR_DS = 0, HIGH_VAR_DS = 4 };
enum DGtal::DigitalTopologyProperties
Possible properties of digital topologies.
Enumerator
UNKNOWN_DT
NOT_JORDAN_DT
JORDAN_DT
Definition at line 55 of file DigitalTopology.h.
                                  { UNKNOWN_DT = 0,
            NOT_JORDAN_DT = 1,
            JORDAN_DT = 2 };
enum DGtal::DomainDrawMode
Specifies the drawing mode for domains.
Enumerator
GRID
PAVING
Definition at line 57 of file Board2D.h.
 { GRID = 0, PAVING = 1 };
enum DGtal::Duality
Aim: Duality enumerator tells if templated object lives in primal or dual space. Used as template parameter for DEC classes.
Description of 'Duality'
Enumerator
PRIMAL
DUAL
Definition at line 57 of file Duality.h.
 {
     PRIMAL = 0,
     DUAL = 1
 };
enum DGtal::ImageBelongTestability
Enumerator
HIGH_BEL_I
LOW_BEL_I
Definition at line 55 of file ImageSelector.h.
 {  HIGH_BEL_I = 0, LOW_BEL_I = 2 };
enum DGtal::ImageIterability
Enumerator
HIGH_ITER_IMAGE
LOW_ITER_I
Definition at line 54 of file ImageSelector.h.
 {  HIGH_ITER_IMAGE = 0 , LOW_ITER_I = 1};
enum DGtal::ImageSpecificContainer
Enumerator
NORMAL_CONTAINER_I
VTKIMAGEDATA_CONTAINER_I
Definition at line 56 of file ImageSelector.h.
 { NORMAL_CONTAINER_I = 0, VTKIMAGEDATA_CONTAINER_I = 4 };
enum DGtal::Orientation
Global enum definition for orientation.
Enumerator
INSIDE
ON
OUTSIDE
Definition at line 125 of file Common.h.
 { INSIDE = 0, ON = 1, OUTSIDE = 2};
enum DGtal::SignEnum
Enumerator
SIGNED
UNSIGNED
SIGN_UNKNOWN
Definition at line 54 of file NumberTraits.h.
 {SIGNED = 0, UNSIGNED = 1, SIGN_UNKNOWN = 2};
enum DGtal::Surfel2PointEmbedding
Possible embeddings for surfel as point(s)
Enumerator
Pointels
InnerSpel
OuterSpel
Definition at line 58 of file VoronoiCovarianceMeasureOnDigitalSurface.h.
 { Pointels = 0, InnerSpel = 1, OuterSpel = 2 };
Function Documentation
template<typename IC > void DGtal::advanceIterator (IC & ic, typename IteratorCirculatorTraits< IC >::Difference n) inline
Moves ic at position @ it + n
Parameters
ic any (circular)iterator
n any positive distance
Template Parameters
IC any model o fiterator or circulator
void DGtal::assert_failed (const std::string & expr, const std::string & function, const std::string & file, long int line) inline
Definition at line 65 of file Assert.h.
   {
       trace.error()
           << " Assertion Error - assertion (" << expr << ") failed in " << function << ": "
           << file << '(' << line << ")" << std::endl;
       std::abort();
   }
void DGtal::assert_failed_message (const std::string & expr, const std::string & message, const std::string & function, const std::string & file, long int line) inline
Definition at line 81 of file Assert.h.
   {
       trace.error()
           << " Assertion Error - assertion (" << expr << ") failed in " << function << ": "
           << file << '(' << line << "): " << std::endl << message << std::endl;
       std::abort();
   }
template<typename TSequence > BackInsertionSequenceToStackAdapter<TSequence> DGtal::backStack (TSequence & aSequence)
Function returning an object of class 'BackInsertionSequenceToStackAdapter'
Parameters
aSequence container to adapt.
Template Parameters
TSequence a model of back insertion sequence
Returns
the adapter.
template<int N, int n, typename Ring , typename Alloc > MPolynomial<n, Ring, Alloc> DGtal::derivative (const MPolynomial< n, Ring, Alloc > & p) inline
Computes the partial derivative of p with respect to the N-th indeterminate. We assume that 0 <= N < n.
Parameters
p an arbitrary polynomial.
Template Parameters
N the variable used for derivation.
n the number of variables or indeterminates.
Ring the type chosen for the polynomial, defines also the type of the coefficents (generally int, float or double).
Alloc is an allocator for Ring, for example std::allocator<Ring>; this is also the default parameter. Usually this parameter does not needs to be changed.
Definition at line 1966 of file MPolynomial.h.
References DGtal::MPolynomialDerivativeComputer< N, n, Ring, Alloc >::computeDerivative(), and DGtal::MPolynomial< n, TRing, TAlloc >::getAllocator().
   {
     MPolynomial<n, Ring, Alloc> res( p.getAllocator() );
     MPolynomialDerivativeComputer<N, n, Ring, Alloc>::computeDerivative(p, res);
     return res;
   }
template<int N, int n, typename Ring > MPolynomial<n, Ring, std::allocator<Ring> > DGtal::derivative (const MPolynomial< n, Ring, std::allocator< Ring > > & p) inline
Computes the partial derivative of p with respect to the N-th indeterminate. We assume that 0 <= N < n.
Parameters
p an arbitrary polynomial.
Template Parameters
N the variable used for derivation.
n the number of variables or indeterminates.
Ring the type chosen for the polynomial, defines also the type of the coefficents (generally int, float or double).
Definition at line 1990 of file MPolynomial.h.
    {
      MPolynomial<n, Ring, std::allocator<Ring> > res( p.getAllocator() );
      MPolynomialDerivativeComputer<N, n, Ring, std::allocator<Ring> >
        ::computeDerivative( p, res );
      return res;
    }
template<typename TRing , typename TAlloc > void DGtal::euclidDiv (const MPolynomial< 1, TRing, TAlloc > & f, const MPolynomial< 1, TRing, TAlloc > & g, MPolynomial< 1, TRing, TAlloc > & q, MPolynomial< 1, TRing, TAlloc > & r)
Forward declaration, to be able to declare this as a friend.
Referenced by gcd().
template<typename Ring , typename Alloc > void DGtal::euclidDiv (const MPolynomial< 1, Ring, Alloc > & f, const MPolynomial< 1, Ring, Alloc > & g, MPolynomial< 1, Ring, Alloc > & q, MPolynomial< 1, Ring, Alloc > & r)
Computes q and r such that f = q g + r and degree(r) < degree(g).
Definition at line 2003 of file MPolynomial.h.
    {
      if (f.degree() < g.degree())
        {
          // Ignore the trivial case
          q = MPolynomial<1, Ring, Alloc>(f.getAllocator());
          r = f;
          return;
        }
     q = MPolynomial<1, Ring, Alloc>( true, f.degree() - g.degree() + 1,
                                      f.getAllocator() );
     r = f;
     for (int i = q.degree(); i >= 0; --i)
       {
         q[i] = r[i + g.degree()] / g.leading();
         for (int j = g.degree(); j >= 0; --j)
           r[i + j] -= q[i] * g[j];
       }
     r.normalize();
     // Note that the degree of q is already correct.
    }
template<typename Ring > void DGtal::euclidDiv (const MPolynomial< 1, Ring, std::allocator< Ring > > & f, const MPolynomial< 1, Ring, std::allocator< Ring > > & g, MPolynomial< 1, Ring, std::allocator< Ring > > & q, MPolynomial< 1, Ring, std::allocator< Ring > > & r)
Computes q and r such that f = q g + r and degree(r) < degree(g).
Definition at line 2033 of file MPolynomial.h.
    {
      euclidDiv<Ring, std::allocator<Ring> >(f, g, q, r);
    }
void DGtal::fatal_error_failed (const std::string & expr, const std::string & function, const std::string & file, long int line) inline
Definition at line 93 of file Assert.h.
   {
       trace.error()
           << " Fatal Error - assertion (" << expr << ") failed in " << function << ": "
           << file << '(' << line << ")" << std::endl;
       std::abort();
   }
void DGtal::fatal_error_failed_message (const std::string & expr, const std::string & message, const std::string & function, const std::string & file, long int line) inline
Definition at line 104 of file Assert.h.
   {
       trace.error()
           << " Fatal Error - assertion (" << expr << ") failed in " << function << ": "
           << file << '(' << line << "): " << std::endl << message << std::endl;
       std::abort();
   }
template<typename I , typename S > bool DGtal::findAndGetValue (const I & aImg, const S & aSet, const typename I::Point & aPoint, typename I::Value & aValue)
Read the value contained in aImg at aPoint if aPoint belongs to aSet.
Parameters
aImg an image
aSet a digital set
aPoint a point
aValue (returned) value
Returns
'true' if a new point is found and the value read but 'false' otherwise
Template Parameters
I any model of CConstImage
S any model of CDigitalSet
The general behavior is like:
However, this code is specialized if I is an ImageContainerBySTLMap and S is a DigitalSetFromMap<I> as follows:
See also
ImageContainerBySTLMap DigitalSetFromMap
insertAndSetValue
template<typename SC > void DGtal::firstMaximalSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end, DGtal::ForwardSegmentComputer)
Computes the first maximal segment passing through i
Parameters
s any instance of segment computer
i any ConstIterator
begin any begin ConstIterator bounding a range
end any end ConstIterator bounding a range
Template Parameters
SC any model of CForwardSegmentComputer
Definition at line 412 of file SegmentComputerUtils.h.
References longestSegment().
Referenced by firstMaximalSegment(), mostCenteredMaximalSegment(), and nextMaximalSegment().
 {
   typedef typename SC::ConstIterator ConstIterator;
   typedef typename SC::Reverse ReverseSegmentComputer;
   typedef typename ReverseSegmentComputer::ConstIterator ConstReverseIterator;
   if ( isNotEmpty<ConstIterator>(i,end) ) {
     //backward extension
     ConstIterator it( i ); ++it;
     ConstReverseIterator rit( it );
     ConstReverseIterator rend( begin );
     ReverseSegmentComputer r( s.getReverse() );
     longestSegment(r, rit, rend);
     //forward extension
     ConstIterator it2( r.end().base() );
     longestSegment(s, it2, end);
   }
 }
template<typename SC > void DGtal::firstMaximalSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end, DGtal::BidirectionalSegmentComputer)
Computes the first maximal segment passing through i
Parameters
s any instance of segment computer
i any ConstIterator
begin any begin ConstIterator bounding a range
end any end ConstIterator bounding a range
Template Parameters
SC any model of CBidirectionalSegmentComputer
Definition at line 449 of file SegmentComputerUtils.h.
References maximalExtension(), and oppositeEndMaximalExtension().
 {
   s.init(i);
   oppositeEndMaximalExtension(s, begin);
   maximalExtension(s, end);
 }
template<typename SC > void DGtal::firstMaximalSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end, DGtal::DynamicSegmentComputer)
Computes the first maximal segment passing through i
Parameters
s any instance of segment computer
i any ConstIterator
begin any begin ConstIterator bounding a range
end any end ConstIterator bounding a range
Template Parameters
SC any model of CDynamicSegmentComputer
Note
calls the function dedicated to ForwardSegmentComputer
Definition at line 471 of file SegmentComputerUtils.h.
References firstMaximalSegment().
 {
   firstMaximalSegment(s,i,begin,end,DGtal::ForwardSegmentComputer() );
 }
template<typename SC > void DGtal::firstMaximalSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end, DGtal::DynamicBidirectionalSegmentComputer)
Computes the first maximal segment passing through i
Parameters
s any instance of segment computer
i any ConstIterator
begin any begin ConstIterator bounding a range
end any end ConstIterator bounding a range
Template Parameters
SC any model of CDynamicBidirectionalSegmentComputer
Note
calls the function dedicated to BidirectionalSegmentComputer
Definition at line 490 of file SegmentComputerUtils.h.
References firstMaximalSegment().
 {
   firstMaximalSegment(s,i,begin,end,DGtal::BidirectionalSegmentComputer() );
 }
template<typename SC > void DGtal::firstMaximalSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end)
Computes the first maximal segment passing through i
Parameters
s any instance of segment computer
i any ConstIterator
begin any begin ConstIterator bounding a range
end any end ConstIterator bounding a range
Template Parameters
SC any model of segment computer
Definition at line 508 of file SegmentComputerUtils.h.
 {
   firstMaximalSegment<SC>(s, i, begin, end,
 typename DGtal::SegmentComputerTraits<SC>::Category() );
 }
template<typename TSequence > FrontInsertionSequenceToStackAdapter<TSequence> DGtal::frontStack (TSequence & aSequence)
Function returning an object of class 'FrontInsertionSequenceToStackAdapter'
Parameters
aSequence container to adapt.
Template Parameters
TSequence a model of back insertion sequence
Returns
the adapter.
template<typename Ring , typename Alloc > MPolynomial<1, Ring, Alloc> DGtal::gcd (const MPolynomial< 1, Ring, Alloc > & f, const MPolynomial< 1, Ring, Alloc > & g)
Compute the monic greatest common divisor of f and g using the Euclidean Algorithm.
Definition at line 2047 of file MPolynomial.h.
References euclidDiv().
    {
      if (f.isZero())
        {
          if (g.isZero()) return f; // both are zero
          else            return g / g.leading(); // make g monic
        }
      MPolynomial<1, Ring, Alloc>
        d1(f / f.leading()),
        d2(g / g.leading()),
        q(f.getAllocator()),
        r(f.getAllocator());
      while (!d2.isZero())
        {
          euclidDiv(d1, d2, q, r);
          d1.swap(d2);
          d2 = r;
          d2 /= r.leading(); // make r monic
        }
      return d1;
    }
template<typename Ring > MPolynomial<1, Ring, std::allocator<Ring> > DGtal::gcd (const MPolynomial< 1, Ring, std::allocator< Ring > > & f, const MPolynomial< 1, Ring, std::allocator< Ring > > & g)
Compute the monic greatest common divisor of f and g using the Euclidean Algorithm.
Definition at line 2076 of file MPolynomial.h.
   {
     return gcd<Ring, std::allocator<Ring> >(f, g);
   }
template<typename IC > IC DGtal::getMiddleIterator (const IC & itb, const IC & ite, RandomAccessCategory)
Specialization for random access category
Definition at line 87 of file SegmentComputerUtils.h.
Referenced by getMiddleIterator(), and mostCenteredMaximalSegment().
 {
 //how to compute this with circulators ?
 //return itb + ((ite-itb)/2);
 //does not work
   return getMiddleIterator(itb, ite, BidirectionalCategory() );
 }
template<typename IC > IC DGtal::getMiddleIterator (const IC & itb, const IC & ite, BidirectionalCategory)
Specialization for bidirectional category NB: in O(ite-itb)
Definition at line 100 of file SegmentComputerUtils.h.
 {
   IC b( itb );
   IC f( ite );
   bool flag = true;
   while (b != f) {
     if (flag) {
       --f;
       flag = false;
     } else {
       ++b;
       flag = true;
     }
   }
   return b;
 }
template<typename IC > IC DGtal::getMiddleIterator (const IC & itb, const IC & ite, ForwardCategory)
Specialization for forward category NB: in O(ite-itb)
Definition at line 122 of file SegmentComputerUtils.h.
 {
   IC i( itb );
   unsigned int c = 0;
   while (i != ite) {
     ++i;
     ++c;
   }
   unsigned int k = c/2;
   c = 0;
   i = itb;
   while (c != k) {
     ++i;
     ++c;
   }
   return i;
 }
template<typename IC > IC DGtal::getMiddleIterator (const IC & itb, const IC & ite)
Computes the middle iterator of a given range, i.e. itb + (ite-itb)/2)
Parameters
itb begin iterator of a range
ite end iterator of a range
Returns
the middle iterator of the range [itb,ite)
Template Parameters
IC iterator or circulator
Definition at line 151 of file SegmentComputerUtils.h.
References getMiddleIterator().
{
   typedef typename IteratorCirculatorTraits<IC>::Category Category;
   return getMiddleIterator(itb, ite, Category() );
 }
template<Dimension dim, typename TInteger > size_t DGtal::hash_value (const KhalimskyCell< dim, TInteger > & cell)
Hash function for Khalimsky unsigned cells.
Parameters
cell input signed cell.
Returns
hash value.
template<typename I , typename F > void DGtal::imageFromFunctor (I & aImg, const F & aFun)
In a window corresponding to the domain of aImg, copy the values of aFun into aImg
Parameters
aImg (returned) image
aFun a unary functor
Template Parameters
I any model of CImage
F any model of CPointFunctor
template<typename I1 , typename I2 > void DGtal::imageFromImage (I1 & aImg1, const I2 & aImg2)
Copy the values of aImg2 into aImg1 .
Parameters
aImg1 the image to fill
aImg2 the image to copy
Template Parameters
I1 any model of CImage
I2 any model of CConstImage
template<typename It , typename Im > void DGtal::imageFromRangeAndValue (const It & itb, const It & ite, Im & aImg, const typename Im::Value & aValue = 0)
Set the values of aImg at aValue for each points of the range [ itb , ite)
Parameters
itb begin iterator on points
ite end iterator on points
aImg (returned) image
aValue any value (default: 0)
Template Parameters
It any model of forward iterator
Im any model of CImage
template<typename R , typename I > void DGtal::imageFromRangeAndValue (const R & aRange, I & aImg, const typename I::Value & aValue = 0)
Set the values of aImg at aValue for each points of the range aRange
Parameters
aRange any range
aImg (returned) image
aValue any value (default: 0)
Template Parameters
R any model of CConstSinglePassRange
I any model of CImage
template<typename I , typename S > bool DGtal::insertAndAlwaysSetValue (I & aImg, S & aSet, const typename I::Point & aPoint, const typename I::Value & aValue)
Insert aPoint in aSet and set aValue at aPoint in aImg.
Parameters
aImg an image
aSet a digital set
aPoint a point
aValue a value
Returns
'true' if a new point was inserted in aSet but 'false' if the same point already exist in aSet
Template Parameters
I any model of CImage
S any model of CDigitalSet
The general behavior is like:
 bool found = false;
 if ( aSet.find( aPoint ) != aSet.end() )
   found = true;
 //always set value
 aSet.insert( aPoint );
 aImg.setValue( aPoint, aValue );
 return !found;
However, this code is specialized if I is an ImageContainerBySTLMap and S is a DigitalSetFromMap<I> as follows:
 std::pair<P, V>
 pair( aPoint, aValue );
 std::pair<Iterator, bool> res
 = aImg.insert( pair );
 bool flag = res.second;
 if (flag == false) //set value even in this case
 res.first->second = aValue;
 return flag;
See also
ImageContainerBySTLMap DigitalSetFromMap
insertAndSetValue
template<typename I , typename S > bool DGtal::insertAndSetValue (I & aImg, S & aSet, const typename I::Point & aPoint, const typename I::Value & aValue)
Insert aPoint in aSet and if (and only if) aPoint is a newly inserted point. Then set aValue at aPoint in aImg.
Parameters
aImg an image
aSet a digital set
aPoint a point
aValue a value
Returns
'true' if a new point was inserted in aSet but 'false' if the same point already exist in aSet
Template Parameters
I any model of CImage
S any model of CDigitalSet
The general behavior is like:
 bool found = true;
 if ( aSet.find( aPoint ) == aSet.end() )
   { //if not found
     found = false;
     aSet.insert( aPoint );
     aImg.setValue( aPoint, aValue );
   }
 return !found;
However, this code is specialized if I is an ImageContainerBySTLMap and S is a DigitalSetFromMap<I> as follows:
 std::pair<P, V>
 pair( aPoint, aValue );
 std::pair<Iterator, bool> res
 = aImg.insert( pair );
 return res.second;
See also
ImageContainerBySTLMap DigitalSetFromMap
insertAndAlwaysSetValue
template<typename IC > bool DGtal::isEmpty (const IC & itb, const IC & ite) inline
Checks if the range [ itb , ite) is empty
Parameters
itb begin iterator of the range
ite end iterator of the range
Template Parameters
IC model of iterator or circulator
template<typename IC > bool DGtal::isNotEmpty (const IC & itb, const IC & ite) inline
Checks if the range [ itb , ite) is not empty
Parameters
itb begin iterator of the range
ite end iterator of the range
Template Parameters
IC model of iterator or circulator
Referenced by mostCenteredMaximalSegment().
template<typename SC > void DGtal::lastMaximalSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end, DGtal::ForwardSegmentComputer)
Computes the last maximal segment passing through i
Parameters
s any instance of segment computer
i any ConstIterator
begin any begin ConstIterator bounding a range
end any end ConstIterator bounding a range
Template Parameters
SC any model of CForwardSegmentComputer
Definition at line 681 of file SegmentComputerUtils.h.
References longestSegment().
Referenced by lastMaximalSegment(), and previousMaximalSegment().
 {
   typedef typename SC::ConstIterator ConstIterator;
   typedef typename SC::Reverse ReverseSegmentComputer;
   typedef typename ReverseSegmentComputer::ConstIterator ConstReverseIterator;
   //forward extension
   ConstIterator j( i );
   longestSegment(s, j, end);
   //backward extension
   ConstIterator it( s.end() );
   ConstReverseIterator rit( it );
   ConstReverseIterator rend( begin );
   ReverseSegmentComputer r( s.getReverse() );
   longestSegment(r, rit, rend);
   //forward extension
   ConstIterator it2( r.end().base() );
   longestSegment(s, it2, end);
 }
template<typename SC > void DGtal::lastMaximalSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end, BidirectionalSegmentComputer)
Computes the last maximal segment passing through i
Parameters
s any instance of segment computer
i any ConstIterator
begin any begin ConstIterator bounding a range
end any end ConstIterator bounding a range
Template Parameters
SC any model of CBidirectionalSegmentComputer
Definition at line 717 of file SegmentComputerUtils.h.
References maximalExtension(), and oppositeEndMaximalExtension().
 {
   s.init(i);
   maximalExtension(s, end);
   oppositeEndMaximalExtension(s, begin);
 }
template<typename SC > void DGtal::lastMaximalSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end, DGtal::DynamicSegmentComputer)
Computes the last maximal segment passing through i
Parameters
s any instance of segment computer
i any ConstIterator
begin any begin ConstIterator bounding a range
end any end ConstIterator bounding a range
Template Parameters
SC any model of CDynamicSegmentComputer
Note
calls the function dedicated to ForwardSegmentComputer
Definition at line 739 of file SegmentComputerUtils.h.
References lastMaximalSegment().
 {
   lastMaximalSegment(s,i,begin,end,DGtal::ForwardSegmentComputer() );
 }
template<typename SC > void DGtal::lastMaximalSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end, DGtal::DynamicBidirectionalSegmentComputer)
Computes the last maximal segment passing through i
Parameters
s any instance of segment computer
i any ConstIterator
begin any begin ConstIterator bounding a range
end any end ConstIterator bounding a range
Template Parameters
SC any model of CDynamicBidirectionalSegmentComputer
Note
calls the function dedicated to BidirectionalSegmentComputer
Definition at line 758 of file SegmentComputerUtils.h.
References lastMaximalSegment().
 {
   lastMaximalSegment(s,i,begin,end,DGtal::BidirectionalSegmentComputer() );
 }
template<typename SC > void DGtal::lastMaximalSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end)
Computes the last maximal segment passing through i
Parameters
s any instance of segment computer
i any ConstIterator
begin any begin ConstIterator bounding a range
end any end ConstIterator bounding a range
Template Parameters
SC any model of segment computer
Definition at line 776 of file SegmentComputerUtils.h.
 {
    lastMaximalSegment<SC>(s, i, begin, end,
 typename DGtal::SegmentComputerTraits<SC>::Category() );
 }
template<typename SC > void DGtal::longestSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & end, IteratorType)
Specialization for Iterator type
Definition at line 359 of file SegmentComputerUtils.h.
References maximalExtension().
Referenced by firstMaximalSegment(), lastMaximalSegment(), longestSegment(), and mostCenteredMaximalSegment().
  {
   if (i != end) {
     s.init(i);
     maximalExtension(s, end, IteratorType() );
   }
 }
template<typename SC > void DGtal::longestSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & end, CirculatorType)
Specialization for Circulator type
Definition at line 374 of file SegmentComputerUtils.h.
References maximalExtension().
 {
   s.init(i);
   maximalExtension(s, end, CirculatorType() );
 }
template<typename SC > void DGtal::longestSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & end)
Computes the longest possible segment from [i]
Parameters
s any instance of segment computer
i a given ConstIterator
end any end ConstIterator
Template Parameters
SC any model of segment computer
Definition at line 391 of file SegmentComputerUtils.h.
References longestSegment().
 {
   typedef typename IteratorCirculatorTraits<typename SC::ConstIterator>::Type Type;
   longestSegment( s, i, end, Type() );
 }
template<typename TImage , typename TDomain = typename TImage::Domain> ArrayImageAdapter< decltype(((TImage*)nullptr)->begin()), TDomain > DGtal::makeArrayImageAdapterFromImage (TImage & anImage, TDomain const & aViewDomain)
Returns an ArrayImageAdapter from an image and a viewable domain.
Parameters
anImage The image that models the CConstImage concept.
aViewDomain The viewable domain of this image.
Definition at line 500 of file ArrayImageAdapter.h.
     {
       // Remove constness because CConstImage requires assignability.
       BOOST_CONCEPT_ASSERT( (DGtal::concepts::CConstImage< typename std::remove_const<TImage>::type >) );
       return { anImage.begin(), anImage.domain(), aViewDomain };
     }
template<typename TImage , typename TDomain = typename TImage::Domain> ArrayImageAdapter< decltype(((TImage*)nullptr)->begin()), TDomain > DGtal::makeArrayImageAdapterFromImage (TImage & anImage)
Returns an ArrayImageAdapter from an image.
The viewable domain will be the same as the given image domain.
Parameters
anImage The image that models the CConstImage concept.
Definition at line 521 of file ArrayImageAdapter.h.
     {
       // Remove constness because CConstImage requires assignability.
       BOOST_CONCEPT_ASSERT( (DGtal::concepts::CConstImage< typename std::remove_const<TImage>::type >) );
       return { anImage.begin(), anImage.domain(), anImage.domain() };
     }
template<typename TArrayIterator , typename TDomain > ArrayImageAdapter< TArrayIterator, TDomain > DGtal::makeArrayImageAdapterFromIterator (TArrayIterator anArrayIterator, TDomain const & aFullDomain, TDomain const & aViewDomain)
Returns an ArrayImageAdapter from an iterator, a full domain and a viewable domain.
Parameters
anArrayIterator A random-access iterator on the datas.
aFullDomain The domain span by the given iterator.
aViewDomain The viewable domain of this image.
Returns
an ArrayImageAdapter instance.
Definition at line 465 of file ArrayImageAdapter.h.
     {
       return { anArrayIterator, aFullDomain, aViewDomain };
     }
template<typename TArrayIterator , typename TDomain > ArrayImageAdapter< TArrayIterator, TDomain > DGtal::makeArrayImageAdapterFromIterator (TArrayIterator anArrayIterator, TDomain const & aFullDomain)
Returns an ArrayImageAdapter from an iterator and a full domain.
The viewable domain will be the same as the full domain.
Parameters
anArrayIterator A random-access iterator on the datas.
aFullDomain The domain span by the given iterator.
Returns
an ArrayImageAdapter instance.
Definition at line 483 of file ArrayImageAdapter.h.
     {
       return { anArrayIterator, aFullDomain, aFullDomain };
     }
template<typename SC > void DGtal::maximalExtension (SC & s, const typename SC::ConstIterator & end, IteratorType)
Specialization for Iterator type
Definition at line 164 of file SegmentComputerUtils.h.
Referenced by firstMaximalSegment(), lastMaximalSegment(), longestSegment(), maximalExtension(), mostCenteredMaximalSegment(), and nextMaximalSegment().
{
   //stop if s.end() == end
   while ( (s.end() != end)
        && (s.extendFront()) ) {}
 }
template<typename SC > void DGtal::maximalExtension (SC & s, const typename SC::ConstIterator & , CirculatorType)
Specialization for Circulator type
Definition at line 174 of file SegmentComputerUtils.h.
 {
   //stop if the segment is the whole range
   const typename SC::ConstIterator newEnd( s.begin() );
   while ( (s.extendFront())
     && (s.end() != newEnd) ) {}
 }
template<typename SC > void DGtal::maximalExtension (SC & s, const typename SC::ConstIterator & end)
Calls s.extendFront() while possible
Parameters
s any instance of segment computer
end any ConstIterator
Template Parameters
SC any model of segment computer
Definition at line 188 of file SegmentComputerUtils.h.
References maximalExtension().
{
   typedef typename IteratorCirculatorTraits<typename SC::ConstIterator>::Type Type;
   maximalExtension( s, end, Type() );
 }
template<typename SC > void DGtal::maximalRetraction (SC & s, const typename SC::ConstIterator & end)
Calls s.retractBack() while s.isExtendableFront() returns false
Parameters
s any instance of segment computer
end any ConstIterator
Template Parameters
SC any model of segment computer
Definition at line 323 of file SegmentComputerUtils.h.
Referenced by nextMaximalSegment().
 {
   if ( isNotEmpty<typename SC::ConstIterator>(s.end(),end) ) {
     while ( (! s.isExtendableFront() )
           &&(s.retractBack() ) )  {}
   } else {
     while ( s.retractBack() ) {}
   }
 }
template<typename SC > bool DGtal::maximalSymmetricExtension (SC & s, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end, IteratorType)
Specialization for Iterator type
Definition at line 236 of file SegmentComputerUtils.h.
Referenced by maximalSymmetricExtension(), and mostCenteredMaximalSegment().
                  {
   bool flagOk = true;
   bool flagForward = true;
   //while the extension is possible
   //at the front and (then) at the back
   while (flagOk)  {
     if (flagForward) {
       flagForward = false;
       if ( s.end() != end ) flagOk = s.extendFront();
       else flagOk = false;
     } else {
       flagForward = true;
       if ( s.begin() != begin ) flagOk = s.extendBack();
       else flagOk = false;
     }
   }
   //extend one more time if s.begin() == begin
   if (s.begin() != begin ) {
     if (s.extendBack()) return !s.extendFront();
     else return false;
   } else {
     return !flagForward;
   }
 }
template<typename SC > bool DGtal::maximalSymmetricExtension (SC & s, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end, CirculatorType)
Specialization for Circulator type
Definition at line 270 of file SegmentComputerUtils.h.
 {
   boost::ignore_unused_variable_warning( begin );
   boost::ignore_unused_variable_warning( end );
   bool flagOk = true;
   bool flagForward = true;
   //while the extensions are possible and
   //the segment does not correspond to the whole range
   while ( (flagOk) && ( s.end() != s.begin() ) )  {
     if (flagForward) {
       flagForward = false;
       flagOk = s.extendFront();
     } else {
       flagForward = true;
       flagOk = s.extendBack();
     }
   }
   return !flagForward;
 }
template<typename SC > bool DGtal::maximalSymmetricExtension (SC & s, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end)
Calls alternatively s.extendFront() and s.extendBack() while it is possible
Parameters
s any instance of (bidirectional)segment computer
begin begin iterator of a range
end end iterator of a range
Returns
'true' if the extension at the front fails first and 'false' if the extension at the back fails first
Template Parameters
SC any model of CBidirectionalSegmentComputer
Definition at line 305 of file SegmentComputerUtils.h.
References maximalSymmetricExtension().
{
   typedef typename IteratorCirculatorTraits<typename SC::ConstIterator>::Type Type;
   return maximalSymmetricExtension( s, begin, end, Type() );
 }
template<typename Ring , typename Alloc > MPolynomial<1, Ring, Alloc> DGtal::mmonomial (unsigned int e) inline
Creates a monomial in one indeterminate.
Parameters
e the exponent for X_0
Returns
the 1-variable polynomial X_0^e
Template Parameters
Ring the type for the coefficent ring of the polynomial.
Alloc the type of allocator.
Definition at line 1686 of file MPolynomial.h.
   {
     MPolynomial<1, Ring, Alloc> p;
     p[e] = 1;
     return p;
   }
template<typename Ring , typename Alloc > MPolynomial<2, Ring, Alloc> DGtal::mmonomial (unsigned int e, unsigned int f) inline
Creates a monomial in two indeterminates.
Parameters
e the exponent for X_0
f the exponent for X_1
Returns
the 2-variables polynomial X_0^e X_1^f
Template Parameters
Ring the type for the coefficent ring of the polynomial.
Alloc the type of allocator.
Definition at line 1704 of file MPolynomial.h.
   {
     MPolynomial<2, Ring, Alloc> p;
     p[e][f] = 1;
     return p;
   }
template<typename Ring , typename Alloc > MPolynomial<3, Ring, Alloc> DGtal::mmonomial (unsigned int e, unsigned int f, unsigned int g) inline
Creates a monomial in three indeterminates.
Parameters
e the exponent for X_0
f the exponent for X_1
g the exponent for X_2
Returns
the 3-variables polynomial X_0^e X_1^f X_2^g
Template Parameters
Ring the type for the coefficent ring of the polynomial.
Alloc the type of allocator.
Definition at line 1722 of file MPolynomial.h.
   {
     MPolynomial<3, Ring, Alloc> p;
     p[e][f][g] = 1;
     return p;
   }
template<typename Ring , typename Alloc > MPolynomial<4, Ring, Alloc> DGtal::mmonomial (unsigned int e, unsigned int f, unsigned int g, unsigned int h) inline
Creates a monomial in four indeterminates.
Parameters
e the exponent for X_0
f the exponent for X_1
g the exponent for X_2
h the exponent for X_3
Returns
the 3-variables polynomial X_0^e X_1^f X_2^g X_3^h
Template Parameters
Ring the type for the coefficent ring of the polynomial.
Alloc the type of allocator.
Definition at line 1742 of file MPolynomial.h.
   {
     MPolynomial<4, Ring, Alloc> p;
     p[e][f][g][h] = 1;
     return p;
   }
template<typename Ring > MPolynomial<1, Ring, std::allocator<Ring> > DGtal::mmonomial (unsigned int e) inline
Creates a monomial in one indeterminate.
Parameters
e the exponent for X_0
Returns
the 1-variable polynomial X_0^e
Template Parameters
Ring the type for the coefficent ring of the polynomial.
Definition at line 1758 of file MPolynomial.h.
   {
     MPolynomial<1, Ring, std::allocator<Ring> > p;
     p[e] = 1;
     return p;
   }
template<typename Ring > MPolynomial<2, Ring, std::allocator<Ring> > DGtal::mmonomial (unsigned int e, unsigned int f) inline
Creates a monomial in two indeterminates.
Parameters
e the exponent for X_0
f the exponent for X_1
Returns
the 2-variables polynomial X_0^e X_1^f
Template Parameters
Ring the type for the coefficent ring of the polynomial.
Definition at line 1775 of file MPolynomial.h.
   {
     MPolynomial<2, Ring, std::allocator<Ring> > p;
     p[e][f] = 1;
     return p;
   }
template<typename Ring > MPolynomial<3, Ring, std::allocator<Ring> > DGtal::mmonomial (unsigned int e, unsigned int f, unsigned int g) inline
Creates a monomial in three indeterminates.
Parameters
e the exponent for X_0
f the exponent for X_1
g the exponent for X_2
Returns
the 3-variables polynomial X_0^e X_1^f X_2^g
Template Parameters
Ring the type for the coefficent ring of the polynomial.
Definition at line 1793 of file MPolynomial.h.
   {
     MPolynomial<3, Ring, std::allocator<Ring> > p;
     p[e][f][g] = 1;
     return p;
   }
template<typename Ring > MPolynomial<4, Ring, std::allocator<Ring> > DGtal::mmonomial (unsigned int e, unsigned int f, unsigned int g, unsigned int h) inline
Creates a monomial in four indeterminates.
Parameters
e the exponent for X_0
f the exponent for X_1
g the exponent for X_2
h the exponent for X_3
Returns
the 3-variables polynomial X_0^e X_1^f X_2^g X_3^h
Template Parameters
Ring the type for the coefficent ring of the polynomial.
Definition at line 1813 of file MPolynomial.h.
   {
     MPolynomial<4, Ring, std::allocator<Ring> > p;
     p[e][f][g][h] = 1;
     return p;
   }
template<typename SC > void DGtal::mostCenteredMaximalSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end, DGtal::ForwardSegmentComputer)
Computes the most centered maximal segment passing through i
Parameters
s any instance of segment computer
i any ConstIterator
begin any begin ConstIterator bounding a range
end any end ConstIterator bounding a range
Template Parameters
SC any model of CForwardSegmentComputer
Definition at line 529 of file SegmentComputerUtils.h.
References firstMaximalSegment(), getMiddleIterator(), and longestSegment().
Referenced by mostCenteredMaximalSegment().
 {
   typedef typename SC::ConstIterator ConstIterator;
   typedef typename SC::Reverse ReverseSegmentComputer;
   typedef typename ReverseSegmentComputer::ConstIterator ConstReverseIterator;
  //get the first maximal segment passing through i
   firstMaximalSegment( s, i, begin, end, DGtal::ForwardSegmentComputer() );
  //get the next maximal segment while i is not at the middle of
  //the current maximal segment.
   ConstIterator k( s.begin() );
   while ( k != i ) {
     if ( isNotEmpty<ConstIterator>(s.end(),end) ) {
       //backward extension
       ConstIterator it( s.end() ); ++it;
       ConstReverseIterator rit( it );
       ConstReverseIterator rend( s.begin() );
       ReverseSegmentComputer r( s.getReverse() );
       longestSegment(r, rit, rend);
       ConstIterator newBegin = r.end().base();
       ASSERT( newBegin != s.begin() );
       while ( ( k != getMiddleIterator(newBegin, s.end() ) )
             &&( k != i ) ) {
         ++k;
       }
       if ( k != i ) {
         //get the next maximal segment
         longestSegment(s, newBegin, end);
       }
     } else {
       k = i;
     }
   }
 }
template<typename SC > void DGtal::mostCenteredMaximalSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end, DGtal::BidirectionalSegmentComputer)
Computes the most centered maximal segment passing through i
Parameters
s any instance of segment computer
i any ConstIterator
begin any begin ConstIterator bounding a range
end any end ConstIterator bounding a range
Template Parameters
SC any model of CBidirectionalSegmentComputer
Definition at line 587 of file SegmentComputerUtils.h.
References isNotEmpty(), maximalExtension(), maximalSymmetricExtension(), and oppositeEndMaximalExtension().
 {
   if ( (isNotEmpty(i,end)) || (isNotEmpty(i,begin)) ) {
     s.init(i);
     //symmetric extension
     if ( (isNotEmpty(i,end)) && (isNotEmpty(i,begin)) ) {
       maximalSymmetricExtension(s, begin, end);
     }
   //forward extension
   maximalExtension(s, end);
   //backward extension
   oppositeEndMaximalExtension(s, begin);
   }
 }
template<typename SC > void DGtal::mostCenteredMaximalSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end, DGtal::DynamicSegmentComputer)
Computes the most centered maximal segment passing through i
Parameters
s any instance of segment computer
i any ConstIterator
begin any begin ConstIterator bounding a range
end any end ConstIterator bounding a range
Template Parameters
SC any model of CDynamicSegmentComputer
Note
calls the function dedicated to ForwardSegmentComputer
Definition at line 623 of file SegmentComputerUtils.h.
References mostCenteredMaximalSegment().
 {
   mostCenteredMaximalSegment(s,i,begin,end,DGtal::ForwardSegmentComputer() );
 }
template<typename SC > void DGtal::mostCenteredMaximalSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end, DGtal::DynamicBidirectionalSegmentComputer)
Computes the most centered maximal segment passing through i
Parameters
s any instance of segment computer
i any ConstIterator
begin any begin ConstIterator bounding a range
end any end ConstIterator bounding a range
Template Parameters
SC any model of CDynamicBidirectionalSegmentComputer
Note
calls the function dedicated to BidirectionalSegmentComputer
Definition at line 642 of file SegmentComputerUtils.h.
References mostCenteredMaximalSegment().
 {
   mostCenteredMaximalSegment(s,i,begin,end,DGtal::BidirectionalSegmentComputer() );
 }
template<typename SC > void DGtal::mostCenteredMaximalSegment (SC & s, const typename SC::ConstIterator & i, const typename SC::ConstIterator & begin, const typename SC::ConstIterator & end)
Computes the most centered maximal segment passing through i
Parameters
s any instance of segment computer
i any ConstIterator
begin any begin ConstIterator bounding a range
end any end ConstIterator bounding a range
Template Parameters
SC any model of segment computer
Definition at line 660 of file SegmentComputerUtils.h.
 {
    mostCenteredMaximalSegment<SC>(s, i, begin, end,
 typename DGtal::SegmentComputerTraits<SC>::Category() );
 }
template<typename SC > void DGtal::nextMaximalSegment (SC & s, const typename SC::ConstIterator & end, DGtal::ForwardSegmentComputer)
Computes the next maximal segment of s (s is assumed to be maximal)
Parameters
s any instance of segment computer
end any end ConstIterator
Template Parameters
SC any model of CForwardSegmentComputer
Note
firstMaximalSegment of s.end()
Definition at line 797 of file SegmentComputerUtils.h.
References firstMaximalSegment().
Referenced by nextMaximalSegment().
 {
   firstMaximalSegment(s, s.end(), s.begin(), end, ForwardSegmentComputer() );
 }
template<typename SC > void DGtal::nextMaximalSegment (SC & s, const typename SC::ConstIterator & end, DGtal::BidirectionalSegmentComputer)
Computes the next maximal segment of s (s is assumed to be maximal)
Parameters
s any instance of segment computer
end end ConstIterator
Template Parameters
SC any model of CBidirectionalSegmentComputer
Note
firstMaximalSegment of s.end()
Definition at line 813 of file SegmentComputerUtils.h.
References firstMaximalSegment().
 {
   firstMaximalSegment(s, s.end(), s.begin(), end, DGtal::BidirectionalSegmentComputer() );
 }
template<typename SC > void DGtal::nextMaximalSegment (SC & s, const typename SC::ConstIterator & end, DGtal::DynamicSegmentComputer)
Computes the next maximal segment of s (s is assumed to be maximal)
Parameters
s any instance of segment computer
end end ConstIterator
Template Parameters
SC any model of CDynamicSegmentComputer
Definition at line 828 of file SegmentComputerUtils.h.
References maximalExtension(), and maximalRetraction().
 {
   typedef typename SC::ConstIterator ConstIterator;
   //rectract
   maximalRetraction(s, end);
   //intersection test
   ConstIterator i( s.begin() ); ++i;
   //if the intersection between the two
   // consecutive maximal segments is empty
   if ( i == s.end() ) {
     if ( isNotEmpty<ConstIterator>(i, end) ) {
       ++i;
       s.init(i);
     }
   }
   //extend
   maximalExtension(s, end);
 }
template<typename SC > void DGtal::nextMaximalSegment (SC & s, const typename SC::ConstIterator & end, DGtal::DynamicBidirectionalSegmentComputer)
Computes the next maximal segment of s (s is assumed to be maximal)
Parameters
s any instance of segment computer
end end ConstIterator
Template Parameters
SC any model of CDynamicBidirectionalSegmentComputer
Note
calls the function dedicated to DynamicSegmentComputer
Definition at line 861 of file SegmentComputerUtils.h.
References nextMaximalSegment().
 {
   nextMaximalSegment(s, end, DGtal::DynamicSegmentComputer() );
 }
template<typename SC > void DGtal::nextMaximalSegment (SC & s, const typename SC::ConstIterator & end)
Computes the next maximal segment of s (s is assumed to be maximal)
Parameters
s any instance of segment computer
end any end ConstIterator
Template Parameters
SC any model of segment computer
Definition at line 876 of file SegmentComputerUtils.h.
 {
    nextMaximalSegment<SC>(s, end,
 typename DGtal::SegmentComputerTraits<SC>::Category() );
 }
template<typename Calculus , Order order_in, Duality duality_in, Order order_out, Duality duality_out> LinearOperator<Calculus, order_in, duality_in, order_out, duality_out> DGtal::operator* (const typename Calculus::Scalar & scalar, const LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > & linear_operator)
Overloads 'operator*' for scalar multiplication of objects of class 'LinearOperator'.
Parameters
scalar left operant
linear_operator right operant
Returns
scalar * linear_operator.
template<typename Calculus , Order order_in, Duality duality_in, Order order_fold, Duality duality_fold, Order order_out, Duality duality_out> LinearOperator<Calculus, order_in, duality_in, order_out, duality_out> DGtal::operator* (const LinearOperator< Calculus, order_fold, duality_fold, order_out, duality_out > & operator_left, const LinearOperator< Calculus, order_in, duality_in, order_fold, duality_fold > & operator_right)
Overloads 'operator*' for internal multiplication of objects of class 'LinearOperator'.
Parameters
operator_left left operant
operator_right right operant
Returns
operator_left * operator_right.
template<typename Calculus , Order order_in, Duality duality_in, Order order_out, Duality duality_out> KForm<Calculus, order_out, duality_out> DGtal::operator* (const LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > & linear_operator, const KForm< Calculus, order_in, duality_in > & input_form)
Overloads 'operator*' for application of objects of class 'LinearOperator' on objects of class 'KForm'.
Parameters
linear_operator left operant
input_form right operant
Returns
linear_operator * input_form.
template<typename Calculus , Order order, Duality duality> KForm<Calculus, order, duality> DGtal::operator* (const typename Calculus::Scalar & scalar, const KForm< Calculus, order, duality > & form)
Overloads 'operator*' for scalar multiplication of objects of class 'KForm'.
Parameters
scalar left operant
form right operant
Returns
scalar * form.
template<typename Calculus , Duality duality> VectorField<Calculus, duality> DGtal::operator* (const typename Calculus::Scalar & scalar, const VectorField< Calculus, duality > & vector_field)
Overloads 'operator*' for scalar multiplication of objects of class 'VectorField'.
Parameters
scalar left operant
vector_field right operant
Returns
scalar * vector_field.
template<typename TComponent , DGtal::Dimension TM, DGtal::Dimension TN> SimpleMatrix<TComponent, TM, TN> DGtal::operator* (const TComponent & scalar, const SimpleMatrix< TComponent, TM, TN > & matrix)
External scalar multiplication
Color DGtal::operator* (const double coeff, const Color & aColor)
External multiplication operator with a scalar number
Parameters
coeff is the factor Color is multiplied by.
aColor is the vector that is multiplied by the factor coef.
Returns
a new Vector that is the multiplication of aVector by coeff.
template<Dimension dim, typename Component , typename Container > PointVector<dim, Component,Container> DGtal::operator* (Component coeff, const PointVector< dim, Component, Container > & aVector)
External multiplication operator with a scalar number
Parameters
coeff is the factor aVector is multiplied by.
aVector is the vector that is multiplied by the factor coef.
Returns
a new Vector that is the multiplication of aVector by coeff.
template<typename Calculus , Order order_in, Duality duality_in, Order order_out, Duality duality_out> LinearOperator<Calculus, order_in, duality_in, order_out, duality_out> DGtal::operator+ (const LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > & linear_operator_a, const LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > & linear_operator_b)
Overloads 'operator+' for adding objects of class 'LinearOperator'.
Parameters
linear_operator_a left operant
linear_operator_b right operant
Returns
linear_operator_a + linear_operator_b.
template<typename Calculus , Order order, Duality duality> KForm<Calculus, order, duality> DGtal::operator+ (const KForm< Calculus, order, duality > & form_a, const KForm< Calculus, order, duality > & form_b)
Overloads 'operator+' for adding objects of class 'KForm'.
Parameters
form_a left operant
form_b right operant
Returns
form_a + form_b.
template<typename Calculus , Duality duality> VectorField<Calculus, duality> DGtal::operator+ (const VectorField< Calculus, duality > & vector_field_a, const VectorField< Calculus, duality > & vector_field_b)
Overloads 'operator+' for adding objects of class 'VectorField'.
Parameters
vector_field_a left operant
vector_field_b right operant
Returns
vector_field_a + vector_field_b.
template<typename TIterator > Circulator<TIterator> DGtal::operator+ (typename IteratorCirculatorTraits< TIterator >::Difference d, Circulator< TIterator > & object)
Definition at line 453 of file Circulator.h.
   {
     Circulator<TIterator> tmp = object;
     return tmp += d;
   }
template<typename Calculus , Order order_in, Duality duality_in, Order order_out, Duality duality_out> LinearOperator<Calculus, order_in, duality_in, order_out, duality_out> DGtal::operator- (const LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > & linear_operator_a, const LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > & linear_operator_b)
Overloads 'operator-' for substracting objects of class 'LinearOperator'.
Parameters
linear_operator_a left operant
linear_operator_b right operant
Returns
linear_operator_a - linear_operator_b.
template<typename Calculus , Order order, Duality duality> KForm<Calculus, order, duality> DGtal::operator- (const KForm< Calculus, order, duality > & form_a, const KForm< Calculus, order, duality > & form_b)
Overloads 'operator-' for substracting objects of class 'KForm'.
Parameters
form_a left operant
form_b right operant
Returns
form_a - form_b.
template<typename Calculus , Duality duality> VectorField<Calculus, duality> DGtal::operator- (const VectorField< Calculus, duality > & vector_field_a, const VectorField< Calculus, duality > & vector_field_b)
Overloads 'operator-' for substracting objects of class 'VectorField'.
Parameters
vector_field_a left operant
vector_field_b right operant
Returns
vector_field_a - vector_field_b.
template<typename Calculus , Order order, Duality duality> KForm<Calculus, order, duality> DGtal::operator- (const KForm< Calculus, order, duality > & form)
Overloads 'operator-' for unary additive inverse of objects of class 'KForm'.
Parameters
form operant
Returns
-form.
template<typename Calculus , Order order_in, Duality duality_in, Order order_out, Duality duality_out> LinearOperator<Calculus, order_in, duality_in, order_out, duality_out> DGtal::operator- (const LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > & linear_operator)
Overloads 'operator-' for unary additive inverse of objects of class 'LinearOperator'.
Parameters
linear_operator operant
Returns
-linear_operator.
template<typename Calculus , Duality duality> VectorField<Calculus, duality> DGtal::operator- (const VectorField< Calculus, duality > & vector_field)
Overloads 'operator-' for unary additive inverse of objects of class 'VectorField'.
Parameters
vector_field operant
Returns
-vector_field
std::ostream& DGtal::operator<< (std::ostream & out, const Duality & object)
Overloads 'operator<<' for displaying objects of class 'Duality'.
Parameters
out the output stream where the object is written.
object the object of class 'Duality' to write.
Returns
the output stream after the writing.
std::ostream& DGtal::operator<< (std::ostream & os, const Eigen::ComputationInfo & info) inline
Overloads 'operator<<' for displaying objects of class 'Eigen::ComputationInfo'.
Parameters
os the output stream where the object is written.
info the object of class 'EigenSupport' to write.
Returns
the output stream after the writing.
Definition at line 124 of file EigenSupport.h.
 {
     switch (info)
     {
         case Eigen::Success:
             os << "success";
             break;
         case Eigen::NumericalIssue:
             os << "numerical_issue";
             break;
         case Eigen::NoConvergence:
             os << "no_convergence";
             break;
         case Eigen::InvalidInput:
             os << "invalid_input";
             break;
     }
     return os;
 }
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const BLUELocalLengthEstimator< T > & object)
Overloads 'operator<<' for displaying objects of class 'BLUELocalLengthEstimator'.
Parameters
out the output stream where the object is written.
object the object of class 'BLUELocalLengthEstimator' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const RosenProffittLocalLengthEstimator< T > & object)
Overloads 'operator<<' for displaying objects of class 'RosenProffittLocalLengthEstimator'.
Parameters
out the output stream where the object is written.
object the object of class 'RosenProffittLocalLengthEstimator' to write.
Returns
the output stream after the writing.
std::ostream& DGtal::operator<< (std::ostream & out, const TraceWriter & object)
Overloads 'operator<<' for displaying objects of class 'TraceWriter'.
Parameters
out the output stream where the object is written.
object the object of class 'TraceWriter' to write.
Returns
the output stream after the writing.
template<typename C , typename S , Order order_in, Duality duality_in, Order order_out, Duality duality_out> std::ostream& DGtal::operator<< (std::ostream & out, const DiscreteExteriorCalculusSolver< C, S, order_in, duality_in, order_out, duality_out > & object)
Overloads 'operator<<' for displaying objects of class 'DiscreteExteriorCalculusSolver'.
Parameters
out the output stream where the object is written.
object the object of class 'DiscreteExteriorCalculusSolver' to write.
Returns
the output stream after the writing.
std::ostream& DGtal::operator<< (std::ostream & out, const TraceWriterFile & object)
Overloads 'operator<<' for displaying objects of class 'TraceWriterFile'.
Parameters
out the output stream where the object is written.
object the object of class 'TraceWriterFile' to write.
Returns
the output stream after the writing.
template<typename TPoint > bool DGtal::operator<< (Mesh< TPoint > & mesh, const std::string & filename)
'operator<<' for exporting objects of class 'Mesh'.
Parameters
mesh a mesh
filename a filename
Returns
true if the mesh has been exported correctly.
template<Dimension dim, typename TInteger > std::ostream& DGtal::operator<< (std::ostream & out, const KhalimskyPreCell< dim, TInteger > & object)
template<typename TSpace > std::ostream& DGtal::operator<< (std::ostream & out, const ClosedIntegerHalfPlane< TSpace > & object)
Overloads 'operator<<' for displaying objects of class 'ClosedIntegerHalfPlane'.
Parameters
out the output stream where the object is written.
object the object of class 'ClosedIntegerHalfPlane' to write.
Returns
the output stream after the writing.
std::ostream& DGtal::operator<< (std::ostream & out, const Clock & object) inline
Overloads 'operator<<' for displaying objects of class 'Clock'.
Parameters
out the output stream where the object is written.
object the object of class 'Clock' to write.
Returns
the output stream after the writing.
Definition at line 164 of file Clock.h.
     {
       object.selfDisplay( out );
       return out;
     }
template<typename TSpace > std::ostream& DGtal::operator<< (std::ostream & out, const CanonicEmbedder< TSpace > & object)
Overloads 'operator<<' for displaying objects of class 'CanonicEmbedder'.
Parameters
out the output stream where the object is written.
object the object of class 'CanonicEmbedder' to write.
Returns
the output stream after the writing.
template<Dimension dim> std::ostream& DGtal::operator<< (std::ostream & out, const SurfelAdjacency< dim > & object)
Overloads 'operator<<' for displaying objects of class 'SurfelAdjacency'.
Parameters
out the output stream where the object is written.
object the object of class 'SurfelAdjacency' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const L1LengthEstimator< T > & object)
Overloads 'operator<<' for displaying objects of class 'L1LengthEstimator'.
Parameters
out the output stream where the object is written.
object the object of class 'L1LengthEstimator' to write.
Returns
the output stream after the writing.
template<typename TKSpace , typename TImage > std::ostream& DGtal::operator<< (std::ostream & out, const DGtal::functors::BoundaryPredicate< TKSpace, TImage > & object)
Overloads 'operator<<' for displaying objects of class 'BoundaryPredicate'.
Parameters
out the output stream where the object is written.
object the object of class 'BoundaryPredicate' to write.
Returns
the output stream after the writing.
template<typename Calculus , Order order_in, Duality duality_in, Order order_out, Duality duality_out> std::ostream& DGtal::operator<< (std::ostream & out, const LinearOperator< Calculus, order_in, duality_in, order_out, duality_out > & object)
Overloads 'operator<<' for displaying objects of class 'LinearOperator'.
Parameters
out the output stream where the object is written.
object the object of class 'LinearOperator' to write.
Returns
the output stream after the writing.
template<typename TKSpace , typename TImage > std::ostream& DGtal::operator<< (std::ostream & out, const DGtal::functors::FrontierPredicate< TKSpace, TImage > & object)
Overloads 'operator<<' for displaying objects of class 'FrontierPredicate'.
Parameters
out the output stream where the object is written.
object the object of class 'FrontierPredicate' to write.
Returns
the output stream after the writing.
template<typename TKSpace > std::ostream& DGtal::operator<< (std::ostream & out, const CanonicCellEmbedder< TKSpace > & object)
Overloads 'operator<<' for displaying objects of class 'CanonicCellEmbedder'.
Parameters
out the output stream where the object is written.
object the object of class 'CanonicCellEmbedder' to write.
Returns
the output stream after the writing.
template<typename TKSpace > std::ostream& DGtal::operator<< (std::ostream & out, const CanonicSCellEmbedder< TKSpace > & object)
Overloads 'operator<<' for displaying objects of class 'CanonicSCellEmbedder'.
Parameters
out the output stream where the object is written.
object the object of class 'CanonicSCellEmbedder' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const FPLengthEstimator< T > & object)
Overloads 'operator<<' for displaying objects of class 'FPLengthEstimator'.
Parameters
out the output stream where the object is written.
object the object of class 'FPLengthEstimator' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const MLPLengthEstimator< T > & object)
Overloads 'operator<<' for displaying objects of class 'MLPLengthEstimator'.
Parameters
out the output stream where the object is written.
object the object of class 'MLPLengthEstimator' to write.
Returns
the output stream after the writing.
template<typename TOrientationFunctor , bool acceptNeg, bool acceptZero> std::ostream& DGtal::operator<< (std::ostream & out, const PredicateFromOrientationFunctor2< TOrientationFunctor, acceptNeg, acceptZero > & object)
Overloads 'operator<<' for displaying objects of class 'PredicateFromOrientationFunctor2'.
Parameters
out the output stream where the object is written.
object the object of class 'PredicateFromOrientationFunctor2' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const Measure< T > & object)
Overloads 'operator<<' for displaying objects of class 'Measure'.
Parameters
out the output stream where the object is written.
object the object of class 'Measure' to write.
Returns
the output stream after the writing.
std::ostream& DGtal::operator<< (std::ostream & out, const ContourHelper & object)
Overloads 'operator<<' for displaying objects of class 'ContourHelper'.
Parameters
out the output stream where the object is written.
object the object of class 'ContourHelper' to write.
Returns
the output stream after the writing.
template<typename TDigitalSurface , typename TNormalVectorEstimator , typename TEmbedder > std::ostream& DGtal::operator<< (std::ostream & out, const NormalVectorEstimatorLinearCellEmbedder< TDigitalSurface, TNormalVectorEstimator, TEmbedder > & object)
Overloads 'operator<<' for displaying objects of class 'NormalVectorEstimatorLinearCellEmbedder'.
Parameters
out the output stream where the object is written.
object the object of class 'NormalVectorEstimatorLinearCellEmbedder' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const TwoStepLocalLengthEstimator< T > & object)
Overloads 'operator<<' for displaying objects of class 'TwoStepLocalLengthEstimator'.
Parameters
out the output stream where the object is written.
object the object of class 'TwoStepLocalLengthEstimator' to write.
Returns
the output stream after the writing.
template<typename TSequence > std::ostream& DGtal::operator<< (std::ostream & out, const BackInsertionSequenceToStackAdapter< TSequence > & object)
Overloads 'operator<<' for displaying objects of class 'BackInsertionSequenceToStackAdapter'.
Parameters
out the output stream where the object is written.
object the object of class 'BackInsertionSequenceToStackAdapter' to write.
Returns
the output stream after the writing.
template<typename TSequence > std::ostream& DGtal::operator<< (std::ostream & out, const FrontInsertionSequenceToStackAdapter< TSequence > & object)
Overloads 'operator<<' for displaying objects of class 'FrontInsertionSequenceToStackAdapter'.
Parameters
out the output stream where the object is written.
object the object of class 'FrontInsertionSequenceToStackAdapter' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const ImplicitBall< T > & object)
Overloads 'operator<<' for displaying objects of class 'ImplicitBall'.
Parameters
out the output stream where the object is written.
object the object of class 'ImplicitBall' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const DSSLengthEstimator< T > & object)
Overloads 'operator<<' for displaying objects of class 'DSSLengthEstimator'.
Parameters
out the output stream where the object is written.
object the object of class 'DSSLengthEstimator' to write.
Returns
the output stream after the writing.
template<typename TDigitalSurface > std::ostream& DGtal::operator<< (std::ostream & out, const CanonicDigitalSurfaceEmbedder< TDigitalSurface > & object)
Overloads 'operator<<' for displaying objects of class 'CanonicDigitalSurfaceEmbedder'.
Parameters
out the output stream where the object is written.
object the object of class 'CanonicDigitalSurfaceEmbedder' to write.
Returns
the output stream after the writing.
std::ostream& DGtal::operator<< (std::ostream & out, const TraceWriterTerm & object)
Overloads 'operator<<' for displaying objects of class 'TraceWriterTerm'.
Parameters
out the output stream where the object is written.
object the object of class 'TraceWriterTerm' to write.
Returns
the output stream after the writing.
std::ostream& DGtal::operator<< (std::ostream & out, const Board2D & object)
Overloads 'operator<<' for displaying objects of class 'Board2D'.
Parameters
out the output stream where the object is written.
object the object of class 'Board2D' to write.
Returns
the output stream after the writing.
std::ostream& DGtal::operator<< (std::ostream & out, const RandomColorMap & object)
Overloads 'operator<<' for displaying objects of class 'RandomColorMap'.
Parameters
out the output stream where the object is written.
object the object of class 'RandomColorMap' to write.
Returns
the output stream after the writing.
template<typename TPoint , typename TInteger > std::ostream& DGtal::operator<< (std::ostream & out, const InHalfPlaneBySimple3x3Matrix< TPoint, TInteger > & object)
Overloads 'operator<<' for displaying objects of class 'InHalfPlaneBySimple3x3Matrix'.
Parameters
out the output stream where the object is written.
object the object of class 'InHalfPlaneBySimple3x3Matrix' to write.
Returns
the output stream after the writing.
template<typename TF , typename TKS > std::ostream& DGtal::operator<< (std::ostream & out, const FunctorOnCells< TF, TKS > & object)
Overloads 'operator<<' for displaying objects of class 'FunctorOnCells'.
Parameters
out the output stream where the object is written.
object the object of class 'FunctorOnCells' to write.
Returns
the output stream after the writing.
template<Dimension dim, typename TInteger > std::ostream& DGtal::operator<< (std::ostream & out, const KhalimskyCell< dim, TInteger > & object)
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const OwningOrAliasingPtr< T > & object)
Overloads 'operator<<' for displaying objects of class 'OwningOrAliasingPtr'.
Parameters
out the output stream where the object is written.
object the object of class 'OwningOrAliasingPtr' to write.
Returns
the output stream after the writing.
template<typename Calculus , Order order, Duality duality> std::ostream& DGtal::operator<< (std::ostream & out, const KForm< Calculus, order, duality > & object)
Overloads 'operator<<' for displaying objects of class 'KForm'.
Parameters
out the output stream where the object is written.
object the object of class 'KForm' to write.
Returns
the output stream after the writing.
template<typename TO , typename TD , typename TS > std::ostream& DGtal::operator<< (std::ostream & out, const KanungoNoise< TO, TD, TS > & object)
Overloads 'operator<<' for displaying objects of class 'KanungoNoise'.
Parameters
out the output stream where the object is written.
object the object of class 'KanungoNoise' to write.
Returns
the output stream after the writing.
template<typename Space , typename KSpace > std::ostream& DGtal::operator<< (std::ostream & out, const Board3D< Space, KSpace > & object)
Overloads 'operator<<' for displaying objects of class 'Board3D'.
Parameters
out the output stream where the object is written.
object the object of class 'Board3D' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const Filtered2x2DetComputer< T > & object)
Overloads 'operator<<' for displaying objects of class 'Filtered2x2DetComputer'.
Parameters
out the output stream where the object is written.
object the object of class 'Filtered2x2DetComputer' to write.
Returns
the output stream after the writing.
template<typename TSpace > std::ostream& DGtal::operator<< (std::ostream & out, const RegularPointEmbedder< TSpace > & object)
Overloads 'operator<<' for displaying objects of class 'RegularPointEmbedder'.
Parameters
out the output stream where the object is written.
object the object of class 'RegularPointEmbedder' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const CowPtr< T > & object)
Overloads 'operator<<' for displaying objects of class 'CowPtr'.
Parameters
out the output stream where the object is written.
object the object of class 'CowPtr' to write.
Returns
the output stream after the writing.
template<typename TKSpace , typename TImplicitFunction , typename TEmbedder > std::ostream& DGtal::operator<< (std::ostream & out, const ImplicitFunctionLinearCellEmbedder< TKSpace, TImplicitFunction, TEmbedder > & object)
Overloads 'operator<<' for displaying objects of class 'ImplicitFunctionLinearCellEmbedder'.
Parameters
out the output stream where the object is written.
object the object of class 'ImplicitFunctionLinearCellEmbedder' to write.
Returns
the output stream after the writing.
template<typename TPoint , typename TDetComputer > std::ostream& DGtal::operator<< (std::ostream & out, const InHalfPlaneBy2x2DetComputer< TPoint, TDetComputer > & object)
Overloads 'operator<<' for displaying objects of class 'InHalfPlaneBy2x2DetComputer'.
Parameters
out the output stream where the object is written.
object the object of class 'InHalfPlaneBy2x2DetComputer' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const ModuloComputer< T > & object)
Displays object on the output stream out.
Template Parameters
T the type of integer for the modulo computer.
Parameters
out the output stream
object the object to display.
Definition at line 206 of file ModuloComputer.h.
   {
     object.selfDisplay( out );
     return out;
   }
template<typename Calculus , Duality duality> std::ostream& DGtal::operator<< (std::ostream & out, const VectorField< Calculus, duality > & object)
Overloads 'operator<<' for displaying objects of class 'VectorField'.
Parameters
out the output stream where the object is written.
object the object of class 'VectorField' to write.
Returns
the output stream after the writing.
template<typename TPoint > std::ostream& DGtal::operator<< (std::ostream & out, const StraightLineFrom2Points< TPoint > & object) inline
Overloads 'operator<<' for displaying objects of class 'StraightLineFrom2Points'.
Parameters
out the output stream where the object is written.
object the object of class 'StraightLineFrom2Points' to write.
Returns
the output stream after the writing.
Definition at line 210 of file StraightLineFrom2Points.h.
   {
     object.selfDisplay( out );
     return out;
   }
template<typename TKSpace , typename TImage , typename TEmbedder > std::ostream& DGtal::operator<< (std::ostream & out, const ImageLinearCellEmbedder< TKSpace, TImage, TEmbedder > & object)
Overloads 'operator<<' for displaying objects of class 'ImageLinearCellEmbedder'.
Parameters
out the output stream where the object is written.
object the object of class 'ImageLinearCellEmbedder' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const ImplicitNorm1Ball< T > & object)
Overloads 'operator<<' for displaying objects of class 'ImplicitNorm1Ball'.
Parameters
out the output stream where the object is written.
object the object of class 'ImplicitNorm1Ball' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const ImplicitHyperCube< T > & object)
Overloads 'operator<<' for displaying objects of class 'ImplicitHyperCube'.
Parameters
out the output stream where the object is written.
object the object of class 'ImplicitHyperCube' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const DigitalSetDomain< T > & object)
Overloads 'operator<<' for displaying objects of class 'DigitalSetDomain'.
Parameters
out the output stream where the object is written.
object the object of class 'DigitalSetDomain' to write.
Returns
the output stream after the writing.
template<typename TImageContainer > std::ostream& DGtal::operator<< (std::ostream & out, const ImageFactoryFromImage< TImageContainer > & object)
Overloads 'operator<<' for displaying objects of class 'ImageFactoryFromImage'.
Parameters
out the output stream where the object is written.
object the object of class 'ImageFactoryFromImage' to write.
Returns
the output stream after the writing.
template<typename PValue > std::ostream& DGtal::operator<< (std::ostream & out, const GrayscaleColorMap< PValue > & object)
Overloads 'operator<<' for displaying objects of class 'GrayscaleColorMap'.
Parameters
out the output stream where the object is written.
object the object of class 'GrayscaleColorMap' to write.
Returns
the output stream after the writing.
template<typename TPoint > std::ostream& DGtal::operator<< (std::ostream & out, const CircleFrom2Points< TPoint > & object) inline
Overloads 'operator<<' for displaying objects of class 'CircleFrom2Points'.
Parameters
out the output stream where the object is written.
object the object of class 'CircleFrom2Points' to write.
Returns
the output stream after the writing.
Definition at line 226 of file CircleFrom2Points.h.
   {
     object.selfDisplay( out );
     return out;
   }
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const DigitalMetricAdapter< T > & object)
Overloads 'operator<<' for displaying objects of class 'DigitalMetricAdapter'.
Parameters
out the output stream where the object is written.
object the object of class 'DigitalMetricAdapter' to write.
Returns
the output stream after the writing.
template<typename TValue , typename CMAP > std::ostream& DGtal::operator<< (std::ostream & out, const TickedColorMap< TValue, CMAP > & object)
Overloads 'operator<<' for displaying objects of class 'TickedColorMap'.
Parameters
out the output stream where the object is written.
object te output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const Ball2D< T > & object)
Overloads 'operator<<' for displaying objects of class 'Ball2D'.
Parameters
out the output stream where the object is written.
object the object of class 'Ball2D' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const ImplicitRoundedHyperCube< T > & object)
Overloads 'operator<<' for displaying objects of class 'ImplicitRoundedHyperCube'.
Parameters
out the output stream where the object is written.
object the object of class 'ImplicitRoundedHyperCube' to write.
Returns
the output stream after the writing.
template<typename TSequence , typename TRank > std::ostream& DGtal::operator<< (std::ostream & out, const InputIteratorWithRankOnSequence< TSequence, TRank > & object)
Overloads 'operator<<' for displaying objects of class 'InputIteratorWithRankOnSequence'.
Parameters
out the output stream where the object is written.
object the object of class 'InputIteratorWithRankOnSequence' to write.
Returns
the output stream after the writing.
template<typename TSpace > std::ostream& DGtal::operator<< (std::ostream & out, const SpatialCubicalSubdivision< TSpace > & object)
Overloads 'operator<<' for displaying objects of class 'SpatialCubicalSubdivision'.
Parameters
out the output stream where the object is written.
object the object of class 'SpatialCubicalSubdivision' to write.
Returns
the output stream after the writing.
template<typename TI , typename TO > std::ostream& DGtal::operator<< (std::ostream & out, const Simple2x2DetComputer< TI, TO > & object)
Overloads 'operator<<' for displaying objects of class 'Simple2x2DetComputer'.
Parameters
out the output stream where the object is written.
object the object of class 'Simple2x2DetComputer' to write.
Returns
the output stream after the writing.
template<typename TForegroundAdjacency , typename TBackgroundAdjacency > std::ostream& DGtal::operator<< (std::ostream & out, const DigitalTopology< TForegroundAdjacency, TBackgroundAdjacency > & object)
Overloads 'operator<<' for displaying objects of class 'DigitalTopology'.
Parameters
out the output stream where the object is written.
object the object of class 'DigitalTopology' to write.
Returns
the output stream after the writing.
template<typename TPoint > std::ostream& DGtal::operator<< (std::ostream & out, const CircleFrom3Points< TPoint > & object) inline
Overloads 'operator<<' for displaying objects of class 'CircleFrom3Points'.
Parameters
out the output stream where the object is written.
object the object of class 'CircleFrom3Points' to write.
Returns
the output stream after the writing.
Definition at line 236 of file CircleFrom3Points.h.
   {
     object.selfDisplay( out );
     return out;
   }
std::ostream& DGtal::operator<< (std::ostream & out, const Trace & object)
Overloads 'operator<<' for displaying objects of class 'Trace'.
Parameters
out the output stream where the object is written.
object the object of class 'Trace' to write.
Returns
the output stream after the writing.
template<typename TPoint , typename TOrientationFunctor > std::ostream& DGtal::operator<< (std::ostream & out, const MelkmanConvexHull< TPoint, TOrientationFunctor > & object)
Overloads 'operator<<' for displaying objects of class 'MelkmanConvexHull'.
Parameters
out the output stream where the object is written.
object the object of class 'MelkmanConvexHull' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const Astroid2D< T > & object)
Overloads 'operator<<' for displaying objects of class 'Astroid2D'.
Parameters
out the output stream where the object is written.
object the object of class 'Astroid2D' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const Lemniscate2D< T > & object)
Overloads 'operator<<' for displaying objects of class 'Lemniscate2D'.
Parameters
out the output stream where the object is written.
object the object of class 'Lemniscate2D' to write.
Returns
the output stream after the writing.
template<typename PValue , int DefaultCycles> std::ostream& DGtal::operator<< (std::ostream & out, const HueShadeColorMap< PValue, DefaultCycles > & object)
Overloads 'operator<<' for displaying objects of class 'HueShadeColorMap'.
Parameters
out the output stream where the object is written.
object the object of class 'HueShadeColorMap' to write.
Returns
the output stream after the writing.
template<typename PValue , int PDefaultColor> std::ostream& DGtal::operator<< (std::ostream & out, const ColorBrightnessColorMap< PValue, PDefaultColor > & object)
Overloads 'operator<<' for displaying objects of class 'ColorBrightnessColorMap'.
Parameters
out the output stream where the object is written.
object the object of class 'ColorBrightnessColorMap' to write.
Returns
the output stream after the writing.
template<typename TSpace , Dimension maxNorm1> std::ostream& DGtal::operator<< (std::ostream & out, const MetricAdjacency< TSpace, maxNorm1, TSpace::dimension > & object)
Overloads 'operator<<' for displaying objects of class 'MetricAdjacency'.
Parameters
out the output stream where the object is written.
object the object of class 'MetricAdjacency' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const Ellipse2D< T > & object)
Overloads 'operator<<' for displaying objects of class 'Ellipse2D'.
Parameters
out the output stream where the object is written.
object the object of class 'Ellipse2D' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const NGon2D< T > & object)
Overloads 'operator<<' for displaying objects of class 'NGon2D'.
Parameters
out the output stream where the object is written.
object the object of class 'NGon2D' to write.
Returns
the output stream after the writing.
template<Dimension dim, typename TInteger > std::ostream& DGtal::operator<< (std::ostream & out, const SignedKhalimskyPreCell< dim, TInteger > & object)
template<typename W , typename TSep > std::ostream& DGtal::operator<< (std::ostream & out, const ReverseDistanceTransformation< W, TSep > & object) inline
Definition at line 257 of file ReverseDistanceTransformation.h.
   {
     object.selfDisplay( out );
     return out;
   }
template<typename S , typename P , typename TSep > std::ostream& DGtal::operator<< (std::ostream & out, const DistanceTransformation< S, P, TSep > & object) inline
Definition at line 259 of file DistanceTransformation.h.
   {
     object.selfDisplay( out );
     return out;
   }
template<typename TDomain , typename TValue > std::ostream& DGtal::operator<< (std::ostream & out, const ImageContainerBySTLMap< TDomain, TValue > & object) inline
Overloads 'operator<<' for displaying objects of class 'Image'.
Parameters
out the output stream where the object is written.
object the object of class 'Image' to write.
Returns
the output stream after the writing.
Definition at line 262 of file ImageContainerBySTLMap.h.
   {
     object.selfDisplay ( out );
     return out;
   }
template<typename TM > std::ostream& DGtal::operator<< (std::ostream & out, const SeparableMetricAdapter< TM > & object)
Overloads 'operator<<' for displaying objects of class 'SeparableMetricAdapter'.
Parameters
out the output stream where the object is written.
object the object of class 'SeparableMetricAdapter' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const Flower2D< T > & object)
Overloads 'operator<<' for displaying objects of class 'Flower2D'.
Parameters
out the output stream where the object is written.
object the object of class 'Flower2D' to write.
Returns
the output stream after the writing.
template<typename TDomain , typename TAdjacency > std::ostream& DGtal::operator<< (std::ostream & out, const DomainAdjacency< TDomain, TAdjacency > & object)
Overloads 'operator<<' for displaying objects of class 'DomainAdjacency'.
Parameters
out the output stream where the object is written.
object the object of class 'DomainAdjacency' to write.
Returns
the output stream after the writing.
template<typename TKSpace , typename TShape , typename TGeometricFunctor > std::ostream& DGtal::operator<< (std::ostream & out, const TrueDigitalSurfaceLocalEstimator< TKSpace, TShape, TGeometricFunctor > & object)
Overloads 'operator<<' for displaying objects of class 'TrueDigitalSurfaceLocalEstimator'.
Parameters
out the output stream where the object is written.
object the object of class 'TrueDigitalSurfaceLocalEstimator' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const ImplicitPolynomial3Shape< T > & object)
Overloads 'operator<<' for displaying objects of class 'ImplicitPolynomial3Shape'.
Parameters
out the output stream where the object is written.
object the object of class 'ImplicitPolynomial3Shape' to write.
Returns
the output stream after the writing.
template<typename T , typename V > std::ostream& DGtal::operator<< (std::ostream & out, const InexactPredicateLpSeparableMetric< T, V > & object)
Overloads 'operator<<' for displaying objects of class 'InexactPredicateLpSeparableMetric'.
Parameters
out the output stream where the object is written.
object the object of class 'InexactPredicateLpSeparableMetric' to write.
Returns
the output stream after the writing.
template<typename TSpace , bool muIncluded, bool muPlusNuIncluded> std::ostream& DGtal::operator<< (std::ostream & out, const ParallelStrip< TSpace, muIncluded, muPlusNuIncluded > & object)
Overloads 'operator<<' for displaying objects of class 'ParallelStrip'.
Parameters
out the output stream where the object is written.
object the object of class 'ParallelStrip' to write.
Returns
the output stream after the writing.
template<typename TIterableClass > std::ostream& DGtal::operator<< (std::ostream & out, const ArrayImageIterator< TIterableClass > & object)
Overloads 'operator<<' for displaying objects of class 'ArrayImageIterator'.
Parameters
out the output stream where the object is written.
object the object of class 'ArrayImageIterator' to write.
Returns
the output stream after the writing.
template<typename TDomain > std::ostream& DGtal::operator<< (std::ostream & out, const Shapes< TDomain > & object)
Overloads 'operator<<' for displaying objects of class 'Shapes'.
Parameters
out the output stream where the object is written.
object the object of class 'Shapes' to write.
Returns
the output stream after the writing.
template<typename TSpace , typename TEuclideanShape > std::ostream& DGtal::operator<< (std::ostream & out, const GaussDigitizer< TSpace, TEuclideanShape > & object)
Overloads 'operator<<' for displaying objects of class 'GaussDigitizer'.
Parameters
out the output stream where the object is written.
object the object of class 'GaussDigitizer' to write.
Returns
the output stream after the writing.
template<typename TDigitalSurfaceEmbedder , typename TNormalVectorEstimator > std::ostream& DGtal::operator<< (std::ostream & out, const DigitalSurfaceEmbedderWithNormalVectorEstimator< TDigitalSurfaceEmbedder, TNormalVectorEstimator > & object)
Overloads 'operator<<' for displaying objects of class 'DigitalSurfaceEmbedderWithNormalVectorEstimator'.
Parameters
out the output stream where the object is written.
object the object of class 'DigitalSurfaceEmbedderWithNormalVectorEstimator' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const AccFlower2D< T > & object)
Overloads 'operator<<' for displaying objects of class 'AccFlower2D'.
Parameters
out the output stream where the object is written.
object the object of class 'AccFlower2D' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const Ball3D< T > & object)
Overloads 'operator<<' for displaying objects of class 'Ball3D'.
Parameters
out the output stream where the object is written.
object the object of class 'Ball3D' to write.
Returns
the output stream after the writing.
template<typename PValue , int PDefaultPreset, int PDefaultFirstColor, int PDefaultLastColor> std::ostream& DGtal::operator<< (std::ostream & out, const GradientColorMap< PValue, PDefaultPreset, PDefaultFirstColor, PDefaultLastColor > & object)
Overloads 'operator<<' for displaying objects of class 'GradientColorMap'.
Parameters
out the output stream where the object is written.
object the object of class 'GradientColorMap' to write.
Returns
the output stream after the writing.
template<typename TProfile > std::ostream& DGtal::operator<< (std::ostream & out, const MeaningfulScaleAnalysis< TProfile > & object)
Overloads 'operator<<' for displaying objects of class 'MeaningfulScaleAnalysis'.
Parameters
out the output stream where the object is written.
object the object of class 'MeaningfulScaleAnalysis' to write.
Returns
the output stream after the writing.
template<typename TImageContainer , typename TImageFactory , typename TReadPolicy , typename TWritePolicy > std::ostream& DGtal::operator<< (std::ostream & out, const ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy > & object)
Overloads 'operator<<' for displaying objects of class 'ImageCache'.
Parameters
out the output stream where the object is written.
object the object of class 'ImageCache' to write.
Returns
the output stream after the writing.
std::ostream& DGtal::operator<< (std::ostream & that_stream, const SimpleLinearRegression & that_object_to_display)
Overloads 'operator<<' for displaying objects of class 'SimpleLinearRegression'.
Parameters
that_stream the output stream where the object is written.
that_object_to_display the object of class 'SimpleLinearRegression' to write.
Returns
the output stream after the writing.
template<typename TI , typename TO > std::ostream& DGtal::operator<< (std::ostream & out, const SimpleIncremental2x2DetComputer< TI, TO > & object)
Overloads 'operator<<' for displaying objects of class 'SimpleIncremental2x2DetComputer'.
Parameters
out the output stream where the object is written.
object the object of class 'SimpleIncremental2x2DetComputer' to write.
Returns
the output stream after the writing.
template<typename TSpace , typename TSeparableMetric > std::ostream& DGtal::operator<< (std::ostream & out, const VoronoiCovarianceMeasure< TSpace, TSeparableMetric > & object)
Overloads 'operator<<' for displaying objects of class 'VoronoiCovarianceMeasure'.
Parameters
out the output stream where the object is written.
object the object of class 'VoronoiCovarianceMeasure' to write.
Returns
the output stream after the writing.
template<typename TDigitalSurfaceContainer , typename TSeparableMetric , typename TKernelFunction , typename TVCMGeometricFunctor > std::ostream& DGtal::operator<< (std::ostream & out, const VCMDigitalSurfaceLocalEstimator< TDigitalSurfaceContainer, TSeparableMetric, TKernelFunction, TVCMGeometricFunctor > & object)
Overloads 'operator<<' for displaying objects of class 'VCMDigitalSurfaceLocalEstimator'.
Parameters
out the output stream where the object is written.
object the object of class 'VCMDigitalSurfaceLocalEstimator' to write.
Returns
the output stream after the writing.
template<typename TFraction > std::ostream& DGtal::operator<< (std::ostream & out, const Pattern< TFraction > & object)
Overloads 'operator<<' for displaying objects of class 'Pattern'.
Parameters
out the output stream where the object is written.
object the object of class 'Pattern' to write.
Returns
the output stream after the writing.
template<typename TSurface , bool isUpward, bool isClosed> std::ostream& DGtal::operator<< (std::ostream & out, const DGtal::functors::Point2ShapePredicate< TSurface, isUpward, isClosed > & object) inline
Overloads 'operator<<' for displaying objects of class 'Point2ShapePredicate'.
Parameters
out the output stream where the object is written.
object the object of class 'Point2ShapePredicate' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const StarShaped2D< T > & object)
Overloads 'operator<<' for displaying objects of class 'StarShaped2D'.
Parameters
out the output stream where the object is written.
object the object of class 'StarShaped2D' to write.
Returns
the output stream after the writing.
std::ostream& DGtal::operator<< (std::ostream & out, const MeasureOfStraightLines & object)
Overloads 'operator<<' for displaying objects of class 'MeasureOfStraightLines'.
Parameters
out the output stream where the object is written.
object the object of class 'MeasureOfStraightLines' to write.
Returns
the output stream after the writing.
template<typename Space , typename KSpace > std::ostream& DGtal::operator<< (std::ostream & out, const Board3DTo2D< Space, KSpace > & object)
Overloads 'operator<<' for displaying objects of class 'Board3DTo2D'.
Parameters
out the output stream where the object is written.
object the object of class 'Board3DTo2D' to write.
Returns
the output stream after the writing.
template<typename TDigitalSurfaceContainer , typename TSeparableMetric , typename TKernelFunction > std::ostream& DGtal::operator<< (std::ostream & out, const VoronoiCovarianceMeasureOnDigitalSurface< TDigitalSurfaceContainer, TSeparableMetric, TKernelFunction > & object)
Overloads 'operator<<' for displaying objects of class 'VoronoiCovarianceMeasureOnDigitalSurface'.
Parameters
out the output stream where the object is written.
object the object of class 'VoronoiCovarianceMeasureOnDigitalSurface' to write.
Returns
the output stream after the writing.
template<typename TDigitalSurfaceTracker > std::ostream& DGtal::operator<< (std::ostream & out, const DigitalSurface2DSlice< TDigitalSurfaceTracker > & object)
Overloads 'operator<<' for displaying objects of class 'DigitalSurface2DSlice'.
Parameters
out the output stream where the object is written.
object the object of class 'DigitalSurface2DSlice' to write.
Returns
the output stream after the writing.
template<typename TKSpace , typename TImplicitFunctionDiff1 , typename TEmbedder > std::ostream& DGtal::operator<< (std::ostream & out, const ImplicitFunctionDiff1LinearCellEmbedder< TKSpace, TImplicitFunctionDiff1, TEmbedder > & object)
Overloads 'operator<<' for displaying objects of class 'ImplicitFunctionDiff1LinearCellEmbedder'.
Parameters
out the output stream where the object is written.
object the object of class 'ImplicitFunctionDiff1LinearCellEmbedder' to write.
Returns
the output stream after the writing.
std::ostream& DGtal::operator<< (std::ostream & that_stream, const OrderedLinearRegression & that_object_to_display)
Overloads 'operator<<' for displaying objects of class 'OrderedLinearRegression'.
Parameters
that_stream the output stream where the object is written.
that_object_to_display the object of class 'OrderedLinearRegression' to write.
Returns
the output stream after the writing.
template<typename T , typename TC > std::ostream& DGtal::operator<< (std::ostream & out, const EstimatorCache< T, TC > & object)
Overloads 'operator<<' for displaying objects of class 'EstimatorCache'.
Parameters
out the output stream where the object is written.
object the object of class 'EstimatorCache' to write.
Returns
the output stream after the writing.
Definition at line 301 of file EstimatorCache.h.
   {
     object.selfDisplay( out );
     return out;
   }
template<typename TIterator , typename TInteger , int connectivity> std::ostream& DGtal::operator<< (std::ostream & out, const StandardDSS6Computer< TIterator, TInteger, connectivity > & object)
Overloads 'operator<<' for displaying objects of class 'StandardDSS6Computer'.
Parameters
out the output stream where the object is written.
object the object of class 'StandardDSS6Computer' to write.
Returns
the output stream after the writing.
Definition at line 303 of file StandardDSS6Computer.h.
   {
     object.selfDisplay( out);
     return out;
   }
template<typename TDigitalSurfaceTracker > std::ostream& DGtal::operator<< (std::ostream & out, const UmbrellaComputer< TDigitalSurfaceTracker > & object)
Overloads 'operator<<' for displaying objects of class 'UmbrellaComputer'.
Parameters
out the output stream where the object is written.
object the object of class 'UmbrellaComputer' to write.
Returns
the output stream after the writing.
template<typename TQuantity > std::ostream& DGtal::operator<< (std::ostream & thatStream, const Statistic< TQuantity > & that_object_to_display)
Overloads 'operator<<' for displaying objects of class 'Statistic'.
Parameters
thatStream the output stream where the object is written.
that_object_to_display the object of class 'Statistic' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const Image< T > & object)
Overloads 'operator<<' for displaying objects of class 'Image'.
Parameters
out the output stream where the object is written.
object the object of class 'Image' to write.
Returns
the output stream after the writing.
template<typename TKSpace , typename TDigitalSet > std::ostream& DGtal::operator<< (std::ostream & out, const DigitalSetBoundary< TKSpace, TDigitalSet > & object)
Overloads 'operator<<' for displaying objects of class 'DigitalSetBoundary'.
Parameters
out the output stream where the object is written.
object the object of class 'DigitalSetBoundary' to write.
Returns
the output stream after the writing.
Template Parameters
TKSpace a model of CCellularGridSpaceND: the type chosen for the cellular grid space.
TDigitalSet a model of CDigitalSet: the type chosen for the set of digital points.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const Expander< T > & object)
Overloads 'operator<<' for displaying objects of class 'Expander'.
Parameters
out the output stream where the object is written.
object the object of class 'Expander' to write.
Returns
the output stream after the writing.
template<typename TIterator , typename TFunctor , typename TReturnType > std::ostream& DGtal::operator<< (std::ostream & out, const ConstRangeAdapter< TIterator, TFunctor, TReturnType > & object)
Overloads 'operator<<' for displaying objects of class 'ConstRangeAdapter'.
Parameters
out the output stream where the object is written.
object the object of class 'ConstRangeAdapter' to write.
Returns
the output stream after the writing.
Definition at line 316 of file ConstRangeAdapter.h.
    {
      object.selfDisplay( out );
      return out;
    }
template<Dimension dim, typename TInteger > std::ostream& DGtal::operator<< (std::ostream & out, const SignedKhalimskyCell< dim, TInteger > & object)
template<typename TGraphVisitor > std::ostream& DGtal::operator<< (std::ostream & out, const GraphVisitorRange< TGraphVisitor > & object)
Overloads 'operator<<' for displaying objects of class 'GraphVisitorRange'.
Parameters
out the output stream where the object is written.
object the object of class 'GraphVisitorRange' to write.
Returns
the output stream after the writing.
template<typename TGraph , typename TMarkSet > std::ostream& DGtal::operator<< (std::ostream & out, const BreadthFirstVisitor< TGraph, TMarkSet > & object)
Overloads 'operator<<' for displaying objects of class 'BreadthFirstVisitor'.
Parameters
out the output stream where the object is written.
object the object of class 'BreadthFirstVisitor' to write.
Returns
the output stream after the writing.
template<typename TGraph , typename TMarkSet > std::ostream& DGtal::operator<< (std::ostream & out, const DepthFirstVisitor< TGraph, TMarkSet > & object)
Overloads 'operator<<' for displaying objects of class 'DepthFirstVisitor'.
Parameters
out the output stream where the object is written.
object the object of class 'DepthFirstVisitor' to write.
Returns
the output stream after the writing.
template<typename TInteger > std::ostream& DGtal::operator<< (std::ostream & out, const AvnaimEtAl2x2DetSignComputer< TInteger > & object)
Overloads 'operator<<' for displaying objects of class 'AvnaimEtAl2x2DetSignComputer'.
Parameters
out the output stream where the object is written.
object the object of class 'AvnaimEtAl2x2DetSignComputer' to write.
Returns
the output stream after the writing.
template<typename TImageContainer , typename TNewDomain , typename TFunctorD , typename TNewValue , typename TFunctorV > std::ostream& DGtal::operator<< (std::ostream & out, const ConstImageAdapter< TImageContainer, TNewDomain, TFunctorD, TNewValue, TFunctorV > & object)
Overloads 'operator<<' for displaying objects of class 'ConstImageAdapter'.
Parameters
out the output stream where the object is written.
object the object of class 'ConstImageAdapter' to write.
Returns
the output stream after the writing.
template<typename TKSpace , typename TSurfelSet > std::ostream& DGtal::operator<< (std::ostream & out, const SetOfSurfels< TKSpace, TSurfelSet > & object)
Overloads 'operator<<' for displaying objects of class 'SetOfSurfels'.
Parameters
out the output stream where the object is written.
object the object of class 'SetOfSurfels' to write.
Returns
the output stream after the writing.
Template Parameters
TKSpace a model of CCellularGridSpaceND: the type chosen for the cellular grid space.
TSurfelSet a model of CDigitalSet: the type chosen for the set of digital points.
template<typename A , typename B > std::ostream& DGtal::operator<< (std::ostream & out, const std::pair< A, B > & object)
//To move elsewhere ? Overloads 'operator<<' for displaying STL pairs.
Parameters
out the output stream where the object is written.
object the STL pair to write.
Returns
the output stream after the writing.
Definition at line 330 of file ConstRangeAdapter.h.
    {
      out << object.first << "|" << object.second;
      return out;
    }
template<typename TD , typename TV , typename TF , typename TC > std::ostream& DGtal::operator<< (std::ostream & out, const LocalEstimatorFromSurfelFunctorAdapter< TD, TV, TF, TC > & object)
Overloads 'operator<<' for displaying objects of class 'LocalEstimatorFromSurfelFunctorAdapter'.
Parameters
out the output stream where the object is written.
object the object of class 'LocalEstimatorFromSurfelFunctorAdapter' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const CountedPtr< T > & object)
Overloads 'operator<<' for displaying objects of class 'CountedPtr'.
Parameters
out the output stream where the object is written.
object the object of class 'CountedPtr' to write.
Returns
the output stream after the writing.
template<typename TQuantity , typename TBinner > std::ostream& DGtal::operator<< (std::ostream & out, const Histogram< TQuantity, TBinner > & object)
Overloads 'operator<<' for displaying objects of class 'Histogram'.
Parameters
out the output stream where the object is written.
object the object of class 'Histogram' to write.
Returns
the output stream after the writing.
template<typename TKSpace , typename TPointPredicate > std::ostream& DGtal::operator<< (std::ostream & out, const DGtal::deprecated::IntegralInvariantNormalVectorEstimator< TKSpace, TPointPredicate > & object)
Overloads 'operator<<' for displaying objects of class 'IntegralInvariantNormalVectorEstimator'.
Parameters
out the output stream where the object is written.
object the object of class 'IntegralInvariantNormalVectorEstimator' to write.
Returns
the output stream after the writing.
template<typename TKSpace , typename TPointPredicate , typename TVolumeFunctor > std::ostream& DGtal::operator<< (std::ostream & out, const IntegralInvariantVolumeEstimator< TKSpace, TPointPredicate, TVolumeFunctor > & object)
Overloads 'operator<<' for displaying objects of class 'IntegralInvariantVolumeEstimator'.
Parameters
out the output stream where the object is written.
object the object of class 'IntegralInvariantVolumeEstimator' to write.
Returns
the output stream after the writing.
template<typename T , typename TV > std::ostream& DGtal::operator<< (std::ostream & out, const ImageContainerByITKImage< T, TV > & object)
Overloads 'operator<<' for displaying objects of class 'ImageContainerByITKImage'.
Parameters
out the output stream where the object is written.
object the object of class 'ImageContainerByITKImage' to write.
Returns
the output stream after the writing.
template<typename TKSpace , typename TPointPredicate , typename TCovarianceMatrixFunctor > std::ostream& DGtal::operator<< (std::ostream & out, const IntegralInvariantCovarianceEstimator< TKSpace, TPointPredicate, TCovarianceMatrixFunctor > & object)
Overloads 'operator<<' for displaying objects of class 'IntegralInvariantCovarianceEstimator'.
Parameters
out the output stream where the object is written.
object the object of class 'IntegralInvariantCovarianceEstimator' to write.
Returns
the output stream after the writing.
template<unsigned int L, typename TWord > std::ostream& DGtal::operator<< (std::ostream & out, const Labels< L, TWord > & object)
Overloads 'operator<<' for displaying objects of class 'Labels'.
Parameters
out the output stream where the object is written.
object the object of class 'Labels' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const StarShaped3D< T > & object)
Overloads 'operator<<' for displaying objects of class 'StarShaped3D'.
Parameters
out the output stream where the object is written.
object the object of class 'StarShaped2D' to write.
Returns
the output stream after the writing.
template<typename TKSpace , typename TPointPredicate > std::ostream& DGtal::operator<< (std::ostream & out, const ImplicitDigitalSurface< TKSpace, TPointPredicate > & object)
Overloads 'operator<<' for displaying objects of class 'ImplicitDigitalSurface'.
Parameters
out the output stream where the object is written.
object the object of class 'ImplicitDigitalSurface' to write.
Returns
the output stream after the writing.
Template Parameters
TKSpace a model of CCellularGridSpaceND: the type chosen for the cellular grid space.
TPointPredicate a model of CDigitalSet: the type chosen for the set of digital points.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const SurfelNeighborhood< T > & object)
Overloads 'operator<<' for displaying objects of class 'SurfelNeighborhood'.
Parameters
out the output stream where the object is written.
object the object of class 'SurfelNeighborhood' to write.
Returns
the output stream after the writing.
template<typename TKSpace , typename TSurfelPredicate > std::ostream& DGtal::operator<< (std::ostream & out, const ExplicitDigitalSurface< TKSpace, TSurfelPredicate > & object)
Overloads 'operator<<' for displaying objects of class 'ExplicitDigitalSurface'.
Parameters
out the output stream where the object is written.
object the object of class 'ExplicitDigitalSurface' to write.
Returns
the output stream after the writing.
Template Parameters
TKSpace a model of CCellularGridSpaceND: the type chosen for the cellular grid space.
TSurfelPredicate a model of CDigitalSet: the type chosen for the set of digital points.
template<typename TConstIterator > std::ostream& DGtal::operator<< (std::ostream & out, const StabbingCircleComputer< TConstIterator > & object)
Overloads 'operator<<' for displaying objects of class 'StabbingCircleComputer'.
Parameters
out the output stream where the object is written.
object the object of class 'StabbingCircleComputer' to write.
Returns
the output stream after the writing.
template<typename TImageContainer , typename TNewDomain , typename TFunctorD , typename TNewValue , typename TFunctorV , typename TFunctorVm1 > std::ostream& DGtal::operator<< (std::ostream & out, const ImageAdapter< TImageContainer, TNewDomain, TFunctorD, TNewValue, TFunctorV, TFunctorVm1 > & object)
Overloads 'operator<<' for displaying objects of class 'ImageAdapter'.
Parameters
out the output stream where the object is written.
object the object of class 'ImageAdapter' to write.
Returns
the output stream after the writing.
template<typename TValue > std::ostream& DGtal::operator<< (std::ostream & out, const Signal< TValue > & object)
Overloads 'operator<<' for displaying objects of class 'Signal'.
Parameters
out the output stream where the object is written.
object the object of class 'Signal' to write.
Returns
the output stream after the writing.
template<typename Domain > std::ostream& DGtal::operator<< (std::ostream & out, const DigitalSetBySTLVector< Domain > & object)
Overloads 'operator<<' for displaying objects of class 'DigitalSetBySTLVector'.
Parameters
out the output stream where the object is written.
object the object of class 'DigitalSetBySTLVector' to write.
Returns
the output stream after the writing.
template<typename Domain , typename Compare > std::ostream& DGtal::operator<< (std::ostream & out, const DigitalSetBySTLSet< Domain, Compare > & object)
Overloads 'operator<<' for displaying objects of class 'DigitalSetBySTLSet'.
Parameters
out the output stream where the object is written.
object the object of class 'DigitalSetBySTLSet' to write.
Returns
the output stream after the writing.
template<typename TValueFunctor , typename TValue > std::ostream& DGtal::operator<< (std::ostream & out, const Profile< TValueFunctor, TValue > & object)
Overloads 'operator<<' for displaying objects of class 'Profile'.
Parameters
out the output stream where the object is written.
object the object of class 'Profile' to write.
Returns
the output stream after the writing.
template<typename Domain , typename Container > std::ostream& DGtal::operator<< (std::ostream & out, const DigitalSetByAssociativeContainer< Domain, Container > & object)
Overloads 'operator<<' for displaying objects of class 'DigitalSetByAssociativeContainer'.
Parameters
out the output stream where the object is written.
object the object of class 'DigitalSetByAssociativeContainer' to write.
Returns
the output stream after the writing.
template<typename TMapImage > std::ostream& DGtal::operator<< (std::ostream & out, const DigitalSetFromMap< TMapImage > & object)
Overloads 'operator<<' for displaying objects of class 'DigitalSetFromMap'.
Parameters
out the output stream where the object is written.
object the object of class 'DigitalSetFromMap' to write.
Returns
the output stream after the writing.
template<typename TConstIteratorOnPoints , typename TValue > std::ostream& DGtal::operator<< (std::ostream & out, const BinomialConvolver< TConstIteratorOnPoints, TValue > & object)
Overloads 'operator<<' for displaying objects of class 'BinomialConvolver'.
Parameters
out the output stream where the object is written.
object the object of class 'BinomialConvolver' to write.
Returns
the output stream after the writing.
template<typename TPoint , typename TDetComputer > std::ostream& DGtal::operator<< (std::ostream & out, const InGeneralizedDiskOfGivenRadius< TPoint, TDetComputer > & object)
Overloads 'operator<<' for displaying objects of class 'InGeneralizedDiskOfGivenRadius'.
Parameters
out the output stream where the object is written.
object the object of class 'InGeneralizedDiskOfGivenRadius' to write.
Returns
the output stream after the writing.
template<typename TConstIterator > std::ostream& DGtal::operator<< (std::ostream & out, const StabbingLineComputer< TConstIterator > & object)
Overloads 'operator<<' for displaying objects of class 'StabbingLineComputer'.
Parameters
out the output stream where the object is written.
object the object of class 'StabbingLineComputer' to write.
Returns
the output stream after the writing.
std::ostream& DGtal::operator<< (std::ostream & out, const OrderedAlphabet & object)
Overloads 'operator<<' for displaying objects of class 'OrderedAlphabet'.
Parameters
out the output stream where the object is written.
object the object of class 'OrderedAlphabet' to write.
Returns
the output stream after the writing.
template<typename TFraction > std::ostream& DGtal::operator<< (std::ostream & out, const StandardDSLQ0< TFraction > & object)
Overloads 'operator<<' for displaying objects of class 'StandardDSLQ0'.
Parameters
out the output stream where the object is written.
object the object of class 'StandardDSLQ0' to write.
Returns
the output stream after the writing.
template<typename TIterator , typename TInteger , unsigned short adjacency> std::ostream& DGtal::operator<< (std::ostream & out, const ArithmeticalDSSComputer< TIterator, TInteger, adjacency > & object)
Overloads 'operator<<' for displaying objects of class 'ArithmeticalDSSComputer'.
Parameters
out the output stream where the object is written.
object the object of class 'ArithmeticalDSSComputer' to write.
Returns
the output stream after the writing.
Definition at line 421 of file ArithmeticalDSSComputer.h.
 {
   object.selfDisplay( out);
   return out;
 }
template<typename W , typename Sep , typename Image > std::ostream& DGtal::operator<< (std::ostream & out, const PowerMap< W, Sep, Image > & object)
Overloads 'operator<<' for displaying objects of class 'ExactPredicateLpSeparableMetric'.
Parameters
out the output stream where the object is written.
object the object of class 'ExactPredicateLpSeparableMetric' to write.
Returns
the output stream after the writing.
template<int n, typename TRing , typename TAlloc , typename TIterator > std::ostream& DGtal::operator<< (std::ostream & out, const MPolynomialReader< n, TRing, TAlloc, TIterator > & object)
Overloads 'operator<<' for displaying objects of class 'MPolynomialReader'.
Parameters
out the output stream where the object is written.
object the object of class 'MPolynomialReader' to write.
Returns
the output stream after the writing.
template<typename S , typename P , typename Sep , typename TI > std::ostream& DGtal::operator<< (std::ostream & out, const VoronoiMap< S, P, Sep, TI > & object)
Overloads 'operator<<' for displaying objects of class 'ExactPredicateLpSeparableMetric'.
Parameters
out the output stream where the object is written.
object the object of class 'ExactPredicateLpSeparableMetric' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const SphericalAccumulator< T > & object)
Overloads 'operator<<' for displaying objects of class 'SphericalAccumulator'.
Parameters
out the output stream where the object is written.
object the object of class 'SphericalAccumulator' to write.
Returns
the output stream after the writing.
template<typename TSpace , typename TInputPoint , typename TInternalScalar > std::ostream& DGtal::operator<< (std::ostream & out, const ChordGenericNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar > & object)
Overloads 'operator<<' for displaying objects of class 'ChordGenericNaivePlaneComputer'.
Parameters
out the output stream where the object is written.
object the object of class 'ChordGenericNaivePlaneComputer' to write.
Returns
the output stream after the writing.
template<typename T , DGtal::Dimension M, DGtal::Dimension N> std::ostream& DGtal::operator<< (std::ostream & out, const SimpleMatrix< T, M, N > & object)
Overloads 'operator<<' for displaying objects of class 'SimpleMatrix'.
Parameters
out the output stream where the object is written.
object the object of class 'SimpleMatrix' to write.
Returns
the output stream after the writing.
template<typename TKSpace , typename TPointPredicate > std::ostream& DGtal::operator<< (std::ostream & out, const LightImplicitDigitalSurface< TKSpace, TPointPredicate > & object)
Overloads 'operator<<' for displaying objects of class 'LightImplicitDigitalSurface'.
Parameters
out the output stream where the object is written.
object the object of class 'LightImplicitDigitalSurface' to write.
Returns
the output stream after the writing.
Template Parameters
TKSpace a model of CCellularGridSpaceND: the type chosen for the cellular grid space.
TPointPredicate a model of CDigitalSet: the type chosen for the set of digital points.
template<typename Shape > std::ostream& DGtal::operator<< (std::ostream & out, const Preimage2D< Shape > & object)
Overloads 'operator<<' for displaying objects of class 'Preimage2D'.
Parameters
out the output stream where the object is written.
object the object of class 'Preimage2D' to write.
Returns
the output stream after the writing.
template<typename TKSpace , typename TSurfelPredicate > std::ostream& DGtal::operator<< (std::ostream & out, const LightExplicitDigitalSurface< TKSpace, TSurfelPredicate > & object)
Overloads 'operator<<' for displaying objects of class 'LightExplicitDigitalSurface'.
Parameters
out the output stream where the object is written.
object the object of class 'LightExplicitDigitalSurface' to write.
Returns
the output stream after the writing.
Template Parameters
TKSpace a model of CCellularGridSpaceND: the type chosen for the cellular grid space.
TSurfelPredicate a model of CDigitalSet: the type chosen for the set of digital points.
template<typename TArrayIterator , typename TDomain > std::ostream& DGtal::operator<< (std::ostream & out, const ArrayImageAdapter< TArrayIterator, TDomain > & object)
[IteratorCompletionTraits]
Overloads 'operator<<' for displaying objects of class 'ArrayImageIterator'.
Parameters
out the output stream where the object is written.
object the object of class 'ArrayImageIterator' to write.
Returns
the output stream after the writing.
Definition at line 444 of file ArrayImageAdapter.h.
     {
       object.selfDisplay( out );
       return out;
     }
template<typename TSpace , typename TInternalInteger > std::ostream& DGtal::operator<< (std::ostream & out, const COBAGenericNaivePlaneComputer< TSpace, TInternalInteger > & object)
Overloads 'operator<<' for displaying objects of class 'COBAGenericNaivePlaneComputer'.
Parameters
out the output stream where the object is written.
object the object of class 'COBAGenericNaivePlaneComputer' to write.
Returns
the output stream after the writing.
std::ostream& DGtal::operator<< (std::ostream & out, const MultiStatistics & object)
Overloads 'operator<<' for displaying objects of class 'MultiStatistics'.
Parameters
out the output stream where the object is written.
object the object of class 'MultiStatistics' to write.
Returns
the output stream after the writing.
template<typename T , DGtal::uint32_t p, typename P > std::ostream& DGtal::operator<< (std::ostream & out, const ExactPredicateLpSeparableMetric< T, p, P > & object)
Overloads 'operator<<' for displaying objects of class 'ExactPredicateLpSeparableMetric'.
Parameters
out the output stream where the object is written.
object the object of class 'ExactPredicateLpSeparableMetric' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const CountedPtrOrPtr< T > & object)
Overloads 'operator<<' for displaying objects of class 'CountedPtrOrPtr'.
Parameters
out the output stream where the object is written.
object the object of class 'CountedPtrOrPtr' to write.
Returns
the output stream after the writing.
std::ostream& DGtal::operator<< (std::ostream & out, const Color & aColor)
Overloads 'operator<<' for displaying objects of class 'Color'.
Parameters
out the output stream where the object is written.
aColor the object of class 'Color' to write.
Returns
the output stream after the writing.
template<typename T , DGtal::uint32_t p, typename P > std::ostream& DGtal::operator<< (std::ostream & out, const ExactPredicateLpPowerSeparableMetric< T, p, P > & object)
Overloads 'operator<<' for displaying objects of class 'ExactPredicateLpPowerSeparableMetric'.
Parameters
out the output stream where the object is written.
object the object of class 'ExactPredicateLpPowerSeparableMetric' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const CountedConstPtrOrConstPtr< T > & object)
Overloads 'operator<<' for displaying objects of class 'CountedConstPtrOrConstPtr'.
Parameters
out the output stream where the object is written.
object the object of class 'CountedConstPtrOrConstPtr' to write.
Returns
the output stream after the writing.
template<typename TKSpace > std::ostream& DGtal::operator<< (std::ostream & out, const GridCurve< TKSpace > & object)
Overloads 'operator<<' for displaying objects of class 'GridCurve'.
Parameters
out the output stream where the object is written.
object the object of class 'GridCurve' to write.
Returns
the output stream after the writing.
template<typename SegmentComputer > std::ostream& DGtal::operator<< (std::ostream & out, const GreedySegmentation< SegmentComputer > & object)
Overloads 'operator<<' for displaying objects of class 'GreedySegmentation'.
Parameters
out the output stream where the object is written.
object the object of class 'GreedySegmentation' to write.
Returns
the output stream after the writing.
template<typename TSpace , typename TInputPoint , typename TInternalScalar > std::ostream& DGtal::operator<< (std::ostream & out, const ChordGenericStandardPlaneComputer< TSpace, TInputPoint, TInternalScalar > & object)
Overloads 'operator<<' for displaying objects of class 'ChordGenericStandardPlaneComputer'.
Parameters
out the output stream where the object is written.
object the object of class 'ChordGenericStandardPlaneComputer' to write.
Returns
the output stream after the writing.
template<typename TImage , typename TSet , typename TPointPredicate , typename TPointFunctor > std::ostream& DGtal::operator<< (std::ostream & out, const FMM< TImage, TSet, TPointPredicate, TPointFunctor > & object)
Overloads 'operator<<' for displaying objects of class 'FMM'.
Parameters
out the output stream where the object is written.
object the object of class 'FMM' to write.
Returns
the output stream after the writing.
template<typename Domain , typename V > std::ostream& DGtal::operator<< (std::ostream & out, const ImageContainerBySTLVector< Domain, V > & object) inline
Overloads 'operator<<' for displaying objects of class 'Image'.
Parameters
out the output stream where the object is written.
object the object of class 'Image' to write.
Returns
the output stream after the writing.
Definition at line 532 of file ImageContainerBySTLVector.h.
   {
     object.selfDisplay ( out );
     return out;
   }
template<typename SegmentComputer > std::ostream& DGtal::operator<< (std::ostream & out, const SaturatedSegmentation< SegmentComputer > & object)
Overloads 'operator<<' for displaying objects of class 'SaturatedSegmentation'.
Parameters
out the output stream where the object is written.
object the object of class 'SaturatedSegmentation' to write.
Returns
the output stream after the writing.
std::ostream& DGtal::operator<< (std::ostream & out, const AngleLinearMinimizer & object)
Overloads 'operator<<' for displaying objects of class 'AngleLinearMinimizer'.
Parameters
out the output stream where the object is written.
object the object of class 'AngleLinearMinimizer' to write.
Returns
the output stream after the writing.
template<typename TGraph , typename TVertexFunctor , typename TMarkSet > std::ostream& DGtal::operator<< (std::ostream & out, const DistanceBreadthFirstVisitor< TGraph, TVertexFunctor, TMarkSet > & object)
Overloads 'operator<<' for displaying objects of class 'DistanceBreadthFirstVisitor'.
Parameters
out the output stream where the object is written.
object the object of class 'DistanceBreadthFirstVisitor' to write.
Returns
the output stream after the writing.
template<typename TIterator , typename TInteger , int connectivity> std::ostream& DGtal::operator<< (std::ostream & out, const FP< TIterator, TInteger, connectivity > & object)
Overloads 'operator<<' for displaying objects of class 'FP'.
Parameters
out the output stream where the object is written.
object the object of class 'FP' to write.
Returns
the output stream after the writing.
template<typename T > std::ostream& DGtal::operator<< (std::ostream & out, const experimental::ChamferNorm2D< T > & object)
Overloads 'operator<<' for displaying objects of class 'ChamferNorm2D'.
Parameters
out the output stream where the object is written.
object the object of class 'ChamferNorm2D' to write.
Returns
the output stream after the writing.
template<typename TSpace , typename TInternalInteger > std::ostream& DGtal::operator<< (std::ostream & out, const COBAGenericStandardPlaneComputer< TSpace, TInternalInteger > & object)
Overloads 'operator<<' for displaying objects of class 'COBAGenericStandardPlaneComputer'.
Parameters
out the output stream where the object is written.
object the object of class 'COBAGenericStandardPlaneComputer' to write.
Returns
the output stream after the writing.
template<typename TInteger > std::ostream& DGtal::operator<< (std::ostream & out, const IntegerComputer< TInteger > & object)
Overloads 'operator<<' for displaying objects of class 'IntegerComputer'.
Parameters
out the output stream where the object is written.
object the object of class 'IntegerComputer' to write.
Returns
the output stream after the writing.
template<typename TSpace , typename TSequence > std::ostream& DGtal::operator<< (std::ostream & out, const LatticePolytope2D< TSpace, TSequence > & object)
Overloads 'operator<<' for displaying objects of class 'LatticePolytope2D'.
Parameters
out the output stream where the object is written.
object the object of class 'LatticePolytope2D' to write.
Returns
the output stream after the writing.
template<typename TSpace , typename TInternalInteger > std::ostream& DGtal::operator<< (std::ostream & out, const COBANaivePlaneComputer< TSpace, TInternalInteger > & object)
Overloads 'operator<<' for displaying objects of class 'COBANaivePlaneComputer'.
Parameters
out the output stream where the object is written.
object the object of class 'COBANaivePlaneComputer' to write.
Returns
the output stream after the writing.
template<typename TPoint > std::ostream& DGtal::operator<< (std::ostream & out, const TriangulatedSurface< TPoint > & object)
Overloads 'operator<<' for displaying objects of class 'TriangulatedSurface'.
Parameters
out the output stream where the object is written.
object the object of class 'TriangulatedSurface' to write.
Returns
the output stream after the writing.
template<typename TImageContainer > std::ostream& DGtal::operator<< (std::ostream & out, const ImageFactoryFromHDF5< TImageContainer > & object)
Overloads 'operator<<' for displaying objects of class 'ImageFactoryFromHDF5'.
Parameters
out the output stream where the object is written.
object the object of class 'ImageFactoryFromHDF5' to write.
Returns
the output stream after the writing.
template<typename TPoint > std::ostream& DGtal::operator<< (std::ostream & out, const PolygonalSurface< TPoint > & object)
Overloads 'operator<<' for displaying objects of class 'PolygonalSurface'.
Parameters
out the output stream where the object is written.
object the object of class 'PolygonalSurface' to write.
Returns
the output stream after the writing.
template<typename TKSpace , typename TObject , typename TCellContainer > std::ostream& DGtal::operator<< (std::ostream & out, const VoxelComplex< TKSpace, TObject, TCellContainer > & object)
Overloads 'operator<<' for displaying objects of class 'VoxelComplex'.
Parameters
out the output stream where the object is written.
object the object of class 'VoxelComplex' to write.
Returns
the output stream after the writing.
std::ostream& DGtal::operator<< (std::ostream & out, const HalfEdgeDataStructure & object)
Overloads 'operator<<' for displaying objects of class 'HalfEdgeDataStructure'.
Parameters
out the output stream where the object is written.
object the object of class 'HalfEdgeDataStructure' to write.
Returns
the output stream after the writing.
template<Dimension dimEmbedded, Dimension dimAmbient, typename TLinearAlgebraBackend , typename TInteger > std::ostream& DGtal::operator<< (std::ostream & out, const DiscreteExteriorCalculus< dimEmbedded, dimAmbient, TLinearAlgebraBackend, TInteger > & object)
Overloads 'operator<<' for displaying objects of class 'DiscreteExteriorCalculus'.
Parameters
out the output stream where the object is written.
object the object of class 'DiscreteExteriorCalculus' to write.
Returns
the output stream after the writing.
template<typename TPoint > std::ostream& DGtal::operator<< (std::ostream & out, const Mesh< TPoint > & object)
Overloads 'operator<<' for displaying objects of class 'Mesh'.
Parameters
out the output stream where the object is written.
object the object of class 'Mesh' to write.
Returns
the output stream after the writing.
template<typename TSpace > std::ostream& DGtal::operator<< (std::ostream & out, const HyperRectDomain< TSpace > & object)
Overloads 'operator<<' for displaying objects of class 'HyperRectDomain'.
Parameters
out the output stream where the object is written.
object the object of class 'HyperRectDomain' to write.
Returns
the output stream after the writing.
template<typename TCoordinate , typename TInteger , unsigned short adjacency> std::ostream& DGtal::operator<< (std::ostream & out, const ArithmeticalDSL< TCoordinate, TInteger, adjacency > & object)
Overloads 'operator<<' for displaying objects of class 'ArithmeticalDSL'.
Parameters
out the output stream where the object is written.
object the object of class 'ArithmeticalDSL' to write.
Returns
the output stream after the writing.
template<typename TDigitalSurfaceContainer > std::ostream& DGtal::operator<< (std::ostream & out, const DigitalSurface< TDigitalSurfaceContainer > & object)
Overloads 'operator<<' for displaying objects of class 'DigitalSurface'.
Parameters
out the output stream where the object is written.
object the object of class 'DigitalSurface' to write.
Returns
the output stream after the writing.
template<typename TDigitalTopology , typename TDigitalSet > std::ostream& DGtal::operator<< (std::ostream & out, const Object< TDigitalTopology, TDigitalSet > & object)
Overloads 'operator<<' for displaying objects of class 'Object'.
Parameters
out the output stream where the object is written.
object the object of class 'Object' to write.
Returns
the output stream after the writing.
template<typename TInputPoint , typename TConstIterator > std::ostream& DGtal::operator<< (std::ostream & out, const AlphaThickSegmentComputer< TInputPoint, TConstIterator > & object)
Overloads 'operator<<' for displaying objects of class 'AlphaThickSegmentComputer'.
Parameters
out the output stream where the object is written.
object the object of class 'AlphaThickSegmentComputer' to write.
Returns
the output stream after the writing.
template<typename TDigitalSurfaceContainer > std::ostream& DGtal::operator<< (std::ostream & out, const IndexedDigitalSurface< TDigitalSurfaceContainer > & object)
Overloads 'operator<<' for displaying objects of class 'IndexedDigitalSurface'.
Parameters
out the output stream where the object is written.
object the object of class 'IndexedDigitalSurface' to write.
Returns
the output stream after the writing.
template<class TDomain , typename T > std::ostream& DGtal::operator<< (std::ostream & out, const RealFFT< TDomain, T > & object)
Overloads 'operator<<' for displaying objects of class 'RealFFT'.
Parameters
out the output stream where the object is written.
object the object of class 'RealFFT' to write.
Returns
the output stream after the writing.
template<typename TValue , unsigned int N, unsigned int M> std::ostream& DGtal::operator<< (std::ostream & out, const IndexedListWithBlocks< TValue, N, M > & object)
Overloads 'operator<<' for displaying objects of class 'IndexedListWithBlocks'.
Parameters
out the output stream where the object is written.
object the object of class 'IndexedListWithBlocks' to write.
Returns
the output stream after the writing.
Template Parameters
TValue the type for the values stored in the list.
N the number of value stored in the first block.
M the number of value stored in the further blocks.
template<typename ShapeA , typename ShapeB > std::ostream& DGtal::operator<< (std::ostream & out, const deprecated::EuclideanShapesUnion< ShapeA, ShapeB > & object)
Overloads 'operator<<' for displaying objects of class 'EuclideanShapesDecorator'.
Parameters
out the output stream where the object is written.
object the object of class 'EuclideanShapesDecorator' to write.
Returns
the output stream after the writing.
template<typename ShapeA , typename ShapeB > std::ostream& DGtal::operator<< (std::ostream & out, const deprecated::DigitalShapesUnion< ShapeA, ShapeB > & object)
Overloads 'operator<<' for displaying objects of class 'DigitalShapesDecorator'.
Parameters
out the output stream where the object is written.
object the object of class 'DigitalShapesDecorator' to write.
Returns
the output stream after the writing.
template<typename ShapeA , typename ShapeB > std::ostream& DGtal::operator<< (std::ostream & out, const deprecated::EuclideanShapesIntersection< ShapeA, ShapeB > & object)
template<typename ShapeA , typename ShapeB > std::ostream& DGtal::operator<< (std::ostream & out, const deprecated::DigitalShapesIntersection< ShapeA, ShapeB > & object)
template<typename ShapeA , typename ShapeB > std::ostream& DGtal::operator<< (std::ostream & out, const deprecated::EuclideanShapesMinus< ShapeA, ShapeB > & object)
template<typename ShapeA , typename ShapeB > std::ostream& DGtal::operator<< (std::ostream & out, const deprecated::DigitalShapesMinus< ShapeA, ShapeB > & object)
template<typename TCoordinate , typename TInteger , unsigned short adjacency> std::ostream& DGtal::operator<< (std::ostream & out, const ArithmeticalDSS< TCoordinate, TInteger, adjacency > & object)
Overloads 'operator<<' for displaying objects of class 'ArithmeticalDSS'.
Parameters
out the output stream where the object is written.
object the object of class 'ArithmeticalDSS' to write.
Returns
the output stream after the writing.
template<typename TSpace , typename TInputPoint , typename TInternalScalar > std::ostream& DGtal::operator<< (std::ostream & out, const ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar > & object)
Overloads 'operator<<' for displaying objects of class 'ChordNaivePlaneComputer'.
Parameters
out the output stream where the object is written.
object the object of class 'ChordNaivePlaneComputer' to write.
Returns
the output stream after the writing.
template<Dimension dim, typename Component , typename TC > std::ostream& DGtal::operator<< (std::ostream & out, const PointVector< dim, Component, TC > & object)
Operator <<.
template<typename TImageContainer , typename TImageFactory , typename TImageCacheReadPolicy , typename TImageCacheWritePolicy > std::ostream& DGtal::operator<< (std::ostream & out, const TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy > & object)
Overloads 'operator<<' for displaying objects of class 'TiledImage'.
Parameters
out the output stream where the object is written.
object the object of class 'TiledImage' to write.
Returns
the output stream after the writing.
template<typename TKSpace > std::ostream& DGtal::operator<< (std::ostream & out, const Surfaces< TKSpace > & object)
Overloads 'operator<<' for displaying objects of class 'Surfaces'.
Parameters
out the output stream where the object is written.
object the object of class 'Surfaces' to write.
Returns
the output stream after the writing.
template<typename TIterator , typename TInteger > std::ostream& DGtal::operator<< (std::ostream & out, const FrechetShortcut< TIterator, TInteger > & object)
Overloads 'operator<<' for displaying objects of class 'FrechetShortcut'.
Parameters
out the output stream where the object is written.
object the object of class 'FrechetShortcut' to write.
Returns
the output stream after the writing.
template<typename Space , typename KSpace > std::ostream& DGtal::operator<< (std::ostream & out, const DGtal::Display3D< Space, KSpace > & object)
Overloads 'operator<<' for displaying objects of class 'Display3D'.
Parameters
out the output stream where the object is written.
object the object of class 'Display3D' to write.
Returns
the output stream after the writing.
template<typename TConstIterator , typename TInteger > std::ostream& DGtal::operator<< (std::ostream & out, const OneBalancedWordComputer< TConstIterator, TInteger > & object)
Overloads 'operator<<' for displaying objects of class 'OneBalancedWord'.
Parameters
out the output stream where the object is written.
object the object of class 'OneBalancedWord' to write.
Returns
the output stream after the writing.
template<typename TF , typename TKF , typename TKS , typename TDK , Dimension dimension> std::ostream& DGtal::operator<< (std::ostream & out, const DGtal::DigitalSurfaceConvolver< TF, TKF, TKS, TDK, dimension > & object)
Overloads 'operator<<' for displaying objects of class 'DigitalSurfaceConvolver'.
Parameters
out the output stream where the object is written.
object the object of class 'DigitalSurfaceConvolver' to write.
Returns
the output stream after the writing.
template<typename TF , typename TKF , typename TKS , typename TDK > std::ostream& DGtal::operator<< (std::ostream & out, const DGtal::DigitalSurfaceConvolver< TF, TKF, TKS, TDK, 2 > & object)
template<typename TF , typename TKF , typename TKS , typename TDK > std::ostream& DGtal::operator<< (std::ostream & out, const DGtal::DigitalSurfaceConvolver< TF, TKF, TKS, TDK, 3 > & object)
template<typename TInteger > std::ostream& DGtal::operator<< (std::ostream & out, const FreemanChain< TInteger > & object)
Overloads 'operator<<' for displaying objects of class 'FreemanChain'.
Parameters
out the output stream where the object is written.
object the object of class 'FreemanChain' to write.
Returns
the output stream after the writing.
template<typename TData , unsigned int L, typename TWord , unsigned int N, unsigned int M> std::ostream& DGtal::operator<< (std::ostream & out, const LabelledMap< TData, L, TWord, N, M > & object)
Overloads 'operator<<' for displaying objects of class 'LabelledMap'.
Parameters
out the output stream where the object is written.
object the object of class 'LabelledMap' to write.
Returns
the output stream after the writing.
Template Parameters
TData the type for the datas stored in the list.
N the number of data stored in the first block.
M the number of data stored in the further blocks.
template<typename TKSpace , typename TCellContainer > std::ostream& DGtal::operator<< (std::ostream & out, const CubicalComplex< TKSpace, TCellContainer > & object)
Overloads 'operator<<' for displaying objects of class 'CubicalComplex'.
Parameters
out the output stream where the object is written.
object the object of class 'CubicalComplex' to write.
Returns
the output stream after the writing.
template<Dimension dim, typename TInteger > std::ostream& DGtal::operator<< (std::ostream & out, const KhalimskyPreSpaceND< dim, TInteger > & object)
Overloads 'operator<<' for displaying objects of class 'KhalimskyPreSpaceND'.
Parameters
out the output stream where the object is written.
object the object of class 'KhalimskyPreSpaceND' to write.
Returns
the output stream after the writing.
template<int N, typename TRing , class TAlloc > std::ostream& DGtal::operator<< (std::ostream & out, const MPolynomial< N, TRing, TAlloc > & object)
Overloads 'operator<<' for displaying objects of class 'MPolynomial'.
Parameters
out the output stream where the object is written.
object the object of class 'MPolynomial' to write.
Returns
the output stream after the writing.
template<typename TSpace , typename TKSpace > std::ostream& DGtal::operator<< (std::ostream & out, const Viewer3D< TSpace, TKSpace > & object)
Overloads 'operator<<' for displaying objects of class 'Viewer3D'.
Parameters
out the output stream where the object is written.
object the object of class 'Viewer3D' to write.
Returns
the output stream after the writing.
template<Dimension dim, typename TInteger > std::ostream& DGtal::operator<< (std::ostream & out, const KhalimskySpaceND< dim, TInteger > & object)
Overloads 'operator<<' for displaying objects of class 'KhalimskySpaceND'.
Parameters
out the output stream where the object is written.
object the object of class 'KhalimskySpaceND' to write.
Returns
the output stream after the writing.
template<typename TPoint > bool DGtal::operator>> (Mesh< TPoint > & aMesh, const std::string & aFilename)
'operator>>' for exporting objects of class 'Mesh'. This operator automatically selects the good method according to the filename extension (off, obj).
Parameters
aMesh the mesh to be exported.
aFilename the filename of the file to be exported.
Returns
true, if the export was successful.
template<typename TPoint > bool DGtal::operator>> (Mesh< TPoint > & aMesh, std::ostream & out)
'operator>>' for exporting objects of class 'Mesh' in OFF format.
Parameters
aMesh the mesh to be exported.
out the output of the OFF exportation.
Returns
true, if the export was successful.
template<typename TImageContainer > bool DGtal::operator>> (const TImageContainer & aContainer, const std::string & aFilename)
'operator>>' for exporting an ImageContainer. This operator automatically selects the best method according to the filename extension (pgm, pgm3D, raw, vol).
Parameters
aContainer the container to be exported.
aFilename the filename of the file to be exported.
Returns
true, if the export was successful.
template<int n, typename TRing , class TAlloc > std::istream& DGtal::operator>> (std::istream & in, MPolynomial< n, TRing, TAlloc > & aMPolynomial)
Overloads 'operator>>' to create directly multi-variate polynomials from input istreams. Note that the type of aMPolynomial defines the kind of constructed polynomial. For instance, if the stream is "x+1" and the type is MPolynomial<2,int>, then the polynomial is 2-variate like P(x,y)=1+x.
The stream is read till the end of line. It may stop before if the stream does not correspond anymore to a multi-variate polynomial. The stream is returned at the position where the polynomial reader stopped (except the newline).
Parameters
in the input stream.
aMPolynomial (returns) the modified polynomial constructed from the input stream.
Template Parameters
n the number of variables of the polynomial
TRing the coefficient ring
TAlloc is an allocator for TRing, for example std::allocator<TRing>; this is also the default parameter. Usually this parameter does not needs to be changed.
template<typename Space , typename KSpace > void DGtal::operator>> (const Display3D< Space, KSpace > & aDisplay3D, DGtal::Mesh< typename Display3D< Space, KSpace >::RealPoint > & aMesh)
Operator ">>" to export a Display3D into a Mesh
Parameters
aDisplay3D the Display3D to be exported.
aMesh (return) the resulting mesh.
template<typename Space , typename KSpace > void DGtal::operator>> (const Display3D< Space, KSpace > & aDisplay3D, std::string aFilename)
Operator ">>" to export a Display3D directly a file
Parameters
aDisplay3D the Display3D to be exported.
aFilename (return) the resulting mesh.
template<typename SC > void DGtal::oppositeEndMaximalExtension (SC & s, const typename SC::ConstIterator & begin, IteratorType)
Specialization for Iterator type
Definition at line 198 of file SegmentComputerUtils.h.
Referenced by firstMaximalSegment(), lastMaximalSegment(), mostCenteredMaximalSegment(), oppositeEndMaximalExtension(), and previousMaximalSegment().
{
   //extend one more time if s.begin() == begin
   while ( (s.begin() != begin)
        && (s.extendBack()) ) {}
   if (s.begin() == begin) s.extendBack();
 }
template<typename SC > void DGtal::oppositeEndMaximalExtension (SC & s, const typename SC::ConstIterator & begin, CirculatorType)
Specialization for Circulator type
Definition at line 209 of file SegmentComputerUtils.h.
 {
   boost::ignore_unused_variable_warning( begin );
   //stop if the segment is the whole range
   const typename SC::ConstIterator newBegin( s.end() );
   while ( (s.extendBack())
        && (s.begin() != newBegin) ) {}
 }
template<typename SC > void DGtal::oppositeEndMaximalExtension (SC & s, const typename SC::ConstIterator & begin)
Calls s.extendBack() while possible
Parameters
s any instance of (bidirectional) segment computer
begin any ConstIterator
Template Parameters
SC any model of CBidirectionalSegmentComputer
Definition at line 225 of file SegmentComputerUtils.h.
References oppositeEndMaximalExtension().
{
   typedef typename IteratorCirculatorTraits<typename SC::ConstIterator>::Type Type;
   oppositeEndMaximalExtension( s, begin, Type() );
 }
template<typename SC > void DGtal::oppositeEndMaximalRetraction (SC & s, const typename SC::ConstIterator & begin)
Calls s.retractFront() while s.isExtendableBack() returns false
Parameters
s any instance of segment computer
begin any ConstIterator
Template Parameters
SC any model of segment computer
Definition at line 341 of file SegmentComputerUtils.h.
Referenced by previousMaximalSegment().
 {
   if ( isNotEmpty<typename SC::ConstIterator>(s.begin(),begin) ) {
     while ( (! s.isExtendableBack() )
           &&(s.retractFront() ) ) {}
   } else {
     while ( s.retractFront() ) {}
   }
 }
template<typename SC > void DGtal::previousMaximalSegment (SC & s, const typename SC::ConstIterator & begin, DGtal::ForwardSegmentComputer)
Computes the previous maximal segment of s (s is assumed to be maximal)
Parameters
s any instance of segment computer
begin any begin ConstIterator
Template Parameters
SC any model of CForwardSegmentComputer
Note
lastMaximalSegment of –s.begin()
Definition at line 895 of file SegmentComputerUtils.h.
References lastMaximalSegment().
Referenced by previousMaximalSegment().
 {
   if ( isNotEmpty<typename SC::ConstIterator>(s.begin(),begin) )
     lastMaximalSegment(s, --s.begin(), begin, s.end(), DGtal::ForwardSegmentComputer() );
 }
template<typename SC > void DGtal::previousMaximalSegment (SC & s, const typename SC::ConstIterator & begin, DGtal::BidirectionalSegmentComputer)
Computes the previous maximal segment of s (s is assumed to be maximal)
Parameters
s any instance of segment computer
begin any begin ConstIterator
Template Parameters
SC any model of CBidirectionalSegmentComputer
Note
lastMaximalSegment of –s.begin()
Definition at line 912 of file SegmentComputerUtils.h.
References lastMaximalSegment().
 {
   if ( isNotEmpty<typename SC::ConstIterator>(s.begin(),begin) )
     lastMaximalSegment(s, --s.begin(), begin, s.end(), DGtal::BidirectionalSegmentComputer() );
 }
template<typename SC > void DGtal::previousMaximalSegment (SC & s, const typename SC::ConstIterator & begin, DGtal::DynamicSegmentComputer)
Computes the previous maximal segment of s (s is assumed to be maximal)
Parameters
s any instance of segment computer
begin any begin ConstIterator
Template Parameters
SC any model of CDynamicSegmentComputer
Definition at line 928 of file SegmentComputerUtils.h.
References oppositeEndMaximalExtension(), and oppositeEndMaximalRetraction().
 {
   typedef typename SC::ConstIterator ConstIterator;
   //rectract
   oppositeEndMaximalRetraction(s, begin);
   //intersection test
   ConstIterator i( s.end() ); --i;
   //if the intersection between the two
   // consecutive maximal segments is empty
   if ( i == s.begin() ) {
     if ( isNotEmpty<ConstIterator>(i, begin) ) {
       --i;
       s.init(i);
     }
   }
   //extend
   oppositeEndMaximalExtension(s, begin);
 }
template<typename SC > void DGtal::previousMaximalSegment (SC & s, const typename SC::ConstIterator & end, DGtal::DynamicBidirectionalSegmentComputer)
Computes the previous maximal segment of s (s is assumed to be maximal)
Parameters
s any instance of segment computer
end end ConstIterator
Template Parameters
SC any model of CDynamicBidirectionalSegmentComputer
Note
calls the function dedicated to DynamicSegmentComputer
Definition at line 963 of file SegmentComputerUtils.h.
References previousMaximalSegment().
 {
   previousMaximalSegment(s, end, DGtal::DynamicSegmentComputer() );
 }
template<typename SC > void DGtal::previousMaximalSegment (SC & s, const typename SC::ConstIterator & begin)
Computes the previous maximal segment of s (s is assumed to be maximal)
Parameters
s any instance of segment computer
begin any begin ConstIterator
Template Parameters
SC any model of segment computer
Definition at line 978 of file SegmentComputerUtils.h.
References previousMaximalSegment().
 {
   previousMaximalSegment(s, begin,
 typename DGtal::SegmentComputerTraits<SC>::Category() );
 }
template<typename IC > IC DGtal::rangeMiddle (const IC & itb, const IC & ite) inline
Computes the middle iterator of a given range [ itb , ite). If the size of a given range is n, its middle would be equal to the iterator itb after n/2 incrementations. In the two following examples, m locates the middle of the range :
odd case: b—|—m—|—|—e
even case: b—|—|—m—|—|—e
Parameters
itb begin iterator of the range
ite end iterator of the range
Returns
the middle iterator of the range [ itb , ite)
Template Parameters
IC any model iterator or circulator
template<typename IC > IteratorCirculatorTraits<IC>::Difference DGtal::rangeSize (const IC & itb, const IC & ite) inline
Computes the size of a given range [ itb , ite)
Parameters
itb begin iterator of the range
ite end iterator of the range
Returns
the size
Template Parameters
IC any model of iterator or circulator
template<typename Word > FILE* DGtal::raw_reader_read_word (FILE * fin, Word & aValue)
Generic read word (binary mode) in little-endian mode.
Parameters
fin input FILE.
aValue value to write.
Returns
modified stream.
template<typename Word > std::ostream& DGtal::raw_writer_write_word (std::ostream & outs, Word value)
Generic write word (binary mode) in little-endian.
Parameters
outs output stream.
value value to write.
Returns
modified stream.
template<Dimension dim, typename Container > std::bitset<dim> DGtal::setDimensionsIn (const Container & dimensions)
Returns
a bitset having true for each dimension presents in dimensions.
template<Dimension dim, typename Container > std::bitset<dim> DGtal::setDimensionsNotIn (const Container & dimensions)
Returns
a bitset having true for each dimension not presents in dimensions.
template<typename I , typename O > void DGtal::setFromImage (const I & aImg, const O & ito, const typename I::Value & aThreshold = 0)
Fill a set through the inserter ito with the points lying within the domain of the image aImg whose value (in the image) is less than or equal to aThreshold
Parameters
aImg any image
ito set inserter
aThreshold any value (default: 0)
Template Parameters
I any model of CConstImage
O any model of output iterator
template<typename I , typename O > void DGtal::setFromImage (const I & aImg, const O & ito, const typename I::Value & low, const typename I::Value & up)
Fill a set through the inserter ito with the points lying within the domain of the image aImg whose value (in the image) lies between low and up (both included)
Parameters
aImg any image
ito set inserter
low lower value
up upper value
Template Parameters
I any model of CConstImage
O any model of output iterator
template<typename I , typename O , typename F > void DGtal::setFromPointsRangeAndFunctor (const I & itb, const I & ite, const O & ito, const F & aFunctor, const typename F::Value & aThreshold = 0)
Fill a set through the inserter ito with the points of the range [itb , ite) such that their associated value (returned by aFunctor) is less than or equal to aThreshold
Parameters
itb begin iterator on points
ite end iterator on points
ito output iterator on points
aFunctor any functor on points
aThreshold any value (default: 0)
Template Parameters
I any model of input iterator
O any model of output iterator
F any model of CPointFunctor
template<typename I , typename O , typename P > void DGtal::setFromPointsRangeAndPredicate (const I & itb, const I & ite, const O & ito, const P & aPred)
useful functions
Fill a set through the inserter ito with the points of the range [itb , ite) such that aPred is true
Parameters
itb begin iterator on points
ite end iterator on points
ito output iterator on points
aPred any predicate
Template Parameters
I any model of input iterator
O any model of output iterator
P any model of concepts::CPointPredicate
template<typename IC > IC DGtal::subRangeMiddle (const IC & itb, const IC & ite) inline
Computes the middle iterator of a given subrange [ itb , ite) (calls rangeMiddle with IteratorType whatever the true type of IC)
Parameters
itb begin iterator of the subrange
ite end iterator of the subrange
Returns
the middle iterator of the subrange [ itb , ite)
Template Parameters
IC any model of iterator or circulator
template<typename IC > IteratorCirculatorTraits<IC>::Difference DGtal::subRangeSize (const IC & itb, const IC & ite) inline
Computes the size of a given subrange [ itb , ite), (calls rangeSize functions with IteratorType, whatever the true type of IC)
Parameters
itb begin iterator of the subrange
ite end iterator of the subrange
Returns
the size
Template Parameters
IC any model of iterator or circulator
template<typename KSpace , typename PointPredicate > bool DGtal::testImplicitDigitalSurface (const KSpace & K, const PointPredicate & pp, const typename KSpace::Surfel & bel)
Definition at line 49 of file testImplicitDigitalSurface-benchmark.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and trace.
   {
     typedef ImplicitDigitalSurface<KSpace,PointPredicate> Boundary;
     typedef typename Boundary::SurfelConstIterator ConstIterator;
     unsigned int nbok = 0;
     unsigned int nb = 0;
     trace.beginBlock ( "Testing block ... ImplicitDigitalSurface" );
     trace.beginBlock ( "ImplicitDigitalSurface instanciation" );
     Boundary boundary( K, pp,
                        SurfelAdjacency<KSpace::dimension>( true ), bel,
                        true );
     trace.endBlock();
     trace.beginBlock ( "Counting the number of surfels (breadth first traversal)" );
     unsigned int nbsurfels = 0;
     for ( ConstIterator it = boundary.begin(), it_end = boundary.end();
           it != it_end; ++it )
       {
         ++nbsurfels;
       }
     trace.info() << nbsurfels << " surfels found." << std::endl;
     nb++, nbok += nbsurfels == 354382 ? 1 : 0;
     trace.info() << "(" << nbok << "/" << nb << ") "
                    << "nbsurfels == 354382" << std::endl;
     trace.endBlock();
     trace.endBlock();
     return nbok == nb;
   }
template<typename KSpace , typename PointPredicate > bool DGtal::testLightImplicitDigitalSurface (const KSpace & K, const PointPredicate & pp, const typename KSpace::Surfel & bel)
Definition at line 49 of file testLightImplicitDigitalSurface-benchmark.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and trace.
   {
     typedef LightImplicitDigitalSurface<KSpace,PointPredicate> Boundary;
     typedef typename Boundary::SurfelConstIterator ConstIterator;
     unsigned int nbok = 0;
     unsigned int nb = 0;
     trace.beginBlock ( "Testing block ... LightImplicitDigitalSurface" );
     trace.beginBlock ( "LightImplicitDigitalSurface instanciation" );
     Boundary boundary( K, pp,
                        SurfelAdjacency<KSpace::dimension>( true ), bel );
     trace.endBlock();
     trace.beginBlock ( "Counting the number of surfels (breadth first traversal)" );
     unsigned int nbsurfels = 0;
     for ( ConstIterator it = boundary.begin(), it_end = boundary.end();
           it != it_end; ++it )
       {
         ++nbsurfels;
       }
     trace.info() << nbsurfels << " surfels found." << std::endl;
     nb++, nbok += nbsurfels == 354382 ? 1 : 0;
     trace.info() << "(" << nbok << "/" << nb << ") "
                    << "nbsurfels == 354382" << std::endl;
     trace.endBlock();
     trace.endBlock();
     return nbok == nb;
   }
Trace DGtal::trace (traceWriterTerm)
template<int n, typename Ring , typename Alloc > MPolynomial<n, Ring, Alloc> DGtal::Xe_k (unsigned int k, unsigned int e) inline
Creates a monomial X_k^e
Parameters
k the index of the variable (X_k)
e the exponent for X_k
Returns
the 1-variable polynomial X_0^e
Template Parameters
n the number of indetermionates.
Ring the type for the coefficent ring of the polynomial.
Alloc the type of allocator.
Definition at line 1654 of file MPolynomial.h.
   {
     return Xe_kComputer<n, Ring, Alloc>().get( k, e );
   }
template<int n, typename Ring > MPolynomial<n, Ring, std::allocator<Ring> > DGtal::Xe_k (unsigned int k, unsigned int e) inline
Creates a monomial X_k^e
Parameters
k the index of the variable (X_k)
e the exponent for X_k
Returns
the 1-variable polynomial X_0^e
Template Parameters
n the number of indetermionates.
Ring the type for the coefficent ring of the polynomial.
Definition at line 1670 of file MPolynomial.h.
   {
     return Xe_kComputer<n, Ring, std::allocator<Ring> >().get( k, e );
   }
Variable Documentation
std::size_t const DGtal::HALF_EDGE_INVALID_INDEX = boost::integer_traits<std::size_t>::const_max static
Defines the invalid half-edge (i.e. exterior).
Note
It is defined external to the HalfEdgeDataStructure because there was link error with gcc 4.8.4 for all variants within HalfEdgeDataStructure (e.g. BOOST_STATIC_CONSTANT, c++ constexpr, c++ constexpr with const reference).
Definition at line 57 of file HalfEdgeDataStructure.h.
Referenced by DGtal::HalfEdgeDataStructure::arc2FaceIndex().
Trace DGtal::trace
DGtal Assert function.
ASSERT(expr) and ASSERT_MSG(expr, message) are defined and expr is avaluated only when NDEBUG isn't defined. FATAL_ERROR(expr) and FATAL_ERROR_MSG(expr, message) are always defined.
Examples:
dec/exampleDECSurface.cpp, dec/exampleDiscreteExteriorCalculusSolve.cpp, dec/exampleHeatLaplace.cpp, dec/examplePropagation.cpp, geometry/volumes/distance/exampleFMM3D.cpp, tutorial-examples/AreaSurfaceEstimation-final.cpp, tutorial-examples/FMMErosion.cpp, and tutorial-examples/volDTGranulo.cpp.
Definition at line 137 of file Common.h.
Referenced by DGtal::ConstImageAdapter< TImageContainer, TNewDomain, TFunctorD, TNewValue, TFunctorV >::ConstImageAdapter(), DGtal::VoxelComplex< KSpace, FixtureObject >::criticalCliques(), DGtal::functors::SphereFittingEstimator< TSurfel, TEmbedder, TNormalVectorEstimatorCache >::eval(), DGtal::ImageFactoryFromHDF5< TImageContainer >::flushImage(), DGtal::functions::generateSimplicityTable(), DGtal::functions::generateVoxelComplexTable(), DGtal::Image< TImageContainer >::Image(), DGtal::ImageAdapter< TImageContainer, TNewDomain, TFunctorD, TNewValue, TFunctorV, TFunctorVm1 >::ImageAdapter(), DGtal::GenericReader< TContainer, Tdim, TValue >::importWithColorFunctor(), DGtal::GenericReader< TContainer, 2, TValue >::importWithColorFunctor(), DGtal::GenericReader< TContainer, 2, DGtal::uint32_t >::importWithColorFunctor(), DGtal::GenericReader< TContainer, Tdim, TValue >::importWithValueFunctor(), DGtal::GenericReader< TContainer, 3, TValue >::importWithValueFunctor(), DGtal::GenericReader< TContainer, 3, DGtal::uint32_t >::importWithValueFunctor(), DGtal::GenericReader< TContainer, 2, TValue >::importWithValueFunctor(), DGtal::GenericReader< TContainer, 2, DGtal::uint32_t >::importWithValueFunctor(), DGtal::functors::Point2DEmbedderIn3D< TDomain3D, TInteger >::operator()(), DGtal::functors::BasicDomainSubSampler< TDomain, TInteger, TValue >::operator()(), DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::operator()(), DGtal::ConstImageAdapter< TImageContainer, TNewDomain, TFunctorD, TNewValue, TFunctorV >::operator=(), DGtal::ImageAdapter< TImageContainer, TNewDomain, TFunctorD, TNewValue, TFunctorV, TFunctorVm1 >::operator=(), DGtal::Image< TImageContainer >::operator=(), DGtal::functors::SphereFittingEstimator< TSurfel, TEmbedder, TNormalVectorEstimatorCache >::pushSurfel(), DGtal::ImageFactoryFromHDF5< TImageContainer >::requestImage(), HodgeTester< Calculus, order >::test(), DerivativeTester< Calculus, order >::test(), testImplicitDigitalSurface(), and testLightImplicitDigitalSurface().
TraceWriterTerm DGtal::traceWriterTerm
DGtal Global variables
Definition at line 136 of file Common.h.