DGtal: LibBoard::Circle Struct Reference
LibBoard::Circle Struct Reference
#include <Board/Shapes.h>
Public Member Functions
Circle (double x, double y, double radius, DGtal::Color pen, DGtal::Color fill, double lineWidth, const LineStyle style=SolidStyle, int depthValue=-1)
const std::string & name () const
Point center () const
Circle & rotate (double angle, const Point &center)
Circle rotated (double angle, const Point &center) const
Circle & rotate (double angle)
Circle rotated (double angle) const
Circle & translate (double dx, double dy)
Circle translated (double dx, double dy) const
Shape & scale (double sx, double sy)
Shape & scale (double s)
Circle scaled (double sx, double sy) const
Circle scaled (double s) const
void scaleAll (double s)
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
Circle * clone () const
Public Member Functions inherited from LibBoard::Ellipse
Ellipse (double x, double y, double xRadius, double yRadius, DGtal::Color pen, DGtal::Color fill, double lineWidth, const LineStyle lineStyle=SolidStyle, int depthValue=-1)
Ellipse rotated (double angle, const Point &center) const
Ellipse rotated (double angle) const
Ellipse translated (double dx, double dy) const
Ellipse scaled (double sx, double sy) const
Ellipse scaled (double s) const
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const
Rect boundingBox () const
Public Member Functions inherited from LibBoard::Shape
Shape (DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, LineStyle style, const LineCap cap, const LineJoin join, int depth)
virtual ~Shape ()
bool filled () const
Shape & rotateDeg (double angle, const Point &center)
Shape & rotateDeg (double angle)
Rect bbox ()
Shape & operator-- ()
Shape & operator++ ()
int depth () const
virtual void depth (int)
virtual void shiftDepth (int shift)
const DGtal::Color & penColor () const
const DGtal::Color & fillColor () const
Static Private Attributes
static const std::string _name
Additional Inherited Members
Public Types inherited from LibBoard::Shape
enum LineCap { ButtCap = 0, RoundCap, SquareCap }
enum LineJoin { MiterJoin = 0, RoundJoin, BevelJoin }
enum LineStyle {
SolidStyle = 0, DashStyle, DotStyle, DashDotStyle,
DashDotDotStyle, DashDotDotDotStyle
}
Protected Member Functions inherited from LibBoard::Shape
std::string svgProperties (const TransformSVG &transform) const
std::string postscriptProperties () const
void setCairoDashStyle (cairo_t *cr, LineStyle type) const
std::string tikzProperties (const TransformTikZ &transform) const
Protected Attributes inherited from LibBoard::Ellipse
Point _center
double _xRadius
double _yRadius
double _angle
bool _circle
Protected Attributes inherited from LibBoard::Shape
int _depth
DGtal::Color _penColor
DGtal::Color _fillColor
double _lineWidth
LineStyle _lineStyle
LineCap _lineCap
LineJoin _lineJoin
Detailed Description
A circle.
The circle structure.
Definition at line 1460 of file Board/Shapes.h.
Constructor & Destructor Documentation
LibBoard::Circle::Circle (double x, double y, double radius, DGtal::Color pen, DGtal::Color fill, double lineWidth, const LineStyle style = SolidStyle, int depthValue = -1) inline
Definition at line 1462 of file Board/Shapes.h.
References LibBoard::Ellipse::_circle.
Referenced by clone(), rotated(), scaled(), and translated().
     : Ellipse( x, y, radius, radius, pen, fill, lineWidth, style, depthValue )
   { _circle = true; }
Member Function Documentation
Point LibBoard::Circle::center () const virtual
Returns the gravity center of the shape.
Returns
The center of the shape.
Reimplemented from LibBoard::Ellipse.
Definition at line 1328 of file Shapes.cpp.
References LibBoard::Ellipse::_center.
                      {
     return _center;
 }
Circle * LibBoard::Circle::clone () const virtual
Return a copy of the shape.
Returns
copye of the shape.
Reimplemented from LibBoard::Ellipse.
Definition at line 1410 of file Shapes.cpp.
References Circle().
                     {
     return new Circle(*this);
 }
void LibBoard::Circle::flushCairo (cairo_t * cr, const TransformCairo & transform) const virtual
Writes the cairo code of the shape in a cairo drawing context according to a transform.
Parameters
cr The cairo drawing context.
transform A 2D transform to be applied.
Reimplemented from LibBoard::Ellipse.
Reimplemented in LibBoard::Arc.
Definition at line 1431 of file Shapes.cpp.
References LibBoard::Ellipse::_center, LibBoard::Ellipse::_circle, LibBoard::Shape::_fillColor, LibBoard::Shape::_lineCap, LibBoard::Shape::_lineJoin, LibBoard::Shape::_lineStyle, LibBoard::Shape::_lineWidth, LibBoard::Shape::_penColor, LibBoard::Ellipse::_xRadius, DGtal::Color::blue(), LibBoard::Shape::filled(), LibBoard::Ellipse::flushCairo(), DGtal::Color::green(), LibBoard::Transform::mapX(), LibBoard::TransformCairo::mapY(), DGtal::Color::None, DGtal::Color::red(), LibBoard::Transform::scale(), LibBoard::Shape::setCairoDashStyle(), LibBoard::Point::x, and LibBoard::Point::y.
 {
     if ( ! _circle )
         Ellipse::flushCairo( cr, transform );
     else
     {
       cairo_save (cr);
   cairo_set_source_rgba (cr, _fillColor.red()/255.0, _fillColor.green()/255.0, _fillColor.blue()/255.0, 1.);
   cairo_arc (cr, transform.mapX( _center.x ), transform.mapY( _center.y ), transform.scale( _xRadius ), 0, 2*M_PI);
   if ( filled() )
   {
     if ( _penColor != DGtal::Color::None )
       cairo_fill_preserve (cr);
     else
       cairo_fill (cr);
   }
   //
   if ( _penColor != DGtal::Color::None )
   {
     cairo_set_source_rgba (cr, _penColor.red()/255.0, _penColor.green()/255.0, _penColor.blue()/255.0, 1.);
     cairo_set_line_width (cr, _lineWidth);
     cairo_set_line_cap (cr, cairoLineCap[_lineCap]);
     cairo_set_line_join (cr, cairoLineJoin[_lineJoin]);
     setCairoDashStyle (cr, _lineStyle);
     cairo_stroke (cr);
   }
       cairo_restore (cr);
     }
 }
void LibBoard::Circle::flushSVG (std::ostream & stream, const TransformSVG & transform) const virtual
Writes the SVG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Reimplemented from LibBoard::Ellipse.
Reimplemented in LibBoard::Arc.
Definition at line 1415 of file Shapes.cpp.
References LibBoard::Ellipse::_center, LibBoard::Ellipse::_circle, LibBoard::Ellipse::_xRadius, LibBoard::Ellipse::flushSVG(), LibBoard::Transform::mapX(), LibBoard::TransformSVG::mapY(), LibBoard::Transform::scale(), LibBoard::Shape::svgProperties(), LibBoard::Point::x, and LibBoard::Point::y.
 {
     if ( ! _circle )
         Ellipse::flushSVG( stream, transform );
     else {
         stream << "<circle cx=\"" << transform.mapX( _center.x ) << '"'
         << " cy=\"" << transform.mapY( _center.y ) << '"'
         << " r=\"" << transform.scale( _xRadius ) << '"'
         << svgProperties( transform )
         << " />" << std::endl;
     }
 }
void LibBoard::Circle::flushTikZ (std::ostream & stream, const TransformTikZ & transform) const virtual
Writes the TikZ code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Reimplemented from LibBoard::Ellipse.
Reimplemented in LibBoard::Arc.
Definition at line 1472 of file Shapes.cpp.
References LibBoard::Ellipse::_center, LibBoard::Ellipse::_circle, LibBoard::Ellipse::_xRadius, LibBoard::Ellipse::flushTikZ(), LibBoard::Transform::mapX(), LibBoard::TransformSVG::mapY(), LibBoard::Transform::scale(), LibBoard::Shape::tikzProperties(), LibBoard::Point::x, and LibBoard::Point::y.
 {
     if ( ! _circle )
         Ellipse::flushTikZ( stream, transform );
     else {
         stream << "\\path[" << tikzProperties(transform) << "] ("
         << transform.mapX( _center.x ) << ','
         << transform.mapY( _center.y ) << ')'
         << " circle (" << transform.scale( _xRadius ) << ");"
         << std::endl;
     }
 }
const std::string & LibBoard::Circle::name () const virtual
Returns the generic name of the shape (e.g., Circle, Rectangle, etc.)
Returns
generic name as a string
Reimplemented from LibBoard::Ellipse.
Reimplemented in LibBoard::Arc.
Definition at line 1322 of file Shapes.cpp.
References _name.
 {
     return _name;
 }
Circle & LibBoard::Circle::rotate (double angle, const Point & center) virtual
Rotate the shape around a given center of rotation.
Parameters
angle The rotation angle in radian.
center The center of rotation.
Returns
A reference to the shape itself.
Reimplemented from LibBoard::Ellipse.
Definition at line 1333 of file Shapes.cpp.
References LibBoard::Ellipse::_center, LibBoard::Ellipse::_circle, LibBoard::Point::rotate(), and LibBoard::Ellipse::rotate().
 {
     if ( _circle ) {
         if ( rotCenter == _center ) return *this;
         _center.rotate( angle, rotCenter );
         return *this;
     }
     Ellipse::rotate( angle, rotCenter );
     return *this;
 }
Circle & LibBoard::Circle::rotate (double angle) virtual
Rotate the shape around its center.
Parameters
angle The rotation angle in radian.
Returns
A reference to the shape itself.
Reimplemented from LibBoard::Ellipse.
Definition at line 1351 of file Shapes.cpp.
References LibBoard::Ellipse::_circle, and LibBoard::Ellipse::rotate().
 {
     if ( !_circle )
         Ellipse::rotate( angle );
     return *this;
 }
Circle LibBoard::Circle::rotated (double angle, const Point & center) const
Definition at line 1345 of file Shapes.cpp.
References Circle().
 {
     return Circle(*this).rotate( angle, rotCenter );
 }
Circle LibBoard::Circle::rotated (double angle) const
Definition at line 1359 of file Shapes.cpp.
References Circle().
 {
     return Circle(*this).rotate( angle );
 }
Shape & LibBoard::Circle::scale (double sx, double sy) virtual
Scale the shape along the x an y axis.
Parameters
sx The scale factor along the x axis.
sy The scale factor along the y axis.
Returns
The shape itself.
Reimplemented from LibBoard::Ellipse.
Definition at line 1378 of file Shapes.cpp.
References LibBoard::Ellipse::scale().
 {
     return Ellipse::scale( sx, sy );
 }
Shape & LibBoard::Circle::scale (double s) virtual
Scale the shape along both axis.
Parameters
s The scale factor along both axis.
Returns
The shape itself.
Reimplemented from LibBoard::Ellipse.
Definition at line 1384 of file Shapes.cpp.
References LibBoard::Ellipse::scale().
 {
     return Ellipse::scale( s );
 }
void LibBoard::Circle::scaleAll (double s) virtual
Scales all the values (positions, dimensions, etc.) associated with the shape.
Parameters
s The scaling factor.
Reimplemented from LibBoard::Ellipse.
Definition at line 1402 of file Shapes.cpp.
References LibBoard::Ellipse::_center, LibBoard::Ellipse::_xRadius, and LibBoard::Ellipse::_yRadius.
 {
     _center *= s;
     _xRadius *= s;
     _yRadius *= s;
 }
Circle LibBoard::Circle::scaled (double sx, double sy) const
Definition at line 1390 of file Shapes.cpp.
References Circle().
 {
     return static_cast<Circle &>( Circle(*this).scale( sx, sy ) );
 }
Circle LibBoard::Circle::scaled (double s) const
Definition at line 1396 of file Shapes.cpp.
References Circle().
 {
     return static_cast<Circle &>( Circle(*this).scale( s, s ) );
 }
Circle & LibBoard::Circle::translate (double dx, double dy) virtual
Translate the shape by a given offset.
Parameters
dx The x offset.
dy The y offset.
Returns
A reference to the shape itself.
Reimplemented from LibBoard::Ellipse.
Definition at line 1365 of file Shapes.cpp.
References LibBoard::Ellipse::_center.
 {
     _center += Point( dx, dy );
     return *this;
 }
Circle LibBoard::Circle::translated (double dx, double dy) const
Definition at line 1372 of file Shapes.cpp.
References Circle().
 {
     return Circle(*this).translate( dx, dy );
 }
Field Documentation
const std::string LibBoard::Circle::_name static private
The generic name of the shape.
Definition at line 1521 of file Board/Shapes.h.
Referenced by name().
The documentation for this struct was generated from the following files:
Board/Shapes.h
Shapes.cpp