DGtal: LibBoard::Shape Struct Reference
LibBoard::Shape Struct Reference abstract
#include <Board/Shapes.h>
Public Types
enum LineCap { ButtCap = 0, RoundCap, SquareCap }
enum LineJoin { MiterJoin = 0, RoundJoin, BevelJoin }
enum LineStyle {
SolidStyle = 0, DashStyle, DotStyle, DashDotStyle,
DashDotDotStyle, DashDotDotDotStyle
}
Public Member Functions
Shape (DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, LineStyle style, const LineCap cap, const LineJoin join, int depth)
virtual ~Shape ()
virtual const std::string & name () const
virtual Shape * clone () const =0
bool filled () const
virtual Point center () const =0
virtual Shape & rotate (double angle, const Point &center)=0
virtual Shape & rotate (double angle)=0
Shape & rotateDeg (double angle, const Point &center)
Shape & rotateDeg (double angle)
virtual Shape & translate (double dx, double dy)=0
virtual Shape & scale (double sx, double sy)=0
virtual Shape & scale (double s)=0
virtual Rect boundingBox () const =0
Rect bbox ()
Shape & operator-- ()
Shape & operator++ ()
virtual void scaleAll (double s)=0
virtual void flushPostscript (std::ostream &stream, const TransformEPS &transform) const =0
virtual void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const =0
virtual void flushSVG (std::ostream &stream, const TransformSVG &transform) const =0
virtual void flushCairo (cairo_t *cr, const TransformCairo &transform) const =0
virtual void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const =0
int depth () const
virtual void depth (int)
virtual void shiftDepth (int shift)
const DGtal::Color & penColor () const
const DGtal::Color & fillColor () const
Protected Member Functions
std::string svgProperties (const TransformSVG &transform) const
std::string postscriptProperties () const
void setCairoDashStyle (cairo_t *cr, LineStyle type) const
std::string tikzProperties (const TransformTikZ &transform) const
Protected Attributes
int _depth
DGtal::Color _penColor
DGtal::Color _fillColor
double _lineWidth
LineStyle _lineStyle
LineCap _lineCap
LineJoin _lineJoin
Static Private Attributes
static const std::string _name
Detailed Description
Abstract structure for a 2D shape.
Shape structure.
Definition at line 58 of file Board/Shapes.h.
Member Enumeration Documentation
enum LibBoard::Shape::LineCap
Enumerator
ButtCap
RoundCap
SquareCap
Definition at line 60 of file Board/Shapes.h.
 { ButtCap = 0, RoundCap, SquareCap };
enum LibBoard::Shape::LineJoin
Enumerator
MiterJoin
RoundJoin
BevelJoin
Definition at line 61 of file Board/Shapes.h.
 { MiterJoin = 0, RoundJoin, BevelJoin };
enum LibBoard::Shape::LineStyle
Enumerator
SolidStyle
DashStyle
DotStyle
DashDotStyle
DashDotDotStyle
DashDotDotDotStyle
Definition at line 62 of file Board/Shapes.h.
                  { SolidStyle = 0,
        DashStyle,
        DotStyle,
        DashDotStyle,
        DashDotDotStyle,
        DashDotDotDotStyle };
Constructor & Destructor Documentation
LibBoard::Shape::Shape (DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, LineStyle style, const LineCap cap, const LineJoin join, int depth) inline
Shape constructor.
Parameters
penColor The pen color of the shape.
fillColor The fill color of the shape.
lineWidth The line thickness.
style The line style.
cap The line cap.
join The line join.
depth The depth of the shape.
virtual LibBoard::Shape::~Shape () inline virtual
Shape destructor.
Definition at line 90 of file Board/Shapes.h.
 { }
Member Function Documentation
Rect LibBoard::Shape::bbox () inline
Returns the bounding box of the figure. (Convenience method to call "boundingBox" with a short name.)
Definition at line 339 of file Board/Shapes.h.
References boundingBox().
 {
   return this->boundingBox();
 }
virtual Rect LibBoard::Shape::boundingBox () const pure virtual
Returns the bounding box of the figure.
Returns
The rectangle of the bounding box.
Implemented in LibBoard::Text, LibBoard::Ellipse, LibBoard::Polyline, LibBoard::Line, LibBoard::Dot, LibBoard::Group, and LibBoard::ShapeList.
Referenced by bbox().
virtual Point LibBoard::Shape::center () const pure virtual
Returns the gravity center of the shape.
Returns
The center of the shape.
Implemented in LibBoard::Text, LibBoard::Circle, LibBoard::Ellipse, LibBoard::GouraudTriangle, LibBoard::Polyline, LibBoard::Line, LibBoard::Dot, and LibBoard::ShapeList.
Referenced by rotateDeg().
virtual Shape* LibBoard::Shape::clone () const pure virtual
Return a copy of the shape.
Returns
copye of the shape.
Implemented in LibBoard::Text, LibBoard::Circle, LibBoard::Ellipse, LibBoard::GouraudTriangle, LibBoard::Triangle, LibBoard::Image, LibBoard::Rectangle, LibBoard::Polyline, LibBoard::Arrow, LibBoard::Line, LibBoard::Dot, LibBoard::Group, and LibBoard::ShapeList.
Referenced by LibBoard::Board::addDuplicates(), LibBoard::ShapeList::addShape(), LibBoard::ShapeList::operator+=(), and LibBoard::ShapeList::operator<<().
int LibBoard::Shape::depth () const inline
Definition at line 361 of file Board/Shapes.h.
References _depth.
Referenced by LibBoard::ShapeList::addShape(), LibBoard::ShapeList::operator<<(), LibBoard::Board::saveFIG(), and LibBoard::shapeGreaterDepth().
 {
   return _depth;
 }
void LibBoard::Shape::depth (int d) virtual
Definition at line 194 of file Shapes.cpp.
References _depth.
 {
     _depth = d;
 }
const DGtal::Color & LibBoard::Shape::fillColor () const inline
Definition at line 373 of file Board/Shapes.h.
References _fillColor.
 {
   return _fillColor;
 }
bool LibBoard::Shape::filled () const inline
Checks whether a shape is filled with a color or not.
Returns
true if the shape is filled.
Definition at line 111 of file Board/Shapes.h.
References _fillColor, and DGtal::Color::None.
Referenced by LibBoard::Arrow::flushCairo(), LibBoard::Polyline::flushCairo(), LibBoard::Rectangle::flushCairo(), LibBoard::QuadraticBezierCurve::flushCairo(), LibBoard::Ellipse::flushCairo(), LibBoard::Circle::flushCairo(), LibBoard::Arc::flushCairo(), LibBoard::Arrow::flushFIG(), LibBoard::Polyline::flushFIG(), LibBoard::Rectangle::flushFIG(), LibBoard::Ellipse::flushFIG(), LibBoard::Arrow::flushPostscript(), LibBoard::Polyline::flushPostscript(), LibBoard::Ellipse::flushPostscript(), and LibBoard::Arc::flushPostscript().
 { return _fillColor != DGtal::Color::None; }
virtual void LibBoard::Shape::flushCairo (cairo_t * cr, const TransformCairo & transform) const pure virtual
Writes the cairo code of the shape in a cairo drawing context according to a transform.
Parameters
cr The cairo drawing context.
transform A 2D transform to be applied.
Implemented in LibBoard::Text, LibBoard::Arc, LibBoard::Circle, LibBoard::Ellipse, LibBoard::GouraudTriangle, LibBoard::QuadraticBezierCurve, LibBoard::Image, LibBoard::Rectangle, LibBoard::Polyline, LibBoard::Arrow, LibBoard::Line, LibBoard::Dot, LibBoard::Group, and LibBoard::ShapeList.
virtual void LibBoard::Shape::flushFIG (std::ostream & stream, const TransformFIG & transform, std::map< DGtal::Color, int > & colormap) const pure virtual
Writes the FIG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
colormap A colormap.
Implemented in LibBoard::Text, LibBoard::Ellipse, LibBoard::GouraudTriangle, LibBoard::QuadraticBezierCurve, LibBoard::Image, LibBoard::Rectangle, LibBoard::Polyline, LibBoard::Arrow, LibBoard::Line, LibBoard::Dot, LibBoard::Group, and LibBoard::ShapeList.
virtual void LibBoard::Shape::flushPostscript (std::ostream & stream, const TransformEPS & transform) const pure virtual
Writes the EPS code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implemented in LibBoard::Text, LibBoard::Arc, LibBoard::Ellipse, LibBoard::GouraudTriangle, LibBoard::QuadraticBezierCurve, LibBoard::Polyline, LibBoard::Arrow, LibBoard::Line, LibBoard::Dot, LibBoard::Group, and LibBoard::ShapeList.
virtual void LibBoard::Shape::flushSVG (std::ostream & stream, const TransformSVG & transform) const pure virtual
Writes the SVG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implemented in LibBoard::Text, LibBoard::Arc, LibBoard::Circle, LibBoard::Ellipse, LibBoard::GouraudTriangle, LibBoard::QuadraticBezierCurve, LibBoard::Image, LibBoard::Rectangle, LibBoard::Polyline, LibBoard::Arrow, LibBoard::Line, LibBoard::Dot, LibBoard::Group, and LibBoard::ShapeList.
virtual void LibBoard::Shape::flushTikZ (std::ostream & stream, const TransformTikZ & transform) const pure virtual
Writes the TikZ code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implemented in LibBoard::Text, LibBoard::Arc, LibBoard::Circle, LibBoard::Ellipse, LibBoard::GouraudTriangle, LibBoard::QuadraticBezierCurve, LibBoard::Image, LibBoard::Rectangle, LibBoard::Polyline, LibBoard::Arrow, LibBoard::Line, LibBoard::Dot, LibBoard::Group, and LibBoard::ShapeList.
const std::string & LibBoard::Shape::name () const virtual
Returns the generic name of the shape (e.g., Circle, Rectangle, etc.)
Returns
object name
Reimplemented in LibBoard::Text, LibBoard::Arc, LibBoard::Circle, LibBoard::Ellipse, LibBoard::GouraudTriangle, LibBoard::QuadraticBezierCurve, LibBoard::Triangle, LibBoard::Image, LibBoard::Rectangle, LibBoard::Polyline, LibBoard::Arrow, LibBoard::Line, LibBoard::Dot, LibBoard::Group, and LibBoard::ShapeList.
Definition at line 103 of file Shapes.cpp.
References _name.
 {
     return _name;
 }
Shape & LibBoard::Shape::operator++ () inline
Increment the depth of the shape. (Push the shape toward the background.)
Returns
a shape
Definition at line 346 of file Board/Shapes.h.
References _depth.
 {
   ++_depth;
   return *this;
 }
Shape & LibBoard::Shape::operator-- () inline
Decrement the depth of the shape. (Pull the shape toward the foreground.)
Returns
a shape
Definition at line 353 of file Board/Shapes.h.
References _depth.
 {
   --_depth;
   return *this;
 }
const DGtal::Color & LibBoard::Shape::penColor () const inline
Definition at line 367 of file Board/Shapes.h.
References _penColor.
 {
   return _penColor;
 }
std::string LibBoard::Shape::postscriptProperties () const protected
Return a string of the properties lineWidth, penColor, lineCap, and lineJoin as Postscript commands.
Returns
A string of the Postscript commands.
Definition at line 140 of file Shapes.cpp.
References _lineCap, _lineJoin, _lineStyle, and _lineWidth.
Referenced by LibBoard::Dot::flushPostscript(), LibBoard::Line::flushPostscript(), LibBoard::Arrow::flushPostscript(), LibBoard::Polyline::flushPostscript(), LibBoard::QuadraticBezierCurve::flushPostscript(), and LibBoard::Ellipse::flushPostscript().
 {
     std::stringstream str;
     str << _lineWidth << " slw ";
     str << _lineCap << " slc ";
     str << _lineJoin << " slj";
     str << xFigDashStylesPS[ _lineStyle ];
     return str.str();
 }
virtual Shape& LibBoard::Shape::rotate (double angle, const Point & center) pure virtual
Rotate the shape around a given center of rotation.
Parameters
angle The rotation angle in radian.
center The center of rotation.
Returns
A reference to the shape itself.
Implemented in LibBoard::Text, LibBoard::Circle, LibBoard::Ellipse, LibBoard::GouraudTriangle, LibBoard::Polyline, LibBoard::Line, LibBoard::Dot, LibBoard::Group, LibBoard::Board, and LibBoard::ShapeList.
Referenced by LibBoard::Board::addDuplicates(), and rotateDeg().
virtual Shape& LibBoard::Shape::rotate (double angle) pure virtual
Rotate the shape around its center.
Parameters
angle The rotation angle in radian.
Returns
A reference to the shape itself.
Implemented in LibBoard::Text, LibBoard::Circle, LibBoard::Ellipse, LibBoard::GouraudTriangle, LibBoard::Polyline, LibBoard::Line, LibBoard::Dot, LibBoard::Group, LibBoard::Board, and LibBoard::ShapeList.
Shape & LibBoard::Shape::rotateDeg (double angle, const Point & center) inline
Rotate the shape around a given center of rotation.
Parameters
angle The rotation angle in degree.
center The center of rotation.
Returns
A reference to the shape itself.
Definition at line 379 of file Board/Shapes.h.
References rotate().
 {
   return rotate( angle * ( M_PI / 180.0 ), aCenter );
 }
Shape & LibBoard::Shape::rotateDeg (double angle) inline
Rotate the shape around its center.
Parameters
angle The rotation angle in degree.
Returns
A reference to the shape itself.
Definition at line 385 of file Board/Shapes.h.
References center(), and rotate().
 {
   return rotate( angle * ( M_PI / 180.0 ), center() );
 }
virtual Shape& LibBoard::Shape::scale (double sx, double sy) pure virtual
Scale the shape along the x an y axis.
Parameters
sx The scale factor along the x axis.
sy The scale factor along the y axis.
Returns
The shape itself.
Implemented in LibBoard::Text, LibBoard::Circle, LibBoard::Ellipse, LibBoard::Polyline, LibBoard::Line, LibBoard::Dot, LibBoard::Group, LibBoard::Board, and LibBoard::ShapeList.
Referenced by LibBoard::Board::addDuplicates().
virtual Shape& LibBoard::Shape::scale (double s) pure virtual
Scale the shape along both axis.
Parameters
s The scale factor along both axis.
Returns
The shape itself.
Implemented in LibBoard::Text, LibBoard::Circle, LibBoard::Ellipse, LibBoard::Polyline, LibBoard::Line, LibBoard::Dot, LibBoard::Group, LibBoard::Board, and LibBoard::ShapeList.
virtual void LibBoard::Shape::scaleAll (double s) pure virtual
Scales all the values (positions, dimensions, etc.) associated with the shape.
Parameters
s The scaling factor.
Implemented in LibBoard::Text, LibBoard::Circle, LibBoard::Ellipse, LibBoard::GouraudTriangle, LibBoard::Rectangle, LibBoard::Polyline, LibBoard::Line, LibBoard::Dot, and LibBoard::ShapeList.
Referenced by LibBoard::ShapeList::addShape(), and LibBoard::Board::State::unit().
void LibBoard::Shape::setCairoDashStyle (cairo_t * cr, LineStyle type) const protected
Set a cairo dash style.
Parameters
cr The cairo drawing context.
type LineStyle: SolidStyle, DashStyle, DotStyle, DashDotStyle, DashDotDotStyle, DashDotDotDotStyle.
Definition at line 153 of file Shapes.cpp.
References DashDotDotDotStyle, DashDotDotStyle, DashDotStyle, DashStyle, DotStyle, and SolidStyle.
Referenced by LibBoard::Dot::flushCairo(), LibBoard::Line::flushCairo(), LibBoard::Arrow::flushCairo(), LibBoard::Polyline::flushCairo(), LibBoard::Rectangle::flushCairo(), LibBoard::QuadraticBezierCurve::flushCairo(), LibBoard::Ellipse::flushCairo(), LibBoard::Circle::flushCairo(), and LibBoard::Arc::flushCairo().
 {
     switch (type)
     {
       case SolidStyle:
   cairo_set_dash (cr, cairoSolidStyle, ARRAY_SIZE(cairoSolidStyle), cairoSolidStyle_offset); break;
       case DashStyle:
   cairo_set_dash (cr, cairoDashStyle, ARRAY_SIZE(cairoDashStyle), cairoDashStyle_offset); break;
       case DotStyle:
   cairo_set_dash (cr, cairoDotStyle, ARRAY_SIZE(cairoDotStyle), cairoDotStyle_offset); break;
       case DashDotStyle:
   cairo_set_dash (cr, cairoDashDotStyle, ARRAY_SIZE(cairoDashDotStyle), cairoDashDotStyle_offset); break;
       case DashDotDotStyle:
   cairo_set_dash (cr, cairoDashDotDotStyle, ARRAY_SIZE(cairoDashDotDotStyle), cairoDashDotDotStyle_offset); break;
       case DashDotDotDotStyle:
   cairo_set_dash (cr, cairoDashDotDotDotStyle, ARRAY_SIZE(cairoDashDotDotDotStyle), cairoDashDotDotDotStyle_offset); break;
       default: // SolidStyle
   cairo_set_dash (cr, cairoSolidStyle, ARRAY_SIZE(cairoSolidStyle), cairoSolidStyle_offset);
     }
 }
void LibBoard::Shape::shiftDepth (int shift) virtual
Reimplemented in LibBoard::ShapeList.
Definition at line 200 of file Shapes.cpp.
References _depth.
 {
     _depth += shift;
 }
std::string LibBoard::Shape::svgProperties (const TransformSVG & transform) const protected
Return a string of the svg properties lineWidth, opacity, penColor, fillColor, lineCap, and lineJoin.
Returns
A string of the properties suitable for inclusion in an svg tag.
Definition at line 109 of file Shapes.cpp.
References _fillColor, _lineCap, _lineJoin, _lineStyle, _lineWidth, _penColor, LibBoard::TransformSVG::mapWidth(), DGtal::Color::None, SolidStyle, DGtal::Color::svg(), and DGtal::Color::svgAlpha().
Referenced by LibBoard::Dot::flushSVG(), LibBoard::Line::flushSVG(), LibBoard::Polyline::flushSVG(), LibBoard::Rectangle::flushSVG(), LibBoard::QuadraticBezierCurve::flushSVG(), LibBoard::Ellipse::flushSVG(), LibBoard::Circle::flushSVG(), and LibBoard::Arc::flushSVG().
 {
     static const char * capStrings[3] = { "butt", "round", "square" };
     static const char * joinStrings[3] = { "miter", "round", "bevel" };
     std::stringstream str;
     if ( _penColor != DGtal::Color::None ) {
         str << " fill=\"" << _fillColor.svg() << '"'
         << " stroke=\"" << _penColor.svg() << '"'
         << " stroke-width=\"" << transform.mapWidth( _lineWidth ) << "mm\""
         << " style=\"stroke-linecap:" << capStrings[ _lineCap ]
         << ";stroke-linejoin:" << joinStrings[ _lineJoin ];
         if ( _lineStyle != SolidStyle )
             str << ";" << xFigDashStylesSVG[ _lineStyle ];
         str << '"'
         << _fillColor.svgAlpha( " fill" )
         << _penColor.svgAlpha( " stroke" );
     } else  {
         str << " fill=\"" << _fillColor.svg() << '"'
 //   << " stroke=\"" << _fillColor.svg() << '"'
 //   << " stroke-width=\"0.5px\""
         << " stroke=\"none\""
         << " stroke-width=\"0\""
         << " style=\"stroke-linecap:round;stroke-linejoin:round;"
         << '"'
         << _fillColor.svgAlpha( " fill" )
         << _fillColor.svgAlpha( " stroke" );
     }
     return str.str();
 }
std::string LibBoard::Shape::tikzProperties (const TransformTikZ & transform) const protected
Return a string of the properties lineWidth, penColor, lineCap, and lineJoin as TikZ commands.
Returns
A string of the TikZ commands.
Definition at line 177 of file Shapes.cpp.
References _fillColor, _lineCap, _lineJoin, _lineStyle, _lineWidth, _penColor, LibBoard::TransformSVG::mapWidth(), and DGtal::Color::tikz().
Referenced by LibBoard::Line::flushTikZ(), LibBoard::Arrow::flushTikZ(), LibBoard::Polyline::flushTikZ(), LibBoard::Rectangle::flushTikZ(), LibBoard::QuadraticBezierCurve::flushTikZ(), LibBoard::Ellipse::flushTikZ(), LibBoard::Circle::flushTikZ(), LibBoard::Arc::flushTikZ(), and LibBoard::Text::flushTikZ().
 {
     static const char * capStrings[3] = { "" /* initial value "butt" */, "line cap=round,", "line cap=rect," };
     static const char * joinStrings[3] = { "" /* initial value "miter" */, "line join=round", "line join=bevel" };
     std::stringstream str;
     str << "fill=" << _fillColor.tikz() << ',';
     str << "draw=" << _penColor.tikz() << ',';
     str << "line width=" << transform.mapWidth( _lineWidth ) << "mm,";
     str << xFigDashStylesTikZ[ _lineStyle ];
     str << capStrings[ _lineCap ];
     str << joinStrings[ _lineJoin ];
     return str.str();
 }
virtual Shape& LibBoard::Shape::translate (double dx, double dy) pure virtual
Translate the shape by a given offset.
Parameters
dx The x offset.
dy The y offset.
Returns
A reference to the shape itself.
Implemented in LibBoard::Text, LibBoard::Circle, LibBoard::Ellipse, LibBoard::Polyline, LibBoard::Line, LibBoard::Dot, LibBoard::Group, LibBoard::Board, and LibBoard::ShapeList.
Referenced by LibBoard::Board::addDuplicates().
Field Documentation
int LibBoard::Shape::_depth protected
The depth of the shape.
Definition at line 295 of file Board/Shapes.h.
Referenced by depth(), LibBoard::Dot::flushFIG(), LibBoard::Line::flushFIG(), LibBoard::Arrow::flushFIG(), LibBoard::Polyline::flushFIG(), LibBoard::Rectangle::flushFIG(), LibBoard::Image::flushFIG(), LibBoard::Ellipse::flushFIG(), LibBoard::Text::flushFIG(), LibBoard::GouraudTriangle::flushPostscript(), LibBoard::GouraudTriangle::flushSVG(), operator++(), operator--(), and shiftDepth().
DGtal::Color LibBoard::Shape::_fillColor protected
The color of the shape.
Definition at line 297 of file Board/Shapes.h.
Referenced by fillColor(), filled(), LibBoard::Arrow::flushCairo(), LibBoard::Polyline::flushCairo(), LibBoard::Rectangle::flushCairo(), LibBoard::QuadraticBezierCurve::flushCairo(), LibBoard::Ellipse::flushCairo(), LibBoard::Circle::flushCairo(), LibBoard::Arc::flushCairo(), LibBoard::Polyline::flushFIG(), LibBoard::Rectangle::flushFIG(), LibBoard::Ellipse::flushFIG(), LibBoard::Polyline::flushPostscript(), LibBoard::QuadraticBezierCurve::flushPostscript(), LibBoard::Ellipse::flushPostscript(), LibBoard::Arc::flushPostscript(), LibBoard::Arrow::flushSVG(), LibBoard::Text::flushSVG(), LibBoard::GouraudTriangle::GouraudTriangle(), svgProperties(), and tikzProperties().
LineCap LibBoard::Shape::_lineCap protected
The linecap attribute. (The way line terminates.)
Definition at line 300 of file Board/Shapes.h.
Referenced by LibBoard::Dot::flushCairo(), LibBoard::Line::flushCairo(), LibBoard::Arrow::flushCairo(), LibBoard::Polyline::flushCairo(), LibBoard::Rectangle::flushCairo(), LibBoard::QuadraticBezierCurve::flushCairo(), LibBoard::Ellipse::flushCairo(), LibBoard::Circle::flushCairo(), LibBoard::Arc::flushCairo(), LibBoard::Dot::flushFIG(), LibBoard::Line::flushFIG(), LibBoard::Arrow::flushFIG(), LibBoard::Polyline::flushFIG(), LibBoard::Rectangle::flushFIG(), postscriptProperties(), svgProperties(), and tikzProperties().
LineJoin LibBoard::Shape::_lineJoin protected
The linejoin attribute. (The shape of line junctions.)
Definition at line 301 of file Board/Shapes.h.
Referenced by LibBoard::Dot::flushCairo(), LibBoard::Line::flushCairo(), LibBoard::Arrow::flushCairo(), LibBoard::Polyline::flushCairo(), LibBoard::Rectangle::flushCairo(), LibBoard::QuadraticBezierCurve::flushCairo(), LibBoard::Ellipse::flushCairo(), LibBoard::Circle::flushCairo(), LibBoard::Arc::flushCairo(), LibBoard::Dot::flushFIG(), LibBoard::Line::flushFIG(), LibBoard::Arrow::flushFIG(), LibBoard::Polyline::flushFIG(), LibBoard::Rectangle::flushFIG(), postscriptProperties(), svgProperties(), and tikzProperties().
LineStyle LibBoard::Shape::_lineStyle protected
The line style (solid, dashed, etc.).
Definition at line 299 of file Board/Shapes.h.
Referenced by LibBoard::Dot::flushCairo(), LibBoard::Line::flushCairo(), LibBoard::Arrow::flushCairo(), LibBoard::Polyline::flushCairo(), LibBoard::Rectangle::flushCairo(), LibBoard::QuadraticBezierCurve::flushCairo(), LibBoard::Ellipse::flushCairo(), LibBoard::Circle::flushCairo(), LibBoard::Arc::flushCairo(), LibBoard::Line::flushFIG(), LibBoard::Arrow::flushFIG(), LibBoard::Polyline::flushFIG(), LibBoard::Rectangle::flushFIG(), LibBoard::Image::flushFIG(), LibBoard::Ellipse::flushFIG(), LibBoard::Arrow::flushSVG(), postscriptProperties(), svgProperties(), and tikzProperties().
double LibBoard::Shape::_lineWidth protected
The line thickness.
Definition at line 298 of file Board/Shapes.h.
Referenced by LibBoard::Dot::flushCairo(), LibBoard::Line::flushCairo(), LibBoard::Arrow::flushCairo(), LibBoard::Polyline::flushCairo(), LibBoard::Rectangle::flushCairo(), LibBoard::QuadraticBezierCurve::flushCairo(), LibBoard::Ellipse::flushCairo(), LibBoard::Circle::flushCairo(), LibBoard::Arc::flushCairo(), LibBoard::Dot::flushFIG(), LibBoard::Line::flushFIG(), LibBoard::Arrow::flushFIG(), LibBoard::Polyline::flushFIG(), LibBoard::Rectangle::flushFIG(), LibBoard::Image::flushFIG(), LibBoard::Ellipse::flushFIG(), LibBoard::Arrow::flushPostscript(), LibBoard::Arrow::flushSVG(), postscriptProperties(), svgProperties(), and tikzProperties().
const std::string LibBoard::Shape::_name static private
The generic name of the shape.
Definition at line 291 of file Board/Shapes.h.
Referenced by name().
DGtal::Color LibBoard::Shape::_penColor protected
The color of the shape.
Definition at line 296 of file Board/Shapes.h.
Referenced by LibBoard::Dot::flushCairo(), LibBoard::Line::flushCairo(), LibBoard::Arrow::flushCairo(), LibBoard::Polyline::flushCairo(), LibBoard::Rectangle::flushCairo(), LibBoard::QuadraticBezierCurve::flushCairo(), LibBoard::Ellipse::flushCairo(), LibBoard::Circle::flushCairo(), LibBoard::Arc::flushCairo(), LibBoard::Dot::flushFIG(), LibBoard::Line::flushFIG(), LibBoard::Arrow::flushFIG(), LibBoard::Polyline::flushFIG(), LibBoard::Rectangle::flushFIG(), LibBoard::Image::flushFIG(), LibBoard::Ellipse::flushFIG(), LibBoard::Text::flushFIG(), LibBoard::Dot::flushPostscript(), LibBoard::Line::flushPostscript(), LibBoard::Arrow::flushPostscript(), LibBoard::Polyline::flushPostscript(), LibBoard::QuadraticBezierCurve::flushPostscript(), LibBoard::Ellipse::flushPostscript(), LibBoard::Arc::flushPostscript(), LibBoard::Text::flushPostscript(), LibBoard::Arrow::flushSVG(), LibBoard::Text::flushSVG(), penColor(), svgProperties(), and tikzProperties().
The documentation for this struct was generated from the following files:
Board/Shapes.h
Shapes.cpp