DGtal: DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator Class Reference
DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator Class Reference
#include <ImageContainerByHashTree.h>
Public Member Functions
Iterator (Node **data, unsigned int position, unsigned int arraySize)
bool isAtEnd () const
Value & operator* ()
bool operator++ ()
bool operator== (const Iterator &it)
bool operator!= (const Iterator &it)
HashKey getKey () const
bool next ()
Protected Attributes
Node * myNode
unsigned int myCurrentCell
unsigned int myArraySize
Node ** myContainerData
Detailed Description
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t>
class DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator
Definition at line 494 of file ImageContainerByHashTree.h.
Constructor & Destructor Documentation
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::Iterator (Node ** data, unsigned int position, unsigned int arraySize) inline
Definition at line 497 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myArraySize, DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myContainerData, DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myCurrentCell, and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myNode.
       {
         myArraySize = arraySize;
         myContainerData = data;
         myNode = data[0];
         myCurrentCell = position;
         while ((!myNode) && (myCurrentCell < myArraySize))
           {
             myNode = myContainerData[++myCurrentCell];
           }
       }
Member Function Documentation
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> HashKey DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::getKey () const inline
Definition at line 534 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getKey(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myNode.
       {
         return myNode->getKey();
       }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> bool DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::isAtEnd () const inline
Definition at line 508 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myArraySize, and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myCurrentCell.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator!=(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator==().
       {
         return myCurrentCell >= myArraySize;
       }
template<typename Domain , typename Value , typename HashKey > bool DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::Iterator::next () inline
Definition at line 435 of file ImageContainerByHashTree.ih.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getNext(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myArraySize, DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myContainerData, DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myCurrentCell, and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myNode.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator++().
   {
     if ( myNode )
       {
         myNode = myNode->getNext();
         if ( myNode )
           {
             return true;
           }
         else
           {
             do
               {
                 myNode = myContainerData[++myCurrentCell];
                 if ( myCurrentCell >= myArraySize )
                   return false;
               }
             while ( !myNode );
             return true;
           }
       }
     return false;
   }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> bool DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator!= (const Iterator & it) inline
Definition at line 527 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::isAtEnd(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myNode.
       {
         if (isAtEnd() && it.isAtEnd())
           return false;
         else
           return (myNode != it.myNode);
       }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Value& DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator* () inline
Definition at line 512 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getObject(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myNode.
       {
         return myNode->getObject();
       }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> bool DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator++ () inline
Definition at line 516 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::next().
       {
         return next();
       }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> bool DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator== (const Iterator & it) inline
Definition at line 520 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::isAtEnd(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myNode.
       {
         if (isAtEnd() && it.isAtEnd())
           return true;
         else
           return (myNode == it.myNode);
       }
Field Documentation
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> unsigned int DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myArraySize protected
Definition at line 542 of file ImageContainerByHashTree.h.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::isAtEnd(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::Iterator(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::next().
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Node** DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myContainerData protected
Definition at line 543 of file ImageContainerByHashTree.h.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::Iterator(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::next().
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> unsigned int DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myCurrentCell protected
Definition at line 541 of file ImageContainerByHashTree.h.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::isAtEnd(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::Iterator(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::next().
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Node* DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myNode protected
Definition at line 540 of file ImageContainerByHashTree.h.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::getKey(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::Iterator(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::next(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator!=(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator*(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator==().
The documentation for this class was generated from the following files:
ImageContainerByHashTree.h
ImageContainerByHashTree.ih