DGtal: DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate > Class Template Reference
DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate > Class Template Reference
#include <LightImplicitDigitalSurface.h>
Data Structures
class Tracker
struct VertexMap
Public Types
typedef
LightImplicitDigitalSurface
< TKSpace, TPointPredicate > Self
typedef TKSpace KSpace
typedef KSpace::SCell Surfel
typedef KSpace::Size Size
typedef TPointPredicate PointPredicate
typedef SurfelAdjacency
< KSpace::dimension > Adjacency
typedef KSpace::Cell Cell
typedef KSpace::SCell SCell
typedef KSpace::CellSet CellSet
typedef KSpace::SCellSet SCellSet
typedef Surfel Vertex
typedef SCellSet VertexSet
typedef BreadthFirstVisitor< Self > SelfVisitor
typedef GraphVisitorRange
< SelfVisitor > SelfVisitorRange
typedef
SelfVisitorRange::ConstIterator SurfelConstIterator
typedef KSpace::Space Space
typedef KSpace::Point Point
typedef Tracker DigitalSurfaceTracker
Public Member Functions
BOOST_CONCEPT_ASSERT ((CPointPredicate< PointPredicate >))
~LightImplicitDigitalSurface ()
LightImplicitDigitalSurface (const LightImplicitDigitalSurface &other)
LightImplicitDigitalSurface (const KSpace &aKSpace, const PointPredicate &aPP, const Adjacency &adj, const Surfel &s)
const Adjacency & surfelAdjacency () const
Adjacency & surfelAdjacency ()
const PointPredicate & pointPredicate () const
const KSpace & space () const
bool isInside (const Surfel &s) const
SurfelConstIterator begin () const
SurfelConstIterator end () const
Size nbSurfels () const
bool empty () const
DigitalSurfaceTracker * newTracker (const Surfel &s) const
Connectedness connectedness () const
Size degree (const Vertex &v) const
template<typename OutputIterator >
void writeNeighbors (OutputIterator &it, const Vertex &v) const
template<typename OutputIterator , typename VertexPredicate >
void writeNeighbors (OutputIterator &it, const Vertex &v, const VertexPredicate &pred) const
Size bestCapacity () const
void selfDisplay (std::ostream &out) const
bool isValid () const
Private Member Functions
LightImplicitDigitalSurface & operator= (const LightImplicitDigitalSurface &other)
Private Attributes
const KSpace & myKSpace
const PointPredicate & myPointPredicate
Adjacency mySurfelAdjacency
Surfel mySurfel
Tracker myTracker
Detailed Description
template<typename TKSpace, typename TPointPredicate>
class DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >
Aim: A model of CDigitalSurfaceContainer which defines the digital surface as the boundary of an implicitly define shape. The whole boundary is not precomputed nor stored. You may use an iterator to visit it.
Description of template class 'LightImplicitDigitalSurface'
It is also a model of CUndirectedSimpleLocalGraph, so as to be able to visit itself with a BreadthFirstVisitor. The "Light" or lazyness is implemented this way.
Template Parameters
TKSpace a model of CCellularGridSpaceND: the type chosen for the cellular grid space.
TPointPredicate a model of CPointPredicate: this functor defines the inside of a shape on points where it is true.
Remarks
Being a CDigitalSurfaceContainer, it is a model of CConstSinglePassRange, but it is not a model of CConstBidirectionalRange. For instance, if you wish to do an algorithm like: for all vertex x, for all vertex y, compute something, then the following code will not work:
// This snippet does NOT work.
const SurfelConstIterator itb = mySurface.begin();
const SurfelConstIterator ite = mySurface.end();
for (SurfelConstIterator itX = itb; itX != ite; ++itX)
{
  for ( SurfelConstIterator itY = itb; itY != ite; ++itY )
  { // compute something with *itX and *itY. }
  // now itX == itY == ite !
  }
You may use this range only once ! This is because the iterators are only single pass. If you wish to visit twice the range, you must indeed creates two ranges by calling begin() twice (end() is not compulsory here, but advised).
// This snippet does ALWAYS work.
for (SurfelConstIterator itX = mySurface.begin(),
                          itXEnd = mySurface.end();
      itX != itXEnd; ++itX )
{
  for ( SurfelConstIterator itY = mySurface.begin(),
                            itYEnd = mySurface.end();
        itY != itYEnd; ++itY )
    { // compute something with *itX and *itY. }
}
Definition at line 114 of file LightImplicitDigitalSurface.h.
Member Typedef Documentation
template<typename TKSpace, typename TPointPredicate> typedef SurfelAdjacency<KSpace::dimension> DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Adjacency
Definition at line 213 of file LightImplicitDigitalSurface.h.
template<typename TKSpace, typename TPointPredicate> typedef KSpace::Cell DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Cell
Definition at line 214 of file LightImplicitDigitalSurface.h.
template<typename TKSpace, typename TPointPredicate> typedef KSpace::CellSet DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::CellSet
Definition at line 216 of file LightImplicitDigitalSurface.h.
template<typename TKSpace, typename TPointPredicate> typedef Tracker DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::DigitalSurfaceTracker
Definition at line 234 of file LightImplicitDigitalSurface.h.
template<typename TKSpace, typename TPointPredicate> typedef TKSpace DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::KSpace
Model of cellular grid space.
Definition at line 200 of file LightImplicitDigitalSurface.h.
template<typename TKSpace, typename TPointPredicate> typedef KSpace::Point DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Point
Definition at line 233 of file LightImplicitDigitalSurface.h.
template<typename TKSpace, typename TPointPredicate> typedef TPointPredicate DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::PointPredicate
Definition at line 206 of file LightImplicitDigitalSurface.h.
template<typename TKSpace, typename TPointPredicate> typedef KSpace::SCell DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::SCell
Definition at line 215 of file LightImplicitDigitalSurface.h.
template<typename TKSpace, typename TPointPredicate> typedef KSpace::SCellSet DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::SCellSet
Definition at line 217 of file LightImplicitDigitalSurface.h.
template<typename TKSpace, typename TPointPredicate> typedef LightImplicitDigitalSurface<TKSpace,TPointPredicate> DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Self
Definition at line 198 of file LightImplicitDigitalSurface.h.
template<typename TKSpace, typename TPointPredicate> typedef BreadthFirstVisitor< Self > DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::SelfVisitor
Definition at line 229 of file LightImplicitDigitalSurface.h.
template<typename TKSpace, typename TPointPredicate> typedef GraphVisitorRange< SelfVisitor > DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::SelfVisitorRange
Definition at line 230 of file LightImplicitDigitalSurface.h.
template<typename TKSpace, typename TPointPredicate> typedef KSpace::Size DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Size
Type for sizes (unsigned integral type).
Definition at line 204 of file LightImplicitDigitalSurface.h.
template<typename TKSpace, typename TPointPredicate> typedef KSpace::Space DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Space
Definition at line 232 of file LightImplicitDigitalSurface.h.
template<typename TKSpace, typename TPointPredicate> typedef KSpace::SCell DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Surfel
Type for surfels.
Definition at line 202 of file LightImplicitDigitalSurface.h.
template<typename TKSpace, typename TPointPredicate> typedef SelfVisitorRange::ConstIterator DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::SurfelConstIterator
Definition at line 231 of file LightImplicitDigitalSurface.h.
template<typename TKSpace, typename TPointPredicate> typedef Surfel DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Vertex
Definition at line 221 of file LightImplicitDigitalSurface.h.
template<typename TKSpace, typename TPointPredicate> typedef SCellSet DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::VertexSet
Definition at line 222 of file LightImplicitDigitalSurface.h.
Constructor & Destructor Documentation
template<typename TKSpace , typename TPointPredicate > DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::~LightImplicitDigitalSurface () inline
Destructor.
Definition at line 123 of file LightImplicitDigitalSurface.ih.
 {
 }
template<typename TKSpace , typename TPointPredicate > DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::LightImplicitDigitalSurface (const LightImplicitDigitalSurface< TKSpace, TPointPredicate > & other) inline
Copy constructor.
Parameters
other the object to clone.
Definition at line 130 of file LightImplicitDigitalSurface.ih.
   : myKSpace( other.myKSpace ),
     myPointPredicate( other.myPointPredicate ),
     mySurfelAdjacency( other.mySurfelAdjacency ),
     mySurfel( other.mySurfel ),
     myTracker( *this, other.mySurfel )
 {
 }
template<typename TKSpace , typename TPointPredicate > DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::LightImplicitDigitalSurface (const KSpace & aKSpace, const PointPredicate & aPP, const Adjacency & adj, const Surfel & s) inline
Constructor from digital set.
Parameters
aKSpace a cellular grid space (referenced).
aPP a point predicate defining implicitly the shape (referenced).
adj the surfel adjacency (for instance Adjacency(true) is interior to exterior adjacency).
s any surfel of aKSpace such that aPP is true in the interior and false in the exterior.
Definition at line 142 of file LightImplicitDigitalSurface.ih.
   : myKSpace( aKSpace ), myPointPredicate( aPP ), mySurfelAdjacency( adj ),
     mySurfel( s ), myTracker( *this, s )
 {
 }
Member Function Documentation
template<typename TKSpace , typename TPointPredicate > DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::SurfelConstIterator DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::begin () const inline
Returns
an iterator pointing on the first surfel of the digital surface (unspecified order).
Definition at line 213 of file LightImplicitDigitalSurface.ih.
References DGtal::GraphVisitorRange< TGraphVisitor >::begin(), and DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::mySurfel.
Referenced by DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::nbSurfels().
 {
   SelfVisitorRange range( new SelfVisitor( *this, mySurfel ) );
   return range.begin();
 }
template<typename TKSpace , typename TPointPredicate > DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Size DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::bestCapacity () const inline
Should return a reasonable estimation of the number of neighbors for all vertices. For instance a planar triangulation should return 6-8, a quad-mesh should return 4, digital surface is 2*(K::dimension-1).
Returns
2*(K::dimension-1)
Definition at line 335 of file LightImplicitDigitalSurface.ih.
 {
   return KSpace::dimension * 2 - 2;
 }
template<typename TKSpace, typename TPointPredicate> DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::BOOST_CONCEPT_ASSERT ((CPointPredicate< PointPredicate >))
Referenced by DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::writeNeighbors().
template<typename TKSpace , typename TPointPredicate > DGtal::Connectedness DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::connectedness () const inline
Returns
the connectedness of this surface. Either CONNECTED, DISCONNECTED, or UNKNOWN.
Definition at line 258 of file LightImplicitDigitalSurface.ih.
References DGtal::CONNECTED.
 {
   return CONNECTED;
 }
template<typename TKSpace , typename TPointPredicate > DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Size DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::degree (const Vertex & v) const inline
Parameters
v any vertex of this graph
Returns
the number of neighbors of this Vertex/Surfel.
Definition at line 269 of file LightImplicitDigitalSurface.ih.
References DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Tracker::adjacent(), DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Tracker::move(), DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::myTracker, and DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::space().
 {
   Size d = 0;
   Vertex s;
   myTracker.move( v );
   for ( typename KSpace::DirIterator q = space().sDirs( v );
         q != 0; ++q )
     {
       if ( myTracker.adjacent( s, *q, true ) )
         ++d;
       if ( myTracker.adjacent( s, *q, false ) )
         ++d;
     }
   return d;
 }
template<typename TKSpace , typename TPointPredicate > bool DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::empty () const inline
Returns
'true' is the surface has no surfels, 'false' otherwise. NB: O(1) operation.
Definition at line 241 of file LightImplicitDigitalSurface.ih.
 {
   return false;
 }
template<typename TKSpace , typename TPointPredicate > DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::SurfelConstIterator DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::end () const inline
Returns
an iterator after the last surfel of the digital surface (unspecified order).
Definition at line 222 of file LightImplicitDigitalSurface.ih.
Referenced by DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::nbSurfels().
 {
   return SurfelConstIterator();
 }
template<typename TKSpace , typename TPointPredicate > bool DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::isInside (const Surfel & s) const inline
Parameters
s any surfel of the space.
Returns
'true' if s belongs to this digital surface.
Definition at line 192 of file LightImplicitDigitalSurface.ih.
References DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::myKSpace, and DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::myPointPredicate.
Referenced by DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Tracker::move().
 {
   Dimension k = myKSpace.sOrthDir( s );
   // checks if the surfel is on the space boundary.
   if ( myKSpace.sIsMax( s, k ) || myKSpace.sIsMin( s, k ) )
     return false;
   // p1 must be in the set and p2 must not be in the set.
   SCell spel1 = myKSpace.sDirectIncident( s, k );
   Point p1 = myKSpace.sCoords( spel1 );
   if ( myPointPredicate( p1 ) )
     {
       SCell spel2 = myKSpace.sIndirectIncident( s, k );
       Point p2 = myKSpace.sCoords( spel2 );
       return ! myPointPredicate( p2 );
     }
   return false;
 }
template<typename TKSpace , typename TPointPredicate > bool DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 365 of file LightImplicitDigitalSurface.ih.
 {
   return true;
 }
template<typename TKSpace , typename TPointPredicate > DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Size DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::nbSurfels () const inline
Returns
the number of surfels of this digital surface. NB: O(N) computational complexity where N is the number of surfels.
Definition at line 230 of file LightImplicitDigitalSurface.ih.
References DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::begin(), and DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::end().
 {
   Size nb = 0;
   for ( SurfelConstIterator it = begin(), it_end = end(); it != it_end; ++it )
     ++nb;
   return nb;
 }
template<typename TKSpace , typename TPointPredicate > DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::DigitalSurfaceTracker * DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::newTracker (const Surfel & s) const inline
Parameters
s any surfel of the space.
Precondition
'isInside(s)'
Returns
a dyn. alloc. pointer on a tracker positionned at s.
Definition at line 250 of file LightImplicitDigitalSurface.ih.
 {
   return new Tracker( *this, s );
 }
template<typename TKSpace, typename TPointPredicate> LightImplicitDigitalSurface& DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::operator= (const LightImplicitDigitalSurface< TKSpace, TPointPredicate > & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
template<typename TKSpace , typename TPointPredicate > const DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::PointPredicate & DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::pointPredicate () const inline
accessor to point predicate.
Definition at line 172 of file LightImplicitDigitalSurface.ih.
References DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::myPointPredicate.
Referenced by DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Tracker::adjacent().
 {
   return myPointPredicate;
 }
template<typename TKSpace , typename TPointPredicate > void DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 353 of file LightImplicitDigitalSurface.ih.
 {
   out << "[LightImplicitDigitalSurface]";
 }
template<typename TKSpace , typename TPointPredicate > const DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::KSpace & DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::space () const inline
Returns
the cellular space in which lives the surface.
Definition at line 183 of file LightImplicitDigitalSurface.ih.
References DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::myKSpace.
Referenced by DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::degree(), DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Tracker::Tracker(), and DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::writeNeighbors().
 {
   return myKSpace;
 }
template<typename TKSpace , typename TPointPredicate > const DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Adjacency & DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::surfelAdjacency () const inline
accessor to surfel adjacency.
Definition at line 155 of file LightImplicitDigitalSurface.ih.
References DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::mySurfelAdjacency.
Referenced by DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Tracker::Tracker().
 {
   return mySurfelAdjacency;
 }
template<typename TKSpace , typename TPointPredicate > DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Adjacency & DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::surfelAdjacency () inline
mutator to surfel adjacency.
Definition at line 163 of file LightImplicitDigitalSurface.ih.
References DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::mySurfelAdjacency.
 {
   return mySurfelAdjacency;
 }
template<typename TKSpace , typename TPointPredicate > template<typename OutputIterator > void DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::writeNeighbors (OutputIterator & it, const Vertex & v) const inline
Writes the neighbors of [v] in the output iterator [it]. Neighbors are given in no specific order.
Template Parameters
OutputIterator the type for the output iterator (e.g. back_insert_iterator<std::vector<Vertex> >).
Parameters
[in,out] it any output iterator on Vertex (*it++ should be allowed), which specifies where neighbors are written.
[in] v any vertex of this graph
Definition at line 290 of file LightImplicitDigitalSurface.ih.
References DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Tracker::adjacent(), DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Tracker::move(), DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::myTracker, and DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::space().
 {
   Vertex s;
   myTracker.move( v );
   for ( typename KSpace::DirIterator q = space().sDirs( v );
         q != 0; ++q )
     {
       if ( myTracker.adjacent( s, *q, true ) )
         *it++ = s;
       if ( myTracker.adjacent( s, *q, false ) )
         *it++ = s;
     }
 }
template<typename TKSpace , typename TPointPredicate > template<typename OutputIterator , typename VertexPredicate > void DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::writeNeighbors (OutputIterator & it, const Vertex & v, const VertexPredicate & pred) const inline
Writes the neighbors of [v], verifying the predicate [pred] in the output iterator [it]. Neighbors are given in no specific order.
Template Parameters
OutputIterator the type for the output iterator (e.g. back_insert_iterator<std::vector<Vertex> >).
VertexPredicate any type of predicate taking a Vertex as input.
Parameters
[in,out] it any output iterator on Vertex (*it++ should be allowed), which specifies where neighbors are written.
[in] v any vertex of this graph
[in] pred the predicate for selecting neighbors.
Definition at line 310 of file LightImplicitDigitalSurface.ih.
References DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Tracker::adjacent(), DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::BOOST_CONCEPT_ASSERT(), DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::Tracker::move(), DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::myTracker, and DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::space().
 {
   BOOST_CONCEPT_ASSERT(( CVertexPredicate< VertexPredicate > ));
   Vertex s;
   myTracker.move( v );
   for ( typename KSpace::DirIterator q = space().sDirs( v );
         q != 0; ++q )
     {
       if ( myTracker.adjacent( s, *q, true ) )
         {
           if ( pred( s ) ) *it++ = s;
         }
       if ( myTracker.adjacent( s, *q, false ) )
         {
           if ( pred( s ) ) *it++ = s;
         }
     }
 }
Field Documentation
template<typename TKSpace, typename TPointPredicate> const KSpace& DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::myKSpace private
a reference to the cellular space.
Definition at line 391 of file LightImplicitDigitalSurface.h.
Referenced by DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::isInside(), and DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::space().
template<typename TKSpace, typename TPointPredicate> const PointPredicate& DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::myPointPredicate private
a reference to the point predicate defining the shape.
Definition at line 393 of file LightImplicitDigitalSurface.h.
Referenced by DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::isInside(), and DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::pointPredicate().
template<typename TKSpace, typename TPointPredicate> Surfel DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::mySurfel private
a surfel belonging to the surface.
Definition at line 397 of file LightImplicitDigitalSurface.h.
Referenced by DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::begin().
template<typename TKSpace, typename TPointPredicate> Adjacency DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::mySurfelAdjacency private
the surfel adjacency used to determine neighbors.
Definition at line 395 of file LightImplicitDigitalSurface.h.
Referenced by DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::surfelAdjacency().
template<typename TKSpace, typename TPointPredicate> Tracker DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::myTracker mutable private
Internal tracker for visiting surfels.
Definition at line 399 of file LightImplicitDigitalSurface.h.
Referenced by DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::degree(), and DGtal::LightImplicitDigitalSurface< TKSpace, TPointPredicate >::writeNeighbors().
The documentation for this class was generated from the following files:
LightImplicitDigitalSurface.h
LightImplicitDigitalSurface.ih