DGtal: DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 > Class Template Reference
DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 > Class Template Reference
#include <IntegralInvariantMeanCurvatureEstimator.h>
Public Types
typedef TKSpace KSpace
typedef Z3i::Domain Domain
typedef KSpace::Space::RealPoint RealPoint
typedef Z3i::DigitalSet DigitalSet
typedef KSpace::SCell Cell
typedef KSpace::SurfelSet SurfelSet
typedef SurfelSet::const_iterator ConstIteratorKernel
typedef double Quantity
typedef int Value
typedef TShapeFunctor ShapeCellFunctor
typedef ConstValueFunctor< Value > KernelCellFunctor
typedef
DigitalSurfaceConvolver
< ShapeCellFunctor,
KernelCellFunctor, KSpace,
ConstIteratorKernel > Convolver
typedef Convolver::PairIterators PairIterators
typedef Ball3D< Z3i::Space > KernelSupport
Public Member Functions
BOOST_CONCEPT_ASSERT ((CCellFunctor< ShapeCellFunctor >))
IntegralInvariantMeanCurvatureEstimator (const KSpace &space, const ShapeCellFunctor &f)
~IntegralInvariantMeanCurvatureEstimator ()
void init (const double _h, const double re)
template<typename ConstIteratorOnCells >
Quantity eval (const ConstIteratorOnCells &it)
template<typename ConstIteratorOnCells , typename OutputIterator >
void eval (const ConstIteratorOnCells &itb, const ConstIteratorOnCells &ite, OutputIterator &result)
const ConstIteratorKernel & beginKernel () const
const ConstIteratorKernel & endKernel () const
void selfDisplay (std::ostream &out) const
bool isValid () const
template<typename ConstIteratorOnCells >
DGtal::IntegralInvariantMeanCurvatureEstimator
< TKSpace, TShapeFunctor, 3 >
::Quantity eval (const ConstIteratorOnCells &it)
Private Member Functions
IntegralInvariantMeanCurvatureEstimator (const IntegralInvariantMeanCurvatureEstimator &other)
IntegralInvariantMeanCurvatureEstimator & operator= (const IntegralInvariantMeanCurvatureEstimator &other)
Private Attributes
std::vector< SurfelSet > kernels
std::vector< PairIterators > kernelsIterators
Cell myOrigin
const KernelCellFunctor myKernelFunctor
Convolver myConvolver
float h
float radius
Quantity dh3
Quantity d8_3r
Quantity d_4_PIr4
Detailed Description
template<typename TKSpace, typename TShapeFunctor>
class DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >
Specialization for dimension = 3
Definition at line 386 of file IntegralInvariantMeanCurvatureEstimator.h.
Member Typedef Documentation
template<typename TKSpace , typename TShapeFunctor > typedef KSpace::SCell DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::Cell
Definition at line 393 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef SurfelSet::const_iterator DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::ConstIteratorKernel
Definition at line 395 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef DigitalSurfaceConvolver<ShapeCellFunctor, KernelCellFunctor, KSpace, ConstIteratorKernel> DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::Convolver
Definition at line 402 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef Z3i::DigitalSet DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::DigitalSet
Definition at line 392 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef Z3i::Domain DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::Domain
Definition at line 390 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef ConstValueFunctor<Value> DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::KernelCellFunctor
Definition at line 401 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef Ball3D<Z3i::Space> DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::KernelSupport
Definition at line 405 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef TKSpace DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::KSpace
Definition at line 389 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef Convolver::PairIterators DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::PairIterators
Definition at line 403 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef double DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::Quantity
Definition at line 397 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef KSpace::Space::RealPoint DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::RealPoint
Definition at line 391 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef TShapeFunctor DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::ShapeCellFunctor
Definition at line 400 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef KSpace::SurfelSet DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::SurfelSet
Definition at line 394 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef int DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::Value
Definition at line 398 of file IntegralInvariantMeanCurvatureEstimator.h.
Constructor & Destructor Documentation
template<typename TKSpace , typename TShapeFunctor > DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::IntegralInvariantMeanCurvatureEstimator (const KSpace & space, const ShapeCellFunctor & f) inline
Constructor.
Parameters
space space in which the shape is defined.
f functor on cell of the shape.
Definition at line 60 of file IntegralInvariantMeanCurvatureEstimator.ih.
   : myKernelFunctor(NumberTraits<Quantity>::ONE),
     myConvolver(shapeFunctor, myKernelFunctor, space)
 {}
template<typename TKSpace , typename TShapeFunctor > DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::~IntegralInvariantMeanCurvatureEstimator () inline
Destructor.
Definition at line 422 of file IntegralInvariantMeanCurvatureEstimator.h.
   {}
template<typename TKSpace , typename TShapeFunctor > DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::IntegralInvariantMeanCurvatureEstimator (const IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 > & other) private
4/(PI*r^4)
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
Member Function Documentation
template<typename TKSpace , typename TShapeFunctor > const ConstIteratorKernel& DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::beginKernel () const
Returns
iterator of the begin spel of the kernel support
template<typename TKSpace , typename TShapeFunctor > DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::BOOST_CONCEPT_ASSERT ((CCellFunctor< ShapeCellFunctor >))
template<typename TKSpace , typename TShapeFunctor > const ConstIteratorKernel& DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::endKernel () const
Returns
iterator of the end spel of the kernel support
template<typename TKSpace , typename TShapeFunctor > template<typename ConstIteratorOnCells > DGtal::IntegralInvariantMeanCurvatureEstimator<TKSpace, TShapeFunctor, 3>::Quantity DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::eval (const ConstIteratorOnCells & it) inline
Definition at line 295 of file IntegralInvariantMeanCurvatureEstimator.ih.
 {
   Quantity measure = (Quantity)myConvolver.eval(it);
   measure *= dh3;
   return d8_3r - d_4_PIr4 * measure;
 }
template<typename TKSpace , typename TShapeFunctor > template<typename ConstIteratorOnCells > Quantity DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::eval (const ConstIteratorOnCells & it)
Compute the integral invariant mean curvature to cell *it of a shape.
Template Parameters
ConstIteratorOnCells iterator on a Cell
Parameters
it iterator of a cell (from a shape) we want compute the integral invariant curvature.
Returns
quantity of the result of Integral Invariant estimator at position *it
template<typename TKSpace , typename TShapeFunctor > template<typename ConstIteratorOnCells , typename OutputIterator > void DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::eval (const ConstIteratorOnCells & itb, const ConstIteratorOnCells & ite, OutputIterator & result) inline
Compute the integral invariant mean curvature from two cells (from *itb to *ite (exclude)) of a shape. Return the result on an OutputIterator (param).
Template Parameters
ConstIteratorOnCells iterator on a Cell
OutputIterator output iterator type
Parameters
ite iterator of the begin position on the shape where we compute the integral invariant curvature.
itb iterator of the end position (excluded) on the shape where we compute the integral invariant curvature.
result iterator of the result of the computation.
Definition at line 345 of file IntegralInvariantMeanCurvatureEstimator.ih.
 {
   std::vector< Quantity > quantities;
   back_insert_iterator< std::vector< double > > quantitiesIterator( quantities );
   myConvolver.eval ( itb, ite, quantitiesIterator );
   Quantity measure(0);
   unsigned int qsize = quantities.size();
   for ( unsigned int i = 0; i < qsize; ++i )
   {
     measure = quantities[ i ];
     measure *= dh3;
     *result = d8_3r - d_4_PIr4 * measure;
     ++result;
   }
 }
template<typename TKSpace , typename TShapeFunctor > void DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::init (const double _h, const double re) inline
Initialise the IntegralInvariantMeanCurvatureEstimator with a specific Euclidean kernel radius re, and grid step h.
Parameters
_h precision of the grid
re Euclidean radius of the kernel support
Full Kernel computation
It's a trit ({0,1,2}) encoded array, and base10(111) is 13
End of Full Kernel
Computation of masks
End of computation of masks
Definition at line 172 of file IntegralInvariantMeanCurvatureEstimator.ih.
References DGtal::GaussDigitizer< TSpace, TEuclideanShape >::attach(), DGtal::DigitalSetBySTLSet< TDomain >::begin(), DGtal::Shapes< TDomain >::digitalShaper(), DGtal::DigitalSetBySTLSet< TDomain >::end(), DGtal::Trace::error(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getDomain(), DGtal::Ball3D< TSpace >::getLowerBound(), DGtal::Ball3D< TSpace >::getUpperBound(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::init(), DGtal::HyperRectDomain< TSpace >::lowerBound(), M_PI, DGtal::trace, and DGtal::HyperRectDomain< TSpace >::upperBound().
 {
   h = _h;
   radius =  re;
   dh3 = h*h*h;
   d8_3r = 8.0 / (3.0 * radius);
   double r2 = radius * radius;
   d_4_PIr4 = 4.0 / ( M_PI * r2 * r2 );
   RealPoint pOrigin = RealPoint ( 0.0, 0.0, 0.0 );
   KernelSupport kernel( pOrigin, radius + 0.000123 );
   KSpace KSpaceKernel;
   kernels = std::vector< SurfelSet >( 27 );
   kernelsIterators = std::vector< PairIterators > ( 27 );
   typedef EuclideanShapesMinus< KernelSupport, KernelSupport > EuclideanShape;
   GaussDigitizer<Z3i::Space, KernelSupport> digKernel;
   digKernel.attach( kernel );
   digKernel.init( kernel.getLowerBound(), kernel.getUpperBound(), h );
   Domain domainKernel = digKernel.getDomain();
   DigitalSet setKernel( domainKernel );
   Shapes< Domain >::digitalShaper ( setKernel, digKernel );
   bool space_ok = KSpaceKernel.init( domainKernel.lowerBound() - Domain::Point( 1, 1, 1 ), domainKernel.upperBound() + Domain::Point( 1, 1, 1 ), true );
   if ( !space_ok )
   {
     trace.error() << "Error in the Khalimsky space construction." << std::endl;
     return;
   }
   for(typename DigitalSet::ConstIterator it = setKernel.begin(), itend = setKernel.end();
       it != itend;
       ++it)
   {
     kernels[ 13 ].insert( KSpaceKernel.sSpel( *it ));
   }
   kernelsIterators[ 13 ].first = kernels[ 13 ].begin();
   kernelsIterators[ 13 ].second = kernels[ 13 ].end();
   for (int z = -1; z <= 1; ++z )
   {
     for ( int y = -1; y <= 1; ++y )
     {
       for ( int x = -1; x <= 1; ++x )
       {
         RealPoint shiftPoint = pOrigin + RealPoint( x * h, y * h, z * h);
         KernelSupport kernelShifted( shiftPoint, radius );
         int offset = ( x + 1 ) + (( y + 1 ) * 3 ) + (( z + 1 ) * 9 );
         if ( offset == 13 ) // Full kernel
         {
           continue;
         }
         else
         {
           EuclideanShape current( kernel, kernelShifted );
           GaussDigitizer< Z3i::Space, EuclideanShape > digCurrentKernel;
           digCurrentKernel.attach( current );
           digCurrentKernel.init( kernel.getLowerBound(), kernel.getUpperBound(), h );
           DigitalSet setCurrentKernel( domainKernel );
           Shapes< Domain>::digitalShaper ( setCurrentKernel, digCurrentKernel );
           for( typename DigitalSet::ConstIterator it = setCurrentKernel.begin(), itend = setCurrentKernel.end();
                it != itend;
                ++it)
           {
             kernels[ offset ].insert( KSpaceKernel.sSpel( *it ));
           }
           kernelsIterators[ offset ].first = kernels[ offset ].begin();
           kernelsIterators[ offset ].second = kernels[ offset ].end();
         }
       }
     }
   }
   myOrigin = KSpaceKernel.sSpel( pOrigin );
   myConvolver.init ( kernelsIterators[ 13 ].first, kernelsIterators[ 13 ].second, myOrigin, kernelsIterators );
 }
template<typename TKSpace , typename TShapeFunctor > bool DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 418 of file IntegralInvariantMeanCurvatureEstimator.ih.
 {
   return true;
 }
template<typename TKSpace , typename TShapeFunctor > IntegralInvariantMeanCurvatureEstimator& DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::operator= (const IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 > & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
template<typename TKSpace , typename TShapeFunctor > void DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 389 of file IntegralInvariantMeanCurvatureEstimator.ih.
 {
   out << "[IntegralInvariantMeanCurvatureEstimator]";
 }
Field Documentation
template<typename TKSpace , typename TShapeFunctor > Quantity DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::d8_3r private
h*h*h
Definition at line 509 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > Quantity DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::d_4_PIr4 private
8/3r
Definition at line 510 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > Quantity DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::dh3 private
kernel's radius-dependant variable. Used to compute IntegralInvariant.
Definition at line 508 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > float DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::h private
precision of the grid
Definition at line 502 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > std::vector< SurfelSet > DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::kernels private
array of shifting masks. Size = 27 for each shiftings (0-adjacent and full kernel included)
Definition at line 488 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > std::vector< PairIterators > DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::kernelsIterators private
array of begin/end iterator of shifting masks.
Definition at line 490 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > Convolver DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::myConvolver private
convolver
Definition at line 499 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > const KernelCellFunctor DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::myKernelFunctor private
kernel functor
Definition at line 496 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > Cell DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::myOrigin private
origin spel of the kernel support.
Definition at line 493 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > float DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::radius private
Euclidean radius of the kernel.
Definition at line 505 of file IntegralInvariantMeanCurvatureEstimator.h.
The documentation for this class was generated from the following files:
IntegralInvariantMeanCurvatureEstimator.h
IntegralInvariantMeanCurvatureEstimator.ih