DGtal: DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 > Class Template Reference
DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 > Class Template Reference
#include <IntegralInvariantGaussianCurvatureEstimator.h>
Public Types
typedef TKSpace KSpace
typedef Z3i::Domain Domain
typedef KSpace::Space::RealPoint RealPoint
typedef Z3i::DigitalSet DigitalSet
typedef KSpace::SCell Cell
typedef KSpace::SurfelSet SurfelSet
typedef SurfelSet::const_iterator ConstIteratorKernel
typedef double Quantity
typedef int Value
typedef TShapeFunctor ShapeCellFunctor
typedef ConstValueFunctor< Value > KernelCellFunctor
typedef
DigitalSurfaceConvolver
< ShapeCellFunctor,
KernelCellFunctor, KSpace,
ConstIteratorKernel > Convolver
typedef Convolver::PairIterators PairIterators
typedef Convolver::CovarianceMatrix Matrix3x3
typedef EigenValues3D
< Quantity >::Vector3 Vector3
typedef CurvatureInformation
< Quantity, Matrix3x3, Vector3 > CurvInformation
typedef Ball3D< Z3i::Space > KernelSupport
Public Member Functions
BOOST_CONCEPT_ASSERT ((CCellFunctor< ShapeCellFunctor >))
IntegralInvariantGaussianCurvatureEstimator (const KSpace &space, const ShapeCellFunctor &f)
~IntegralInvariantGaussianCurvatureEstimator ()
void init (const double _h, const double re)
template<typename ConstIteratorOnCells >
Quantity eval (const ConstIteratorOnCells &it)
template<typename ConstIteratorOnCells >
CurvInformation evalComplete (const ConstIteratorOnCells &it)
template<typename ConstIteratorOnCells , typename OutputIterator >
void eval (const ConstIteratorOnCells &itb, const ConstIteratorOnCells &ite, OutputIterator &result)
template<typename ConstIteratorOnCells , typename OutputStructIterator >
void evalComplete (const ConstIteratorOnCells &itb, const ConstIteratorOnCells &ite, OutputStructIterator &result)
const ConstIteratorKernel & beginKernel () const
const ConstIteratorKernel & endKernel () const
void selfDisplay (std::ostream &out) const
bool isValid () const
template<typename ConstIteratorOnCells >
DGtal::IntegralInvariantGaussianCurvatureEstimator
< TKSpace, TShapeFunctor, 3 >
::Quantity eval (const ConstIteratorOnCells &it)
template<typename ConstIteratorOnCells >
DGtal::IntegralInvariantGaussianCurvatureEstimator
< TKSpace, TShapeFunctor, 3 >
::CurvInformation evalComplete (const ConstIteratorOnCells &it)
Private Member Functions
IntegralInvariantGaussianCurvatureEstimator (const IntegralInvariantGaussianCurvatureEstimator &other)
IntegralInvariantGaussianCurvatureEstimator & operator= (const IntegralInvariantGaussianCurvatureEstimator &other)
Private Attributes
std::vector< SurfelSet > kernels
std::vector< PairIterators > kernelsIterators
Cell myOrigin
const KernelCellFunctor myKernelFunctor
Convolver myConvolver
float h
float radius
Quantity d6_PIr6
Quantity d8_5r
Quantity dh5
Detailed Description
template<typename TKSpace, typename TShapeFunctor>
class DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >
Specialization for dimension = 3
Definition at line 405 of file IntegralInvariantGaussianCurvatureEstimator.h.
Member Typedef Documentation
template<typename TKSpace , typename TShapeFunctor > typedef KSpace::SCell DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::Cell
Definition at line 412 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef SurfelSet::const_iterator DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::ConstIteratorKernel
Definition at line 414 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef DigitalSurfaceConvolver<ShapeCellFunctor, KernelCellFunctor, KSpace, ConstIteratorKernel> DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::Convolver
Definition at line 421 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef CurvatureInformation< Quantity, Matrix3x3, Vector3 > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::CurvInformation
Definition at line 426 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef Z3i::DigitalSet DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::DigitalSet
Definition at line 411 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef Z3i::Domain DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::Domain
Definition at line 409 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef ConstValueFunctor<Value> DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::KernelCellFunctor
Definition at line 420 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef Ball3D<Z3i::Space> DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::KernelSupport
Definition at line 428 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef TKSpace DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::KSpace
Definition at line 408 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef Convolver::CovarianceMatrix DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::Matrix3x3
Definition at line 424 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef Convolver::PairIterators DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::PairIterators
Definition at line 422 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef double DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::Quantity
Definition at line 416 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef KSpace::Space::RealPoint DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::RealPoint
Definition at line 410 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef TShapeFunctor DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::ShapeCellFunctor
Definition at line 419 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef KSpace::SurfelSet DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::SurfelSet
Definition at line 413 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef int DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::Value
Definition at line 417 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef EigenValues3D< Quantity >::Vector3 DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::Vector3
Definition at line 425 of file IntegralInvariantGaussianCurvatureEstimator.h.
Constructor & Destructor Documentation
template<typename TKSpace , typename TShapeFunctor > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::IntegralInvariantGaussianCurvatureEstimator (const KSpace & space, const ShapeCellFunctor & f) inline
Constructor.
Parameters
space space in which the shape is defined.
f functor on cell of the shape.
Definition at line 58 of file IntegralInvariantGaussianCurvatureEstimator.ih.
   : myKernelFunctor(NumberTraits<Quantity>::ONE),
     myConvolver(shapeFunctor, myKernelFunctor, space)
 {}
template<typename TKSpace , typename TShapeFunctor > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::~IntegralInvariantGaussianCurvatureEstimator () inline
Destructor.
Definition at line 445 of file IntegralInvariantGaussianCurvatureEstimator.h.
   {}
template<typename TKSpace , typename TShapeFunctor > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::IntegralInvariantGaussianCurvatureEstimator (const IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 > & other) private
h^5
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
Member Function Documentation
template<typename TKSpace , typename TShapeFunctor > const ConstIteratorKernel& DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::beginKernel () const
Returns
iterator of the begin spel of the kernel support
template<typename TKSpace , typename TShapeFunctor > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::BOOST_CONCEPT_ASSERT ((CCellFunctor< ShapeCellFunctor >))
template<typename TKSpace , typename TShapeFunctor > const ConstIteratorKernel& DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::endKernel () const
Returns
iterator of the end spel of the kernel support
template<typename TKSpace , typename TShapeFunctor > template<typename ConstIteratorOnCells > DGtal::IntegralInvariantGaussianCurvatureEstimator<TKSpace, TShapeFunctor, 3>::Quantity DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::eval (const ConstIteratorOnCells & it) inline
Definition at line 295 of file IntegralInvariantGaussianCurvatureEstimator.ih.
References DGtal::EigenValues3D< TQuantity >::getEigenDecomposition(), and DGtal::SimpleMatrix< TComponent, TM, TN >::setComponent().
 {
   double k1,k2 = 0.0;
   Matrix3x3 covarianceMatrix = myConvolver.evalCovarianceMatrix( it );
   Matrix3x3 eigenVectors;
   Vector3 eigenValues;
   for ( DGtal::Dimension i = 0; i < 3; ++i )
   {
     for ( DGtal::Dimension j = 0; j < 3; ++j )
     {
       covarianceMatrix.setComponent ( i, j, covarianceMatrix( i, j ) * dh5 );
     }
   }
   EigenValues3D< Quantity >::getEigenDecomposition( covarianceMatrix, eigenVectors, eigenValues );
   ASSERT ( eigenValues[ 0 ] == eigenValues[ 0 ] ); // NaN
   ASSERT ( (eigenValues[ 0 ] <= eigenValues[ 2 ]) && (eigenValues[ 0 ] <= eigenValues[ 1 ]) && (eigenValues[ 1 ] <= eigenValues[ 2 ]) );
   k1 = d6_PIr6 * ( eigenValues[ 1 ] - ( 3.0 * eigenValues[ 2 ] )) + d8_5r;
   k2 = d6_PIr6 * ( eigenValues[ 2 ] - ( 3.0 * eigenValues[ 1 ] )) + d8_5r;
   return ( k1 * k2 );
 }
template<typename TKSpace , typename TShapeFunctor > template<typename ConstIteratorOnCells > Quantity DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::eval (const ConstIteratorOnCells & it)
Compute the integral invariant Gaussian curvature to cell *it of a shape.
Template Parameters
ConstIteratorOnCells iterator on a Cell
Parameters
it iterator of a cell (from a shape) we want compute the integral invariant curvature.
Returns
quantity of the result of Integral Invariant estimator at position *it
template<typename TKSpace , typename TShapeFunctor > template<typename ConstIteratorOnCells , typename OutputIterator > void DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::eval (const ConstIteratorOnCells & itb, const ConstIteratorOnCells & ite, OutputIterator & result) inline
Compute the integral invariant Gaussian curvature from two cells (from *itb to *ite (exclude)) of a shape. Return the result on an OutputIterator (param).
Template Parameters
ConstIteratorOnCells iterator on a Cell
OutputIterator iterator of a list of Quantity
Parameters
ite iterator of the begin position on the shape where we compute the integral invariant curvature.
itb iterator of the end position (excluded) on the shape where we compute the integral invariant curvature.
result iterator of results of the computation.
Definition at line 397 of file IntegralInvariantGaussianCurvatureEstimator.ih.
References DGtal::EigenValues3D< TQuantity >::getEigenDecomposition(), and DGtal::SimpleMatrix< TComponent, TM, TN >::setComponent().
 {
   Quantity k1,k2;
   k1 = k2 = Quantity(0);
   std::vector< Matrix3x3 > vCovarianceMatrix;
   back_insert_iterator< std::vector< Matrix3x3 > > coMatrixIterator( vCovarianceMatrix );
   myConvolver.evalCovarianceMatrix ( itb, ite, coMatrixIterator );
   Matrix3x3 currentMatrix;
   Matrix3x3 eigenVectors;
   Vector3 eigenValues;
   unsigned int cmsize = vCovarianceMatrix.size();
   for( unsigned int i = 0; i < cmsize; ++i )
   {
     currentMatrix = vCovarianceMatrix[ i ];
     for( DGtal::Dimension j = 0; j < 3; ++j )
     {
       for( DGtal::Dimension k = 0; k < 3; ++k )
       {
         currentMatrix.setComponent ( j, k, currentMatrix ( j, k ) * dh5 );
       }
     }
     EigenValues3D< Quantity >::getEigenDecomposition( currentMatrix, eigenVectors, eigenValues );
     ASSERT ( eigenValues[ 0 ] == eigenValues[ 0 ] ); // NaN
     ASSERT ( (eigenValues[ 0 ] <= eigenValues[ 2 ]) && (eigenValues[ 0 ] <= eigenValues[ 1 ]) && (eigenValues[ 1 ] <= eigenValues[ 2 ]) );
     k1 = d6_PIr6 * ( eigenValues[ 1 ] - ( 3.0 * eigenValues[ 2 ] )) + d8_5r;
     k2 = d6_PIr6 * ( eigenValues[ 2 ] - ( 3.0 * eigenValues[ 1 ] )) + d8_5r;
     *result = k1 * k2;
     *result =
     ++result;
   }
 }
template<typename TKSpace , typename TShapeFunctor > template<typename ConstIteratorOnCells > DGtal::IntegralInvariantGaussianCurvatureEstimator<TKSpace, TShapeFunctor, 3>::CurvInformation DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::evalComplete (const ConstIteratorOnCells & it) inline
Definition at line 329 of file IntegralInvariantGaussianCurvatureEstimator.ih.
References DGtal::EigenValues3D< TQuantity >::getEigenDecomposition(), and DGtal::SimpleMatrix< TComponent, TM, TN >::setComponent().
 {
     double k1,k2 = 0.0;
     Matrix3x3 covarianceMatrix = myConvolver.evalCovarianceMatrix( it );
     Matrix3x3 eigenVectors;
     Vector3 eigenValues;
     for ( DGtal::Dimension i = 0; i < 3; ++i )
     {
       for ( DGtal::Dimension j = 0; j < 3; ++j )
       {
         covarianceMatrix.setComponent ( i, j, covarianceMatrix( i, j ) * dh5 );
       }
     }
     EigenValues3D< Quantity >::getEigenDecomposition( covarianceMatrix, eigenVectors, eigenValues );
     ASSERT ( (eigenValues[ 0 ] <= eigenValues[ 2 ]) && (eigenValues[ 0 ] <= eigenValues[ 1 ]) && (eigenValues[ 1 ] <= eigenValues[ 2 ]) );
     k1 = d6_PIr6 * ( eigenValues[ 1 ] - ( 3.0 * eigenValues[ 2 ] )) + d8_5r;
     k2 = d6_PIr6 * ( eigenValues[ 2 ] - ( 3.0 * eigenValues[ 1 ] )) + d8_5r;
     return CurvInformation( Quantity( k1 * k2 ), eigenVectors, eigenValues );
 }
template<typename TKSpace , typename TShapeFunctor > template<typename ConstIteratorOnCells > CurvInformation DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::evalComplete (const ConstIteratorOnCells & it)
Compute the integral invariant Gaussian curvature to cell *it of a shape.
Template Parameters
ConstIteratorOnCells iterator on a Cell
Parameters
it iterator of a cell (from a shape) we want compute the integral invariant curvature.
Returns
a struct with Gaussian curvature value of Integral Invariant estimator at position *it, and eigenVectors and eigenValues resulting of the PCA (contening principals curvature information)
template<typename TKSpace , typename TShapeFunctor > template<typename ConstIteratorOnCells , typename OutputStructIterator > void DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::evalComplete (const ConstIteratorOnCells & itb, const ConstIteratorOnCells & ite, OutputStructIterator & result) inline
Compute the integral invariant Gaussian curvature from two cells (from *itb to *ite (exclude)) of a shape. Return the result on an OutputIterator (param).
Template Parameters
ConstIteratorOnCells iterator on a Cell
OutputStructIterator iterator of list of CurvInformation
Parameters
ite iterator of the begin position on the shape where we compute the integral invariant curvature.
itb iterator of the end position (excluded) on the shape where we compute the integral invariant curvature.
result iterator of a structs with Gaussian curvature value of Integral Invariant estimator, and eigenVectors and eigenValues resulting of the PCA (contening principals curvature information)
Definition at line 447 of file IntegralInvariantGaussianCurvatureEstimator.ih.
References DGtal::EigenValues3D< TQuantity >::getEigenDecomposition(), and DGtal::SimpleMatrix< TComponent, TM, TN >::setComponent().
 {
   Quantity k1,k2;
   k1 = k2 = Quantity(0);
   std::vector< Matrix3x3 > vCovarianceMatrix;
   back_insert_iterator< std::vector< Matrix3x3 > > coMatrixIterator( vCovarianceMatrix );
   myConvolver.evalCovarianceMatrix ( itb, ite, coMatrixIterator );
   Matrix3x3 currentMatrix;
   Matrix3x3 eigenVectors;
   Vector3 eigenValues;
   unsigned int cmsize = vCovarianceMatrix.size();
   for( unsigned int i = 0; i < cmsize; ++i )
   {
     currentMatrix = vCovarianceMatrix[ i ];
     for( DGtal::Dimension j = 0; j < 3; ++j )
     {
       for( DGtal::Dimension k = 0; k < 3; ++k )
       {
         currentMatrix.setComponent ( j, k, currentMatrix ( j, k ) * dh5 );
       }
     }
     EigenValues3D< Quantity >::getEigenDecomposition( currentMatrix, eigenVectors, eigenValues );
     ASSERT ( (eigenValues[ 0 ] <= eigenValues[ 2 ]) && (eigenValues[ 0 ] <= eigenValues[ 1 ]) && (eigenValues[ 1 ] <= eigenValues[ 2 ]) );
     k1 = d6_PIr6 * ( eigenValues[ 1 ] - ( 3.0 * eigenValues[ 2 ] )) + d8_5r;
     k2 = d6_PIr6 * ( eigenValues[ 2 ] - ( 3.0 * eigenValues[ 1 ] )) + d8_5r;
     *result = CurvInformation( Quantity( k1 * k2 ), eigenVectors, eigenValues );
     ++result;
   }
 }
template<typename TKSpace , typename TShapeFunctor > void DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::init (const double _h, const double re) inline
Initialise the IntegralInvariantGaussianCurvatureEstimator with a specific Euclidean kernel radius re, and grid step k.
Parameters
_h precision of the grid
re Euclidean radius of the kernel support
Bug:
known bug with radius of kernel. Small hack for the moment.
Full Kernel computation
It's a trit ({0,1,2}) encoded array, and base10(111) is 13
End of Full Kernel
Computation of masks
End of computation of masks
Definition at line 171 of file IntegralInvariantGaussianCurvatureEstimator.ih.
References DGtal::GaussDigitizer< TSpace, TEuclideanShape >::attach(), DGtal::DigitalSetBySTLSet< TDomain >::begin(), DGtal::Shapes< TDomain >::digitalShaper(), DGtal::DigitalSetBySTLSet< TDomain >::end(), DGtal::Trace::error(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getDomain(), DGtal::Ball3D< TSpace >::getLowerBound(), DGtal::Ball3D< TSpace >::getUpperBound(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::init(), DGtal::HyperRectDomain< TSpace >::lowerBound(), M_PI, DGtal::trace, and DGtal::HyperRectDomain< TSpace >::upperBound().
 {
   h = _h;
   radius = re;
   double r3 = radius * radius * radius;
   double r6 = r3 * r3;
   d6_PIr6 = 6.0 / ( M_PI * r6 );
   d8_5r = 8.0 / ( 5.0 * radius );
   double h2 = h * h;
   dh5 = h2 * h2 * h;
   RealPoint pOrigin = RealPoint ( 0.0, 0.0, 0.0 );
   KernelSupport kernel( pOrigin, radius + 0.000123 );
   KSpace KSpaceKernel;
   kernels = std::vector< SurfelSet >( 27 );
   kernelsIterators = std::vector< PairIterators > ( 27 );
   typedef EuclideanShapesMinus< KernelSupport, KernelSupport > EuclideanShape;
   GaussDigitizer<Z3i::Space, KernelSupport> digKernel;
   digKernel.attach( kernel );
   digKernel.init( kernel.getLowerBound() - Domain::Point( 1, 1, 1 ), kernel.getUpperBound() + Domain::Point( 1, 1, 1 ), h );
   Domain domainKernel = digKernel.getDomain();
   DigitalSet setKernel( domainKernel );
   Shapes< Domain >::digitalShaper ( setKernel, digKernel );
   bool space_ok = KSpaceKernel.init( domainKernel.lowerBound(), domainKernel.upperBound(), true );
   if ( !space_ok )
   {
     trace.error() << "Error in the Khalimsky space construction." << std::endl;
     return;
   }
   for(typename DigitalSet::ConstIterator it = setKernel.begin(), itend = setKernel.end();
       it != itend;
       ++it)
   {
     kernels[ 13 ].insert( KSpaceKernel.sSpel( *it ));
   }
   kernelsIterators[ 13 ].first = kernels[ 13 ].begin();
   kernelsIterators[ 13 ].second = kernels[ 13 ].end();
   for (int z = -1; z <= 1; ++z )
   {
     for ( int y = -1; y <= 1; ++y )
     {
       for ( int x = -1; x <= 1; ++x )
       {
         RealPoint shiftPoint = pOrigin + RealPoint( x * h, y * h, z * h);
         KernelSupport kernelShifted( shiftPoint, radius );
         int offset = ( x + 1 ) + (( y + 1 ) * 3 ) + (( z + 1 ) * 9 );
         if ( offset == 13 ) // Full kernel
         {
           continue;
         }
         else
         {
           EuclideanShape current( kernel, kernelShifted );
           GaussDigitizer< Z3i::Space, EuclideanShape > digCurrentKernel;
           digCurrentKernel.attach( current );
           digCurrentKernel.init( kernel.getLowerBound(), kernel.getUpperBound(), h );
           DigitalSet setCurrentKernel( domainKernel );
           Shapes< Domain>::digitalShaper ( setCurrentKernel, digCurrentKernel );
           for( typename DigitalSet::ConstIterator it = setCurrentKernel.begin(), itend = setCurrentKernel.end();
                it != itend;
                ++it)
           {
             kernels[ offset ].insert( KSpaceKernel.sSpel( *it ));
           }
           kernelsIterators[ offset ].first = kernels[ offset ].begin();
           kernelsIterators[ offset ].second = kernels[ offset ].end();
         }
       }
     }
   }
   myOrigin = KSpaceKernel.sSpel( pOrigin );
   myConvolver.init ( kernelsIterators[ 13 ].first, kernelsIterators[ 13 ].second, myOrigin, kernelsIterators );
 }
template<typename TKSpace , typename TShapeFunctor > bool DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 539 of file IntegralInvariantGaussianCurvatureEstimator.ih.
 {
   return true;
 }
template<typename TKSpace , typename TShapeFunctor > IntegralInvariantGaussianCurvatureEstimator& DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::operator= (const IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 > & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
template<typename TKSpace , typename TShapeFunctor > void DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 510 of file IntegralInvariantGaussianCurvatureEstimator.ih.
 {
   out << "[IntegralInvariantGaussianCurvatureEstimator]";
 }
Field Documentation
template<typename TKSpace , typename TShapeFunctor > Quantity DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::d6_PIr6 private
Definition at line 562 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > Quantity DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::d8_5r private
6/PI*r^6
Definition at line 563 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > Quantity DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::dh5 private
8/5r
Definition at line 564 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > float DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::h private
precision of the grid
Definition at line 557 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > std::vector< SurfelSet > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::kernels private
array of shifting masks. Size = 27 for each shiftings (0-adjacent and full kernel included)
Definition at line 543 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > std::vector< PairIterators > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::kernelsIterators private
array of begin/end iterator of shifting masks.
Definition at line 545 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > Convolver DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::myConvolver private
convolver
Definition at line 554 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > const KernelCellFunctor DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::myKernelFunctor private
kernel functor
Definition at line 551 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > Cell DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::myOrigin private
origin spel of the kernel support.
Definition at line 548 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > float DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::radius private
Euclidean radius of the kernel.
Definition at line 560 of file IntegralInvariantGaussianCurvatureEstimator.h.
The documentation for this class was generated from the following files:
IntegralInvariantGaussianCurvatureEstimator.h
IntegralInvariantGaussianCurvatureEstimator.ih