DGtal: DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension > Class Template Reference
DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension > Class Template Reference
#include <IntegralInvariantMeanCurvatureEstimator.h>
Public Types
typedef TKSpace KSpace
typedef Z3i::Domain Domain
typedef KSpace::Space::RealPoint RealPoint
typedef Z3i::DigitalSet DigitalSet
typedef KSpace::SCell Cell
typedef KSpace::SurfelSet SurfelSet
typedef SurfelSet::const_iterator ConstIteratorKernel
typedef double Quantity
typedef int Value
typedef TShapeFunctor ShapeCellFunctor
typedef ConstValueFunctor< Value > KernelCellFunctor
typedef
DigitalSurfaceConvolver
< ShapeCellFunctor,
KernelCellFunctor, KSpace,
ConstIteratorKernel > Convolver
typedef Convolver::PairIterators PairIterators
typedef Ball3D< Z3i::Space > KernelSupport
Public Member Functions
BOOST_CONCEPT_ASSERT ((CCellFunctor< ShapeCellFunctor >))
IntegralInvariantMeanCurvatureEstimator (const KSpace &space, const ShapeCellFunctor &f)
~IntegralInvariantMeanCurvatureEstimator ()
void init (const double _h, const double re)
template<typename ConstIteratorOnCells >
Quantity eval (const ConstIteratorOnCells &it)
template<typename ConstIteratorOnCells , typename OutputIterator >
void eval (const ConstIteratorOnCells &itb, const ConstIteratorOnCells &ite, OutputIterator &result)
const ConstIteratorKernel & beginKernel () const
const ConstIteratorKernel & endKernel () const
void selfDisplay (std::ostream &out) const
bool isValid () const
template<typename ConstIteratorOnCells >
DGtal::IntegralInvariantMeanCurvatureEstimator
< TKSpace, TShapeFunctor,
dimension >::Quantity eval (const ConstIteratorOnCells &it)
Private Member Functions
IntegralInvariantMeanCurvatureEstimator (const IntegralInvariantMeanCurvatureEstimator &other)
IntegralInvariantMeanCurvatureEstimator & operator= (const IntegralInvariantMeanCurvatureEstimator &other)
Private Attributes
std::vector< SurfelSet > kernels
std::vector< PairIterators > kernelsIterators
Cell myOrigin
const KernelCellFunctor myKernelFunctor
Convolver myConvolver
float h
float radius
Detailed Description
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension>
class DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >
Aim: This class implement a Integral Invariant mean curvature estimation.
Description of template class 'IntegralInvariantMeanCurvatureEstimator'
See Also
related article: Coeurjolly, D.; Lachaud, J.O; Levallois, J., (2013). Integral based Curvature Estimators in Digital Geometry. DGCI 2013. Retrieved from https://liris.cnrs.fr/publis/?id=5866
The algorithm we propose uses volume of a kernel (2D: Ball2D, 3D: Ball3D) to approximate mean curvature. To compute the volume, we convolve a kernel around the surface and counting the number of cells belonging the shape. Theorical multigrid convergence is proved, with a convergence speed of O(h^1/3) with hypothesis about the shape geometry and the convolution kernel radius. Experimental results showed a multigrid convergence.
Some optimization are available when we set a range of 0-adjacent surfels to the estimator.
Template Parameters
TKSpace space in which the shape is defined.
TShapeFunctor TFunctor a model of a functor for the shape (f(x)).
dimension dimension of the shape. Let default value to use the correct specialization.
See Also
exampleIntegralInvariantCurvature2D.cpp testIntegralInvariantMeanCurvature3D.cpp testIntegralInvariantCurvature2D.cpp
Definition at line 87 of file IntegralInvariantMeanCurvatureEstimator.h.
Member Typedef Documentation
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef KSpace::SCell DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::Cell
Definition at line 94 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef SurfelSet::const_iterator DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::ConstIteratorKernel
Definition at line 96 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef DigitalSurfaceConvolver<ShapeCellFunctor, KernelCellFunctor, KSpace, ConstIteratorKernel> DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::Convolver
Definition at line 103 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef Z3i::DigitalSet DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::DigitalSet
Definition at line 93 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef Z3i::Domain DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::Domain
Definition at line 91 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef ConstValueFunctor<Value> DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::KernelCellFunctor
Definition at line 102 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef Ball3D<Z3i::Space> DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::KernelSupport
Definition at line 106 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef TKSpace DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::KSpace
Definition at line 90 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef Convolver::PairIterators DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::PairIterators
Definition at line 104 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef double DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::Quantity
Definition at line 98 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef KSpace::Space::RealPoint DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::RealPoint
Definition at line 92 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef TShapeFunctor DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::ShapeCellFunctor
Definition at line 101 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef KSpace::SurfelSet DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::SurfelSet
Definition at line 95 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef int DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::Value
Definition at line 99 of file IntegralInvariantMeanCurvatureEstimator.h.
Constructor & Destructor Documentation
template<typename TKSpace , typename TShapeFunctor , DGtal::Dimension dimension> DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::IntegralInvariantMeanCurvatureEstimator (const KSpace & space, const ShapeCellFunctor & f) inline
Constructor.
Parameters
space space in which the shape is defined.
f functor on cell of the shape.
Definition at line 46 of file IntegralInvariantMeanCurvatureEstimator.ih.
   : myKernelFunctor(NumberTraits<Quantity>::ONE),
     myConvolver(shapeFunctor, myKernelFunctor, space)
 {}
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::~IntegralInvariantMeanCurvatureEstimator () inline
Destructor.
Definition at line 123 of file IntegralInvariantMeanCurvatureEstimator.h.
   {}
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::IntegralInvariantMeanCurvatureEstimator (const IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension > & other) private
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
Member Function Documentation
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> const ConstIteratorKernel& DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::beginKernel () const
Returns
iterator of the begin spel of the kernel support
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::BOOST_CONCEPT_ASSERT ((CCellFunctor< ShapeCellFunctor >))
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> const ConstIteratorKernel& DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::endKernel () const
Returns
iterator of the end spel of the kernel support
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> template<typename ConstIteratorOnCells > Quantity DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::eval (const ConstIteratorOnCells & it)
Compute the integral invariant mean curvature to cell *it of a shape.
Template Parameters
ConstIteratorOnCells iterator on a Cell
Parameters
it iterator of a cell (from a shape) we want compute the integral invariant curvature.
Returns
quantity of the result of Integral Invariant estimator at position *it
template<typename TKSpace , typename TShapeFunctor , DGtal::Dimension dimension> template<typename ConstIteratorOnCells , typename OutputIterator > void DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::eval (const ConstIteratorOnCells & itb, const ConstIteratorOnCells & ite, OutputIterator & result) inline
Compute the integral invariant mean curvature from two cells (from *itb to *ite (exclude)) of a shape. Return the result on an OutputIterator (param).
Template Parameters
ConstIteratorOnCells iterator on a Cell
OutputIterator Output iterator type
Parameters
ite iterator of the begin position on the shape where we compute the integral invariant curvature.
itb iterator of the end position (excluded) on the shape where we compute the integral invariant curvature.
result iterator of the result of the computation.
Definition at line 311 of file IntegralInvariantMeanCurvatureEstimator.ih.
References DGtal::Trace::error(), and DGtal::trace.
 {
   trace.error() << "IntegralInvariantMeanCurvatureEstimator@eval() : Not available yet.";
 }
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> template<typename ConstIteratorOnCells > DGtal::IntegralInvariantMeanCurvatureEstimator<TKSpace, TShapeFunctor, dimension>::Quantity DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::eval (const ConstIteratorOnCells & it) inline
Definition at line 271 of file IntegralInvariantMeanCurvatureEstimator.ih.
References DGtal::Trace::error(), and DGtal::trace.
 {
   Quantity measure;
   trace.error() << "Not available yet.";
   return measure;
 }
template<typename TKSpace , typename TShapeFunctor , DGtal::Dimension dimension> void DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::init (const double _h, const double re) inline
Initialise the IntegralInvariantMeanCurvatureEstimator with a specific Euclidean kernel radius re, and grid step h.
Parameters
_h precision of the grid
re Euclidean radius of the kernel support
Bug:
known bug with radius of kernel. Small hack for the moment.
Definition at line 73 of file IntegralInvariantMeanCurvatureEstimator.ih.
References DGtal::Trace::error(), and DGtal::trace.
 {
   trace.error() << "Not available yet.";
 }
template<typename TKSpace , typename TShapeFunctor , DGtal::Dimension dimension> bool DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 402 of file IntegralInvariantMeanCurvatureEstimator.ih.
 {
   return true;
 }
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> IntegralInvariantMeanCurvatureEstimator& DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::operator= (const IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension > & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
template<typename TKSpace , typename TShapeFunctor , DGtal::Dimension dimension> void DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 373 of file IntegralInvariantMeanCurvatureEstimator.ih.
 {
   out << "[IntegralInvariantMeanCurvatureEstimator]";
 }
Field Documentation
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> float DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::h private
precision of the grid
Definition at line 206 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> std::vector< SurfelSet > DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::kernels private
array of shifting masks.
Definition at line 192 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> std::vector< PairIterators > DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::kernelsIterators private
array of begin/end iterator of shifting masks.
Definition at line 194 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> Convolver DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::myConvolver private
convolver
Definition at line 203 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> const KernelCellFunctor DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::myKernelFunctor private
kernel functor
Definition at line 200 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> Cell DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::myOrigin private
origin spel of the kernel support
Definition at line 197 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> float DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::radius private
Euclidean radius of the kernel.
Definition at line 209 of file IntegralInvariantMeanCurvatureEstimator.h.
The documentation for this class was generated from the following files:
IntegralInvariantMeanCurvatureEstimator.h
IntegralInvariantMeanCurvatureEstimator.ih