DGtal: DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 > Class Template Reference
DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 > Class Template Reference
#include <IntegralInvariantMeanCurvatureEstimator.h>
Public Types
typedef TKSpace KSpace
typedef Z2i::Domain Domain
typedef KSpace::Space::RealPoint RealPoint
typedef Z2i::DigitalSet DigitalSet
typedef KSpace::SCell Cell
typedef KSpace::SurfelSet SurfelSet
typedef SurfelSet::const_iterator ConstIteratorKernel
typedef double Quantity
typedef int Value
typedef TShapeFunctor ShapeCellFunctor
typedef ConstValueFunctor< Value > KernelCellFunctor
typedef
DigitalSurfaceConvolver
< ShapeCellFunctor,
KernelCellFunctor, KSpace,
ConstIteratorKernel > Convolver
typedef Convolver::PairIterators PairIterators
typedef Ball2D< Z2i::Space > KernelSupport
Public Member Functions
BOOST_CONCEPT_ASSERT ((CCellFunctor< ShapeCellFunctor >))
IntegralInvariantMeanCurvatureEstimator (const KSpace &space, const ShapeCellFunctor &f)
~IntegralInvariantMeanCurvatureEstimator ()
void init (const double _h, const double re)
template<typename ConstIteratorOnCells >
Quantity eval (const ConstIteratorOnCells &it)
template<typename ConstIteratorOnCells , typename OutputIterator >
void eval (const ConstIteratorOnCells &itb, const ConstIteratorOnCells &ite, OutputIterator &result)
const ConstIteratorKernel & beginKernel () const
const ConstIteratorKernel & endKernel () const
void selfDisplay (std::ostream &out) const
bool isValid () const
template<typename ConstIteratorOnCells >
DGtal::IntegralInvariantMeanCurvatureEstimator
< TKSpace, TShapeFunctor, 2 >
::Quantity eval (const ConstIteratorOnCells &it)
Private Member Functions
IntegralInvariantMeanCurvatureEstimator (const IntegralInvariantMeanCurvatureEstimator &other)
IntegralInvariantMeanCurvatureEstimator & operator= (const IntegralInvariantMeanCurvatureEstimator &other)
Private Attributes
std::vector< SurfelSet > kernels
std::vector< PairIterators > kernelsIterators
Cell myOrigin
const KernelCellFunctor myKernelFunctor
Convolver myConvolver
float h
float radius
Quantity dh2
Quantity d3_r
Quantity dPI_2
Quantity d1_r2
Detailed Description
template<typename TKSpace, typename TShapeFunctor>
class DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >
Specialization for dimension = 2
Definition at line 234 of file IntegralInvariantMeanCurvatureEstimator.h.
Member Typedef Documentation
template<typename TKSpace , typename TShapeFunctor > typedef KSpace::SCell DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::Cell
Definition at line 241 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef SurfelSet::const_iterator DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::ConstIteratorKernel
Definition at line 243 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef DigitalSurfaceConvolver<ShapeCellFunctor, KernelCellFunctor, KSpace, ConstIteratorKernel> DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::Convolver
Definition at line 250 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef Z2i::DigitalSet DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::DigitalSet
Definition at line 240 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef Z2i::Domain DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::Domain
Definition at line 238 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef ConstValueFunctor<Value> DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::KernelCellFunctor
Definition at line 249 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef Ball2D<Z2i::Space> DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::KernelSupport
Definition at line 253 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef TKSpace DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::KSpace
Definition at line 237 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef Convolver::PairIterators DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::PairIterators
Definition at line 251 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef double DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::Quantity
Definition at line 245 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef KSpace::Space::RealPoint DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::RealPoint
Definition at line 239 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef TShapeFunctor DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::ShapeCellFunctor
Definition at line 248 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef KSpace::SurfelSet DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::SurfelSet
Definition at line 242 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef int DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::Value
Definition at line 246 of file IntegralInvariantMeanCurvatureEstimator.h.
Constructor & Destructor Documentation
template<typename TKSpace , typename TShapeFunctor > DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::IntegralInvariantMeanCurvatureEstimator (const KSpace & space, const ShapeCellFunctor & f) inline
Constructor.
Parameters
space space in which the shape is defined.
f functor on cell of the shape.
Definition at line 53 of file IntegralInvariantMeanCurvatureEstimator.ih.
   : myKernelFunctor(NumberTraits<Quantity>::ONE),
     myConvolver(shapeFunctor, myKernelFunctor, space)
 {}
template<typename TKSpace , typename TShapeFunctor > DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::~IntegralInvariantMeanCurvatureEstimator () inline
Destructor.
Definition at line 270 of file IntegralInvariantMeanCurvatureEstimator.h.
   {}
template<typename TKSpace , typename TShapeFunctor > DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::IntegralInvariantMeanCurvatureEstimator (const IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 > & other) private
1/r^2
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
Member Function Documentation
template<typename TKSpace , typename TShapeFunctor > const ConstIteratorKernel& DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::beginKernel () const
Returns
iterator of the begin spel of the kernel support
template<typename TKSpace , typename TShapeFunctor > DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::BOOST_CONCEPT_ASSERT ((CCellFunctor< ShapeCellFunctor >))
template<typename TKSpace , typename TShapeFunctor > const ConstIteratorKernel& DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::endKernel () const
Returns
iterator of the end spel of the kernel support
template<typename TKSpace , typename TShapeFunctor > template<typename ConstIteratorOnCells > DGtal::IntegralInvariantMeanCurvatureEstimator<TKSpace, TShapeFunctor, 2>::Quantity DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::eval (const ConstIteratorOnCells & it) inline
Definition at line 282 of file IntegralInvariantMeanCurvatureEstimator.ih.
 {
   Quantity measure = (Quantity)myConvolver.eval(it);
   measure *= dh2;
   return d3_r * ( dPI_2 - d1_r2 * measure );
 }
template<typename TKSpace , typename TShapeFunctor > template<typename ConstIteratorOnCells > Quantity DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::eval (const ConstIteratorOnCells & it)
Compute the integral invariant mean curvature to cell *it of a shape.
Template Parameters
ConstIteratorOnCells iterator on a Cell
Parameters
it iterator of a cell (from a shape) we want compute the integral invariant curvature.
Returns
quantity of the result of Integral Invariant estimator at position *it
template<typename TKSpace , typename TShapeFunctor > template<typename ConstIteratorOnCells , typename OutputIterator > void DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::eval (const ConstIteratorOnCells & itb, const ConstIteratorOnCells & ite, OutputIterator & result) inline
Compute the integral invariant mean curvature from two cells (from *itb to *ite (exclude)) of a shape. Return the result on an OutputIterator (param).
Template Parameters
ConstIteratorOnCells iterator on a Cell
OutputIterator output iterator type
Parameters
ite iterator of the begin position on the shape where we compute the integral invariant curvature.
itb iterator of the end position (excluded) on the shape where we compute the integral invariant curvature.
result iterator of the result of the computation.
Definition at line 322 of file IntegralInvariantMeanCurvatureEstimator.ih.
 {
   std::vector< Quantity > quantities;
   back_insert_iterator< std::vector< double > > quantitiesIterator( quantities );
   myConvolver.eval ( itb, ite, quantitiesIterator );
   Quantity measure(0);
   for ( unsigned int i = 0; i < quantities.size(); ++i )
   {
     measure = quantities[ i ];
     measure *= dh2;
     *result = d3_r * ( dPI_2 - d1_r2 * measure );
     ++result;
   }
 }
template<typename TKSpace , typename TShapeFunctor > void DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::init (const double _h, const double re) inline
Initialise the IntegralInvariantMeanCurvatureEstimator with a specific Euclidean kernel radius re, and grid step h.
Parameters
_h precision of the grid
re Euclidean radius of the kernel support
Bug:
known bug with radius of kernel. Small hack for the moment.
Full Kernel computation
It's a trit ({0,1,2}) encoded array, and base10(11) is 4
End of full kernel
Computation of shifting masks
End of computation of masks
Definition at line 81 of file IntegralInvariantMeanCurvatureEstimator.ih.
References DGtal::GaussDigitizer< TSpace, TEuclideanShape >::attach(), DGtal::DigitalSetBySTLSet< TDomain >::begin(), DGtal::Shapes< TDomain >::digitalShaper(), DGtal::DigitalSetBySTLSet< TDomain >::end(), DGtal::Trace::error(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getDomain(), DGtal::Ball2D< TSpace >::getLowerBound(), DGtal::Ball2D< TSpace >::getUpperBound(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::init(), DGtal::HyperRectDomain< TSpace >::lowerBound(), M_PI, DGtal::trace, and DGtal::HyperRectDomain< TSpace >::upperBound().
 {
   h = _h;
   radius = re;
   dh2 = h*h;
   d3_r = 3.0 / radius;
   dPI_2 = M_PI / 2.0;
   d1_r2 = 1.0 / ( radius * radius );
   RealPoint pOrigin = RealPoint ( 0.0, 0.0 );
   KernelSupport kernel( pOrigin, radius + 0.000123 );
   KSpace KSpaceKernel;
   kernels = std::vector< SurfelSet > ( 9 );
   kernelsIterators = std::vector< PairIterators > ( 9 );
   typedef EuclideanShapesMinus< KernelSupport, KernelSupport > EuclideanShape;
   GaussDigitizer<Z2i::Space, KernelSupport> digKernel;
   digKernel.attach( kernel );
   digKernel.init( kernel.getLowerBound() - Domain::Point( 1, 1 ), kernel.getUpperBound() + Domain::Point( 1, 1 ), h );
   Domain domainKernel = digKernel.getDomain();
   DigitalSet setKernel( domainKernel );
   Shapes< Domain >::digitalShaper ( setKernel, digKernel );
   bool space_ok = KSpaceKernel.init( domainKernel.lowerBound(), domainKernel.upperBound(), true );
   if ( !space_ok )
   {
     trace.error() << "Error in the Khalimsky space construction." << std::endl;
     return;
   }
   for(typename DigitalSet::ConstIterator it = setKernel.begin(), itend = setKernel.end();
       it != itend;
       ++it)
   {
     kernels[ 4 ].insert( KSpaceKernel.sSpel( *it ));
   }
   kernelsIterators[ 4 ].first = kernels[ 4 ].begin();
   kernelsIterators[ 4 ].second = kernels[ 4 ].end();
   for ( int y = -1; y <= 1; ++y )
   {
     for ( int x = -1; x <= 1; ++x )
     {
       RealPoint shiftPoint = pOrigin + RealPoint( x * h , y * h );
       KernelSupport kernelShifted( shiftPoint, radius );
       int offset = ( x + 1 ) + (( y + 1 ) * 3 );
       if ( offset == 4 ) // Full kernel, already done
       {
         continue;
       }
       else
       {
         EuclideanShape current( kernel, kernelShifted );
         GaussDigitizer<Z2i::Space, EuclideanShape > digCurrentKernel;
         digCurrentKernel.attach( current );
         digCurrentKernel.init( kernel.getLowerBound(), kernel.getUpperBound(), h );
         DigitalSet setCurrentKernel( domainKernel );
         Shapes< Domain >::digitalShaper ( setCurrentKernel, digCurrentKernel );
         for(typename DigitalSet::ConstIterator it = setCurrentKernel.begin(), itend = setCurrentKernel.end();
             it != itend;
             ++it)
         {
           kernels[ offset ].insert( KSpaceKernel.sSpel( *it ));
         }
         kernelsIterators[ offset ].first = kernels[ offset ].begin();
         kernelsIterators[ offset ].second = kernels[ offset ].end();
       }
     }
   }
   myOrigin = KSpaceKernel.sSpel( pOrigin );
   myConvolver.init ( kernelsIterators[ 4 ].first, kernelsIterators[ 4 ].second, myOrigin, kernelsIterators );
 }
template<typename TKSpace , typename TShapeFunctor > bool DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 410 of file IntegralInvariantMeanCurvatureEstimator.ih.
 {
   return true;
 }
template<typename TKSpace , typename TShapeFunctor > IntegralInvariantMeanCurvatureEstimator& DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::operator= (const IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 > & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
template<typename TKSpace , typename TShapeFunctor > void DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 381 of file IntegralInvariantMeanCurvatureEstimator.ih.
 {
   out << "[IntegralInvariantMeanCurvatureEstimator]";
 }
Field Documentation
template<typename TKSpace , typename TShapeFunctor > Quantity DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::d1_r2 private
PI/2.
Definition at line 362 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > Quantity DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::d3_r private
h*h
Definition at line 360 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > Quantity DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::dh2 private
kernel's radius-dependant variable. Used to compute IntegralInvariant.
Definition at line 359 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > Quantity DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::dPI_2 private
3/r
Definition at line 361 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > float DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::h private
precision of the grid
Definition at line 353 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > std::vector< SurfelSet > DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::kernels private
array of shifting masks. Size = 9 for each shiftings (0-adjacent and full kernel included)
Definition at line 339 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > std::vector< PairIterators > DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::kernelsIterators private
array of begin/end iterator of shifting masks.
Definition at line 341 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > Convolver DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::myConvolver private
convolver
Definition at line 350 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > const KernelCellFunctor DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::myKernelFunctor private
kernel functor
Definition at line 347 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > Cell DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::myOrigin private
origin spel of the kernel support.
Definition at line 344 of file IntegralInvariantMeanCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > float DGtal::IntegralInvariantMeanCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::radius private
Euclidean radius of the kernel.
Definition at line 356 of file IntegralInvariantMeanCurvatureEstimator.h.
The documentation for this class was generated from the following files:
IntegralInvariantMeanCurvatureEstimator.h
IntegralInvariantMeanCurvatureEstimator.ih