DGtal: DGtal::NumberTraits< T > Struct Template Reference
DGtal::NumberTraits< T > Struct Template Reference
#include <NumberTraits.h>
Public Types
typedef TagUnknown IsBounded
typedef TagUnknown IsUnsigned
typedef TagUnknown IsSigned
typedef TagUnknown IsIntegral
typedef TagFalse IsSpecialized
typedef T SignedVersion
typedef T UnsignedVersion
typedef T ReturnType
typedef boost::call_traits< T >
::param_type ParamType
Static Public Member Functions
static ReturnType zero ()
static ReturnType one ()
static ReturnType min ()
static ReturnType max ()
static unsigned int digits ()
static BoundEnum isBounded ()
static SignEnum isSigned ()
static DGtal::int64_t castToInt64_t (const T &aT)
static double castToDouble (const T &aT)
static bool even (ParamType aT)
static bool odd (ParamType aT)
Static Public Attributes
static const T ZERO = T(0)
static const T ONE = T(1)
Detailed Description
template<typename T>
struct DGtal::NumberTraits< T >
Aim: The traits class for all models of Cinteger.
Description of template class 'NumberTraits'
Since CInteger describes the concept Integer, this class is used by models of CIinteger to specialize some definitions related to Integer. For instance it defines whether a given Integer is signed or not and what is signed/unsigned version.
Examples:
arithmetic/approximation.cpp.
Definition at line 69 of file NumberTraits.h.
Member Typedef Documentation
template<typename T> typedef TagUnknown DGtal::NumberTraits< T >::IsBounded
Definition at line 72 of file NumberTraits.h.
template<typename T> typedef TagUnknown DGtal::NumberTraits< T >::IsIntegral
Definition at line 75 of file NumberTraits.h.
template<typename T> typedef TagUnknown DGtal::NumberTraits< T >::IsSigned
Definition at line 74 of file NumberTraits.h.
template<typename T> typedef TagFalse DGtal::NumberTraits< T >::IsSpecialized
Definition at line 76 of file NumberTraits.h.
template<typename T> typedef TagUnknown DGtal::NumberTraits< T >::IsUnsigned
Definition at line 73 of file NumberTraits.h.
template<typename T> typedef boost::call_traits<T>::param_type DGtal::NumberTraits< T >::ParamType
Definition at line 83 of file NumberTraits.h.
template<typename T> typedef T DGtal::NumberTraits< T >::ReturnType
Definition at line 79 of file NumberTraits.h.
template<typename T> typedef T DGtal::NumberTraits< T >::SignedVersion
Definition at line 77 of file NumberTraits.h.
template<typename T> typedef T DGtal::NumberTraits< T >::UnsignedVersion
Definition at line 78 of file NumberTraits.h.
Member Function Documentation
template<typename T> static double DGtal::NumberTraits< T >::castToDouble (const T & aT) inline static
Cast method to double (for I/O or board export uses only).
Definition at line 154 of file NumberTraits.h.
Referenced by DGtal::Display3DFactory::draw(), DGtal::Display2DFactory::draw(), DGtal::Display2DFactory::drawAsDigitalPoints(), DGtal::Display3DFactory::drawAsPoints(), DGtal::ImageLinearCellEmbedder< TKSpace, TImage, TEmbedder >::embedSCell(), DGtal::COBANaivePlane< TSpace, TInternalInteger >::getBounds(), DGtal::CircleFrom3Points< TPoint >::getCurvature(), DGtal::COBANaivePlane< TSpace, TInternalInteger >::getNormal(), DGtal::CircleFrom3Points< TPoint >::getParameters(), DGtal::Preimage2D< Shape >::getSeparatingStraightLine(), DGtal::Statistic< TQuantity >::mean(), DGtal::PointVector< dim, TEuclideanRing, TContainer >::norm(), DGtal::ImplicitBall< TSpace >::operator()(), DGtal::ImageLinearCellEmbedder< TKSpace, TImage, TEmbedder >::operator()(), DGtal::detail::NormalizedTangentVectorFromDSS::operator()(), DGtal::detail::NormalVectorFromDCA::operator()(), and DGtal::detail::DistanceFromDCA::operator()().
     {
       return static_cast<double>(aT);
     }
template<typename T> static DGtal::int64_t DGtal::NumberTraits< T >::castToInt64_t (const T & aT) inline static
Cast method to DGtal::int64_t (for I/O or board export uses only).
Examples:
arithmetic/approximation.cpp.
Definition at line 146 of file NumberTraits.h.
Referenced by DGtal::LighterSternBrocot< TInteger, TQuotient, TMap >::Node::child(), DGtal::Display3DFactory::draw(), DGtal::LightSternBrocot< TInteger, TQuotient, TMap >::Fraction::Fraction(), DGtal::LighterSternBrocot< TInteger, TQuotient, TMap >::Fraction::Fraction(), DGtal::SternBrocot< TInteger, TQuotient >::Fraction::getCFrac(), DGtal::LightSternBrocot< TInteger, TQuotient, TMap >::Fraction::getCFrac(), DGtal::LighterSternBrocot< TInteger, TQuotient, TMap >::Fraction::getCFrac(), DGtal::Pattern< TFraction >::getGreatestIncludedSubpattern(), and DGtal::Pattern< TFraction >::getSmallestCoveringSubpattern().
     {
       return static_cast<DGtal::int64_t>(aT);
     }
template<typename T > unsigned int DGtal::NumberTraits< T >::digits () inline static
Returns
the number of significant digits for this integer type, or 0 if unbounded or unknown.
Definition at line 104 of file NumberTraits.ih.
 {
     return 0;
 }
template<typename T> static bool DGtal::NumberTraits< T >::even (ParamType aT) inline static
Parameters
aT any number.
Returns
'true' iff the number is even.
Definition at line 162 of file NumberTraits.h.
Referenced by DGtal::LightSternBrocot< TInteger, TQuotient, TMap >::Node::even(), DGtal::LighterSternBrocot< TInteger, TQuotient, TMap >::Node::even(), DGtal::LightSternBrocot< TInteger, TQuotient, TMap >::Fraction::even(), and DGtal::LighterSternBrocot< TInteger, TQuotient, TMap >::Fraction::even().
     {
       return ( aT & ONE ) == ZERO;
     }
template<typename T > DGtal::BoundEnum DGtal::NumberTraits< T >::isBounded () inline static
Returns
BOUNDED, UNBOUNDED, or BOUND_UNKNOWN.
1 if bounded, 0, if not bounded, 2 if unknown.
Definition at line 115 of file NumberTraits.ih.
References DGtal::BOUND_UNKNOWN.
 {
     return BOUND_UNKNOWN;
 }
template<typename T > DGtal::SignEnum DGtal::NumberTraits< T >::isSigned () inline static
Returns
SIGNED, UNSIGNED or SIGN_UNKNOWN.
1 if unsigned, 0, if signed, 2 if unknown.
Definition at line 126 of file NumberTraits.ih.
References DGtal::SIGN_UNKNOWN.
 {
     return SIGN_UNKNOWN;
 }
template<typename T > DGtal::NumberTraits< T >::ReturnType DGtal::NumberTraits< T >::max () inline static
Returns
the maximum possible value for this type of integer or ZERO if not bounded or unknown.
Definition at line 92 of file NumberTraits.ih.
Referenced by DGtal::KhalimskySpaceND< dim, TInteger >::KhalimskySpaceND().
 {
     return ZERO;
 }
template<typename T > DGtal::NumberTraits< T >::ReturnType DGtal::NumberTraits< T >::min () inline static
Returns
the minimum possible value for this type of integer or ONE if not bounded or unknown.
Definition at line 80 of file NumberTraits.ih.
Referenced by DGtal::KhalimskySpaceND< dim, TInteger >::KhalimskySpaceND().
 {
     return ONE;
 }
template<typename T> static bool DGtal::NumberTraits< T >::odd (ParamType aT) inline static
Parameters
aT any number.
Returns
'true' iff the number is odd.
Definition at line 170 of file NumberTraits.h.
Referenced by DGtal::LightSternBrocot< TInteger, TQuotient, TMap >::Node::odd(), DGtal::LighterSternBrocot< TInteger, TQuotient, TMap >::Node::odd(), DGtal::LightSternBrocot< TInteger, TQuotient, TMap >::Fraction::odd(), DGtal::LighterSternBrocot< TInteger, TQuotient, TMap >::Fraction::odd(), and DGtal::LighterSternBrocot< TInteger, TQuotient, TMap >::Fraction::reduced().
     {
       return ( aT & ONE ) != ZERO;
     }
template<typename T > DGtal::NumberTraits< T >::ReturnType DGtal::NumberTraits< T >::one () inline static
Returns
the one of this integer.
Definition at line 64 of file NumberTraits.ih.
 {
 #if (defined(WIN32))
     return 1;
 #else
     return ONE;
 #endif
 }
template<typename T > DGtal::NumberTraits< T >::ReturnType DGtal::NumberTraits< T >::zero () inline static
Returns
the zero of this integer.
Definition at line 49 of file NumberTraits.ih.
 {
 #if (defined(WIN32))
     return 0;
 #else
     return ZERO;
 #endif
 }
Field Documentation
template<typename T> const T DGtal::NumberTraits< T >::ONE = T(1) static
Constant One.
Definition at line 102 of file NumberTraits.h.
Referenced by DGtal::NumberTraits< Integer >::even(), and DGtal::NumberTraits< Integer >::odd().
template<typename T> const T DGtal::NumberTraits< T >::ZERO = T(0) static
Constant Zero.
Definition at line 93 of file NumberTraits.h.
Referenced by DGtal::NumberTraits< Integer >::even(), and DGtal::NumberTraits< Integer >::odd().
The documentation for this struct was generated from the following files:
NumberTraits.h
NumberTraits.ih