DGtal: DGtal::CImplicitFunctionDiff1< T > Struct Template Reference
DGtal::CImplicitFunctionDiff1< T > Struct Template Reference
DGtal Concepts
#include <CImplicitFunctionDiff1.h>
Public Types
typedef T::RealPoint RealPoint
typedef T::RealVector RealVector
Public Types inherited from DGtal::CImplicitFunction< T >
typedef T::RealPoint RealPoint
typedef T::Value Value
Public Member Functions
BOOST_CONCEPT_USAGE (CImplicitFunctionDiff1)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::CImplicitFunction< T >
BOOST_CONCEPT_ASSERT ((boost::UnaryFunction< T, Value, RealPoint >))
Private Attributes
T myX
RealPoint myA
RealVector myB
Detailed Description
template<typename T>
struct DGtal::CImplicitFunctionDiff1< T >
Aim: Describes a 1-differentiable function of the form f(x), where x is some real point in the given space, and f(x) is some value.
Description of concept 'CImplicitFunctionDiff1'
Refinement of CImplicitFunction
Associated types :
RealPoint: the type for the domain
RealVector: the type for a vector in the domain
Value: the type for the range
Notation
X : A type that is a model of CImplicitFunctionDiff1
f : objet of type X
a : objet of type RealPoint
Definitions
Valid expressions and
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
gradient operator gradient(a) RealVector Evaluates the gradient of the function f at point a
Invariants
Models
ImplicitPolynomial3Shape
Notes
Template Parameters
T the type that should be a model of CImplicitFunctionDiff1.
Definition at line 91 of file CImplicitFunctionDiff1.h.
Member Typedef Documentation
template<typename T > typedef T::RealPoint DGtal::CImplicitFunctionDiff1< T >::RealPoint
Definition at line 96 of file CImplicitFunctionDiff1.h.
template<typename T > typedef T::RealVector DGtal::CImplicitFunctionDiff1< T >::RealVector
Definition at line 97 of file CImplicitFunctionDiff1.h.
Member Function Documentation
template<typename T > DGtal::CImplicitFunctionDiff1< T >::BOOST_CONCEPT_USAGE (CImplicitFunctionDiff1< T >) inline
Definition at line 99 of file CImplicitFunctionDiff1.h.
References DGtal::CImplicitFunctionDiff1< T >::checkConstConstraints().
     {
       // check const methods.
       checkConstConstraints();
     }
template<typename T > void DGtal::CImplicitFunctionDiff1< T >::checkConstConstraints () const inline
Definition at line 104 of file CImplicitFunctionDiff1.h.
References DGtal::CImplicitFunctionDiff1< T >::myA, DGtal::CImplicitFunctionDiff1< T >::myB, DGtal::CImplicitFunctionDiff1< T >::myX, and DGtal::ConceptUtils::sameType().
Referenced by DGtal::CImplicitFunctionDiff1< T >::BOOST_CONCEPT_USAGE().
     {
       // const method dummyConst should take parameter myA of type A and return
       // something of type B
       ConceptUtils::sameType( myB, myX.gradient( myA ) );
     }
Field Documentation
template<typename T > RealPoint DGtal::CImplicitFunctionDiff1< T >::myA private
Definition at line 113 of file CImplicitFunctionDiff1.h.
Referenced by DGtal::CImplicitFunctionDiff1< T >::checkConstConstraints().
template<typename T > RealVector DGtal::CImplicitFunctionDiff1< T >::myB private
Definition at line 114 of file CImplicitFunctionDiff1.h.
Referenced by DGtal::CImplicitFunctionDiff1< T >::checkConstConstraints().
template<typename T > T DGtal::CImplicitFunctionDiff1< T >::myX private
Definition at line 112 of file CImplicitFunctionDiff1.h.
Referenced by DGtal::CImplicitFunctionDiff1< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CImplicitFunctionDiff1.h