DGtal: DGtal::CMetric< T > Struct Template Reference
DGtal::CMetric< T > Struct Template Reference
DGtal Concepts
#include <CMetric.h>
Public Types
typedef T::Point Point
typedef T::Vector Vector
typedef T::Value Value
Public Types inherited from DGtal::CLocalPremetric< T >
typedef T::Space Space
typedef T::Space::Point Point
typedef T::Space::Vector Vector
typedef T::Value Value
Public Member Functions
BOOST_CONCEPT_USAGE (CMetric)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::CLocalPremetric< T >
BOOST_CONCEPT_ASSERT ((CSpace< Space >))
BOOST_CONCEPT_ASSERT ((CQuantity< Value >))
BOOST_CONCEPT_USAGE (CLocalPremetric)
void checkConstConstraints () const
Private Attributes
T myX
Point myPoint
Point myPoint2
Point myPoint3
Value myValue
DGtal::Closest myClosest
Detailed Description
template<typename T>
struct DGtal::CMetric< T >
Aim: defines the concept of metrics.
Description of concept 'CMetric'
In addition to CLocalPremetric requirements (non-negativity and coincidence axiom), CMetric models should implement a distance function on points satisfying the metric conditions:
d(x,y) == d(y,x) (symmetry)
d(x,y) <= d(x,z) + d(z,y) (triangle inequality)
For performance purposes, we ask the model to implement a closest() method to decide given two points which one is closer to a third one. This method can simply be implemented as a test "d(aOrigin,aP)<d(aOrigin,aQ)" (see below) but fast implementation can be expected without computing the distances.
Refinement of CLocalPremetric
Associated types :
Inherited from CLocalPremetric:
Point: type of points associated with the underlying metric space.
Vector: type of vectors associated with the underlying metric space.
Value: the value type of the metric (model of CQuantity)
Notation
X : A type that is a model of CMetric
x, y : object of type X
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
distance computation x(aPoint,anotherPoint) aPoint and anotherPoint of type Point a value of type Value compute the distance between two points -
closest point test closest(aOrigin, aP, aQ) aOrigin, aP,aQ of type aPoint a value of type Closest decide between aP and aQ which one is closer to the origin. This functions returns either DGtal::ClosestFIRST if aP is closer, DGtal::ClosestSECOND if aQ is closer and DGtal::ClosestBOTH if both are equidistant. -
Invariants
Models
ExactPredicateLpSeparableMetric, InexactPredicateLpSeparableMetric
Notes
Template Parameters
T the type that should be a model of CMetric.
Definition at line 102 of file CMetric.h.
Member Typedef Documentation
template<typename T > typedef T::Point DGtal::CMetric< T >::Point
Definition at line 106 of file CMetric.h.
template<typename T > typedef T::Value DGtal::CMetric< T >::Value
Definition at line 108 of file CMetric.h.
template<typename T > typedef T::Vector DGtal::CMetric< T >::Vector
Definition at line 107 of file CMetric.h.
Member Function Documentation
template<typename T > DGtal::CMetric< T >::BOOST_CONCEPT_USAGE (CMetric< T >) inline
Definition at line 110 of file CMetric.h.
References DGtal::CMetric< T >::checkConstConstraints().
   {
     checkConstConstraints();
   }
template<typename T > void DGtal::CMetric< T >::checkConstConstraints () const inline
Definition at line 115 of file CMetric.h.
References DGtal::CMetric< T >::myClosest, DGtal::CMetric< T >::myPoint, DGtal::CMetric< T >::myPoint2, DGtal::CMetric< T >::myPoint3, DGtal::CMetric< T >::myValue, DGtal::CMetric< T >::myX, and DGtal::ConceptUtils::sameType().
Referenced by DGtal::CMetric< T >::BOOST_CONCEPT_USAGE().
   {
     // const method dummyConst should take parameter myA of type A and return
     // something of type B
     ConceptUtils::sameType( myValue, myX.operator()( myPoint , myPoint2 ) );
     ConceptUtils::sameType( myClosest, myX.closest( myPoint , myPoint2,myPoint3 ) );
  }
Field Documentation
template<typename T > DGtal::Closest DGtal::CMetric< T >::myClosest private
Definition at line 127 of file CMetric.h.
Referenced by DGtal::CMetric< T >::checkConstConstraints().
template<typename T > Point DGtal::CMetric< T >::myPoint private
Definition at line 125 of file CMetric.h.
Referenced by DGtal::CMetric< T >::checkConstConstraints().
template<typename T > Point DGtal::CMetric< T >::myPoint2 private
Definition at line 125 of file CMetric.h.
Referenced by DGtal::CMetric< T >::checkConstConstraints().
template<typename T > Point DGtal::CMetric< T >::myPoint3 private
Definition at line 125 of file CMetric.h.
Referenced by DGtal::CMetric< T >::checkConstConstraints().
template<typename T > Value DGtal::CMetric< T >::myValue private
Definition at line 126 of file CMetric.h.
Referenced by DGtal::CMetric< T >::checkConstConstraints().
template<typename T > T DGtal::CMetric< T >::myX private
Definition at line 124 of file CMetric.h.
Referenced by DGtal::CMetric< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CMetric.h