DGtal: DGtal::DefaultDrawStyle_DigitalSetBySTLSet Struct Reference
DGtal::DefaultDrawStyle_DigitalSetBySTLSet Struct Reference
Public Member Functions
virtual void setStyle (Board2D &aBoard) const
Public Member Functions inherited from DGtal::DrawableWithBoard2D
virtual ~DrawableWithBoard2D ()
Detailed Description
Default style.
Definition at line 115 of file Style2DFactory.ih.
Member Function Documentation
virtual void DGtal::DefaultDrawStyle_DigitalSetBySTLSet::setStyle (Board2D &) const inline virtual
Operation to override. Does nothing by default.
Reimplemented from DGtal::DrawableWithBoard2D.
Definition at line 117 of file Style2DFactory.ih.
References LibBoard::Board::setFillColorRGBi(), LibBoard::Board::setLineStyle(), and LibBoard::Board::setPenColorRGBi().
     {
       aBoard.setLineStyle(Board2D::Shape::SolidStyle);
       aBoard.setFillColorRGBi(160,160,160);
       aBoard.setPenColorRGBi(80,80,80);
     }
The documentation for this struct was generated from the following file:
Style2DFactory.ih