DGtal: DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator Struct Reference
DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator Struct Reference
#include <CombinatorialDSS.h>
Public Types
typedef bidirectional_iterator_tag iterator_category
typedef Point value_type
typedef Index difference_type
typedef Point * pointer
typedef Point & reference
Public Member Functions
ConstPointIterator ()
ConstPointIterator (const CombinatorialDSS *dss, Index ind, Point pt)
~ConstPointIterator ()
bool operator== (const ConstPointIterator other) const
bool operator!= (const ConstPointIterator other) const
Index operator- (const ConstPointIterator other) const
ConstPointIterator & operator= (const ConstPointIterator &other)
Point operator* () const
ConstPointIterator & operator++ ()
ConstPointIterator operator++ (int)
ConstPointIterator & operator-- ()
ConstPointIterator operator-- (int)
void next ()
void prev ()
const CombinatorialDSS * getDSS () const
Index getIndex () const
Data Fields
const CombinatorialDSS * myDSS
Index i
Point p
Detailed Description
template<typename TConstIterator, typename TInteger>
struct DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator
Iterator on the points of the DSS
Definition at line 243 of file CombinatorialDSS.h.
Member Typedef Documentation
template<typename TConstIterator, typename TInteger> typedef Index DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::difference_type
Definition at line 248 of file CombinatorialDSS.h.
template<typename TConstIterator, typename TInteger> typedef bidirectional_iterator_tag DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::iterator_category
Definition at line 246 of file CombinatorialDSS.h.
template<typename TConstIterator, typename TInteger> typedef Point* DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::pointer
Definition at line 249 of file CombinatorialDSS.h.
template<typename TConstIterator, typename TInteger> typedef Point& DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::reference
Definition at line 250 of file CombinatorialDSS.h.
template<typename TConstIterator, typename TInteger> typedef Point DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::value_type
Definition at line 247 of file CombinatorialDSS.h.
Constructor & Destructor Documentation
template<typename TConstIterator, typename TInteger> DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::ConstPointIterator () inline
Default constructor, does nothing
Definition at line 259 of file CombinatorialDSS.h.
           {}
template<typename TConstIterator, typename TInteger> DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::ConstPointIterator (const CombinatorialDSS * dss, Index ind, Point pt) inline
Initialization constructor.
Parameters
Index of the first letter.
CombinatorialDSS on which the iterator is defined.
Starting point of the iterator.
Definition at line 268 of file CombinatorialDSS.h.
                                                                                   :
             myDSS(dss), i(ind), p(pt)
{}
template<typename TConstIterator, typename TInteger> DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::~ConstPointIterator () inline
Destructor. Does nothing.
Definition at line 275 of file CombinatorialDSS.h.
 {}
Member Function Documentation
template<typename TConstIterator, typename TInteger> const CombinatorialDSS* DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::getDSS () const inline
Definition at line 358 of file CombinatorialDSS.h.
References DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::myDSS.
Referenced by DGtal::CombinatorialDSS< TConstIterator, TInteger >::init().
             {
               return myDSS;
             }
template<typename TConstIterator, typename TInteger> Index DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::getIndex () const inline
Definition at line 365 of file CombinatorialDSS.h.
References DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::i.
Referenced by DGtal::CombinatorialDSS< TConstIterator, TInteger >::computeLeaningPoints(), DGtal::CombinatorialDSS< TConstIterator, TInteger >::getArithmeticalDescription(), and DGtal::CombinatorialDSS< TConstIterator, TInteger >::mainPatternVector().
             {
               return i;
             }
template<typename TConstIterator, typename TInteger> void DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::next () inline
Definition at line 343 of file CombinatorialDSS.h.
References DGtal::CombinatorialDSS< TConstIterator, TInteger >::getCode(), DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::i, DGtal::CombinatorialDSS< TConstIterator, TInteger >::myDisplacements, and DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::myDSS.
Referenced by DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator++().
             {
               p += myDSS->myDisplacements( myDSS->getCode( i ) );
               ++i;
             }
template<typename TConstIterator, typename TInteger> bool DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator!= (const ConstPointIterator other) const inline
Definition at line 284 of file CombinatorialDSS.h.
References DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::i.
             {
               return i != other.i;
             }
template<typename TConstIterator, typename TInteger> Point DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator* () const inline
Definition at line 306 of file CombinatorialDSS.h.
References DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::p.
             {
               return p;
             }
template<typename TConstIterator, typename TInteger> ConstPointIterator& DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator++ () inline
Definition at line 312 of file CombinatorialDSS.h.
References DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::next().
             {
               next();
               return *this;
             }
template<typename TConstIterator, typename TInteger> ConstPointIterator DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator++ (int) inline
Definition at line 319 of file CombinatorialDSS.h.
References DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::next().
             {
               ConstPointIterator it = *this;
               next();
               return it;
             }
template<typename TConstIterator, typename TInteger> Index DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator- (const ConstPointIterator other) const inline
Definition at line 289 of file CombinatorialDSS.h.
References DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::i.
             {
               return i - other.i;
             }
template<typename TConstIterator, typename TInteger> ConstPointIterator& DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator-- () inline
Definition at line 328 of file CombinatorialDSS.h.
References DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::prev().
             {
               prev();
               return *this;
             }
template<typename TConstIterator, typename TInteger> ConstPointIterator DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator-- (int) inline
Definition at line 335 of file CombinatorialDSS.h.
References DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::prev().
             {
               ConstPointIterator it = *this;
               prev();
               return it;
             }
template<typename TConstIterator, typename TInteger> ConstPointIterator& DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator= (const ConstPointIterator & other) inline
Copy operator
Definition at line 298 of file CombinatorialDSS.h.
References DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::i, DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::myDSS, and DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::p.
             {
               i = other.i;
               myDSS = other.myDSS;
               p = other.p;
               return *this;
             }
template<typename TConstIterator, typename TInteger> bool DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator== (const ConstPointIterator other) const inline
Comparaison operators.
Definition at line 280 of file CombinatorialDSS.h.
References DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::i.
             {
               return i == other.i;
             }
template<typename TConstIterator, typename TInteger> void DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::prev () inline
Definition at line 350 of file CombinatorialDSS.h.
References DGtal::CombinatorialDSS< TConstIterator, TInteger >::getCode(), DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::i, DGtal::CombinatorialDSS< TConstIterator, TInteger >::myDisplacements, and DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::myDSS.
Referenced by DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator--().
             {
               --i;
               p -= myDSS->myDisplacements( myDSS->getCode( i ) );
             }
Field Documentation
template<typename TConstIterator, typename TInteger> Index DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::i
Definition at line 253 of file CombinatorialDSS.h.
Referenced by DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::getIndex(), DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::next(), DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator!=(), DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator-(), DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator=(), DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator==(), and DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::prev().
template<typename TConstIterator, typename TInteger> const CombinatorialDSS* DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::myDSS
Definition at line 252 of file CombinatorialDSS.h.
Referenced by DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::getDSS(), DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::next(), DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator=(), and DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::prev().
template<typename TConstIterator, typename TInteger> Point DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::p
Definition at line 254 of file CombinatorialDSS.h.
Referenced by DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator*(), and DGtal::CombinatorialDSS< TConstIterator, TInteger >::ConstPointIterator::operator=().
The documentation for this struct was generated from the following file:
CombinatorialDSS.h