source 'https://rubygems.org'

gem 'execjs'
gem 'therubyracer'
gem 'github-pages'
gem 'rouge'
gem 'middleman-syntax'
gem 'jekyll', '3.0.2'
gem 'jekyll-paginate'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
