source 'https://rubygems.org'

gem "github-pages", '197', group: :jekyll_plugins

# enable tzinfo-data for local build
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
# gem 'jekyll-seo-tag'
# gem 'jekyll-feed'
# gem 'jekyll-redirect-from'
# gem 'jekyll-assets'
# gem 'jekyll-gist'
# gem 'jekyll-paginate-v2'
# gem 'jekyll-toc'
# gem 'jekyll-archives'
# gem 'jekyll-compose'
# gem 'jekyll-sass-converter'
# gem 'jekyll-sassify'
# gem 'jekyll-watch'
# gem 'jekyll-include-cache'
# gem 'jekyll-remote-theme'
# gem 'jekyll-avatar'
# gem 'jekyll-mentions'
# gem 'jekyll-optional-front-matter'
# gem 'jekyll-paginate-categories'
# gem 'jekyll-paginate-content'
# gem 'jekyll-paginate-tags'
# gem 'jekyll-paginate-v2'
# gem 'jekyll-paginate-v2'
