DGtal: myreverse_iterator< _Iterator > Class Template Reference
myreverse_iterator< _Iterator > Class Template Reference
#include <DGtal/kernel/domains/HyperRectDomain_Iterator.h>
Public Types
typedef _Iterator iterator_type
typedef std::iterator_traits< _Iterator >::difference_type difference_type
typedef std::iterator_traits< _Iterator >::reference reference
typedef std::iterator_traits< _Iterator >::pointer pointer
Public Member Functions
myreverse_iterator (iterator_type __x)
myreverse_iterator (const myreverse_iterator &__x)
iterator_type base () const
reference operator * () const
reference operator * ()
pointer operator-> () const
myreverse_iterator & operator++ ()
myreverse_iterator operator++ (int)
myreverse_iterator & operator-- ()
myreverse_iterator operator-- (int)
myreverse_iterator operator+ (difference_type __n) const
myreverse_iterator & operator+= (difference_type __n)
myreverse_iterator operator- (difference_type __n) const
myreverse_iterator & operator-= (difference_type __n)
reference operator[] (difference_type __n) const
Protected Attributes
_Iterator current
_Iterator prev
Detailed Description
template<typename _Iterator>
class myreverse_iterator< _Iterator >
Examples
doc-examples/range.cpp.
Definition at line 52 of file HyperRectDomain_Iterator.h.
Member Typedef Documentation
difference_type
template<typename _Iterator> typedef std::iterator_traits<_Iterator>::difference_type myreverse_iterator< _Iterator >::difference_type
Definition at line 66 of file HyperRectDomain_Iterator.h.
iterator_type
template<typename _Iterator> typedef _Iterator myreverse_iterator< _Iterator >::iterator_type
Definition at line 64 of file HyperRectDomain_Iterator.h.
pointer
template<typename _Iterator> typedef std::iterator_traits<_Iterator>::pointer myreverse_iterator< _Iterator >::pointer
Definition at line 68 of file HyperRectDomain_Iterator.h.
reference
template<typename _Iterator> typedef std::iterator_traits<_Iterator>::reference myreverse_iterator< _Iterator >::reference
Definition at line 67 of file HyperRectDomain_Iterator.h.
Constructor & Destructor Documentation
myreverse_iterator() [1/2]
template<typename _Iterator> myreverse_iterator< _Iterator >::myreverse_iterator (iterator_type __x) inline explicit
Definition at line 72 of file HyperRectDomain_Iterator.h.
                                             : current(__x),
       prev(current)
   { --prev; }
References myreverse_iterator< _Iterator >::prev.
Referenced by myreverse_iterator< _Iterator >::operator+(), and myreverse_iterator< _Iterator >::operator-().
myreverse_iterator() [2/2]
template<typename _Iterator> myreverse_iterator< _Iterator >::myreverse_iterator (const myreverse_iterator< _Iterator > & __x) inline
Definition at line 76 of file HyperRectDomain_Iterator.h.
     : current(__x.current), prev(__x.prev) { }
Member Function Documentation
base()
template<typename _Iterator> iterator_type myreverse_iterator< _Iterator >::base () const inline
Definition at line 79 of file HyperRectDomain_Iterator.h.
   { return current; }
References myreverse_iterator< _Iterator >::current.
operator *() [1/2]
template<typename _Iterator> reference myreverse_iterator< _Iterator >::operator * () const inline
Definition at line 82 of file HyperRectDomain_Iterator.h.
   { return *prev; }
References myreverse_iterator< _Iterator >::prev.
Referenced by myreverse_iterator< _Iterator >::operator->().
operator *() [2/2]
template<typename _Iterator> reference myreverse_iterator< _Iterator >::operator * () inline
Definition at line 85 of file HyperRectDomain_Iterator.h.
   { return *prev; }
References myreverse_iterator< _Iterator >::prev.
operator+()
template<typename _Iterator> myreverse_iterator myreverse_iterator< _Iterator >::operator+ (difference_type __n) const inline
Definition at line 116 of file HyperRectDomain_Iterator.h.
   { return myreverse_iterator(current - __n); }
References myreverse_iterator< _Iterator >::current, and myreverse_iterator< _Iterator >::myreverse_iterator().
operator++() [1/2]
template<typename _Iterator> myreverse_iterator& myreverse_iterator< _Iterator >::operator++ () inline
Definition at line 91 of file HyperRectDomain_Iterator.h.
   { --current; --prev;
     return *this;
   }
References myreverse_iterator< _Iterator >::current, and myreverse_iterator< _Iterator >::prev.
Referenced by myreverse_iterator< _Iterator >::operator++().
operator++() [2/2]
template<typename _Iterator> myreverse_iterator myreverse_iterator< _Iterator >::operator++ (int) inline
Definition at line 96 of file HyperRectDomain_Iterator.h.
   {
     myreverse_iterator __tmp = *this;
     operator++();
     return __tmp;
   }
References myreverse_iterator< _Iterator >::operator++().
operator+=()
template<typename _Iterator> myreverse_iterator& myreverse_iterator< _Iterator >::operator+= (difference_type __n) inline
Definition at line 119 of file HyperRectDomain_Iterator.h.
{
     current -= __n; prev = current; --prev;
     return *this;
   }
References myreverse_iterator< _Iterator >::current, and myreverse_iterator< _Iterator >::prev.
operator-()
template<typename _Iterator> myreverse_iterator myreverse_iterator< _Iterator >::operator- (difference_type __n) const inline
Definition at line 125 of file HyperRectDomain_Iterator.h.
   { return myreverse_iterator(current + __n); }
References myreverse_iterator< _Iterator >::current, and myreverse_iterator< _Iterator >::myreverse_iterator().
operator--() [1/2]
template<typename _Iterator> myreverse_iterator& myreverse_iterator< _Iterator >::operator-- () inline
Definition at line 103 of file HyperRectDomain_Iterator.h.
   {
     ++current; ++prev;
     return *this;
   }
References myreverse_iterator< _Iterator >::current, and myreverse_iterator< _Iterator >::prev.
Referenced by myreverse_iterator< _Iterator >::operator--().
operator--() [2/2]
template<typename _Iterator> myreverse_iterator myreverse_iterator< _Iterator >::operator-- (int) inline
Definition at line 109 of file HyperRectDomain_Iterator.h.
   {
     myreverse_iterator __tmp = *this;
     operator--();
     return __tmp;
   }
References myreverse_iterator< _Iterator >::operator--().
operator-=()
template<typename _Iterator> myreverse_iterator& myreverse_iterator< _Iterator >::operator-= (difference_type __n) inline
Definition at line 128 of file HyperRectDomain_Iterator.h.
{
     current += __n; prev = current; --prev;
     return *this;
   }
References myreverse_iterator< _Iterator >::current, and myreverse_iterator< _Iterator >::prev.
operator->()
template<typename _Iterator> pointer myreverse_iterator< _Iterator >::operator-> () const inline
Definition at line 88 of file HyperRectDomain_Iterator.h.
   { return &(operator*()); }
References myreverse_iterator< _Iterator >::operator *().
operator[]()
template<typename _Iterator> reference myreverse_iterator< _Iterator >::operator[] (difference_type __n) const inline
Definition at line 134 of file HyperRectDomain_Iterator.h.
   { return *(*this + __n); }
Field Documentation
current
template<typename _Iterator> _Iterator myreverse_iterator< _Iterator >::current protected
Definition at line 60 of file HyperRectDomain_Iterator.h.
Referenced by myreverse_iterator< _Iterator >::base(), myreverse_iterator< _Iterator >::operator+(), myreverse_iterator< _Iterator >::operator++(), myreverse_iterator< _Iterator >::operator+=(), myreverse_iterator< _Iterator >::operator-(), myreverse_iterator< _Iterator >::operator--(), and myreverse_iterator< _Iterator >::operator-=().
prev
template<typename _Iterator> _Iterator myreverse_iterator< _Iterator >::prev protected
Definition at line 61 of file HyperRectDomain_Iterator.h.
Referenced by myreverse_iterator< _Iterator >::myreverse_iterator(), myreverse_iterator< _Iterator >::operator *(), myreverse_iterator< _Iterator >::operator++(), myreverse_iterator< _Iterator >::operator+=(), myreverse_iterator< _Iterator >::operator--(), and myreverse_iterator< _Iterator >::operator-=().
The documentation for this class was generated from the following file:
HyperRectDomain_Iterator.h