DGtal: DGtal::ConceptUtils Class Reference
DGtal::ConceptUtils Class Reference
Aim: This utility class gathers several static methods useful for concept checks.
#include <ConceptUtils.h>
Static Public Member Functions
template<typename T >
static void sameType (const T &t1, const T &t2)
static void checkTrue (const TagTrue &tag)
static void checkFalse (const TagFalse &tag)
static void checkUnknown (const TagUnknown &tag)
Detailed Description
Aim: This utility class gathers several static methods useful for concept checks.
Description of class 'ConceptUtils'
This class, as well as its methods are not meant to be realized. They are just used to check concepts.
Definition at line 75 of file ConceptUtils.h.
Member Function Documentation
static void DGtal::ConceptUtils::checkFalse (const TagFalse & tag) [static]
static void DGtal::ConceptUtils::checkTrue (const TagTrue & tag) [static]
Referenced by DGtal::CUnsignedInteger< T >::BOOST_CONCEPT_USAGE(), DGtal::CSignedInteger< T >::BOOST_CONCEPT_USAGE(), and DGtal::CBoundedDomain< T >::BOOST_CONCEPT_USAGE().
static void DGtal::ConceptUtils::checkUnknown (const TagUnknown & tag) [static]
template<typename T > static void DGtal::ConceptUtils::sameType (const T & t1, const T & t2) [static]
Type deduction will fail unless the arguments have the same type.
Parameters:
t1 some object of type T.
t2 some object of type T.
Referenced by DGtal::CSpace< T >::BOOST_CONCEPT_USAGE(), DGtal::CSeparableMetric< T >::BOOST_CONCEPT_USAGE(), DGtal::CPointPredicate< T >::BOOST_CONCEPT_USAGE(), DGtal::CInteger< T >::BOOST_CONCEPT_USAGE(), DGtal::CImplicitShape< TShape >::BOOST_CONCEPT_USAGE(), DGtal::CDrawableWithDGtalQGLViewer< T >::BOOST_CONCEPT_USAGE(), DGtal::CDrawableWithDGtalBoard< T >::BOOST_CONCEPT_USAGE(), DGtal::CDomainAdjacency< T >::BOOST_CONCEPT_USAGE(), DGtal::CDomain< T >::BOOST_CONCEPT_USAGE(), DGtal::CColorMap< CMap >::BOOST_CONCEPT_USAGE(), and DGtal::CAdjacency< T >::BOOST_CONCEPT_USAGE().
The documentation for this class was generated from the following file:
ConceptUtils.h