Board: LibBoard::Color Class Reference
LibBoard::Color Class Reference
Structure representing an RGB triple.
#include <Color.h>
Public Member Functions
Color (const unsigned int rgb, unsigned char alpha=255)
Color (unsigned char redValue, unsigned char greenValue, unsigned char blueValue, unsigned char alphaValue=255)
Color (unsigned char grayValue, unsigned char alphaValue=255)
Color (const bool validColor=true)
void red (unsigned char red)
void green (unsigned char green)
void blue (unsigned char blue)
void alpha (unsigned char alpha)
unsigned char red () const
unsigned char green () const
unsigned char blue () const
unsigned char alpha () const
Color & setRGBi (const unsigned char red, const unsigned char green, const unsigned char blue, const unsigned char alpha=255)
Color & setRGBf (float red, float green, float blue, float alpha=1.0)
bool operator== (const Color &other) const
bool operator!= (const Color &other) const
bool operator< (const Color &other) const
void flushPostscript (std::ostream &) const
std::string svg () const
std::string svgAlpha (const char *prefix) const
std::string postscript () const
bool valid () const
Static Public Attributes
static const Color None
static const Color Black
static const Color Gray
static const Color White
static const Color Red
static const Color Green
static const Color Lime
static const Color Blue
static const Color Cyan
static const Color Magenta
static const Color Yellow
static const Color Silver
static const Color Purple
static const Color Navy
static const Color Aqua
Private Attributes
int _red
int _green
int _blue
int _alpha
Detailed Description
Structure representing an RGB triple.
Color structure.
Constructor & Destructor Documentation
LibBoard::Color::Color (const unsigned int rgb, unsigned char alpha = 255)
References _blue, _green, and _red.
LibBoard::Color::Color (unsigned char redValue, unsigned char greenValue, unsigned char blueValue, unsigned char alphaValue = 255) [inline]
LibBoard::Color::Color (unsigned char grayValue, unsigned char alphaValue = 255) [inline]
LibBoard::Color::Color (const bool validColor = true) [inline]
References _blue, _green, and _red.
Member Function Documentation
void LibBoard::Color::alpha (unsigned char alpha) [inline]
References _alpha.
unsigned char LibBoard::Color::alpha () const [inline]
References _alpha.
void LibBoard::Color::blue (unsigned char blue) [inline]
References _blue.
Referenced by LibBoard::Board::fillGouraudTriangle(), LibBoard::GouraudTriangle::flushFIG(), LibBoard::GouraudTriangle::flushPostscript(), LibBoard::GouraudTriangle::flushSVG(), and LibBoard::GouraudTriangle::GouraudTriangle().
unsigned char LibBoard::Color::blue () const [inline]
References _blue.
void LibBoard::Color::flushPostscript (std::ostream & stream) const
References _blue, _green, and _red.
Referenced by LibBoard::Polyline::flushPostscript().
unsigned char LibBoard::Color::green () const [inline]
References _green.
void LibBoard::Color::green (unsigned char green) [inline]
References _green.
Referenced by LibBoard::Board::fillGouraudTriangle(), LibBoard::GouraudTriangle::flushFIG(), LibBoard::GouraudTriangle::flushPostscript(), LibBoard::GouraudTriangle::flushSVG(), and LibBoard::GouraudTriangle::GouraudTriangle().
bool LibBoard::Color::operator!= (const Color & other) const
References _alpha, _blue, _green, and _red.
bool LibBoard::Color::operator< (const Color & other) const
References _alpha, _blue, _green, and _red.
bool LibBoard::Color::operator== (const Color & other) const
References _alpha, _blue, _green, and _red.
string LibBoard::Color::postscript () const
References _blue, _green, _red, and secured_sprintf.
Referenced by LibBoard::Text::flushPostscript(), LibBoard::Ellipse::flushPostscript(), LibBoard::Arrow::flushPostscript(), LibBoard::Line::flushPostscript(), and LibBoard::Dot::flushPostscript().
void LibBoard::Color::red (unsigned char red) [inline]
References _red.
Referenced by LibBoard::Board::fillGouraudTriangle(), LibBoard::GouraudTriangle::flushFIG(), LibBoard::GouraudTriangle::flushPostscript(), LibBoard::GouraudTriangle::flushSVG(), and LibBoard::GouraudTriangle::GouraudTriangle().
unsigned char LibBoard::Color::red () const [inline]
References _red.
Color & LibBoard::Color::setRGBf (float red, float green, float blue, float alpha = 1.0)
References _alpha, _blue, _green, and _red.
Referenced by LibBoard::Board::setFillColorRGBf(), and LibBoard::Board::setPenColorRGBf().
Color & LibBoard::Color::setRGBi (const unsigned char red, const unsigned char green, const unsigned char blue, const unsigned char alpha = 255) [inline]
References _alpha, _blue, _green, and _red.
Referenced by LibBoard::Board::setFillColorRGBi(), and LibBoard::Board::setPenColorRGBi().
string LibBoard::Color::svg () const
References _blue, _green, _red, None, and secured_sprintf.
Referenced by LibBoard::Text::flushSVG(), LibBoard::Arrow::flushSVG(), and LibBoard::Shape::svgProperties().
string LibBoard::Color::svgAlpha (const char * prefix) const
Return a an SVG parameter string for the opacity value.
Parameters:
prefix A prefix string to be appended to the returned string if not empty.
Returns:
An empty string if alpha == 255, otherwise the string <prefix>-opacity="<alpha-value>".
References _alpha, None, and secured_sprintf.
Referenced by LibBoard::Text::flushSVG(), LibBoard::Arrow::flushSVG(), and LibBoard::Shape::svgProperties().
bool LibBoard::Color::valid () const [inline]
References None.
Referenced by LibBoard::Rectangle::flushFIG(), LibBoard::Polyline::flushFIG(), LibBoard::Ellipse::flushFIG(), LibBoard::Arrow::flushFIG(), LibBoard::Image::flushFIG(), LibBoard::Line::flushFIG(), LibBoard::Dot::flushFIG(), and LibBoard::Board::saveFIG().
Field Documentation
int LibBoard::Color::_alpha [private]
The opacity.
Referenced by alpha(), operator!=(), operator<(), operator==(), setRGBf(), setRGBi(), and svgAlpha().
int LibBoard::Color::_blue [private]
The blue component.
Referenced by blue(), Color(), flushPostscript(), operator!=(), operator<(), operator==(), postscript(), setRGBf(), setRGBi(), and svg().
int LibBoard::Color::_green [private]
The green component.
Referenced by Color(), flushPostscript(), green(), operator!=(), operator<(), operator==(), postscript(), setRGBf(), setRGBi(), and svg().
int LibBoard::Color::_red [private]
The red component.
Referenced by Color(), flushPostscript(), operator!=(), operator<(), operator==(), postscript(), red(), setRGBf(), setRGBi(), and svg().
const Color LibBoard::Color::Aqua [static]
const Color LibBoard::Color::Black [static]
Referenced by LibBoard::Board::State::State().
const Color LibBoard::Color::Blue [static]
const Color LibBoard::Color::Cyan [static]
const Color LibBoard::Color::Gray [static]
const Color LibBoard::Color::Green [static]
const Color LibBoard::Color::Lime [static]
const Color LibBoard::Color::Magenta [static]
const Color LibBoard::Color::Navy [static]
const Color LibBoard::Color::None [static]
Referenced by LibBoard::Board::drawArrow(), LibBoard::Board::fillCircle(), LibBoard::Shape::filled(), LibBoard::Board::fillEllipse(), LibBoard::Board::fillPolyline(), LibBoard::Board::fillRectangle(), LibBoard::Board::fillTriangle(), LibBoard::GouraudTriangle::flushFIG(), LibBoard::Polyline::flushPostscript(), LibBoard::Ellipse::flushPostscript(), LibBoard::Board::saveEPS(), LibBoard::Board::saveFIG(), LibBoard::Board::saveSVG(), LibBoard::Board::State::State(), svg(), svgAlpha(), LibBoard::Shape::svgProperties(), and valid().
const Color LibBoard::Color::Purple [static]
const Color LibBoard::Color::Red [static]
const Color LibBoard::Color::Silver [static]
const Color LibBoard::Color::White [static]
const Color LibBoard::Color::Yellow [static]
The documentation for this class was generated from the following files:
Color.h
Color.cpp