DGtal: DGtal::Z3i Namespace Reference
DGtal::Z3i Namespace Reference
Z3i this namespace gathers the standard of types for 3D imagery.
Typedefs
typedef SpaceND< 3 > Space
typedef Space Z3
typedef MetricAdjacency< Space, 1 > Adj6
typedef MetricAdjacency< Space, 2 > Adj18
typedef MetricAdjacency< Space, 3 > Adj26
typedef DigitalTopology< Adj6,
Adj18 > DT6_18
typedef DigitalTopology< Adj18,
Adj6 > DT18_6
typedef DigitalTopology< Adj6,
Adj26 > DT6_26
typedef DigitalTopology< Adj26,
Adj6 > DT26_6
typedef Space::Point Point
typedef Space::Vector Vector
typedef HyperRectDomain< Space > Domain
typedef DigitalSetSelector
< Domain, BIG_DS+HIGH_BEL_DS >
::Type DigitalSet
typedef Object< DT6_18,
DigitalSet > Object6_18
typedef Object< DT6_18,
DigitalSet >::ComplementObject ComplementObject6_18
typedef Object< DT6_18,
DigitalSet >::SmallObject SmallObject6_18
typedef Object< DT6_18,
DigitalSet >
::SmallComplementObject SmallComplementObject6_18
typedef Object< DT18_6,
DigitalSet > Object18_6
typedef Object< DT18_6,
DigitalSet >::ComplementObject ComplementObject18_6
typedef Object< DT18_6,
DigitalSet >::SmallObject SmallObject18_6
typedef Object< DT18_6,
DigitalSet >
::SmallComplementObject SmallComplementObject18_6
typedef Object< DT6_26,
DigitalSet > Object6_26
typedef Object< DT6_26,
DigitalSet >::ComplementObject ComplementObject6_26
typedef Object< DT6_26,
DigitalSet >::SmallObject SmallObject6_26
typedef Object< DT6_26,
DigitalSet >
::SmallComplementObject SmallComplementObject6_26
typedef Object< DT26_6,
DigitalSet > Object26_6
typedef Object< DT26_6,
DigitalSet >::ComplementObject ComplementObject26_6
typedef Object< DT26_6,
DigitalSet >::SmallObject SmallObject26_6
typedef Object< DT26_6,
DigitalSet >
::SmallComplementObject SmallComplementObject26_6
Variables
static const Adj6 adj6
static const Adj18 adj18
static const Adj26 adj26
static const DT6_18 dt6_18 = DT6_18(adj6, adj18, JORDAN_DT)
static const DT18_6 dt18_6 = DT18_6(adj18, adj6, JORDAN_DT)
static const DT6_26 dt6_26 = DT6_26(adj6, adj26, JORDAN_DT)
static const DT26_6 dt26_6 = DT26_6(adj26, adj6, JORDAN_DT)
Detailed Description
Z3i this namespace gathers the standard of types for 3D imagery.
This namespacef gathers all standard type definitions as well as some static instances for using a 3D digital space with integers represented by 'int'. It is useful for a developer who wants to develop an application in the 3D plane and who does not wish to tune specifically the possible types.
This is the standard set of types for 3D imagery.
Todo:
Once stabilized, provide a Z3l (for int64) and a Z3I (for arbitrary integers).
Typedef Documentation
typedef MetricAdjacency< Space, 2> DGtal::Z3i::Adj18
Standard 18-neighborhood for a 3D digital space.
Examples:
3dBorderExtraction.cpp.
Definition at line 117 of file StdDefs.h.
typedef MetricAdjacency< Space, 3> DGtal::Z3i::Adj26
Standard 26-neighborhood for a 3D digital space.
Definition at line 119 of file StdDefs.h.
typedef MetricAdjacency< Space, 1> DGtal::Z3i::Adj6
Standard 6-neighborhood for a 3D digital space.
Examples:
3dBorderExtraction.cpp.
Definition at line 115 of file StdDefs.h.
typedef Object<DT18_6, DigitalSet>::ComplementObject DGtal::Z3i::ComplementObject18_6
Definition at line 133 of file StdDefs.h.
typedef Object<DT26_6, DigitalSet>::ComplementObject DGtal::Z3i::ComplementObject26_6
Definition at line 141 of file StdDefs.h.
typedef Object<DT6_18, DigitalSet>::ComplementObject DGtal::Z3i::ComplementObject6_18
Definition at line 129 of file StdDefs.h.
typedef Object<DT6_26, DigitalSet>::ComplementObject DGtal::Z3i::ComplementObject6_26
Definition at line 137 of file StdDefs.h.
typedef DigitalSetSelector< Domain, BIG_DS+HIGH_BEL_DS >::Type DGtal::Z3i::DigitalSet
Definition at line 127 of file StdDefs.h.
typedef HyperRectDomain< Space > DGtal::Z3i::Domain
Definition at line 126 of file StdDefs.h.
typedef DigitalTopology< Adj18, Adj6 > DGtal::Z3i::DT18_6
Definition at line 121 of file StdDefs.h.
typedef DigitalTopology< Adj26, Adj6 > DGtal::Z3i::DT26_6
Definition at line 123 of file StdDefs.h.
typedef DigitalTopology< Adj6, Adj18 > DGtal::Z3i::DT6_18
Examples:
3dBorderExtraction.cpp.
Definition at line 120 of file StdDefs.h.
typedef DigitalTopology< Adj6, Adj26 > DGtal::Z3i::DT6_26
Definition at line 122 of file StdDefs.h.
typedef Object<DT18_6, DigitalSet> DGtal::Z3i::Object18_6
Examples:
dgtalQGLviewer-3-objects.cpp.
Definition at line 132 of file StdDefs.h.
typedef Object<DT26_6, DigitalSet> DGtal::Z3i::Object26_6
Definition at line 140 of file StdDefs.h.
typedef Object<DT6_18, DigitalSet> DGtal::Z3i::Object6_18
Examples:
dgtalQGLviewer-3-objects.cpp.
Definition at line 128 of file StdDefs.h.
typedef Object<DT6_26, DigitalSet> DGtal::Z3i::Object6_26
Examples:
homotopicThinning3D.cpp.
Definition at line 136 of file StdDefs.h.
typedef Space::Point DGtal::Z3i::Point
Definition at line 124 of file StdDefs.h.
typedef Object<DT18_6, DigitalSet>::SmallComplementObject DGtal::Z3i::SmallComplementObject18_6
Definition at line 135 of file StdDefs.h.
typedef Object<DT26_6, DigitalSet>::SmallComplementObject DGtal::Z3i::SmallComplementObject26_6
Definition at line 143 of file StdDefs.h.
typedef Object<DT6_18, DigitalSet>::SmallComplementObject DGtal::Z3i::SmallComplementObject6_18
Definition at line 131 of file StdDefs.h.
typedef Object<DT6_26, DigitalSet>::SmallComplementObject DGtal::Z3i::SmallComplementObject6_26
Definition at line 139 of file StdDefs.h.
typedef Object<DT18_6, DigitalSet>::SmallObject DGtal::Z3i::SmallObject18_6
Definition at line 134 of file StdDefs.h.
typedef Object<DT26_6, DigitalSet>::SmallObject DGtal::Z3i::SmallObject26_6
Definition at line 142 of file StdDefs.h.
typedef Object<DT6_18, DigitalSet>::SmallObject DGtal::Z3i::SmallObject6_18
Definition at line 130 of file StdDefs.h.
typedef Object<DT6_26, DigitalSet>::SmallObject DGtal::Z3i::SmallObject6_26
Definition at line 138 of file StdDefs.h.
typedef SpaceND<3> DGtal::Z3i::Space
Definition at line 112 of file StdDefs.h.
typedef Space::Vector DGtal::Z3i::Vector
Definition at line 125 of file StdDefs.h.
typedef Space DGtal::Z3i::Z3
Examples:
3dBorderExtraction.cpp.
Definition at line 113 of file StdDefs.h.
Variable Documentation
const Adj18 DGtal::Z3i::adj18 [static]
Examples:
3dBorderExtraction.cpp.
Definition at line 146 of file StdDefs.h.
Referenced by testExpander(), testObject3D(), and testSimplePoints3D().
const Adj26 DGtal::Z3i::adj26 [static]
Definition at line 147 of file StdDefs.h.
const Adj6 DGtal::Z3i::adj6 [static]
Examples:
3dBorderExtraction.cpp.
Definition at line 145 of file StdDefs.h.
Referenced by testExpander(), testObject3D(), and testSimplePoints3D().
const DT18_6 DGtal::Z3i::dt18_6 = DT18_6(adj18, adj6, JORDAN_DT) [static]
Examples:
3dBorderExtractionImg.cpp, and dgtalQGLviewer-3-objects.cpp.
Definition at line 149 of file StdDefs.h.
const DT26_6 DGtal::Z3i::dt26_6 = DT26_6(adj26, adj6, JORDAN_DT) [static]
Definition at line 151 of file StdDefs.h.
const DT6_18 DGtal::Z3i::dt6_18 = DT6_18(adj6, adj18, JORDAN_DT) [static]
Examples:
3dBorderExtraction.cpp, and dgtalQGLviewer-3-objects.cpp.
Definition at line 148 of file StdDefs.h.
Referenced by testExpander(), testObject3D(), and testSimplePoints3D().
const DT6_26 DGtal::Z3i::dt6_26 = DT6_26(adj6, adj26, JORDAN_DT) [static]
Examples:
homotopicThinning3D.cpp.
Definition at line 150 of file StdDefs.h.