DGtal: DGtal::Z2i Namespace Reference
DGtal::Z2i Namespace Reference
Z2i this namespace gathers the standard of types for 2D imagery.
Typedefs
typedef SpaceND< 2 > Space
typedef Space Z2
typedef MetricAdjacency< Space, 1 > Adj4
typedef MetricAdjacency< Space, 2 > Adj8
typedef DigitalTopology< Adj4,
Adj8 > DT4_8
typedef DigitalTopology< Adj8,
Adj4 > DT8_4
typedef Space::Point Point
typedef Space::Vector Vector
typedef HyperRectDomain< Space > Domain
typedef DigitalSetSelector
< Domain, BIG_DS+HIGH_BEL_DS >
::Type DigitalSet
typedef Object< DT4_8, DigitalSet > Object4_8
typedef Object< DT4_8,
DigitalSet >::ComplementObject ComplementObject4_8
typedef Object< DT4_8,
DigitalSet >::SmallObject SmallObject4_8
typedef Object< DT4_8,
DigitalSet >
::SmallComplementObject SmallComplementObject4_8
typedef Object< DT8_4, DigitalSet > Object8_4
typedef Object< DT8_4,
DigitalSet >::ComplementObject ComplementObject8_4
typedef Object< DT8_4,
DigitalSet >::SmallObject SmallObject8_4
typedef Object< DT8_4,
DigitalSet >
::SmallComplementObject SmallComplementObject8_4
Variables
static const Adj4 adj4
static const Adj8 adj8
static const DT4_8 dt4_8 = DT4_8(adj4, adj8, JORDAN_DT)
static const DT8_4 dt8_4 = DT8_4(adj8, adj4, JORDAN_DT)
Detailed Description
Z2i this namespace gathers the standard of types for 2D imagery.
This namespace gathers all standard type definitions as well as some static instances for using a 2D digital space with integers represented by 'int'. It is useful for a developer who wants to develop an application in the 2D plane and who does not wish to tune specifically the possible types.
This is the standard set of types for 2D imagery.
Todo:
Once stabilized, provide a Z2l (for int64) and a Z2I (for arbitrary integers).
Typedef Documentation
typedef MetricAdjacency< Space, 1> DGtal::Z2i::Adj4
Standard 4-neighborhood for a 2D digital space.
Definition at line 74 of file StdDefs.h.
typedef MetricAdjacency< Space, 2> DGtal::Z2i::Adj8
Standard 8-neighborhood for a 2D digital space.
Definition at line 76 of file StdDefs.h.
typedef Object<DT4_8, DigitalSet>::ComplementObject DGtal::Z2i::ComplementObject4_8
Definition at line 84 of file StdDefs.h.
typedef Object<DT8_4, DigitalSet>::ComplementObject DGtal::Z2i::ComplementObject8_4
Definition at line 88 of file StdDefs.h.
typedef DigitalSetSelector< Domain, BIG_DS+HIGH_BEL_DS >::Type DGtal::Z2i::DigitalSet
Examples:
3dBorderExtraction.cpp, dgtalboard-2-sets.cpp, dgtalboard-4-colormaps.cpp, dgtalQGLviewer-2-sets.cpp, dgtalQGLviewer-3-objects.cpp, dgtalQGLviewer-6-clipping.cpp, and homotopicThinning3D.cpp.
Definition at line 82 of file StdDefs.h.
typedef HyperRectDomain< Space > DGtal::Z2i::Domain
Examples:
3dBorderExtraction.cpp, dgtalboard-2-sets.cpp, dgtalboard-4-colormaps.cpp, dgtalQGLviewer-1-points.cpp, dgtalQGLviewer-2-sets.cpp, dgtalQGLviewer-3-objects.cpp, dgtalQGLviewer-4-modes.cpp, dgtalQGLviewer-5-custom.cpp, dgtalQGLviewer-6-clipping.cpp, and homotopicThinning3D.cpp.
Definition at line 81 of file StdDefs.h.
typedef DigitalTopology< Adj4, Adj8 > DGtal::Z2i::DT4_8
Definition at line 77 of file StdDefs.h.
typedef DigitalTopology< Adj8, Adj4 > DGtal::Z2i::DT8_4
Definition at line 78 of file StdDefs.h.
typedef Object<DT4_8, DigitalSet> DGtal::Z2i::Object4_8
Examples:
dgtalboard-2-sets.cpp.
Definition at line 83 of file StdDefs.h.
typedef Object<DT8_4, DigitalSet> DGtal::Z2i::Object8_4
Examples:
dgtalboard-2-sets.cpp.
Definition at line 87 of file StdDefs.h.
typedef Space::Point DGtal::Z2i::Point
Definition at line 79 of file StdDefs.h.
typedef Object<DT4_8, DigitalSet>::SmallComplementObject DGtal::Z2i::SmallComplementObject4_8
Definition at line 86 of file StdDefs.h.
typedef Object<DT8_4, DigitalSet>::SmallComplementObject DGtal::Z2i::SmallComplementObject8_4
Definition at line 90 of file StdDefs.h.
typedef Object<DT4_8, DigitalSet>::SmallObject DGtal::Z2i::SmallObject4_8
Definition at line 85 of file StdDefs.h.
typedef Object<DT8_4, DigitalSet>::SmallObject DGtal::Z2i::SmallObject8_4
Definition at line 89 of file StdDefs.h.
typedef SpaceND<2> DGtal::Z2i::Space
Definition at line 71 of file StdDefs.h.
typedef Space::Vector DGtal::Z2i::Vector
Examples:
distancetransform2D.cpp, and distancetransform3D.cpp.
Definition at line 80 of file StdDefs.h.
typedef Space DGtal::Z2i::Z2
Definition at line 72 of file StdDefs.h.
Variable Documentation
const Adj4 DGtal::Z2i::adj4 [static]
Definition at line 93 of file StdDefs.h.
Referenced by testDGtalBoard(), testDigitalTopologyZ2(), testDraw(), testObject(), testObjectBorder(), and testSimpleExpander().
const Adj8 DGtal::Z2i::adj8 [static]
Definition at line 94 of file StdDefs.h.
Referenced by testDGtalBoard(), testDigitalTopologyZ2(), testDraw(), testObject(), testObjectBorder(), and testSimpleExpander().
const DT4_8 DGtal::Z2i::dt4_8 = DT4_8(adj4, adj8, JORDAN_DT) [static]
Examples:
dgtalboard-2-sets.cpp.
Definition at line 95 of file StdDefs.h.
Referenced by testLayers(), testObjectBorder(), testSimpleExpander(), and testSimplePoints2D().
const DT8_4 DGtal::Z2i::dt8_4 = DT8_4(adj8, adj4, JORDAN_DT) [static]
Examples:
dgtalboard-2-sets.cpp.
Definition at line 96 of file StdDefs.h.
Referenced by testDGtalBoard(), testLayers(), testObjectBorder(), testSimpleExpander(), and testSimplePoints2D().