DGtal: DGtal::HyperRectDomain< TSpace >::ConstRange Struct Reference
DGtal::HyperRectDomain< TSpace >::ConstRange Struct Reference
Aim: range through all the points in the domain. Defines a constructor taking a domain in parameter, begin and end methods returning ConstIterator, and rbegin and rend methods returning ReverseConstIterator.
#include <HyperRectDomain.h>
Public Types
typedef Domain::ConstIterator ConstIterator
typedef
Domain::ReverseConstIterator ReverseConstIterator
Public Member Functions
ConstRange (const HyperRectDomain< TSpace > &domain)
const ConstIterator & begin () const
ConstIterator begin (const Point &aPoint) const
const ConstIterator & end () const
ReverseConstIterator rbegin () const
ReverseConstIterator rbegin (const Point &aPoint) const
ReverseConstIterator rend () const
Private Attributes
const HyperRectDomain< TSpace > & myDomain
ConstIterator myIteratorBegin
ConstIterator myIteratorEnd
Detailed Description
template<typename TSpace>
struct DGtal::HyperRectDomain< TSpace >::ConstRange
Aim: range through all the points in the domain. Defines a constructor taking a domain in parameter, begin and end methods returning ConstIterator, and rbegin and rend methods returning ReverseConstIterator.
Description of class 'ConstRange'
Definition at line 173 of file HyperRectDomain.h.
Member Typedef Documentation
template<typename TSpace> typedef Domain::ConstIterator DGtal::HyperRectDomain< TSpace >::ConstRange::ConstIterator
Definition at line 175 of file HyperRectDomain.h.
template<typename TSpace> typedef Domain::ReverseConstIterator DGtal::HyperRectDomain< TSpace >::ConstRange::ReverseConstIterator
Definition at line 176 of file HyperRectDomain.h.
Constructor & Destructor Documentation
template<typename TSpace> DGtal::HyperRectDomain< TSpace >::ConstRange::ConstRange (const HyperRectDomain< TSpace > & domain) [inline]
ConstRange constructor from a given domain.
Parameters:
domain the domain.
Definition at line 182 of file HyperRectDomain.h.
References DGtal::HyperRectDomain< TSpace >::ConstRange::myIteratorEnd.
Member Function Documentation
template<typename TSpace> const ConstIterator& DGtal::HyperRectDomain< TSpace >::ConstRange::begin () const [inline]
Definition at line 196 of file HyperRectDomain.h.
References DGtal::HyperRectDomain< TSpace >::ConstRange::myIteratorBegin.
Referenced by DGtal::HyperRectDomain< TSpace >::begin(), DGtal::HyperRectDomain< TSpace >::ConstRange::rbegin(), and DGtal::HyperRectDomain< TSpace >::ConstRange::rend().
template<typename TSpace> ConstIterator DGtal::HyperRectDomain< TSpace >::ConstRange::begin (const Point & aPoint) const [inline]
Definition at line 205 of file HyperRectDomain.h.
References ASSERT, and DGtal::HyperRectDomain< TSpace >::ConstRange::myDomain.
template<typename TSpace> const ConstIterator& DGtal::HyperRectDomain< TSpace >::ConstRange::end () const [inline]
Definition at line 214 of file HyperRectDomain.h.
References DGtal::HyperRectDomain< TSpace >::ConstRange::myIteratorEnd.
Referenced by DGtal::HyperRectDomain< TSpace >::end(), and DGtal::HyperRectDomain< TSpace >::ConstRange::rbegin().
template<typename TSpace> ReverseConstIterator DGtal::HyperRectDomain< TSpace >::ConstRange::rbegin () const [inline]
Definition at line 221 of file HyperRectDomain.h.
References DGtal::HyperRectDomain< TSpace >::ConstRange::end().
template<typename TSpace> ReverseConstIterator DGtal::HyperRectDomain< TSpace >::ConstRange::rbegin (const Point & aPoint) const [inline]
Definition at line 230 of file HyperRectDomain.h.
References ASSERT, DGtal::HyperRectDomain< TSpace >::ConstRange::begin(), and DGtal::HyperRectDomain< TSpace >::ConstRange::myDomain.
template<typename TSpace> ReverseConstIterator DGtal::HyperRectDomain< TSpace >::ConstRange::rend () const [inline]
Definition at line 239 of file HyperRectDomain.h.
References DGtal::HyperRectDomain< TSpace >::ConstRange::begin().
Field Documentation
template<typename TSpace> const HyperRectDomain<TSpace>& DGtal::HyperRectDomain< TSpace >::ConstRange::myDomain [private]
Domain associated to the range.
Definition at line 244 of file HyperRectDomain.h.
Referenced by DGtal::HyperRectDomain< TSpace >::ConstRange::begin(), and DGtal::HyperRectDomain< TSpace >::ConstRange::rbegin().
template<typename TSpace> ConstIterator DGtal::HyperRectDomain< TSpace >::ConstRange::myIteratorBegin [private]
Begin iterator.
Definition at line 246 of file HyperRectDomain.h.
Referenced by DGtal::HyperRectDomain< TSpace >::ConstRange::begin().
template<typename TSpace> ConstIterator DGtal::HyperRectDomain< TSpace >::ConstRange::myIteratorEnd [private]
End iterator.
Definition at line 248 of file HyperRectDomain.h.
Referenced by DGtal::HyperRectDomain< TSpace >::ConstRange::ConstRange(), and DGtal::HyperRectDomain< TSpace >::ConstRange::end().
The documentation for this struct was generated from the following file:
HyperRectDomain.h