DGtal: testArithDSS.cpp File Reference
testArithDSS.cpp File Reference
DGtal test files
#include <iostream>
#include <iterator>
#include <cstdio>
#include <cmath>
#include <fstream>
#include <vector>
#include "DGtal/base/Common.h"
#include "DGtal/base/Exceptions.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/geometry/2d/ArithmeticalDSS.h"
#include "DGtal/io/DGtalBoard.h"
Functions
bool testDSS4drawing ()
bool testDSS8drawing ()
bool testExtendRetract ()
bool testCorner ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
Tristan Roussillon (tristan.roussillon@liris.cnrs.fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date:
2010/07/02
This file is part of the DGtal library
Definition in file testArithDSS.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 373 of file testArithDSS.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testCorner(), testDSS4drawing(), testDSS8drawing(), testExtendRetract(), and DGtal::trace.
bool testCorner ()
Test for corners in 8-connected curves (not compatible steps)
Definition at line 350 of file testArithDSS.cpp.
References DGtal::ArithmeticalDSS< TIterator, TInteger, connectivity >::init().
Referenced by main().
bool testDSS4drawing ()
Test for 4-connected points
Definition at line 66 of file testArithDSS.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), LibBoard::Board::saveSVG(), LibBoard::Board::setUnit(), DGtal::HyperRectDomain< TSpace >::styleName(), and DGtal::trace.
Referenced by main().
bool testDSS8drawing ()
Test for 8-connected points
Definition at line 132 of file testArithDSS.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), LibBoard::Board::saveSVG(), LibBoard::Board::setUnit(), DGtal::HyperRectDomain< TSpace >::styleName(), and DGtal::trace.
Referenced by main().
bool testExtendRetract ()
checking consistency between extension and retractation.
Definition at line 202 of file testArithDSS.cpp.
References ASSERT, DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.
Referenced by main().