DGtal: testImageContainerBenchmark.cpp File Reference
testImageContainerBenchmark.cpp File Reference
DGtal test files | DGtal test files
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/kernel/images/ImageSelector.h"
Functions
template<typename Image >
double builtinIteratorScan (const Image &aImage)
template<typename Image , typename Domain >
double domainIteratorScan (const Image &aImage, const Domain &aDomain)
template<typename Point , typename Image , typename Domain >
bool testSuite (unsigned int dim, unsigned int n)
bool testImageContainerBenchmark ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
David Coeurjolly (david.coeurjolly@liris.cnrs.fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date:
2010/07/22
Functions for testing class ImageContainerBenchmark.
This file is part of the DGtal library.
Definition in file testImageContainerBenchmark.cpp.
Function Documentation
template<typename Image > double builtinIteratorScan (const Image & aImage)
Definition at line 46 of file testImageContainerBenchmark.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.
Referenced by testSuite().
template<typename Image , typename Domain > double domainIteratorScan (const Image & aImage, const Domain & aDomain)
Definition at line 63 of file testImageContainerBenchmark.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.
int main (int argc, char ** argv)
Definition at line 226 of file testImageContainerBenchmark.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testImageContainerBenchmark(), and DGtal::trace.
bool testImageContainerBenchmark ()
Example of a test. To be completed.
Definition at line 132 of file testImageContainerBenchmark.cpp.
References DGtal::Trace::beginBlock(), dim, DGtal::Trace::endBlock(), and DGtal::trace.
Referenced by main().
template<typename Point , typename Image , typename Domain > bool testSuite (unsigned int dim, unsigned int n)
Definition at line 79 of file testImageContainerBenchmark.cpp.
References DGtal::Trace::beginBlock(), builtinIteratorScan(), dim, DGtal::Trace::endBlock(), DGtal::Trace::error(), DGtal::Trace::info(), DGtal::trace, and DGtal::Trace::warning().