DGtal: testDT2Dperf.cpp File Reference
testDT2Dperf.cpp File Reference
DGtal test files
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/kernel/images/ImageSelector.h"
#include "DGtal/geometry/nd/volumetric/DistanceTransformation.h"
Functions
template<typename Image >
void randomSeeds (Image &input, const unsigned int nb, const int value)
bool testDT2Dperf ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
David Coeurjolly (david.coeurjolly@liris.cnrs.fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date:
2011/03/03
Functions for testing class DT2Dperf.
This file is part of the DGtal library.
Definition in file testDT2Dperf.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 110 of file testDT2Dperf.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testDT2Dperf(), and DGtal::trace.
template<typename Image > void randomSeeds (Image & input, const unsigned int nb, const int value)
Definition at line 47 of file testDT2Dperf.cpp.
References dim.
bool testDT2Dperf ()
Example of a test. To be completed.
Definition at line 71 of file testDT2Dperf.cpp.
References DGtal::Trace::beginBlock(), DGtal::DistanceTransformation< TImage, TImageOutput, TSeparableMetric >::checkTypesValidity(), DGtal::DistanceTransformation< TImage, TImageOutput, TSeparableMetric >::compute(), DGtal::Trace::endBlock(), DGtal::Trace::info(), randomSeeds(), and DGtal::trace.
Referenced by main().