DGtal: testSpaceND.cpp File Reference
testSpaceND.cpp File Reference
#include <cstdio>
#include <cmath>
#include <iostream>
#include <fstream>
#include <assert.h>
#include <vector>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
Functions
bool testSimpleSpace ()
bool testInteger ()
int main ()
Function Documentation
int main ()
Definition at line 76 of file testSpaceND.cpp.
References testInteger(), and testSimpleSpace().
bool testInteger ()
Definition at line 68 of file testSpaceND.cpp.
bool testSimpleSpace ()
Test instanciation of SpaceND
Definition at line 51 of file testSpaceND.cpp.
References DGtal::SpaceND< dim, TInteger >::subcospace().
Referenced by main().