DGtal: testObject-benchmark.cpp File Reference
testObject-benchmark.cpp File Reference
#include <cmath>
#include <iostream>
#include <sstream>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/DomainPredicate.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/kernel/sets/DigitalSetSelector.h"
#include "DGtal/kernel/sets/DigitalSetConverter.h"
#include "DGtal/topology/MetricAdjacency.h"
#include "DGtal/topology/DomainMetricAdjacency.h"
#include "DGtal/topology/DomainAdjacency.h"
#include "DGtal/topology/DigitalTopology.h"
#include "DGtal/topology/Object.h"
#include "DGtal/topology/Expander.h"
Defines
#define INBLOCK_TEST(x)
#define INBLOCK_TEST2(x, y)
Functions
bool testObject ()
bool testObject3D ()
bool testSimplePoints3D ()
bool testDraw ()
int main (int argc, char **argv)
Define Documentation
#define INBLOCK_TEST (x)
Value:
nbok += (x) ? 1 : 0; \
  nb++; \
  trace.info() << "(" << nbok << "/" << nb << ") " \
  << #x << std::endl;
Definition at line 52 of file testObject-benchmark.cpp.
Referenced by testObject3D().
#define INBLOCK_TEST2 (x, y)
Value:
nbok += (x) ? 1 : 0; \
  nb++; \
  trace.info() << "(" << nbok << "/" << nb << ") " \
  << y << std::endl;
Definition at line 58 of file testObject-benchmark.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 512 of file testObject-benchmark.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testDraw(), testObject(), testObject3D(), testSimplePoints3D(), and DGtal::trace.
bool testDraw ()
Definition at line 410 of file testObject-benchmark.cpp.
References DGtal::Z2i::adj4, DGtal::Z2i::adj8, DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::JORDAN_DT, LibBoard::Board::saveSVG(), LibBoard::Board::setUnit(), and DGtal::trace.
Referenced by main().
bool testObject ()
Example of a test. To be completed.
Definition at line 71 of file testObject-benchmark.cpp.
References DGtal::Z2i::adj4, DGtal::Z2i::adj8, DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::JORDAN_DT, DGtal::Object< TDigitalTopology, TDigitalSet >::neighborhood(), DGtal::Object< TDigitalTopology, TDigitalSet >::pointSet(), DGtal::Object< TDigitalTopology, TDigitalSet >::properNeighborhood(), DGtal::Object< TDigitalTopology, TDigitalSet >::size(), and DGtal::trace.
Referenced by main().
bool testObject3D ()
Example of a test. To be completed.
Definition at line 253 of file testObject-benchmark.cpp.
References DGtal::Z3i::adj18, DGtal::Z3i::adj6, DGtal::Trace::beginBlock(), DGtal::Z3i::dt6_18, DGtal::Trace::endBlock(), INBLOCK_TEST, DGtal::Trace::info(), DGtal::JORDAN_DT, and DGtal::trace.
Referenced by main().
bool testSimplePoints3D ()
Example of a test. To be completed.
Definition at line 348 of file testObject-benchmark.cpp.
References DGtal::Z3i::adj18, DGtal::Z3i::adj6, DGtal::Trace::beginBlock(), DGtal::Z3i::dt6_18, DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::JORDAN_DT, and DGtal::trace.
Referenced by main().