DGtal: test3dViewer.cpp File Reference
test3dViewer.cpp File Reference
DGtal test files
#include <iostream>
#include <QtGui/qapplication.h>
#include "DGtal/3dViewer/DGtalQGLViewer.h"
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/helpers/Shapes.h"
Functions
bool testDGtalQGLViewer ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
Bertrand Kerautret (kerautre@loria.fr) LORIA (CNRS, UMR 7503), University of Nancy, France
Date:
2011/01/03
Functions for testing class DGtalQGLViewer.
This file is part of the DGtal library.
Definition in file test3dViewer.cpp.
Function Documentation
int main (int argc, char ** argv)
Examples:
3dBorderExtraction.cpp, 3dBorderExtractionImg.cpp, dgtalboard-1-points.cpp, dgtalboard-2-sets.cpp, dgtalboard-3-custom-classes.cpp, dgtalboard-3-custom-points.cpp, dgtalboard-4-colormaps.cpp, dgtalQGLviewer-1-points.cpp, dgtalQGLviewer-2-sets.cpp, dgtalQGLviewer-3-objects.cpp, dgtalQGLviewer-4-modes.cpp, dgtalQGLviewer-5-custom.cpp, dgtalQGLviewer-6-clipping.cpp, digitalSetFromPointList.cpp, digitalSetFromVol.cpp, distancetransform2D.cpp, distancetransform3D.cpp, and homotopicThinning3D.cpp.
Definition at line 68 of file test3dViewer.cpp.
References DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::PointVector< dim, Integer >::styleName(), DGtal::HyperRectDomain< TSpace >::styleName(), and DGtal::trace.
bool testDGtalQGLViewer ()
Example of a test. To be completed.
Definition at line 50 of file test3dViewer.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.