DGtal: volIVViewer.cpp File Reference
volIVViewer.cpp File Reference
#include <iostream>
#include <Qt/qapplication.h>
#include <Inventor/nodes/SoCube.h>
#include "DGtal/inventor/DGtalInventor.h"
#include "DGtal/inventor/IVViewer.h"
#include "DGtal/base/Common.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/kernel/images/ImageSelector.h"
#include "DGtal/io/readers/VolReader.h"
#include "DGtal/io/colormaps/GradientColorMap.h"
#include "DGtal/topology/SurfelAdjacency.h"
#include "DGtal/topology/SurfelNeighborhood.h"
#include "DGtal/topology/KhalimskySpaceND.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/helpers/Shapes.h"
#include "DGtal/helpers/Surfaces.h"
#include "ConfigTest.h"
Functions
void addAxis (DGtalInventor< Space > &inventor, const Point &low, const Point &up, Dimension k, const LibBoard::Color &c1, const LibBoard::Color &c2)
void addBounds (DGtalInventor< Space > &inventor, const Point &low, const Point &up)
int main (int argc, char **argv)
Function Documentation
void addAxis (DGtalInventor< Space > & inventor, const Point & low, const Point & up, Dimension k, const LibBoard::Color & c1, const LibBoard::Color & c2)
Definition at line 60 of file volIVViewer.cpp.
References DGtal::GradientColorMap< PValue, PDefaultPreset, PDefaultFirstColor, PDefaultLastColor >::addColor(), LibBoard::Color::blue(), DGtal::GradientColorMap< PValue, PDefaultPreset, PDefaultFirstColor, PDefaultLastColor >::clearColors(), DGtal::DGtalInventor< TSpace >::drawPoint(), LibBoard::Color::green(), LibBoard::Color::red(), and DGtal::DGtalInventor< TSpace >::setDiffuseColor().
void addBounds (DGtalInventor< Space > & inventor, const Point & low, const Point & up)
Definition at line 82 of file volIVViewer.cpp.
References DGtal::DGtalInventor< TSpace >::drawPoint(), and DGtal::DGtalInventor< TSpace >::setDiffuseColor().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 107 of file volIVViewer.cpp.
References addBounds(), DGtal::Trace::beginBlock(), DGtal::DGtalInventor< TSpace >::drawCell(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::DGtalInventor< TSpace >::generate(), DGtal::Trace::info(), DGtal::IVViewer::root(), DGtal::DGtalInventor< TSpace >::setDiffuseColor(), DGtal::IVViewer::show(), testPath, and DGtal::trace.