DGtal: DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey > Class Template Reference
DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey > Class Template Reference
#include <ImageContainerByHashTree.h>
Data Structures
class Iterator
class Node
Public Types
typedef
ImageContainerByHashTree
< TDomain, TValue, THashKey > Self
typedef THashKey HashKey
typedef TDomain Domain
typedef Domain::Point Point
typedef Domain::Vector Vector
typedef Domain::Integer Integer
typedef Domain::Size Size
typedef Domain::Dimension Dimension
typedef Point Vertex
typedef POW< 2, dimension > PowHelper
typedef TValue Value
typedef DefaultConstImageRange
< Self > ConstRange
typedef DefaultImageRange< Self > Range
typedef SetValueIterator< Self > OutputIterator
Public Member Functions
BOOST_CONCEPT_ASSERT ((CDomain< TDomain >))
BOOST_STATIC_CONSTANT (Dimension, dimension=Domain::dimension)
BOOST_STATIC_CONSTANT (Dimension, dim=Domain::dimension)
BOOST_STATIC_CONSTANT (unsigned int, NbChildrenPerNode=PowHelper::VALUE)
BOOST_STATIC_CONSTANT (HashKey, ROOT_KEY=static_cast< THashKey >(1))
BOOST_STATIC_ASSERT ((boost::is_same< Domain, HyperRectDomain< typename Domain::Space > >::value))
BOOST_CONCEPT_ASSERT ((CLabel< TValue >))
ImageContainerByHashTree (const unsigned int hashKeySize, const unsigned int depth, const Value defaultValue)
ImageContainerByHashTree (const unsigned int hashKeySize, const Point &p1, const Point &p2, const Value defaultValue)
ImageContainerByHashTree (const Domain &aDomain, const unsigned int hashKeySize=3, const Value defaultValue=NumberTraits< Value >::ZERO)
const Domain & domain () const
ConstRange constRange () const
Range range ()
Value get (const HashKey key) const
Value operator() (const HashKey key) const
Value operator() (const Point &aPoint) const
Value get (const Point &aPoint) const
Value upwardGet (const HashKey key) const
Value reverseGet (const HashKey key) const
void setValue (const HashKey key, const Value object)
void setValue (const Point &aPoint, const Value object)
unsigned int getSpanSize () const
unsigned int getDepth () const
bool isKeyValid (HashKey key) const
bool checkIntegrity (HashKey key=ROOT_KEY, bool leafAbove=false) const
HashKey getKey (const Point &aPoint) const
unsigned int getKeyDepth (HashKey key) const
int * getCoordinatesFromKey (HashKey key) const
void printState (std::ostream &out, bool displayKeys=false) const
void printTree (HashKey key, std::ostream &out, bool displayKeys) const
void printInternalState (std::ostream &out, unsigned int nbBits=0) const
void printInfo (std::ostream &out) const
unsigned int getNbEmptyLists () const
double getAverageCollisions () const
unsigned int getMaxCollisions () const
unsigned int getNbNodes (unsigned int intermediateKey) const
unsigned int getNbNodes () const
Iterator begin ()
Iterator end ()
void selfDisplay (std::ostream &out)
bool isValid () const
std::string className () const
Node * getNode (const HashKey key) const
Data Fields
int myDebugCounter
Point myOrigin
Morton< HashKey, Point > myMorton
Protected Member Functions
template<typename C >
void recursiveDraw (HashKey key, const double p1[2], const double len, Board2D &board, const C &cmap) const
HashKey getIntermediateKey (const HashKey key) const
Node * addNode (const Value object, const HashKey key)
bool removeNode (HashKey key)
void recursiveRemoveNode (HashKey key, unsigned int nbRecursions)
void setDepth (unsigned int depth)
Value blendChildren (HashKey key) const
BOOST_STATIC_CONSTANT (unsigned int, myN=NbChildrenPerNode)
Protected Attributes
Domain myDomain
Node ** myData
unsigned int myKeySize
unsigned int myArraySize
unsigned int myTreeDepth
unsigned int mySpanSize
HashKey myDepthMask
HashKey myPreComputedIntermediateMask
Detailed Description
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t>
class DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >
Model of CImageContainer implementing the association key<->Value using a hash tree. This class provides a built-in iterator.
Description of template class 'ImageContainerByHashTree'
Todo:
doc here
The ImageContainerByHashTree relies on a tree model implemented using a hash table based on Morton Codes. A Morton hash key is obtained from coordinates by interleaving the binary representations of the coordinate values. This means the coordinates have to be of integer type for the morton code to be valid.
The data can be accessed using keys, coordinates or Iterators provided by the container.
The parent of a given key can be found by simply shifting to the left the key's bits by it's dimension. exemples: for an octree (N = 3) the parent key of the key 1110100001 is 1110100. for a quadtree (N = 2) the parent key of the key 10010111 is 100101.
It is then easy to determine, for a N-Dimmensionnal container, all the children keys of a given key, by concatenating any combination of N bits at the right side of the key (least important bits). exemple: for a quadtree (N = 2) 1010100, 1010101, 1010110 and 1010111 are the children of 10101.
In order to disgard any ambiguous case, we need to make the assertion that the root of the hash is at key 1. Else we would have to deal with the problem of the key 00000..0 which would have one of it's children equal to 0 and so on... This means that we need to set the key's N*maxDepth bit to 1 after interleaving the corrdinates bit for key generation.
Note that not any combination of bits is valid. We saw the exemple of the key 0, and there are other cases of invalidity. For a key to be valid, the last set bit (most important set bit) must be at a position of the form k*N with N the Dimmension of the Domain and k a positive integer. exemples: for an octree(N = 3) 1, 1000, 1010111 are valid keys, whereas 0, 10, 11101 are not !
Warning ! For performances this container's access method never check for a key's validity. Trying to access an invalid key may destroy the validity of the tree's structure and/or get the program stuck into an infinite loop.
The method isKeyValid(..) is provided to verify the validity of a key. Note that using this security strongly affects performances.
Template Parameters
TDomain type of domains
TValue type for image values
THashKey type to store Morton keys (default: DGtal::uint64_t)
See Also
testImageContainerByHashTree.cpp
Definition at line 128 of file ImageContainerByHashTree.h.
Member Typedef Documentation
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> typedef DefaultConstImageRange<Self> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::ConstRange
Definition at line 167 of file ImageContainerByHashTree.h.
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> typedef Domain::Dimension DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Dimension
Definition at line 148 of file ImageContainerByHashTree.h.
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> typedef TDomain DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Domain
Definition at line 143 of file ImageContainerByHashTree.h.
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> typedef THashKey DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::HashKey
Definition at line 139 of file ImageContainerByHashTree.h.
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> typedef Domain::Integer DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Integer
Definition at line 146 of file ImageContainerByHashTree.h.
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> typedef SetValueIterator<Self> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::OutputIterator
output iterator
Definition at line 171 of file ImageContainerByHashTree.h.
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> typedef Domain::Point DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Point
Definition at line 144 of file ImageContainerByHashTree.h.
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> typedef POW<2, dimension> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::PowHelper
Definition at line 154 of file ImageContainerByHashTree.h.
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> typedef DefaultImageRange<Self> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Range
Definition at line 168 of file ImageContainerByHashTree.h.
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> typedef ImageContainerByHashTree<TDomain, TValue, THashKey> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Self
Definition at line 132 of file ImageContainerByHashTree.h.
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> typedef Domain::Size DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Size
Definition at line 147 of file ImageContainerByHashTree.h.
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> typedef TValue DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Value
Definition at line 165 of file ImageContainerByHashTree.h.
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> typedef Domain::Vector DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Vector
Definition at line 145 of file ImageContainerByHashTree.h.
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> typedef Point DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Vertex
Definition at line 149 of file ImageContainerByHashTree.h.
Constructor & Destructor Documentation
template<typename Domain , typename Value , typename HashKey > DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::ImageContainerByHashTree (const unsigned int hashKeySize, const unsigned int depth, const Value defaultValue) inline
The constructor from a hashKeySize, a depth and a defaultValue.
Parameters
hashKeySize Number of bit of the hash key. This parameter is important as it influences the amount of collisions in the hash table. A value K creates an array of length 2^K with potential unused cells so a compromise between speed and memory usage is to be done here.
depth Determines the maximum depth of the tree and thus qthe "size" of the image. Each span then extends from 0 to 2^depth.
defaultValue In order for the tree to be valid it needs a default value at the root (key = 1)
Definition at line 64 of file ImageContainerByHashTree.ih.
References DGtal::Trace::error(), and DGtal::trace.
     :  myKeySize ( hashKeySize )
   {
     //Consistency check of the hashKeysize
     ASSERT ( hashKeySize <= sizeof ( HashKey ) *8 );
     myOrigin = Point::zero;
     myPreComputedIntermediateMask = ~ ( static_cast<HashKey> ( ~0 ) << myKeySize );
     unsigned int acceptedDepth = ( ( sizeof ( HashKey ) * 8 - 2 ) / dim );
     unsigned int acceptedDomainDepth = ( sizeof ( typename Domain::Point::Coordinate ) * 8 - 1 );
     if (( depth > acceptedDepth ) || (depth > acceptedDomainDepth))
       {
         trace.error() << "ImageContainerByHashTree::Constructor: error !" << std::endl;
         trace.error() << "requested depth too high for the key type" << std::endl;
         trace.error() << "accepted: " << acceptedDepth << " accepted (Domain): "<<acceptedDomainDepth<<" Requested: " << depth << std::endl;
         setDepth ( ( acceptedDepth < acceptedDomainDepth) ? acceptedDepth -1 : acceptedDomainDepth -1 );
       }
     else
       setDepth ( depth );
     myDomain = Domain(Point::zero, Point::diagonal(static_cast<typename Point::Component>( pow(2.0, (int)myTreeDepth) )));
     //init the array
     myArraySize = 1 << myKeySize;
     myData = new Node*[myArraySize];
     for ( unsigned i = 0; i < myArraySize; ++i )
       myData[i] = 0;
     addNode ( defaultValue, ROOT_KEY );
   }
template<typename Domain , typename Value , typename HashKey > DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::ImageContainerByHashTree (const unsigned int hashKeySize, const Point & p1, const Point & p2, const Value defaultValue) inline
The constructor from a hashKeySize, a defaultValue and a pair of points. In this case, the depth of the tree is given by the logarithm of the domain size defined by the two points.
Parameters
hashKeySize Number of bit of the hash key. This parameter is important as it influences the amount of collisions in the hash table. A value K creates an array of length 2^K with potential unused cells so a compromise between speed and memory usage is to be done here.
p1 First point of the image bounding box.
p2 Second point of the image bounding box.
defaultValue In order for the tree to be valid it needs a default value at the root (key = 1)
Definition at line 148 of file ImageContainerByHashTree.ih.
References DGtal::Trace::error(), and DGtal::trace.
     : myDomain( p1, p2 ), myKeySize ( hashKeySize ), myOrigin ( p1 )
   {
     //Consistency check of the hashKeysize
     ASSERT ( hashKeySize <= sizeof ( HashKey ) *8 );
     myPreComputedIntermediateMask = ~ ( static_cast<HashKey> ( ~0 ) << myKeySize );
     int maxSize = 0;
     for ( unsigned int i = 0; i < dim; ++i )
       if ( maxSize < p1[i] - p2[i] )
         maxSize = p1[i] - p2[i];
     unsigned int depth = (unsigned int)(ceil ( log ( (double) maxSize ) / log((double) 2.0) ));
     unsigned int  acceptedDepth = ( ( sizeof ( HashKey ) * 8 - 1 ) / dim );
     if ( depth > acceptedDepth )
       {
         trace.error() << "ImageContainerByHashTree::Constructor: error !"
                       << " requested depth too high for the key type" << std::endl;
         trace.error() << "accepted: " << acceptedDepth
                       << " Requested: " << depth << std::endl;
         setDepth ( acceptedDepth );
       }
     else
       setDepth ( depth );
     //init the array
     myArraySize = 1 << hashKeySize;
     myData = new Node*[myArraySize];
     for ( unsigned int i = 0; i < myArraySize; ++i )
       myData[i] = 0;
     //add the default value
     addNode ( defaultValue, ROOT_KEY );
   }
template<typename Domain , typename Value , typename HashKey > DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::ImageContainerByHashTree (const Domain & aDomain, const unsigned int hashKeySize = 3, const Value defaultValue = NumberTraits<Value>::ZERO) inline
The constructor from a domain, a defaultValue (default value: 0) and a hashKeySize (default value: 3). In this case, the depth of the tree is given by the logarithm of the domain size defined by the two points.
Parameters
aDomain the image domain
hashKeySize Number of bit of the hash key. This parameter is important as it influences the amount of collisions in the hash table. A value K creates an array of length 2^K with potential unused cells so a compromise between speed and memory usage is to be done here (default: 3).
defaultValue In order for the tree to be valid it needs a default value at the root (key = 1)
Definition at line 104 of file ImageContainerByHashTree.ih.
References DGtal::Trace::error(), and DGtal::trace.
                                                          :
     myDomain(aDomain),  myKeySize ( hashKeySize )
   {
     myOrigin = aDomain.lowerBound() ;
     //Consistency check of the hashKeysize
     ASSERT ( hashKeySize <= sizeof ( HashKey ) *8 );
     Point p1 = myDomain.lowerBound();
     Point p2 = myDomain.upperBound();
     myPreComputedIntermediateMask = ~ ( static_cast<HashKey> ( ~0 ) << myKeySize );
     typename Point::Component maxSize = (p2-p1).normInfinity();
     unsigned int depth = (unsigned int)(ceil ( log2 ( (double) maxSize ))) ;
     unsigned int  acceptedDepth = ( ( sizeof ( HashKey ) * 8 - 1 ) / dim );
     trace.error()<<" MAXSIZE = "<< maxSize<<" DEPTH="<< depth <<" accepted="<< acceptedDepth<< std::endl;
     if ( depth > acceptedDepth )
       {
         trace.error() << "ImageContainerByHashTree::Constructor: error !"
                       << " requested depth too high for the key type" << std::endl;
         trace.error() << "accepted: " << acceptedDepth
                       << " Requested: " << depth << std::endl;
         setDepth ( acceptedDepth );
       }
     else
       setDepth ( depth );
     //init the array
     myArraySize = 1 << hashKeySize;
     myData = new Node*[myArraySize];
     for ( unsigned int i = 0; i < myArraySize; ++i )
       myData[i] = 0;
     //add the default value
     addNode ( defaultValue, ROOT_KEY );
   }
Member Function Documentation
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Node* DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::addNode (const Value object, const HashKey key) inline protected
Add a Node to the tree. This method is very used when writing in the tree (set method). As detailed in the inner class Node, nodes are pairs (value,key)
Parameters
object a object (value)
key a hashtree key
Returns
a pointer to the node list.
Definition at line 679 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getIntermediateKey(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNode(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getObject(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myData, and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::setNext().
     {
       Node* n = getNode(key);
       if (n)
         {
           n->getObject() = object;
           //n->setObject(object);
           return n;
         }
       n = new Node(object, key);
       HashKey key2 = getIntermediateKey(key);
       n->setNext(myData[key2]);
       myData[key2] = n;
       return n;
     }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Iterator DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::begin () inline
Returns an iterator to the first value as stored in the container.
Definition at line 550 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myArraySize, and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myData.
     {
       return Iterator(myData, 0, myArraySize);
     }
template<typename Domain , typename Value , typename HashKey > Value DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::blendChildren (HashKey key) const protected
Recursively get the value of all the leafs below and blend it to get the value of a parent node. This is called in the get() method when it has been determined that the leafs are deeper than the requested key.
Definition at line 822 of file ImageContainerByHashTree.ih.
References DGtal::Morton< THashKey, TPoint >::childrenKeys(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNode(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getObject(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myMorton.
   {
     Node* n = getNode ( key );
     if ( n )
       {
         return n->getObject();
       }
     else
       {
         HashKey children[myN];
         myMorton.childrenKeys ( key, children );
         float result = 0;
         for ( unsigned int i = 0; i < myN; ++i )
           {
             result += blendChildren ( children[i] );
           }
         return static_cast<Value> ( result / myN );
       }
   }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::BOOST_CONCEPT_ASSERT ((CDomain< TDomain >))
domain
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::BOOST_CONCEPT_ASSERT ((CLabel< TValue >))
values range
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::BOOST_STATIC_ASSERT ((boost::is_same< Domain, HyperRectDomain< typename Domain::Space > >::value))
domain should be rectangular
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::BOOST_STATIC_CONSTANT (Dimension , dimension = Domain::dimension)
static constants
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::BOOST_STATIC_CONSTANT (Dimension , dim = Domain::dimension)
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::BOOST_STATIC_CONSTANT (unsigned int, NbChildrenPerNode = PowHelper::VALUE)
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::BOOST_STATIC_CONSTANT (HashKey , ROOT_KEY = static_cast< THashKey >(1))
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::BOOST_STATIC_CONSTANT (unsigned int, myN = NbChildrenPerNode) protected
template<typename Domain , typename Value , typename HashKey > bool DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::checkIntegrity (HashKey key = ROOT_KEY, bool leafAbove = false) const
Checks recursively that the sub-tree starting with key is valid. A tree is valid if there's one (and only one) leaf for each position at maximal depth.
Parameters
key the key
leafAbove leafAbove ()
Definition at line 845 of file ImageContainerByHashTree.ih.
References DGtal::Bits::bitString(), DGtal::Morton< THashKey, TPoint >::childrenKeys(), DGtal::Trace::error(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getKeyDepth(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNode(), DGtal::Trace::info(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::isKeyValid(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myMorton, DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myTreeDepth, and DGtal::trace.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::isValid().
   {
     trace.info() << "Checking key=" << key << std::endl;
     if ( !isKeyValid ( key ) )
       {
         trace.error() << "checkIntegrity->invalid key " << Bits::bitString ( key );
         trace.info() << std::endl;
         ASSERT ( 1 == 0 );
       }
     Node* n = getNode ( key );
     if ( ( n != 0 ) && ( leafAbove ) )
       {
         trace.error() << "ImageContainerByHashTree::checkIntegrity - error:" << std::endl
                       << "at key " << Bits::bitString ( key ) << std::endl
                       << "several leafs found" << std::endl;
         return false;
       }
     if ( getKeyDepth ( key ) >= myTreeDepth )
       {
         if ( leafAbove || n )
           {
             return true;
           }
         else
           {
             trace.error() << "ImageContainerByHashTree::checkIntegrity - error:" << std::endl
                           << "at key " << Bits::bitString ( key ) << std::endl
                           << "no leaf found" << std::endl;
             return false;
           }
       }
     HashKey children[myN];
     myMorton.childrenKeys ( key, children );
     bool returnValue = true;
     for ( unsigned int i = 0; i < myN; ++i )
       returnValue &= checkIntegrity ( children[i], ( n || leafAbove ) );
     return returnValue;
   }
template<typename Domain , typename Value , typename HashKey > std::string DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::className () const inline
Default drawing style object.
Returns
the dyn. alloc. default style for this object.
the style name used for drawing this object.
Definition at line 815 of file ImageContainerByHashTree.ih.
   {
     return "ImageContainerByHashTree";
   }
template<typename Domain , typename Value , typename HashKey > ImageContainerByHashTree< Domain, Value, HashKey >::ConstRange DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::constRange () const inline
Returns
an instance of ConstRange used to iterate over the values.
Definition at line 204 of file ImageContainerByHashTree.ih.
   {
     return ConstRange(  *this );
   }
template<typename Domain , typename Value , typename HashKey > const ImageContainerByHashTree< Domain, Value, HashKey >::Domain & DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::domain () const inline
Copy contructor.
Parameters
other object to copy. Assignment.
other object to copy. Destructor Free the memory allocated by myData
Returns
the domain associated to the image.
Definition at line 195 of file ImageContainerByHashTree.ih.
   {
     return myDomain;
   }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Iterator DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::end () inline
Returns an iterator to the last value as stored in the container.
Definition at line 558 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myArraySize, and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myData.
     {
       return Iterator(myData, myArraySize, myArraySize);
     }
template<typename Domain , typename Value , typename HashKey > Value DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::get (const HashKey key) const inline
Returns the value corresponding to a key.
This is the generic method working with any valid key. For efficiency no check is performed on the key so be careful when calling this method. If the leafs are deeper than the requested key, this method will recursively browse through the children nodes and compute a average of each child's value using blendChildren(..) which is very slow. Thus performances are much better when accessing a leaf from a deeper key (needs no blending).
Parameters
key the haskkey
Returns
the value
Definition at line 331 of file ImageContainerByHashTree.ih.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getObject().
   {
     HashKey iterKey = key;
     // node above the requested node
     while ( iterKey != 0 )
       {
         Node* n = getNode ( iterKey );
         if ( n )
           return n->getObject();
         iterKey >>= dim;
       }
     //if the node is deeper than the one requested
     return blendChildren ( key );
   }
template<typename Domain , typename Value , typename HashKey > Value DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::get (const Point & aPoint) const inline
Returns the value at a given coordinate using upwardGet().
Parameters
aPoint The point
Returns
the value
Definition at line 378 of file ImageContainerByHashTree.ih.
   {
     return get ( getKey ( aPoint ) );
   }
template<typename Domain , typename Value , typename HashKey > double DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::getAverageCollisions () const inline
Returns The average number of collisions in the hash table, without counting the empty places.
Definition at line 766 of file ImageContainerByHashTree.ih.
References DGtal::Trace::error(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNbNodes(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myData, DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myKeySize, and DGtal::trace.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInfo(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInternalState().
   {
     double count = 0;
     double nbLists = 0;
     unsigned int arraySize = 1 << myKeySize;
     for ( unsigned int i = 0; i < arraySize; ++i )
       {
         if ( myData[i] )
           {
             count += getNbNodes ( i ) - 1;
             nbLists++;
           }
       }
     if ( nbLists == 0 )
       {
         trace.error() << "ImageContainerByHashTree::getAverageCollision() - error" << std::endl
                       << "the container is empty !" << std::endl;
         return 0;
       }
     return count / nbLists;
   }
template<typename Domain , typename Value , typename HashKey > int * DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::getCoordinatesFromKey (HashKey key) const inline
Definition at line 548 of file ImageContainerByHashTree.ih.
References DGtal::Bits::mask().
   {
     //remove the first bit equal 1
     for ( int i = ( sizeof ( HashKey ) << 3 ) - 1; i >= 0; --i )
       {
         if ( key & Bits::mask<HashKey> ( i ) )
           {
             key &= ~Bits::mask<HashKey> ( i );
             break;
           }
       }
     int* coordinates = new int[dim];
     //deinterleave the bits
     for ( unsigned int i = 0; i < dim; ++i )
       {
         coordinates[i] = 0;
         for ( unsigned int bitPos = 0; bitPos < ( sizeof ( HashKey ) << 3 ) / dim; ++bitPos )
           {
             if ( key & Bits::mask ( bitPos*dim + i ) )
               {
                 coordinates[i] |= Bits::mask<HashKey> ( bitPos );
               }
           }
       }
     return coordinates;
   }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> unsigned int DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getDepth () const inline
Returns the tree's depth.
Returns
the depth
Definition at line 379 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myTreeDepth.
     {
       return myTreeDepth;
     }
template<typename Domain , typename Value , typename HashKey > HashKey DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::getIntermediateKey (const HashKey key) const inline protected
This is part of the hash function. It is called whenever a key is accessed. The mask used to compute the result is precomputed in the constructor for efficiency.
Parameters
key a node in the hashtree.
Definition at line 427 of file ImageContainerByHashTree.ih.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::addNode(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNode(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::removeNode().
   {
     return ( key & myPreComputedIntermediateMask );
   }
template<typename Domain , typename Value , typename HashKey > HashKey DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::getKey (const Point & aPoint) const inline
Definition at line 410 of file ImageContainerByHashTree.ih.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInternalState().
   {
     HashKey result = 0;
     Point currentPos = aPoint - myOrigin;
     myMorton.interleaveBits ( currentPos, result );
     // by convention, the root node has the key 0..01
     // it makes it easy to determine the depth of a node by it's key (looking
     // at the position of the most significant bit that is equal to 1)
     result |= myDepthMask;
     return result;
   }
template<typename Domain , typename Value , typename HashKey > unsigned int DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::getKeyDepth (HashKey key) const inline
Definition at line 534 of file ImageContainerByHashTree.ih.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::checkIntegrity(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::isKeyValid(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printTree().
   {
     for ( int i = ( sizeof ( HashKey ) << 3 ) - 1; i >= 0; --i )
       if ( key & ( static_cast<HashKey> ( 1 ) << i ) )
         {
           return ( i ) / dim;
         }
     return 0;
   }
template<typename Domain , typename Value , typename HashKey > unsigned int DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::getMaxCollisions () const inline
Returns the highest number of collisions in the hash table.
Definition at line 793 of file ImageContainerByHashTree.ih.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNbNodes(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myData, and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myKeySize.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInfo(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInternalState().
   {
     unsigned int count = 0;
     unsigned int arraySize = 1 << myKeySize;
     for ( unsigned int i = 0; i < arraySize; ++i )
       {
         if ( myData[i] )
           {
             unsigned int collision = getNbNodes ( i ) - 1;
             if ( collision > count )
               {
                 count = collision;
               }
           }
       }
     return count;
   }
template<typename Domain , typename Value , typename HashKey > unsigned int DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::getNbEmptyLists () const inline
Returns the number of empty places in the hash table.
Definition at line 750 of file ImageContainerByHashTree.ih.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myData, and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myKeySize.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInfo(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInternalState().
   {
     unsigned int count = 0;
     unsigned int arraySize =  1 << myKeySize;
     for ( unsigned int i = 0; i < arraySize; ++i )
       {
         if ( !myData[i] )
           count++;
       }
     return count;
   }
template<typename Domain , typename Value , typename HashKey > unsigned int DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::getNbNodes (unsigned int intermediateKey) const inline
Returns the number of elements for a given key of the hash table.
Parameters
intermediateKey a hashtree key.
Definition at line 711 of file ImageContainerByHashTree.ih.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getNext(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myData.
   {
     if ( !myData[intermediateKey] )
       {
         return 0;
       }
     else
       {
         unsigned int count = 1;
         Node* n = myData[intermediateKey]->getNext();
         while ( n )
           {
             ++count;
             n = n->getNext();
           }
         return count;
       }
   }
template<typename Domain , typename Value , typename HashKey > unsigned int DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::getNbNodes () const inline
Returns the total amount of elements in the container.
Definition at line 735 of file ImageContainerByHashTree.ih.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myKeySize.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getAverageCollisions(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getMaxCollisions(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInfo(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInternalState().
   {
     unsigned int count = 0;
     unsigned int arraySize = 1 << myKeySize;
     for ( unsigned int i = 0; i < arraySize; ++i )
       {
         count += getNbNodes ( i );
       }
     return count;
   }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Node* DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNode (const HashKey key) const inline
Returns a pointer to the node corresponding to the key. If it does'nt exist, returns 0. This method is called VERY often, and thus should operate as fast as possible.
Parameters
key The key.
Returns
the pointer to the node corresponding to the key.
Definition at line 703 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getIntermediateKey(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getKey(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getNext(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myData.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::addNode(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::blendChildren(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::checkIntegrity(), DGtal::Display2DFactory::drawImageRecursive(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printTree().
     {
       Node* iter = myData[getIntermediateKey(key)];
       while (iter != 0)
         {
           if (iter->getKey() == key)
             return iter;
           iter = iter->getNext();
         }
       return 0;
     }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> unsigned int DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getSpanSize () const inline
Returns the size of a dimension (the container represents a line, a square, a cube, etc. depending on the dimmension so no need for distinctions between width, height, ect.)
Returns
the dimension size
Definition at line 370 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::mySpanSize.
Referenced by DGtal::Display2DFactory::drawImageHashTree(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInfo(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInternalState().
     {
       return mySpanSize;
     }
template<typename Domain , typename Value , typename HashKey > bool DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::isKeyValid (HashKey key) const inline
Returns true if the key is valid. A key is valid if the the most important bit that is equal to 1 is at a position of the type dim*k with dim the dimmension of the container (template parameter) and k a strictly positive integer.
Parameters
key the key
Returns
the boolean result
Definition at line 579 of file ImageContainerByHashTree.ih.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getKeyDepth(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myTreeDepth.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::checkIntegrity().
   {
     if ( !key )
       return false;
     if ( getKeyDepth ( key ) > myTreeDepth )
       return false;
     int i = ( sizeof ( HashKey ) << 3 ) - 1;
     for ( ; i >= 0; --i )
       if ( key & ( static_cast<HashKey> ( 1 ) << i ) )
         break;
     if ( i % dim )
       {
         return false;
       }
     return true;
   }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> bool DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::isValid () const inline
Definition at line 565 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::checkIntegrity().
     {
       return checkIntegrity();
     }
template<typename Domain , typename Value , typename HashKey > Value DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::operator() (const HashKey key) const inline
Returns the value at a given key.
Parameters
key the hash key used as an index.
Returns
the value
Definition at line 318 of file ImageContainerByHashTree.ih.
   {
     return get ( key );
   }
template<typename Domain , typename Value , typename HashKey > Value DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::operator() (const Point & aPoint) const inline
Returns the value at a given point.
Parameters
aPoint The point
Returns
the value
Definition at line 324 of file ImageContainerByHashTree.ih.
   {
     return get ( aPoint );
   }
template<typename Domain , typename Value , typename HashKey > void DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::printInfo (std::ostream & out) const inline
Prints informations about the state of the container without displaying the data:
- Nunber of elements in the tree.
- Amount of unused disk space due to blanks in the hash table.
- The dimmension.
- The number of bits of the HashKey.
- The size of the image.
- The average and the maximum amount of collisions.
- The total memory usage.
Parameters
out output stream.
Definition at line 692 of file ImageContainerByHashTree.ih.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getAverageCollisions(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getMaxCollisions(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNbEmptyLists(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNbNodes(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getSpanSize(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myKeySize, and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myTreeDepth.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::selfDisplay().
   {
     unsigned int nbNodes = getNbNodes();
     unsigned int totalSize = sizeof ( *this ) + ( 1 << myKeySize ) * sizeof ( Node* ) + nbNodes * sizeof ( Node );
     out << "[ImageContainerByHashTree]:  Dimension=" << ( int ) dim << ", HashKey size="
         << myKeySize << ", Depth=" << myTreeDepth << ", image size=" << getSpanSize()
         << "^" << ( int ) dim << " (" << std::pow ( ( double ) getSpanSize(), ( double ) dim ) *sizeof ( Value )
         << " bytes)" << ", " << nbNodes << " nodes" << ", Empty lists=" << getNbEmptyLists()
         << " (" << getNbEmptyLists() *sizeof ( Node* ) << " bytes)" << ", Average collisions=" << getAverageCollisions()
         << ", Max collisions " << getMaxCollisions()
         << ", total memory usage=" << totalSize << " bytes" << std::endl;
   }
template<typename Domain , typename Value , typename HashKey > void DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::printInternalState (std::ostream & out, unsigned int nbBits = 0) const inline
Prints the state of the container in a way that displays the hash table and every node as it is stored in memory instead of the usual tree representation.
Parameters
out output stream.
nbBits number of bits
Definition at line 650 of file ImageContainerByHashTree.ih.
References DGtal::Bits::bitString(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getAverageCollisions(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getKey(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getMaxCollisions(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNbEmptyLists(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNbNodes(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getNext(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getObject(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getSpanSize(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myData, DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myDepthMask, DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myKeySize, and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myTreeDepth.
   {
     out << "ImageContainerByHashTree::printInternalState ----------------------------------" << std::endl;
     out << "| <template> dim = " << dim << " myN = " << myN << std::endl;
     out << "| tree depth = " << myTreeDepth << " mask = " << Bits::bitString ( myDepthMask ) << std::endl;
     for ( unsigned int i = 0; i < ( 1 << myKeySize ); ++i )
       {
         out << "| " << Bits::bitString ( i, myKeySize ) << " [";
         if ( myData[i] )
           {
             out << "-]->(";
             if ( nbBits )
               out << Bits::bitString ( myData[i]->getKey(), nbBits ) << ":";
             out << myData[i]->getObject() << ")";
             Node* iter = myData[i]->getNext();
             while ( iter )
               {
                 out << "->(";
                 if ( nbBits )
                   out << Bits::bitString ( myData[i]->getKey(), nbBits ) << ":";
                 out << iter->getObject() << ")";
                 iter = iter->getNext();
               }
             out << std::endl;
           }
         else
           {
             std::cout << "x]" << std::endl;
           }
       }
     out << "| image size: " << getSpanSize() << "^" << dim << " (" << std::pow ( getSpanSize(), dim ) *sizeof ( Value ) << " bytes)" << std::endl;
     out << "| " << getNbNodes() << " nodes - Empty lists: " << getNbEmptyLists() << " (" << getNbEmptyLists() *sizeof ( Node* ) << " bytes)" << std::endl;
     out << "| Average collisions: " << getAverageCollisions() << " - Max collisions " << getMaxCollisions() << std::endl;
     out << "----------------------------------------------------------------" << std::endl;
   }
template<typename Domain , typename Value , typename HashKey > void DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::printState (std::ostream & out, bool displayKeys = false) const inline
Definition at line 606 of file ImageContainerByHashTree.ih.
References DGtal::Bits::bitString(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myDepthMask, DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myTreeDepth, and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printTree().
   {
     out << "ImageContainerByHashTree::printState" << std::endl;
     out << "depth: " << myTreeDepth << " (" << Bits::bitString ( myDepthMask ) << ")" << std::endl;
     out << "dim: " << dim << "myN: " << myN << std::endl;
     printTree ( ROOT_KEY, out, displayKeys );
   }
template<typename Domain , typename Value , typename HashKey > void DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::printTree (HashKey key, std::ostream & out, bool displayKeys) const inline
Prints the sub-tree starting with the node corresponding to key.
Parameters
key root of the subtree to display
out output stream.
displayKeys boolean to decide if keys are displayed .
Definition at line 617 of file ImageContainerByHashTree.ih.
References DGtal::Bits::bitString(), DGtal::Morton< THashKey, TPoint >::childrenKeys(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getKeyDepth(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNode(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getObject(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myMorton, and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myTreeDepth.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printState().
   {
     unsigned int level = getKeyDepth ( key );
     for ( unsigned int i = 0; i < level; ++i )
       out << "  ";
     Node* n = getNode ( key );
     if ( n )
       {
         out << " < " << n->getObject() << " > ";
         if ( displayKeys )
           out << Bits::bitString ( key, 8 );
         out << std::endl;
       }
     else
       {
         out << " < x > ";
         if ( displayKeys )
           out << Bits::bitString ( key, 8 );
         out << std::endl;
       }
     if ( level < myTreeDepth )
       {
         HashKey children[myN];
         myMorton.childrenKeys ( key, children );
         for ( unsigned int i = 0; i < myN; ++i )
           printTree ( children[i], out, displayKeys );
       }
   }
template<typename Domain , typename Value , typename HashKey > ImageContainerByHashTree< Domain, Value, HashKey >::Range DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::range () inline
Returns
an instance of ConstRange used to iterate over the values.
Definition at line 212 of file ImageContainerByHashTree.ih.
   {
     return Range(  *this );
   }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> template<typename C > void DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::recursiveDraw (HashKey key, const double p1[2], const double len, Board2D & board, const C & cmap) const protected
template<typename Domain , typename Value , typename HashKey > void DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::recursiveRemoveNode (HashKey key, unsigned int nbRecursions) inline protected
Recusrively calls RemoveNode on the key and its children.
Parameters
key The key.
nbRecursions the number of recursions performed.
Definition at line 498 of file ImageContainerByHashTree.ih.
References DGtal::Morton< THashKey, TPoint >::childrenKeys(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myMorton, and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::removeNode().
   {
     if ( removeNode ( key ) )
       return;
     if ( --nbRecursions > 0 )
       {
         HashKey children[myN];
         myMorton.childrenKeys ( key, children );
         for ( unsigned int i = 0; i < myN; ++i )
           {
             recursiveRemoveNode ( children[i], nbRecursions );
           }
       }
   }
template<typename Domain , typename Value , typename HashKey > bool DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::removeNode (HashKey key) inline protected
Remove the node corresponding to a key. Returns false if the node doesn't exist.
Parameters
key The key
Definition at line 467 of file ImageContainerByHashTree.ih.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getIntermediateKey(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getKey(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getNext(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myData, and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::setNext().
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::recursiveRemoveNode().
   {
     HashKey key2 = getIntermediateKey ( key );
     Node* iter = myData[key2];
     // if the node is the first in the list we have to modify the pointer stored in myData
     if ( iter && ( iter->getKey() == key ) )
       {
         myData[key2] = iter->getNext();
         delete iter;
         return true;
       }
     while ( iter )
       {
         Node* next = iter->getNext();
         if ( next )
           {
             if ( next->getKey() == key )
               {
                 iter->setNext ( next->getNext() );
                 delete next;
                 return true;
               }
           }
         iter = iter->getNext();
       }
     return false;
   }
template<typename Domain , typename Value , typename HashKey > Value DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::reverseGet (const HashKey key) const inline
A attempt to do the same thing as get(HashKey) but looking for deeper leafs in the first place instead of doing this in the second place. It hasn't show better results so far.
Parameters
key The key.
Returns
the value
Definition at line 350 of file ImageContainerByHashTree.ih.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getObject().
   {
     HashKey iterKey = key;
     // node above the requested node
     HashKey limit = myDepthMask << 1;
     while ( iterKey < limit )
       {
         Node* n = getNode ( iterKey );
         if ( n )
           return blendChildren ( key );
         iterKey <<= dim;
       }
     iterKey = key;
     while ( iterKey != 0 )
       {
         Node* n = getNode ( iterKey );
         if ( n )
           return n->getObject();
         iterKey >>= dim;
       }
     return 0;
   }
template<typename Domain , typename Value , typename HashKey > void DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::selfDisplay (std::ostream & out) inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 901 of file ImageContainerByHashTree.ih.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInfo().
   {
     printInfo ( out );
   }
template<typename Domain , typename Value , typename HashKey > void DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::setDepth (unsigned int depth) inline protected
Set the (maximum) depth of the tree and precompute a mask used for some calculations. The depth of the tree must be known because accessing the data from coordinates depends on it.
Parameters
depth the maxumum depth.
Definition at line 522 of file ImageContainerByHashTree.ih.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myDepthMask, DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::mySpanSize, and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myTreeDepth.
   {
     myTreeDepth = depth;
     mySpanSize = 1 << depth;
     //precompute the mask
     myDepthMask = static_cast<HashKey> ( 1 ) << dim * depth;
   }
template<typename Domain , typename Value , typename HashKey > void DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::setValue (const HashKey key, const Value object) inline
Sets the value of an element in the container, creating it if necessary. In order to keep the tree's coherence this method may add and remove several other nodes in the tree so performances strongly depend on wether or not and how much the tree's structure needs to be modified. For efficiency no check is performed on the key
Parameters
key The key
object The associated object
Definition at line 239 of file ImageContainerByHashTree.ih.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getObject().
   {
     HashKey brothers[myN-1];
     bool broValue = ( key != static_cast<HashKey> ( 1 ) );
     myMorton.brotherKeys ( key, brothers );
     for ( unsigned int i = 0; i < myN - 1; ++ i )
       {
         Node* n = getNode ( brothers[i] );
         if ( ! ( n && ( n->getObject() == value ) ) )
           {
             broValue = false;
             break;
           }
       }
     if ( broValue )
       {
         setValue ( myMorton.parentKey ( key ), value );
         return;
       }
     // if the key already exists
     Node* n = getNode ( key );
     if ( n )
       {
         n->getObject() = value;
         return;
       }
     //if there's a leaf above the requested node
     HashKey iterKey = key;
     std::list< HashKey > nodeList;
     while ( iterKey != 0 )
       {
         //  cerr << "while(iter)..." << std::endl;
         n = getNode ( iterKey );
         if ( n )
           {
             Value tempVal = n->getObject();
             if ( tempVal == value )
               return;
             removeNode ( iterKey );
             for ( typename std::list< HashKey >::iterator  it = nodeList.begin();
                   it != nodeList.end();
                   it++ )
               {
                 //  cerr << "adding a node ("<< bits::bitString(*it, 8)<<")" << std::endl;
                 addNode ( tempVal, *it );
               }
             addNode ( value, key );
             //cerr << "return " << std::endl;
             return;
           }
         else
           {
             //cerr << " + " << std::endl;
             HashKey brothersH[myN-1];
             myMorton.brotherKeys ( iterKey, brothersH );
             for ( unsigned int i = 0; i < myN - 1; ++i )
               {
                 nodeList.push_front ( brothersH[i] );
               }
           }
         iterKey >>= dim;
       }
     addNode ( value, key );
     unsigned int nbRecur = myTreeDepth - getKeyDepth ( key ) + 1;
     HashKey children[myN];
     myMorton.childrenKeys ( key, children );
     for ( unsigned int i = 0; i < myN; ++i )
       recursiveRemoveNode ( children[i], nbRecur );
     return;
   }
template<typename Domain , typename Value , typename HashKey > void DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::setValue (const Point & aPoint, const Value object) inline
Sets the value of an element in the container, creating it if necessary. In order to keep the tree's coherence this method may add and remove several other nodes in the tree so performances strongly depend on wether or not and how much the tree's structure needs to be modified. For efficiency no check is performed on the coordinates
Parameters
aPoint The point
object the associated object
Definition at line 230 of file ImageContainerByHashTree.ih.
   {
     setValue ( getKey ( aPoint ), value );
   }
template<typename Domain , typename Value , typename HashKey > Value DGtal::experimental::ImageContainerByHashTree< Domain, Value, HashKey >::upwardGet (const HashKey key) const inline
Returns the value corresponding to a key making the assumption that the key is at same depth or deeper than the leaf we are looking for.
Parameters
key The key.
Returns
the value.
Definition at line 387 of file ImageContainerByHashTree.ih.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getKey(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getNext(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getObject().
   {
     //cerr << "ImageContainerByHashTree::upWardGet" << std::endl;
     HashKey aKey = key;
     while ( aKey )
       {
         HashKey key2 = getIntermediateKey ( aKey );
         Node* iter = myData[key2];
         while ( iter != 0 )
           {
             if ( iter->getKey() == aKey )
               return iter->getObject();
             iter = iter->getNext();
           }
         aKey >>= dim; // transorm the key to search in an upper level
       }
   }
Field Documentation
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> unsigned int DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myArraySize protected
Definition at line 768 of file ImageContainerByHashTree.h.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::begin(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::end().
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Node** DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myData protected
The array of linked lists containing all the data
Definition at line 759 of file ImageContainerByHashTree.h.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::addNode(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::begin(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::end(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getAverageCollisions(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getMaxCollisions(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNbEmptyLists(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNbNodes(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNode(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInternalState(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::removeNode().
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> int DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myDebugCounter
Definition at line 403 of file ImageContainerByHashTree.h.
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> HashKey DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myDepthMask protected
Precoputed masks to avoid recalculating it all the time
Definition at line 789 of file ImageContainerByHashTree.h.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInternalState(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printState(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::setDepth().
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Domain DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myDomain protected
The image domain
Definition at line 754 of file ImageContainerByHashTree.h.
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> unsigned int DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myKeySize protected
The size of the intermediate hashkey. The bigger the less collisions, but at the same time the more chances to have unused memory allocated.
Definition at line 766 of file ImageContainerByHashTree.h.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getAverageCollisions(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getMaxCollisions(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNbEmptyLists(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNbNodes(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInfo(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInternalState().
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Morton<HashKey, Point> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myMorton
The morton code computer.
Definition at line 794 of file ImageContainerByHashTree.h.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::blendChildren(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::checkIntegrity(), DGtal::Display2DFactory::drawImageRecursive(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printTree(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::recursiveRemoveNode().
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Point DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myOrigin
Definition at line 783 of file ImageContainerByHashTree.h.
Referenced by DGtal::Display2DFactory::drawImageHashTree().
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> HashKey DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myPreComputedIntermediateMask protected
Definition at line 790 of file ImageContainerByHashTree.h.
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> unsigned int DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::mySpanSize protected
Definition at line 775 of file ImageContainerByHashTree.h.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getSpanSize(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::setDepth().
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> unsigned int DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::myTreeDepth protected
The depth of the tree
Definition at line 773 of file ImageContainerByHashTree.h.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::checkIntegrity(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getDepth(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::isKeyValid(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInfo(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInternalState(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printState(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printTree(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::setDepth().
The documentation for this class was generated from the following files:
ImageContainerByHashTree.h
ImageContainerByHashTree.ih