DGtal: DGtal::GaussianCurvatureFunctor3< Matrix3x3 > Class Template Reference
DGtal::GaussianCurvatureFunctor3< Matrix3x3 > Class Template Reference
#include <IntegralInvariantGaussianCurvatureEstimator.h>
Public Types
typedef double Value
typedef EigenValues3D< Value >
::Vector3 Vector3
Public Member Functions
GaussianCurvatureFunctor3 ()
void init (const double &h, const double &r)
Value operator() (const Matrix3x3 &aInput)
Protected Member Functions
void evalk1k2 (Matrix3x3 &matrix, Matrix3x3 &eigenVectors, Vector3 &eigenValues, Value &k1, Value &k2)
Private Attributes
Value dh5
Value d6_PIr6
Value d8_5r
Detailed Description
template<typename Matrix3x3>
class DGtal::GaussianCurvatureFunctor3< Matrix3x3 >
Definition at line 160 of file IntegralInvariantGaussianCurvatureEstimator.h.
Member Typedef Documentation
template<typename Matrix3x3 > typedef double DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::Value
Definition at line 163 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename Matrix3x3 > typedef EigenValues3D< Value >::Vector3 DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::Vector3
Definition at line 164 of file IntegralInvariantGaussianCurvatureEstimator.h.
Constructor & Destructor Documentation
template<typename Matrix3x3 > DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::GaussianCurvatureFunctor3 () inline
Definition at line 166 of file IntegralInvariantGaussianCurvatureEstimator.h.
 {}
Member Function Documentation
template<typename Matrix3x3 > void DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::evalk1k2 (Matrix3x3 & matrix, Matrix3x3 & eigenVectors, Vector3 & eigenValues, Value & k1, Value & k2) inline protected
Definition at line 190 of file IntegralInvariantGaussianCurvatureEstimator.h.
References DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::d6_PIr6, DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::d8_5r, and DGtal::EigenValues3D< TQuantity >::getEigenDecomposition().
Referenced by DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::operator()().
   {
     EigenValues3D< Value >::getEigenDecomposition( matrix, eigenVectors, eigenValues );
     ASSERT ( eigenValues[ 0 ] == eigenValues[ 0 ] ); // NaN
     ASSERT ( (eigenValues[ 0 ] <= eigenValues[ 2 ]) && (eigenValues[ 0 ] <= eigenValues[ 1 ]) && (eigenValues[ 1 ] <= eigenValues[ 2 ]) );
     k1 = d6_PIr6 * ( eigenValues[ 1 ] - ( 3.0 * eigenValues[ 2 ] )) + d8_5r;
     k2 = d6_PIr6 * ( eigenValues[ 2 ] - ( 3.0 * eigenValues[ 1 ] )) + d8_5r;
   }
template<typename Matrix3x3 > void DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::init (const double & h, const double & r) inline
Definition at line 168 of file IntegralInvariantGaussianCurvatureEstimator.h.
References DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::d6_PIr6, DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::d8_5r, and DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::dh5.
   {
     double r3 = r * r * r;
     double r6 = r3 * r3;
     d6_PIr6 = 6.0 / ( M_PI * r6 );
     d8_5r = 8.0 / ( 5.0 * r );
     double h2 = h * h;
     dh5 = h2 * h2 * h;
   }
template<typename Matrix3x3 > Value DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::operator() (const Matrix3x3 & aInput) inline
Definition at line 178 of file IntegralInvariantGaussianCurvatureEstimator.h.
References DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::dh5, and DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::evalk1k2().
   {
     Matrix3x3 cp_matrix = aInput;
     cp_matrix *= dh5;
     Value k1,k2;
     Matrix3x3 eigenVectors;
     Vector3 eigenValues;
     evalk1k2( cp_matrix, eigenVectors, eigenValues, k1, k2 );
     return k1 * k2;
   }
Field Documentation
template<typename Matrix3x3 > Value DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::d6_PIr6 private
h^5
Definition at line 208 of file IntegralInvariantGaussianCurvatureEstimator.h.
Referenced by DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::evalk1k2(), and DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::init().
template<typename Matrix3x3 > Value DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::d8_5r private
6/(PI*r^6)
Definition at line 209 of file IntegralInvariantGaussianCurvatureEstimator.h.
Referenced by DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::evalk1k2(), and DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::init().
template<typename Matrix3x3 > Value DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::dh5 private
Definition at line 207 of file IntegralInvariantGaussianCurvatureEstimator.h.
Referenced by DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::init(), and DGtal::GaussianCurvatureFunctor3< Matrix3x3 >::operator()().
The documentation for this class was generated from the following file:
IntegralInvariantGaussianCurvatureEstimator.h