DGtal: DGtal::Histogram< TQuantity, TBinner > Class Template Reference
DGtal::Histogram< TQuantity, TBinner > Class Template Reference
#include <Histogram.h>
Public Types
enum Formula { SquareRoot, Sturges, Rice, Scott }
typedef TQuantity Quantity
typedef TBinner Binner
typedef Histogram< Quantity,
Binner > Self
typedef Binner::Bin Bin
typedef DGtal::uint64_t Size
typedef std::vector< Size > Container
typedef Container::const_iterator ConstIterator
Public Member Functions
BOOST_CONCEPT_ASSERT ((CEuclideanRing< TQuantity >))
BOOST_CONCEPT_ASSERT ((CBinner< TBinner >))
BOOST_STATIC_ASSERT ((boost::is_same< TQuantity, typename TBinner::Quantity >::value))
~Histogram ()
Histogram ()
void clear ()
void init (Clone< Binner > binner)
void init (Formula formula, const Statistic< Quantity > &stat)
void init (Bin nbBins, const Statistic< Quantity > &stat)
void addValue (Quantity q)
template<typename TInputIterator >
void addValues (TInputIterator it, TInputIterator itE)
void terminate ()
Bin bin (Quantity q) const
Bin size () const
Size area () const
Size nb (Bin b) const
Size accumulation (Bin b) const
double pdf (Bin b) const
double cdf (Bin b) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Protected Attributes
const Binner * myBinner
Container myHistogram
Container myCumulativeHistogram
Private Member Functions
Histogram (const Histogram &other)
Histogram & operator= (const Histogram &other)
void prepare (Bin size)
Detailed Description
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >>
class DGtal::Histogram< TQuantity, TBinner >
Aim: Represents a typical histogram in statistics, which is a discrete estimate of the probability distribution of a continuous variable.
Description of template class 'Histogram'
std::vector<double> v;
...
Statistic<double> stats;
stats.addValues(v.begin(), v.end());
stats.terminate(); // stats are computed.
Histogram<double> hist;
hist.init(Histogram<double>::Scott, stats);
hist.addValues(v.begin(), v.end());
hist.terminate();
// Displays the estimated probability density function
for (unsigned int i = 0; i < hist.size(); ++i)
  std::cout << i << " " << hist.pdf( i ) << std::endl;
Template Parameters
TQuantity any model of CEuclideanRing listed in NumberTraits and that can be castToDouble.
TBinner any model of CBinner that puts a quantity into a bin. Default is RegularBinner<TQuantity>.
Definition at line 146 of file Histogram.h.
Member Typedef Documentation
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >> typedef Binner::Bin DGtal::Histogram< TQuantity, TBinner >::Bin
Definition at line 158 of file Histogram.h.
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >> typedef TBinner DGtal::Histogram< TQuantity, TBinner >::Binner
Definition at line 156 of file Histogram.h.
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >> typedef Container::const_iterator DGtal::Histogram< TQuantity, TBinner >::ConstIterator
Definition at line 161 of file Histogram.h.
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >> typedef std::vector<Size> DGtal::Histogram< TQuantity, TBinner >::Container
Definition at line 160 of file Histogram.h.
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >> typedef TQuantity DGtal::Histogram< TQuantity, TBinner >::Quantity
Definition at line 155 of file Histogram.h.
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >> typedef Histogram< Quantity, Binner > DGtal::Histogram< TQuantity, TBinner >::Self
Definition at line 157 of file Histogram.h.
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >> typedef DGtal::uint64_t DGtal::Histogram< TQuantity, TBinner >::Size
Definition at line 159 of file Histogram.h.
Member Enumeration Documentation
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >> enum DGtal::Histogram::Formula
Determines the number of bins k or the width h as a function of n (number of samples), s (variance of samples).
Enumerator
SquareRoot
Rule is k=sqrt(n)
Sturges
Rule is k=ceil(log_2(n)+1)
Rice
Rule is k=ceil(n^(1/3))
Scott
Rule is h=3.5s/(n^(1/3))
Definition at line 167 of file Histogram.h.
                  { SquareRoot ,
                    Sturges ,
                    Rice ,
                    Scott  };
Constructor & Destructor Documentation
template<typename TQuantity , typename TBinner > DGtal::Histogram< TQuantity, TBinner >::~Histogram () inline
Destructor.
Definition at line 44 of file Histogram.ih.
 {
   if ( myBinner != 0 ) delete myBinner;
 }
template<typename TQuantity , typename TBinner > DGtal::Histogram< TQuantity, TBinner >::Histogram () inline
Constructor. The object is not valid.
Definition at line 51 of file Histogram.ih.
   : myBinner( 0 )
 {
 }
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >> DGtal::Histogram< TQuantity, TBinner >::Histogram (const Histogram< TQuantity, TBinner > & other) private
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
Member Function Documentation
template<typename TQuantity , typename TBinner > DGtal::Histogram< TQuantity, TBinner >::Size DGtal::Histogram< TQuantity, TBinner >::accumulation (Bin b) const inline
Parameters
b any bin in 0 .. size()-1
Returns
the total number of quantities in bins 0 to b (included).
Precondition
terminate() must be called before.
Definition at line 174 of file Histogram.ih.
 {
   ASSERT( b < size() );
   return myCumulativeHistogram[ b ];
 }
template<typename TQuantity , typename TBinner > void DGtal::Histogram< TQuantity, TBinner >::addValue (Quantity q) inline
Add the quantity q to the histogram.
Parameters
q any quantity.
Definition at line 130 of file Histogram.ih.
 {
   ++myHistogram[ bin( q ) ];
 }
template<typename TQuantity , typename TBinner > template<typename TInputIterator > void DGtal::Histogram< TQuantity, TBinner >::addValues (TInputIterator it, TInputIterator itE) inline
Add the quantities stored in range [it,itE) to the histogram.
Template Parameters
TInputIterator any model of boost::InputIterator on Quantity.
Parameters
it an iterator on the first element of the range [it,itE)
itE an iterator after the last element of the range [it,itE)
Definition at line 139 of file Histogram.ih.
 {
   BOOST_CONCEPT_ASSERT(( boost::InputIterator< ConstIterator > ));
   for ( ; it != itE; ++it )
     addValue( *it );
 }
template<typename TQuantity , typename TBinner > DGtal::Histogram< TQuantity, TBinner >::Size DGtal::Histogram< TQuantity, TBinner >::area () const inline
Returns
the total number of samples in the histogram, i.e. the number of added quantities.
Precondition
terminate() must be called before.
Definition at line 157 of file Histogram.ih.
 {
   return myCumulativeHistogram.back();
 }
template<typename TQuantity , typename TBinner > DGtal::Histogram< TQuantity, TBinner >::Bin DGtal::Histogram< TQuantity, TBinner >::bin (Quantity q) const inline
Parameters
q any quantity
Returns
the bin in which quantity q would fall if added to this object.
Definition at line 121 of file Histogram.ih.
 {
   ASSERT( isValid() );
   return (*myBinner)( q );
 }
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >> DGtal::Histogram< TQuantity, TBinner >::BOOST_CONCEPT_ASSERT ((CEuclideanRing< TQuantity >))
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >> DGtal::Histogram< TQuantity, TBinner >::BOOST_CONCEPT_ASSERT ((CBinner< TBinner >))
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >> DGtal::Histogram< TQuantity, TBinner >::BOOST_STATIC_ASSERT ((boost::is_same< TQuantity, typename TBinner::Quantity >::value))
template<typename TQuantity , typename TBinner > double DGtal::Histogram< TQuantity, TBinner >::cdf (Bin b) const inline
Returns
the cumulative distribution function at bin b.
Precondition
terminate() must be called before.
Definition at line 192 of file Histogram.ih.
References DGtal::NumberTraits< T >::castToDouble().
 {
   return NumberTraits<Bin>::castToDouble( accumulation( b ) )
     / NumberTraits<Size>::castToDouble( area() );
 }
template<typename TQuantity , typename TBinner > void DGtal::Histogram< TQuantity, TBinner >::clear () inline
The object is fully cleared. The object must be initialized in order to be valid.
Definition at line 59 of file Histogram.ih.
 {
   if ( myBinner != 0 )
     {
       delete myBinner;
       myBinner = 0;
     }
   myHistogram.clear();
   myCumulativeHistogram.clear();
 }
template<typename TQuantity , typename TBinner > void DGtal::Histogram< TQuantity, TBinner >::init (Clone< Binner > binner) inline
Initialization from Binner. The binner is cloned into this object.
Definition at line 74 of file Histogram.ih.
 {
   clear();
   myBinner = new Binner( binner );
   prepare( myBinner->size() );
 }
template<typename TQuantity , typename TBinner > void DGtal::Histogram< TQuantity, TBinner >::init (Formula formula, const Statistic< Quantity > & stat)
Initialization from a statistic (min, max, samples, variance can typically be used) and a given formula.
< Rule is k=sqrt(n)
< Rule is k=ceil(log_2(n)+1)
< Rule is k=ceil(n^(1/3))
< Rule is h=3.5s/(n^(1/3))
Definition at line 84 of file Histogram.ih.
References DGtal::Statistic< TQuantity >::max(), DGtal::Statistic< TQuantity >::min(), DGtal::Statistic< TQuantity >::samples(), and DGtal::Statistic< TQuantity >::unbiasedVariance().
 {
   clear();
   switch( formula ) {
   case SquareRoot:
     myBinner = new Binner( stat.min(), stat.max(),
                            static_cast<Bin>( ceil( sqrt( stat.samples() ) ) ) );
     break;
   case Sturges:
     myBinner = new Binner( stat.min(), stat.max(),
                            static_cast<Bin>( ceil( log2( stat.samples() ) + 1 ) ) );
     break;
   case Rice:
     myBinner = new Binner( stat.min(), stat.max(),
                            static_cast<Bin>( ceil( pow( stat.samples(), 1.0/3.0 ) ) ) );
     break;
   case Scott:
     double h = 3.5 * stat.unbiasedVariance() / ceil( pow( stat.samples(), 1.0/3.0 ) );
     myBinner = new Binner( stat.min(), stat.max(),
                            static_cast<Bin>( ceil( ( stat.max() - stat.min() ) / h ) ) );
     break;
   }
   if ( myBinner != 0 ) prepare( myBinner->size() );
 }
template<typename TQuantity , typename TBinner > void DGtal::Histogram< TQuantity, TBinner >::init (Bin nbBins, const Statistic< Quantity > & stat)
Initialization from a number of bins and a statistic (min, max, samples, variance can typically be used).
Definition at line 111 of file Histogram.ih.
References DGtal::Statistic< TQuantity >::max(), and DGtal::Statistic< TQuantity >::min().
 {
   clear();
   myBinner = new Binner( stat.min(), stat.max(), nbBins );
   prepare( myBinner->size() );
 }
template<typename TQuantity , typename TBinner > bool DGtal::Histogram< TQuantity, TBinner >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 236 of file Histogram.ih.
 {
   return myBinner != 0;
 }
template<typename TQuantity , typename TBinner > DGtal::Histogram< TQuantity, TBinner >::Size DGtal::Histogram< TQuantity, TBinner >::nb (Bin b) const inline
Parameters
b any bin in 0 .. size()-1
Returns
the number of quantities in bin b.
Definition at line 165 of file Histogram.ih.
 {
   ASSERT( b < size() );
   return myHistogram[ b ];
 }
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >> Histogram& DGtal::Histogram< TQuantity, TBinner >::operator= (const Histogram< TQuantity, TBinner > & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
template<typename TQuantity , typename TBinner > double DGtal::Histogram< TQuantity, TBinner >::pdf (Bin b) const inline
Returns
the probability density function in the whole bin b (constant).
Precondition
terminate() must be called before.
Definition at line 183 of file Histogram.ih.
References DGtal::NumberTraits< T >::castToDouble().
 {
   return NumberTraits<Bin>::castToDouble( nb( b ) )
     / NumberTraits<Size>::castToDouble( area() );
 }
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >> void DGtal::Histogram< TQuantity, TBinner >::prepare (Bin size) inline private
Prepares container for further data.
Definition at line 245 of file Histogram.ih.
 {
   myHistogram.resize( myBinner->size(), 0 );
   myCumulativeHistogram.resize( myBinner->size(), 0 );
 }
template<typename TQuantity , typename TBinner > void DGtal::Histogram< TQuantity, TBinner >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 224 of file Histogram.ih.
 {
   out << "[Histogram size=" << size() << " area=" << area() << "]";
 }
template<typename TQuantity , typename TBinner > DGtal::Histogram< TQuantity, TBinner >::Bin DGtal::Histogram< TQuantity, TBinner >::size () const inline
Returns
the number of bins.
Definition at line 149 of file Histogram.ih.
 {
   return static_cast<Bin>( myHistogram.size() );
 }
template<typename TQuantity , typename TBinner > void DGtal::Histogram< TQuantity, TBinner >::terminate () inline
Should be called when all values have been added.
Definition at line 201 of file Histogram.ih.
 {
   ConstIterator srcIt = myHistogram.begin();
   ConstIterator srcItE = myHistogram.end();
   Bin b = 0;
   myCumulativeHistogram[ b ] = *srcIt++;
   for ( ; srcIt != srcItE; ++srcIt, ++b )
     {
       myCumulativeHistogram[ b+1 ] = myCumulativeHistogram[ b ] + *srcIt;
     }
 }
Field Documentation
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >> const Binner* DGtal::Histogram< TQuantity, TBinner >::myBinner protected
The binner that places quantities into a bin.
Definition at line 286 of file Histogram.h.
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >> Container DGtal::Histogram< TQuantity, TBinner >::myCumulativeHistogram protected
The cumulative histogram data.
Definition at line 290 of file Histogram.h.
template<typename TQuantity, typename TBinner = RegularBinner< TQuantity >> Container DGtal::Histogram< TQuantity, TBinner >::myHistogram protected
The histogram data.
Definition at line 288 of file Histogram.h.
The documentation for this class was generated from the following files:
Histogram.h
Histogram.ih