DGtal: DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 > Class Template Reference
DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 > Class Template Reference
#include <IntegralInvariantGaussianCurvatureEstimator.h>
Public Types
typedef TKSpace KSpace
typedef Z2i::Domain Domain
typedef KSpace::Space::RealPoint RealPoint
typedef Z2i::DigitalSet DigitalSet
typedef KSpace::SCell Spel
typedef KSpace::SurfelSet SurfelSet
typedef SurfelSet::const_iterator ConstIteratorKernel
typedef int Value
typedef TShapeFunctor ShapeSpelFunctor
typedef ConstValueCellFunctor
< Value, Spel > KernelSpelFunctor
typedef ImplicitBall< Z2i::Space > KernelSupport
typedef EuclideanShapesMinus
< KernelSupport, KernelSupport > EuclideanMinus
typedef GaussDigitizer
< Z2i::Space, KernelSupport > DigitalShapeKernel
typedef GaussDigitizer
< Z2i::Space, EuclideanMinus > DigitalShape
typedef
DigitalSurfaceConvolver
< ShapeSpelFunctor,
KernelSpelFunctor, KSpace,
DigitalShapeKernel > Convolver
typedef Convolver::CovarianceMatrix Matrix2x2
typedef
GaussianCurvatureFunctor2
< Matrix2x2 > ValuesFunctor
typedef
PrincipalCurvatureFunctor2
< Matrix2x2 > PrincipalCurvatureFunctor
typedef ValuesFunctor::Value Quantity
typedef
PrincipalCurvatureFunctor::Value PrincipalCurvatures
typedef Convolver::PairIterators PairIterators
Public Member Functions
BOOST_CONCEPT_ASSERT ((CCellFunctor< ShapeSpelFunctor >))
IntegralInvariantGaussianCurvatureEstimator (ConstAlias< KSpace > space, ConstAlias< ShapeSpelFunctor > f)
~IntegralInvariantGaussianCurvatureEstimator ()
void init (const double _h, const double re)
template<typename SurfelIterator >
Quantity eval (const SurfelIterator &it)
template<typename SurfelIterator , typename OutputIterator >
void eval (const SurfelIterator &itb, const SurfelIterator &ite, OutputIterator &result)
template<typename SurfelIterator >
PrincipalCurvatures evalPrincipalCurvatures (const SurfelIterator &it)
template<typename SurfelIterator , typename OutputIterator >
void evalPrincipalCurvatures (const SurfelIterator &itb, const SurfelIterator &ite, OutputIterator &result)
void selfDisplay (std::ostream &out) const
bool isValid () const
template<typename SurfelIterator >
DGtal::IntegralInvariantGaussianCurvatureEstimator
< TKSpace, TShapeFunctor, 2 >
::Quantity eval (const SurfelIterator &it)
template<typename SurfelIterator >
DGtal::IntegralInvariantGaussianCurvatureEstimator
< TKSpace, TShapeFunctor, 2 >
::PrincipalCurvatures evalPrincipalCurvatures (const SurfelIterator &it)
Private Member Functions
IntegralInvariantGaussianCurvatureEstimator (const IntegralInvariantGaussianCurvatureEstimator &other)
IntegralInvariantGaussianCurvatureEstimator & operator= (const IntegralInvariantGaussianCurvatureEstimator &other)
Private Attributes
std::vector< PairIterators > kernels
std::vector< DigitalSet * > kernelsSet
KernelSupport * kernel
DigitalShapeKernel * digKernel
const KernelSpelFunctor myKernelFunctor
Convolver myConvolver
double h
double radius
ValuesFunctor gaussFunctor
PrincipalCurvatureFunctor princCurvFunctor
Detailed Description
template<typename TKSpace, typename TShapeFunctor>
class DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >
Specialization for dimension = 2
Definition at line 492 of file IntegralInvariantGaussianCurvatureEstimator.h.
Member Typedef Documentation
template<typename TKSpace , typename TShapeFunctor > typedef SurfelSet::const_iterator DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::ConstIteratorKernel
Definition at line 501 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef DigitalSurfaceConvolver<ShapeSpelFunctor, KernelSpelFunctor, KSpace, DigitalShapeKernel> DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::Convolver
Definition at line 512 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef Z2i::DigitalSet DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::DigitalSet
Definition at line 498 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef GaussDigitizer< Z2i::Space, EuclideanMinus > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::DigitalShape
Definition at line 510 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef GaussDigitizer< Z2i::Space, KernelSupport > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::DigitalShapeKernel
Definition at line 509 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef Z2i::Domain DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::Domain
Definition at line 496 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef EuclideanShapesMinus< KernelSupport, KernelSupport > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::EuclideanMinus
Definition at line 508 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef ConstValueCellFunctor<Value, Spel> DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::KernelSpelFunctor
Definition at line 506 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef ImplicitBall<Z2i::Space> DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::KernelSupport
Definition at line 507 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef TKSpace DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::KSpace
Definition at line 495 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef Convolver::CovarianceMatrix DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::Matrix2x2
Definition at line 514 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef Convolver::PairIterators DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::PairIterators
Definition at line 522 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef PrincipalCurvatureFunctor2< Matrix2x2 > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::PrincipalCurvatureFunctor
Definition at line 517 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef PrincipalCurvatureFunctor::Value DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::PrincipalCurvatures
Definition at line 520 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef ValuesFunctor::Value DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::Quantity
Definition at line 519 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef KSpace::Space::RealPoint DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::RealPoint
Definition at line 497 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef TShapeFunctor DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::ShapeSpelFunctor
Definition at line 505 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef KSpace::SCell DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::Spel
Definition at line 499 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef KSpace::SurfelSet DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::SurfelSet
Definition at line 500 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef int DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::Value
Definition at line 503 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > typedef GaussianCurvatureFunctor2< Matrix2x2 > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::ValuesFunctor
Definition at line 516 of file IntegralInvariantGaussianCurvatureEstimator.h.
Constructor & Destructor Documentation
template<typename TKSpace , typename TShapeFunctor > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::IntegralInvariantGaussianCurvatureEstimator (ConstAlias< KSpace > space, ConstAlias< ShapeSpelFunctor > f) inline
Constructor.
Parameters
space space in which the shape is defined.
f functor on spel of the shape.
Definition at line 51 of file IntegralInvariantGaussianCurvatureEstimator.ih.
     : myKernelFunctor(NumberTraits<Quantity>::ONE),
       myConvolver(shapeFunctor, myKernelFunctor, space)
 {}
template<typename TKSpace , typename TShapeFunctor > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::~IntegralInvariantGaussianCurvatureEstimator () inline
Destructor.
Definition at line 539 of file IntegralInvariantGaussianCurvatureEstimator.h.
References DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::digKernel, DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::kernel, and DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::kernelsSet.
   {
     for( unsigned int i = 0; i < kernelsSet.size(); ++i )
     {
       delete kernelsSet[ i ];
     }
     kernelsSet.clear();
     delete kernel;
     delete digKernel;
   }
template<typename TKSpace , typename TShapeFunctor > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::IntegralInvariantGaussianCurvatureEstimator (const IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 > & other) private
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
Member Function Documentation
template<typename TKSpace , typename TShapeFunctor > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::BOOST_CONCEPT_ASSERT ((CCellFunctor< ShapeSpelFunctor >))
template<typename TKSpace , typename TShapeFunctor > template<typename SurfelIterator > DGtal::IntegralInvariantGaussianCurvatureEstimator<TKSpace, TShapeFunctor, 2>::Quantity DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::eval (const SurfelIterator & it) inline
Definition at line 215 of file IntegralInvariantGaussianCurvatureEstimator.ih.
 {
     Quantity measure = myConvolver.eval( it );
     return gaussFunctor( measure );
 }
template<typename TKSpace , typename TShapeFunctor > template<typename SurfelIterator > Quantity DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::eval (const SurfelIterator & it)
– Gaussian curvature – Compute the integral invariant Gaussian curvature at surfel *it of a shape.
Template Parameters
SurfelIterator type of Iterator on a Surfel
Parameters
[in] it iterator of a surfel (from a shape) we want compute the integral invariant Gaussian curvature.
Returns
quantity (Gaussian curvature) at position *it
template<typename TKSpace , typename TShapeFunctor > template<typename SurfelIterator , typename OutputIterator > void DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::eval (const SurfelIterator & itb, const SurfelIterator & ite, OutputIterator & result) inline
– Gaussian curvature – Compute the integral invariant Gaussian curvature from two surfels (from *itb to *ite (exclude)) of a shape. Return the result on an OutputIterator (param).
Template Parameters
SurfelIterator type of Iterator on a Surfel
OutputIterator type of Iterator of a list of Quantity
Parameters
[in] ite iterator of the begin surfel on the shape we want compute the integral invariant Gaussian curvature.
[in] itb iterator of the end surfel (excluded) on the shape we want compute the integral invariant Gaussiaan curvature.
[out] result iterator of results of the computation.
Definition at line 248 of file IntegralInvariantGaussianCurvatureEstimator.ih.
 {
     myConvolver.eval( itb, ite, result, gaussFunctor );
 }
template<typename TKSpace , typename TShapeFunctor > template<typename SurfelIterator > DGtal::IntegralInvariantGaussianCurvatureEstimator<TKSpace, TShapeFunctor, 2>::PrincipalCurvatures DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::evalPrincipalCurvatures (const SurfelIterator & it) inline
Definition at line 284 of file IntegralInvariantGaussianCurvatureEstimator.ih.
References DGtal::Trace::error(), and DGtal::trace.
 {
     PrincipalCurvatures measure;
     trace.error() << "IntegralInvariantGaussianCurvatureEstimator@eval() : Not available yet.";
     return measure;
 }
template<typename TKSpace , typename TShapeFunctor > template<typename SurfelIterator > PrincipalCurvatures DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::evalPrincipalCurvatures (const SurfelIterator & it)
– Principal curvatures – Compute the integral invariant Gaussian curvature on surfel *it of a shape.
Template Parameters
SurfelIterator iterator on a Surfel
Parameters
[in] it iterator of a surfel (from a shape) we want compute the integral invariant principal curvatures.
Returns
a struct with principal curvatures value of Integral Invariant estimator at surfel *it, and eigenVectors and eigenValues resulting of the covariance matrix (see above: struct CurvatureInformations)
template<typename TKSpace , typename TShapeFunctor > template<typename SurfelIterator , typename OutputIterator > void DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::evalPrincipalCurvatures (const SurfelIterator & itb, const SurfelIterator & ite, OutputIterator & result) inline
– Principal curvatures – Compute the integral invariant Gaussian curvature from two surfels (from *itb to *ite (exclude)) of a shape. Return the result on an OutputIterator (param).
Template Parameters
SurfelIterator iterator on a Surfel
OutputIterator iterator of array of PrincipalCurvatures
Parameters
[in] ite iterator of the begin surfel on the shape where we compute the integral invariant principal curvatures.
[in] itb iterator of the end surfel (excluded) on the shape where we compute the integral invariant principal curvatures.
[out] result iterator of structs with principal curvatures value of Integral Invariant estimator at surfel *it, and eigenVectors and eigenValues resulting of the covariance matrix (see above: struct CurvatureInformations)
Definition at line 319 of file IntegralInvariantGaussianCurvatureEstimator.ih.
References DGtal::Trace::error(), and DGtal::trace.
 {
     trace.error() << "IntegralInvariantGaussianCurvatureEstimator@eval() : Not available yet.";
     return;
 }
template<typename TKSpace , typename TShapeFunctor > void DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::init (const double _h, const double re) inline
Initialise the estimator with a specific Euclidean kernel radius re, and grid step _h.
Parameters
[in] _h precision of the grid
[in] re Euclidean radius of the kernel support
Computation of shifting masks
End of computation of masks
Definition at line 79 of file IntegralInvariantGaussianCurvatureEstimator.ih.
References DGtal::GaussDigitizer< TSpace, TEuclideanShape >::attach(), DGtal::Shapes< TDomain >::digitalShaper(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getDomain(), and DGtal::GaussDigitizer< TSpace, TEuclideanShape >::init().
 {
     h = _h;
     radius = re;
     gaussFunctor.init( h, radius );
     princCurvFunctor.init( h, radius );
     RealPoint rOrigin = RealPoint ( 0.0, 0.0 );
     Domain::Point pOrigin = Domain::Point( 0, 0 );
     kernel = new KernelSupport( rOrigin, radius );
     digKernel = new DigitalShapeKernel();
     digKernel->attach( *kernel );
     digKernel->init( kernel->getLowerBound(), kernel->getUpperBound(), RealPoint( h, h ) );
     kernels = std::vector< PairIterators > ( 9 );
     kernelsSet = std::vector< DigitalSet* >( 9 );
     for( int y = -1; y <= 1; ++y )
     {
         for( int x = -1; x <= 1; ++x )
         {
             unsigned int offset = ( x + 1 ) + (( y + 1 ) * 3 );
             if( offset == 4 ) // Full kernel, already done
             {
                 continue;
             }
             else
             {
                 RealPoint shiftPoint = rOrigin + RealPoint( x * h , y * h );
                 KernelSupport * kernelShifted = new KernelSupport( shiftPoint, radius );
                 EuclideanMinus * current = new EuclideanMinus( *kernel, *kernelShifted );
                 DigitalShape digCurrent;
                 digCurrent.attach( *current );
                 digCurrent.init( kernel->getLowerBound(), kernel->getUpperBound(), h );
                 kernelsSet[ offset ] = new DigitalSet( digCurrent.getDomain() );
                 Shapes< Domain>::digitalShaper ( *(kernelsSet[ offset ]), digCurrent );
                 kernels[ offset ].first = kernelsSet[ offset ]->begin();
                 kernels[ offset ].second = kernelsSet[ offset ]->end();
                 delete current;
                 delete kernelShifted;
             }
         }
     }
     myConvolver.init( pOrigin, digKernel, kernels );
 }
template<typename TKSpace , typename TShapeFunctor > bool DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 381 of file IntegralInvariantGaussianCurvatureEstimator.ih.
 {
     return true;
 }
template<typename TKSpace , typename TShapeFunctor > IntegralInvariantGaussianCurvatureEstimator& DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::operator= (const IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 > & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
template<typename TKSpace , typename TShapeFunctor > void DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 352 of file IntegralInvariantGaussianCurvatureEstimator.ih.
 {
     out << "[IntegralInvariantGaussianCurvatureEstimator]";
 }
Field Documentation
template<typename TKSpace , typename TShapeFunctor > DigitalShapeKernel* DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::digKernel private
Digital kernel.
Definition at line 646 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > ValuesFunctor DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::gaussFunctor private
Functor to transform covarianceMatrix to Quantity/PrincipalCurvatures.
Definition at line 656 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > double DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::h private
precision of the grid
Definition at line 652 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > KernelSupport* DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::kernel private
Euclidean kernel.
Definition at line 644 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > std::vector< PairIterators > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::kernels private
array of begin/end iterator of shifting masks.
Definition at line 640 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > std::vector< DigitalSet * > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::kernelsSet private
Array of shifting masks. Size = 9 for each shifting (0-adjacent and full kernel included)
Definition at line 642 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > Convolver DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::myConvolver private
Convolver.
Definition at line 650 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > const KernelSpelFunctor DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::myKernelFunctor private
Kernel functor (on Spel)
Definition at line 648 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > PrincipalCurvatureFunctor DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::princCurvFunctor private
Definition at line 657 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace , typename TShapeFunctor > double DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::radius private
Euclidean radius of the kernel.
Definition at line 654 of file IntegralInvariantGaussianCurvatureEstimator.h.
The documentation for this class was generated from the following files:
IntegralInvariantGaussianCurvatureEstimator.h
IntegralInvariantGaussianCurvatureEstimator.ih