DGtal: DGtal::ColorBrightnessColorMap< PValue, PDefaultColor > Class Template Reference
DGtal::ColorBrightnessColorMap< PValue, PDefaultColor > Class Template Reference
#include <ColorBrightnessColorMap.h>
Public Types
typedef PValue Value
Public Member Functions
ColorBrightnessColorMap (const PValue &min, const PValue &max, const Color color=Color(DGTAL_RED_COMPONENT(PDefaultColor), DGTAL_GREEN_COMPONENT(PDefaultColor), DGTAL_BLUE_COMPONENT(PDefaultColor)))
Color operator() (const PValue &value) const
~ColorBrightnessColorMap ()
ColorBrightnessColorMap (const ColorBrightnessColorMap &other)
ColorBrightnessColorMap & operator= (const ColorBrightnessColorMap &other)
void selfDisplay (std::ostream &out) const
bool isValid () const
const PValue & min () const
const PValue & max () const
Static Public Member Functions
static Color getColor (const Color color, const PValue &min, const PValue &max, const PValue &value)
Protected Member Functions
ColorBrightnessColorMap ()
Protected Attributes
PValue myMin
PValue myMax
Color myColor
Static Private Member Functions
static void HSVtoRGB (double &r, double &g, double &b, double h, const double s, const double v)
static void RGBtoHSV (double &h, double &s, double &v, const unsigned char r, const unsigned char g, const unsigned char b)
Detailed Description
template<typename PValue, int PDefaultColor = DGTAL_RGB2INT(255, 255, 255)>
class DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >
Aim: This class template may be used to (linearly) convert scalar values in a given range into a color with given lightness.
Description of template class 'ColorBrightnessColorMap'
The ColorBrightnessColorMap can be used either as a functor object (the value range is given at the object's construction, together with the reference color) which converts a value into a LibBoard::Color structure, or it can be used through a static method taking both the range and the value as parameters.
The code below shows a possible use of this class.
* #include "DGtal/io/Color.h"
* #include "ColorBrightnessColorMap.h"
* // ...
* {
*   ColorBrightnessColorMap<float> blueShade(0.0f,1.0f,Color::Blue);
*   Color red = blueShade(1.0f);
*   Color blue1 = blueShade(0.5f);
*   // Or, equivalently:
*   Color blue2 = ColorBrightnessColorMap<float>::getColor(Color::Blue,0.0f,1.0f,0.5f);
* }
*
Template Parameters
PValue The type of the range values.
PDefaultColor The default color as an integer built using the DGTAL_RGB2INT macro.
Definition at line 89 of file ColorBrightnessColorMap.h.
Member Typedef Documentation
template<typename PValue, int PDefaultColor = DGTAL_RGB2INT(255, 255, 255)> typedef PValue DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::Value
Definition at line 93 of file ColorBrightnessColorMap.h.
Constructor & Destructor Documentation
template<typename PValue , int PDefaultColor> DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::ColorBrightnessColorMap (const PValue & min, const PValue & max, const Color color = Color(DGTAL_RED_COMPONENT(PDefaultColor), DGTAL_GREEN_COMPONENT(PDefaultColor), DGTAL_BLUE_COMPONENT(PDefaultColor))) inline
Constructor.
Parameters
min The lower bound of the value range.
max The upper bound of the value range.
Definition at line 45 of file ColorBrightnessColorMap.ih.
   : myMin( minV ), myMax( maxV ), myColor( color )
 { }
template<typename PValue , int PDefaultColor> DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::~ColorBrightnessColorMap () inline
Destructor.
Definition at line 60 of file ColorBrightnessColorMap.ih.
 {
 }
template<typename PValue , int PDefaultColor> DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::ColorBrightnessColorMap (const ColorBrightnessColorMap< PValue, PDefaultColor > & other) inline
Copy constructor.
Parameters
other the object to clone.
Definition at line 53 of file ColorBrightnessColorMap.ih.
   : myMin( other.myMin ), myMax( other.myMax ), myColor( other.myColor )
 {
 }
template<typename PValue, int PDefaultColor = DGTAL_RGB2INT(255, 255, 255)> DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::ColorBrightnessColorMap () protected
Constructor. Forbidden by default (protected to avoid g++ warnings).
Member Function Documentation
template<typename PValue , int PDefaultColor> DGtal::Color DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::getColor (const Color color, const PValue & min, const PValue & max, const PValue & value) inline static
Computes the color associated with a value in a given range.
Parameters
color The color associated with the upper bound.
min The lower bound of the value range.
max The upper bound of the value range.
value A value within the value range.
Returns
A color whose brightness linearly depends on the position of [value] within the range [min]..[max].
Definition at line 138 of file ColorBrightnessColorMap.ih.
References DGtal::Color::blue(), DGtal::Color::green(), and DGtal::Color::red().
 {
   double h=0.0,s,v;
   ColorBrightnessColorMap<PValue,PDefaultColor>::RGBtoHSV( h, s, v,
             color.red(),
             color.green(),
             color.blue() );
   const double range = static_cast<double>( max - min );
   const double scale = static_cast<double>( value - min ) / range;
   double red, green, blue;
   ColorBrightnessColorMap<PValue,PDefaultColor>::HSVtoRGB( red, green, blue, h, s, v * scale );
   return DGtal::Color( static_cast<int>( red * 255),
         static_cast<int>( green * 255),
         static_cast<int>( blue * 255) );
 }
template<typename PValue , int PDefaultColor> void DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::HSVtoRGB (double & r, double & g, double & b, double h, const double s, const double v) inline static private
Converts a color from the HSV (Hue,Saturation,Value) space to the RGB space.
Parameters
r The red component (out).
g The green component (out).
b The blue component (out).
h The hue of the color in [0..360)
s The saturation of the color in [0..1].
v The value of the color in [0..1].
Definition at line 181 of file ColorBrightnessColorMap.ih.
 {
   int i;
   double f, p, q, t;
   if( s == 0 ) {                     // achromatic (gray)
     r = g = b = v;
     return;
   }
   i = static_cast<int>( floor( h / 60 ) );
   f = ( h / 60 ) - i;                        // factorial part of h
   p = v * ( 1 - s );
   q = v * ( 1 - s * f );
   t = v * ( 1 - s * ( 1 - f ) );
   switch( i ) {
   case 0:
     r = v; g = t; b = p;
     break;
   case 1:
     r = q; g = v; b = p;
     break;
   case 2:
     r = p; g = v; b = t;
     break;
    case 3:
      r = p; g = q; b = v;
      break;
   case 4:
     r = t;  g = p; b = v;
     break;
   default:    // case 5:
     r = v; g = p; b = q;
     break;
   }
 }
template<typename PValue , int PDefaultColor> bool DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 130 of file ColorBrightnessColorMap.ih.
 {
     return true;
 }
template<typename PValue , int PDefaultColor> const PValue & DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::max () const inline
Returns the upper bound of the value range.
Returns
The upper bound of the value range.
Definition at line 91 of file ColorBrightnessColorMap.ih.
 {
   return myMax;
 }
template<typename PValue , int PDefaultColor> const PValue & DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::min () const inline
Returns the lower bound of the value range.
Returns
The lower bound of the value range.
Definition at line 83 of file ColorBrightnessColorMap.ih.
 {
   return myMin;
 }
template<typename PValue , int PDefaultColor> DGtal::Color DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::operator() (const PValue & value) const inline
Computes the color associated with a value in a given range.
Parameters
value A value within the value range.
Returns
A color whose brightness linearly depends on the position of [value] within the current range.
Definition at line 99 of file ColorBrightnessColorMap.ih.
 {
   return ColorBrightnessColorMap<PValue,PDefaultColor>::getColor( myColor, myMin, myMax, value );
 }
template<typename PValue , int PDefaultColor> DGtal::ColorBrightnessColorMap< PValue, PDefaultColor > & DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::operator= (const ColorBrightnessColorMap< PValue, PDefaultColor > & other)
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'.
Definition at line 67 of file ColorBrightnessColorMap.ih.
References DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::myColor, DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::myMax, and DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::myMin.
 {
   if ( &other != this ) {
     myMin = other.myMin;
     myMax = other.myMax;
     myColor = other.myColor;
   }
   return *this;
 }
template<typename PValue , int PDefaultColor> void DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::RGBtoHSV (double & h, double & s, double & v, const unsigned char r, const unsigned char g, const unsigned char b) inline static private
Converts a color from the RGB space to the HSV (Hue,Saturation,Value) space.
Parameters
h (out) The hue of the color in [0..360)
s (out) The saturation of the color in [0..1].
v (out) The value of the color in [0..1].
r The red component.
g The green component.
b The blue component.
Definition at line 221 of file ColorBrightnessColorMap.ih.
 {
   double min = (r<g) ? r : g;
   if ( b < min ) min = b;
   unsigned char max = (r>g) ? r : g;
   if ( b > max ) max = b;
   double dr = r / 255.0;
   double dg = g / 255.0;
   double db = b / 255.0;
   v = max / 255.0; // (0.3*dr + 0.59*dg + 0.11*db);
   if ( max == min ) {
     h = 0;
     s = 0;
     return;
   } else {
     double diff = ( max - min ) / 255.0;
     if ( max == r ) {
       h = (dg - db ) / diff;
     } else if ( max == g ) {
       h = 2.0 + ( ( db - dr ) / diff );
     } else if ( max == b ) {
       h = 4.0 + ( ( dr - dg ) / diff );
     }
     h *= 60.0;
     if ( h < 0 ) h += 360;
     s = diff / v;
   }
 }
template<typename PValue , int PDefaultColor> void DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 111 of file ColorBrightnessColorMap.ih.
 {
   out << "[ColorBrightnessColorMap "
       << " min=" << myMin
       << " max=" << myMax
       << " color=("
       << myColor.red() << ","
       << myColor.green() << ","
       << myColor.blue() << ") "
       << " ]";
 }
Field Documentation
template<typename PValue, int PDefaultColor = DGTAL_RGB2INT(255, 255, 255)> Color DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::myColor protected
The color of the upper bound value.
Definition at line 196 of file ColorBrightnessColorMap.h.
Referenced by DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::operator=().
template<typename PValue, int PDefaultColor = DGTAL_RGB2INT(255, 255, 255)> PValue DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::myMax protected
The lower bound of the value range.
Definition at line 195 of file ColorBrightnessColorMap.h.
Referenced by DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::operator=().
template<typename PValue, int PDefaultColor = DGTAL_RGB2INT(255, 255, 255)> PValue DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::myMin protected
The lower bound of the value range.
Definition at line 194 of file ColorBrightnessColorMap.h.
Referenced by DGtal::ColorBrightnessColorMap< PValue, PDefaultColor >::operator=().
The documentation for this class was generated from the following files:
ColorBrightnessColorMap.h
ColorBrightnessColorMap.ih