DGtal: DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate > Class Template Reference
DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate > Class Template Reference
#include <LightExplicitDigitalSurface.h>
Data Structures
class Tracker
struct VertexMap
Public Types
typedef
LightExplicitDigitalSurface
< TKSpace, TSurfelPredicate > Self
typedef TKSpace KSpace
typedef KSpace::SCell Surfel
typedef KSpace::Size Size
typedef TSurfelPredicate SurfelPredicate
typedef SurfelAdjacency
< KSpace::dimension > Adjacency
typedef KSpace::Cell Cell
typedef KSpace::SCell SCell
typedef KSpace::CellSet CellSet
typedef KSpace::SCellSet SCellSet
typedef Surfel Vertex
typedef SCellSet VertexSet
typedef BreadthFirstVisitor< Self > SelfVisitor
typedef GraphVisitorRange
< SelfVisitor > SelfVisitorRange
typedef
SelfVisitorRange::ConstIterator SurfelConstIterator
typedef KSpace::Space Space
typedef KSpace::Point Point
typedef Tracker DigitalSurfaceTracker
Public Member Functions
BOOST_CONCEPT_ASSERT ((CSurfelPredicate< SurfelPredicate >))
~LightExplicitDigitalSurface ()
LightExplicitDigitalSurface (const LightExplicitDigitalSurface &other)
LightExplicitDigitalSurface (const KSpace &aKSpace, const SurfelPredicate &aSP, const Adjacency &adj, const Surfel &s)
const Adjacency & surfelAdjacency () const
Adjacency & surfelAdjacency ()
const SurfelPredicate & surfelPredicate () const
const Surfel & surfel () const
void setSurfel (const Surfel &aSurfel)
const KSpace & space () const
bool isInside (const Surfel &s) const
SurfelConstIterator begin () const
SurfelConstIterator end () const
Size nbSurfels () const
bool empty () const
DigitalSurfaceTracker * newTracker (const Surfel &s) const
Connectedness connectedness () const
Size degree (const Vertex &v) const
template<typename OutputIterator >
void writeNeighbors (OutputIterator &it, const Vertex &v) const
template<typename OutputIterator , typename VertexPredicate >
void writeNeighbors (OutputIterator &it, const Vertex &v, const VertexPredicate &pred) const
Size bestCapacity () const
void selfDisplay (std::ostream &out) const
bool isValid () const
Private Member Functions
LightExplicitDigitalSurface & operator= (const LightExplicitDigitalSurface &other)
Private Attributes
const KSpace & myKSpace
const SurfelPredicate & mySurfelPredicate
Adjacency mySurfelAdjacency
Surfel mySurfel
Tracker myTracker
Detailed Description
template<typename TKSpace, typename TSurfelPredicate>
class DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >
Aim: A model of CDigitalSurfaceContainer which defines the digital surface as connected surfels. The shape is determined by a predicate telling whether a given surfel belongs or not to the shape boundary. The whole boundary is not precomputed nor stored. You may use an iterator to visit it.
Description of template class 'LightExplicitDigitalSurface'
It is also a model of CUndirectedSimpleLocalGraph, so as to be able to visit itself with a BreadthFirstVisitor. The "Light" or lazyness is implemented this way.
Template Parameters
TKSpace a model of CCellularGridSpaceND: the type chosen for the cellular grid space.
TSurfelPredicate a model of CSurfelPredicate: this functor defines the digital surface as a characteristic function returning true iff the surfel belongs to it.
Remarks
Being a CDigitalSurfaceContainer, it is a model of CConstSinglePassRange, but it is not a model of CConstBidirectionalRange. For instance, if you wish to do an algorithm like: for all vertex x, for all vertex y, compute something, then the following code will not work:
// This snippet does NOT work.
const SurfelConstIterator itb = mySurface.begin();
const SurfelConstIterator ite = mySurface.end();
for (SurfelConstIterator itX = itb; itX != ite; ++itX)
{
  for ( SurfelConstIterator itY = itb; itY != ite; ++itY )
  { // compute something with *itX and *itY.
    // But itX == itY at each step ! }
  // now itX == itY == ite !
  }
You may use this range only once ! This is because the iterators are only single pass. If you wish to visit twice the range, you must indeed creates two ranges by calling begin() twice (end() is not compulsory here, but advised).
// This snippet does ALWAYS work.
for (SurfelConstIterator itX = mySurface.begin(),
                          itXEnd = mySurface.end();
      itX != itXEnd; ++itX )
{
  for ( SurfelConstIterator itY = mySurface.begin(),
                            itYEnd = mySurface.end();
        itY != itYEnd; ++itY )
    { // compute something with *itX and *itY. }
}
Definition at line 117 of file LightExplicitDigitalSurface.h.
Member Typedef Documentation
template<typename TKSpace, typename TSurfelPredicate> typedef SurfelAdjacency<KSpace::dimension> DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Adjacency
Definition at line 216 of file LightExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef KSpace::Cell DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Cell
Definition at line 217 of file LightExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef KSpace::CellSet DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::CellSet
Definition at line 219 of file LightExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef Tracker DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::DigitalSurfaceTracker
Definition at line 237 of file LightExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef TKSpace DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::KSpace
Model of cellular grid space.
Definition at line 203 of file LightExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef KSpace::Point DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Point
Definition at line 236 of file LightExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef KSpace::SCell DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::SCell
Definition at line 218 of file LightExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef KSpace::SCellSet DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::SCellSet
Definition at line 220 of file LightExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef LightExplicitDigitalSurface<TKSpace,TSurfelPredicate> DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Self
Definition at line 201 of file LightExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef BreadthFirstVisitor< Self > DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::SelfVisitor
Definition at line 232 of file LightExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef GraphVisitorRange< SelfVisitor > DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::SelfVisitorRange
Definition at line 233 of file LightExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef KSpace::Size DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Size
Type for sizes (unsigned integral type).
Definition at line 207 of file LightExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef KSpace::Space DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Space
Definition at line 235 of file LightExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef KSpace::SCell DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Surfel
Type for surfels.
Definition at line 205 of file LightExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef SelfVisitorRange::ConstIterator DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::SurfelConstIterator
Definition at line 234 of file LightExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef TSurfelPredicate DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::SurfelPredicate
Definition at line 209 of file LightExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef Surfel DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Vertex
Definition at line 224 of file LightExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef SCellSet DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::VertexSet
Definition at line 225 of file LightExplicitDigitalSurface.h.
Constructor & Destructor Documentation
template<typename TKSpace , typename TSurfelPredicate > DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::~LightExplicitDigitalSurface () inline
Destructor.
Definition at line 124 of file LightExplicitDigitalSurface.ih.
 {
 }
template<typename TKSpace , typename TSurfelPredicate > DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::LightExplicitDigitalSurface (const LightExplicitDigitalSurface< TKSpace, TSurfelPredicate > & other) inline
Copy constructor.
Parameters
other the object to clone.
Definition at line 131 of file LightExplicitDigitalSurface.ih.
   : myKSpace( other.myKSpace ),
     mySurfelPredicate( other.mySurfelPredicate ),
     mySurfelAdjacency( other.mySurfelAdjacency ),
     mySurfel( other.mySurfel ),
     myTracker( *this, other.mySurfel )
 {
 }
template<typename TKSpace , typename TSurfelPredicate > DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::LightExplicitDigitalSurface (const KSpace & aKSpace, const SurfelPredicate & aSP, const Adjacency & adj, const Surfel & s) inline
Constructor from digital set.
Parameters
aKSpace a cellular grid space (referenced).
aSP a surfel predicate defining the shape (referenced).
adj the surfel adjacency (for instance Adjacency(true) is interior to exterior adjacency).
s any surfel of aKSpace such that aPP is true in the interior and false in the exterior.
Definition at line 143 of file LightExplicitDigitalSurface.ih.
   : myKSpace( aKSpace ), mySurfelPredicate( aSP ), mySurfelAdjacency( adj ),
     mySurfel( s ), myTracker( *this, s )
 {
 }
Member Function Documentation
template<typename TKSpace , typename TSurfelPredicate > DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::SurfelConstIterator DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::begin () const inline
Returns
an iterator pointing on the first surfel of the digital surface (unspecified order).
Definition at line 222 of file LightExplicitDigitalSurface.ih.
References DGtal::GraphVisitorRange< TGraphVisitor >::begin(), and DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfel.
Referenced by DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::nbSurfels().
 {
   SelfVisitorRange range( new SelfVisitor( *this, mySurfel ) );
   return range.begin();
   // SelfVisitor* ptrVisitor = new SelfVisitor( *this, mySurfel );
   // ASSERT( ptrVisitor != 0 );
   // return SurfelConstIterator( ptrVisitor );
 }
template<typename TKSpace , typename TSurfelPredicate > DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Size DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::bestCapacity () const inline
Should return a reasonable estimation of the number of neighbors for all vertices. For instance a planar triangulation should return 6-8, a quad-mesh should return 4, digital surface is 2*(K::dimension-1).
Returns
2*(K::dimension-1)
Definition at line 347 of file LightExplicitDigitalSurface.ih.
 {
   return KSpace::dimension * 2 - 2;
 }
template<typename TKSpace, typename TSurfelPredicate> DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::BOOST_CONCEPT_ASSERT ((CSurfelPredicate< SurfelPredicate >))
Referenced by DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::writeNeighbors().
template<typename TKSpace , typename TSurfelPredicate > DGtal::Connectedness DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::connectedness () const inline
Returns
the connectedness of this surface. By construction CONNECTED.
Definition at line 270 of file LightExplicitDigitalSurface.ih.
References DGtal::CONNECTED.
 {
   return CONNECTED;
 }
template<typename TKSpace , typename TSurfelPredicate > DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Size DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::degree (const Vertex & v) const inline
Parameters
v any vertex of this graph
Returns
the number of neighbors of this Vertex/Surfel.
Definition at line 281 of file LightExplicitDigitalSurface.ih.
References DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Tracker::adjacent(), DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Tracker::move(), DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::myTracker, and DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::space().
 {
   Size d = 0;
   Vertex s;
   myTracker.move( v );
   for ( typename KSpace::DirIterator q = space().sDirs( v );
         q != 0; ++q )
     {
       if ( myTracker.adjacent( s, *q, true ) )
         ++d;
       if ( myTracker.adjacent( s, *q, false ) )
         ++d;
     }
   return d;
 }
template<typename TKSpace , typename TSurfelPredicate > bool DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::empty () const inline
Returns
'true' is the surface has no surfels, 'false' otherwise. NB: O(1) operation.
Definition at line 253 of file LightExplicitDigitalSurface.ih.
 {
   return false;
 }
template<typename TKSpace , typename TSurfelPredicate > DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::SurfelConstIterator DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::end () const inline
Returns
an iterator after the last surfel of the digital surface (unspecified order).
Definition at line 234 of file LightExplicitDigitalSurface.ih.
Referenced by DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::nbSurfels().
 {
   return SurfelConstIterator();
 }
template<typename TKSpace , typename TSurfelPredicate > bool DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::isInside (const Surfel & s) const inline
Parameters
s any surfel of the space.
Returns
'true' if s belongs to this digital surface.
Definition at line 214 of file LightExplicitDigitalSurface.ih.
References DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::surfelPredicate().
Referenced by DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Tracker::move().
 {
   return surfelPredicate()( s );
 }
template<typename TKSpace , typename TSurfelPredicate > bool DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 377 of file LightExplicitDigitalSurface.ih.
 {
   return true;
 }
template<typename TKSpace , typename TSurfelPredicate > DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Size DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::nbSurfels () const inline
Returns
the number of surfels of this digital surface. NB: O(N) computational complexity where N is the number of surfels.
Definition at line 242 of file LightExplicitDigitalSurface.ih.
References DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::begin(), and DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::end().
 {
   Size nb = 0;
   for ( SurfelConstIterator it = begin(), it_end = end(); it != it_end; ++it )
     ++nb;
   return nb;
 }
template<typename TKSpace , typename TSurfelPredicate > DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::DigitalSurfaceTracker * DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::newTracker (const Surfel & s) const inline
Parameters
s any surfel of the space.
Precondition
'isInside(s)'
Returns
a dyn. alloc. pointer on a tracker positionned at s.
Definition at line 262 of file LightExplicitDigitalSurface.ih.
 {
   return new Tracker( *this, s );
 }
template<typename TKSpace, typename TSurfelPredicate> LightExplicitDigitalSurface& DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::operator= (const LightExplicitDigitalSurface< TKSpace, TSurfelPredicate > & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
template<typename TKSpace , typename TSurfelPredicate > void DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 365 of file LightExplicitDigitalSurface.ih.
 {
   out << "[LightExplicitDigitalSurface]";
 }
template<typename TKSpace , typename TSurfelPredicate > void DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::setSurfel (const Surfel & aSurfel) inline
mutator to starting surfel.
Definition at line 190 of file LightExplicitDigitalSurface.ih.
References DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::myKSpace, DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfel, DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfelPredicate, and DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::myTracker.
 {
   mySurfel = aSurfel;
   ASSERT( myKSpace.sIsSurfel( mySurfel ) );
   ASSERT( mySurfelPredicate( mySurfel ) );
   myTracker = Tracker( *this, mySurfel );
 }
template<typename TKSpace , typename TSurfelPredicate > const DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::KSpace & DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::space () const inline
Returns
the cellular space in which lives the surface.
Definition at line 205 of file LightExplicitDigitalSurface.ih.
References DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::myKSpace.
Referenced by DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::degree(), DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Tracker::Tracker(), and DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::writeNeighbors().
 {
   return myKSpace;
 }
template<typename TKSpace , typename TSurfelPredicate > const DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Surfel & DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::surfel () const inline
accessor to starting surfel.
Definition at line 182 of file LightExplicitDigitalSurface.ih.
References DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfel.
 {
   return mySurfel;
 }
template<typename TKSpace , typename TSurfelPredicate > const DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Adjacency & DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::surfelAdjacency () const inline
accessor to surfel adjacency.
Definition at line 156 of file LightExplicitDigitalSurface.ih.
References DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfelAdjacency.
Referenced by DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Tracker::Tracker().
 {
   return mySurfelAdjacency;
 }
template<typename TKSpace , typename TSurfelPredicate > DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Adjacency & DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::surfelAdjacency () inline
mutator to surfel adjacency.
Definition at line 164 of file LightExplicitDigitalSurface.ih.
References DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfelAdjacency.
 {
   return mySurfelAdjacency;
 }
template<typename TKSpace , typename TSurfelPredicate > const DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::SurfelPredicate & DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::surfelPredicate () const inline
accessor to surfel predicate.
Definition at line 173 of file LightExplicitDigitalSurface.ih.
References DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfelPredicate.
Referenced by DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Tracker::adjacent(), and DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::isInside().
 {
   return mySurfelPredicate;
 }
template<typename TKSpace , typename TSurfelPredicate > template<typename OutputIterator > void DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::writeNeighbors (OutputIterator & it, const Vertex & v) const inline
Writes the neighbors of [v] in the output iterator [it]. Neighbors are given in no specific order.
Template Parameters
OutputIterator the type for the output iterator (e.g. back_insert_iterator<std::vector<Vertex> >).
Parameters
[in,out] it any output iterator on Vertex (*it++ should be allowed), which specifies where neighbors are written.
[in] v any vertex of this graph
Definition at line 302 of file LightExplicitDigitalSurface.ih.
References DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Tracker::adjacent(), DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Tracker::move(), DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::myTracker, and DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::space().
 {
   Vertex s;
   myTracker.move( v );
   for ( typename KSpace::DirIterator q = space().sDirs( v );
         q != 0; ++q )
     {
       if ( myTracker.adjacent( s, *q, true ) )
         *it++ = s;
       if ( myTracker.adjacent( s, *q, false ) )
         *it++ = s;
     }
 }
template<typename TKSpace , typename TSurfelPredicate > template<typename OutputIterator , typename VertexPredicate > void DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::writeNeighbors (OutputIterator & it, const Vertex & v, const VertexPredicate & pred) const inline
Writes the neighbors of [v], verifying the predicate [pred] in the output iterator [it]. Neighbors are given in no specific order.
Template Parameters
OutputIterator the type for the output iterator (e.g. back_insert_iterator<std::vector<Vertex> >).
VertexPredicate any type of predicate taking a Vertex as input.
Parameters
[in,out] it any output iterator on Vertex (*it++ should be allowed), which specifies where neighbors are written.
[in] v any vertex of this graph
[in] pred the predicate for selecting neighbors.
Definition at line 322 of file LightExplicitDigitalSurface.ih.
References DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Tracker::adjacent(), DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::BOOST_CONCEPT_ASSERT(), DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Tracker::move(), DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::myTracker, and DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::space().
 {
   BOOST_CONCEPT_ASSERT(( CVertexPredicate< VertexPredicate > ));
   Vertex s;
   myTracker.move( v );
   for ( typename KSpace::DirIterator q = space().sDirs( v );
         q != 0; ++q )
     {
       if ( myTracker.adjacent( s, *q, true ) )
         {
           if ( pred( s ) ) *it++ = s;
         }
       if ( myTracker.adjacent( s, *q, false ) )
         {
           if ( pred( s ) ) *it++ = s;
         }
     }
 }
Field Documentation
template<typename TKSpace, typename TSurfelPredicate> const KSpace& DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::myKSpace private
a reference to the cellular space.
Definition at line 397 of file LightExplicitDigitalSurface.h.
Referenced by DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::setSurfel(), and DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::space().
template<typename TKSpace, typename TSurfelPredicate> Surfel DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfel private
a surfel belonging to the surface.
Definition at line 403 of file LightExplicitDigitalSurface.h.
Referenced by DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::begin(), DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::setSurfel(), and DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::surfel().
template<typename TKSpace, typename TSurfelPredicate> Adjacency DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfelAdjacency private
the surfel adjacency used to determine neighbors.
Definition at line 401 of file LightExplicitDigitalSurface.h.
Referenced by DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::surfelAdjacency().
template<typename TKSpace, typename TSurfelPredicate> const SurfelPredicate& DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfelPredicate private
a reference to the surfel predicate defining the shape.
Definition at line 399 of file LightExplicitDigitalSurface.h.
Referenced by DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::setSurfel(), and DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::surfelPredicate().
template<typename TKSpace, typename TSurfelPredicate> Tracker DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::myTracker mutable private
Internal tracker for visiting surfels.
Definition at line 405 of file LightExplicitDigitalSurface.h.
Referenced by DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::degree(), DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::setSurfel(), and DGtal::LightExplicitDigitalSurface< TKSpace, TSurfelPredicate >::writeNeighbors().
The documentation for this class was generated from the following files:
LightExplicitDigitalSurface.h
LightExplicitDigitalSurface.ih