DGtal: DGtal::Viewer3D< S, KS > Class Template Reference
DGtal::Viewer3D< S, KS > Class Template Reference
DGtal Concepts
#include <CDrawableWithViewer3D.h>
Data Structures
struct CompFarthestPolygonFromCamera
struct CompFarthestSurfelFromCamera
struct CompFarthestTriangleFromCamera
struct CompFarthestVoxelFromCamera
struct GLTextureImage
struct Image2DDomainD3D
struct TextureImage
Public Types
enum ImageDirection { xDirection, yDirection, zDirection, undefDirection }
enum TextureMode { RGBMode, GrayScaleMode }
Public Types inherited from DGtal::Display3D< Space, KSpace >
enum StreamKey { addNewList, updateDisplay, shiftSurfelVisu }
typedef DGtal::Z3i::RealPoint RealPoint
typedef std::map< std::string,
std::string > ModeMapping
typedef std::map< std::string,
CountedPtr
< DrawableWithDisplay3D > > StyleMapping
Public Member Functions
Viewer3D ()
Viewer3D (const KSpace &KSEmb)
Viewer3D (const Space &SEmb, const KSpace &KSEmb)
void setCameraPosition (double ax, double ay, double az)
void setCameraDirection (double ax, double ay, double az)
void setCameraUpVector (double ax, double ay, double az)
void setNearFar (double _near, double _far)
void setGLScale (float sx, float sy, float sz)
Viewer3D< Space, KSpace > & operator<< (const DGtal::Color &aColor)
Viewer3D< Space, KSpace > & operator<< (const typename Viewer3D< Space, KSpace >::StreamKey &key)
void sortSurfelFromCamera ()
void sortTriangleFromCamera ()
void sortQuadFromCamera ()
void sortPolygonFromCamera ()
template<typename TDrawableWithViewer3D >
Viewer3D< Space, KSpace > & operator<< (const TDrawableWithViewer3D &object)
void selfDisplay (std::ostream &out) const
bool isValid () const
virtual unsigned int getCurrentDomainNumber ()
virtual unsigned int getCurrentGLImageNumber ()
void addTextureImage (const TextureImage &image)
template<typename TImageType , typename TFunctor >
void updateTextureImage (unsigned int imageIndex, const TImageType &image, const TFunctor &aFunctor, double xTranslation=0.0, double yTranslation=0.0, double zTranslation=0.0, double rotationAngle=0.0, ImageDirection rotationDir=zDirection)
void updateOrientationTextureImage (unsigned int imageIndex, double xPosition, double yPosition, double zPosition, ImageDirection newDirection)
void updateEmbeddingTextureImage (unsigned int anImageIndex, typename Space::Point aPoint1, typename Space::Point aPoint2, typename Space::Point aPoint3, typename Space::Point aPoint4)
template<typename TDomain >
void addImage2DDomainD3D (const TDomain &anImageDomain, std::string mode, const DGtal::Color &aColor=DGtal::Color::Red)
void updateAn2DDomainOrientation (unsigned int imageIndex, double xPosition, double yPosition, double zPosition, ImageDirection newDirection)
void translateAn2DDomain (unsigned int domainIndex, double xTranslation, double yTranslation, double zTranslation)
std::vector< typename
DGtal::Viewer3D< Space, KSpace >
::LineD3D > compute2DDomainLineRepresentation (Image2DDomainD3D &anImageDomain, double delta)
std::vector< typename
DGtal::Viewer3D< Space, KSpace >
::LineD3D > compute2DDomainLineRepresentation (Image2DDomainD3D &anImageDomain)
void rotateLineD3D (typename DGtal::Display3D< Space, KSpace >::LineD3D &aLine, DGtal::PointVector< 3, int > pt, double angleRotation, ImageDirection dirRotation)
void rotateDomain (Image2DDomainD3D &anDom, double angle, ImageDirection rotationDir)
void updateList (bool needToUpdateBoundingBox=true)
void glDrawGLLinel (typename Viewer3D< Space, KSpace >::LineD3D aLinel)
void glDrawGLPointel (typename Viewer3D< Space, KSpace >::BallD3D pointel)
virtual void keyPressEvent (QKeyEvent *e)
virtual void drawWithNames ()
virtual void draw ()
virtual void init ()
virtual QString helpString () const
virtual void postSelection (const QPoint &point)
template<typename TDrawableWithViewer3D >
DGtal::Viewer3D< Space, KSpace > & operator<< (const TDrawableWithViewer3D &object)
Public Member Functions inherited from DGtal::Display3D< Space, KSpace >
BOOST_CONCEPT_ASSERT ((CSpace< Space >))
~Display3D ()
Display3D ()
Display3D (const KSpace &KSEmb)
Display3D (const Space &Semb, const KSpace &KSEmb)
virtual void setFillColor (DGtal::Color aColor)
virtual void setFillTransparency (unsigned char alpha)
virtual void setLineColor (DGtal::Color aColor)
virtual DGtal::Color getFillColor ()
virtual DGtal::Color getLineColor ()
virtual void setSpaceEmbedder (CanonicEmbedder< Space > *anEmbedder)
virtual void setKSpaceEmbedder (CanonicCellEmbedder< KSpace > *anEmbedder)
virtual void setSKSpaceEmbedder (CanonicSCellEmbedder< KSpace > *anEmbedder)
void addClippingPlane (double a, double b, double c, double d, bool drawPlane)
std::string getMode (const std::string &objectName) const
void createNewLineList (std::string s="")
void createNewBallList (std::string s="")
void createNewCubeList (std::string s="")
void createNewQuadList (std::string s="")
void createNewTriangleList (std::string s="")
void createNewPolygonList (std::string s="")
void addQuad (const RealPoint &p1, const RealPoint &p2, const RealPoint &p3, const RealPoint &p4)
void addTriangle (const RealPoint &p1, const RealPoint &p2, const RealPoint &p3)
void addPolygon (const std::vector< RealPoint > &vertices)
void addLine (const RealPoint &p1, const RealPoint &p2, double width=0.03)
void addCube (const RealPoint &center, double width=1.0)
void addBall (const RealPoint &center, double size=0.05)
void addSurfelPrism (const RealPoint &baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel, double sizeShiftFactor, double sizeFactor=1.0, bool isSigned=false, bool aSign=true)
void addQuad (const RealPoint &baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel, double sizeShiftFactor, double sizeFactor=1.0, bool isSigned=false, bool aSign=true)
void addCone (const RealPoint &p1, const RealPoint &p2, double width=0.02)
void addCylinder (const RealPoint &p1, const RealPoint &p2, const double width=0.02)
void updateBoundingBox (const RealPoint &point)
void exportToMesh (Mesh< Display3D::BallD3D > &aMesh) const
template<typename TDrawableWithDisplay3D >
Display3D & operator<< (const TDrawableWithDisplay3D &object)
void selfDisplay (std::ostream &out) const
bool isValid () const
DGtal::CanonicEmbedder< Space >
::RealPoint embed (const typename Space::Point &dp) const
DGtal::CanonicSCellEmbedder
< KSpace >::RealPoint embedKS (const typename KSpace::SCell &cell) const
DGtal::CanonicSCellEmbedder
< KSpace >::RealPoint embedKS (const DGtal::TransformedSurfelPrism &aTrans) const
DGtal::CanonicCellEmbedder
< KSpace >::RealPoint embedK (const typename KSpace::Cell &cell) const
template<typename TDrawableWithDisplay3D >
DGtal::Display3D< Space,KSpace > & operator<< (const TDrawableWithDisplay3D &object)
Static Public Member Functions
template<typename TImageORDomain >
static void rotateImageVertex (TImageORDomain &anImageOrDom, double angle, ImageDirection rotationDir)
static void rotatePoint (double &x, double &y, double &z, double cx, double cy, double cz, double rotationAngle, ImageDirection rotationDir)
Data Fields
DGtal::Color myDefaultBackgroundColor
DGtal::Color myDefaultColor
bool myIsBackgroundDefault
bool myViewWire
Data Fields inherited from DGtal::Display3D< Space, KSpace >
ModeMapping myModes
StyleMapping myStyles
bool myBoundingPtEmptyTag
double myBoundingPtUp [3]
double myBoundingPtLow [3]
Private Member Functions
BOOST_CONCEPT_ASSERT ((CSpace< Space >))
Private Attributes
GLuint myListToAff
unsigned int myNbListe
qglviewer::Vec myOrig
qglviewer::Vec myDir
qglviewer::Vec myDirSelector
qglviewer::Vec mySelectedPoint
QPoint myPosSelector
std::vector< GLTextureImage > myVectTextureImage
bool myIsDoubleFaceRendering
double camera_position [3]
double camera_direction [3]
double camera_upVector [3]
double ZNear
double ZFar
float myMeshDefaultLineWidth
float myGLScaleFactorX
float myGLScaleFactorY
float myGLScaleFactorZ
std::vector< TextureImage > myGSImageList
std::vector< Image2DDomainD3D > myImageDomainList
Additional Inherited Members
Static Protected Member Functions inherited from DGtal::Display3D< Space, KSpace >
static void cross (double dst[3], double srcA[3], double srcB[3])
static void normalize (double vec[3])
Protected Attributes inherited from DGtal::Display3D< Space, KSpace >
CanonicEmbedder< Space > * myEmbedder
CanonicCellEmbedder< KSpace > * myCellEmbedder
CanonicSCellEmbedder< KSpace > * mySCellEmbedder
DGtal::Color myCurrentFillColor
DGtal::Color myCurrentLineColor
double myCurrentfShiftVisuSurfelPrisms
std::vector< std::vector
< CubeD3D > > myCubeSetList
std::vector< std::vector
< LineD3D > > myLineSetList
std::vector< std::vector
< BallD3D > > myBallSetList
std::vector< ClippingPlaneD3D > myClippingPlaneList
std::vector< QuadD3D > mySurfelPrismList
std::vector< std::vector
< QuadD3D > > myQuadSetList
std::vector< std::vector
< TriangleD3D > > myTriangleSetList
std::vector< std::vector
< PolygonD3D > > myPolygonSetList
std::vector< std::string > myCubeSetNameList
std::vector< std::string > myLineSetNameList
std::vector< std::string > myBallSetNameList
std::vector< std::string > myClippingPlaneNameList
std::vector< std::string > mySurfelPrismNameList
std::vector< std::string > myQuadSetNameList
std::vector< std::string > myTriangleSetNameList
std::vector< std::string > myPolygonSetNameList
Detailed Description
template<class S, class KS>
class DGtal::Viewer3D< S, KS >
Aim: The concept CDrawableWithViewer3D specifies what are the classes that admit an export with Viewer3D.
Description of concept 'CDrawableWithViewer3D'
An object x satisfying this concept may then be used as:
Viewer3D display;
display << CustomStyle(x.className(), x.defaultStyle())
      << x;
Refinement of
Associated types :
Notation
X : A type that is a model of CDrawableWithViewer3DD
x, y : Object of type X
m : a string of characters
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
the default draw style x.defaultStyle(m = "") mode m: std::string CDrawableWithViewer3D returns a dynamic allocation of the default style for the model X in mode m
the name of the model X x.className() std::string returns a string telling the name of the model X
the way the object x is drawn x.setStyle(CDrawableWithViewer3D &display) draws the object x on the display stream
Invariants
Models
ArimeticalDSS, FreemanChain, HyperRectDomain, ImageContainerByHashTree, ImageContainerBySTLVector, PointVector, DigitalSetBySTLSet,DigitalSetBySTLVector, Object
Notes
Todo:
ImageContainerByHashTree does not implement setStyle(display &).
ImageContainerByHashTree does not implement defaultStyle(std::string&)const.
Description of class 'Viewer3D'
Aim: Display 3D primitive (like PointVector, DigitalSetBySTLSet, Object ...). This class uses the libQGLViewer library (
See Also
http://www.libqglviewer.com). It inherits of the class Display3D and permits to display object using a simple stream mechanism of "<<".
For instance you can display objects as follows:
* #include <QtGui/qapplication.h>
* #include "DGtal/helpers/StdDefs.h"
* #include "DGtal/io/viewers/Viewer3D.h"
* ...
* using namespace Z3i;
* ...
*
* Point p1(0, 0, 0);
* Point p2(5, 5 ,5);
* Point p3(2, 3, 4);
* Domain domain(p1, p2);
* Viewer3D<> viewer;
* viewer.show();
* viewer << domain;
* viewer << p1 << p2 << p3;
* viewer<< Viewer3D<>::updateDisplay;
* return application.exec();
*
*
This class is parametrized by both the Digital and Khalimsky space used to display object. More precisely, embed methods are used to compute the Euclidean coordinate of digital obejects/khalimksy cells.
Template Parameters
Space any model of Digital 3D Space
KSpace any mode of Khalimksky 3D space
See Also
Display3D, Board3DTo2D
Examples:
geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, geometry/volumes/distance/distancetransform3D.cpp, graph/volDistanceTraversal.cpp, images/extract2DImagesFrom3DandVisu.cpp, io/digitalSetFromPointList.cpp, io/digitalSetFromVol.cpp, io/meshFromOFF.cpp, io/viewers/viewer3D-1-points.cpp, io/viewers/viewer3D-2-sets.cpp, io/viewers/viewer3D-3-objects.cpp, io/viewers/viewer3D-5-custom.cpp, io/viewers/viewer3D-6-clipping.cpp, io/viewers/viewer3D-7-planes.cpp, io/viewers/viewer3D-7-stdplane.cpp, io/viewers/viewer3D-7bis-planes.cpp, io/viewers/viewer3D-7bis-stdplane.cpp, io/viewers/viewer3D-8-2DSliceImages.cpp, io/viewers/viewer3D-8bis-2Dimages.cpp, io/viewers/viewer3D-9-3Dimages.cpp, shapes/Mesh3DConstructionAndVisualisation.cpp, topology/3dBorderExtraction.cpp, topology/3dBorderExtractionImg.cpp, topology/3dKSSurfaceExtraction.cpp, topology/ctopo-2-3d.cpp, topology/frontierAndBoundary.cpp, topology/homotopicThinning3D.cpp, topology/volScanBoundary.cpp, and topology/volTrackBoundary.cpp.
Definition at line 97 of file CDrawableWithViewer3D.h.
Member Enumeration Documentation
template<class S, class KS> enum DGtal::Viewer3D::ImageDirection
the 3 possible axes for the image direction
Enumerator
xDirection
yDirection
zDirection
undefDirection
Definition at line 214 of file Viewer3D.h.
 {xDirection, yDirection, zDirection, undefDirection };
template<class S, class KS> enum DGtal::Viewer3D::TextureMode
the modes of representation of an image
Enumerator
RGBMode
GrayScaleMode
Definition at line 216 of file Viewer3D.h.
 {RGBMode, GrayScaleMode };
Constructor & Destructor Documentation
template<class S, class KS> DGtal::Viewer3D< S, KS >::Viewer3D () inline
Constructor
Definition at line 133 of file Viewer3D.h.
                :QGLViewer(), Display3D<Space, KSpace>()
     {};
template<class S, class KS> DGtal::Viewer3D< S, KS >::Viewer3D (const KSpace & KSEmb) inline
Constructor with a khalimsky space
Parameters
KSEmb the Khalimsky space
Definition at line 140 of file Viewer3D.h.
                                  :QGLViewer(), Display3D<Space,KSpace>(KSEmb)
     {};
template<class S, class KS> DGtal::Viewer3D< S, KS >::Viewer3D (const Space & SEmb, const KSpace & KSEmb) inline
Constructor with a space and a khalimsky space
Parameters
SEmb a space
KSEmb a khalimsky space
Definition at line 148 of file Viewer3D.h.
                                                      : QGLViewer(), Display3D<Space,KSpace>(SEmb, KSEmb)
     {};
Member Function Documentation
template<typename Space , typename KSpace > template<typename TDomain > void DGtal::Viewer3D< Space, KSpace >::addImage2DDomainD3D (const TDomain & anImageDomain, std::string mode, const DGtal::Color & aColor = DGtal::Color::Red)
add an 2D image in a 3d space
Parameters
anImageDomain an image and its domain
mode mode of representation
aColor color of the image
Definition at line 313 of file Viewer3D.ih.
References DGtal::Viewer3D< S, KS >::Image2DDomainD3D::color, DGtal::Viewer3D< S, KS >::Image2DDomainD3D::myLineSetIndex, DGtal::Viewer3D< S, KS >::Image2DDomainD3D::myMode, DGtal::Viewer3D< S, KS >::Image2DDomainD3D::point1, DGtal::Viewer3D< S, KS >::Image2DDomainD3D::point2, DGtal::Viewer3D< S, KS >::Image2DDomainD3D::point3, and DGtal::Viewer3D< S, KS >::Image2DDomainD3D::point4.
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::draw().
 {
   typename DGtal::Viewer3D< Space ,KSpace >::Image2DDomainD3D anImageDomain(aDomain);
   anImageDomain.color = aColor;
   anImageDomain.myMode = mode;
   anImageDomain.myLineSetIndex=Viewer3D<Space, KSpace>::myLineSetList.size();
   myImageDomainList.push_back(anImageDomain);
   Display3D< Space, KSpace>::updateBoundingBox(anImageDomain.point1);
   Display3D< Space, KSpace>::updateBoundingBox(anImageDomain.point2);
   Display3D< Space, KSpace>::updateBoundingBox(anImageDomain.point3);
   Display3D< Space, KSpace>::updateBoundingBox(anImageDomain.point4);
   std::vector<typename DGtal::Viewer3D< Space ,KSpace >::LineD3D> vectLines= compute2DDomainLineRepresentation(anImageDomain);
   Viewer3D<Space, KSpace>::myLineSetList.push_back(vectLines);
 }
template<class S, class KS> void DGtal::Viewer3D< Space, KSpace >::addTextureImage (const TextureImage & image) inline
Add a TextureImage in the list of image to be displayed.
Parameters
image a TextureImage including image data buffer and position, orientation.
Definition at line 163 of file Viewer3D.ih.
References DGtal::Viewer3D< S, KS >::TextureImage::point1, DGtal::Viewer3D< S, KS >::TextureImage::point2, DGtal::Viewer3D< S, KS >::TextureImage::point3, and DGtal::Viewer3D< S, KS >::TextureImage::point4.
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::drawImage2D().
 {
   myGSImageList.push_back(image);
   Display3D< Space, KSpace>::updateBoundingBox(image.point1);
   Display3D< Space, KSpace>::updateBoundingBox(image.point2);
   Display3D< Space, KSpace>::updateBoundingBox(image.point3);
   Display3D< Space, KSpace>::updateBoundingBox(image.point4);
 }
template<class S, class KS> DGtal::Viewer3D< S, KS >::BOOST_CONCEPT_ASSERT ((CSpace< Space >)) private
Referenced by DGtal::Viewer3D< S, KS >::Image2DDomainD3D::Image2DDomainD3D(), DGtal::Viewer3D< S, KS >::TextureImage::TextureImage(), and DGtal::Viewer3D< S, KS >::TextureImage::updateImageDataAndParam().
template<class S, class KS> std::vector<typename DGtal::Viewer3D< Space , KSpace >::LineD3D> DGtal::Viewer3D< S, KS >::compute2DDomainLineRepresentation (Image2DDomainD3D & anImageDomain, double delta)
compute2DDomainLineRepresentation
Parameters
anImageDomain the image domain
delta the delte for computing
Returns
the vector containing the line domain representation.
template<class S, class KS> std::vector<typename DGtal::Viewer3D< Space , KSpace >::LineD3D> DGtal::Viewer3D< S, KS >::compute2DDomainLineRepresentation (Image2DDomainD3D & anImageDomain)
compute2DDomainLineRepresentation
Parameters
anImageDomain the image domain
Returns
the vector containing the line domain representation.
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::draw () inline virtual
draw
Definition at line 639 of file Viewer3D.ih.
References DGtal::Viewer3D< S, KS >::GLTextureImage::myTextureFitX, DGtal::Viewer3D< S, KS >::GLTextureImage::myTextureFitY, DGtal::Viewer3D< S, KS >::GLTextureImage::myTextureName, DGtal::Viewer3D< S, KS >::GLTextureImage::point1, DGtal::Viewer3D< S, KS >::GLTextureImage::point2, DGtal::Viewer3D< S, KS >::GLTextureImage::point3, DGtal::Viewer3D< S, KS >::GLTextureImage::point4, and DGtal::Viewer3D< S, KS >::GLTextureImage::vectNormal.
 {
   glPushMatrix();
   glMultMatrixd ( manipulatedFrame()->matrix() );
   glPushMatrix();
   glScalef(myGLScaleFactorX, myGLScaleFactorY, myGLScaleFactorZ);
   unsigned int i = 0;
   typename vector< typename Viewer3D<Space, KSpace>::ClippingPlaneD3D >::const_iterator it = Viewer3D<Space, KSpace>::myClippingPlaneList.begin();
   // OpenGL can't draw more than GL_MAX_CLIP_PLANES clipping plane
   while ( i < GL_MAX_CLIP_PLANES && it !=Viewer3D<Space, KSpace>::myClippingPlaneList.end() )
     {
       double eq [4];
       eq[0]=it->a;
       eq[1]=it->b;
       eq[2]=it->c;
       eq[3]=it->d;
       glEnable ( GL_CLIP_PLANE0+i );
       glClipPlane ( GL_CLIP_PLANE0+i, eq );
       i++;
       it++;
     }
   if (i == GL_MAX_CLIP_PLANES)
     {
       std::cerr <<"Warning maximal clipping plane added" << std::endl;
     }
   Vec centerS = sceneCenter();
   Vec posCam = camera()->position();
   double distCam =sqrt ( ( posCam.x-centerS.x ) * ( posCam.x-centerS.x ) +
                          ( posCam.y-centerS.y ) * ( posCam.y-centerS.y ) +
                          ( posCam.z-centerS.z ) * ( posCam.z-centerS.z ) );
   for ( unsigned int j=0; j< Viewer3D<Space, KSpace>::myBallSetList.size(); j++ )
     {
       if ( Viewer3D<Space, KSpace>::myBallSetList.at ( j ).size() !=0 )
         {
           glPointSize ( ( Viewer3D<Space, KSpace>::myBallSetList.at ( j ).at ( 0 ).size ) /distCam );
         }
       glCallList ( GLuint ( myListToAff+ Viewer3D<Space, KSpace>::myCubeSetList.size()+ Viewer3D<Space, KSpace>::myLineSetList.size() +j+1 ) );
     }
   for ( unsigned int j=0; j< Viewer3D<Space, KSpace>::myLineSetList.size(); j++ )
     {
       if ( Viewer3D<Space, KSpace>::myLineSetList.at ( j ).size() !=0 )
         {
           glLineWidth ( ( Viewer3D<Space, KSpace>::myLineSetList.at ( j ).at ( 0 ).width ) );
         }
       glCallList ( GLuint ( myListToAff+ Viewer3D<Space, KSpace>::myCubeSetList.size()+1+j ) );
     }
   glCallList ( GLuint ( myListToAff+ Viewer3D<Space, KSpace>::myCubeSetList.size()) );
   for ( unsigned int j=0; j< Viewer3D<Space, KSpace>::myCubeSetList.size() ; j++ )
     {
       glCallList ( myListToAff+j );
     }
   glCallList ( GLuint ( myListToAff+Viewer3D<Space, KSpace>::myCubeSetList.size()) );
   for ( unsigned int j=0; j<Viewer3D<Space, KSpace>::myCubeSetList.size() ; j++ )
     {
       glCallList ( myListToAff+j );
     }
   // Calling lists associated to Mesh display (see. updateList)
   unsigned int nbListOfPrimitives = Viewer3D<Space, KSpace>::myLineSetList.size() +Viewer3D<Space, KSpace>::myCubeSetList.size()+ Viewer3D<Space, KSpace>::myBallSetList.size();
   glLineWidth ( Viewer3D<Space, KSpace>::myMeshDefaultLineWidth /distCam );
   glDisable(GL_CULL_FACE);
   glCallList ( GLuint ( myListToAff+nbListOfPrimitives+1 ) );
   if(myViewWire)
     {
       glLineWidth ( Viewer3D<Space, KSpace>::myMeshDefaultLineWidth /distCam );
       glCallList ( GLuint ( myListToAff+nbListOfPrimitives+2 ) );
     }
   glDisable(GL_CULL_FACE);
   glCallList ( GLuint ( myListToAff+nbListOfPrimitives+3 ) );
   if(myViewWire)
     {
       glLineWidth ( Viewer3D<Space, KSpace>::myMeshDefaultLineWidth /distCam );
       glCallList ( GLuint ( myListToAff+nbListOfPrimitives+4 ) );
     }
   glDisable(GL_CULL_FACE);
   glCallList ( GLuint ( myListToAff+nbListOfPrimitives+5 ) );
   if(myViewWire)
     {
       glLineWidth ( Viewer3D<Space, KSpace>::myMeshDefaultLineWidth /distCam );
       glCallList ( GLuint ( myListToAff+nbListOfPrimitives+6 ) );
     }
   // Drawing all Khalimsky Space Cells
   for ( typename vector<vector< typename Viewer3D<Space, KSpace>::BallD3D> >::const_iterator itb= Viewer3D<Space, KSpace>::myBallSetList.begin();
         itb != Viewer3D<Space, KSpace>::myBallSetList.end(); itb++ )
     {
       for ( typename vector< typename Viewer3D<Space, KSpace>::BallD3D>::const_iterator it_s = itb->begin(); it_s !=itb->end() ; it_s ++)
         {
           glDrawGLPointel ( *it_s );
         }
     }
   for ( typename vector<vector< typename Viewer3D<Space, KSpace>::LineD3D> >::const_iterator itb= Viewer3D<Space, KSpace>::myLineSetList.begin();
         itb != Viewer3D<Space, KSpace>::myLineSetList.end(); itb++ )
     {
       for ( typename vector< typename Viewer3D<Space, KSpace>::LineD3D>::const_iterator it_s = itb->begin(); it_s !=itb->end() ; it_s ++)
         {
           glDrawGLLinel (*it_s );
         }
     }
   for(unsigned int j=0; j< myVectTextureImage.size(); j++)
     {
       GLTextureImage &textureImg = myVectTextureImage.at(j);
       glPushName ( textureImg.myTextureName );
       glEnable(GL_TEXTURE_2D);
       glTexEnvf(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE);
       glBindTexture(GL_TEXTURE_2D, textureImg.myTextureName);
       glBegin(GL_QUADS);
       glColor4ub ( 255.0, 255.0, 255.0, 255.0 );
       glNormal3d(textureImg.vectNormal[0], textureImg.vectNormal[1], textureImg.vectNormal[2]);
       glTexCoord2f(0, 0);
       glVertex3f(textureImg.point1[0], textureImg.point1[1], textureImg.point1[2]);
       glTexCoord2f(textureImg.myTextureFitX, 0.0);
       glVertex3f(textureImg.point2[0], textureImg.point2[1], textureImg.point2[2]);
       glTexCoord2f(textureImg.myTextureFitX, textureImg.myTextureFitY);
       glVertex3f(textureImg.point3[0], textureImg.point3[1], textureImg.point3[2]);
       glTexCoord2f(0.0, textureImg.myTextureFitY);
       glVertex3f(textureImg.point4[0], textureImg.point4[1], textureImg.point4[2]);
       glEnd();
       glDisable(GL_TEXTURE_2D);
     }
    glPopMatrix();
    glPopMatrix();
    drawLight(GL_LIGHT1);
 }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::drawWithNames () inline virtual
drawWithNames
Definition at line 619 of file Viewer3D.ih.
 {
   for ( unsigned int i=0; i<Viewer3D<Space, KSpace>::myCubeSetList.size() ; i++ )
     {
       glCallList ( myListToAff+i );
     }
   for ( unsigned int i=0; i<Viewer3D<Space, KSpace>::myLineSetList.size(); i++ )
     {
       glCallList ( GLuint ( myListToAff+Viewer3D<Space, KSpace>::myCubeSetList.size()+i ) );
     }
   for ( unsigned int i=0; i<Viewer3D<Space, KSpace>::myBallSetList.size(); i++ )
     {
       glCallList ( GLuint ( myListToAff+Viewer3D<Space, KSpace>::myCubeSetList.size()+Viewer3D<Space, KSpace>::myLineSetList.size() +i ) );
     }
 }
template<typename Space , typename KSpace > unsigned int DGtal::Viewer3D< Space, KSpace >::getCurrentDomainNumber () inline virtual
Definition at line 146 of file Viewer3D.ih.
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::drawImage2D().
 {
   return myImageDomainList.size();
 }
template<typename Space , typename KSpace > unsigned int DGtal::Viewer3D< Space, KSpace >::getCurrentGLImageNumber () inline virtual
Definition at line 154 of file Viewer3D.ih.
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::draw().
 {
   return myGSImageList.size();
 }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::glDrawGLLinel (typename Viewer3D< Space, KSpace >::LineD3D aLinel)
Draw a linel by using the [gluCylinder] primitive.
Parameters
aLinel the linel to draw
Definition at line 1399 of file Viewer3D.ih.
 {
   glPushMatrix();
   glTranslatef ( aLinel.point1[0], aLinel.point1[1], aLinel.point1[2] );
   Vec dir ( aLinel.point2[0]-aLinel.point1[0], aLinel.point2[1]-aLinel.point1[1], aLinel.point2[2]-aLinel.point1[2] );
   glMultMatrixd ( Quaternion ( Vec ( 0,0,1 ), dir ).matrix() );
   GLUquadric* quadric = gluNewQuadric();
   glColor4ub ( aLinel.color.red(), aLinel.color.green(), aLinel.color.blue(), aLinel.color.alpha() );
   gluCylinder ( quadric, ( aLinel.signPos || !aLinel.isSigned ) ? aLinel.width :0 ,
                 ( aLinel.signPos && aLinel.isSigned ) ? 0 :aLinel.width ,
                 dir.norm(),10, 4 );
   glPopMatrix();
 }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::glDrawGLPointel (typename Viewer3D< Space, KSpace >::BallD3D pointel)
Draw a linel by using the [gluCShere] primitive.
Parameters
pointel the pointel to draw
Definition at line 1417 of file Viewer3D.ih.
 {
   if ( !ballel.isSigned )
     {
       glPushMatrix();
       glTranslatef ( ballel.center[0], ballel.center[1], ballel.center[2] );
       GLUquadric* quadric = gluNewQuadric();
       glColor4ub ( ballel.color.red(), ballel.color.green(), ballel.color.blue(), ballel.color.alpha() );
       gluSphere ( quadric, ballel.size, 10, 10 );
       glPopMatrix();
     }
   else
     {
       // a small "+" is drawn with cylinder
       if ( ballel.signPos )
         {
           glPushMatrix();
           glTranslatef ( ballel.center[0]-0.07, ballel.center[1]-0.07, ballel.center[2] );
           Vec dir ( 0.14, 0.14, 0 );
           glMultMatrixd ( Quaternion ( Vec ( 0,0,1 ), dir ).matrix() );
           GLUquadric* quadric = gluNewQuadric();
           glColor4ub ( ballel.color.red(), ballel.color.green(), ballel.color.blue(), ballel.color.alpha() );
           gluCylinder ( quadric, ballel.size/3.0 , ballel.size/3.0,
                         dir.norm(),10, 4 );
           glPopMatrix();
           glPushMatrix();
           glTranslatef ( ballel.center[0]-0.07, ballel.center[1]+0.07, ballel.center[2] );
           dir=Vec ( 0.14, -0.14, 0 );
           glMultMatrixd ( Quaternion ( Vec ( 0,0,1 ), dir ).matrix() );
           quadric = gluNewQuadric();
           glColor4ub ( ballel.color.red(), ballel.color.green(), ballel.color.blue(), ballel.color.alpha() );
           gluCylinder ( quadric, ballel.size/3.0 , ballel.size/3.0,
                         dir.norm(),10, 4 );
           glPopMatrix();
         }
       else
         {
           glPushMatrix();
           glTranslatef ( ballel.center[0], ballel.center[1]+0.07, ballel.center[2]-0.07 );
           Vec dir ( 0.0, -0.14, 0.14 );
           glMultMatrixd ( Quaternion ( Vec ( 0,0,1 ), dir ).matrix() );
           GLUquadric* quadric = gluNewQuadric();
           glColor4ub ( ballel.color.red(), ballel.color.green(), ballel.color.blue(), ballel.color.alpha() );
           gluCylinder ( quadric, ballel.size/4.0 , ballel.size/4.0,
                         dir.norm(),10, 4 );
           glPopMatrix();
         }
     }
 }
template<typename Space , typename KSpace > QString DGtal::Viewer3D< Space, KSpace >::helpString () const virtual
Returns
astring corresponding to the help of the viewer (list of commands, etc)
Definition at line 1608 of file Viewer3D.ih.
 {
   QString text ( "<h2> Viewer3D</h2>" );
   text += "Use the mouse to move the camera around the object. ";
   text += "You can respectively revolve around, zoom and translate with the three mouse buttons. ";
   text += "Left and middle buttons pressed together rotate around the camera view direction axis<br><br>";
   text += "Pressing <b>Alt</b> and one of the function keys (<b>F1</b>..<b>F12</b>) defines a camera keyFrame. ";
   text += "Simply press the function key again to restore it-> Several keyFrames define a ";
   text += "camera path. Paths are saved when you quit the application and restored at next start.<br><br>";
   text += "Press <b>F</b> to display the frame rate, <b>A</b> for the world axis, ";
   text += "<b>Alt+Return</b> for full screen mode and <b>Control+S</b> to save a snapshot. ";
   text += "See the <b>Keyboard</b> tab in this window for a complete shortcut list.<br><br>";
   text += "Double clicks automates single click actions: A left button double click aligns the closer axis with the camera (if close enough). ";
   text += "A middle button double click fits the zoom of the camera and the right button re-centers the scene.<br><br>";
   text += "A left button double click while holding right button pressed defines the camera <i>Revolve Around Ball</i>. ";
   text += "See the <b>Mouse</b> tab and the documentation web pages for details.<br><br>";
   text += "Press <b>Escape</b> to exit the viewer.";
   return text;
 }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::init () virtual
init
Definition at line 808 of file Viewer3D.ih.
 {
   Viewer3D<Space, KSpace>::myMeshDefaultLineWidth=10.0;
   myNbListe=0;
   myViewWire=true;
   myGLScaleFactorX=1.0;
   myGLScaleFactorY=1.0;
   myGLScaleFactorZ=1.0;
   myIsDoubleFaceRendering=true;
   Viewer3D<Space, KSpace>::createNewCubeList ( );
   vector<typename Viewer3D<Space, KSpace>::LineD3D> listeLine;
   Viewer3D<Space, KSpace>::myLineSetList.push_back ( listeLine );
   vector<typename Viewer3D<Space, KSpace>::BallD3D> listeBall;
   Viewer3D<Space, KSpace>::myBallSetList.push_back ( listeBall );
   Viewer3D<Space, KSpace>::myCurrentFillColor = Color ( 220, 220, 220 );
   Viewer3D<Space, KSpace>::myCurrentLineColor = Color ( 22, 22, 222, 50 );
   myDefaultBackgroundColor = Color ( backgroundColor().red(), backgroundColor().green(),
                                      backgroundColor().blue() );
   myIsBackgroundDefault=true;
   Viewer3D<Space, KSpace>::myBoundingPtLow[0]=-10.0;//numeric_limits<double>::max( );
   Viewer3D<Space, KSpace>::myBoundingPtLow[1]=-10.0;//numeric_limits<double>::max( );
   Viewer3D<Space, KSpace>::myBoundingPtLow[2]=-10.0;//numeric_limits<double>::max( );
   Viewer3D<Space, KSpace>::myBoundingPtUp[0]=-10.0;//numeric_limits<double>::min( );
   Viewer3D<Space, KSpace>::myBoundingPtUp[1]=-10.0;//numeric_limits<double>::min( );
   Viewer3D<Space, KSpace>:: myBoundingPtUp[2]=-10.0;//numeric_limits<double>::min( );
   Viewer3D<Space, KSpace>::createNewCubeList ( );
   typename std::vector< typename Viewer3D<Space, KSpace>::CubeD3D> aKSCubeList;
   Viewer3D<Space, KSpace>::myCurrentfShiftVisuSurfelPrisms=0.0;
   Viewer3D<Space, KSpace>::myDefaultColor= Color ( 255, 255, 255 );
   camera()->showEntireScene();
   setKeyDescription ( Qt::Key_E, "Export the current display into OFF file (just Cube, surfel and SurfelPrism for now)." );
   setKeyDescription ( Qt::Key_W, "Switch display with and without wired view of triangle and quad faces." );
   setKeyDescription ( Qt::Key_T, "Sort elements for display improvements." );
   setKeyDescription ( Qt::Key_L, "Load last visualisation settings." );
   setKeyDescription ( Qt::Key_B, "Switch background color with White/Black colors." );
   setKeyDescription ( Qt::Key_C, "Show camera informations." );
   setKeyDescription ( Qt::Key_R, "Reset default scale for 3 axes to 1.0f." );
   setKeyDescription ( Qt::Key_D, "Enable/Disable the two side face rendering." );
   setKeyDescription ( Qt::Key_R, "Reset default scale for 3 axes to 1.0f." );
   glLightModeli(GL_LIGHT_MODEL_TWO_SIDE, GL_TRUE);
   setMouseBindingDescription ( Qt::ShiftModifier+Qt::RightButton, "Delete the mouse selected list." );
   setManipulatedFrame ( new ManipulatedFrame() );
 }
template<typename Space , typename KSpace > bool DGtal::Viewer3D< Space, KSpace >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 789 of file Viewer3D.ih.
 {
   return true;
 }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::keyPressEvent (QKeyEvent * e) virtual
Used to manage new key event (wich are added from the default QGLviewer keys).
Note that when a new key event is taken into account it could be added in the QGLviewer init() method to update automatically the key description in the help QGLviewer window. For instance when a new key is processed in this method you simply should add the following code in the init() method:
setKeyDescription(Qt::Key_NEW, "Description of the new Key.");
Parameters
e the QKeyEvent
Definition at line 1473 of file Viewer3D.ih.
References DGtal::Trace::info(), and DGtal::trace.
 {
   bool handled = false;
   if( e->key() == Qt::Key_D)
     {
       myIsDoubleFaceRendering = !myIsDoubleFaceRendering;
       if(myIsDoubleFaceRendering)
         glLightModeli(GL_LIGHT_MODEL_TWO_SIDE, GL_TRUE);
       else
         glLightModeli(GL_LIGHT_MODEL_TWO_SIDE, GL_FALSE);
       updateGL();
     }
   if( e->key() == Qt::Key_E)
     {
       trace.info() << "Exporting mesh..." ;
       // (*this) >> "exportedMesh.off";
       //because the template operator can't reconise the operator defined in Display3D
       operator>> <Space, KSpace>(*this, "exportedMesh.off");
       trace.info() << "[done]"<< endl ;
     }
   if ( ( e->key() ==Qt::Key_W ) )
     {
       myViewWire=!myViewWire;
       updateList(false);
       updateGL();
     }
   if ( ( e->key() ==Qt::Key_R ) )
     {
       myGLScaleFactorX=1.0f;
       myGLScaleFactorY=1.0f;
       myGLScaleFactorZ=1.0f;
       updateGL();
     }
   if ( ( e->key() ==Qt::Key_T ) )
     {
       handled=true;
       DGtal::trace.info() << "sorting surfel according camera position....";
       sortSurfelFromCamera();
       sortTriangleFromCamera();
       sortQuadFromCamera();
       sortPolygonFromCamera();
       DGtal::trace.info() << " [done]"<< std::endl;
       updateList(false);
       updateGL();
     }
   if ( ( e->key() ==Qt::Key_B ) )
     {
       handled=true;
       myIsBackgroundDefault=!myIsBackgroundDefault;
       if ( !myIsBackgroundDefault )
         {
           setBackgroundColor ( QColor ( 255, 255,255 ) );
         }
       else
         {
           setBackgroundColor ( QColor ( 51, 51, 51 ) );
         }
       updateGL();
     }
   if ( ( e->key() ==Qt::Key_L ) )
     {
       restoreStateFromFile();
       updateGL();
     }
   if ( ( e->key() ==Qt::Key_C ) ) // MT
     {
       handled=true;
       GLint Viewport[4];
       GLdouble Projection[16], Modelview[16];
       //Unused matrix so I remove it (DC)
       //GLdouble matrix[16];
       // Precomputation begin
       glGetIntegerv ( GL_VIEWPORT , Viewport );
       glGetDoublev ( GL_MODELVIEW_MATRIX , Modelview );
       glGetDoublev ( GL_PROJECTION_MATRIX, Projection );
       for ( unsigned short m=0; m<4; ++m )
         {
           for ( unsigned short l=0; l<4; ++l )
             {
               double sum = 0.0;
               for ( unsigned short k=0; k<4; ++k )
                 sum += Projection[l+4*k]*Modelview[k+4*m];
               //matrix[l+4*m] = sum;
             }
         }
       // Precomputation end
       // print
       DGtal::trace.info() << "Viewport: ";
       for ( unsigned short l=0; l<4; ++l )
         DGtal::trace.info() << Viewport[l] << ", ";
       DGtal::trace.info() << std::endl;
       Vec cp = camera()->position();
       Vec cd = camera()->viewDirection();
       Vec cup = camera()->upVector();
       DGtal::trace.info() << "camera.position: " ;
       for ( unsigned short l=0; l<3; ++l )
         DGtal::trace.info() << cp[l] << ", ";
       DGtal::trace.info() << std::endl;
       DGtal::trace.info() << "camera.direction: ";
       for ( unsigned short l=0; l<3; ++l )
         DGtal::trace.info() << cd[l] << ", ";
       DGtal::trace.info() << std::endl;
       DGtal::trace.info() << "camera.upVector: ";
       for ( unsigned short l=0; l<3; ++l )
         DGtal::trace.info() << cup[l] << ", ";
       DGtal::trace.info() << std::endl;
       DGtal::trace.info() << "zNear: " << camera()->zNear() << " - zFar: " << camera()->zFar() << std::endl;
       // print
     }
   if ( !handled )
     QGLViewer::keyPressEvent ( e );
 }
template<typename Space , typename KSpace > DGtal::Viewer3D< Space, KSpace > & DGtal::Viewer3D< Space, KSpace >::operator<< (const typename Viewer3D< Space, KSpace >::StreamKey & key) inline
Set the default color for future drawing.
Parameters
key a stream key
Returns
a reference on 'this'.
Definition at line 551 of file Viewer3D.ih.
 {
   switch (key)
     {
     case Viewer3D<Space, KSpace>::updateDisplay:
       Viewer3D<Space, KSpace>::updateList();
       break;
     case Viewer3D<Space, KSpace>::addNewList:
       Viewer3D<Space, KSpace>::createNewCubeList();
       break;
     case Viewer3D<Space, KSpace>::shiftSurfelVisu:
       Viewer3D<Space, KSpace>::myCurrentfShiftVisuSurfelPrisms+=0.3;
       break;
     }
   return *this;
 }
template<typename Space , typename KSpace > DGtal::Viewer3D< Space, KSpace > & DGtal::Viewer3D< Space, KSpace >::operator<< (const DGtal::Color & aColor) inline
Set the default color for future drawing.
Parameters
aColor a DGtal::Color (allow to set a trasnparency value).
Returns
a reference on 'this'.
Definition at line 542 of file Viewer3D.ih.
 {
   myDefaultColor=aColor;
   return *this;
 }
template<class S, class KS> template<typename TDrawableWithViewer3D > Viewer3D<Space, KSpace>& DGtal::Viewer3D< S, KS >::operator<< (const TDrawableWithViewer3D< S, KS > & object)
Draws the drawable [object] in this board. It should satisfy the concept CDrawableWithViewer3D, which requires for instance a method setStyle(Viewer3D<Space, KSpace> &).
Parameters
object any drawable object.
Returns
a reference on 'this'.
template<class S, class KS> template<typename TDrawableWithViewer3D > DGtal::Viewer3D<Space, KSpace>& DGtal::Viewer3D< S, KS >::operator<< (const TDrawableWithViewer3D< S, KS > & object) inline
Definition at line 574 of file Viewer3D.ih.
References DGtal::Viewer3DFactory< TSpace, TKSpace >::draw().
 {
   BOOST_CONCEPT_ASSERT((CDrawableWithViewer3D< TDrawableWithViewer3D, Space, KSpace >));
   DGtal::Viewer3DFactory<Space,KSpace>::draw(*this, object);
   return *this;
 }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::postSelection (const QPoint & point) virtual
postSelection
Parameters
point a point
Definition at line 934 of file Viewer3D.ih.
References DGtal::Trace::info(), and DGtal::trace.
 {
   camera()->convertClickToLine ( point, myOrig, myDir );
   bool found;
   this->myPosSelector= point;
   mySelectedPoint = camera()->pointUnderPixel ( point, found );
   if ( found )
     {
       DGtal::trace.info() << "Element of liste= " << selectedName() << "selected" << endl;
       if ( selectedName() !=-1 )
         {
           unsigned int id = abs ( selectedName()-1 );
           if ( id< Viewer3D<Space, KSpace>::myCubeSetList.size())
             {
               DGtal::trace.info() << "deleting list="<< id<<endl;
               Viewer3D<Space, KSpace>::myCubeSetList.erase ( Viewer3D<Space, KSpace>::myCubeSetList.begin() +id );
               updateList ( false );
             }
           else if ( id< Viewer3D<Space, KSpace>::myCubeSetList.size()+ Viewer3D<Space, KSpace>::myLineSetList.size() )
             {
               Viewer3D<Space, KSpace>::myLineSetList.erase ( Viewer3D<Space, KSpace>::myLineSetList.begin() + ( id- Viewer3D<Space, KSpace>::myCubeSetList.size()) );
               updateList ( false );
             }
           else if ( id< Viewer3D<Space, KSpace>::myBallSetList.size() + Viewer3D<Space, KSpace>::myLineSetList.size() + Viewer3D<Space, KSpace>::myCubeSetList.size())
             {
               Viewer3D<Space, KSpace>::myBallSetList.erase ( Viewer3D<Space, KSpace>::myBallSetList.begin() + ( id- Viewer3D<Space, KSpace>::myCubeSetList.size() - Viewer3D<Space, KSpace>::myLineSetList.size() ) );
               updateList ( false );
             }
         }
     }
 }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::rotateDomain (Image2DDomainD3D & anDom, double angle, ImageDirection rotationDir) inline
Rotate an Image2DDomainD3D from its bounding points and from its grid line.
Parameters
anDom (returns) the domain to be rotated.
angle the angle of rotation.
rotationDir the rotation will be applied around this direction.
Definition at line 66 of file Viewer3D.ih.
References DGtal::Viewer3D< S, KS >::Image2DDomainD3D::myLineSetIndex, DGtal::Viewer3D< S, KS >::Image2DDomainD3D::point1, DGtal::Viewer3D< S, KS >::Image2DDomainD3D::point2, DGtal::Viewer3D< S, KS >::Image2DDomainD3D::point3, and DGtal::Viewer3D< S, KS >::Image2DDomainD3D::point4.
{
   DGtal::PointVector<3, int> pt;
   pt[0] = (int) (anDom.point1[0]+anDom.point2[0]+anDom.point3[0]+anDom.point4[0])/4.0;
   pt[1] = (int) (anDom.point1[1]+anDom.point2[1]+anDom.point3[1]+anDom.point4[1])/4.0;
   pt[2] = (int) (anDom.point1[2]+anDom.point2[2]+anDom.point3[2]+anDom.point4[2])/4.0;
   rotateImageVertex(anDom, angleRotation, rotationDir);
   std::vector<typename DGtal::Display3D<Space, KSpace>::LineD3D> &aVectLine = Viewer3D<Space, KSpace>::myLineSetList.at(anDom.myLineSetIndex);
   for(unsigned int i = 0; i< aVectLine.size();i++){
     typename DGtal::Display3D<Space, KSpace>::LineD3D &aLine = aVectLine.at(i);
     rotateLineD3D(aLine, pt, angleRotation, rotationDir );
   }
 }
template<class S, class KS> template<typename TImageORDomain > static void DGtal::Viewer3D< S, KS >::rotateImageVertex (TImageORDomain & anImageOrDom, double angle, ImageDirection rotationDir) inline static
Rotate Image2DDomainD3D or TextureImage vertex from a given angle and a rotation direction. The center of rotation is defined from the image center point.
Template Parameters
TImageORDomain the type object to be rotated (should be an Image2DDomainD3D or a TextureImage)
Parameters
anImageOrDom (returns) the domain or image to be rotated.
angle the angle of the rotation.
rotationDir the rotation is applied around this axis direction.
Definition at line 1035 of file Viewer3D.h.
{
       double xB = (anImageOrDom.point1[0]+anImageOrDom.point2[0]+anImageOrDom.point3[0]+anImageOrDom.point4[0])/4.0;
       double yB = (anImageOrDom.point1[1]+anImageOrDom.point2[1]+anImageOrDom.point3[1]+anImageOrDom.point4[1])/4.0;
       double zB = (anImageOrDom.point1[2]+anImageOrDom.point2[2]+anImageOrDom.point3[2]+anImageOrDom.point4[2])/4.0;
       rotatePoint( anImageOrDom.point1[0],  anImageOrDom.point1[1], anImageOrDom.point1[2],   xB, yB, zB, angle, rotationDir);
       rotatePoint( anImageOrDom.point2[0],  anImageOrDom.point2[1], anImageOrDom.point2[2],   xB, yB, zB, angle, rotationDir);
       rotatePoint( anImageOrDom.point3[0],  anImageOrDom.point3[1], anImageOrDom.point3[2],   xB, yB, zB, angle, rotationDir);
       rotatePoint( anImageOrDom.point4[0],  anImageOrDom.point4[1], anImageOrDom.point4[2],   xB, yB, zB, angle, rotationDir);
     }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::rotateLineD3D (typename DGtal::Display3D< Space, KSpace >::LineD3D & aLine, DGtal::PointVector< 3, int > pt, double angleRotation, ImageDirection dirRotation) inline
Rotate an lineD3D from its two extremity points.
Parameters
aLine (returns) the line to be rotated.
pt the center of rotation.
angleRotation the angle of rotation.
dirRotation the rotation will be applied around this direction.
Definition at line 109 of file Viewer3D.ih.
References DGtal::Trace::error(), DGtal::Display3D< Space, KSpace >::LineD3D::point1, DGtal::Display3D< Space, KSpace >::LineD3D::point2, and DGtal::trace.
{
   double dx1 = aLine.point1[0] - pt[0]; double dy1 = aLine.point1[1] - pt[1]; double dz1 = aLine.point1[2] - pt[2];
   double dx2 = aLine.point2[0] - pt[0]; double dy2 = aLine.point2[1] - pt[1]; double dz2 = aLine.point2[2] - pt[2];
   if(dirRotation==zDirection){
      aLine.point1[0]=pt[0]+dx1*std::cos(angleRotation)-dy1*std::sin(angleRotation);
      aLine.point1[1]=pt[1]+dx1*std::sin(angleRotation)+dy1*std::cos(angleRotation);
      aLine.point2[0]=pt[0]+dx2*std::cos(angleRotation)-dy2*std::sin(angleRotation);
      aLine.point2[1]=pt[1]+dx2*std::sin(angleRotation)+dy2*std::cos(angleRotation);
   }else if(dirRotation==xDirection){
     aLine.point1[1]=pt[1]+dy1*std::cos(angleRotation)-dz1*std::sin(angleRotation);
     aLine.point1[2]=pt[2]+dy1*std::sin(angleRotation)+dz1*std::cos(angleRotation);
     aLine.point2[1]=pt[1]+dy2*std::cos(angleRotation)-dz2*std::sin(angleRotation);
     aLine.point2[2]=pt[2]+dy2*std::sin(angleRotation)+dz2*std::cos(angleRotation);
   }else  if(dirRotation==yDirection){
     aLine.point1[0]=pt[0]+dx1*std::cos(angleRotation)-dz1*std::sin(angleRotation);
     aLine.point1[2]=pt[2]+dx1*std::sin(angleRotation)+dz1*std::cos(angleRotation);
     aLine.point2[0]=pt[0]+dx2*std::cos(angleRotation)-dz2*std::sin(angleRotation);
     aLine.point2[2]=pt[2]+dx2*std::sin(angleRotation)+dz2*std::cos(angleRotation);
   }else{
     trace.error() << "No direction!!"<< std::endl;
   }
 }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::rotatePoint (double & x, double & y, double & z, double cx, double cy, double cz, double rotationAngle, ImageDirection rotationDir) inline static
Rotate a vertex from a given angle, a center point and a rotation direction.
Parameters
x the x coordinate of the point to rotated (return).
y the y coordinate of the point to rotated (return).
z the z coordinate of the point to rotated (return).
cx the x coordinate of the rotation center.
cy the y coordinate of the rotation center.
cz the z coordinate of the rotation center.
rotationAngle the angle of the rotation.
rotationDir the rotation is applied around this axis direction.
Definition at line 86 of file Viewer3D.ih.
Referenced by DGtal::Viewer3D< Space, KSpace >::rotateImageVertex().
{
   double dx = x-cx; double dy = y-cy; double dz = z-cz;
   if(rotationDir  == zDirection){
     x = cx+dx*cos(angleRotation)-dy*sin(angleRotation);
     y = cy+dx*sin(angleRotation)+dy*cos(angleRotation);
   }
   if(rotationDir  == yDirection){
     x = cx+dx*cos(angleRotation)-dz*sin(angleRotation);
     z = cz+dx*sin(angleRotation)+dz*cos(angleRotation);
   }
   if(rotationDir  == xDirection){
     y = cy+dy*cos(angleRotation)-dz*sin(angleRotation);
     z = cz+dy*sin(angleRotation)+dz*cos(angleRotation);
   }
 }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 781 of file Viewer3D.ih.
 {
   out << "[Viewer3D]";
 }
template<class S, class KS> void DGtal::Viewer3D< S, KS >::setCameraDirection (double ax, double ay, double az) inline
Set camera direction.
Parameters
ax x direction.
ay y direction.
az z direction.
Definition at line 170 of file Viewer3D.h.
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::draw().
     {
       camera_direction[0] = ax; camera_direction[1] = ay; camera_direction[2] = az;
     }
template<class S, class KS> void DGtal::Viewer3D< S, KS >::setCameraPosition (double ax, double ay, double az) inline
Set camera position.
Parameters
ax x position.
ay y position.
az z position.
Definition at line 159 of file Viewer3D.h.
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::draw().
     {
       camera_position[0] = ax; camera_position[1] = ay; camera_position[2] = az;
     }
template<class S, class KS> void DGtal::Viewer3D< S, KS >::setCameraUpVector (double ax, double ay, double az) inline
Set camera up-vector.
Parameters
ax x coordinate of up-vector.
ay y coordinate of up-vector.
az z coordinate of up-vector.
Definition at line 181 of file Viewer3D.h.
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::draw().
     {
       camera_upVector[0] = ax; camera_upVector[1] = ay; camera_upVector[2] = az;
     }
template<class S, class KS> void DGtal::Viewer3D< S, KS >::setGLScale (float sx, float sy, float sz) inline
Set the open gl scale of x,y,z axis. It doesn't change the geometry of anything, it is just visualisation parameter (useful to produce more realistic 3D volume display)
Parameters
sx the scale on the x axis.
sy the scale on the y axis.
sz the scale on the z axis.
Definition at line 205 of file Viewer3D.h.
     {
       myGLScaleFactorX=sx;
       myGLScaleFactorY=sy;
       myGLScaleFactorZ=sz;
     }
template<class S, class KS> void DGtal::Viewer3D< S, KS >::setNearFar (double _near, double _far) inline
Set near and far distance, too near or too far end up not visible.
Parameters
_near near distance.
_far far distance.
Definition at line 191 of file Viewer3D.h.
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::draw().
     {
       ZNear = _near; ZFar = _far;
     }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::sortPolygonFromCamera ()
Sort all polygons from the camera.
Definition at line 916 of file Viewer3D.ih.
References DGtal::Trace::info(), DGtal::Viewer3D< S, KS >::CompFarthestPolygonFromCamera::posCam, and DGtal::trace.
 {
   CompFarthestPolygonFromCamera comp;
   comp.posCam= camera()->position();
   for (typename std::vector<std::vector< typename Viewer3D<Space, KSpace>::PolygonD3D> >::iterator it = Viewer3D<Space, KSpace>::myPolygonSetList.begin(); it != Viewer3D<Space, KSpace>:: myPolygonSetList.end(); it++)
     {
       DGtal::trace.info() << "sort polygon size" << it->size() << std::endl;
       sort ( it->begin(), it->end(), comp );
     }
 }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::sortQuadFromCamera ()
Sort all triangle from the camera.
Definition at line 900 of file Viewer3D.ih.
References DGtal::Trace::info(), DGtal::Viewer3D< S, KS >::CompFarthestSurfelFromCamera::posCam, and DGtal::trace.
 {
   CompFarthestSurfelFromCamera comp;
   comp.posCam= camera()->position();
   for (typename std::vector<std::vector< typename Viewer3D<Space, KSpace>::QuadD3D> >::iterator it = Viewer3D<Space, KSpace>::myQuadSetList.begin(); it != Viewer3D<Space, KSpace>::myQuadSetList.end(); it++)
     {
       DGtal::trace.info() << "sort quad size" << it->size() << std::endl;
       sort ( it->begin(), it->end(), comp );
     }
 }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::sortSurfelFromCamera ()
Sort all surfels from the camera.
Definition at line 868 of file Viewer3D.ih.
References DGtal::Trace::info(), DGtal::Viewer3D< S, KS >::CompFarthestVoxelFromCamera::posCam, and DGtal::trace.
 {
   CompFarthestVoxelFromCamera comp;
   comp.posCam= camera()->position();
   for ( unsigned int i=0; i< Viewer3D<Space, KSpace>::myCubeSetList.size() ; i++ )
     {
       sort ( Viewer3D<Space, KSpace>::myCubeSetList.at ( i ).begin(), Viewer3D<Space, KSpace>::myCubeSetList.at ( i ).end(), comp );
     }
   CompFarthestSurfelFromCamera compSurf;
   DGtal::trace.info() << "sort surfel size" << Viewer3D<Space, KSpace>::mySurfelPrismList.size() << std::endl;
   sort ( Viewer3D<Space, KSpace>::mySurfelPrismList.begin(), Viewer3D<Space, KSpace>::mySurfelPrismList.end(), compSurf );
 }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::sortTriangleFromCamera ()
Sort all triangle from the camera.
Definition at line 884 of file Viewer3D.ih.
References DGtal::Trace::info(), DGtal::Viewer3D< S, KS >::CompFarthestTriangleFromCamera::posCam, and DGtal::trace.
 {
   CompFarthestTriangleFromCamera comp;
   comp.posCam= camera()->position();
   for (typename std::vector<std::vector< typename Viewer3D<Space, KSpace>::TriangleD3D> >::iterator it = Viewer3D<Space, KSpace>::myTriangleSetList.begin(); it != Viewer3D<Space, KSpace>::myTriangleSetList.end(); it++)
     {
       DGtal::trace.info() << "sort triangle size" << it->size() << std::endl;
       sort ( it->begin(), it->end(), comp );
     }
 }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::translateAn2DDomain (unsigned int domainIndex, double xTranslation, double yTranslation, double zTranslation) inline
translate a 2D domain
Parameters
domainIndex the index of the domain in the list
xTranslation x part of the translation vector
yTranslation y part of the translation vector
zTranslation z part of the translation vector
Definition at line 513 of file Viewer3D.ih.
References DGtal::Viewer3D< S, KS >::Image2DDomainD3D::myLineSetIndex, DGtal::Display3D< Space, KSpace >::LineD3D::point1, DGtal::Viewer3D< S, KS >::Image2DDomainD3D::point1, DGtal::Display3D< Space, KSpace >::LineD3D::point2, DGtal::Viewer3D< S, KS >::Image2DDomainD3D::point2, DGtal::Viewer3D< S, KS >::Image2DDomainD3D::point3, DGtal::Viewer3D< S, KS >::Image2DDomainD3D::point4, and DGtal::Viewer3D< S, KS >::Image2DDomainD3D::translateDomain().
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::draw().
 {
   typename Viewer3D< Space ,KSpace >::Image2DDomainD3D &anDomain = myImageDomainList.at(domainIndex);
   anDomain.translateDomain(xTranslation, yTranslation, zTranslation);
   Display3D< Space, KSpace>::updateBoundingBox(anDomain.point1);
   Display3D< Space, KSpace>::updateBoundingBox(anDomain.point2);
   Display3D< Space, KSpace>::updateBoundingBox(anDomain.point3);
   Display3D< Space, KSpace>::updateBoundingBox(anDomain.point4);
   std::vector<typename DGtal::Display3D<Space, KSpace>::LineD3D> &vectLines = Viewer3D<Space,KSpace>::myLineSetList.at(anDomain.myLineSetIndex);
   for(unsigned int i=0; i<vectLines.size(); i++){
     typename DGtal::Display3D<Space,KSpace>::LineD3D &aLine = vectLines.at(i);
     aLine.point1[0]=aLine.point1[0]+xTranslation; aLine.point1[1]=aLine.point1[1]+yTranslation; aLine.point1[2]=aLine.point1[2]+zTranslation;
     aLine.point2[0]=aLine.point2[0]+xTranslation; aLine.point2[1]=aLine.point2[1]+yTranslation; aLine.point2[2]=aLine.point2[2]+zTranslation;
   }
 }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::updateAn2DDomainOrientation (unsigned int imageIndex, double xPosition, double yPosition, double zPosition, ImageDirection newDirection) inline
update a 2D domain orientation
Parameters
imageIndex index of the image in the list
xPosition the x position
yPosition the y position
zPosition the z position
newDirection the new direction
Definition at line 486 of file Viewer3D.ih.
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::draw().
 {
   ASSERT( domainIndex < myImageDomainList.size());
   typename Viewer3D< Space ,KSpace >::Image2DDomainD3D &aDomain = myImageDomainList.at(domainIndex);
   Display3D< Space, KSpace>::updateBoundingBox(aDomain.point1);
   Display3D< Space, KSpace>::updateBoundingBox(aDomain.point2);
   Display3D< Space, KSpace>::updateBoundingBox(aDomain.point3);
   Display3D< Space, KSpace>::updateBoundingBox(aDomain.point4);
   aDomain.updateDomainOrientation(newDirection, xPosition, yPosition, zPosition);
   std::vector<typename DGtal::Viewer3D< Space ,KSpace >::LineD3D> vectNewLines= compute2DDomainLineRepresentation(aDomain);
   std::vector<typename DGtal::Viewer3D< Space ,KSpace >::LineD3D> &vectLines = Viewer3D<Space, KSpace>::myLineSetList.at(aDomain.myLineSetIndex);
   vectLines.clear();
   for(unsigned int i=0; i<vectNewLines.size(); i++)
     {
       vectLines.push_back(vectNewLines.at(i));
     }
 }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::updateEmbeddingTextureImage (unsigned int anImageIndex, typename Space::Point aPoint1, typename Space::Point aPoint2, typename Space::Point aPoint3, typename Space::Point aPoint4) inline
Update the vertex coordinates of the image embedded in 3D.
Parameters
anImageIndex corresponds to the chronoloigic index given by the fuction (addTextureImage).
aPoint1 the new first point position embedded in 3D associated the lower point of the 2D image.
aPoint2 the new second point position embedded in 3D (in CCW order).
aPoint3 the new third point position embedded in 3D associated the upper point of the 2D image.
aPoint4 the new fourth point position embedded in 3D (in CCW order).
Definition at line 224 of file Viewer3D.ih.
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::draw().
 {
   assert ( anImageIndex< myGSImageList.size());
   typename Viewer3D< Space ,KSpace >::TextureImage &anImage = myGSImageList.at(anImageIndex);
   Display3D< Space, KSpace>::updateBoundingBox(aPoint1);
   Display3D< Space, KSpace>::updateBoundingBox(aPoint2);
   Display3D< Space, KSpace>::updateBoundingBox(aPoint3);
   Display3D< Space, KSpace>::updateBoundingBox(aPoint4);
   anImage.updateImage3DEmbedding(aPoint1, aPoint2, aPoint3, aPoint4);
 }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::updateList (bool needToUpdateBoundingBox = true)
Permit to update the OpenGL list to be displayed. Need to called after a number of addVoxel or after a sortSurfelFromCamera().
Parameters
needToUpdateBoundingBox flag to update the bounding box
Definition at line 970 of file Viewer3D.ih.
References DGtal::Viewer3D< S, KS >::GLTextureImage::myBufferHeight, DGtal::Viewer3D< S, KS >::GLTextureImage::myBufferWidth, DGtal::Viewer3D< S, KS >::GLTextureImage::myMode, DGtal::Viewer3D< S, KS >::GLTextureImage::myTextureImageBufferGS, DGtal::Viewer3D< S, KS >::GLTextureImage::myTextureImageBufferRGB, and DGtal::Viewer3D< S, KS >::GLTextureImage::myTextureName.
 {
   // Additionnaly to the primitive list (of myCubeSetList myLineSetList.size() myBallSetList.size()) we add
   // 6 new lists associated to the mesh Display.
   unsigned int nbList= ( unsigned int ) ( Viewer3D<Space, KSpace>::myCubeSetList.size()+
                                           Viewer3D<Space, KSpace>::myLineSetList.size() +
                                           Viewer3D<Space, KSpace>::myBallSetList.size() +6 );
   glDeleteLists ( myListToAff, myNbListe );
   myListToAff = glGenLists ( nbList );
   myNbListe=0;
   unsigned int listeID=0;
   glEnable ( GL_BLEND );
   glEnable ( GL_MULTISAMPLE_ARB );
   glEnable ( GL_SAMPLE_ALPHA_TO_COVERAGE_ARB );
   glBlendFunc ( GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA );
   //OPT new
   typedef typename std::vector<typename Viewer3D<Space, KSpace>::CubeD3D> vectorCubes;
   typedef typename vectorCubes::iterator ItCube;
   std::vector<ItCube> listIt;
   std::vector<ItCube> listEnd;
   int nbCubes =0;
   unsigned int i =0; //number of lists in myCubeSetList already added to listToAff
   //adding all the unvoid lists of cubes to draw
   for (typename std::vector<vectorCubes >::iterator it = Viewer3D<Space, KSpace>::myCubeSetList.begin() ;
        it != Viewer3D<Space, KSpace>::myCubeSetList.end() ; it++ )
     {
       if ((*it).size() > 0 || (*it).begin() != (*it).end() )
         {
           nbCubes += (*it).size();
           listIt.push_back((*it).begin());
           listEnd.push_back((*it).end());
         }
       else
         {
           //create void lists
           glNewList ( myListToAff+i , GL_COMPILE );
           myNbListe++;
           glPushName ( myNbListe );
           glBegin ( GL_QUADS );
           glEnd();
           glEndList();
           i++;
         }
     }
   if (listIt.size() > 0)
     {
       glNewList ( myListToAff+i , GL_COMPILE );
       myNbListe++;
       glPushName ( myNbListe );
       glBegin ( GL_QUADS );
       i++;
       qglviewer::Vec posCam = camera()->position();
       while (listIt.size() > 0)
         {
           //searchin the farest cube between the lists
           typename std::vector<ItCube>::iterator itBest= listIt.begin();
           typename std::vector<ItCube>::iterator endBest= listEnd.begin();
           typename std::vector<ItCube>::iterator itEnd =  listEnd.begin();
           for ( typename std::vector<ItCube>::iterator it = listIt.begin(); it != listIt.end(); it++)
             {
               typename Viewer3D<Space, KSpace>::CubeD3D s1 = (**it);
               typename Viewer3D<Space, KSpace>::CubeD3D s2 = (**itBest);
               double dist1= sqrt ( ( posCam.x-s1.center[0] ) * ( posCam.x-s1.center[0] ) +
                                    ( posCam.y-s1.center[1] ) * ( posCam.y-s1.center[1] ) +
                                    ( posCam.z-s1.center[2] ) * ( posCam.z-s1.center[2] ) );
               double dist2= sqrt ( ( posCam.x-s2.center[0] ) * ( posCam.x-s2.center[0] ) +
                                    ( posCam.y-s2.center[1] ) * ( posCam.y-s2.center[1] ) +
                                    ( posCam.z-s2.center[2] ) * ( posCam.z-s2.center[2] ) );
               //check if the if the cube is the farhest or the most included( the most small)
               if (( it != itBest) and
                   (
                    (( (dist2 + (2*s2.width)) - (dist1-(2*s1.width)) ) < 0)
                    or( ( dist1-s1.width == dist2 - s2.width) and (dist1 > dist2) )
                    or( (( (dist2 + (2*s2.width)) - (dist1 -(2*s1.width)) ) > 0) and (s1.color.alpha() > s2.color.alpha()) )
                    )
                   )
                 {
                   itBest= it;
                   endBest= itEnd;
                 }
               itEnd++;
             }
           typename Viewer3D<Space, KSpace>::CubeD3D cube = (**itBest);
           glColor4ub ( cube.color.red(), cube.color.green(), cube.color.blue(), cube.color.alpha() );
           double _width= cube.width;
           //z+
           glNormal3f ( 0.0, 0.0, 1.0 );
           glVertex3f ( cube.center[0]-_width, cube.center[1]+_width, cube.center[2]+_width );
           glVertex3f ( cube.center[0]-_width, cube.center[1]-_width, cube.center[2]+_width );
           glVertex3f ( cube.center[0]+_width, cube.center[1]-_width, cube.center[2]+_width );
           glVertex3f ( cube.center[0]+_width, cube.center[1]+_width, cube.center[2]+_width );
           //z-
           glNormal3f ( 0.0, 0.0, -1.0 );
           glVertex3f ( cube.center[0]-_width, cube.center[1]+_width, cube.center[2]-_width );
           glVertex3f ( cube.center[0]+_width, cube.center[1]+_width, cube.center[2]-_width );
           glVertex3f ( cube.center[0]+_width, cube.center[1]-_width, cube.center[2]-_width );
           glVertex3f ( cube.center[0]-_width, cube.center[1]-_width, cube.center[2]-_width );
           //x+
           glNormal3f ( 1.0, 0.0, 0.0 );
           glVertex3f ( cube.center[0]+_width, cube.center[1]-_width, cube.center[2]+_width );
           glVertex3f ( cube.center[0]+_width, cube.center[1]-_width, cube.center[2]-_width );
           glVertex3f ( cube.center[0]+_width, cube.center[1]+_width, cube.center[2]-_width );
           glVertex3f ( cube.center[0]+_width, cube.center[1]+_width, cube.center[2]+_width );
           //x-
           glNormal3f ( -1.0, 0.0, 0.0 );
           glVertex3f ( cube.center[0]-_width, cube.center[1]-_width, cube.center[2]+_width );
           glVertex3f ( cube.center[0]-_width, cube.center[1]+_width, cube.center[2]+_width );
           glVertex3f ( cube.center[0]-_width, cube.center[1]+_width, cube.center[2]-_width );
           glVertex3f ( cube.center[0]-_width, cube.center[1]-_width, cube.center[2]-_width );
           //y+
           glNormal3f ( 0.0, 1.0, 0.0 );
           glVertex3f ( cube.center[0]-_width, cube.center[1]+_width, cube.center[2]+_width );
           glVertex3f ( cube.center[0]+_width, cube.center[1]+_width, cube.center[2]+_width );
           glVertex3f ( cube.center[0]+_width, cube.center[1]+_width, cube.center[2]-_width );
           glVertex3f ( cube.center[0]-_width, cube.center[1]+_width, cube.center[2]-_width );
           //y-
           glNormal3f ( 0.0, -1.0, 0.0 );
           glVertex3f ( cube.center[0]-_width, cube.center[1]-_width, cube.center[2]+_width );
           glVertex3f ( cube.center[0]-_width, cube.center[1]-_width, cube.center[2]-_width );
           glVertex3f ( cube.center[0]+_width, cube.center[1]-_width, cube.center[2]-_width );
           glVertex3f ( cube.center[0]+_width, cube.center[1]-_width, cube.center[2]+_width );
           //increment the list where the farthest cube were and remove it if ended
           (*itBest) ++;
           if ((*itBest) == (*endBest) )
             {
               listIt.erase(itBest);
               listEnd.erase(endBest);
               glEnd();
               glEndList();
               if (listIt.size() >0)
                 {
                   glNewList ( myListToAff+i , GL_COMPILE );
                   myNbListe++;
                   glPushName ( myNbListe );
                   glBegin ( GL_QUADS );
                   i++;
                 }
             }
         }
     }
   glNewList ( GLuint ( myListToAff+Viewer3D<Space, KSpace>::myCubeSetList.size()), GL_COMPILE );
   myNbListe++;
   glPushName ( myNbListe );
   glEnable ( GL_DEPTH_TEST );
   glEnable ( GL_BLEND );
   glEnable ( GL_MULTISAMPLE_ARB );
   glEnable ( GL_SAMPLE_ALPHA_TO_COVERAGE_ARB );
   glBlendFunc ( GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA );
   glBegin ( GL_QUADS );
   glEnable ( GL_DEPTH_TEST );
   for ( typename std::vector<typename Viewer3D<Space, KSpace>::QuadD3D>::iterator s_it = Viewer3D<Space, KSpace>::mySurfelPrismList.begin();
         s_it != Viewer3D<Space, KSpace>::mySurfelPrismList.end();
         ++s_it )
     {
       glColor4ub ( ( *s_it ).color.red(), ( *s_it ).color.green(), ( *s_it ).color.blue(), ( *s_it ).color.alpha() );
       glNormal3f ( ( *s_it ).nx, ( *s_it ).ny, ( *s_it ).nz );
       glVertex3f ( ( *s_it ).point1[0], ( *s_it ).point1[1] , ( *s_it ).point1[2] );
       glVertex3f ( ( *s_it ).point2[0], ( *s_it ).point2[1] , ( *s_it ).point2[2] );
       glVertex3f ( ( *s_it ).point3[0], ( *s_it ).point3[1] , ( *s_it ).point3[2] );
       glVertex3f ( ( *s_it ).point4[0], ( *s_it ).point4[1] , ( *s_it ).point4[2] );
     }
   glEnd();
   glEndList();
   for ( unsigned int j=0; j<Viewer3D<Space, KSpace>::myLineSetList.size(); j++ )
     {
       listeID++;
       glNewList ( GLuint ( myListToAff+Viewer3D<Space, KSpace>::myCubeSetList.size()+j+1 ), GL_COMPILE );
       myNbListe++;
       glDisable ( GL_LIGHTING );
       glPushName ( myNbListe );
       glBegin ( GL_LINES );
       for ( typename std::vector<typename Viewer3D<Space, KSpace>::LineD3D>::iterator s_it = Viewer3D<Space, KSpace>::myLineSetList.at ( j ).begin();
             s_it != Viewer3D<Space, KSpace>::myLineSetList.at ( j ).end();
             ++s_it )
         {
           glColor4ub ( ( *s_it ).color.red(), ( *s_it ).color.green(), ( *s_it ).color.blue(), ( *s_it ).color.alpha() );
           glVertex3f ( ( *s_it ).point1[0], ( *s_it ).point1[1], ( *s_it ).point1[2] );
           glVertex3f ( ( *s_it ).point2[0], ( *s_it ).point2[1], ( *s_it ).point2[2] );
         }
       glEnd();
       glEnable ( GL_LIGHTING );
       glEndList();
     }
   for ( unsigned int j=0; j<Viewer3D<Space, KSpace>::myBallSetList.size(); j++ )
     {
       glNewList ( GLuint ( myListToAff+Viewer3D<Space, KSpace>::myLineSetList.size() +Viewer3D<Space, KSpace>::myCubeSetList.size()+j+1 ), GL_COMPILE );
       myNbListe++;
       glDepthMask ( GL_TRUE );
       glDisable ( GL_TEXTURE_2D );
       glDisable ( GL_POINT_SMOOTH );
       glDisable ( GL_LIGHTING );
       glPushName ( myNbListe );
       glBegin ( GL_POINTS );
       for ( typename std::vector<typename Viewer3D<Space, KSpace>::BallD3D>::iterator s_it = Viewer3D<Space, KSpace>::myBallSetList.at ( j ).begin();
             s_it != Viewer3D<Space, KSpace>::myBallSetList.at ( j ).end();
             ++s_it )
         {
           glColor4ub ( ( *s_it ).color.red(), ( *s_it ).color.green(), ( *s_it ).color.blue(), ( *s_it ).color.alpha() );
           glVertex3f ( ( *s_it ).center[0], ( *s_it ).center[1], ( *s_it ).center[2] );
         }
       glEnd();
       glEnable ( GL_LIGHTING );
       glEndList();
     }
   // Creation of new lists to display 3D mesh
   // First list: quad faces.
   // Second list: Wired version of quad face.
   // Third list: Triangle faces.
   // Fourth list: Wired version of triangle face.
   // Fifth list: Polygonal faces.
   // Sixth list: Wired version of polygonal face.
   unsigned int nbListOfPrimitives = Viewer3D<Space, KSpace>::myLineSetList.size() +Viewer3D<Space, KSpace>::myCubeSetList.size()+ Viewer3D<Space, KSpace>::myBallSetList.size();
   // First List (quad faces)
   glNewList ( GLuint ( myListToAff +nbListOfPrimitives + 1 ), GL_COMPILE );
   myNbListe++;
   glPushName ( myNbListe );
   glEnable ( GL_LIGHTING );
   glBegin ( GL_QUADS );
   for (typename std::vector<std::vector<typename Viewer3D<Space, KSpace>::QuadD3D> >::iterator it = Viewer3D<Space, KSpace>::myQuadSetList.begin(); it != Viewer3D<Space, KSpace>::myQuadSetList.end(); it++)
     {
       for (typename std::vector<typename Viewer3D<Space, KSpace>::QuadD3D>::iterator it_s = it->begin(); it_s != it->end(); it_s++)
         {
           glColor4ub ( it_s->color.red(), it_s->color.green(), it_s->color.blue(), it_s->color.alpha() );
           glNormal3f ( it_s->nx, it_s->ny ,it_s->nz );
           glVertex3f ( it_s->point1[0], it_s->point1[1], it_s->point1[2] );
           glVertex3f ( it_s->point2[0], it_s->point2[1], it_s->point2[2] );
           glVertex3f ( it_s->point3[0], it_s->point3[1], it_s->point3[2] );
           glVertex3f ( it_s->point4[0], it_s->point4[1], it_s->point4[2] );
         }
     }
   glEnd();
   glEndList();
   // Second list: Wired version of quad face.
   glNewList ( GLuint ( myListToAff +nbListOfPrimitives + 2 ), GL_COMPILE );
   myNbListe++;
   glPushName ( myNbListe );
   glDisable ( GL_LIGHTING );
   glBegin ( GL_LINES );
   for (typename std::vector<std::vector<typename Viewer3D<Space, KSpace>::QuadD3D> >::iterator it = Viewer3D<Space, KSpace>::myQuadSetList.begin(); it != Viewer3D<Space, KSpace>::myQuadSetList.end(); it++)
     {
       for (typename std::vector<typename Viewer3D<Space, KSpace>::QuadD3D>::iterator it_s = it->begin(); it_s != it->end(); it_s++)
         {
           glColor4ub ( 150.0,150.0,150.0,255.0 );
           glColor4ub ( Viewer3D<Space, KSpace>::myCurrentLineColor.red(), Viewer3D<Space, KSpace>::myCurrentLineColor.green(), Viewer3D<Space, KSpace>::myCurrentLineColor.blue() , Viewer3D<Space, KSpace>::myCurrentLineColor.alpha() );
           glVertex3f ( it_s->point1[0], it_s->point1[1], it_s->point1[2] );
           glVertex3f ( it_s->point2[0], it_s->point2[1], it_s->point2[2] );
           glVertex3f ( it_s->point2[0], it_s->point2[1], it_s->point2[2] );
           glColor4ub ( Viewer3D<Space, KSpace>::myCurrentLineColor.red(), Viewer3D<Space, KSpace>::myCurrentLineColor.green(), Viewer3D<Space, KSpace>::myCurrentLineColor.blue() , Viewer3D<Space, KSpace>::myCurrentLineColor.alpha() );
           glVertex3f ( it_s->point3[0], it_s->point3[1], it_s->point3[2] );
           glVertex3f ( it_s->point3[0], it_s->point3[1], it_s->point3[2] );
           glVertex3f ( it_s->point4[0], it_s->point4[1], it_s->point4[2] );
           glColor4ub ( Viewer3D<Space, KSpace>::myCurrentLineColor.red(), Viewer3D<Space, KSpace>::myCurrentLineColor.green(), Viewer3D<Space, KSpace>::myCurrentLineColor.blue() , Viewer3D<Space, KSpace>::myCurrentLineColor.alpha() );
           glVertex3f ( it_s->point4[0], it_s->point4[1], it_s->point4[2] );
           glVertex3f(it_s->point1[0], it_s->point1[1], it_s->point1[2]);
         }
     }
   glEnable ( GL_LIGHTING );
   glEnd();
   glEndList();
   // Third list: Triangle faces.
   glNewList ( GLuint (myListToAff +nbListOfPrimitives + 3 ), GL_COMPILE );
   myNbListe++;
   glPushName ( myNbListe );
   glEnable ( GL_LIGHTING );
   glBegin ( GL_TRIANGLES );
   for (typename std::vector<std::vector<typename Viewer3D<Space, KSpace>::TriangleD3D> >::iterator it = Viewer3D<Space, KSpace>::myTriangleSetList.begin(); it != Viewer3D<Space, KSpace>::myTriangleSetList.end(); it++)
     {
       for (typename std::vector<typename Viewer3D<Space, KSpace>::TriangleD3D>::iterator it_s = it->begin(); it_s != it->end(); it_s++)
         {
           glColor4ub (it_s->color.red(),it_s->color.green(),it_s->color.blue(),it_s->color.alpha() );
           glNormal3f (it_s->nx,it_s->ny ,it_s->nz );
           glVertex3f (it_s->point1[0],it_s->point1[1],it_s->point1[2] );
           glVertex3f (it_s->point2[0],it_s->point2[1],it_s->point2[2] );
           glVertex3f (it_s->point3[0],it_s->point3[1],it_s->point3[2] );
         }
     }
   glEnd();
   glEndList();
   // Fourth list: Wired version of triangle face.
   glNewList ( GLuint ( myListToAff + nbListOfPrimitives +4), GL_COMPILE );
   myNbListe++;
   glPushName ( myNbListe );
   glDisable ( GL_LIGHTING );
   glBegin ( GL_LINES );
   for (typename std::vector<std::vector<typename Viewer3D<Space, KSpace>::TriangleD3D> >::iterator it = Viewer3D<Space, KSpace>::myTriangleSetList.begin(); it != Viewer3D<Space, KSpace>::myTriangleSetList.end(); it++)
     {
       for (typename std::vector<typename Viewer3D<Space, KSpace>::TriangleD3D>::iterator it_s = it->begin(); it_s != it->end(); it_s++)
         {
           glColor4ub ( Viewer3D<Space, KSpace>::myCurrentLineColor.red(), Viewer3D<Space, KSpace>::myCurrentLineColor.green(), Viewer3D<Space, KSpace>::myCurrentLineColor.blue() , Viewer3D<Space, KSpace>::myCurrentLineColor.alpha() );
           glVertex3f (it_s->point1[0],it_s->point1[1],it_s->point1[2] );
           glVertex3f (it_s->point2[0],it_s->point2[1],it_s->point2[2] );
           glVertex3f (it_s->point2[0],it_s->point2[1],it_s->point2[2] );
           glVertex3f (it_s->point3[0],it_s->point3[1],it_s->point3[2] );
           glVertex3f (it_s->point3[0],it_s->point3[1],it_s->point3[2] );
           glVertex3f (it_s->point1[0],it_s->point1[1],it_s->point1[2] );
         }
     }
   glEnd();
   glEnable ( GL_LIGHTING );
   glEndList();
   // Fifth list: Polygonal faces.
   glNewList ( GLuint (myListToAff + nbListOfPrimitives +5 ), GL_COMPILE );
   myNbListe++;
   glPushName ( myNbListe );
   glEnable ( GL_LIGHTING );
   for (typename std::vector<std::vector<typename Viewer3D<Space, KSpace>::PolygonD3D> >::iterator it = Viewer3D<Space, KSpace>::myPolygonSetList.begin();
        it != Viewer3D<Space, KSpace>::myPolygonSetList.end(); it++)
     {
       for (typename std::vector<typename Viewer3D<Space, KSpace>::PolygonD3D>::iterator it_s = it->begin(); it_s != it->end(); it_s++)
         {
           glBegin ( GL_POLYGON );
           glColor4ub ( it_s->color.red(), it_s->color.green(), it_s->color.blue(), it_s->color.alpha() );
           glNormal3f ( it_s->nx, it_s->ny ,it_s->nz );
           for(unsigned int j=0;j < (it_s->vertices).size();j++)
             {
               glVertex3f ( (it_s->vertices).at(j)[0], (it_s->vertices).at(j)[1], (it_s->vertices).at ( j )[2] );
             }
           glEnd();
         }
     }
   glEndList();
   // Sixth list: Wired version of polygonal face.
   glNewList ( GLuint (myListToAff + nbListOfPrimitives +6 ), GL_COMPILE );
   myNbListe++;
   glPushName ( myNbListe );
   glDisable ( GL_LIGHTING );
   glBegin ( GL_LINES );
   for (typename std::vector<std::vector<typename Viewer3D<Space, KSpace>::PolygonD3D> >::iterator it = Viewer3D<Space, KSpace>::myPolygonSetList.begin();
        it != Viewer3D<Space, KSpace>::myPolygonSetList.end(); it++)
     {
       for (typename std::vector<typename Viewer3D<Space, KSpace>::PolygonD3D>::iterator it_s = it->begin(); it_s != it->end(); it_s++)
         {
           glColor4ub ( Viewer3D<Space, KSpace>::myCurrentLineColor.red(), Viewer3D<Space, KSpace>::myCurrentLineColor.green(),
                        Viewer3D<Space, KSpace>::myCurrentLineColor.blue() , Viewer3D<Space, KSpace>::myCurrentLineColor.alpha() );
           for(unsigned int j=0;j < (it_s->vertices).size();j++)
             {
               glVertex3f ( (it_s->vertices).at(j)[0], (it_s->vertices).at(j)[1], (it_s->vertices).at ( j )[2] );
               glVertex3f ( (it_s->vertices).at((j+1)%(it_s->vertices).size())[0], (it_s->vertices).at((j+1)%(it_s->vertices).size())[1], (it_s->vertices).at ( (j+1)%(it_s->vertices).size() )[2] );
             }
         }
     }
   glEnd();
   glEndList();
   myVectTextureImage.clear();
   //Filling new image texture from myGSImageList
   for(unsigned int j=0; j<Viewer3D<Space, KSpace>::myGSImageList.size(); j++)
     {
       typename Viewer3D<Space, KSpace>::TextureImage & aGSImage = Viewer3D<Space, KSpace>::myGSImageList.at(j);
       GLTextureImage textureImg(aGSImage);
       glGenTextures(1, &textureImg.myTextureName);
       glBindTexture(GL_TEXTURE_2D, textureImg.myTextureName);
       glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
       glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
       glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
       glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
       if(textureImg.myMode==Viewer3D<Space, KSpace>::GrayScaleMode)
         {
           glTexImage2D(GL_TEXTURE_2D, 0, GL_LUMINANCE, textureImg.myBufferWidth, textureImg.myBufferHeight, 0,
                        GL_LUMINANCE, GL_UNSIGNED_BYTE, textureImg.myTextureImageBufferGS);
         }else if(textureImg.myMode==Viewer3D<Space, KSpace>::RGBMode)
         {
           glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, textureImg.myBufferWidth, textureImg.myBufferHeight, 0,
                        GL_RGB, GL_UNSIGNED_BYTE, textureImg.myTextureImageBufferRGB);
         }
       myVectTextureImage.push_back(textureImg);
     }
   if ( needToUpdateBoundingBox )
     {
       setSceneBoundingBox ( qglviewer::Vec ( Viewer3D<Space, KSpace>::myBoundingPtLow[0],Viewer3D<Space, KSpace>::myBoundingPtLow[1],Viewer3D<Space, KSpace>::myBoundingPtLow[2] ),
                             qglviewer::Vec ( Viewer3D<Space, KSpace>::myBoundingPtUp[0], Viewer3D<Space, KSpace>::myBoundingPtUp[1], Viewer3D<Space, KSpace>::myBoundingPtUp[2] ) );
       showEntireScene();
     }
   glPopMatrix();
 }
template<typename Space , typename KSpace > void DGtal::Viewer3D< Space, KSpace >::updateOrientationTextureImage (unsigned int imageIndex, double xPosition, double yPosition, double zPosition, ImageDirection newDirection) inline
Update the image parameters from std image (image buffer, vertex coordinates) The new image should be with same dimension than the original.
Parameters
imageIndex corresponds to the chronoloigic index given by the fuction (addTextureImage).
xPosition the image translation in the x direction (default 0).
yPosition the image translation in the y direction (default 0).
zPosition the image translation in the z direction (default 0).
newDirection a new direction
Definition at line 205 of file Viewer3D.ih.
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::draw().
 {
   assert ( imageIndex< myGSImageList.size());
   typename Viewer3D< Space ,KSpace >::TextureImage &anImage = myGSImageList.at(imageIndex);
   Display3D< Space, KSpace>::updateBoundingBox(anImage.point1);
   Display3D< Space, KSpace>::updateBoundingBox(anImage.point2);
   Display3D< Space, KSpace>::updateBoundingBox(anImage.point3);
   Display3D< Space, KSpace>::updateBoundingBox(anImage.point4);
   anImage.updateImageOrientation(newDirection, xPosition, yPosition, zPosition);
   if(anImage.myDrawDomain)
     {
       *this << DGtal::Update2DDomainPosition<Space ,KSpace >(anImage.myIndexDomain,newDirection, xPosition, yPosition, zPosition);
     }
 }
template<typename Space , typename KSpace > template<typename TImageType , typename TFunctor > void DGtal::Viewer3D< Space, KSpace >::updateTextureImage (unsigned int imageIndex, const TImageType & image, const TFunctor & aFunctor, double xTranslation = 0.0, double yTranslation = 0.0, double zTranslation = 0.0, double rotationAngle = 0.0, ImageDirection rotationDir = zDirection) inline
Update the image parameters from std image (image buffer, vertex coordinates) The new image should be with same dimension than the original.
Parameters
imageIndex corresponds to the chronoloigic index given by the fuction (addTextureImage).
image the new image containing the new buffer (with same dimensions than the other image).
aFunctor a functor
xTranslation the image translation in the x direction (default 0).
yTranslation the image translation in the y direction (default 0).
zTranslation the image translation in the z direction (default 0).
rotationAngle the angle of rotation.
rotationDir the rotation is applied around the given direction.
Definition at line 178 of file Viewer3D.ih.
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::draw().
 {
   BOOST_CONCEPT_ASSERT(( CConstImage < TImageType > ));
   assert ( imageIndex< myGSImageList.size());
   typename Viewer3D< Space ,KSpace >::TextureImage &anImage = myGSImageList.at(imageIndex);
   Display3D< Space, KSpace>::updateBoundingBox(DGtal::Z3i::RealPoint(anImage.point1[0]+xTranslation, anImage.point1[1]+yTranslation, anImage.point1[2]+zTranslation));
   Display3D< Space, KSpace>::updateBoundingBox(DGtal::Z3i::RealPoint(anImage.point2[0]+xTranslation, anImage.point2[1]+yTranslation, anImage.point2[2]+zTranslation));
   Display3D< Space, KSpace>::updateBoundingBox(DGtal::Z3i::RealPoint(anImage.point3[0]+xTranslation, anImage.point3[1]+yTranslation, anImage.point3[2]+zTranslation));
   Display3D< Space, KSpace>::updateBoundingBox(DGtal::Z3i::RealPoint(anImage.point4[0]+xTranslation, anImage.point4[1]+yTranslation, anImage.point4[2]+zTranslation));
   anImage.updateImageDataAndParam(image, aFunctor, xTranslation, yTranslation, zTranslation);
   if(anImage.myDrawDomain)
     {
       *this << DGtal::Translate2DDomain(anImage.myIndexDomain, xTranslation, yTranslation, zTranslation);
     }
   if(rotationAngle!=0.0){
     rotateDomain(myImageDomainList.at(anImage.myIndexDomain), rotationAngle, rotationDir);
     rotateImageVertex(anImage, rotationAngle, rotationDir);
   }
 }
Field Documentation
template<class S, class KS> double DGtal::Viewer3D< S, KS >::camera_direction[3] private
camera direction
Definition at line 1084 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< Space, KSpace >::setCameraDirection().
template<class S, class KS> double DGtal::Viewer3D< S, KS >::camera_position[3] private
camera position
Definition at line 1083 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< Space, KSpace >::setCameraPosition().
template<class S, class KS> double DGtal::Viewer3D< S, KS >::camera_upVector[3] private
camera up-vector
Definition at line 1085 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< Space, KSpace >::setCameraUpVector().
template<class S, class KS> DGtal::Color DGtal::Viewer3D< S, KS >::myDefaultBackgroundColor
the default background color of the viewer
Definition at line 219 of file Viewer3D.h.
template<class S, class KS> DGtal::Color DGtal::Viewer3D< S, KS >::myDefaultColor
the default color of the viewer
Definition at line 221 of file Viewer3D.h.
template<class S, class KS> qglviewer::Vec DGtal::Viewer3D< S, KS >::myDir private
Definition at line 1075 of file Viewer3D.h.
template<class S, class KS> qglviewer::Vec DGtal::Viewer3D< S, KS >::myDirSelector private
Definition at line 1075 of file Viewer3D.h.
template<class S, class KS> float DGtal::Viewer3D< S, KS >::myGLScaleFactorX private
Definition at line 1094 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< Space, KSpace >::setGLScale().
template<class S, class KS> float DGtal::Viewer3D< S, KS >::myGLScaleFactorY private
Definition at line 1095 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< Space, KSpace >::setGLScale().
template<class S, class KS> float DGtal::Viewer3D< S, KS >::myGLScaleFactorZ private
Definition at line 1096 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< Space, KSpace >::setGLScale().
template<class S, class KS> std::vector<TextureImage> DGtal::Viewer3D< S, KS >::myGSImageList private
Used to store all displayed images.
Definition at line 1099 of file Viewer3D.h.
template<class S, class KS> std::vector<Image2DDomainD3D> DGtal::Viewer3D< S, KS >::myImageDomainList private
Used to store all the domains.
Definition at line 1101 of file Viewer3D.h.
template<class S, class KS> bool DGtal::Viewer3D< S, KS >::myIsBackgroundDefault
true if the background is default
Definition at line 223 of file Viewer3D.h.
template<class S, class KS> bool DGtal::Viewer3D< S, KS >::myIsDoubleFaceRendering private
true if is double face rendering
Definition at line 1081 of file Viewer3D.h.
template<class S, class KS> GLuint DGtal::Viewer3D< S, KS >::myListToAff private
lists of the list to draw
Definition at line 1071 of file Viewer3D.h.
template<class S, class KS> float DGtal::Viewer3D< S, KS >::myMeshDefaultLineWidth private
Definition at line 1091 of file Viewer3D.h.
template<class S, class KS> unsigned int DGtal::Viewer3D< S, KS >::myNbListe private
number of lists in myListToAff
Definition at line 1073 of file Viewer3D.h.
template<class S, class KS> qglviewer::Vec DGtal::Viewer3D< S, KS >::myOrig private
information linked to the navigation in the viewer
Definition at line 1075 of file Viewer3D.h.
template<class S, class KS> QPoint DGtal::Viewer3D< S, KS >::myPosSelector private
a point selected with postSelection
See Also
postSelection
Definition at line 1077 of file Viewer3D.h.
template<class S, class KS> qglviewer::Vec DGtal::Viewer3D< S, KS >::mySelectedPoint private
Definition at line 1075 of file Viewer3D.h.
template<class S, class KS> std::vector<GLTextureImage> DGtal::Viewer3D< S, KS >::myVectTextureImage private
list of the images textures in this viewer
Definition at line 1079 of file Viewer3D.h.
template<class S, class KS> bool DGtal::Viewer3D< S, KS >::myViewWire
Definition at line 225 of file Viewer3D.h.
template<class S, class KS> double DGtal::Viewer3D< S, KS >::ZFar private
zfar distance
Definition at line 1088 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< Space, KSpace >::setNearFar().
template<class S, class KS> double DGtal::Viewer3D< S, KS >::ZNear private
znear distance
Definition at line 1087 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< Space, KSpace >::setNearFar().
The documentation for this class was generated from the following files:
CDrawableWithViewer3D.h
Viewer3D.h
Viewer3D.ih