DGtal: DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate > Class Template Reference
DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate > Class Template Reference
#include <ExplicitDigitalSurface.h>
Data Structures
class Tracker
Public Types
typedef ExplicitDigitalSurface
< TKSpace, TSurfelPredicate > Self
typedef TKSpace KSpace
typedef KSpace::SCell Surfel
typedef KSpace::Size Size
typedef TSurfelPredicate SurfelPredicate
typedef std::vector< Surfel > SurfelStorage
typedef
SurfelStorage::const_iterator SurfelConstIterator
typedef KSpace::Space Space
typedef KSpace::Point Point
typedef Tracker DigitalSurfaceTracker
typedef SurfelAdjacency
< KSpace::dimension > Adjacency
typedef KSpace::Cell Cell
typedef KSpace::SCell SCell
typedef KSpace::CellSet CellSet
typedef KSpace::SCellSet SCellSet
Public Member Functions
BOOST_CONCEPT_ASSERT ((CSurfelPredicate< SurfelPredicate >))
~ExplicitDigitalSurface ()
ExplicitDigitalSurface (const ExplicitDigitalSurface &other)
ExplicitDigitalSurface (const KSpace &aKSpace, const SurfelPredicate &aSP, const Adjacency &adj, const Surfel &s, bool closed=false)
const Adjacency & surfelAdjacency () const
Adjacency & surfelAdjacency ()
const SurfelPredicate & surfelPredicate () const
const KSpace & space () const
bool isInside (const Surfel &s) const
SurfelConstIterator begin () const
SurfelConstIterator end () const
Size nbSurfels () const
bool empty () const
DigitalSurfaceTracker * newTracker (const Surfel &s) const
Connectedness connectedness () const
void selfDisplay (std::ostream &out) const
bool isValid () const
Protected Member Functions
void computeSurfels (const Surfel &p, bool closed)
Private Member Functions
ExplicitDigitalSurface & operator= (const ExplicitDigitalSurface &other)
Private Attributes
const KSpace & myKSpace
const SurfelPredicate & mySurfelPredicate
Adjacency mySurfelAdjacency
SurfelStorage mySurfels
Detailed Description
template<typename TKSpace, typename TSurfelPredicate>
class DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >
Aim: A model of CDigitalSurfaceContainer which defines the digital surface as connected surfels. The shape is determined by a predicate telling whether a given surfel belongs or not to the shape boundary. Compute once the boundary of the surface with a tracking.
Description of template class 'ExplicitDigitalSurface'
Note that in the 2D case, this object corresponds to a digital contour made of linels, ordered as a direct orientation sequence. If the contour is open, then begin() returns one extremity while end() is the surfel past the last extremity. If the contour is closed, then begin() is the surfel given at the instantiation of the object.
Template Parameters
TKSpace a model of CCellularGridSpaceND: the type chosen for the cellular grid space.
TSurfelPredicate a model of CSurfelPredicate: this functor defines the digital surface as a characteristic function returning true iff the surfel belongs to it.
Examples:
topology/frontierAndBoundary.cpp.
Definition at line 80 of file ExplicitDigitalSurface.h.
Member Typedef Documentation
template<typename TKSpace, typename TSurfelPredicate> typedef SurfelAdjacency<KSpace::dimension> DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Adjacency
Definition at line 186 of file ExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef KSpace::Cell DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Cell
Definition at line 187 of file ExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef KSpace::CellSet DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::CellSet
Definition at line 189 of file ExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef Tracker DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::DigitalSurfaceTracker
Definition at line 182 of file ExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef TKSpace DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::KSpace
Model of cellular grid space.
Definition at line 166 of file ExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef KSpace::Point DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Point
Definition at line 181 of file ExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef KSpace::SCell DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::SCell
Definition at line 188 of file ExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef KSpace::SCellSet DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::SCellSet
Definition at line 190 of file ExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef ExplicitDigitalSurface<TKSpace,TSurfelPredicate> DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Self
Definition at line 164 of file ExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef KSpace::Size DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Size
Type for sizes (unsigned integral type).
Definition at line 170 of file ExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef KSpace::Space DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Space
Definition at line 180 of file ExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef KSpace::SCell DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Surfel
Type for surfels.
Definition at line 168 of file ExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef SurfelStorage::const_iterator DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::SurfelConstIterator
Definition at line 179 of file ExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef TSurfelPredicate DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::SurfelPredicate
Definition at line 172 of file ExplicitDigitalSurface.h.
template<typename TKSpace, typename TSurfelPredicate> typedef std::vector<Surfel> DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::SurfelStorage
Definition at line 178 of file ExplicitDigitalSurface.h.
Constructor & Destructor Documentation
template<typename TKSpace , typename TSurfelPredicate > DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::~ExplicitDigitalSurface () inline
Destructor.
Definition at line 123 of file ExplicitDigitalSurface.ih.
 {
 }
template<typename TKSpace , typename TSurfelPredicate > DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::ExplicitDigitalSurface (const ExplicitDigitalSurface< TKSpace, TSurfelPredicate > & other) inline
Copy constructor.
Parameters
other the object to clone.
NB: O(N) computational complexity operation, where N is the number of surfels of the surface. This is due to the fact that the surface is stored explicitly.
Definition at line 130 of file ExplicitDigitalSurface.ih.
   : myKSpace( other.myKSpace ),
     mySurfelPredicate( other.mySurfelPredicate ),
     mySurfelAdjacency( other.mySurfelAdjacency ),
     mySurfels( other.mySurfels )
 {
 }
template<typename TKSpace , typename TSurfelPredicate > DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::ExplicitDigitalSurface (const KSpace & aKSpace, const SurfelPredicate & aSP, const Adjacency & adj, const Surfel & s, bool closed = false) inline
Constructor from digital set.
Parameters
aKSpace a cellular grid space (referenced).
aSP a surfel predicate defining the shape (referenced).
adj the surfel adjacency (for instance Adjacency(true) is interior to exterior adjacency).
s any surfel of aKSpace such that aSP is true in the interior and false in the exterior.
closed when 'true', the surface is known to be closed, hence faster extraction can be performed, default is 'false'.
NB: O(N) computational complexity operation, where N is the number of surfels of the surface. This is due to the fact that, at construction, the surface is extracted and stored.
See Also
computeSurfels
Definition at line 141 of file ExplicitDigitalSurface.ih.
References DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::computeSurfels().
   : myKSpace( aKSpace ), mySurfelPredicate( aPP ), mySurfelAdjacency( adj )
 {
   computeSurfels( s, closed );
 }
Member Function Documentation
template<typename TKSpace , typename TSurfelPredicate > DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::SurfelConstIterator DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::begin () const inline
Returns
an iterator pointing on the first surfel of the digital surface (unspecified order).
Definition at line 200 of file ExplicitDigitalSurface.ih.
References DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfels.
 {
   return mySurfels.begin();
 }
template<typename TKSpace, typename TSurfelPredicate> DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::BOOST_CONCEPT_ASSERT ((CSurfelPredicate< SurfelPredicate >))
template<typename TKSpace , typename TSurfelPredicate > void DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::computeSurfels (const Surfel & p, bool closed) inline protected
Recomputes the set of boundary surfels from the point predicate and some initial surfel.
Parameters
p any surfel of the surface
closed when 'true', the surface is known to be closed, hence faster extraction can be performed.
Definition at line 252 of file ExplicitDigitalSurface.ih.
References DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::myKSpace, DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfelAdjacency, DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfelPredicate, DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfels, DGtal::Surfaces< TKSpace >::track2DSurface(), DGtal::Surfaces< TKSpace >::trackClosedSurface(), and DGtal::Surfaces< TKSpace >::trackSurface().
Referenced by DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::ExplicitDigitalSurface().
 {
   mySurfels.clear();
   if ( KSpace::dimension > 2 )
     {
       typename KSpace::SCellSet surface;
       if ( closed )
         Surfaces<KSpace>::trackClosedSurface( surface,
                                               myKSpace,
                                               mySurfelAdjacency,
                                               mySurfelPredicate,
                                               p );
       else
         Surfaces<KSpace>::trackSurface( surface,
                                         myKSpace,
                                         mySurfelAdjacency,
                                         mySurfelPredicate,
                                         p );
       for ( typename KSpace::SCellSet::const_iterator it = surface.begin(),
               it_end = surface.end(); it != it_end; ++it )
         mySurfels.push_back( *it );
     }
   else
     {
       ASSERT( KSpace::dimension == 2 );
       Surfaces<KSpace>::track2DSurface( mySurfels,
                                         myKSpace,
                                         mySurfelAdjacency,
                                         mySurfelPredicate,
                                         p );
     }
 }
template<typename TKSpace , typename TSurfelPredicate > DGtal::Connectedness DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::connectedness () const inline
Returns
the connectedness of this surface. By construction CONNECTED.
Definition at line 241 of file ExplicitDigitalSurface.ih.
References DGtal::CONNECTED.
 {
   return CONNECTED;
 }
template<typename TKSpace , typename TSurfelPredicate > bool DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::empty () const inline
Returns
'true' is the surface has no surfels, 'false' otherwise. NB: O(1) operation.
Definition at line 224 of file ExplicitDigitalSurface.ih.
References DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfels.
 {
   return mySurfels.empty();
 }
template<typename TKSpace , typename TSurfelPredicate > DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::SurfelConstIterator DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::end () const inline
Returns
an iterator after the last surfel of the digital surface (unspecified order).
Definition at line 208 of file ExplicitDigitalSurface.ih.
References DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfels.
 {
   return mySurfels.end();
 }
template<typename TKSpace , typename TSurfelPredicate > bool DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::isInside (const Surfel & s) const inline
Parameters
s any surfel of the space.
Returns
'true' if s belongs to this digital surface.
Definition at line 192 of file ExplicitDigitalSurface.ih.
References DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::surfelPredicate().
Referenced by DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Tracker::move().
 {
   return surfelPredicate()( s );
 }
template<typename TKSpace , typename TSurfelPredicate > bool DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 307 of file ExplicitDigitalSurface.ih.
 {
   return true;
 }
template<typename TKSpace , typename TSurfelPredicate > DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Size DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::nbSurfels () const inline
Returns
the number of surfels of this digital surface. NB: O(1)
Definition at line 216 of file ExplicitDigitalSurface.ih.
References DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfels.
 {
   return mySurfels.size();
 }
template<typename TKSpace , typename TSurfelPredicate > DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::DigitalSurfaceTracker * DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::newTracker (const Surfel & s) const inline
Parameters
s any surfel of the space.
Precondition
'isInside(s)'
Returns
a dyn. alloc. pointer on a tracker positionned at s.
Definition at line 233 of file ExplicitDigitalSurface.ih.
 {
   return new Tracker( *this, s );
 }
template<typename TKSpace, typename TSurfelPredicate> ExplicitDigitalSurface& DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::operator= (const ExplicitDigitalSurface< TKSpace, TSurfelPredicate > & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
template<typename TKSpace , typename TSurfelPredicate > void DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 295 of file ExplicitDigitalSurface.ih.
 {
   out << "[ExplicitDigitalSurface]";
 }
template<typename TKSpace , typename TSurfelPredicate > const DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::KSpace & DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::space () const inline
Returns
the cellular space in which lives the surface.
Definition at line 183 of file ExplicitDigitalSurface.ih.
References DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::myKSpace.
Referenced by DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Tracker::Tracker().
 {
   return myKSpace;
 }
template<typename TKSpace , typename TSurfelPredicate > const DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Adjacency & DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::surfelAdjacency () const inline
accessor to surfel adjacency.
Definition at line 155 of file ExplicitDigitalSurface.ih.
References DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfelAdjacency.
Referenced by DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Tracker::Tracker().
 {
   return mySurfelAdjacency;
 }
template<typename TKSpace , typename TSurfelPredicate > DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Adjacency & DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::surfelAdjacency () inline
mutator to surfel adjacency.
Definition at line 163 of file ExplicitDigitalSurface.ih.
References DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfelAdjacency.
 {
   return mySurfelAdjacency;
 }
template<typename TKSpace , typename TSurfelPredicate > const DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::SurfelPredicate & DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::surfelPredicate () const inline
accessor to point predicate.
Definition at line 172 of file ExplicitDigitalSurface.ih.
References DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfelPredicate.
Referenced by DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::Tracker::adjacent(), and DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::isInside().
 {
   return mySurfelPredicate;
 }
Field Documentation
template<typename TKSpace, typename TSurfelPredicate> const KSpace& DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::myKSpace private
a reference to the cellular space.
Definition at line 301 of file ExplicitDigitalSurface.h.
Referenced by DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::computeSurfels(), and DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::space().
template<typename TKSpace, typename TSurfelPredicate> Adjacency DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfelAdjacency private
the surfel adjacency used to determine neighbors.
Definition at line 305 of file ExplicitDigitalSurface.h.
Referenced by DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::computeSurfels(), and DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::surfelAdjacency().
template<typename TKSpace, typename TSurfelPredicate> const SurfelPredicate& DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfelPredicate private
a reference to the surfel predicate defining the shape.
Definition at line 303 of file ExplicitDigitalSurface.h.
Referenced by DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::computeSurfels(), and DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::surfelPredicate().
template<typename TKSpace, typename TSurfelPredicate> SurfelStorage DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::mySurfels private
a vector storing all the surfels of the boundary.
Definition at line 307 of file ExplicitDigitalSurface.h.
Referenced by DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::begin(), DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::computeSurfels(), DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::empty(), DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::end(), and DGtal::ExplicitDigitalSurface< TKSpace, TSurfelPredicate >::nbSurfels().
The documentation for this class was generated from the following files:
ExplicitDigitalSurface.h
ExplicitDigitalSurface.ih