DGtal: DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy > Class Template Reference
DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy > Class Template Reference
#include <ImageCache.h>
Public Types
typedef ImageCache
< TImageContainer,
TImageFactory, TReadPolicy,
TWritePolicy > Self
typedef TImageContainer ImageContainer
typedef ImageContainer::Domain Domain
typedef ImageContainer::Point Point
typedef ImageContainer::Value Value
typedef TImageFactory ImageFactory
typedef TReadPolicy ReadPolicy
typedef TWritePolicy WritePolicy
Public Member Functions
BOOST_CONCEPT_ASSERT ((CImage< TImageContainer >))
BOOST_CONCEPT_ASSERT ((CImageFactory< TImageFactory >))
BOOST_CONCEPT_ASSERT ((CImageCacheReadPolicy< TReadPolicy >))
BOOST_CONCEPT_ASSERT ((CImageCacheWritePolicy< TWritePolicy >))
ImageCache (Alias< ImageFactory > anImageFactory, Alias< ReadPolicy > aReadPolicy, Alias< WritePolicy > aWritePolicy)
~ImageCache ()
void selfDisplay (std::ostream &out) const
bool isValid () const
bool read (const Point &aPoint, Value &aValue) const
ImageContainer * getPage (const Domain &aDomain) const
bool write (const Point &aPoint, const Value &aValue)
void update (const Domain &aDomain)
unsigned int getCacheMissRead ()
unsigned int getCacheMissWrite ()
void incCacheMissRead ()
void incCacheMissWrite ()
void clearCacheAndResetCacheMisses ()
Protected Attributes
ImageFactory * myImageFactoryPtr
ReadPolicy * myReadPolicy
WritePolicy * myWritePolicy
Private Member Functions
ImageCache (const ImageCache &other)
ImageCache & operator= (const ImageCache &other)
Private Attributes
unsigned int cacheMissRead
unsigned int cacheMissWrite
Detailed Description
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy>
class DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >
Aim: implements an images cache with 'read and write' policies.
Description of template class 'ImageCache'
Template Parameters
TImageContainer an image container type (model of CImage).
TImageFactory an image factory type (model of CImageFactory).
TReadPolicy an image cache read policy class (model of CImageCacheReadPolicy).
TWritePolicy an image cache write policy class (model of CImageCacheWritePolicy).
The cache provides 3 functions:
read : for getting the value of an image from cache at a given position given by a point only if that point belongs to an image from cache
write : for setting a value on an image from cache at a given position given by a point only if that point belongs to an image from cache
update : for updating the cache according to the read cache policy
Definition at line 77 of file ImageCache.h.
Member Typedef Documentation
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> typedef ImageContainer::Domain DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::Domain
Definition at line 93 of file ImageCache.h.
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> typedef TImageContainer DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::ImageContainer
Types copied from the container.
Definition at line 92 of file ImageCache.h.
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> typedef TImageFactory DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::ImageFactory
Definition at line 97 of file ImageCache.h.
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> typedef ImageContainer::Point DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::Point
Definition at line 94 of file ImageCache.h.
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> typedef TReadPolicy DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::ReadPolicy
Definition at line 99 of file ImageCache.h.
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> typedef ImageCache<TImageContainer, TImageFactory, TReadPolicy, TWritePolicy> DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::Self
Definition at line 83 of file ImageCache.h.
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> typedef ImageContainer::Value DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::Value
Definition at line 95 of file ImageCache.h.
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> typedef TWritePolicy DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::WritePolicy
Definition at line 100 of file ImageCache.h.
Constructor & Destructor Documentation
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::ImageCache (Alias< ImageFactory > anImageFactory, Alias< ReadPolicy > aReadPolicy, Alias< WritePolicy > aWritePolicy) inline
Constructor.
Parameters
anImageFactory alias on the image factory (see ImageFactoryFromImage or ImageFactoryFromHDF5).
aReadPolicy a read policy.
aWritePolicy a write policy.
Definition at line 112 of file ImageCache.h.
References DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::cacheMissRead, DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::cacheMissWrite, and DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::myReadPolicy.
                                                                                                                   :
       myImageFactoryPtr(&anImageFactory), myReadPolicy(&aReadPolicy), myWritePolicy(&aWritePolicy)
     {
       myReadPolicy->clearCache();
       cacheMissRead = 0;
       cacheMissWrite = 0;
     }
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::~ImageCache () inline
Destructor. Does nothing
Definition at line 125 of file ImageCache.h.
     {
     }
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::ImageCache (const ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy > & other) private
Member Function Documentation
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::BOOST_CONCEPT_ASSERT ((CImage< TImageContainer >))
Checking concepts.
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::BOOST_CONCEPT_ASSERT ((CImageFactory< TImageFactory >))
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::BOOST_CONCEPT_ASSERT ((CImageCacheReadPolicy< TReadPolicy >))
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::BOOST_CONCEPT_ASSERT ((CImageCacheWritePolicy< TWritePolicy >))
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> void DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::clearCacheAndResetCacheMisses () inline
Clear the cache and reset the cache misses
Definition at line 235 of file ImageCache.h.
References DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::cacheMissRead, DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::cacheMissWrite, and DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::myReadPolicy.
Referenced by DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::clearCacheAndResetCacheMisses().
     {
       myReadPolicy->clearCache();
       cacheMissRead = 0;
       cacheMissWrite = 0;
     }
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> unsigned int DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::getCacheMissRead () inline
Get the cacheMissRead value.
Definition at line 203 of file ImageCache.h.
References DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::cacheMissRead.
Referenced by DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::getCacheMissRead().
     {
         return cacheMissRead;
     }
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> unsigned int DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::getCacheMissWrite () inline
Get the cacheMissWrite value.
Definition at line 211 of file ImageCache.h.
References DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::cacheMissWrite.
Referenced by DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::getCacheMissWrite().
     {
         return cacheMissWrite;
     }
template<typename TImageContainer , typename TImageFactory , typename TReadPolicy , typename TWritePolicy > TImageContainer * DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::getPage (const Domain & aDomain) const inline
Get the alias on the image that matchs the domain aDomain or NULL if no image in the cache matchs the domain aDomain.
Parameters
aDomain the domain.
Returns
the alias on the image container or NULL pointer.
Definition at line 76 of file ImageCache.ih.
Referenced by DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::findTileFromBlockCoords().
 {
     return myReadPolicy->getPage(aDomain);
 }
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> void DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::incCacheMissRead () inline
Inc the cacheMissRead value.
Definition at line 219 of file ImageCache.h.
References DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::cacheMissRead.
Referenced by DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::findTileFromBlockCoords(), and DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::operator()().
     {
         cacheMissRead++;
     }
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> void DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::incCacheMissWrite () inline
Inc the cacheMissWrite value.
Definition at line 227 of file ImageCache.h.
References DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::cacheMissWrite.
Referenced by DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::setValue().
     {
         cacheMissWrite++;
     }
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> bool DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 156 of file ImageCache.h.
References DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::myImageFactoryPtr.
Referenced by DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::isValid().
     {
         return (myImageFactoryPtr->isValid());
     }
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> ImageCache& DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::operator= (const ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy > & other) private
template<typename TImageContainer , typename TImageFactory , typename TReadPolicy , typename TWritePolicy > bool DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::read (const Point & aPoint, Value & aValue) const inline
Get the value of an image from cache at a given position given by aPoint only if aPoint belongs to an image from cache.
Parameters
aPoint the point.
aValue the value returned.
Returns
'true' if aPoint belongs to an image from cache, 'false' otherwise.
Definition at line 61 of file ImageCache.ih.
Referenced by DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::operator()().
 {
     ImageContainer *myImagePtr = myReadPolicy->getPage(aPoint);
     if (myImagePtr)
     {
       aValue = myImagePtr->operator()(aPoint);
       return true;
     }
     return false;
 }
template<typename TImageContainer , typename TImageFactory , typename TReadPolicy , typename TWritePolicy > void DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 53 of file ImageCache.ih.
 {
     out << "[ImageCache] ";
 }
template<typename TImageContainer , typename TImageFactory , typename TReadPolicy , typename TWritePolicy > void DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::update (const Domain & aDomain) inline
Update the cache according to the read cache policy.
Parameters
aDomain the domain.
Definition at line 99 of file ImageCache.ih.
Referenced by DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::findTileFromBlockCoords(), DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::operator()(), and DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::setValue().
 {
     ImageContainer *myImagePtr = myReadPolicy->getPageToDetach();
     if (myImagePtr)
     {
       myWritePolicy->flushPage(myImagePtr);
       myImageFactoryPtr->detachImage(myImagePtr);
     }
     myReadPolicy->updateCache(aDomain);
 }
template<typename TImageContainer , typename TImageFactory , typename TReadPolicy , typename TWritePolicy > bool DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::write (const Point & aPoint, const Value & aValue) inline
Set a value on an image from cache at a given position given by aPoint only if aPoint belongs to an image from cache.
Parameters
aPoint the point.
aValue the value returned.
Returns
'true' if aPoint belongs to an image from cache, 'false' otherwise.
Definition at line 84 of file ImageCache.ih.
Referenced by DGtal::TiledImage< TImageContainer, TImageFactory, TImageCacheReadPolicy, TImageCacheWritePolicy >::setValue().
 {
     ImageContainer *myImagePtr = myReadPolicy->getPage(aPoint);
     if (myImagePtr)
     {
       myWritePolicy->writeInPage(myImagePtr, aPoint, aValue);
       return true;
     }
     return false;
 }
Field Documentation
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> unsigned int DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::cacheMissRead private
cache miss values
Definition at line 263 of file ImageCache.h.
Referenced by DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::clearCacheAndResetCacheMisses(), DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::getCacheMissRead(), DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::ImageCache(), and DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::incCacheMissRead().
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> unsigned int DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::cacheMissWrite private
Definition at line 264 of file ImageCache.h.
Referenced by DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::clearCacheAndResetCacheMisses(), DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::getCacheMissWrite(), DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::ImageCache(), and DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::incCacheMissWrite().
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> ImageFactory* DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::myImageFactoryPtr protected
Alias on the image factory.
Default constructor.
Definition at line 254 of file ImageCache.h.
Referenced by DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::isValid().
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> ReadPolicy* DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::myReadPolicy protected
Specialized caches.
Definition at line 257 of file ImageCache.h.
Referenced by DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::clearCacheAndResetCacheMisses(), and DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::ImageCache().
template<typename TImageContainer, typename TImageFactory, typename TReadPolicy, typename TWritePolicy> WritePolicy* DGtal::ImageCache< TImageContainer, TImageFactory, TReadPolicy, TWritePolicy >::myWritePolicy protected
Definition at line 258 of file ImageCache.h.
The documentation for this class was generated from the following files:
ImageCache.h
ImageCache.ih