DGtal: DGtal::Statistic< TQuantity > Class Template Reference
DGtal::Statistic< TQuantity > Class Template Reference
#include <Statistic.h>
Public Types
typedef TQuantity Quantity
typedef std::vector< Quantity > Container
typedef Container::const_iterator ConstIterator
Public Member Functions
BOOST_CONCEPT_ASSERT ((CCommutativeRing< Quantity >))
~Statistic ()
Statistic (bool storeSample=false)
Statistic (const Statistic &other)
Statistic & operator= (const Statistic &other)
Statistic & operator+= (const Statistic &other)
Statistic operator+ (const Statistic &other) const
ConstIterator begin () const
ConstIterator end () const
unsigned int samples () const
double mean () const
double variance () const
double unbiasedVariance () const
Quantity max () const
Quantity min () const
Quantity median ()
void addValue (Quantity v)
template<class Iter >
void addValues (Iter b, Iter e)
void clear ()
void terminate ()
void selfDisplay (std::ostream &that_stream) const
bool OK () const
Private Attributes
unsigned int mySamples
Quantity myExp
Quantity myExp2
Quantity myMax
Quantity myMin
Quantity myMedian
Container myValues
bool myStoreSamples
bool myIsTerminated
Detailed Description
template<typename TQuantity>
class DGtal::Statistic< TQuantity >
Aim: This class processes a set of sample values for one variable and can then compute different statistics, like sample mean, sample variance, sample unbiased variance, etc. It is minimalistic for space efficiency. For multiple variables, sample storage and others, see Statistics class.
Description of class 'Statistic'
Backported from ImaGene. [22]
See Also
testStatistics.cpp
Template Parameters
TQuantity any model of CCommutativeRing.
Definition at line 69 of file Statistic.h.
Member Typedef Documentation
template<typename TQuantity> typedef Container::const_iterator DGtal::Statistic< TQuantity >::ConstIterator
Definition at line 77 of file Statistic.h.
template<typename TQuantity> typedef std::vector< Quantity > DGtal::Statistic< TQuantity >::Container
Definition at line 76 of file Statistic.h.
template<typename TQuantity> typedef TQuantity DGtal::Statistic< TQuantity >::Quantity
Definition at line 74 of file Statistic.h.
Constructor & Destructor Documentation
template<typename TQuantity > DGtal::Statistic< TQuantity >::~Statistic () inline
Destructor.
Definition at line 44 of file Statistic.ih.
 {}
template<typename TQuantity > DGtal::Statistic< TQuantity >::Statistic (bool storeSample = false) inline
Constructor.
Definition at line 50 of file Statistic.ih.
References DGtal::Statistic< TQuantity >::myValues.
   : mySamples( 0 ), myExp( NumberTraits<Quantity>::ZERO ), myExp2( NumberTraits<Quantity>::ZERO ),  myMax( NumberTraits<Quantity>::ZERO ),myMin( NumberTraits<Quantity>::ZERO ), myMedian(NumberTraits<Quantity>::ZERO),  myStoreSamples (storeSample),
     myIsTerminated(false)
 {
   myValues=  std::vector<Quantity> ();
 }
template<typename TQuantity > DGtal::Statistic< TQuantity >::Statistic (const Statistic< TQuantity > & other) inline
Copy constructor.
Parameters
other the object to clone.
Definition at line 62 of file Statistic.ih.
References DGtal::Statistic< TQuantity >::myValues.
   : mySamples( other.mySamples ),
     myExp( other.myExp ),
     myExp2( other.myExp2 ),
     myMax( other.myMax ),
     myMin( other.myMin ),
     myMedian( other.myMedian),
     myStoreSamples (other.myStoreSamples),
     myIsTerminated(other.myIsTerminated)
 {
   if(myStoreSamples){
     myValues=  std::vector<TQuantity> ();
     for(unsigned int i=0; i<other.myValues.size(); i++){
       myValues.push_back(other.myValues.at(i));
     }
   }
 }
Member Function Documentation
template<typename TQuantity > void DGtal::Statistic< TQuantity >::addValue (Quantity v) inline
Adds a new sample value [v].
Parameters
v the new sample value.
Definition at line 256 of file Statistic.ih.
Referenced by DGtal::CompareLocalEstimators< TFirstEsimator, TSecondEstimator >::compare(), and DGtal::CompareLocalEstimators< TFirstEsimator, TSecondEstimator >::compareVectors().
 {
   if ( mySamples == 0 )
     {
       myMin = v;
       myMax = v;
     }
   else if ( v < myMin ) myMin = v;
   else if ( v > myMax ) myMax = v;
   myExp += v;
   myExp2 += v * v;
   ++mySamples;
   if(myStoreSamples){
     myValues.push_back(v);
   }
 }
template<typename TQuantity > template<class Iter > void DGtal::Statistic< TQuantity >::addValues (Iter b, Iter e) inline
Adds a sequence of sample values, scanning a container from iterators [b] to [e].
Exemple:
vector<Quantity> x;
Statistic stats;
stats.addValue(x + 4, x + 10);
Parameters
b an iterator on the starting point.
e an iterator after the last point.
Definition at line 279 of file Statistic.ih.
 {
   for ( ; b != e; ++b )
     addValue( *b );
 }
template<typename TQuantity > DGtal::Statistic< TQuantity >::ConstIterator DGtal::Statistic< TQuantity >::begin () const inline
Returns
an iterator on the first stored value (if storeSample was set).
Definition at line 159 of file Statistic.ih.
 {
   return myValues.begin();
 }
template<typename TQuantity> DGtal::Statistic< TQuantity >::BOOST_CONCEPT_ASSERT ((CCommutativeRing< Quantity >))
template<typename TQuantity > void DGtal::Statistic< TQuantity >::clear () inline
Clears the object. As if it has just been created.
Definition at line 290 of file Statistic.ih.
 {
   mySamples = 0;
   myExp = NumberTraits<Quantity>::ZERO;
   myExp2 = NumberTraits<Quantity>::ZERO;
   myMin = NumberTraits<Quantity>::ZERO;
   myMax = NumberTraits<Quantity>::ZERO;
   myMedian=NumberTraits<Quantity>::ZERO;
   myIsTerminated=false;
   if(myStoreSamples){
     myValues.clear();
   }
 }
template<typename TQuantity > DGtal::Statistic< TQuantity >::ConstIterator DGtal::Statistic< TQuantity >::end () const inline
Returns
an iterator after the last stored value (if storeSample was set).
Definition at line 167 of file Statistic.ih.
 {
   return myValues.end();
 }
template<typename TQuantity > TQuantity DGtal::Statistic< TQuantity >::max () const inline
Returns
the maximal value.
Definition at line 219 of file Statistic.ih.
Referenced by DGtal::Histogram< TQuantity, TBinner >::init().
 {
   return myMax;
 }
template<typename TQuantity > double DGtal::Statistic< TQuantity >::mean () const inline
Returns
the sample mean (given as double).
Definition at line 189 of file Statistic.ih.
References DGtal::NumberTraits< T >::castToDouble().
 {
   return NumberTraits<Quantity>::castToDouble(myExp) /
     static_cast<double>(mySamples );
 }
template<typename TQuantity > TQuantity DGtal::Statistic< TQuantity >::median () inline
Return the median value of the Statistic values. It can be given in two possible cases:
if the the values are stored in the 'Statistic' objects (not always a good solution). (complexity: linear on average)
if the values were first stored and computed by the function terminate().
Returns
the median value.
See Also
terminate, Statistic
Definition at line 237 of file Statistic.ih.
 {
   ASSERT( myStoreSamples || myIsTerminated );
   if(myIsTerminated){
     return myMedian;
   }
   else{
     ASSERT(myValues.size()>0);
     nth_element( myValues.begin(), myValues.begin()+(myValues.size()/2),
                  myValues.end());
     return *(myValues.begin()+(myValues.size()/2));
   }
 }
template<typename TQuantity > TQuantity DGtal::Statistic< TQuantity >::min () const inline
Returns
the minimal value.
Definition at line 228 of file Statistic.ih.
Referenced by DGtal::Histogram< TQuantity, TBinner >::init().
 {
   return myMin;
 }
template<typename TQuantity > bool DGtal::Statistic< TQuantity >::OK () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 347 of file Statistic.ih.
 {
   return true;
 }
template<typename TQuantity > DGtal::Statistic< TQuantity > DGtal::Statistic< TQuantity >::operator+ (const Statistic< TQuantity > & other) const inline
Adds two set of statistics (should be of the same variable).
Parameters
other the object to add.
Returns
a new object that is the union of these statistics.
Definition at line 147 of file Statistic.ih.
 {
   Statistic<TQuantity> stat( *this );
   stat += other;
   return stat;
 }
template<typename TQuantity > DGtal::Statistic< TQuantity > & DGtal::Statistic< TQuantity >::operator+= (const Statistic< TQuantity > & other) inline
Adds to self another set of statistics (should be of the same variable).
Parameters
other the object to add.
Returns
a reference on 'this'.
Definition at line 116 of file Statistic.ih.
References DGtal::Statistic< TQuantity >::myExp, DGtal::Statistic< TQuantity >::myExp2, DGtal::Statistic< TQuantity >::myMax, DGtal::Statistic< TQuantity >::myMin, DGtal::Statistic< TQuantity >::mySamples, DGtal::Statistic< TQuantity >::myStoreSamples, and DGtal::Statistic< TQuantity >::myValues.
 {
   if ( other.mySamples != 0 )
     {
       if ( ( mySamples == 0 ) || ( other.myMin < myMin ) )
         myMin = other.myMin;
       if ( ( mySamples == 0 ) || ( other.myMax > myMax ) )
         myMax = other.myMax;
     }
   mySamples += other.mySamples;
   myExp += other.myExp;
   myExp2 += other.myExp2;
   myIsTerminated=false;
   if(myStoreSamples && other.myStoreSamples){
     for(unsigned int i=0; i<other.myValues.size(); i++){
       myValues.push_back(other.myValues.at(i));
     }
   }else{
     myStoreSamples=false;
   }
 }
template<typename TQuantity > DGtal::Statistic< TQuantity > & DGtal::Statistic< TQuantity >::operator= (const Statistic< TQuantity > & other) inline
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'.
Definition at line 87 of file Statistic.ih.
References DGtal::Statistic< TQuantity >::myExp, DGtal::Statistic< TQuantity >::myExp2, DGtal::Statistic< TQuantity >::myIsTerminated, DGtal::Statistic< TQuantity >::myMax, DGtal::Statistic< TQuantity >::myMedian, DGtal::Statistic< TQuantity >::myMin, DGtal::Statistic< TQuantity >::mySamples, DGtal::Statistic< TQuantity >::myStoreSamples, and DGtal::Statistic< TQuantity >::myValues.
 {
   if ( this != &other )
     {
       mySamples = other.mySamples;
       myExp = other.myExp;
       myExp2 = other.myExp2;
       myMin = other.myMin;
       myMax = other.myMax;
       myMedian = other.myMedian;
       myStoreSamples = other.myStoreSamples;
       myIsTerminated=other.myIsTerminated;
       if(myStoreSamples){
         myValues=  std::vector<Quantity> ();
         for(unsigned int i=0; i<other.myValues.size(); i++){
           myValues.push_back(other.myValues.at(i));
         }
       }
     }
   return *this;
 }
template<typename TQuantity > unsigned int DGtal::Statistic< TQuantity >::samples () const inline
Returns
the number of samples.
Definition at line 181 of file Statistic.ih.
Referenced by DGtal::Histogram< TQuantity, TBinner >::init().
 {
   return mySamples;
 }
template<typename TQuantity > void DGtal::Statistic< TQuantity >::selfDisplay (std::ostream & that_stream) const inline
Writes/Displays the object on an output stream.
Parameters
that_stream the output stream where the object is written.
Definition at line 331 of file Statistic.ih.
Referenced by DGtal::operator<<().
 {
   thatStream << "[Statistic "
              << " nb=" << samples()
              << " exp=" << mean()
              << " var=" << variance()
              << " uvar=" << unbiasedVariance()
              << " min=" << min()
              << " max=" << max()
              << "]";
 }
template<typename TQuantity > void DGtal::Statistic< TQuantity >::terminate () inline
Computes the median value of the statistics and switch to mode which does not save the statistics samples (myStore_samples = false). Usefull only if the values are stored (specified in the the constructor) else it doest nothing.
See Also
median, Statistic, myStore_samples
Definition at line 310 of file Statistic.ih.
Referenced by DGtal::CompareLocalEstimators< TFirstEsimator, TSecondEstimator >::compare(), and DGtal::CompareLocalEstimators< TFirstEsimator, TSecondEstimator >::compareVectors().
 {
   if(myStoreSamples){
     myMedian=median();
     // JOL: Perhaps a cleanUp() or dispose() method is
     // preferable. Sometimes, it is useful to access also the values.
     // myValues.clear();
     myStoreSamples=false;
     myIsTerminated=true;
   }
 }
template<typename TQuantity > double DGtal::Statistic< TQuantity >::unbiasedVariance () const inline
Returns
the unbiased sample variance (given as double).
Definition at line 208 of file Statistic.ih.
Referenced by DGtal::Histogram< TQuantity, TBinner >::init().
 {
   ASSERT( mySamples != 0 );
   return ( (double) mySamples ) * variance()
     / ( (double) mySamples );
 }
template<typename TQuantity > double DGtal::Statistic< TQuantity >::variance () const inline
Returns
the sample variance (given as double).
Definition at line 199 of file Statistic.ih.
 {
   return ( NumberTraits<Quantity>::castToDouble(myExp2) / (double) mySamples ) - mean() * mean();
 }
Field Documentation
template<typename TQuantity> Quantity DGtal::Statistic< TQuantity >::myExp private
stores the sum of sample values for computing sample mean.
Definition at line 251 of file Statistic.h.
Referenced by DGtal::Statistic< TQuantity >::operator+=(), and DGtal::Statistic< TQuantity >::operator=().
template<typename TQuantity> Quantity DGtal::Statistic< TQuantity >::myExp2 private
stores the sum of squared sample values for computing sample variance.
Definition at line 257 of file Statistic.h.
Referenced by DGtal::Statistic< TQuantity >::operator+=(), and DGtal::Statistic< TQuantity >::operator=().
template<typename TQuantity> bool DGtal::Statistic< TQuantity >::myIsTerminated private
Tells if terminate was called. Usefull to return median value even if the m_values are no more stored (possible after serialisation which doest store the values.).
Definition at line 295 of file Statistic.h.
Referenced by DGtal::Statistic< TQuantity >::operator=().
template<typename TQuantity> Quantity DGtal::Statistic< TQuantity >::myMax private
stores the maximal sample value.
Definition at line 262 of file Statistic.h.
Referenced by DGtal::Statistic< TQuantity >::operator+=(), and DGtal::Statistic< TQuantity >::operator=().
template<typename TQuantity> Quantity DGtal::Statistic< TQuantity >::myMedian private
stores the median sample value.
Definition at line 273 of file Statistic.h.
Referenced by DGtal::Statistic< TQuantity >::operator=().
template<typename TQuantity> Quantity DGtal::Statistic< TQuantity >::myMin private
stores the minimal sample value.
Definition at line 267 of file Statistic.h.
Referenced by DGtal::Statistic< TQuantity >::operator+=(), and DGtal::Statistic< TQuantity >::operator=().
template<typename TQuantity> unsigned int DGtal::Statistic< TQuantity >::mySamples private
number of samples
Definition at line 246 of file Statistic.h.
Referenced by DGtal::Statistic< TQuantity >::operator+=(), and DGtal::Statistic< TQuantity >::operator=().
template<typename TQuantity> bool DGtal::Statistic< TQuantity >::myStoreSamples private
Tells if values must be stored or not.
Definition at line 286 of file Statistic.h.
Referenced by DGtal::Statistic< TQuantity >::operator+=(), and DGtal::Statistic< TQuantity >::operator=().
template<typename TQuantity> Container DGtal::Statistic< TQuantity >::myValues private
stores the sample to determine the median value
Definition at line 280 of file Statistic.h.
Referenced by DGtal::Statistic< TQuantity >::operator+=(), DGtal::Statistic< TQuantity >::operator=(), and DGtal::Statistic< TQuantity >::Statistic().
The documentation for this class was generated from the following files:
Statistic.h
Statistic.ih