DGtal: DGtal::Object< TDigitalTopology, TDigitalSet > Class Template Reference
DGtal::Object< TDigitalTopology, TDigitalSet > Class Template Reference
#include <Object.h>
Data Structures
struct Edge
struct VertexMap
Public Types
typedef TDigitalSet DigitalSet
typedef TDigitalTopology DigitalTopology
typedef
DigitalTopology::ReverseTopology ReverseTopology
typedef DigitalSet::Size Size
typedef DigitalSet::Point Point
typedef DigitalTopology::Point DTPoint
typedef DigitalSet::Domain Domain
typedef Domain::Space Space
typedef DigitalSetSelector
< Domain, SMALL_DS+HIGH_ITER_DS >
::Type SmallSet
typedef
DigitalTopology::ForegroundAdjacency ForegroundAdjacency
typedef
DigitalTopology::BackgroundAdjacency BackgroundAdjacency
typedef Object
< ReverseTopology, DigitalSet > ComplementObject
typedef Object
< DigitalTopology, SmallSet > SmallObject
typedef Object
< ReverseTopology, SmallSet > SmallComplementObject
typedef TDigitalSet VertexSet
typedef DigitalSet::Point Vertex
typedef DigitalSet::ConstIterator ConstIterator
Public Member Functions
Object ()
Object (Clone< DigitalTopology > aTopology, Clone< DigitalSet > aPointSet, Connectedness cxn=UNKNOWN)
Object (Clone< DigitalTopology > aTopology, Clone< Domain > domain)
Object (const Object &other)
~Object ()
Object & operator= (const Object &other)
Size size () const
const Domain & domain () const
CowPtr< Domain > domainPointer () const
const DigitalSet & pointSet () const
DigitalSet & pointSet ()
const DigitalTopology & topology () const
const ForegroundAdjacency & adjacency () const
SmallObject neighborhood (const Point &p) const
Size neighborhoodSize (const Point &p) const
SmallObject properNeighborhood (const Point &p) const
Size properNeighborhoodSize (const Point &p) const
Object border () const
template<typename OutputObjectIterator >
Size writeComponents (OutputObjectIterator &it) const
Connectedness connectedness () const
Connectedness computeConnectedness () const
ConstIterator begin () const
ConstIterator end () const
Size degree (const Vertex &v) const
Size bestCapacity () const
template<typename OutputIterator >
void writeNeighbors (OutputIterator &it, const Vertex &v) const
template<typename OutputIterator , typename VertexPredicate >
void writeNeighbors (OutputIterator &it, const Vertex &v, const VertexPredicate &pred) const
template<typename TAdjacency >
SmallObject geodesicNeighborhood (const TAdjacency &adj, const Point &p, unsigned int k) const
template<typename TAdjacency >
SmallComplementObject geodesicNeighborhoodInComplement (const TAdjacency &adj, const Point &p, unsigned int k) const
bool isSimple (const Point &v) const
void selfDisplay (std::ostream &out) const
bool isValid () const
std::string className () const
template<typename OutputObjectIterator >
DGtal::Object
< TDigitalTopology,
TDigitalSet >::Size writeComponents (OutputObjectIterator &it) const
template<typename TAdjacency >
DGtal::Object
< TDigitalTopology,
TDigitalSet >::SmallObject geodesicNeighborhood (const TAdjacency &adj, const Point &p, unsigned int k) const
template<typename TAdjacency >
DGtal::Object
< TDigitalTopology,
TDigitalSet >
::SmallComplementObject geodesicNeighborhoodInComplement (const TAdjacency &adj, const Point &p, unsigned int k) const
Private Attributes
CowPtr< DigitalTopology > myTopo
CowPtr< DigitalSet > myPointSet
Connectedness myConnectedness
Detailed Description
template<typename TDigitalTopology, typename TDigitalSet>
class DGtal::Object< TDigitalTopology, TDigitalSet >
Aim: An object (or digital object) represents a set in some digital space associated with a digital topology.
Description of template class 'Object'
The digital topology induces a connectedness relation on the object (transitive closure of the foreground adjacency) and a connectedness relation on the complement of the set (transitive closure of the background adjacency).
Objects may be connected or not. The connectedness is stored with the object, if it is known. Objects have a border, which are the points which touch the complement in the sense of background adjacency.
export: An Object realizes the concept CDrawableWithBoard2D. It may be displayed with a Board2D, and is by default displayed as a set of digital points. An Object reacts to the mode "DrawAdjacencies". In this case the set of points and the adjacency relations are displayed.
Model of CUndirectedSimpleLocalGraph and CUndirectedSimpleGraph.
Template Parameters
TDigitalTopology any realization of DigitalTopology.
TDigitalSet any model of CDigitalSet.*
See Also
testObject.cpp
testObject-benchmark.cpp
Examples:
topology/3dBorderExtraction.cpp, and topology/3dBorderExtractionImg.cpp.
Definition at line 92 of file Object.h.
Member Typedef Documentation
template<typename TDigitalTopology, typename TDigitalSet> typedef DigitalTopology::BackgroundAdjacency DGtal::Object< TDigitalTopology, TDigitalSet >::BackgroundAdjacency
Definition at line 110 of file Object.h.
template<typename TDigitalTopology, typename TDigitalSet> typedef Object<ReverseTopology, DigitalSet> DGtal::Object< TDigitalTopology, TDigitalSet >::ComplementObject
Definition at line 111 of file Object.h.
template<typename TDigitalTopology, typename TDigitalSet> typedef DigitalSet::ConstIterator DGtal::Object< TDigitalTopology, TDigitalSet >::ConstIterator
Definition at line 121 of file Object.h.
template<typename TDigitalTopology, typename TDigitalSet> typedef TDigitalSet DGtal::Object< TDigitalTopology, TDigitalSet >::DigitalSet
Definition at line 96 of file Object.h.
template<typename TDigitalTopology, typename TDigitalSet> typedef TDigitalTopology DGtal::Object< TDigitalTopology, TDigitalSet >::DigitalTopology
Definition at line 97 of file Object.h.
template<typename TDigitalTopology, typename TDigitalSet> typedef DigitalSet::Domain DGtal::Object< TDigitalTopology, TDigitalSet >::Domain
Definition at line 104 of file Object.h.
template<typename TDigitalTopology, typename TDigitalSet> typedef DigitalTopology::Point DGtal::Object< TDigitalTopology, TDigitalSet >::DTPoint
Definition at line 102 of file Object.h.
template<typename TDigitalTopology, typename TDigitalSet> typedef DigitalTopology::ForegroundAdjacency DGtal::Object< TDigitalTopology, TDigitalSet >::ForegroundAdjacency
Definition at line 109 of file Object.h.
template<typename TDigitalTopology, typename TDigitalSet> typedef DigitalSet::Point DGtal::Object< TDigitalTopology, TDigitalSet >::Point
Definition at line 100 of file Object.h.
template<typename TDigitalTopology, typename TDigitalSet> typedef DigitalTopology::ReverseTopology DGtal::Object< TDigitalTopology, TDigitalSet >::ReverseTopology
Definition at line 98 of file Object.h.
template<typename TDigitalTopology, typename TDigitalSet> typedef DigitalSet::Size DGtal::Object< TDigitalTopology, TDigitalSet >::Size
Definition at line 99 of file Object.h.
template<typename TDigitalTopology, typename TDigitalSet> typedef Object<ReverseTopology, SmallSet> DGtal::Object< TDigitalTopology, TDigitalSet >::SmallComplementObject
Definition at line 113 of file Object.h.
template<typename TDigitalTopology, typename TDigitalSet> typedef Object<DigitalTopology, SmallSet> DGtal::Object< TDigitalTopology, TDigitalSet >::SmallObject
Definition at line 112 of file Object.h.
template<typename TDigitalTopology, typename TDigitalSet> typedef DigitalSetSelector< Domain, SMALL_DS + HIGH_ITER_DS >::Type DGtal::Object< TDigitalTopology, TDigitalSet >::SmallSet
Definition at line 108 of file Object.h.
template<typename TDigitalTopology, typename TDigitalSet> typedef Domain::Space DGtal::Object< TDigitalTopology, TDigitalSet >::Space
Definition at line 105 of file Object.h.
template<typename TDigitalTopology, typename TDigitalSet> typedef DigitalSet::Point DGtal::Object< TDigitalTopology, TDigitalSet >::Vertex
Definition at line 117 of file Object.h.
template<typename TDigitalTopology, typename TDigitalSet> typedef TDigitalSet DGtal::Object< TDigitalTopology, TDigitalSet >::VertexSet
Definition at line 116 of file Object.h.
Constructor & Destructor Documentation
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Object< TDigitalTopology, TDigitalSet >::Object () inline
Constructor. The object is not valid.
Constructor.
Parameters
aTopology the digital topology chosen for this set, a copy of which is stored in the object.
aPointSet the set of points of the object. It is copied in the object.
Definition at line 59 of file Object.ih.
References DGtal::UNKNOWN.
   : myTopo( 0 ), myPointSet( 0 ), myConnectedness( UNKNOWN )
 {
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Object< TDigitalTopology, TDigitalSet >::Object (Clone< DigitalTopology > aTopology, Clone< DigitalSet > aPointSet, Connectedness cxn = UNKNOWN) inline
Constructor.
Parameters
aTopology the digital topology chosen for this set, a copy of which is stored in the object.
aPointSet the set of points of the object. It is copied in the object.
cxn the connectedness (default is UNKNOWN).
Constructor.
Parameters
aTopology the digital topology chosen for this set, a copy of which is stored in the object.
aPointSet the set of points of the object. It is copied in the object.
Definition at line 76 of file Object.ih.
   : myTopo( aTopology ),
     myPointSet( aPointSet ),
     myConnectedness( cxn )
 {
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Object< TDigitalTopology, TDigitalSet >::Object (Clone< DigitalTopology > aTopology, Clone< Domain > aDomain) inline
Constructor of an empty object by providing a domain.
Parameters
aTopology the digital topology chosen for this set, a copy of which is stored in the object.
domain any domain related to the given topology.
Constructor of an empty object by providing a domain.
Parameters
aTopology the digital topology chosen for this set, a copy of which is stored in the object.
aDomain any domain related to the given topology.
Definition at line 113 of file Object.ih.
   : myTopo( new DigitalTopology( aTopology ) ),
     myPointSet( new DigitalSet( aDomain ) ),
     myConnectedness( CONNECTED )
 {
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Object< TDigitalTopology, TDigitalSet >::Object (const Object< TDigitalTopology, TDigitalSet > & other) inline
Copy constructor.
Parameters
other the object to clone.
The copy is smart in the sense that the digital set is referenced, and will be copied only if the set is changed.
Definition at line 95 of file Object.ih.
   : myTopo( other.myTopo ),
     myPointSet( other.myPointSet ),
     myConnectedness( other.myConnectedness )
 {
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Object< TDigitalTopology, TDigitalSet >::~Object () inline
Destructor.
Definition at line 127 of file Object.ih.
 {
 }
Member Function Documentation
template<typename TDigitalTopology , typename TDigitalSet > const TDigitalTopology::ForegroundAdjacency & DGtal::Object< TDigitalTopology, TDigitalSet >::adjacency () const inline
Returns
a const reference to the adjacency of this object.
Definition at line 224 of file Object.ih.
 {
   return myTopo->kappa();
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Object< TDigitalTopology, TDigitalSet >::ConstIterator DGtal::Object< TDigitalTopology, TDigitalSet >::begin () const inline
Definition at line 579 of file Object.ih.
 {
   return myPointSet->begin();
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Object< TDigitalTopology, TDigitalSet >::Size DGtal::Object< TDigitalTopology, TDigitalSet >::bestCapacity () const inline
Returns
the maximum number of neighbors for a vertex of this object
Definition at line 612 of file Object.ih.
 {
   return myTopo->kappa().bestCapacity();
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Object< TDigitalTopology, TDigitalSet > DGtal::Object< TDigitalTopology, TDigitalSet >::border () const inline
Returns
the border of this object (the set of points of this which is lambda()-adjacent with some point of the background).
NB : the background adjacency should be a symmetric relation.
Returns
the border of this object (the set of points of this which is lambda()-adjacent with some point of the background).
Examples:
topology/3dBorderExtractionImg.cpp.
Definition at line 396 of file Object.ih.
References DGtal::Object< TDigitalTopology, TDigitalSet >::pointSet().
 {
   typedef std::vector<Vertex> Container;
   typedef typename Container::const_iterator ContainerConstIterator;
   typedef typename DigitalSet::ConstIterator DigitalSetConstIterator;
   typedef typename DigitalSet::ConstIterator DigitalSetConstIterator;
   //typedef typename Domain::Predicate Predicate;
   // Intermediate container that is fast writable.
   const DigitalSet & mySet = pointSet();
   Object<DigitalTopology, DigitalSet> output( topology(),
                                               mySet.domainPointer() );
   DigitalSet & outputSet = output.pointSet();
   // Loop on all points of the set.
   Container tmp_local_points;
   const DigitalSetConstIterator it_end = mySet.end();
   for ( DigitalSetConstIterator it = mySet.begin();
       it != it_end;
       ++it )
   {
     std::back_insert_iterator< Container > back_ins_it( tmp_local_points );
     // Computing neighborhood within domain.
     topology().lambda().writeNeighbors
     ( back_ins_it, *it, domain().predicate() );
     // Checks if any point is not in the object.
     const ContainerConstIterator itc_end( tmp_local_points.end() );
     for ( ContainerConstIterator itc = tmp_local_points.begin();
         itc != itc_end;
         ++itc )
       if ( pointSet().find( *itc ) == it_end )
       {
         outputSet.insertNew( *it );
         break;
       }
     tmp_local_points.clear();
   }
   return output;
 }
template<typename TDigitalTopology , typename TDigitalSet > std::string DGtal::Object< TDigitalTopology, TDigitalSet >::className () const inline
Default drawing style object.
Returns
the dyn. alloc. default style for this object.
the style name used for drawing this object.
Definition at line 925 of file Object.ih.
Referenced by DGtal::Display2DFactory::draw(), and DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   return "Object";
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Connectedness DGtal::Object< TDigitalTopology, TDigitalSet >::computeConnectedness () const
If 'connectedness() == UNKNOWN', computes the connectedness of this object. After that, the connectedness of 'this' is either CONNECTED or DISCONNECTED.
Returns
the connectedness of this object. Either CONNECTED or DISCONNECTED.
See Also
connectedness
Definition at line 541 of file Object.ih.
References DGtal::CONNECTED, DGtal::DISCONNECTED, DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::expand(), DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::finished(), DGtal::UNKNOWN, and DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::visitedVertices().
Referenced by DGtal::Object< TDigitalTopology, TDigitalSet >::isSimple().
 {
   if ( myConnectedness == UNKNOWN )
   {
     if ( pointSet().empty() )
       myConnectedness = CONNECTED;
     else
     {
       // Take first point
       Vertex p = *( pointSet().begin() );
       BreadthFirstVisitor< Object, std::set<Vertex> > visitor( *this, p );
       while ( ! visitor.finished() )
        {
          visitor.expand();
        }
       myConnectedness = ( visitor.visitedVertices().size() == pointSet().size() )
         ? CONNECTED : DISCONNECTED;
       // JOL: 2012/11/16 There is apparently now a bug in expander !
       // Very weird considering this was working in 2012/05. Perhaps
       // this is related to some manipulations in predicates.
       //
       // Expander<Object> expander( *this, p );
       // // and expand.
       // while ( expander.nextLayer() )
       //   ;
       // myConnectedness = ( expander.core().size() == pointSet().size() )
       //     ? CONNECTED : DISCONNECTED;
     }
   }
   return myConnectedness;
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Connectedness DGtal::Object< TDigitalTopology, TDigitalSet >::connectedness () const
Returns
the connectedness of this object. Either CONNECTED, DISCONNECTED, or UNKNOWN.
See Also
computeConnectedness
Definition at line 524 of file Object.ih.
 {
   return myConnectedness;
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Object< TDigitalTopology, TDigitalSet >::Size DGtal::Object< TDigitalTopology, TDigitalSet >::degree (const Vertex & v) const inline
Parameters
v any vertex of the object
Returns
the number of neighbors of this vertex
Definition at line 601 of file Object.ih.
 {
   return neighborhoodSize( v );
 }
template<typename TDigitalTopology , typename TDigitalSet > const DGtal::Object< TDigitalTopology, TDigitalSet >::Domain & DGtal::Object< TDigitalTopology, TDigitalSet >::domain () const inline
A const reference to the embedding domain.
Definition at line 168 of file Object.ih.
 {
   return myPointSet->domain();
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::CowPtr< typename DGtal::Object< TDigitalTopology, TDigitalSet >::Domain > DGtal::Object< TDigitalTopology, TDigitalSet >::domainPointer () const inline
A counted pointer to the embedding domain.
Definition at line 176 of file Object.ih.
 {
   return myPointSet->domainPointer();
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Object< TDigitalTopology, TDigitalSet >::ConstIterator DGtal::Object< TDigitalTopology, TDigitalSet >::end () const inline
Definition at line 587 of file Object.ih.
 {
   return myPointSet->end();
 }
template<typename TDigitalTopology, typename TDigitalSet> template<typename TAdjacency > SmallObject DGtal::Object< TDigitalTopology, TDigitalSet >::geodesicNeighborhood (const TAdjacency & adj, const Point & p, unsigned int k) const
Geodesic neighborhood of point [p] and order [k] in the object for the given metric adjacency.
template<typename TDigitalTopology, typename TDigitalSet> template<typename TAdjacency > DGtal::Object<TDigitalTopology, TDigitalSet>::SmallObject DGtal::Object< TDigitalTopology, TDigitalSet >::geodesicNeighborhood (const TAdjacency & adj, const Point & p, unsigned int k) const inline
Geodesic neighborhood of point [p] and order [k] in the object for the given metric adjacency.
Definition at line 711 of file Object.ih.
References DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::current(), and DGtal::Object< TDigitalTopology, TDigitalSet >::pointSet().
 {
   // Local types.
   typedef std::vector<Vertex> Container;
   typedef MetricAdjacency<Space, Space::dimension> AlphaAdjacency;
   typedef MetricAdjacency<Space, 1> OmegaAdjacency;
   typedef DGtal::DigitalTopology<TAdjacency, OmegaAdjacency> LocalTopology;
   typedef Object<LocalTopology, SmallSet> LocalObject;
   typedef HyperRectDomain<Space> LocalDomain;
   AlphaAdjacency alpha;
   OmegaAdjacency omega;
   // Intermediate container that is fast writable.
   Container tmp_local_points;
   std::back_insert_iterator< Container > back_ins_it( tmp_local_points );
   alpha.writeNeighbors( back_ins_it, p, *myPointSet ); // p is not a neighbor itself.
   // Construct local domain.
   Point p1 = p - Point::diagonal(1);
   Point p2 = p + Point::diagonal(1);
   CowPtr<LocalDomain> aDomain( new LocalDomain( p1, p2 ) );
   // Construct local X.
   LocalTopology aTopology( adj, omega );
   LocalObject X( aTopology, aDomain );
   X.pointSet().insertNew( tmp_local_points.begin(), tmp_local_points.end() );
   // A neighborhood is small, so is defined the digital object.
   typename LocalObject::SmallObject neighAdj = X.properNeighborhood( p );
   BreadthFirstVisitor<LocalObject, std::set<Vertex> > visitor
     ( X, neighAdj.pointSet().begin(),
       neighAdj.pointSet().end() );
   while ( ! visitor.finished() )
     {
       typename LocalObject::Size d = visitor.current().second;
       if ( d < k )       visitor.expand(); // we need to go further
       else if ( d == k ) visitor.ignore(); // no need to go further
       else break; // to far away, we exit
     }
   visitor.terminate();
   SmallObject geodesicN( this->topology(), aDomain );
   geodesicN.pointSet().insertNew( visitor.markedVertices().begin(),
                                   visitor.markedVertices().end()  );
   // JOL: 2012/11/16 There is apparently now a bug in expander !
   // Very weird considering this was working in 2012/05. Perhaps
   // this is related to some manipulations in predicates.
   // Expander<LocalObject> expander( X,
   //     neighAdj.pointSet().begin(),
   //     neighAdj.pointSet().end() );
   // for ( unsigned int i = 1; ( i < k ) && ( ! expander.finished() ); ++i )
   //   expander.nextLayer();
   // SmallObject geodesicN( this->topology(), expander.core() );
   return geodesicN;
 }
template<typename TDigitalTopology, typename TDigitalSet> template<typename TAdjacency > SmallComplementObject DGtal::Object< TDigitalTopology, TDigitalSet >::geodesicNeighborhoodInComplement (const TAdjacency & adj, const Point & p, unsigned int k) const
Geodesic neighborhood of point [p] and order [k] in the complemented object for the given metric adjacency.
template<typename TDigitalTopology, typename TDigitalSet> template<typename TAdjacency > DGtal::Object<TDigitalTopology, TDigitalSet>::SmallComplementObject DGtal::Object< TDigitalTopology, TDigitalSet >::geodesicNeighborhoodInComplement (const TAdjacency & adj, const Point & p, unsigned int k) const inline
Geodesic neighborhood of point [p] and order [k] in the complemented object for the given metric adjacency.
Definition at line 779 of file Object.ih.
References DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::current(), and DGtal::Object< TDigitalTopology, TDigitalSet >::pointSet().
 {
   // Local types.
   typedef std::vector<Vertex> Container;
   typedef MetricAdjacency<Space, Space::dimension> AlphaAdjacency;
   typedef MetricAdjacency<Space, 1> OmegaAdjacency;
   typedef DGtal::DigitalTopology<TAdjacency, OmegaAdjacency> LocalTopology;
   typedef Object<LocalTopology, SmallSet> LocalObject;
   typedef HyperRectDomain<Space> LocalDomain;
   // DigitalSetDomain<DigitalSet> limitedX( *myPointSet );
   AlphaAdjacency alpha;
   OmegaAdjacency omega;
   // Intermediate container that is fast writable.
   Container tmp_local_points;
   std::back_insert_iterator< Container > back_ins_it( tmp_local_points );
   NotPointPredicate<DigitalSet> not_pred_is_in_X( *myPointSet );
   alpha.writeNeighbors( back_ins_it, p, not_pred_is_in_X );
   // Construct local domain.
   Point p1 = p - Point::diagonal(1);
   Point p2 = p + Point::diagonal(1);
   CowPtr<LocalDomain> aDomain( new LocalDomain( p1, p2 ) );
   // Construct local Xcomp.
   LocalTopology aTopology( adj, omega );
   LocalObject Xcomp( aTopology, aDomain );
   Xcomp.pointSet().insertNew( tmp_local_points.begin(), tmp_local_points.end() );
   // A neighborhood is small, so is defined the digital object.
   typename LocalObject::SmallObject neighAdj = Xcomp.properNeighborhood( p );
   BreadthFirstVisitor<LocalObject, std::set<Vertex> > visitor
     ( Xcomp, neighAdj.pointSet().begin(),
       neighAdj.pointSet().end() );
   while ( ! visitor.finished() )
     {
       typename LocalObject::Size d = visitor.current().second;
       if ( d < k )       visitor.expand(); // we need to go further
       else if ( d == k ) visitor.ignore(); // no need to go further
       else break; // to far away, we exit
     }
   visitor.terminate();
   SmallComplementObject geodesicN( this->topology().reverseTopology(),
                                    aDomain );
   geodesicN.pointSet().insertNew( visitor.markedVertices().begin(),
                                   visitor.markedVertices().end()  );
   // JOL: 2012/11/16 There is apparently now a bug in expander !
   // Very weird considering this was working in 2012/05. Perhaps
   // this is related to some manipulations in predicates.
   // Expander<LocalObject> expander( Xcomp,
   //     neighAdj.pointSet().begin(),
   //     neighAdj.pointSet().end() );
   // for ( unsigned int i = 1; ( i < k ) && ( ! expander.finished() ); ++i )
   //   expander.nextLayer();
   // SmallComplementObject geodesicN( this->topology().reverseTopology(),
   //     expander.core() );
   return geodesicN;
 }
template<typename TDigitalTopology , typename TDigitalSet > bool DGtal::Object< TDigitalTopology, TDigitalSet >::isSimple (const Point & v) const inline
[Bertrand, 1994] A voxel v is simple for a set X if #C6 [G6 (v, X)] = #C18[G18(v, X^c)] = 1, where #Ck [Y] denotes the number of k-connected components of a set Y.
We adapt this definition to (kappa,lambda) connectednesses. Be careful, such a definition is valid only for Jordan couples in dimension 2 and 3.
Returns
'true' if this point is simple.
Definition at line 855 of file Object.ih.
References DGtal::Object< TDigitalTopology, TDigitalSet >::computeConnectedness(), DGtal::CONNECTED, and DGtal::Object< TDigitalTopology, TDigitalSet >::pointSet().
 {
   static const int kappa_n =
     DigitalTopologyTraits< ForegroundAdjacency, BackgroundAdjacency, Space::dimension >::GEODESIC_NEIGHBORHOOD_SIZE;
   static const int lambda_n =
     DigitalTopologyTraits< BackgroundAdjacency, ForegroundAdjacency, Space::dimension >::GEODESIC_NEIGHBORHOOD_SIZE;
   SmallObject Gkappa_X
   = geodesicNeighborhood( topology().kappa(),
                           v, kappa_n ); // Space::dimension );
   if ( Gkappa_X.computeConnectedness() == CONNECTED )
   {
     if ( Gkappa_X.pointSet().empty() )
       return false;
     SmallComplementObject Glambda_compX
       = geodesicNeighborhoodInComplement( topology().lambda(),
                                           v, lambda_n ); // Space::dimension );
     return ( Glambda_compX.computeConnectedness()
              == CONNECTED )
       && ( ! Glambda_compX.pointSet().empty() );
   }
   return false;
 }
template<typename TDigitalTopology , typename TDigitalSet > bool DGtal::Object< TDigitalTopology, TDigitalSet >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 908 of file Object.ih.
 {
   return ( *myPointSet != 0 ) && (*myTopo != 0 );
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Object< TDigitalTopology, TDigitalSet >::SmallObject DGtal::Object< TDigitalTopology, TDigitalSet >::neighborhood (const Point & p) const inline
Let A be this object with foreground adjacency k and N_k(p) the k-neighborhood of p. Returns the set A intersected with N_k(p).
Parameters
p any point (in the domain of the digital object, not necessarily in the object).
Returns
the kappa-neighborhood of [p] in this object.
See Also
neighborhoodSize
NB: if you need only the size of neighborhood, use neighborhoodSize.
Let A be this object with foreground adjacency k and N_k(p) the k-neighborhood of p. Returns the set A intersected with N_k(p).
Parameters
p any point (in the domain of the digital object, not necessarily in the object).
Returns
the kappa-neighborhood of [p] in this object.
Definition at line 246 of file Object.ih.
References DGtal::DigitalSetBySTLSet< TDomain, TCompare >::insertNew(), and DGtal::Object< TDigitalTopology, TDigitalSet >::pointSet().
 {
   typedef std::vector<Vertex> Container;
   typedef typename Container::const_iterator ContainerConstIterator;
   typedef typename DigitalSet::ConstIterator DigitalSetConstIterator;
   // Intermediate container that is fast writable.
   Container tmp_local_points;
   std::back_insert_iterator< Container > back_ins_it( tmp_local_points );
   adjacency().writeNeighbors( back_ins_it, p );
   tmp_local_points.push_back( p );
   // A neighborhood is small, so is defined the digital object.
   SmallObject neighA( myTopo, pointSet().domainPointer() );
   const ContainerConstIterator it_end( tmp_local_points.end() );
   const DigitalSetConstIterator not_found( pointSet().end() );
   SmallSet & neighASet = neighA.pointSet();
   for ( ContainerConstIterator it = tmp_local_points.begin();
       it != it_end;
       ++it )
     if ( pointSet().find( *it ) != not_found )
       neighASet.insertNew( *it ); // insertNew is guaranteed by construction.
   return neighA;
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Object< TDigitalTopology, TDigitalSet >::Size DGtal::Object< TDigitalTopology, TDigitalSet >::neighborhoodSize (const Point & p) const inline
Parameters
p any point (in the domain of the digital object, not necessarily in the object).
Returns
the cardinal of the kappa-neighborhood of [p] in this object.
See Also
neighborhood
NB: faster than computing the neighborhood then computing its cardinal.
Definition at line 285 of file Object.ih.
 {
   typedef std::vector<Vertex> Container;
   typedef typename Container::const_iterator ContainerConstIterator;
   typedef typename DigitalSet::ConstIterator DigitalSetConstIterator;
   // Intermediate container that is fast writable.
   Container tmp_local_points;
   std::back_insert_iterator< Container > back_ins_it( tmp_local_points );
   adjacency().writeNeighbors( back_ins_it, p );
   tmp_local_points.push_back( p );
   // A neighborhood is small, so is defined the digital object.
   const ContainerConstIterator it_end( tmp_local_points.end() );
   const DigitalSetConstIterator not_found( pointSet().end() );
   Size nb = 0;
   for ( ContainerConstIterator it = tmp_local_points.begin();
       it != it_end;
       ++it )
     if ( pointSet().find( *it ) != not_found )
       ++nb;
   return nb;
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Object< TDigitalTopology, TDigitalSet > & DGtal::Object< TDigitalTopology, TDigitalSet >::operator= (const Object< TDigitalTopology, TDigitalSet > & other) inline
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'.
Definition at line 140 of file Object.ih.
References DGtal::Object< TDigitalTopology, TDigitalSet >::myConnectedness, DGtal::Object< TDigitalTopology, TDigitalSet >::myPointSet, and DGtal::Object< TDigitalTopology, TDigitalSet >::myTopo.
 {
   if ( this != &other )
   {
     myTopo = other.myTopo;
     myPointSet = other.myPointSet;
     myConnectedness = other.myConnectedness;
   }
   return *this;
 }
template<typename TDigitalTopology , typename TDigitalSet > const TDigitalSet & DGtal::Object< TDigitalTopology, TDigitalSet >::pointSet () const inline
A const reference on the point set defining the points of the digital object.
Definition at line 189 of file Object.ih.
Referenced by DGtal::Object< TDigitalTopology, TDigitalSet >::border(), DGtal::Display2DFactory::draw(), DGtal::Display3DFactory< TSpace, TKSpace >::draw(), DGtal::Display2DFactory::drawWithAdjacencies(), DGtal::Display3DFactory< TSpace, TKSpace >::drawWithAdjacencies(), DGtal::Object< TDigitalTopology, TDigitalSet >::geodesicNeighborhood(), DGtal::Object< TDigitalTopology, TDigitalSet >::geodesicNeighborhoodInComplement(), DGtal::Object< TDigitalTopology, TDigitalSet >::isSimple(), DGtal::Object< TDigitalTopology, TDigitalSet >::neighborhood(), and DGtal::Object< TDigitalTopology, TDigitalSet >::properNeighborhood().
 {
   return *myPointSet;
 }
template<typename TDigitalTopology , typename TDigitalSet > TDigitalSet & DGtal::Object< TDigitalTopology, TDigitalSet >::pointSet () inline
A reference on the point set defining the points of the digital object (may duplicate the set).
Definition at line 201 of file Object.ih.
References DGtal::UNKNOWN.
 {
   myConnectedness = UNKNOWN;
   return *myPointSet;
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Object< TDigitalTopology, TDigitalSet >::SmallObject DGtal::Object< TDigitalTopology, TDigitalSet >::properNeighborhood (const Point & p) const inline
Let A be this object with foreground adjacency k and N*_k(p) the proper k-neighborhood of p. Returns the set A intersected with N*_k(p).
Parameters
p any point (in the domain of the digital object, not necessarily in the object).
Returns
the kappa-neighborhood of [p] in this object, without p.
See Also
properNeighborhoodSize
NB: if you need only the size of the proper neighborhood, use properNeighborhoodSize.
Let A be this object with foreground adjacency k and N*_k(p) the proper k-neighborhood of p. Returns the set A intersected with N*_k(p).
Parameters
p any point (in the domain of the digital object, not necessarily in the object).
Returns
the kappa-neighborhood of [p] in this object, without p.
Definition at line 324 of file Object.ih.
References DGtal::DigitalSetBySTLSet< TDomain, TCompare >::insertNew(), and DGtal::Object< TDigitalTopology, TDigitalSet >::pointSet().
Referenced by DGtal::Display2DFactory::drawWithAdjacencies(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawWithAdjacencies().
 {
   typedef std::vector<Vertex> Container;
   typedef typename Container::const_iterator ContainerConstIterator;
   typedef typename DigitalSet::ConstIterator DigitalSetConstIterator;
   // Intermediate container that is fast writable.
   Container tmp_local_points;
   std::back_insert_iterator< Container > back_ins_it( tmp_local_points );
   adjacency().writeNeighbors( back_ins_it, p );
   // A neighborhood is small, so is defined the digital object.
   SmallObject neighA( myTopo, pointSet().domainPointer() );
   const ContainerConstIterator it_end( tmp_local_points.end() );
   const DigitalSetConstIterator not_found( pointSet().end() );
   SmallSet & neighASet = neighA.pointSet();
   for ( ContainerConstIterator it = tmp_local_points.begin();
       it != it_end;
       ++it )
     if ( pointSet().find( *it ) != not_found )
       neighASet.insertNew( *it ); // insertNew is guaranteed by construction.
   return neighA;
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Object< TDigitalTopology, TDigitalSet >::Size DGtal::Object< TDigitalTopology, TDigitalSet >::properNeighborhoodSize (const Point & p) const inline
Parameters
p any point (in the domain of the digital object, not necessarily in the object).
Returns
the cardinal of the kappa-neighborhood of [p] in this object.
See Also
properNeighborhood
NB: faster than computing the proper neighborhood then computing its cardinal.
Definition at line 363 of file Object.ih.
 {
   typedef std::vector<Vertex> Container;
   typedef typename Container::const_iterator ContainerConstIterator;
   typedef typename DigitalSet::ConstIterator DigitalSetConstIterator;
   // Intermediate container that is fast writable.
   Container tmp_local_points;
   std::back_insert_iterator< Container > back_ins_it( tmp_local_points );
   adjacency().writeNeighbors( back_ins_it, p );
   // A neighborhood is small, so is defined the digital object.
   const ContainerConstIterator it_end( tmp_local_points.end() );
   const DigitalSetConstIterator not_found( pointSet().end() );
   Size nb = 0;
   for ( ContainerConstIterator it = tmp_local_points.begin();
       it != it_end;
       ++it )
     if ( pointSet().find( *it ) != not_found )
       ++nb;
   return nb;
 }
template<typename TDigitalTopology , typename TDigitalSet > void DGtal::Object< TDigitalTopology, TDigitalSet >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 891 of file Object.ih.
 {
   out << "[Object"
   << " topology=" << myTopo
   << " counts=" << myPointSet.count()
   << " set=" << *myPointSet
   << " cxn=" << myConnectedness
   << "]";
 }
template<typename TDigitalTopology , typename TDigitalSet > DGtal::Object< TDigitalTopology, TDigitalSet >::Size DGtal::Object< TDigitalTopology, TDigitalSet >::size () const inline
Returns
the number of elements in the set.
Definition at line 157 of file Object.ih.
 {
   return myPointSet->size();
 }
template<typename TDigitalTopology , typename TDigitalSet > const TDigitalTopology & DGtal::Object< TDigitalTopology, TDigitalSet >::topology () const inline
Returns
a const reference to the topology of this object.
Definition at line 213 of file Object.ih.
 {
   return *myTopo;
 }
template<typename TDigitalTopology, typename TDigitalSet> template<typename OutputObjectIterator > Size DGtal::Object< TDigitalTopology, TDigitalSet >::writeComponents (OutputObjectIterator & it) const
  Computes the connected components of the object and writes
  them on the output iterator [it].
  @tparam OutputObjectIterator the type of an output iterator in
  a container of Object s.
  @param it the output iterator. *it is an Object.
  @return the number of components.
  NB: Be careful that the [it] should not be an output iterator
  pointing in the same container containing 'this'. The following
  example might make a 'bus error' because the vector might be
  resized during insertion.
typedef ... MyObject;
      vector<MyObject> objects;
      objects[ 0 ] = ... some object;
      ...
      back_insert_iterator< vector<MyObject> > it( objects );
      objects[ 0 ].writeComponents( it ); // it points in same container as this.
      // might 'bus error'.
If you wish to use an output iterator (like a std::back_insert_iterator) in the same container containing your object, you can write:
MyObject(objects[ 0 ]).writeComponents(it);
It is nearly as efficient (the clone uses smart copy on write pointers) and works in any case. You might even overwrite your object while doing this.
template<typename TDigitalTopology, typename TDigitalSet> template<typename OutputObjectIterator > DGtal::Object<TDigitalTopology, TDigitalSet>::Size DGtal::Object< TDigitalTopology, TDigitalSet >::writeComponents (OutputObjectIterator & it) const inline
Computes the connected components of the object and writes them on the output iterator [it].
Template Parameters
OutputObjectIterator the type of an output iterator in a container of Object s.
Parameters
it the output iterator. *it is an Object.
Definition at line 450 of file Object.ih.
References DGtal::CONNECTED, DGtal::DISCONNECTED, DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::expand(), DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::finished(), and DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::markedVertices().
 {
   Size nb_components = 0;
   if ( pointSet().empty() )
   {
     myConnectedness = CONNECTED;
     return nb_components;
   }
   else
     if ( connectedness() == CONNECTED )
     {
       *it++ = *this;
       return 1;
     }
   typedef typename DigitalSet::ConstIterator DigitalSetConstIterator;
   DigitalSetConstIterator it_object = pointSet().begin();
   Point p( *it_object++ );
   // first component.
   BreadthFirstVisitor< Object, std::set<Vertex> > visitor( *this, p );
   while ( ! visitor.finished() ) visitor.expand();
   DigitalSet visited( domainPointer() );
   visited.insertNew( visitor.markedVertices().begin(),
                      visitor.markedVertices().end() );
   *it++ = Object( myTopo, visited, CONNECTED );
   ++nb_components;
   while ( it_object != pointSet().end() )
   {
     p = *it_object++;
     if ( visited.find( p ) == visited.end() )
     {
       BreadthFirstVisitor< Object, std::set<Vertex> > visitor2( *this, p );
       while ( ! visitor2.finished() ) visitor2.expand();
       DigitalSet visited2( domainPointer() );
       visited2.insertNew( visitor2.markedVertices().begin(),
                           visitor2.markedVertices().end() );
       *it++ = Object( myTopo, visited2, CONNECTED );
       ++nb_components;
       visited += visited2;
     }
   }
   // Expander<Object> expander( *this, p );
   // while ( expander.nextLayer() )
   //   ;
   // Object component( myTopo, expander.core(), CONNECTED );
   // *it++ = component;
   // ++nb_components;
   // DigitalSet visited( expander.core() );
   // while ( it_object != pointSet().end() )
   // {
   //   p = *it_object++;
   //   if ( visited.find( p ) == visited.end() )
   //   {
   //     Expander<Object> expander2( *this, p );
   //     while ( expander2.nextLayer() )
   //       ;
   //     Object component2( myTopo, expander2.core(), CONNECTED );
   //     *it++ = component2;
   //     ++nb_components;
   //     visited += expander2.core();
   //   }
   // }
   myConnectedness = nb_components == 1 ? CONNECTED : DISCONNECTED;
   return nb_components;
 }
template<typename TDigitalTopology , typename TDigitalSet > template<typename OutputIterator > void DGtal::Object< TDigitalTopology, TDigitalSet >::writeNeighbors (OutputIterator & it, const Vertex & v) const inline
Writes the neighbors of a vertex using an output iterator
Template Parameters
OutputIterator the type of an output iterator writing in a container of vertices.
Parameters
it the output iterator
v the vertex whose neighbors will be writeNeighbors
Writes the neighbors of a vertex using an output iterator
Template Parameters
OutputObjectIterator the type of an output iterator writing in a container of vertices.
Parameters
it the output iterator
v the vertex whose neighbors will be writeNeighbors
Definition at line 633 of file Object.ih.
 {
   typedef std::vector<Vertex> Container;
   typedef typename Container::const_iterator ContainerConstIterator;
   typedef typename DigitalSet::ConstIterator DigitalSetConstIterator;
   // Intermediate container that is fast writable.
   Container tmp_local_points;
   std::back_insert_iterator< Container > back_ins_it( tmp_local_points );
   adjacency().writeNeighbors( back_ins_it, v );
   // A neighborhood is small, so is defined the digital object.
   const ContainerConstIterator it_end( tmp_local_points.end() );
   const DigitalSetConstIterator not_found( pointSet().end() );
   for ( ContainerConstIterator cit = tmp_local_points.begin();
       cit != it_end;
       ++cit )
     if ( pointSet().find( *cit ) != not_found )
       *it++ = *cit;
 }
template<typename TDigitalTopology , typename TDigitalSet > template<typename OutputIterator , typename VertexPredicate > void DGtal::Object< TDigitalTopology, TDigitalSet >::writeNeighbors (OutputIterator & it, const Vertex & v, const VertexPredicate & pred) const inline
Writes the neighbors of a vertex which satisfy a predicate using an output iterator
Template Parameters
OutputIterator the type of an output iterator writing in a container of vertices.
VertexPredicate the type of the predicate
Parameters
it the output iterator
v the vertex whose neighbors will be written
pred the predicate that must be satisfied
Writes the neighbors of a vertex which satisfy a predicate using an output iterator
Template Parameters
OutputObjectIterator the type of an output iterator writing in a container of vertices.
VertexPredicate the type of the predicate
Parameters
it the output iterator
v the vertex whose neighbors will be written
pred the predicate that must be satisfied
Definition at line 676 of file Object.ih.
 {
   typedef std::vector<Vertex> Container;
   typedef typename Container::const_iterator ContainerConstIterator;
   typedef typename DigitalSet::ConstIterator DigitalSetConstIterator;
   // Intermediate container that is fast writable.
   Container tmp_local_points;
   std::back_insert_iterator< Container > back_ins_it( tmp_local_points );
   adjacency().writeNeighbors( back_ins_it, v );
   // A neighborhood is small, so is defined the digital object.
   const ContainerConstIterator it_end( tmp_local_points.end() );
   const DigitalSetConstIterator not_found( pointSet().end() );
   for ( ContainerConstIterator cit = tmp_local_points.begin();
       cit != it_end;
       ++cit )
     if ( ( pointSet().find( *cit ) != not_found ) && pred(*cit) )
       *it++ = *cit;
 }
Field Documentation
template<typename TDigitalTopology, typename TDigitalSet> Connectedness DGtal::Object< TDigitalTopology, TDigitalSet >::myConnectedness mutable private
Connectedness of this object. Either CONNECTED, DISCONNECTED, or UNKNOWN.
Definition at line 513 of file Object.h.
Referenced by DGtal::Object< TDigitalTopology, TDigitalSet >::operator=().
template<typename TDigitalTopology, typename TDigitalSet> CowPtr<DigitalSet> DGtal::Object< TDigitalTopology, TDigitalSet >::myPointSet private
A copy on write pointer on the associated (owned or not) point set
Definition at line 508 of file Object.h.
Referenced by DGtal::Object< TDigitalTopology, TDigitalSet >::operator=().
template<typename TDigitalTopology, typename TDigitalSet> CowPtr<DigitalTopology> DGtal::Object< TDigitalTopology, TDigitalSet >::myTopo private
the digital topology of the object.
Definition at line 503 of file Object.h.
Referenced by DGtal::Object< TDigitalTopology, TDigitalSet >::operator=().
The documentation for this class was generated from the following files:
Object.h
Object.ih