DGtal: DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor > Class Template Reference
DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor > Class Template Reference
#include <LocalEstimatorFromSurfelFunctorAdapter.h>
Public Types
typedef TDigitalSurface DigitalSurface
typedef TMetric Metric
typedef TMetric::Value Value
typedef TFunctorOnSurfel FunctorOnSurfel
typedef TConvolutionFunctor ConvolutionFunctor
typedef TFunctorOnSurfel::Quantity Quantity
Public Member Functions
BOOST_CONCEPT_ASSERT ((CMetric< TMetric >))
BOOST_CONCEPT_ASSERT ((CLocalEstimatorFromSurfelFunctor< TFunctorOnSurfel >))
BOOST_CONCEPT_ASSERT ((CUnaryFunctor< TConvolutionFunctor, double, double >))
BOOST_CONCEPT_ASSERT ((CDigitalSurfaceContainer< TDigitalSurface >))
LocalEstimatorFromSurfelFunctorAdapter (ConstAlias< DigitalSurface > aSurface, ConstAlias< TMetric > aMetric, Alias< FunctorOnSurfel > aFunctor, ConstAlias< ConvolutionFunctor > aConvolutionFunctor)
~LocalEstimatorFromSurfelFunctorAdapter ()
void init (const double h, const Value radius)
template<typename SurfelConstIterator >
Quantity eval (const SurfelConstIterator &it) const
template<typename SurfelConstIterator , typename OutputIterator >
OutputIterator eval (const SurfelConstIterator &itb, const SurfelConstIterator &ite, OutputIterator result) const
void selfDisplay (std::ostream &out) const
bool isValid () const
template<typename SurfelConstIterator >
DGtal::LocalEstimatorFromSurfelFunctorAdapter
< DigitalSurf, TMetric,
Functor, ConvFunctor >
::Quantity eval (const SurfelConstIterator &it) const
Protected Member Functions
LocalEstimatorFromSurfelFunctorAdapter ()
Private Types
typedef
FunctorOnSurfel::SCellEmbedder Embedder
typedef std::binder1st< Metric > MetricToPoint
typedef Composer< Embedder,
MetricToPoint, Value > VertexFunctor
typedef
DistanceBreadthFirstVisitor
< DigitalSurface,
VertexFunctor > Visitor
Private Member Functions
LocalEstimatorFromSurfelFunctorAdapter (const LocalEstimatorFromSurfelFunctorAdapter &other)
LocalEstimatorFromSurfelFunctorAdapter & operator= (const LocalEstimatorFromSurfelFunctorAdapter &other)
Private Attributes
const DigitalSurface * mySurface
FunctorOnSurfel * myFunctor
const Metric * myMetric
double myH
bool myInit
const Embedder myEmbedder
const ConvolutionFunctor * myConvFunctor
Value myRadius
Detailed Description
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor>
class DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >
Aim: this class adapts any local functor on digital surface element to define a local estimator.
Description of template class 'LocalEstimatorFromSurfelFunctorAdapter'
When we evaluate the adapted estimator at a surfel s, we first identify the set of neighboring around s using a DistanceBreadthFirstVisitor parametrized by a given metric. Then, the estimated quantity is computed applying a functor on the surfel set.
More precisely, this adapter needs a model of CMetric to define the neighborhood and a model of CLocalEstimatorFromSurfelFunctor to perform the local estimator computation. When sent to the functor, the surfels are weighted using the distance from the kernel boundary: weights are defined in [0,1] interval, 1 for the center and decreasing to 0 with the distance to the specified kernel radius specified during the init(). The shape of the distance-to-weight function is defined by a functor of type TConvolutionFunctor.
Models of TConvolutionFunctor could be for instance DefaultFunctor (returns the distance itself), ConstValueFunctor (returns a constant value) or GaussianKernelFunctor (parametrized by a sigma).
During the init() method, we thus specify the gridstep h and the radius of the ball to consider to define the neighborhood. An instance of the convolution functor should be passed to the constructor.
Note that the visitor used in this class considers the distance function in the ambient space (not a geodesic one for instance) on canonical embedding of surfel elements (cf CanonicSCellEmbedder).
Template Parameters
TDigitalSurface any model of digital surface concept (CDigitalSurfaceContainer)
TMetric any model of CMetric to be used in the neighborhood construction.
TFunctorOnSurfel an estimator on surfel set (model of CLocalEstimatorFromSurfelFunctor)
TConvolutionFunctor type of functor on double [0,1]->[0,1] to implement the response of a symmetric convolution kernel.
Definition at line 106 of file LocalEstimatorFromSurfelFunctorAdapter.h.
Member Typedef Documentation
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> typedef TConvolutionFunctor DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::ConvolutionFunctor
Functor on double to compute convolution weights.
Definition at line 130 of file LocalEstimatorFromSurfelFunctorAdapter.h.
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> typedef TDigitalSurface DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::DigitalSurface
Digital surface type.
Definition at line 118 of file LocalEstimatorFromSurfelFunctorAdapter.h.
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> typedef FunctorOnSurfel::SCellEmbedder DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::Embedder private
Embedded and type definitions.
Definition at line 138 of file LocalEstimatorFromSurfelFunctorAdapter.h.
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> typedef TFunctorOnSurfel DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::FunctorOnSurfel
Functor on surfels type.
Definition at line 127 of file LocalEstimatorFromSurfelFunctorAdapter.h.
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> typedef TMetric DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::Metric
Metric type.
Definition at line 121 of file LocalEstimatorFromSurfelFunctorAdapter.h.
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> typedef std::binder1st<Metric> DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::MetricToPoint private
Definition at line 139 of file LocalEstimatorFromSurfelFunctorAdapter.h.
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> typedef TFunctorOnSurfel::Quantity DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::Quantity
Quantity type.
Definition at line 133 of file LocalEstimatorFromSurfelFunctorAdapter.h.
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> typedef TMetric::Value DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::Value
Metric value type.
Definition at line 124 of file LocalEstimatorFromSurfelFunctorAdapter.h.
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> typedef Composer<Embedder, MetricToPoint, Value> DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::VertexFunctor private
Definition at line 140 of file LocalEstimatorFromSurfelFunctorAdapter.h.
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> typedef DistanceBreadthFirstVisitor<DigitalSurface, VertexFunctor> DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::Visitor private
Definition at line 141 of file LocalEstimatorFromSurfelFunctorAdapter.h.
Constructor & Destructor Documentation
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::LocalEstimatorFromSurfelFunctorAdapter (ConstAlias< DigitalSurface > aSurface, ConstAlias< TMetric > aMetric, Alias< FunctorOnSurfel > aFunctor, ConstAlias< ConvolutionFunctor > aConvolutionFunctor)
Constructor.
Parameters
aSurface a digital surface
aFunctor a functor on digital surface elements.
template<typename DigitalSurf , typename TMetric , typename Functor , typename ConvFunctor > DGtal::LocalEstimatorFromSurfelFunctorAdapter< DigitalSurf, TMetric, Functor, ConvFunctor >::~LocalEstimatorFromSurfelFunctorAdapter () inline
Destructor.
Definition at line 51 of file LocalEstimatorFromSurfelFunctorAdapter.ih.
 {
 }
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::LocalEstimatorFromSurfelFunctorAdapter () protected
Constructor. Forbidden by default (protected to avoid g++ warnings).
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::LocalEstimatorFromSurfelFunctorAdapter (const LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor > & other) private
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
Member Function Documentation
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::BOOST_CONCEPT_ASSERT ((CMetric< TMetric >))
Concept Checks.
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::BOOST_CONCEPT_ASSERT ((CLocalEstimatorFromSurfelFunctor< TFunctorOnSurfel >))
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::BOOST_CONCEPT_ASSERT ((CUnaryFunctor< TConvolutionFunctor, double, double >))
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::BOOST_CONCEPT_ASSERT ((CDigitalSurfaceContainer< TDigitalSurface >))
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> template<typename SurfelConstIterator > DGtal::LocalEstimatorFromSurfelFunctorAdapter<DigitalSurf,TMetric,Functor,ConvFunctor>::Quantity DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::eval (const SurfelConstIterator & it) const inline
Definition at line 89 of file LocalEstimatorFromSurfelFunctorAdapter.ih.
References DGtal::DistanceBreadthFirstVisitor< TGraph, TVertexFunctor, TMarkSet >::current(), DGtal::DistanceBreadthFirstVisitor< TGraph, TVertexFunctor, TMarkSet >::expand(), and DGtal::DistanceBreadthFirstVisitor< TGraph, TVertexFunctor, TMarkSet >::finished().
 {
   ASSERT_MSG( isValid(), "Missing init() before evaluation" );
   MetricToPoint metricToPoint( *myMetric, myEmbedder( *it ));
   VertexFunctor vfunctor( myEmbedder, metricToPoint);
   Visitor visitor( *mySurface, vfunctor, *it);
   Value currentDistance = 0;
   while ( (currentDistance < myRadius) && (! visitor.finished() ))
   {
     typename Visitor::Node node = visitor.current();
     currentDistance = node.second;
     myFunctor->pushSurfel( node.first , myConvFunctor->operator()((myRadius - currentDistance)/myRadius));
     visitor.expand();
   }
   Quantity val = myFunctor->eval();
   myFunctor->reset();
   return val;
 }
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> template<typename SurfelConstIterator > Quantity DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::eval (const SurfelConstIterator & it) const
Returns
the estimated quantity at *it
Parameters
[in] it the surfel iterator at which we evaluate the quantity.
template<typename DigitalSurf , typename TMetric , typename Functor , typename ConvFunctor > template<typename SurfelConstIterator , typename OutputIterator > OutputIterator DGtal::LocalEstimatorFromSurfelFunctorAdapter< DigitalSurf, TMetric, Functor, ConvFunctor >::eval (const SurfelConstIterator & itb, const SurfelConstIterator & ite, OutputIterator result) const inline
Returns
the estimated quantity from itb till ite (exculded)
Parameters
[in] itb starting surfel iterator.
[in] ite end surfel iterator.
[in,out] result resulting output iterator
Definition at line 115 of file LocalEstimatorFromSurfelFunctorAdapter.ih.
 {
   for ( SurfelConstIterator it = itb; it != ite; ++it )
   {
     Quantity q = eval( it );
     *result++ = q;
   }
   return result;
 }
template<typename DigitalSurf , typename TMetric , typename Functor , typename ConvFunctor > void DGtal::LocalEstimatorFromSurfelFunctorAdapter< DigitalSurf, TMetric, Functor, ConvFunctor >::init (const double h, const Value radius) inline
Initialisation of estimator parameters.
Parameters
[in] h grid size (must be >0).
[in] radius radius of the ball kernel.
Definition at line 75 of file LocalEstimatorFromSurfelFunctorAdapter.ih.
 {
   ASSERT(h>0);
   ASSERT(radius>0);
   myH = h;
   myRadius = radius;
   myInit = true;
 }
template<typename DigitalSurf , typename TMetric , typename Functor , typename ConvFunctor > bool DGtal::LocalEstimatorFromSurfelFunctorAdapter< DigitalSurf, TMetric, Functor, ConvFunctor >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 67 of file LocalEstimatorFromSurfelFunctorAdapter.ih.
 {
   return myInit;
 }
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> LocalEstimatorFromSurfelFunctorAdapter& DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::operator= (const LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor > & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
template<typename DigitalSurf , typename TMetric , typename Functor , typename ConvFunctor > void DGtal::LocalEstimatorFromSurfelFunctorAdapter< DigitalSurf, TMetric, Functor, ConvFunctor >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 59 of file LocalEstimatorFromSurfelFunctorAdapter.ih.
 {
   out << "[LocalEstimatorFromSurfelFunctorAdapter]";
 }
Field Documentation
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> const ConvolutionFunctor* DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::myConvFunctor private
Convolution functor.
Definition at line 256 of file LocalEstimatorFromSurfelFunctorAdapter.h.
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> const Embedder DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::myEmbedder private
Embedder object.
Definition at line 253 of file LocalEstimatorFromSurfelFunctorAdapter.h.
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> FunctorOnSurfel* DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::myFunctor private
Functor member.
Definition at line 241 of file LocalEstimatorFromSurfelFunctorAdapter.h.
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> double DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::myH private
Grid step.
Definition at line 247 of file LocalEstimatorFromSurfelFunctorAdapter.h.
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> bool DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::myInit private
Has init been done before eval.
Definition at line 250 of file LocalEstimatorFromSurfelFunctorAdapter.h.
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> const Metric* DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::myMetric private
Distance functor.
Definition at line 244 of file LocalEstimatorFromSurfelFunctorAdapter.h.
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> Value DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::myRadius private
Ball radius.
Definition at line 259 of file LocalEstimatorFromSurfelFunctorAdapter.h.
template<typename TDigitalSurface, typename TMetric, typename TFunctorOnSurfel, typename TConvolutionFunctor> const DigitalSurface* DGtal::LocalEstimatorFromSurfelFunctorAdapter< TDigitalSurface, TMetric, TFunctorOnSurfel, TConvolutionFunctor >::mySurface private
Digital surface member.
Definition at line 238 of file LocalEstimatorFromSurfelFunctorAdapter.h.
The documentation for this class was generated from the following files:
LocalEstimatorFromSurfelFunctorAdapter.h
LocalEstimatorFromSurfelFunctorAdapter.ih