DGtal: DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency > Class Template Reference
DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency > Class Template Reference
#include <ArithmeticalDSSFactory.h>
Public Types
typedef TCoordinate Coordinate
typedef TInteger Integer
typedef DGtal::PointVector
< 2, Coordinate > Point
typedef Point Vector
typedef std::pair< Vector, Vector > Steps
typedef ArithmeticalDSS
< TCoordinate, TInteger,
adjacency > DSS
Static Public Member Functions
static DSS createPattern (const Point &aF, const Point &aL)
static DSS createReversedPattern (const Point &aF, const Point &aL)
Static Private Member Functions
static Vector bezoutVector (const Coordinate &aA, const Coordinate &aB, const Coordinate &aR)
Detailed Description
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8>
class DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency >
Aim: Set of static methods that create digital straight segments (DSS) from some input parameters, eg. patterns (or reversed patterns) from two upper leaning points (or lower leaning points).
Description of template class 'ArithmeticalDSSFactory'
Template Parameters
TCoordinate a model of integer for the DGtal point coordinate
TInteger a model of integer for the DSS parameters (a, b, mu, omega)
adjacency a integer equal to 8 (default) for naive and 8-connected DSS, and 4 for standard and 4-connected DSS.
Definition at line 72 of file ArithmeticalDSSFactory.h.
Member Typedef Documentation
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> typedef TCoordinate DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency >::Coordinate
Definition at line 78 of file ArithmeticalDSSFactory.h.
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> typedef ArithmeticalDSS<TCoordinate,TInteger,adjacency> DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency >::DSS
Definition at line 85 of file ArithmeticalDSSFactory.h.
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> typedef TInteger DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency >::Integer
Definition at line 79 of file ArithmeticalDSSFactory.h.
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> typedef DGtal::PointVector<2, Coordinate> DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency >::Point
Definition at line 81 of file ArithmeticalDSSFactory.h.
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> typedef std::pair<Vector,Vector> DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency >::Steps
Definition at line 83 of file ArithmeticalDSSFactory.h.
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> typedef Point DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency >::Vector
Definition at line 82 of file ArithmeticalDSSFactory.h.
Member Function Documentation
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency >::Vector DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency >::bezoutVector (const Coordinate & aA, const Coordinate & aB, const Coordinate & aR) inline static private
Returns the bezout vector (u,v) of a given direction vector of slope aA / aB such that u and aB (resp. v and aA) have the same sign.
Returns
bezout vector
Parameters
aA y-component of the direction vector
aB x-component of the dirention vector
aR a remainder equal to either 1 or -1
See Also
createPattern
NB: this method uses the extended Euclid's algorithm and runs in logarithmic time.
Definition at line 122 of file ArithmeticalDSSFactory.ih.
References DGtal::IntegerComputer< TInteger >::extendedEuclid().
 {
   ASSERT( (aR == 1)||(aR == -1) );
   //compute one Bezout vector
   IntegerComputer<Coordinate> computer;
   Vector v = computer.extendedEuclid(aA, -aB, aR);
   ASSERT( (aA*v[0]-aB*v[1]) == aR );
   //compute the one whose component
   //have a sign equal to the direction
   //vector components
   if ( (aB >= 0)&&(v[0] < 0) )
     v += Vector(aB,aA);
   else if ( (aB < 0)&&(v[0] >= 0) )
     v += Vector(aB,aA);
   else if ( ( aA >= 0 )&&(v[1] < 0) )
     v += Vector(aB,aA);
   else if ( ( aA < 0 )&&(v[1] >= 0) )
     v += Vector(aB,aA);
   ASSERT( (aA*v[0]-aB*v[1]) == aR );
   ASSERT( (( aA >= 0 )&&(v[1] >= 0))||(( aA < 0 )&&(v[1] < 0)) );
   ASSERT( (( aB >= 0 )&&(v[0] >= 0))||(( aB < 0 )&&(v[0] < 0)) );
   return v;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency > DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency >::createPattern (const Point & aF, const Point & aL) inline static
Method that creates a DSS that is a pattern or a repetition of a pattern from two input digital points, viewed as upper leaning points.
Parameters
aF first input digital point
aL second input digital point
NB: logarithmic-time in the greatest component of the vector starting from aF and pointing to aL
Definition at line 46 of file ArithmeticalDSSFactory.ih.
References DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::a(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::b(), DGtal::IntegerComputer< TInteger >::gcd(), DGtal::gcd(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::remainder(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::shift(), and DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::steps().
 {
   //specific case: a and b are both null
   if (aF == aL)
     {
       return DGtal::ArithmeticalDSS<TCoordinate,TInteger,adjacency>( aF );
     }
   //otherwise
   else
     {
       //upper leaning points
       Point Uf, Ul, Lf, Ll;
       Uf = aF;
       Ul = aL;
       //direction vector
       Vector u2 = aL - aF;
       IntegerComputer<Coordinate> computer;
       Coordinate gcd = computer.gcd(u2[0], u2[1]);
       //irreductible direction vector
       Vector u = Vector(u2[0]/gcd, u2[1]/gcd);
       //intercept
       Integer mu = DGtal::ArithmeticalDSL<TCoordinate,TInteger,adjacency>::remainder(u[1], u[0], Uf);
       //DSL
       DGtal::ArithmeticalDSL<TCoordinate,TInteger,adjacency> dsl(u[1], u[0], mu);
       //lower leaning points
       if ( dsl.steps().second == Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ZERO) )
         { //specific case: there is only one step,
           //ie. either a == 0, or b == 0, or
           //(a == 1 and b == 1) in the naive case
           Lf = Uf;
           Ll = Ul;
           return DGtal::ArithmeticalDSS<TCoordinate,TInteger,adjacency>(dsl.a(), dsl.b(),
                                                    mu, mu, aF, aL,
                                                    Uf, Ul, Lf, Ll,
                                                    dsl.steps(), dsl.shift());
         }
       else
         { //otherwise
           Coordinate signedUnity = -1;
           Vector v = bezoutVector(u[1], u[0], signedUnity);
           Lf = Uf + v - dsl.shift()*signedUnity;
           Ll = Uf + u*(gcd-1) + v - dsl.shift()*signedUnity;
           Integer mu2 = DGtal::ArithmeticalDSL<TCoordinate,TInteger,adjacency>::remainder(u[1], u[0], Lf);
           return DGtal::ArithmeticalDSS<TCoordinate,TInteger,adjacency>(dsl.a(), dsl.b(),
                                                    mu, mu2, aF, aL,
                                                    Uf, Ul, Lf, Ll,
                                                    dsl.steps(), dsl.shift());
         }
     }
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency > DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency >::createReversedPattern (const Point & aF, const Point & aL) inline static
Method that creates a DSS that is a reversed pattern or a repetition of a reversed pattern from two input digital points, viewed as lower leaning points. Creates the pattern from aL to aF and negates the result.
See Also
createPattern
Parameters
aF first input digital point
aL second input digital point
NB: logarithmic-time in the greatest component of the vector starting from aF and pointing to aL
Definition at line 111 of file ArithmeticalDSSFactory.ih.
References DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::negate().
 {
   DGtal::ArithmeticalDSS<TCoordinate,TInteger,adjacency> pattern = createPattern(aL, aF);
   return pattern.negate();
 }
The documentation for this class was generated from the following files:
ArithmeticalDSSFactory.h
ArithmeticalDSSFactory.ih