DGtal: DGtal::DSLSubsegment< TInteger, TNumber > Class Template Reference
DGtal::DSLSubsegment< TInteger, TNumber > Class Template Reference
#include <DSLSubsegment.h>
Data Structures
class RayC
Public Types
typedef TNumber Number
typedef TInteger Integer
typedef long double LongDoubleType
typedef DGtal::PointVector
< 2, Integer > Ray
typedef DGtal::PointVector
< 2, Integer > Point
typedef DGtal::PointVector
< 2, Number > PointF
typedef DGtal::PointVector
< 2, Integer > Vector
typedef DGtal::PointVector
< 2, Number > VectorF
Public Member Functions
~DSLSubsegment ()
void selfDisplay (std::ostream &out) const
bool isValid () const
BOOST_CONCEPT_ASSERT ((CEuclideanRing< Number >))
BOOST_CONCEPT_ASSERT ((CInteger< Integer >))
DSLSubsegment (Number a, Number b, Number mu, Point &A, Point &B, std::string type)
DSLSubsegment (Number alpha, Number beta, Point &A, Point &B, Number precision=1e-10)
Integer computeMinRemainder (Number a, Number b, Number mu, Point A, Point B)
Integer computeMaxRemainder (Number a, Number b, Number mu, Point A, Point B)
Integer getA () const
Integer getB () const
Integer getMu () const
Protected Types
enum Position { ABOVE, BELOW, ONTO }
typedef enum
DGtal::DSLSubsegment::Position Position
Protected Member Functions
void DSLSubsegmentFareyFan (Number a, Number b, Number mu, Point &A, Point &B)
void DSLSubsegmentLocalCH (Number a, Number b, Number mu, Point &A, Point &B)
DSLSubsegment ()
Integer intersectionVertical (Point &P, Vector &v, Integer n)
Integer intersection (Point &P, Vector &v, Vector &aL, Integer r)
Integer intersection (Point &P, Vector &v, Number s)
void update (Vector &u, Point &A, Vector &l, Integer r, Vector *v)
void update (Vector &u, Point &A, Number s, Vector *v)
void lowerConvexHull (Vector &l, Integer mu, Point &A, Point &B, Point *prevInfL, Point *infL, Point *infR, Point *prevInfR)
void convexHullApprox (Vector &l, Integer r, Integer n, Point *inf, Point *sup)
void convexHullApprox (Number s, Integer n, Point *inf, Point *sup)
void convexHullApproxTwoPoints (Vector &l, Integer r, Integer n, Point *inf, Point *sup, Point *prevInf, Point *prevSup, bool inv)
void convexHullHarPeled (Vector &l, Integer n, Point *inf, Point *sup)
Point nextTermInFareySeriesEuclid (Integer fp, Integer fq, Integer n)
RayC rayOfHighestSlope (Integer p, Integer q, Integer r, Integer smallestSlope, Integer n)
Integer slope (Integer p, Integer q, Integer r, Number a, Number b, Number mu)
Integer slope (Integer p, Integer q, Integer r, Number alpha, Number beta)
Position positionWrtRay (RayC &r, Number a, Number b, Number mu)
Position positionWrtRay (RayC &r, Number alpha, Number beta)
RayC smartRayOfSmallestSlope (Integer fp, Integer fq, Integer gp, Integer gq, Integer r)
Integer smartFirstDichotomy (Integer fp, Integer fq, Integer gp, Integer gq, Number a, Number b, Number mu, Integer n, bool *flagRayFound)
Integer smartFirstDichotomy (Integer fp, Integer fq, Integer gp, Integer gq, Number alpha, Number beta, Integer n, bool *flagRayFound)
RayC localizeRay (Integer fp, Integer fq, Integer gp, Integer gq, Integer r, Number a, Number b, Number mu, Integer n)
RayC localizeRay (Integer fp, Integer fq, Integer gp, Integer gq, Integer r, Number alpha, Number beta, Integer n)
RayC raySup (Integer fp, Integer fq, RayC r)
void findSolutionWithoutFractions (Integer fp, Integer fq, Integer gp, Integer gq, RayC r, Integer n, Integer *resAlphaP, Integer *resAlphaQ, Integer *resBetaP, bool found)
void shortFindSolution (Integer fp, Integer fq, Integer gp, Integer gq, RayC r, Integer n, Integer *resAlphaP, Integer *resAlphaQ, Integer *resBetaP)
Protected Attributes
Integer myA
Integer myB
Integer myMu
Number myPrecision
Detailed Description
template<typename TInteger, typename TNumber>
class DGtal::DSLSubsegment< TInteger, TNumber >
Aim: Given a Digital Straight line and two endpoints A and B on this line, compute the minimal characteristics of the digital subsegment [AB] in logarithmic time. Two algorithms are implemented: one is based on the local computation of lower and upper convex hulls, the other is based on a dual transformation and uses the Farey fan. Implementation requires that the DSL lies in the first octant (0 <= a <= b).
Description of class 'DSLSubsegment'
Template Parameters
TInteger is the type of integer used
TNumber is the type of number used to represent the input DSL characteristics.
Definition at line 77 of file DSLSubsegment.h.
Member Typedef Documentation
template<typename TInteger, typename TNumber> typedef TInteger DGtal::DSLSubsegment< TInteger, TNumber >::Integer
Definition at line 106 of file DSLSubsegment.h.
template<typename TInteger, typename TNumber> typedef long double DGtal::DSLSubsegment< TInteger, TNumber >::LongDoubleType
Definition at line 107 of file DSLSubsegment.h.
template<typename TInteger, typename TNumber> typedef TNumber DGtal::DSLSubsegment< TInteger, TNumber >::Number
Number types
Definition at line 105 of file DSLSubsegment.h.
template<typename TInteger, typename TNumber> typedef DGtal::PointVector<2,Integer> DGtal::DSLSubsegment< TInteger, TNumber >::Point
2D integer point
Definition at line 119 of file DSLSubsegment.h.
template<typename TInteger, typename TNumber> typedef DGtal::PointVector<2,Number> DGtal::DSLSubsegment< TInteger, TNumber >::PointF
2D real point
Definition at line 124 of file DSLSubsegment.h.
template<typename TInteger, typename TNumber> typedef enum DGtal::DSLSubsegment::Position DGtal::DSLSubsegment< TInteger, TNumber >::Position protected
Position of a point wrt a ray
template<typename TInteger, typename TNumber> typedef DGtal::PointVector<2,Integer> DGtal::DSLSubsegment< TInteger, TNumber >::Ray
A ray is defined as a 2D integer vector (x,y) such that Ray(x,y) is the straight line beta = -x alpha +y in the (alpha,beta)-space.
Definition at line 114 of file DSLSubsegment.h.
template<typename TInteger, typename TNumber> typedef DGtal::PointVector<2,Integer> DGtal::DSLSubsegment< TInteger, TNumber >::Vector
2D integer vector
Definition at line 129 of file DSLSubsegment.h.
template<typename TInteger, typename TNumber> typedef DGtal::PointVector<2,Number> DGtal::DSLSubsegment< TInteger, TNumber >::VectorF
2D real vector
Definition at line 134 of file DSLSubsegment.h.
Member Enumeration Documentation
template<typename TInteger, typename TNumber> enum DGtal::DSLSubsegment::Position protected
Position of a point wrt a ray
Enumerator
ABOVE
BELOW
ONTO
Definition at line 281 of file DSLSubsegment.h.
       {
         ABOVE,
         BELOW,
         ONTO
       } Position;
Constructor & Destructor Documentation
template<typename TInteger, typename TNumber> DGtal::DSLSubsegment< TInteger, TNumber >::~DSLSubsegment () inline
Destructor.
Definition at line 85 of file DSLSubsegment.h.
 {};
template<typename TInteger , typename TNumber > DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegment (Number a, Number b, Number mu, Point & A, Point & B, std::string type) inline
Constructor Given the parameters of a DSL 0 <= ax -by + mu < b, and two points A and B of this DSL, compute the parameters of the DSS [AB]. The algorithm used depends on the value of the boolean (Farey fan if true, local convex hull otherwise).
Parameters
[in] a DSL a parameter
[in] b DSL b parameter
[in] mu DSL mu parameter
[in] A left-most point
[in] B right-most point
[in] type a type
Definition at line 1172 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegmentFareyFan(), and DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegmentLocalCH().
 {
   try
     {
       if(type.compare("farey")==0)
         this->DSLSubsegmentFareyFan(a,b,mu,A,B);
       else
         if(type.compare("localCH")==0)
           this->DSLSubsegmentLocalCH(a,b,mu,A,B);
         else
           throw std::invalid_argument("ERROR: Unknow string to specify the algorithm. \"farey\" is used hereafter.");
     }
   catch(std::invalid_argument & e)
     {
       std::cerr << e.what() << std::endl;
       this->DSLSubsegmentFareyFan(a,b,mu,A,B);
     }
 }
template<typename TInteger , typename TNumber > DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegment (Number alpha, Number beta, Point & A, Point & B, Number precision = 1e-10) inline
Constructor Given a straight line of equation y = alpha x + beta, and two points A and B of the OBQ digitization of this line, compute the parameters of the DSS [AB]. The algorithm implemented uses the Farey fan. Requires a precision parameter for floating-point geometrical predicates
Parameters
[in] alpha slope of the line
[in] beta intercept of the line
[in] A left-most point
[in] B right-most point
[in] precision precision
Definition at line 1456 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::convexHullApprox(), DGtal::DSLSubsegment< TInteger, TNumber >::findSolutionWithoutFractions(), DGtal::DSLSubsegment< TInteger, TNumber >::localizeRay(), DGtal::DSLSubsegment< TInteger, TNumber >::myA, DGtal::DSLSubsegment< TInteger, TNumber >::myB, DGtal::DSLSubsegment< TInteger, TNumber >::myMu, DGtal::DSLSubsegment< TInteger, TNumber >::myPrecision, DGtal::DSLSubsegment< TInteger, TNumber >::nextTermInFareySeriesEuclid(), DGtal::DSLSubsegment< TInteger, TNumber >::smartFirstDichotomy(), and DGtal::DSLSubsegment< TInteger, TNumber >::smartRayOfSmallestSlope().
 {
   Integer n = B[0] - A[0];
   myPrecision = precision;
   // A becomes the origin
   beta +=alpha*A[0] - A[1];
   Point inf, sup;
   Integer fp,fq,gp,gq;
 #ifdef DEBUG
   std::cout << "\n \nDSLSubsegment with floats, n=" << n << " precision = " << myPrecision << std::endl;
   std::cout << std::setprecision(15) << "alpha = " << alpha << " beta = " << beta << std::endl;
 #endif
   convexHullApprox(alpha,n,&inf,&sup);
   fp = inf[1];
   fq = inf[0];
   gp = sup[1];
   gq = sup[0];
 #ifdef DEBUG
   std::cout << "f and g = " << fp << " " << fq << " " << gp << " " << gq << std::endl;
 #endif
   if(fp == gp && fq == gq)
     {
       Point next = nextTermInFareySeriesEuclid(fp,fq,n);
       gp = next[1];
       gq = next[0];
     }
   bool found;
   // Find the height in the ladder
   // Returns the height h such that:
   // - param is in between the rays passing through the point (inf =
   // p/q, h/q)
   // ==> found is set to false
   // - or param is above the ray of smallest slope passing through
   // (inf = p/q, h/q) but below all the rays passing through (p/q,
   // h+1/q)  ==> found is set to true
   Integer h = smartFirstDichotomy(fp,fq,gp,gq,alpha,beta,n,&found);
   RayC r;
   if(found)
     r = smartRayOfSmallestSlope(fp,fq,gp,gq,h);
   else
     r = localizeRay(fp,fq,gp,gq,h,alpha,beta,n);
   Integer resAlphaP=0, resAlphaQ=0, resBetaP=0;
   findSolutionWithoutFractions(fp,fq, gp, gq, r, n, &resAlphaP, &resAlphaQ, &resBetaP, found);
   myA = resAlphaP;
   myB = resAlphaQ;
   myMu = resBetaP - myA*A[0] + myB*A[1];
 }
template<typename TInteger, typename TNumber> DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegment () protected
Constructor. Forbidden by default (protected to avoid g++ warnings).
Member Function Documentation
template<typename TInteger, typename TNumber> DGtal::DSLSubsegment< TInteger, TNumber >::BOOST_CONCEPT_ASSERT ((CEuclideanRing< Number >))
Check that Number type verifies the Euclidean Rign concept and Integer type verifies the Integer concept
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::positionWrtRay(), DGtal::DSLSubsegment< TInteger, TNumber >::slope(), and DGtal::DSLSubsegment< TInteger, TNumber >::smartFirstDichotomy().
template<typename TInteger, typename TNumber> DGtal::DSLSubsegment< TInteger, TNumber >::BOOST_CONCEPT_ASSERT ((CInteger< Integer >))
template<typename TInteger, typename TNumber> Integer DGtal::DSLSubsegment< TInteger, TNumber >::computeMaxRemainder (Number a, Number b, Number mu, Point A, Point B)
template<typename TInteger, typename TNumber> Integer DGtal::DSLSubsegment< TInteger, TNumber >::computeMinRemainder (Number a, Number b, Number mu, Point A, Point B)
template<typename TInteger , typename TNumber > void DGtal::DSLSubsegment< TInteger, TNumber >::convexHullApprox (Vector & l, Integer r, Integer n, Point * inf, Point * sup) inline protected
Compute the left part of the upper and lower convex hulls of the line of directional vector l and intercept r, between x=0 and x=n. Returns the upper and lower closest points. Implementation of Charrier and Buzer algorithm [CharrierBuzer2009]}
Parameters
l directional vector of the line
r intercept of the line
n maximal value of x-coordinate
[out] inf closest point below the line
[out] sup closest point above the line
Definition at line 234 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::intersection(), DGtal::DSLSubsegment< TInteger, TNumber >::intersectionVertical(), DGtal::IntegerComputer< TInteger >::min(), and DGtal::DSLSubsegment< TInteger, TNumber >::update().
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegment(), and DGtal::DSLSubsegment< TInteger, TNumber >::shortFindSolution().
 {
   //std::cout << "In Convex hull approx" << std::endl;
   //std::cout << l << " " << n << std::endl;
   if(n >= l[0])
     {
       *inf = l;
       *sup = l;
     }
   else
     if(l[1] == 0)
       {
         *inf = l;
         *sup = Point(n,1);
       }
     else
       {
         Point A = Point(0,1);
         Point B = Point(1,0);
         Vector u = Vector(1,-1);
         Vector v = Vector(1,0);
         Vector normal = Vector(-l[1],l[0]);
         Integer alpha;
         bool ok = true;
         bool found = false;
         bool first = true;
         DGtal::IntegerComputer<TInteger> ic;
         while(ok)
           {
             if(v[0]*normal[0]+v[1]*normal[1] ==0) // should never happen
               {
                 ok = false;
                 found = true;
               }
             else
               if(v[0]*normal[0]+v[1]*normal[1] < 0)
                 {
                   alpha = ic.min(intersection(A,v,l,r), intersectionVertical(A,v,n));
                   if(alpha >= 1 || first)
                     {
                       Vector vv  = v;
                       vv *= alpha;
                       A += vv;
                       u = B - A;
                       update(u,A,l,r,&v);
                     }
                   else
                     ok = false;
                   first = false;
                 }
               else
                 if(v[0]*normal[0]+v[1]*normal[1] > 0)
                   {
                     alpha = ic.min(intersection(B,v,l,r),intersectionVertical(B,v,n));
                     if(alpha >= 1)
                       {
                         Vector vv = v;
                         vv *= alpha;
                         B += vv;
                         u = B - A;
                         update(u,A,l,r,&v);
                       }
                     else
                       ok = false;
                   }
           }
         if(found)
           {
             *sup = v;
             *inf = v;
           }
         else
           {
             *sup = A;
             *inf = B;
             assert(A[0] != B[0] || A[1] != B[1]);
           }
       }
 }
template<typename TInteger , typename TNumber > void DGtal::DSLSubsegment< TInteger, TNumber >::convexHullApprox (Number s, Integer n, Point * inf, Point * sup) inline protected
Compute the left part of the upper and lower convex hulls of the line of slope s, between x=0 and x=n. Returns the upper and lower closest points.
Parameters
s slope of the line (interpect is equal to zero here)
n maximal value of x-coordinate
[out] inf closest point below the line
[out] sup closest point above the line
Definition at line 498 of file DSLSubsegment.ih.
References DGtal::IntegerComputer< TInteger >::gcd(), DGtal::DSLSubsegment< TInteger, TNumber >::intersection(), DGtal::DSLSubsegment< TInteger, TNumber >::intersectionVertical(), DGtal::IntegerComputer< TInteger >::min(), DGtal::DSLSubsegment< TInteger, TNumber >::myPrecision, and DGtal::DSLSubsegment< TInteger, TNumber >::update().
 {
   // slope to be approximated = (1,s)
   //std::cout << "In Convex hull approx" << std::endl;
   Point A = Point(0,1);
   Point B = Point(1,0);
   Vector u = Vector(1,-1);
   Vector v = Vector(1,0);
   VectorF normal = VectorF(-s,1);
   Integer alpha;
   bool ok = true;
   bool found = false;
   DGtal::IntegerComputer<Integer> ic;
   while(ok)
     {
       if(fabs(v[0]*normal[0]+v[1]*normal[1]) <= myPrecision)
         {
           ok = false;
           found = true;
         }
       else
         if(v[0]*normal[0]+v[1]*normal[1] < 0)
           {
             alpha = ic.min(intersection(A,v,s), intersectionVertical(A,v,n));
             if(alpha >= 1)
               {
                 Vector vv  = v;
                 vv *= alpha;
                 A += vv;
                 // test if A is on the slope
                 if(fabs(A[0]*normal[0]+A[1]*normal[1]) <= myPrecision)
                   {
                     ok = false;
                     v = A;
                     found = true;
                   }
                 else
                   {
                     u = B - A;
                     update(u,A,s,&v);
                   }
               }
             else
               ok = false;
           }
       else
         if(v[0]*normal[0]+v[1]*normal[1] > 0)
           {
             alpha = ic.min(intersection(B,v,s),intersectionVertical(B,v,n));
             if(alpha >= 1)
               {
                 Vector vv = v;
                 vv *= alpha;
                 B += vv;
                 // test if B is on the slope
                 if(fabs(B[0]*normal[0]+B[1]*normal[1]) <= myPrecision)
                   {
                     ok = false;
                     v = B;
                     found = true;
                   }
                 else
                   {
                     u = B - A;
                     update(u,A,s,&v);
                   }
               }
             else
               ok = false;
           }
     }
   if(found)
     {
       Integer g = ic.gcd(v[0],v[1]);
       v[0] = v[0]/g;
       v[1] = v[1]/g;
       *sup = v;
       *inf = v;
     }
   else
     {
       *sup = A;
       *inf = B;
       assert(A[0] != B[0] || A[1] != B[1]);
     }
 }
template<typename TInteger , typename TNumber > void DGtal::DSLSubsegment< TInteger, TNumber >::convexHullApproxTwoPoints (Vector & l, Integer r, Integer n, Point * inf, Point * sup, Point * prevInf, Point * prevSup, bool inv) inline protected
Compute the left part of the upper and lower convex hulls of the line of slope s, between x=0 and x=n. Returns the last two points computed. Implementation of Charrier and Buzer algorithm [CharrierBuzer2009]}
Parameters
l directional vector of the line
r intercept of the line
n maximal value of x-coordinate
[out] inf closest point below the line
[out] sup closest point above the line
[out] prevInf second-closest point below the line
[out] prevSup second-closest point above the line
inv boolean used to know if the CH is computed from left-to-right (inv=false) or right-to-left (inv = true)
Definition at line 328 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::intersection(), DGtal::DSLSubsegment< TInteger, TNumber >::intersectionVertical(), DGtal::IntegerComputer< TInteger >::min(), and DGtal::DSLSubsegment< TInteger, TNumber >::update().
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::lowerConvexHull().
 {
   Point A,B,Aold,Bold;
   Vector u,v;
   if(inv && r==0)
     {
       A = Point(0,0);
       B = Point(1,0);
       u = Vector(1,0);
       v = Vector(0,1);
       Aold = Point(0,0);
       Bold = B;
     }
   else
     {
       A = Point(0,1);
       B = Point(0,0);
       u = Vector(0,-1);
       v = Vector(1,0);
       Aold = A;
       Bold = B;
     }
   Vector vv;
   Vector normal = Vector(-l[1],l[0]);
   Integer alpha;
   bool ok = true;
   bool first = true;
   DGtal::IntegerComputer<Integer> ic;
   while(ok)
     {
       if(v[0]*normal[0]+v[1]*normal[1]< 0)
         {
           alpha = ic.min(intersection(A,v,l,r), intersectionVertical(A,v,n));
           if(alpha >= 1 || first)
             {
               Aold = A;
               vv  = v;
               vv *= alpha;
               A += vv;
               //test if A is on the slope
               if(A[0]*l[1]-A[1]*l[0]+r ==0)
                 {
                   ok = false;
                 }
               else
                 {
                   u = B - A;
                   update(u,A,l,r,&v);
                 }
             }
           else
             ok = false;
           first = false;
         }
       else
         if(v[0]*normal[0]+v[1]*normal[1]> 0)
               {
                 alpha = ic.min(intersection(B,v,l,r),intersectionVertical(B,v,n));
                 if(alpha >= 1)
                   {
                     Bold = B;
                     vv = v;
                     vv *= alpha;
                     B += vv;
                     // test if B is on the slope
                     if(B[0]*l[1]-B[1]*l[0] +r==0 )
                       {
                         ok = false;
                       }
                     else
                       {
                         u = B - A;
                         update(u,A,l,r,&v);
                       }
                   }
                 else
                   ok = false;
               }
             else
               ok = false;
         }
       if(!inv)
         {
           // if A is on the line, A is a vertex for both the lower and the upper convex hulls
           if(A[0]*l[1]-A[1]*l[0]+r ==0)
             {
               *sup = A;
               *inf = A;
               *prevSup = Aold;
               *prevInf = B;
             }
           else
             if(B[0]*l[1]-B[1]*l[0]+r ==0)
               {
                 *inf = B;
                 *prevInf = Bold;
                 if(B[0]>A[0])
                   {
                     *sup = B;
                     *prevSup = A;
                   }
                 else
                   {
                     *sup = A;
                     *prevSup = Aold;
                   }
               }
             else
               {
                 *sup = A;
                 *inf = B;
                 *prevInf = Bold;
                 *prevSup = Aold;
               }
         }
       else
         {
           if(B[0]*l[1]-B[1]*l[0]+r ==0)
             {
               *sup = B;
               *inf = B;
               *prevSup = A;
               *prevInf = Bold;
             }
           else
             if(A[0]*l[1]-A[1]*l[0]+r ==0)
               {
                 *sup = A;
                 *prevSup = Aold;
                 if(A[0]>B[0])
                   {
                     *inf = A;
                     *prevInf = B;
                   }
                 else
                   {
                     *inf = B;
                     *prevInf = Bold;
                   }
               }
             else
               {
                 *sup = A;
                 *inf = B;
                 *prevInf = Bold;
                 *prevSup = Aold;
               }
         }
 }
template<typename TInteger , typename TNumber > void DGtal::DSLSubsegment< TInteger, TNumber >::convexHullHarPeled (Vector & l, Integer n, Point * inf, Point * sup) inline protected
Compute the left part of the upper and lower convex hulls of the line of directional vector l, between x=0 and x=n. Returns the last two points computed. Implementation of Har-Peled algorithm (Computational Geometry: Theory and Applications, 1998)
Parameters
l directional vector of the line (intercept is zero)
n maximal value of x-coordinate
[out] inf closest point below the line
[out] sup closest point above the line
Definition at line 176 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::intersection(), DGtal::DSLSubsegment< TInteger, TNumber >::intersectionVertical(), and DGtal::IntegerComputer< TInteger >::min().
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegmentFareyFan(), and DGtal::DSLSubsegment< TInteger, TNumber >::findSolutionWithoutFractions().
 {
    if(n >= l[0])
      {
        *inf = l;
        *sup = l;
      }
    if(l[1] == 0)
      {
        *inf = l;
        *sup = Point(n,1);
      }
    else
      {
        Point A = Point(0,1);
        Point B = Point(1,0);
        int i=0;
        bool ok = true;
        Integer alpha1, alpha2, alpha;
        DGtal::IntegerComputer<Integer> ic;
        while(ok)
          {
            if(i%2==0)
              {
                alpha1 = intersection(A,B,l,0);
                alpha2 = intersectionVertical(A,B,n);
                alpha = ic.min(alpha1,alpha2);
                A = A + alpha*B;
                if(A[0]*l[1]-A[1]*l[0]==0 || alpha == alpha2)
                  ok = false;
              }
            if(i%2==1)
              {
                alpha1 = intersection(B,A,l,0);
                alpha2 = intersectionVertical(B,A,n);
                alpha = ic.min(alpha1,alpha2);
                B = B + alpha*A;
                if(B[0]*l[1]-B[1]*l[0]==0 || alpha == alpha2)
                  ok = false;
              }
            i++;
          }
        *inf = B;
        *sup = A;
      }
 }
template<typename TInteger , typename TNumber > void DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegmentFareyFan (Number a, Number b, Number mu, Point & A, Point & B) inline protected
Function called by the constructor when the input parameters are integers and the Farey Fan algorithm is used.
Parameters
a DSL a parameter
b DSL b parameter
mu DSL mu parameter
A left-most point
B right-most point
Definition at line 1195 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::convexHullHarPeled(), DGtal::DSLSubsegment< TInteger, TNumber >::findSolutionWithoutFractions(), DGtal::DSLSubsegment< TInteger, TNumber >::localizeRay(), DGtal::DSLSubsegment< TInteger, TNumber >::myA, DGtal::DSLSubsegment< TInteger, TNumber >::myB, DGtal::DSLSubsegment< TInteger, TNumber >::myMu, DGtal::DSLSubsegment< TInteger, TNumber >::nextTermInFareySeriesEuclid(), DGtal::DSLSubsegment< TInteger, TNumber >::smartFirstDichotomy(), and DGtal::DSLSubsegment< TInteger, TNumber >::smartRayOfSmallestSlope().
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegment().
 {
   Integer n = B[0] - A[0];
   if(n >= 2*b)
     {
       myA = a;
       myB = b;
       myMu = mu;
       //std::cout << "DSS parameters are DSL parameters." << std::endl;
     }
   else
     {
       // A becomes the origin // mu must be between 0 and b
       mu += a*A[0] - A[1]*b;
       Point inf, sup;
       Point inf2, sup2;
       Integer fp,fq,gp,gq;
       if(b>n)
         {
           Vector v(b,a);
           convexHullHarPeled(v,n,&inf,&sup);
           fp = inf[1];
           fq = inf[0];
           gp = sup[1];
           gq = sup[0];
         }
       else
         {
           Point next = nextTermInFareySeriesEuclid(a,b,n);
           fp = a;
           fq = b;
           gp = next[1];
           gq = next[0];
         }
 // #ifdef DEBUG
 //       std::cout << "fractions = " << fp << " " << fq << " " << gp << " " << gq << std::endl;
 // #endif
       bool found;
       // Find the height in the ladder
       // Returns the height h such that:
       // - param is in between the rays passing through the point (inf =
       // p/q, h/q)
       // ==> found is set to false
       // - or param is above the ray of smallest slope passing through
       // (inf = p/q, h/q) but below all the rays passing through (p/q,
       // h+1/q)  ==> found is set to true
       Integer h = smartFirstDichotomy(fp,fq,gp,gq,a,b,mu,n,&found);
       RayC r;
       if(found)
         {
           r = smartRayOfSmallestSlope(fp,fq,gp,gq,h);
         }
       else
         {
           r = localizeRay(fp,fq,gp,gq,h,a,b,mu,n);
         }
       Integer resAlphaP=0, resAlphaQ=0, resBetaP=0;
       findSolutionWithoutFractions(fp,fq, gp, gq, r, n, &resAlphaP, &resAlphaQ, &resBetaP, found);
       //shortFindSolution(fp,fq, gp, gq, r, n, &resAlphaP, &resAlphaQ, &resBetaP);
       myA = resAlphaP;
       myB = resAlphaQ;
       myMu = resBetaP - myA*A[0] + myB*A[1];
     }
 }
template<typename TInteger , typename TNumber > void DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegmentLocalCH (Number a, Number b, Number mu, Point & A, Point & B) inline protected
Function called by the constructor when the input parameters are integers and the local convex hull algorithm is used.
Parameters
a DSL a parameter
b DSL b parameter
mu DSL mu parameter
A left-most point
B right-most point
Definition at line 1362 of file DSLSubsegment.ih.
References DGtal::IntegerComputer< TInteger >::gcd(), DGtal::DSLSubsegment< TInteger, TNumber >::lowerConvexHull(), DGtal::IntegerComputer< TInteger >::max(), DGtal::DSLSubsegment< TInteger, TNumber >::myA, DGtal::DSLSubsegment< TInteger, TNumber >::myB, and DGtal::DSLSubsegment< TInteger, TNumber >::myMu.
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegment().
 {
   Integer rB = a*B[0]-b*B[1] + mu;
   Vector l(b,a);
   Point infL,supL,infR,supR,prevInfL,prevSupL,prevInfR,prevSupR;
   lowerConvexHull(l,mu,A,B,&prevInfL,&infL,&infR,&prevInfR);
   Point pz(0,0);
   Point BA=B-A;
   lowerConvexHull(l,l[0]-rB-1,pz,BA,&prevSupR, &supR, &supL, &prevSupL);
   prevSupR = B+Point(0,1)-prevSupR;
   supR = B+Point(0,1)-supR;
   prevSupL = B+Point(0,1)-prevSupL;
   supL = B+Point(0,1)-supL;
   DGtal::IntegerComputer<Integer> ic;
   myA=0, myB=0, myMu=0;
   // we are left with four possible lines given by the couples (prevInfL, infL=infR) (infL = infR,prevInfR)
   // (prevSupL, supL = supR) (supL = supR, prevSupR)
   // the solution is given by the slope with bigger b
         Point inf[4];
         inf[0] = prevInfL;
         inf[1] = infL;
         inf[2] = infR;
         inf[3] = prevInfR;
         Point sup[4];
         sup[0] = prevSupL;
         sup[1] = supL;
         sup[2] = supR;
         sup[3] = prevSupR;
         Integer atmp, btmp;
         for(int i=0;i<3;i++)
           {
             btmp = inf[i+1][0] - inf[i][0];
             atmp = inf[i+1][1] - inf[i][1];
             Integer g;
             if(atmp==0 || btmp==0)
               g = ic.max((Integer) 1,ic.max(atmp,btmp));
             else
               g = ic.gcd(btmp,atmp);
             btmp = btmp/g;
             atmp = atmp/g;
             if(btmp > myB)
               {
                 myB =btmp;
                 myA =atmp;
               }
           }
         for(int i=0;i<3;i++)
           {
             btmp = sup[i+1][0] - sup[i][0];
             atmp = sup[i+1][1] - sup[i][1];
             Integer g;
             if(atmp==0 || btmp==0)
               g = ic.max((Integer) 1,ic.max(atmp,btmp));
             else
               g = ic.gcd(btmp,atmp);
             btmp = btmp/g;
             atmp = atmp/g;
             if(btmp > myB)
               {
                 myB =btmp;
                 myA =atmp;
               }
           }
         myMu = -myA*infL[0] + myB*infL[1];
 }
template<typename TInteger , typename TNumber > void DGtal::DSLSubsegment< TInteger, TNumber >::findSolutionWithoutFractions (Integer fp, Integer fq, Integer gp, Integer gq, RayC r, Integer n, Integer * resAlphaP, Integer * resAlphaQ, Integer * resBetaP, bool found) inline protected
The two fractions f and g together with the ray r define a segment PQ. PQ is part of the lower boundary of exactly one cell of the FareyFan. This cell represents a DSS. This function computes the vertex of the cell that represents the minimal characteristics of the DSS. Optimized version of the algorithm presented in the paper [sivignonDGCI2013]}. Complexity of nextTermInFareySeriesEuclid
Parameters
fp numerator of the smallest fraction of the ladder
fq denominator of the smallest fraction of the ladder
gp numerator of the greatest fraction of the ladder
gq denominator of the greatest fraction of the ladder
r a ray
n order of the Farey Fan
[out] resAlphaP numerator of the x-coordinate of the result
[out] resAlphaQ denominator of the x- and y- coordinates of the result
[out] resBetaP numerator of the y-coordinate of the result
[in] found used for optimization (true if r is the ray of smallest slope on point P, false otherwise). Its value comes from the smartFirstDichotomy function.
Definition at line 1043 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::convexHullHarPeled(), DGtal::IntegerComputer< TInteger >::gcd(), DGtal::IntegerComputer< TInteger >::max(), DGtal::DSLSubsegment< TInteger, TNumber >::nextTermInFareySeriesEuclid(), DGtal::DSLSubsegment< TInteger, TNumber >::raySup(), DGtal::DSLSubsegment< TInteger, TNumber >::smartRayOfSmallestSlope(), DGtal::DSLSubsegment< TInteger, TNumber >::RayC::x, and DGtal::DSLSubsegment< TInteger, TNumber >::RayC::y.
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegment(), and DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegmentFareyFan().
 {
   Point inf, sup;
   DGtal::IntegerComputer<Integer> ic;
   RayC rr;
   if(found == false)
     // r is not the highest ray on A
     {
       if(gq <= ic.max(r.x,n-r.x))
         { // B is a multiple point, r is the lowest ray on B
           // (otherwise, there would be an intersection in [AB]
           // between the lowest ray on B and the ray above r on A.
           // Thus B is the solution
           *resAlphaP = gp;
           *resAlphaQ = gq;
           *resBetaP = -gp*r.x + r.y*gq;
         }
       else
         { // compute the ray juste above r
           rr = raySup(fp,fq,r);
           // compute the fraction following f in the Farey Series
           // given by the slope of rr
           if(ic.max(rr.x,n-rr.x)>ic.max(r.x,n-r.x))
             {
               Point next = nextTermInFareySeriesEuclid(fp,fq,ic.max(rr.x,n-rr.x));
               *resAlphaP = next[1];
               *resAlphaQ = next[0];
               *resBetaP = (Integer) -(*resAlphaP)*r.x+(*resAlphaQ)*r.y;
             }
           else
             {
               Point next = nextTermInFareySeriesEuclid(fp,fq,ic.max(r.x,n-r.x));
               *resAlphaP = next[1];
               *resAlphaQ = next[0];
               *resBetaP = (Integer) -(*resAlphaP)*r.x+(*resAlphaQ)*r.y ;
             }
         }
     }
   else
     {
       if(fq <= ic.max(r.x,n-r.x))
         { // A is a multiple point
           // A is the solution
           *resAlphaP = fp;
           *resAlphaQ = fq;
           *resBetaP = -fp*r.x +fq*r.y;
         }
       else
         if(gq <= ic.max(r.x,n-r.x) && (r.x + gq) >n)
           { // B is a multiple point and r is the lowest ray
             // B is the solution
             *resAlphaP = gp;
             *resAlphaQ = gq;
             *resBetaP = -gp*r.x +gq*r.y;
           }
         else
           {
             // A is not a multiple point. Check if the vertex above A
             // is a multiple point
             Integer h = -fp*r.x + r.y*fq +1;
             rr = smartRayOfSmallestSlope(fp,fq,gp,gq,h);
             if(fq<=ic.max(rr.x,n-rr.x))
               {  //the vertex above A is a
                 // multiple point -> A is the solution
                 *resAlphaP = fp;
                 *resAlphaQ = fq;
                 *resBetaP = -fp*r.x +fq*r.y;
               }
             else
               {
                 Vector v(fq,fp);
                 convexHullHarPeled(v,ic.max(r.x,n-r.x),&inf,&sup);
                 // Let C be the point on r with abscissa equal to inf.
                 rr = raySup(inf[1],inf[0],r); // ray above r passing through C
                 if(rr.x == r.x) // r is the highest ray passing through C
                   { // C is the solution
                     *resAlphaP = inf[1];
                     *resAlphaQ = inf[0];
                     *resBetaP = -inf[1]*r.x + inf[0]*r.y;
                   }
                 else
                   {
                     if(ic.max(rr.x,n-rr.x)>ic.max(r.x,n-r.x))
                       {
                         // the solution is given by the fraction following inf
                         // in the Farey Series of order
                         // max(x-inf.q(),n-(x.inf.q())), on the ray rr
                         // we compute the mediant on inf and sup: if
                         // the denominator is lower or equal to the
                         // order given by the ray rr, then the
                         // mediant is the solution. Otherwise, sup is
                         // the solution.
                         Integer g = ic.gcd(inf[1] + sup[1],inf[0]+sup[0]);
                         if((inf[0]+sup[0])/g <= ic.max(rr.x,n-rr.x))
{
                             *resAlphaP = (inf[1]+sup[1])/g;
                             *resAlphaQ = (inf[0]+sup[0])/g;
                           }
                         else
{
                             *resAlphaP = sup[1];
                             *resAlphaQ = sup[0];
                           }
                         *resBetaP = -(*resAlphaP)*rr.x+(*resAlphaQ)*rr.y - 1;
                       }
                     else
                       {
                         *resAlphaP = sup[1];
                         *resAlphaQ = sup[0];
                         *resBetaP = -(*resAlphaP)*r.x+(*resAlphaQ)*r.y;
                       }
                   }
               }
           }
     }
 }
template<typename TInteger , typename TNumber > TInteger DGtal::DSLSubsegment< TInteger, TNumber >::getA () const inline
Returns
an Integer of value myA.
Definition at line 1537 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::myA.
{
   return myA;
 }
template<typename TInteger , typename TNumber > TInteger DGtal::DSLSubsegment< TInteger, TNumber >::getB () const inline
Returns
an Integer of value myB.
Definition at line 1545 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::myB.
{
   return myB;
 }
template<typename TInteger , typename TNumber > TInteger DGtal::DSLSubsegment< TInteger, TNumber >::getMu () const inline
Returns
an Integer of value myMu.
Definition at line 1554 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::myMu.
{
   return myMu;
 }
template<typename TInteger , typename TNumber > DGtal::DSLSubsegment< TInteger, TNumber >::Integer DGtal::DSLSubsegment< TInteger, TNumber >::intersection (Point & P, Vector & v, Vector & aL, Integer r) inline protected
Compute the intersection between the line of direction v passing through P and the line y = (aL[1]/aL[0])*x +r The intersection point is of the form P + *v and the function returns the value floor(alpha).
Parameters
P a point of the first line
v directional vector of the first line
aL slope of the second line is equal to aL[1]/aL[0]
r intercept of the second line
Returns
integer
Definition at line 91 of file DSLSubsegment.ih.
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::convexHullApprox(), DGtal::DSLSubsegment< TInteger, TNumber >::convexHullApproxTwoPoints(), DGtal::DSLSubsegment< TInteger, TNumber >::convexHullHarPeled(), and DGtal::DSLSubsegment< TInteger, TNumber >::update().
 {
   Number num = P[1]*aL[0]-aL[1]*P[0]-r;
   Number denom = aL[1]*v[0]-v[1]*aL[0];
   // using parametric definition of lines and solving for t -> not more precise than the other computation...
   Integer val = num/denom;
   // integer rounding is not equivalent to the floor operation when num/denom is negative
   if((num<0 ||denom <0) && !(num<0 && denom <0))
     val--;
   return val;
 }
template<typename TInteger , typename TNumber > DGtal::DSLSubsegment< TInteger, TNumber >::Integer DGtal::DSLSubsegment< TInteger, TNumber >::intersection (Point & P, Vector & v, Number s) inline protected
Compute the intersection between the line of direction v passing through P and the line y = s*x The intersection point is of the form P + *v and the function returns the value floor(alpha).
Parameters
P a point of the first line
v directional vector of the first line
s slope of the second line
Returns
integer
Definition at line 111 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::myPrecision.
 {
   // vector to be approximated = (1,s)
   if(v[0]==0)
     {
       Number val = (s*P[0] - P[1])/(v[1]*s);
       if(ceil(val)-val <= myPrecision) // val is very close and slightly under an integer -> round to the integer
         return (Integer) ceil(val);
       else
         return (Integer) floor(val);
     }
   else
     {
       Number num = -P[1]*v[0] - P[0]*(v[1] - s*v[0]) + v[1]*P[0];
       Number denom = v[0]*(v[1] - s*v[0]);
       Number val = num/denom;
       Number val3;
       PointF Q;
       Q[0] = P[0] + ceil(val)*v[0];
       Q[1] = P[1] + ceil(val)*v[1];
       val3 = (Number) Q[0]*s - (Number) Q[1];
       if(fabs(val3) <= myPrecision)
         return (Integer) ceil(val);
       else
         return (Integer) floor(val);
     }
 }
template<typename TInteger , typename TNumber > DGtal::DSLSubsegment< TInteger, TNumber >::Integer DGtal::DSLSubsegment< TInteger, TNumber >::intersectionVertical (Point & P, Vector & v, Integer n) inline protected
Compute the intersection between the line of direction v passing through P and the vertical line x = n. The intersection point is of the form P + *v and the function returns the value floor(alpha).
Parameters
P a point
v directional vector of the line
n maximal value for x-coordinate
Returns
integer
Definition at line 72 of file DSLSubsegment.ih.
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::convexHullApprox(), DGtal::DSLSubsegment< TInteger, TNumber >::convexHullApproxTwoPoints(), and DGtal::DSLSubsegment< TInteger, TNumber >::convexHullHarPeled().
 {
   if(v[0] == 0)
     return n;
   else
     {
       Integer val = (n-P[0])/v[0];
       if(((n-P[0])<0 || v[0] <0) && !((n-P[0])<0 && v[0] <0))
         val--;
       return val;
     }
 }
template<typename TInteger, typename TNumber> bool DGtal::DSLSubsegment< TInteger, TNumber >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
template<typename TInteger, typename TNumber> RayC DGtal::DSLSubsegment< TInteger, TNumber >::localizeRay (Integer fp, Integer fq, Integer gp, Integer gq, Integer r, Number a, Number b, Number mu, Integer n) protected
Compute the closest ray below the point (a/b,mu/b) passing through the point (fp/fq,r/fq) in the Farey fan of order n
Parameters
fp numerator of the smallest fraction of the ladder
fq denominator of the smallest fraction of the ladder
gp numerator of the greatest fraction of the ladder
gq denominator of the greatest fraction of the ladder
a DSL a parameter
b DSL b parameter
mu DSL my parameter
Returns
a ray
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegment(), and DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegmentFareyFan().
template<typename TInteger , typename TNumber > DGtal::DSLSubsegment< TInteger, TNumber >::RayC DGtal::DSLSubsegment< TInteger, TNumber >::localizeRay (Integer fp, Integer fq, Integer gp, Integer gq, Integer r, Number alpha, Number beta, Integer n) inline protected
Compute the closest ray below the point (alpha,beta) passing through the point (fp/fq,r/fq) in the Farey fan of order n
Parameters
fp numerator of the smallest fraction of the ladder
fq denominator of the smallest fraction of the ladder
gp numerator of the greatest fraction of the ladder
gq denominator of the greatest fraction of the ladder
alpha DSL slope
beta DSL intercept
n order of the Farey Fan
Returns
a ray
Definition at line 910 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::ABOVE, DGtal::DSLSubsegment< TInteger, TNumber >::ONTO, DGtal::DSLSubsegment< TInteger, TNumber >::positionWrtRay(), DGtal::DSLSubsegment< TInteger, TNumber >::smartRayOfSmallestSlope(), DGtal::DSLSubsegment< TInteger, TNumber >::RayC::x, and DGtal::DSLSubsegment< TInteger, TNumber >::RayC::y.
 {
   Integer smallestSlope = smartRayOfSmallestSlope(fp,fq,gp,gq,r).x;
   Integer kmax = floor((n-smallestSlope)/fq) +1;
   Integer k = 0;
   Integer lup = 0;
   Integer ldown = kmax;
   Position myPosition;
   RayC aRay;
   bool found;
   while((lup>=2 || ldown >=2) && !found)
     {
       aRay = RayC(fp,fq,r,smallestSlope+k*fq);
       myPosition = positionWrtRay(aRay,alpha,beta);
 #ifdef DEBUG
       std::cout << "k " << k << " Ray " << aRay.x << " " << aRay.y << std::endl;
       std::cout << "myPosition " << myPosition << std::endl;
 #endif
       if(myPosition == ONTO)
         found = true;
       else
         if(myPosition == ABOVE)
           {
             k = k - ((lup%2 == 0)?lup/2:(lup-1)/2);
             ldown = ((lup%2 ==0)?lup/2:(lup-1)/2);
             lup = ((lup%2==0)?lup/2:(lup+1)/2);
           }
         else
           {
             k = k + ((ldown%2==0)?ldown/2:(ldown+1)/2);
             lup = ((ldown%2==0)?ldown/2:(ldown+1)/2);
             ldown = ((ldown%2==0)?ldown/2:(ldown-1)/2);
           }
     }
   if(!found)
     {
       aRay = RayC(fp,fq,r,smallestSlope+k*fq);
       myPosition = positionWrtRay(aRay,alpha,beta);
       if(myPosition == ABOVE || myPosition == ONTO)
         return aRay;
       else
         return RayC(fp,fq,r,smallestSlope+(k+1)*fq);
     }
   else
     return aRay;
 }
template<typename TInteger , typename TNumber > void DGtal::DSLSubsegment< TInteger, TNumber >::lowerConvexHull (Vector & l, Integer mu, Point & A, Point & B, Point * prevInfL, Point * infL, Point * infR, Point * prevInfR) inline protected
Compute the lower integer convex hull of the line of directional vector l and intercept mu between the points A and B. The algorithm works in two steps (from left to right and right to left). Each step returns the two closest points, and these four points are returned by the function.
Parameters
l directional vector of the straight line
mu intercept of the straight line
A left-most bound of the CH
B right-most bound of the CH
[out] prevInfL last-but-one point of the CH from left to right
[out] infL last point of the CH from left to right
[out] infR last point of the CH from right to left
[out] prevInfR last-but-one point of the CH from right to left
Definition at line 1286 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::convexHullApproxTwoPoints().
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegmentLocalCH().
 {
   Integer rA = l[1]*A[0]-l[0]*A[1] + mu;
   Integer rB = l[1]*B[0]-l[0]*B[1] + mu;
   Point prevSupL,supL,supR,prevSupR;
   // from left to right
   convexHullApproxTwoPoints(l,rA,B[0]-A[0],infL,&supL,prevInfL,&prevSupL,0); // computation of the left part of the convex hulls
   *infL += A;
   supL += A;
   *prevInfL +=A;
   prevSupL +=A;
   // from right to left
   if(rB !=0)
     {
       convexHullApproxTwoPoints(l,l[0]-rB,B[0]-A[0],infR,&supR,prevInfR,&prevSupR,1);
       Point B1 = B + Point(0,1);
       *infR = B1 - *infR;
       supR = B1 - supR;
       // swap inf and sup
       Point tmp;
       tmp = *infR;
       *infR = supR;
       supR = tmp;
       *prevInfR = B1 - *prevInfR;
       prevSupR = B1 - prevSupR;
       tmp = *prevInfR;
       *prevInfR = prevSupR;
       prevSupR = tmp;
     }
   else
     {
       convexHullApproxTwoPoints(l,0,B[0]-A[0],infR,&supR,prevInfR,&prevSupR,1);
       *infR = B - *infR;
       supR = B - supR;
       Point tmp;
       tmp = *infR;
       *infR = supR;
       supR = tmp;
       *prevInfR = B - *prevInfR;
       prevSupR = B - prevSupR;
       tmp = *prevInfR;
       *prevInfR = prevSupR;
       prevSupR = tmp;
     }
 }
template<typename TInteger , typename TNumber > DGtal::DSLSubsegment< TInteger, TNumber >::Point DGtal::DSLSubsegment< TInteger, TNumber >::nextTermInFareySeriesEuclid (Integer fp, Integer fq, Integer n) inline protected
Compute the term following fp/fq in the Farey series of order n.
Parameters
fp numerator
fq denominator
n order the the Farey Series
Returns
a point (q,p) such that p/q follows fp/fq in the Farey Series of order n
Definition at line 603 of file DSLSubsegment.ih.
References DGtal::IntegerComputer< TInteger >::extendedEuclid().
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegment(), DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegmentFareyFan(), and DGtal::DSLSubsegment< TInteger, TNumber >::findSolutionWithoutFractions().
 {
   Integer u,v;
   // u*p+v*q = 1
   DGtal::IntegerComputer<Integer> ic;
   Point p;
   p = ic.extendedEuclid(fp,fq,1);
   u = p[0];
   v = p[1];
   Integer pp = v;
   Integer qq = -u;
   pp = pp + floor((n+u)/fq)*fp;
   qq = qq + floor((n+u)/fq)*fq;
   return Point(qq,pp);
 }
template<typename TInteger , typename TNumber > DGtal::DSLSubsegment< TInteger, TNumber >::Position DGtal::DSLSubsegment< TInteger, TNumber >::positionWrtRay (RayC & r, Number a, Number b, Number mu) inline protected
Compute the position of the point (a/b,mu/b) with respect to a ray r. Number must be an Integer type
Parameters
r a ray
a numerator of x-coordinate
b denominator of x- and y-coordinates
mu numerator of x-coordinate
Returns
Position equal to BELOW, ABOVE or ONTO
Definition at line 660 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::ABOVE, DGtal::DSLSubsegment< TInteger, TNumber >::BELOW, DGtal::DSLSubsegment< TInteger, TNumber >::BOOST_CONCEPT_ASSERT(), DGtal::DSLSubsegment< TInteger, TNumber >::ONTO, DGtal::DSLSubsegment< TInteger, TNumber >::RayC::x, and DGtal::DSLSubsegment< TInteger, TNumber >::RayC::y.
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::localizeRay(), and DGtal::DSLSubsegment< TInteger, TNumber >::smartFirstDichotomy().
 {
   BOOST_CONCEPT_ASSERT((CInteger<TNumber>));
   Integer v = -a*r.x + r.y*b - mu;
   if(v == 0)
     return ONTO;
   else
     if(v > 0)
       return BELOW;
   return ABOVE;
 }
template<typename TInteger , typename TNumber > DGtal::DSLSubsegment< TInteger, TNumber >::Position DGtal::DSLSubsegment< TInteger, TNumber >::positionWrtRay (RayC & r, Number alpha, Number beta) inline protected
Compute the position of the floating-point point(alpha,beta) with respect to a ray r.
Parameters
r a ray
alpha x-coordinate
beta y-coordinate
Returns
Position equal to BELOW, ABOVE or ONTO
Definition at line 679 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::ABOVE, DGtal::DSLSubsegment< TInteger, TNumber >::BELOW, DGtal::DSLSubsegment< TInteger, TNumber >::myPrecision, DGtal::DSLSubsegment< TInteger, TNumber >::ONTO, DGtal::DSLSubsegment< TInteger, TNumber >::RayC::x, and DGtal::DSLSubsegment< TInteger, TNumber >::RayC::y.
 {
   Number v = -alpha*r.x + r.y - beta;
   if(fabs(v) <= myPrecision )
     {
       return ONTO;
     }
   else
     if(v > 0)
       return BELOW;
   return ABOVE;
 }
template<typename TInteger , typename TNumber > DGtal::DSLSubsegment< TInteger, TNumber >::RayC DGtal::DSLSubsegment< TInteger, TNumber >::rayOfHighestSlope (Integer p, Integer q, Integer r, Integer smallestSlope, Integer n) inline protected
Compute the ray of highest slope passing through a given point (p/q,r/q) in O(1) knowing the ray of smallest slope and the order of the Farey fan
Parameters
p numerator of x-coordinate
q denominator of x- and y-coordinates
r numerator of y-coordinate
smallestSlope smallest slope of the rays passing through (p/q,r/q)
n order of the Farey fan
Returns
a ray
Definition at line 628 of file DSLSubsegment.ih.
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::smartFirstDichotomy().
  {
    return RayC(p,q,r,n-(n-smallestSlope)%q);
  }
template<typename TInteger , typename TNumber > DGtal::DSLSubsegment< TInteger, TNumber >::RayC DGtal::DSLSubsegment< TInteger, TNumber >::raySup (Integer fp, Integer fq, RayC r) inline protected
Compute the ray passing through from (f=fp/fq,h/fq) just above r. The knowledge of h is not necessary. Complexity O(1)
Parameters
fp numerator
fq denominator
Definition at line 973 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::RayC::x, and DGtal::DSLSubsegment< TInteger, TNumber >::RayC::y.
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::findSolutionWithoutFractions().
  {
    RayC rr;
    // r is the highest ray
    if(r.x - fq < 0)
      return r;
    else
      {
        rr.x = r.x - fq;
        rr.y = r.y - fp;
      }
    return rr;
  }
template<typename TInteger, typename TNumber> void DGtal::DSLSubsegment< TInteger, TNumber >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
template<typename TInteger , typename TNumber > void DGtal::DSLSubsegment< TInteger, TNumber >::shortFindSolution (Integer fp, Integer fq, Integer gp, Integer gq, RayC r, Integer n, Integer * resAlphaP, Integer * resAlphaQ, Integer * resBetaP) inline protected
Corresponds to the algorithm presented in [sivignonDGCI2013]}.
Parameters
fp numerator of the smallest fraction of the ladder
fq denominator of the smallest fraction of the ladder
gp numerator of the greatest fraction of the ladder
gq denominator of the greatest fraction of the ladder
r a ray
n order of the Farey Fan
[out] resAlphaP numerator of the x-coordinate of the result
[out] resAlphaQ denominator of the x- and y- coordinates of the result
[out] resBetaP numerator of the y-coordinate of the result
Definition at line 991 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::convexHullApprox(), DGtal::IntegerComputer< TInteger >::gcd(), DGtal::IntegerComputer< TInteger >::max(), DGtal::DSLSubsegment< TInteger, TNumber >::RayC::x, and DGtal::DSLSubsegment< TInteger, TNumber >::RayC::y.
 {
   Point inf, sup , tmpsup, tmpinf;
   DGtal::IntegerComputer<Integer> ic;
   //Compute the lower edge of the facet
   if(fq <= ic.max(r.x,n-r.x))
     {
       inf[0] = fq;
       inf[1] = fp;
     }
   else
     convexHullApprox(Vector(fq,fp),0,ic.max(r.x,n-r.x),&inf,&tmpsup);
   if(gq <= ic.max(r.x,n-r.x))
     {
       sup[0] = gq;
       sup[1] = gp;
     }
   else
     convexHullApprox(Vector(gq,gp),0,ic.max(r.x,n-r.x),&tmpinf,&sup);
   if(r.x-inf[0] < 0) // R is the ray of smallest slope in inf
     {
       *resAlphaP = inf[1];
       *resAlphaQ = inf[0];
       *resBetaP = -(*resAlphaP)*r.x+(*resAlphaQ)*r.y;
     }
   else
     if(r.x+sup[0] > n) // R is the ray of highest slope in sup
       {
         *resAlphaP = sup[1];
         *resAlphaQ = sup[0];
         *resBetaP = -(*resAlphaP)*r.x+(*resAlphaQ)*r.y;
       }
     else  //the facet is upper triangular,
       {
         Integer g = ic.gcd(inf[1] + sup[1],inf[0]+sup[0]);
         *resAlphaP = (inf[1]+sup[1])/g;
         *resAlphaQ = (inf[0]+sup[0])/g;
         *resBetaP = -(*resAlphaP)*r.x+(*resAlphaQ)*r.y;
       }
 }
template<typename TInteger , typename TNumber > DGtal::DSLSubsegment< TInteger, TNumber >::Integer DGtal::DSLSubsegment< TInteger, TNumber >::slope (Integer p, Integer q, Integer r, Number a, Number b, Number mu) inline protected
Compute the ceil of the slope of the line through (f=p/q,r/q) and point (a/b,mu/b) - O(1) - Number must be an Integer type.
Parameters
p numerator of x-coordinate of the first point
q denominator of x- and y-coordinates of the first point
r numerator of y-coordinate of the first point
a numerator of x-coordinate of the second point
b denominator of x- and y-coordinates of the second point
mu numerator of y-coordinate of the second point
Returns
the ceil of the slope of the line passing through the two points
Definition at line 637 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::BOOST_CONCEPT_ASSERT().
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::RayC::RayC().
 {
   BOOST_CONCEPT_ASSERT((CInteger<TNumber>));
   return (Integer) ceil((LongDoubleType) (r*b-mu*q)/(-p*b+a*q));
 }
template<typename TInteger , typename TNumber > DGtal::DSLSubsegment< TInteger, TNumber >::Integer DGtal::DSLSubsegment< TInteger, TNumber >::slope (Integer p, Integer q, Integer r, Number alpha, Number beta) inline protected
Compute the ceil of the slope of the line through (f=p/q,r/q) and floating-point point (alpha,beta) - O(1)
Parameters
p numerator of x-coordinate of the first point
q denominator of x- and y-coordinates of the first point
r numerator of y-coordinate of the first point
alpha x-coordinate of the second point
beta y-coordinate of the second point
Returns
the ceil of the slope of the line passing through the two points
Definition at line 645 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::myPrecision.
 {
   Number val = (r-beta*q)/(-p+alpha*q);
   // if the value is very close to a slightly smaller integer, we round to the close integer
   if(val-floor(val) <= myPrecision)
     return((Integer) floor(val));
   else
     return((Integer) ceil(val));
 }
template<typename TInteger , typename TNumber > DGtal::DSLSubsegment< TInteger, TNumber >::Integer DGtal::DSLSubsegment< TInteger, TNumber >::smartFirstDichotomy (Integer fp, Integer fq, Integer gp, Integer gq, Number a, Number b, Number mu, Integer n, bool * flagRayFound) inline protected
Performs a dichotomy among the rays of smallest slope passing through the points (fp/fq,r/fq), r in [0,fq] in order to locate the point lambda(a/b,mu/b) in the ladder. Implements line 3 of Algorithm 1 in [sivignonDGCI2013]}. Return an integer h such that either i) lambda is in between the rays passing through the point (fp/fq,h/fq) and flagRayFound is set to false or ii) lambda is below all the rays passing through the point (fp/fq,h+1/fq) and above all the rays passing through the point (fp/fq,h/fq) and flagRayFound is set to false. In case i), function localizeRay is used afterwards to localize lambda in between the rays. In case ii), the ray under lambda has been found and no further search is needed. The Number type must verify the CInteger concept (otherwise, see overloaded function).
Parameters
fp numerator of the smallest fraction of the ladder
fq denominator of the smallest fraction of the ladder
gp numerator of the greatest fraction of the ladder
gq denominator of the greatest fraction of the ladder
a DSL a parameter
b DSL b parameter
mu DSL mu parameter
n order of the Farey Fan
[out] flagRayFound pointer on a boolean, used to check whether localizeRay should be called ot not
Returns
an integer
Definition at line 720 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::ABOVE, DGtal::DSLSubsegment< TInteger, TNumber >::BELOW, DGtal::DSLSubsegment< TInteger, TNumber >::BOOST_CONCEPT_ASSERT(), DGtal::DSLSubsegment< TInteger, TNumber >::ONTO, DGtal::DSLSubsegment< TInteger, TNumber >::positionWrtRay(), DGtal::DSLSubsegment< TInteger, TNumber >::rayOfHighestSlope(), and DGtal::DSLSubsegment< TInteger, TNumber >::smartRayOfSmallestSlope().
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegment(), and DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegmentFareyFan().
 {
   BOOST_CONCEPT_ASSERT((CInteger<Number>));
   RayC myRay;
   Position myPosition;
   Integer r = 0;
   Integer lup = fq;
   Integer ldown = 0;
   *flagRayFound = false;
   while((lup>=2 || ldown >=2) && !*flagRayFound)
     {
       myRay = smartRayOfSmallestSlope(fp,fq,gp,gq,r);
       myPosition = positionWrtRay(myRay,a,b,mu);
 // #ifdef DEBUG
 //       std::cout << "height " << r << " Ray " << myRay.x << " " << myRay.y << std::endl;
 //       std::cout << "myPosition " << myPosition << std::endl;
 // #endif
       if(myPosition == ONTO)
          *flagRayFound = true;
       else
         if(myPosition == ABOVE)
           {
             r = r + ((lup%2 == 0)?lup/2:(lup-1)/2);
             ldown = ((lup%2 ==0)?lup/2:(lup-1)/2);
             lup = ((lup%2==0)?lup/2:(lup+1)/2);
           }
         else
           {
             r = r - ((ldown%2==0)?ldown/2:(ldown+1)/2);
             lup = ((ldown%2==0)?ldown/2:(ldown+1)/2);
             ldown = ((ldown%2==0)?ldown/2:(ldown-1)/2);
           }
     }
   // If the point is not on a ray of smallest slope
   if(!*flagRayFound)
      {
        myRay = smartRayOfSmallestSlope(fp,fq,gp,gq,r);
        myPosition = positionWrtRay(myRay,a,b,mu);
        if(myPosition != ONTO)
          {
            if(myPosition == ABOVE)
              r++;
            RayC SteepestRay = rayOfHighestSlope(fp, fq,r,(smartRayOfSmallestSlope(fp,fq,gp,gq,r)).x,n);
            Position pos = positionWrtRay(SteepestRay,a,b,mu);
            if(pos==BELOW)
              {
                r--;
                *flagRayFound = true;
              }
          }
        else
          *flagRayFound = true;
      }
 // #ifdef DEBUG
 //    std::cout << r << std::endl;
 // #endif
    return r;
  }
template<typename TInteger , typename TNumber > DGtal::DSLSubsegment< TInteger, TNumber >::Integer DGtal::DSLSubsegment< TInteger, TNumber >::smartFirstDichotomy (Integer fp, Integer fq, Integer gp, Integer gq, Number alpha, Number beta, Integer n, bool * flagRayFound) inline protected
Performs a dichotomy among the rays of smallest slope passing through the points (fp/fq,r/fq), r in [0,fq] in order to locate the point lambda(alpha,beta) in the ladder. Implements line 3 of Algorithm 1 in [sivignonDGCI2013]}. Return an integer h such that either i) lambda is in between the rays passing through the point (fp/fq,h/fq) and flagRayFound is set to false or ii) lambda is below all the rays passing through the point (fp/fq,h+1/fq) and above all the rays passing through the point (fp/fq,h/fq) and flagRayFound is set to false. In case i), function localizeRay is used afterwards to localize lambda in between the rays. In case ii), the ray under lambda has been found and no further search is needed.
Parameters
fp numerator of the smallest fraction of the ladder
fq denominator of the smallest fraction of the ladder
gp numerator of the greatest fraction of the ladder
gq denominator of the greatest fraction of the ladder
alpha DSL slope
beta DSL intercept
n order of the Farey Fan
[out] flagRayFound pointer on a boolean, used to check whether localizeRay should be called ot not
Returns
an integer
Definition at line 799 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::ABOVE, DGtal::DSLSubsegment< TInteger, TNumber >::BELOW, DGtal::DSLSubsegment< TInteger, TNumber >::ONTO, DGtal::DSLSubsegment< TInteger, TNumber >::positionWrtRay(), DGtal::DSLSubsegment< TInteger, TNumber >::rayOfHighestSlope(), and DGtal::DSLSubsegment< TInteger, TNumber >::smartRayOfSmallestSlope().
 {
   RayC myRay;
   Position myPosition;
   Integer r = 0;
   Integer lup = fq;
   Integer ldown = 0;
   *flagRayFound = false;
 // #ifdef DEBUG
 //   std::cout << fp << " " << fq << " " << gp << " " << gq << std::endl;
 // #endif
   while((lup>=2 || ldown >=2) && !*flagRayFound)
     {
       myRay = smartRayOfSmallestSlope(fp,fq,gp,gq,r);
       myPosition = positionWrtRay(myRay,alpha,beta);
  // #ifdef DEBUG
  //             std::cout << "height " << r << " Ray " << myRay.x << " " << myRay.y << std::endl;
  //          std::cout << "myPosition " << myPosition << std::endl;
  // #endif
       if(myPosition == ONTO)
         *flagRayFound = true;
       else
         if(myPosition == ABOVE)
           {
             r = r + ((lup%2 == 0)?lup/2:(lup-1)/2);
             ldown = ((lup%2 ==0)?lup/2:(lup-1)/2);
             lup = ((lup%2==0)?lup/2:(lup+1)/2);
           }
         else
           {
             r = r - ((ldown%2==0)?ldown/2:(ldown+1)/2);
             lup = ((ldown%2==0)?ldown/2:(ldown+1)/2);
             ldown = ((ldown%2==0)?ldown/2:(ldown-1)/2);
           }
     }
   // If the point is not on a ray of smallest slope
    if(!*flagRayFound)
      {
        myRay = smartRayOfSmallestSlope(fp,fq,gp,gq,r);
        myPosition = positionWrtRay(myRay,alpha,beta);
        if(myPosition != ONTO)
          {
            if(myPosition == ABOVE)
              r++;
            RayC SteepestRay = rayOfHighestSlope(fp, fq,r,(smartRayOfSmallestSlope(fp,fq,gp,gq,r)).x,n);
            Position pos = positionWrtRay(SteepestRay,alpha,beta);
            if(pos == BELOW)
              {
                r--;
                *flagRayFound = true;
              }
          }
        else
          *flagRayFound = true;
      }
    //std::cout << r;
 // #ifdef DEBUG
 //    std::cout << r << std::endl;
 // #endif
    return r;
 }
template<typename TInteger , typename TNumber > DGtal::DSLSubsegment< TInteger, TNumber >::RayC DGtal::DSLSubsegment< TInteger, TNumber >::smartRayOfSmallestSlope (Integer fp, Integer fq, Integer gp, Integer gq, Integer r) inline protected
Computes the ray of smallest slope emanating from the point (f=p/q, r/q) using the knowledge of the next fraction g in the Farey Series. Complexity O(1)
Parameters
fp numerator of the point x-coordinate
fq denominator of the point x- and y-coordinates
gp numerator of the fraction following fp/fq in the Farey Series
gq denominator of the fraction following fp/fq in the Farey Series
r numerator of the point y-coordinate
Returns
the ray of smallest slope passing through the point
Definition at line 698 of file DSLSubsegment.ih.
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegment(), DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegmentFareyFan(), DGtal::DSLSubsegment< TInteger, TNumber >::findSolutionWithoutFractions(), DGtal::DSLSubsegment< TInteger, TNumber >::localizeRay(), and DGtal::DSLSubsegment< TInteger, TNumber >::smartFirstDichotomy().
  {
    // Version 1: using floor operator
    Integer rr;
    if(r == fq)
      rr = gq;
    else
      rr = (r*gq)/fq;
    // Compute the slope of the line through (f=p/Q,r/q) and
    // (g=p'/q',rr/q')
    Integer x = (r*gq - rr*fq);
    Integer y = r*gp-rr*fp; // after simplification of the above formula
    return RayC(x,y);
  }
template<typename TInteger , typename TNumber > void DGtal::DSLSubsegment< TInteger, TNumber >::update (Vector & u, Point & A, Vector & l, Integer r, Vector * v) inline protected
Update the Bezout vector v of u according to the new point A in the case of integer parameters. Follows algorithm presented in [CharrierBuzer2009]}
Parameters
u a vector
A a point
l directional vector of the line
r intercept of the line
[in,out] v bezout vector updated in this function
Definition at line 148 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::intersection().
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::convexHullApprox(), and DGtal::DSLSubsegment< TInteger, TNumber >::convexHullApproxTwoPoints().
 {
   Point AA = A;
   AA +=(*v);
   Integer alpha = intersection(AA,u,l,r);
   u *= alpha;
   (*v) += u;
 }
template<typename TInteger , typename TNumber > void DGtal::DSLSubsegment< TInteger, TNumber >::update (Vector & u, Point & A, Number s, Vector * v) inline protected
Update the Bezout vector v of u according to the new point A in the case of floating-point parameters. Follows algorithm presented in [CharrierBuzer2009]}
Parameters
u a vector
A a point
s slope of the line
[in,out] v bezout vector updated in this function
Definition at line 162 of file DSLSubsegment.ih.
References DGtal::DSLSubsegment< TInteger, TNumber >::intersection().
 {
   Point AA = A;
   AA +=(*v);
   Integer alpha = intersection(AA,u,s);
   u *= alpha;
   (*v) += u;
 }
Field Documentation
template<typename TInteger, typename TNumber> Integer DGtal::DSLSubsegment< TInteger, TNumber >::myA protected
The minimal characteristics of the subsegment AB of the DSL(a,b,mu) are (myA,myB,myMu).
Definition at line 149 of file DSLSubsegment.h.
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegment(), DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegmentFareyFan(), DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegmentLocalCH(), and DGtal::DSLSubsegment< TInteger, TNumber >::getA().
template<typename TInteger, typename TNumber> Integer DGtal::DSLSubsegment< TInteger, TNumber >::myB protected
The minimal characteristics of the subsegment AB of the DSL(a,b,mu) are (myA,myB,myMu).
Definition at line 156 of file DSLSubsegment.h.
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegment(), DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegmentFareyFan(), DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegmentLocalCH(), and DGtal::DSLSubsegment< TInteger, TNumber >::getB().
template<typename TInteger, typename TNumber> Integer DGtal::DSLSubsegment< TInteger, TNumber >::myMu protected
The minimal characteristics of the subsegment AB of the DSL(a,b,mu) are (myA,myB,myMu).
Definition at line 163 of file DSLSubsegment.h.
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegment(), DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegmentFareyFan(), DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegmentLocalCH(), and DGtal::DSLSubsegment< TInteger, TNumber >::getMu().
template<typename TInteger, typename TNumber> Number DGtal::DSLSubsegment< TInteger, TNumber >::myPrecision protected
Precision used for floating-point geometrical predicates (when TNumber is not an integer type)
Definition at line 169 of file DSLSubsegment.h.
Referenced by DGtal::DSLSubsegment< TInteger, TNumber >::convexHullApprox(), DGtal::DSLSubsegment< TInteger, TNumber >::DSLSubsegment(), DGtal::DSLSubsegment< TInteger, TNumber >::intersection(), DGtal::DSLSubsegment< TInteger, TNumber >::positionWrtRay(), and DGtal::DSLSubsegment< TInteger, TNumber >::slope().
The documentation for this class was generated from the following files:
DSLSubsegment.h
DSLSubsegment.ih