DGtal: DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency > Class Template Reference
DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency > Class Template Reference
#include <ArithmeticalDSL.h>
Data Structures
class ConstIterator
Public Types
typedef TCoordinate Coordinate
typedef TInteger Integer
typedef ArithmeticalDSLKernel
< Coordinate, adjacency >
::Space Space
typedef Space::Point Point
typedef Space::Vector Vector
typedef std::pair< Vector, Vector > Steps
typedef DGtal::ReverseIterator
< ConstIterator > ConstReverseIterator
Public Member Functions
BOOST_CONCEPT_ASSERT ((CInteger< Coordinate >))
BOOST_CONCEPT_ASSERT ((CInteger< Integer >))
ArithmeticalDSL (const Coordinate &aA, const Coordinate &aB, const Integer &aLowerIntercept, const Integer &aUpperIntercept, const Steps &aSteps, const Vector &aShift)
ArithmeticalDSL (const Coordinate &aA, const Coordinate &aB, const Integer &aMu)
ArithmeticalDSL (const ArithmeticalDSL &aOther)
ArithmeticalDSL & operator= (const ArithmeticalDSL &aOther)
ArithmeticalDSL negate () const
bool equalsTo (const ArithmeticalDSL &aOther) const
bool operator== (const ArithmeticalDSL &aOther) const
bool operator!= (const ArithmeticalDSL &aOther) const
~ArithmeticalDSL ()
void selfDisplay (std::ostream &out) const
bool checkShiftAndSteps () const
bool isValid () const
Coordinate a () const
Coordinate b () const
Integer mu () const
Integer omega () const
Vector shift () const
Steps steps () const
Integer remainder (const Point &aPoint) const
Integer orthogonalPosition (const Point &aPoint) const
Integer position (const Point &aPoint) const
bool before (const Point &aP1, const Point &aP2) const
bool beforeOrEqual (const Point &aP1, const Point &aP2) const
bool isInDSL (const Point &aPoint) const
bool operator() (const Point &aPoint) const
ConstIterator begin (const Point &aPoint) const
ConstIterator end (const Point &aPoint) const
ConstReverseIterator rbegin (const Point &aPoint) const
ConstReverseIterator rend (const Point &aPoint) const
Static Public Member Functions
static Integer remainder (const Integer &aA, const Integer &aB, const Point &aPoint)
Static Public Attributes
static const unsigned short foregroundAdjacency = adjacency
Protected Attributes
Steps mySteps
Vector myShift
Coordinate myA
Coordinate myB
Integer myLowerBound
Integer myUpperBound
Friends
class ArithmeticalDSS< TCoordinate, TInteger, adjacency >
Detailed Description
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8>
class DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >
Aim: This class represents a naive (resp. standard) digital straight line (DSL), ie. the set of digital points \((x,y) \in \mathbb{Z}^2 \) such that \(\mu \leq ax - by < \mu + \omega \) with \(a,b,\mu,\omega \in \mathbb{Z} \), \(\gcd(a,b) = 1 \) and \(\omega = \max(|a|,|b|) \) (resp. \(\omega = |a| + |b| \)). Note that any DSL such that \(\omega = \max(|a|,|b|) \) (resp. \(\omega = |a| + |b| \)) is simply 8-connected (resp. 4-connected).
[Reveilles, 1991 : [30]].
A naive DSL can be declared and constructed as follows:
#include "DGtal/arithmetic/geometry/curves/ArithmeticalDSL.h"
...
ArithmeticalDSL<DGtal::int32_t, DGtal::int64_t, 8> line(17711, 28657, 1607895256);
// equivalent to ArithmeticalDSL<DGtal::int32_t, DGtal::int64_t> line(17711, 28657, 1607895256);
See Digital straight lines and segments. for further details.
This class is a model of CPointFunctor and of CConstBidirectionalRange.
In the standard case, it is enough to replace 8 by 4.
Template Parameters
TCoordinate a model of integer for the DGtal point coordinates and the slope parameters.
TInteger a model of integer for the intercepts and the remainders that represents a larger range of integers than TCoordinate.
adjacency an unsigned integer equal to 8 (default) for naive DSL, and 4 for standard DSL.
See Also
ArithmeticalDSL NaiveDSL StandardDSL
exampleArithmeticalDSL.cpp
Definition at line 104 of file ArithmeticalDSL.h.
Member Typedef Documentation
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> typedef DGtal::ReverseIterator<ConstIterator> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::ConstReverseIterator
Type of const reverse iterator, adapted from ConstIterator.
Definition at line 258 of file ArithmeticalDSL.h.
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> typedef TCoordinate DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::Coordinate
Type used for the points coordinates and the slope parameters.
Definition at line 125 of file ArithmeticalDSL.h.
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> typedef TInteger DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::Integer
Type used for the intercepts and the remainders.
Definition at line 130 of file ArithmeticalDSL.h.
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> typedef Space::Point DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::Point
Type of point.
Definition at line 140 of file ArithmeticalDSL.h.
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> typedef ArithmeticalDSLKernel<Coordinate,adjacency>::Space DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::Space
Type of digital plane.
Definition at line 136 of file ArithmeticalDSL.h.
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> typedef std::pair<Vector,Vector> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::Steps
Type of step vectors, defined as STL pair of vectors.
Definition at line 148 of file ArithmeticalDSL.h.
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> typedef Space::Vector DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::Vector
Type of vector.
Definition at line 144 of file ArithmeticalDSL.h.
Constructor & Destructor Documentation
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::ArithmeticalDSL (const Coordinate & aA, const Coordinate & aB, const Integer & aLowerIntercept, const Integer & aUpperIntercept, const Steps & aSteps, const Vector & aShift) inline
Constructor. The user gives all the (redondant) parameters and should be sure that the resulting DSL is valid.
See Also
isValid
Parameters
aA y-component of the direction vector
aB x-component of the direction vector
aLowerIntercept lower intercept
aUpperIntercept upper intercept
aSteps pair of steps used to iterate over the DSL points
aShift shift vector
Definition at line 44 of file ArithmeticalDSL.ih.
   :
   mySteps(aSteps), myShift(aShift),
   myA(aA), myB(aB),
   myLowerBound(aLowerBound), myUpperBound(aUpperBound)
 {
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::ArithmeticalDSL (const Coordinate & aA, const Coordinate & aB, const Integer & aMu) inline
Constructor with the minimal set of parameters.
Parameters
aA y-component of the direction vector
aB x-component of the direction vector
aMu intercept
Definition at line 58 of file ArithmeticalDSL.ih.
References DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::myShift, DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::myUpperBound, and DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::remainder().
   :
   mySteps( DGtal::ArithmeticalDSLKernel<TCoordinate,adjacency>::steps(aA, aB) ),
   myShift( DGtal::ArithmeticalDSLKernel<TCoordinate,adjacency>::shift(aA, aB) ),
   myA(aA), myB(aB),
   myLowerBound( aMu ),
   myUpperBound( aMu )
 {
   if ( (aA != 0)&&(aB !=0 ) )
     myUpperBound = aMu + remainder( myShift ) - NumberTraits<Integer>::ONE;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::ArithmeticalDSL (const ArithmeticalDSL< TCoordinate, TInteger, adjacency > & aOther) inline
Copy constructor.
Parameters
aOther the object to clone.
Definition at line 75 of file ArithmeticalDSL.ih.
   :
   mySteps(aOther.mySteps), myShift(aOther.myShift),
   myA(aOther.myA), myB(aOther.myB),
   myLowerBound(aOther.myLowerBound), myUpperBound(aOther.myUpperBound)
 {}
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::~ArithmeticalDSL () inline
Destructor.
Definition at line 150 of file ArithmeticalDSL.ih.
 {
 }
Member Function Documentation
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::Coordinate DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::a () const inline
Returns
a parameter (y-component of the direction vector)
Definition at line 208 of file ArithmeticalDSL.ih.
Referenced by DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency >::createPattern(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::remainder(), and DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::selfDisplay().
 {
   return myA;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::Coordinate DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::b () const inline
Returns
b parameter (x-component of the direction vector)
Definition at line 217 of file ArithmeticalDSL.ih.
Referenced by DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency >::createPattern(), DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::remainder(), and DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::selfDisplay().
 {
   return myB;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::before (const Point & aP1, const Point & aP2) const inline
Returns a boolean equal to 'true' if aP1 is located (strictly) before aP2 in the direction orthogonal to myShift, 'false' otherwise.
Parameters
aP1 any point
aP2 any point
Returns
'true' is aP2 is strictly before aP2, 'false' otherwise
See Also
beforeOrEqual position
Definition at line 303 of file ArithmeticalDSL.ih.
 {
   return ( position( aP1 ) < position( aP2 ) );
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::beforeOrEqual (const Point & aP1, const Point & aP2) const inline
Returns a boolean equal to 'true' if aP1 is located before aP2 or is equal to aP2, 'false' otherwise.
Parameters
aP1 any point
aP2 any point
Returns
'true' is aP2 is before or equal to aP2, 'false' otherwise
See Also
before position
Definition at line 312 of file ArithmeticalDSL.ih.
 {
   return ( position( aP1 ) <= position( aP2 ) );
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::ConstIterator DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::begin (const Point & aPoint) const inline
Parameters
aPoint any point of the DSL
Precondition
aPoint sould belongs to the DSL
Returns
begin iterator, which points to aPoint
Definition at line 341 of file ArithmeticalDSL.ih.
 {
   ASSERT( isInDSL(aPoint) );
   return ConstIterator(this, aPoint);
 }
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::BOOST_CONCEPT_ASSERT ((CInteger< Coordinate >))
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::BOOST_CONCEPT_ASSERT ((CInteger< Integer >))
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::checkShiftAndSteps () const inline
Checks the consistency between the slope parameters, ie. myA , myB and the translating vectors myShift , mySteps
Returns
'true' if ok, 'false' otherwise
Precondition
myA and myB must not be both null
Definition at line 182 of file ArithmeticalDSL.ih.
 {
   ASSERT( (myA != 0) || (myB != 0) );
   bool flagIsValid; //'true' if valid, 'false' otherwise
   if (mySteps != DGtal::ArithmeticalDSLKernel<TCoordinate,adjacency>::steps(myA, myB))
     flagIsValid = false;
   else if (myShift != DGtal::ArithmeticalDSLKernel<TCoordinate,adjacency>::shift(myA, myB))
     flagIsValid = false;
   else if ( ( (mySteps.second[0] != NumberTraits<Coordinate>::ZERO)
               ||(mySteps.second[1] != NumberTraits<Coordinate>::ZERO) )
             &&( (mySteps.first - mySteps.second) != myShift ) )
     flagIsValid = false;
   else if ( remainder( myShift ) != (myUpperBound - myLowerBound + NumberTraits<Integer>::ONE) )
     flagIsValid = false;
   else
     flagIsValid = true;
   return flagIsValid;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::ConstIterator DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::end (const Point & aPoint) const inline
Parameters
aPoint any point of the DSL
Precondition
aPoint sould belongs to the DSL
Returns
end iterator, which points to the point located after aPoint
Definition at line 351 of file ArithmeticalDSL.ih.
 {
   ASSERT( isInDSL(aPoint) );
   ConstIterator it(this, aPoint);
   it++;
   return it;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::equalsTo (const ArithmeticalDSL< TCoordinate, TInteger, adjacency > & aOther) const inline
Equality.
Parameters
aOther the object to compare with.
Returns
'true' if the parameters of the DSL are equal (orientation matters), 'false' otherwise
Definition at line 118 of file ArithmeticalDSL.ih.
References DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::myA, DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::myB, DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::myLowerBound, and DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::myUpperBound.
 {
   return ( (myA == aOther.myA) &&
            (myB == aOther.myB) &&
            (myLowerBound == aOther.myLowerBound) &&
            (myUpperBound == aOther.myUpperBound) );
   //NB: other redondant members are not tested
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::isInDSL (const Point & aPoint) const inline
Returns
'true' if aPoint is in the DSL 'false' otherwise.
Parameters
aPoint any point
Definition at line 321 of file ArithmeticalDSL.ih.
 {
   Integer r = remainder(aPoint);
   return ( (r >= myLowerBound)&&(r <= myUpperBound) );
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
NB: runs in O(log(max(|myA |,| myB |))) because it checks if myA and myB are relatively primes.
Definition at line 158 of file ArithmeticalDSL.ih.
References DGtal::gcd(), and DGtal::IntegerComputer< TInteger >::staticGcd().
 {
   bool flagIsValid; //'true' if valid, 'false' otherwise
   if ( (myA != 0) || (myB != 0) )
     {
       Integer gcd = IntegerComputer<Coordinate>::staticGcd(myA, myB);
       if (gcd != NumberTraits<Coordinate>::ONE)
         flagIsValid = false; //a,b must be relatively prime
       else if (!checkShiftAndSteps())
         flagIsValid = false; //redondant parameters must be consistent
       else
         flagIsValid = true;
     }
   else
     flagIsValid = false; //a and b cannot be both null
   return flagIsValid;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::Integer DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::mu () const inline
Returns
mu parameter, the intercept \(\mu \)
Definition at line 226 of file ArithmeticalDSL.ih.
Referenced by DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::selfDisplay().
 {
   return myLowerBound;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency > DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::negate () const inline
Returns a copy of '*this' with a reverse orientation, ie. with parameters (-myA , -myB , -myUpperIntercept , -myLowerIntercept).
Returns
the negation of '*this'.
Definition at line 106 of file ArithmeticalDSL.ih.
Referenced by DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::operator==().
 {
     return DGtal::ArithmeticalDSL<TCoordinate, TInteger, adjacency>(-myA, -myB, -myUpperBound, -myLowerBound,
                                                std::make_pair(-mySteps.first, -mySteps.second),
                                                -myShift);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::Integer DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::omega () const inline
Returns
the arithmetical thickness \(\omega \)
Definition at line 235 of file ArithmeticalDSL.ih.
Referenced by DGtal::OneBalancedWordComputer< TConstIterator, TInteger >::selfDisplay().
 {
   return remainder(myShift);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::operator!= (const ArithmeticalDSL< TCoordinate, TInteger, adjacency > & aOther) const inline
Difference.
Parameters
aOther the object to compare with.
Returns
'true' the two set of points that are implicitly defined are different, 'false' otherwise
Definition at line 142 of file ArithmeticalDSL.ih.
 {
   return !( operator==(aOther) );
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::operator() (const Point & aPoint) const inline
Returns
'true' if aPoint is in the DSL 'false' otherwise.
Parameters
aPoint any point
See Also
isInDSL
Definition at line 332 of file ArithmeticalDSL.ih.
 {
   return isInDSL(aPoint);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency > & DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::operator= (const ArithmeticalDSL< TCoordinate, TInteger, adjacency > & aOther) inline
Assignment.
Parameters
aOther the object to copy.
Returns
a reference on 'this'.
Definition at line 87 of file ArithmeticalDSL.ih.
References DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::myA, DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::myB, DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::myLowerBound, DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::myShift, DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::mySteps, and DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::myUpperBound.
 {
   if ( this != &aOther )
     {
       myA = aOther.myA;
       myB = aOther.myB;
       myLowerBound = aOther.myLowerBound;
       myUpperBound = aOther.myUpperBound;
       mySteps = aOther.mySteps;
       myShift = aOther.myShift;
     }
   return *this;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::operator== (const ArithmeticalDSL< TCoordinate, TInteger, adjacency > & aOther) const inline
Equality.
Parameters
aOther the object to compare with.
Returns
'true' the two sets of points that are implicitly defined are equal (without respect to the orientation), 'false' otherwise
See Also
equalsTo
Definition at line 132 of file ArithmeticalDSL.ih.
References DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::negate().
 {
   return ( equalsTo(aOther) || equalsTo(aOther.negate()) );
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::Integer DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::orthogonalPosition (const Point & aPoint) const inline
Returns the position of aPoint (which does not necessarily belong to the DSL) computed along the direction that is orthogonal to the direction vector
Parameters
aPoint the point whose position is returned
Returns
the position
Definition at line 283 of file ArithmeticalDSL.ih.
 {
   return myB * static_cast<Integer>(aPoint[0])
     + myA * static_cast<Integer>(aPoint[1]);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::Integer DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::position (const Point & aPoint) const inline
Returns the position of aPoint (which does not necessarily belong to the DSL) computed along the direction orthogonal to myShift
Parameters
aPoint the point whose position is returned
Returns
the position
Definition at line 293 of file ArithmeticalDSL.ih.
 {
   return ( -static_cast<Integer>(myShift[1]) * static_cast<Integer>(aPoint[0])
     +static_cast<Integer>(myShift[0]) * static_cast<Integer>(aPoint[1]) );
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::ConstReverseIterator DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::rbegin (const Point & aPoint) const inline
Parameters
aPoint any point of the DSL
Precondition
aPoint sould belongs to the DSL
Returns
begin reverse iterator, which points to aPoint
Definition at line 363 of file ArithmeticalDSL.ih.
 {
   ASSERT( isInDSL(aPoint) );
   return ConstReverseIterator( end(aPoint) );
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::Integer DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::remainder (const Integer & aA, const Integer & aB, const Point & aPoint) inline static
Returns the remainder of aPoint with respect to the direction vector of components aA and aB
Parameters
aA y-component of the direction vector
aB x-component of the direction vector
aPoint any point
Returns
remainder of aPoint
Definition at line 262 of file ArithmeticalDSL.ih.
Referenced by DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::ArithmeticalDSL(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::ConstIterator::ConstIterator(), DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency >::createPattern(), and DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::remainder().
 {
   return aA * static_cast<Integer>(aPoint[0])
     - aB * static_cast<Integer>(aPoint[1]);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::Integer DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::remainder (const Point & aPoint) const inline
Returns the remainder of aPoint (which does not necessarily belong to the DSL)
Returns
remainder of aPoint
Parameters
aPoint any point
Definition at line 274 of file ArithmeticalDSL.ih.
References DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::remainder().
 {
   return DGtal::ArithmeticalDSL<TCoordinate, TInteger, adjacency>::remainder(myA, myB, aPoint);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::ConstReverseIterator DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::rend (const Point & aPoint) const inline
Parameters
aPoint any point of the DSL
Precondition
aPoint sould belongs to the DSL
Returns
end iterator, which points to the point located before aPoint
Definition at line 373 of file ArithmeticalDSL.ih.
 {
   ASSERT( isInDSL(aPoint) );
   return ConstReverseIterator( begin(aPoint) );
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> void DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 383 of file ArithmeticalDSL.ih.
 {
   out << "[ArithmeticalDSL] ";
   out << "(" << myA << "," << myB << "," << myLowerBound << "," << omega() << ")" << std::endl;
   out << "by steps " << mySteps.first << " " << mySteps.second << std::endl;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::Vector DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::shift () const inline
Returns
the shift vector (translating a point of remainder \(r \) to a point of remainder \(r+\omega \)).
Definition at line 244 of file ArithmeticalDSL.ih.
Referenced by DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency >::createPattern().
 {
   return myShift;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::Steps DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::steps () const inline
Returns
the two vectors used to iterate over the DSL points.
Definition at line 253 of file ArithmeticalDSL.ih.
Referenced by DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency >::createPattern().
 {
   return mySteps;
 }
Friends And Related Function Documentation
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> friend class ArithmeticalDSS< TCoordinate, TInteger, adjacency > friend
Definition at line 109 of file ArithmeticalDSL.h.
Field Documentation
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> const unsigned short DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::foregroundAdjacency = adjacency static
Adjacency of the DSL.
Definition at line 116 of file ArithmeticalDSL.h.
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> Coordinate DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::myA protected
y-component of the direction vector
Definition at line 535 of file ArithmeticalDSL.h.
Referenced by DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::equalsTo(), and DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::operator=().
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> Coordinate DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::myB protected
x-component of the direction vector
Definition at line 539 of file ArithmeticalDSL.h.
Referenced by DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::equalsTo(), and DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::operator=().
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> Integer DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::myLowerBound protected
Lower intercept. Invariants:
for any upper leaning point U, we have remainder(U) == myLowerBound.
myLowerBound <= myUpperBound
Definition at line 545 of file ArithmeticalDSL.h.
Referenced by DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::equalsTo(), and DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::operator=().
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> Vector DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::myShift protected
Shift vector. It is computed from myA and myB in ArithmeticalDSLKernel.
See Also
ArithmeticalDSLKernel::shift
Definition at line 529 of file ArithmeticalDSL.h.
Referenced by DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::ArithmeticalDSL(), and DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::operator=().
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> Steps DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::mySteps protected
Pair of steps used to iterate over the DSL points. They are computed from myA and myB in ArithmeticalDSLKernel.
See Also
ArithmeticalDSLKernel::steps
Definition at line 524 of file ArithmeticalDSL.h.
Referenced by DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::ConstIterator::ConstIterator(), and DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::operator=().
template<typename TCoordinate, typename TInteger = TCoordinate, unsigned short adjacency = 8> Integer DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::myUpperBound protected
Upper intercept. Invariants:
for any lower leaning point L, we have remainder(L) == myUpperBound.
if myA and myB are not both null, myUpperBound == myLowerBound + omega() - 1
myLowerBound <= myUpperBound
Definition at line 552 of file ArithmeticalDSL.h.
Referenced by DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::ArithmeticalDSL(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::equalsTo(), DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::ConstIterator::increment(), and DGtal::ArithmeticalDSL< TCoordinate, TInteger, adjacency >::operator=().
The documentation for this class was generated from the following files:
ArithmeticalDSL.h
ArithmeticalDSL.ih