DGtal: DGtal::FP< TIterator, TInteger, connectivity > Class Template Reference
DGtal::FP< TIterator, TInteger, connectivity > Class Template Reference
#include <FP.h>
Public Types
typedef DGtal::PointVector
< 2, TInteger > Point
typedef DGtal::PointVector
< 2, TInteger > Vector
typedef DGtal::PointVector
< 2, double > RealPoint
typedef DGtal::PointVector
< 2, double > RealVector
typedef
DGtal::ArithmeticalDSSComputer
< TIterator, TInteger,
connectivity > DSSComputer
typedef std::list< Point > Polygon
Public Member Functions
BOOST_CONCEPT_ASSERT ((CInteger< TInteger >))
FP (const TIterator &itb, const TIterator &ite) throw (InputException)
~FP ()
const Polygon & polygon () const
bool isClosed () const
bool isValid () const
Polygon::size_type size () const
template<typename OutputIterator >
OutputIterator copyFP (OutputIterator result) const
template<typename OutputIterator >
OutputIterator copyMLP (OutputIterator result) const
void selfDisplay (std::ostream &out) const
std::string className () const
Private Member Functions
template<typename Adapter >
Adapter * initConvexityConcavity (typename Adapter::DSS &aDSS)
template<typename Adapter >
bool removingStep (Adapter *adapter)
template<typename Adapter >
bool addingStep (Adapter *adapter, const typename Adapter::DSS::ConstIterator &itEnd)
template<typename Adapter >
void addingStep (Adapter *adapter)
void algorithm (const TIterator &itb, const TIterator &ite) throw (InputException)
void algorithm (const TIterator &itb, const TIterator &ite, IteratorType) throw (InputException)
void algorithm (const TIterator &itb, const TIterator &ite, CirculatorType) throw (InputException)
bool isValid (const Point &a, const Point &b, const Point &c) const
bool quadrant (const Vector &v, const int &q) const
RealPoint getRealPoint (const Point &a, const Point &b, const Point &c) const
FP (const FP &other)
FP & operator= (const FP &other)
Private Attributes
Polygon myPolygon
Detailed Description
template<typename TIterator, typename TInteger, int connectivity>
class DGtal::FP< TIterator, TInteger, connectivity >
Aim: Computes the faithful polygon (FP) of a range of 4/8-connected 2D Points.
The FP has several interesting properties:
its vertices are points of the underlying digital curve, thus with integer coordinates,
it respects the convex and concave parts of the underlying digital curve,
it is reversible,
it is unique for digital curves that are not digital straight segments,
it is closed to the minimum length polygon (MLP) (and converges toward the MLP as the resolution tends to the infinity) for closed digital curves.
It is computed in the course of the maximal digital straight segments computation, because in convex parts (resp. concave parts), the first and last upper (resp. lower) leaning points of segments that are maximal at the front or at the back are also vertices of the FP.
See Also
ArithmeticalDSSComputer DSSDecorator DSSDecorator4ConvexPart DSSDecorator4ConcavePart
Note
T. ROUSSILLON and I. SIVIGNON, Faithful polygonal representation of the convex and concave parts of a digital curve, Pattern Recognition, Volume 44, Issues 10-11, October-November 2011, Pages 2693-2700.
Usage:
//r is a range of 4-connected 2D points
FP<ConstIterator, Integer, 4> theFP(r .begin(), r.end());
*
Once the FP is computed, copyFP() is a way of geting its vertices. In the same way, copyMLP() is a way of getting the vertices of the MLP.
Template Parameters
TIterator type ConstIterator on 2D points,
TInteger (satisfying CInteger)
connectivity 4 for standard (4-connected) DSS or 8 for naive (8-connected) DSS. (Any other integers act as 8).
See Also
testFP.cpp
Definition at line 292 of file FP.h.
Member Typedef Documentation
template<typename TIterator, typename TInteger, int connectivity> typedef DGtal::ArithmeticalDSSComputer<TIterator,TInteger,connectivity> DGtal::FP< TIterator, TInteger, connectivity >::DSSComputer
Definition at line 307 of file FP.h.
template<typename TIterator, typename TInteger, int connectivity> typedef DGtal::PointVector<2,TInteger> DGtal::FP< TIterator, TInteger, connectivity >::Point
Definition at line 301 of file FP.h.
template<typename TIterator, typename TInteger, int connectivity> typedef std::list<Point> DGtal::FP< TIterator, TInteger, connectivity >::Polygon
Definition at line 309 of file FP.h.
template<typename TIterator, typename TInteger, int connectivity> typedef DGtal::PointVector<2, double> DGtal::FP< TIterator, TInteger, connectivity >::RealPoint
Definition at line 304 of file FP.h.
template<typename TIterator, typename TInteger, int connectivity> typedef DGtal::PointVector<2, double> DGtal::FP< TIterator, TInteger, connectivity >::RealVector
Definition at line 305 of file FP.h.
template<typename TIterator, typename TInteger, int connectivity> typedef DGtal::PointVector<2,TInteger> DGtal::FP< TIterator, TInteger, connectivity >::Vector
Definition at line 302 of file FP.h.
Constructor & Destructor Documentation
template<typename TIterator , typename TInteger , int connectivity> DGtal::FP< TIterator, TInteger, connectivity >::FP (const TIterator & itb, const TIterator & ite) throw (InputException) inline
Constructor.
Parameters
itb begin iterator
ite end iterator
Definition at line 44 of file FP.ih.
 {
   algorithm(itb, ite);
 }
template<typename TIterator , typename TInteger , int connectivity> DGtal::FP< TIterator, TInteger, connectivity >::~FP () inline
Destructor.
Definition at line 343 of file FP.ih.
 {
 }
template<typename TIterator, typename TInteger, int connectivity> DGtal::FP< TIterator, TInteger, connectivity >::FP (const FP< TIterator, TInteger, connectivity > & other) private
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
Member Function Documentation
template<typename TIterator , typename TInteger , int connectivity> template<typename Adapter > bool DGtal::FP< TIterator, TInteger, connectivity >::addingStep (Adapter * adapter, const typename Adapter::DSS::ConstIterator & itEnd) inline private
Adding step in the open case
Parameters
adapter an Adapter to the current DSS
itEnd end iterator used to stop the algorithm (when currentDSS.end() == itEnd)
Returns
'false' if the algorithm has to stop and 'true' otherwise
Template Parameters
Adapter type that adapts a DSS computer
See Also
details::DSSDecorator details::DSSDecorator4ConvexParts details::DSSDecorator4ConcaveParts
Definition at line 282 of file FP.ih.
 {
   //std::cerr << "Adding step " << currentDSS << std::endl;
   ASSERT( adapter->isExtendableFront() == true );
   //remove the last leaning point
   //if the first and last leaning points
   //of the current DSS are not confounded
   if (adapter->firstLeaningPoint() != adapter->lastLeaningPoint()) {
     ASSERT( myPolygon.size() > 0 );
     myPolygon.pop_back();
   }
   //adding step
   while ( (adapter->end() != itEnd)&&(adapter->extendFront()) ) {
     //store the first leaning point
     ASSERT( myPolygon.size() > 0 );
     if (adapter->firstLeaningPoint() != myPolygon.back()) {
       myPolygon.push_back(adapter->firstLeaningPoint());
     }
   }
   return (adapter->end() != itEnd);
 }
template<typename TIterator , typename TInteger , int connectivity> template<typename Adapter > void DGtal::FP< TIterator, TInteger, connectivity >::addingStep (Adapter * adapter) inline private
Adding step in the closed case
Parameters
adapter an Adapter to the current DSS
Template Parameters
Adapter type that adapts a DSS computer
See Also
details::DSSDecorator details::DSSDecorator4ConvexParts details::DSSDecorator4ConcaveParts
Definition at line 315 of file FP.ih.
 {
   //std::cerr << "Adding step " << currentDSS << std::endl;
   ASSERT( adapter->isExtendableFront() == true );
   //remove the last leaning point
   //if the first and last leaning points
   //of the current DSS are not confounded
   if (adapter->firstLeaningPoint() != adapter->lastLeaningPoint()) {
     ASSERT( myPolygon.size() > 0 );
     myPolygon.pop_back();
   }
   //adding step
   while ( adapter->extendFront() ) {
     //store the first leaning point
     ASSERT( myPolygon.size() > 0 );
     if (adapter->firstLeaningPoint() != myPolygon.back()) {
       myPolygon.push_back(adapter->firstLeaningPoint());
     }
   }
 }
template<typename TIterator , typename TInteger , int connectivity> void DGtal::FP< TIterator, TInteger, connectivity >::algorithm (const TIterator & itb, const TIterator & ite) throw (InputException) inline private
Main algorithm
Parameters
itb begin iterator
ite end iterator
Definition at line 54 of file FP.ih.
 {
   if (isNotEmpty(itb,ite))
     {
       typedef typename IteratorCirculatorTraits<TIterator>::Type Type;
       algorithm( itb, ite, Type() );
     }
 }
template<typename TIterator , typename TInteger , int connectivity> void DGtal::FP< TIterator, TInteger, connectivity >::algorithm (const TIterator & itb, const TIterator & ite, IteratorType) throw (InputException) inline private
Main algorithm overloading for classic iterator types (process as open)
Parameters
itb begin iterator
ite end iterator
Definition at line 68 of file FP.ih.
References DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::end(), DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::extendFront(), DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::init(), DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Lf(), DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::retractBack(), and DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Uf().
 {
   ASSERT(isNotEmpty(itb,ite));
   //list of successive upper (U) and lower (L)
   // leaning points.
   std::list<Point> vTmpU, vTmpL;
   vTmpU.push_back(*itb);
   vTmpL.push_back(*itb);
   //longest DSS
   DSSComputer longestDSS;
   longestDSS.init(itb);
   while ( (longestDSS.end() != ite)&&(longestDSS.extendFront()) )
     {
       //store the first upper leaning point
       if (longestDSS.Uf() != vTmpU.back()) {
         vTmpU.push_back(longestDSS.Uf());
       }
       //store the first lower leaning point
       if (longestDSS.Lf() != vTmpL.back()) {
         vTmpL.push_back(longestDSS.Lf());
       }
     }
   //std::cerr << "First MS" << std::endl << longestDSS << std::endl;
   typedef details::DSSDecorator<DSSComputer> DSSDecorator;
   DSSDecorator* adapter = 0; //adapter for the current DSS
   if (longestDSS.end() != ite)
     {
       //if the curve is not straight
       //it is either locally convex or concave at longestDSS.end()
       adapter = initConvexityConcavity<DSSDecorator>( longestDSS );
       ASSERT(adapter);
       if ( adapter->isInConvexPart() ) myPolygon = vTmpU;
       else myPolygon = vTmpL;
       ASSERT(myPolygon.size() > 0);
       bool go = true;
       while ( go )
         { //main loop
           if ( !removingStep( adapter ) )
             { //disconnected digital curve
               throw InputException();
             }
           go = addingStep( adapter, ite );
           if ( go )
             {
               delete (adapter);
               adapter = initConvexityConcavity<DSSDecorator>( longestDSS );
             }
         }
     }
   else
     {
       //the curve is assumed to be convex
       //if it is straight
       myPolygon = vTmpU;
       adapter = new details::DSSDecorator4ConvexPart<DSSComputer>(longestDSS);
       ASSERT(adapter);
     }
   //store the last leaning point
   //if the first and last leaning points
   //of the MS are not confounded
   if (adapter->firstLeaningPoint() != adapter->lastLeaningPoint()) {
     myPolygon.push_back(adapter->lastLeaningPoint());
   }
   //last removing step
   while ( longestDSS.retractBack() ) {
     //store the last leaning point
     if (adapter->lastLeaningPoint() != myPolygon.back()) {
       myPolygon.push_back(adapter->lastLeaningPoint());
     }
   }
   ASSERT(adapter);//had to be allocated
   delete (adapter);
 }
template<typename TIterator , typename TInteger , int connectivity> void DGtal::FP< TIterator, TInteger, connectivity >::algorithm (const TIterator & itb, const TIterator & ite, CirculatorType) throw (InputException) inline private
Main algorithm overloading for circular iterator types (process as closed)
Parameters
itb begin iterator
ite end iterator
Definition at line 160 of file FP.ih.
References DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::extendBack(), DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::extendFront(), and DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::init().
 {
   ASSERT(isNotEmpty(itb,ite));
   //first maximal DSS
   DSSComputer currentDSS;
   currentDSS.init( itb );
   //forward extension
   while ( currentDSS.extendFront() ) {}
   //backward extension
   while ( currentDSS.extendBack() ) {}
   //std::cerr << "First MS" << std::endl << currentDSS << std::endl;
   //local convexity
   typedef details::DSSDecorator<DSSComputer> DSSDecorator;
   DSSDecorator* adapter = 0; //adapter for the current DSS
   adapter = initConvexityConcavity<DSSDecorator>( currentDSS );
   //stopping point
   Point stoppingPoint = adapter->lastLeaningPoint();
   if (adapter->firstLeaningPoint() == stoppingPoint) {
     myPolygon.push_back( stoppingPoint );
   }//stored in removingStep function otherwise
   //since there are more than 2 MS (closed case)
   //but no more than 2 MS sharing a leaning point
   //at the same position
   if ( !removingStep( adapter ) )
     { //disconnected digital curve
       throw InputException();
     }
   addingStep( adapter );
   bool go = true;
   while ( go )
     { //main loop
       delete (adapter);
       adapter = initConvexityConcavity<DSSDecorator>( currentDSS );
       if ( !removingStep( adapter ) )
         { //disconnected digital curve
           throw InputException();
         }
       addingStep( adapter );
       if ( adapter->lastLeaningPoint() == stoppingPoint )
         { //stop and remove the last point to avoid a repetition
           if (adapter->firstLeaningPoint() == stoppingPoint) {
             ASSERT( myPolygon.size() > 0 );
             myPolygon.pop_back();
           }
           go = false;
         }
     }
   delete (adapter);
 }
template<typename TIterator, typename TInteger, int connectivity> DGtal::FP< TIterator, TInteger, connectivity >::BOOST_CONCEPT_ASSERT ((CInteger< TInteger >))
template<typename TIterator , typename TInteger , int connectivity> std::string DGtal::FP< TIterator, TInteger, connectivity >::className () const inline
Returns
the style name used for drawing this object.
Definition at line 599 of file FP.ih.
Referenced by DGtal::Display2DFactory::draw().
 {
   return "FP";
 }
template<typename TIterator , typename TInteger , int connectivity> template<typename OutputIterator > OutputIterator DGtal::FP< TIterator, TInteger, connectivity >::copyFP (OutputIterator result) const inline
Returns
the vertices of the FP NB: O(n)
Definition at line 463 of file FP.ih.
Referenced by DGtal::FPLengthEstimator< TConstIterator >::init().
{
   typename Polygon::const_iterator i = myPolygon.begin();
   while ( i != myPolygon.end() ) {
     *result++ = *i++;
   }
   return result;
 }
template<typename TIterator , typename TInteger , int connectivity> template<typename OutputIterator > OutputIterator DGtal::FP< TIterator, TInteger, connectivity >::copyMLP (OutputIterator result) const inline
Returns
the vertices of the MLP NB: O(n)
Definition at line 475 of file FP.ih.
Referenced by DGtal::MLPLengthEstimator< TConstIterator >::init().
{
   ASSERT( isValid() );
   unsigned int n = (unsigned int) myPolygon.size();
   if (n < 3) { //special case < 3 points
     typename Polygon::const_iterator i = myPolygon.begin();
     for ( ; i!= myPolygon.end() ; ++i) {
       *result++ = RealPoint( *i );
     }
   } else {    //standard case
     typename Polygon::const_iterator i, j, k;
     i = myPolygon.begin();
     j = i; ++j;
     k = j; ++k;
     if ( isClosed() ) {
       //first point
       *result++ = getRealPoint(myPolygon.back(),*i,*j);
       //middle points
       while ( k != myPolygon.end() ) {
         *result++ = getRealPoint(*i,*j,*k);
         ++i; ++j; ++k;
       }
       //last point
       *result++ = getRealPoint(*i,*j,myPolygon.front());
     } else {
       //first point
       *result++ = RealPoint( myPolygon.front() );
       //middle points
       while ( k != myPolygon.end() ) {
         *result++ = getRealPoint(*i,*j,*k);
         ++i; ++j; ++k;
       }
       //last point
       *result++ = RealPoint( myPolygon.back() );
     }
   }
   return result;
 }
template<typename TIterator , typename TInteger , int connectivity> DGtal::PointVector< 2, double > DGtal::FP< TIterator, TInteger, connectivity >::getRealPoint (const Point & a, const Point & b, const Point & c) const inline private
Gets a MLP vertex from three consecutive vertices of the FP.
Parameters
a previous vertex of the FP
b current vertex of the FP
c next vertex of the FP
Returns
vertex of the MLP, which is the tranlated of b by (+- 0.5, +- 0.5)
Definition at line 528 of file FP.ih.
{
   ASSERT( isValid() );
   RealVector shift;
   Vector e1 = b - a; //previous edge
   Vector e2 = c - b; //next edge
   if ( (e1[0]*e2[1]-e1[1]*e2[0]) <= 0 ) {
     //convex turn
     if ( (quadrant(e1,1))&&(quadrant(e2,1)) ) {
       shift = RealVector(0.5,-0.5);
     } else if ( (quadrant(e1,2))&&(quadrant(e2,2)) ) {
       shift = RealVector(-0.5,-0.5);
     } else if ( (quadrant(e1,3))&&(quadrant(e2,3)) ) {
       shift = RealVector(-0.5,0.5);
     } else if ( (quadrant(e1,4))&&(quadrant(e2,4)) ) {
       shift = RealVector(0.5,0.5);
     } else {
       ASSERT(false && "DGtal::FP<TIterator,TInteger,connectivity>::getRealPoint: not valid polygon" );
     }
   } else {
     //concave turn
     if ( (quadrant(e1,1))&&(quadrant(e2,1)) ) {
       shift = RealVector(-0.5,0.5);
     } else if ( (quadrant(e1,2))&&(quadrant(e2,2)) ) {
       shift = RealVector(0.5,0.5);
     } else if ( (quadrant(e1,3))&&(quadrant(e2,3)) ) {
       shift = RealVector(0.5,-0.5);
     } else if ( (quadrant(e1,4))&&(quadrant(e2,4)) ) {
       shift = RealVector(-0.5,-0.5);
     } else {
       ASSERT(false && "DGtal::FP<TIterator,TInteger,connectivity>::getRealPoint: not valid polygon" );
     }
   }
   return ( RealPoint(b) + shift );
 }
template<typename TIterator , typename TInteger , int connectivity> template<typename Adapter > Adapter * DGtal::FP< TIterator, TInteger, connectivity >::initConvexityConcavity (typename Adapter::DSS & aDSS) inline private
A DSS adapter is returned according to the local convexity/concavity
Parameters
aDSS a DSS lying on the range to process
Returns
an adapter to aDSS for convex or concave part
Template Parameters
Adapter type that adapts a DSS computer
See Also
details::DSSDecorator details::DSSDecorator4ConvexParts details::DSSDecorator4ConcaveParts
Definition at line 224 of file FP.ih.
 {
   ASSERT( aDSS.isExtendableFront() == false );
   if ( aDSS.remainder( aDSS.end() ) < (aDSS.mu()) )
     {      //concave part
       return new details
         ::DSSDecorator4ConcavePart<typename Adapter::DSS>(aDSS);
     }
   else
     {     //convex part
       return new details
         ::DSSDecorator4ConvexPart<typename Adapter::DSS>(aDSS);
     }
 }
template<typename TIterator , typename TInteger , int connectivity> bool DGtal::FP< TIterator, TInteger, connectivity >::isClosed () const inline
Returns
true if the list has to be consider as circular.
Definition at line 361 of file FP.ih.
Referenced by DGtal::Display2DFactory::drawAsPolygon().
 {
   //since the input digital curve has to be connected
   return IsCirculator<TIterator>::value;
 }
template<typename TIterator , typename TInteger , int connectivity> bool DGtal::FP< TIterator, TInteger, connectivity >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 393 of file FP.ih.
 {
   typedef typename Polygon::const_iterator I;
   //not two consecutive confounded points
   bool flag1 = true;
   I it = myPolygon.begin();
   if (it != myPolygon.end())
     {
       I itPrev = it; ++it;
       if (it != myPolygon.end())
         {
           while ( (it != myPolygon.end())&&(flag1) )
             {
               flag1 = (*itPrev != *it);
               itPrev = it;
               ++it;
             }
         }//if only one point ok
     }//if no point ok
   //valid quadrant for all consecutive pairs of edges
   bool flag2 = true;
   if (myPolygon.size() >= 3) {
     I  i, j, k;
     i = myPolygon.begin();
     j = i; ++j;
     k = j; ++k;
     if ( isClosed() ) {
       //first point
       flag2 = isValid(myPolygon.back(),*i,*j);
       //middle points
       while ( (k != myPolygon.end())&&(flag2) ) {
         flag2 = isValid(*i,*j,*k);
         ++i; ++j; ++k;
       }
       //last point
       if (flag2)
         flag2 = isValid(*i,*j,myPolygon.front());
     } else {
       //middle points
       while ( (k != myPolygon.end())&&(flag2) ) {
         flag2 = isValid(*i,*j,*k);
         ++i; ++j; ++k;
       }
     }
   }//special case of less than 3 points ok
   return flag1 && flag2;
 }
template<typename TIterator , typename TInteger , int connectivity> bool DGtal::FP< TIterator, TInteger, connectivity >::isValid (const Point & a, const Point & b, const Point & c) const inline private
Checks if a turn defined by three consecutive vertices of the FP is valid or not
Parameters
a previous vertex of the FP
b current vertex of the FP
c next vertex of the FP
Returns
'true' if valid, 'false' otherwise.
Definition at line 371 of file FP.ih.
{
   Vector e1 = b - a; //previous edge
   Vector e2 = c - b; //next edge
   if ( (quadrant(e1,1))&&(quadrant(e2,1)) ) {
     return true;
   } else if ( (quadrant(e1,2))&&(quadrant(e2,2)) ) {
     return true;
   } else if ( (quadrant(e1,3))&&(quadrant(e2,3)) ) {
     return true;
   } else if ( (quadrant(e1,4))&&(quadrant(e2,4)) ) {
     return true;
   } else {
     return false;
   }
 }
template<typename TIterator, typename TInteger, int connectivity> FP& DGtal::FP< TIterator, TInteger, connectivity >::operator= (const FP< TIterator, TInteger, connectivity > & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
template<typename TIterator , typename TInteger , int connectivity> const DGtal::FP< TIterator, TInteger, connectivity >::Polygon & DGtal::FP< TIterator, TInteger, connectivity >::polygon () const inline
Returns
the list where each vertex of the FP is stored.
Definition at line 353 of file FP.ih.
Referenced by DGtal::Display2DFactory::drawAsPolygon().
 {
   return myPolygon;
 }
template<typename TIterator , typename TInteger , int connectivity> bool DGtal::FP< TIterator, TInteger, connectivity >::quadrant (const Vector & v, const int & q) const inline private
Returns the quadrant number of a vector
Parameters
v any vector
q a quandrant number (0,1,2 or 3)
Returns
'true' if v lies in quadrant number q, 'false' otherwise
Definition at line 576 of file FP.ih.
{
   if (q == 1) {
     return ( (v[0]>=0)&&(v[1]>=0) );
   } else if (q == 2) {
     return ( (v[0]>=0)&&(v[1]<=0) );
   } else if (q == 3) {
     return ( (v[0]<=0)&&(v[1]<=0) );
   } else if (q == 4) {
     return ( (v[0]<=0)&&(v[1]>=0) );
   } else {
     ASSERT(false &&
            "DGtal::FP<TIterator,TInteger,connectivity>::quadrant: quadrant number should be 0,1,2 or 3"  );
     return false;
   }
 }
template<typename TIterator , typename TInteger , int connectivity> template<typename Adapter > bool DGtal::FP< TIterator, TInteger, connectivity >::removingStep (Adapter * adapter) inline private
Removing step
Parameters
adapter an Adapter to the current DSS
Returns
'false' if the underlying digital curve is detected as disconnected and 'true' otherwise
Template Parameters
Adapter type that adapts a DSS computer
See Also
details::DSSDecorator details::DSSDecorator4ConvexParts details::DSSDecorator4ConcaveParts
Definition at line 246 of file FP.ih.
 {
   //std::cerr << "Removing step " << currentDSS << std::endl;
   ASSERT( adapter->isExtendableFront() == false );
   //store the last leaning point
   //if the first and last leaning points
   //of the MS are not confounded
   if (adapter->firstLeaningPoint() != adapter->lastLeaningPoint()) {
     myPolygon.push_back(adapter->lastLeaningPoint());
   }
   //removing step
   while ( !adapter->isExtendableFront() ) {
     //remove a point from the back
     if ( adapter->retractBack() ) {
       //store the last leaning point
       ASSERT( myPolygon.size() > 0 );
       if (adapter->lastLeaningPoint() != myPolygon.back()) {
         myPolygon.push_back(adapter->lastLeaningPoint());
       }
     } else {
       return false;
     }
   }
   return true;
 }
template<typename TIterator , typename TInteger , int connectivity> void DGtal::FP< TIterator, TInteger, connectivity >::selfDisplay (std::ostream & out) const inline
Definition at line 608 of file FP.ih.
 {
   out << "[FP]" << std::endl;
   typename Polygon::const_iterator i = myPolygon.begin();
   for ( ;i != myPolygon.end();++i)
     {
       out << "\t " << (*i) << std::endl;
     }
   out << "[end FP]" << std::endl;
 }
template<typename TIterator , typename TInteger , int connectivity> DGtal::FP< TIterator, TInteger, connectivity >::Polygon::size_type DGtal::FP< TIterator, TInteger, connectivity >::size () const inline
Returns
number of FP vertices
Definition at line 453 of file FP.ih.
Referenced by DGtal::FPLengthEstimator< TConstIterator >::init(), and DGtal::MLPLengthEstimator< TConstIterator >::init().
 {
   return myPolygon.size();
 }
Field Documentation
template<typename TIterator, typename TInteger, int connectivity> Polygon DGtal::FP< TIterator, TInteger, connectivity >::myPolygon private
Definition at line 379 of file FP.h.
The documentation for this class was generated from the following files:
FP.h
FP.ih