DGtal: DGtal::PrincipalCurvatureFunctor3< Matrix3x3 > Class Template Reference
DGtal::PrincipalCurvatureFunctor3< Matrix3x3 > Class Template Reference
#include <IntegralInvariantGaussianCurvatureEstimator.h>
Public Types
typedef double Quantity
typedef EigenValues3D
< Quantity >::Vector3 Vector3
typedef CurvatureInformations Value
Public Member Functions
PrincipalCurvatureFunctor3 ()
void init (const double &h, const double &r)
Value operator() (const Matrix3x3 &aInput)
Protected Member Functions
void evalk1k2 (Matrix3x3 &matrix, Matrix3x3 &eigenVectors, Vector3 &eigenValues, Quantity &k1, Quantity &k2)
Private Attributes
Quantity dh5
Quantity d6_PIr6
Quantity d8_5r
Detailed Description
template<typename Matrix3x3>
class DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >
Definition at line 214 of file IntegralInvariantGaussianCurvatureEstimator.h.
Member Typedef Documentation
template<typename Matrix3x3 > typedef double DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::Quantity
Definition at line 217 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename Matrix3x3 > typedef CurvatureInformations DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::Value
Definition at line 219 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename Matrix3x3 > typedef EigenValues3D< Quantity >::Vector3 DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::Vector3
Definition at line 218 of file IntegralInvariantGaussianCurvatureEstimator.h.
Constructor & Destructor Documentation
template<typename Matrix3x3 > DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::PrincipalCurvatureFunctor3 () inline
Definition at line 221 of file IntegralInvariantGaussianCurvatureEstimator.h.
 {}
Member Function Documentation
template<typename Matrix3x3 > void DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::evalk1k2 (Matrix3x3 & matrix, Matrix3x3 & eigenVectors, Vector3 & eigenValues, Quantity & k1, Quantity & k2) inline protected
Definition at line 250 of file IntegralInvariantGaussianCurvatureEstimator.h.
References DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::d6_PIr6, DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::d8_5r, and DGtal::EigenValues3D< TQuantity >::getEigenDecomposition().
Referenced by DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::operator()().
   {
     EigenValues3D< Quantity >::getEigenDecomposition( matrix, eigenVectors, eigenValues );
     ASSERT ( eigenValues[ 0 ] == eigenValues[ 0 ] ); // NaN
     ASSERT ( (eigenValues[ 0 ] <= eigenValues[ 2 ]) && (eigenValues[ 0 ] <= eigenValues[ 1 ]) && (eigenValues[ 1 ] <= eigenValues[ 2 ]) );
     k1 = d6_PIr6 * ( eigenValues[ 1 ] - ( 3.0 * eigenValues[ 2 ] )) + d8_5r;
     k2 = d6_PIr6 * ( eigenValues[ 2 ] - ( 3.0 * eigenValues[ 1 ] )) + d8_5r;
   }
template<typename Matrix3x3 > void DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::init (const double & h, const double & r) inline
Definition at line 223 of file IntegralInvariantGaussianCurvatureEstimator.h.
References DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::d6_PIr6, DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::d8_5r, and DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::dh5.
   {
     double r3 = r * r * r;
     double r6 = r3 * r3;
     d6_PIr6 = 6.0 / ( M_PI * r6 );
     d8_5r = 8.0 / ( 5.0 * r );
     double h2 = h * h;
     dh5 = h2 * h2 * h;
   }
template<typename Matrix3x3 > Value DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::operator() (const Matrix3x3 & aInput) inline
Definition at line 233 of file IntegralInvariantGaussianCurvatureEstimator.h.
References DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::dh5, DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::evalk1k2(), DGtal::CurvatureInformations::k1, DGtal::CurvatureInformations::k2, DGtal::CurvatureInformations::values, and DGtal::CurvatureInformations::vectors.
   {
     Matrix3x3 cp_matrix = aInput;
     cp_matrix *= dh5;
     Quantity k1,k2;
     Matrix3x3 eigenVectors;
     Vector3 eigenValues;
     evalk1k2( cp_matrix, eigenVectors, eigenValues, k1, k2 );
     Value result;
     result.k1 = k1;
     result.k2 = k2;
     result.values = eigenValues;
     result.vectors = eigenVectors;
     return result;
   }
Field Documentation
template<typename Matrix3x3 > Quantity DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::d6_PIr6 private
h^5
Definition at line 268 of file IntegralInvariantGaussianCurvatureEstimator.h.
Referenced by DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::evalk1k2(), and DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::init().
template<typename Matrix3x3 > Quantity DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::d8_5r private
6/(PI*r^6)
Definition at line 269 of file IntegralInvariantGaussianCurvatureEstimator.h.
Referenced by DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::evalk1k2(), and DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::init().
template<typename Matrix3x3 > Quantity DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::dh5 private
Definition at line 267 of file IntegralInvariantGaussianCurvatureEstimator.h.
Referenced by DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::init(), and DGtal::PrincipalCurvatureFunctor3< Matrix3x3 >::operator()().
The documentation for this class was generated from the following file:
IntegralInvariantGaussianCurvatureEstimator.h