DGtal: DGtal::Board3D< Space, KSpace > Class Template Reference
DGtal::Board3D< Space, KSpace > Class Template Reference
#include <Board3D.h>
Public Member Functions
Board3D ()
Board3D (const KSpace &KSEmb)
Board3D (const Space &SEmb, const KSpace &KSEmb)
~Board3D ()
std::string className () const
void saveOBJ (const std::string &filename)
Board3D & operator<< (const DGtal::Color &aColor)
template<typename TDrawableWithDisplay3D >
Board3D & operator<< (const TDrawableWithDisplay3D &object)
void selfDisplay (std::ostream &out) const
bool isValid () const
template<typename TDrawableWithDisplay3D >
DGtal::Board3D< Space, KSpace > & operator<< (const TDrawableWithDisplay3D &object)
Public Member Functions inherited from DGtal::Display3D< Space, KSpace >
BOOST_CONCEPT_ASSERT ((CSpace< Space >))
~Display3D ()
Display3D ()
Display3D (const KSpace &KSEmb)
Display3D (const Space &Semb, const KSpace &KSEmb)
virtual void setFillColor (DGtal::Color aColor)
virtual void setFillTransparency (unsigned char alpha)
virtual void setLineColor (DGtal::Color aColor)
virtual DGtal::Color getFillColor ()
virtual DGtal::Color getLineColor ()
virtual void setSpaceEmbedder (CanonicEmbedder< Space > *anEmbedder)
virtual void setKSpaceEmbedder (CanonicCellEmbedder< KSpace > *anEmbedder)
virtual void setSKSpaceEmbedder (CanonicSCellEmbedder< KSpace > *anEmbedder)
void addClippingPlane (double a, double b, double c, double d, bool drawPlane)
std::string getMode (const std::string &objectName) const
void createNewLineList (std::string s="")
void createNewBallList (std::string s="")
void createNewCubeList (std::string s="")
void createNewQuadList (std::string s="")
void createNewTriangleList (std::string s="")
void createNewPolygonList (std::string s="")
void addQuad (const RealPoint &p1, const RealPoint &p2, const RealPoint &p3, const RealPoint &p4)
void addTriangle (const RealPoint &p1, const RealPoint &p2, const RealPoint &p3)
void addPolygon (const std::vector< RealPoint > &vertices)
void addLine (const RealPoint &p1, const RealPoint &p2, double width=0.03)
void addCube (const RealPoint &center, double width=1.0)
void addBall (const RealPoint &center, double size=0.05)
void addSurfelPrism (const RealPoint &baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel, double sizeShiftFactor, double sizeFactor=1.0, bool isSigned=false, bool aSign=true)
void addQuad (const RealPoint &baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel, double sizeShiftFactor, double sizeFactor=1.0, bool isSigned=false, bool aSign=true)
void addCone (const RealPoint &p1, const RealPoint &p2, double width=0.02)
void addCylinder (const RealPoint &p1, const RealPoint &p2, const double width=0.02)
void updateBoundingBox (const RealPoint &point)
void exportToMesh (Mesh< Display3D::BallD3D > &aMesh) const
template<typename TDrawableWithDisplay3D >
Display3D & operator<< (const TDrawableWithDisplay3D &object)
void selfDisplay (std::ostream &out) const
bool isValid () const
DGtal::CanonicEmbedder< Space >
::RealPoint embed (const typename Space::Point &dp) const
DGtal::CanonicSCellEmbedder
< KSpace >::RealPoint embedKS (const typename KSpace::SCell &cell) const
DGtal::CanonicSCellEmbedder
< KSpace >::RealPoint embedKS (const DGtal::TransformedSurfelPrism &aTrans) const
DGtal::CanonicCellEmbedder
< KSpace >::RealPoint embedK (const typename KSpace::Cell &cell) const
template<typename TDrawableWithDisplay3D >
DGtal::Display3D< Space,KSpace > & operator<< (const TDrawableWithDisplay3D &object)
Data Fields
DGtal::Color myDefaultColor
Data Fields inherited from DGtal::Display3D< Space, KSpace >
ModeMapping myModes
StyleMapping myStyles
bool myBoundingPtEmptyTag
double myBoundingPtUp [3]
double myBoundingPtLow [3]
Protected Member Functions
void init ()
Additional Inherited Members
Public Types inherited from DGtal::Display3D< Space, KSpace >
enum StreamKey { addNewList, updateDisplay, shiftSurfelVisu }
typedef DGtal::Z3i::RealPoint RealPoint
typedef std::map< std::string,
std::string > ModeMapping
typedef std::map< std::string,
CountedPtr
< DrawableWithDisplay3D > > StyleMapping
Static Protected Member Functions inherited from DGtal::Display3D< Space, KSpace >
static void cross (double dst[3], double srcA[3], double srcB[3])
static void normalize (double vec[3])
Protected Attributes inherited from DGtal::Display3D< Space, KSpace >
CanonicEmbedder< Space > * myEmbedder
CanonicCellEmbedder< KSpace > * myCellEmbedder
CanonicSCellEmbedder< KSpace > * mySCellEmbedder
DGtal::Color myCurrentFillColor
DGtal::Color myCurrentLineColor
double myCurrentfShiftVisuSurfelPrisms
std::vector< std::vector
< CubeD3D > > myCubeSetList
std::vector< std::vector
< LineD3D > > myLineSetList
std::vector< std::vector
< BallD3D > > myBallSetList
std::vector< ClippingPlaneD3D > myClippingPlaneList
std::vector< QuadD3D > mySurfelPrismList
std::vector< std::vector
< QuadD3D > > myQuadSetList
std::vector< std::vector
< TriangleD3D > > myTriangleSetList
std::vector< std::vector
< PolygonD3D > > myPolygonSetList
std::vector< std::string > myCubeSetNameList
std::vector< std::string > myLineSetNameList
std::vector< std::string > myBallSetNameList
std::vector< std::string > myClippingPlaneNameList
std::vector< std::string > mySurfelPrismNameList
std::vector< std::string > myQuadSetNameList
std::vector< std::string > myTriangleSetNameList
std::vector< std::string > myPolygonSetNameList
Detailed Description
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace>
class DGtal::Board3D< Space, KSpace >
The class Board3D is a type of Display3D which export the figures in the format OBJ/MTL when calling the method saveOBJ.
The format OBJ/MTL is a geometry definition file format, this format has been adopted by many 3D graphics application vendors (pbrt, blender, etc.). to learn more about OBJ see http://en.wikipedia.org/wiki/Wavefront_.obj_file
When exporting Board3D regroup objects by they list name. If two lists have the same name they will melt in the same mesh eventually. If a list doesn't have a name the program will try to give it an unique name so it will become a separate mesh. Each list have a material description which correspond to its first element color. If two lists have the same name and merge the final mesh will have two materials (one per list).
Template Parameters
Space a model of digital space (default type=Z3i::Space)
KSpace a model of Khalimsky space (default type=Z3i::KSpace)
Examples:
io/boards/dgtalBoard3D-1-points.cpp, io/boards/dgtalBoard3D-2-ks.cpp, and io/boards/dgtalBoard3D-6-clipping.cpp.
Definition at line 81 of file Board3D.h.
Constructor & Destructor Documentation
template<typename Space , typename KSpace > DGtal::Board3D< Space, KSpace >::Board3D () inline
Constructor.
Definition at line 90 of file Board3D.ih.
References DGtal::Board3D< Space, KSpace >::init().
                                      : Display3D<Space,KSpace>()
 {
   init();
 }
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> DGtal::Board3D< Space, KSpace >::Board3D (const KSpace & KSEmb) inline
Constructor with a khalimsky space
Parameters
KSEmb the Khalimsky space
Definition at line 95 of file Board3D.h.
References DGtal::Board3D< Space, KSpace >::init().
                                  :Display3D<Space,KSpace>(KSEmb)
     {
       init();
     }
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> DGtal::Board3D< Space, KSpace >::Board3D (const Space & SEmb, const KSpace & KSEmb) inline
Constructor with a space and a khalimsky space
Parameters
SEmb a space
KSEmb a khalimsky space
Definition at line 105 of file Board3D.h.
References DGtal::Board3D< Space, KSpace >::init().
                                                     :Display3D<Space,KSpace>(SEmb,
                                                                              KSEmb)
     {
       init();
     }
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> DGtal::Board3D< Space, KSpace >::~Board3D () inline
Destructor.
Definition at line 115 of file Board3D.h.
 {};
Member Function Documentation
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> std::string DGtal::Board3D< Space, KSpace >::className () const inline
Returns
the style name used for drawing this object.
Definition at line 120 of file Board3D.h.
     {
       return "Board3D";
     }
template<typename Space , typename KSpace > void DGtal::Board3D< Space, KSpace >::init () inline protected
init function (should be in Constructor).
init function (should be in Constructor).
Definition at line 676 of file Board3D.ih.
References DGtal::Display3D< Space, KSpace >::createNewBallList(), DGtal::Display3D< Space, KSpace >::createNewCubeList(), and DGtal::Display3D< Space, KSpace >::createNewLineList().
Referenced by DGtal::Board3D< Space, KSpace >::Board3D().
 {
   Board3D<Space, KSpace>::createNewCubeList();
   Board3D<Space, KSpace>::createNewLineList();
   Board3D<Space, KSpace>::createNewBallList();
   Board3D<Space, KSpace>::myCurrentFillColor = DGtal::Color (220, 220, 220);
   Board3D<Space, KSpace>::myCurrentLineColor = DGtal::Color (22, 22, 222, 50);
   Board3D<Space, KSpace>::myDefaultColor= DGtal::Color(255, 255, 255);
   Board3D<Space, KSpace>::myModes["Board3D"]="SolidMode";
   std::string nameLineSet;
   Board3D<Space, KSpace>::myLineSetNameList.push_back(nameLineSet);
   std::string nameBallSet;
   Board3D<Space, KSpace>::myBallSetNameList.push_back(nameBallSet);
   std::string nameQuad;
   Board3D<Space, KSpace>::myQuadSetNameList.push_back(nameQuad);
   std::string nameTriangle;
   Board3D<Space, KSpace>::myTriangleSetNameList.push_back(nameTriangle);
   std::string namePolygon;
   Board3D<Space, KSpace>::myPolygonSetNameList.push_back(namePolygon);
 }
template<typename Space , typename KSpace > bool DGtal::Board3D< Space, KSpace >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 116 of file Board3D.ih.
 {
   return true;
 }
template<typename Space , typename KSpace > DGtal::Board3D< Space, KSpace > & DGtal::Board3D< Space, KSpace >::operator<< (const DGtal::Color & aColor) inline
Set the default color for future drawing.
Parameters
aColor a DGtal::Color (allow to set a trasnparency value).
Set the default color for future drawing.
Parameters
aColor,: a DGtal::Color (allow to set a trasnparency value).
Definition at line 53 of file Board3D.ih.
 {
   myDefaultColor=aColor;
   return *this;
 }
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> template<typename TDrawableWithDisplay3D > Board3D& DGtal::Board3D< Space, KSpace >::operator<< (const TDrawableWithDisplay3D & object)
Draws the drawable [object] in this board. It should satisfy the concept CDrawableWithDisplay3D, which requires for instance a method setStyle(Board3D &).
Parameters
object any drawable object.
Returns
a reference on 'this'.
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> template<typename TDrawableWithDisplay3D > DGtal::Board3D<Space, KSpace>& DGtal::Board3D< Space, KSpace >::operator<< (const TDrawableWithDisplay3D & object) inline
Draws the drawable [object] in this board. It should satisfy the concept CDrawableWithBoard3D, which requires for instance a method setStyle(Board3D &).
Parameters
object any drawable object.
Returns
a reference on 'this'.
Definition at line 72 of file Board3D.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   BOOST_CONCEPT_ASSERT((CDrawableWithDisplay3D< TDrawableWithDisplay3D, Space, KSpace>));
   DGtal::Display3DFactory<Space,KSpace>::draw(*this, object);
   return *this;
 }
template<typename Space , typename KSpace > void DGtal::Board3D< Space, KSpace >::saveOBJ (const std::string & filename) inline
Save a OBJ image.
Parameters
filename filename of the image to save.
Definition at line 128 of file Board3D.ih.
References DGtal::Trace::info(), and DGtal::trace.
 {
   size_t k, j; //id of each elements and sub elements of a list for the .OBJ identification
   double Re, Gr, Bl, Tr; // colors of the elements
   double sizePixel = 0.003 ;  // size of one pixel (depending on resolution )
   std::ofstream outOBJ; //OBJ file where to write
   std::ofstream outMTL; //MTL file where to write
   std::stringstream bufMTL; // Buffering what to write in the MTL file
   //WARNING quand deux obj ont le meme nom ils fusionnent (danger deux sets differents fusionnes)
   std::string noExt(filename.substr(0, filename.find_first_of("."))); //the filename withoutOBJ any extention
   std::stringstream nameOBJ;
   std::stringstream nameMTL;
   nameOBJ << noExt << ".obj";
   nameMTL << noExt << ".mtl";
   outOBJ.open(nameOBJ.str().c_str());
   outOBJ << "#  OBJ format"<< std::endl;
   outOBJ << "# generated from Board3D from the DGTal library"<< std::endl;
   outOBJ << "mtllib " <<  nameMTL.str() << std::endl;
   outOBJ << std::endl;
   outMTL.open(nameMTL.str().c_str());
   outMTL << "#  MTL format"<< std::endl;
   outMTL << "# generated from Board3D from the DGTal library"<< std::endl;
   //OPT head
   // TODOLP tests unitaires pour chaque partie
   //myClippingPlaneList++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   //std::vector< clippingPlaneD3D >::const_iterator
   {
     if(Board3D<Space, KSpace>::myClippingPlaneList.size()> 0)
       {
         trace.info() << "number of clipping plane : "
                      << Board3D<Space, KSpace>::myClippingPlaneList.size() << std::endl;
       }
   }
   // Draw the shapes -----------------------------------------------------------------------
   // myBallSetList++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   {
     k=0;//id of each BallSetList for the .OBJ identification
     for ( typename std::vector< std::vector< typename Board3D<Space, KSpace>::BallD3D> >::const_iterator it = Board3D<Space, KSpace>::myBallSetList.begin();
           it != Board3D<Space, KSpace>::myBallSetList.end(); it++)
       {
         std::ostringstream tmpStream; // checking that points exist before creating an object
         for (typename std::vector<  typename Board3D<Space, KSpace>::BallD3D>::const_iterator s_it = it->begin();
              s_it != it->end(); s_it++)
           {
             //test if a clipping plane do not cut it
             bool notCut =true;
             typename std::vector< typename Board3D<Space, KSpace>::ClippingPlaneD3D>::const_iterator itClip = Board3D<Space, KSpace>::myClippingPlaneList.begin();
             while (itClip !=Board3D<Space, KSpace>::myClippingPlaneList.end() && notCut )
               {
                 double d2 = ( itClip->a * (*s_it)[0]) + (itClip->b * (*s_it)[1]) + ( itClip->c * (*s_it)[2] ) + itClip->d;
                 notCut = ( d2 >= 0);
                 itClip ++;
               }
             if (notCut)
               {
                 tmpStream << "v " << (*s_it)[0] << " " << (*s_it)[1] << " " << (*s_it)[2] << std::endl;
                 tmpStream << "f " << "-1" << " " << "-1" << " "<< "-1" << std::endl;
               }
           }
         if (tmpStream.str().size() > 0)
           {
             std::stringstream name;
             name << Board3D<Space, KSpace>::myBallSetNameList.at(k);
             if ( name.str() == "")
               {
                 name << "myBallSetList_" << k ;
               }
             //NOTE up until now one object = one material
             std::stringstream matName;
             matName << "myBallSetList_" << k << "MAT";
             outOBJ << "o  " << name.str() << std::endl;
             outOBJ << "usemtl " << matName.str() << std::endl;
             outOBJ << tmpStream.str();
             typename std::vector< typename Board3D<Space, KSpace>::BallD3D>::const_iterator itBegin = it->begin();
             Re = itBegin->color.red() /255.0 ;
             Gr = itBegin->color.green() /255.0;
             Bl = itBegin->color.blue() /255.0;
             Tr = itBegin->color.alpha() /255.0;
             bufMTL << "newmtl " << matName.str()  <<std::endl;
             bufMTL << "Ka " << Re << " " << Gr << " " << Bl << std::endl;
             bufMTL << "Kd " << Re << " " << Gr << " " << Bl << std::endl;
             bufMTL << "Ks 0 0 0" << std::endl;
             bufMTL << "d " << Tr << std::endl;
             bufMTL << "illum 2" << std::endl << std::endl;
           }
         k++;
       }
   }
   // myLineSetList+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   {
     j =0;
     k=0;//id of each LineSetList for the .OBJ identification
     for(typename std::vector<std::vector< typename Board3D<Space, KSpace>::LineD3D> >::const_iterator it =Board3D<Space, KSpace>::myLineSetList.begin();
         it!= Board3D<Space, KSpace>::myLineSetList.end();   it++)
       {
         std::ostringstream tmpStream;
         for (typename std::vector< typename Board3D<Space, KSpace>::LineD3D>::const_iterator s_it = it->begin();
              s_it != it->end();++s_it)
           {
             //test if a clipping plane do not cut it
             bool notCut =true;
             typename std::vector< typename Board3D<Space, KSpace>::ClippingPlaneD3D>::const_iterator itClip = Board3D<Space, KSpace>::myClippingPlaneList.begin();
             while (itClip !=Board3D<Space, KSpace>::myClippingPlaneList.end() && notCut )
               {
                 double a = itClip->a;
                 double b = itClip->b;
                 double c = itClip->c;
                 double d = itClip->d;
                 double d2 ;
                 d2 = ( a * s_it->point1[0]) + (b * (s_it->point1[1] -sizePixel)) + ( c * s_it->point1[2] ) + d;
                 notCut = ( d2 >= 0);
                 d2 = ( a * s_it->point1[0]) + (b * (s_it->point1[1] +sizePixel)) + ( c * s_it->point1[2] ) + d;
                 notCut = ( notCut  && ( d2 >= 0) );
                 d2 = ( a * s_it->point2[0]) + (b * (s_it->point2[1] +sizePixel)) + ( c * s_it->point2[2] ) + d;
                 notCut = ( notCut  && ( d2 >= 0) );
                 d2 = ( a * s_it->point2[0]) + (b * (s_it->point2[1] -sizePixel)) + ( c * s_it->point2[2] ) + d;
                 notCut = ( notCut  && ( d2 >= 0) );
                 d2 = ( a * s_it->point1[0]) + (b * s_it->point1[1]) + ( c * (s_it->point1[2] -sizePixel )) + d;
                 notCut = ( notCut  && ( d2 >= 0) );
                 d2 = ( a * s_it->point1[0]) + (b * s_it->point1[1]) + ( c * (s_it->point1[2] +sizePixel )) + d;
                 notCut = ( notCut  && ( d2 >= 0) );
                 d2 = ( a * s_it->point2[0]) + (b * s_it->point2[1]) + ( c * (s_it->point2[2] +sizePixel )) + d;
                 notCut = ( notCut  && ( d2 >= 0) );
                 d2 = ( a * s_it->point2[0]) + (b * s_it->point2[1]) + ( c * (s_it->point2[2] -sizePixel )) + d;
                 notCut = ( notCut  && ( d2 >= 0) );
                 itClip ++;
               }
             if (notCut)
               {
                 // OBJ dont know how to draw lines, have to make a cuboid with a depth and height of a pixel width
                 tmpStream << "v " << s_it->point1[0]     << " " << s_it->point1[1] -sizePixel << " " << s_it->point1[2] << std::endl;
                 tmpStream << "v " << s_it->point1[0]     << " " << s_it->point1[1] +sizePixel << " " << s_it->point1[2] << std::endl;
                 tmpStream << "v " << s_it->point2[0]     << " " << s_it->point2[1] +sizePixel << " " << s_it->point2[2] << std::endl;
                 tmpStream << "v " << s_it->point2[0]     << " " << s_it->point2[1] -sizePixel << " " << s_it->point2[2] << std::endl;
                 tmpStream << "v " << s_it->point1[0]     << " " << s_it->point1[1]     << " " << s_it->point1[2] -sizePixel << std::endl;
                 tmpStream << "v " << s_it->point1[0]     << " " << s_it->point1[1]     << " " << s_it->point1[2] +sizePixel<< std::endl;
                 tmpStream << "v " << s_it->point2[0]     << " " << s_it->point2[1]     << " " << s_it->point2[2] +sizePixel<< std::endl;
                 tmpStream << "v " << s_it->point2[0]     << " " << s_it->point2[1]     << " " << s_it->point2[2] -sizePixel<< std::endl;
                 tmpStream  << "vn " <<  "-1"  << " " << "0" << " " << "0" << std::endl;//left
                 tmpStream  << "vn " <<  "0"  << " " << "0" << " " << "-1" << std::endl;//front
                 tmpStream  << "vn " <<  "0"  << " " << "1" << " " << "0" << std::endl;//up
                 tmpStream  << "vn " <<  "0"  << " " << "0" << " " << "1" << std::endl;//back
                 tmpStream  << "vn " <<  "0"  << " " << "-1" << " " << "0" << std::endl;//down
                 tmpStream  << "vn " <<  "1"  << " " << "0" << " " << "0" << std::endl;//right
                 tmpStream << "f " << "-8//-6" << " " << "-7//-6" << " " << "-5//-6"<< " " << "-6//-6" << std::endl;//left
                 tmpStream << "f " << "-8//-5" << " " << "-6//-5" << " " << "-2//-5"<< " " << "-4//-5"<< std::endl;//front
                 tmpStream << "f " << "-8//-4" << " " << "-7//-4" << " " << "-3//-4"<< " " << "-4//-4"<< std::endl;//up
                 tmpStream << "f " << "-7//-3" << " " << "-5//-3" << " " << "-1//-3"<< " " << "-3//-3"<< std::endl;//back
                 tmpStream << "f " << "-6//-2" << " " << "-5//-2" << " " << "-1//-2"<< " " << "-2//-2"<< std::endl;//down
                 tmpStream << "f " << "-4//-1" << " " << "-3//-1" << " " << "-1//-1"<< " " << "-2//-1"<< std::endl;//right
                 j++;
               }
           }
         if (tmpStream.str() != "")
           {
             std::stringstream name;
             name << Board3D<Space, KSpace>::myLineSetNameList.at(k);
             if ( name.str()== "")
               {
                 name << "myLineSetList_" << k ;
               }
             std::stringstream matName;
             matName << "myLineSetList_" << k  << "MAT";
             outOBJ << "o " << name.str() << std::endl;
             outOBJ << "usemtl " << matName.str() << std::endl;
             outOBJ << tmpStream.str();
             typename std::vector< typename Board3D<Space, KSpace>::LineD3D>::const_iterator itBegin = it->begin();
             Re = itBegin->color.red() /255.0 ;
             Gr = itBegin->color.green() /255.0;
             Bl = itBegin->color.blue() /255.0;
             Tr = itBegin->color.alpha() /255.0;
             bufMTL << "newmtl " << matName.str()  <<std::endl;
             bufMTL << "Ka " << Re << " " << Gr << " " << Bl << std::endl;
             bufMTL << "Kd " << Re << " " << Gr << " " << Bl << std::endl;
             bufMTL << "Ks 0 0 0" << std::endl;
             bufMTL << "d " << Tr << std::endl;
             bufMTL << "illum 2" << std::endl << std::endl;
           }
         k++;
       }
   }
   // myCubeSetList++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   {
     j  = 0 ; //id of each Cube sub list for the .OBJ identification
     k = 0; // id of each list
     for(typename std::vector<std::vector< typename Board3D<Space, KSpace>::CubeD3D> >::const_iterator it =Board3D<Space, KSpace>::myCubeSetList.begin();
         it != Board3D<Space, KSpace>::myCubeSetList.end();   it++)
       {
         std::ostringstream tmpStream;
         for (typename std::vector< typename Board3D<Space, KSpace>::CubeD3D>::const_iterator s_it = it->begin();
              s_it != it->end(); ++s_it)
           {
             double wid = s_it->width;
             double x = s_it->center[0];
             double y = s_it->center[1];
             double z = s_it->center[2];
             double x1 = x - wid;
             double x2 = x + wid;
             double y1 = y - wid;
             double y2 = y + wid;
             double z1 = z - wid;
             double z2 = z + wid;
             //test if a clipping plane do not cut it
             bool notCut =true;
             typename std::vector< typename Board3D<Space, KSpace>::ClippingPlaneD3D>::const_iterator itClip = Board3D<Space, KSpace>::myClippingPlaneList.begin();
             while (itClip !=Board3D<Space, KSpace>::myClippingPlaneList.end() && notCut )
               {
                 double a = itClip->a;
                 double b = itClip->b;
                 double c = itClip->c;
                 double d = itClip->d;
                 double d2 = ( a * x1) + (b * y1) + ( c * z2 ) + d;
                 notCut = ( d2 >= 0);
                 d2 = ( a * x2) + (b * y1) + ( c * z2) + d;
                 notCut = ( notCut  && ( d2 >= 0) );
                 d2 = ( a * x1) + (b * y1) + ( c * z1) + d;
                 notCut = ( notCut  && ( d2 >= 0) );
                 d2 = ( a * x2) + (b * y1) + ( c * z1) + d;
                 notCut = ( notCut  && ( d2 >= 0) );
                 d2 = ( a * x1) + (b * y2) + ( c * z2) + d;
                 notCut = ( notCut  && ( d2 >= 0) );
                 d2 = ( a * x2) + (b * y2) + ( c * z2) + d;
                 notCut = ( notCut  && ( d2 >= 0) );
                 d2 = ( a * x1) + (b * y2) + ( c * z1) + d;
                 notCut = ( notCut  && ( d2 >= 0) );
                 d2 = ( a * x2) + (b * y2) + ( c * z1) + d;
                 notCut = ( notCut  && ( d2 >= 0) );
                 itClip ++;
               }
             //OPT cube
             if (notCut)
               {
                 // this version is  one cube with (x,y,z) the center of it and wid its distance between it and its faces
                 tmpStream  << "v " << x1   << " " << y1 << " " << z2 << std::endl;
                 tmpStream  << "v " << x2   << " " << y1 << " " << z2 << std::endl;
                 tmpStream  << "v " << x1   << " " << y1 << " " << z1 << std::endl;
                 tmpStream  << "v " << x2   << " " << y1 << " " << z1 << std::endl;
                 tmpStream  << "v " << x1   << " " << y2 << " " << z2 << std::endl;
                 tmpStream  << "v " << x2   << " " << y2 << " " << z2 << std::endl;
                 tmpStream  << "v " << x1   << " " << y2 << " " << z1 << std::endl;
                 tmpStream  << "v " << x2   << " " << y2 << " " << z1 << std::endl;
                 tmpStream  << "vn " <<  "-1"  << " " << "0" << " " << "0" << std::endl;//left
                 tmpStream  << "vn " <<  "0"  << " " << "0" << " " << "-1" << std::endl;//front
                 tmpStream  << "vn " <<  "0"  << " " << "1" << " " << "0" << std::endl;//up
                 tmpStream  << "vn " <<  "0"  << " " << "0" << " " << "1" << std::endl;//back
                 tmpStream  << "vn " <<  "0"  << " " << "-1" << " " << "0" << std::endl;//down
                 tmpStream  << "vn " <<  "1"  << " " << "0" << " " << "0" << std::endl;//right
                 tmpStream << "f " << "-8//-6" << " " << "-7//-6" << " " << "-5//-6"<< " " << "-6//-6" << std::endl;//left
                 tmpStream << "f " << "-8//-5" << " " << "-6//-5" << " " << "-2//-5"<< " " << "-4//-5"<< std::endl;//front
                 tmpStream << "f " << "-8//-4" << " " << "-7//-4" << " " << "-3//-4"<< " " << "-4//-4"<< std::endl;//up
                 tmpStream << "f " << "-7//-3" << " " << "-5//-3" << " " << "-1//-3"<< " " << "-3//-3"<< std::endl;//back
                 tmpStream << "f " << "-6//-2" << " " << "-5//-2" << " " << "-1//-2"<< " " << "-2//-2"<< std::endl;//down
                 tmpStream << "f " << "-4//-1" << " " << "-3//-1" << " " << "-1//-1"<< " " << "-2//-1"<< std::endl;//right
                 j ++;
               }
           }
         if (tmpStream.str() != "")
           {
             std::stringstream name;
             name << Board3D<Space, KSpace>::myCubeSetNameList.at(k);
             if ( name.str() == "")
               {
                 name << "myCubeSetList_" << k ;
               }
             std::stringstream matName;
             matName << "myCubeSetList_" << k << "MAT";
             outOBJ << "o  " << name.str() << std::endl;
             outOBJ << "usemtl " << matName.str() << std::endl;
             outOBJ << tmpStream.str();
             typename std::vector< typename Board3D<Space, KSpace>::CubeD3D>::const_iterator itBegin = it->begin();
             Re = itBegin->color.red() /255.0 ;
             Gr = itBegin->color.green() /255.0;
             Bl = itBegin->color.blue() /255.0;
             Tr = itBegin->color.alpha()/255.0;
             bufMTL << "newmtl " << matName.str()  <<std::endl;
             bufMTL << "Ka " << Re << " " << Gr << " " << Bl << std::endl;
             bufMTL << "Kd " << Re << " " << Gr << " " << Bl << std::endl;
             bufMTL << "Ks 0 0 0" << std::endl;
             bufMTL << "d " << Tr << std::endl;
             bufMTL << "illum 2" << std::endl << std::endl;
           }
         k++;
       }
   }
   //OPT quad
   // myQuadList++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   {
     //std::vector<quadD3D>::const_iterator
     k = 0; // id of each list
     for(typename std::vector<std::vector< typename Board3D<Space, KSpace>::QuadD3D> >::const_iterator it =Board3D<Space, KSpace>::myQuadSetList.begin();
         it != Board3D<Space, KSpace>::myQuadSetList.end();   it++)
       {
         std::ostringstream tmpStream;
         for (typename std::vector< typename Board3D<Space, KSpace>::QuadD3D>::const_iterator s_it = it->begin();
              s_it != it->end(); ++s_it)
           {
             //test if a clipping plane do not cut it
             tmpStream << "v " << s_it->point1[0]     << " " << s_it->point1[1]      << " " << s_it->point1[2] << std::endl;
             tmpStream << "v " << s_it->point2[0]     << " " << s_it->point2[1]      << " " << s_it->point2[2] << std::endl;
             tmpStream << "v " << s_it->point3[0]     << " " << s_it->point3[1]      << " " << s_it->point3[2] << std::endl;
             tmpStream << "v " << s_it->point4[0]     << " " << s_it->point4[1]      << " " << s_it->point4[2] << std::endl;
             tmpStream << "f " << "-4" << " " << "-3" << " " << "-2"<< " " << "-1"<< std::endl;
           }
         if (tmpStream.str() != "")
           {
             std::stringstream name;
             name << Board3D<Space, KSpace>::myCubeSetNameList.at(k);
             if ( name.str() == "")
               {
                 name << "myQuadSetList_" << k ;
               }
             std::stringstream matName;
             matName << "myQuadSetList_" << k  << "MAT";
             outOBJ << "o  " << name.str() << std::endl;
             outOBJ << "usemtl " << matName.str() << std::endl;
             outOBJ << tmpStream.str();
             typename std::vector< typename Board3D<Space, KSpace>::QuadD3D>::const_iterator itBegin = it->begin();
             Re = itBegin->color.red() /255.0 ;
             Gr = itBegin->color.green() /255.0;
             Bl = itBegin->color.blue() /255.0;
             Tr = itBegin->color.alpha() /255.0;
             bufMTL << "newmtl " << matName.str()  <<std::endl;
             bufMTL << "Ka " << Re << " " << Gr << " " << Bl << std::endl;
             bufMTL << "Kd " << Re << " " << Gr << " " << Bl << std::endl;
             bufMTL << "Ks 0 0 0" << std::endl;
             bufMTL << "d " << Tr << std::endl;
             bufMTL << "illum 2" << std::endl << std::endl;
           }
       }
   }
   //OPT triangle
   // myTriangleList++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   {
     //std::vector<triangleD3D>::const_iterator
     k = 0; // id of each list
     for(typename std::vector<std::vector< typename Board3D<Space, KSpace>::TriangleD3D> >::const_iterator it =Board3D<Space, KSpace>::myTriangleSetList.begin();
         it != Board3D<Space, KSpace>::myTriangleSetList.end();   it++)
       {
         std::ostringstream tmpStream;
         for (typename std::vector< typename Board3D<Space, KSpace>::TriangleD3D>::const_iterator s_it = it->begin();
              s_it != it->end(); ++s_it)
           {
             //test if a clipping plane do not cut it
             bool notCut =true;
             typename std::vector< typename Board3D<Space, KSpace>::ClippingPlaneD3D>::const_iterator itClip =
               Board3D<Space, KSpace>::myClippingPlaneList.begin();
             while (itClip !=Board3D<Space, KSpace>::myClippingPlaneList.end() && notCut )
               {
                 double a = itClip->a;
                 double b = itClip->b;
                 double c = itClip->c;
                 double d = itClip->d;
                 double d2 = ( a * s_it->point1[0]) + (b * s_it->point1[1]) + ( c * s_it->point1[2] ) + d;
                 notCut = ( d2 >= 0);
                 d2 = ( a * s_it->point2[0]) + (b * s_it->point2[1]) + ( c * s_it->point2[2]) + d;
                 notCut = ( notCut  && ( d2 >= 0) );
                 d2 = ( a * s_it->point3[0]) + (b * s_it->point3[1]) + ( c * s_it->point3[2]) + d;
                 notCut = ( notCut  && ( d2 >= 0) );
                 itClip ++;
               }
             if (notCut)
               {
                 tmpStream << "v " << s_it->point1[0]     << " " << s_it->point1[1]      << " " << s_it->point1[2] << std::endl;
                 tmpStream << "v " << s_it->point2[0]     << " " << s_it->point2[1]      << " " << s_it->point2[2] << std::endl;
                 tmpStream << "v " << s_it->point3[0]     << " " << s_it->point3[1]      << " " << s_it->point3[2] << std::endl;
                 tmpStream << "vn " << s_it->nx    << " " << s_it->ny     << " " << s_it->nz << std::endl;
                 tmpStream << "f " << "-3//-1" << " " << "-2//-1"<< " " << "-1//-1"<< std::endl;
               }
           }
         if (tmpStream.str() != "")
           {
             std::stringstream name;
             name << Board3D<Space, KSpace>::myTriangleSetNameList.at(k);
             if ( name.str() == "")
               {
                 name << "myTriangleSetList_" << k ;
               }
             std::stringstream matName;
             matName << "myTriangleSetList_" << k << "MAT";
             outOBJ << "o  " << name.str() << std::endl;
             outOBJ << "usemtl " << matName.str() << std::endl;
             outOBJ << tmpStream.str();
             typename std::vector< typename Board3D<Space, KSpace>::TriangleD3D>::const_iterator itBegin = it->begin();
             Re = itBegin->color.red() /255.0 ;
             Gr = itBegin->color.green() /255.0;
             Bl = itBegin->color.blue() /255.0;
             Tr = itBegin->color.alpha() /255.0;
             bufMTL << "newmtl " << matName.str()  <<std::endl;
             bufMTL << "Ka " << Re << " " << Gr << " " << Bl << std::endl;
             bufMTL << "Kd " << Re << " " << Gr << " " << Bl << std::endl;
             bufMTL << "Ks 0 0 0" << std::endl;
             bufMTL << "d " << Tr << std::endl;
             bufMTL << "illum 2" << std::endl << std::endl;
           }
       }
   }
   //OPT scell
   // Drawing all Khalimsky Space Cells --------------------------------------------------------------------
   // SurfelPrism (from updateList)+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   {
     j=0;
     k=0;
     std::ostringstream tmpStream;
     for (typename std::vector< typename Board3D<Space, KSpace>::QuadD3D>::iterator s_it = Board3D<Space, KSpace>::mySurfelPrismList.begin();
          s_it != Board3D<Space, KSpace>::mySurfelPrismList.end();
          ++s_it)
       {
         //test if a clipping plane do not cut it
         bool notCut =true;
         typename std::vector< typename Board3D<Space, KSpace>::ClippingPlaneD3D>::const_iterator itClip = Board3D<Space, KSpace>::myClippingPlaneList.begin();
         while (itClip !=Board3D<Space, KSpace>::myClippingPlaneList.end() && notCut )
           {
             double a = itClip->a;
             double b = itClip->b;
             double c = itClip->c;
             double d = itClip->d;
             double d2 = ( a * s_it->point1[0]) + (b * s_it->point1[1]) + ( c * s_it->point1[2] ) + d;
             notCut = ( d2 >= 0);
             d2 = ( a * s_it->point2[0]) + (b * s_it->point2[1]) + ( c * s_it->point2[2]) + d;
             notCut = ( notCut  && ( d2 >= 0) );
             d2 = ( a * s_it->point3[0]) + (b * s_it->point3[1]) + ( c * s_it->point3[2]) + d;
             notCut = ( notCut  && ( d2 >= 0) );
             d2 = ( a * s_it->point4[0]) + (b * s_it->point4[1]) + ( c * s_it->point4[2]) + d;
             notCut = ( notCut  && ( d2 >= 0) );
             itClip ++;
           }
         if (notCut)
           {
             tmpStream << "v " << s_it->point1[0]     << " " << s_it->point1[1]      << " " << s_it->point1[2] << std::endl;
             tmpStream << "v " << s_it->point2[0]     << " " << s_it->point2[1]      << " " << s_it->point2[2] << std::endl;
             tmpStream << "v " << s_it->point3[0]     << " " << s_it->point3[1]      << " " << s_it->point3[2] << std::endl;
             tmpStream << "v " << s_it->point4[0]     << " " << s_it->point4[1]      << " " << s_it->point4[2] << std::endl;
             tmpStream << "vn " << s_it->nx    << " " << s_it->ny     << " " << s_it->nz << std::endl;
             tmpStream << "f " << "-4//-1" << " " << "-3//-1" << " " << "-2//-1"<< " " << "-1//-1" << std::endl;
             j++;
           }
         if (tmpStream.str() != "")
           {
             std::stringstream name;
             name << "mySurfelPrismList" << j;
             std::stringstream matName;
             matName << "mySurfelPrismList" << j << "MAT";
             outOBJ << "o  " << name.str() << std::endl;
             outOBJ << "usemtl " << matName.str() << std::endl;
             outOBJ << tmpStream.str();
             typename std::vector< typename Board3D<Space, KSpace>::QuadD3D>::const_iterator itBegin = Board3D<Space, KSpace>::mySurfelPrismList.begin();
             Re = itBegin->color.red() /255.0 ;
             Gr = itBegin->color.green() /255.0;
             Bl = itBegin->color.blue() /255.0;
             Tr = itBegin->color.alpha() /255.0;
             bufMTL << "newmtl " << matName.str()  <<std::endl;
             bufMTL << "Ka " << Re << " " << Gr << " " << Bl << std::endl;
             bufMTL << "Kd " << Re << " " << Gr << " " << Bl << std::endl;
             bufMTL << "Ks 0 0 0" << std::endl;
             bufMTL << "d " << Tr << std::endl;
             bufMTL << "illum 2" << std::endl << std::endl;
           }
       }
   }
   //OPT tail
   // end SurfelPrism (from updateList)+++++++++++++++++++++++++++++++
   outMTL << bufMTL.str();
   outOBJ.close();
   outMTL.close();
 }
template<typename Space , typename KSpace > void DGtal::Board3D< Space, KSpace >::selfDisplay (std::ostream & outOBJ) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Writes/Displays the object on an output stream.
Parameters
outOBJ the output stream where the object is written.
Definition at line 105 of file Board3D.ih.
 {
   outOBJ << "[Board3D]";
 }
Field Documentation
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> DGtal::Color DGtal::Board3D< Space, KSpace >::myDefaultColor
default color
Definition at line 133 of file Board3D.h.
The documentation for this class was generated from the following files:
Board3D.h
Board3D.ih