DGtal: DGtal::Board3DTo2D< Space, KSpace > Class Template Reference
DGtal::Board3DTo2D< Space, KSpace > Class Template Reference
DGtal Concepts
#include <Board3DTo2D.h>
Public Types
enum CairoType {
CairoPDF, CairoPNG, CairoPS, CairoEPS,
CairoSVG
}
Public Types inherited from DGtal::Display3D< Space, KSpace >
enum StreamKey { addNewList, updateDisplay, shiftSurfelVisu }
typedef DGtal::Z3i::RealPoint RealPoint
typedef std::map< std::string,
std::string > ModeMapping
typedef std::map< std::string,
CountedPtr
< DrawableWithDisplay3D > > StyleMapping
Public Member Functions
Board3DTo2D ()
Board3DTo2D (KSpace KSEmb)
Board3DTo2D (Space SEmb, KSpace KSEmb)
~Board3DTo2D ()
std::string className () const
void setCameraPosition (double x, double y, double z)
void setCameraDirection (double x, double y, double z)
void setCameraUpVector (double x, double y, double z)
void setNearFar (double _near, double _far)
void saveCairo (const char *filename, CairoType type, int bWidth, int bHeight)
Board3DTo2D & operator<< (const DGtal::Color &aColor)
template<typename TDrawableWithDisplay3D >
Board3DTo2D & operator<< (const TDrawableWithDisplay3D &object)
void selfDisplay (std::ostream &out) const
bool isValid () const
template<typename TDrawableWithBoard3DTo2D >
DGtal::Board3DTo2D< Space,
KSpace > & operator<< (const TDrawableWithBoard3DTo2D &object)
Public Member Functions inherited from DGtal::Display3D< Space, KSpace >
BOOST_CONCEPT_ASSERT ((CSpace< Space >))
~Display3D ()
Display3D ()
Display3D (const KSpace &KSEmb)
Display3D (const Space &Semb, const KSpace &KSEmb)
virtual void setFillColor (DGtal::Color aColor)
virtual void setFillTransparency (unsigned char alpha)
virtual void setLineColor (DGtal::Color aColor)
virtual DGtal::Color getFillColor ()
virtual DGtal::Color getLineColor ()
virtual void setSpaceEmbedder (CanonicEmbedder< Space > *anEmbedder)
virtual void setKSpaceEmbedder (CanonicCellEmbedder< KSpace > *anEmbedder)
virtual void setSKSpaceEmbedder (CanonicSCellEmbedder< KSpace > *anEmbedder)
void addClippingPlane (double a, double b, double c, double d, bool drawPlane)
std::string getMode (const std::string &objectName) const
void createNewLineList (std::string s="")
void createNewBallList (std::string s="")
void createNewCubeList (std::string s="")
void createNewQuadList (std::string s="")
void createNewTriangleList (std::string s="")
void createNewPolygonList (std::string s="")
void addQuad (const RealPoint &p1, const RealPoint &p2, const RealPoint &p3, const RealPoint &p4)
void addTriangle (const RealPoint &p1, const RealPoint &p2, const RealPoint &p3)
void addPolygon (const std::vector< RealPoint > &vertices)
void addLine (const RealPoint &p1, const RealPoint &p2, double width=0.03)
void addCube (const RealPoint &center, double width=1.0)
void addBall (const RealPoint &center, double size=0.05)
void addSurfelPrism (const RealPoint &baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel, double sizeShiftFactor, double sizeFactor=1.0, bool isSigned=false, bool aSign=true)
void addQuad (const RealPoint &baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel, double sizeShiftFactor, double sizeFactor=1.0, bool isSigned=false, bool aSign=true)
void addCone (const RealPoint &p1, const RealPoint &p2, double width=0.02)
void addCylinder (const RealPoint &p1, const RealPoint &p2, const double width=0.02)
void updateBoundingBox (const RealPoint &point)
void exportToMesh (Mesh< Display3D::BallD3D > &aMesh) const
template<typename TDrawableWithDisplay3D >
Display3D & operator<< (const TDrawableWithDisplay3D &object)
void selfDisplay (std::ostream &out) const
bool isValid () const
DGtal::CanonicEmbedder< Space >
::RealPoint embed (const typename Space::Point &dp) const
DGtal::CanonicSCellEmbedder
< KSpace >::RealPoint embedKS (const typename KSpace::SCell &cell) const
DGtal::CanonicSCellEmbedder
< KSpace >::RealPoint embedKS (const DGtal::TransformedSurfelPrism &aTrans) const
DGtal::CanonicCellEmbedder
< KSpace >::RealPoint embedK (const typename KSpace::Cell &cell) const
template<typename TDrawableWithDisplay3D >
DGtal::Display3D< Space,KSpace > & operator<< (const TDrawableWithDisplay3D &object)
Data Fields
DGtal::Color myDefaultColor
Data Fields inherited from DGtal::Display3D< Space, KSpace >
ModeMapping myModes
StyleMapping myStyles
bool myBoundingPtEmptyTag
double myBoundingPtUp [3]
double myBoundingPtLow [3]
Protected Member Functions
virtual void init ()
Private Member Functions
BOOST_CONCEPT_ASSERT ((CSpace< Space >))
void precompute_projection_matrix ()
void project (double x3d, double y3d, double z3d, double &x2d, double &y2d)
Static Private Member Functions
static void TransposeMt (double tmat[16], double mat[16])
static void MulMt (double v[4], double mat[16], double b[4])
static void LookAtMt (double mat[16], double eyex, double eyey, double eyez, double dirx, double diry, double dirz, double upx, double upy, double upz)
Private Attributes
int Viewport [4]
double matrix [16]
double camera_position [3]
double camera_direction [3]
double camera_upVector [3]
double ZNear
double ZFar
Additional Inherited Members
Static Protected Member Functions inherited from DGtal::Display3D< Space, KSpace >
static void cross (double dst[3], double srcA[3], double srcB[3])
static void normalize (double vec[3])
Protected Attributes inherited from DGtal::Display3D< Space, KSpace >
CanonicEmbedder< Space > * myEmbedder
CanonicCellEmbedder< KSpace > * myCellEmbedder
CanonicSCellEmbedder< KSpace > * mySCellEmbedder
DGtal::Color myCurrentFillColor
DGtal::Color myCurrentLineColor
double myCurrentfShiftVisuSurfelPrisms
std::vector< std::vector
< CubeD3D > > myCubeSetList
std::vector< std::vector
< LineD3D > > myLineSetList
std::vector< std::vector
< BallD3D > > myBallSetList
std::vector< ClippingPlaneD3D > myClippingPlaneList
std::vector< QuadD3D > mySurfelPrismList
std::vector< std::vector
< QuadD3D > > myQuadSetList
std::vector< std::vector
< TriangleD3D > > myTriangleSetList
std::vector< std::vector
< PolygonD3D > > myPolygonSetList
std::vector< std::string > myCubeSetNameList
std::vector< std::string > myLineSetNameList
std::vector< std::string > myBallSetNameList
std::vector< std::string > myClippingPlaneNameList
std::vector< std::string > mySurfelPrismNameList
std::vector< std::string > myQuadSetNameList
std::vector< std::string > myTriangleSetNameList
std::vector< std::string > myPolygonSetNameList
Detailed Description
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace>
class DGtal::Board3DTo2D< Space, KSpace >
Class for PDF, PNG, PS, EPS, SVG export drawings with Cairo with 3D->2D projection.
Aim: The concept CDrawableWithBoard3DTo2D specifies what are the classes that admit an export with Board3DTo2D.
Description of class 'Board3DTo2D'
Description of concept 'CDrawableWithBoard3DTo2D'
An object x satisfying this concept may then be used as:
Board3DTo2D display;
display << CustomStyle(x.className(), x.defaultStyle())
      << x;
Refinement of
Associated types :
Notation
X : A type that is a model of CDrawableWithBoard3DTo2DD
x, y : Object of type X
m : a string of characters
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
the default draw style x.defaultStyle(m = "") mode m: std::string CDrawableWithBoard3DTo2D returns a dynamic allocation of the default style for the model X in mode m
the name of the model X x.className() std::string returns a string telling the name of the model X
the way the object x is drawn x.setStyle(CDrawableWithBoard3DTo2D &display) draws the object x on the display stream
Invariants
Models
ArimeticalDSS, FreemanChain, HyperRectDomain, ImageContainerByHashTree, ImageContainerBySTLVector, PointVector, DigitalSetBySTLSet,DigitalSetBySTLVector, Object
Notes
Todo:
ImageContainerByHashTree does not implement setStyle(display &).
ImageContainerByHashTree does not implement defaultStyle(std::string&)const.
Examples:
io/boards/dgtalBoard3DTo2D-1-points.cpp, io/boards/dgtalBoard3DTo2D-2-sets.cpp, io/boards/dgtalBoard3DTo2D-2bis-sets.cpp, io/boards/dgtalBoard3DTo2D-3-objects.cpp, io/boards/dgtalBoard3DTo2D-5-custom.cpp, io/boards/dgtalBoard3DTo2D-6.cpp, and io/boards/dgtalBoard3DTo2D-KSCell.cpp.
Definition at line 68 of file Board3DTo2D.h.
Member Enumeration Documentation
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> enum DGtal::Board3DTo2D::CairoType
Cairo type for save files.
Enumerator
CairoPDF
CairoPNG
CairoPS
CairoEPS
CairoSVG
Definition at line 76 of file Board3DTo2D.h.
 { CairoPDF, CairoPNG, CairoPS, CairoEPS, CairoSVG };
Constructor & Destructor Documentation
template<typename Space , typename KSpace > DGtal::Board3DTo2D< Space, KSpace >::Board3DTo2D ()
Constructor.
Constructor.
Definition at line 106 of file Board3DTo2D.ih.
 {
     init();
 }
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> DGtal::Board3DTo2D< Space, KSpace >::Board3DTo2D (KSpace KSEmb) inline
Constructor with a khalimsky space
Parameters
KSEmb the Khalimsky space
Definition at line 87 of file Board3DTo2D.h.
 :Display3D<Space,KSpace>(KSEmb) {}
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> DGtal::Board3DTo2D< Space, KSpace >::Board3DTo2D (Space SEmb, KSpace KSEmb) inline
Constructor with a space and a khalimsky space
Parameters
SEmb a space
KSEmb a khalimsky space
Definition at line 94 of file Board3DTo2D.h.
 :Display3D<Space,KSpace>(SEmb, KSEmb){}
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> DGtal::Board3DTo2D< Space, KSpace >::~Board3DTo2D () inline
Definition at line 97 of file Board3DTo2D.h.
 {}
Member Function Documentation
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> DGtal::Board3DTo2D< Space, KSpace >::BOOST_CONCEPT_ASSERT ((CSpace< Space >)) private
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> std::string DGtal::Board3DTo2D< Space, KSpace >::className () const inline
Returns
the style name used for drawing this object.
Definition at line 103 of file Board3DTo2D.h.
     {
         return "Board3DTo2D";
     }
template<typename Space , typename KSpace > void DGtal::Board3DTo2D< Space, KSpace >::init () protected virtual
init function (should be in Constructor).
init function (should be in Constructor).
Definition at line 617 of file Board3DTo2D.ih.
 {
     Board3DTo2D<Space, KSpace>::createNewCubeList();
     std::vector<typename Board3DTo2D<Space, KSpace>::LineD3D> listeLine;
     Board3DTo2D<Space, KSpace>::myLineSetList.push_back(listeLine);
     std::vector<typename Board3DTo2D<Space, KSpace>::BallD3D> listeBall;
     Board3DTo2D<Space, KSpace>::myBallSetList.push_back(listeBall);
     Board3DTo2D<Space, KSpace>::myCurrentFillColor = DGtal::Color (220, 220, 220);
     Board3DTo2D<Space, KSpace>::myCurrentLineColor = DGtal::Color (22, 22, 222, 50);
     /*createNewCubeList();
 std::vector<cubeD3D> aKSCubeList;*/
     Board3DTo2D<Space, KSpace>::myDefaultColor= DGtal::Color(255, 255, 255);
     //
     camera_position[0] = 5.000000; camera_position[1] = 5.000000; camera_position[2] = 29.893368;
     camera_direction[0] = 0.000000; camera_direction[1] = 0.000000; camera_direction[2] = -1.000000;
     camera_upVector[0] = 0.000000; camera_upVector[1] = 1.000000; camera_upVector[2] = 0.000000;
     ZNear = 0.001;
     ZFar = 100.0;
     //ZNear = 4.578200;
     //ZFar = 22.578199;
    Board3DTo2D<Space, KSpace>::myModes ["Board3DTo2D"]="SolidMode";
 }
template<typename Space , typename KSpace > bool DGtal::Board3DTo2D< Space, KSpace >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 133 of file Board3DTo2D.ih.
 {
     return true;
 }
template<typename Space , typename KSpace > void DGtal::Board3DTo2D< Space, KSpace >::LookAtMt (double mat[16], double eyex, double eyey, double eyez, double dirx, double diry, double dirz, double upx, double upy, double upz) static private
Compute 4x4 LookAt matrix.
Parameters
mat destination matrix.
eyex x position of eye.
eyey y position of eye.
eyez z position of eye.
dirx x direction of eye.
diry y direction of eye.
dirz z director of eye.
upx x coordinate of up-vector.
upy y coordinate of up-vector.
upz z coordinate of up-vector.
Definition at line 185 of file Board3DTo2D.ih.
 {
     double up[3]; up[0]= upx; up[1]= upy; up[2]= upz;
     double z[3]; z[0]= -dirx; z[1]= -diry; z[2]= -dirz; Display3D<Space,KSpace>::normalize(z);
     double x[3]; Display3D<Space,KSpace>::cross (x, up, z); Display3D<Space,KSpace>::normalize(x);
     double y[3]; Display3D<Space,KSpace>::cross (y, z, x); Display3D<Space,KSpace>::normalize(y);
     double m[16];
     m[0] = x[0]; m[1] = x[1]; m[2] = x[2]; m[3] = 0;
     m[4] = y[0]; m[5] = y[1]; m[6] = y[2]; m[7] = 0;
     m[8] = z[0]; m[9] = z[1]; m[10] = z[2]; m[11] = 0;
     m[12] = 0; m[13] = 0; m[14] = 0; m[15] = 1;
     double e[4]; e[0]= -eyex; e[1]= -eyey; e[2]= -eyez; e[3]= 1;
     double eyePrime[4]; MulMt(eyePrime, m, e);
     TransposeMt(mat, m);
     mat[12] = eyePrime[0]; mat[13] = eyePrime[1]; mat[14] = eyePrime[2];
 }
template<typename Space , typename KSpace > void DGtal::Board3DTo2D< Space, KSpace >::MulMt (double v[4], double mat[16], double b[4]) static private
Multiply a 3d vector by a 4x4 matrix.
Parameters
v destination vector.
mat source matrix.
b source vector.
Definition at line 162 of file Board3DTo2D.ih.
 {
     v[0] = mat[0] * b[0] + mat[1] * b[1] + mat[2] * b[2] + mat[3] * b[3];
     v[1] = mat[4] * b[0] + mat[5] * b[1] + mat[6] * b[2] + mat[7] * b[3];
     v[2] = mat[8] * b[0] + mat[9] * b[1] + mat[10] * b[2] + mat[11] * b[3];
     v[3] = mat[12] * b[0] + mat[13] * b[1] + mat[14] * b[2] + mat[15] * b[3];
 }
template<typename Space , typename KSpace > DGtal::Board3DTo2D< Space, KSpace > & DGtal::Board3DTo2D< Space, KSpace >::operator<< (const DGtal::Color & aColor) inline
Set the default color for future drawing.
Parameters
aColor a DGtal::Color (allow to set a trasnparency value).
Set the default color for future drawing.
Parameters
aColor,: a DGtal::Color (allow to set a trasnparency value).
Definition at line 68 of file Board3DTo2D.ih.
 {
   myDefaultColor=aColor;
   return *this;
 }
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> template<typename TDrawableWithDisplay3D > Board3DTo2D& DGtal::Board3DTo2D< Space, KSpace >::operator<< (const TDrawableWithDisplay3D & object)
Draws the drawable [object] in this board. It should satisfy the concept CDrawableWithDisplay3D, which requires for instance a method setStyle(Board3DTo2D &).
Parameters
object any drawable object.
Returns
a reference on 'this'.
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> template<typename TDrawableWithBoard3DTo2D > DGtal::Board3DTo2D<Space, KSpace>& DGtal::Board3DTo2D< Space, KSpace >::operator<< (const TDrawableWithBoard3DTo2D< Space, KSpace > & object) inline
Draws the drawable [object] in this board. It should satisfy the concept CDrawableWithBoard3DTo2D, which requires for instance a method setStyle(Board3DTo2D &).
Parameters
object any drawable object.
Returns
a reference on 'this'.
Definition at line 87 of file Board3DTo2D.ih.
References DGtal::Board3DTo2DFactory< TSpace, TKSpace >::draw().
 {
   BOOST_CONCEPT_ASSERT((CDrawableWithBoard3DTo2D< TDrawableWithBoard3DTo2D, Space, KSpace>));
   DGtal::Board3DTo2DFactory<Space,KSpace>::draw(*this, object);
   return *this;
 }
template<typename Space , typename KSpace > void DGtal::Board3DTo2D< Space, KSpace >::precompute_projection_matrix () private
Precompute 4x4 projection matrix for 3D->2D projection.
Definition at line 213 of file Board3DTo2D.ih.
 {
     // Projection: from qglviewer
     /*const double f = 1.0/tan(fieldOfView()/2.0);
 projectionMatrix_[0]  = f/aspectRatio();
 projectionMatrix_[5]  = f;
 projectionMatrix_[10] = (ZNear + ZFar) / (ZNear - ZFar);
 projectionMatrix_[11] = -1.0;
 projectionMatrix_[14] = 2.0 * ZNear * ZFar / (ZNear - ZFar);
 projectionMatrix_[15] = 0.0;
 // same as gluPerspective( 180.0*fieldOfView()/M_PI, aspectRatio(), zNear(), zFar() );*/
     double fieldOfView = M_PI/4.;
     double f = 1.0/tan(fieldOfView/2.0);
     double aspectRatio = (double)Viewport[2]/Viewport[3];
     double Projection[16] = { f/aspectRatio, 0.00, 0.00, 0.00,
                               0.00, f, 0.00, 0.00,
                               0.00, 0.00, (ZNear + ZFar) / (ZNear - ZFar), -1.00,
                               0.00, 0.00, 2.0 * ZNear * ZFar / (ZNear - ZFar), 0.00 };
     double Modelview[16];
     LookAtMt(Modelview,
              camera_position[0], camera_position[1], camera_position[2],
             camera_direction[0], camera_direction[1], camera_direction[2],
             camera_upVector[0], camera_upVector[1], camera_upVector[2]);
     for (unsigned short m=0; m<4; ++m)
     {
         for (unsigned short l=0; l<4; ++l)
         {
             double sum = 0.0;
             for (unsigned short k=0; k<4; ++k)
                 sum += Projection[l+4*k]*Modelview[k+4*m];
             matrix[l+4*m] = sum;
         }
     }
 }
template<typename Space , typename KSpace > void DGtal::Board3DTo2D< Space, KSpace >::project (double x3d, double y3d, double z3d, double & x2d, double & y2d) private
Project a 3d point (3D->2D).
Parameters
x3d x position of the 3d point.
y3d y position of the 3d point.
z3d z position of the 3d point.
x2d x destination projection position of the 2d point.
y2d y destination projection position of the 2d point.
Definition at line 261 of file Board3DTo2D.ih.
 {
     double v[4], vs[4];
     v[0]=x3d; v[1]=y3d; v[2]=z3d; v[3]=1.0;
     vs[0]=matrix[0 ]*v[0] + matrix[4 ]*v[1] + matrix[8 ]*v[2] + matrix[12 ]*v[3];
     vs[1]=matrix[1 ]*v[0] + matrix[5 ]*v[1] + matrix[9 ]*v[2] + matrix[13 ]*v[3];
     vs[2]=matrix[2 ]*v[0] + matrix[6 ]*v[1] + matrix[10]*v[2] + matrix[14 ]*v[3];
     vs[3]=matrix[3 ]*v[0] + matrix[7 ]*v[1] + matrix[11]*v[2] + matrix[15 ]*v[3];
     vs[0] /= vs[3];
     vs[1] /= vs[3];
     vs[2] /= vs[3];
     vs[0] = vs[0] * 0.5 + 0.5;
     vs[1] = vs[1] * 0.5 + 0.5;
     vs[2] = vs[2] * 0.5 + 0.5;
     vs[0] = vs[0] * Viewport[2] + Viewport[0];
     vs[1] = vs[1] * Viewport[3] + Viewport[1];
     x2d = vs[0];
     y2d = Viewport[3]-vs[1];
 }
template<typename Space , typename KSpace > void DGtal::Board3DTo2D< Space, KSpace >::saveCairo (const char * filename, CairoType type, int bWidth, int bHeight)
Save a Cairo image.
Parameters
filename filename of the image to save.
type type of the image to save (CairoPDF, CairoPNG, CairoPS, CairoEPS, CairoSVG).
bWidth width of the image to save.
bHeight height of the image to save.
Definition at line 295 of file Board3DTo2D.ih.
References DGtal::Trace::info(), and DGtal::trace.
 {
     for(unsigned int i =0; i< Board3DTo2D<Space, KSpace>::myClippingPlaneList.size(); i++)
         trace.info() << "-> ClippingPlane not implemented in Board3DTo2D" << std::endl;
     Viewport[0] = 0; Viewport[1] = 0; Viewport[2] = bWidth; Viewport[3] = bHeight;
     precompute_projection_matrix();
     cairo_surface_t *surface;
     cairo_t *cr;
     switch (type)
     {
     case CairoPDF:
         surface = cairo_pdf_surface_create (filename, Viewport[2], Viewport[3]); break;
     case CairoPS:
         surface = cairo_ps_surface_create (filename, Viewport[2], Viewport[3]); break;
     case CairoEPS:
         surface = cairo_ps_surface_create (filename, Viewport[2], Viewport[3]);
         cairo_ps_surface_set_eps(surface, true); break;
     case CairoSVG:
         surface = cairo_svg_surface_create (filename, Viewport[2], Viewport[3]); break;
     case CairoPNG:
     default:
         surface = cairo_image_surface_create (CAIRO_FORMAT_ARGB32, Viewport[2], Viewport[3]);
     }
     cr = cairo_create (surface);
     // Fill the background with gray
     cairo_set_source_rgba (cr, .3, .3, .3, 1.);
     cairo_rectangle (cr, 0, 0, Viewport[2], Viewport[3]);
     cairo_fill (cr);
     // Draw the shapes
     // myBallSetList
     for(unsigned int i=0; i<Board3DTo2D<Space, KSpace>::myBallSetList.size(); i++)
     {
         for (typename std::vector<typename Board3DTo2D<Space, KSpace>::BallD3D>::iterator s_it = Board3DTo2D<Space, KSpace>::myBallSetList.at(i).begin();
              s_it != Board3DTo2D<Space, KSpace>::myBallSetList.at(i).end();
              ++s_it)
         {
             {
                 cairo_save (cr);
                 cairo_set_source_rgba (cr, (*s_it).color.red()/255.0, (*s_it).color.green()/255.0,
                                        (*s_it).color.blue()/255.0, (*s_it).color.alpha()/255.0);
                 cairo_set_line_width (cr, 1.); // arbitraire car non set
                 double x1, y1, x2, y2, x3, y3, x4, y4;
                 //double width=(*s_it).size/120.; // arbitraire
                 double width=0.05; // arbitraire
                 // TODO:
                 /*double distCam =sqrt((camera_position[0]-centerS.x)*(camera_position[0]-centerS.x)+
 (camera_position[1]-centerS.y)*(camera_position[1]-centerS.y)+
 (camera_position[2]-centerS.z)*(camera_position[2]-centerS.z));*/
                 //z+
                 project((*s_it).center[0]-width,  (*s_it).center[1]+width, (*s_it).center[2]+width, x1, y1);
                 project((*s_it).center[0]+width,  (*s_it).center[1]+width, (*s_it).center[2]+width, x2, y2);
                 project((*s_it).center[0]+width,  (*s_it).center[1]-width, (*s_it).center[2]+width, x3, y3);
                 project((*s_it).center[0]-width,  (*s_it).center[1]-width, (*s_it).center[2]+width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr); Board3DTo2D<Space, KSpace>::myModes["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 //z-
                 project((*s_it).center[0]-width,  (*s_it).center[1]+width, (*s_it).center[2]-width, x1, y1);
                 project((*s_it).center[0]+width,  (*s_it).center[1]+width, (*s_it).center[2]-width, x2, y2);
                 project((*s_it).center[0]+width,  (*s_it).center[1]-width, (*s_it).center[2]-width, x3, y3);
                 project((*s_it).center[0]-width,  (*s_it).center[1]-width, (*s_it).center[2]-width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr); Board3DTo2D<Space, KSpace>::myModes["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 //x+
                 project((*s_it).center[0]+width,  (*s_it).center[1]-width, (*s_it).center[2]+width, x1, y1);
                 project((*s_it).center[0]+width,  (*s_it).center[1]+width, (*s_it).center[2]+width, x2, y2);
                 project((*s_it).center[0]+width,  (*s_it).center[1]+width, (*s_it).center[2]-width, x3, y3);
                 project((*s_it).center[0]+width,  (*s_it).center[1]-width, (*s_it).center[2]-width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr); Board3DTo2D<Space, KSpace>::myModes["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 //x-
                 project((*s_it).center[0]-width,  (*s_it).center[1]-width, (*s_it).center[2]+width, x1, y1);
                 project((*s_it).center[0]-width,  (*s_it).center[1]+width, (*s_it).center[2]+width, x2, y2);
                 project((*s_it).center[0]-width,  (*s_it).center[1]+width, (*s_it).center[2]-width, x3, y3);
                 project((*s_it).center[0]-width,  (*s_it).center[1]-width, (*s_it).center[2]-width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr); Board3DTo2D<Space, KSpace>::myModes["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 //y+
                 project((*s_it).center[0]-width,  (*s_it).center[1]+width, (*s_it).center[2]+width, x1, y1);
                 project((*s_it).center[0]+width,  (*s_it).center[1]+width, (*s_it).center[2]+width, x2, y2);
                 project((*s_it).center[0]+width,  (*s_it).center[1]+width, (*s_it).center[2]-width, x3, y3);
                 project((*s_it).center[0]-width,  (*s_it).center[1]+width, (*s_it).center[2]-width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr); Board3DTo2D<Space, KSpace>::myModes["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 //y-
                 project((*s_it).center[0]-width,  (*s_it).center[1]-width, (*s_it).center[2]+width, x1, y1);
                 project((*s_it).center[0]+width,  (*s_it).center[1]-width, (*s_it).center[2]+width, x2, y2);
                 project((*s_it).center[0]+width,  (*s_it).center[1]-width, (*s_it).center[2]-width, x3, y3);
                 project((*s_it).center[0]-width,  (*s_it).center[1]-width, (*s_it).center[2]-width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr); Board3DTo2D<Space, KSpace>::myModes["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 cairo_restore (cr);
             }
         }
     }
     // myLineSetList
     for(unsigned int i=0; i<Board3DTo2D<Space, KSpace>::myLineSetList.size(); i++)
     {
         for (typename std::vector<typename Board3DTo2D<Space, KSpace>::LineD3D>::iterator s_it = Board3DTo2D<Space, KSpace>::myLineSetList.at(i).begin();
              s_it != Board3DTo2D<Space, KSpace>::myLineSetList.at(i).end();
              ++s_it)
         {
             {
                 cairo_save (cr);
                 cairo_set_source_rgba (cr, (*s_it).color.red()/255.0, (*s_it).color.green()/255.0,
                                        (*s_it).color.blue()/255.0, (*s_it).color.alpha()/255.0);
                 double x1, y1;
                 double x2, y2;
                 project((*s_it).point1[0], (*s_it).point1[1], (*s_it).point1[2], x1, y1);
                 project((*s_it).point2[0], (*s_it).point2[1], (*s_it).point2[2], x2, y2);
                 cairo_move_to (cr, x1, y1);
                 cairo_line_to (cr, x2, y2);
                 //cairo_set_line_width (cr, (*s_it).width);
                 cairo_set_line_width (cr, 1.); // arbitraire car non set
                 cairo_stroke (cr);
                 cairo_restore (cr);
             }
         }
     }
     // myCubeSetList
     for(unsigned int i=0; i<Board3DTo2D<Space, KSpace>::myCubeSetList.size(); i++)
     {
         for (typename std::vector< typename Board3DTo2D<Space, KSpace>::CubeD3D>::iterator s_it = Board3DTo2D<Space, KSpace>::myCubeSetList.at(i).begin();
              s_it != Board3DTo2D<Space, KSpace>::myCubeSetList.at(i).end();
              ++s_it)
         {
             {
                 cairo_save (cr);
                 if (Board3DTo2D<Space, KSpace>::myModes["Board3DTo2D"]=="SolidMode")
                   cairo_set_source_rgba (cr, (*s_it).color.red()/255.0, (*s_it).color.green()/255.0,
                                          (*s_it).color.blue()/255.0, (*s_it).color.alpha()/(255.0*1.75)); // *1.75 arbitraire
                 else
                   cairo_set_source_rgba (cr, (*s_it).color.red()/255.0, (*s_it).color.green()/255.0,
                                          (*s_it).color.blue()/255.0, (*s_it).color.alpha()/(255.0*0.75)); // *0.75 arbitraire
                 cairo_set_line_width (cr, 1.); // arbitraire car non set
                 double x1, y1, x2, y2, x3, y3, x4, y4;
                 double width=(*s_it).width;
                 //z+
                 project((*s_it).center[0]-width,  (*s_it).center[1]+width, (*s_it).center[2]+width, x1, y1);
                 project((*s_it).center[0]+width,  (*s_it).center[1]+width, (*s_it).center[2]+width, x2, y2);
                 project((*s_it).center[0]+width,  (*s_it).center[1]-width, (*s_it).center[2]+width, x3, y3);
                 project((*s_it).center[0]-width,  (*s_it).center[1]-width, (*s_it).center[2]+width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr);Board3DTo2D<Space, KSpace>::myModes ["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 //z-
                 project((*s_it).center[0]-width,  (*s_it).center[1]+width, (*s_it).center[2]-width, x1, y1);
                 project((*s_it).center[0]+width,  (*s_it).center[1]+width, (*s_it).center[2]-width, x2, y2);
                 project((*s_it).center[0]+width,  (*s_it).center[1]-width, (*s_it).center[2]-width, x3, y3);
                 project((*s_it).center[0]-width,  (*s_it).center[1]-width, (*s_it).center[2]-width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr);Board3DTo2D<Space, KSpace>::myModes ["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 //x+
                 project((*s_it).center[0]+width,  (*s_it).center[1]-width, (*s_it).center[2]+width, x1, y1);
                 project((*s_it).center[0]+width,  (*s_it).center[1]+width, (*s_it).center[2]+width, x2, y2);
                 project((*s_it).center[0]+width,  (*s_it).center[1]+width, (*s_it).center[2]-width, x3, y3);
                 project((*s_it).center[0]+width,  (*s_it).center[1]-width, (*s_it).center[2]-width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr);Board3DTo2D<Space, KSpace>::myModes ["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 //x-
                 project((*s_it).center[0]-width,  (*s_it).center[1]-width, (*s_it).center[2]+width, x1, y1);
                 project((*s_it).center[0]-width,  (*s_it).center[1]+width, (*s_it).center[2]+width, x2, y2);
                 project((*s_it).center[0]-width,  (*s_it).center[1]+width, (*s_it).center[2]-width, x3, y3);
                 project((*s_it).center[0]-width,  (*s_it).center[1]-width, (*s_it).center[2]-width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr);Board3DTo2D<Space, KSpace>::myModes ["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 //y+
                 project((*s_it).center[0]-width,  (*s_it).center[1]+width, (*s_it).center[2]+width, x1, y1);
                 project((*s_it).center[0]+width,  (*s_it).center[1]+width, (*s_it).center[2]+width, x2, y2);
                 project((*s_it).center[0]+width,  (*s_it).center[1]+width, (*s_it).center[2]-width, x3, y3);
                 project((*s_it).center[0]-width,  (*s_it).center[1]+width, (*s_it).center[2]-width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr);Board3DTo2D<Space, KSpace>::myModes ["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 //y-
                 project((*s_it).center[0]-width,  (*s_it).center[1]-width, (*s_it).center[2]+width, x1, y1);
                 project((*s_it).center[0]+width,  (*s_it).center[1]-width, (*s_it).center[2]+width, x2, y2);
                 project((*s_it).center[0]+width,  (*s_it).center[1]-width, (*s_it).center[2]-width, x3, y3);
                 project((*s_it).center[0]-width,  (*s_it).center[1]-width, (*s_it).center[2]-width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr);Board3DTo2D<Space, KSpace>::myModes ["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 cairo_restore (cr);
             }
         }
     }
     for(typename std::vector<std::vector<typename Board3DTo2D<Space, KSpace>::QuadD3D> >::iterator it=Board3DTo2D<Space, KSpace>::myQuadSetList.begin(); it != Board3DTo2D<Space, KSpace>::myQuadSetList.end(); it++)
         trace.info() << "-> Quad not YET implemented in Board3DTo2D" << std::endl;
     // Drawing all Khalimsky Space Cells
     // SurfelPrism (from updateList)
     for (typename std::vector<typename Board3DTo2D<Space, KSpace>::QuadD3D>::iterator s_it =Board3DTo2D<Space, KSpace>:: mySurfelPrismList.begin();
          s_it != Board3DTo2D<Space, KSpace>::mySurfelPrismList.end();
          ++s_it)
     {
         {
             cairo_save (cr);
             if (Board3DTo2D<Space, KSpace>::myModes["Board3DTo2D"]=="SolidMode")
               cairo_set_source_rgba (cr, (*s_it).color.red()/255.0, (*s_it).color.green()/255.0,
                                      (*s_it).color.blue()/255.0, (*s_it).color.alpha()/(255.0*3.75)); // *3.75 arbitraire
             else
               cairo_set_source_rgba (cr, (*s_it).color.red()/255.0, (*s_it).color.green()/255.0,
                                      (*s_it).color.blue()/255.0, (*s_it).color.alpha()/(255.0*0.75)); // *0.75 arbitraire
             cairo_set_line_width (cr, 1.); // arbitraire car non set
             double x1, y1, x2, y2, x3, y3, x4, y4;
             project((*s_it).point1[0],  (*s_it).point1[1], (*s_it).point1[2], x1, y1);
             project((*s_it).point2[0],  (*s_it).point2[1], (*s_it).point2[2], x2, y2);
             project((*s_it).point3[0],  (*s_it).point3[1], (*s_it).point3[2], x3, y3);
             project((*s_it).point4[0],  (*s_it).point4[1], (*s_it).point4[2], x4, y4);
             cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr); Board3DTo2D<Space, KSpace>::myModes["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
             cairo_restore (cr);
         }
     }
     /*
     // KSLinel
     for(unsigned int i=0; i< myKSLinelList.size();i++)
     {
         //if (!myKSLinelList.at(i).isSigned) // for the moment, same for Signed or NonSigned
         {
             {
                 cairo_save (cr);
                 cairo_set_source_rgba (cr, myKSLinelList.at(i).R/255.0, myKSLinelList.at(i).G/255.0, myKSLinelList.at(i).B/255.0, myKSLinelList.at(i).T/255.0);
                 cairo_set_line_width (cr, 4.); // arbitraire car non set
                 double x1, y1, x2, y2;
                 project(myKSLinelList.at(i).x1,  myKSLinelList.at(i).y1, myKSLinelList.at(i).z1, x1, y1);
                 project(myKSLinelList.at(i).x2,  myKSLinelList.at(i).y2, myKSLinelList.at(i).z2, x2, y2);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_close_path (cr); cairo_stroke (cr);
                 cairo_restore (cr);
             }
         }
     }
     // KSBallel
     for(std::vector<ballD3D>::iterator it=myKSBallelList.begin(); it != myKSBallelList.end(); it++)
     {
         //if (!it->isSigned) // for the moment, same for Signed or NonSigned
         {
             {
                 cairo_save (cr);
                 cairo_set_source_rgba (cr, it->R/255.0, it->G/255.0, it->B/255.0, it->T/255.0);
                 cairo_set_line_width (cr, 1.); // arbitraire car non set
                 double x1, y1, x2, y2, x3, y3, x4, y4;
                 //double width=it->size/120.; // arbitraire
                 double width=0.04; // arbitraire
                 //z+
                 project(it->x-width,  it->y+width, it->z+width, x1, y1);
                 project(it->x+width,  it->y+width, it->z+width, x2, y2);
                 project(it->x+width,  it->y-width, it->z+width, x3, y3);
                 project(it->x-width,  it->y-width, it->z+width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr);Board3DTo2D<Space, KSpace>::myModes ["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 //z-
                 project(it->x-width,  it->y+width, it->z-width, x1, y1);
                 project(it->x+width,  it->y+width, it->z-width, x2, y2);
                 project(it->x+width,  it->y-width, it->z-width, x3, y3);
                 project(it->x-width,  it->y-width, it->z-width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr);Board3DTo2D<Space, KSpace>::myModes ["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 //x+
                 project(it->x+width,  it->y-width, it->z+width, x1, y1);
                 project(it->x+width,  it->y+width, it->z+width, x2, y2);
                 project(it->x+width,  it->y+width, it->z-width, x3, y3);
                 project(it->x+width,  it->y-width, it->z-width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr);Board3DTo2D<Space, KSpace>::myModes ["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 //x-
                 project(it->x-width,  it->y-width, it->z+width, x1, y1);
                 project(it->x-width,  it->y+width, it->z+width, x2, y2);
                 project(it->x-width,  it->y+width, it->z-width, x3, y3);
                 project(it->x-width,  it->y-width, it->z-width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr);Board3DTo2D<Space, KSpace>::myModes ["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 //y+
                 project(it->x-width,  it->y+width, it->z+width, x1, y1);
                 project(it->x+width,  it->y+width, it->z+width, x2, y2);
                 project(it->x+width,  it->y+width, it->z-width, x3, y3);
                 project(it->x-width,  it->y+width, it->z-width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr);Board3DTo2D<Space, KSpace>::myModes ["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 //y-
                 project(it->x-width,  it->y-width, it->z+width, x1, y1);
                 project(it->x+width,  it->y-width, it->z+width, x2, y2);
                 project(it->x+width,  it->y-width, it->z-width, x3, y3);
                 project(it->x-width,  it->y-width, it->z-width, x4, y4);
                 cairo_move_to (cr, x1, y1); cairo_line_to (cr, x2, y2); cairo_line_to (cr, x3, y3); cairo_line_to (cr, x4, y4); cairo_line_to (cr, x1, y1); cairo_close_path (cr);Board3DTo2D<Space, KSpace>::myModes ["Board3DTo2D"]=="SolidMode"?cairo_fill (cr):cairo_stroke (cr);
                 cairo_restore (cr);
             }
         }
     }
      */
     if (type==CairoPNG)
         cairo_surface_write_to_png (surface, filename);
     cairo_destroy (cr);
     cairo_surface_destroy (surface);
 }
template<typename Space , typename KSpace > void DGtal::Board3DTo2D< Space, KSpace >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 122 of file Board3DTo2D.ih.
 {
     out << "[Board3DTo2D]";
 }
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> void DGtal::Board3DTo2D< Space, KSpace >::setCameraDirection (double x, double y, double z) inline
Set camera direction.
Parameters
x x direction.
y y direction.
z z direction.
Definition at line 123 of file Board3DTo2D.h.
Referenced by DGtal::Board3DTo2DFactory< TSpace, TKSpace >::draw().
     { camera_direction[0] = x; camera_direction[1] = y; camera_direction[2] = z; }
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> void DGtal::Board3DTo2D< Space, KSpace >::setCameraPosition (double x, double y, double z) inline
Set camera position.
Parameters
x x position.
y y position.
z z position.
Definition at line 114 of file Board3DTo2D.h.
Referenced by DGtal::Board3DTo2DFactory< TSpace, TKSpace >::draw().
     { camera_position[0] = x; camera_position[1] = y; camera_position[2] = z; }
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> void DGtal::Board3DTo2D< Space, KSpace >::setCameraUpVector (double x, double y, double z) inline
Set camera up-vector.
Parameters
x x coordinate of up-vector.
y y coordinate of up-vector.
z z coordinate of up-vector.
Definition at line 132 of file Board3DTo2D.h.
Referenced by DGtal::Board3DTo2DFactory< TSpace, TKSpace >::draw().
     { camera_upVector[0] = x; camera_upVector[1] = y; camera_upVector[2] = z; }
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> void DGtal::Board3DTo2D< Space, KSpace >::setNearFar (double _near, double _far) inline
Set near and far distance, too near or too far end up not visible.
Parameters
_near near distance.
_far far distance.
Definition at line 140 of file Board3DTo2D.h.
Referenced by DGtal::Board3DTo2DFactory< TSpace, TKSpace >::draw().
 { ZNear = _near; ZFar = _far; }
template<typename Space , typename KSpace > void DGtal::Board3DTo2D< Space, KSpace >::TransposeMt (double tmat[16], double mat[16]) static private
Transpose a 4x4 matrix.
Parameters
tmat destination matrix.
mat source matrix.
Definition at line 146 of file Board3DTo2D.ih.
 {
     tmat[0] = mat[0]; tmat[1] = mat[4]; tmat[2] = mat[8]; tmat[3] = mat[12];
     tmat[4] = mat[1]; tmat[5] = mat[5]; tmat[6] = mat[9]; tmat[7] = mat[13];
     tmat[8] = mat[2]; tmat[9] = mat[6]; tmat[10] = mat[10]; tmat[11] = mat[14];
     tmat[12] = mat[3]; tmat[13] = mat[7]; tmat[14] = mat[11]; tmat[15] = mat[15];
 }
Field Documentation
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> double DGtal::Board3DTo2D< Space, KSpace >::camera_direction[3] private
camera direction
Definition at line 263 of file Board3DTo2D.h.
Referenced by DGtal::Board3DTo2D< S, KS >::setCameraDirection().
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> double DGtal::Board3DTo2D< Space, KSpace >::camera_position[3] private
camera position
Definition at line 262 of file Board3DTo2D.h.
Referenced by DGtal::Board3DTo2D< S, KS >::setCameraPosition().
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> double DGtal::Board3DTo2D< Space, KSpace >::camera_upVector[3] private
camera up-vector
Definition at line 264 of file Board3DTo2D.h.
Referenced by DGtal::Board3DTo2D< S, KS >::setCameraUpVector().
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> double DGtal::Board3DTo2D< Space, KSpace >::matrix[16] private
projection matrix
Definition at line 260 of file Board3DTo2D.h.
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> DGtal::Color DGtal::Board3DTo2D< Space, KSpace >::myDefaultColor
default color
The associated map type for storing possible modes used for displaying for digital objects. The associated map type for storing the default styles of digital objects.
Definition at line 166 of file Board3DTo2D.h.
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> int DGtal::Board3DTo2D< Space, KSpace >::Viewport[4] private
2D viewport
Definition at line 259 of file Board3DTo2D.h.
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> double DGtal::Board3DTo2D< Space, KSpace >::ZFar private
zfar distance
Definition at line 267 of file Board3DTo2D.h.
Referenced by DGtal::Board3DTo2D< S, KS >::setNearFar().
template<typename Space = Z3i::Space, typename KSpace = Z3i::KSpace> double DGtal::Board3DTo2D< Space, KSpace >::ZNear private
znear distance
Definition at line 266 of file Board3DTo2D.h.
Referenced by DGtal::Board3DTo2D< S, KS >::setNearFar().
The documentation for this class was generated from the following files:
Board3DTo2D.h
Board3DTo2D.ih