DGtal: DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension > Class Template Reference
DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension > Class Template Reference
#include <IntegralInvariantGaussianCurvatureEstimator.h>
Public Types
typedef TKSpace KSpace
typedef Z2i::Domain Domain
typedef KSpace::Space::RealPoint RealPoint
typedef Z2i::DigitalSet DigitalSet
typedef KSpace::SCell Spel
typedef KSpace::SurfelSet SurfelSet
typedef SurfelSet::const_iterator ConstIteratorKernel
typedef int Value
typedef TShapeFunctor ShapeSpelFunctor
typedef ConstValueCellFunctor
< Value, Spel > KernelSpelFunctor
typedef ImplicitBall< Z2i::Space > KernelSupport
typedef EuclideanShapesMinus
< KernelSupport, KernelSupport > EuclideanMinus
typedef GaussDigitizer
< Z2i::Space, KernelSupport > DigitalShapeKernel
typedef GaussDigitizer
< Z2i::Space, EuclideanMinus > DigitalShape
typedef
DigitalSurfaceConvolver
< ShapeSpelFunctor,
KernelSpelFunctor, KSpace,
DigitalShapeKernel > Convolver
typedef Convolver::CovarianceMatrix Matrix2x2
typedef
GaussianCurvatureFunctor2
< Matrix2x2 > ValuesFunctor
typedef
PrincipalCurvatureFunctor2
< Matrix2x2 > PrincipalCurvatureFunctor
typedef ValuesFunctor::Value Quantity
typedef
PrincipalCurvatureFunctor::Value PrincipalCurvatures
typedef Convolver::PairIterators PairIterators
Public Member Functions
BOOST_CONCEPT_ASSERT ((CCellFunctor< ShapeSpelFunctor >))
IntegralInvariantGaussianCurvatureEstimator (ConstAlias< KSpace > space, ConstAlias< ShapeSpelFunctor > f)
~IntegralInvariantGaussianCurvatureEstimator ()
void init (const double _h, const double re)
template<typename SurfelIterator >
Quantity eval (const SurfelIterator &it)
template<typename SurfelIterator , typename OutputIterator >
void eval (const SurfelIterator &itb, const SurfelIterator &ite, OutputIterator &result)
template<typename SurfelIterator >
PrincipalCurvatures evalPrincipalCurvatures (const SurfelIterator &it)
template<typename SurfelIterator , typename OutputIterator >
void evalPrincipalCurvatures (const SurfelIterator &itb, const SurfelIterator &ite, OutputIterator &result)
void selfDisplay (std::ostream &out) const
bool isValid () const
template<typename SurfelIterator >
DGtal::IntegralInvariantGaussianCurvatureEstimator
< TKSpace, TShapeFunctor,
dimension >::Quantity eval (const SurfelIterator &it)
template<typename SurfelIterator >
DGtal::IntegralInvariantGaussianCurvatureEstimator
< TKSpace, TShapeFunctor,
dimension >
::PrincipalCurvatures evalPrincipalCurvatures (const SurfelIterator &it)
Private Member Functions
IntegralInvariantGaussianCurvatureEstimator (const IntegralInvariantGaussianCurvatureEstimator &other)
IntegralInvariantGaussianCurvatureEstimator & operator= (const IntegralInvariantGaussianCurvatureEstimator &other)
Private Attributes
std::vector< PairIterators > kernels
std::vector< DigitalSet * > kernelsSet
KernelSupport * kernel
DigitalShapeKernel * digKernel
const KernelSpelFunctor myKernelFunctor
Convolver myConvolver
double h
double radius
ValuesFunctor gaussFunctor
PrincipalCurvatureFunctor princCurvFunctor
Detailed Description
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension>
class DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >
Aim: This class implement a Integral Invariant Gaussian curvature estimation.
Description of template class 'IntegralInvariantMeanCurvatureEstimator'
See Also
related article: Coeurjolly, D.; Lachaud, J.O; Levallois, J., (2013). Integral based Curvature Estimators in Digital Geometry. DGCI 2013. Retrieved from https://liris.cnrs.fr/publis/?id=5866
The algorithm we propose uses covariance matrix to approximate Gaussian curvature. To compute the covariance matrix on each surfel of the surface, we convolve a kernel (ImplicitBall) around the surface. The resulting covariance matrix gives us principal curvatures and principal directions by computing respectively eigenvectors and eigenvalues on it. Theorical multigrid convergence is proved with principal curvatures, with a convergence speed of O(h^1/3) with hypothesis about the shape geometry and the convolution kernel radius. Experimental results showed a multigrid convergence for principal curvatures.
Some optimization is available when we set a range of 0-adjacent surfels to the estimator.
Template Parameters
TKSpace space in which the shape is defined.
TShapeFunctor TFunctor a model of a functor for the shape (f(x)).
dimension dimension of the shape. Let default value to use the correct specialization.
See Also
exampleIntegralInvariantGaussianCurvature3D.cpp testIntegralInvariantGaussianCurvature3D.cpp
Definition at line 302 of file IntegralInvariantGaussianCurvatureEstimator.h.
Member Typedef Documentation
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef SurfelSet::const_iterator DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::ConstIteratorKernel
Definition at line 311 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef DigitalSurfaceConvolver<ShapeSpelFunctor, KernelSpelFunctor, KSpace, DigitalShapeKernel> DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::Convolver
Definition at line 322 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef Z2i::DigitalSet DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::DigitalSet
Definition at line 308 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef GaussDigitizer< Z2i::Space, EuclideanMinus > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::DigitalShape
Definition at line 320 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef GaussDigitizer< Z2i::Space, KernelSupport > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::DigitalShapeKernel
Definition at line 319 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef Z2i::Domain DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::Domain
Definition at line 306 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef EuclideanShapesMinus< KernelSupport, KernelSupport > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::EuclideanMinus
Definition at line 318 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef ConstValueCellFunctor<Value, Spel> DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::KernelSpelFunctor
Definition at line 316 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef ImplicitBall<Z2i::Space> DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::KernelSupport
Definition at line 317 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef TKSpace DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::KSpace
Definition at line 305 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef Convolver::CovarianceMatrix DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::Matrix2x2
Definition at line 324 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef Convolver::PairIterators DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::PairIterators
Definition at line 332 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef PrincipalCurvatureFunctor2< Matrix2x2 > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::PrincipalCurvatureFunctor
Definition at line 327 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef PrincipalCurvatureFunctor::Value DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::PrincipalCurvatures
Definition at line 330 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef ValuesFunctor::Value DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::Quantity
Definition at line 329 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef KSpace::Space::RealPoint DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::RealPoint
Definition at line 307 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef TShapeFunctor DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::ShapeSpelFunctor
Definition at line 315 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef KSpace::SCell DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::Spel
Definition at line 309 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef KSpace::SurfelSet DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::SurfelSet
Definition at line 310 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef int DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::Value
Definition at line 313 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> typedef GaussianCurvatureFunctor2< Matrix2x2 > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::ValuesFunctor
Definition at line 326 of file IntegralInvariantGaussianCurvatureEstimator.h.
Constructor & Destructor Documentation
template<typename TKSpace , typename TShapeFunctor , DGtal::Dimension dimension> DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::IntegralInvariantGaussianCurvatureEstimator (ConstAlias< KSpace > space, ConstAlias< ShapeSpelFunctor > f) inline
Constructor.
Parameters
space space in which the shape is defined.
f functor on spel of the shape.
Definition at line 44 of file IntegralInvariantGaussianCurvatureEstimator.ih.
     : myKernelFunctor(NumberTraits<Quantity>::ONE),
       myConvolver(shapeFunctor, myKernelFunctor, space)
 {}
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::~IntegralInvariantGaussianCurvatureEstimator () inline
Destructor.
Definition at line 349 of file IntegralInvariantGaussianCurvatureEstimator.h.
References DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::digKernel, DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::kernel, and DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::kernelsSet.
   {
     for( unsigned int i = 0; i < kernelsSet.size(); ++i )
     {
       delete kernelsSet[ i ];
     }
     kernelsSet.clear();
     delete kernel;
     delete digKernel;
   }
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::IntegralInvariantGaussianCurvatureEstimator (const IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension > & other) private
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
Member Function Documentation
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::BOOST_CONCEPT_ASSERT ((CCellFunctor< ShapeSpelFunctor >))
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> template<typename SurfelIterator > DGtal::IntegralInvariantGaussianCurvatureEstimator<TKSpace, TShapeFunctor, dimension>::Quantity DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::eval (const SurfelIterator & it) inline
Definition at line 204 of file IntegralInvariantGaussianCurvatureEstimator.ih.
References DGtal::Trace::error(), and DGtal::trace.
 {
     Quantity measure(0);
     trace.error() << "IntegralInvariantGaussianCurvatureEstimator@eval() : Not available yet.";
     return measure;
 }
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> template<typename SurfelIterator > Quantity DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::eval (const SurfelIterator & it)
– Gaussian curvature – Compute the integral invariant Gaussian curvature at surfel *it of a shape.
Template Parameters
SurfelIterator type of Iterator on a Surfel
Parameters
[in] it iterator of a surfel (from a shape) we want compute the integral invariant Gaussian curvature.
Returns
quantity (Gaussian curvature) at position *it
template<typename TKSpace , typename TShapeFunctor , DGtal::Dimension dimension> template<typename SurfelIterator , typename OutputIterator > void DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::eval (const SurfelIterator & itb, const SurfelIterator & ite, OutputIterator & result) inline
– Gaussian curvature – Compute the integral invariant Gaussian curvature from two surfels (from *itb to *ite (exclude)) of a shape. Return the result on an OutputIterator (param).
Template Parameters
SurfelIterator type of Iterator on a Surfel
OutputIterator type of Iterator of a list of Quantity
Parameters
[in] ite iterator of the begin surfel on the shape we want compute the integral invariant Gaussian curvature.
[in] itb iterator of the end surfel (excluded) on the shape we want compute the integral invariant Gaussiaan curvature.
[out] result iterator of results of the computation.
Definition at line 237 of file IntegralInvariantGaussianCurvatureEstimator.ih.
References DGtal::Trace::error(), and DGtal::trace.
 {
     trace.error() << "IntegralInvariantGaussianCurvatureEstimator@eval() : Not available yet.";
 }
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> template<typename SurfelIterator > DGtal::IntegralInvariantGaussianCurvatureEstimator<TKSpace, TShapeFunctor, dimension>::PrincipalCurvatures DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::evalPrincipalCurvatures (const SurfelIterator & it) inline
Definition at line 273 of file IntegralInvariantGaussianCurvatureEstimator.ih.
References DGtal::Trace::error(), and DGtal::trace.
 {
     PrincipalCurvatures measure;
     trace.error() << "IntegralInvariantGaussianCurvatureEstimator@eval() : Not available yet.";
     return measure;
 }
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> template<typename SurfelIterator > PrincipalCurvatures DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::evalPrincipalCurvatures (const SurfelIterator & it)
– Principal curvatures – Compute the integral invariant Gaussian curvature on surfel *it of a shape.
Template Parameters
SurfelIterator iterator on a Surfel
Parameters
[in] it iterator of a surfel (from a shape) we want compute the integral invariant principal curvatures.
Returns
a struct with principal curvatures value of Integral Invariant estimator at surfel *it, and eigenVectors and eigenValues resulting of the covariance matrix (see above: struct CurvatureInformations)
template<typename TKSpace , typename TShapeFunctor , DGtal::Dimension dimension> template<typename SurfelIterator , typename OutputIterator > void DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::evalPrincipalCurvatures (const SurfelIterator & itb, const SurfelIterator & ite, OutputIterator & result) inline
– Principal curvatures – Compute the integral invariant Gaussian curvature from two surfels (from *itb to *ite (exclude)) of a shape. Return the result on an OutputIterator (param).
Template Parameters
SurfelIterator iterator on a Surfel
OutputIterator iterator of array of PrincipalCurvatures
Parameters
[in] ite iterator of the begin surfel on the shape where we compute the integral invariant principal curvatures.
[in] itb iterator of the end surfel (excluded) on the shape where we compute the integral invariant principal curvatures.
[out] result iterator of structs with principal curvatures value of Integral Invariant estimator at surfel *it, and eigenVectors and eigenValues resulting of the covariance matrix (see above: struct CurvatureInformations)
Definition at line 307 of file IntegralInvariantGaussianCurvatureEstimator.ih.
References DGtal::Trace::error(), and DGtal::trace.
 {
     trace.error() << "IntegralInvariantGaussianCurvatureEstimator@eval() : Not available yet.";
     return;
 }
template<typename TKSpace , typename TShapeFunctor , DGtal::Dimension dimension> void DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::init (const double _h, const double re) inline
Initialise the estimator with a specific Euclidean kernel radius re, and grid step _h.
Parameters
[in] _h precision of the grid
[in] re Euclidean radius of the kernel support
Definition at line 71 of file IntegralInvariantGaussianCurvatureEstimator.ih.
References DGtal::Trace::error(), and DGtal::trace.
 {
     trace.error() << "Not available yet.";
 }
template<typename TKSpace , typename TShapeFunctor , DGtal::Dimension dimension> bool DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 373 of file IntegralInvariantGaussianCurvatureEstimator.ih.
 {
     return true;
 }
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> IntegralInvariantGaussianCurvatureEstimator& DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::operator= (const IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension > & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
template<typename TKSpace , typename TShapeFunctor , DGtal::Dimension dimension> void DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 344 of file IntegralInvariantGaussianCurvatureEstimator.ih.
 {
     out << "[IntegralInvariantGaussianCurvatureEstimator]";
 }
Field Documentation
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> DigitalShapeKernel* DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::digKernel private
Digital kernel.
Definition at line 456 of file IntegralInvariantGaussianCurvatureEstimator.h.
Referenced by DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::~IntegralInvariantGaussianCurvatureEstimator(), DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::~IntegralInvariantGaussianCurvatureEstimator(), and DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::~IntegralInvariantGaussianCurvatureEstimator().
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> ValuesFunctor DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::gaussFunctor private
Functor to transform covarianceMatrix to Quantity/PrincipalCurvatures.
Definition at line 466 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> double DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::h private
precision of the grid
Definition at line 462 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> KernelSupport* DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::kernel private
Euclidean kernel.
Definition at line 454 of file IntegralInvariantGaussianCurvatureEstimator.h.
Referenced by DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::~IntegralInvariantGaussianCurvatureEstimator(), DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::~IntegralInvariantGaussianCurvatureEstimator(), and DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::~IntegralInvariantGaussianCurvatureEstimator().
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> std::vector< PairIterators > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::kernels private
array of begin/end iterator of shifting masks.
Definition at line 450 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> std::vector< DigitalSet * > DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::kernelsSet private
Array of shifting masks. Size = 9 for each shifting (0-adjacent and full kernel included)
Definition at line 452 of file IntegralInvariantGaussianCurvatureEstimator.h.
Referenced by DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::~IntegralInvariantGaussianCurvatureEstimator(), DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 2 >::~IntegralInvariantGaussianCurvatureEstimator(), and DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, 3 >::~IntegralInvariantGaussianCurvatureEstimator().
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> Convolver DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::myConvolver private
Convolver.
Definition at line 460 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> const KernelSpelFunctor DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::myKernelFunctor private
Kernel functor (on Spel)
Definition at line 458 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> PrincipalCurvatureFunctor DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::princCurvFunctor private
Definition at line 467 of file IntegralInvariantGaussianCurvatureEstimator.h.
template<typename TKSpace, typename TShapeFunctor, Dimension dimension = TKSpace::dimension> double DGtal::IntegralInvariantGaussianCurvatureEstimator< TKSpace, TShapeFunctor, dimension >::radius private
Euclidean radius of the kernel.
Definition at line 464 of file IntegralInvariantGaussianCurvatureEstimator.h.
The documentation for this class was generated from the following files:
IntegralInvariantGaussianCurvatureEstimator.h
IntegralInvariantGaussianCurvatureEstimator.ih