DGtal: DGtal::DigitalSetBySTLVector< TDomain > Class Template Reference
DGtal::DigitalSetBySTLVector< TDomain > Class Template Reference
#include <DigitalSetBySTLVector.h>
Public Types
typedef TDomain Domain
typedef DigitalSetBySTLVector
< Domain > Self
typedef Domain::Space Space
typedef Domain::Point Point
typedef Domain::Size Size
typedef std::vector< Point >
::const_iterator Iterator
typedef std::vector< Point >
::const_iterator ConstIterator
typedef std::vector< Point >
::iterator MutableIterator
Public Member Functions
~DigitalSetBySTLVector ()
DigitalSetBySTLVector (Clone< Domain > d)
DigitalSetBySTLVector (const DigitalSetBySTLVector &other)
DigitalSetBySTLVector & operator= (const DigitalSetBySTLVector &other)
const Domain & domain () const
CowPtr< Domain > domainPointer () const
Size size () const
bool empty () const
void insert (const Point &p)
template<typename PointInputIterator >
void insert (PointInputIterator first, PointInputIterator last)
void insertNew (const Point &p)
template<typename PointInputIterator >
void insertNew (PointInputIterator first, PointInputIterator last)
Size erase (const Point &p)
void erase (Iterator it)
void erase (Iterator first, Iterator last)
void clear ()
ConstIterator find (const Point &p) const
Iterator find (const Point &p)
ConstIterator begin () const
ConstIterator end () const
Iterator begin ()
Iterator end ()
DigitalSetBySTLVector< Domain > & operator+= (const DigitalSetBySTLVector< Domain > &aSet)
bool operator() (const Point &p) const
template<typename TOutputIterator >
void computeComplement (TOutputIterator &ito) const
void assignFromComplement (const DigitalSetBySTLVector< Domain > &other_set)
void computeBoundingBox (Point &lower, Point &upper) const
void selfDisplay (std::ostream &out) const
bool isValid () const
std::string className () const
Protected Member Functions
DigitalSetBySTLVector ()
Protected Attributes
CowPtr< Domain > myDomain
std::vector< Point > myVector
Detailed Description
template<typename TDomain>
class DGtal::DigitalSetBySTLVector< TDomain >
Aim: Realizes the concept CDigitalSet by using the STL container std::vector.
Description of template class 'DigitalSetBySTLVector'
It thus describes a modifiable set of points within the given domain [Domain].
Template Parameters
TDomain a realization of the concept CDomain.
See Also
CDigitalSet,CDomain
Since
0.7 Domains are now hold with counted pointers and no more only aliased. The problem was related to returning sets with a locally constructed domain. With CountedPtr, you are sure that the domain remains valid during the lifetime of your set.
Definition at line 80 of file DigitalSetBySTLVector.h.
Member Typedef Documentation
template<typename TDomain> typedef std::vector<Point>::const_iterator DGtal::DigitalSetBySTLVector< TDomain >::ConstIterator
Definition at line 89 of file DigitalSetBySTLVector.h.
template<typename TDomain> typedef TDomain DGtal::DigitalSetBySTLVector< TDomain >::Domain
Definition at line 83 of file DigitalSetBySTLVector.h.
template<typename TDomain> typedef std::vector<Point>::const_iterator DGtal::DigitalSetBySTLVector< TDomain >::Iterator
Definition at line 88 of file DigitalSetBySTLVector.h.
template<typename TDomain> typedef std::vector<Point>::iterator DGtal::DigitalSetBySTLVector< TDomain >::MutableIterator
Definition at line 90 of file DigitalSetBySTLVector.h.
template<typename TDomain> typedef Domain::Point DGtal::DigitalSetBySTLVector< TDomain >::Point
Definition at line 86 of file DigitalSetBySTLVector.h.
template<typename TDomain> typedef DigitalSetBySTLVector<Domain> DGtal::DigitalSetBySTLVector< TDomain >::Self
Definition at line 84 of file DigitalSetBySTLVector.h.
template<typename TDomain> typedef Domain::Size DGtal::DigitalSetBySTLVector< TDomain >::Size
Definition at line 87 of file DigitalSetBySTLVector.h.
template<typename TDomain> typedef Domain::Space DGtal::DigitalSetBySTLVector< TDomain >::Space
Definition at line 85 of file DigitalSetBySTLVector.h.
Constructor & Destructor Documentation
template<typename Domain > DGtal::DigitalSetBySTLVector< Domain >::~DigitalSetBySTLVector () inline
Destructor.
Definition at line 47 of file DigitalSetBySTLVector.ih.
 {
 }
template<typename Domain > DGtal::DigitalSetBySTLVector< Domain >::DigitalSetBySTLVector (Clone< Domain > d) inline
Constructor. Creates the empty set in the domain [d].
Parameters
d any domain.
Definition at line 60 of file DigitalSetBySTLVector.ih.
   : myDomain( d ), myVector()
 {
 }
template<typename Domain > DGtal::DigitalSetBySTLVector< Domain >::DigitalSetBySTLVector (const DigitalSetBySTLVector< TDomain > & other) inline
Copy constructor.
Parameters
other the object to clone.
Definition at line 72 of file DigitalSetBySTLVector.ih.
   : myDomain( other.myDomain ), myVector( other.myVector )
 {
 }
template<typename TDomain> DGtal::DigitalSetBySTLVector< TDomain >::DigitalSetBySTLVector () protected
Default Constructor. Forbidden since a Domain is necessary for defining a set.
Member Function Documentation
template<typename Domain > void DGtal::DigitalSetBySTLVector< Domain >::assignFromComplement (const DigitalSetBySTLVector< Domain > & other_set) inline
Builds the complement in the domain of the set [other_set] in this.
Parameters
other_set defines the set whose complement is assigned to 'this'.
Definition at line 448 of file DigitalSetBySTLVector.ih.
References DGtal::DigitalSetBySTLVector< TDomain >::begin(), and DGtal::DigitalSetBySTLVector< TDomain >::end().
 {
   clear();
   typename Domain::ConstIterator itPoint = domain().begin();
   typename Domain::ConstIterator itEnd = domain().end();
   while ( itPoint != itEnd ) {
     if ( std::find( other_set.begin(),
         other_set.end(),
         *itPoint ) == other_set.end() ) {
       insert( *itPoint );
     }
     ++itPoint;
   }
 }
template<typename Domain > DGtal::DigitalSetBySTLVector< Domain >::ConstIterator DGtal::DigitalSetBySTLVector< Domain >::begin () const inline
Returns
a const iterator on the first element in this set.
Definition at line 342 of file DigitalSetBySTLVector.ih.
Referenced by DGtal::DigitalSetBySTLVector< TDomain >::assignFromComplement(), DGtal::Display2DFactory::draw(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsGrid(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPaving(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingTransparent().
 {
   return myVector.begin();
 }
template<typename Domain > DGtal::DigitalSetBySTLVector< Domain >::Iterator DGtal::DigitalSetBySTLVector< Domain >::begin () inline
Returns
an iterator on the first element in this set.
Definition at line 365 of file DigitalSetBySTLVector.ih.
 {
   return myVector.begin();
 }
template<typename Domain > std::string DGtal::DigitalSetBySTLVector< Domain >::className () const inline
Default drawing style object.
Returns
the dyn. alloc. default style for this object.
the style name used for drawing this object.
the style name used for drawing this object.
Definition at line 532 of file DigitalSetBySTLVector.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPaving(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingTransparent().
 {
   return "DigitalSetBySTLVector";
 }
template<typename Domain > void DGtal::DigitalSetBySTLVector< Domain >::clear () inline
Clears the set.
Postcondition
this set is empty.
Definition at line 300 of file DigitalSetBySTLVector.ih.
 {
   myVector.clear();
 }
template<typename Domain > void DGtal::DigitalSetBySTLVector< Domain >::computeBoundingBox (Point & lower, Point & upper) const inline
Computes the bounding box of this set.
Parameters
lower the first point of the bounding box (lowest in all directions).
upper the last point of the bounding box (highest in all directions).
Definition at line 475 of file DigitalSetBySTLVector.ih.
 {
   if ( begin() != end() )
     {
       ConstIterator it = begin();
       ConstIterator it_end = end();
       upper = lower = *it;
       for ( ; it != it_end; ++it )
   if ( it->isLower( lower ) ) lower = *it;
   else if ( it->isUpper( upper ) ) upper = *it;
     }
   else
     {
       lower = domain().upperBound();
       upper = domain().lowerBound();
     }
 }
template<typename Domain > template<typename TOutputIterator > void DGtal::DigitalSetBySTLVector< Domain >::computeComplement (TOutputIterator & ito) const inline
Computes the complement in the domain of this set
Parameters
ito an output iterator
Template Parameters
TOutputIterator a model of output iterator
Definition at line 426 of file DigitalSetBySTLVector.ih.
 {
   typename Domain::ConstIterator itPoint = domain().begin();
   typename Domain::ConstIterator itEnd = domain().end();
   while ( itPoint != itEnd ) {
     if ( std::find( begin(), end(), *itPoint ) == end() ) {
       *ito++ = *itPoint;
     }
     ++itPoint;
   }
 }
template<typename Domain > const Domain & DGtal::DigitalSetBySTLVector< Domain >::domain () const inline
Returns
the embedding domain.
Definition at line 102 of file DigitalSetBySTLVector.ih.
Referenced by DGtal::DigitalSetBySTLVector< TDomain >::operator=().
 {
   return *myDomain;
 }
template<typename Domain > DGtal::CowPtr< Domain > DGtal::DigitalSetBySTLVector< Domain >::domainPointer () const inline
Returns
a copy-on-write pointer on the embedding domain.
Definition at line 110 of file DigitalSetBySTLVector.ih.
 {
   return myDomain;
 }
template<typename Domain > bool DGtal::DigitalSetBySTLVector< Domain >::empty () const inline
Returns
'true' iff the set is empty (no element).
Definition at line 136 of file DigitalSetBySTLVector.ih.
 {
   return myVector.empty();
 }
template<typename Domain > DGtal::DigitalSetBySTLVector< Domain >::ConstIterator DGtal::DigitalSetBySTLVector< Domain >::end () const inline
Returns
a const iterator on the element after the last in this set.
Definition at line 353 of file DigitalSetBySTLVector.ih.
Referenced by DGtal::DigitalSetBySTLVector< TDomain >::assignFromComplement(), DGtal::Display2DFactory::draw(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsGrid(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPaving(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingTransparent().
 {
   return myVector.end();
 }
template<typename Domain > DGtal::DigitalSetBySTLVector< Domain >::Iterator DGtal::DigitalSetBySTLVector< Domain >::end () inline
Returns
a iterator on the element after the last in this set.
Definition at line 377 of file DigitalSetBySTLVector.ih.
 {
   return myVector.end();
 }
template<typename Domain > DGtal::DigitalSetBySTLVector< Domain >::Size DGtal::DigitalSetBySTLVector< Domain >::erase (const Point & p) inline
Removes point [p] from the set.
Parameters
p the point to remove.
Returns
the number of removed elements (0 or 1).
Definition at line 233 of file DigitalSetBySTLVector.ih.
 {
   Iterator it = find( p );
   if ( it != end() )
     {
       erase( it );
       return 1;
     }
   return 0;
 }
template<typename Domain > void DGtal::DigitalSetBySTLVector< Domain >::erase (Iterator it) inline
Removes the point pointed by [it] from the set.
Parameters
it an iterator on this set.
Precondition
it should point on a valid element (it != end()). Note: generally faster than giving just the point.
Definition at line 254 of file DigitalSetBySTLVector.ih.
 {
   //take a mutable iterator
   typename std::iterator_traits<Iterator>::difference_type d = it - this->begin();
   typename std::vector<Point>::iterator it2 = myVector.begin() + d;
   //swap
   *it2 = myVector.back();
   myVector.pop_back();
 }
template<typename Domain > void DGtal::DigitalSetBySTLVector< Domain >::erase (Iterator first, Iterator last) inline
Removes the collection of points specified by the two iterators from this set.
Parameters
first the start point in this set.
last the last point in this set.
Definition at line 274 of file DigitalSetBySTLVector.ih.
 {
   while ( ( last != end() )
     && ( first != last ) )
     {
       //take a mutable iterator
       typename std::iterator_traits<Iterator>::difference_type d = first - this->begin();
       typename std::vector<Point>::iterator first2 = myVector.begin() + d;
       //swap
       *first2 = myVector.back();
       myVector.pop_back();
       //advance
       first++;
     }
   if ( first != last )
     while ( first != end() )
       myVector.pop_back();
 }
template<typename Domain > DGtal::DigitalSetBySTLVector< Domain >::ConstIterator DGtal::DigitalSetBySTLVector< Domain >::find (const Point & p) const inline
Parameters
p any digital point.
Returns
a const iterator pointing on [p] if found, otherwise end().
Definition at line 312 of file DigitalSetBySTLVector.ih.
 {
   const ConstIterator it_end = end();
   for ( ConstIterator it = begin(); it != it_end; ++it )
     if ( p == *it ) return it;
   return it_end;
 }
template<typename Domain > DGtal::DigitalSetBySTLVector< Domain >::Iterator DGtal::DigitalSetBySTLVector< Domain >::find (const Point & p) inline
Parameters
p any digital point.
Returns
an iterator pointing on [p] if found, otherwise end().
Definition at line 327 of file DigitalSetBySTLVector.ih.
 {
   const Iterator it_end = end();
   for ( Iterator it = begin(); it != it_end; ++it )
     if ( p == *it ) return it;
   return it_end;
 }
template<typename Domain > void DGtal::DigitalSetBySTLVector< Domain >::insert (const Point & p) inline
Adds point [p] to this set.
Parameters
p any digital point.
Precondition
p should belong to the associated domain.
Definition at line 150 of file DigitalSetBySTLVector.ih.
 {
   // ASSERT( domain().isInside( p ) );
   Iterator it = find( p );
   if ( it == end() )
     myVector.push_back( p );
 }
template<typename Domain > template<typename PointInputIterator > void DGtal::DigitalSetBySTLVector< Domain >::insert (PointInputIterator first, PointInputIterator last) inline
Adds the collection of points specified by the two iterators to this set.
Parameters
first the start point in the collection of Point.
last the last point in the collection of Point.
Precondition
all points should belong to the associated domain.
Definition at line 171 of file DigitalSetBySTLVector.ih.
 {
   for ( ; first != last; ++first )
     insert( *first );
 }
template<typename Domain > void DGtal::DigitalSetBySTLVector< Domain >::insertNew (const Point & p) inline
Adds point [p] to this set if the point is not already in the set. There is no defined behavior if the point is already in the set (for instance, may be present twice).
Parameters
p any digital point.
Precondition
p should belong to the associated domain.
p should not belong to this.
Definition at line 190 of file DigitalSetBySTLVector.ih.
 {
   // ASSERT( domain().isInside( p ) );
   ASSERT( find( p ) == end() );
   myVector.push_back( p );
 }
template<typename Domain > template<typename PointInputIterator > void DGtal::DigitalSetBySTLVector< Domain >::insertNew (PointInputIterator first, PointInputIterator last) inline
Adds the collection of points specified by the two iterators to this set. The collection should contain distinct points. Each of these points should also not belong already to the set. set. There is no defined behavior if the preceding requisites are not satisfied (for instance, points may be present several times in the set).
Parameters
first the start point in the collection of Point.
last the last point in the collection of Point.
Precondition
all points should belong to the associated domain.
each point should not belong to this.
Definition at line 216 of file DigitalSetBySTLVector.ih.
 {
   while ( first != last )
     myVector.push_back( *first++ );
   // std::copy( first, last, myVector.end() );
 }
template<typename Domain > bool DGtal::DigitalSetBySTLVector< Domain >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 516 of file DigitalSetBySTLVector.ih.
 {
     return true;
 }
template<typename Domain > bool DGtal::DigitalSetBySTLVector< Domain >::operator() (const Point & p) const inline
Parameters
p any point.
Returns
'true' if and only if p belongs to this set.
Definition at line 412 of file DigitalSetBySTLVector.ih.
 {
   return find( p ) != end();
 }
template<typename Domain > DGtal::DigitalSetBySTLVector< Domain > & DGtal::DigitalSetBySTLVector< Domain >::operator+= (const DigitalSetBySTLVector< Domain > & aSet) inline
set union to left.
Parameters
aSet any other set.
Definition at line 390 of file DigitalSetBySTLVector.ih.
References DGtal::DigitalSetBySTLVector< TDomain >::myVector.
 {
   if ( this != &aSet )
     {
       std::vector<Point> other( aSet.myVector );
       std::stable_sort( other.begin(), other.end() );
       std::stable_sort( myVector.begin(), myVector.end() );
       std::vector<Point> new_vector;
       new_vector.reserve( size() + other.size() );
       std::set_union( begin(), end(), other.begin(), other.end(),
           std::back_insert_iterator< std::vector<Point> >
           ( new_vector ) );
       myVector.swap( new_vector );
     }
   return *this;
 }
template<typename Domain > DGtal::DigitalSetBySTLVector< Domain > & DGtal::DigitalSetBySTLVector< Domain >::operator= (const DigitalSetBySTLVector< TDomain > & other) inline
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'.
Definition at line 86 of file DigitalSetBySTLVector.ih.
References DGtal::DigitalSetBySTLVector< TDomain >::domain(), and DGtal::DigitalSetBySTLVector< TDomain >::myVector.
 {
   ASSERT( ( domain().lowerBound() <= other.domain().lowerBound() )
     && ( domain().upperBound() >= other.domain().upperBound() )
     && "This domain should include the domain of the other set in case of assignment." );
   myVector = other.myVector;
   return *this;
 }
template<typename Domain > void DGtal::DigitalSetBySTLVector< Domain >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 504 of file DigitalSetBySTLVector.ih.
 {
   out << "[DigitalSetBySTLVector]" << " size=" << size();
 }
template<typename Domain > DGtal::DigitalSetBySTLVector< Domain >::Size DGtal::DigitalSetBySTLVector< Domain >::size () const inline
Returns
the number of elements in the set.
Definition at line 125 of file DigitalSetBySTLVector.ih.
 {
   return (unsigned int)myVector.size();
 }
Field Documentation
template<typename TDomain> CowPtr<Domain> DGtal::DigitalSetBySTLVector< TDomain >::myDomain protected
The associated domain. The pointed domain may be changed but it remains valid during the lifetime of the set.
Definition at line 323 of file DigitalSetBySTLVector.h.
template<typename TDomain> std::vector<Point> DGtal::DigitalSetBySTLVector< TDomain >::myVector protected
The container storing the points of the set.
Definition at line 328 of file DigitalSetBySTLVector.h.
Referenced by DGtal::DigitalSetBySTLVector< TDomain >::operator+=(), and DGtal::DigitalSetBySTLVector< TDomain >::operator=().
The documentation for this class was generated from the following files:
DigitalSetBySTLVector.h
DigitalSetBySTLVector.ih