DGtal: DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency > Class Template Reference
DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency > Class Template Reference
#include <ArithmeticalDSSComputer.h>
Public Types
typedef TIterator ConstIterator
typedef
IteratorCirculatorTraits
< ConstIterator >::Value Point
typedef
IteratorCirculatorTraits
< TIterator >
::Value::Coordinate Coordinate
typedef TInteger Integer
typedef ArithmeticalDSS
< Coordinate, Integer,
adjacency > DSS
typedef DSS Primitive
typedef Point Vector
typedef
ArithmeticalDSSComputer
< ConstIterator, TInteger,
adjacency > Self
typedef
ArithmeticalDSSComputer
< ReverseIterator
< ConstIterator >, TInteger,
adjacency > Reverse
Public Member Functions
BOOST_CONCEPT_ASSERT ((boost_concepts::ReadableIteratorConcept< ConstIterator >))
BOOST_CONCEPT_ASSERT ((boost_concepts::ForwardTraversalConcept< ConstIterator >))
BOOST_STATIC_ASSERT ((Point::dimension==2))
BOOST_CONCEPT_ASSERT ((CInteger< Coordinate >))
BOOST_CONCEPT_ASSERT ((CInteger< Integer >))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Point, typename DSS::Point >::value))
ArithmeticalDSSComputer ()
ArithmeticalDSSComputer (const ConstIterator &it)
void init (const ConstIterator &it)
ArithmeticalDSSComputer (const ArithmeticalDSSComputer &other)
ArithmeticalDSSComputer & operator= (const ArithmeticalDSSComputer &other)
Self getSelf () const
Reverse getReverse () const
bool operator== (const ArithmeticalDSSComputer &other) const
bool operator!= (const ArithmeticalDSSComputer &other) const
~ArithmeticalDSSComputer ()
bool isExtendableFront ()
bool isExtendableBack ()
bool extendFront ()
bool extendBack ()
bool retractFront ()
bool retractBack ()
const Primitive & primitive () const
Integer a () const
Integer b () const
Integer mu () const
Integer omega () const
Point Uf () const
Point Ul () const
Point Lf () const
Point Ll () const
Point back () const
Point front () const
ConstIterator begin () const
ConstIterator end () const
bool isValid () const
Integer remainder (const ConstIterator &it) const
Integer remainder (const Point &aPoint) const
Integer position (const ConstIterator &it) const
Integer position (const Point &aPoint) const
bool isInDSL (const Point &aPoint) const
bool isInDSL (const ConstIterator &it) const
bool isInDSS (const Point &aPoint) const
bool isInDSS (const ConstIterator &it) const
void selfDisplay (std::ostream &out)
Protected Attributes
DSS myDSS
ConstIterator myBegin
ConstIterator myEnd
Detailed Description
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8>
class DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >
Aim: This class is a wrapper around ArithmeticalDSS that is devoted to the dynamic recognition of digital straight segments (DSS) along any sequence of digital points.
See Digital straight lines and segments. for further details. See also classes NaiveDSS8Computer and StandardDSS4Computer, which are aliases of this class.
Template Parameters
TIterator type of iterator on 2d digital points, at least readable and forward.
TInteger type of integers used for the computation of remainders, which is a model of CInteger.
adjacency an unsigned integer equal to 4 for standard (simply 4-connected) DSS or 8 for naive (simply 8-connected) DSS (default).
This class is a model of CDynamicBidirectionalSegmentComputer. It is also default constructible, copy constructible, assignable and equality comparable.
See Also
ArithmeticalDSS NaiveDSS StandardDSS
exampleArithmeticalDSS.cpp exampleArithmeticalDSSComputer.cpp
Examples:
geometry/curves/greedy-dss-decomposition.cpp.
Definition at line 86 of file ArithmeticalDSSComputer.h.
Member Typedef Documentation
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> typedef TIterator DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::ConstIterator
Type of iterator, at least readable and forward
Definition at line 95 of file ArithmeticalDSSComputer.h.
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> typedef IteratorCirculatorTraits<TIterator>::Value::Coordinate DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Coordinate
Type of coordinate
Definition at line 108 of file ArithmeticalDSSComputer.h.
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> typedef ArithmeticalDSS<Coordinate, Integer, adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::DSS
Type of objects that represents DSSs
Definition at line 120 of file ArithmeticalDSSComputer.h.
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> typedef TInteger DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Integer
Type of integer, devoted to remainders (and intercepts)
Definition at line 114 of file ArithmeticalDSSComputer.h.
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> typedef IteratorCirculatorTraits<ConstIterator>::Value DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Point
Type of 2d digital point
Definition at line 102 of file ArithmeticalDSSComputer.h.
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> typedef DSS DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Primitive
Type of primitive representation, defined as an alias of DSS
Definition at line 127 of file ArithmeticalDSSComputer.h.
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> typedef ArithmeticalDSSComputer<ReverseIterator<ConstIterator>,TInteger,adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Reverse
Definition at line 135 of file ArithmeticalDSSComputer.h.
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> typedef ArithmeticalDSSComputer<ConstIterator,TInteger,adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Self
Definition at line 134 of file ArithmeticalDSSComputer.h.
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> typedef Point DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Vector
Type of vector, defined as an alias of point
Definition at line 132 of file ArithmeticalDSSComputer.h.
Constructor & Destructor Documentation
template<typename TIterator , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::ArithmeticalDSSComputer () inline
Default constructor. not valid
Definition at line 49 of file ArithmeticalDSSComputer.ih.
   : myDSS( Point(0,0) ), myBegin(), myEnd()
 {
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::ArithmeticalDSSComputer (const ConstIterator & it) inline
Constructor with initialisation
Parameters
it an iterator on 2D points
See Also
init
Definition at line 59 of file ArithmeticalDSSComputer.ih.
References DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::myEnd.
   : myDSS( *it ), myBegin(it), myEnd(it)
 {
   ++myEnd;
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::ArithmeticalDSSComputer (const ArithmeticalDSSComputer< TIterator, TInteger, adjacency > & other) inline
Copy constructor.
Parameters
other the object to clone.
Definition at line 82 of file ArithmeticalDSSComputer.ih.
   : myDSS(other.myDSS), myBegin(other.myBegin), myEnd(other.myEnd)
 {
 }
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::~ArithmeticalDSSComputer () inline
Destructor.
Definition at line 202 of file ArithmeticalDSSComputer.h.
 {};
Member Function Documentation
template<typename TIterator , typename TInteger , unsigned short adjacency> TInteger DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::a () const inline
Returns
a-parameter of the DSS
Definition at line 318 of file ArithmeticalDSSComputer.ih.
 {
   return myDSS.a();
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> TInteger DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::b () const inline
Returns
b-parameter of the DSS
Definition at line 327 of file ArithmeticalDSSComputer.ih.
 {
   return myDSS.b();
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Point DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::back () const inline
Returns
the first point of the DSS.
Definition at line 390 of file ArithmeticalDSSComputer.ih.
 {
   return myDSS.back();
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> TIterator DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::begin () const inline
Returns
begin iterator of the DSS range.
Definition at line 408 of file ArithmeticalDSSComputer.ih.
 {
   return myBegin;
 }
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::BOOST_CONCEPT_ASSERT ((boost_concepts::ReadableIteratorConcept< ConstIterator >))
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::BOOST_CONCEPT_ASSERT ((boost_concepts::ForwardTraversalConcept< ConstIterator >))
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::BOOST_CONCEPT_ASSERT ((CInteger< Coordinate >))
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::BOOST_CONCEPT_ASSERT ((CInteger< Integer >))
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::BOOST_STATIC_ASSERT ((Point::dimension==2))
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Point, typename DSS::Point >::value))
template<typename TIterator , typename TInteger , unsigned short adjacency> TIterator DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::end () const inline
Returns
end iterator of the DSS range.
Definition at line 417 of file ArithmeticalDSSComputer.ih.
Referenced by DGtal::FP< TIterator, TInteger, connectivity >::algorithm().
 {
   return myEnd;
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::extendBack () inline
Tests whether the current DSS can be extended at the back. Computes the parameters of the extended DSS if yes.
Returns
'true' if yes, 'false' otherwise.
Definition at line 187 of file ArithmeticalDSSComputer.ih.
Referenced by DGtal::FP< TIterator, TInteger, connectivity >::algorithm().
 {
   ConstIterator it = myBegin;
   --it;
   if (myDSS.extendBack(*it))
     {
       myBegin = it;
       return true;
     }
   else
     return false;
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::extendFront () inline
Tests whether the current DSS can be extended at the front. Computes the parameters of the extended DSS if yes.
Returns
'true' if yes, 'false' otherwise.
Definition at line 172 of file ArithmeticalDSSComputer.ih.
Referenced by DGtal::FP< TIterator, TInteger, connectivity >::algorithm().
 {
   if (myDSS.extendFront(*myEnd))
     {
       ++myEnd;
       return true;
     }
   else
     return false;
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Point DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::front () const inline
Returns
the last point of the DSS.
Definition at line 399 of file ArithmeticalDSSComputer.ih.
 {
   return myDSS.front();
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Reverse DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::getReverse () const inline
Returns
a default-constructed instance of Reverse
Definition at line 108 of file ArithmeticalDSSComputer.ih.
 {
   return Reverse();
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Self DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::getSelf () const inline
Returns
a default-constructed instance of Self
Definition at line 118 of file ArithmeticalDSSComputer.ih.
 {
   return Self();
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> void DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::init (const ConstIterator & it) inline
Initialisation.
Parameters
it an iterator on 2D points
Definition at line 69 of file ArithmeticalDSSComputer.ih.
Referenced by DGtal::FP< TIterator, TInteger, connectivity >::algorithm().
 {
   myBegin = it;
   myEnd = it;
   ++myEnd;
   Point p = *it;
   myDSS = DSS( p );
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::isExtendableBack () inline
Tests whether the current DSS can be extended at the back.
Returns
'true' if yes, 'false' otherwise.
Definition at line 161 of file ArithmeticalDSSComputer.ih.
 {
   ConstIterator it = myBegin;
   --it;
   return myDSS.isExtendableBack( *it );
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::isExtendableFront () inline
Tests whether the current DSS can be extended at the front.
Returns
'true' if yes, 'false' otherwise.
Definition at line 152 of file ArithmeticalDSSComputer.ih.
 {
   return myDSS.isExtendableFront( *myEnd );
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::isInDSL (const Point & aPoint) const inline
Checks whether a point is in the bounding DSL of minimal parameters
Parameters
aPoint the point to be checked
Returns
'true' if yes, 'false' otherwise
Definition at line 282 of file ArithmeticalDSSComputer.ih.
 {
   return myDSS.isInDSL( aPoint );
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::isInDSL (const ConstIterator & it) const inline
Checks whether a point is in the bounding DSL of minimal parameters
Parameters
it an iterator on the point to be checked
Returns
'true' if yes, 'false' otherwise
Definition at line 291 of file ArithmeticalDSSComputer.ih.
 {
   return isInDSL(*it);
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::isInDSS (const Point & aPoint) const inline
Checks whether a point belongs to the DSS or not
Parameters
aPoint the point to be checked
Returns
'true' if yes, 'false' otherwise
Definition at line 300 of file ArithmeticalDSSComputer.ih.
 {
   return myDSS.isInDSS( aPoint );
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::isInDSS (const ConstIterator & it) const inline
Checks whether a point belongs to the DSS or not
Parameters
it an iterator on the point to be checked
Returns
'true' if yes, 'false' otherwise
Definition at line 309 of file ArithmeticalDSSComputer.ih.
 {
   return isInDSS(*it);
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 426 of file ArithmeticalDSSComputer.ih.
References DGtal::isNotEmpty().
 {
   return ( (myDSS.isValid())&&(isNotEmpty(myBegin,myEnd)) );
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Point DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Lf () const inline
Returns
first lower leaning point.
Definition at line 372 of file ArithmeticalDSSComputer.ih.
Referenced by DGtal::FP< TIterator, TInteger, connectivity >::algorithm().
 {
   return myDSS.Lf();
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Point DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Ll () const inline
Returns
last lower leaning point.
Definition at line 381 of file ArithmeticalDSSComputer.ih.
 {
   return myDSS.Ll();
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> TInteger DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::mu () const inline
Returns
mu-parameter of the DSS
Definition at line 336 of file ArithmeticalDSSComputer.ih.
 {
   return myDSS.mu();
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> TInteger DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::omega () const inline
Returns
omega-parameter of the DSS
Definition at line 345 of file ArithmeticalDSSComputer.ih.
 {
   return myDSS.omega();
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::operator!= (const ArithmeticalDSSComputer< TIterator, TInteger, adjacency > & other) const inline
Difference operator.
Parameters
other the object to compare with.
Returns
'false' if equal 'true' otherwise
Definition at line 140 of file ArithmeticalDSSComputer.ih.
 {
   return (!(*this == other));
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency > & DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::operator= (const ArithmeticalDSSComputer< TIterator, TInteger, adjacency > & other) inline
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'.
Definition at line 92 of file ArithmeticalDSSComputer.ih.
References DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::myBegin, DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::myDSS, and DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::myEnd.
 {
   if ( this != &other )
     {
       myDSS = other.myDSS;
       myBegin = other.myBegin;
       myEnd = other.myEnd;
     }
   return *this;
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::operator== (const ArithmeticalDSSComputer< TIterator, TInteger, adjacency > & other) const inline
Equality operator.
Parameters
other the object to compare with.
Returns
'true' if the DSS representations and the ranges of the two objects match, 'false' otherwise
Definition at line 128 of file ArithmeticalDSSComputer.ih.
References DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::myBegin, DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::myDSS, and DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::myEnd.
 {
   return ( (myBegin == other.myBegin)
            && (myEnd == other.myEnd)
            && (myDSS == other.myDSS) );
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> TInteger DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::position (const ConstIterator & it) const inline
Computes the position of a point (that does not necessarily belong to the DSS)
Parameters
it an iterator on points
Returns
the position of *it.
Definition at line 273 of file ArithmeticalDSSComputer.ih.
 {
   return position(*it);
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> TInteger DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::position (const Point & aPoint) const inline
Computes the position of a point (that does not necessarily belong to the DSS)
Parameters
aPoint the point whose position is returned
Returns
the position of aPoint.
Definition at line 264 of file ArithmeticalDSSComputer.ih.
 {
   return myDSS.position( aPoint );
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> const DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Primitive & DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::primitive () const inline
Returns
the current DSS representation. NB: since we return a const reference, you must copy the result, if you want to keep it beyond the object's existence.
Definition at line 237 of file ArithmeticalDSSComputer.ih.
 {
   return myDSS;
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> TInteger DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::remainder (const ConstIterator & it) const inline
Computes the remainder of a point (that does not necessarily belong to the DSS)
Parameters
it an iterator on points
Returns
the remainder of *it.
Definition at line 255 of file ArithmeticalDSSComputer.ih.
 {
   return remainder(*it);
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> TInteger DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::remainder (const Point & aPoint) const inline
Computes the remainder of a point (that does not necessarily belong to the DSS)
Parameters
aPoint the point whose remainder is returned
Returns
the remainder
Definition at line 246 of file ArithmeticalDSSComputer.ih.
 {
   return myDSS.remainder( aPoint );
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::retractBack () inline
Removes the back point of the DSS if it has more than two points
Returns
'true' if the back point is removed, 'false' otherwise.
Definition at line 219 of file ArithmeticalDSSComputer.ih.
Referenced by DGtal::FP< TIterator, TInteger, connectivity >::algorithm().
 {
   if (myDSS.retractBack())
     {
       ++myBegin;
       return true;
     }
   else
     return false;
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::retractFront () inline
Removes the front point of the DSS if it has more than two points
Returns
'true' if the front point is removed, 'false' otherwise.
Definition at line 204 of file ArithmeticalDSSComputer.ih.
 {
   if (myDSS.retractFront())
     {
       --myEnd;
       return true;
     }
   else
     return false;
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> void DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::selfDisplay (std::ostream & out) inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 435 of file ArithmeticalDSSComputer.ih.
 {
   out << "[ArithmeticalDSSComputer] " << myDSS;
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Point DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Uf () const inline
Returns
first upper leaning point.
Definition at line 354 of file ArithmeticalDSSComputer.ih.
Referenced by DGtal::FP< TIterator, TInteger, connectivity >::algorithm().
 {
   return myDSS.Uf();
 }
template<typename TIterator , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Point DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::Ul () const inline
Returns
last upper leaning point.
Definition at line 363 of file ArithmeticalDSSComputer.ih.
 {
   return myDSS.Ul();
 }
Field Documentation
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> ConstIterator DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::myBegin protected
begin iterator
Definition at line 393 of file ArithmeticalDSSComputer.h.
Referenced by DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::operator=(), and DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::operator==().
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> DSS DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::myDSS protected
DSS representation
Definition at line 389 of file ArithmeticalDSSComputer.h.
Referenced by DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::operator=(), and DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::operator==().
template<typename TIterator, typename TInteger = typename IteratorCirculatorTraits<TIterator>::Value::Coordinate, unsigned short adjacency = 8> ConstIterator DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::myEnd protected
end iterator
Definition at line 397 of file ArithmeticalDSSComputer.h.
Referenced by DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::ArithmeticalDSSComputer(), DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::operator=(), and DGtal::ArithmeticalDSSComputer< TIterator, TInteger, adjacency >::operator==().
The documentation for this class was generated from the following files:
ArithmeticalDSSComputer.h
ArithmeticalDSSComputer.ih