DGtal: DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar > Class Template Reference
DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar > Class Template Reference
#include <ChordNaivePlaneComputer.h>
Data Structures
struct State
Public Types
typedef TSpace Space
typedef TInputPoint InputPoint
typedef TInternalScalar InternalScalar
typedef InputPoint InputVector
typedef InputVector::Component Component
typedef InputPoint::Coordinate Coordinate
typedef PointVector
< 3, InternalScalar > InternalVector
typedef std::set< InputPoint > InputPointSet
typedef InputPointSet::size_type Size
typedef
InputPointSet::const_iterator ConstIterator
typedef InputPointSet::iterator Iterator
typedef Space::Point Point
typedef ParallelStrip< Space,
true, true > Primitive
typedef
InputPointSet::const_iterator const_iterator
typedef
InputPointSet::const_pointer const_pointer
typedef
InputPointSet::const_reference const_reference
typedef InputPointSet::value_type value_type
typedef
InputPointSet::difference_type difference_type
typedef InputPointSet::size_type size_type
Public Member Functions
~ChordNaivePlaneComputer ()
ChordNaivePlaneComputer ()
ChordNaivePlaneComputer (const ChordNaivePlaneComputer &other)
ChordNaivePlaneComputer & operator= (const ChordNaivePlaneComputer &other)
void clear ()
void init (Dimension axis, InternalScalar widthNumerator=NumberTraits< InternalScalar >::ONE, InternalScalar widthDenominator=NumberTraits< InternalScalar >::ONE)
Size size () const
bool empty () const
ConstIterator begin () const
ConstIterator end () const
Size max_size () const
Size maxSize () const
bool operator() (const Point &p) const
bool extendAsIs (const InputPoint &p)
bool extend (const InputPoint &p)
bool isExtendable (const InputPoint &p) const
template<typename TInputIterator >
bool extend (TInputIterator itB, TInputIterator itE)
template<typename TInputIterator >
bool isExtendable (TInputIterator itB, TInputIterator itE) const
template<typename TInputIterator >
bool satisfies (TInputIterator itB, TInputIterator itE) const
template<typename TInputIterator >
std::pair< InternalScalar,
InternalScalar > axisWidth (TInputIterator itB, TInputIterator itE) const
Primitive primitive () const
template<typename Vector3D >
void getNormal (Vector3D &normal) const
const InternalVector & exactNormal () const
template<typename Vector3D >
void getUnitNormal (Vector3D &normal) const
void getBounds (double &min, double &max) const
const InputPoint & minimalPoint () const
const InputPoint & maximalPoint () const
void selfDisplay (std::ostream &out) const
bool isValid () const
template<typename TInputIterator >
std::pair< TInternalScalar,
TInternalScalar > computeAxisWidth (Dimension axis, TInputIterator itB, TInputIterator itE)
template<typename TInputIterator >
std::pair< TInternalScalar,
TInternalScalar > axisWidth (State &state, TInputIterator itB, TInputIterator itE) const
template<typename TInputIterator >
std::pair< TInternalScalar,
TInternalScalar > axisWidth (TInputIterator itB, TInputIterator itE) const
template<typename TVector1 , typename TVector2 >
DGtal::ChordNaivePlaneComputer
< TSpace, TInputPoint,
TInternalScalar >
::InternalScalar internalDot (const TVector1 &u, const TVector2 &v)
Static Public Member Functions
template<typename TInputIterator >
static std::pair
< InternalScalar,
InternalScalar > computeAxisWidth (Dimension axis, TInputIterator itB, TInputIterator itE)
template<typename TVector1 , typename TVector2 >
static InternalScalar internalDot (const TVector1 &u, const TVector2 &v)
template<typename TVector1 , typename TVector2 >
static void internalCross (InternalVector &n, const TVector1 &u, const TVector2 &v)
Private Member Functions
BOOST_CONCEPT_ASSERT ((CSpace< TSpace >))
BOOST_CONCEPT_ASSERT ((CSignedNumber< TInternalScalar >))
BOOST_STATIC_ASSERT ((TSpace::dimension==3))
BOOST_STATIC_ASSERT ((TInputPoint::dimension==3))
template<typename TInputIterator >
void computeMinMax (State &state, TInputIterator itB, TInputIterator itE) const
template<typename TInputIterator >
bool updateMinMax (State &state, TInputIterator itB, TInputIterator itE) const
bool checkPlaneWidth (const State &state) const
bool setUp1 (const InputPoint &p1)
void setUpNormal (State &state) const
void setUpNormal1 (State &state) const
void setUpNormal2 (State &state) const
void setUpNormal3 (State &state) const
int signDelta (const InputPoint &A, const InputPoint &B, const InputPoint &C) const
int signDelta (const InputPoint &A, const InputPoint &C) const
bool newCurrentTriangle (State &state, const InputPoint &M) const
template<typename TInputIterator >
unsigned int findTriangle (State &state, TInputIterator itB, TInputIterator itE) const
template<typename TInputIterator >
unsigned int findTriangle1 (State &state, TInputIterator itB, TInputIterator itE) const
template<typename TInputIterator >
unsigned int findTriangle2 (State &state, TInputIterator itB, TInputIterator itE) const
template<typename TInputIterator1 , typename TInputIterator2 >
unsigned int findMixedTriangle (State &state, TInputIterator1 itB1, TInputIterator1 itE1, TInputIterator2 itB2, TInputIterator2 itE2) const
bool alignedAlongAxis (const InputPoint &p1, const InputPoint &p2) const
void computeHeight (State &state) const
void computeNormal (State &state) const
template<typename TInputIterator >
bool satisfies (State &state, TInputIterator itB, TInputIterator itE) const
template<typename TInputIterator >
std::pair< InternalScalar,
InternalScalar > axisWidth (State &state, TInputIterator itB, TInputIterator itE) const
bool checkWidth (const State &state) const
void selfDisplay (std::ostream &out, const State &state) const
Private Attributes
Dimension z
Dimension x
Dimension y
InternalScalar myWidth0
InternalScalar myWidth1
InputPointSet myPointSet
State myState
State _state
InternalScalar _d
Detailed Description
template<typename TSpace, typename TInputPoint, typename TInternalScalar>
class DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >
Aim: A class that contains the chord-based algorithm for recognizing pieces of digital planes of given axis width [ Gerard, Debled-Rennesson, Zimmermann, 2005 ]. When the width is 1, it corresponds to naive planes. The axis is specified at initialization of the object.
Description of template class 'ChordNaivePlaneComputer'.This class is an implementation of Gerard, Debled-Rennesson, Zimmermann, 2005: An elementary digital plane recognition algorithm, [17].
As a (3D) geometric primitive computer, it obeys the concept CAdditivePrimitiveComputer. It is copy constructible, assignable. It has methods extend(), extend(InputIterator, InputIterator) and isExtendable(), isExtendable(InputIterator, InputIterator). The object stores all the distinct points p such that 'extend(p)' was successful. It is thus a model of boost::ForwardContainer (non mutable). It is iterable (inner type ConstIterator, begin(), end()). You may clear() it.
It is also a model of CPointPredicate (returns 'true' iff a point is within the current bounds).
Note on complexity: According to the paper, the
worst-case complexity is \(O(n^7) \) (in its non-incremental form). However, the observed complexity is quasi-linear.
Note on execution times: The user should favor int32_t or
int64_t instead of BigInteger whenever possible. When the point components are smaller than 14000, int32_t are sufficient. For point components smaller than 440000000, int64_t are sufficient. For greater diameters, it is necessary to use BigInteger.
What is the best algorithm to check if a set of digital points is some (naive) plane ?
We discuss only this question between ChordNaivePlaneComputer (1) and COBANaivePlaneComputer (2) (see also Comparative evaluation of COBA and Chord algorithm):
Complexity: (2) has a better worst time complexity than (1), but neither (1) nor (2) has an easy bound on the number of global recomputation (traversal of all input points to recompute a valid direction).
Big integers: (1) requires (significantly) smaller integers than (2). For instance, int64_t are required for diameter greater than 25 for (1) instead of 14000 for (2).
Practice: both algorithms are very comparable. (1) seems slightly faster than (2) on average (but this was not tested on many architecture).
Exactness: Both algorithms do not return the smallest possible arithmetic parameters for the plane, but only a rational approximation.
Services: Algorithm (1) can be transformed to find the exact axis width of a given set of points, (2) is not suited for that task.
A small example to show how to check if some points form a subset of a naive plane.
// Example. Checks that the following four points does not belong to a naive plane.
typedef SpaceND<3,int> Z3;
typedef ChordNaivePlaneComputer< Z3, Z3::Point, int64_t > NaivePlaneComputer;
NaivePlaneComputer plane;
plane.init(2, 1, 1); // axis is z, width is 1/1 => naive
plane.extend(Point(10, 0, 0)); // return 'true'
plane.extend(Point(0, 8, 0));  // return 'true'
plane.extend(Point(0, 0, 6));  // return 'true'
plane.extend(Point(5, 5, 5));  // return 'false'
// There is no naive plane going through the 3 first points and the last one.
Model of boost::DefaultConstructible, boost::CopyConstructible, boost::Assignable, boost::ForwardContainer, CAdditivePrimitiveComputer, CPointPredicate.
Template Parameters
TSpace specifies the digital space (provides dimension and types for the primitive)
TInputPoint specifies the type of the input points (digital or not). Usually, you may choose TInputPoint = TSpace::Point, but this is not compulsory. You may for instance wish to manipulate floating-point value points. This is possible, but you have to choose the type TInternalScalar accordingly.
TInternalScalar specifies the type of scalar used in internal computations, generally a more precise type than TInputPoint::Component. For instance, for digital points, the type should be able to hold integers of order \((2*D)^2\) if D is the diameter of the set of digital points.
Examples:
io/viewers/viewer3D-7bis-planes.cpp.
Definition at line 157 of file ChordNaivePlaneComputer.h.
Member Typedef Documentation
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef InputVector::Component DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::Component
Definition at line 171 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef InputPointSet::const_iterator DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::const_iterator
Definition at line 184 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef InputPointSet::const_pointer DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::const_pointer
Definition at line 185 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef InputPointSet::const_reference DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::const_reference
Definition at line 186 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef InputPointSet::const_iterator DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::ConstIterator
Definition at line 177 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef InputPoint::Coordinate DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::Coordinate
Definition at line 172 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef InputPointSet::difference_type DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::difference_type
Definition at line 188 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef TInputPoint DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::InputPoint
Definition at line 168 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef std::set< InputPoint > DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::InputPointSet
Definition at line 175 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef InputPoint DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::InputVector
Definition at line 170 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef TInternalScalar DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::InternalScalar
Definition at line 169 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef PointVector<3,InternalScalar> DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::InternalVector
Definition at line 173 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef InputPointSet::iterator DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::Iterator
Definition at line 178 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef Space::Point DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::Point
Definition at line 179 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef ParallelStrip<Space,true,true> DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::Primitive
Definition at line 180 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef InputPointSet::size_type DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::Size
Definition at line 176 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef InputPointSet::size_type DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::size_type
Definition at line 189 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef TSpace DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::Space
Definition at line 167 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> typedef InputPointSet::value_type DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::value_type
Definition at line 187 of file ChordNaivePlaneComputer.h.
Constructor & Destructor Documentation
template<typename TSpace , typename TInputPoint , typename TInternalScalar > DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::~ChordNaivePlaneComputer () inline
Destructor.
Definition at line 48 of file ChordNaivePlaneComputer.ih.
 { // Nothing to do.
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::ChordNaivePlaneComputer () inline
Constructor. The object is not valid and should be initialized.
See Also
init
Definition at line 55 of file ChordNaivePlaneComputer.ih.
                           : z( -1 )
 { // Object is invalid
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::ChordNaivePlaneComputer (const ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar > & other) inline
Copy constructor.
Parameters
other the object to clone.
Definition at line 62 of file ChordNaivePlaneComputer.ih.
   : z( other.z ), x( other.x ), y( other.y ),
     myWidth0( other.myWidth0 ),
     myWidth1( other.myWidth1 ),
     myPointSet( other.myPointSet ),
     myState( other.myState )
 {
 }
Member Function Documentation
template<typename TSpace , typename TInputPoint , typename TInternalScalar > bool DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::alignedAlongAxis (const InputPoint & p1, const InputPoint & p2) const inline private
Parameters
p1 any point.
p2 any point.
Returns
'true' iff the two points form a vector aligned with the main axis.
Definition at line 1122 of file ChordNaivePlaneComputer.ih.
 {
  return ( p1[ x ] == p2[ x ] ) && ( p1[ y ] == p2[ y ] );
 }
template<typename TSpace, typename TInputPoint, typename TInternalScalar> template<typename TInputIterator > std::pair<InternalScalar, InternalScalar> DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::axisWidth (TInputIterator itB, TInputIterator itE) const
Useful to compute the axis width of a given range of points (public version).
Template Parameters
TInputIterator any model of InputIterator on InputPoint.
Parameters
[in] itB an iterator on the first element of the range of 3D points.
[in] itE an iterator after the last element of the range of 3D points.
Returns
the axis width as a pair numerator/denominator.
Referenced by DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::computeAxisWidth().
template<typename TSpace, typename TInputPoint, typename TInternalScalar> template<typename TInputIterator > std::pair<TInternalScalar, TInternalScalar> DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::axisWidth (State & state, TInputIterator itB, TInputIterator itE) const
Definition at line 438 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::A, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::max, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::min, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::N, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::nbValid, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::ptMax, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::ptMin, DGtal::trace, and DGtal::Trace::warning().
 {
   BOOST_CONCEPT_ASSERT(( boost::InputIterator<TInputIterator> ));
   ASSERT( isValid() );
   state.nbValid = 0;
   if ( itB == itE ) return std::make_pair( (TInternalScalar) 0, (TInternalScalar) 0 );
   state.nbValid = findTriangle( state, itB, itE );
   setUpNormal( state );
   computeMinMax( state, itB, itE );
   InternalVector formerN; // memorizes former normal vector.
   formerN[ 0 ] = state.N[ 0 ]; formerN[ 1 ] = state.N[ 1 ]; formerN[ 2 ] = state.N[ 2 ];
   std::pair<TInternalScalar, TInternalScalar> width( state.max - state.min, state.N[ z ] );
   bool optimum = false;
   for ( unsigned int loop = 0; ! optimum; ++loop )
     {
       computeHeight( state );
       if ( state.nbValid >= 2 )
         { // in case 2 and 3, we have a starting triangle.
           InputPoint M = state.ptMax - state.ptMin;
           if ( ( M[ x ] == 0 ) && ( M[ y ] == 0 ) )
             { // Case where M is aligned with axis, width is M[ z ].
               width.first = M[ z ];
               width.second = 1;
               optimum = true;
               break;
             }
           else
             {
               newCurrentTriangle( state, M );
               computeNormal( state );
             }
         }
       else
         { // in case 1, normal is already aligned with main axis.
           state.A = state.ptMax - state.ptMin;
         }
       computeMinMax( state, itB, itE );
       // To determine the optimum position:
       // - it is not enough to look at the current width and check for the smallest one.
       // - it is not enough to look at the current vector ptMax - ptMin to see if it is changing
       // - it suffices to look at the normal vector and check that it has changed.
       if ( ( formerN[ 0 ] == state.N[ 0 ] )
            && ( formerN[ 1 ] == state.N[ 1 ] )
            && ( formerN[ 2 ] == state.N[ 2 ] ) )
         { // optimum
           optimum = true;
         }
       else
         { // better width found.
           width.first = state.max - state.min;
           width.second = state.N[ z ];
           formerN[ 0 ] = state.N[ 0 ]; formerN[ 1 ] = state.N[ 1 ]; formerN[ 2 ] = state.N[ 2 ];
         }
       if (loop>=1000) {
         trace.warning() << "[ChordNaivePlaneComputer::axisWidth()]"
                   << " more than 1000 loops, computing error suspected" << std::endl;
         trace.warning() << "- Former state: " << *this << std::endl;
         trace.warning() << "- Current state: ";
         selfDisplay( trace.warning(), state );
         trace.warning() << std::endl;
         trace.warning() << "- Added Points: ";
         for ( TInputIterator it = itB; it != itE; ++it )
           trace.warning() << " " << *it;
         trace.warning() << std::endl;
         optimum = true;
       }
     }
   return width;
 }
template<typename TSpace, typename TInputPoint, typename TInternalScalar> template<typename TInputIterator > std::pair<TInternalScalar, TInternalScalar> DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::axisWidth (TInputIterator itB, TInputIterator itE) const inline
Definition at line 513 of file ChordNaivePlaneComputer.ih.
 {
   return axisWidth( _state, itB, itE );
 }
template<typename TSpace, typename TInputPoint, typename TInternalScalar> template<typename TInputIterator > std::pair<InternalScalar, InternalScalar> DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::axisWidth (State & state, TInputIterator itB, TInputIterator itE) const private
Useful to compute the axis width of a given range of points.
Template Parameters
TInputIterator any model of InputIterator on InputPoint.
Parameters
[out] state the resulting state, if you need to have a look.
[in] itB an iterator on the first element of the range of 3D points.
[in] itE an iterator after the last element of the range of 3D points.
Returns
the axis width as a pair numerator/denominator.
template<typename TSpace , typename TInputPoint , typename TInternalScalar > DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::ConstIterator DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::begin () const inline
Returns
a const iterator pointing on the first point stored in the current naive plane.
Definition at line 141 of file ChordNaivePlaneComputer.ih.
 {
   return myPointSet.begin();
 }
template<typename TSpace, typename TInputPoint, typename TInternalScalar> DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::BOOST_CONCEPT_ASSERT ((CSpace< TSpace >)) private
template<typename TSpace, typename TInputPoint, typename TInternalScalar> DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::BOOST_CONCEPT_ASSERT ((CSignedNumber< TInternalScalar >)) private
template<typename TSpace, typename TInputPoint, typename TInternalScalar> DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::BOOST_STATIC_ASSERT ((TSpace::dimension==3)) private
template<typename TSpace, typename TInputPoint, typename TInternalScalar> DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::BOOST_STATIC_ASSERT ((TInputPoint::dimension==3)) private
template<typename TSpace, typename TInputPoint, typename TInternalScalar> bool DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::checkPlaneWidth (const State & state) const private
Parameters
state the state where the normal state.N, the scalars state.min and state.max are used in computations.
Returns
'true' if the current width along state.N (computed from the difference of state.max and state.min) is strictly inferior to the maximal specified width (in myWidth), 'false' otherwise.
template<typename TSpace , typename TInputPoint , typename TInternalScalar > bool DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::checkWidth (const State & state) const inline private
Parameters
[in,out] state the current state of the algorithm (fields state.min, state.max, state.height are used)
Returns
'true' iff the current state indicates that the set of points is included between two planes of axis width smaller than the width specified at initialization. It is the value: state.max - state.min <= state.height.
See Also
init
Definition at line 1158 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::height, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::max, and DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::min.
 {
   return ( state.max - state.min ) <= state.height;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > void DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::clear () inline
Clear the object, free memory. The plane keeps its main axis, diameter and width, but contains no point.
Definition at line 94 of file ChordNaivePlaneComputer.ih.
 {
   myPointSet.clear();
   myState.nbValid = 0;
 }
template<typename TSpace, typename TInputPoint, typename TInternalScalar> template<typename TInputIterator > static std::pair<InternalScalar, InternalScalar> DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::computeAxisWidth (Dimension axis, TInputIterator itB, TInputIterator itE) static
Useful to compute the axis width of a given range of points (public static version).
Template Parameters
TInputIterator any model of InputIterator on InputPoint.
Parameters
[in] axis the main axis (0,1,2) for x, y or z.
[in] itB an iterator on the first element of the range of 3D points.
[in] itE an iterator after the last element of the range of 3D points.
Returns
the axis width as a pair numerator/denominator.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> template<typename TInputIterator > std::pair<TInternalScalar, TInternalScalar> DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::computeAxisWidth (Dimension axis, TInputIterator itB, TInputIterator itE) inline
Definition at line 426 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::axisWidth(), and DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::init().
 {
   ChordNaivePlaneComputer plane;
   plane.init( axis );
   return plane.axisWidth( itB, itE );
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > void DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::computeHeight (State & state) const inline private
Parameters
[in,out] state the field state.height is updated and contains the main axis height of the current triangle.
Definition at line 1131 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::A, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::height, and DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::N.
 {
   state.height = internalDot( state.A, state.N );
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > template<typename TInputIterator > void DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::computeMinMax (State & state, TInputIterator itB, TInputIterator itE) const private
Computes the min and max values/arguments of the scalar product between the normal state.N and the points in the range [itB,itE). Overwrites state.min, state.max at the start.
Template Parameters
TInputIterator any model of InputIterator.
Parameters
state (modified) the state where the normal N is used in computation and where fields state.min, state.max, state.ptMin, state.ptMax are updated.
itB an input iterator on the first point of the range.
itE an input iterator after the last point of the range.
Definition at line 1021 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::max, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::min, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::N, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::ptMax, and DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::ptMin.
 {
   BOOST_CONCEPT_ASSERT(( boost::InputIterator<TInputIterator> ));
   ASSERT( itB != itE );
   _d = internalDot( state.N, *itB );
   state.min = state.max = _d;
   state.ptMin = state.ptMax = *itB;
   ++itB;
   for ( ; itB != itE; ++itB )
     {
       _d = internalDot( state.N, *itB );
       if ( _d > state.max ) {
         state.max = _d;
         state.ptMax = *itB;
       } else if ( _d < state.min ) {
         state.min = _d;
         state.ptMin = *itB;
       }
     }
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > void DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::computeNormal (State & state) const inline private
Computes a new normal according to the given values of state.A, state.B, state.C.
Parameters
[in,out] state the field state.normal is updated and contains the new normal.
Precondition
state.nbValid >= 2
Definition at line 1140 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::A, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::B, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::C, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::N, and DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::nbValid.
 {
   ASSERT( state.nbValid >= 2 );
   internalCross( state.N, state.B - state.A, state.C - state.A );
   if ( state.N[ z ] < 0 ) {
     state.N[ 0 ] = -state.N[ 0 ];
     state.N[ 1 ] = -state.N[ 1 ];
     state.N[ 2 ] = -state.N[ 2 ];
     InputPoint M = state.A;
     state.A = state.B;
     state.B = M;
   }
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > bool DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::empty () const inline
Returns
'true' if and only if this object contains no point.
Definition at line 132 of file ChordNaivePlaneComputer.ih.
 {
   return myPointSet.empty();
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::ConstIterator DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::end () const inline
Returns
a const iterator pointing after the last point stored in the current naive plane.
Definition at line 150 of file ChordNaivePlaneComputer.ih.
 {
   return myPointSet.end();
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > const DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::InternalVector & DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::exactNormal () const inline
Returns
a reference to the current normal vector (exact form).
Definition at line 748 of file ChordNaivePlaneComputer.ih.
 {
   return myState.N;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > bool DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::extend (const InputPoint & p)
Adds the point p and checks if we have still a digital plane of specified width. The plane parameters may be updated so as to include the new point.
Parameters
p any 3D point (in the specified diameter).
Returns
'true' if it is still a plane, 'false' otherwise (the object is then in its original state).
Definition at line 202 of file ChordNaivePlaneComputer.ih.
References DGtal::trace, and DGtal::Trace::warning().
 {
   unsigned int loop;
   ASSERT( isValid() );
   // Checks if algorithm is initialized.
   if ( extendAsIs( p ) )
     {
       // std::cout << "extended as is: " << p << std::endl;
       return true;
     }
   std::pair<Iterator,bool> ins = myPointSet.insert( p );
   Iterator itP = ins.first;
   ASSERT( ins.second == true );
   if ( myState.nbValid < 3 )
     { // initial case
       _state.nbValid = findTriangle( _state, myPointSet.begin(), myPointSet.end() );
       // std::cout << "findTriangle #=" << _state.nbValid << std::endl;
       setUpNormal( _state );
     }
   else
     _state = myState;
   unsigned int result = 0; // 0: computing, 1: too large, 2: found.
   for ( loop = 0; result == 0; ++loop )
     {
       computeHeight( _state );
       if ( ( _state.height * myWidth1 ) >= ( _state.N[ z ] * myWidth0 ) ) // because width is strict
         result = 1;
       else
         {
           computeMinMax( _state, myPointSet.begin(), myPointSet.end() );
           if ( checkWidth( _state ) )
             { // Ok. Found it.
               result = 2;
             }
           else if ( _state.nbValid >= 2 )
             { // in case 2 and 3, we have a starting triangle.
               InputPoint M = _state.ptMax - _state.ptMin;
               if ( ( M[ x ] == 0 ) && ( M[ y ] == 0 ) )
                 { // Case where M is aligned with axis, width is M[ z ].
                   result = M[ z ] * myWidth1 >= myWidth0 ? 1 : 2;
                 }
               else
                 {
                   newCurrentTriangle( _state, M );
                   computeNormal( _state );
                 }
             }
           else
             { // in case 1, normal is already aligned with main axis.
               _state.A = _state.ptMax - _state.ptMin;
             }
         }
       if (loop>=1000) {
         trace.warning() << "[ChordNaivePlaneComputer::extend()]"
                   << " more than 1000 loops, computing error suspected" << std::endl;
         trace.warning() << "- Former state: " << *this << std::endl;
         trace.warning() << "- Current state: ";
         selfDisplay( trace.warning(), _state );
         trace.warning() << std::endl;
         trace.warning() << "- Points: ";
         for ( ConstIterator it = this->begin(), itE = this->end();
               it != itE; ++it )
           trace.warning() << " " << *it;
         trace.warning() << std::endl;
         trace.warning() << "- Added Points: " << p;
         trace.warning() << std::endl;
         result = 1;
       }
     }
   // was unable to find a correct plane.
   if ( result == 2 )
     myState = _state;
   else
     myPointSet.erase( itP );
   return result == 2;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > template<typename TInputIterator > bool DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::extend (TInputIterator itB, TInputIterator itE)
Adds the range of points [it, itE) and checks if we have still a digital plane of specified width. The plane parameters may be updated so as to include all the new points. All points pointed by iterators should be in the diameter of this object.
Template Parameters
TInputIterator any model of InputIterator on InputPoint.
Parameters
[in] itB an iterator on the first element of the range of 3D points.
[in] itE an iterator after the last element of the range of 3D points.
Returns
'true' if it is still a plane, 'false' otherwise (the object is then in its original state).
Definition at line 524 of file ChordNaivePlaneComputer.ih.
References DGtal::trace, and DGtal::Trace::warning().
 {
   BOOST_CONCEPT_ASSERT(( boost::InputIterator<TInputIterator> ));
   if ( itB == itE ) return true;
   unsigned int loop;
   ASSERT( isValid() );
   if ( empty() ) { // case where object is empty.
     bool ok = satisfies( _state, itB, itE );
     if ( ok ) // ideal case: all points false within current plane.
       {
         myState = _state;
         myPointSet.insert( itB, itE );
         // std::cout << "- (Group extend) satisfies for " << *this << std::endl;
       }
     return ok;
   }
   // Object contains already some points.
   _state = myState;
   bool changed = updateMinMax( _state, itB, itE );
   if ( ! changed ) { // cases where added points did not change the bounds.
     myPointSet.insert( itB, itE );
     // std::cout << "- (Group extend) unchanged for " << *this << std::endl;
     return true;
   }
   if ( myState.nbValid < 3 )
     { // initial case
       _state.nbValid = findMixedTriangle( _state,
                                           myPointSet.begin(), myPointSet.end(),
                                           itB, itE );
       setUpNormal( _state );
       // std::cout << "- (Group extend) findTriangle #=" << _state.nbValid << std::endl;
     }
   else
     {
       _state = myState;
       // std::cout << "- (Group extend) Getting state " << std::endl;
     }
   unsigned int result = 0; // 0: computing, 1: too large, 2: found.
   for ( loop = 0; result == 0; ++loop )
     {
       computeHeight( _state );
       // std::cout << "  - " << loop << "/h=" << _state.height
       //           << "/N=" << _state.N[ z ]
       //           << " : ";
       // selfDisplay( std::cout, _state );
       // std::cout << std::endl;
       if ( ( _state.height * myWidth1 ) >= ( _state.N[ z ] * myWidth0 ) ) // because width is strict
         result = 1;
       else
         {
           computeMinMax( _state, myPointSet.begin(), myPointSet.end() );
           updateMinMax( _state, itB, itE );
           if ( checkWidth( _state ) )
             { // ok, plane is fine.
               result = 2;
             }
           else if ( _state.nbValid >= 2 )
             { // in case 2 and 3, we have a starting triangle.
               InputPoint M = _state.ptMax - _state.ptMin;
               if ( ( M[ x ] == 0 ) && ( M[ y ] == 0 ) )
                 { // Case where M is aligned with axis, width is M[ z ].
                   result = M[ z ] * myWidth1 >= myWidth0 ? 1 : 2;
                 }
               else
                 {
                   newCurrentTriangle( _state, M );
                   computeNormal( _state );
                 }
             }
           else
             { // in case 1, normal is already aligned with main axis.
               _state.A = _state.ptMax - _state.ptMin;
             }
         }
       if (loop>=1000) {
         trace.warning() << "[ChordNaivePlaneComputer::extend(Iterator,Iterator)]"
                   << " more than 1000 loops, computing error suspected" << std::endl;
         trace.warning() << "- Former state: " << *this << std::endl;
         trace.warning() << "- Current state: ";
         selfDisplay( trace.warning(), _state );
         trace.warning() << std::endl;
         trace.warning() << "- Points: ";
         for ( ConstIterator it = this->begin(), itEnd = this->end();
               it != itEnd; ++it )
           trace.warning() << " " << *it;
         trace.warning() << std::endl;
         trace.warning() << "- Added Points: ";
         for ( TInputIterator it2 = itB; it2 != itE; ++it2 )
           trace.warning() << " " << *it2;
         trace.warning() << std::endl;
         result = 1;
       }
     }
   // find a correct plane.
   if ( result == 2 )
     {
       myState = _state;
       myPointSet.insert( itB, itE );
       return true;
     }
   // was unable to find a correct plane.
   return false;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > bool DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::extendAsIs (const InputPoint & p) inline
Adds the point p to this plane if it is within the current bounds. The plane parameters are not updated.
Parameters
p any 3D point (in the specified diameter).
Returns
'true' if p is in the plane, 'false' otherwise (the object is then in its original state).
Definition at line 187 of file ChordNaivePlaneComputer.ih.
 {
   ASSERT( isValid() );
   if ( empty() ) {
     myPointSet.insert( p );
     return setUp1( p );
   }
   bool ok = this->operator()( p );
   if ( ok ) myPointSet.insert( p );
   return ok;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > template<typename TInputIterator1 , typename TInputIterator2 > unsigned int DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::findMixedTriangle (State & state, TInputIterator1 itB1, TInputIterator1 itE1, TInputIterator2 itB2, TInputIterator2 itE2) const private
Definition at line 1098 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::A, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::B, and DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::C.
 {
   BOOST_CONCEPT_ASSERT(( boost::InputIterator<TInputIterator1> ));
   BOOST_CONCEPT_ASSERT(( boost::InputIterator<TInputIterator2> ));
   if ( itB1 == itE1 ) return findTriangle( state, itB2, itE2 ) ;
   state.A = *itB1++; // first point
   for ( ; ( itB1 != itE1 ) && alignedAlongAxis( state.A, *itB1 ); ++itB1 )
     ;
   if ( itB1 == itE1 ) return findTriangle1( state, itB2, itE2 );
   state.B = *itB1++; // second point
   for ( ; ( itB1 != itE1 ) && ( signDelta( state.A, state.B, *itB1 ) == 0 ); ++itB1 )
     ;
   if ( itB1 == itE1 ) return findTriangle2( state, itB2, itE2 );
   state.C = *itB1;   // third point
   return 3;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > template<typename TInputIterator > unsigned int DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::findTriangle (State & state, TInputIterator itB, TInputIterator itE) const private
Template Parameters
TInputIterator any model of boost::InputIterator on InputPoint.
Initializes the Chord algorithm by determining an initial triangle of the convex chord set (S+(-S)) if S is the set of points. If points have special alignment with the main axis, it may not return a triangle.
Parameters
[in] itB the beginning of the range of input points.
[in] itE the end of the range of input points.
[out] state contains the points forming a triangle not containing the main axis (state.A, state.B, state.C) if one was found, otherwise a segment not containing the main axis (state.A, state.B), otherwise the first point (state.A).
Returns
0 if object is initialized and there is no points, 1 when all points are aligned with main axis, 2 when all points form a triangle containing the main axis direction, 3 when there are at least 3 points that form a triangle not aligned with the main axis direction.
Definition at line 1046 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::A, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::B, and DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::C.
 {
   BOOST_CONCEPT_ASSERT(( boost::InputIterator<TInputIterator> ));
   if ( itB == itE ) return 0;
   state.A = *itB++; // first point
   for ( ; ( itB != itE ) && alignedAlongAxis( state.A, *itB ); ++itB )
     ;
   if ( itB == itE ) return 1;
   state.B = *itB++; // second point
   for ( ; ( itB != itE ) && ( signDelta( state.A, state.B, *itB ) == 0 ); ++itB )
     ;
   if ( itB == itE ) return 2;
   state.C = *itB;   // third point
   return 3;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > template<typename TInputIterator > unsigned int DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::findTriangle1 (State & state, TInputIterator itB, TInputIterator itE) const private
Definition at line 1066 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::A, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::B, and DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::C.
 {
   BOOST_CONCEPT_ASSERT(( boost::InputIterator<TInputIterator> ));
   for ( ; ( itB != itE ) && alignedAlongAxis( state.A, *itB ); ++itB )
     ;
   if ( itB == itE ) return 1;
   state.B = *itB++; // second point
   for ( ; ( itB != itE ) && ( signDelta( state.A, state.B, *itB ) == 0 ); ++itB )
     ;
   if ( itB == itE ) return 2;
   state.C = *itB;   // third point
   return 3;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > template<typename TInputIterator > unsigned int DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::findTriangle2 (State & state, TInputIterator itB, TInputIterator itE) const private
Definition at line 1084 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::A, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::B, and DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::C.
 {
   BOOST_CONCEPT_ASSERT(( boost::InputIterator<TInputIterator> ));
   for ( ; ( itB != itE ) && ( signDelta( state.A, state.B, *itB ) == 0 ); ++itB )
     ;
   if ( itB == itE ) return 2;
   state.C = *itB;   // third point
   return 3;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > void DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::getBounds (double & min, double & max) const inline
If n is the unit normal to the current plane, then n.x >= min and n.x <= max are the two half-planes defining it.
Parameters
min the lower bound (corresponding to the unit vector).
max the upper bound (corresponding to the unit vector).
Definition at line 774 of file ChordNaivePlaneComputer.ih.
References DGtal::NumberTraits< T >::castToDouble().
 {
   double nx = NumberTraits<InternalScalar>::castToDouble( myState.N[ 0 ] );
   double ny = NumberTraits<InternalScalar>::castToDouble( myState.N[ 1 ] );
   double nz = NumberTraits<InternalScalar>::castToDouble( myState.N[ 2 ] );
   double l = sqrt( nx*nx + ny*ny + nz*nz );
   min = NumberTraits<InternalScalar>::castToDouble( myState.min ) / l;
   max = NumberTraits<InternalScalar>::castToDouble( myState.max ) / l;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > template<typename Vector3D > void DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::getNormal (Vector3D & normal) const inline
Template Parameters
Vector3D any type T such that T.operator[](int i) returns a reference to a double. i ranges in 0,1,2.
Parameters
[in,out] normal the current normal vector
Definition at line 738 of file ChordNaivePlaneComputer.ih.
 {
   for ( Dimension i = 0; i < 3; ++i )
     normal[ i ] = NumberTraits<InternalScalar>::castToDouble( myState.N[ i ] );
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > template<typename Vector3D > void DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::getUnitNormal (Vector3D & normal) const inline
Template Parameters
Vector3D any type T such that T.operator[](int i) returns a reference to a double. i ranges in 0,1,2.
Parameters
[in,out] normal the current unit normal vector
Definition at line 759 of file ChordNaivePlaneComputer.ih.
 {
   getNormal( normal );
   double l = sqrt( normal[ 0 ] * normal[ 0 ]
                    + normal[ 1 ] * normal[ 1 ]
                    + normal[ 2 ] * normal[ 2 ] );
   normal[ 0 ] /= l;
   normal[ 1 ] /= l;
   normal[ 2 ] /= l;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > void DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::init (Dimension axis, InternalScalar widthNumerator = NumberTraits< InternalScalar >::ONE, InternalScalar widthDenominator = NumberTraits< InternalScalar >::ONE) inline
All these parameters cannot be changed during the process. After this call, the object is in a consistent state and can accept new points for recognition. Calls clear so that the object is ready to be extended.
Parameters
axis the main axis (0,1,2) for x, y or z.
widthNumerator the maximal axis-width (x,y,or z) for the plane is defined as the rational number widthNumerator / widthDenominator (default is 1/1, i.e. naive plane).
widthDenominator the maximal axis-width (x,y,or z) for the plane is defined as the rational number widthNumerator / widthDenominator (default is 1/1, i.e. naive plane).
Examples:
io/viewers/viewer3D-7bis-planes.cpp.
Definition at line 104 of file ChordNaivePlaneComputer.ih.
Referenced by DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::computeAxisWidth().
 {
   ASSERT( ( axis < 3 ) );
   myWidth0 = widthNumerator;
   myWidth1 = widthDenominator;
   switch ( axis ) {
   case 0: x = 1; y = 2; z = 0; break;
   case 1: x = 2; y = 0; z = 1; break;
   case 2: x = 0; y = 1; z = 2; break;
   }
   clear();
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > template<typename TVector1 , typename TVector2 > void DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::internalCross (InternalVector & n, const TVector1 & u, const TVector2 & v) inline static
Cross product with potentially better precision.
Parameters
[out] n the vector that stores the cross product of u and v.
u any vector
v any vector
Definition at line 822 of file ChordNaivePlaneComputer.ih.
 {
   n[ 0 ] = (InternalScalar) u[ 1 ] * (InternalScalar) v[ 2 ] - (InternalScalar) u[ 2 ] * (InternalScalar) v[ 1 ];
   n[ 1 ] = (InternalScalar) u[ 2 ] * (InternalScalar) v[ 0 ] - (InternalScalar) u[ 0 ] * (InternalScalar) v[ 2 ];
   n[ 2 ] = (InternalScalar) u[ 0 ] * (InternalScalar) v[ 1 ] - (InternalScalar) u[ 1 ] * (InternalScalar) v[ 0 ];
 }
template<typename TSpace, typename TInputPoint, typename TInternalScalar> template<typename TVector1 , typename TVector2 > static InternalScalar DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::internalDot (const TVector1 & u, const TVector2 & v) static
Inner product with potentially better precision.
Parameters
u any vector
v any vector
template<typename TSpace, typename TInputPoint, typename TInternalScalar> template<typename TVector1 , typename TVector2 > DGtal::ChordNaivePlaneComputer<TSpace, TInputPoint, TInternalScalar>::InternalScalar DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::internalDot (const TVector1 & u, const TVector2 & v) inline
Definition at line 810 of file ChordNaivePlaneComputer.ih.
 {
   return (InternalScalar) u[ 0 ] * (InternalScalar) v[ 0 ]
     +    (InternalScalar) u[ 1 ] * (InternalScalar) v[ 1 ]
     +    (InternalScalar) u[ 2 ] * (InternalScalar) v[ 2 ];
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > bool DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::isExtendable (const InputPoint & p) const
Checks if we have still a digital plane of specified width when adding point p. The object is left unchanged whatever the returned value. The invariant is 'this->isExtendable(p) == true <=> this->extend(p) == true'.
Parameters
p any 3D point (in the specified diameter).
Returns
'true' if this is still a plane, 'false' otherwise.
Definition at line 282 of file ChordNaivePlaneComputer.ih.
References DGtal::trace, and DGtal::Trace::warning().
 {
   unsigned int loop;
   ASSERT( isValid() );
   if ( empty() || this->operator()( p ) ) return true;
   std::pair<Iterator,bool> ins = myPointSet.insert( p );
   Iterator itP = ins.first;
   ASSERT( ins.second == true );
   if ( myState.nbValid < 3 )
     { // initial case
       _state.nbValid = findTriangle( _state, myPointSet.begin(), myPointSet.end() );
       // std::cout << "findTriangle #=" << _state.nbValid << std::endl;
       setUpNormal( _state );
     }
   else
     _state = myState;
   unsigned int result = 0; // 0: computing, 1: too large, 2: found.
   for ( loop = 0; result == 0; ++loop )
     {
       computeHeight( _state );
       if ( ( _state.height * myWidth1 ) >= ( _state.N[ z ] * myWidth0 ) ) // check >=
         result = 1;
       else
         {
           computeMinMax( _state, myPointSet.begin(), myPointSet.end() );
           if ( checkWidth( _state ) )
             { // Ok. Found it.
               result = 2;
             }
           else if ( _state.nbValid >= 2 )
             { // in case 2 and 3, we have a starting triangle.
               InputPoint M = _state.ptMax - _state.ptMin;
               if ( ( M[ x ] == 0 ) && ( M[ y ] == 0 ) )
                 { // Case where M is aligned with axis, width is M[ z ].
                   result = M[ z ] * myWidth1 >= myWidth0 ? 1 : 2;
                 }
               else
                 {
                   newCurrentTriangle( _state, M );
                   computeNormal( _state );
                 }
             }
           else
             { // in case 1, normal is already aligned with main axis.
               _state.A = _state.ptMax - _state.ptMin;
             }
         }
       if (loop>=1000) {
         trace.warning() << "[ChordNaivePlaneComputer::isExtendable()]"
                   << " more than 1000 loops, computing error suspected" << std::endl;
         trace.warning() << "- Former state: " << *this << std::endl;
         trace.warning() << "- Current state: ";
         selfDisplay( trace.warning(), _state );
         trace.warning() << std::endl;
         trace.warning() << "- Points: ";
         for ( ConstIterator it = this->begin(), itE = this->end();
               it != itE; ++it )
           trace.warning() << " " << *it;
         trace.warning() << std::endl;
         trace.warning() << "- Added Points: " << p;
         trace.warning() << std::endl;
         result = 1;
       }
     }
   // Goes back to starting state.
   myPointSet.erase( itP );
   return result == 2;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > template<typename TInputIterator > bool DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::isExtendable (TInputIterator itB, TInputIterator itE) const
Checks if we have still a digital plane of specified width when adding the range of points [it, itE). The object is left unchanged whatever the returned value. All points pointed by iterators should be in the diameter of this object. The invariant is 'this->isExtendable(it, itE) == true <=> this->extend(it, itE) == true'.
Template Parameters
TInputIterator any model of InputIterator on InputPoint.
Parameters
[in] itB an iterator on the first element of the range of 3D points.
[in] itE an iterator after the last element of the range of 3D points.
Returns
'true' if this is still a plane, 'false' otherwise.
Definition at line 632 of file ChordNaivePlaneComputer.ih.
References DGtal::trace, and DGtal::Trace::warning().
 {
   BOOST_CONCEPT_ASSERT(( boost::InputIterator<TInputIterator> ));
   if ( itB == itE ) return true;
   unsigned int loop;
   ASSERT( isValid() );
   if ( empty() )
     { // case where object is empty.
       return satisfies( _state, itB, itE );
     }
   // Object contains already some points.
   _state = myState;
   bool changed = updateMinMax( _state, itB, itE );
   if ( ! changed )
     { // cases where added points did not change the bounds.
       return true;
     }
   if ( myState.nbValid < 3 )
     { // initial case
       _state.nbValid = findMixedTriangle( _state,
                                           myPointSet.begin(), myPointSet.end(),
                                           itB, itE );
       setUpNormal( _state );
     }
   else
     {
       _state = myState;
     }
   unsigned int result = 0; // 0: computing, 1: too large, 2: found.
   for ( loop = 0; result == 0; ++loop )
     {
       computeHeight( _state );
       if ( ( _state.height * myWidth1 ) >= ( _state.N[ z ] * myWidth0 ) ) // because width is strict
         result = 1;
       else
         {
           computeMinMax( _state, myPointSet.begin(), myPointSet.end() );
           updateMinMax( _state, itB, itE );
           if ( checkWidth( _state ) )
             { // ok, plane is fine.
               result = 2;
             }
           else if ( _state.nbValid >= 2 )
             { // in case 2 and 3, we have a starting triangle.
               InputPoint M = _state.ptMax - _state.ptMin;
               if ( ( M[ x ] == 0 ) && ( M[ y ] == 0 ) )
                 { // Case where M is aligned with axis, width is M[ z ].
                   result = M[ z ] * myWidth1 >= myWidth0 ? 1 : 2;
                 }
               else
                 {
                   newCurrentTriangle( _state, M );
                   computeNormal( _state );
                 }
             }
           else
             { // in case 1, normal is already aligned with main axis.
               _state.A = _state.ptMax - _state.ptMin;
             }
         }
       if (loop>=1000) {
         trace.warning() << "[ChordNaivePlaneComputer::isExtendable(Iterator,Iterator)]"
                   << " more than 1000 loops, computing error suspected" << std::endl;
         trace.warning() << "- Former state: " << *this << std::endl;
         trace.warning() << "- Current state: ";
         selfDisplay( trace.warning(), _state );
         trace.warning() << std::endl;
         trace.warning() << "- Points: ";
         for ( ConstIterator it = this->begin(), itEnd = this->end();
               it != itEnd; ++it )
           trace.warning() << " " << *it;
         trace.warning() << std::endl;
         trace.warning() << "- Added Points: ";
         for ( TInputIterator it2 = itB; it2 != itE; ++it2 )
           trace.warning() << " " << *it2;
         trace.warning() << std::endl;
         result = 1;
       }
     }
   // find a correct plane.
   return result == 2;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > bool DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 878 of file ChordNaivePlaneComputer.ih.
 {
   return z < 3;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::Size DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::max_size () const inline
NB: std version.
Returns
the maximal allowed number of points in the current naive plane.
See Also
maxSize
Definition at line 159 of file ChordNaivePlaneComputer.ih.
 {
   return myPointSet.max_size();
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > const DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::InputPoint & DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::maximalPoint () const inline
Precondition
! empty()
Returns
the current maximal point of the plane, i.e. the one with the highest scalar product with the current normal vector. Note that other points may also have a maximum value.
Definition at line 798 of file ChordNaivePlaneComputer.ih.
 {
   ASSERT( ! this->empty() );
   return myState.ptMax;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::Size DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::maxSize () const inline
same as max_size
Returns
the maximal allowed number of points in the current naive plane.
Definition at line 168 of file ChordNaivePlaneComputer.ih.
 {
   return max_size();
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > const DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::InputPoint & DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::minimalPoint () const inline
Precondition
! empty()
Returns
the current minimal point of the plane, i.e. the one with the smallest scalar product with the current normal vector. Note that other points may also have a minimum value.
Definition at line 788 of file ChordNaivePlaneComputer.ih.
 {
   ASSERT( ! this->empty() );
   return myState.ptMin;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > bool DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::newCurrentTriangle (State & state, const InputPoint & M) const private
Puts in (A,B,C) the new current triangle. We choose the triangle of the tetrahedron A,B,C,M having the highest intersection with Oz.
Parameters
state the current state of the algorithm, state.A, state.B and state.C should represent the current triangle.
M should be the vector P2-P1, where P2 is the point maximizing the dot product with the normal and P1 is the point minimizing the same dot product.
Returns
'true' if a consistent new triangle was found, 'false' if error (M was not correct in this case).
Precondition
state.nbValid >= 2
Definition at line 1166 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::A, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::B, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::C, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::nbValid, DGtal::trace, and DGtal::Trace::warning().
 {
   ASSERT( state.nbValid >= 2 );
   int da =  signDelta( state.A, M ); // A, O, M
   int db =  signDelta( state.B, M ); // B, O, M
   int dc =  signDelta( state.C, M ); // C, O, M
   if ( ( da >= 0 ) && ( db <= 0 ) ) {
     if ( ( signDelta( state.A, state.B ) == 0 ) && ( da == 0 ) ) {
       if ( ( state.A[ x ] * M[ x ] > 0 ) || ( state.A[ y ] * M[ y ] > 0 ) )
         state.A = M;
       else
         state.B = M;
     } else
       state.C = M;
   } else if ( ( db >= 0 ) && ( dc <= 0 ) ) {
     if ( ( signDelta( state.B, state.C ) ==0 ) && ( db == 0 ) ) {
       if ( ( state.B[ x ] * M[ x ] > 0 ) || ( state.B[ y ] * M[ y ] > 0 ) )
         state.B = M;
       else
         state.C = M;
     } else
       state.A = M;
   } else if ( ( dc >= 0 ) && ( da <= 0 ) ) {
     if ( ( signDelta( state.C, state.A ) ==0 ) && ( dc == 0 ) ) {
       if ( ( state.C[ x ] * M[ x ] > 0 ) || ( state.C[ y ] * M[ y ] > 0 ) )
         state.C = M;
       else
         state.A = M;
     } else
       state.B = M;
   } else {
     trace.warning() << "[ChordNaivePlaneComputer::newCurrentTriangle]"
               << " cannot find a triangle cutting the main axis" << std::endl;
     return false;
   }
   return true;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > bool DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::operator() (const Point & p) const inline
Checks if the point p is in the current digital plane. Therefore, a ChordNaivePlaneComputer is a model of CPointPredicate.
Parameters
p any 3D point.
Returns
'true' if it is in the current plane, false otherwise.
Definition at line 177 of file ChordNaivePlaneComputer.ih.
 {
   _d = internalDot( myState.N, p );
   return ( _d >= myState.min ) && ( _d <= myState.max );
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar > & DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::operator= (const ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar > & other) inline
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'.
Definition at line 75 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::myPointSet, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::myState, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::myWidth0, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::myWidth1, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::x, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::y, and DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::z.
 {
   if ( this != &other )
     {
       z = other.z;
       x = other.x;
       y = other.y;
       myWidth0 = other.myWidth0;
       myWidth1 = other.myWidth1;
       myPointSet = other.myPointSet;
       myState = other.myState;
     }
   return *this;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::Primitive DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::primitive () const inline
Returns
the current primitive recognized by this computer, which is a ParallelStrip of axis width smaller than the one specified at instanciation.
Note
The returned primitive has the form \(\mu \le \vec{N} \cdot \vec{X} \le \mu + \epsilon\). It is guaranteed that its axis width is strictly less than the value widthNumerator / widthDenominator specified with method init.
Definition at line 720 of file ChordNaivePlaneComputer.ih.
References DGtal::NumberTraits< T >::castToDouble().
 {
   typedef typename Space::RealVector RealVector;
   typedef typename RealVector::Component Scalar;
   RealVector N;
   for ( Dimension i = 0; i < 3; ++i )
     N[ i ] = NumberTraits<InternalScalar>::castToDouble( myState.N[ i ] );
   Scalar min = NumberTraits<InternalScalar>::castToDouble( myState.min );
   Scalar max = NumberTraits<InternalScalar>::castToDouble( myState.max );
   return Primitive( min, N, max - min );
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > template<typename TInputIterator > bool DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::satisfies (TInputIterator itB, TInputIterator itE) const inline
Useful to check if a given set of points has a valid axis width (public version).
Template Parameters
TInputIterator any model of InputIterator on InputPoint.
Parameters
[in] itB an iterator on the first element of the range of 3D points.
[in] itE an iterator after the last element of the range of 3D points.
Returns
'true' iff the set of points given by range [itB,itE) has a valid width.
Definition at line 415 of file ChordNaivePlaneComputer.ih.
 {
   return satisfies( _state, itB, itE );
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > template<typename TInputIterator > bool DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::satisfies (State & state, TInputIterator itB, TInputIterator itE) const private
Useful to check if a given set of points has a valid axis width.
Template Parameters
TInputIterator any model of InputIterator on InputPoint.
Parameters
[out] state the resulting state, if you need to have a look.
[in] itB an iterator on the first element of the range of 3D points.
[in] itE an iterator after the last element of the range of 3D points.
Returns
'true' iff the set of points given by range [itB,itE) has a valid width.
Definition at line 355 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::A, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::height, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::N, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::nbValid, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::ptMax, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::ptMin, DGtal::trace, and DGtal::Trace::warning().
 {
   BOOST_CONCEPT_ASSERT(( boost::InputIterator<TInputIterator> ));
   ASSERT( isValid() );
   state.nbValid = 0;
   if ( itB == itE ) return true;
   unsigned int loop;
   state.nbValid = findTriangle( state, itB, itE );
   setUpNormal( state );
   unsigned int result = 0; // 0: computing, 1: too large, 2: found.
   for ( loop = 0; result == 0; ++loop )
     {
       computeHeight( state );
       if ( ( state.height * myWidth1 ) >= ( state.N[ z ] * myWidth0 ) ) // because width is strict
         result = 1;
       else
         {
           computeMinMax( state, itB, itE );
           if ( checkWidth( state ) )
             result = 2;
           else if ( state.nbValid >= 2 )
             { // in case 2 and 3, we have a starting triangle.
               InputPoint M = _state.ptMax - _state.ptMin;
               if ( ( M[ x ] == 0 ) && ( M[ y ] == 0 ) )
                 { // Case where M is aligned with axis, width is M[ z ].
                   result = M[ z ] * myWidth1 >= myWidth0 ? 1 : 2;
                 }
               else
                 {
                   newCurrentTriangle( _state, M );
                   computeNormal( _state );
                 }
             }
           else
             { // in case 1, normal is already aligned with main axis.
               state.A = state.ptMax - state.ptMin;
             }
         }
       if (loop>=1000) {
         trace.warning() << "[ChordNaivePlaneComputer::satisfies()]"
                   << " more than 1000 loops, computing error suspected" << std::endl;
         trace.warning() << "- Former state: " << *this << std::endl;
         trace.warning() << "- Current state: ";
         selfDisplay( trace.warning(), state );
         trace.warning() << std::endl;
         trace.warning() << "- Added Points: ";
         for ( TInputIterator it = itB; it != itE; ++it )
           trace.warning() << " " << *it;
         trace.warning() << std::endl;
         result = 1;
       }
     }
   return result == 2;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > void DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 836 of file ChordNaivePlaneComputer.ih.
 {
   selfDisplay( out, myState );
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > void DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::selfDisplay (std::ostream & out, const State & state) const inline private
Writes/Displays the object on an output stream (debug purposes).
Parameters
out the output stream where the object is written.
state a given state for the display.
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 847 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::A, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::B, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::C, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::max, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::min, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::N, and DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::nbValid.
 {
   double min, max;
   double N[ 3 ];
   out << "[ChordNaivePlaneComputer"
       << " axis=" << z << " w=" << myWidth0 << "/" << myWidth1
       << " size=" << size()
       << " N=(" << state.N[ 0 ] << "," << state.N[ 1 ] << "," << state.N[ 2 ] << ")"
       << " A=(" << state.A[ 0 ] << "," << state.A[ 1 ] << "," << state.A[ 2 ] << ")"
       << " B=(" << state.B[ 0 ] << "," << state.B[ 1 ] << "," << state.B[ 2 ] << ")"
       << " C=(" << state.C[ 0 ] << "," << state.C[ 1 ] << "," << state.C[ 2 ] << ")"
       << " #=" << state.nbValid
       << " min=" << state.min
       << " max=" << state.max
       << ": ";
   this->getUnitNormal( N );
   this->getBounds( min, max );
   out << min << " <= "
       << N[ 0 ] << " * x + "
       << N[ 1 ] << " * y + "
       << N[ 2 ] << " * z "
       << " <= " << max << " ]";
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > bool DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::setUp1 (const InputPoint & p1) inline private
Sets up a consistent state with only one point.
Parameters
p1 any point.
Definition at line 954 of file ChordNaivePlaneComputer.ih.
 {
   myState.nbValid = 1;
   myState.height = NumberTraits<InternalScalar>::ZERO;
   setUpNormal1( myState );
   myState.ptMax = p1;
   myState.ptMin = p1;
   myState.max = (InternalScalar) p1[ z ];
   myState.min = myState.max;
   return true;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > void DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::setUpNormal (State & state) const private
Sets up a consistent initial normal direction given the output of findTriangle (state.nbValid, state.A, state.B, state.C).
Parameters
[in,out] state the modified state.
Definition at line 891 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::nbValid.
 {
   switch ( state.nbValid ) {
   case 1: setUpNormal1( state ); break;
   case 2: setUpNormal2( state ); break;
   case 3: setUpNormal3( state ); break;
   }
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > void DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::setUpNormal1 (State & state) const private
Sets up a consistent initial normal direction given the output of findTriangle (state.nbValid == 1).
Parameters
[in,out] state the modified state.
Definition at line 903 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::A, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::B, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::C, and DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::N.
 {
   state.A.reset();
   state.B.reset();
   state.C.reset();
   state.N[ x ] = state.N[ y ] = NumberTraits<InternalScalar>::ZERO;
   state.N[ z ] = NumberTraits<InternalScalar>::ONE;
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > void DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::setUpNormal2 (State & state) const private
Sets up a consistent initial normal direction given the output of findTriangle (state.nbValid == 2, state.A).
Parameters
[in,out] state the modified state.
Definition at line 915 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::A, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::B, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::C, and DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::N.
 { // In this case, we create an imaginary point in the plane 0xy, orthogonal to direction AB.
   state.N[ x ] = state.N[ y ] = NumberTraits<InternalScalar>::ZERO;
   state.N[ z ] = NumberTraits<InternalScalar>::ONE;
   state.A = state.B - state.A;
   // 3 next lines compute internalCross( state.C, state.A, state.N );
   state.C[ x ] = state.A[ y ];
   state.C[ y ] = -state.A[ x ];
   state.C[ z ] = 0;
   if ( ( state.C[ x ] != 0 ) || ( state.C[ y ] != 0 ) )
     // zero iff _state.A is aligned with main axis
     internalCross( state.N, state.C, state.A );
   state.B = -state.A - state.C;
   if ( state.N[ z ] < 0 ) {
     state.N[ 0 ] = -state.N[ 0 ];
     state.N[ 1 ] = -state.N[ 1 ];
     state.N[ 2 ] = -state.N[ 2 ];
     InputPoint M = state.A;
     state.A = state.B;
     state.B = M;
   }
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > void DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::setUpNormal3 (State & state) const inline private
Sets up a consistent initial normal direction given the output of findTriangle (state.nbValid == 3, state.A, state.B, state.C).
Parameters
[in,out] state the modified state.
Definition at line 942 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::A, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::B, and DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::C.
 {
   state.A = state.B - state.A; // p2 - p1;
   state.B = state.C - state.B; // p3 - p2;
   state.C = -state.A - state.B;// p1 - p3;
   computeNormal( state );
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > int DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::signDelta (const InputPoint & A, const InputPoint & B, const InputPoint & C) const inline private
Computes the orientation of vectors AB and AC viewed from the main axis vector. It is the sign of the 2D determinant of AB and AC.
Parameters
A any point.
B any point.
C any point.
Returns
the sign of det(ab,ac), where a,b,c are the 2d projections of A,B,C along main axis.
Definition at line 970 of file ChordNaivePlaneComputer.ih.
 {
   InternalScalar res =
     ( (InternalScalar) (B[ x ]-A[ x ]) ) * ( (InternalScalar) (C[ y ]-A[ y ]) )
     - ( (InternalScalar) (B[ y ]-A[ y ]) ) * ( (InternalScalar) (C[ x ]-A[ x ]) );
   return ( res > (InternalScalar) 0 )
     ? 1 : ( ( res < (InternalScalar) 0 ) ? -1 : 0 );
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > int DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::signDelta (const InputPoint & A, const InputPoint & C) const inline private
Computes the orientation of vectors AO and AC viewed from the main axis vector. It is the sign of the 2D determinant of AO and AC, where O is the origin.
Parameters
A any point.
C any point.
Returns
the sign of det(ao,ac), where a,o,c are the 2d projections of A,O,C along main axis.
Definition at line 983 of file ChordNaivePlaneComputer.ih.
 { // B is zero
   InternalScalar res =
     ( (InternalScalar) (-A[ x ]) ) * ( (InternalScalar) (C[ y ]-A[ y ]) )
     + ( (InternalScalar) (A[ y ]) ) * ( (InternalScalar) (C[ x ]-A[ x ]) );
   return ( res > (InternalScalar) 0 )
     ? 1 : ( ( res < (InternalScalar) 0 ) ? -1 : 0 );
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::Size DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::size () const inline
Returns
the number of distinct points in the current naive plane.
Definition at line 123 of file ChordNaivePlaneComputer.ih.
 {
   return myPointSet.size();
 }
template<typename TSpace , typename TInputPoint , typename TInternalScalar > template<typename TInputIterator > bool DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::updateMinMax (State & state, TInputIterator itB, TInputIterator itE) const private
Updates the min and max values/arguments of the scalar product between the normal state.N and the points in the range [itB,itE). Do not overwrite state.min, state.max at the start.
Template Parameters
TInputIterator any model of InputIterator.
Parameters
state (modified) the state where the normal N is used in computation and where fields state.min, state.max, state.ptMin, state.ptMax are updated.
itB an input iterator on the first point of the range.
itE an input iterator after the last point of the range.
Returns
'true' if any of the fields state.min, state.max, state.ptMin, state.ptMax have been updated, 'false' otherwise.
Definition at line 997 of file ChordNaivePlaneComputer.ih.
References DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::max, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::min, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::N, DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::ptMax, and DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::State::ptMin.
 {
   BOOST_CONCEPT_ASSERT(( boost::InputIterator<TInputIterator> ));
   bool changed = false;
   for ( ; itB != itE; ++itB )
     {
       _d = internalDot( state.N, *itB );
       if ( _d > state.max ) {
         state.max = _d;
         state.ptMax = *itB;
         changed = true;
       } else if ( _d < state.min ) {
         state.min = _d;
         state.ptMin = *itB;
         changed = true;
       }
     }
   return changed;
 }
Field Documentation
template<typename TSpace, typename TInputPoint, typename TInternalScalar> InternalScalar DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::_d mutable private
temporary variable used in some computations.
Definition at line 539 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> State DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::_state mutable private
Temporary state used in computations.
Definition at line 538 of file ChordNaivePlaneComputer.h.
template<typename TSpace, typename TInputPoint, typename TInternalScalar> InputPointSet DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::myPointSet mutable private
the set of points within the plane, mutable since its state may temporarily be changed during some computations.
Definition at line 536 of file ChordNaivePlaneComputer.h.
Referenced by DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::operator=().
template<typename TSpace, typename TInputPoint, typename TInternalScalar> State DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::myState private
the current state that defines the plane being recognized.
Definition at line 537 of file ChordNaivePlaneComputer.h.
Referenced by DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::operator=().
template<typename TSpace, typename TInputPoint, typename TInternalScalar> InternalScalar DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::myWidth0 private
the plane width as a positive rational number myWidth0/myWidth1
Definition at line 534 of file ChordNaivePlaneComputer.h.
Referenced by DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::operator=().
template<typename TSpace, typename TInputPoint, typename TInternalScalar> InternalScalar DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::myWidth1 private
the plane width as a positive rational number myWidth0/myWidth1
Definition at line 535 of file ChordNaivePlaneComputer.h.
Referenced by DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::operator=().
template<typename TSpace, typename TInputPoint, typename TInternalScalar> Dimension DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::x private
Definition at line 533 of file ChordNaivePlaneComputer.h.
Referenced by DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::operator=().
template<typename TSpace, typename TInputPoint, typename TInternalScalar> Dimension DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::y private
the two other axes used in all subsequent computations.
Definition at line 533 of file ChordNaivePlaneComputer.h.
Referenced by DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::operator=().
template<typename TSpace, typename TInputPoint, typename TInternalScalar> Dimension DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::z private
the main axis used in all subsequent computations.
Definition at line 532 of file ChordNaivePlaneComputer.h.
Referenced by DGtal::ChordNaivePlaneComputer< TSpace, TInputPoint, TInternalScalar >::operator=().
The documentation for this class was generated from the following files:
ChordNaivePlaneComputer.h
ChordNaivePlaneComputer.ih