DGtal: DGtal::BasicColorToScalarFunctors::MeanChannels Struct Reference
DGtal::BasicColorToScalarFunctors::MeanChannels Struct Reference
#include <BasicColorToScalarFunctors.h>
Public Member Functions
unsigned char operator() (const Color &aCol) const
Detailed Description
Basic color to scalar functor which returns the mean of the three channel values.
Definition at line 103 of file BasicColorToScalarFunctors.h.
Member Function Documentation
unsigned char DGtal::BasicColorToScalarFunctors::MeanChannels::operator() (const Color & aCol) const inline
Definition at line 106 of file BasicColorToScalarFunctors.h.
References DGtal::Color::blue(), DGtal::Color::green(), and DGtal::Color::red().
       {
         return static_cast<unsigned char>(  ((int)aCol.green() + (int)aCol.blue() + (int)aCol.red()) / 3);
       }
The documentation for this struct was generated from the following file:
BasicColorToScalarFunctors.h