DGtal: DGtal::Board3DTo2DFactory< TSpace, TKSpace > Struct Template Reference
DGtal::Board3DTo2DFactory< TSpace, TKSpace > Struct Template Reference
#include <Board3DTo2DFactory.h>
Public Types
typedef TSpace Space
typedef TKSpace KSpace
Public Types inherited from DGtal::Display3DFactory< TSpace, TKSpace >
typedef TSpace Space
typedef TKSpace KSpace
Public Member Functions
template<typename TSpace>
DGtal::DrawableWithBoard3DTo2D * defaultStyle (std::string str, const DGtal::HyperRectDomain< TSpace > &aDomain)
template<typename TSpace >
void drawAsBoundingBox (Board3DTo2D< Space, KSpace > &board, const DGtal::HyperRectDomain< TSpace > &aDomain)
template<typename TSpace>
void drawAsGrid (Board3DTo2D< Space, KSpace > &board, const DGtal::HyperRectDomain< TSpace > &aDomain)
template<typename TSpace >
void drawAsPavingBalls (Board3DTo2D< Space, KSpace > &board, const DGtal::HyperRectDomain< TSpace > &aDomain)
template<typename TSpace>
void drawAsPaving (Board3DTo2D< Space, KSpace > &board, const DGtal::HyperRectDomain< TSpace > &aDomain)
template<typename TSpace>
void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::HyperRectDomain< TSpace > &aDomain)
Public Member Functions inherited from DGtal::Display3DFactory< TSpace, TKSpace >
template<typename TV>
void draw (Display3D< Space, KSpace > &display, const DGtal::SphericalAccumulator< TV > &aAccumulator, const typename DGtal::SphericalAccumulator< TV >::RealVector &shift, const double radius)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToPoint< KSpace >, typename KSpace::Point > &object)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, CanonicSCellEmbedder< KSpace >, typename KSpace::Space::RealPoint > &object)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToArrow< KSpace >, std::pair< typename KSpace::Point, typename KSpace::Vector > > &object)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToInnerPoint< KSpace >, typename KSpace::Point > &object)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToOuterPoint< KSpace >, typename KSpace::Point > &object)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToIncidentPoints< KSpace >, std::pair< typename KSpace::Point, typename KSpace::Point > > &object)
Static Public Member Functions
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::CameraPosition &aThing)
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::CameraDirection &aThing)
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::CameraUpVector &aThing)
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::CameraZNearFar &aThing)
template<typename TVector >
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::SphericalAccumulator< TVector > &accumulator, const typename DGtal::SphericalAccumulator< TVector >::RealVector &shift=typename DGtal::SphericalAccumulator< TVector >::RealVector(0, 0, 0), const double radius=1.0)
template<typename TPoint >
static void drawAsFaces (Board3DTo2D< Space, KSpace > &board, const DGtal::Mesh< TPoint > &aMesh)
template<typename TPoint >
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::Mesh< TPoint > &aMesh)
template<typename TIterator , typename TInteger , int connectivity>
static
DGtal::DrawableWithBoard3DTo2D * defaultStyle (std::string str, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &arithm)
template<typename TIterator , typename TInteger , int connectivity>
static void drawAsBalls (Board3DTo2D< Space, KSpace > &board, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &arithm)
template<typename TIterator , typename TInteger , int connectivity>
static void drawAsBoundingBox (Board3DTo2D< Space, KSpace > &board, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &arithm)
template<typename TIterator , typename TInteger , int connectivity>
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &arithm)
template<typename Domain , typename Compare >
static
DGtal::DrawableWithBoard3DTo2D * defaultStyle (std::string str, const DGtal::DigitalSetBySTLSet< Domain, Compare > &aSet)
template<typename Domain , typename Compare >
static void drawAsPavingTransparent (Board3DTo2D< Space, KSpace > &board, const DGtal::DigitalSetBySTLSet< Domain, Compare > &aSet)
template<typename Domain , typename Compare >
static void drawAsPaving (Board3DTo2D< Space, KSpace > &board, const DGtal::DigitalSetBySTLSet< Domain, Compare > &aSet)
template<typename Domain , typename Compare >
static void drawAsGrid (Board3DTo2D< Space, KSpace > &board, const DGtal::DigitalSetBySTLSet< Domain, Compare > &aSet)
template<typename Domain , typename Compare >
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::DigitalSetBySTLSet< Domain, Compare > &aSet)
template<typename Domain >
static
DGtal::DrawableWithBoard3DTo2D * defaultStyle (std::string str, const DGtal::DigitalSetBySTLVector< Domain > &aSet)
template<typename Domain >
static void drawAsPavingTransparent (Board3DTo2D< Space, KSpace > &board, const DGtal::DigitalSetBySTLVector< Domain > &aSet)
template<typename Domain >
static void drawAsPaving (Board3DTo2D< Space, KSpace > &board, const DGtal::DigitalSetBySTLVector< Domain > &aSet)
template<typename Domain >
static void drawAsGrid (Board3DTo2D< Space, KSpace > &board, const DGtal::DigitalSetBySTLVector< Domain > &aSet)
template<typename Domain >
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::DigitalSetBySTLVector< Domain > &aSet)
template<typename SpaceDom >
static
DGtal::DrawableWithBoard3DTo2D * defaultStyle (std::string str, const DGtal::HyperRectDomain< SpaceDom > &aDomain)
template<typename SpaceDom >
static void drawAsBoundingBox (Board3DTo2D< Space, KSpace > &board, const DGtal::HyperRectDomain< SpaceDom > &aDomain)
template<typename SpaceDom >
static void drawAsGrid (Board3DTo2D< Space, KSpace > &board, const DGtal::HyperRectDomain< SpaceDom > &aDomain)
template<typename SpaceDom >
static void drawAsPavingBalls (Board3DTo2D< Space, KSpace > &board, const DGtal::HyperRectDomain< SpaceDom > &aDomain)
template<typename SpaceDom >
static void drawAsPaving (Board3DTo2D< Space, KSpace > &board, const DGtal::HyperRectDomain< SpaceDom > &aDomain)
template<typename SpaceDom >
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::HyperRectDomain< SpaceDom > &aDomain)
static
DGtal::DrawableWithBoard3DTo2D * defaultStyle (std::string str, const typename KSpace::Cell &aCell)
static void draw (Board3DTo2D< Space, KSpace > &board, const typename KSpace::Cell &aCell)
template<typename TDigitalTopology , typename TDigitalSet >
static
DGtal::DrawableWithBoard3DTo2D * defaultStyle (std::string str, const DGtal::Object< TDigitalTopology, TDigitalSet > &anObject)
template<typename TDigitalTopology , typename TDigitalSet >
static void drawWithAdjacencies (Board3DTo2D< Space, KSpace > &board, const DGtal::Object< TDigitalTopology, TDigitalSet > &anObject)
template<typename TDigitalTopology , typename TDigitalSet >
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::Object< TDigitalTopology, TDigitalSet > &anObject)
template<Dimension dim, typename TComponent >
static
DGtal::DrawableWithBoard3DTo2D * defaultStyle (std::string str, const DGtal::PointVector< dim, TComponent > &aPoint)
template<Dimension dim, typename TComponent >
static void drawAsGrid (Board3DTo2D< Space, KSpace > &board, const DGtal::PointVector< dim, TComponent > &aPoint)
template<Dimension dim, typename TComponent >
static void drawAsPaving (Board3DTo2D< Space, KSpace > &board, const DGtal::PointVector< dim, TComponent > &aPoint)
template<Dimension dim, typename TComponent >
static void drawAsPavingWired (Board3DTo2D< Space, KSpace > &board, const DGtal::PointVector< dim, TComponent > &aPoint)
template<Dimension dim, typename TComponent >
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::PointVector< dim, TComponent > &aPoint)
template<Dimension dim, typename TComponent >
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::PointVector< dim, TComponent > &aPoint, const DGtal::PointVector< dim, TComponent > &aPoint2)
static
DGtal::DrawableWithBoard3DTo2D * defaultStyle (std::string str, const typename KSpace::SCell &aSCell)
static void draw (Board3DTo2D< Space, KSpace > &board, const typename KSpace::SCell &aSCell)
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::GridCurve< KSpace > &aGrid)
template<typename TIterator , typename TSCell >
static void draw (Board3DTo2D< Space, KSpace > &board, const ConstRangeAdapter< TIterator, DGtal::DefaultFunctor, TSCell > &aRangeAdapter)
template<typename TIterator >
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::ConstRangeAdapter< TIterator, SCellToPoint< KSpace >, typename KSpace::Point > &aRangeAdapter)
template<typename TIterator >
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::ConstRangeAdapter< TIterator, CanonicSCellEmbedder< KSpace >, typename KSpace::Space::RealPoint > &aRangeAdapter)
template<typename TIterator >
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::ConstRangeAdapter< TIterator, SCellToArrow< KSpace >, std::pair< typename KSpace::Point, typename KSpace::Vector > > &aRangeAdapter)
template<typename TIterator >
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::ConstRangeAdapter< TIterator, SCellToInnerPoint< KSpace >, typename KSpace::Point > &aRangeAdapter)
template<typename TIterator >
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::ConstRangeAdapter< TIterator, SCellToOuterPoint< KSpace >, typename KSpace::Point > &aRangeAdapter)
template<typename TIterator >
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::ConstRangeAdapter< TIterator, SCellToIncidentPoints< KSpace >, std::pair< typename KSpace::Point, typename KSpace::Point > > &aRangeAdapter)
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::SetMode3D &aMode)
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::CustomStyle3D &aStyle)
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::CustomColors3D &aColor)
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::ClippingPlane &aClipping)
static void draw (Board3DTo2D< Space, KSpace > &board, const DGtal::TransformedSurfelPrism &aTransformedSurfelPrism)
Static Public Member Functions inherited from DGtal::Display3DFactory< TSpace, TKSpace >
template<typename TVector >
static void draw (Display3D< Space, KSpace > &display, const DGtal::SphericalAccumulator< TVector > &accumulator, const typename DGtal::SphericalAccumulator< TVector >::RealVector &shift=typename DGtal::SphericalAccumulator< TVector >::RealVector(0, 0, 0), const double radius=1.0)
template<typename TPoint >
static void drawAsFaces (Display3D< Space, KSpace > &display, const DGtal::Mesh< TPoint > &aMesh)
template<typename TPoint >
static void draw (Display3D< Space, KSpace > &display, const DGtal::Mesh< TPoint > &aMesh)
template<typename TIterator , typename TInteger , int connectivity>
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &anObject)
template<typename TIterator , typename TInteger , int connectivity>
static void drawAsBalls (Display3D< Space, KSpace > &display, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &anObject)
template<typename TIterator , typename TInteger , int connectivity>
static void drawAsBoundingBox (Display3D< Space, KSpace > &display, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &anObject)
template<typename TIterator , typename TInteger , int connectivity>
static void draw (Display3D< Space, KSpace > &display, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &anObject)
template<typename Domain , typename Compare >
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::DigitalSetBySTLSet< Domain, Compare > &anObject)
template<typename Domain , typename Compare >
static void drawAsPavingTransparent (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLSet< Domain, Compare > &anObject)
template<typename Domain , typename Compare >
static void drawAsPaving (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLSet< Domain, Compare > &anObject)
template<typename Domain , typename Compare >
static void drawAsGrid (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLSet< Domain, Compare > &anObject)
template<typename Domain , typename Compare >
static void draw (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLSet< Domain, Compare > &anObject)
template<typename Domain >
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::DigitalSetBySTLVector< Domain > &anObject)
template<typename Domain >
static void drawAsPavingTransparent (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLVector< Domain > &anObject)
template<typename Domain >
static void drawAsPaving (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLVector< Domain > &anObject)
template<typename Domain >
static void drawAsGrid (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLVector< Domain > &anObject)
template<typename Domain >
static void draw (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLVector< Domain > &anObject)
template<typename SpaceDom >
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::HyperRectDomain< SpaceDom > &anObject)
template<typename SpaceDom >
static void drawAsBoundingBox (Display3D< Space, KSpace > &display, const DGtal::HyperRectDomain< SpaceDom > &anObject)
template<typename SpaceDom >
static void drawAsGrid (Display3D< Space, KSpace > &display, const DGtal::HyperRectDomain< SpaceDom > &anObject)
template<typename SpaceDom >
static void drawAsPavingBalls (Display3D< Space, KSpace > &display, const DGtal::HyperRectDomain< SpaceDom > &anObject)
template<typename SpaceDom >
static void drawAsPaving (Display3D< Space, KSpace > &display, const DGtal::HyperRectDomain< SpaceDom > &anObject)
template<typename SpaceDom >
static void draw (Display3D< Space, KSpace > &display, const DGtal::HyperRectDomain< SpaceDom > &anObject)
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const typename KSpace::Cell &anObject)
static void draw (Display3D< Space, KSpace > &display, const typename KSpace::Cell &anObject)
template<typename TDigitalTopology , typename TDigitalSet >
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::Object< TDigitalTopology, TDigitalSet > &anObject)
template<typename TDigitalTopology , typename TDigitalSet >
static void drawWithAdjacencies (Display3D< Space, KSpace > &display, const DGtal::Object< TDigitalTopology, TDigitalSet > &anObject)
template<typename TDigitalTopology , typename TDigitalSet >
static void draw (Display3D< Space, KSpace > &display, const DGtal::Object< TDigitalTopology, TDigitalSet > &anObject)
template<Dimension dim, typename TComponent >
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::PointVector< dim, TComponent > &anObject)
template<Dimension dim, typename TComponent >
static void drawAsGrid (Display3D< Space, KSpace > &display, const DGtal::PointVector< dim, TComponent > &anObject)
template<Dimension dim, typename TComponent >
static void drawAsPaving (Display3D< Space, KSpace > &display, const DGtal::PointVector< dim, TComponent > &anObject)
template<Dimension dim, typename TComponent >
static void drawAsPavingWired (Display3D< Space, KSpace > &display, const DGtal::PointVector< dim, TComponent > &anObject)
template<Dimension dim, typename TComponent >
static void draw (Display3D< Space, KSpace > &display, const DGtal::PointVector< dim, TComponent > &anObject)
template<Dimension dim, typename TComponent >
static void draw (Display3D< Space, KSpace > &display, const DGtal::PointVector< dim, TComponent > &, const DGtal::PointVector< dim, TComponent > &anObject)
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const typename KSpace::SCell &anObject)
static void draw (Display3D< Space, KSpace > &display, const typename KSpace::SCell &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::GridCurve< KSpace > &anObject)
template<typename TIterator , typename TSCell >
static void draw (DGtal::Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, DGtal::DefaultFunctor, TSCell > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToPoint< KSpace >, typename TKSpace::Point > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, CanonicSCellEmbedder< KSpace >, typename TKSpace::Space::RealPoint > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToArrow< KSpace >, std::pair< typename TKSpace::Point, typename TKSpace::Vector > > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToInnerPoint< KSpace >, typename TKSpace::Point > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToOuterPoint< KSpace >, typename TKSpace::Point > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToIncidentPoints< KSpace >, std::pair< typename TKSpace::Point, typename TKSpace::Point > > &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::SetMode3D &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::CustomStyle3D &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::CustomColors3D &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::ClippingPlane &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::TransformedSurfelPrism &aTransformedSurfelPrism)
Detailed Description
template<typename TSpace, typename TKSpace>
struct DGtal::Board3DTo2DFactory< TSpace, TKSpace >
Factory for GPL Display3D:
Description of struct 'Board3DTo2DFactory'
Definition at line 77 of file Board3DTo2DFactory.h.
Member Typedef Documentation
template<typename TSpace , typename TKSpace > typedef TKSpace DGtal::Board3DTo2DFactory< TSpace, TKSpace >::KSpace
Definition at line 80 of file Board3DTo2DFactory.h.
template<typename TSpace , typename TKSpace > typedef TSpace DGtal::Board3DTo2DFactory< TSpace, TKSpace >::Space
Definition at line 79 of file Board3DTo2DFactory.h.
Member Function Documentation
template<typename Space , typename KSpace > template<typename TIterator , typename TInteger , int connectivity> DGtal::DrawableWithBoard3DTo2D * DGtal::Board3DTo2DFactory< Space, KSpace >::defaultStyle (std::string str, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > & arithm) inline static
Default drawing style object.
Parameters
str the name of the class
arithm the arithm to draw
Returns
the dyn. alloc. default style for this object.
Default DGtal::Board3DTo2DFactory<Space,KSpace>::drawing style object.
Returns
the dyn. alloc. default style for this object.
Definition at line 133 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle().
 {
   return DGtal::Display3DFactory<Space,KSpace>::defaultStyle(str, arithm);
 }
template<typename Space , typename KSpace > template<typename Domain , typename Compare > DGtal::DrawableWithBoard3DTo2D * DGtal::Board3DTo2DFactory< Space, KSpace >::defaultStyle (std::string str, const DGtal::DigitalSetBySTLSet< Domain, Compare > & aSet) inline static
Default drawing style object.
Parameters
str the name of the class
aSet the set to draw
Returns
the dyn. alloc. default style for this object.
Default DGtal::Board3DTo2DFactory<Space,KSpace>::drawing style object.
Returns
the dyn. alloc. default style for this object.
Definition at line 175 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle().
 {
   return DGtal::Display3DFactory<Space,KSpace>::defaultStyle(str, aSet);
 }
template<typename Space , typename KSpace > template<typename Domain > DGtal::DrawableWithBoard3DTo2D * DGtal::Board3DTo2DFactory< Space, KSpace >::defaultStyle (std::string str, const DGtal::DigitalSetBySTLVector< Domain > & aSet) inline static
Default drawing style object.
Parameters
str the name of the class
aSet the set to draw
Returns
the dyn. alloc. default style for this object.
Default DGtal::Board3DTo2DFactory<Space,KSpace>::drawing style object.
Returns
the dyn. alloc. default style for this object.
Definition at line 228 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle().
 {
   return DGtal::Display3DFactory<Space,KSpace>::defaultStyle(str, aSet);
 }
template<typename TSpace , typename TKSpace > template<typename TSpace> DGtal::DrawableWithBoard3DTo2D* DGtal::Board3DTo2DFactory< TSpace, TKSpace >::defaultStyle (std::string str, const DGtal::HyperRectDomain< TSpace > & aDomain) inline
Default DGtal::Board3DTo2DFactory<Space,KSpace>::drawing style object.
Returns
the dyn. alloc. default style for this object.
Definition at line 281 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle().
 {
   return  DGtal::Display3DFactory<Space,KSpace>::defaultStyle( str, aDomain);
 }
template<typename TSpace , typename TKSpace > template<typename SpaceDom > static DGtal::DrawableWithBoard3DTo2D* DGtal::Board3DTo2DFactory< TSpace, TKSpace >::defaultStyle (std::string str, const DGtal::HyperRectDomain< SpaceDom > & aDomain) static
Default drawing style object.
Parameters
str the name of the class
aDomain the domain to draw
Returns
the dyn. alloc. default style for this object.
template<typename Space , typename KSpace > DGtal::DrawableWithBoard3DTo2D * DGtal::Board3DTo2DFactory< Space, KSpace >::defaultStyle (std::string str, const typename KSpace::Cell & aCell) inline static
Default drawing style object.
Parameters
str the name of the class
aCell the cell to draw
Returns
the dyn. alloc. default style for this object.
Definition at line 340 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle().
 {
   return   DGtal::Display3DFactory<Space,KSpace>::defaultStyle(str, aCell);
 }
template<typename Space , typename KSpace > template<typename TDigitalTopology , typename TDigitalSet > DGtal::DrawableWithBoard3DTo2D * DGtal::Board3DTo2DFactory< Space, KSpace >::defaultStyle (std::string str, const DGtal::Object< TDigitalTopology, TDigitalSet > & anObject) inline static
defaultStyle
Parameters
str the name of the class
anObject the object to draw
Returns
the dyn. alloc. default style for this object.
Definition at line 361 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle().
 {
   return DGtal::Display3DFactory<Space,KSpace>::defaultStyle( str, anObject);
 }
template<typename Space , typename KSpace > template<DGtal::Dimension dim, typename TComponent > DGtal::DrawableWithBoard3DTo2D * DGtal::Board3DTo2DFactory< Space, KSpace >::defaultStyle (std::string str, const DGtal::PointVector< dim, TComponent > & aPoint) inline static
Default drawing style object.
Parameters
str the name of the class
aPoint the point to draw
Returns
the dyn. alloc. default style for this object.
Default DGtal::Board3DTo2DFactory<Space,KSpace>::drawing style object.
Returns
the dyn. alloc. default style for this object.
Definition at line 395 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle().
 {
   return DGtal::Display3DFactory<Space,KSpace>::defaultStyle( str, aPoint);
 }
template<typename Space , typename KSpace > DGtal::DrawableWithBoard3DTo2D * DGtal::Board3DTo2DFactory< Space, KSpace >::defaultStyle (std::string str, const typename KSpace::SCell & aSCell) inline static
Default drawing style object.
Parameters
str the name of the class
aSCell the signed cell to draw
Returns
the dyn. alloc. default style for this object.
Default DGtal::Board3DTo2DFactory<Space,KSpace>::drawing style object.
Returns
the dyn. alloc. default style for this object.
Definition at line 456 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle().
 {
   return DGtal::Display3DFactory<Space,KSpace>::defaultStyle( str, aSCell);
 }
template<typename Space , typename KSpace > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::CameraPosition & aThing) inline static
set the camera position on the board
Parameters
board the board where to draw
aThing the camera position to set
Definition at line 44 of file Board3DTo2DFactory.ih.
References DGtal::CameraPosition::eyex, DGtal::CameraPosition::eyey, DGtal::CameraPosition::eyez, and DGtal::Board3DTo2D< Space, KSpace >::setCameraPosition().
Referenced by DGtal::Board3DTo2D< Space, KSpace >::operator<<().
 {
   board.setCameraPosition(cp.eyex, cp.eyey, cp.eyez);
 }
template<typename Space , typename KSpace > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::CameraDirection & aThing) inline static
set the camera direction on the board
Parameters
board the board where to draw
aThing the camera direction to set
Definition at line 52 of file Board3DTo2DFactory.ih.
References DGtal::CameraDirection::dirx, DGtal::CameraDirection::diry, DGtal::CameraDirection::dirz, and DGtal::Board3DTo2D< Space, KSpace >::setCameraDirection().
 {
   board.setCameraDirection(cd.dirx, cd.diry, cd.dirz);
 }
template<typename Space , typename KSpace > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::CameraUpVector & aThing) inline static
set the camera up vector on the board
Parameters
board the board where to draw
aThing the camera up vector to set
Definition at line 60 of file Board3DTo2DFactory.ih.
References DGtal::Board3DTo2D< Space, KSpace >::setCameraUpVector(), DGtal::CameraUpVector::upx, DGtal::CameraUpVector::upy, and DGtal::CameraUpVector::upz.
 {
   board.setCameraUpVector(cuv.upx, cuv.upy, cuv.upz);
 }
template<typename Space , typename KSpace > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::CameraZNearFar & aThing) inline static
set the near and far distance on the board
Parameters
board the board where to draw
aThing the near and far distance
Definition at line 68 of file Board3DTo2DFactory.ih.
References DGtal::Board3DTo2D< Space, KSpace >::setNearFar(), DGtal::CameraZNearFar::ZFar, and DGtal::CameraZNearFar::ZNear.
 {
   board.setNearFar(cz.ZNear, cz.ZFar);
 }
template<typename Space , typename KSpace > template<typename TVector > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::SphericalAccumulator< TVector > & accumulator, const typename DGtal::SphericalAccumulator< TVector >::RealVector & shift = typename DGtal::SphericalAccumulator<TVector>::RealVector(0,0,0), const double radius = 1.0) inline static
Display an spherical accumulator in 3D. Bin values are mapped using a default HueShadeColorMap.
Parameters
board the board where to draw current board
accumulator the accumulator to board
shift translate vector for board purposes (default: zero vector)
radius scale factor for the unit sphere radius (default:1)
Template Parameters
TVector a vector model
Display an spherical accumulator in 3D. Bin values are mapped using a default HueShadeColorMap.
Parameters
board current board
accumulator the accumulator to board
shift translate vector for board purposes (default: zero vector)
radius scale factor for the unit sphere radius (default:1)
Template Parameters
TVector a vector model
Definition at line 94 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw ( board, accumulator, shift, radius);
 }
template<typename Space , typename KSpace > template<typename TPoint > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::Mesh< TPoint > & aMesh) inline static
draw
Parameters
board the board where to draw
aMesh the mesh to draw
Definition at line 117 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw (board, aMesh);
 }
template<typename Space , typename KSpace > template<typename TIterator , typename TInteger , int connectivity> void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > & arithm) inline static
draw
Parameters
board the board where to draw
arithm the arithm to draw
Definition at line 158 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw(board , arithm);
 }
template<typename Space , typename KSpace > template<typename Domain , typename Compare > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::DigitalSetBySTLSet< Domain, Compare > & aSet) inline static
draw
Parameters
board the board where to draw
aSet the set to draw
Definition at line 211 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aSet);
 }
template<typename Space , typename KSpace > template<typename Domain > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::DigitalSetBySTLVector< Domain > & aSet) inline static
draw
Parameters
board the board where to draw
aSet the set to draw
Definition at line 264 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aSet);
 }
template<typename TSpace , typename TKSpace > template<typename TSpace> void DGtal::Board3DTo2DFactory< TSpace, TKSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::HyperRectDomain< TSpace > & aDomain) inline
Definition at line 327 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aDomain);
 }
template<typename TSpace , typename TKSpace > template<typename SpaceDom > static void DGtal::Board3DTo2DFactory< TSpace, TKSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::HyperRectDomain< SpaceDom > & aDomain) static
draw
Parameters
board the board where to draw
aDomain the domain to draw
template<typename Space , typename KSpace > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const typename KSpace::Cell & aCell) inline static
draw
Parameters
board the board where to draw
aCell the cell to draw
Definition at line 348 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aCell);
 }
template<typename Space , typename KSpace > template<typename TDigitalTopology , typename TDigitalSet > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::Object< TDigitalTopology, TDigitalSet > & anObject) inline static
draw
Parameters
board the board where to draw
anObject the object to draw
Definition at line 378 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, anObject);
 }
template<typename Space , typename KSpace > template<DGtal::Dimension dim, typename TComponent > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::PointVector< dim, TComponent > & aPoint) inline static
draw
Parameters
board the board where to draw
aPoint the point to draw
Definition at line 431 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aPoint);
 }
template<typename Space , typename KSpace > template<DGtal::Dimension dim, typename TComponent > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::PointVector< dim, TComponent > & aPoint, const DGtal::PointVector< dim, TComponent > & aPoint2) inline static
draw
Parameters
board the board where to draw
aPoint the point to draw
aPoint2 the point to draw
Definition at line 440 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aPoint, aPoint2);
 }
template<typename Space , typename KSpace > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const typename KSpace::SCell & aSCell) inline static
draw
Parameters
board the board where to draw
aSCell the signed cell to draw
Definition at line 464 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aSCell);
 }
template<typename Space , typename KSpace > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::GridCurve< KSpace > & aGrid) inline static
draw
Parameters
board the board where to draw
aGrid the grid to draw
Definition at line 475 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aGrid);
 }
template<typename Space , typename KSpace > template<typename TIterator, typename TSCell > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (DGtal::Board3DTo2D< Space, KSpace > & board, const ConstRangeAdapter< TIterator, DGtal::DefaultFunctor, TSCell > & aRangeAdapter) inline static
draw
Parameters
board the board where to draw
aRangeAdapter the range adapter to draw
Definition at line 487 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aRangeAdapter);
 }
template<typename Space , typename KSpace > template<typename TIterator> void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::ConstRangeAdapter< TIterator, SCellToPoint< KSpace >, typename KSpace::Point > & aRangeAdapter) inline static
draw
Parameters
board the board where to draw
aRangeAdapter the range adapter to draw
Definition at line 500 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aRangeAdapter);
 }
template<typename Space , typename KSpace > template<typename TIterator> void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::ConstRangeAdapter< TIterator, CanonicSCellEmbedder< KSpace >, typename KSpace::Space::RealPoint > & aRangeAdapter) inline static
draw
Parameters
board the board where to draw
aRangeAdapter the range adapter to draw
Definition at line 513 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aRangeAdapter);
 }
template<typename Space , typename KSpace > template<typename TIterator> void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::ConstRangeAdapter< TIterator, SCellToArrow< KSpace >, std::pair< typename KSpace::Point, typename KSpace::Vector > > & aRangeAdapter) inline static
draw
Parameters
board the board where to draw
aRangeAdapter the range adapter to draw
Definition at line 526 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aRangeAdapter);
 }
template<typename Space , typename KSpace > template<typename TIterator> void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::ConstRangeAdapter< TIterator, SCellToInnerPoint< KSpace >, typename KSpace::Point > & aRangeAdapter) inline static
draw
Parameters
board the board where to draw
aRangeAdapter the range adapter to draw
Definition at line 539 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aRangeAdapter);
 }
template<typename Space , typename KSpace > template<typename TIterator> void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::ConstRangeAdapter< TIterator, SCellToOuterPoint< KSpace >, typename KSpace::Point > & aRangeAdapter) inline static
draw
Parameters
board the board where to draw
aRangeAdapter the range adapter to draw
Definition at line 552 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aRangeAdapter);
 }
template<typename Space , typename KSpace > template<typename TIterator> void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::ConstRangeAdapter< TIterator, SCellToIncidentPoints< KSpace >, std::pair< typename KSpace::Point, typename KSpace::Point > > & aRangeAdapter) inline static
draw
Parameters
board the board where to draw
aRangeAdapter the range adapter to draw
Definition at line 565 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aRangeAdapter);
 }
template<typename Space , typename KSpace > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::SetMode3D & aMode) inline static
draw
Parameters
board the board where to draw
aMode the mode to set
Definition at line 577 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aMode);
 }
template<typename Space , typename KSpace > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::CustomStyle3D & aStyle) inline static
draw
Parameters
board the board where to draw
aStyle the style to set
Definition at line 586 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aStyle);
 }
template<typename Space , typename KSpace > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::CustomColors3D & aColor) inline static
draw
Parameters
board the board where to draw
aColor the color to set
Definition at line 594 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aColor);
 }
template<typename Space , typename KSpace > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::ClippingPlane & aClipping) inline static
draw
Parameters
board the board where to draw
aClipping the clipping plane to draw
Definition at line 602 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aClipping);
 }
template<typename Space , typename KSpace > void DGtal::Board3DTo2DFactory< Space, KSpace >::draw (Board3DTo2D< Space, KSpace > & board, const DGtal::TransformedSurfelPrism & aTransformedSurfelPrism) inline static
draw
Parameters
board the board where to draw
aTransformedSurfelPrism the transformed surfelprism to draw
Definition at line 611 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( board, aTransformedSurfelPrism);
 }
template<typename Space , typename KSpace > template<typename TIterator , typename TInteger , int connectivity> void DGtal::Board3DTo2DFactory< Space, KSpace >::drawAsBalls (Board3DTo2D< Space, KSpace > & board, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > & arithm) inline static
drawAsBalls
Parameters
board the board where to draw
arithm the arithm to draw
Definition at line 142 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsBalls().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsBalls(board, arithm);
 }
template<typename Space , typename KSpace > template<typename TIterator , typename TInteger , int connectivity> void DGtal::Board3DTo2DFactory< Space, KSpace >::drawAsBoundingBox (Board3DTo2D< Space, KSpace > & board, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > & arithm) inline static
drawAsBoundingBox
Parameters
board the board where to draw
arithm the arithm to draw
Definition at line 150 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsBoundingBox().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsBoundingBox(board, arithm);
 }
template<typename TSpace , typename TKSpace > template<typename TSpace > void DGtal::Board3DTo2DFactory< TSpace, TKSpace >::drawAsBoundingBox (Board3DTo2D< Space, KSpace > & board, const DGtal::HyperRectDomain< TSpace > & aDomain) inline
Definition at line 290 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsBoundingBox().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsBoundingBox( board, aDomain);
 }
template<typename TSpace , typename TKSpace > template<typename SpaceDom > static void DGtal::Board3DTo2DFactory< TSpace, TKSpace >::drawAsBoundingBox (Board3DTo2D< Space, KSpace > & board, const DGtal::HyperRectDomain< SpaceDom > & aDomain) static
drawAsBoundingBox
Parameters
board the board where to draw
aDomain the domain to draw
template<typename Space , typename KSpace > template<typename TPoint > void DGtal::Board3DTo2DFactory< Space, KSpace >::drawAsFaces (Board3DTo2D< Space, KSpace > & board, const DGtal::Mesh< TPoint > & aMesh) inline static
drawAsFaces
Parameters
board the board where to draw
aMesh the mesh to draw
Definition at line 108 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsFaces().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsFaces( board, aMesh);
 }
template<typename Space , typename KSpace > template<typename Domain , typename Compare > void DGtal::Board3DTo2DFactory< Space, KSpace >::drawAsGrid (Board3DTo2D< Space, KSpace > & board, const DGtal::DigitalSetBySTLSet< Domain, Compare > & aSet) inline static
drawAsGrid
Parameters
board the board where to draw
aSet the set to draw
Definition at line 202 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsGrid().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsGrid(board, aSet);
 }
template<typename Space , typename KSpace > template<typename Domain > void DGtal::Board3DTo2DFactory< Space, KSpace >::drawAsGrid (Board3DTo2D< Space, KSpace > & board, const DGtal::DigitalSetBySTLVector< Domain > & aSet) inline static
drawAsGrid
Parameters
board the board where to draw
aSet the set to draw
Definition at line 255 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsGrid().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsGrid(board, aSet);
 }
template<typename TSpace , typename TKSpace > template<typename TSpace> void DGtal::Board3DTo2DFactory< TSpace, TKSpace >::drawAsGrid (Board3DTo2D< Space, KSpace > & board, const DGtal::HyperRectDomain< TSpace > & aDomain) inline
Definition at line 299 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsGrid().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsGrid( board, aDomain);
 }
template<typename TSpace , typename TKSpace > template<typename SpaceDom > static void DGtal::Board3DTo2DFactory< TSpace, TKSpace >::drawAsGrid (Board3DTo2D< Space, KSpace > & board, const DGtal::HyperRectDomain< SpaceDom > & aDomain) static
drawAsGrid
Parameters
board the board where to draw
aDomain the domain to draw
template<typename Space , typename KSpace > template<DGtal::Dimension dim, typename TComponent > void DGtal::Board3DTo2DFactory< Space, KSpace >::drawAsGrid (Board3DTo2D< Space, KSpace > & board, const DGtal::PointVector< dim, TComponent > & aPoint) inline static
drawAsGrid
Parameters
board the board where to draw
aPoint the point to draw
Definition at line 404 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsGrid().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsGrid( board, aPoint);
 }
template<typename Space , typename KSpace > template<typename Domain , typename Compare > void DGtal::Board3DTo2DFactory< Space, KSpace >::drawAsPaving (Board3DTo2D< Space, KSpace > & board, const DGtal::DigitalSetBySTLSet< Domain, Compare > & aSet) inline static
drawAsPaving
Parameters
board the board where to draw
aSet the set to draw
Definition at line 193 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPaving().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsPaving( board, aSet);
 }
template<typename Space , typename KSpace > template<typename Domain > void DGtal::Board3DTo2DFactory< Space, KSpace >::drawAsPaving (Board3DTo2D< Space, KSpace > & board, const DGtal::DigitalSetBySTLVector< Domain > & aSet) inline static
drawAsPaving
Parameters
board the board where to draw
aSet the set to draw
Definition at line 246 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPaving().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsPaving( board, aSet);
 }
template<typename TSpace , typename TKSpace > template<typename TSpace> void DGtal::Board3DTo2DFactory< TSpace, TKSpace >::drawAsPaving (Board3DTo2D< Space, KSpace > & board, const DGtal::HyperRectDomain< TSpace > & aDomain) inline
Definition at line 317 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPaving().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsPaving( board, aDomain);
 }
template<typename TSpace , typename TKSpace > template<typename SpaceDom > static void DGtal::Board3DTo2DFactory< TSpace, TKSpace >::drawAsPaving (Board3DTo2D< Space, KSpace > & board, const DGtal::HyperRectDomain< SpaceDom > & aDomain) static
drawAsPaving
Parameters
board the board where to draw
aDomain the domain to draw
template<typename Space , typename KSpace > template<DGtal::Dimension dim, typename TComponent > void DGtal::Board3DTo2DFactory< Space, KSpace >::drawAsPaving (Board3DTo2D< Space, KSpace > & board, const DGtal::PointVector< dim, TComponent > & aPoint) inline static
drawAsPaving
Parameters
board the board where to draw
aPoint the point to draw
Definition at line 413 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPaving().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsPaving( board, aPoint);
 }
template<typename TSpace , typename TKSpace > template<typename TSpace > void DGtal::Board3DTo2DFactory< TSpace, TKSpace >::drawAsPavingBalls (Board3DTo2D< Space, KSpace > & board, const DGtal::HyperRectDomain< TSpace > & aDomain) inline
Definition at line 308 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingBalls().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsPavingBalls( board, aDomain);
 }
template<typename TSpace , typename TKSpace > template<typename SpaceDom > static void DGtal::Board3DTo2DFactory< TSpace, TKSpace >::drawAsPavingBalls (Board3DTo2D< Space, KSpace > & board, const DGtal::HyperRectDomain< SpaceDom > & aDomain) static
drawAsPavingBalls
Parameters
board the board where to draw
aDomain the domain to draw
template<typename Space , typename KSpace > template<typename Domain , typename Compare > void DGtal::Board3DTo2DFactory< Space, KSpace >::drawAsPavingTransparent (Board3DTo2D< Space, KSpace > & board, const DGtal::DigitalSetBySTLSet< Domain, Compare > & aSet) inline static
drawAsPavingTransparent
Parameters
board the board where to draw
aSet the set to draw
Definition at line 184 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingTransparent().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsPavingTransparent(board, aSet);
 }
template<typename Space , typename KSpace > template<typename Domain > void DGtal::Board3DTo2DFactory< Space, KSpace >::drawAsPavingTransparent (Board3DTo2D< Space, KSpace > & board, const DGtal::DigitalSetBySTLVector< Domain > & aSet) inline static
drawAsPavingTransparent
Parameters
board the board where to draw
aSet the set to draw
Definition at line 237 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingTransparent().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsPavingTransparent( board, aSet);
 }
template<typename Space , typename KSpace > template<DGtal::Dimension dim, typename TComponent > void DGtal::Board3DTo2DFactory< Space, KSpace >::drawAsPavingWired (Board3DTo2D< Space, KSpace > & board, const DGtal::PointVector< dim, TComponent > & aPoint) inline static
drawAsPavingWired
Parameters
board the board where to draw
aPoint the point to draw
Definition at line 422 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingWired().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsPavingWired( board, aPoint);
 }
template<typename Space , typename KSpace > template<typename TDigitalTopology , typename TDigitalSet > void DGtal::Board3DTo2DFactory< Space, KSpace >::drawWithAdjacencies (Board3DTo2D< Space, KSpace > & board, const DGtal::Object< TDigitalTopology, TDigitalSet > & anObject) inline static
drawWithAdjacencies
Parameters
board the board where to draw
anObject the object to draw
Definition at line 370 of file Board3DTo2DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawWithAdjacencies().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawWithAdjacencies( board, anObject);
 }
The documentation for this struct was generated from the following files:
Board3DTo2DFactory.h
Board3DTo2DFactory.ih