DGtal: LibBoard::TransformFIG Struct Reference
LibBoard::TransformFIG Struct Reference
#include <Transforms.h>
Public Member Functions
TransformFIG ()
double rounded (double x) const
double mapY (double y) const
int mapWidth (double width) const
void setBoundingBox (const Rect &rect, const double pageWidth, const double pageHeight, const double margin)
void setDepthRange (const ShapeList &shapes)
int mapDepth (int depth) const
Public Member Functions inherited from LibBoard::Transform
Transform ()
virtual ~Transform ()
virtual double mapX (double x) const
virtual void apply (double &x, double &y) const
virtual double scale (double x) const
Private Attributes
int _maxDepth
int _minDepth
Additional Inherited Members
Static Public Member Functions inherited from LibBoard::Transform
static double round (const double &x)
Protected Attributes inherited from LibBoard::Transform
double _scale
double _deltaX
double _deltaY
double _height
Detailed Description
Structure representing a scaling and translation suitable for an XFig output.
The TransformFIG structure.
Definition at line 73 of file Transforms.h.
Constructor & Destructor Documentation
TransformFIG::TransformFIG () inline
Definition at line 8 of file Transforms.h.
                    {
Member Function Documentation
int LibBoard::TransformFIG::mapDepth (int depth) const
Definition at line 158 of file Transforms.cpp.
References _maxDepth, _minDepth, and LibBoard::Transform::round().
Referenced by LibBoard::Dot::flushFIG(), LibBoard::Line::flushFIG(), LibBoard::Arrow::flushFIG(), LibBoard::Polyline::flushFIG(), LibBoard::Rectangle::flushFIG(), LibBoard::Image::flushFIG(), LibBoard::Ellipse::flushFIG(), and LibBoard::Text::flushFIG().
 {
   if ( depth > _maxDepth ) return 999;
   if ( _maxDepth - _minDepth > 998 ) {
     double range = _maxDepth - _minDepth;
     int r = static_cast<int>( 1 + Transform::round( ( ( depth - _minDepth ) / range ) * 998 ) );
     return r>=0?r:0;
   } else {
     int r = 1 + depth - _minDepth;
     return r>=0?r:0;
   }
 }
int LibBoard::TransformFIG::mapWidth (double width) const
Definition at line 111 of file Transforms.cpp.
References LibBoard::Transform::round().
Referenced by LibBoard::Dot::flushFIG(), LibBoard::Line::flushFIG(), LibBoard::Arrow::flushFIG(), LibBoard::Polyline::flushFIG(), LibBoard::Rectangle::flushFIG(), LibBoard::Image::flushFIG(), and LibBoard::Ellipse::flushFIG().
 {
   // FIG width unit is 1/160 inch
   // Postscript points are 1/72 inch
   if ( width == 0.0 ) return 0;
   int result = static_cast<int>( Transform::round( 160 * ( width / 72.0 ) ) );
   return result>0?result:1;
 }
double LibBoard::TransformFIG::mapY (double y) const virtual
Implements LibBoard::Transform.
Definition at line 105 of file Transforms.cpp.
References LibBoard::Transform::_deltaY, LibBoard::Transform::_height, LibBoard::Transform::_scale, and rounded().
Referenced by LibBoard::Path::flushFIG(), LibBoard::Group::flushFIG(), LibBoard::Dot::flushFIG(), LibBoard::Line::flushFIG(), LibBoard::Arrow::flushFIG(), LibBoard::Ellipse::flushFIG(), and LibBoard::Text::flushFIG().
 {
   return rounded( _height - ( y * _scale + _deltaY ) );
 }
double LibBoard::TransformFIG::rounded (double x) const virtual
Reimplemented from LibBoard::Transform.
Definition at line 99 of file Transforms.cpp.
References LibBoard::Transform::round().
Referenced by mapY().
 {
   return Transform::round( x );
 }
void LibBoard::TransformFIG::setBoundingBox (const Rect & rect, const double pageWidth, const double pageHeight, const double margin) virtual
Implements LibBoard::Transform.
Definition at line 121 of file Transforms.cpp.
References LibBoard::Transform::_deltaX, LibBoard::Transform::_deltaY, LibBoard::Transform::_height, LibBoard::Transform::_scale, LibBoard::Rect::height, LibBoard::Rect::left, LibBoard::Rect::top, and LibBoard::Rect::width.
Referenced by LibBoard::Board::saveFIG().
 {
   if ( pageWidth <= 0 || pageHeight <= 0 ) {
     _scale = fig_ppmm / ppmm;
     _deltaX = 0.5 * 210 * fig_ppmm - _scale * ( rect.left + 0.5 * rect.width );
     //_deltaX = - rect.left;
     _deltaY = 0.5 * 297 * fig_ppmm - _scale * ( rect.top - 0.5 * rect.height );
     // _deltaY = - rect.top;
     // _deltaY = - ( rect.top - rect.height );
     //_height = rect.height;
     _height = 297 * fig_ppmm;
   } else {
     const double w = pageWidth - 2 * margin;
     const double h = pageHeight - 2 * margin;
     if ( rect.height / rect.width > ( h / w ) ) {
       _scale = ( h * fig_ppmm ) / rect.height;
     } else {
       _scale = ( w * fig_ppmm ) / rect.width;
     }
     _deltaX = 0.5 * pageWidth * fig_ppmm - _scale * ( rect.left + 0.5 * rect.width );
     _deltaY = 0.5 * pageHeight * fig_ppmm - _scale * ( rect.top - 0.5 * rect.height );
     _height = pageHeight * fig_ppmm;
   }
   // float ppmm = (1200/25.4);
 }
void LibBoard::TransformFIG::setDepthRange (const ShapeList & shapes)
Definition at line 151 of file Transforms.cpp.
References _maxDepth, _minDepth, LibBoard::ShapeList::maxDepth(), and LibBoard::ShapeList::minDepth().
Referenced by LibBoard::Board::saveFIG().
 {
   _maxDepth = shapes.maxDepth();
   _minDepth = shapes.minDepth();
 }
Field Documentation
int LibBoard::TransformFIG::_maxDepth private
Definition at line 86 of file Transforms.h.
Referenced by mapDepth(), and setDepthRange().
int LibBoard::TransformFIG::_minDepth private
Definition at line 87 of file Transforms.h.
Referenced by mapDepth(), and setDepthRange().
The documentation for this struct was generated from the following files:
Transforms.h
Transforms.cpp
Transforms.ih