DGtal: DGtal::DefaultDrawStyle_FP Struct Reference
DGtal::DefaultDrawStyle_FP Struct Reference
Public Member Functions
virtual void setStyle (Board2D &aBoard) const
Public Member Functions inherited from DGtal::DrawableWithBoard2D
virtual ~DrawableWithBoard2D ()
Detailed Description
Default style.
Definition at line 178 of file Style2DFactory.ih.
Member Function Documentation
virtual void DGtal::DefaultDrawStyle_FP::setStyle (Board2D & aBoard) const inline virtual
Drawing method.
Parameters
aBoard the output board where the object is drawn.
Reimplemented from DGtal::DrawableWithBoard2D.
Definition at line 184 of file Style2DFactory.ih.
References DGtal::Color::None, DGtal::Color::Red, LibBoard::Board::setFillColor(), LibBoard::Board::setLineStyle(), LibBoard::Board::setLineWidth(), LibBoard::Board::setPenColor(), and LibBoard::Shape::SolidStyle.
     {
       // Set board style
       aBoard.setLineStyle(Board2D::Shape::SolidStyle);
       aBoard.setPenColor(Color::Red);
       aBoard.setLineWidth(2);
       aBoard.setFillColor(Color::None);
     }
The documentation for this struct was generated from the following file:
Style2DFactory.ih