DGtal: DGtal::MeshWriter< TPoint > Struct Template Reference
DGtal::MeshWriter< TPoint > Struct Template Reference
#include <MeshWriter.h>
Static Public Member Functions
static bool export2OFF (std::ostream &out, const Mesh< TPoint > &aMesh, bool exportColor=false) throw (DGtal::IOException)
static bool export2OBJ (std::ostream &out, const Mesh< TPoint > &aMesh) throw (DGtal::IOException)
Detailed Description
template<typename TPoint>
struct DGtal::MeshWriter< TPoint >
Aim: Export a Mesh (Mesh object) in different format as OFF and OBJ).
Description of template struct 'MeshWriter'
The exportation can be done automatically according the input file extension with the ">>" operator
Example of typical use: First you have to add the following include files:
Then you create a simple Mesh object:
Finally you can export directly the Mesh object:
See Also
Mesh MeshWriter
Definition at line 76 of file MeshWriter.h.
Member Function Documentation
template<typename TPoint > bool DGtal::MeshWriter< TPoint >::export2OBJ (std::ostream & out, const Mesh< TPoint > & aMesh) throw (DGtal::IOException) inline static
Export a Mesh towards a OBJ format.
Parameters
out the output stream of the exported OBJ object.
aMesh the Mesh object to be exported.
Returns
true if no errors occur.
Definition at line 88 of file MeshWriter.ih.
References DGtal::Trace::error(), and DGtal::trace.
Referenced by DGtal::operator>>().
{
   DGtal::IOException dgtalio;
   try
     {
       out << "#  OBJ format"<< std::endl;
       out << "# generated from MeshWriter from the DGTal library"<< std::endl;
       out << std::endl;
       out << "o anObj" << std::endl;
       out << std::endl;
       // processing vertex
       for(unsigned int i=0; i< aMesh.nbVertex(); i++){
         out << "v " << aMesh.getVertex(i)[0] << " " << aMesh.getVertex(i)[1] << " "<< aMesh.getVertex(i)[2] << std::endl;
       }
       out << std::endl;
       // processing faces:
       for (unsigned int i=0; i< aMesh.nbFaces(); i++){
         std::vector<unsigned int>  aFace = aMesh.getFace(i);
         out << "f " ;
         for(unsigned int j=0; j<aFace.size(); j++){
           unsigned int indexVertex = aFace.at(j);
           out << (indexVertex+1) << " " ;
         }
         out << std::endl;
       }
       out << std::endl;
     }catch( ... )
     {
       trace.error() << "OBJ writer IO error on export "  << std::endl;
       throw dgtalio;
     }
   return true;
 }
template<typename TPoint > bool DGtal::MeshWriter< TPoint >::export2OFF (std::ostream & out, const Mesh< TPoint > & aMesh, bool exportColor = false) throw (DGtal::IOException) inline static
Export Mesh towards a OFF format.
Parameters
out the output stream of the exported OFF object.
aMesh the Mesh object to be exported.
exportColor true to export colors (default false).
Returns
true if no errors occur.
Definition at line 47 of file MeshWriter.ih.
References DGtal::Color::alpha(), DGtal::Color::blue(), DGtal::Trace::error(), DGtal::Color::green(), DGtal::Color::red(), and DGtal::trace.
Referenced by DGtal::operator>>().
{
   DGtal::IOException dgtalio;
   try
     {
       out << "OFF"<< std::endl;
       out << "# generated from MeshWriter from the DGTal library"<< std::endl;
       out << aMesh.nbVertex()  << " " << aMesh.nbFaces() << " " << 0 << " " << std::endl;
       for(unsigned int i=0; i< aMesh.nbVertex(); i++){
         out << aMesh.getVertex(i)[0] << " " << aMesh.getVertex(i)[1] << " "<< aMesh.getVertex(i)[2] << std::endl;
       }
       for (unsigned int i=0; i< aMesh.nbFaces(); i++){
         std::vector<unsigned int>  aFace = aMesh.getFace(i);
         out << aFace.size() << " " ;
         for(unsigned int j=0; j<aFace.size(); j++){
           unsigned int indexVertex = aFace.at(j);
           out << indexVertex << " " ;
         }
         DGtal::Color col = aMesh.getFaceColor(i);
         if(exportColor){
           out << " ";
           out << ((double) col.red())/255.0 << " "
               << ((double) col.green())/255.0 << " "<< ((double) col.blue())/255.0
               << " " << ((double) col.alpha())/255.0 ;
         }
         out << std::endl;
       }
     }catch( ... )
     {
       trace.error() << "OFF writer IO error on export " << std::endl;
       throw dgtalio;
     }
   return true;
 }
The documentation for this struct was generated from the following files:
MeshWriter.h
MeshWriter.ih