DGtal: DGtal::GenericReader< TContainer, 2 > Struct Template Reference
DGtal::GenericReader< TContainer, 2 > Struct Template Reference
#include <GenericReader.h>
Public Member Functions
BOOST_CONCEPT_ASSERT ((CImage< TContainer >))
Static Public Member Functions
static TContainer import (const std::string &filename) throw (DGtal::IOException)
template<typename TFunctor >
static TContainer importWithColorFunctor (const std::string &filename, const TFunctor &aFunctor) throw (DGtal::IOException)
template<typename TFunctor >
static TContainer importWithValueFunctor (const std::string &filename, const TFunctor &aFunctor) throw (DGtal::IOException)
Detailed Description
template<typename TContainer>
struct DGtal::GenericReader< TContainer, 2 >
GenericReader Template partial specialisation for volume images of dimension 2
Definition at line 197 of file GenericReader.h.
Member Function Documentation
template<typename TContainer > DGtal::GenericReader< TContainer, 2 >::BOOST_CONCEPT_ASSERT ((CImage< TContainer >))
template<typename TContainer > TContainer DGtal::GenericReader< TContainer, 2 >::import (const std::string & filename) throw (DGtal::IOException) inline static
Import a volume image file. For the special format h5 (you need to set WITH_HDF5 of cmake build), the default parameter datasetName needs to be updated according to the dimension if the image.
Parameters
filename the image filename to be imported.
Definition at line 105 of file GenericReader.ih.
References DGtal::Trace::error(), DGtal::MagickReader< TImageContainer, TFunctor >::importImage(), and DGtal::trace.
 {
   DGtal::IOException dgtalio;
   //Getting image extension
   std::string extension = filename.substr(filename.find_last_of(".") + 1);
   if(extension=="pgm")
     return PGMReader<TContainer>::importPGM(filename);
   if(extension=="ppm")
     return PPMReader<TContainer>::importPPM(filename);
 #ifdef WITH_HDF5
    if (extension=="h5")
      return HDF5Reader<TContainer>::importHDF5(filename, "image8bit");
 #endif
    if( extension=="gif" || extension=="jpg" || extension=="png" || extension=="jpeg" || extension=="bmp")
      {
 #ifdef WITH_MAGICK
        MagickReader<TContainer> reader;
        return reader.importImage( filename );
 #else
        trace.error() << "Extension " << extension<< " not yet implemented in DGtal but you can add Magick option to deal with this image type." << std::endl;
        throw dgtalio;
 #endif
      }
    trace.error() << "Extension " << extension<< " not yet implemented in DGtal GenericReader." << std::endl;
    throw dgtalio;
 }
template<typename TContainer > template<typename TFunctor > static TContainer DGtal::GenericReader< TContainer, 2 >::importWithColorFunctor (const std::string & filename, const TFunctor & aFunctor) throw (DGtal::IOException) inline static
Import an image file by specifying a color encoder functor (used only for color image format ppm, (gif, jpeg, ... if the magick image lib is installed) .
Template Parameters
TFunctor The type of the functor (should verify the concept CUnaryFunctor<TFunctor, TContainer::Value, DGtal::Color >).
Parameters
aFunctor an ColorRGBEncoder. The type of the functor (should verify the concept CUnaryFunctor<TFunctor, TContainer::Value, DGtal::Color >). image.
Definition at line 224 of file GenericReader.h.
References DGtal::GenericReader< TContainer, Tdim >::BOOST_CONCEPT_ASSERT(), DGtal::Trace::error(), DGtal::MagickReader< TImageContainer, TFunctor >::importImage(), DGtal::PPMReader< TImageContainer, TFunctor >::importPPM(), and DGtal::trace.
{
       BOOST_CONCEPT_ASSERT((  CUnaryFunctor<TFunctor, typename TContainer::Value, DGtal::Color> )) ;
       DGtal::IOException dgtalio;
       //Getting image extension
       std::string extension = filename.substr(filename.find_last_of(".") + 1);
       if(extension=="ppm")
         return PPMReader<TContainer>::importPPM(filename, aFunctor);
       if( extension=="gif" || extension=="jpg" || extension=="png" || extension=="jpeg" || extension=="bmp")
         {
 #ifdef WITH_MAGICK
           MagickReader<TContainer> reader;
           return reader.importImage( filename, aFunctor );
 #else
           trace.error() << "Extension " << extension<< " not yet implemented in DGtal but you can add Magick option to deal with this image type." << std::endl;
           throw dgtalio;
 #endif
         }
       trace.error() << "Extension " << extension<< " not yet implemented in DGtal GenericReader." << std::endl;
       throw dgtalio;
     }
template<typename TContainer > template<typename TFunctor > static TContainer DGtal::GenericReader< TContainer, 2 >::importWithValueFunctor (const std::string & filename, const TFunctor & aFunctor) throw (DGtal::IOException) inline static
Import an image file by specifying a value functor used for grayscale image.
Template Parameters
TFunctor The type of the functor (should verify the concept CUnaryFunctor<TFunctor, unsigned char, TContainer::Value >).
Parameters
aFunctor to transform input unsigned char of image value into the given image type. image.
Definition at line 261 of file GenericReader.h.
References DGtal::GenericReader< TContainer, Tdim >::BOOST_CONCEPT_ASSERT(), DGtal::Trace::error(), DGtal::HDF5Reader< TImageContainer, TFunctor >::importHDF5(), DGtal::PGMReader< TImageContainer, TFunctor >::importPGM(), and DGtal::trace.
{
       BOOST_CONCEPT_ASSERT((  CUnaryFunctor<TFunctor, unsigned char, typename TContainer::Value > )) ;
       DGtal::IOException dgtalio;
       //Getting image extension
       std::string extension = filename.substr(filename.find_last_of(".") + 1);
       if(extension=="pgm")
         return PGMReader<TContainer>::importPGM(filename, aFunctor);
 #ifdef WITH_HDF5
       if (extension=="h5")
         return HDF5Reader<TContainer>::importHDF5(filename, "image8bit", aFunctor);
 #endif
       trace.error() << "Extension " << extension<< " not yet implemented in DGtal GenericReader." << std::endl;
       throw dgtalio;
     }
The documentation for this struct was generated from the following files:
GenericReader.h
GenericReader.ih