DGtal: DGtal::GenericReader< TContainer, 3 > Struct Template Reference
DGtal::GenericReader< TContainer, 3 > Struct Template Reference
#include <GenericReader.h>
Public Member Functions
BOOST_CONCEPT_ASSERT ((CImage< TContainer >))
Static Public Member Functions
static TContainer import (const std::string &filename, unsigned int x=0, unsigned int y=0, unsigned int z=0) throw (DGtal::IOException)
template<typename TFunctor >
static TContainer importWithValueFunctor (const std::string &filename, const TFunctor &aFunctor, unsigned int x=0, unsigned int y=0, unsigned int z=0) throw (DGtal::IOException)
Detailed Description
template<typename TContainer>
struct DGtal::GenericReader< TContainer, 3 >
GenericReader Template partial specialisation for volume images of dimension 3
Definition at line 121 of file GenericReader.h.
Member Function Documentation
template<typename TContainer > DGtal::GenericReader< TContainer, 3 >::BOOST_CONCEPT_ASSERT ((CImage< TContainer >))
template<typename TContainer > TContainer DGtal::GenericReader< TContainer, 3 >::import (const std::string & filename, unsigned int x = 0, unsigned int y = 0, unsigned int z = 0) throw (DGtal::IOException) inline static
Import a volume image file. For the special format of raw image, the default parameter x,y, z need to be updated according to the dimension if the image.
Parameters
filename the image filename to be imported.
x the size in the x direction.
y the size in the y direction.
z the size in the z direction.
Definition at line 69 of file GenericReader.ih.
References DGtal::Trace::error(), and DGtal::trace.
 {
   DGtal::IOException dgtalio;
   std::string extension = filename.substr(filename.find_last_of(".") + 1);
   if(extension=="vol")
     return  VolReader<TContainer>::importVol( filename );
   if(extension=="longvol")
     return  LongvolReader<TContainer>::importLongvol( filename );
   if(extension=="pgm3d"|| extension=="pgm3D" ||extension=="p3d" || extension=="pgm")
     return PGMReader<TContainer>::importPGM3D(filename);
   if(extension=="raw")
     {
       ASSERT(x!=0 && y!=0 && z!=0);
       typename TContainer::Point pt (x,y,z);
       return RawReader< TContainer >::importRaw8 ( filename, pt  );
     }
 #ifdef WITH_HDF5
   if (extension=="h5")
     return HDF5Reader<TContainer>::importHDF5_3D(filename, "UInt8Array3D");
 #endif
   trace.error() << "Extension " << extension<< " not yet implemented in DGtal GenericReader." << std::endl;
   throw dgtalio;
 }
template<typename TContainer > template<typename TFunctor > static TContainer DGtal::GenericReader< TContainer, 3 >::importWithValueFunctor (const std::string & filename, const TFunctor & aFunctor, unsigned int x = 0, unsigned int y = 0, unsigned int z = 0) throw (DGtal::IOException) inline static
Import an image file by specifying a value functor (used for gray scale image format: vol, longvol, pgm3D, raw).
Template Parameters
TFunctor The type of the functor (should verify the concept CUnaryFunctor<TFunctor, unsigned char , TContainer::Value >).
Parameters
aFunctor an ColorRGBEncoder. The type of the functor (should verify the concept CUnaryFunctor<TFunctor, TContainer::Value, DGtal::Color >).
x x
y y
z z
Definition at line 153 of file GenericReader.h.
References DGtal::GenericReader< TContainer, Tdim >::BOOST_CONCEPT_ASSERT(), DGtal::Trace::error(), DGtal::DicomReader< TImageContainer, TFunctor >::importDicom(), DGtal::HDF5Reader< TImageContainer, TFunctor >::importHDF5_3D(), DGtal::LongvolReader< TImageContainer, TFunctor >::importLongvol(), DGtal::PGMReader< TImageContainer, TFunctor >::importPGM3D(), DGtal::RawReader< TImageContainer, TFunctor >::importRaw8(), DGtal::VolReader< TImageContainer, TFunctor >::importVol(), and DGtal::trace.
{
       BOOST_CONCEPT_ASSERT((  CUnaryFunctor<TFunctor, unsigned char, typename TContainer::Value > )) ;
       DGtal::IOException dgtalio;
       std::string extension = filename.substr(filename.find_last_of(".") + 1);
       if(extension=="vol")
         return  VolReader<TContainer>::importVol( filename, aFunctor );
       if(extension=="longvol")
         return  LongvolReader<TContainer>::importLongvol( filename, aFunctor  );
       if(extension=="pgm3d"|| extension=="pgm3D" || extension=="p3d" || extension=="pgm")
         return PGMReader<TContainer>::importPGM3D(filename, aFunctor);
       if(extension=="raw")
         {
           ASSERT(x!=0 && y!=0 && z!=0);
           typename TContainer::Point pt (x,y,z);
           return RawReader< TContainer >::importRaw8 ( filename, pt, aFunctor  );
         }
 #ifdef WITH_HDF5
       if (extension=="h5")
         return HDF5Reader<TContainer>::importHDF5_3D(filename, "UInt8Array3D", aFunctor);
 #endif
 #ifdef WITH_ITK
       if(extension=="dcm")
         return DicomReader<TContainer>::importDicom(filename, aFunctor);
 #endif
       trace.error() << "Extension " << extension<< " not yet implemented in DGtal GenericReader." << std::endl;
       throw dgtalio;
     }
The documentation for this struct was generated from the following files:
GenericReader.h
GenericReader.ih