DGtal: DGtal::Display3DFactory< TSpace, TKSpace > Struct Template Reference
DGtal::Display3DFactory< TSpace, TKSpace > Struct Template Reference
#include <Display3DFactory.h>
Public Types
typedef TSpace Space
typedef TKSpace KSpace
Public Member Functions
template<typename TV>
void draw (Display3D< Space, KSpace > &display, const DGtal::SphericalAccumulator< TV > &aAccumulator, const typename DGtal::SphericalAccumulator< TV >::RealVector &shift, const double radius)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToPoint< KSpace >, typename KSpace::Point > &object)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, CanonicSCellEmbedder< KSpace >, typename KSpace::Space::RealPoint > &object)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToArrow< KSpace >, std::pair< typename KSpace::Point, typename KSpace::Vector > > &object)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToInnerPoint< KSpace >, typename KSpace::Point > &object)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToOuterPoint< KSpace >, typename KSpace::Point > &object)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToIncidentPoints< KSpace >, std::pair< typename KSpace::Point, typename KSpace::Point > > &object)
Static Public Member Functions
template<typename TVector >
static void draw (Display3D< Space, KSpace > &display, const DGtal::SphericalAccumulator< TVector > &accumulator, const typename DGtal::SphericalAccumulator< TVector >::RealVector &shift=typename DGtal::SphericalAccumulator< TVector >::RealVector(0, 0, 0), const double radius=1.0)
template<typename TPoint >
static void drawAsFaces (Display3D< Space, KSpace > &display, const DGtal::Mesh< TPoint > &aMesh)
template<typename TPoint >
static void draw (Display3D< Space, KSpace > &display, const DGtal::Mesh< TPoint > &aMesh)
template<typename TIterator , typename TInteger , int connectivity>
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &anObject)
template<typename TIterator , typename TInteger , int connectivity>
static void drawAsBalls (Display3D< Space, KSpace > &display, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &anObject)
template<typename TIterator , typename TInteger , int connectivity>
static void drawAsBoundingBox (Display3D< Space, KSpace > &display, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &anObject)
template<typename TIterator , typename TInteger , int connectivity>
static void draw (Display3D< Space, KSpace > &display, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &anObject)
template<typename Domain , typename Compare >
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::DigitalSetBySTLSet< Domain, Compare > &anObject)
template<typename Domain , typename Compare >
static void drawAsPavingTransparent (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLSet< Domain, Compare > &anObject)
template<typename Domain , typename Compare >
static void drawAsPaving (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLSet< Domain, Compare > &anObject)
template<typename Domain , typename Compare >
static void drawAsGrid (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLSet< Domain, Compare > &anObject)
template<typename Domain , typename Compare >
static void draw (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLSet< Domain, Compare > &anObject)
template<typename Domain >
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::DigitalSetBySTLVector< Domain > &anObject)
template<typename Domain >
static void drawAsPavingTransparent (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLVector< Domain > &anObject)
template<typename Domain >
static void drawAsPaving (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLVector< Domain > &anObject)
template<typename Domain >
static void drawAsGrid (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLVector< Domain > &anObject)
template<typename Domain >
static void draw (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLVector< Domain > &anObject)
template<typename SpaceDom >
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::HyperRectDomain< SpaceDom > &anObject)
template<typename SpaceDom >
static void drawAsBoundingBox (Display3D< Space, KSpace > &display, const DGtal::HyperRectDomain< SpaceDom > &anObject)
template<typename SpaceDom >
static void drawAsGrid (Display3D< Space, KSpace > &display, const DGtal::HyperRectDomain< SpaceDom > &anObject)
template<typename SpaceDom >
static void drawAsPavingBalls (Display3D< Space, KSpace > &display, const DGtal::HyperRectDomain< SpaceDom > &anObject)
template<typename SpaceDom >
static void drawAsPaving (Display3D< Space, KSpace > &display, const DGtal::HyperRectDomain< SpaceDom > &anObject)
template<typename SpaceDom >
static void draw (Display3D< Space, KSpace > &display, const DGtal::HyperRectDomain< SpaceDom > &anObject)
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const typename KSpace::Cell &anObject)
static void draw (Display3D< Space, KSpace > &display, const typename KSpace::Cell &anObject)
template<typename TDigitalTopology , typename TDigitalSet >
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::Object< TDigitalTopology, TDigitalSet > &anObject)
template<typename TDigitalTopology , typename TDigitalSet >
static void drawWithAdjacencies (Display3D< Space, KSpace > &display, const DGtal::Object< TDigitalTopology, TDigitalSet > &anObject)
template<typename TDigitalTopology , typename TDigitalSet >
static void draw (Display3D< Space, KSpace > &display, const DGtal::Object< TDigitalTopology, TDigitalSet > &anObject)
template<Dimension dim, typename TComponent >
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::PointVector< dim, TComponent > &anObject)
template<Dimension dim, typename TComponent >
static void drawAsGrid (Display3D< Space, KSpace > &display, const DGtal::PointVector< dim, TComponent > &anObject)
template<Dimension dim, typename TComponent >
static void drawAsPaving (Display3D< Space, KSpace > &display, const DGtal::PointVector< dim, TComponent > &anObject)
template<Dimension dim, typename TComponent >
static void drawAsPavingWired (Display3D< Space, KSpace > &display, const DGtal::PointVector< dim, TComponent > &anObject)
template<Dimension dim, typename TComponent >
static void draw (Display3D< Space, KSpace > &display, const DGtal::PointVector< dim, TComponent > &anObject)
template<Dimension dim, typename TComponent >
static void draw (Display3D< Space, KSpace > &display, const DGtal::PointVector< dim, TComponent > &, const DGtal::PointVector< dim, TComponent > &anObject)
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const typename KSpace::SCell &anObject)
static void draw (Display3D< Space, KSpace > &display, const typename KSpace::SCell &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::GridCurve< KSpace > &anObject)
template<typename TIterator , typename TSCell >
static void draw (DGtal::Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, DGtal::DefaultFunctor, TSCell > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToPoint< KSpace >, typename TKSpace::Point > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, CanonicSCellEmbedder< KSpace >, typename TKSpace::Space::RealPoint > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToArrow< KSpace >, std::pair< typename TKSpace::Point, typename TKSpace::Vector > > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToInnerPoint< KSpace >, typename TKSpace::Point > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToOuterPoint< KSpace >, typename TKSpace::Point > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToIncidentPoints< KSpace >, std::pair< typename TKSpace::Point, typename TKSpace::Point > > &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::SetMode3D &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::CustomStyle3D &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::CustomColors3D &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::ClippingPlane &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::TransformedSurfelPrism &aTransformedSurfelPrism)
Detailed Description
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace>
struct DGtal::Display3DFactory< TSpace, TKSpace >
Factory for GPL Display3D:
Description of struct 'Display3DFactory'
Definition at line 79 of file Display3DFactory.h.
Member Typedef Documentation
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> typedef TKSpace DGtal::Display3DFactory< TSpace, TKSpace >::KSpace
Definition at line 83 of file Display3DFactory.h.
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> typedef TSpace DGtal::Display3DFactory< TSpace, TKSpace >::Space
Definition at line 82 of file Display3DFactory.h.
Member Function Documentation
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator , typename TInteger , int connectivity> static DGtal::DrawableWithDisplay3D* DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle (std::string str, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > & anObject) static
Default drawing style object.
Parameters
str the name of the class
anObject the object to draw
Returns
the dyn. alloc. default style for this object.
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::defaultStyle(), and DGtal::Board3DTo2DFactory< TSpace, TKSpace >::defaultStyle().
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename Domain , typename Compare > static DGtal::DrawableWithDisplay3D* DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle (std::string str, const DGtal::DigitalSetBySTLSet< Domain, Compare > & anObject) static
defaultStyle
Parameters
str the name of the class
anObject the object to draw
Returns
the dyn. alloc. default style for this object.
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename Domain > static DGtal::DrawableWithDisplay3D* DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle (std::string str, const DGtal::DigitalSetBySTLVector< Domain > & anObject) static
Default drawing style object.
Parameters
str the name of the class
anObject the object to draw
Returns
the dyn. alloc. default style for this object.
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename SpaceDom > static DGtal::DrawableWithDisplay3D* DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle (std::string str, const DGtal::HyperRectDomain< SpaceDom > & anObject) static
Default drawing style object.
Parameters
str the name of the class
anObject the object to draw
Returns
the dyn. alloc. default style for this object.
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> static DGtal::DrawableWithDisplay3D* DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle (std::string str, const typename KSpace::Cell & anObject) static
Default drawing style object.
Parameters
str the name of the class
anObject the object to draw
Returns
the dyn. alloc. default style for this object.
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TDigitalTopology , typename TDigitalSet > static DGtal::DrawableWithDisplay3D* DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle (std::string str, const DGtal::Object< TDigitalTopology, TDigitalSet > & anObject) static
Default drawing style object.
Parameters
str the name of the class
anObject the object to draw
Returns
the dyn. alloc. default style for this object.
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<Dimension dim, typename TComponent > static DGtal::DrawableWithDisplay3D* DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle (std::string str, const DGtal::PointVector< dim, TComponent > & anObject) static
Default drawing style object.
Parameters
str the name of the class
anObject the object to draw
Returns
the dyn. alloc. default style for this object.
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> static DGtal::DrawableWithDisplay3D* DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle (std::string str, const typename KSpace::SCell & anObject) static
Default drawing style object.
Parameters
str the name of the class
anObject the object to draw
Returns
the dyn. alloc. default style for this object.
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TV> void DGtal::Display3DFactory< TSpace, TKSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::SphericalAccumulator< TV > & aAccumulator, const typename DGtal::SphericalAccumulator< TV >::RealVector & shift, const double radius) inline
Definition at line 46 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addQuad(), DGtal::SphericalAccumulator< TVector >::begin(), DGtal::SphericalAccumulator< TVector >::binCoordinates(), DGtal::SphericalAccumulator< TVector >::count(), DGtal::SphericalAccumulator< TVector >::end(), DGtal::SphericalAccumulator< TVector >::getBinGeometry(), DGtal::Display3D< Space, KSpace >::getFillColor(), DGtal::SphericalAccumulator< TVector >::isValidBin(), and DGtal::Display3D< Space, KSpace >::setFillColor().
 {
   DGtal::Color saveFillColor = display.getFillColor();
   typedef typename DGtal::SphericalAccumulator<TV>::Size Size;
   typename DGtal::SphericalAccumulator<TV>::RealVector a,b,c,d;
   Size i,j;
   DGtal::int32_t m = 1, M=0;
   for(typename DGtal::SphericalAccumulator<TV>::ConstIterator it = aAccumulator.begin(),
         itend= aAccumulator.end(); it != itend; ++it)
     {
       aAccumulator.binCoordinates(it, i,j);
       if (aAccumulator.isValidBin(i,j))
         {
           if (aAccumulator.count(i,j) > M) M=aAccumulator.count(i,j);
           if (aAccumulator.count(i,j) < m) m=aAccumulator.count(i,j);
         }
     }
   HueShadeColorMap<typename DGtal::SphericalAccumulator<TV>::Quantity> cmap(m,M+1);
   for(typename DGtal::SphericalAccumulator<TV>::ConstIterator it = aAccumulator.begin(),
         itend= aAccumulator.end(); it != itend; ++it)
     {
       aAccumulator.binCoordinates(it, i,j);
       if (aAccumulator.isValidBin(i,j))
         {
           aAccumulator.binCoordinates(it, i,j);
           aAccumulator.getBinGeometry(i,j,a,b,c,d);
           a+= shift;
           b+= shift;
           c+= shift;
           d+= shift;
           a = a*radius;
           b = b*radius;
           c = c*radius;
           d = d*radius;
           display.setFillColor( cmap(aAccumulator.count(i,j)));
           display.addQuad(a, b, c, d);
         }
     }
   display.setFillColor( saveFillColor);
 }
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TVector > static void DGtal::Display3DFactory< TSpace, TKSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::SphericalAccumulator< TVector > & accumulator, const typename DGtal::SphericalAccumulator< TVector >::RealVector & shift = typename DGtal::SphericalAccumulator< TVector >::RealVector(0, 0, 0), const double radius = 1.0) static
Display an spherical accumulator in 3D. Bin values are mapped using a default HueShadeColorMap.
Parameters
display the display where to draw current display
accumulator the accumulator to display
shift translate vector for display purposes (default: zero vector)
radius scale factor for the unit sphere radius (default:1)
Template Parameters
TVector a vector model
Referenced by DGtal::Board3DTo2DFactory< TSpace, TKSpace >::draw(), DGtal::Viewer3DFactory< TSpace, TKSpace >::draw(), DGtal::Board3D< Space, KSpace >::operator<<(), and DGtal::Display3D< Space, KSpace >::operator<<().
template<typename Space , typename KSpace > template<typename TPoint > void DGtal::Display3DFactory< Space, KSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::Mesh< TPoint > & aMesh) inline static
draw
Parameters
display the display where to draw
aMesh the mesh to draw
Definition at line 99 of file Display3DFactory.ih.
References DGtal::Mesh< TPoint >::className(), and DGtal::Display3D< Space, KSpace >::getMode().
 {
   std::string mode = display.getMode( aMesh.className() );
   if ( mode == "Faces" || mode=="")
     drawAsFaces( display, aMesh );
 }
template<typename Space , typename KSpace > template<typename TIterator , typename TInteger , int connectivity> void DGtal::Display3DFactory< Space, KSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > & anObject) inline static
draw
Parameters
display the display where to draw
anObject the object to draw
Definition at line 313 of file Display3DFactory.ih.
References DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity >::className(), and DGtal::Display3D< Space, KSpace >::getMode().
 {
   std::string mode = display.getMode( a.className() );
   if ( mode == "BoundingBox" )
     drawAsBoundingBox( display, a );
   else if ( mode == "Points" )
     drawAsBalls( display, a );
   else if ( ( mode == "" ) )
     {
       drawAsBalls( display, a );
     }
 }
template<typename Space , typename KSpace > template<typename Domain , typename Compare > void DGtal::Display3DFactory< Space, KSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::DigitalSetBySTLSet< Domain, Compare > & anObject) inline static
draw
Parameters
display the display where to draw
anObject the object to draw
Definition at line 395 of file Display3DFactory.ih.
References DGtal::DigitalSetBySTLSet< TDomain, TCompare >::className(), and DGtal::Display3D< Space, KSpace >::getMode().
 {
   ASSERT(Domain::Space::dimension == 3);
   std::string mode = display.getMode( s.className() );
   ASSERT( (mode=="Paving" || mode=="PavingTransp" || mode=="Grid" || mode=="Both" || mode=="") );
   if ( mode == "Paving" || ( mode == "" ) )
     drawAsPaving( display, s );
   else if ( mode == "PavingTransp" )
     drawAsPavingTransparent( display, s );
   else if ( mode == "Grid" )
     drawAsGrid( display, s );
   else if ( ( mode == "Both" ) )
     {
       drawAsPaving( display, s );
       drawAsGrid( display, s );
     }
 }
template<typename Space , typename KSpace > template<typename Domain > void DGtal::Display3DFactory< Space, KSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::DigitalSetBySTLVector< Domain > & anObject) inline static
draw
Parameters
display the display where to draw
anObject the object to draw
Definition at line 484 of file Display3DFactory.ih.
References DGtal::DigitalSetBySTLVector< TDomain >::className(), and DGtal::Display3D< Space, KSpace >::getMode().
 {
   ASSERT(Domain::Space::dimension == 3);
   std::string mode = display.getMode( v.className() );
   ASSERT( (mode=="Paving" || mode=="PavingTransp" || mode=="Grid" || mode=="Both" || mode=="") );
   if ( mode == "Paving" || ( mode == "" ) )
     drawAsPaving( display, v );
   else if ( mode == "PavingTransp" )
     drawAsPavingTransparent( display, v );
   else if ( mode == "Grid" )
     drawAsGrid( display, v );
   else if ( ( mode == "Both" ) )
     {
       drawAsPaving( display, v);
       drawAsGrid( display, v );
     }
 }
template<typename Space , typename KSpace > template<typename SpaceDom > void DGtal::Display3DFactory< Space, KSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::HyperRectDomain< SpaceDom > & anObject) inline static
draw
Parameters
display the display where to draw
anObject the object to draw
Definition at line 773 of file Display3DFactory.ih.
References DGtal::HyperRectDomain< TSpace >::className(), DGtal::Display3D< Space, KSpace >::createNewBallList(), DGtal::Display3D< Space, KSpace >::createNewCubeList(), DGtal::Display3D< Space, KSpace >::createNewLineList(), and DGtal::Display3D< Space, KSpace >::getMode().
 {
   std::string mode = display.getMode( aDomain.className() );
   ASSERT((mode=="" || mode=="Grid" || mode=="Paving"|| mode=="PavingPoints"|| mode=="PavingGrids" ||
           mode=="BoundingBox")||
          ("DGtal::Display3DFactory<Space,KSpace>::draw( Display3DD<Space, KSpace> & display, const DGtal::HyperRectDomain<Space> & aDomain ): Unknown mode "+mode)=="");
   /*
     if ( mode == "BoundingBox" )
     {
     display.createNewLineList(aDomain.className());
     drawAsBoundingBox( display, aDomain );
     }else if( ( mode == "" ) || (mode == "Grid"))
     {
     display.createNewLineList(aDomain.className());
     drawAsGrid( display, aDomain );
     }
     else if ( mode == "Paving" )
     {
     display.createNewCubeList( aDomain.className());
     }
   */
   ASSERT((Space::dimension==3)|| (Space::dimension==2));
   ASSERT((Space::dimension!=3) || (mode=="" || mode=="Grid" || mode=="Paving"|| mode=="PavingPoints"|| mode=="PavingGrids" ||
                                    mode=="BoundingBox")||
          ("DGtal::Display3DFactory<Space,KSpace>::draw( Display3D<Space, KSpace> & display, const DGtal::HyperRectDomain<Space> & aDomain ): Unknown mode "+mode)=="");
   ASSERT((Space::dimension!=2) || (mode=="" || mode=="BoundingBox" || mode=="Grid") ||
          ("DGtal::Display3DFactory<Space,KSpace>::draw( Display3D<Space, KSpace> & display, const DGtal::HyperRectDomain<Space> & aDomain ): Unknown mode "+mode)=="");
   if(Space::dimension == 2)
     {
       if (mode=="")
         mode="BoundingBox";
     }else if ( mode == "BoundingBox" )
     {
       display.createNewLineList(aDomain.className());
       drawAsBoundingBox( display, aDomain );
     }else if(( mode == "" ) || (mode == "Grid"))
     {
       display.createNewLineList(aDomain.className());
       drawAsGrid( display, aDomain );
     } else if ( mode == "Paving" )
     {
       display.createNewCubeList(aDomain.className());
       drawAsPaving( display, aDomain );
     } else if ( mode == "PavingPoints" )
     {
       display.createNewBallList(aDomain.className());
       drawAsPavingBalls( display, aDomain );
     }else if ( mode == "PavingGrids" )
     {
       display.createNewLineList(aDomain.className());
       display.createNewCubeList( aDomain.className());
       drawAsGrid( display, aDomain );
       drawAsPaving( display, aDomain );
     }
 }
template<typename Space , typename KSpace > void DGtal::Display3DFactory< Space, KSpace >::draw (Display3D< Space, KSpace > & display, const typename KSpace::Cell & anObject) inline static
draw
Parameters
display the display where to draw
anObject the object to draw
Definition at line 838 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addBall(), DGtal::Display3D< Space, KSpace >::addCube(), DGtal::Display3D< Space, KSpace >::addCylinder(), DGtal::Display3D< Space, KSpace >::addSurfelPrism(), DGtal::Display3D< Space, KSpace >::createNewCubeList(), DGtal::Display3D< Space, KSpace >::embedK(), DGtal::Display3D< Space, KSpace >::getFillColor(), DGtal::Display3D< Space, KSpace >::getMode(), and DGtal::Display3D< Space, KSpace >::setFillColor().
 {
   ASSERT(Space::dimension == 3);
   DGtal::Color fillColorSave = display.getFillColor();
   std::string mode = display.getMode( k.className() );
   ASSERT((mode=="" || mode=="Highlighted" || mode=="Transparent"|| mode=="Basic"|| mode=="Illustration"||mode=="IllustrationCustomColor")||
          ("DGtal::Display3DFactory<Space,KSpace>::draw( Display3D<Space, KSpace> & display, const DGtal::KhalimskyCell<dim, TInteger> & k ): Unknown mode "+mode)=="");
   // used to display surfels located at a same position.
   double factorVolSurfel=1.0;
   if(mode=="Highlighted")
     {
       factorVolSurfel = 1.1;
       display.setFillColor(DGtal::Color(255, 50, 50, 255));
     }else if(mode=="Transparent")
     {
       display.setFillColor(DGtal::Color(180, 180, 250, 25));
     }else if(mode=="Basic")
     {
       //Code
     }
   DGtal::Z3i::RealPoint rp = display.embedK( k );
   bool xodd = ( NumberTraits<typename KSpace::Integer>::castToInt64_t(k.myCoordinates[ 0 ]) & 1 );
   bool yodd = ( NumberTraits<typename KSpace::Integer>::castToInt64_t(k.myCoordinates[ 1 ]) & 1 );
   bool zodd = ( NumberTraits<typename KSpace::Integer>::castToInt64_t(k.myCoordinates[ 2 ]) & 1 );
   unsigned int spaceDim= (xodd ? 1:0) + (yodd ? 1:0) + (zodd ? 1:0);
   switch (spaceDim) {
   case 0:
     if(mode!=""&& mode!="IllustrationCustomColor")
       {
         display.setFillColor(DGtal::Color(200, 200, 20, 255));
       }
     display.addBall(rp, 0.05);
     break;
   case 1:
     if(mode!=""&& mode!="IllustrationCustomColor")
       {
         display.setFillColor(DGtal::Color(255, 255, 50, 255));
       }
     display.addCylinder(DGtal::Z3i::RealPoint(rp[0]- (xodd? 0.5:0 ), rp[1]- (yodd? 0.5:0 ), rp[2]- (zodd? 0.5:0 )),
                         DGtal::Z3i::RealPoint(rp[0]+ (xodd? 0.5:0 ), rp[1]+ (yodd? 0.5:0 ), rp[2]+ (zodd? 0.5:0 )));
     break;
   case 2:
     if(mode!="" && mode!="IllustrationCustomColor")
       {
         display.setFillColor(DGtal::Color(20, 200, 200, 255));
       }
     display.addSurfelPrism(DGtal::Z3i::RealPoint(rp[0]+(xodd? 0:0.5 ), rp[1]+(yodd? 0:0.5 ), rp[2]+(zodd? 0:0.5 )),
                            ! xodd, !yodd, !zodd, factorVolSurfel,1.0, false, false);
     break;
   case 3:
     if(mode!="" && mode!="IllustrationCustomColor")
       {
         display.setFillColor(DGtal::Color(255, 180, 250, 255));
       }
     if(mode=="Illustration"|| mode=="IllustrationCustomColor")
       {
         display.createNewCubeList("khalimsky cell");
         display.addCube(rp,0.80);
       }else{
       display.createNewCubeList("khalimsky cell");
       display.addCube(rp,0.90);
     }
     break;
   }
   display.setFillColor(fillColorSave);
 }
template<typename Space , typename KSpace > template<typename TDigitalTopology , typename TDigitalSet > void DGtal::Display3DFactory< Space, KSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::Object< TDigitalTopology, TDigitalSet > & anObject) inline static
draw
Parameters
display the display where to draw
anObject the object to draw
Definition at line 1043 of file Display3DFactory.ih.
References DGtal::Object< TDigitalTopology, TDigitalSet >::className(), DGtal::Display3D< Space, KSpace >::getMode(), and DGtal::Object< TDigitalTopology, TDigitalSet >::pointSet().
 {
   std::string mode = display.getMode( o.className() );
   if ( mode == "Basic" || mode == "" )
     draw( display, o.pointSet() );
   else if ( mode == "PavingTransp" )
     {
       drawAsPavingTransparent( display, o.pointSet() );
     }
   else if ( mode == "DrawAdjacencies" )
     {
       draw( display, o.pointSet() );
       drawWithAdjacencies( display, o );
     }
   else
     ASSERT(false && (("DGtal::Display3DFactory<Space,KSpace>::draw( Display3D<Space, KSpace> & display, const DGtal::Object<TDigitalTopology, TDigitalSet> & o ): Unknown mode " + mode) == ""));
 }
template<typename Space , typename KSpace > template<DGtal::Dimension dim, typename TComponent > void DGtal::Display3DFactory< Space, KSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::PointVector< dim, TComponent > & anObject) inline static
draw
Parameters
display the display where to draw
anObject the object to draw
Definition at line 1136 of file Display3DFactory.ih.
References DGtal::PointVector< dim, TEuclideanRing, TContainer >::className(), DGtal::Display3D< Space, KSpace >::getFillColor(), DGtal::Display3D< Space, KSpace >::getMode(), and DGtal::Display3D< Space, KSpace >::setFillColor().
 {
   DGtal::Color fillColorSave = display.getFillColor();
   ASSERT(dim == 3);
   std::string mode = display.getMode( p.className() );
   ASSERT( (mode=="Paving" || mode=="Grid" || mode=="Both" || mode=="PavingWired"|| mode=="") );
   if ( mode == "Paving" || ( mode == "" ) )
     drawAsPaving( display, p );
   else if ( mode == "Grid" )
     drawAsGrid( display, p );
   else if ( ( mode == "Both" ) )
     {
       drawAsPaving( display, p );
       drawAsGrid( display, p );
     }
   else if( mode=="PavingWired")
     {
       drawAsPavingWired( display, p );
     }
   display.setFillColor(fillColorSave);
 }
template<typename Space , typename KSpace > template<DGtal::Dimension dim, typename TComponent > void DGtal::Display3DFactory< Space, KSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::PointVector< dim, TComponent > & p, const DGtal::PointVector< dim, TComponent > & anObject) inline static
draw
Parameters
display the display where to draw
anObject the object to draw
Definition at line 1164 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addLine(), and DGtal::Display3D< Space, KSpace >::embed().
 {
   ASSERT(dim == 3);
   DGtal::Z3i::RealPoint rp = display.embed(p );
   DGtal::Z3i::RealPoint rpa = display.embed(aPoint );
   display.addLine(rpa, DGtal::Z3i::RealPoint( rpa[0] + rp[0], rpa[1] + rp[1], rpa[2] + rp[2]));
 }
template<typename Space , typename KSpace > void DGtal::Display3DFactory< Space, KSpace >::draw (Display3D< Space, KSpace > & display, const typename KSpace::SCell & anObject) inline static
draw
Parameters
display the display where to draw
anObject the object to draw
Definition at line 917 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addBall(), DGtal::Display3D< Space, KSpace >::addCone(), DGtal::Display3D< Space, KSpace >::addCube(), DGtal::Display3D< Space, KSpace >::addSurfelPrism(), DGtal::Display3D< Space, KSpace >::createNewCubeList(), DGtal::Display3D< Space, KSpace >::embedKS(), DGtal::Display3D< Space, KSpace >::getFillColor(), DGtal::Display3D< Space, KSpace >::getMode(), and DGtal::Display3D< Space, KSpace >::setFillColor().
 {
   ASSERT(Space::dimension == 3);
   DGtal::Color fillColorSave = display.getFillColor();
   std::string mode = display.getMode( sk.className() );
   ASSERT((mode=="" || mode=="Highlighted" || mode=="Transparent" || mode=="Basic" || mode=="Illustration" || mode=="IllustrationCustomColor")||
          ("DGtal::Display3DFactory<Space,KSpace>::draw( Display3D<Space, KSpace> & display, const DGtal::SignedKhalimskyCell<dim, TInteger> & sk ): Unknown mode "+mode)=="");
   // used to display surfels located at a same position.
   double factorVolSurfel=1.0;
   if(mode=="Highlighted")
     {
       factorVolSurfel = 1.2;
       display.setFillColor(DGtal::Color(255, 50, 50, 255));
     }else if(mode=="Transparent")
     {
       display.setFillColor(DGtal::Color(180, 180, 250, 25));
     }else if(mode=="Basic")
     {
       //basicMode=true;
     }
   DGtal::Z3i::RealPoint rps = display.embedKS( sk );
   bool xodd = ( sk.myCoordinates[ 0 ] & 1 );
   bool yodd = ( sk.myCoordinates[ 1 ] & 1 );
   bool zodd = ( sk.myCoordinates[ 2 ] & 1 );
   unsigned int spaceDim= (xodd ? 1:0) + (yodd ? 1:0) + (zodd ? 1:0);
   // pointel
   switch (spaceDim)
     {
     case 0:
       if(mode!="" && mode!="IllustrationCustomColor")
         {
           if( sk.myPositive)
             display.setFillColor(DGtal::Color(20, 20, 250, 255));
           else
             display.setFillColor(DGtal::Color(20, 20, 150, 255));
         }
       display.addBall(rps, 0.05);
       break;
     case 1:
       if(mode!="" && mode!="IllustrationCustomColor")
         {
           display.setFillColor(  DGtal::Color(255, 50, 50, 255));
         }
       if (sk.myPositive)
         {
           display.addCone(DGtal::Z3i::RealPoint(rps[0]- (xodd? 0.5:0 ), rps[1]- (yodd? 0.5:0 ), rps[2]- (zodd? 0.5:0 )),
                           DGtal::Z3i::RealPoint(rps[0]+ (xodd? 0.5:0 ), rps[1]+ (yodd? 0.5:0 ), rps[2]+ (zodd? 0.5:0 )));
         }
       else
         {
           display.addCone(DGtal::Z3i::RealPoint(rps[0]+ (xodd? 0.5:0 ), rps[1]+ (yodd? 0.5:0 ), rps[2]+ (zodd? 0.5:0 )),
                           DGtal::Z3i::RealPoint(rps[0]- (xodd? 0.5:0 ),rps[1]- (yodd? 0.5:0 ), rps[2]- (zodd? 0.5:0 )));
         }
       break;
     case 2:
       display.addSurfelPrism(DGtal::Z3i::RealPoint(rps[0]+(xodd? 0:0.5 ), rps[1]+(yodd? 0:0.5 ), rps[2]+(zodd? 0:0.5 )),
                              ! xodd, !yodd, !zodd, factorVolSurfel,1.0, true, sk.myPositive );
       break;
     case 3:
       if(mode!="" && mode!="IllustrationCustomColor")
         {
           if( sk.myPositive)
             {
               display.setFillColor(DGtal::Color(200, 20, 20, 255));
             }else
             {
               display.setFillColor(DGtal::Color(20, 200, 20, 255));
             }
         }
       if(mode=="Illustration"|| mode=="IllustrationCustomColor")
         {
           //KSCube
           display.createNewCubeList("signed khalimsky cell");
           display.addCube(rps, 0.80);
         }else
         {
           display.createNewCubeList("signed khalimsky cell");
           display.addCube(rps, 0.90 );
         }
       break;
     }
   display.setFillColor(fillColorSave);
 }
template<typename Space , typename KSpace > void DGtal::Display3DFactory< Space, KSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::GridCurve< KSpace > & anObject) inline static
draw
Parameters
display the display where to draw
anObject the object to draw
Definition at line 1180 of file Display3DFactory.ih.
References DGtal::GridCurve< TKSpace >::getSCellsRange().
 {
   typedef typename DGtal::GridCurve<KSpace>::SCellsRange Range;
   Range r = gc.getSCellsRange();
   for ( typename Range::ConstIterator it = r.begin(), itEnd = r.end();
         it != itEnd; ++it )
     {
       draw( display, *it );
     }
 }
template<typename Space , typename KSpace > template<typename TIterator, typename TSCell > void DGtal::Display3DFactory< Space, KSpace >::draw (DGtal::Display3D< Space, KSpace > & display, const DGtal::ConstRangeAdapter< TIterator, DGtal::DefaultFunctor, TSCell > & anObject) inline static
draw
Parameters
display the display where to draw
anObject the object to draw
Definition at line 1197 of file Display3DFactory.ih.
 {
   typedef DGtal::ConstRangeAdapter<TIterator, DGtal::DefaultFunctor, TSCell> Range;
   typedef typename Range::ConstIterator ConstIterator;
   ConstIterator it ( object.begin() );
   ConstIterator itEnd ( object.end() );
   for( ; it != itEnd; ++it)
     {
       draw( display, *it);
     }
 }
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator > static void DGtal::Display3DFactory< TSpace, TKSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::ConstRangeAdapter< TIterator, SCellToPoint< KSpace >, typename TKSpace::Point > & anObject) static
draw
Parameters
display the display where to draw
anObject the object to draw
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator > static void DGtal::Display3DFactory< TSpace, TKSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::ConstRangeAdapter< TIterator, CanonicSCellEmbedder< KSpace >, typename TKSpace::Space::RealPoint > & anObject) static
draw
Parameters
display the display where to draw
anObject the object to draw
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator > static void DGtal::Display3DFactory< TSpace, TKSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::ConstRangeAdapter< TIterator, SCellToArrow< KSpace >, std::pair< typename TKSpace::Point, typename TKSpace::Vector > > & anObject) static
draw
Parameters
display the display where to draw
anObject the object to draw
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator > static void DGtal::Display3DFactory< TSpace, TKSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::ConstRangeAdapter< TIterator, SCellToInnerPoint< KSpace >, typename TKSpace::Point > & anObject) static
draw
Parameters
display the display where to draw
anObject the object to draw
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator > static void DGtal::Display3DFactory< TSpace, TKSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::ConstRangeAdapter< TIterator, SCellToOuterPoint< KSpace >, typename TKSpace::Point > & anObject) static
draw
Parameters
display the display where to draw
anObject the object to draw
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator > static void DGtal::Display3DFactory< TSpace, TKSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::ConstRangeAdapter< TIterator, SCellToIncidentPoints< KSpace >, std::pair< typename TKSpace::Point, typename TKSpace::Point > > & anObject) static
draw
Parameters
display the display where to draw
anObject the object to draw
template<typename Space , typename KSpace > void DGtal::Display3DFactory< Space, KSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::SetMode3D & anObject) inline static
draw
Parameters
display the display where to draw
anObject the object to draw
Definition at line 1347 of file Display3DFactory.ih.
References DGtal::SetMode3D::myClassname, DGtal::SetMode3D::myMode, and DGtal::Display3D< Space, KSpace >::myModes.
 {
   display.myModes[ sm3d.myClassname ] = sm3d.myMode;
 }
template<typename Space , typename KSpace > void DGtal::Display3DFactory< Space, KSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::CustomStyle3D & anObject) inline static
draw
Parameters
display the display where to draw
anObject the object to draw
Definition at line 1355 of file Display3DFactory.ih.
References DGtal::CustomStyle3D::myClassname, DGtal::CustomStyle3D::myStyle, and DGtal::Display3D< Space, KSpace >::myStyles.
 {
   display.myStyles[ cs3d.myClassname ] = cs3d.myStyle;
 }
template<typename Space , typename KSpace > void DGtal::Display3DFactory< Space, KSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::CustomColors3D & anObject) inline static
draw
Parameters
display the display where to draw
anObject the object to draw
Definition at line 1363 of file Display3DFactory.ih.
References DGtal::CustomColors3D::myFillColor, DGtal::CustomColors3D::myPenColor, DGtal::Display3D< Space, KSpace >::setFillColor(), and DGtal::Display3D< Space, KSpace >::setLineColor().
 {
   display.setFillColor(cc3d.myFillColor);
   display.setLineColor(cc3d.myPenColor);
 }
template<typename Space , typename KSpace > void DGtal::Display3DFactory< Space, KSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::ClippingPlane & anObject) inline static
draw
Parameters
display the display where to draw
anObject the object to draw
Definition at line 1371 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addClippingPlane(), DGtal::ClippingPlane::myA, DGtal::ClippingPlane::myB, DGtal::ClippingPlane::myC, DGtal::ClippingPlane::myD, DGtal::ClippingPlane::myDrawPlane, and DGtal::Display3D< Space, KSpace >::setFillColor().
 {
   display.setFillColor(DGtal::Color(205,0,0, 30));
   display.addClippingPlane(cl.myA, cl.myB, cl.myC, cl.myD, cl.myDrawPlane);
 }
template<typename Space , typename KSpace > void DGtal::Display3DFactory< Space, KSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::TransformedSurfelPrism & aTransformedSurfelPrism) inline static
Draw a surfel
Parameters
display the display where to draw
aTransformedSurfelPrism a transformed surfel prism
Definition at line 1380 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addSurfelPrism(), DGtal::Display3D< Space, KSpace >::embedKS(), DGtal::Display3D< Space, KSpace >::getFillColor(), DGtal::Display3D< Space, KSpace >::getMode(), DGtal::TransformedSurfelPrism::mySurfel, and DGtal::Display3D< Space, KSpace >::setFillColor().
 {
   DGtal::Color fillColorSave = display.getFillColor();
   std::string mode = display.getMode( aTransformedSurfelPrism.mySurfel.className() );
   ASSERT((mode=="" || mode=="Highlighted" || mode=="Transparent" || mode=="Basic" || mode=="Illustration")||
          ("DGtal::Display3DFactory<Space,KSpace>::draw( Display3D<Space, KSpace> & display, const DGtal::ShiftedKSSurfel & aTransformedSurfelPrism ): Unknown mode "+mode)=="");
   // used to display surfels located at a same position.
   double factorVolSurfel=1.0;
   if(mode=="Highlighted")
     {
       factorVolSurfel = 1.2;
       display.setFillColor(DGtal::Color(255, 50, 50, 255));
     }else if(mode=="Transparent")
     {
       display.setFillColor(DGtal::Color(180, 180, 250, 25));
     }else if(mode=="Basic")
     {
       // basicMode=true;
     }
   DGtal::Z3i::RealPoint rps = display.embedKS(aTransformedSurfelPrism );
   bool xodd = ( aTransformedSurfelPrism.mySurfel.myCoordinates[ 0 ] & 1 );
   bool yodd = ( aTransformedSurfelPrism.mySurfel.myCoordinates[ 1 ] & 1 );
   bool zodd = ( aTransformedSurfelPrism.mySurfel.myCoordinates[ 2 ] & 1 );
   unsigned int spaceDim= (xodd ? 1:0) + (yodd ? 1:0) + (zodd ? 1:0);
   ASSERT(spaceDim==2);
   //display.addSurfelPrism(rps[0], rps[1], rps[2],! xodd, !yodd, !zodd, factorVolSurfel, aTransformedSurfelPrism.mySizeFactor, true, aTransformedSurfelPrism.mySurfel.myPositive );
   display.addSurfelPrism(DGtal::Z3i::RealPoint(rps[0]+(xodd? 0:0.5 ), rps[1]+(yodd? 0:0.5 ), rps[2]+(zodd? 0:0.5 )),! xodd, !yodd, !zodd, factorVolSurfel,1.0, true, aTransformedSurfelPrism.mySurfel.myPositive );
   display.setFillColor(fillColorSave);
 }
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator> void DGtal::Display3DFactory< TSpace, TKSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::ConstRangeAdapter< TIterator, SCellToPoint< KSpace >, typename KSpace::Point > & object) inline
Definition at line 1216 of file Display3DFactory.ih.
 {
   typedef ConstRangeAdapter<TIterator, SCellToPoint<KSpace>, typename KSpace::Point> Range;
   typedef typename Range::ConstIterator ConstIterator;
   ConstIterator it ( object.begin() );
   ConstIterator itEnd ( object.end() );
   for( ; it != itEnd; ++it)
     {
       display << SetMode3D(it->className(),"Paving");
       display << *it;
     }
 }
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator> void DGtal::Display3DFactory< TSpace, TKSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::ConstRangeAdapter< TIterator, CanonicSCellEmbedder< KSpace >, typename KSpace::Space::RealPoint > & object) inline
Definition at line 1236 of file Display3DFactory.ih.
 {
   typedef typename KSpace::Space::RealPoint RPoint;
   typedef ConstRangeAdapter<TIterator, CanonicSCellEmbedder<KSpace>, RPoint > Range;
   typedef typename Range::ConstIterator ConstIterator;
   ConstIterator it ( object.begin() );
   ConstIterator itEnd ( object.end() );
   for( ; it != itEnd; ++it)
     {
       display << SetMode3D(it->className(),"Grid");
       display << *it;
     }
 }
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator> void DGtal::Display3DFactory< TSpace, TKSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::ConstRangeAdapter< TIterator, SCellToArrow< KSpace >, std::pair< typename KSpace::Point, typename KSpace::Vector > > & object) inline
Definition at line 1258 of file Display3DFactory.ih.
 {
   typedef typename KSpace::Point Point;
   typedef typename KSpace::Vector Vector;
   typedef std::pair<Point, Vector> Arrow;
   typedef ConstRangeAdapter<TIterator, SCellToArrow<KSpace>, Arrow > Range;
   typedef typename Range::ConstIterator ConstIterator;
   ConstIterator it ( object.begin() );
   ConstIterator itEnd ( object.end() );
   for( ; it != itEnd; ++it)
     { //display the associated cell
       draw( display, *(it.base()) );
     }
 }
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator> void DGtal::Display3DFactory< TSpace, TKSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::ConstRangeAdapter< TIterator, SCellToInnerPoint< KSpace >, typename KSpace::Point > & object) inline
Definition at line 1281 of file Display3DFactory.ih.
 {
   typedef ConstRangeAdapter<TIterator, SCellToInnerPoint<KSpace>, typename KSpace::Point> Range;
   typedef typename Range::ConstIterator ConstIterator;
   ConstIterator it ( object.begin() );
   ConstIterator itEnd ( object.end() );
   for( ; it != itEnd; ++it)
     {
       display << SetMode3D(it->className(),"Paving");
       display << CustomColors3D(Color(0, 0, 255,0),Color(0, 0, 200, 100));
       display << *it;
     }
 }
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator> void DGtal::Display3DFactory< TSpace, TKSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::ConstRangeAdapter< TIterator, SCellToOuterPoint< KSpace >, typename KSpace::Point > & object) inline
Definition at line 1302 of file Display3DFactory.ih.
 {
   typedef ConstRangeAdapter<TIterator, SCellToOuterPoint<KSpace>, typename KSpace::Point> Range;
   typedef typename Range::ConstIterator ConstIterator;
   ConstIterator it ( object.begin() );
   ConstIterator itEnd ( object.end() );
   for( ; it != itEnd; ++it)
     {
       display << SetMode3D(it->className(),"Paving");
       display << CustomColors3D(Color(0, 255, 0 ,0),Color(0, 200, 0, 100));
       display << *it;
     }
 }
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator> void DGtal::Display3DFactory< TSpace, TKSpace >::draw (Display3D< Space, KSpace > & display, const DGtal::ConstRangeAdapter< TIterator, SCellToIncidentPoints< KSpace >, std::pair< typename KSpace::Point, typename KSpace::Point > > & object) inline
Definition at line 1323 of file Display3DFactory.ih.
 {
   typedef std::pair<typename KSpace::Point, typename KSpace::Point > Pair;
   typedef ConstRangeAdapter<TIterator, SCellToIncidentPoints<KSpace>, Pair> Range;
   typedef typename Range::ConstIterator ConstIterator;
   ConstIterator it ( object.begin() );
   ConstIterator itEnd ( object.end() );
   for( ; it != itEnd; ++it)
     {
       Pair pair( *it );
       display << SetMode3D(pair.first.className(),"Paving");
       display << CustomColors3D(Color(0, 0, 255,0),Color(0, 0, 200, 100));
       display << pair.first;
       display << CustomColors3D(Color(0, 255, 0 ,0),Color(0, 200, 0, 100));
       display << pair.second;
     }
 }
template<typename Space , typename KSpace > template<typename TIterator , typename TInteger , int connectivity> void DGtal::Display3DFactory< Space, KSpace >::drawAsBalls (Display3D< Space, KSpace > & display, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > & anObject) inline static
drawAsBalls
Parameters
display the display where to draw
anObject the object to draw
Definition at line 161 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addLine(), DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity >::begin(), DGtal::Display3D< Space, KSpace >::embed(), DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity >::end(), DGtal::Display3D< Space, KSpace >::getFillColor(), DGtal::Display3D< Space, KSpace >::getLineColor(), and DGtal::Display3D< Space, KSpace >::getMode().
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::drawAsBalls(), and DGtal::Board3DTo2DFactory< TSpace, TKSpace >::drawAsBalls().
 {
   typedef TIterator ConstIterator;
   typedef typename IteratorCirculatorTraits<ConstIterator>::Value Point3d;
   // Draw points
   display << CustomColors3D( display.getLineColor(), display.getFillColor() );
   for (ConstIterator i = a.begin(); i != a.end(); ++i)
     {
       display << *i;
     }
   // Draw a linking polygonal line if the voxels are drawn as points.
   if(display.getMode("PointVector")=="Grid")
     {
       ConstIterator k = a.begin();
       Point3d prevp = *k;
       DGtal::Z3i::RealPoint rprevp = display.embed( prevp);
       ++k;
       for ( ; k != a.end(); ++k) {
         Point3d p = *k;
         DGtal::Z3i::RealPoint rp = display.embed( p );
         display.addLine(rprevp,rp);
         rprevp = rp;
       }
     }
 }
template<typename Space , typename KSpace > template<typename TIterator , typename TInteger , int connectivity> void DGtal::Display3DFactory< Space, KSpace >::drawAsBoundingBox (Display3D< Space, KSpace > & display, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > & anObject) inline static
drawAsBoundingBox
Parameters
display the display where to draw
anObject the object to draw
Definition at line 195 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addLine(), DGtal::Display3D< Space, KSpace >::addQuad(), DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity >::begin(), DGtal::Display3D< Space, KSpace >::embed(), DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity >::end(), and DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity >::getParameters().
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::drawAsBoundingBox(), and DGtal::Board3DTo2DFactory< TSpace, TKSpace >::drawAsBoundingBox().
 {
   typedef TIterator ConstIterator;
   typedef typename IteratorCirculatorTraits<ConstIterator>::Value Point3d;
   typedef DGtal::PointVector<3,double> PointD3d;
   typedef typename IteratorCirculatorTraits<ConstIterator>::Value Vector3d;
   typedef DGtal::PointVector<3,double> VectorD3d;
   typedef TInteger Integer;
   //get DSS parameters
   Vector3d v; //direction vector
   PointD3d mu; //intercept
   PointD3d omega; //thickness
   a.getParameters(v,mu,omega);
   //casting coordinates of v in double
   VectorD3d u = VectorD3d(NumberTraits<Integer>::castToDouble(v[0]),
                           NumberTraits<Integer>::castToDouble(v[1]),
                           NumberTraits<Integer>::castToDouble(v[2]) );
   //L2 norm of u
   double n = u[0]*u[0] + u[1]*u[1] + u[2]*u[2];
   //first and last points
   Point3d first = *a.begin();
   Point3d last = *(--a.end());
   PointD3d f = PointD3d(NumberTraits<Integer>::castToDouble(first[0]),
                         NumberTraits<Integer>::castToDouble(first[1]),
                         NumberTraits<Integer>::castToDouble(first[2]) );
   PointD3d l = PointD3d(NumberTraits<Integer>::castToDouble(last[0]),
                         NumberTraits<Integer>::castToDouble(last[1]),
                         NumberTraits<Integer>::castToDouble(last[2]) );
   if (n != 0) {
     //last coefficient of the normal plane to the DSS direction
     //passing trough f and l
     double df = -u[0]*f[0] -u[1]*f[1] -u[2]*f[2];
     double dl = -u[0]*l[0] -u[1]*l[1] -u[2]*l[2];
     //omega masks
     PointD3d omega1, omega2;
     if (omega[0] == 0) {
       omega1 = PointD3d(0,omega[1],0);
       omega2 = PointD3d(0,0,omega[2]);
     } else {
       if (omega[1] == 0) {
         omega1 = PointD3d(omega[0],0,0);
         omega2 = PointD3d(0,0,omega[2]);
       } else {//omega[2] == 0
         omega1 = PointD3d(omega[0],0,0);
         omega2 = PointD3d(0,omega[1],0);
       }
     }
     double m1 = u[0]*mu[0] + u[1]*mu[1] + u[2]*mu[2];
     double m2 = u[0]*(mu[0]+omega1[0]) + u[1]*(mu[1]+omega1[1]) + u[2]*(mu[2]+omega1[2]);
     double m3 = u[0]*(mu[0]+omega2[0]) + u[1]*(mu[1]+omega2[1]) + u[2]*(mu[2]+omega2[2]);
     double m4 = u[0]*(mu[0]+omega[0]) + u[1]*(mu[1]+omega[1]) + u[2]*(mu[2]+omega[2]);
     //4 lines
     PointD3d pf = PointD3d( mu[0] - ( (m1+df)*u[0] )/n,
                             mu[1] - ( (m1+df)*u[1] )/n,
                             mu[2] - ( (m1+df)*u[2] )/n );
     DGtal::Z3i::RealPoint rpf = display.embed( pf );
     PointD3d pl = PointD3d( mu[0] - ( (m1+dl)*u[0] )/n,
                             mu[1] - ( (m1+dl)*u[1] )/n,
                             mu[2] - ( (m1+dl)*u[2] )/n );
     DGtal::Z3i::RealPoint rpl = display.embed( pl );
     display.addLine(rpf, rpl);
     PointD3d pf2 = PointD3d((mu[0]+omega1[0]) - ( (m2+df)*u[0] )/n,
                             (mu[1]+omega1[1]) - ( (m2+df)*u[1] )/n,
                             (mu[2]+omega1[2]) - ( (m2+df)*u[2] )/n );
     DGtal::Z3i::RealPoint rpf2 = display.embed( pf2 );
     PointD3d pl2 = PointD3d((mu[0]+omega1[0]) - ( (m2+dl)*u[0] )/n,
                             (mu[1]+omega1[1]) - ( (m2+dl)*u[1] )/n,
                             (mu[2]+omega1[2]) - ( (m2+dl)*u[2] )/n );
     DGtal::Z3i::RealPoint rpl2 = display.embed( pl2 );
     display.addLine(rpf2, rpl2);
     PointD3d pf3 = PointD3d((mu[0]+omega2[0]) - ( (m3+df)*u[0] )/n,
                             (mu[1]+omega2[1]) - ( (m3+df)*u[1] )/n,
                             (mu[2]+omega2[2]) - ( (m3+df)*u[2] )/n );
     DGtal::Z3i::RealPoint rpf3 = display.embed( pf3 );
     PointD3d pl3 = PointD3d((mu[0]+omega2[0]) - ( (m3+dl)*u[0] )/n,
                             (mu[1]+omega2[1]) - ( (m3+dl)*u[1] )/n,
                             (mu[2]+omega2[2]) - ( (m3+dl)*u[2] )/n );
     DGtal::Z3i::RealPoint rpl3 = display.embed( pl3 );
     display.addLine(rpf3, rpl3);
     PointD3d pf4 = PointD3d((mu[0]+omega[0]) - ( (m4+df)*u[0] )/n,
                             (mu[1]+omega[1]) - ( (m4+df)*u[1] )/n,
                             (mu[2]+omega[2]) - ( (m4+df)*u[2] )/n );
     DGtal::Z3i::RealPoint rpf4 = display.embed( pf4 );
     PointD3d pl4 = PointD3d((mu[0]+omega[0]) - ( (m4+dl)*u[0] )/n,
                             (mu[1]+omega[1]) - ( (m4+dl)*u[1] )/n,
                             (mu[2]+omega[2]) - ( (m4+dl)*u[2] )/n );
     DGtal::Z3i::RealPoint rpl4 = display.embed( pl4 );
     display.addLine(rpf4, rpl4);
     //two end facets
     display.addQuad(rpf,rpf2,rpf4, rpf3);
     display.addQuad(rpl, rpl2, rpl4,rpl3);
   }
 }
template<typename Space , typename KSpace > template<typename SpaceDom > void DGtal::Display3DFactory< Space, KSpace >::drawAsBoundingBox (Display3D< Space, KSpace > & display, const DGtal::HyperRectDomain< SpaceDom > & anObject) inline static
drawAsBoundingBox
Parameters
display the display where to draw
anObject the object to draw
Definition at line 511 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addQuad(), DGtal::Display3D< Space, KSpace >::embed(), DGtal::Display3D< Space, KSpace >::getFillColor(), DGtal::HyperRectDomain< TSpace >::myLowerBound, DGtal::HyperRectDomain< TSpace >::myUpperBound, and DGtal::Display3D< Space, KSpace >::setFillColor().
 {
   DGtal::Color fillColorSave = display.getFillColor();
   ASSERT(Space::dimension == 2 || Space::dimension == 3 || "drawAsBoundingBox-NOT-YET-IMPLEMENTED-in-ND");
   DGtal::Z3i::RealPoint upperBound;
   DGtal::Z3i::RealPoint lowerBound;
   if (SpaceDom::dimension == 3)
     {
       upperBound = display.embed( DGtal::Z3i::Point(h.myUpperBound[0], h.myUpperBound[1], h.myUpperBound[2]));
       lowerBound = display.embed( DGtal::Z3i::Point(h.myLowerBound[0], h.myLowerBound[1], h.myLowerBound[2]));
     }
   if (SpaceDom::dimension == 2)
     {
       upperBound = display.embed( DGtal::Z3i::Point(h.myUpperBound[0], h.myUpperBound[1], 0));
       lowerBound = display.embed( DGtal::Z3i::Point(h.myLowerBound[0], h.myLowerBound[1], 0));
     }
   display.setFillColor(DGtal::Color(250,250,250,10));
   double shiftSize=0.01;
   if (SpaceDom::dimension == 3)
     {
       //Z upper face
       display.addQuad(DGtal::Z3i::RealPoint(upperBound[0]+(0.5+shiftSize),
                                             upperBound[1]+(0.5+shiftSize),
                                             upperBound[2]+(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(lowerBound[0]-(0.5+shiftSize),
                                             upperBound[1]+(0.5+shiftSize),
                                             upperBound[2]+(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(lowerBound[0]-(0.5+shiftSize),
                                             lowerBound[1]-(0.5+shiftSize),
                                             upperBound[2]+(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(upperBound[0]+(0.5+shiftSize),
                                             lowerBound[1]-(0.5+shiftSize),
                                             upperBound[2]+(0.5+shiftSize)));
       //Z lower face
       display.addQuad(DGtal::Z3i::RealPoint(upperBound[0]+(0.5+shiftSize),
                                             upperBound[1]+(0.5+shiftSize),
                                             lowerBound[2]-(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(upperBound[0]+(0.5+shiftSize),
                                             lowerBound[1]-(0.5+shiftSize),
                                             lowerBound[2]-(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(lowerBound[0]-(0.5+shiftSize),
                                             lowerBound[1]-(0.5+shiftSize),
                                             lowerBound[2]-(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(lowerBound[0]-(0.5+shiftSize),
                                             upperBound[1]+(0.5+shiftSize),
                                             lowerBound[2]-(0.5+shiftSize)));
       //Y upper face
       display.addQuad(DGtal::Z3i::RealPoint(upperBound[0]+(0.5+shiftSize),
                                             upperBound[1]+(0.5+shiftSize),
                                             upperBound[2]+(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(upperBound[0]+(0.5+shiftSize),
                                             upperBound[1]+(0.5+shiftSize),
                                             lowerBound[2]-(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(lowerBound[0]-(0.5+shiftSize),
                                             upperBound[1]+(0.5+shiftSize),
                                             lowerBound[2]-(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(lowerBound[0]-(0.5+shiftSize),
                                             upperBound[1]+(0.5+shiftSize),
                                             upperBound[2]+(0.5+shiftSize)));
       //Y lower face
       display.addQuad(DGtal::Z3i::RealPoint(upperBound[0]+(0.5+shiftSize),
                                             lowerBound[1]-(0.5+shiftSize),
                                             upperBound[2]+(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(lowerBound[0]-(0.5+shiftSize),
                                             lowerBound[1]-(0.5+shiftSize),
                                             upperBound[2]+(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(lowerBound[0]-(0.5+shiftSize),
                                             lowerBound[1]-(0.5+shiftSize),
                                             lowerBound[2]-(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(upperBound[0]+(0.5+shiftSize),
                                             lowerBound[1]-(0.5+shiftSize),
                                             lowerBound[2]-(0.5+shiftSize)));
       // X upper face
       display.addQuad(DGtal::Z3i::RealPoint(upperBound[0]+(0.5+shiftSize),
                                             upperBound[1]+(0.5+shiftSize),
                                             upperBound[2]+(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(upperBound[0]+(0.5+shiftSize),
                                             lowerBound[1]-(0.5+shiftSize),
                                             upperBound[2]+(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(upperBound[0]+(0.5+shiftSize),
                                             lowerBound[1]-(0.5+shiftSize),
                                             lowerBound[2]-(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(upperBound[0]+(0.5+shiftSize),
                                             upperBound[1]+(0.5+shiftSize),
                                             lowerBound[2]-(0.5+shiftSize)));
       // X lower face
       display.addQuad(DGtal::Z3i::RealPoint(lowerBound[0]-(0.5+shiftSize),
                                             upperBound[1]+(0.5+shiftSize),
                                             upperBound[2]+(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(lowerBound[0]-(0.5+shiftSize),
                                             upperBound[1]+(0.5+shiftSize),
                                             lowerBound[2]-(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(lowerBound[0]-(0.5+shiftSize),
                                             lowerBound[1]-(0.5+shiftSize),
                                             lowerBound[2]-(0.5+shiftSize)),
                       DGtal::Z3i::RealPoint(lowerBound[0]-(0.5+shiftSize),
                                             lowerBound[1]-(0.5+shiftSize),
                                             upperBound[2]+(0.5+shiftSize)));
     }
   display.setFillColor( fillColorSave);
 }
template<typename Space , typename KSpace > template<typename TPoint > void DGtal::Display3DFactory< Space, KSpace >::drawAsFaces (Display3D< Space, KSpace > & display, const DGtal::Mesh< TPoint > & aMesh) inline static
drawAsFaces
Parameters
display the display where to draw
aMesh the mesh to draw
Definition at line 110 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addPolygon(), DGtal::Display3D< Space, KSpace >::addQuad(), DGtal::Display3D< Space, KSpace >::addTriangle(), DGtal::Mesh< TPoint >::className(), DGtal::Display3D< Space, KSpace >::createNewQuadList(), DGtal::Mesh< TPoint >::getFace(), DGtal::Mesh< TPoint >::getFaceColor(), DGtal::Display3D< Space, KSpace >::getFillColor(), DGtal::Mesh< TPoint >::getVertex(), DGtal::Mesh< TPoint >::isStoringFaceColors(), DGtal::Mesh< TPoint >::nbFaces(), DGtal::Display3D< Space, KSpace >::setFillColor(), DGtal::trace, and DGtal::Trace::warning().
Referenced by DGtal::Board3DTo2DFactory< TSpace, TKSpace >::drawAsFaces(), and DGtal::Viewer3DFactory< TSpace, TKSpace >::drawAsFaces().
 {
   DGtal::Color fillColorSave = display.getFillColor();
   bool useGlobalColor =  !aMesh.isStoringFaceColors();
   display.createNewQuadList(aMesh.className());
   for(unsigned int i=0; i< aMesh.nbFaces(); i++)
     {
       typename Mesh<TPoint>::MeshFace aFace = aMesh.getFace(i);
       unsigned int aNum = aFace.size();
       if(!useGlobalColor){
         display.setFillColor(aMesh.getFaceColor(i));
       }
       if(aNum==4)
         {
           TPoint p1 = aMesh.getVertex(aFace.at(0));
           TPoint p2 = aMesh.getVertex(aFace.at(1));
           TPoint p3 = aMesh.getVertex(aFace.at(2));
           TPoint p4 = aMesh.getVertex(aFace.at(3));
           display.addQuad(p1, p2, p3, p4);
         }else if(aNum==3)
         {
           TPoint p1 = aMesh.getVertex(aFace.at(0));
           TPoint p2 = aMesh.getVertex(aFace.at(1));
           TPoint p3 = aMesh.getVertex(aFace.at(2));
           display.addTriangle(p1, p2,p3);
         }else if(aNum>4)
         {
           std::vector<typename Display3D<Space, KSpace>::RealPoint> vectPoly;
           for(unsigned int j=0; j< aFace.size(); j++)
             {
               typename Display3D<Space, KSpace>::RealPoint point(aMesh.getVertex(aFace.at(j)));
               vectPoly.push_back(point);
             }
           display.addPolygon(vectPoly);
         }else
         {
           trace.warning()<< "Face not valid, only "<< aNum << "vertex... "<< std::endl;
         }
     }
   display.setFillColor(fillColorSave);
 }
template<typename Space , typename KSpace > template<typename Domain , typename Compare > void DGtal::Display3DFactory< Space, KSpace >::drawAsGrid (Display3D< Space, KSpace > & display, const DGtal::DigitalSetBySTLSet< Domain, Compare > & anObject) inline static
drawAsGrid
Parameters
display the display where to draw
anObject the object to draw
Definition at line 375 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addBall(), DGtal::DigitalSetBySTLSet< TDomain, TCompare >::begin(), DGtal::Display3D< Space, KSpace >::embed(), and DGtal::DigitalSetBySTLSet< TDomain, TCompare >::end().
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::drawAsGrid(), and DGtal::Board3DTo2DFactory< TSpace, TKSpace >::drawAsGrid().
 {
   typedef typename Domain::Point Point;
   typedef typename std::set<Point>::const_iterator ConstIterator;
   ASSERT(Domain::Space::dimension == 3);
   for ( ConstIterator it = s.begin();
         it != s.end();
         ++it )
     {
       DGtal::Z3i::RealPoint rp = display.embed((*it) );
       display.addBall(rp);
     }
 }
template<typename Space , typename KSpace > template<typename Domain > void DGtal::Display3DFactory< Space, KSpace >::drawAsGrid (Display3D< Space, KSpace > & display, const DGtal::DigitalSetBySTLVector< Domain > & anObject) inline static
drawAsGrid
Parameters
display the display where to draw
anObject the object to draw
Definition at line 464 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addBall(), DGtal::DigitalSetBySTLVector< TDomain >::begin(), DGtal::Display3D< Space, KSpace >::embed(), and DGtal::DigitalSetBySTLVector< TDomain >::end().
 {
   typedef typename Domain::Point Point;
   typedef typename std::vector<Point>::const_iterator ConstIterator;
   ASSERT(Domain::Space::dimension == 3);
   for ( ConstIterator it = v.begin();
         it != v.end();
         ++it )
     {
       DGtal::Z3i::RealPoint rp = display.embed((*it) );
       display.addBall(rp);
     }
 }
template<typename Space , typename KSpace > template<typename SpaceDom > void DGtal::Display3DFactory< Space, KSpace >::drawAsGrid (Display3D< Space, KSpace > & display, const DGtal::HyperRectDomain< SpaceDom > & anObject) inline static
drawAsGrid
Parameters
display the display where to draw
anObject the object to draw
Definition at line 621 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addLine(), DGtal::Display3D< Space, KSpace >::embed(), DGtal::HyperRectDomain< TSpace >::myLowerBound, and DGtal::HyperRectDomain< TSpace >::myUpperBound.
 {
   typedef typename Space::Integer Integer;
   ASSERT(Space::dimension == 3 || "drawAsGrid-NOT-YET-IMPLEMENTED-in-ND");
   if (Space::dimension == 3)
     {
       // Face XY
       for (int64_t z = NumberTraits<Integer>::castToInt64_t(h.myLowerBound[2]);
            z <= NumberTraits<Integer>::castToInt64_t(h.myUpperBound[2]); z++)
         {
           for (int64_t x = NumberTraits<Integer>::castToInt64_t(h.myLowerBound[0]);
                x <= NumberTraits<Integer>::castToInt64_t(h.myUpperBound[0]); x++)
             {
               DGtal::Z3i::RealPoint rp1 = display.embed( DGtal::Z3i::Point(x, h.myLowerBound[1], z) );
               DGtal::Z3i::RealPoint rp2 = display.embed( DGtal::Z3i::Point(x, h.myUpperBound[1], z) );
               display.addLine( rp1, rp2);
             }
           for (int64_t y = NumberTraits<Integer>::castToInt64_t(h.myLowerBound[1]);
                y <= NumberTraits<Integer>::castToInt64_t(h.myUpperBound[1]); y++)
             {
               DGtal::Z3i::RealPoint rp1 = display.embed( DGtal::Z3i::Point(h.myLowerBound[0], y, z) );
               DGtal::Z3i::RealPoint rp2 = display.embed( DGtal::Z3i::Point(h.myUpperBound[0], y, z) );
               display.addLine( rp1, rp2 );
             }
         }
       // Faces XZ
       for (int64_t y = NumberTraits<Integer>::castToInt64_t(h.myLowerBound[1]);
            y <= NumberTraits<Integer>::castToInt64_t(h.myUpperBound[1]); y++)
         {
           for (int64_t x = NumberTraits<Integer>::castToInt64_t(h.myLowerBound[0]);
                x <= NumberTraits<Integer>::castToInt64_t(h.myUpperBound[0]); x++)
             {
               DGtal::Z3i::RealPoint rp1 = display.embed( DGtal::Z3i::Point(x, y, h.myLowerBound[2]) );
               DGtal::Z3i::RealPoint rp2 = display.embed( DGtal::Z3i::Point(x, y, h.myLowerBound[2]) );
               display.addLine( rp1, rp2);
             }
           for (int64_t z = NumberTraits<Integer>::castToInt64_t(h.myLowerBound[2]);
                z <= NumberTraits<Integer>::castToInt64_t(h.myUpperBound[2]); z++)
             {
               DGtal::Z3i::RealPoint rp1 = display.embed( DGtal::Z3i::Point(h.myLowerBound[0], y, z) );
               DGtal::Z3i::RealPoint rp2 = display.embed( DGtal::Z3i::Point(h.myUpperBound[0], y, z) );
               display.addLine( rp1, rp2);
             }
         }
       // Faces YZ
       for (int64_t x = NumberTraits<Integer>::castToInt64_t(h.myLowerBound[0]);
            x <= NumberTraits<Integer>::castToInt64_t(h.myUpperBound[0]); x++)
         {
           for (int64_t y = NumberTraits<Integer>::castToInt64_t(h.myLowerBound[1]);
                y <= NumberTraits<Integer>::castToInt64_t(h.myUpperBound[1]); y++)
             {
               DGtal::Z3i::RealPoint rp1 = display.embed( DGtal::Z3i::Point(x, y, h.myLowerBound[2]) );
               DGtal::Z3i::RealPoint rp2 = display.embed( DGtal::Z3i::Point(x, y, h.myUpperBound[2]) );
               display.addLine( rp1, rp2);
             }
           for (int64_t z = NumberTraits<Integer>::castToInt64_t(h.myLowerBound[2]);
                z <= NumberTraits<Integer>::castToInt64_t(h.myUpperBound[2]); z++)
             {
               DGtal::Z3i::RealPoint rp1 = display.embed( DGtal::Z3i::Point(x, h.myLowerBound[1], z) );
               DGtal::Z3i::RealPoint rp2 = display.embed( DGtal::Z3i::Point(x, h.myLowerBound[1], z) );
               display.addLine( rp1, rp2);
             }
         }
     }
 }
template<typename Space , typename KSpace > template<DGtal::Dimension dim, typename TComponent > void DGtal::Display3DFactory< Space, KSpace >::drawAsGrid (Display3D< Space, KSpace > & display, const DGtal::PointVector< dim, TComponent > & anObject) inline static
drawAsGrid
Parameters
display the display where to draw
anObject the object to draw
Definition at line 1069 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addBall(), DGtal::Display3D< Space, KSpace >::embed(), DGtal::Display3D< Space, KSpace >::getFillColor(), DGtal::Display3D< Space, KSpace >::getLineColor(), and DGtal::Display3D< Space, KSpace >::setFillColor().
 {
   DGtal::Color fillColorSave = display.getFillColor();
   ASSERT(dim == 3);
   DGtal::Z3i::RealPoint rp = display.embed( p );
   display.setFillColor(display.getLineColor());
   display.addBall( rp);
   display.setFillColor(fillColorSave);
 }
template<typename Space , typename KSpace > template<typename Domain , typename Compare > void DGtal::Display3DFactory< Space, KSpace >::drawAsPaving (Display3D< Space, KSpace > & display, const DGtal::DigitalSetBySTLSet< Domain, Compare > & anObject) inline static
drawAsPaving
Parameters
display the display where to draw
anObject the object to draw
Definition at line 354 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addCube(), DGtal::DigitalSetBySTLSet< TDomain, TCompare >::begin(), DGtal::DigitalSetBySTLSet< TDomain, TCompare >::className(), DGtal::Display3D< Space, KSpace >::createNewCubeList(), DGtal::Display3D< Space, KSpace >::embed(), and DGtal::DigitalSetBySTLSet< TDomain, TCompare >::end().
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::drawAsPaving(), and DGtal::Board3DTo2DFactory< TSpace, TKSpace >::drawAsPaving().
 {
   typedef typename Domain::Point Point;
   typedef typename std::set<Point>::const_iterator ConstIterator;
   ASSERT(Domain::Space::dimension == 3);
   display.createNewCubeList( s.className());
   for ( ConstIterator it = s.begin();
         it != s.end();
         ++it )
     {
       DGtal::Z3i::RealPoint rp = display.embed((*it) );
       display.addCube(rp);
     }
 }
template<typename Space , typename KSpace > template<typename Domain > void DGtal::Display3DFactory< Space, KSpace >::drawAsPaving (Display3D< Space, KSpace > & display, const DGtal::DigitalSetBySTLVector< Domain > & anObject) inline static
drawAsPaving
Parameters
display the display where to draw
anObject the object to draw
Definition at line 443 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addCube(), DGtal::DigitalSetBySTLVector< TDomain >::begin(), DGtal::DigitalSetBySTLVector< TDomain >::className(), DGtal::Display3D< Space, KSpace >::createNewCubeList(), DGtal::Display3D< Space, KSpace >::embed(), and DGtal::DigitalSetBySTLVector< TDomain >::end().
 {
   typedef typename Domain::Point Point;
   typedef typename std::vector<Point>::const_iterator ConstIterator;
   ASSERT(Domain::Space::dimension == 3);
   display.createNewCubeList( v.className());
   for ( ConstIterator it = v.begin();
         it != v.end();
         ++it )
     {
       DGtal::Z3i::RealPoint rp = display.embed((*it) );
       display.addCube(rp);
     }
 }
template<typename Space , typename KSpace > template<typename SpaceDom > void DGtal::Display3DFactory< Space, KSpace >::drawAsPaving (Display3D< Space, KSpace > & display, const DGtal::HyperRectDomain< SpaceDom > & anObject) inline static
drawAsPaving
Parameters
display the display where to draw
anObject the object to draw
Definition at line 734 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addCube(), DGtal::Display3D< Space, KSpace >::embed(), DGtal::Display3D< Space, KSpace >::getFillColor(), DGtal::HyperRectDomain< TSpace >::myLowerBound, DGtal::HyperRectDomain< TSpace >::myUpperBound, and DGtal::Display3D< Space, KSpace >::setFillColor().
 {
   DGtal::Color fillColorSave = display.getFillColor();
   typedef typename Space::Integer Integer;
   ASSERT(Space::dimension == 3 || "drawAsPaving-NOT-YET-IMPLEMENTED-in-ND");
   if (Space::dimension == 3)
     {
       // Face XY
       for (int64_t z = NumberTraits<Integer>::castToInt64_t(h.myLowerBound[2]);
            z <= NumberTraits<Integer>::castToInt64_t(h.myUpperBound[2]); z++)
         {
           for (int64_t x = NumberTraits<Integer>::castToInt64_t(h.myLowerBound[0]);
                x <= NumberTraits<Integer>::castToInt64_t(h.myUpperBound[0]); x++)
             {
               for (int64_t y = NumberTraits<Integer>::castToInt64_t(h.myLowerBound[1]);
                    y <= NumberTraits<Integer>::castToInt64_t(h.myUpperBound[1]); y++)
                 {
                   DGtal::Z3i::RealPoint rp = display.embed( DGtal::Z3i::Point(x, y, z) );
                   rp[0]+=0.5;
                   rp[1]+=0.5;
                   rp[2]+=0.5;
                   //a transparent color for the paving
                   display.setFillColor( Color(255, 255 ,255, 15));
                   display.addCube(rp, 1.0);
                 }
             }
         }
     }
   display.setFillColor(fillColorSave);
 }
template<typename Space , typename KSpace > template<DGtal::Dimension dim, typename TComponent > void DGtal::Display3DFactory< Space, KSpace >::drawAsPaving (Display3D< Space, KSpace > & display, const DGtal::PointVector< dim, TComponent > & anObject) inline static
drawAsPaving
Parameters
display the display where to draw
anObject the object to draw
Definition at line 1083 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addCube(), and DGtal::Display3D< Space, KSpace >::embed().
 {
   ASSERT(dim == 3);
   DGtal::Z3i::RealPoint rp = display.embed( p );
   display.addCube(rp);
 }
template<typename Space , typename KSpace > template<typename SpaceDom > void DGtal::Display3DFactory< Space, KSpace >::drawAsPavingBalls (Display3D< Space, KSpace > & display, const DGtal::HyperRectDomain< SpaceDom > & anObject) inline static
drawAsPavingBalls
Parameters
display the display where to draw
anObject the object to draw
Definition at line 701 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addBall(), DGtal::Display3D< Space, KSpace >::embed(), DGtal::Display3D< Space, KSpace >::getFillColor(), DGtal::HyperRectDomain< TSpace >::myLowerBound, DGtal::HyperRectDomain< TSpace >::myUpperBound, and DGtal::Display3D< Space, KSpace >::setFillColor().
Referenced by DGtal::Board3DTo2DFactory< TSpace, TKSpace >::drawAsPavingBalls(), and DGtal::Viewer3DFactory< TSpace, TKSpace >::drawAsPavingBalls().
 {
   DGtal::Color fillColorSave = display.getFillColor();
   typedef typename Space::Integer Integer;
   ASSERT(Space::dimension == 3 || "drawAsPavingPoints-NOT-YET-IMPLEMENTED-in-ND");
   if (Space::dimension == 3)
     {
       // Face XY
       for (int64_t z = NumberTraits<Integer>::castToInt64_t(h.myLowerBound[2]);
            z <= NumberTraits<Integer>::castToInt64_t(h.myUpperBound[2]); z++)
         {
           for (int64_t x = NumberTraits<Integer>::castToInt64_t(h.myLowerBound[0]);
                x <= NumberTraits<Integer>::castToInt64_t(h.myUpperBound[0]); x++)
             {
               for (int64_t y = NumberTraits<Integer>::castToInt64_t(h.myLowerBound[1]);
                    y <= NumberTraits<Integer>::castToInt64_t(h.myUpperBound[1]); y++)
                 {
                   DGtal::Z3i::RealPoint rp = display.embed( DGtal::Z3i::Point(x, y, z) );
                   display.setFillColor(DGtal::Color(255, 0 ,0));
                   display.addBall(rp);
                 }
             }
         }
     }
   display.setFillColor(fillColorSave);
 }
template<typename Space , typename KSpace > template<typename Domain , typename Compare > void DGtal::Display3DFactory< Space, KSpace >::drawAsPavingTransparent (Display3D< Space, KSpace > & display, const DGtal::DigitalSetBySTLSet< Domain, Compare > & anObject) inline static
drawAsPavingTransparent
Parameters
display the display where to draw
anObject the object to draw
Definition at line 333 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addCube(), DGtal::DigitalSetBySTLSet< TDomain, TCompare >::begin(), DGtal::DigitalSetBySTLSet< TDomain, TCompare >::className(), DGtal::Display3D< Space, KSpace >::createNewCubeList(), DGtal::Display3D< Space, KSpace >::embed(), and DGtal::DigitalSetBySTLSet< TDomain, TCompare >::end().
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::drawAsPavingTransparent(), and DGtal::Board3DTo2DFactory< TSpace, TKSpace >::drawAsPavingTransparent().
 {
   typedef typename Domain::Point Point;
   typedef typename std::set<Point>::const_iterator ConstIterator;
   ASSERT(Domain::Space::dimension == 3);
   display.createNewCubeList( s.className());
   for ( ConstIterator it = s.begin();
         it != s.end();
         ++it )
     {
       DGtal::Z3i::RealPoint rp = display.embed((*it) );
       display.addCube(rp);
     }
 }
template<typename Space , typename KSpace > template<typename Domain > void DGtal::Display3DFactory< Space, KSpace >::drawAsPavingTransparent (Display3D< Space, KSpace > & display, const DGtal::DigitalSetBySTLVector< Domain > & anObject) inline static
drawAsPavingTransparent
Parameters
display the display where to draw
anObject the object to draw
Definition at line 422 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addCube(), DGtal::DigitalSetBySTLVector< TDomain >::begin(), DGtal::DigitalSetBySTLVector< TDomain >::className(), DGtal::Display3D< Space, KSpace >::createNewCubeList(), DGtal::Display3D< Space, KSpace >::embed(), and DGtal::DigitalSetBySTLVector< TDomain >::end().
 {
   typedef typename Domain::Point Point;
   typedef typename std::vector<Point>::const_iterator ConstIterator;
   ASSERT(Domain::Space::dimension == 3);
   display.createNewCubeList( v.className());
   for ( ConstIterator it = v.begin();
         it != v.end();
         ++it )
     {
       DGtal::Z3i::RealPoint rp = display.embed((*it) );
       display.addCube(rp);
     }
 }
template<typename Space , typename KSpace > template<DGtal::Dimension dim, typename TComponent > void DGtal::Display3DFactory< Space, KSpace >::drawAsPavingWired (Display3D< Space, KSpace > & display, const DGtal::PointVector< dim, TComponent > & anObject) inline static
drawAsPavingWired
Parameters
display the display where to draw
anObject the object to draw
Definition at line 1095 of file Display3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::addCube(), DGtal::Display3D< Space, KSpace >::addLine(), DGtal::Display3D< Space, KSpace >::embed(), DGtal::Display3D< Space, KSpace >::getLineColor(), and DGtal::Display3D< Space, KSpace >::setLineColor().
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::drawAsPavingWired(), and DGtal::Board3DTo2DFactory< TSpace, TKSpace >::drawAsPavingWired().
 {
   DGtal::Color lineColorSave = display.getLineColor();
   ASSERT(dim == 3);
   DGtal::Z3i::RealPoint rp = display.embed( p );
   display.addCube(rp);
   display.setLineColor(DGtal::Color(0,0,0));
   display.addLine(DGtal::Z3i::RealPoint(rp[0]-0.5, rp[1]-0.5, rp[2]-0.5),
                   DGtal::Z3i::RealPoint(rp[0]+0.5, rp[1]-0.5, rp[2]-0.5));
   display.addLine(DGtal::Z3i::RealPoint(rp[0]+0.5, rp[1]-0.5, rp[2]-0.5),
                   DGtal::Z3i::RealPoint(rp[0]+0.5, rp[1]+0.5, rp[2]-0.5));
   display.addLine(DGtal::Z3i::RealPoint(rp[0]+0.5, rp[1]+0.5, rp[2]-0.5),
                   DGtal::Z3i::RealPoint(rp[0]-0.5, rp[1]+0.5, rp[2]-0.5));
   display.addLine(DGtal::Z3i::RealPoint(rp[0]-0.5, rp[1]+0.5, rp[2]-0.5),
                   DGtal::Z3i::RealPoint(rp[0]-0.5, rp[1]-0.5, rp[2]-0.5));
   display.addLine(DGtal::Z3i::RealPoint(rp[0]-0.5, rp[1]-0.5, rp[2]+0.5),
                   DGtal::Z3i::RealPoint(rp[0]+0.5, rp[1]-0.5, rp[2]+0.5));
   display.addLine(DGtal::Z3i::RealPoint(rp[0]+0.5, rp[1]-0.5, rp[2]+0.5),
                   DGtal::Z3i::RealPoint(rp[0]+0.5, rp[1]+0.5, rp[2]+0.5));
   display.addLine(DGtal::Z3i::RealPoint(rp[0]+0.5, rp[1]+0.5, rp[2]+0.5),
                   DGtal::Z3i::RealPoint(rp[0]-0.5, rp[1]+0.5, rp[2]+0.5));
   display.addLine(DGtal::Z3i::RealPoint(rp[0]-0.5, rp[1]+0.5, rp[2]+0.5),
                   DGtal::Z3i::RealPoint(rp[0]-0.5, rp[1]-0.5, rp[2]+0.5));
   display.addLine(DGtal::Z3i::RealPoint(rp[0]-0.5, rp[1]-0.5, rp[2]-0.5),
                   DGtal::Z3i::RealPoint(rp[0]-0.5, rp[1]-0.5, rp[2]+0.5));
   display.addLine(DGtal::Z3i::RealPoint(rp[0]+0.5, rp[1]-0.5, rp[2]-0.5),
                   DGtal::Z3i::RealPoint(rp[0]+0.5, rp[1]-0.5, rp[2]+0.5));
   display.addLine(DGtal::Z3i::RealPoint(rp[0]+0.5, rp[1]+0.5, rp[2]-0.5),
                   DGtal::Z3i::RealPoint(rp[0]+0.5, rp[1]+0.5, rp[2]+0.5));
   display.addLine(DGtal::Z3i::RealPoint(rp[0]-0.5, rp[1]+0.5, rp[2]-0.5),
                   DGtal::Z3i::RealPoint(rp[0]-0.5, rp[1]+0.5, rp[2]+0.5));
   display.setLineColor(lineColorSave);
 }
template<typename Space , typename KSpace > template<typename TDigitalTopology , typename TDigitalSet > void DGtal::Display3DFactory< Space, KSpace >::drawWithAdjacencies (Display3D< Space, KSpace > & display, const DGtal::Object< TDigitalTopology, TDigitalSet > & anObject) inline static
drawWithAdjacencies
Parameters
display the display where to draw
anObject the object to draw
Definition at line 1012 of file Display3DFactory.ih.
References DGtal::HIGH_ITER_DS, DGtal::Object< TDigitalTopology, TDigitalSet >::pointSet(), DGtal::Object< TDigitalTopology, TDigitalSet >::properNeighborhood(), and DGtal::SMALL_DS.
Referenced by DGtal::Viewer3DFactory< TSpace, TKSpace >::drawWithAdjacencies(), and DGtal::Board3DTo2DFactory< TSpace, TKSpace >::drawWithAdjacencies().
 {
   typedef typename TDigitalSet::Point Point;
   typedef typename TDigitalSet::Domain Domain;
   typedef
     typename DigitalSetSelector < Domain,
                                   SMALL_DS + HIGH_ITER_DS >::Type SmallSet;
   typedef Object<TDigitalTopology, SmallSet> SmallObject;
   Point p;
   for (typename TDigitalSet::ConstIterator it = o.pointSet().begin();
        it != o.pointSet().end();
        ++it)
     {
       //Brute-force scan of the neighborhood.
       SmallObject neig = o.properNeighborhood(*it);
       for (typename SmallObject::DigitalSet::ConstIterator it2 = neig.pointSet().begin();
            it2 != neig.pointSet().end();
            ++it2)
         {
           p = (*it2) - (*it);
           draw(display, p, (*it));
         }
     }
 }
The documentation for this struct was generated from the following files:
Display3DFactory.h
Display3DFactory.ih