DGtal: DGtal::CNormalVectorEstimator< T > Struct Template Reference
DGtal::CNormalVectorEstimator< T > Struct Template Reference
DGtal Concepts
#include <CNormalVectorEstimator.h>
Public Types
typedef T::Surface Surface
typedef T::SCell SCell
typedef T::ConstIterator ConstIterator
typedef T::Quantity Quantity
Public Member Functions
BOOST_CONCEPT_ASSERT ((CCellularGridSpaceND< typename Surface::KSpace >))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< SCell, typename Surface::SCell >::value))
BOOST_CONCEPT_ASSERT ((boost::InputIterator< ConstIterator >))
BOOST_CONCEPT_USAGE (CNormalVectorEstimator)
void checkConstConstraints () const
Private Attributes
T myX
Surface mySurface
SCell mySCell
Quantity myQuantity
boost::output_iterator_archetype
< Quantity > myOutIt
Detailed Description
template<typename T>
struct DGtal::CNormalVectorEstimator< T >
Aim: Represents the concept of estimator of normal vector along digital surfaces.
Description of concept 'CNormalVectorEstimator'
Refinement of
Associated types :
Surface : the type of digital surface (must be some DigitalSurface<X>)
ConstIterator : an iterator on the signed cells of the digital surface (same as Surface::ConstIterator).
SCell : the type of signed cell (for surfels along the digital surface) (same as Surface::SCell).
Quantity: the type representing normal vectors.
Notation
X : A type that is a model of CNormalVectorEstimator
x : object of type X
sc : object of type SCell
out_it : an OutputIterator on Quantity
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
Accessor to surface x.surface() const Surface & returns a reference to the digital surface
Local normal vector estimation x.eval(sc) Quantity returns the estimation of the normal vector at the signed cell sc
Global normal vector estimation template <OutputIterator>x.evalAll(out_it) OutputIterator outputs the estimation of the normal vector field of the whole surface
Invariants
Models
LocalConvolutionNormalVectorEstimator
Notes
Template Parameters
T the type that should be a model of CNormalVectorEstimator.
Definition at line 93 of file CNormalVectorEstimator.h.
Member Typedef Documentation
template<typename T > typedef T::ConstIterator DGtal::CNormalVectorEstimator< T >::ConstIterator
Definition at line 99 of file CNormalVectorEstimator.h.
template<typename T > typedef T::Quantity DGtal::CNormalVectorEstimator< T >::Quantity
Definition at line 100 of file CNormalVectorEstimator.h.
template<typename T > typedef T::SCell DGtal::CNormalVectorEstimator< T >::SCell
Definition at line 98 of file CNormalVectorEstimator.h.
template<typename T > typedef T::Surface DGtal::CNormalVectorEstimator< T >::Surface
Definition at line 97 of file CNormalVectorEstimator.h.
Member Function Documentation
template<typename T > DGtal::CNormalVectorEstimator< T >::BOOST_CONCEPT_ASSERT ((CCellularGridSpaceND< typename Surface::KSpace >))
template<typename T > DGtal::CNormalVectorEstimator< T >::BOOST_CONCEPT_ASSERT ((boost::InputIterator< ConstIterator >))
template<typename T > DGtal::CNormalVectorEstimator< T >::BOOST_CONCEPT_USAGE (CNormalVectorEstimator< T >) inline
Definition at line 106 of file CNormalVectorEstimator.h.
References DGtal::CNormalVectorEstimator< T >::checkConstConstraints(), DGtal::CNormalVectorEstimator< T >::myOutIt, DGtal::CNormalVectorEstimator< T >::myQuantity, DGtal::CNormalVectorEstimator< T >::mySCell, DGtal::CNormalVectorEstimator< T >::mySurface, DGtal::CNormalVectorEstimator< T >::myX, and DGtal::ConceptUtils::sameType().
   {
     ConceptUtils::sameType( mySurface, myX.surface() );
     ConceptUtils::sameType( myQuantity, myX.eval( mySCell ) );
     ConceptUtils::sameType( myOutIt, myX.evalAll( myOutIt ) );
     checkConstConstraints();
   }
template<typename T > DGtal::CNormalVectorEstimator< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< SCell, typename Surface::SCell >::value))
template<typename T > void DGtal::CNormalVectorEstimator< T >::checkConstConstraints () const inline
Definition at line 113 of file CNormalVectorEstimator.h.
Referenced by DGtal::CNormalVectorEstimator< T >::BOOST_CONCEPT_USAGE().
   {
   }
Field Documentation
template<typename T > boost::output_iterator_archetype<Quantity> DGtal::CNormalVectorEstimator< T >::myOutIt private
Definition at line 122 of file CNormalVectorEstimator.h.
Referenced by DGtal::CNormalVectorEstimator< T >::BOOST_CONCEPT_USAGE().
template<typename T > Quantity DGtal::CNormalVectorEstimator< T >::myQuantity private
Definition at line 121 of file CNormalVectorEstimator.h.
Referenced by DGtal::CNormalVectorEstimator< T >::BOOST_CONCEPT_USAGE().
template<typename T > SCell DGtal::CNormalVectorEstimator< T >::mySCell private
Definition at line 120 of file CNormalVectorEstimator.h.
Referenced by DGtal::CNormalVectorEstimator< T >::BOOST_CONCEPT_USAGE().
template<typename T > Surface DGtal::CNormalVectorEstimator< T >::mySurface private
Definition at line 119 of file CNormalVectorEstimator.h.
Referenced by DGtal::CNormalVectorEstimator< T >::BOOST_CONCEPT_USAGE().
template<typename T > T DGtal::CNormalVectorEstimator< T >::myX private
Definition at line 118 of file CNormalVectorEstimator.h.
Referenced by DGtal::CNormalVectorEstimator< T >::BOOST_CONCEPT_USAGE().
The documentation for this struct was generated from the following file:
CNormalVectorEstimator.h