DGtal: DGtal::PGMReader< TImageContainer, TFunctor > Struct Template Reference
DGtal::PGMReader< TImageContainer, TFunctor > Struct Template Reference
#include <PGMReader.h>
Public Types
enum MagicNumber {
P1, P2, P3, P4,
P5, P6
}
typedef TImageContainer ImageContainer
typedef TImageContainer::Value Value
typedef
TImageContainer::Domain::Vector Vector
typedef TFunctor Functor
Public Member Functions
BOOST_CONCEPT_ASSERT ((CUnaryFunctor< TFunctor, unsigned char, Value >))
BOOST_STATIC_ASSERT ((ImageContainer::Domain::dimension==2)||(ImageContainer::Domain::dimension==3))
Static Public Member Functions
static ImageContainer importPGM (const std::string &aFilename, const Functor &aFunctor=Functor(), bool topbotomOrder=true) throw (DGtal::IOException)
static ImageContainer importPGM3D (const std::string &aFilename, const Functor &aFunctor=Functor()) throw (DGtal::IOException)
Detailed Description
template<typename TImageContainer, typename TFunctor = CastFunctor< typename TImageContainer::Value >>
struct DGtal::PGMReader< TImageContainer, TFunctor >
Aim: Import a 2D or 3D using the Netpbm formats (ASCII mode).
Description of class 'PGMReader'
PPM: RGB
PGM: grayscale
PPM3D: 3D variant of PPM
PGM3D: 3D variant of PGM
Simple example: (extract from test file testPGMReader.cpp)
*  #include "DGtal/helpers/StdDefs.h"
*  #include "DGtal/io/readers/PGMReader.h"
*  #include "DGtal/kernel/images/ImageSelector.h"
*  ...
*  string filename = "test.pgm";
*  typedef ImageSelector < Z2i::Domain, uint>::Type Image;
*  Image image = PGMReader<Image>::importPGMImage(filename);
*
You can then for instance display a threshold part of the image:
*  #include "DGtal/kernel/imagesSetsUtils/SetFromImage.h"
*  ...
*  Z2i::DigitalSet set2d (image.domain());
*  // Threshold all pixel in ]0, 255] in a DigitalSet
*  SetFromImage<Z2i::DigitalSet>::append<Image>(set2d, image, 0, 255);
*  Board2D board;
*  board << image.domain() << set2d; // display domain and set
*
Template Parameters
TImageContainer the type of the image container
TFunctor the type of functor used in the import (by default set to CastFunctor< TImageContainer::Value>) .
Examples:
topology/ctopo-2.cpp.
Definition at line 96 of file PGMReader.h.
Member Typedef Documentation
template<typename TImageContainer , typename TFunctor = CastFunctor< typename TImageContainer::Value >> typedef TFunctor DGtal::PGMReader< TImageContainer, TFunctor >::Functor
Definition at line 105 of file PGMReader.h.
template<typename TImageContainer , typename TFunctor = CastFunctor< typename TImageContainer::Value >> typedef TImageContainer DGtal::PGMReader< TImageContainer, TFunctor >::ImageContainer
Definition at line 101 of file PGMReader.h.
template<typename TImageContainer , typename TFunctor = CastFunctor< typename TImageContainer::Value >> typedef TImageContainer::Value DGtal::PGMReader< TImageContainer, TFunctor >::Value
Definition at line 102 of file PGMReader.h.
template<typename TImageContainer , typename TFunctor = CastFunctor< typename TImageContainer::Value >> typedef TImageContainer::Domain::Vector DGtal::PGMReader< TImageContainer, TFunctor >::Vector
Definition at line 103 of file PGMReader.h.
Member Enumeration Documentation
template<typename TImageContainer , typename TFunctor = CastFunctor< typename TImageContainer::Value >> enum DGtal::PGMReader::MagicNumber
Enumerator
P1
P2
P3
P4
P5
P6
Definition at line 107 of file PGMReader.h.
 {P1,P2,P3,P4,P5,P6};
Member Function Documentation
template<typename TImageContainer , typename TFunctor = CastFunctor< typename TImageContainer::Value >> DGtal::PGMReader< TImageContainer, TFunctor >::BOOST_CONCEPT_ASSERT ((CUnaryFunctor< TFunctor, unsigned char, Value >))
template<typename TImageContainer , typename TFunctor = CastFunctor< typename TImageContainer::Value >> DGtal::PGMReader< TImageContainer, TFunctor >::BOOST_STATIC_ASSERT ((ImageContainer::Domain::dimension==2)||(ImageContainer::Domain::dimension==3))
template<typename TImageContainer , typename TFunctor > TImageContainer DGtal::PGMReader< TImageContainer, TFunctor >::importPGM (const std::string & aFilename, const Functor & aFunctor = Functor(), bool topbotomOrder = true) throw (DGtal::IOException) inline static
Main method to import a Pgm (8bits) into an instance of the template parameter ImageContainer.
Parameters
aFilename the file name to import.
aFunctor the functor used to import and cast the source image values into the type of the image container value (by default set to CastFunctor < TImageContainer::Value > .
topbotomOrder if true, the point of coordinate (0,0) will be the bottom left corner image point (default) else the center of image coordinate will be the top left of the image (not usual).
Returns
an instance of the ImageContainer.
Examples:
tutorial-examples/freemanChainFromImage.cpp.
Definition at line 54 of file PGMReader.ih.
References DGtal::Trace::error(), and DGtal::trace.
Referenced by DGtal::GenericReader< TContainer, 2 >::importWithValueFunctor().
 {
   std::ifstream infile;
   DGtal::IOException dgtalio;
   BOOST_STATIC_ASSERT( (ImageContainer::Domain::dimension == 2));
   try
     {
       infile.open (aFilename.c_str(), std::ifstream::in);
     }
   catch( ... )
     {
       trace.error() << "PGMReader : can't open " << aFilename << std::endl;
       throw dgtalio;
     }
   bool isASCIImode = false;
   std::string str;
   getline( infile, str );
   if ( ! infile.good() )
     {
       trace.error() << "PGMReader : can't read " << aFilename << std::endl;
       throw dgtalio;
     }
   if ( str != "P5" &&  str != "P2")
     {
       trace.error() << "PGMReader : No P5 or P2 format in " << aFilename << std::endl;
       throw dgtalio;
     }
   if(str== "P2")
     {
       isASCIImode=true;
     }
   do
     {
       getline( infile, str );
       if ( ! infile.good() )
         {
           trace.error() << "PGMReader : Invalid format in " << aFilename << std::endl;
           throw dgtalio;
         }
     }
   while ( str[ 0 ] == '#' || str=="");
   std::istringstream str_in( str );
   unsigned int w, h;
   str_in >> w >> h;
   typename TImageContainer::Point firstPoint;
   typename TImageContainer::Point lastPoint;
   firstPoint = TImageContainer::Point::zero;
   lastPoint[0] = w-1;
   lastPoint[1] = h-1;
   typename TImageContainer::Domain domain(firstPoint,lastPoint);
   TImageContainer image(domain);
   getline( infile, str );
   std::istringstream str2_in( str );
   unsigned int max_value;
   str2_in >> max_value;
   if ( ! infile.good() )
     {
       trace.error() << "PGMReader : Invalid format in " << aFilename << std::endl;
       throw dgtalio;
     }
   unsigned int nb_read = 0;
   if(!isASCIImode)
     infile >> std::noskipws;
   else
     infile >> std::skipws;
   for(unsigned int y=0; y <h; y++)
     for(unsigned int x=0; x <w; x++)
       {
           typename TImageContainer::Point pt;
           if (topbotomOrder){
             pt[0]=x; pt[1]=h-1-y;
           }else{
             pt[0]=x; pt[1]=y;
           }
           if(!isASCIImode)
             {
               unsigned char c;
               infile >> c;
               if ( infile.good() )
                 {
                   ++nb_read;
                   image.setValue( pt, aFunctor(c));
                 }
             }
           else
             {
               int c;
               infile >> c;
               if ( infile.good() )
                 {
                   ++nb_read;
                   image.setValue( pt, aFunctor(c));
                 }
             }
       }
   if ( infile.fail() || infile.bad() )
     {
       trace.error() << "# nbread=" << nb_read << std::endl;
       throw dgtalio;
     }
   infile >> std::skipws;
   return  image;
 }
template<typename TImageContainer , typename TFunctor > TImageContainer DGtal::PGMReader< TImageContainer, TFunctor >::importPGM3D (const std::string & aFilename, const Functor & aFunctor = Functor()) throw (DGtal::IOException) inline static
Main method to import a Pgm3D (8bits) into an instance of the template parameter ImageContainer.
Parameters
aFilename the file name to import.
aFunctor the functor used to import and cast the source image values into the type of the image container value (by default set to CastFunctor < TImageContainer::Value > .
Returns
an instance of the ImageContainer.
Definition at line 175 of file PGMReader.ih.
References DGtal::Trace::error(), and DGtal::trace.
Referenced by DGtal::GenericReader< TContainer, 3 >::importWithValueFunctor().
 {
   std::ifstream infile;
   DGtal::IOException dgtalio;
   BOOST_STATIC_ASSERT( (ImageContainer::Domain::dimension == 3));
   try
     {
       infile.open (aFilename.c_str(), std::ifstream::in);
     }
   catch( ... )
     {
       trace.error() << "PGMReader : can't open " << aFilename << std::endl;
       throw dgtalio;
     }
   std::string str;
   getline( infile, str );
   if ( ! infile.good() ) {
     trace.error() << "PGMReader : can't read " << aFilename << std::endl;
     throw dgtalio;
   }
   if ( str != "P3d" &&  str != "P3D"&&  str != "P2-3D" &&  str != "P5-3D" &&  str != "P5" &&  str != "P3" ){
     trace.error() << "PGMReader : No P3d format in " << aFilename << std::endl;
     throw dgtalio;
   }
   bool isASCIImode = (str=="P2-3D" || str=="P2" );
   if(!isASCIImode)
     infile >> std::noskipws;
   else
     infile >> std::skipws;
   do
     {
       getline( infile, str );
       if ( ! infile.good() ){
         trace.error() << "PGMReader : Invalid format in " << aFilename << std::endl;
         throw dgtalio;
       }
     }
   while ( str[ 0 ] == '#' || str=="");
   std::istringstream str_in( str );
   unsigned int w, h, e;
   str_in >> w >> h >> e ;
   typename TImageContainer::Point firstPoint;
   typename TImageContainer::Point lastPoint;
   firstPoint = TImageContainer::Point::zero;
   lastPoint[0] = w-1;
   lastPoint[1] = h-1;
   lastPoint[2] = e-1;
   typename TImageContainer::Domain domain(firstPoint,lastPoint);
   TImageContainer image(domain);
   getline( infile, str );
   std::istringstream str2_in( str );
   int max_value;
   str2_in >> max_value;
   if ( ! infile.good() ){
     trace.error() << "PGMReader : Invalid format in " << aFilename << std::endl;
     throw dgtalio;
   }
   unsigned int nb_read = 0;
   infile >> std::noskipws;
   for(unsigned int z=0; z <e; z++){
     for(unsigned int y=0; y <h; y++){
       for(unsigned int x=0; x <w; x++){
         typename TImageContainer::Point pt;
         pt[0]=x; pt[1]=y; pt[2]=z;
   if(!isASCIImode)
             {
               unsigned char c;
               infile >> c;
               if ( infile.good() )
                 {
                   ++nb_read;
                   image.setValue( pt, aFunctor(c));
                 }
             }
           else
             {
               int c;
               infile >> c;
               if ( infile.good() )
                 {
                   ++nb_read;
                   image.setValue( pt, aFunctor(c));
                 }
             }
       }
     }
   }
   if ( infile.fail() || infile.bad() )
     {
       trace.error() << "# nbread=" << nb_read << std::endl;
       throw dgtalio;
     }
   infile >> std::skipws;
   return  image;
 }
The documentation for this struct was generated from the following files:
PGMReader.h
PGMReader.ih