DGtal: DGtal::Viewer3DFactory< TSpace, TKSpace > Struct Template Reference
DGtal::Viewer3DFactory< TSpace, TKSpace > Struct Template Reference
#include <Viewer3DFactory.h>
Public Types
typedef TSpace Space
typedef TKSpace KSpace
Public Types inherited from DGtal::Display3DFactory< TSpace, TKSpace >
typedef TSpace Space
typedef TKSpace KSpace
Public Member Functions
template<typename TIterator>
void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToPoint< KSpace >, typename KSpace::Point > &aRangeAdapter)
template<typename TIterator>
void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::ConstRangeAdapter< TIterator, CanonicSCellEmbedder< KSpace >, typename KSpace::Space::RealPoint > &aRangeAdapter)
template<typename TIterator>
void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToArrow< KSpace >, std::pair< typename KSpace::Point, typename KSpace::Vector > > &aRangeAdapter)
template<typename TIterator>
void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToInnerPoint< KSpace >, typename KSpace::Point > &aRangeAdapter)
template<typename TIterator>
void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToOuterPoint< KSpace >, typename KSpace::Point > &aRangeAdapter)
template<typename TIterator>
void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToIncidentPoints< KSpace >, std::pair< typename KSpace::Point, typename KSpace::Point > > &aRangeAdapter)
Public Member Functions inherited from DGtal::Display3DFactory< TSpace, TKSpace >
template<typename TV>
void draw (Display3D< Space, KSpace > &display, const DGtal::SphericalAccumulator< TV > &aAccumulator, const typename DGtal::SphericalAccumulator< TV >::RealVector &shift, const double radius)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToPoint< KSpace >, typename KSpace::Point > &object)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, CanonicSCellEmbedder< KSpace >, typename KSpace::Space::RealPoint > &object)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToArrow< KSpace >, std::pair< typename KSpace::Point, typename KSpace::Vector > > &object)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToInnerPoint< KSpace >, typename KSpace::Point > &object)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToOuterPoint< KSpace >, typename KSpace::Point > &object)
template<typename TIterator>
void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToIncidentPoints< KSpace >, std::pair< typename KSpace::Point, typename KSpace::Point > > &object)
Static Public Member Functions
static void draw (Viewer3D< Space, KSpace > &board, const DGtal::CameraPosition &aThing)
static void draw (Viewer3D< Space, KSpace > &board, const DGtal::CameraDirection &aThing)
static void draw (Viewer3D< Space, KSpace > &board, const DGtal::CameraUpVector &aThing)
static void draw (Viewer3D< Space, KSpace > &board, const DGtal::CameraZNearFar &aThing)
template<typename TVector >
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::SphericalAccumulator< TVector > &accumulator, const typename DGtal::SphericalAccumulator< TVector >::RealVector &shift=typename DGtal::SphericalAccumulator< TVector >::RealVector(0, 0, 0), const double radius=1.0)
template<typename TPoint >
static void drawAsFaces (Viewer3D< Space, KSpace > &viewer, const DGtal::Mesh< TPoint > &aMesh)
template<typename TPoint >
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::Mesh< TPoint > &aMesh)
template<typename TIterator , typename TInteger , int connectivity>
static
DGtal::DrawableWithViewer3D * defaultStyle (std::string str, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &arithm)
template<typename TIterator , typename TInteger , int connectivity>
static void drawAsBalls (Viewer3D< Space, KSpace > &viewer, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &arithm)
template<typename TIterator , typename TInteger , int connectivity>
static void drawAsBoundingBox (Viewer3D< Space, KSpace > &viewer, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &arithm)
template<typename TIterator , typename TInteger , int connectivity>
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &arithm)
template<typename Domain , typename Compare >
static
DGtal::DrawableWithViewer3D * defaultStyle (std::string str, const DGtal::DigitalSetBySTLSet< Domain, Compare > &aSet)
template<typename Domain , typename Compare >
static void drawAsPavingTransparent (Viewer3D< Space, KSpace > &viewer, const DGtal::DigitalSetBySTLSet< Domain, Compare > &aSet)
template<typename Domain , typename Compare >
static void drawAsPaving (Viewer3D< Space, KSpace > &viewer, const DGtal::DigitalSetBySTLSet< Domain, Compare > &aSet)
template<typename Domain , typename Compare >
static void drawAsGrid (Viewer3D< Space, KSpace > &viewer, const DGtal::DigitalSetBySTLSet< Domain, Compare > &aSet)
template<typename Domain , typename Compare >
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::DigitalSetBySTLSet< Domain, Compare > &aSet)
template<typename Domain >
static
DGtal::DrawableWithViewer3D * defaultStyle (std::string str, const DGtal::DigitalSetBySTLVector< Domain > &aSet)
template<typename Domain >
static void drawAsPavingTransparent (Viewer3D< Space, KSpace > &viewer, const DGtal::DigitalSetBySTLVector< Domain > &aSet)
template<typename Domain >
static void drawAsPaving (Viewer3D< Space, KSpace > &viewer, const DGtal::DigitalSetBySTLVector< Domain > &aSet)
template<typename Domain >
static void drawAsGrid (Viewer3D< Space, KSpace > &viewer, const DGtal::DigitalSetBySTLVector< Domain > &aSet)
template<typename Domain >
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::DigitalSetBySTLVector< Domain > &aSet)
template<typename SpaceDom >
static
DGtal::DrawableWithViewer3D * defaultStyle (std::string str, const DGtal::HyperRectDomain< SpaceDom > &aDomain)
template<typename SpaceDom >
static void drawAsBoundingBox (Viewer3D< Space, KSpace > &viewer, const DGtal::HyperRectDomain< SpaceDom > &aDomain)
template<typename SpaceDom >
static void drawAsGrid (Viewer3D< Space, KSpace > &viewer, const DGtal::HyperRectDomain< SpaceDom > &aDomain)
template<typename SpaceDom >
static void drawAsPavingBalls (Viewer3D< Space, KSpace > &viewer, const DGtal::HyperRectDomain< SpaceDom > &aDomain)
template<typename SpaceDom >
static void drawAsPaving (Viewer3D< Space, KSpace > &viewer, const DGtal::HyperRectDomain< SpaceDom > &aDomain)
template<typename SpaceDom >
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::HyperRectDomain< SpaceDom > &aDomain)
static
DGtal::DrawableWithViewer3D * defaultStyle (std::string str, const typename KSpace::Cell &aCell)
static void draw (Viewer3D< Space, KSpace > &viewer, const typename KSpace::Cell &aCell)
template<typename TDigitalTopology , typename TDigitalSet >
static
DGtal::DrawableWithViewer3D * defaultStyle (std::string str, const DGtal::Object< TDigitalTopology, TDigitalSet > &anObject)
template<typename TDigitalTopology , typename TDigitalSet >
static void drawWithAdjacencies (Viewer3D< Space, KSpace > &viewer, const DGtal::Object< TDigitalTopology, TDigitalSet > &anObject)
template<typename TDigitalTopology , typename TDigitalSet >
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::Object< TDigitalTopology, TDigitalSet > &anObject)
template<Dimension dim, typename TComponent >
static
DGtal::DrawableWithViewer3D * defaultStyle (std::string str, const DGtal::PointVector< dim, TComponent > &aPoint)
template<Dimension dim, typename TComponent >
static void drawAsGrid (Viewer3D< Space, KSpace > &viewer, const DGtal::PointVector< dim, TComponent > &aPoint)
template<Dimension dim, typename TComponent >
static void drawAsPaving (Viewer3D< Space, KSpace > &viewer, const DGtal::PointVector< dim, TComponent > &aPoint)
template<Dimension dim, typename TComponent >
static void drawAsPavingWired (Viewer3D< Space, KSpace > &viewer, const DGtal::PointVector< dim, TComponent > &aPoint)
template<Dimension dim, typename TComponent >
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::PointVector< dim, TComponent > &aPoint)
template<Dimension dim, typename TComponent >
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::PointVector< dim, TComponent > &aPoint, const DGtal::PointVector< dim, TComponent > &aPoint2)
static
DGtal::DrawableWithViewer3D * defaultStyle (std::string str, const typename KSpace::SCell &aSCell)
static void draw (Viewer3D< Space, KSpace > &viewer, const typename KSpace::SCell &aSCell)
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::GridCurve< KSpace > &aGrid)
template<typename TIterator , typename TSCell >
static void draw (DGtal::Viewer3D< Space, KSpace > &viewer, const DGtal::ConstRangeAdapter< TIterator, DGtal::DefaultFunctor, TSCell > &aRangeAdapter)
template<typename TIterator >
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToPoint< TKSpace >, typename TKSpace::Point > &aRangeAdapter)
template<typename TIterator >
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::ConstRangeAdapter< TIterator, CanonicSCellEmbedder< TKSpace >, typename TKSpace::Space::RealPoint > &aRangeAdapter)
template<typename TIterator >
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToArrow< TKSpace >, std::pair< typename TKSpace::Point, typename TKSpace::Vector > > &aRangeAdapter)
template<typename TIterator >
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToInnerPoint< TKSpace >, typename TKSpace::Point > &aRangeAdapter)
template<typename TIterator >
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToOuterPoint< TKSpace >, typename TKSpace::Point > &aRangeAdapter)
template<typename TIterator >
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToIncidentPoints< TKSpace >, std::pair< typename TKSpace::Point, typename TKSpace::Point > > &aRangeAdapter)
template<typename TValue >
static void draw (Viewer3D< Space, KSpace > &viewer, const ImageContainerBySTLVector< DGtal::Z2i::Domain, TValue > &anImage)
template<typename TValue >
static void draw (Viewer3D< Space, KSpace > &viewer, const ImageContainerBySTLMap< DGtal::Z2i::Domain, TValue > &anImage)
template<typename TImageContainer , typename TFunctorD , typename TNewValue , typename TFunctorValue >
static void draw (Viewer3D< Space, KSpace > &viewer, const ConstImageAdapter< TImageContainer, DGtal::Z2i::Domain, TFunctorD, TNewValue, TFunctorValue > &anImage)
template<typename TImageContainer , typename TFunctorD , typename TNewValue , typename TFunctorValue , typename TFunctorValueVm1 >
static void draw (Viewer3D< Space, KSpace > &viewer, const ImageAdapter< TImageContainer, DGtal::Z2i::Domain, TFunctorD, TNewValue, TFunctorValue, TFunctorValueVm1 > &anImage)
template<typename TValue >
static void draw (Viewer3D< Space, KSpace > &viewer, const ImageContainerBySTLVector< DGtal::Z3i::Domain, TValue > &anImage)
template<typename TValue >
static void draw (Viewer3D< Space, KSpace > &viewer, const ImageContainerBySTLMap< DGtal::Z3i::Domain, TValue > &anImage)
template<typename TImageContainer , typename TFunctorD , typename TNewValue , typename TFunctorValue >
static void draw (Viewer3D< Space, KSpace > &viewer, const ConstImageAdapter< TImageContainer, DGtal::Z3i::Domain, TFunctorD, TNewValue, TFunctorValue > &anImage)
template<typename TImageContainer , typename TFunctorD , typename TNewValue , typename TFunctorValue , typename TFunctorValueVm1 >
static void draw (Viewer3D< Space, KSpace > &viewer, const ImageAdapter< TImageContainer, DGtal::Z3i::Domain, TFunctorD, TNewValue, TFunctorValue, TFunctorValueVm1 > &anImage)
template<typename TImageType2D , typename TFunctor >
static void drawImage2D (Viewer3D< Space, KSpace > &viewer, const TImageType2D &anImage, const TFunctor &aFunctor, typename Viewer3D< Space, KSpace >::TextureMode aTextureMode)
template<typename TImageType3D , typename TFunctor >
static void drawImage3D (Viewer3D< Space, KSpace > &viewer, const TImageType3D &anImage3D, const TFunctor &aFunctor, typename Viewer3D< Space, KSpace >::TextureMode aTextureMode)
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::SetMode3D &aMode)
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::CustomStyle3D &aStyle)
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::CustomColors3D &aColor)
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::ClippingPlane &aClipping)
template<typename TImageType , typename TFunctor >
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::AddTextureImage3DWithFunctor< TImageType, TFunctor, Space, KSpace > &aFunctor)
template<typename TImageType , typename TFunctor >
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::AddTextureImage2DWithFunctor< TImageType, TFunctor, Space, KSpace > &aFunctor)
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::UpdateImagePosition< Space, KSpace > &anUpdate)
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::UpdateLastImagePosition< Space, KSpace > &anUpdate)
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::UpdateImage3DEmbedding< Space, KSpace > &anUpdate)
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::Update2DDomainPosition< Space, KSpace > &anUpdate)
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::Translate2DDomain &anTranslation)
template<typename TImageType , typename TFunctor >
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::UpdateImageData< TImageType, TFunctor > &anUpdate)
static void draw (Viewer3D< Space, KSpace > &viewer, const DGtal::TransformedSurfelPrism &aTransformedSurfelPrism)
Static Public Member Functions inherited from DGtal::Display3DFactory< TSpace, TKSpace >
template<typename TVector >
static void draw (Display3D< Space, KSpace > &display, const DGtal::SphericalAccumulator< TVector > &accumulator, const typename DGtal::SphericalAccumulator< TVector >::RealVector &shift=typename DGtal::SphericalAccumulator< TVector >::RealVector(0, 0, 0), const double radius=1.0)
template<typename TPoint >
static void drawAsFaces (Display3D< Space, KSpace > &display, const DGtal::Mesh< TPoint > &aMesh)
template<typename TPoint >
static void draw (Display3D< Space, KSpace > &display, const DGtal::Mesh< TPoint > &aMesh)
template<typename TIterator , typename TInteger , int connectivity>
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &anObject)
template<typename TIterator , typename TInteger , int connectivity>
static void drawAsBalls (Display3D< Space, KSpace > &display, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &anObject)
template<typename TIterator , typename TInteger , int connectivity>
static void drawAsBoundingBox (Display3D< Space, KSpace > &display, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &anObject)
template<typename TIterator , typename TInteger , int connectivity>
static void draw (Display3D< Space, KSpace > &display, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > &anObject)
template<typename Domain , typename Compare >
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::DigitalSetBySTLSet< Domain, Compare > &anObject)
template<typename Domain , typename Compare >
static void drawAsPavingTransparent (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLSet< Domain, Compare > &anObject)
template<typename Domain , typename Compare >
static void drawAsPaving (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLSet< Domain, Compare > &anObject)
template<typename Domain , typename Compare >
static void drawAsGrid (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLSet< Domain, Compare > &anObject)
template<typename Domain , typename Compare >
static void draw (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLSet< Domain, Compare > &anObject)
template<typename Domain >
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::DigitalSetBySTLVector< Domain > &anObject)
template<typename Domain >
static void drawAsPavingTransparent (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLVector< Domain > &anObject)
template<typename Domain >
static void drawAsPaving (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLVector< Domain > &anObject)
template<typename Domain >
static void drawAsGrid (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLVector< Domain > &anObject)
template<typename Domain >
static void draw (Display3D< Space, KSpace > &display, const DGtal::DigitalSetBySTLVector< Domain > &anObject)
template<typename SpaceDom >
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::HyperRectDomain< SpaceDom > &anObject)
template<typename SpaceDom >
static void drawAsBoundingBox (Display3D< Space, KSpace > &display, const DGtal::HyperRectDomain< SpaceDom > &anObject)
template<typename SpaceDom >
static void drawAsGrid (Display3D< Space, KSpace > &display, const DGtal::HyperRectDomain< SpaceDom > &anObject)
template<typename SpaceDom >
static void drawAsPavingBalls (Display3D< Space, KSpace > &display, const DGtal::HyperRectDomain< SpaceDom > &anObject)
template<typename SpaceDom >
static void drawAsPaving (Display3D< Space, KSpace > &display, const DGtal::HyperRectDomain< SpaceDom > &anObject)
template<typename SpaceDom >
static void draw (Display3D< Space, KSpace > &display, const DGtal::HyperRectDomain< SpaceDom > &anObject)
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const typename KSpace::Cell &anObject)
static void draw (Display3D< Space, KSpace > &display, const typename KSpace::Cell &anObject)
template<typename TDigitalTopology , typename TDigitalSet >
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::Object< TDigitalTopology, TDigitalSet > &anObject)
template<typename TDigitalTopology , typename TDigitalSet >
static void drawWithAdjacencies (Display3D< Space, KSpace > &display, const DGtal::Object< TDigitalTopology, TDigitalSet > &anObject)
template<typename TDigitalTopology , typename TDigitalSet >
static void draw (Display3D< Space, KSpace > &display, const DGtal::Object< TDigitalTopology, TDigitalSet > &anObject)
template<Dimension dim, typename TComponent >
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const DGtal::PointVector< dim, TComponent > &anObject)
template<Dimension dim, typename TComponent >
static void drawAsGrid (Display3D< Space, KSpace > &display, const DGtal::PointVector< dim, TComponent > &anObject)
template<Dimension dim, typename TComponent >
static void drawAsPaving (Display3D< Space, KSpace > &display, const DGtal::PointVector< dim, TComponent > &anObject)
template<Dimension dim, typename TComponent >
static void drawAsPavingWired (Display3D< Space, KSpace > &display, const DGtal::PointVector< dim, TComponent > &anObject)
template<Dimension dim, typename TComponent >
static void draw (Display3D< Space, KSpace > &display, const DGtal::PointVector< dim, TComponent > &anObject)
template<Dimension dim, typename TComponent >
static void draw (Display3D< Space, KSpace > &display, const DGtal::PointVector< dim, TComponent > &, const DGtal::PointVector< dim, TComponent > &anObject)
static
DGtal::DrawableWithDisplay3D * defaultStyle (std::string str, const typename KSpace::SCell &anObject)
static void draw (Display3D< Space, KSpace > &display, const typename KSpace::SCell &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::GridCurve< KSpace > &anObject)
template<typename TIterator , typename TSCell >
static void draw (DGtal::Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, DGtal::DefaultFunctor, TSCell > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToPoint< KSpace >, typename TKSpace::Point > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, CanonicSCellEmbedder< KSpace >, typename TKSpace::Space::RealPoint > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToArrow< KSpace >, std::pair< typename TKSpace::Point, typename TKSpace::Vector > > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToInnerPoint< KSpace >, typename TKSpace::Point > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToOuterPoint< KSpace >, typename TKSpace::Point > &anObject)
template<typename TIterator >
static void draw (Display3D< Space, KSpace > &display, const DGtal::ConstRangeAdapter< TIterator, SCellToIncidentPoints< KSpace >, std::pair< typename TKSpace::Point, typename TKSpace::Point > > &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::SetMode3D &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::CustomStyle3D &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::CustomColors3D &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::ClippingPlane &anObject)
static void draw (Display3D< Space, KSpace > &display, const DGtal::TransformedSurfelPrism &aTransformedSurfelPrism)
Detailed Description
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace>
struct DGtal::Viewer3DFactory< TSpace, TKSpace >
Factory for GPL Viewer3D:
Description of struct 'Viewer3DFactory'
Definition at line 78 of file Viewer3DFactory.h.
Member Typedef Documentation
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> typedef TKSpace DGtal::Viewer3DFactory< TSpace, TKSpace >::KSpace
KSpace type.
Definition at line 84 of file Viewer3DFactory.h.
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> typedef TSpace DGtal::Viewer3DFactory< TSpace, TKSpace >::Space
Space type.
Definition at line 81 of file Viewer3DFactory.h.
Member Function Documentation
template<typename Space , typename KSpace > template<typename TIterator , typename TInteger , int connectivity> DGtal::DrawableWithViewer3D * DGtal::Viewer3DFactory< Space, KSpace >::defaultStyle (std::string str, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > & arithm) inline static
Default drawing style object.
Parameters
str the name of the class
arithm the arithm to draw
Returns
the dyn. alloc. default style for this object.
Definition at line 429 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle().
 {
   return DGtal::Display3DFactory<Space,KSpace>::defaultStyle(str, arithm);
 }
template<typename Space , typename KSpace > template<typename Domain , typename Compare > DGtal::DrawableWithViewer3D * DGtal::Viewer3DFactory< Space, KSpace >::defaultStyle (std::string str, const DGtal::DigitalSetBySTLSet< Domain, Compare > & aSet) inline static
Return the default drawing style object.
Parameters
str the name of the class
aSet the set to draw
Returns
the dyn. alloc. default style for this object.
Definition at line 468 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle().
 {
   return DGtal::Display3DFactory<Space,KSpace>::defaultStyle(str, aSet);
 }
template<typename Space , typename KSpace > template<typename Domain > DGtal::DrawableWithViewer3D * DGtal::Viewer3DFactory< Space, KSpace >::defaultStyle (std::string str, const DGtal::DigitalSetBySTLVector< Domain > & aSet) inline static
Default drawing style object.
Parameters
str the name of the class
aSet the set to draw
Returns
the dyn. alloc. default style for this object.
Definition at line 516 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle().
 {
   return DGtal::Display3DFactory<Space,KSpace>::defaultStyle(str, aSet);
 }
template<typename Space , typename KSpace > template<typename SpaceDom > DGtal::DrawableWithViewer3D * DGtal::Viewer3DFactory< Space, KSpace >::defaultStyle (std::string str, const DGtal::HyperRectDomain< SpaceDom > & aDomain) inline static
Default drawing style object.
Parameters
str the name of the class
aDomain the domain to draw
Returns
the dyn. alloc. default style for this object.
Definition at line 564 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle().
 {
   return DGtal::Display3DFactory<Space,KSpace>::defaultStyle( str, aDomain);
 }
template<typename Space , typename KSpace > DGtal::DrawableWithViewer3D * DGtal::Viewer3DFactory< Space, KSpace >::defaultStyle (std::string str, const typename KSpace::Cell & aCell) inline static
Default drawing style object.
Parameters
str the name of the class
aCell the cell to draw
Returns
the dyn. alloc. default style for this object.
Definition at line 613 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle().
 {
   return DGtal::Display3DFactory<Space,KSpace>::defaultStyle(str, aCell);
 }
template<typename Space , typename KSpace > template<typename TDigitalTopology , typename TDigitalSet > DGtal::DrawableWithViewer3D * DGtal::Viewer3DFactory< Space, KSpace >::defaultStyle (std::string str, const DGtal::Object< TDigitalTopology, TDigitalSet > & anObject) inline static
Method to return the defaultStyle of an object.
Parameters
str the name of the class
anObject the object to draw
Returns
a pointer to the default object style
Definition at line 633 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle().
 {
   return DGtal::Display3DFactory<Space,KSpace>::defaultStyle( str, anObject);
 }
template<typename Space , typename KSpace > template<DGtal::Dimension dim, typename TComponent > DGtal::DrawableWithViewer3D * DGtal::Viewer3DFactory< Space, KSpace >::defaultStyle (std::string str, const DGtal::PointVector< dim, TComponent > & aPoint) inline static
Default drawing style object.
Parameters
str the name of the class
aPoint the point to draw
Returns
the dyn. alloc. default style for this object.
Definition at line 663 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle().
 {
   return DGtal::Display3DFactory<Space,KSpace>::defaultStyle( str, aPoint);
 }
template<typename Space , typename KSpace > DGtal::DrawableWithViewer3D * DGtal::Viewer3DFactory< Space, KSpace >::defaultStyle (std::string str, const typename KSpace::SCell & aSCell) inline static
Default drawing style object.
Parameters
str the name of the class
aSCell the signed cell to draw
Returns
the dyn. alloc. default style for this object.
Definition at line 719 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::defaultStyle().
 {
   return  DGtal::Display3DFactory<Space,KSpace>::defaultStyle( str, aSCell);
 }
template<typename Space , typename KSpace > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & board, const DGtal::CameraPosition & aThing) inline static
Set the camera position on the board.
Parameters
board the board where to draw
aThing the camera position to set
Definition at line 45 of file Viewer3DFactory.ih.
References DGtal::CameraPosition::eyex, DGtal::CameraPosition::eyey, DGtal::CameraPosition::eyez, and DGtal::Viewer3D< S, KS >::setCameraPosition().
Referenced by DGtal::Viewer3D< S, KS >::operator<<().
 {
   viewer.setCameraPosition(cp.eyex, cp.eyey, cp.eyez);
 }
template<typename Space , typename KSpace > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & board, const DGtal::CameraDirection & aThing) inline static
Set the camera direction on the board.
Parameters
board the board where to draw
aThing the camera direction to set
Definition at line 53 of file Viewer3DFactory.ih.
References DGtal::CameraDirection::dirx, DGtal::CameraDirection::diry, DGtal::CameraDirection::dirz, and DGtal::Viewer3D< S, KS >::setCameraDirection().
 {
   viewer.setCameraDirection(cd.dirx, cd.diry, cd.dirz);
 }
template<typename Space , typename KSpace > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & board, const DGtal::CameraUpVector & aThing) inline static
Set the camera up vector on the board.
Parameters
board the board where to draw
aThing the camera up vector to set
Definition at line 61 of file Viewer3DFactory.ih.
References DGtal::Viewer3D< S, KS >::setCameraUpVector(), DGtal::CameraUpVector::upx, DGtal::CameraUpVector::upy, and DGtal::CameraUpVector::upz.
 {
   viewer.setCameraUpVector(cuv.upx, cuv.upy, cuv.upz);
 }
template<typename Space , typename KSpace > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & board, const DGtal::CameraZNearFar & aThing) inline static
Set the near and far distance on the board.
Parameters
board the board where to draw
aThing the near and far distance
Definition at line 69 of file Viewer3DFactory.ih.
References DGtal::Viewer3D< S, KS >::setNearFar(), DGtal::CameraZNearFar::ZFar, and DGtal::CameraZNearFar::ZNear.
 {
   viewer.setNearFar(cz.ZNear, cz.ZFar);
 }
template<typename Space , typename KSpace > template<typename TVector > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::SphericalAccumulator< TVector > & accumulator, const typename DGtal::SphericalAccumulator< TVector >::RealVector & shift = typename DGtal::SphericalAccumulator<TVector>::RealVector(0,0,0), const double radius = 1.0) inline static
Display an spherical accumulator in 3D. Bin values are mapped using a default HueShadeColorMap.
Parameters
viewer the viewer where to draw current viewer
accumulator the accumulator to viewer
shift translate vector for viewer purposes (default: zero vector)
radius scale factor for the unit sphere radius (default:1)
Template Parameters
TVector a vector model
Definition at line 396 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw ( viewer, accumulator, shift, radius);
 }
template<typename Space , typename KSpace > template<typename TPoint > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::Mesh< TPoint > & aMesh) inline static
Method to draw Mesh.
Parameters
viewer the viewer where to draw
aMesh the mesh to draw
Definition at line 418 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw (viewer, aMesh);
 }
template<typename Space , typename KSpace > template<typename TIterator , typename TInteger , int connectivity> void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > & arithm) inline static
Method to draw StandardDSS6Computer.
Parameters
viewer the viewer where to draw
arithm the arithm to draw
Definition at line 456 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw(viewer , arithm);
 }
template<typename Space , typename KSpace > template<typename Domain , typename Compare > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::DigitalSetBySTLSet< Domain, Compare > & aSet) inline static
Method to draw DigitalSetBySTLSet.
Parameters
viewer the viewer where to draw
aSet the set to draw
Definition at line 504 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aSet);
 }
template<typename Space , typename KSpace > template<typename Domain > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::DigitalSetBySTLVector< Domain > & aSet) inline static
Method to draw DigitalSetBySTLVector.
Parameters
viewer the viewer where to draw
aSet the set to draw
Definition at line 552 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aSet);
 }
template<typename Space , typename KSpace > template<typename SpaceDom > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::HyperRectDomain< SpaceDom > & aDomain) inline static
Method to draw HyperRectDomain.
Parameters
viewer the viewer where to draw
aDomain the domain to draw
Definition at line 342 of file Viewer3DFactory.ih.
References DGtal::Viewer3D< S, KS >::addImage2DDomainD3D(), DGtal::HyperRectDomain< TSpace >::className(), DGtal::Display3D< Space, KSpace >::createNewCubeList(), DGtal::Display3D< Space, KSpace >::createNewLineList(), and DGtal::Display3D< Space, KSpace >::getMode().
 {
   std::string mode = viewer.getMode( aDomain.className() );
   ASSERT((SpaceDom::dimension==3)|| (SpaceDom::dimension==2));
   ASSERT((SpaceDom::dimension!=3) || (mode=="" || mode=="Grid" || mode=="Paving"|| mode=="PavingPoints"|| mode=="PavingGrids" ||
                                     mode=="BoundingBox")||
          ("DGtal::Display3DFactory<Space,KSpace>::draw( Display3D<Space, KSpace> & viewer, const DGtal::HyperRectDomain<Space> & aDomain ): Unknown mode "+mode)=="");
   ASSERT((SpaceDom::dimension!=2) || (mode=="" || mode=="BoundingBox" || mode=="InterGrid"|| mode=="Grid") ||
          ("DGtal::Display3DFactory<Space,KSpace>::draw( Display3D<Space, KSpace> & viewer, const DGtal::HyperRectDomain<Space> & aDomain ): Unknown mode "+mode)=="");
   if(SpaceDom::dimension == 3){
     if ( mode == "BoundingBox" )
       {
         viewer.createNewLineList(aDomain.className());
         drawAsBoundingBox( viewer, aDomain );
       }else if( ( mode == "" ) || (mode == "Grid"))
       {
         viewer.createNewLineList(aDomain.className());
         drawAsGrid( viewer, aDomain );
       }
     else if ( mode == "Paving" )
       {
         viewer.createNewCubeList( aDomain.className());
         drawAsPaving( viewer, aDomain );
       }else if ( mode == "PavingGrids" )
       {
         viewer.createNewLineList(aDomain.className());
         viewer.createNewCubeList( aDomain.className());
         drawAsGrid( viewer, aDomain );
         drawAsPaving( viewer, aDomain );
       }
   }else if(SpaceDom::dimension == 2)
     {
       if (mode=="")
         mode="BoundingBox";
       viewer.addImage2DDomainD3D(aDomain, mode);
     }
 }
template<typename Space , typename KSpace > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const typename KSpace::Cell & aCell) inline static
Method to draw KhalimskyCell.
Parameters
viewer the viewer where to draw
aCell the cell to draw
Definition at line 621 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aCell);
 }
template<typename Space , typename KSpace > template<typename TDigitalTopology , typename TDigitalSet > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::Object< TDigitalTopology, TDigitalSet > & anObject) inline static
Method to draw Object.
Parameters
viewer the viewer where to draw
anObject the object to draw
Definition at line 651 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, anObject);
 }
template<typename Space , typename KSpace > template<DGtal::Dimension dim, typename TComponent > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::PointVector< dim, TComponent > & aPoint) inline static
Method to draw PointVector.
Parameters
viewer the viewer where to draw
aPoint the point to draw
Definition at line 699 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aPoint);
 }
template<typename Space , typename KSpace > template<DGtal::Dimension dim, typename TComponent > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::PointVector< dim, TComponent > & aPoint, const DGtal::PointVector< dim, TComponent > & aPoint2) inline static
Method to draw PointVector.
Parameters
viewer the viewer where to draw
aPoint the point to draw
aPoint2 the point to draw
Definition at line 708 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aPoint, aPoint2);
 }
template<typename Space , typename KSpace > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const typename KSpace::SCell & aSCell) inline static
Method to draw SignedKhalimskyCell.
Parameters
viewer the viewer where to draw
aSCell the signed cell to draw
Definition at line 727 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aSCell);
 }
template<typename Space , typename KSpace > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::GridCurve< KSpace > & aGrid) inline static
Method to draw GridCurve.
Parameters
viewer the viewer where to draw
aGrid the grid to draw
Definition at line 737 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aGrid);
 }
template<typename Space , typename KSpace > template<typename TIterator, typename TSCell > void DGtal::Viewer3DFactory< Space, KSpace >::draw (DGtal::Viewer3D< Space, KSpace > & viewer, const DGtal::ConstRangeAdapter< TIterator, DGtal::DefaultFunctor, TSCell > & aRangeAdapter) inline static
Method to draw SCellsRange.
Parameters
viewer the viewer where to draw
aRangeAdapter the range adapter to draw
Definition at line 748 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aRangeAdapter);
 }
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator > static void DGtal::Viewer3DFactory< TSpace, TKSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToPoint< TKSpace >, typename TKSpace::Point > & aRangeAdapter) static
Method to draw PointsRange.
Parameters
viewer the viewer where to draw
aRangeAdapter the range adapter to draw
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator > static void DGtal::Viewer3DFactory< TSpace, TKSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::ConstRangeAdapter< TIterator, CanonicSCellEmbedder< TKSpace >, typename TKSpace::Space::RealPoint > & aRangeAdapter) static
Method to draw MidPointsRange.
Parameters
viewer the viewer where to draw
aRangeAdapter the range adapter to draw
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator > static void DGtal::Viewer3DFactory< TSpace, TKSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToArrow< TKSpace >, std::pair< typename TKSpace::Point, typename TKSpace::Vector > > & aRangeAdapter) static
Method to draw ArrowsRange.
Parameters
viewer the viewer where to draw
aRangeAdapter the range adapter to draw
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator > static void DGtal::Viewer3DFactory< TSpace, TKSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToInnerPoint< TKSpace >, typename TKSpace::Point > & aRangeAdapter) static
Method to draw InnerPointsRange.
Parameters
viewer the viewer where to draw
aRangeAdapter the range adapter to draw
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator > static void DGtal::Viewer3DFactory< TSpace, TKSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToOuterPoint< TKSpace >, typename TKSpace::Point > & aRangeAdapter) static
Method to draw OuterPointsRange.
Parameters
viewer the viewer where to draw
aRangeAdapter the range adapter to draw
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator > static void DGtal::Viewer3DFactory< TSpace, TKSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToIncidentPoints< TKSpace >, std::pair< typename TKSpace::Point, typename TKSpace::Point > > & aRangeAdapter) static
Method to draw IncidentPointsRange.
Parameters
viewer the viewer where to draw
aRangeAdapter the range adapter to draw
template<typename Space , typename KSpace > template<typename TValue> void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const ImageContainerBySTLVector< DGtal::Z2i::Domain, TValue > & anImage) inline static
Method to draw an 2D Image (ImageContainerBySTLVector).
Parameters
viewer the viewer where to draw
anImage the image to draw
Definition at line 246 of file Viewer3DFactory.ih.
 {
   drawImage2D(viewer, anImage, CastFunctor<unsigned int> (), Viewer3D<Space,KSpace>::GrayScaleMode);
 }
template<typename Space , typename KSpace > template<typename TValue> void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const ImageContainerBySTLMap< DGtal::Z2i::Domain, TValue > & anImage) inline static
Method to draw an 2D Image (ImageContainerBySTLMap).
Parameters
viewer the viewer where to draw
anImage the image to draw
Definition at line 258 of file Viewer3DFactory.ih.
 {
   drawImage2D(viewer, anImage, CastFunctor<unsigned int> (), anImage.myMode);
 }
template<typename Space , typename KSpace > template<typename TImageContainer, typename TFunctorD , typename TNewValue, typename TFunctorValue > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const ConstImageAdapter< TImageContainer, DGtal::Z2i::Domain, TFunctorD, TNewValue, TFunctorValue > & anImage) inline static
Method to draw an 2D Image (ConstImageAdapter).
Parameters
viewer the viewer where to draw
anImage the image to draw
Definition at line 293 of file Viewer3DFactory.ih.
 {
   drawImage2D(viewer, anImage, CastFunctor<unsigned int> (), Viewer3D<Space,KSpace>::GrayScaleMode );
 }
template<typename Space , typename KSpace > template<typename TImageContainer, typename TFunctorD , typename TNewValue, typename TFunctorValue , typename TFunctorValueVm1 > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const ImageAdapter< TImageContainer, DGtal::Z2i::Domain, TFunctorD, TNewValue, TFunctorValue, TFunctorValueVm1 > & anImage) inline static
Method to draw an 2D Image (ImageAdapter).
Parameters
viewer the viewer where to draw
anImage the image to draw
Definition at line 304 of file Viewer3DFactory.ih.
 {
   drawImage2D(viewer, anImage, CastFunctor<unsigned int> (), anImage.myMode);
 }
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TValue > static void DGtal::Viewer3DFactory< TSpace, TKSpace >::draw (Viewer3D< Space, KSpace > & viewer, const ImageContainerBySTLVector< DGtal::Z3i::Domain, TValue > & anImage) static
Method to draw an 3D Image (ImageContainerBySTLVector).
Parameters
viewer the viewer where to draw
anImage the image to draw
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TValue > static void DGtal::Viewer3DFactory< TSpace, TKSpace >::draw (Viewer3D< Space, KSpace > & viewer, const ImageContainerBySTLMap< DGtal::Z3i::Domain, TValue > & anImage) static
Method to draw an 3D Image (ImageContainerBySTLMap).
Parameters
viewer the viewer where to draw
anImage the image to draw
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TImageContainer , typename TFunctorD , typename TNewValue , typename TFunctorValue > static void DGtal::Viewer3DFactory< TSpace, TKSpace >::draw (Viewer3D< Space, KSpace > & viewer, const ConstImageAdapter< TImageContainer, DGtal::Z3i::Domain, TFunctorD, TNewValue, TFunctorValue > & anImage) static
Method to draw an 3D Image (ConstImageAdapter).
Parameters
viewer the viewer where to draw
anImage the image to draw
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TImageContainer , typename TFunctorD , typename TNewValue , typename TFunctorValue , typename TFunctorValueVm1 > static void DGtal::Viewer3DFactory< TSpace, TKSpace >::draw (Viewer3D< Space, KSpace > & viewer, const ImageAdapter< TImageContainer, DGtal::Z3i::Domain, TFunctorD, TNewValue, TFunctorValue, TFunctorValueVm1 > & anImage) static
Method to draw an 3D Image (ImageAdapter).
Parameters
viewer the viewer where to draw
anImage the image to draw
template<typename Space , typename KSpace > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::SetMode3D & aMode) inline static
Method to set a custom mode for 3d object
Parameters
viewer the viewer where to draw
aMode the mode to set
Definition at line 858 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aMode);
 }
template<typename Space , typename KSpace > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::CustomStyle3D & aStyle) inline static
Method to set a custom style for 3d object
Parameters
viewer the viewer where to draw
aStyle the style to set
Definition at line 866 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aStyle);
 }
template<typename Space , typename KSpace > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::CustomColors3D & aColor) inline static
Method to set a custom color for 3d object
Parameters
viewer the viewer where to draw
aColor the color to set
Definition at line 874 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aColor);
 }
template<typename Space , typename KSpace > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::ClippingPlane & aClipping) inline static
Method to add an clipping plane
Parameters
viewer the viewer where to draw
aClipping the clipping plane to draw
Definition at line 882 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aClipping);
 }
template<typename Space , typename KSpace > template<typename TImageType, typename TFunctor > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::AddTextureImage3DWithFunctor< TImageType, TFunctor, Space, KSpace > & aFunctor) static
Method to draw an TextureImage3D.
Parameters
viewer the viewer where to draw
aFunctor the functor to draw
Definition at line 81 of file Viewer3DFactory.ih.
References DGtal::AddTextureImage3DWithFunctor< TImageType, TFunctor, Space, KSpace >::my3DImage, DGtal::AddTextureImage3DWithFunctor< TImageType, TFunctor, Space, KSpace >::myFunctor, and DGtal::AddTextureImage3DWithFunctor< TImageType, TFunctor, Space, KSpace >::myMode.
 {
   drawImage3D(viewer, *anAddGS3D.my3DImage, anAddGS3D.myFunctor, anAddGS3D.myMode);
 }
template<typename Space , typename KSpace > template<typename TImageType, typename TFunctor > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::AddTextureImage2DWithFunctor< TImageType, TFunctor, Space, KSpace > & aFunctor) static
Method to draw an TextureImage2D.
Parameters
viewer the viewer where to draw
aFunctor the functor to draw
Definition at line 91 of file Viewer3DFactory.ih.
References DGtal::AddTextureImage2DWithFunctor< TImageType, TFunctor, Space, KSpace >::my2DImage, DGtal::AddTextureImage2DWithFunctor< TImageType, TFunctor, Space, KSpace >::myFunctor, and DGtal::AddTextureImage2DWithFunctor< TImageType, TFunctor, Space, KSpace >::myMode.
 {
   drawImage2D(viewer, *anAddGS2D.my2DImage, anAddGS2D.myFunctor, anAddGS2D.myMode);
 }
template<typename Space , typename KSpace > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::UpdateImagePosition< Space, KSpace > & anUpdate) inline static
Method to update the position of an image.
Parameters
viewer the viewer where to draw
anUpdate the update to set
Definition at line 100 of file Viewer3DFactory.ih.
References DGtal::UpdateImagePosition< Space, KSpace >::myIndex, DGtal::UpdateImagePosition< Space, KSpace >::myNewDirection, DGtal::UpdateImagePosition< Space, KSpace >::myPosXBottomLeft, DGtal::UpdateImagePosition< Space, KSpace >::myPosYBottomLeft, DGtal::UpdateImagePosition< Space, KSpace >::myPosZBottomLeft, and DGtal::Viewer3D< S, KS >::updateOrientationTextureImage().
 {
   viewer.updateOrientationTextureImage(anUpdate.myIndex, anUpdate.myPosXBottomLeft, anUpdate.myPosYBottomLeft,
                                        anUpdate.myPosZBottomLeft, anUpdate.myNewDirection);
 }
template<typename Space , typename KSpace > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::UpdateLastImagePosition< Space, KSpace > & anUpdate) inline static
Method to update the position of the last added image.
Parameters
viewer the viewer where to draw
anUpdate the update to set
Definition at line 109 of file Viewer3DFactory.ih.
References DGtal::Viewer3D< S, KS >::getCurrentGLImageNumber(), DGtal::UpdateLastImagePosition< Space, KSpace >::myNewDirection, DGtal::UpdateLastImagePosition< Space, KSpace >::myPosXBottomLeft, DGtal::UpdateLastImagePosition< Space, KSpace >::myPosYBottomLeft, DGtal::UpdateLastImagePosition< Space, KSpace >::myPosZBottomLeft, and DGtal::Viewer3D< S, KS >::updateOrientationTextureImage().
 {
   unsigned int index = viewer.getCurrentGLImageNumber()-1;
   viewer.updateOrientationTextureImage(index, anUpdate.myPosXBottomLeft, anUpdate.myPosYBottomLeft,
                                        anUpdate.myPosZBottomLeft, anUpdate.myNewDirection);
 }
template<typename Space , typename KSpace > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::UpdateImage3DEmbedding< Space, KSpace > & anUpdate) inline static
Method to modify 3D Image embedding.
Parameters
viewer the viewer where to draw
anUpdate the update to set
Definition at line 119 of file Viewer3DFactory.ih.
References DGtal::UpdateImage3DEmbedding< Space, KSpace >::myIndex, DGtal::UpdateImage3DEmbedding< Space, KSpace >::myNewPoint1, DGtal::UpdateImage3DEmbedding< Space, KSpace >::myNewPoint2, DGtal::UpdateImage3DEmbedding< Space, KSpace >::myNewPoint3, DGtal::UpdateImage3DEmbedding< Space, KSpace >::myNewPoint4, and DGtal::Viewer3D< S, KS >::updateEmbeddingTextureImage().
 {
   viewer.updateEmbeddingTextureImage(anUpdate.myIndex, anUpdate.myNewPoint1, anUpdate.myNewPoint2, anUpdate.myNewPoint3, anUpdate.myNewPoint4);
 }
template<typename Space , typename KSpace > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::Update2DDomainPosition< Space, KSpace > & anUpdate) inline static
Method to apply domain position change
Parameters
viewer the viewer where to draw
anUpdate the update to set
Definition at line 128 of file Viewer3DFactory.ih.
References DGtal::Update2DDomainPosition< Space, KSpace >::myIndex, DGtal::Update2DDomainPosition< Space, KSpace >::myNewDirection, DGtal::Update2DDomainPosition< Space, KSpace >::myPosXBottomLeft, DGtal::Update2DDomainPosition< Space, KSpace >::myPosYBottomLeft, DGtal::Update2DDomainPosition< Space, KSpace >::myPosZBottomLeft, and DGtal::Viewer3D< S, KS >::updateAn2DDomainOrientation().
 {
   viewer.updateAn2DDomainOrientation(anUpdate.myIndex, anUpdate.myPosXBottomLeft, anUpdate.myPosYBottomLeft,
                                      anUpdate.myPosZBottomLeft, anUpdate.myNewDirection);
 }
template<typename Space , typename KSpace > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::Translate2DDomain & anTranslation) inline static
Method to apply image translate.
Parameters
viewer the viewer where to draw
anTranslation the translation to apply
Definition at line 137 of file Viewer3DFactory.ih.
References DGtal::Translate2DDomain::myIndex, DGtal::Translate2DDomain::myTranslateX, DGtal::Translate2DDomain::myTranslateY, DGtal::Translate2DDomain::myTranslateZ, and DGtal::Viewer3D< S, KS >::translateAn2DDomain().
 {
   viewer.translateAn2DDomain(anTranslation.myIndex, anTranslation.myTranslateX, anTranslation.myTranslateY,
                              anTranslation.myTranslateZ);
 }
template<typename Space , typename KSpace > template<typename TImageType, typename TFunctor > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::UpdateImageData< TImageType, TFunctor > & anUpdate) static
Method to apply image data change.
Parameters
viewer the viewer where to draw
anUpdate the update to set
Definition at line 146 of file Viewer3DFactory.ih.
References DGtal::UpdateImageData< TImageType, TFunctor >::myFunctor, DGtal::UpdateImageData< TImageType, TFunctor >::myImage, DGtal::UpdateImageData< TImageType, TFunctor >::myIndex, DGtal::UpdateImageData< TImageType, TFunctor >::myRotationAngle, DGtal::UpdateImageData< TImageType, TFunctor >::myRotationDir, DGtal::UpdateImageData< TImageType, TFunctor >::myTranslateX, DGtal::UpdateImageData< TImageType, TFunctor >::myTranslateY, DGtal::UpdateImageData< TImageType, TFunctor >::myTranslateZ, and DGtal::Viewer3D< S, KS >::updateTextureImage().
 {
   viewer.updateTextureImage(anUpdate.myIndex, *(anUpdate.myImage), anUpdate.myFunctor, anUpdate.myTranslateX,
                             anUpdate.myTranslateY, anUpdate.myTranslateZ, anUpdate.myRotationAngle, anUpdate.myRotationDir);
 }
template<typename Space , typename KSpace > void DGtal::Viewer3DFactory< Space, KSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::TransformedSurfelPrism & aTransformedSurfelPrism) inline static
Method to draw TransformedSurfelPrism
Parameters
viewer the viewer where to draw
aTransformedSurfelPrism the transformed surfelprism to draw
Definition at line 891 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aTransformedSurfelPrism);
 }
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator> void DGtal::Viewer3DFactory< TSpace, TKSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToPoint< KSpace >, typename KSpace::Point > & aRangeAdapter) inline
Definition at line 760 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aRangeAdapter);
 }
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator> void DGtal::Viewer3DFactory< TSpace, TKSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::ConstRangeAdapter< TIterator, CanonicSCellEmbedder< KSpace >, typename KSpace::Space::RealPoint > & aRangeAdapter) inline
Definition at line 772 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aRangeAdapter);
 }
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator> void DGtal::Viewer3DFactory< TSpace, TKSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToArrow< KSpace >, std::pair< typename KSpace::Point, typename KSpace::Vector > > & aRangeAdapter) inline
Definition at line 784 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aRangeAdapter);
 }
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator> void DGtal::Viewer3DFactory< TSpace, TKSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToInnerPoint< KSpace >, typename KSpace::Point > & aRangeAdapter) inline
Definition at line 796 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aRangeAdapter);
 }
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator> void DGtal::Viewer3DFactory< TSpace, TKSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToOuterPoint< KSpace >, typename KSpace::Point > & aRangeAdapter) inline
Definition at line 808 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aRangeAdapter);
 }
template<typename TSpace = Z3i::Space, typename TKSpace = Z3i::KSpace> template<typename TIterator> void DGtal::Viewer3DFactory< TSpace, TKSpace >::draw (Viewer3D< Space, KSpace > & viewer, const DGtal::ConstRangeAdapter< TIterator, SCellToIncidentPoints< KSpace >, std::pair< typename KSpace::Point, typename KSpace::Point > > & aRangeAdapter) inline
Definition at line 820 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   DGtal::Display3DFactory<Space,KSpace>::draw( viewer, aRangeAdapter);
 }
template<typename Space , typename KSpace > template<typename TIterator , typename TInteger , int connectivity> void DGtal::Viewer3DFactory< Space, KSpace >::drawAsBalls (Viewer3D< Space, KSpace > & viewer, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > & arithm) inline static
Method to draw StandardDSS6Computer as Balls.
Parameters
viewer the viewer where to draw
arithm the arithm to draw
Definition at line 438 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsBalls().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsBalls(viewer, arithm);
 }
template<typename Space , typename KSpace > template<typename TIterator , typename TInteger , int connectivity> void DGtal::Viewer3DFactory< Space, KSpace >::drawAsBoundingBox (Viewer3D< Space, KSpace > & viewer, const DGtal::StandardDSS6Computer< TIterator, TInteger, connectivity > & arithm) inline static
Method to draw StandardDSS6Computer as BoundingBox.
Parameters
viewer the viewer where to draw
arithm the arithm to draw
Definition at line 447 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsBoundingBox().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsBoundingBox(viewer, arithm);
 }
template<typename Space , typename KSpace > template<typename SpaceDom > void DGtal::Viewer3DFactory< Space, KSpace >::drawAsBoundingBox (Viewer3D< Space, KSpace > & viewer, const DGtal::HyperRectDomain< SpaceDom > & aDomain) inline static
Method to draw HyperRectDomain as BoundingBox.
Parameters
viewer the viewer where to draw
aDomain the domain to draw
Definition at line 573 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsBoundingBox().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsBoundingBox( viewer, aDomain);
 }
template<typename Space , typename KSpace > template<typename TPoint > void DGtal::Viewer3DFactory< Space, KSpace >::drawAsFaces (Viewer3D< Space, KSpace > & viewer, const DGtal::Mesh< TPoint > & aMesh) inline static
Method to draw Mesh as faces.
Parameters
viewer the viewer where to draw
aMesh the mesh to draw
Definition at line 409 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsFaces().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsFaces( viewer, aMesh);
 }
template<typename Space , typename KSpace > template<typename Domain , typename Compare > void DGtal::Viewer3DFactory< Space, KSpace >::drawAsGrid (Viewer3D< Space, KSpace > & viewer, const DGtal::DigitalSetBySTLSet< Domain, Compare > & aSet) inline static
Method to draw DigitalSetBySTLSet as Grid.
Parameters
viewer the viewer where to draw
aSet the set to draw
Definition at line 495 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsGrid().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsGrid(viewer, aSet);
 }
template<typename Space , typename KSpace > template<typename Domain > void DGtal::Viewer3DFactory< Space, KSpace >::drawAsGrid (Viewer3D< Space, KSpace > & viewer, const DGtal::DigitalSetBySTLVector< Domain > & aSet) inline static
Method to draw DigitalSetBySTLVector as Grid.
Parameters
viewer the viewer where to draw
aSet the set to draw
Definition at line 543 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsGrid().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsGrid(viewer, aSet);
 }
template<typename Space , typename KSpace > template<typename SpaceDom > void DGtal::Viewer3DFactory< Space, KSpace >::drawAsGrid (Viewer3D< Space, KSpace > & viewer, const DGtal::HyperRectDomain< SpaceDom > & aDomain) inline static
Method to draw HyperRectDomain as grid.
Parameters
viewer the viewer where to draw
aDomain the domain to draw
Definition at line 582 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsGrid().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsGrid( viewer, aDomain);
 }
template<typename Space , typename KSpace > template<DGtal::Dimension dim, typename TComponent > void DGtal::Viewer3DFactory< Space, KSpace >::drawAsGrid (Viewer3D< Space, KSpace > & viewer, const DGtal::PointVector< dim, TComponent > & aPoint) inline static
Method to draw PointVector as Grid.
Parameters
viewer the viewer where to draw
aPoint the point to draw
Definition at line 672 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsGrid().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsGrid( viewer, aPoint);
 }
template<typename Space , typename KSpace > template<typename Domain , typename Compare > void DGtal::Viewer3DFactory< Space, KSpace >::drawAsPaving (Viewer3D< Space, KSpace > & viewer, const DGtal::DigitalSetBySTLSet< Domain, Compare > & aSet) inline static
Method to draw DigitalSetBySTLSet as Paving.
Parameters
viewer the viewer where to draw
aSet the set to draw
Definition at line 486 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPaving().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsPaving( viewer, aSet);
 }
template<typename Space , typename KSpace > template<typename Domain > void DGtal::Viewer3DFactory< Space, KSpace >::drawAsPaving (Viewer3D< Space, KSpace > & viewer, const DGtal::DigitalSetBySTLVector< Domain > & aSet) inline static
Method to draw DigitalSetBySTLVector as Paving.
Parameters
viewer the viewer where to draw
aSet the set to draw
Definition at line 534 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPaving().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsPaving( viewer, aSet);
 }
template<typename Space , typename KSpace > template<typename SpaceDom > void DGtal::Viewer3DFactory< Space, KSpace >::drawAsPaving (Viewer3D< Space, KSpace > & viewer, const DGtal::HyperRectDomain< SpaceDom > & aDomain) inline static
Method to draw HyperRectDomain with Paving mode.
Parameters
viewer the viewer where to draw
aDomain the domain to draw
Definition at line 600 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPaving().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsPaving( viewer, aDomain);
 }
template<typename Space , typename KSpace > template<DGtal::Dimension dim, typename TComponent > void DGtal::Viewer3DFactory< Space, KSpace >::drawAsPaving (Viewer3D< Space, KSpace > & viewer, const DGtal::PointVector< dim, TComponent > & aPoint) inline static
Method to draw PointVector as Paving.
Parameters
viewer the viewer where to draw
aPoint the point to draw
Definition at line 681 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPaving().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsPaving( viewer, aPoint);
 }
template<typename Space , typename KSpace > template<typename SpaceDom > void DGtal::Viewer3DFactory< Space, KSpace >::drawAsPavingBalls (Viewer3D< Space, KSpace > & viewer, const DGtal::HyperRectDomain< SpaceDom > & aDomain) inline static
Method to draw HyperRectDomain with Paving Balls.
Parameters
viewer the viewer where to draw
aDomain the domain to draw
Definition at line 591 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingBalls().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsPavingBalls( viewer, aDomain);
 }
template<typename Space , typename KSpace > template<typename Domain , typename Compare > void DGtal::Viewer3DFactory< Space, KSpace >::drawAsPavingTransparent (Viewer3D< Space, KSpace > & viewer, const DGtal::DigitalSetBySTLSet< Domain, Compare > & aSet) inline static
Method to draw DigitalSetBySTLSet as Paving Transparent.
Parameters
viewer the viewer where to draw
aSet the set to draw
Definition at line 477 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingTransparent().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsPavingTransparent(viewer, aSet);
 }
template<typename Space , typename KSpace > template<typename Domain > void DGtal::Viewer3DFactory< Space, KSpace >::drawAsPavingTransparent (Viewer3D< Space, KSpace > & viewer, const DGtal::DigitalSetBySTLVector< Domain > & aSet) inline static
Method to draw DigitalSetBySTLVector as Paving Transparent.
Parameters
viewer the viewer where to draw
aSet the set to draw
Definition at line 525 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingTransparent().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsPavingTransparent( viewer, aSet);
 }
template<typename Space , typename KSpace > template<DGtal::Dimension dim, typename TComponent > void DGtal::Viewer3DFactory< Space, KSpace >::drawAsPavingWired (Viewer3D< Space, KSpace > & viewer, const DGtal::PointVector< dim, TComponent > & aPoint) inline static
Method to draw PointVector as Paving Wired.
Parameters
viewer the viewer where to draw
aPoint the point to draw
Definition at line 690 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingWired().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawAsPavingWired( viewer, aPoint);
 }
template<typename Space , typename KSpace > template<typename TImageType2D , typename TFunctor > void DGtal::Viewer3DFactory< Space, KSpace >::drawImage2D (Viewer3D< Space, KSpace > & viewer, const TImageType2D & anImage, const TFunctor & aFunctor, typename Viewer3D< Space, KSpace >::TextureMode aTextureMode) inline static
Method to draw an 3D Image.
Parameters
viewer the viewer where to draw
anImage the image to draw
aFunctor the functor to draw
aTextureMode the mode of the texture to set
Definition at line 833 of file Viewer3DFactory.ih.
References DGtal::Viewer3D< S, KS >::addTextureImage(), DGtal::Viewer3D< S, KS >::getCurrentDomainNumber(), and DGtal::Display3D< Space, KSpace >::getMode().
 {
   std::string mode = viewer.getMode( anImage.className() );
   ASSERT( (mode=="BoundingBox" || mode=="InterGrid" || mode=="Grid"|| mode=="") ||
           ("DGtal::Display3DFactory<Space,KSpace>::draw( Display3D<Space, KSpace> & viewer,const TImageType2D & anImage ): Unknown mode "+mode)=="");
   if(mode=="")
     {
       typename Viewer3D<Space, KSpace>::TextureImage aGSImage(anImage, aFunctor,Viewer3D<Space, KSpace>::zDirection, 0,0,0, aTextureMode);
       viewer.addTextureImage(aGSImage);
     }else if(mode=="BoundingBox" || mode == "InterGrid" || mode == "Grid")
     {
       typename Viewer3D<Space, KSpace>::TextureImage aGSImage(anImage, aFunctor, Viewer3D<Space, KSpace>::zDirection, 0,0,0, aTextureMode);
       aGSImage.myDrawDomain = true;
       viewer << SetMode3D( anImage.domain().className(), mode );
       viewer << anImage.domain();
       aGSImage.myIndexDomain = viewer.getCurrentDomainNumber()-1;
       viewer.addTextureImage(aGSImage);
     }
 }
template<typename Space , typename KSpace > template<typename TImageType3D , typename TFunctor > void DGtal::Viewer3DFactory< Space, KSpace >::drawImage3D (Viewer3D< Space, KSpace > & viewer, const TImageType3D & anImage3D, const TFunctor & aFunctor, typename Viewer3D< Space, KSpace >::TextureMode aTextureMode) inline static
Method to draw an 2D Image.
Parameters
viewer the viewer where to draw
anImage3D the image to draw
aFunctor the functor to draw
aTextureMode the mode of the texture to set
Definition at line 156 of file Viewer3DFactory.ih.
References DGtal::Display3D< Space, KSpace >::getMode(), DGtal::Projector< S >::initAddOneDim(), and DGtal::Projector< S >::initRemoveOneDim().
 {
   std::string mode = viewer.getMode( anImage3D.className() );
   ASSERT( (mode=="BoundingBox" || mode=="InterGrid" || mode=="Grid"|| mode=="") ||
           ("DGtal::Viewer3DFactory<Space,KSpace>::draw( DViewer3D<Space, KSpace> & viewer,const TImageType3D & anImage ): Unknown mode "+mode)=="");
   typedef TImageType3D Image3D;
   DGtal::Projector<DGtal::Z2i::Space> invFunctorY; invFunctorY.initRemoveOneDim(1);
   DGtal::Z2i::Domain domainY(invFunctorY(anImage3D.domain().lowerBound()),
                              invFunctorY(anImage3D.domain().upperBound()));
   DGtal::Projector<DGtal::Z2i::Space> invFunctorZ; invFunctorZ.initRemoveOneDim(2);
   DGtal::Z2i::Domain domainZ(invFunctorZ(anImage3D.domain().lowerBound()),
                              invFunctorZ(anImage3D.domain().upperBound()));
   DGtal::Projector<DGtal::Z2i::Space> invFunctorX; invFunctorX.initRemoveOneDim(0);
   DGtal::Z2i::Domain domainX(invFunctorX(anImage3D.domain().lowerBound()),
                              invFunctorX(anImage3D.domain().upperBound()));
   typedef DGtal::ConstImageAdapter<Image3D, DGtal::Z2i::Domain, DGtal::Projector< Z3i::Space>,
                                    typename Image3D::Value, DGtal::DefaultFunctor > SliceImageAdapter;
   DGtal::DefaultFunctor idV;
   DGtal::Projector<DGtal::Z3i::Space> aSliceFunctorY((int)(anImage3D.domain().lowerBound()[1]));
   aSliceFunctorY.initAddOneDim(1);
   SliceImageAdapter sliceImageY(anImage3D, domainY, aSliceFunctorY, idV);
   viewer<< SetMode3D( sliceImageY.className(), mode );
   viewer << DGtal::AddTextureImage2DWithFunctor<SliceImageAdapter, TFunctor,Space, KSpace> (sliceImageY, aFunctor, aTextureMode );
   viewer << DGtal::UpdateLastImagePosition<Space, KSpace>( Viewer3D<Space, KSpace>::yDirection,
                                                            anImage3D.domain().lowerBound()[0],
                                                            anImage3D.domain().lowerBound()[1]-0.5,
                                                            anImage3D.domain().lowerBound()[2]);
   DGtal::Projector<DGtal::Z3i::Space> aSliceFunctorX((int)(anImage3D.domain().lowerBound()[0]));
   aSliceFunctorX.initAddOneDim(0);
   SliceImageAdapter sliceImageX(anImage3D, domainX, aSliceFunctorX, idV);
   viewer << DGtal::AddTextureImage2DWithFunctor<SliceImageAdapter, TFunctor , Space, KSpace> (sliceImageX, aFunctor, aTextureMode );
   viewer << DGtal::UpdateLastImagePosition<Space, KSpace> ( Viewer3D<Space, KSpace>::xDirection,
                                                             anImage3D.domain().lowerBound()[0] -0.5,
                                                             anImage3D.domain().lowerBound()[1],
                                                             anImage3D.domain().lowerBound()[2]);
   DGtal::Projector<DGtal::Z3i::Space> aSliceFunctorZ((int)(anImage3D.domain().lowerBound()[2]));
   aSliceFunctorZ.initAddOneDim(2);
   SliceImageAdapter sliceImageZ(anImage3D, domainZ, aSliceFunctorZ, idV);
   viewer << DGtal::AddTextureImage2DWithFunctor<SliceImageAdapter, TFunctor , Space, KSpace>(sliceImageZ, aFunctor, aTextureMode );
   viewer << DGtal::UpdateLastImagePosition<Space, KSpace> ( Viewer3D<Space, KSpace>::zDirection,
                                                             anImage3D.domain().lowerBound()[0],
                                                             anImage3D.domain().lowerBound()[1],
                                                             anImage3D.domain().lowerBound()[2]-0.5);
   // other symetrics faces
   DGtal::Projector<DGtal::Z3i::Space> aSliceFunctorYl((int)(anImage3D.domain().upperBound()[1]));
   aSliceFunctorYl.initAddOneDim(1);
   SliceImageAdapter sliceImageYl(anImage3D, domainY, aSliceFunctorYl, idV);
   viewer << DGtal::AddTextureImage2DWithFunctor<SliceImageAdapter, TFunctor , Space, KSpace>(sliceImageYl, aFunctor , aTextureMode);
   viewer << DGtal::UpdateLastImagePosition<Space, KSpace> ( Viewer3D<Space, KSpace>::yDirection,
                                                             anImage3D.domain().lowerBound()[0],
                                                             0.5+anImage3D.domain().upperBound()[1],
                                                             anImage3D.domain().lowerBound()[2]);
   DGtal::Projector<DGtal::Z3i::Space> aSliceFunctorXl((int)(anImage3D.domain().upperBound()[0]));
   aSliceFunctorXl.initAddOneDim(0);
   SliceImageAdapter sliceImageXl(anImage3D, domainX, aSliceFunctorXl, idV);
   viewer << DGtal::AddTextureImage2DWithFunctor<SliceImageAdapter, TFunctor, Space, KSpace>(sliceImageXl, aFunctor, aTextureMode );
   viewer << DGtal::UpdateLastImagePosition<Space, KSpace> ( Viewer3D<Space, KSpace>::xDirection,
                                                             0.5+anImage3D.domain().upperBound()[0],
                                                             anImage3D.domain().lowerBound()[1],
                                                             anImage3D.domain().lowerBound()[2] );
   DGtal::Projector<DGtal::Z3i::Space> aSliceFunctorZl((int)(anImage3D.domain().upperBound()[2]));
   aSliceFunctorZl.initAddOneDim(2);
   SliceImageAdapter sliceImageZl(anImage3D, domainZ, aSliceFunctorZl, idV);
   viewer << DGtal::AddTextureImage2DWithFunctor<SliceImageAdapter, TFunctor, Space, KSpace>(sliceImageZl, aFunctor , aTextureMode);
   viewer << DGtal::UpdateLastImagePosition<Space, KSpace>( Viewer3D<Space, KSpace>::zDirection,
                                                            anImage3D.domain().lowerBound()[0],
                                                            anImage3D.domain().lowerBound()[1],
                                                            0.5+ anImage3D.domain().upperBound()[2] );
 }
template<typename Space , typename KSpace > template<typename TDigitalTopology , typename TDigitalSet > void DGtal::Viewer3DFactory< Space, KSpace >::drawWithAdjacencies (Viewer3D< Space, KSpace > & viewer, const DGtal::Object< TDigitalTopology, TDigitalSet > & anObject) inline static
Method to draw Object with adjacency mode.
Parameters
viewer the viewer where to draw
anObject the object to draw
Definition at line 642 of file Viewer3DFactory.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::drawWithAdjacencies().
 {
   DGtal::Display3DFactory<Space,KSpace>::drawWithAdjacencies( viewer, anObject);
 }
The documentation for this struct was generated from the following files:
Viewer3DFactory.h
Viewer3DFactory.ih