DGtal: DGtal::CBinner< T > Struct Template Reference
DGtal::CBinner< T > Struct Template Reference
DGtal Concepts
#include <CBinner.h>
Public Types
typedef T::Quantity Quantity
typedef T::Bin Bin
Public Member Functions
BOOST_CONCEPT_ASSERT ((CEuclideanRing< Quantity >))
BOOST_STATIC_ASSERT ((boost::is_integral< Bin >::value))
BOOST_STATIC_ASSERT ((boost::is_unsigned< Bin >::value))
BOOST_CONCEPT_USAGE (CBinner)
void checkConstConstraints () const
Private Attributes
T myX
Quantity myQ
Bin myBin
T * myClone
Detailed Description
template<typename T>
struct DGtal::CBinner< T >
Aim: Represents an object that places a quantity into a bin, i.e. a functor that associates a natural integer to a continuous value.
Description of concept 'CBinner'
It is used for instance when computing an histogram over samples of a continuous random variable.
Refinement of boost::CopyConstructible
Associated types :
Quantity: the type of domain values (i.e. continuous values), a model of CEuclideanRing.
Bin: should be some unsigned integral type and satisfy boost::is_integral and boost::is_unsigned.
Notation
X : A type that is a model of CBinner
x, y : object of type X
Definitions
Valid expressions and semantics
| Name | Expression | Type requirements | Return type | Precondition | Semantics | Post condition | Complexity | |----—|---------—|----------------—|------------—|-----------—|--------—|-------------—|---------—| | construction | X(m, M, n) | m and M are Quantity, n is a Bin | | | | Constructs a binner with n bins and range from m to M | | | | apply | x(q) | q is a Quantity | Bin | | returns the bin in which fall q | | |
Invariants
Models
RegularBinner
Notes
Template Parameters
T the type that should be a model of CBinner.
Definition at line 96 of file CBinner.h.
Member Typedef Documentation
template<typename T > typedef T::Bin DGtal::CBinner< T >::Bin
Definition at line 101 of file CBinner.h.
template<typename T > typedef T::Quantity DGtal::CBinner< T >::Quantity
Definition at line 100 of file CBinner.h.
Member Function Documentation
template<typename T > DGtal::CBinner< T >::BOOST_CONCEPT_ASSERT ((CEuclideanRing< Quantity >))
template<typename T > DGtal::CBinner< T >::BOOST_CONCEPT_USAGE (CBinner< T >) inline
Definition at line 107 of file CBinner.h.
References DGtal::CBinner< T >::checkConstConstraints(), DGtal::CBinner< T >::myBin, DGtal::CBinner< T >::myClone, and DGtal::CBinner< T >::myQ.
   {
     myClone = new T( myQ, myQ, myBin );
     checkConstConstraints();
   }
template<typename T > DGtal::CBinner< T >::BOOST_STATIC_ASSERT ((boost::is_integral< Bin >::value))
template<typename T > DGtal::CBinner< T >::BOOST_STATIC_ASSERT ((boost::is_unsigned< Bin >::value))
template<typename T > void DGtal::CBinner< T >::checkConstConstraints () const inline
Definition at line 112 of file CBinner.h.
References DGtal::CBinner< T >::myBin, DGtal::CBinner< T >::myQ, DGtal::CBinner< T >::myX, and DGtal::ConceptUtils::sameType().
Referenced by DGtal::CBinner< T >::BOOST_CONCEPT_USAGE().
   {
     ConceptUtils::sameType( myBin, myX( myQ ) );
   }
Field Documentation
template<typename T > Bin DGtal::CBinner< T >::myBin private
Definition at line 120 of file CBinner.h.
Referenced by DGtal::CBinner< T >::BOOST_CONCEPT_USAGE(), and DGtal::CBinner< T >::checkConstConstraints().
template<typename T > T* DGtal::CBinner< T >::myClone private
Definition at line 121 of file CBinner.h.
Referenced by DGtal::CBinner< T >::BOOST_CONCEPT_USAGE().
template<typename T > Quantity DGtal::CBinner< T >::myQ private
Definition at line 119 of file CBinner.h.
Referenced by DGtal::CBinner< T >::BOOST_CONCEPT_USAGE(), and DGtal::CBinner< T >::checkConstConstraints().
template<typename T > T DGtal::CBinner< T >::myX private
Definition at line 118 of file CBinner.h.
Referenced by DGtal::CBinner< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CBinner.h