DGtal: DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency > Struct Template Reference
DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency > Struct Template Reference
#include <ArithmeticalDSLKernel.h>
Public Types
typedef SpaceND< 2, TCoordinate > Space
typedef Space::Vector Vector
typedef std::pair< Vector, Vector > Steps
Public Member Functions
template<typename TInteger >
DGtal::ArithmeticalDSLKernel
< TCoordinate, adjacency >
::Vector shift (const TInteger &a, const TInteger &b)
template<typename TInteger >
DGtal::ArithmeticalDSLKernel
< TCoordinate, adjacency >
::Steps steps (const TInteger &a, const TInteger &b)
Static Public Member Functions
template<typename TInteger >
static Vector shift (const TInteger &a, const TInteger &b)
template<typename TInteger >
static Steps steps (const TInteger &a, const TInteger &b)
template<typename TInteger >
static TInteger norm (const TInteger &a, const TInteger &b)
Static Public Attributes
static const unsigned short ForegroundAdjacency = 8
static const unsigned short BackgroundAdjacency = 4
Detailed Description
template<typename TCoordinate, unsigned short adjacency = 8>
struct DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency >
Aim: Small class that contains the code that depends on the arithmetical thickness (either naive or standard) of a digital straight line (DSL). It provides mainly two static methods:
ArithmeticalDSLKernel::shift that returns the shift vector of a DSL from its slope parameters \(a \) and \(b \). ie. the vector \(s \) translating a point of remainder \(r \) to a point of remainder \(r + \omega \)
ArithmeticalDSLKernel::steps that returns the step vectors of a DSL ie. the couple of vectors \(v \) and \(w \) used to iterate over the points of a DSL in an orientation given by the DSL parameters \(a \) and \(b \). Obviously, these two vectors are equal to 0 if \(\omega = 0 \) (not valid DSL). Moreover, the first vector (\(v \)) is equal to the direction vector, while the second one (\(w \)) is equal to 0, if \(\omega = 1 \), ie. if the lower leaning line and the upper leaning line are counfounded. Though, in the general case, the first vector (\(v \)) translates any point \(p \) of remainder \(r \) to its unique neighbor point \(q \) of remainder greater than or equal to \(r \), while the second one (\(w \)) is such that \(v - w = s \).
These methods are specialized with respect to the chosen adjacency 8 (default) or 4.
Digital straight lines and segments.
Template Parameters
TCoordinate a model of integer for the DGtal point coordinates
adjacency integer equal to 8 (default) for naive (simply 8-connected) DSL, and 4 for standard (simply 4-connected) DSL.
See Also
ArithmeticalDSL
exampleArithmeticalDSL.cpp
Definition at line 91 of file ArithmeticalDSLKernel.h.
Member Typedef Documentation
template<typename TCoordinate, unsigned short adjacency = 8> typedef SpaceND<2, TCoordinate> DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency >::Space
Type of the digital plane.
Definition at line 99 of file ArithmeticalDSLKernel.h.
template<typename TCoordinate, unsigned short adjacency = 8> typedef std::pair<Vector, Vector> DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency >::Steps
Type of the step vectors, defined as a STL pair of Vector
Definition at line 107 of file ArithmeticalDSLKernel.h.
template<typename TCoordinate, unsigned short adjacency = 8> typedef Space::Vector DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency >::Vector
Type of the shift vector.
Definition at line 103 of file ArithmeticalDSLKernel.h.
Member Function Documentation
template<typename TCoordinate , unsigned short adjacency> template<typename TInteger > TInteger DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency >::norm (const TInteger & a, const TInteger & b) inline static
Returns the \(L_{\infty} \) (for the 8-adjacency) or the \(L_1 \) norm (for the 4-adjacency) of two integers a and b,
Parameters
a a-parameter
b b-parameter
Template Parameters
TInteger a model of integer for the parameters a and b
Returns
the norm
Definition at line 222 of file ArithmeticalDSLKernel.ih.
Referenced by DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::isExtendableFront(), and DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::retractUpdateLeaningPoints().
 {
   if (b >= NumberTraits<TInteger>::ZERO)
     {
       if (a >= NumberTraits<TInteger>::ZERO)
         {
           if (b >= a)
             return b;
           else
             return a;
         }
       else
         {
           if (b >= -a)
             return b;
           else
             return -a;
         }
     }
   else
     {
       if (a >= NumberTraits<TInteger>::ZERO)
         {
           if (-b >= a)
             return -b;
           else
             return a;
         }
       else
         {
           if (-b >= -a)
             return -b;
           else
             return -a;
         }
     }
 }
template<typename TCoordinate, unsigned short adjacency = 8> template<typename TInteger > DGtal::ArithmeticalDSLKernel<TCoordinate,adjacency>::Vector DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency >::shift (const TInteger & a, const TInteger & b) inline
Definition at line 45 of file ArithmeticalDSLKernel.ih.
 {
   Vector res;
   if (b == NumberTraits<TInteger>::ZERO)
     {
       if (a == NumberTraits<TInteger>::ZERO)     //no octant
         res = Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ZERO);
       else if (a > NumberTraits<TInteger>::ZERO) //octant 2
         res = Vector(NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ZERO);
       else // (a < 0)                            //octant 6
         res = Vector(-NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ZERO);
     }
   else if (b > NumberTraits<TInteger>::ZERO)
     {
       if (a == NumberTraits<TInteger>::ZERO)     //octant 0
         res = Vector(NumberTraits<TCoordinate>::ZERO,-NumberTraits<TCoordinate>::ONE);
       else if (a > NumberTraits<TInteger>::ZERO)
         {
           if (b > a)                             //octant 0
             res = Vector(NumberTraits<TCoordinate>::ZERO,-NumberTraits<TCoordinate>::ONE);
           else                                   //octant 1
             res = Vector(NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ZERO);
         }
       else // (a < 0)
         {
           if (b >= -a)                           //octant 7
             res = Vector(NumberTraits<TCoordinate>::ZERO,-NumberTraits<TCoordinate>::ONE);
           else                                   //octant 6
             res = Vector(-NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ZERO);
         }
     }
   else // (b < 0)
     {
       if (a == NumberTraits<TInteger>::ZERO)      //octant 4
         res = Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ONE);
       else if (a > NumberTraits<TInteger>::ZERO)
         {
           if (-b >= a)                            //octant 3
             res = Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ONE);
           else                                    //octant 2
             res = Vector(NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ZERO);
         }
       else // (a < 0)
         {
           if (-b > -a)                            //octant 4
             res = Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ONE);
           else                                    //octant 5
             res = Vector(-NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ZERO);
         }
     }
   return res;
 }
template<typename TCoordinate, unsigned short adjacency = 8> template<typename TInteger > static Vector DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency >::shift (const TInteger & a, const TInteger & b) static
Given parameters a and b, this method computes the shift vector translating a point of remainder \(r \) to a point of remainder \(r + \omega \)
NB: The shift vector is set to (0,0) if \(\omega = 0 \), ie. a and b are both null.
NB: If (a , b) lies between two octants (resp. quadrants) (eg. b > 0 and a = 0), the shift vector of the next octant (resp. quadrant) is chosen with respect to the counter-clockwise orientation.
Parameters
a a-parameter
b b-parameter
Template Parameters
TInteger a model of integer for the parameters a and b
Returns
the shift vector
See Also
exampleArithmeticalDSL.cpp
Referenced by DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::extendFront(), and DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::retractUpdateParameters().
template<typename TCoordinate, unsigned short adjacency = 8> template<typename TInteger > DGtal::ArithmeticalDSLKernel<TCoordinate,adjacency>::Steps DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency >::steps (const TInteger & a, const TInteger & b) inline
Definition at line 104 of file ArithmeticalDSLKernel.ih.
 {
   Steps steps;
   if (b == NumberTraits<TInteger>::ZERO)
     {
       if (a == NumberTraits<TInteger>::ZERO)
         { //no octant
           steps.first = Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ZERO);
           steps.second = Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ZERO);
         }
       else if (a > NumberTraits<TInteger>::ZERO)
         { //octant 2
           steps.first = Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ONE);
           steps.second = Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ZERO);
         }
       else // (a < 0)
         { //octant 6
           steps.first = Vector(NumberTraits<TCoordinate>::ZERO,-NumberTraits<TCoordinate>::ONE);
           steps.second = Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ZERO);
         }
     }
   else if (b > NumberTraits<TInteger>::ZERO)
     {
       if (a == NumberTraits<TInteger>::ZERO)
         { //octant 0
           steps.first = Vector(NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ZERO);
           steps.second = Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ZERO);
         }
       else if (a > NumberTraits<TInteger>::ZERO)
         {
           if (b == a)
             {
               steps.first = Vector(NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ONE);
               steps.second = Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ZERO);
             }
           else if (b > a)
             { //octant 0
               steps.first = Vector(NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ZERO);
               steps.second = Vector(NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ONE);
             }
           else // (b < a)
             { //octant 1
               steps.second = Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ONE);
               steps.first = Vector(NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ONE);
             }
         }
       else //(a < 0)
         {
           if (b == -a)
             {
               steps.first = Vector(NumberTraits<TCoordinate>::ONE,-NumberTraits<TCoordinate>::ONE);
               steps.second = Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ZERO);
             }
           else if (b > -a)
             { //octant 7
               steps.second = Vector(NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ZERO);
               steps.first = Vector(NumberTraits<TCoordinate>::ONE,-NumberTraits<TCoordinate>::ONE);
             }
           else // (b < -a)
             { //octant 6
               steps.first = Vector(NumberTraits<TCoordinate>::ZERO,-NumberTraits<TCoordinate>::ONE);
               steps.second = Vector(NumberTraits<TCoordinate>::ONE,-NumberTraits<TCoordinate>::ONE);
             }
         }
     }
   else // (b < 0)
     {
       if (a == NumberTraits<TInteger>::ZERO)
         { //octant 4
           steps.first = Vector(-NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ZERO);
           steps.second = Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ZERO);
         }
       else if (a > NumberTraits<TInteger>::ZERO)
         {
           if (-b == a)
             {
               steps.first = Vector(-NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ONE);
               steps.second = Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ZERO);
             }
           else if (-b > a)
             { //octant 3
               steps.second = Vector(-NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ZERO);
               steps.first = Vector(-NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ONE);
             }
           else // (-b < a)
             { //octant 2
               steps.first = Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ONE);
               steps.second = Vector(-NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ONE);
             }
         }
       else // (a < 0)
         {
           if (-b == -a)
             {
               steps.first = Vector(-NumberTraits<TCoordinate>::ONE,-NumberTraits<TCoordinate>::ONE);
               steps.second = Vector(NumberTraits<TCoordinate>::ZERO,NumberTraits<TCoordinate>::ZERO);
             }
           else if (-b > -a)
             { //octant 4
               steps.first = Vector(-NumberTraits<TCoordinate>::ONE,NumberTraits<TCoordinate>::ZERO);
               steps.second = Vector(-NumberTraits<TCoordinate>::ONE,-NumberTraits<TCoordinate>::ONE);
             }
           else // (-b < -a)
             { //octant 5
               steps.second = Vector(NumberTraits<TCoordinate>::ZERO,-NumberTraits<TCoordinate>::ONE);
               steps.first = Vector(-NumberTraits<TCoordinate>::ONE,-NumberTraits<TCoordinate>::ONE);
             }
         }
     }
   return steps;
 }
template<typename TCoordinate, unsigned short adjacency = 8> template<typename TInteger > static Steps DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency >::steps (const TInteger & a, const TInteger & b) static
Given parameters a and b, this method returns the two step vectors, ie. the vectors that are used to iterate over the points of a DSL of slope a / b.
In the general case, the first vector \(v \) translates any point \(p \) of remainder \(r \) to its unique neighbor point \(q \) of remainder greater than or equal to \(r \), while the second one \(w \) is such that \(v - w = s \).
NB: The two vectors are set to (0,0) if \(\omega = 0 \), ie. a and b are both null.
NB: The second vector is set to (0,0) if \(\omega = 1 \), ie. if either a or b is null, if either a == b or either a == - b in the naive case.
Parameters
a a-parameter
b b-parameter
Template Parameters
TInteger a model of integer for the parameters a and b
Returns
the the pair of steps
See Also
exampleArithmeticalDSL.cpp
Referenced by DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::extendFront(), and DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::retractUpdateParameters().
Field Documentation
template<typename TCoordinate, unsigned short adjacency = 8> const unsigned short DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency >::BackgroundAdjacency = 4 static
Adjacency used for the complement
Definition at line 118 of file ArithmeticalDSLKernel.h.
template<typename TCoordinate, unsigned short adjacency = 8> const unsigned short DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency >::ForegroundAdjacency = 8 static
Adjacency used for the DSL
Definition at line 114 of file ArithmeticalDSLKernel.h.
The documentation for this struct was generated from the following files:
ArithmeticalDSLKernel.h
ArithmeticalDSLKernel.ih