DGtal: LibBoard::TransformSVG Struct Reference
LibBoard::TransformSVG Struct Reference
#include <Transforms.h>
Public Member Functions
double rounded (double x) const
double mapY (double y) const
double mapWidth (double width) const
void setBoundingBox (const Rect &rect, const double pageWidth, const double pageHeight, const double margin)
Public Member Functions inherited from LibBoard::Transform
Transform ()
virtual ~Transform ()
virtual double mapX (double x) const
virtual void apply (double &x, double &y) const
virtual double scale (double x) const
Additional Inherited Members
Static Public Member Functions inherited from LibBoard::Transform
static double round (const double &x)
Protected Attributes inherited from LibBoard::Transform
double _scale
double _deltaX
double _deltaY
double _height
Detailed Description
Structure representing a scaling and translation suitable for an SVG output.
The TransformSVG structure.
Definition at line 95 of file Transforms.h.
Member Function Documentation
double LibBoard::TransformSVG::mapWidth (double width) const
Definition at line 188 of file Transforms.cpp.
References LibBoard::Transform::round().
Referenced by LibBoard::Arrow::flushSVG(), LibBoard::Shape::svgProperties(), and LibBoard::Shape::tikzProperties().
 {
   // return Transform::round( 1000 * width / ppmm ) / 1000.0;
   return Transform::round( 1000 * width  / ppmm  ) / 1000.0;
 }
double LibBoard::TransformSVG::mapY (double y) const virtual
Implements LibBoard::Transform.
Definition at line 182 of file Transforms.cpp.
References LibBoard::Transform::_deltaY, LibBoard::Transform::_height, LibBoard::Transform::_scale, and rounded().
Referenced by LibBoard::Dot::flushSVG(), LibBoard::Line::flushSVG(), LibBoard::Arrow::flushSVG(), LibBoard::Rectangle::flushSVG(), LibBoard::Image::flushSVG(), LibBoard::Ellipse::flushSVG(), LibBoard::Circle::flushSVG(), LibBoard::Arc::flushSVG(), LibBoard::Text::flushSVG(), LibBoard::Path::flushSVGCommands(), LibBoard::Path::flushSVGPoints(), LibBoard::Line::flushTikZ(), LibBoard::Arrow::flushTikZ(), LibBoard::Image::flushTikZ(), LibBoard::Ellipse::flushTikZ(), LibBoard::Circle::flushTikZ(), LibBoard::Arc::flushTikZ(), LibBoard::Text::flushTikZ(), and LibBoard::Path::flushTikZPoints().
 {
   return rounded( _height - ( y * _scale + _deltaY ) );
 }
double LibBoard::TransformSVG::rounded (double x) const virtual
Reimplemented from LibBoard::Transform.
Definition at line 176 of file Transforms.cpp.
References LibBoard::Transform::round().
Referenced by mapY().
 {
   return Transform::round( 100*x ) / 100.0f;
 }
void LibBoard::TransformSVG::setBoundingBox (const Rect & rect, const double pageWidth, const double pageHeight, const double margin) virtual
Implements LibBoard::Transform.
Definition at line 195 of file Transforms.cpp.
References LibBoard::Transform::_deltaX, LibBoard::Transform::_deltaY, LibBoard::Transform::_height, LibBoard::Transform::_scale, LibBoard::Rect::height, LibBoard::Rect::left, LibBoard::Rect::top, and LibBoard::Rect::width.
Referenced by LibBoard::Board::saveSVG(), and LibBoard::Board::saveTikZ().
 {
   if ( pageWidth <= 0 || pageHeight <= 0 ) {
     _scale = 1.0f;
     // _deltaX = 0.5 * 210 * ppmm - ( rect.left + 0.5 * rect.width );
     _deltaX = - rect.left;
     // _deltaY = 0.5 * 297 * ppmm - ( rect.top - 0.5 * rect.height );
     _deltaY = - ( rect.top - rect.height );
     // _height = 297 * fig_ppmm;
     _height = rect.height;
   } else {
     const double w = pageWidth - 2 * margin;
     const double h = pageHeight - 2 * margin;
     if ( rect.height / rect.width > ( h / w ) ) {
       _scale = h * ppmm / rect.height;
     } else {
       _scale = w * ppmm / rect.width;
     }
     _deltaX = 0.5 * pageWidth * ppmm - _scale * ( rect.left + 0.5 * rect.width );
     _deltaY = 0.5 * pageHeight * ppmm - _scale * ( rect.top - 0.5 * rect.height );
     _height = pageHeight * ppmm;
   }
 }
The documentation for this struct was generated from the following files:
Transforms.h
Transforms.cpp