DGtal: DGtal::HDF5Reader< TImageContainer, TFunctor > Struct Template Reference
DGtal::HDF5Reader< TImageContainer, TFunctor > Struct Template Reference
#include <HDF5Reader.h>
Public Types
typedef TImageContainer ImageContainer
typedef TImageContainer OutputImage
typedef TImageContainer::Domain Domain
typedef
TImageContainer::Domain::Vector Vector
typedef TImageContainer::Value Value
typedef TFunctor Functor
Public Member Functions
BOOST_CONCEPT_ASSERT ((CImage< TImageContainer >))
BOOST_CONCEPT_ASSERT ((CUnaryFunctor< TFunctor, unsigned char, Value >))
BOOST_STATIC_ASSERT ((ImageContainer::Domain::dimension==2)||(ImageContainer::Domain::dimension==3))
Static Public Member Functions
static ImageContainer importHDF5 (const std::string &aFilename, const std::string &aDataset, const Functor &aFunctor=Functor(), bool topbotomOrder=true) throw (DGtal::IOException)
static ImageContainer importHDF5_3D (const std::string &aFilename, const std::string &aDataset, const Functor &aFunctor=Functor()) throw (DGtal::IOException)
Detailed Description
template<typename TImageContainer, typename TFunctor = CastFunctor< typename TImageContainer::Value >>
struct DGtal::HDF5Reader< TImageContainer, TFunctor >
Aim: Import a HDF5 file.
Description of class 'HDF5Reader'
Template Parameters
TImageContainer the image container to use.
TFunctor the type of functor used in the import (by default set to CastFunctor< TImageContainer::Value>).
Definition at line 62 of file HDF5Reader.h.
Member Typedef Documentation
template<typename TImageContainer , typename TFunctor = CastFunctor< typename TImageContainer::Value >> typedef TImageContainer::Domain DGtal::HDF5Reader< TImageContainer, TFunctor >::Domain
Definition at line 69 of file HDF5Reader.h.
template<typename TImageContainer , typename TFunctor = CastFunctor< typename TImageContainer::Value >> typedef TFunctor DGtal::HDF5Reader< TImageContainer, TFunctor >::Functor
Definition at line 72 of file HDF5Reader.h.
template<typename TImageContainer , typename TFunctor = CastFunctor< typename TImageContainer::Value >> typedef TImageContainer DGtal::HDF5Reader< TImageContainer, TFunctor >::ImageContainer
Definition at line 67 of file HDF5Reader.h.
template<typename TImageContainer , typename TFunctor = CastFunctor< typename TImageContainer::Value >> typedef TImageContainer DGtal::HDF5Reader< TImageContainer, TFunctor >::OutputImage
Definition at line 68 of file HDF5Reader.h.
template<typename TImageContainer , typename TFunctor = CastFunctor< typename TImageContainer::Value >> typedef TImageContainer::Value DGtal::HDF5Reader< TImageContainer, TFunctor >::Value
Definition at line 71 of file HDF5Reader.h.
template<typename TImageContainer , typename TFunctor = CastFunctor< typename TImageContainer::Value >> typedef TImageContainer::Domain::Vector DGtal::HDF5Reader< TImageContainer, TFunctor >::Vector
Definition at line 70 of file HDF5Reader.h.
Member Function Documentation
template<typename TImageContainer , typename TFunctor = CastFunctor< typename TImageContainer::Value >> DGtal::HDF5Reader< TImageContainer, TFunctor >::BOOST_CONCEPT_ASSERT ((CImage< TImageContainer >))
template<typename TImageContainer , typename TFunctor = CastFunctor< typename TImageContainer::Value >> DGtal::HDF5Reader< TImageContainer, TFunctor >::BOOST_CONCEPT_ASSERT ((CUnaryFunctor< TFunctor, unsigned char, Value >))
template<typename TImageContainer , typename TFunctor = CastFunctor< typename TImageContainer::Value >> DGtal::HDF5Reader< TImageContainer, TFunctor >::BOOST_STATIC_ASSERT ((ImageContainer::Domain::dimension==2)||(ImageContainer::Domain::dimension==3))
template<typename TImageContainer , typename TFunctor > TImageContainer DGtal::HDF5Reader< TImageContainer, TFunctor >::importHDF5 (const std::string & aFilename, const std::string & aDataset, const Functor & aFunctor = Functor(), bool topbotomOrder = true) throw (DGtal::IOException) inline static
Main method to import a HDF5 image file with 2D image dataset(s) (8-bit with palette and 24-bit truecolor with INTERLACE_PIXEL) into an instance of the template parameter ImageContainer.
Parameters
aFilename the file name to import.
aDataset the dataset name to import.
aFunctor the functor used to import and cast the source image values into the type of the image container value (by default set to CastFunctor < TImageContainer::Value >.
topbotomOrder if true, the point of coordinate (0,0) will be the bottom left corner image point (default) else the center of image coordinate will be the top left of the image (not usual).
Returns
an instance of the ImageContainer.
Definition at line 57 of file HDF5Reader.ih.
References DGtal::Trace::error(), and DGtal::trace.
Referenced by DGtal::GenericReader< TContainer, 2 >::importWithValueFunctor().
 {
   DGtal::IOException dgtalio;
   BOOST_STATIC_ASSERT( (ImageContainer::Domain::dimension == 2));
   hid_t         fileID;
   herr_t        hErrVal;
   hsize_t       width;
   hsize_t       height;
   hsize_t       planes;
   char          interlace[16];
   hssize_t      npals;
   unsigned char *imgBuf; // 'unsigned char' is mandated by the HDF5 library
   // Load the library -- not required on most platforms
   hErrVal = H5open();
   if (hErrVal < 0) { trace.error() << "HDF5 ERROR: " << std::endl; H5Eprint2(H5E_DEFAULT, stderr); throw dgtalio; }
   // Open an existing file
   fileID = H5Fopen(aFilename.c_str(), H5F_ACC_RDONLY, H5P_DEFAULT);
   if (fileID < 0) { trace.error() << "HDF5 ERROR: " << std::endl; H5Eprint2(H5E_DEFAULT, stderr); throw dgtalio; }
   // Figure out if the data is an image or not
   hErrVal = H5IMis_image(fileID, aDataset.c_str());
   if (hErrVal < 0) { trace.error() << "HDF5 ERROR: " << std::endl; H5Eprint2(H5E_DEFAULT, stderr); throw dgtalio; }
   if(hErrVal != 1) {
     trace.error() << "The data is NOT an image" << std::endl;
     throw dgtalio;
   }
   // Get info about the image
   interlace[0] = 0;
   hErrVal = H5IMget_image_info (fileID, aDataset.c_str(), &width, &height, &planes, interlace, &npals);
   if (hErrVal < 0) { trace.error() << "HDF5 ERROR: " << std::endl; H5Eprint2(H5E_DEFAULT, stderr); throw dgtalio; }
   // If the image is the wrong type, then throw exception
   if( !( ((planes==1) && (npals==1)) || ((planes==3) && (npals==0) && (strcmp(interlace, "INTERLACE_PIXEL")==0)) ) ) {
     trace.error() << "ERROR: Image is not 8-bit with palette or image is not 24-bit truecolor with INTERLACE_PIXEL pixel layout" << std::endl;
     throw dgtalio;
   }
   // Allocate space for the image
   imgBuf = (unsigned char*) malloc (width * height * planes * sizeof( unsigned char ));
   if (imgBuf == NULL) {
     trace.error() << "ERROR: Could not allocate space for image" << std::endl;
     throw dgtalio;
   }
   // Read the data from the file
   hErrVal = H5IMread_image (fileID, aDataset.c_str(), imgBuf);
   if (hErrVal < 0) { trace.error() << "HDF5 ERROR: " << std::endl; H5Eprint2(H5E_DEFAULT, stderr); throw dgtalio; }
   // Close the file
   hErrVal = H5Fclose(fileID);
   if (hErrVal < 0) { trace.error() << "HDF5 ERROR: " << std::endl; H5Eprint2(H5E_DEFAULT, stderr); throw dgtalio; }
   // Unload the library and free any remaining resources
   hErrVal = H5close();
   if (hErrVal < 0) { trace.error() << "HDF5 ERROR: " << std::endl; H5Eprint2(H5E_DEFAULT, stderr); throw dgtalio; }
   // --
   typename TImageContainer::Point firstPoint;
   typename TImageContainer::Point lastPoint;
   firstPoint = TImageContainer::Point::zero;
   lastPoint[0] = width-1;
   lastPoint[1] = height-1;
   typename TImageContainer::Domain domain(firstPoint,lastPoint);
   TImageContainer image(domain);
   for(hsize_t y=0; y<height; y++)
     for(hsize_t x=0; x<width; x++)
       {
           typename TImageContainer::Point pt;
           if (topbotomOrder){
             pt[0]=x; pt[1]=height-1-y;
           }else{
             pt[0]=x; pt[1]=y;
           }
           if( ((planes==1) && (npals==1)) )
             image.setValue(pt, aFunctor(imgBuf[ y*width+x ]));
           else if( ((planes==3) && (npals==0) && (strcmp(interlace, "INTERLACE_PIXEL")==0)) )
             image.setValue(pt, aFunctor(imgBuf[ ( (y*planes*width+x*planes)+(y*planes*width+x*planes+1)+(y*planes*width+x*planes+2) )/3 ]));
       }
   free(imgBuf);
   return image;
 }
template<typename TImageContainer , typename TFunctor = CastFunctor< typename TImageContainer::Value >> TImageContainer DGtal::HDF5Reader< TImageContainer, TFunctor >::importHDF5_3D (const std::string & aFilename, const std::string & aDataset, const Functor & aFunctor = Functor()) throw (DGtal::IOException) inline static
Main method to import a HDF5 image file with 3D UInt8 image dataset(s) into an instance of the template parameter ImageContainer.
Parameters
aFilename the file name to import.
aDataset the dataset name to import.
aFunctor the functor used to import and cast the source image values into the type of the image container value (by default set to CastFunctor < TImageContainer::Value >.
Returns
an instance of the ImageContainer.
Definition at line 155 of file HDF5Reader.ih.
References DGtal::Trace::error(), and DGtal::trace.
Referenced by DGtal::GenericReader< TContainer, 3 >::importWithValueFunctor().
 {
   DGtal::IOException dgtalio;
   BOOST_STATIC_ASSERT( (ImageContainer::Domain::dimension == 3));
   const int ddim = ImageContainer::Domain::dimension;
   // image domain
   Domain *myDomain;
   Domain aDomain;
   // HDF5 handles
   hid_t file, dataset;
   hid_t datatype, dataspace;
   hsize_t dims_out[ddim];              // dataset dimensions
   // Open the file and the dataset.
   file = H5Fopen(aFilename.c_str(), H5F_ACC_RDWR, H5P_DEFAULT);
   dataset = H5Dopen2(file, aDataset.c_str(), H5P_DEFAULT);
   // Get datatype and dataspace handles and then query dataset class, order, size, rank and dimensions.
   datatype = H5Dget_type(dataset); // datatype handle
   dataspace = H5Dget_space(dataset); // dataspace handle
   H5Sget_simple_extent_dims(dataspace, dims_out, NULL);
   // --
   typedef SpaceND<ddim> TSpace;
   typename TSpace::Point low, up;
   typename Domain::Integer d;
   for(d=0; d<ddim; d++)
   {
     low[d]=0;
     up[d]=dims_out[ddim-d-1]-1;
   }
   myDomain = new Domain(low, up);
   aDomain = *myDomain;          // because here we want the full image
   /* - reading HDF5- */
   hsize_t offset[ddim];        // hyperslab offset in the file
   hsize_t count[ddim];         // size of the hyperslab in the file
   herr_t status;
   hsize_t dimsm[ddim];         // memory space dimensions
   hid_t memspace;
   hsize_t offset_out[ddim];    // hyperslab offset in memory
   hsize_t count_out[ddim];     // size of the hyperslab in memory
   //int i[ddim];
   int N_SUB[ddim];
   int malloc_size=1;
   for(d=0; d<ddim; d++)
   {
     N_SUB[d] = (aDomain.upperBound()[ddim-d-1]-aDomain.lowerBound()[ddim-d-1])+1;
     malloc_size = malloc_size*N_SUB[d];
   }
   Value *data_out = (Value*) malloc (malloc_size * sizeof(Value)); // output buffer
   if (data_out == NULL)
   {
     trace.error() << "data_out malloc error in importHDF5_3D: " << (malloc_size * sizeof(Value)) << std::endl;
     throw dgtalio;
   }
   // Define hyperslab in the dataset.
   for(d=0; d<ddim; d++)
     offset[d] = aDomain.lowerBound()[ddim-d-1]-myDomain->lowerBound()[ddim-d-1];
   for(d=0; d<ddim; d++)
     count[d] = N_SUB[d];
   status = H5Sselect_hyperslab(dataspace, H5S_SELECT_SET, offset, NULL, count, NULL);
   if (status)
   {
     trace.error() << " H5Sselect_hyperslab from dataspace error" << std::endl;
     throw dgtalio;
   }
   // Define the memory dataspace.
   for(d=0; d<ddim; d++)
     dimsm[d] = N_SUB[d];
   memspace = H5Screate_simple(ddim,dimsm,NULL);
   // Define memory hyperslab.
   for(d=0; d<ddim; d++)
     offset_out[d] = 0;
   for(d=0; d<ddim; d++)
     count_out[d] = N_SUB[d];
   status = H5Sselect_hyperslab(memspace, H5S_SELECT_SET, offset_out, NULL, count_out, NULL);
   if (status)
   {
     trace.error() << " H5Sselect_hyperslab from memspace error" << std::endl;
     throw dgtalio;
   }
   // Read data from hyperslab in the file into the hyperslab in memory.
   status = H5Dread(dataset, H5T_NATIVE_UINT8, memspace, dataspace, H5P_DEFAULT, data_out);
   if (status)
   {
     trace.error() << " H5Dread error" << std::endl;
     throw dgtalio;
   }
   OutputImage outputImage(aDomain);
   typedef SpaceND<ddim> TSpace;
   typename TSpace::Point a, b;
   for(d=0; d<ddim; d++)
   {
     a[d]=offset[ddim-d-1]+myDomain->lowerBound()[d];
     b[d]=a[d]+N_SUB[ddim-d-1]-1;
   }
   HyperRectDomain<TSpace> domain(a,b);
   /*std::vector<typename TSpace::Dimension> v(ddim);
   for(d=0; d<ddim; d++)
     v[d]=d;*/
   int p=0;
   for( typename HyperRectDomain<TSpace>/*::ConstSubRange*/::ConstIterator
         it = domain/*.subRange(v, a)*/.begin(), itend = domain/*.subRange(v, a)*/.end();
       it != itend;
       ++it)
   {
     outputImage.setValue((*it), data_out[ p++ ]);
   }
   H5Sclose(memspace);
   free(data_out);
   /* - reading HDF5- */
   delete myDomain;
   // Close/release resources.
   H5Tclose(datatype);
   H5Dclose(dataset);
   H5Sclose(dataspace);
   H5Fclose(file);
   return outputImage;
 }
The documentation for this struct was generated from the following files:
HDF5Reader.h
HDF5Reader.ih