DGtal: DGtal::Display3D< Space, KSpace > Class Template Reference
DGtal::Display3D< Space, KSpace > Class Template Reference
DGtal Concepts
#include <base/Common.h>
Data Structures
struct BallD3D
struct ClippingPlaneD3D
struct CubeD3D
struct LineD3D
struct PolygonD3D
struct QuadD3D
struct TriangleD3D
Public Types
enum StreamKey { addNewList, updateDisplay, shiftSurfelVisu }
typedef Display3D< Space, KSpace > Self
typedef Space::RealPoint RealPoint
typedef Space::RealVector RealVector
typedef CanonicEmbedder< Space > Embedder
typedef CanonicCellEmbedder
< KSpace > CellEmbedder
typedef CanonicSCellEmbedder
< KSpace > SCellEmbedder
typedef std::map< std::string,
std::string > ModeMapping
typedef std::map< std::string,
CountedPtr
< DrawableWithDisplay3D > > StyleMapping
Public Member Functions
BOOST_CONCEPT_ASSERT ((CSpace< Space >))
~Display3D ()
Display3D ()
Display3D (const KSpace &KSEmb)
Display3D (const Space &Semb, const KSpace &KSEmb)
const Embedder & embedder () const
const CellEmbedder & cellEmbedder () const
const SCellEmbedder & sCellEmbedder () const
const KSpace & space () const
virtual void setFillColor (DGtal::Color aColor)
virtual void setFillTransparency (unsigned char alpha)
virtual void setLineColor (DGtal::Color aColor)
virtual DGtal::Color getFillColor ()
virtual DGtal::Color getLineColor ()
virtual void setSpaceEmbedder (Embedder *anEmbedder)
virtual void setKSpaceEmbedder (CellEmbedder *anEmbedder)
virtual void setSKSpaceEmbedder (SCellEmbedder *anEmbedder)
void addClippingPlane (double a, double b, double c, double d, bool drawPlane)
std::string getMode (const std::string &objectName) const
void createNewLineList (std::string s="")
void createNewBallList (std::string s="")
void createNewCubeList (std::string s="")
void createNewQuadList (std::string s="")
void createNewTriangleList (std::string s="")
void createNewPolygonList (std::string s="")
void addQuad (const RealPoint &p1, const RealPoint &p2, const RealPoint &p3, const RealPoint &p4)
void addQuadWithNormal (const RealPoint &p1, const RealPoint &p2, const RealPoint &p3, const RealPoint &p4, const RealPoint &n, const bool enableReorientation, const bool enableDoubleFace=false)
void addQuadFromSurfelCenter (const RealPoint &baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel)
void addQuadFromSurfelCenterWithNormal (const RealPoint &baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel, const RealVector &aNormal, const bool enableReorientation, const bool sign, const bool enableDoubleFace=false)
void addTriangle (const RealPoint &p1, const RealPoint &p2, const RealPoint &p3)
void addPolygon (const std::vector< RealPoint > &vertices)
void addLine (const RealPoint &p1, const RealPoint &p2, const double width=0.03)
void addCube (const RealPoint &center, double width=1.0)
void addBall (const RealPoint &center, double size=0.05)
void addPrism (const RealPoint &baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel, double sizeShiftFactor, double sizeFactor=1.0, bool isSigned=false, bool aSign=true)
void addBasicSurfel (const RealPoint &baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel)
void addCone (const RealPoint &p1, const RealPoint &p2, double width=0.02)
void addCylinder (const RealPoint &p1, const RealPoint &p2, const double width=0.02)
void updateBoundingBox (const RealPoint &point)
void exportToMesh (Mesh< Display3D::BallD3D > &aMesh) const
template<typename TDrawableWithDisplay3D >
Display3D & operator<< (const TDrawableWithDisplay3D &object)
void selfDisplay (std::ostream &out) const
bool isValid () const
void clear ()
RealPoint embed (const typename Space::Point &dp) const
RealPoint embedKS (const typename KSpace::SCell &cell) const
RealPoint embedKS (const DGtal::TransformedPrism &aTrans) const
RealPoint embedK (const typename KSpace::Cell &cell) const
template<typename TDrawableWithDisplay3D >
DGtal::Display3D< Space,KSpace > & operator<< (const TDrawableWithDisplay3D &object)
Data Fields
ModeMapping myModes
StyleMapping myStyles
bool myBoundingPtEmptyTag
double myBoundingPtUp [3]
double myBoundingPtLow [3]
Static Protected Member Functions
static void cross (double dst[3], double srcA[3], double srcB[3])
static void normalize (double vec[3])
Protected Attributes
Embedder * myEmbedder
CellEmbedder * myCellEmbedder
SCellEmbedder * mySCellEmbedder
DGtal::Color myCurrentFillColor
DGtal::Color myCurrentLineColor
double myCurrentfShiftVisuPrisms
std::vector< std::vector
< CubeD3D > > myCubeSetList
std::vector< std::vector
< LineD3D > > myLineSetList
std::vector< std::vector
< BallD3D > > myBallSetList
std::vector< ClippingPlaneD3D > myClippingPlaneList
std::vector< QuadD3D > myPrismList
std::vector< std::vector
< QuadD3D > > myQuadSetList
std::vector< std::vector
< TriangleD3D > > myTriangleSetList
std::vector< std::vector
< PolygonD3D > > myPolygonSetList
std::vector< std::string > myCubeSetNameList
std::vector< std::string > myLineSetNameList
std::vector< std::string > myBallSetNameList
std::vector< std::string > myClippingPlaneNameList
std::vector< std::string > myPrismNameList
std::vector< std::string > myQuadSetNameList
std::vector< std::string > myTriangleSetNameList
std::vector< std::string > myPolygonSetNameList
Private Member Functions
Display3D (const Display3D &other)
Display3D & operator= (const Display3D &other)
Detailed Description
template<class Space, class KSpace>
class DGtal::Display3D< Space, KSpace >
Aim: The concept CDrawableWithDisplay3D specifies what are the classes that admit an export with Display3D.
Aim: This semi abstract class defines the stream mechanism to display 3d primitive (like BallVector, DigitalSetBySTLSet, Object ...). The class Viewer3D and Board3DTo2D implement two different ways to display 3D objects. The first one (Viewer3D), permits an interactive visualisation (based on OpenGL) and the second one (Board3dto2d) provides 3D visualisation from 2D vectorial display (based on the CAIRO library)
Description of concept 'CDrawableWithDisplay3D'
An object x satisfying this concept may then be used as:
Display3D display;
display << CustomStyle(x.className(), x.defaultStyle())
      << x;
Refinement of
Associated types :
Notation
X : A type that is a model of CDrawableWithDisplay3DD
x, y : Object of type X
m : a string of characters
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
the default draw style x.defaultStyle(m = "") mode m: std::string CDrawableWithDisplay3D returns a dynamic allocation of the default style for the model X in mode m
the name of the model X x.className() std::string returns a string telling the name of the model X
the way the object x is drawn x.setStyle(CDrawableWithDisplay3D &display) draws the object x on the display stream
Invariants
Models
ArimeticalDSS, FreemanChain, HyperRectDomain, ImageContainerByHashTree, ImageContainerBySTLVector, PointVector, DigitalSetBySTLSet,DigitalSetBySTLVector, Object
Notes
Todo:
ImageContainerByHashTree does not implement setStyle(display &).
ImageContainerByHashTree does not implement defaultStyle(std::string&)const.
Description of class 'Display3D'
See also
Viewer3D, Board3DTo2D
This class is parametrized by both the Digital and Khalimsky space used to display object. More precisely, embed methods are used to compute the Euclidean coordinate of digital obejects/khalimksy cells.
Template Parameters
Space any model of Digital 3D Space
KSpace any mode of Khalimksky 3D space
Examples:
io/display3DToOFF.cpp.
Definition at line 145 of file src/DGtal/base/Common.h.
Member Typedef Documentation
template<class Space, class KSpace> typedef CanonicCellEmbedder<KSpace> DGtal::Display3D< Space, KSpace >::CellEmbedder
Definition at line 105 of file Display3D.h.
template<class Space, class KSpace> typedef CanonicEmbedder<Space> DGtal::Display3D< Space, KSpace >::Embedder
Definition at line 104 of file Display3D.h.
template<class Space, class KSpace> typedef std::map< std::string, std::string > DGtal::Display3D< Space, KSpace >::ModeMapping
The associated map type for storing possible modes used for displaying for digital objects.
Definition at line 728 of file Display3D.h.
template<class Space, class KSpace> typedef Space::RealPoint DGtal::Display3D< Space, KSpace >::RealPoint
RealPoint type.
Definition at line 101 of file Display3D.h.
template<class Space, class KSpace> typedef Space::RealVector DGtal::Display3D< Space, KSpace >::RealVector
RealVector type.
Definition at line 103 of file Display3D.h.
template<class Space, class KSpace> typedef CanonicSCellEmbedder<KSpace> DGtal::Display3D< Space, KSpace >::SCellEmbedder
Definition at line 106 of file Display3D.h.
template<class Space, class KSpace> typedef Display3D<Space,KSpace> DGtal::Display3D< Space, KSpace >::Self
Definition at line 99 of file Display3D.h.
template<class Space, class KSpace> typedef std::map< std::string,CountedPtr<DrawableWithDisplay3D> > DGtal::Display3D< Space, KSpace >::StyleMapping
The associated map type for storing the default styles of digital objects.
Definition at line 734 of file Display3D.h.
Member Enumeration Documentation
template<class Space, class KSpace> enum DGtal::Display3D::StreamKey
Enumerator
addNewList
updateDisplay
shiftSurfelVisu
Definition at line 218 of file Display3D.h.
 {addNewList, updateDisplay, shiftSurfelVisu};
Constructor & Destructor Documentation
template<class Space, class KSpace> DGtal::Display3D< Space, KSpace >::~Display3D () inline
Destructor.
Definition at line 239 of file Display3D.h.
     {
       delete myEmbedder;
       delete mySCellEmbedder;
       delete myCellEmbedder;
     };
template<class Space, class KSpace> DGtal::Display3D< Space, KSpace >::Display3D () inline
default constructor Display3D
Definition at line 250 of file Display3D.h.
     {
       myCurrentFillColor = Color ( 220, 220, 220 );
       myCurrentLineColor = Color ( 22, 22, 222, 50 );
       myBoundingPtEmptyTag = true;
       myEmbedder= new Embedder();
       myCellEmbedder = new CellEmbedder();
       mySCellEmbedder = new SCellEmbedder();
     }
template<class Space, class KSpace> DGtal::Display3D< Space, KSpace >::Display3D (const KSpace & KSEmb) inline
constructor with the Khalimsky Space
Parameters
KSEmb the khalimsky space for embedding
Definition at line 265 of file Display3D.h.
     {
       myCurrentFillColor = Color ( 220, 220, 220 );
       myCurrentLineColor = Color ( 22, 22, 222, 50 );
       myBoundingPtEmptyTag = true;
       myEmbedder= new Embedder();
       myCellEmbedder = new CellEmbedder(KSEmb);
       mySCellEmbedder = new SCellEmbedder(KSEmb);
     };
template<class Space, class KSpace> DGtal::Display3D< Space, KSpace >::Display3D (const Space & Semb, const KSpace & KSEmb) inline
constructor with the Space and the Khalimsky Space
Parameters
Semb the space for embedding
KSEmb the khalimsky space for embedding
Definition at line 280 of file Display3D.h.
     {
       myCurrentFillColor = Color ( 220, 220, 220 );
       myCurrentLineColor = Color ( 22, 22, 222, 50 );
       myBoundingPtEmptyTag = true;
       myEmbedder = new Embedder(Semb);
       myCellEmbedder = new CellEmbedder(KSEmb);
       mySCellEmbedder = new SCellEmbedder(KSEmb);
     };
template<class Space, class KSpace> DGtal::Display3D< Space, KSpace >::Display3D (const Display3D< Space, KSpace > & other) private
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
Member Function Documentation
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::addBall (const RealPoint & center, double size = 0.05) inline
Method to add a point to the current display.
Parameters
center ball center x
size the point width
Definition at line 218 of file Display3D.ih.
References DGtal::Display3D< Space, KSpace >::BallD3D::center, DGtal::Display3D< Space, KSpace >::BallD3D::color, DGtal::Display3D< Space, KSpace >::BallD3D::isSigned, DGtal::Display3D< Space, KSpace >::BallD3D::signPos, and DGtal::Display3D< Space, KSpace >::BallD3D::size.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsGrid(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingBalls().
 {
   updateBoundingBox(center);
   BallD3D p;
   p.center=center;
   p.color = getFillColor();
   p.isSigned=false;
   p.signPos=false;
   p.size=size;
   if (myBallSetList.size()== 0)
     createNewBallList("Ball Root");
   (myBallSetList.at(myBallSetList.size()-1)).push_back(p);
 }
template<class Space, class KSpace> void DGtal::Display3D< Space, KSpace >::addBasicSurfel (const RealPoint & baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel)
Specific to display a surfel from Kahlimsky space from a basic way.
Parameters
baseQuadCenter base quad center point
xSurfel true if the surfel has its main face in the direction of the x-axis
ySurfel true if the surfel has its main face in the direction of the y-axis
zSurfel true if the surfel has its main face in the direction of the z-axis
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::addClippingPlane (double a, double b, double c, double d, bool drawPlane) inline
Add a new 3D Clipping plane represented by ax+by+cz+d = 0 A maximal of five clipping plane can be added.
Parameters
a a
b b
c c
d d plane equation.
drawPlane true if the plane should be draw
Definition at line 1005 of file Display3D.ih.
References DGtal::Display3D< Space, KSpace >::ClippingPlaneD3D::a, DGtal::Display3D< Space, KSpace >::ClippingPlaneD3D::b, DGtal::Display3D< Space, KSpace >::ClippingPlaneD3D::c, and DGtal::Display3D< Space, KSpace >::ClippingPlaneD3D::d.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   ClippingPlaneD3D cp;
   cp.a=a; cp.b=b; cp.c=c; cp.d=d;
   myClippingPlaneList.push_back(cp);
   if(drawPlane)
     {
       double x1,x2,x3,x4;
       double y1,y2,y3,y4;
       double z1,z2,z3,z4;
       double norm = sqrt(a*a+b*b+c*c);
       double dec=0.1;
       // Z dominant projection of the upper face
       if(abs(c)>=abs(b) && abs(c) >= abs(a))
         {
           x1= myBoundingPtUp[0]+a*dec/norm; y1= myBoundingPtUp[1]+b*dec/norm;
           z1 = c*dec/norm +(-d-a*myBoundingPtUp[0]-b*myBoundingPtUp[1])/c;
           x2= myBoundingPtLow[0]+a*dec/norm; y2= myBoundingPtUp[1]+b*dec/norm;
           z2= c*dec/norm+(-d-a*myBoundingPtLow[0]-b*myBoundingPtUp[1])/c;
           x3= myBoundingPtLow[0]+a*dec/norm; y3= myBoundingPtLow[1]+b*dec/norm;
           z3= c*dec/norm+(-d-a*myBoundingPtLow[0]-b*myBoundingPtLow[1])/c;
           x4= myBoundingPtUp[0]+a*dec/norm; y4= myBoundingPtLow[1]+b*dec/norm;
           z4= c*dec/norm+(-d-a*myBoundingPtUp[0]-b*myBoundingPtLow[1])/c;
           if(c>0)
             {
               addQuad(RealPoint(x4,y4,z4),RealPoint(x3,y3,z3),
                       RealPoint(x2,y2,z2),RealPoint(x1,y1,z1) );
             }else
             {
               addQuad(RealPoint(x1,y1,z1), RealPoint( x2,y2,z2),
                       RealPoint(x3,y3,z3), RealPoint(x4,y4,z4));
             }
         }// Y dominant projection of the upper face
       else if(abs(b)>=abs(c) && abs(b) >= abs(a))
         {
           x1= myBoundingPtUp[0]+a*dec/norm; z1= myBoundingPtUp[2]+c*dec/norm;
           y1= b*dec/norm +(-d-a*myBoundingPtUp[0]-c*myBoundingPtUp[2])/b;
           x2= myBoundingPtUp[0]+a*dec/norm; z2= myBoundingPtLow[2]+c*dec/norm;
           y2= b*dec/norm +(-d-a*myBoundingPtUp[0]-c*myBoundingPtLow[2])/b;
           x3= myBoundingPtLow[0]+a*dec/norm; z3= myBoundingPtLow[2]+c*dec/norm;
           y3= b*dec/norm +(-d-a*myBoundingPtLow[0]-c*myBoundingPtLow[2])/b;
           x4= myBoundingPtLow[0]+a*dec/norm; z4= myBoundingPtUp[2]+c*dec/norm;
           y4= b*dec/norm +(-d-a*myBoundingPtLow[0]-c*myBoundingPtUp[2])/b;
           if(b>0)
             {
               addQuad(RealPoint(x4,y4,z4),RealPoint(x3, y3,z3),
                       RealPoint(x2,y2,z2), RealPoint(x1,y1,z1));
             }else
             {
               addQuad(RealPoint(x1,y1,z1), RealPoint(x2,y2,z2),
                       RealPoint(x3,y3,z3), RealPoint(x4,y4,z4));
             }
         }// X dominant projection of the upper face
       else if(abs(a)>=abs(c) && abs(a) >= abs(b))
         {
           y1= myBoundingPtUp[1]+b*dec/norm; z1= myBoundingPtUp[2]+c*dec/norm;
           x1= a*dec/norm +(-d-b*myBoundingPtUp[1]-c*myBoundingPtUp[2])/a;
           y2= myBoundingPtLow[1]+b*dec/norm; z2= myBoundingPtUp[2]+c*dec/norm;
           x2= a*dec/norm +(-d-b*myBoundingPtLow[1]-c*myBoundingPtUp[2])/a;
           y3= myBoundingPtLow[1]+b*dec/norm; z3= myBoundingPtLow[2]+c*dec/norm;
           x3= a*dec/norm +(-d-b*myBoundingPtLow[1]-c*myBoundingPtLow[2])/a;
           y4= myBoundingPtUp[1]+b*dec/norm; z4= myBoundingPtLow[2]+c*dec/norm;
           x4= a*dec/norm +(-d-b*myBoundingPtUp[1]-c*myBoundingPtLow[2])/a;
           if(a>0)
             {
               addQuad(RealPoint(x4,y4,z4),
                       RealPoint(x3,y3,z3),
                       RealPoint(x2,y2,z2),
                       RealPoint(x1,y1,z1));
             }else
             {
               addQuad( RealPoint(x1,y1,z1), RealPoint(x2,y2,z2),
                        RealPoint(x3,y3,z3),RealPoint(x4,y4,z4));
             }
         }
     }
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::addCone (const RealPoint & p1, const RealPoint & p2, double width = 0.02) inline
Specific to display a surfel from Kahlimsky space in basic mode.
Parameters
baseQuadCenter base quad center point
xSurfel true if the surfel has its main face in the direction of the x-axis
ySurfel true if the surfel has its main face in the direction of the y-axis
zSurfel true if the surfel has its main face in the direction of the z-axis
sizeShiftFactor set the distance between the display of the surfel and potential Cube.
sizeFactor set the difference between the upper face of the prism and the down face
isSigned to specify if we want to display an signed or unsigned Cell.
aSign if isSigned is true it will be used to apply a different displays according this boolean parameter (if aSign=true oriented in the direct axis orientation) Add a signed KSLinel from the Kahlimsky space. Display it as a cone.
p1 the cone apex
p2 the cone base
width the width of the cone (default= 0.02)
Definition at line 721 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   updateBoundingBox(p1);
   updateBoundingBox(p2);
   int nbPoints = 6; //the number of point on the base of the cone
   double degree = 360 / nbPoints; // the angle between two points
   double radian = degree * M_PI/180.0;
   double norm; // norm of the vectors
   // A(x1,y1,z1) and B(x2,y2,z2) vector AB
   double xab, yab, zab;
   xab = p2[0]-p1[0];
   yab = p2[1]-p1[1];
   zab = p2[2]-p1[2];
   norm = sqrt( xab*xab + yab*yab + zab*zab);
   assert (norm > 0);
   xab = xab / norm;
   yab = yab / norm;
   zab = zab / norm;
   //take a third point M different from A and B
   double xm = 0;
   double ym = 0;
   double zm = 0;
   while (p1[0] == xm || p2[0] ==xm) xm++;
   while (p1[1] == ym || p2[1] ==ym) ym++;
   while (p1[2] == zm || p2[2] ==zm) zm++;
   //vector AM
   double xam, yam, zam;
   xam = xm-p1[0];
   yam = ym-p1[1];
   zam = zm-p1[2];
   norm = sqrt( xam*xam + yam*yam + zam*zam);
   assert (norm > 0);
   xam = xam / norm;
   yam = yam / norm;
   zam = zam / norm;
   //normal vector n = AB^AM
   double xn, yn, zn;
   xn = yab*zam - yam*zab;
   yn = xam*zab - xab*zam;
   zn = xab*yam - xam*yab;
   //divide n by its norm
   norm = sqrt( xn*xn + yn*yn + zn*zn);
   assert (norm > 0);
   xn = xn / norm;
   yn = yn / norm;
   zn = zn / norm;
   //the first point of the base
   double xf, yf, zf;
   xf = p2[0] + width * xn;
   yf = p2[1] + width * yn;
   zf = p2[2] + width * zn;
   //two following points of the base
   double xb1 = xf;
   double yb1 = yf;
   double zb1 = zf;
   double xb2,yb2, zb2;
   //r = AB^n for the future rotation
   double xr, yr, zr;
   createNewTriangleList("Cone");
   for (int i =0; i < nbPoints-1; i ++)
     {
       // r = AB^n
       xr = yab*zn - yn*zab;
       yr = xn*zab - xab*zn;
       zr = xab*yn - xn*yab;
       //rotate n by degree
       xn = cos(radian)*xn + sin(radian)*xr;
       yn = cos(radian)*yn + sin(radian)*yr;
       zn = cos(radian)*zn + sin(radian)*zr;
       //divide n by its norm
       norm = sqrt( xn*xn + yn*yn + zn*zn);
       assert (norm > 0);
       xn = xn / norm;
       yn = yn / norm;
       zn = zn / norm;
       // calculate one point with the normal vector at a distance width
       xb2 = p2[0] + width * xn;
       yb2 = p2[1] + width * yn;
       zb2 = p2[2] + width * zn;
       //adding the triangles associated with this point
       addTriangle(p1,
                   RealPoint(xb1, yb1, zb1),
                   RealPoint(xb2, yb2, zb2));
       addTriangle(p2,
                   RealPoint(xb1, yb1, zb1),
                   RealPoint(xb2, yb2, zb2));
       xb1 = xb2;
       yb1 = yb2;
       zb1 = zb2;
     }
   //Last part to close the cone
   addTriangle(p1,
               RealPoint(xb1, yb1,zb1),
               RealPoint(xf, yf, zf));
   addTriangle(p2,
               RealPoint(xb1, yb1, zb1),
               RealPoint(xf, yf, zf));
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::addCube (const RealPoint & center, double width = 1.0) inline
Method to add specific cube. It includes several modes to display the cube with and without the wire visualisation.
Parameters
center cube center
width the cube width.
Definition at line 200 of file Display3D.ih.
References DGtal::Display3D< Space, KSpace >::CubeD3D::center, DGtal::Display3D< Space, KSpace >::CubeD3D::color, and DGtal::Display3D< Space, KSpace >::CubeD3D::width.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPaving(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingTransparent(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingWired().
 {
   //because the width in the cube parameters is actually the distance between the center and the faces
   width = width/2;
   updateBoundingBox(center);
   CubeD3D v;
   v.center=center;
   v.color=getFillColor();
   v.width=width;
   if (myCubeSetList.size() ==0)
     createNewCubeList("Cube Root");
   (myCubeSetList.at(myCubeSetList.size()-1)).push_back(v);
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::addCylinder (const RealPoint & p1, const RealPoint & p2, const double width = 0.02) inline
Add a non signed KSLinel from the Kahlimsky space. Display it as a simple cylinder.
Parameters
p1 the 1st point
p2 the 2nd point
width the width of the cylinder (default= 0.02)
Definition at line 848 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   updateBoundingBox(p1);
   updateBoundingBox(p2);
   int nbPoints = 6; //the number of point on the base of the cone
   double degree = 360 / nbPoints; // the angle between two points
   double radian = degree * M_PI/180.0;
   double norm; // norm of the vectors
   // A(p1[0],p1[1],p1[2]) and B(p2[0],p2[1],p2[2]) vector AB
   double xab, yab, zab;
   xab = p2[0]-p1[0];
   yab = p2[1]-p1[1];
   zab = p2[2]-p1[2];
   norm = sqrt( xab*xab + yab*yab + zab*zab);
   assert (norm > 0);
   xab = xab / norm;
   yab = yab / norm;
   zab = zab / norm;
   //take a third point M different from A and B
   double xm = 0;
   double ym = 0;
   double zm = 0;
   while (p1[0] == xm || p2[0] ==xm) xm++;
   while (p1[1] == ym || p2[1] ==ym) ym++;
   while (p1[2] == zm || p2[2] ==zm) zm++;
   //vector AM
   double xam, yam, zam;
   xam = xm-p1[0];
   yam = ym-p1[1];
   zam = zm-p1[2];
   norm = sqrt( xam*xam + yam*yam + zam*zam);
   assert (norm > 0);
   xam = xam / norm;
   yam = yam / norm;
   zam = zam / norm;
   //normal vector n = AB^AM
   double xn, yn, zn;
   xn = yab*zam - yam*zab;
   yn = xam*zab - xab*zam;
   zn = xab*yam - xam*yab;
   //divide n by its norm
   norm = sqrt( xn*xn + yn*yn + zn*zn);
   assert (norm > 0);
   xn = xn / norm;
   yn = yn / norm;
   zn = zn / norm;
   //the first point of the bases
   double xbf, ybf, zbf;
   double xaf, yaf, zaf;
   xbf = p2[0] + width * xn;
   ybf = p2[1] + width * yn;
   zbf = p2[2] + width * zn;
   xaf = p1[0] + width * xn;
   yaf = p1[1] + width * yn;
   zaf = p1[2] + width * zn;
   //two following points of the bases
   double xb1 = xbf;
   double yb1 = ybf;
   double zb1 = zbf;
   double xb2,yb2, zb2;
   double xa1 = xaf;
   double ya1 = yaf;
   double za1 = zaf;
   double xa2,ya2, za2;
   //r = AB^n for the future rotation
   double xr, yr, zr;
   createNewTriangleList("Cylinder");
   createNewQuadList("Cylinder");
   for (int i =0; i < nbPoints-1; i ++)
     {
       // r = AB^n
       xr = yab*zn - yn*zab;
       yr = xn*zab - xab*zn;
       zr = xab*yn - xn*yab;
       //rotate n by degree
       xn = cos(radian)*xn + sin(radian)*xr;
       yn = cos(radian)*yn + sin(radian)*yr;
       zn = cos(radian)*zn + sin(radian)*zr;
       //divide n by its norm (used when a bug appear)
       norm = sqrt( xn*xn + yn*yn + zn*zn);
       assert (norm > 0);
       xn = xn / norm;
       yn = yn / norm;
       zn = zn / norm;
       // calculate one point with the normal vector at a distance width
       xb2 = p2[0] + width * xn;
       yb2 = p2[1] + width * yn;
       zb2 = p2[2] + width * zn;
       xa2 = p1[0] + width * xn;
       ya2 = p1[1] + width * yn;
       za2 = p1[2] + width * zn;
       //adding the triangles and the quad associated with those points
       addTriangle(p1,
                   RealPoint(xa1, ya1, za1),
                   RealPoint(xa2, ya2, za2));
       addTriangle(p2,
                   RealPoint(xb1, yb1, zb1),
                   RealPoint(xb2, yb2, zb2));
       addQuad(RealPoint(xb1, yb1, zb1),
               RealPoint(xb2, yb2, zb2),
               RealPoint(xa2, ya2, za2),
               RealPoint(xa1, ya1, za1));
       xb1 = xb2;
       yb1 = yb2;
       zb1 = zb2;
       xa1 = xa2;
       ya1 = ya2;
       za1 = za2;
     }
   //Last part to close the cylinder
   addTriangle(p1,
               RealPoint(xa1, ya1, za1),
               RealPoint(xaf, yaf, zaf));
   addTriangle(p2,
               RealPoint(xb1, yb1, zb1),
               RealPoint(xbf, ybf, zbf));
   addQuad(RealPoint(xb1, yb1, zb1),
           RealPoint(xbf, ybf, zbf),
           RealPoint(xaf, yaf, zaf),
           RealPoint(xa1, ya1, za1));
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::addLine (const RealPoint & p1, const RealPoint & p2, const double width = 0.03) inline
Method to add a line to the current display. x1, y1, z1, x2, y2, z2 the two extremty line points.
Parameters
p1 the 1st point
p2 the 2nd point
width the line width
Definition at line 237 of file Display3D.ih.
References DGtal::Display3D< Space, KSpace >::LineD3D::color, DGtal::Display3D< Space, KSpace >::LineD3D::isSigned, DGtal::Display3D< Space, KSpace >::LineD3D::point1, DGtal::Display3D< Space, KSpace >::LineD3D::point2, DGtal::Display3D< Space, KSpace >::LineD3D::signPos, and DGtal::Display3D< Space, KSpace >::LineD3D::width.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsBalls(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsBoundingBox(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsGrid(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingWired().
 {
   updateBoundingBox(p1);
   updateBoundingBox(p2);
   LineD3D l;
   l.point1=p1;
   l.point2=p2;
   l.color= getLineColor();
   l.width=width;
   l.isSigned=false;
   l.signPos=false;
   if (myLineSetList.size()== 0)
     createNewLineList("Line Root");
   (myLineSetList.at(myLineSetList.size()-1)).push_back(l);
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::addPolygon (const std::vector< RealPoint > & vertices) inline
Method to add a specific polygon.
Parameters
vertices a vector containing the polygon vertices.
Definition at line 400 of file Display3D.ih.
References DGtal::Trace::error(), DGtal::trace, and DGtal::Display3D< Space, KSpace >::PolygonD3D::vertices.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::drawAsFaces().
 {
   ASSERT_MSG(vertices.size()>2, "Polygon must have at least two vertices");
   PolygonD3D polygon;
   for(unsigned int i=0; i< vertices.size();i++)
     {
       polygon.vertices.push_back(vertices[i]);
       updateBoundingBox(vertices[i]);
     }
   double x1= vertices[0][0];
   double y1= vertices[0][1];
   double z1= vertices[0][2];
   double x2= vertices[1][0];
   double y2= vertices[1][1];
   double z2= vertices[1][2];
   double x3= vertices[2][0];
   double y3= vertices[2][1];
   double z3= vertices[2][2];
   double u[3]; double v [3]; double n [3];
   u[0]=x2-x1; u[1]=y2-y1; u[2]=z2-z1;
   v[0]=x3-x1; v[1]=y3-y1; v[2]=z3-z1;
   cross(n, u, v );
   normalize(n);
   if(u[0]==0.0 && u[1]==0.0 && u[2]==0.0)
     {
       trace.error()<< "Warning polygio not added due to identical vertex... "<<std::endl;
       return;
     }
   polygon.nx= n[0];
   polygon.ny= n[1];
   polygon.nz= n[2];
   polygon.color = getFillColor();
   if (myPolygonSetList.size()== 0)
     createNewPolygonList("Polygon Root");
   (myPolygonSetList.at(myPolygonSetList.size()-1)).push_back(polygon);
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::addPrism (const RealPoint & baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel, double sizeShiftFactor, double sizeFactor = 1.0, bool isSigned = false, bool aSign = true) inline
Specific to display a surfel from Kahlimsky space. The display can take into accounts the sign of the cell.
Parameters
baseQuadCenter base quad center point
xSurfel true if the surfel has its main face in the direction of the x-axis
ySurfel true if the surfel has its main face in the direction of the y-axis
zSurfel true if the surfel has its main face in the direction of the z-axis
sizeShiftFactor set the distance between the display of the surfel and potential Cube.
sizeFactor set the difference between the upper face of the prism and the down face
isSigned to specify if we want to display an signed or unsigned Cell.
aSign if isSigned is true it will be used to apply a different displays according this boolean parameter (if aSign=true oriented in the direct axis orientation)
Definition at line 452 of file Display3D.ih.
References DGtal::Display3D< Space, KSpace >::QuadD3D::color, DGtal::Display3D< Space, KSpace >::QuadD3D::nx, DGtal::Display3D< Space, KSpace >::QuadD3D::ny, DGtal::Display3D< Space, KSpace >::QuadD3D::nz, DGtal::Display3D< Space, KSpace >::QuadD3D::point1, DGtal::Display3D< Space, KSpace >::QuadD3D::point2, DGtal::Display3D< Space, KSpace >::QuadD3D::point3, and DGtal::Display3D< Space, KSpace >::QuadD3D::point4.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   updateBoundingBox(baseQuadCenter);
   double retract= 0.05*(sizeShiftFactor+myCurrentfShiftVisuPrisms);
   double width= 0.03*(sizeShiftFactor+myCurrentfShiftVisuPrisms);
   double x1, y1, z1, x2, y2, z2, x3, y3, z3, x4, y4, z4;
   double x5, y5, z5, x6, y6, z6, x7, y7, z7, x8, y8, z8;
   double dx, dy, dz;
   ASSERT( xSurfel || ySurfel || zSurfel );
   if(zSurfel)
     {
       x1= baseQuadCenter[0]-(0.5*sizeFactor); y1= baseQuadCenter[1]-(0.5*sizeFactor); z1= baseQuadCenter[2]-0.5;
       x2= baseQuadCenter[0]+(0.5*sizeFactor); y2= baseQuadCenter[1]-(0.5*sizeFactor); z2= baseQuadCenter[2]-0.5;
       x3= baseQuadCenter[0]+(0.5*sizeFactor); y3= baseQuadCenter[1]+(0.5*sizeFactor); z3= baseQuadCenter[2]-0.5;
       x4= baseQuadCenter[0]-(0.5*sizeFactor); y4= baseQuadCenter[1]+(0.5*sizeFactor); z4= baseQuadCenter[2]-0.5;
       y1+=retract; y2+=retract; y3-=retract; y4-=retract;
       x1+=retract; x2-=retract; x3-=retract; x4+=retract;
       dx=0.0; dy=0.0; dz=width;
     }
   else if(ySurfel)
     {
       x1= baseQuadCenter[0]-(0.5*sizeFactor); y1= baseQuadCenter[1]-0.5; z1= baseQuadCenter[2]-(0.5*sizeFactor);
       x2= baseQuadCenter[0]-(0.5*sizeFactor); y2= baseQuadCenter[1]-0.5; z2= baseQuadCenter[2]+(0.5*sizeFactor);
       x3= baseQuadCenter[0]+(0.5*sizeFactor); y3= baseQuadCenter[1]-0.5; z3= baseQuadCenter[2]+(0.5*sizeFactor);
       x4= baseQuadCenter[0]+(0.5*sizeFactor); y4= baseQuadCenter[1]-0.5; z4= baseQuadCenter[2]-(0.5*sizeFactor);
       x1+=retract; x2+=retract; x3-=retract; x4-=retract;
       z1+=retract; z2-=retract; z3-=retract; z4+=retract;
       dx=0.0; dy=width; dz=0.0;
     }
   else
     {
       x1= baseQuadCenter[0]-0.5; y1= baseQuadCenter[1]-(0.5*sizeFactor); z1= baseQuadCenter[2]-(0.5*sizeFactor);
       x2= baseQuadCenter[0]-0.5; y2= baseQuadCenter[1]+(0.5*sizeFactor); z2= baseQuadCenter[2]-(0.5*sizeFactor);
       x3= baseQuadCenter[0]-0.5; y3= baseQuadCenter[1]+(0.5*sizeFactor); z3= baseQuadCenter[2]+(0.5*sizeFactor);
       x4= baseQuadCenter[0]-0.5; y4= baseQuadCenter[1]-(0.5*sizeFactor); z4= baseQuadCenter[2]+(0.5*sizeFactor);
       y1+=retract; y2-=retract; y3-=retract; y4+=retract;
       z1+=retract; z2+=retract; z3-=retract; z4-=retract;
       dx=width; dy=0.0; dz=0.0;
     }
   double xcenter= (x1+x2+x3+x4)/4.0;
   double ycenter= (y1+y2+y3+y4)/4.0;
   double zcenter= (z1+z2+z3+z4)/4.0;
   x5=x1-dx; y5=y1-dy; z5= z1-dz;
   x6=x2-dx; y6=y2-dy; z6= z2-dz;
   x7=x3-dx; y7=y3-dy; z7= z3-dz;
   x8=x4-dx; y8=y4-dy; z8= z4-dz;
   x1=x1+dx; y1=y1+dy; z1= z1+dz;
   x2=x2+dx; y2=y2+dy; z2= z2+dz;
   x3=x3+dx; y3=y3+dy; z3= z3+dz;
   x4=x4+dx; y4=y4+dy; z4= z4+dz;
   //if cell is oriented positively we retrac the upper face:
   if(isSigned && aSign)
     {
       x1= 0.6*x1+0.4*xcenter; x2= 0.6*x2+0.4*xcenter; x3= 0.6*x3+0.4*xcenter; x4= 0.6*x4+0.4*xcenter;
       y1= 0.6*y1+0.4*ycenter; y2= 0.6*y2+0.4*ycenter; y3= 0.6*y3+0.4*ycenter; y4= 0.6*y4+0.4*ycenter;
       z1= 0.6*z1+0.4*zcenter; z2= 0.6*z2+0.4*zcenter; z3= 0.6*z3+0.4*zcenter; z4= 0.6*z4+0.4*zcenter;
     }else if (isSigned)
     {
       x5= 0.6*x5+0.4*xcenter; x6= 0.6*x6+0.4*xcenter; x7= 0.6*x7+0.4*xcenter; x8= 0.6*x8+0.4*xcenter;
       y5= 0.6*y5+0.4*ycenter; y6= 0.6*y6+0.4*ycenter; y7= 0.6*y7+0.4*ycenter; y8= 0.6*y8+0.4*ycenter;
       z5= 0.6*z5+0.4*zcenter; z6= 0.6*z6+0.4*zcenter; z7= 0.6*z7+0.4*zcenter; z8= 0.6*z8+0.4*zcenter;
     }
   //main up face
   QuadD3D qFaceUp;
   double normaleUp [3];
   normaleUp[0] = dx!=0.0? 1.0:0.0;
   normaleUp[1] = dy!=0.0 ? 1.0:0.0;
   normaleUp[2] = dz!=0.0? 1.0:0.0;
   qFaceUp.nx= normaleUp[0];
   qFaceUp.ny= normaleUp[1];
   qFaceUp.nz= normaleUp[2];
   qFaceUp.point1[0]=x1; qFaceUp.point1[1]=y1; qFaceUp.point1[2]= z1;
   qFaceUp.point2[0]=x2; qFaceUp.point2[1]=y2; qFaceUp.point2[2]= z2;
   qFaceUp.point3[0]=x3; qFaceUp.point3[1]=y3; qFaceUp.point3[2]= z3;
   qFaceUp.point4[0]=x4; qFaceUp.point4[1]=y4; qFaceUp.point4[2]= z4;
   qFaceUp.color=myCurrentFillColor;
   myPrismList.push_back(qFaceUp);
   //main down face
   QuadD3D qFaceDown;
   qFaceDown.nx= -normaleUp[0];
   qFaceDown.ny= -normaleUp[1];
   qFaceDown.nz= -normaleUp[2];
   qFaceDown.point1[0]=x5; qFaceDown.point1[1]=y5; qFaceDown.point1[2]= z5;
   qFaceDown.point2[0]=x8; qFaceDown.point2[1]=y8; qFaceDown.point2[2]= z8;
   qFaceDown.point3[0]=x7; qFaceDown.point3[1]=y7; qFaceDown.point3[2]= z7;
   qFaceDown.point4[0]=x6; qFaceDown.point4[1]=y6; qFaceDown.point4[2]= z6;
   qFaceDown.color=myCurrentFillColor;
   myPrismList.push_back(qFaceDown);
   //small face 1
   QuadD3D qFace1;
   double vF1[3]; double v1 [3]; double n1 [3];
   vF1[0] = x2-x1; vF1[1] = y2-y1; vF1[2] = z2-z1;
   v1[0] = x5-x1; v1[1] = y5-y1; v1[2] = z5-z1;
   cross(n1, v1,vF1);
   normalize(n1);
   qFace1.nx=n1[0]; qFace1.ny=n1[1]; qFace1.nz=n1[2];
   qFace1.point1[0]= x1; qFace1.point1[1] =y1; qFace1.point1[2]=z1;
   qFace1.point2[0]= x5; qFace1.point2[1] =y5; qFace1.point2[2]=z5;
   qFace1.point3[0]= x6; qFace1.point3[1] =y6; qFace1.point3[2]=z6;
   qFace1.point4[0]= x2; qFace1.point4[1] =y2; qFace1.point4[2]=z2;
   qFace1.color=myCurrentFillColor;
   myPrismList.push_back(qFace1);
   //small face 2
   QuadD3D qFace2;
   double vF2[3]; double v2 [3]; double n2[3];
   vF2[0]= x3-x2; vF2[1]=y3-y2; vF2[2]= z3-z2;
   v2[0]= x6-x2; v2[1]= y6-y2; v2[2]=z6-z2;
   cross(n2, v2, vF2);
   normalize(n2);
   qFace2.nx=n2[0]; qFace2.ny=n2[1]; qFace2.nz=n2[2];
   qFace2.point1[0]= x2; qFace2.point1[1] =y2; qFace2.point1[2]=z2;
   qFace2.point2[0]= x6; qFace2.point2[1] =y6; qFace2.point2[2]=z6;
   qFace2.point3[0]= x7; qFace2.point3[1] =y7; qFace2.point3[2]=z7;
   qFace2.point4[0]= x3; qFace2.point4[1] =y3; qFace2.point4[2]=z3;
   qFace2.color=myCurrentFillColor;
   myPrismList.push_back(qFace2);
   //small face 3
   QuadD3D qFace3;
   double vF3[3]; double v3 [3]; double n3[3];
   vF3[0]= x4-x3; vF3[1]=y4-y3; vF3[2]= z4-z3;
   v3[0]= x7-x3; v3[1]= y7-y3; v3[2]=z7-z3;
   cross(n3, v3, vF3);
   normalize(n3);
   qFace3.nx=n3[0]; qFace3.ny=n3[1]; qFace3.nz=n3[2];
   qFace3.point1[0]= x3; qFace3.point1[1] =y3; qFace3.point1[2]=z3;
   qFace3.point2[0]= x7; qFace3.point2[1] =y7; qFace3.point2[2]=z7;
   qFace3.point3[0]= x8; qFace3.point3[1] =y8; qFace3.point3[2]=z8;
   qFace3.point4[0]= x4; qFace3.point4[1] =y4; qFace3.point4[2]=z4;
   qFace3.color=myCurrentFillColor;
   myPrismList.push_back(qFace3);
   //small face 4
   QuadD3D qFace4;
   double vF4[3]; double v4 [3]; double n4[3];
   vF4[0]= x1-x4; vF4[1]=y1-y4; vF4[2]= z1-z4;
   v4[0]= x8-x4; v4[1]= y8-y4; v4[2]=z8-z4;
   cross(n4, v4, vF4);
   normalize(n4);
   qFace4.nx=n4[0]; qFace4.ny=n4[1]; qFace4.nz=n4[2];
   qFace4.point1[0]= x4; qFace4.point1[1] =y4; qFace4.point1[2]=z4;
   qFace4.point2[0]= x8; qFace4.point2[1] =y8; qFace4.point2[2]=z8;
   qFace4.point3[0]= x5; qFace4.point3[1] =y5; qFace4.point3[2]=z5;
   qFace4.point4[0]= x1; qFace4.point4[1] =y1; qFace4.point4[2]=z1;
   qFace4.color= myCurrentFillColor;
   myPrismList.push_back(qFace4);
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::addQuad (const RealPoint & p1, const RealPoint & p2, const RealPoint & p3, const RealPoint & p4) inline
Method to add a specific quad (used by addClippingPlane or to represent basic surfels from Khalimsky space). The normal is computed from the vertex order.
Parameters
p1 the 1st point
p2 the 2nd point
p3 the 3rd point
p4 the 4th point
Definition at line 258 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsBoundingBox(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawAsFaces().
 {
   double u[3]; double v [3]; double n [3];
   u[0]=p2[0]-p1[0]; u[1]=p2[1]-p1[1]; u[2]=p2[2]-p1[2];
   v[0]=p3[0]-p1[0]; v[1]=p3[1]-p1[1]; v[2]=p3[2]-p1[2];
   cross(n, u, v );
   normalize(n);
   addQuadWithNormal(p1, p2, p3, p4, RealPoint(n[0], n[1], n[2]), false);
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::addQuadFromSurfelCenter (const RealPoint & baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel) inline
Method to add a quad representing a surfel given from its center and its orientation.
Parameters
baseQuadCenter the surfel center.
xSurfel indicates that the sufel is in the x axis direction
ySurfel indicates that the sufel is in the y axis direction
zSurfel indicates that the sufel is in the z axis direction
Definition at line 623 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   updateBoundingBox(baseQuadCenter);
   ASSERT( xSurfel || ySurfel || zSurfel );
   double x1, y1, z1, x2, y2, z2, x3, y3, z3, x4, y4, z4;
   ASSERT( xSurfel || ySurfel || zSurfel );
   if(zSurfel)
     {
       x1= baseQuadCenter[0]-0.5; y1= baseQuadCenter[1]-0.5; z1= baseQuadCenter[2]-0.5;
       x2= baseQuadCenter[0]+0.5; y2= baseQuadCenter[1]-0.5; z2= baseQuadCenter[2]-0.5;
       x3= baseQuadCenter[0]+0.5; y3= baseQuadCenter[1]+0.5; z3= baseQuadCenter[2]-0.5;
       x4= baseQuadCenter[0]-0.5; y4= baseQuadCenter[1]+0.5; z4= baseQuadCenter[2]-0.5;
     }
   else if(ySurfel)
     {
       x1= baseQuadCenter[0]-0.5; y1= baseQuadCenter[1]-0.5; z1= baseQuadCenter[2]-0.5;
       x2= baseQuadCenter[0]-0.5; y2= baseQuadCenter[1]-0.5; z2= baseQuadCenter[2]+0.5;
       x3= baseQuadCenter[0]+0.5; y3= baseQuadCenter[1]-0.5; z3= baseQuadCenter[2]+0.5;
       x4= baseQuadCenter[0]+0.5; y4= baseQuadCenter[1]-0.5; z4= baseQuadCenter[2]-0.5;
     }
   else
     {
       x1= baseQuadCenter[0]-0.5; y1= baseQuadCenter[1]-0.5; z1= baseQuadCenter[2]-0.5;
       x2= baseQuadCenter[0]-0.5; y2= baseQuadCenter[1]+0.5; z2= baseQuadCenter[2]-0.5;
       x3= baseQuadCenter[0]-0.5; y3= baseQuadCenter[1]+0.5; z3= baseQuadCenter[2]+0.5;
       x4= baseQuadCenter[0]-0.5; y4= baseQuadCenter[1]-0.5; z4= baseQuadCenter[2]+0.5;
     }
   addQuad(RealPoint(x1, y1, z1), RealPoint(x2 ,y2, z2),
           RealPoint(x3, y3, z3), RealPoint(x4, y4, z4));
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::addQuadFromSurfelCenterWithNormal (const RealPoint & baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel, const RealVector & aNormal, const bool enableReorientation, const bool sign, const bool enableDoubleFace = false) inline
Method to add a quad representing a surfel given from its center and its orientation, and attach a unitary normal vector to it. Depending on enableReorientation, Quad points can be reordered to make its orientation constistant with the normal direction.
Parameters
baseQuadCenter the surfel center.
xSurfel indicates that the sufel is in the x axis direction
ySurfel indicates that the sufel is in the y axis direction
zSurfel indicates that the sufel is in the z axis direction
aNormal a unitary normal vector to attach to the quad.
enableReorientation if true, the quad orientation will match with prescribed normal vector (dot product between the normal and the canonical one is >0).
sign if enableReorientation is true, we use this bool to get the surfel sign
enableDoubleFace if true, two quad (with opposite normal vector) will be drawn.
Definition at line 662 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::drawOrientedSurfelWithNormal(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawUnorientedSurfelWithNormal().
 {
   updateBoundingBox(baseQuadCenter);
   ASSERT( xSurfel || ySurfel || zSurfel );
   double x1, y1, z1, x2, y2, z2, x3, y3, z3, x4, y4, z4;
   ASSERT( xSurfel || ySurfel || zSurfel );
   if(zSurfel)
     {
       x1= baseQuadCenter[0]-0.5; y1= baseQuadCenter[1]-0.5; z1= baseQuadCenter[2]-0.5;
       x2= baseQuadCenter[0]+0.5; y2= baseQuadCenter[1]-0.5; z2= baseQuadCenter[2]-0.5;
       x3= baseQuadCenter[0]+0.5; y3= baseQuadCenter[1]+0.5; z3= baseQuadCenter[2]-0.5;
       x4= baseQuadCenter[0]-0.5; y4= baseQuadCenter[1]+0.5; z4= baseQuadCenter[2]-0.5;
     }
   else
     if(ySurfel)
       {
         x1= baseQuadCenter[0]-0.5; y1= baseQuadCenter[1]-0.5; z1= baseQuadCenter[2]-0.5;
         x2= baseQuadCenter[0]-0.5; y2= baseQuadCenter[1]-0.5; z2= baseQuadCenter[2]+0.5;
         x3= baseQuadCenter[0]+0.5; y3= baseQuadCenter[1]-0.5; z3= baseQuadCenter[2]+0.5;
         x4= baseQuadCenter[0]+0.5; y4= baseQuadCenter[1]-0.5; z4= baseQuadCenter[2]-0.5;
       }
     else
       {
         x1= baseQuadCenter[0]-0.5; y1= baseQuadCenter[1]-0.5; z1= baseQuadCenter[2]-0.5;
         x2= baseQuadCenter[0]-0.5; y2= baseQuadCenter[1]+0.5; z2= baseQuadCenter[2]-0.5;
         x3= baseQuadCenter[0]-0.5; y3= baseQuadCenter[1]+0.5; z3= baseQuadCenter[2]+0.5;
         x4= baseQuadCenter[0]-0.5; y4= baseQuadCenter[1]-0.5; z4= baseQuadCenter[2]+0.5;
       }
   //If we need to use the surfel sign and if it is negative, we
   //reorder the points (see drawOriented... vs drawUnoriented methods
   //in Display3DFactory).
   if ((!enableReorientation) && (!sign))
     addQuadWithNormal(RealPoint(x1, y1, z1),RealPoint(x4, y4, z4),
                       RealPoint(x3, y3, z3),
                       RealPoint(x2 ,y2, z2),  aNormal,
                       enableReorientation,
                       enableDoubleFace);
   else
     addQuadWithNormal(RealPoint(x1, y1, z1), RealPoint(x2 ,y2, z2),
                       RealPoint(x3, y3, z3), RealPoint(x4, y4, z4), aNormal,
                       enableReorientation,
                       enableDoubleFace);
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::addQuadWithNormal (const RealPoint & p1, const RealPoint & p2, const RealPoint & p3, const RealPoint & p4, const RealPoint & n, const bool enableReorientation, const bool enableDoubleFace = false) inline
Method to add a specific quad. The normal vector is specified by the user. Depending on enableReorientation, Quad points can be reordered to make its orientation constistant with the normal direction.
Parameters
p1 the 1st point
p2 the 2nd point
p3 the 3rd point
p4 the 4th point
n the normal vector
enableReorientation if true, the quad orientation will match with prescribed normal vector (dot product between the normal and the canonical one is >0).
enableDoubleFace if true, two quad (with opposite normal vector) will be drawn.
Definition at line 272 of file Display3D.ih.
References DGtal::Display3D< Space, KSpace >::QuadD3D::color, DGtal::Display3D< Space, KSpace >::QuadD3D::nx, DGtal::Display3D< Space, KSpace >::QuadD3D::ny, DGtal::Display3D< Space, KSpace >::QuadD3D::nz, DGtal::Display3D< Space, KSpace >::QuadD3D::point1, DGtal::Display3D< Space, KSpace >::QuadD3D::point2, DGtal::Display3D< Space, KSpace >::QuadD3D::point3, DGtal::Display3D< Space, KSpace >::QuadD3D::point4, DGtal::trace, and DGtal::Trace::warning().
 {
   if(myQuadSetList.size() == 0 )
     {
       createNewQuadList("quad");
     }
   QuadD3D aQuad,aQuad2;
   updateBoundingBox(p1);
   updateBoundingBox(p2);
   updateBoundingBox(p3);
   updateBoundingBox(p4);
   double u[3];
   u[0]=p2[0]-p1[0]; u[1]=p2[1]-p1[1]; u[2]=p2[2]-p1[2];
   double v[3];
   v[0]=p3[0]-p2[0]; v[1]=p3[1]-p2[1]; v[2]=p3[2]-p2[2];
   double crossprod[3];
   cross(crossprod, u,v);
   double epsilon = 0.0001;
   if(u[0]==0.0 && u[1]==0.0 && u[2]==0.0)
     {
       trace.warning()<< "Warning quad not added due to identical vertex... "<<std::endl;
       return;
     }
   if ((enableReorientation)
       && ((crossprod[0]*n[0] + crossprod[1]*n[1] +crossprod[2]*n[2])  <0.0))
     {
       aQuad.point1=p1;
       aQuad.point2=p4;
       aQuad.point3=p3;
       aQuad.point4=p2;
       aQuad.nx= n[0];
       aQuad.ny= n[1];
       aQuad.nz= n[2];
       aQuad.color= getFillColor();
       if (enableDoubleFace)
         {
           aQuad2.point1= (p1 - epsilon*n);
           aQuad2.point2= (p2 - epsilon*n);
           aQuad2.point3= (p3 - epsilon*n);
           aQuad2.point4= (p4 - epsilon*n);
           aQuad2.nx= -n[0];
           aQuad2.ny= -n[1];
           aQuad2.nz= -n[2];
           aQuad2.color= getFillColor();
         }
     }
   else
     {
       aQuad.point1=p1;
       aQuad.point2=p2;
       aQuad.point3=p3;
       aQuad.point4=p4;
       aQuad.nx= n[0];
       aQuad.ny= n[1];
       aQuad.nz= n[2];
       aQuad.color= getFillColor();
       if (enableDoubleFace)
         {
           aQuad2.point1=(p1 - epsilon*n);
           aQuad2.point2=(p4 - epsilon*n);
           aQuad2.point3=(p3 - epsilon*n);
           aQuad2.point4=(p2 - epsilon*n);
           aQuad2.nx= -n[0];
           aQuad2.ny= -n[1];
           aQuad2.nz= -n[2];
           aQuad2.color= getFillColor();
         }
     }
   if (myQuadSetList.size()== 0)
     createNewQuadList("Quad Root");
   (myQuadSetList.at(myQuadSetList.size()-1)).push_back(aQuad);
   if (enableDoubleFace)
     (myQuadSetList.at(myQuadSetList.size()-1)).push_back(aQuad2);
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::addTriangle (const RealPoint & p1, const RealPoint & p2, const RealPoint & p3) inline
Method to add a specific quad (used by addClippingPlane). The normal is computed from the vertex order.
Parameters
p1 the 1st point
p2 the 2nd point
p3 the 3rd point
Definition at line 362 of file Display3D.ih.
References DGtal::Display3D< Space, KSpace >::TriangleD3D::color, DGtal::Trace::error(), DGtal::Display3D< Space, KSpace >::TriangleD3D::nx, DGtal::Display3D< Space, KSpace >::TriangleD3D::ny, DGtal::Display3D< Space, KSpace >::TriangleD3D::nz, DGtal::Display3D< Space, KSpace >::TriangleD3D::point1, DGtal::Display3D< Space, KSpace >::TriangleD3D::point2, DGtal::Display3D< Space, KSpace >::TriangleD3D::point3, and DGtal::trace.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::drawAsFaces().
 {
   updateBoundingBox(p1);
   updateBoundingBox(p2);
   updateBoundingBox(p3);
   TriangleD3D aTriangle;
   double u[3]; double v [3]; double n [3];
   u[0]=p2[0]-p1[0]; u[1]=p2[1]-p1[1]; u[2]=p2[2]-p1[2];
   v[0]=p3[0]-p1[0]; v[1]=p3[1]-p1[1]; v[2]=p3[2]-p1[2];
   cross(n, u, v );
   cross(n, u, v );
   normalize(n);
   if(u[0]==0.0 && u[1]==0.0 && u[2]==0.0)
     {
       trace.error()<< "Warning triangle not added due to identical vertex... "<<std::endl;
       return;
     }
   aTriangle.point1=p1;
   aTriangle.point2=p2;
   aTriangle.point3=p3;
   aTriangle.nx= n[0];
   aTriangle.ny= n[1];
   aTriangle.nz= n[2];
   aTriangle.color = getFillColor();
   if (myTriangleSetList.size()== 0)
     createNewTriangleList("Triangle Root");
   (myTriangleSetList.at(myTriangleSetList.size()-1)).push_back(aTriangle);
 }
template<class Space, class KSpace> DGtal::Display3D< Space, KSpace >::BOOST_CONCEPT_ASSERT ((CSpace< Space >))
template<class Space, class KSpace> const CellEmbedder& DGtal::Display3D< Space, KSpace >::cellEmbedder () const inline
Returns
the embedder Cell -> RealPoint
Definition at line 299 of file Display3D.h.
     { return *myCellEmbedder; }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::clear () inline
Removes all sent data.
Definition at line 1339 of file Display3D.ih.
 {
   myCubeSetList.clear();
   myLineSetList.clear();
   myBallSetList.clear();
   myClippingPlaneList.clear();
   myPrismList.clear();
   myQuadSetList.clear();
   myTriangleSetList.clear();
   myPolygonSetList.clear();
   myCubeSetNameList.clear();
   myLineSetNameList.clear();
   myBallSetNameList.clear();
   myClippingPlaneNameList.clear();
   myPrismNameList.clear();
   myQuadSetNameList.clear();
   myTriangleSetNameList.clear();
   myPolygonSetNameList.clear();
   //Bounding box reset
   myBoundingPtEmptyTag = true;
   for (unsigned int i=0; i< 3; i++)
     {
       myBoundingPtUp[i] = 0.0;
       myBoundingPtLow[i] = 0.0;
     }
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::createNewBallList (std::string s = "") inline
Used to create a new list containing new 3D objects (useful to use transparency between different objects).
Parameters
s name of the new list
Definition at line 149 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw(), and DGtal::Board3D< Space, KSpace >::init().
 {
   std::vector< BallD3D > v;
   myBallSetList.push_back(v);
   myBallSetNameList.push_back(str);
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::createNewCubeList (std::string s = "") inline
Used to create a new list containing new 3D objects (useful to use transparency between different objects).
Parameters
s name of the new list
Definition at line 138 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw(), DGtal::Viewer3DFactory< TSpace, TKSpace >::draw(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPaving(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingTransparent(), and DGtal::Board3D< Space, KSpace >::init().
 {
   std::vector< CubeD3D > v;
   myCubeSetList.push_back(v);
   myCubeSetNameList.push_back(str);
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::createNewLineList (std::string s = "") inline
Used to create a new list containing new 3D objects (useful to use transparency between different objects).
Parameters
s name of the new list
Definition at line 159 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw(), DGtal::Viewer3DFactory< TSpace, TKSpace >::draw(), and DGtal::Board3D< Space, KSpace >::init().
 {
   std::vector< LineD3D > v;
   myLineSetList.push_back(v);
   myLineSetNameList.push_back(str);
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::createNewPolygonList (std::string s = "") inline
Used to create a new list containing new 3D objects (useful to use transparency between different objects).
Parameters
s name of the new list
Definition at line 189 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   std::vector< PolygonD3D > v;
   myPolygonSetList.push_back(v);
   myPolygonSetNameList.push_back(str);
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::createNewQuadList (std::string s = "") inline
Used to create a new list containing new 3D objects (useful to use transparency between different objects).
Parameters
s name of the new list
Definition at line 169 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawAsFaces().
 {
   std::vector< QuadD3D > v;
   myQuadSetList.push_back(v);
   myQuadSetNameList.push_back(str);
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::createNewTriangleList (std::string s = "") inline
Used to create a new list containing new 3D objects (useful to use transparency between different objects).
Parameters
s name of the new list
Definition at line 179 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   std::vector< TriangleD3D > v;
   myTriangleSetList.push_back(v);
   myTriangleSetNameList.push_back(str);
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::cross (double dst[3], double srcA[3], double srcB[3]) inline static protected
Calculate the cross product of two 3d vectors and return it.
Parameters
dst destination vector.
srcA source vector A.
srcB source vector B.
Definition at line 1317 of file Display3D.ih.
 {
   dst[0] = srcA[1]*srcB[2] - srcA[2]*srcB[1];
   dst[1] = srcA[2]*srcB[0] - srcA[0]*srcB[2];
   dst[2] = srcA[0]*srcB[1] - srcA[1]*srcB[0];
 }
template<typename Space, typename KSpace > DGtal::Display3D< Space,KSpace >::RealPoint DGtal::Display3D< Space, KSpace >::embed (const typename Space::Point & dp) const inline
Use to embed a DGtal point into space
Parameters
dp a DGtal Point
Returns
the point embeded in real space
Definition at line 1117 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsBalls(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsBoundingBox(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsGrid(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPaving(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingBalls(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingTransparent(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingWired().
 {
   ASSERT( myEmbedder->isValid());
   return myEmbedder->embed(dp);
 }
template<class Space, class KSpace> const Embedder& DGtal::Display3D< Space, KSpace >::embedder () const inline
Returns
the embedder Point -> RealPoint
Definition at line 295 of file Display3D.h.
     { return *myEmbedder; }
template<typename Space , typename KSpace> DGtal::Display3D< Space,KSpace >::RealPoint DGtal::Display3D< Space, KSpace >::embedK (const typename KSpace::Cell & cell) const inline
Use to embed an unsigned DGtal kahlimsky cell into space
Parameters
cell kahlimsky cell
Returns
the point embeded in real space
Definition at line 1145 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawUnorientedSurfelWithNormal().
 {
   ASSERT( myCellEmbedder->isValid());
   return myCellEmbedder->embed(cell);
 }
template<typename Space , typename KSpace> DGtal::Display3D< Space,KSpace >::RealPoint DGtal::Display3D< Space, KSpace >::embedKS (const typename KSpace::SCell & cell) const inline
Use to embed a signed DGtal kahlimsky cell into space
Parameters
cell a kahlimsky cell
Returns
the cell embeded in real space
Definition at line 1126 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawOrientedSurfelWithNormal().
 {
   ASSERT( mySCellEmbedder->isValid());
   return mySCellEmbedder->embed(scell);
 }
template<typename Space , typename KSpace> DGtal::Display3D< Space,KSpace >::RealPoint DGtal::Display3D< Space, KSpace >::embedKS (const DGtal::TransformedPrism & aTrans) const inline
Use to embed a signed DGtal kahlimsky cell into space
Parameters
aTrans a transformed surfel prism
Returns
the cell embeded in real space
Definition at line 1135 of file Display3D.ih.
References DGtal::TransformedPrism::mySurfel.
 {
   ASSERT( mySCellEmbedder->isValid());
   return mySCellEmbedder->embed(aTrans.mySurfel);
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::exportToMesh (Mesh< Display3D< Space, KSpace >::BallD3D > & aMesh) const inline
Export as Mesh the current displayed elements.
Parameters
aMesh : (return) the mesh containing the elements of the display.
Definition at line 1154 of file Display3D.ih.
References DGtal::Mesh< TPoint >::addQuadFace(), DGtal::Mesh< TPoint >::addTriangularFace(), DGtal::Mesh< TPoint >::addVertex(), DGtal::Display3D< Space, KSpace >::CubeD3D::center, DGtal::Display3D< Space, KSpace >::BallD3D::center, DGtal::Display3D< Space, KSpace >::CubeD3D::color, DGtal::Display3D< Space, KSpace >::QuadD3D::color, DGtal::Display3D< Space, KSpace >::QuadD3D::point1, DGtal::Display3D< Space, KSpace >::QuadD3D::point2, DGtal::Display3D< Space, KSpace >::QuadD3D::point3, DGtal::Display3D< Space, KSpace >::QuadD3D::point4, and DGtal::Display3D< Space, KSpace >::CubeD3D::width.
Referenced by DGtal::operator>>().
 {
   unsigned int vertexIndex=0;
   // Export of SurfelPrism lists (generated from KhalimskyCell or SignedKhalimskyCell (through addPrism))
   for (unsigned int i=0; i< myPrismList.size(); i++)
     {
       QuadD3D quad = myPrismList.at(i);
       BallD3D p1, p2, p3, p4;
       p1.center=quad.point1;
       p2.center=quad.point2;
       p3.center=quad.point3;
       p4.center=quad.point4;
       aMesh.addVertex(p1);
       aMesh.addVertex(p2);
       aMesh.addVertex(p3);
       aMesh.addVertex(p4);
       aMesh.addQuadFace(vertexIndex, vertexIndex+1, vertexIndex+2,vertexIndex+3,
                         quad.color);
       vertexIndex+=4;
     }
   // Export QuadList
   for (typename std::vector<std::vector<QuadD3D> >::const_iterator it = myQuadSetList.begin(); it != myQuadSetList.end(); it++)
     {
       for (typename std::vector<QuadD3D>::const_iterator aQuad = it->begin(); aQuad!=it->end();aQuad ++)
         {
           BallD3D p1, p2, p3, p4;
           p1.center=aQuad->point1;
           p2.center=aQuad->point2;
           p3.center=aQuad->point3;
           p4.center=aQuad->point4;
           aMesh.addVertex(p4);
           aMesh.addVertex(p3);
           aMesh.addVertex(p2);
           aMesh.addVertex(p1);
           aMesh.addQuadFace(vertexIndex,vertexIndex+1, vertexIndex+2, vertexIndex+3,
                             aQuad->color);
           vertexIndex+=4;
         }
     }
   // Export the mesh from TriangleList
   for ( typename std::vector<std::vector<TriangleD3D> >::const_iterator it =myTriangleSetList.begin(); it != myTriangleSetList.end(); it++)
     {
       for (typename std::vector<TriangleD3D>::const_iterator aTriangle = it->begin(); aTriangle!=it->end();aTriangle ++)
         {
           BallD3D p1, p2, p3;
           p1.center=aTriangle->point1;
           p2.center=aTriangle->point2;
           p3.center=aTriangle->point3;
           aMesh.addVertex(p1);
           aMesh.addVertex(p2);
           aMesh.addVertex(p3);
           aMesh.addTriangularFace(vertexIndex, vertexIndex+1, vertexIndex+2,
                                   aTriangle->color);
           vertexIndex+=3;
         }
     }
   // Export of cubeSet (generated from addCube)
   for(unsigned int j=0; j<myCubeSetList.size(); j++)
     {
       for (unsigned int i=0; i< myCubeSetList.at(j).size(); i++)
         {
           CubeD3D cube = myCubeSetList.at(j).at(i);
           BallD3D p1, p2, p3, p4, p5, p6, p7, p8;
           double width= cube.width;
           p1.center = RealPoint(cube.center[0]-width, cube.center[1]+width, cube.center[2]+width);
           p2.center = RealPoint(cube.center[0]+width, cube.center[1]+width, cube.center[2]+width);
           p3.center = RealPoint(cube.center[0]+width, cube.center[1]-width, cube.center[2]+width);
           p4.center = RealPoint(cube.center[0]-width, cube.center[1]-width, cube.center[2]+width);
           p5.center = RealPoint(cube.center[0]-width, cube.center[1]+width, cube.center[2]-width);
           p6.center = RealPoint(cube.center[0]+width, cube.center[1]+width, cube.center[2]-width);
           p7.center = RealPoint(cube.center[0]+width, cube.center[1]-width, cube.center[2]-width);
           p8.center = RealPoint(cube.center[0]-width, cube.center[1]-width, cube.center[2]-width);
           aMesh.addVertex(p1);
           aMesh.addVertex(p2);
           aMesh.addVertex(p3);
           aMesh.addVertex(p4);
           aMesh.addVertex(p5);
           aMesh.addVertex(p6);
           aMesh.addVertex(p7);
           aMesh.addVertex(p8);
           //z+
           aMesh.addQuadFace(vertexIndex, vertexIndex+3, vertexIndex+2, vertexIndex+1,
                             cube.color);
           //z-
           aMesh.addQuadFace(vertexIndex+4, vertexIndex+5, vertexIndex+6, vertexIndex+7,
                             cube.color);
           //y+
           aMesh.addQuadFace(vertexIndex+1, vertexIndex+2, vertexIndex+6, vertexIndex+5,
                             cube.color);
           //y-
           aMesh.addQuadFace(vertexIndex, vertexIndex+4, vertexIndex+7, vertexIndex+3,
                             cube.color);
           //x+
           aMesh.addQuadFace(vertexIndex, vertexIndex+1, vertexIndex+5, vertexIndex+4,
                             cube.color);
           //x-
           aMesh.addQuadFace(vertexIndex+3, vertexIndex+7, vertexIndex+6, vertexIndex+2,
                             cube.color);
           vertexIndex+=8;
         }
     }
 }
template<typename Space , typename KSpace > DGtal::Color DGtal::Display3D< Space, KSpace >::getFillColor () inline virtual
Used to get the fill color
Returns
the current fill color.
Definition at line 120 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsBalls(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsBoundingBox(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsFaces(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsGrid(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPaving(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingBalls(), DGtal::Display3DFactory< TSpace, TKSpace >::drawOrientedSurfelWithNormal(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawUnorientedSurfelWithNormal().
 {
   return myCurrentFillColor;
 }
template<typename Space , typename KSpace > DGtal::Color DGtal::Display3D< Space, KSpace >::getLineColor () inline virtual
Used to get the line color
Returns
the current line color.
Definition at line 112 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsBalls(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsGrid(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingWired().
 {
   return myCurrentLineColor;
 }
template<typename Space , typename KSpace > std::string DGtal::Display3D< Space, KSpace >::getMode (const std::string & objectName) const inline
Parameters
objectName the name of the object (generally obtained with a 'object.className()').
Returns
the current mode for the given object name or "" if no specific mode has been set.
Definition at line 128 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw(), DGtal::Viewer3DFactory< TSpace, TKSpace >::draw(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsBalls(), DGtal::Viewer3DFactory< TSpace, TKSpace >::drawImage2D(), DGtal::Viewer3DFactory< TSpace, TKSpace >::drawImage3D(), DGtal::Display3DFactory< TSpace, TKSpace >::drawOrientedSurfelWithNormal(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawUnorientedSurfelWithNormal().
 {
   ModeMapping::const_iterator itm = myModes.find( objectName );
   return itm == myModes.end() ? "" : itm->second;
 }
template<class Space, class KSpace> bool DGtal::Display3D< Space, KSpace >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::normalize (double vec[3]) inline static protected
Normalize the input 3d vector.
Parameters
vec source & destination vector.
Definition at line 1328 of file Display3D.ih.
 {
   const double squaredLen = vec[0]*vec[0] + vec[1]*vec[1] + vec[2]*vec[2];
   vec[0] /= sqrt (squaredLen);
   vec[1] /= sqrt (squaredLen);
   vec[2] /= sqrt (squaredLen);
 }
template<class Space, class KSpace> template<typename TDrawableWithDisplay3D > Display3D& DGtal::Display3D< Space, KSpace >::operator<< (const TDrawableWithDisplay3D< Space, KSpace > & object)
Draws the drawable [object] in this board. It should satisfy the concept CDrawableWithViewer3D, which requires for instance a method setStyle(Viewer3D &).
Parameters
object any drawable object.
Returns
a reference on 'this'.
template<class Space, class KSpace> template<typename TDrawableWithDisplay3D > DGtal::Display3D< Space ,KSpace >& DGtal::Display3D< Space, KSpace >::operator<< (const TDrawableWithDisplay3D< Space, KSpace > & object) inline
Definition at line 1271 of file Display3D.ih.
References DGtal::Display3DFactory< TSpace, TKSpace >::draw().
 {
   // BOOST_CONCEPT_ASSERT((CDrawableWithDisplay3D< TDrawableWithDisplay3D >));
   DGtal::Display3DFactory<Space,KSpace>::draw(*this, object);
   return *this;
 }
template<class Space, class KSpace> Display3D& DGtal::Display3D< Space, KSpace >::operator= (const Display3D< Space, KSpace > & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
template<class Space, class KSpace> const SCellEmbedder& DGtal::Display3D< Space, KSpace >::sCellEmbedder () const inline
Returns
the embedder SCell -> RealPoint
Definition at line 303 of file Display3D.h.
     { return *mySCellEmbedder; }
template<class Space, class KSpace> void DGtal::Display3D< Space, KSpace >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::setFillColor (DGtal::Color aColor) inline virtual
Used to set the current fill color
Parameters
aColor the fill color.
Definition at line 60 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsBoundingBox(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsFaces(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsGrid(), DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPaving(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingBalls().
 {
   myCurrentFillColor=aColor;
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::setFillTransparency (unsigned char alpha) inline virtual
Used to set the alpha value of the current fill color.
Parameters
alpha the transparency value (from 0 to 255).
Definition at line 68 of file Display3D.ih.
 {
   myCurrentFillColor.alpha(alpha);
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::setKSpaceEmbedder (CellEmbedder * anEmbedder) inline virtual
Used to change the default embedder for unsigned cell of Khalimsky 3D Space.
Parameters
anEmbedder the new CanonicCellEmbedder
Definition at line 94 of file Display3D.ih.
 {
   delete myCellEmbedder;
   myCellEmbedder = anEmbedder;
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::setLineColor (DGtal::Color aColor) inline virtual
Used to set the line fill color
Parameters
aColor the line color.
Definition at line 76 of file Display3D.ih.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawAsPavingWired().
 {
   myCurrentLineColor=aColor;
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::setSKSpaceEmbedder (SCellEmbedder * anEmbedder) inline virtual
Used to change the default embedder for signed cell of Khalimsky 3D Space.
Parameters
anEmbedder the new CanonicSCellEmbedder
Definition at line 103 of file Display3D.ih.
 {
   delete mySCellEmbedder;
   mySCellEmbedder = anEmbedder;
 }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::setSpaceEmbedder (Embedder * anEmbedder) inline virtual
Used to change the default embedder for point of the Digital 3D Space
Parameters
anEmbedder the new CanonicEmbedder
Definition at line 85 of file Display3D.ih.
 {
   delete myEmbedder;
   myEmbedder = anEmbedder;
 }
template<class Space, class KSpace> const KSpace& DGtal::Display3D< Space, KSpace >::space () const inline
Returns
the cellular grid space.
Definition at line 307 of file Display3D.h.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::drawOrientedSurfelWithNormal(), and DGtal::Display3DFactory< TSpace, TKSpace >::drawUnorientedSurfelWithNormal().
     { return mySCellEmbedder->space(); }
template<typename Space , typename KSpace > void DGtal::Display3D< Space, KSpace >::updateBoundingBox (const RealPoint & point) inline
Used to update the scene bounding box when objects are added.
Parameters
point the point to be taken into accounts.
Definition at line 1089 of file Display3D.ih.
 {
   if (myBoundingPtEmptyTag)
     {
       myBoundingPtLow[0]= p[0];
       myBoundingPtLow[1]= p[1];
       myBoundingPtLow[2]= p[2];
       myBoundingPtUp[0]= p[0];
       myBoundingPtUp[1]= p[1];
       myBoundingPtUp[2]= p[2];
       myBoundingPtEmptyTag = false;
     }
   else
     {
       if(p[0] <myBoundingPtLow[0]) myBoundingPtLow[0]= p[0];
       if(p[1] <myBoundingPtLow[1]) myBoundingPtLow[1]= p[1];
       if(p[2] <myBoundingPtLow[2]) myBoundingPtLow[2]= p[2];
       if(p[0] >myBoundingPtUp[0]) myBoundingPtUp[0]= p[0];
       if(p[1] >myBoundingPtUp[1]) myBoundingPtUp[1]= p[1];
       if(p[2] >myBoundingPtUp[2]) myBoundingPtUp[2]= p[2];
     }
 }
Field Documentation
template<class Space, class KSpace> std::vector< std::vector<BallD3D> > DGtal::Display3D< Space, KSpace >::myBallSetList protected
Used to represent all the list of point primitive
Definition at line 777 of file Display3D.h.
template<class Space, class KSpace> std::vector<std::string> DGtal::Display3D< Space, KSpace >::myBallSetNameList protected
names of the lists in myBallSetList
Definition at line 806 of file Display3D.h.
template<class Space, class KSpace> bool DGtal::Display3D< Space, KSpace >::myBoundingPtEmptyTag
True if the bounding box is empty (no objects added)
Definition at line 751 of file Display3D.h.
Referenced by DGtal::Display3D< S, KS >::Display3D().
template<class Space, class KSpace> double DGtal::Display3D< Space, KSpace >::myBoundingPtLow[3]
lower point of the bouding box
Definition at line 755 of file Display3D.h.
template<class Space, class KSpace> double DGtal::Display3D< Space, KSpace >::myBoundingPtUp[3]
upper point of the bounding box
Definition at line 753 of file Display3D.h.
template<class Space, class KSpace> CellEmbedder* DGtal::Display3D< Space, KSpace >::myCellEmbedder protected
an embeder from a unsigned khalimsky space point to a real space point
Definition at line 224 of file Display3D.h.
Referenced by DGtal::Display3D< S, KS >::cellEmbedder(), DGtal::Display3D< S, KS >::Display3D(), and DGtal::Display3D< S, KS >::~Display3D().
template<class Space, class KSpace> std::vector< ClippingPlaneD3D > DGtal::Display3D< Space, KSpace >::myClippingPlaneList protected
Represent all the clipping planes added to the scene (of maxSize=5).
Definition at line 781 of file Display3D.h.
template<class Space, class KSpace> std::vector<std::string> DGtal::Display3D< Space, KSpace >::myClippingPlaneNameList protected
names of the lists in myClippingPlaneList
Definition at line 809 of file Display3D.h.
template<class Space, class KSpace> std::vector< std::vector<CubeD3D> > DGtal::Display3D< Space, KSpace >::myCubeSetList protected
Used to represent all the list used in the display.
Definition at line 769 of file Display3D.h.
template<class Space, class KSpace> std::vector<std::string> DGtal::Display3D< Space, KSpace >::myCubeSetNameList protected
names of the lists in myCubeSetList
Definition at line 798 of file Display3D.h.
template<class Space, class KSpace> DGtal::Color DGtal::Display3D< Space, KSpace >::myCurrentFillColor protected
Definition at line 759 of file Display3D.h.
Referenced by DGtal::Display3D< S, KS >::Display3D().
template<class Space, class KSpace> double DGtal::Display3D< Space, KSpace >::myCurrentfShiftVisuPrisms protected
Used to specialized visualisation with KSpace surfels/cubes.
Definition at line 765 of file Display3D.h.
template<class Space, class KSpace> DGtal::Color DGtal::Display3D< Space, KSpace >::myCurrentLineColor protected
Definition at line 761 of file Display3D.h.
Referenced by DGtal::Display3D< S, KS >::Display3D().
template<class Space, class KSpace> Embedder* DGtal::Display3D< Space, KSpace >::myEmbedder protected
an embeder from a dgtal space point to a real space point
Definition at line 222 of file Display3D.h.
Referenced by DGtal::Display3D< S, KS >::Display3D(), DGtal::Display3D< S, KS >::embedder(), and DGtal::Display3D< S, KS >::~Display3D().
template<class Space, class KSpace> std::vector< std::vector<LineD3D> > DGtal::Display3D< Space, KSpace >::myLineSetList protected
Used to represent all the list of line primitive
Definition at line 773 of file Display3D.h.
template<class Space, class KSpace> std::vector<std::string> DGtal::Display3D< Space, KSpace >::myLineSetNameList protected
names of the lists in myLineSetList
Definition at line 802 of file Display3D.h.
template<class Space, class KSpace> ModeMapping DGtal::Display3D< Space, KSpace >::myModes
Definition at line 737 of file Display3D.h.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw().
template<class Space, class KSpace> std::vector<std::vector<PolygonD3D> > DGtal::Display3D< Space, KSpace >::myPolygonSetList protected
Represents all the polygon drawn in the Display3D.
Definition at line 794 of file Display3D.h.
template<class Space, class KSpace> std::vector<std::string> DGtal::Display3D< Space, KSpace >::myPolygonSetNameList protected
names of the lists in myPolygonList
Definition at line 825 of file Display3D.h.
template<class Space, class KSpace> std::vector< QuadD3D > DGtal::Display3D< Space, KSpace >::myPrismList protected
Represent truncated prism object to represent surfels of Khalimsky space (used to display Khalimsky Space Cell)
Definition at line 785 of file Display3D.h.
template<class Space, class KSpace> std::vector<std::string> DGtal::Display3D< Space, KSpace >::myPrismNameList protected
names of the lists in myPrismList
Definition at line 813 of file Display3D.h.
template<class Space, class KSpace> std::vector<std::vector< QuadD3D > > DGtal::Display3D< Space, KSpace >::myQuadSetList protected
Represents all the planes drawn in the Display3D or to display Khalimsky Space Cell.
Definition at line 788 of file Display3D.h.
template<class Space, class KSpace> std::vector<std::string> DGtal::Display3D< Space, KSpace >::myQuadSetNameList protected
names of the lists in myQuadList
Definition at line 817 of file Display3D.h.
template<class Space, class KSpace> SCellEmbedder* DGtal::Display3D< Space, KSpace >::mySCellEmbedder protected
an embeder from a signed khalimsky space point to a real space point
Definition at line 226 of file Display3D.h.
Referenced by DGtal::Display3D< S, KS >::Display3D(), DGtal::Display3D< S, KS >::sCellEmbedder(), DGtal::Display3D< S, KS >::space(), and DGtal::Display3D< S, KS >::~Display3D().
template<class Space, class KSpace> StyleMapping DGtal::Display3D< Space, KSpace >::myStyles
For instance, may associate a new style object T1 to the class "HyperRectDomain": myStyles[ "HyperRectDomain" ] = T1.
One can also store a new style T2 for a specific mode used for drawing a class: myStyles[ "HyperRectDomain/Paving" ] = T2.
Modes may only be used in objects implementing the concept CDrawableWithBoard2D.
Definition at line 748 of file Display3D.h.
Referenced by DGtal::Display3DFactory< TSpace, TKSpace >::draw().
template<class Space, class KSpace> std::vector<std::vector< TriangleD3D > > DGtal::Display3D< Space, KSpace >::myTriangleSetList protected
Represents all the triangles drawn in the Display3D.
Definition at line 791 of file Display3D.h.
template<class Space, class KSpace> std::vector<std::string> DGtal::Display3D< Space, KSpace >::myTriangleSetNameList protected
names of the lists in myTriangleList
Definition at line 821 of file Display3D.h.
The documentation for this class was generated from the following files:
src/DGtal/base/Common.h
Display3D.h
Display3D.ih