DGtal: DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency > Class Template Reference
DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency > Class Template Reference
#include <geometry/curves/ArithmeticalDSL.h>
Public Types
typedef TCoordinate Coordinate
typedef TInteger Integer
typedef ArithmeticalDSL
< Coordinate, Integer,
adjacency > DSL
typedef DSL::Space Space
typedef DSL::Point Point
typedef DSL::Vector Vector
typedef DSL::Steps Steps
typedef Coordinate Position
typedef DSL::ConstIterator ConstIterator
typedef DSL::ConstReverseIterator ConstReverseIterator
typedef DGtal::PointVector
< 2, double > PointD
Public Member Functions
BOOST_CONCEPT_ASSERT ((CInteger< Coordinate >))
BOOST_CONCEPT_ASSERT ((CInteger< Integer >))
ArithmeticalDSS (const Point &aPoint)
ArithmeticalDSS (const Coordinate &aA, const Coordinate &aB, const Integer &aLowerBound, const Integer &aUpperBound, const Point &aF, const Point &aL, const Point &aUf, const Point &aUl, const Point &aLf, const Point &aLl, const Steps &aSteps, const Vector &aShift)
ArithmeticalDSS (const DSL &aDSL, const Point &aF, const Point &aL, const Point &aUf, const Point &aUl, const Point &aLf, const Point &aLl)
ArithmeticalDSS (const Coordinate &aA, const Coordinate &aB, const Point &aF, const Point &aL, const Point &aUf, const Point &aUl, const Point &aLf, const Point &aLl)
ArithmeticalDSS (const Point &aF, const Point &aL, const bool &areOnTheUpperLine=true)
ArithmeticalDSS (const DSL &aDSL, const Point &aF, const Point &aL)
template<typename Iterator >
ArithmeticalDSS (const Iterator &aItb, const Iterator &aIte) throw (InputException)
ArithmeticalDSS (const ArithmeticalDSS &aOther)
ArithmeticalDSS & operator= (const ArithmeticalDSS &aOther)
ArithmeticalDSS negate () const
bool equalsTo (const ArithmeticalDSS &aOther) const
bool operator== (const ArithmeticalDSS &aOther) const
bool operator!= (const ArithmeticalDSS &aOther) const
~ArithmeticalDSS ()
void selfDisplay (std::ostream &out) const
bool isValid () const
const DSL & dsl () const
Coordinate a () const
Coordinate b () const
Integer mu () const
Integer omega () const
Vector shift () const
Steps steps () const
Point back () const
Point front () const
Point Uf () const
Point Ul () const
Point Lf () const
Point Ll () const
Integer remainder (const Point &aPoint) const
Integer orthogonalPosition (const Point &aPoint) const
Position position (const Point &aPoint) const
bool before (const Point &aP1, const Point &aP2) const
bool beforeOrEqual (const Point &aP1, const Point &aP2) const
bool isInDSL (const Point &aPoint) const
bool isInDSS (const Point &aPoint) const
bool operator() (const Point &aPoint) const
ConstIterator begin () const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rend () const
unsigned short int isExtendableFront (const Point &aNewPoint) const
unsigned short int isExtendableBack (const Point &aNewPoint) const
bool extendFront (const Point &aNewPoint)
bool extendBack (const Point &aNewPoint)
bool retractFront ()
bool retractBack ()
PointD project (const Point &aM, double aR) const
PointD project (const Point &aM, const Point &aP) const
std::string className () const
Static Public Attributes
static const unsigned short foregroundAdjacency = adjacency
Protected Member Functions
bool retractUpdateLeaningPoints (const Vector &aDirection, const Point &aFirst, const Point &aLast, const Point &aBezout, const Point &aFirstAtOppositeSide, Point &aLastAtOppositeSide, Point &aFirstAtRemovalSide, const Point &aLastAtRemovalSide)
void retractUpdateParameters (const Vector &aNewDirection)
Protected Attributes
Point myF
Point myL
Point myUf
Point myUl
Point myLf
Point myLl
DSL myDSL
Detailed Description
template<typename TCoordinate, typename TInteger, unsigned short adjacency>
class DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >
Aim: This class represents a naive (resp. standard) digital straight segment (DSS), ie. the sequence of simply 8- (resp. 4-)connected digital points contained in a naive (resp. standard) digital straight line (DSL) between two points of it.
Obviously, a given DSS belongs to infinitely many DSLs, but one of them has minimal parameters, ie has a minimal \(\omega \). ArithmeticalDSS uses this minimal bounding DSL to represent its slope and its intercept. ArithmeticalDSS stores as data members not only this minimal bounding DSL, but also its ending points as well as the first and last lower and upper leaning points, due to the role that these points play in the update algorithms. Indeed, ArithmeticalDSS provides some methods to update its internal representation:
ArithmeticalDSS::extendFront and ArithmeticalDSS::extendBack based on the incremental recognition algorithm of [Debled and Reveilles, 1995 : [22]].
ArithmeticalDSS::retractFront and ArithmeticalDSS::retractBack based on [Lachaud et. al., 2007, Th. 5 : [29]].
See Digital straight lines and segments. for further details. See also NaiveDSS8 and StandardDSS4, which are aliases of this class.
Template Parameters
TCoordinate a model of integer for the DGtal point coordinates and the slope parameters.
TInteger a model of integer for the intercepts and the remainders that represents a larger range of integers than TCoordinate.
This class is a model of CPointFunctor and of CConstBidirectionalRange.
See also
ArithmeticalDSL NaiveDSL StandardDSL
exampleArithmeticalDSL.cpp exampleArithmeticalDSS.cpp
Definition at line 65 of file ArithmeticalDSL.h.
Member Typedef Documentation
template<typename TCoordinate, typename TInteger, unsigned short adjacency> typedef DSL::ConstIterator DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::ConstIterator
Type of iterator.
Definition at line 145 of file ArithmeticalDSS.h.
template<typename TCoordinate, typename TInteger, unsigned short adjacency> typedef DSL::ConstReverseIterator DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::ConstReverseIterator
Type of reverse iterator.
Definition at line 149 of file ArithmeticalDSS.h.
template<typename TCoordinate, typename TInteger, unsigned short adjacency> typedef TCoordinate DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Coordinate
Type used for the points coordinates and the slope parameters.
Definition at line 110 of file ArithmeticalDSS.h.
template<typename TCoordinate, typename TInteger, unsigned short adjacency> typedef ArithmeticalDSL<Coordinate, Integer, adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::DSL
Type of the bounding DSL.
Definition at line 121 of file ArithmeticalDSS.h.
template<typename TCoordinate, typename TInteger, unsigned short adjacency> typedef TInteger DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Integer
Type used for the intercepts and the remainders.
Definition at line 115 of file ArithmeticalDSS.h.
template<typename TCoordinate, typename TInteger, unsigned short adjacency> typedef DSL::Point DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Point
Type of point.
Definition at line 129 of file ArithmeticalDSS.h.
template<typename TCoordinate, typename TInteger, unsigned short adjacency> typedef DGtal::PointVector<2, double> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::PointD
Type of embedded points
See also
project
Definition at line 155 of file ArithmeticalDSS.h.
template<typename TCoordinate, typename TInteger, unsigned short adjacency> typedef Coordinate DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Position
Type used for the position of a point in the DSL.
Definition at line 141 of file ArithmeticalDSS.h.
template<typename TCoordinate, typename TInteger, unsigned short adjacency> typedef DSL::Space DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Space
Type of digital space.
Definition at line 125 of file ArithmeticalDSS.h.
template<typename TCoordinate, typename TInteger, unsigned short adjacency> typedef DSL::Steps DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Steps
Type of steps (defined as a STL pair of vectors).
Definition at line 137 of file ArithmeticalDSS.h.
template<typename TCoordinate, typename TInteger, unsigned short adjacency> typedef DSL::Vector DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Vector
Type of vector.
Definition at line 133 of file ArithmeticalDSS.h.
Constructor & Destructor Documentation
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::ArithmeticalDSS (const Point & aPoint) inline
Simple constructor. All members of the bounding DSL are set to zero and all point members are set to aPoint
Definition at line 44 of file ArithmeticalDSS.ih.
   : myF(aPoint), myL(aPoint),
     myUf(aPoint), myUl(aPoint),
     myLf(aPoint), myLl(aPoint),
     myDSL( NumberTraits<TCoordinate>::ZERO,
            NumberTraits<TCoordinate>::ZERO,
            NumberTraits<TInteger>::ZERO,
            NumberTraits<TInteger>::ZERO,
            std::make_pair( Vector(NumberTraits<TCoordinate>::ZERO, NumberTraits<TCoordinate>::ZERO),
                            Vector(NumberTraits<TCoordinate>::ZERO, NumberTraits<TCoordinate>::ZERO) ),
            Vector(NumberTraits<TCoordinate>::ZERO, NumberTraits<TCoordinate>::ZERO) )
 {
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::ArithmeticalDSS (const Coordinate & aA, const Coordinate & aB, const Integer & aLowerBound, const Integer & aUpperBound, const Point & aF, const Point & aL, const Point & aUf, const Point & aUl, const Point & aLf, const Point & aLl, const Steps & aSteps, const Vector & aShift) inline
Constructor. The user gives all the (redondant) parameters and should be sure that the resulting DSS is valid.
See also
isValid
Parameters
aA y-component of the direction vector
aB x-component of the direction vector
aLowerBound lower intercept
aUpperBound upper intercept
aF the first point
aL the last point
aUf the first upper point
aUl the last upper point
aLf the first lower point
aLl the last lower point
aSteps pair of steps used to iterate over the DSS points
aShift shift vector
Definition at line 62 of file ArithmeticalDSS.ih.
   :
   myF(aF), myL(aL),
   myUf(aUf), myUl(aUl), myLf(aLf), myLl(aLl),
   myDSL( aA, aB, aLowerBound, aUpperBound, aSteps, aShift )
 {
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::ArithmeticalDSS (const DSL & aDSL, const Point & aF, const Point & aL, const Point & aUf, const Point & aUl, const Point & aLf, const Point & aLl) inline
Constructor. The user gives all the (redondant) parameters and should be sure that the resulting DSS is valid.
See also
isValid
Parameters
aDSL bounding DSL
aF the first point
aL the last point
aUf the first upper point
aUl the last upper point
aLf the first lower point
aLl the last lower point
Definition at line 79 of file ArithmeticalDSS.ih.
   :
   myF(aF), myL(aL),
   myUf(aUf), myUl(aUl), myLf(aLf), myLl(aLl),
   myDSL( aDSL )
 {
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::ArithmeticalDSS (const Coordinate & aA, const Coordinate & aB, const Point & aF, const Point & aL, const Point & aUf, const Point & aUl, const Point & aLf, const Point & aLl) inline
Constructor. Minimal set of parameters to build the DSS in constant time. The user should be sure that the slope is consistent with the position of the leaning points.
See also
isValid
Parameters
aA y-component of the direction vector
aB x-component of the direction vector
aF the first point
aL the last point
aUf the first upper point
aUl the last upper point
aLf the first lower point
aLl the last lower point
NB: in O(1)
Definition at line 94 of file ArithmeticalDSS.ih.
   :
   myF(aF), myL(aL),
   myUf(aUf), myUl(aUl), myLf(aLf), myLl(aLl),
   myDSL( aA, aB, DSL::remainder( aA, aB, aUf ) )
 {
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::ArithmeticalDSS (const Point & aF, const Point & aL, const bool & areOnTheUpperLine = true) inline
Construction of a sequence of patterns (or reversed patterns) from two end points.
Parameters
aF the first point
aL the last point
areOnTheUpperLine boolean equal to 'true' if the two given end points are upper leaning points (pattern case, default), 'false' if they are lower leaning points (reversed pattern case).
NB: logarithmic-time in the greatest component of the vector starting from aF and pointing to aL
Definition at line 109 of file ArithmeticalDSS.ih.
   : myDSL( NumberTraits<Coordinate>::ZERO, NumberTraits<Coordinate>::ZERO, NumberTraits<Integer>::ZERO )
 {
   typedef DGtal::ArithmeticalDSSFactory<TCoordinate, TInteger, adjacency> Factory;
   if (areOnTheUpperLine)
     *this = Factory::createPattern(aF, aL);
   else
     *this = Factory::createReversedPattern(aF, aL);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::ArithmeticalDSS (const DSL & aDSL, const Point & aF, const Point & aL) inline
Construction as the subsegment of minimal parameters of a given DSL.
Parameters
aDSL bounding DSL
aF first point of the subsegment
aL last point of the subsegment
NB: logarithmic-time in the greatest component of the direction vector of the subsegment. Uses smartCH algorithm.
Definition at line 125 of file ArithmeticalDSS.ih.
   : myDSL( NumberTraits<Coordinate>::ZERO, NumberTraits<Coordinate>::ZERO, NumberTraits<Integer>::ZERO )
 {
   typedef DGtal::ArithmeticalDSSFactory<TCoordinate, TInteger, adjacency> Factory;
   *this = Factory::createSubsegment(aDSL, aF, aL);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> template<typename Iterator > DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::ArithmeticalDSS (const Iterator & aItb, const Iterator & aIte) throw (InputException) inline
Construction from a range of iterator on points.
Parameters
aItb begin iterator
aIte end iterator
Template Parameters
Iterator a model of forward iterator
NB: linear-time in the size of the range
Definition at line 137 of file ArithmeticalDSS.ih.
   : myDSL( NumberTraits<Coordinate>::ZERO, NumberTraits<Coordinate>::ZERO, NumberTraits<Integer>::ZERO )
 {
   if (aItb != aIte)
     {
       Iterator it = aItb;
       //construction from the begin iterator
       Point p = *it;
       *this = ArithmeticalDSS(p);
       //extension
       for (++it; it != aIte; ++it)
           extendFront(*it);
     }
   else
     {
       throw InputException();
     }
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::ArithmeticalDSS (const ArithmeticalDSS< TCoordinate, TInteger, adjacency > & aOther) inline
Copy constructor.
Parameters
aOther the object to clone.
Definition at line 160 of file ArithmeticalDSS.ih.
   :
   myF(aOther.myF), myL(aOther.myL),
   myUf(aOther.myUf), myUl(aOther.myUl), myLf(aOther.myLf), myLl(aOther.myLl),
   myDSL(aOther.myDSL)
 {}
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::~ArithmeticalDSS () inline
Destructor.
Definition at line 240 of file ArithmeticalDSS.ih.
 {
 }
Member Function Documentation
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Coordinate DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::a () const inline
Returns
a parameter of the bounding DSL of minimal parameters
Definition at line 266 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSSCheck::checkOnePoint(), and DGtal::ArithmeticalDSSCheck::checkPointsPosition().
 {
   return myDSL.a();
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Coordinate DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::b () const inline
Returns
b parameter of the bounding DSL of minimal parameters
Definition at line 275 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSSCheck::checkOnePoint(), and DGtal::ArithmeticalDSSCheck::checkPointsPosition().
 {
   return myDSL.b();
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Point DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::back () const inline
Returns
back point of the DSS, ie. first visited point equal to * ArithmeticalDSS::begin()
Definition at line 320 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSSCheck::checkAll(), DGtal::ArithmeticalDSSCheck::checkOnePoint(), DGtal::ArithmeticalDSSCheck::checkPointsPosition(), DGtal::ArithmeticalDSSCheck::checkPointsRemainder(), and DGtal::Display2DFactory::drawAsBoundingBox().
 {
   return myF;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::before (const Point & aP1, const Point & aP2) const inline
Returns a boolean equal to 'true' if aP1 is located (strictly) before aP2 in the direction orthogonal to myShift, 'false' otherwise.
Parameters
aP1 any point
aP2 any point
Returns
'true' is aP2 is strictly before aP2, 'false' otherwise
See also
beforeOrEqual position
Definition at line 401 of file ArithmeticalDSS.ih.
 {
   return myDSL.before(aP1, aP2);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::beforeOrEqual (const Point & aP1, const Point & aP2) const inline
Returns a boolean equal to 'true' if aP1 is located before aP2 or is equal to aP2, 'false' otherwise.
Parameters
aP1 any point
aP2 any point
Returns
'true' is aP2 is before or equal to aP2, 'false' otherwise
See also
before position
Definition at line 410 of file ArithmeticalDSS.ih.
 {
   return myDSL.beforeOrEqual(aP1, aP2);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::ConstIterator DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::begin () const inline
Returns
begin iterator, which points to the point returned by ArithmeticalDSS::back()
Definition at line 460 of file ArithmeticalDSS.ih.
Referenced by DGtal::Display2DFactory::drawAsDigitalPoints().
 {
   return ConstIterator(&myDSL, myF);
 }
template<typename TCoordinate, typename TInteger, unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::BOOST_CONCEPT_ASSERT ((CInteger< Coordinate >))
template<typename TCoordinate, typename TInteger, unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::BOOST_CONCEPT_ASSERT ((CInteger< Integer >))
template<typename TCoordinate , typename TInteger , unsigned short adjacency> std::string DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::className () const inline
Returns
the style name used for drawing this object.
Definition at line 885 of file ArithmeticalDSS.ih.
Referenced by DGtal::Display2DFactory::draw().
 {
   return "ArithmeticalDSS";
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> const DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::DSL & DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::dsl () const inline
Returns
the bounding DSL of minimal parameters NB: since we return a const reference, you must copy the result, if you want to keep it beyond the object's existence.
Definition at line 257 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSSCheck::checkAll().
 {
   return myDSL;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::ConstIterator DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::end () const inline
Returns
end iterator, which points after the point returned by ArithmeticalDSS::front()
Definition at line 469 of file ArithmeticalDSS.ih.
Referenced by DGtal::Display2DFactory::drawAsDigitalPoints().
 {
   ConstIterator it(&myDSL, myL);
   it++;
   return it;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::equalsTo (const ArithmeticalDSS< TCoordinate, TInteger, adjacency > & aOther) const inline
Equality.
Parameters
aOther the object to compare with.
Returns
'true' if all the members of the two objects are equal, 'false' otherwise
Definition at line 206 of file ArithmeticalDSS.ih.
References DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myDSL, DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myF, DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myL, DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myLf, DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myLl, DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myUf, and DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myUl.
 {
   return ( (myUf == aOther.myUf) &&
            (myUl == aOther.myUl) &&
            (myLf == aOther.myLf) &&
            (myLl == aOther.myLl) &&
            (myF == aOther.myF) &&
            (myL == aOther.myL) &&
            (myDSL.equalsTo(aOther.myDSL)) );
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::extendBack (const Point & aNewPoint) inline
Tests whether the union between a point, which is located at the back of the DSS, and the DSS is still a DSS. Computes the parameters of the new DSS with the adding point if true.
Parameters
aNewPoint the point to add
Returns
'true' if the union is a DSS, 'false' otherwise.
See also
isExtendableBack extendFront
Definition at line 699 of file ArithmeticalDSS.ih.
References DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::extendFront(), and DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::negate().
 {
   //call extendFront to the opposite
   DGtal::ArithmeticalDSS<TCoordinate, TInteger, adjacency> opposite = negate();
   bool flag = opposite.extendFront(aNewPoint);
   if (flag) //update '*this' if required
     *this = opposite.negate();
   return flag;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::extendFront (const Point & aNewPoint) inline
Tests whether the union between a point, which is located at the front of the DSS, and the DSS is still a DSS. Computes the parameters of the new DSS with the adding point if true.
Parameters
aNewPoint the point to add
Returns
'true' if the union is a DSS, 'false' otherwise.
See also
isExtendableFront extendBack
Definition at line 608 of file ArithmeticalDSS.ih.
References DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency >::shift(), and DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency >::steps().
Referenced by DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::extendBack().
 {
   //true if the DSS can be extended to aNewPoint
   //false otherwise
   bool flag = true;
   //code that tells how to update the DSS
   unsigned short int res = isExtendableFront(aNewPoint);
   switch (res)
     {
     case 1: //first step init
       myDSL.mySteps.first[0] = (aNewPoint[0] - myL[0]);
       myDSL.mySteps.first[1] = (aNewPoint[1] - myL[1]);
       myDSL.myA = myDSL.mySteps.first[1];
       myDSL.myB = myDSL.mySteps.first[0];
       myDSL.myLowerBound = remainder(myUf); //myUf doesn't change
       myDSL.myUpperBound = remainder(myLf); //myLf doesn't change
       myL = aNewPoint;
       myUl = aNewPoint;
       myLl = aNewPoint;
       myDSL.myShift = DGtal::ArithmeticalDSLKernel<TCoordinate,adjacency>::shift(myDSL.myA, myDSL.myB);
       break;
     case 2: //first step repeated
       myL = aNewPoint;
       myUl = aNewPoint;
       myLl = aNewPoint;
       break;
     case 3: //second step init on the left
       myDSL.myA = ((myUl[1] - myUf[1]) + (aNewPoint[1] - myL[1]));
       myDSL.myB = ((myUl[0] - myUf[0]) + (aNewPoint[0] - myL[0]));
       myDSL.myLowerBound = remainder(myUf); //myUf doesn't change
       myDSL.myUpperBound = remainder(myLl); //myLl doesn't change
       myL = aNewPoint;
       myUl = aNewPoint;
       myLf = myLl;
       myDSL.mySteps = DGtal::ArithmeticalDSLKernel<TCoordinate,adjacency>::steps(myDSL.myA, myDSL.myB);
       myDSL.myShift = myDSL.mySteps.first-myDSL.mySteps.second;
       break;
     case 4: //second step init on the right
       myDSL.myA = ((myLl[1] - myLf[1]) + (aNewPoint[1] - myL[1]));
       myDSL.myB = ((myLl[0] - myLf[0]) + (aNewPoint[0] - myL[0]));
       myDSL.myLowerBound = remainder(myUl); //myUl doesn't change
       myDSL.myUpperBound = remainder(myLf); //myLf doesn't change
       myL = aNewPoint;
       myLl = aNewPoint;
       myUf = myUl;
       myDSL.mySteps = DGtal::ArithmeticalDSLKernel<TCoordinate,adjacency>::steps(myDSL.myA, myDSL.myB);
       myDSL.myShift = myDSL.mySteps.first-myDSL.mySteps.second;
       break;
     case 5: //weakly interior on the left
       myL = aNewPoint;
       myUl = aNewPoint;
       break;
     case 6: //weakly interior on the right
       myL = aNewPoint;
       myLl = aNewPoint;
       break;
     case 7: //weakly exterior on the left
       myDSL.myA = (aNewPoint[1] - myUf[1]);
       myDSL.myB = (aNewPoint[0] - myUf[0]);
       myDSL.myLowerBound = remainder(myUf); //myUf doesn't change
       myDSL.myUpperBound = remainder(myLl); //myLl doesn't change
       myL = aNewPoint;
       myUl = aNewPoint;
       myLf = myLl;
       break;
     case 8: //weakly exterior on the right
       myDSL.myA = (aNewPoint[1] - myLf[1]);
       myDSL.myB = (aNewPoint[0] - myLf[0]);
       myDSL.myLowerBound = remainder(myUl); //myUl doesn't change
       myDSL.myUpperBound = remainder(myLf); //myLf doesn't change
       myL = aNewPoint;
       myLl = aNewPoint;
       myUf = myUl;
       break;
     case 9: //strongly interior
       myL = aNewPoint;
       break;
     default:
       flag = false;
     }
   return flag;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Point DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::front () const inline
Returns
front point of the DSS, ie. last visited point equal to * - - ArithmeticalDSS::end()
Definition at line 329 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSSCheck::checkAll(), DGtal::ArithmeticalDSSCheck::checkOnePoint(), DGtal::ArithmeticalDSSCheck::checkPointsPosition(), DGtal::ArithmeticalDSSCheck::checkPointsRemainder(), and DGtal::Display2DFactory::drawAsBoundingBox().
 {
   return myL;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> unsigned short int DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::isExtendableBack (const Point & aNewPoint) const inline
Tests whether the union between a new point, which is located at the back of the DSS, and the DSS is still a DSS.
Parameters
aNewPoint the point to test
Returns
an integer equal to 0 if the union between aNewPoint and the segment is not a DSS, but strictly greater than 0 otherwise. The value gives the way of updating the members of the DSS: 1: initialization of the first step 2: repetition of the first step 3: initialization of the second step on the left 4: initialization of the second step on the right 5: weakly interior on the left 6: weakly interior on the right 7: weakly exterior on the left 8: weakly exterior on the right 9: strongly interior, nothing to update
See also
extend isExtendableFront
Definition at line 598 of file ArithmeticalDSS.ih.
 {
   return negate().isExtendableFront( aNewPoint );
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> unsigned short int DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::isExtendableFront (const Point & aNewPoint) const inline
Tests whether the union between a new point, which is located at the front of the DSS, and the DSS is still a DSS.
Parameters
aNewPoint a point to test
Returns
an integer equal to 0 if the union between aNewPoint and the segment is not a DSS, but strictly greater than 0 otherwise. The value gives the way of updating the members of the DSS: 1: initialization of the first step 2: repetition of the first step 3: initialization of the second step on the left 4: initialization of the second step on the right 5: weakly interior on the left 6: weakly interior on the right 7: weakly exterior on the left 8: weakly exterior on the right 9: strongly interior, nothing to update
See also
extend isExtendableBack
Definition at line 512 of file ArithmeticalDSS.ih.
References DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency >::norm().
 {
   Vector step = aNewPoint - myL;
   Coordinate deviation = DGtal::ArithmeticalDSLKernel<TCoordinate,adjacency>::norm(step[0], step[1]);
   //if the two last points are confounded OK
   if (deviation == NumberTraits<Coordinate>::ZERO)
     return 9;
   //if the two last points are not connected KO
   else if (deviation > NumberTraits<Coordinate>::ONE)
     return 0;
   //if the first step does not exist yet OK
   else if ( (myDSL.mySteps.first[0] == NumberTraits<Coordinate>::ZERO)
             &&(myDSL.mySteps.first[1] == NumberTraits<Coordinate>::ZERO) )
     return 1;
   //if the first step exists and
   //if the second step does not exist
   else if ( (myDSL.mySteps.second[0] == NumberTraits<Coordinate>::ZERO)
             &&(myDSL.mySteps.second[1] == NumberTraits<Coordinate>::ZERO) )
     {
       //if the first step exists and is repeated OK
       if (step == myDSL.mySteps.first)
         return 2;
       else
         {
           //if the two steps are compatible OK
           Vector v = step - myDSL.mySteps.first;
           if ( DGtal::ArithmeticalDSLKernel<TCoordinate,DGtal::ArithmeticalDSLKernel<TCoordinate,adjacency>::BackgroundAdjacency>
                ::norm(v[0], v[1]) == NumberTraits<Coordinate>::ONE )
             {
               Integer r = remainder(aNewPoint);
               //if weakly exterior on the left
               if (r == myDSL.myLowerBound-NumberTraits<Integer>::ONE)
                 return 3;
               //if weakly exterior on the right
               else
                 {
                   ASSERT(r == myDSL.myUpperBound+NumberTraits<Integer>::ONE);
                   return 4;
                 }
             }
           else
             return 0;
         }
     }
   //if the two steps are initialized
   else
     {
       //if there are only two steps
       if ( (step == myDSL.mySteps.first) || (step == myDSL.mySteps.second ) )
         {
         Integer r = remainder(aNewPoint);
         //if strongly exterior KO
         if ( (r < myDSL.myLowerBound-NumberTraits<Integer>::ONE)
              ||(r > myDSL.myUpperBound+NumberTraits<Integer>::ONE) )
           return 0;
         //otherwise OK
         else
           {
             if (r == myDSL.myLowerBound)
               return 5;
             else if (r == myDSL.myUpperBound)
               return 6;
             else if (r == myDSL.myLowerBound-NumberTraits<Integer>::ONE)
               return 7;
             else if (r == myDSL.myUpperBound+NumberTraits<Integer>::ONE)
               return 8;
             else
               return 9;
           }
         }
       //if there are more than two steps KO
       else
         return 0;
   }
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::isInDSL (const Point & aPoint) const inline
Returns
'true' if aPoint is in the DSL of minimal parameters containing this segment, 'false' otherwise.
Parameters
aPoint any point
Definition at line 419 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSSCheck::checkPointsRemainder().
 {
   return myDSL(aPoint);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::isInDSS (const Point & aPoint) const inline
Returns
'true' if aPoint is in the DSS 'false' otherwise.
Parameters
aPoint any point
Definition at line 428 of file ArithmeticalDSS.ih.
 {
   if (isInDSL(aPoint))
     {
       Integer s = position(aPoint);
       Integer s1 = position(myF);
       Integer s2 = position(myL);
       if (s1 == s2)
         return (aPoint == myF);
       else if (s1 < s2)
         return ( (s >= s1)&&(s <= s2) );
       else
         return ( (s >= s2)&&(s <= s1) );
     }
   else
     return false;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
NB: in O(log(max(|myA |,| myB |)))
Definition at line 248 of file ArithmeticalDSS.ih.
References DGtal::ArithmeticalDSSCheck::checkAll().
 {
   return ArithmeticalDSSCheck::checkAll(*this);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Point DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Lf () const inline
Returns
first lower leaning point of the DSS
Definition at line 356 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSSCheck::checkOnePoint(), DGtal::ArithmeticalDSSCheck::checkPointsPosition(), DGtal::ArithmeticalDSSCheck::checkPointsRemainder(), and DGtal::Display2DFactory::drawAsBoundingBox().
 {
   return myLf;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Point DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Ll () const inline
Returns
last lower leaning point of the DSS
Definition at line 365 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSSCheck::checkOnePoint(), DGtal::ArithmeticalDSSCheck::checkPointsPosition(), and DGtal::ArithmeticalDSSCheck::checkPointsRemainder().
 {
   return myLl;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Integer DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::mu () const inline
Returns
mu parameter, the intercept of the bounding DSL of minimal parameters
Definition at line 284 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSSCheck::checkOnePoint(), and DGtal::ArithmeticalDSSCheck::checkPointsRemainder().
 {
   return myDSL.mu();
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency > DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::negate () const inline
Returns a copy of '*this' with a reverse orientation, ie. with parameters -myA , -myB , -myUpperBound , -myLowerBound and swapped leaning points.
Returns
the negation of '*this'.
Definition at line 192 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSSFactory< TCoordinate, TInteger, adjacency >::createReversedPattern(), DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::extendBack(), DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::operator==(), and DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::retractFront().
 {
   return ArithmeticalDSS(-myDSL.myA, -myDSL.myB,
                          -myDSL.myUpperBound, -myDSL.myLowerBound,
                          myL, myF, myLl, myLf, myUl, myUf,
                          std::make_pair(-myDSL.mySteps.first, -myDSL.mySteps.second),
                          -myDSL.myShift);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Integer DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::omega () const inline
Returns
omega parameter, the thickness of the bounding DSL of minimal parameters
Definition at line 293 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSSCheck::checkOnePoint(), and DGtal::ArithmeticalDSSCheck::checkPointsRemainder().
 {
   return myDSL.omega();
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::operator!= (const ArithmeticalDSS< TCoordinate, TInteger, adjacency > & aOther) const inline
Difference.
Parameters
aOther the object to compare with.
Returns
'true' the two set of points that are implicitly defined are different, 'false' otherwise
Definition at line 232 of file ArithmeticalDSS.ih.
 {
   return !( operator==(aOther) );
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::operator() (const Point & aPoint) const inline
Returns
'true' if aPoint is in the DSS 'false' otherwise.
Parameters
aPoint any point
See also
isInDSS
Definition at line 451 of file ArithmeticalDSS.ih.
 {
   return isInDSS(aPoint);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency > & DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::operator= (const ArithmeticalDSS< TCoordinate, TInteger, adjacency > & aOther) inline
Assignment.
Parameters
aOther the object to copy.
Returns
a reference on 'this'.
Definition at line 172 of file ArithmeticalDSS.ih.
References DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myDSL, DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myF, DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myL, DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myLf, DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myLl, DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myUf, and DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myUl.
 {
   if ( this != &aOther )
     {
       myF = aOther.myF;
       myL = aOther.myL;
       myUf = aOther.myUf;
       myLf = aOther.myLf;
       myUl = aOther.myUl;
       myLl = aOther.myLl;
       myDSL = aOther.myDSL;
     }
   return *this;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::operator== (const ArithmeticalDSS< TCoordinate, TInteger, adjacency > & aOther) const inline
Equality.
Parameters
aOther the object to compare with.
Returns
'true' the two sets of points that are implicitly defined are equal (without respect to the orientation), 'false' otherwise
Definition at line 222 of file ArithmeticalDSS.ih.
References DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::negate().
 {
   return ( equalsTo(aOther) || equalsTo(aOther.negate()) );
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Integer DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::orthogonalPosition (const Point & aPoint) const inline
Returns the position of aPoint (which does not necessarily belong to the DSS) computed along the direction that is orthogonal to the direction vector
Parameters
aPoint the point whose position is returned
Returns
the position
Definition at line 383 of file ArithmeticalDSS.ih.
 {
   return myDSL.orthogonalPosition(aPoint);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Position DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::position (const Point & aPoint) const inline
Returns the position of aPoint (which does not necessarily belong to the DSS) computed along the direction given by myShift
Parameters
aPoint the point whose position is returned
Returns
the position
Definition at line 392 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSSCheck::checkPointsPosition().
 {
   return myDSL.position(aPoint);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::PointD DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::project (const Point & aM, double aR) const inline
Projects the point aM onto the straight line whose points have remainder aR.
Parameters
aM any point (may not be part of the DSS).
aR the remainder (may not be an integer).
Returns
the projected point.
Definition at line 852 of file ArithmeticalDSS.ih.
References DGtal::NumberTraits< T >::castToDouble().
Referenced by DGtal::Display2DFactory::drawAsBoundingBox().
 {
   //casts
   double aa = NumberTraits<Coordinate>::castToDouble(myDSL.myA);
   double bb = NumberTraits<Coordinate>::castToDouble(myDSL.myB);
   double xm = NumberTraits<Integer>::castToDouble(aM[0]);
   double ym = NumberTraits<Integer>::castToDouble(aM[1]);
   //computation
   double d2 = ( aa * aa + bb * bb );
   double s = bb * xm + aa * ym;
   double xp = ( bb * s + aa * aR ) / d2;
   double yp = ( aa * s - bb * aR ) / d2;
   return PointD( xp, yp );
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::PointD DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::project (const Point & aM, const Point & aP) const inline
Projects the point aM onto the straight line going through point aP.
Parameters
aM any point (may not be part of the DSS).
aP any point (may not be part of the DSS).
Returns
the projected point.
Definition at line 874 of file ArithmeticalDSS.ih.
References DGtal::NumberTraits< T >::castToDouble().
 {
   double r = NumberTraits<Integer>::castToDouble(remainder(aP));
   return project(aM,r);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::ConstReverseIterator DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::rbegin () const inline
Returns
begin reverse iterator, which points to the point returned by ArithmeticalDSS::front()
Definition at line 480 of file ArithmeticalDSS.ih.
 {
   return ConstReverseIterator( end() );
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Integer DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::remainder (const Point & aPoint) const inline
Returns the remainder of aPoint (which does not necessarily belong to the DSS)
Returns
remainder of aPoint
Parameters
aPoint any point
Definition at line 374 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSSCheck::checkPointsRemainder().
 {
   return myDSL.remainder(aPoint);
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::ConstReverseIterator DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::rend () const inline
Returns
end iterator, which points before the point returned by ArithmeticalDSS::back()
Definition at line 489 of file ArithmeticalDSS.ih.
 {
   return ConstReverseIterator( begin() );
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::retractBack () inline
Removes the back point of the DSS if it remains strictly more than one point
Returns
'true' if the retraction has been done, 'false' otherwise
See also
retract
Definition at line 733 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::retractFront().
 {
   if (myF == myL)
     return false;
   else
     {
       //next point computation
       Point next = *++begin();
       //if the next point is the last one
       if (next == myL)
         {
           *this = ArithmeticalDSS(next);
           return true;
         }
       //otherwise
       else
         {
           //points used to update the DSS
           Point bezoutPoint;
           //leaning points / parameters update
           if (myF == myUf)
             {
               bezoutPoint = myUf + myDSL.myShift;
               if ( retractUpdateLeaningPoints( Vector(myDSL.myB, myDSL.myA),
                                                next, myL,
                                                bezoutPoint,
                                                myLf, myLl,
                                                myUf, myUl ) )
                 retractUpdateParameters( myLf - bezoutPoint );
             }
           if (myF == myLf)
             {
               bezoutPoint = myLf - myDSL.myShift;
               if ( retractUpdateLeaningPoints( Vector(myDSL.myB, myDSL.myA),
                                                next, myL,
                                                bezoutPoint,
                                                myUf, myUl,
                                                myLf, myLl ) )
                 retractUpdateParameters( myUf - bezoutPoint );
             }
           //first point update
           myF = next;
           return true;
         }
     }
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::retractFront () inline
Removes the front point of the DSS if it remains strictly more than one point
Returns
'true' if the retraction has been done, 'false' otherwise
See also
retract
Definition at line 716 of file ArithmeticalDSS.ih.
References DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::negate(), and DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::retractBack().
 {
   //call retractBack to the opposite
   DGtal::ArithmeticalDSS<TCoordinate, TInteger, adjacency> opposite = negate();
   bool hasBeenRetracted = opposite.retractBack();
   if (hasBeenRetracted) //update '*this' if required
     *this = opposite.negate();
   return hasBeenRetracted;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> bool DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::retractUpdateLeaningPoints (const Vector & aDirection, const Point & aFirst, const Point & aLast, const Point & aBezout, const Point & aFirstAtOppositeSide, Point & aLastAtOppositeSide, Point & aFirstAtRemovalSide, const Point & aLastAtRemovalSide) inline protected
Updates the leaning points of the DSS if the end point is a leaning point that has to be removed from the DSS.
Parameters
aDirection direction vector
aFirst new end of the DSS
aLast opposite end of the DSS
aBezout weakly exterior point used to compute the new slope and to update the leaning points
aFirstAtOppositeSide first leaning point located at the side that is not affected by the removal
aLastAtOppositeSide last leaning point located at the side that is not affected by the removal but that has to be updated
aFirstAtRemovalSide first leaning point that is removed and has to be updated.
aLastAtRemovalSide last leaning point located on the same side than aFirstAtRemovalSide
Returns
'true' is the slope has to be updated, 'false' otherwise
See also
retractFront retractBack
Definition at line 790 of file ArithmeticalDSS.ih.
References DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency >::norm().
 {
   if (aFirstAtOppositeSide == aLastAtOppositeSide)
     {
       Vector newDirection = aFirstAtOppositeSide - aBezout;
       Coordinate k; //number of repetition of newDirection
       Vector toLastAtRemovalSide = aLastAtRemovalSide - aFirst;
       k = DGtal::ArithmeticalDSLKernel<TCoordinate,adjacency>::norm(toLastAtRemovalSide[1], toLastAtRemovalSide[0])
         / DGtal::ArithmeticalDSLKernel<TCoordinate,adjacency>::norm(newDirection[1], newDirection[0]);
       aFirstAtRemovalSide = aLastAtRemovalSide - newDirection*k;
       Vector toLast = aLast - aFirstAtOppositeSide;
       k = DGtal::ArithmeticalDSLKernel<TCoordinate,adjacency>::norm(toLast[1], toLast[0])
         / DGtal::ArithmeticalDSLKernel<TCoordinate,adjacency>::norm(newDirection[1], newDirection[0]);
       aLastAtOppositeSide = aFirstAtOppositeSide + newDirection*k;
       return true;
     }
   else
     {
       aFirstAtRemovalSide += aDirection;
       return false;
     }
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> void DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::retractUpdateParameters (const Vector & aNewDirection) inline protected
Updates the parameters of the bounding DSL after the retraction.
Parameters
aNewDirection direction vector
See also
retractFront retractBack
Definition at line 827 of file ArithmeticalDSS.ih.
References DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency >::shift(), and DGtal::ArithmeticalDSLKernel< TCoordinate, adjacency >::steps().
 {
   //update of the slope
   myDSL.myA = aNewDirection[1];
   myDSL.myB = aNewDirection[0];
   //intercepts
   myDSL.myLowerBound = remainder(myUf);
   myDSL.myUpperBound = remainder(myLf);
   //update of the steps and shift
   if (myUf == myLf)
     {
       ASSERT( myUl == myLl );
       myDSL.mySteps = DGtal::ArithmeticalDSLKernel<TCoordinate,adjacency>::steps(myDSL.myA, myDSL.myB);
       myDSL.myShift = DGtal::ArithmeticalDSLKernel<TCoordinate,adjacency>::shift(myDSL.myA, myDSL.myB);
     }
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> void DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 498 of file ArithmeticalDSS.ih.
 {
   out << "[ArithmeticalDSS] ";
   out << myDSL;
   out << "from " << myF << " to " << myL << std::endl;
   out << "upper leaning points: " << myUf << " " << myUl << std::endl;
   out << "lower leaning points: " << myLf << " " << myLl;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Vector DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::shift () const inline
Returns
the shift vector
Definition at line 302 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSSCheck::checkOnePoint().
 {
   return myDSL.shift();
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Steps DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::steps () const inline
Returns
the couple of vectors used to iterate over the DSS point.
Definition at line 311 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSSCheck::checkOnePoint().
 {
   return myDSL.steps();
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Point DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Uf () const inline
Returns
first upper leaning point of the DSS
Definition at line 338 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSSCheck::checkOnePoint(), DGtal::ArithmeticalDSSCheck::checkPointsPosition(), DGtal::ArithmeticalDSSCheck::checkPointsRemainder(), and DGtal::Display2DFactory::drawAsBoundingBox().
 {
   return myUf;
 }
template<typename TCoordinate , typename TInteger , unsigned short adjacency> DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Point DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::Ul () const inline
Returns
last upper leaning point of the DSS
Definition at line 347 of file ArithmeticalDSS.ih.
Referenced by DGtal::ArithmeticalDSSCheck::checkOnePoint(), DGtal::ArithmeticalDSSCheck::checkPointsPosition(), and DGtal::ArithmeticalDSSCheck::checkPointsRemainder().
 {
   return myUl;
 }
Field Documentation
template<typename TCoordinate, typename TInteger, unsigned short adjacency> const unsigned short DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::foregroundAdjacency = adjacency static
Adjacency of the DSL.
Definition at line 101 of file ArithmeticalDSS.h.
template<typename TCoordinate, typename TInteger, unsigned short adjacency> DSL DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myDSL protected
Bounding DSL of minimal parameters
Definition at line 726 of file ArithmeticalDSS.h.
Referenced by DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::equalsTo(), and DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::operator=().
template<typename TCoordinate, typename TInteger, unsigned short adjacency> Point DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myF protected
First point
Definition at line 700 of file ArithmeticalDSS.h.
Referenced by DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::equalsTo(), and DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::operator=().
template<typename TCoordinate, typename TInteger, unsigned short adjacency> Point DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myL protected
Last point
Definition at line 704 of file ArithmeticalDSS.h.
Referenced by DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::equalsTo(), and DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::operator=().
template<typename TCoordinate, typename TInteger, unsigned short adjacency> Point DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myLf protected
First lower leaning point (of remainder myMu + myOmega - 1)
Definition at line 716 of file ArithmeticalDSS.h.
Referenced by DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::equalsTo(), and DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::operator=().
template<typename TCoordinate, typename TInteger, unsigned short adjacency> Point DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myLl protected
Last lower leaning point (of remainder myMu + myOmega - 1)
Definition at line 720 of file ArithmeticalDSS.h.
Referenced by DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::equalsTo(), and DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::operator=().
template<typename TCoordinate, typename TInteger, unsigned short adjacency> Point DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myUf protected
First upper leaning point (of remainder myMu)
Definition at line 708 of file ArithmeticalDSS.h.
Referenced by DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::equalsTo(), and DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::operator=().
template<typename TCoordinate, typename TInteger, unsigned short adjacency> Point DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::myUl protected
Last upper leaning point (of remainder myMu)
Definition at line 712 of file ArithmeticalDSS.h.
Referenced by DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::equalsTo(), and DGtal::ArithmeticalDSS< TCoordinate, TInteger, adjacency >::operator=().
The documentation for this class was generated from the following files:
ArithmeticalDSL.h
ArithmeticalDSS.h
ArithmeticalDSS.ih