DGtal: DGtal::ConceptUtils Namespace Reference
DGtal::ConceptUtils Namespace Reference
Data Structures
struct CheckFalse
struct CheckTag
struct CheckTrue
struct CheckTrue< TagTrue >
struct CheckTrueOrFalse
struct CheckUnknown
struct CheckUnknown< TagUnknown >
struct SameType
struct SameType< T, T >
Functions
template<typename T >
void sameType (const T &t1, const T &t2)
void checkTrue (const TagTrue &tag)
void checkFalse (const TagFalse &tag)
void checkUnknown (const TagUnknown &tag)
void checkTag (const TagUnknown &tag)
void checkTag (const TagTrue &tag)
void checkTag (const TagFalse &tag)
void checkTrueOrFalse (const TagFalse &tag)
void checkTrueOrFalse (const TagTrue &tag)
Detailed Description
Aim: Gathers several functions useful for concept checks.
Description of namespace 'ConceptUtils'
Function Documentation
void DGtal::ConceptUtils::checkFalse (const TagFalse & tag)
Type deduction will fail unless the argument type is exactly TagFalse.
Parameters
tag the type to check.
void DGtal::ConceptUtils::checkTag (const TagUnknown & tag)
Type deduction will fail unless the argument type is a tag (TagTrue, TagFalse or TagUnknown).
Parameters
tag the type to check.
void DGtal::ConceptUtils::checkTag (const TagTrue & tag)
Type deduction will fail unless the argument type is a tag (TagTrue, TagFalse or TagUnknown).
Parameters
tag the type to check.
void DGtal::ConceptUtils::checkTag (const TagFalse & tag)
Type deduction will fail unless the argument type is a tag (TagTrue, TagFalse or TagUnknown).
Parameters
tag the type to check.
void DGtal::ConceptUtils::checkTrue (const TagTrue & tag)
Type deduction will fail unless the argument type is exactly TagTrue.
Parameters
tag the type to check.
Referenced by DGtal::concepts::CUnsignedNumber< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CBoundedNumber< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CSignedNumber< T >::BOOST_CONCEPT_USAGE(), and DGtal::concepts::CIntegralNumber< T >::BOOST_CONCEPT_USAGE().
void DGtal::ConceptUtils::checkTrueOrFalse (const TagFalse & tag)
Type deduction will fail unless the argument type is the tag TagTrue or TagFalse.
Parameters
tag the type to check.
void DGtal::ConceptUtils::checkTrueOrFalse (const TagTrue & tag)
Type deduction will fail unless the argument type is the tag TagTrue or TagFalse.
Parameters
tag the type to check.
void DGtal::ConceptUtils::checkUnknown (const TagUnknown & tag)
Type deduction will fail unless the argument type is exactly TagUnknown.
Parameters
tag the type to check.
template<typename T > void DGtal::ConceptUtils::sameType (const T & t1, const T & t2)
Type deduction will fail unless the arguments have the same type.
Parameters
t1 some object of type T.
t2 some object of type T.
Referenced by DGtal::CDynamicBidirectionalSegmentComputer< T >::BOOST_CONCEPT_USAGE(), DGtal::CDynamicSegmentComputer< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CEuclideanRing< T >::BOOST_CONCEPT_USAGE(), DGtal::CUnaryFunctor< T, T::Point, bool >::BOOST_CONCEPT_USAGE(), DGtal::CBidirectionalSegmentComputer< T >::BOOST_CONCEPT_USAGE(), DGtal::CSinglePassRangeWithWritableIterator< T, Value >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CStaticMatrix< T >::BOOST_CONCEPT_USAGE(), DGtal::CSinglePassRangeFromPoint< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CStaticVector< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CDigitalBoundedShape< TShape >::BOOST_CONCEPT_USAGE(), DGtal::CTrivialConstImage< I >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CDigitalOrientedShape< T >::BOOST_CONCEPT_USAGE(), DGtal::CImageFactory< T >::BOOST_CONCEPT_USAGE(), DGtal::CSinglePassRangeWithWritableIteratorFromPoint< T, Value >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CEuclideanOrientedShape< T >::BOOST_CONCEPT_USAGE(), DGtal::CImageCacheReadPolicy< T >::BOOST_CONCEPT_USAGE(), DGtal::CBidirectionalRangeWithWritableIterator< T, Value >::BOOST_CONCEPT_USAGE(), DGtal::CBidirectionalRangeWithWritableIteratorFromPoint< T, Value >::BOOST_CONCEPT_USAGE(), DGtal::CSegmentFactory< T >::BOOST_CONCEPT_USAGE(), DGtal::CColorMap< CMap >::BOOST_CONCEPT_USAGE(), DGtal::CDrawableWithViewer3D< T, S, KS >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CEuclideanBoundedShape< TShape >::BOOST_CONCEPT_USAGE(), DGtal::CDrawableWithBoard3DTo2D< T, S, KS >::BOOST_CONCEPT_USAGE(), DGtal::CDrawableWithDisplay3D< T, S, KS >::BOOST_CONCEPT_USAGE(), DGtal::CConstImage< I >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CCommutativeRing< T >::BOOST_CONCEPT_USAGE(), DGtal::CBidirectionalRangeFromPoint< T >::BOOST_CONCEPT_USAGE(), DGtal::deprecated::CConvolutionWeights< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CVertexMap< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CAdditivePrimitiveComputer< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CDomainAdjacency< T >::BOOST_CONCEPT_USAGE(), DGtal::CDrawableWithBoard2D< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CIncrementalPrimitiveComputer< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CNormalVectorEstimator< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CAdjacency< T >::BOOST_CONCEPT_USAGE(), DGtal::CGlobalGeometricEstimator< T >::BOOST_CONCEPT_USAGE(), DGtal::CSegment< T >::BOOST_CONCEPT_USAGE(), DGtal::CCurveLocalGeometricEstimator< T >::BOOST_CONCEPT_USAGE(), DGtal::CImage< I >::BOOST_CONCEPT_USAGE(), DGtal::CIncrementalSegmentComputer< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CLocalEstimatorFromSurfelFunctor< T >::BOOST_CONCEPT_USAGE(), DGtal::C2x2DetComputer< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CSurfelLocalEstimator< T >::BOOST_CONCEPT_USAGE(), DGtal::CUnaryFunctor< X, A &, R & >::BOOST_CONCEPT_USAGE(), DGtal::COrientationFunctor< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CSpace< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CDomain< T >::BOOST_CONCEPT_USAGE(), DGtal::CPositiveIrreducibleFraction< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CCellularGridSpaceND< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CSurfelLocalEstimator< T >::check_const_constraints(), DGtal::CConstSinglePassRangeFromPoint< T, Value >::checkConstConstraints(), DGtal::concepts::CPowerSeparableMetric< T >::checkConstConstraints(), DGtal::CConstBidirectionalRangeFromPoint< T >::checkConstConstraints(), DGtal::concepts::CWithGradientMap< T >::checkConstConstraints(), DGtal::concepts::CImplicitFunctionDiff1< T >::checkConstConstraints(), DGtal::concepts::CMatrix< T >::checkConstConstraints(), DGtal::concepts::CVector< T >::checkConstConstraints(), DGtal::concepts::CPrimitiveComputer< T >::checkConstConstraints(), DGtal::concepts::CDigitalSurfaceTracker< T >::checkConstConstraints(), DGtal::concepts::CSeparableMetric< T >::checkConstConstraints(), DGtal::concepts::CAdditivePrimitiveComputer< T >::checkConstConstraints(), DGtal::concepts::CIncrementalPrimitiveComputer< T >::checkConstConstraints(), DGtal::concepts::CBinner< T >::checkConstConstraints(), DGtal::concepts::CPointEmbedder< T >::checkConstConstraints(), DGtal::concepts::CCellEmbedder< T >::checkConstConstraints(), DGtal::concepts::CSCellEmbedder< T >::checkConstConstraints(), DGtal::concepts::CPowerMetric< T >::checkConstConstraints(), DGtal::concepts::CDigitalSurfaceEmbedder< T >::checkConstConstraints(), DGtal::concepts::CUndirectedSimpleGraph< T >::checkConstConstraints(), DGtal::concepts::CUndirectedSimpleLocalGraph< Adj >::checkConstConstraints(), DGtal::concepts::CMetricSpace< T >::checkConstConstraints(), DGtal::concepts::CGraphVisitor< T >::checkConstConstraints(), DGtal::concepts::CDigitalSurfaceContainer< T >::checkConstConstraints(), DGtal::concepts::CDigitalSet< T >::checkConstConstraints(), DGtal::CPositiveIrreducibleFraction< T >::checkConstConstraints(), DGtal::concepts::CCellularGridSpaceND< T >::checkConstConstraints(), and DGtal::concepts::CDigitalSet< T >::checkNonConstConstraints().