DGtal: DGtal::CSCellEmbedder< T > Struct Template Reference
DGtal::CSCellEmbedder< T > Struct Template Reference
DGtal Concepts
#include <topology/CSCellEmbedder.h>
Public Types
typedef T::KSpace KSpace
typedef T::SCell SCell
typedef T::RealPoint RealPoint
typedef T::Argument Argument
typedef T::Value Value
Public Member Functions
BOOST_CONCEPT_ASSERT ((CCellularGridSpaceND< KSpace >))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< SCell, typename KSpace::SCell >::value))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< SCell, Argument >::value))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< RealPoint, Value >::value))
BOOST_CONCEPT_USAGE (CSCellEmbedder)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::CUnaryFunctor< T, T::SCell, T::RealPoint >
BOOST_CONCEPT_USAGE (CUnaryFunctor)
Private Attributes
T myX
SCell myP
RealPoint myRP
const KSpace myK
Detailed Description
template<typename T>
struct DGtal::CSCellEmbedder< T >
Aim: A cell embedder is a mapping from signed cells to Euclidean points. It adds inner types to functor.
Description of concept 'CSCellEmbedder'
Refinement of
CUnaryFunctor<T, T::SCell, T::RealPoint>
Associated types :
KSpace: the cellular grid space
SCell: same as KSpace::SCell
RealPoint: the type of Euclidean point
Argument: type of the argument, same as KSpace::SCell
Value: type of value, same as RealPoint
Notation
X : A type that is a model of CSCellEmbedder
x : object of type X
p : object of type SCell
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
Apply function x(p) Value return the value of the function x on argument p
Khalimsky space x.space()) const KSpace & return a reference to the the Kalimsky space
Invariants
Models
CanonicSCellEmbedder, CanonicDigitalSurfaceEmbedder, DigitalSurfaceEmbedderWithNormalVectorEstimator
Notes
Template Parameters
T the type that should be a model of CSCellEmbedder.
Definition at line 96 of file CSCellEmbedder.h.
Member Typedef Documentation
template<typename T > typedef T::Argument DGtal::CSCellEmbedder< T >::Argument
Definition at line 103 of file CSCellEmbedder.h.
template<typename T > typedef T::KSpace DGtal::CSCellEmbedder< T >::KSpace
Definition at line 100 of file CSCellEmbedder.h.
template<typename T > typedef T::RealPoint DGtal::CSCellEmbedder< T >::RealPoint
Definition at line 102 of file CSCellEmbedder.h.
template<typename T > typedef T::SCell DGtal::CSCellEmbedder< T >::SCell
Definition at line 101 of file CSCellEmbedder.h.
template<typename T > typedef T::Value DGtal::CSCellEmbedder< T >::Value
Definition at line 104 of file CSCellEmbedder.h.
Member Function Documentation
template<typename T > DGtal::CSCellEmbedder< T >::BOOST_CONCEPT_ASSERT ((CCellularGridSpaceND< KSpace >))
template<typename T > DGtal::CSCellEmbedder< T >::BOOST_CONCEPT_USAGE (CSCellEmbedder< T >) inline
Definition at line 110 of file CSCellEmbedder.h.
References DGtal::CSCellEmbedder< T >::checkConstConstraints().
   {
     checkConstConstraints();
   }
template<typename T > DGtal::CSCellEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< SCell, typename KSpace::SCell >::value))
template<typename T > DGtal::CSCellEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< SCell, Argument >::value))
template<typename T > DGtal::CSCellEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< RealPoint, Value >::value))
template<typename T > void DGtal::CSCellEmbedder< T >::checkConstConstraints () const inline
Definition at line 115 of file CSCellEmbedder.h.
References DGtal::CSCellEmbedder< T >::myK, DGtal::CSCellEmbedder< T >::myP, DGtal::CSCellEmbedder< T >::myRP, DGtal::CSCellEmbedder< T >::myX, and DGtal::ConceptUtils::sameType().
Referenced by DGtal::CSCellEmbedder< T >::BOOST_CONCEPT_USAGE().
   { // operator()
     ConceptUtils::sameType( myRP, myX( myP ) );
     ConceptUtils::sameType( myK, myX.space() );
   }
Field Documentation
template<typename T > const KSpace DGtal::CSCellEmbedder< T >::myK private
Definition at line 125 of file CSCellEmbedder.h.
Referenced by DGtal::CSCellEmbedder< T >::checkConstConstraints().
template<typename T > SCell DGtal::CSCellEmbedder< T >::myP private
Definition at line 123 of file CSCellEmbedder.h.
Referenced by DGtal::CSCellEmbedder< T >::checkConstConstraints().
template<typename T > RealPoint DGtal::CSCellEmbedder< T >::myRP private
Definition at line 124 of file CSCellEmbedder.h.
Referenced by DGtal::CSCellEmbedder< T >::checkConstConstraints().
template<typename T > T DGtal::CSCellEmbedder< T >::myX private
Definition at line 122 of file CSCellEmbedder.h.
Referenced by DGtal::CSCellEmbedder< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CSCellEmbedder.h