DGtal: DGtal::KFormStyle2D Struct Reference
DGtal::KFormStyle2D Struct Reference
Public Member Functions
KFormStyle2D (const double &_cmap_min=0, const double &_cmap_max=0, const ColorGradientPreset &_cmap_preset=CMAP_JET, const int &_cmap_repeat=0)
virtual void setStyle (Board2D &aBoard) const
Public Member Functions inherited from DGtal::DrawableWithBoard2D
virtual ~DrawableWithBoard2D ()
Data Fields
double cmap_min
double cmap_max
ColorGradientPreset cmap_preset
int cmap_repeat
Detailed Description
Default styles.
Definition at line 62 of file Style2DFactory.ih.
Constructor & Destructor Documentation
DGtal::KFormStyle2D::KFormStyle2D (const double & _cmap_min = 0, const double & _cmap_max = 0, const ColorGradientPreset & _cmap_preset = CMAP_JET, const int & _cmap_repeat = 0) inline
Definition at line 69 of file Style2DFactory.ih.
           : DrawableWithBoard2D(), cmap_min(_cmap_min), cmap_max(_cmap_max), cmap_preset(_cmap_preset), cmap_repeat(_cmap_repeat)
       {
       }
Member Function Documentation
virtual void DGtal::KFormStyle2D::setStyle (Board2D &) const inline virtual
Operation to override. Does nothing by default.
Reimplemented from DGtal::DrawableWithBoard2D.
Definition at line 74 of file Style2DFactory.ih.
References LibBoard::Board::setFillColorRGBi(), LibBoard::Board::setLineStyle(), LibBoard::Board::setLineWidth(), LibBoard::Board::setPenColorRGBi(), and LibBoard::Shape::SolidStyle.
       {
           aBoard.setPenColorRGBi(0,0,0);
           aBoard.setLineStyle(Board2D::Shape::SolidStyle);
           aBoard.setFillColorRGBi(0,0,0);
           aBoard.setLineWidth(1);
       }
Field Documentation
double DGtal::KFormStyle2D::cmap_max
Definition at line 65 of file Style2DFactory.ih.
Referenced by DGtal::Display2DFactory::draw().
double DGtal::KFormStyle2D::cmap_min
Definition at line 64 of file Style2DFactory.ih.
Referenced by DGtal::Display2DFactory::draw().
ColorGradientPreset DGtal::KFormStyle2D::cmap_preset
Definition at line 66 of file Style2DFactory.ih.
Referenced by DGtal::Display2DFactory::draw().
int DGtal::KFormStyle2D::cmap_repeat
Definition at line 67 of file Style2DFactory.ih.
Referenced by DGtal::Display2DFactory::draw().
The documentation for this struct was generated from the following file:
Style2DFactory.ih