DGtal: DGtal::DefaultDrawStyleFilled_LatticePolytope2D Struct Reference
DGtal::DefaultDrawStyleFilled_LatticePolytope2D Struct Reference
Public Member Functions
virtual void setStyle (Board2D &aBoard) const
Public Member Functions inherited from DGtal::DrawableWithBoard2D
virtual ~DrawableWithBoard2D ()
Detailed Description
Definition at line 493 of file Style2DFactory.ih.
Member Function Documentation
virtual void DGtal::DefaultDrawStyleFilled_LatticePolytope2D::setStyle (Board2D &) const inline virtual
Operation to override. Does nothing by default.
Reimplemented from DGtal::DrawableWithBoard2D.
Definition at line 495 of file Style2DFactory.ih.
References LibBoard::Board::setFillColorRGBi(), LibBoard::Board::setLineStyle(), LibBoard::Board::setLineWidth(), LibBoard::Board::setPenColorRGBi(), and LibBoard::Shape::SolidStyle.
     {
       aBoard.setPenColorRGBi( 30, 30, 30 );
       aBoard.setLineStyle( Board2D::Shape::SolidStyle );
       aBoard.setFillColorRGBi( 200, 200, 200 );
       aBoard.setLineWidth( 2 );
     }
The documentation for this struct was generated from the following file:
Style2DFactory.ih