DGtal: DGtal::CCellEmbedder< T > Struct Template Reference
DGtal::CCellEmbedder< T > Struct Template Reference
DGtal Concepts
#include <topology/CCellEmbedder.h>
Public Types
typedef T::KSpace KSpace
typedef T::Cell Cell
typedef T::RealPoint RealPoint
typedef T::Argument Argument
typedef T::Value Value
Public Member Functions
BOOST_CONCEPT_ASSERT ((CCellularGridSpaceND< KSpace >))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Cell, typename KSpace::Cell >::value))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Cell, Argument >::value))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< RealPoint, Value >::value))
BOOST_CONCEPT_USAGE (CCellEmbedder)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::CUnaryFunctor< T, T::Cell, T::RealPoint >
BOOST_CONCEPT_USAGE (CUnaryFunctor)
Private Attributes
T myX
Cell myP
RealPoint myRP
Detailed Description
template<typename T>
struct DGtal::CCellEmbedder< T >
Aim: A cell embedder is a mapping from unsigned cells to Euclidean points. It adds inner types to functor.
Description of concept 'CCellEmbedder'
Refinement of
CUnaryFunctor<T, T::Cell, T::RealPoint>
Associated types :
KSpace: the cellular grid space
Cell: same as KSpace::Cell
RealPoint: the type of Euclidean point
Argument: type of the argument, same as KSpace::Cell
Value: type of value, same as RealPoint
Notation
X : A type that is a model of CCellEmbedder
x : object of type X
p : object of type Cell
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
Apply function x(p) Value return the value of the function x on argument p
Invariants
Models
CanonicCellEmbedder, ImageLinearCellEmbedder, ImplicitFunctionLinearCellEmbedder, ImplicitFunctionDiff1LinearCellEmbedder
Notes
Template Parameters
T the type that should be a model of CCellEmbedder.
Definition at line 95 of file CCellEmbedder.h.
Member Typedef Documentation
template<typename T > typedef T::Argument DGtal::CCellEmbedder< T >::Argument
Definition at line 102 of file CCellEmbedder.h.
template<typename T > typedef T::Cell DGtal::CCellEmbedder< T >::Cell
Definition at line 100 of file CCellEmbedder.h.
template<typename T > typedef T::KSpace DGtal::CCellEmbedder< T >::KSpace
Definition at line 99 of file CCellEmbedder.h.
template<typename T > typedef T::RealPoint DGtal::CCellEmbedder< T >::RealPoint
Definition at line 101 of file CCellEmbedder.h.
template<typename T > typedef T::Value DGtal::CCellEmbedder< T >::Value
Definition at line 103 of file CCellEmbedder.h.
Member Function Documentation
template<typename T > DGtal::CCellEmbedder< T >::BOOST_CONCEPT_ASSERT ((CCellularGridSpaceND< KSpace >))
template<typename T > DGtal::CCellEmbedder< T >::BOOST_CONCEPT_USAGE (CCellEmbedder< T >) inline
Definition at line 109 of file CCellEmbedder.h.
References DGtal::CCellEmbedder< T >::checkConstConstraints().
   {
     checkConstConstraints();
   }
template<typename T > DGtal::CCellEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Cell, typename KSpace::Cell >::value))
template<typename T > DGtal::CCellEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Cell, Argument >::value))
template<typename T > DGtal::CCellEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< RealPoint, Value >::value))
template<typename T > void DGtal::CCellEmbedder< T >::checkConstConstraints () const inline
Definition at line 114 of file CCellEmbedder.h.
References DGtal::CCellEmbedder< T >::myP, DGtal::CCellEmbedder< T >::myRP, DGtal::CCellEmbedder< T >::myX, and DGtal::ConceptUtils::sameType().
Referenced by DGtal::CCellEmbedder< T >::BOOST_CONCEPT_USAGE().
   { // operator()
     ConceptUtils::sameType( myRP, myX( myP ) );
   }
Field Documentation
template<typename T > Cell DGtal::CCellEmbedder< T >::myP private
Definition at line 121 of file CCellEmbedder.h.
Referenced by DGtal::CCellEmbedder< T >::checkConstConstraints().
template<typename T > RealPoint DGtal::CCellEmbedder< T >::myRP private
Definition at line 122 of file CCellEmbedder.h.
Referenced by DGtal::CCellEmbedder< T >::checkConstConstraints().
template<typename T > T DGtal::CCellEmbedder< T >::myX private
Definition at line 120 of file CCellEmbedder.h.
Referenced by DGtal::CCellEmbedder< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CCellEmbedder.h