DGtal: DGtal::CDigitalSet< T > Struct Template Reference
DGtal::CDigitalSet< T > Struct Template Reference
DGtal Concepts
#include <kernel/sets/CDigitalSet.h>
Public Types
typedef T::Domain Domain
typedef T::Point Point
typedef T::Size Size
typedef T::Iterator Iterator
typedef T::ConstIterator ConstIterator
Public Types inherited from DGtal::CPointPredicate< T >
typedef T::Point Point
Public Types inherited from DGtal::CPredicate< T, T::Point >
typedef T::Point Element
Public Member Functions
BOOST_CONCEPT_ASSERT ((CDomain< Domain >))
BOOST_CONCEPT_ASSERT ((boost_concepts::ReadableIteratorConcept< ConstIterator >))
BOOST_CONCEPT_ASSERT ((boost_concepts::BidirectionalTraversalConcept< ConstIterator >))
BOOST_STATIC_ASSERT ((boost::is_same< Iterator, ConstIterator >::value))
BOOST_CONCEPT_USAGE (CDigitalSet)
void checkConstConstraints () const
void checkNonConstConstraints ()
Public Member Functions inherited from DGtal::CPointPredicate< T >
BOOST_CONCEPT_ASSERT ((CUnaryFunctor< T, Point, bool >))
Public Member Functions inherited from DGtal::CUnaryFunctor< T, T::Point, bool >
BOOST_CONCEPT_USAGE (CUnaryFunctor)
Private Attributes
T myX
Domain myDomain
CowPtr< Domain > myDomainPtr
Size mySize
bool myBool
Point myPoint
Iterator myIterator
ConstIterator myConstIterator
Point * myOutputIt
Detailed Description
template<typename T>
struct DGtal::CDigitalSet< T >
Aim: Represents a set of points within the given domain. This set of points is modifiable by the user. It is thus very close to the STL concept of simple associative container (like set std::set<Point>), except that there is a notion of maximal set of points (the whole domain).
Description of concept 'CDigitalSet'
Refinement of
boost::CopyConstructible
CPointPredicate
Todo:
add boost::Container ? Not for now, since coding style do not match with STL (e.g. Iterator instead of iterator).
Note
It is also a refinement of boost::Assignable from CPointPredicate.
Associated types :
Domain: the domain in which points are defined, a model of concept CDomain.
Size: the type for couting elements of the set.
Iterator: the iterator type for visiting elements of the set, as well as modify the set. The iterator should be readable (model of boost_concepts::ReadableIteratorConcept) and allow bidirectional traversal (model of boost_concepts::BidirectionalTraversalConcept). Its value has type Point (defined in CPointPredicate).
ConstIterator: the type for visiting elements of the set. Note that types for Iterator and ConstIterator should be the same, similarly to STL simple associative containers.
Notation
X : A type that is a model of CDigitalSet
x, y : objects of type X
p, p1, p2 : objects of type Point
it : object of type Iterator
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
Get domain x.domain() Domain returns the domain of this set O(1), should be returned by reference
Get counted pointer on domain x.domainPointer() CountedPtr<Domain> returns a counted pointer on the domain of this set O(1)
Number of elements x.size() Size returns the number of elements of this set. at most linear in the number of elements
Empty container test x.empty() bool returns true iff the number of elements is zero, always faster than x.size() == 0 amortized constant time
Insert point x.insert(p) Inserts point p in the set
Insert new point x.insertNew(p) p is not already in x Inserts point p in the set, assuming it is not already inside faster than insert
Erase point x.erase(p) Size Erase point p from the set x, returns the number of points effectively removed from the set (thus either 0 or 1)
Erase point from iterator x.erase(it) it != x.end() Erase the point pointed by valid iterator it from the set x
Removes all points x.clear() Removes all the points from the set x, x.empty() is true afterwards
Get iterator on first element x.begin() Iterator Returns the iterator on the first element of the set Constant time.
Get iterator after the last element x.end() Iterator Returns the iterator after the last element of the set Constant time.
Get iterator on first element x.begin() ConstIterator Returns the const iterator on the first element of the set Constant time.
Get iterator after the last element x.end() ConstIterator Returns the const iterator after the last element of the set Constant time.
Set union to left x += y X & Elements of y should be included in the domain of x Adds all elements of y to x. Returns a reference to itself.
Complement of set x.computeComplement(outIt) outIt is an output iterator on Point Outputs the complement set of x in the given output iterator.
Complement of set x.assignFromComplement(y) Domain of x should contain the domain of y The set x is the complement of set y afterwards.
Bounding box x.computeBoundingBox(p1,p2) Points p1 and p2 define respectively the lower and upper bound of the bounding box of all points of x. Linear in x.size()
Search point x.find(p) Iterator Returns an iterator pointing on point p if it was found in the set x, or x.end() otherwise.
Search point x.find(p) ConstIterator Returns a const iterator pointing on point p if it was found in the set x, or x.end() otherwise.
Invariants
Models
DigitalSetBySTLVector, DigitalSetBySTLSet, DigitalSetFromMap
Notes
Template Parameters
T the type that should be a model of CDigitalSet.
Definition at line 137 of file CDigitalSet.h.
Member Typedef Documentation
template<typename T > typedef T::ConstIterator DGtal::CDigitalSet< T >::ConstIterator
Definition at line 148 of file CDigitalSet.h.
template<typename T > typedef T::Domain DGtal::CDigitalSet< T >::Domain
Definition at line 144 of file CDigitalSet.h.
template<typename T > typedef T::Iterator DGtal::CDigitalSet< T >::Iterator
Definition at line 147 of file CDigitalSet.h.
template<typename T > typedef T::Point DGtal::CDigitalSet< T >::Point
Definition at line 145 of file CDigitalSet.h.
template<typename T > typedef T::Size DGtal::CDigitalSet< T >::Size
Definition at line 146 of file CDigitalSet.h.
Member Function Documentation
template<typename T > DGtal::CDigitalSet< T >::BOOST_CONCEPT_ASSERT ((CDomain< Domain >))
template<typename T > DGtal::CDigitalSet< T >::BOOST_CONCEPT_ASSERT ((boost_concepts::ReadableIteratorConcept< ConstIterator >))
template<typename T > DGtal::CDigitalSet< T >::BOOST_CONCEPT_ASSERT ((boost_concepts::BidirectionalTraversalConcept< ConstIterator >))
template<typename T > DGtal::CDigitalSet< T >::BOOST_CONCEPT_USAGE (CDigitalSet< T >) inline
Definition at line 161 of file CDigitalSet.h.
References DGtal::CDigitalSet< T >::checkConstConstraints(), and DGtal::CDigitalSet< T >::checkNonConstConstraints().
     {
       checkConstConstraints();
       checkNonConstConstraints();
       // look at CInteger.h for testing tags.
     }
template<typename T > DGtal::CDigitalSet< T >::BOOST_STATIC_ASSERT ((boost::is_same< Iterator, ConstIterator >::value))
template<typename T > void DGtal::CDigitalSet< T >::checkConstConstraints () const inline
This method checks const methods when a non-const version exist.
Definition at line 170 of file CDigitalSet.h.
References DGtal::CDigitalSet< T >::myBool, DGtal::CDigitalSet< T >::myConstIterator, DGtal::CDigitalSet< T >::myDomain, DGtal::CDigitalSet< T >::myDomainPtr, DGtal::CDigitalSet< T >::myPoint, DGtal::CDigitalSet< T >::mySize, DGtal::CDigitalSet< T >::myX, and DGtal::ConceptUtils::sameType().
Referenced by DGtal::CDigitalSet< T >::BOOST_CONCEPT_USAGE().
     {
       ConceptUtils::sameType( myDomain, myX.domain() );
       ConceptUtils::sameType( myDomainPtr, myX.domainPointer() );
       ConceptUtils::sameType( mySize, myX.size() );
       ConceptUtils::sameType( myBool, myX.empty() );
       ConceptUtils::sameType( myConstIterator, myX.find( myPoint ) );
       ConceptUtils::sameType( myConstIterator, myX.begin() );
       ConceptUtils::sameType( myConstIterator, myX.end() );
     }
template<typename T > void DGtal::CDigitalSet< T >::checkNonConstConstraints () inline
This method checks non-const methods when a const version exist.
Definition at line 185 of file CDigitalSet.h.
References DGtal::CDigitalSet< T >::myIterator, DGtal::CDigitalSet< T >::myOutputIt, DGtal::CDigitalSet< T >::myPoint, DGtal::CDigitalSet< T >::mySize, DGtal::CDigitalSet< T >::myX, and DGtal::ConceptUtils::sameType().
Referenced by DGtal::CDigitalSet< T >::BOOST_CONCEPT_USAGE().
     {
       myX.insert( myPoint );
       // template <typename PointInputIterator>
       //   BOOST_CONCEPT_REQUIRES
       //   ( ((boost::InputIterator<PointInputIterator>)),
       //     (void) )
       //   myX.insert( PointInputIterator, PointInputIterator );
       myX.insertNew( myPoint );
       ConceptUtils::sameType( mySize, myX.erase( myPoint ) );
       myX.erase( myIterator );
       myX.erase( myIterator, myIterator );
       myX.clear();
       ConceptUtils::sameType( myX, myX.operator+=( myX ) );
       myX.computeComplement( myOutputIt );
       myX.assignFromComplement( myX );
       myX.computeBoundingBox( myPoint, myPoint );
       ConceptUtils::sameType( myIterator, myX.find( myPoint ) );
       ConceptUtils::sameType( myIterator, myX.begin() );
       ConceptUtils::sameType( myIterator, myX.end() );
     }
Field Documentation
template<typename T > bool DGtal::CDigitalSet< T >::myBool private
Definition at line 213 of file CDigitalSet.h.
Referenced by DGtal::CDigitalSet< T >::checkConstConstraints().
template<typename T > ConstIterator DGtal::CDigitalSet< T >::myConstIterator private
Definition at line 216 of file CDigitalSet.h.
Referenced by DGtal::CDigitalSet< T >::checkConstConstraints().
template<typename T > Domain DGtal::CDigitalSet< T >::myDomain private
Definition at line 210 of file CDigitalSet.h.
Referenced by DGtal::CDigitalSet< T >::checkConstConstraints().
template<typename T > CowPtr<Domain> DGtal::CDigitalSet< T >::myDomainPtr private
Definition at line 211 of file CDigitalSet.h.
Referenced by DGtal::CDigitalSet< T >::checkConstConstraints().
template<typename T > Iterator DGtal::CDigitalSet< T >::myIterator private
Definition at line 215 of file CDigitalSet.h.
Referenced by DGtal::CDigitalSet< T >::checkNonConstConstraints().
template<typename T > Point* DGtal::CDigitalSet< T >::myOutputIt private
Definition at line 217 of file CDigitalSet.h.
Referenced by DGtal::CDigitalSet< T >::checkNonConstConstraints().
template<typename T > Point DGtal::CDigitalSet< T >::myPoint private
Definition at line 214 of file CDigitalSet.h.
Referenced by DGtal::CDigitalSet< T >::checkConstConstraints(), and DGtal::CDigitalSet< T >::checkNonConstConstraints().
template<typename T > Size DGtal::CDigitalSet< T >::mySize private
Definition at line 212 of file CDigitalSet.h.
Referenced by DGtal::CDigitalSet< T >::checkConstConstraints(), and DGtal::CDigitalSet< T >::checkNonConstConstraints().
template<typename T > T DGtal::CDigitalSet< T >::myX private
Definition at line 209 of file CDigitalSet.h.
Referenced by DGtal::CDigitalSet< T >::checkConstConstraints(), and DGtal::CDigitalSet< T >::checkNonConstConstraints().
The documentation for this struct was generated from the following file:
CDigitalSet.h