DGtal: DGtal::CSurfelLocalEstimator< T > Struct Template Reference
DGtal::CSurfelLocalEstimator< T > Struct Template Reference
DGtal Concepts
#include <geometry/surfaces/estimation/CSurfelLocalEstimator.h>
Public Types
typedef T::Quantity Quantity
typedef T::Surfel Surfel
Public Member Functions
BOOST_CONCEPT_ASSERT ((CQuantity< Quantity >))
BOOST_CONCEPT_USAGE (CSurfelLocalEstimator)
void check_const_constraints () const
Private Attributes
T myX
double myH
Quantity myQ
boost::iterator_archetype
< Surfel,
boost::iterator_archetypes::readable_iterator_t,
boost::forward_traversal_tag > myItb
boost::iterator_archetype
< Surfel,
boost::iterator_archetypes::readable_iterator_t,
boost::forward_traversal_tag > myIte
boost::iterator_archetype
< Quantity,
boost::iterator_archetypes::writable_iterator_t,
boost::incrementable_traversal_tag > myIto
Detailed Description
template<typename T>
struct DGtal::CSurfelLocalEstimator< T >
Aim: This concept describes an object that can process a range of surfels (that are supposed to belong to some (abstract) surface) so as to return one estimated quantity for each element of the range (or a given subrange).
Description of concept 'CSurfelLocalEstimator'
It is rather general in the sense that it does not impose a type for the shape under study. It may be a digital surface, a point predicate that defines implicitly a digital shape, an implicit function, etc. This concept has refinements specifying some cases.
Refinement of
boost::DefaultConstructible, boost::CopyConstructible, boost::Assignable
Associated types :
Surfel : the type of elements of the surface
Quantity : the type of the (geometric) quantity that is estimated, must be a model of CQuantity.
Notation
X : A type that is a model of CSurfelLocalEstimator
x : object of type X
h : double
itb, ite, it,itb2, ite2 : instances of a model of forward iterators having Surfel as value type.
ito : an instance of a model of output iterator having Quantity as value type
Definitions
Valid expressions and semantics
Name Expression Return type Precondition Semantics Complexity
Initialization x.init(h, itb, ite) void h > 0 Grid step and range initialization in [itb,ite) model dependent
Evaluation x.eval(it) Quantity Estimation of the quantity at it, which must belong to [itb,ite) model dependent
Evaluation ito = x.eval(itb2, ite2, ito) a model of output iterator Estimation for each element of [itb2, ite2), which must be a subrange of or the whole range [itb,ite) model dependent
gridstep accessor x.h() double Accessor to the gridstep value O(1)
Invariants
Models
TrueDigitalSurfaceLocalEstimator, VCMDigitalSurfaceLocalEstimator, IntegralInvariantCovarianceEstimator, IntegralInvariantVolumeEstimator
Notes
Template Parameters
T the type that should be a model of CSurfelLocalEstimator.
Definition at line 105 of file CSurfelLocalEstimator.h.
Member Typedef Documentation
template<typename T > typedef T::Quantity DGtal::CSurfelLocalEstimator< T >::Quantity
Definition at line 112 of file CSurfelLocalEstimator.h.
template<typename T > typedef T::Surfel DGtal::CSurfelLocalEstimator< T >::Surfel
Definition at line 114 of file CSurfelLocalEstimator.h.
Member Function Documentation
template<typename T > DGtal::CSurfelLocalEstimator< T >::BOOST_CONCEPT_ASSERT ((CQuantity< Quantity >))
template<typename T > DGtal::CSurfelLocalEstimator< T >::BOOST_CONCEPT_USAGE (CSurfelLocalEstimator< T >) inline
Definition at line 116 of file CSurfelLocalEstimator.h.
References DGtal::CSurfelLocalEstimator< T >::check_const_constraints(), DGtal::CSurfelLocalEstimator< T >::myH, DGtal::CSurfelLocalEstimator< T >::myItb, DGtal::CSurfelLocalEstimator< T >::myIte, DGtal::CSurfelLocalEstimator< T >::myIto, DGtal::CSurfelLocalEstimator< T >::myQ, DGtal::CSurfelLocalEstimator< T >::myX, and DGtal::ConceptUtils::sameType().
     {
       //init method
       myX.init( myH, myItb, myIte );
       ConceptUtils::sameType( myQ, myX.eval( myItb ) );
       ConceptUtils::sameType( myIto, myX.eval( myItb, myIte, myIto ) );
       check_const_constraints();
     }
template<typename T > void DGtal::CSurfelLocalEstimator< T >::check_const_constraints () const inline
Definition at line 125 of file CSurfelLocalEstimator.h.
References DGtal::CSurfelLocalEstimator< T >::myH, DGtal::CSurfelLocalEstimator< T >::myX, and DGtal::ConceptUtils::sameType().
Referenced by DGtal::CSurfelLocalEstimator< T >::BOOST_CONCEPT_USAGE().
     {
       ConceptUtils::sameType( myH, myX.h() );
     }
Field Documentation
template<typename T > double DGtal::CSurfelLocalEstimator< T >::myH private
Definition at line 134 of file CSurfelLocalEstimator.h.
Referenced by DGtal::CSurfelLocalEstimator< T >::BOOST_CONCEPT_USAGE(), and DGtal::CSurfelLocalEstimator< T >::check_const_constraints().
template<typename T > boost::iterator_archetype<Surfel, boost::iterator_archetypes::readable_iterator_t, boost::forward_traversal_tag > DGtal::CSurfelLocalEstimator< T >::myItb private
Definition at line 138 of file CSurfelLocalEstimator.h.
Referenced by DGtal::CSurfelLocalEstimator< T >::BOOST_CONCEPT_USAGE().
template<typename T > boost::iterator_archetype<Surfel, boost::iterator_archetypes::readable_iterator_t, boost::forward_traversal_tag > DGtal::CSurfelLocalEstimator< T >::myIte private
Definition at line 138 of file CSurfelLocalEstimator.h.
Referenced by DGtal::CSurfelLocalEstimator< T >::BOOST_CONCEPT_USAGE().
template<typename T > boost::iterator_archetype<Quantity, boost::iterator_archetypes::writable_iterator_t, boost::incrementable_traversal_tag > DGtal::CSurfelLocalEstimator< T >::myIto private
Definition at line 141 of file CSurfelLocalEstimator.h.
Referenced by DGtal::CSurfelLocalEstimator< T >::BOOST_CONCEPT_USAGE().
template<typename T > Quantity DGtal::CSurfelLocalEstimator< T >::myQ private
Definition at line 135 of file CSurfelLocalEstimator.h.
Referenced by DGtal::CSurfelLocalEstimator< T >::BOOST_CONCEPT_USAGE().
template<typename T > T DGtal::CSurfelLocalEstimator< T >::myX private
Definition at line 132 of file CSurfelLocalEstimator.h.
Referenced by DGtal::CSurfelLocalEstimator< T >::BOOST_CONCEPT_USAGE(), and DGtal::CSurfelLocalEstimator< T >::check_const_constraints().
The documentation for this struct was generated from the following file:
CSurfelLocalEstimator.h