DGtal: DGtal::CLocalPremetric< T > Struct Template Reference
DGtal::CLocalPremetric< T > Struct Template Reference
DGtal Concepts
#include <geometry/volumes/distance/CLocalPremetric.h>
Public Types
typedef T::Space Space
typedef T::Space::Point Point
typedef T::Space::Vector Vector
typedef T::Value Value
Public Member Functions
BOOST_CONCEPT_ASSERT ((CSpace< Space >))
BOOST_CONCEPT_ASSERT ((CQuantity< Value >))
BOOST_CONCEPT_USAGE (CLocalPremetric)
void checkConstConstraints () const
Private Attributes
T myX
Point myPoint
Vector myDirection
Value myValue
Detailed Description
template<typename T>
struct DGtal::CLocalPremetric< T >
Aim: Defines the concept of local premetric. Models of such concept should implement a distance method which returns positive values for the distance between aPoint and aPoint + aDirection.
Description of concept 'CLocalPremetric'
Being a premetric, models should be such that the distance at a point in a given direction is equal to zero if and only if the direction is a null vector.
Refinement of
boost::CopyConstructible
boost::Assignable
Associated types :
Space: type of space on which the premetric is defined (model of CSpace)
Value: the value type of the metric (model of CQuantity)
Notation
X : A type that is a model of CLocalPremetric
x, y : object of type X
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
local distance computation v = x.local(aPoint,aDirection) aPoint of type Space::Point and aDirection of type Space::Vector v of type Value returns the distance at point aPoint in the direction aDirection. aDirection == null vector if and only if v==0 -
Invariants
Models
ExactPredicateLpSeparableMetric, InexactPredicateLpSeparableMetric
Notes
Template Parameters
T the type that should be a model of CLocalPremetric.
Definition at line 100 of file CLocalPremetric.h.
Member Typedef Documentation
template<typename T > typedef T::Space::Point DGtal::CLocalPremetric< T >::Point
Definition at line 105 of file CLocalPremetric.h.
template<typename T > typedef T::Space DGtal::CLocalPremetric< T >::Space
Definition at line 104 of file CLocalPremetric.h.
template<typename T > typedef T::Value DGtal::CLocalPremetric< T >::Value
Definition at line 107 of file CLocalPremetric.h.
template<typename T > typedef T::Space::Vector DGtal::CLocalPremetric< T >::Vector
Definition at line 106 of file CLocalPremetric.h.
Member Function Documentation
template<typename T > DGtal::CLocalPremetric< T >::BOOST_CONCEPT_ASSERT ((CSpace< Space >))
template<typename T > DGtal::CLocalPremetric< T >::BOOST_CONCEPT_ASSERT ((CQuantity< Value >))
template<typename T > DGtal::CLocalPremetric< T >::BOOST_CONCEPT_USAGE (CLocalPremetric< T >) inline
Definition at line 112 of file CLocalPremetric.h.
References DGtal::CLocalPremetric< T >::checkConstConstraints().
   {
     checkConstConstraints();
   }
template<typename T > void DGtal::CLocalPremetric< T >::checkConstConstraints () const inline
Definition at line 117 of file CLocalPremetric.h.
References DGtal::CLocalPremetric< T >::myDirection, DGtal::CLocalPremetric< T >::myPoint, DGtal::CLocalPremetric< T >::myValue, DGtal::CLocalPremetric< T >::myX, and DGtal::ConceptUtils::sameType().
Referenced by DGtal::CLocalPremetric< T >::BOOST_CONCEPT_USAGE().
   {
     // const method dummyConst should take parameter myA of type A and return
     // something of type B
     ConceptUtils::sameType( myValue, myX.local( myPoint , myDirection ) );
   }
Field Documentation
template<typename T > Vector DGtal::CLocalPremetric< T >::myDirection private
Definition at line 127 of file CLocalPremetric.h.
Referenced by DGtal::CLocalPremetric< T >::checkConstConstraints().
template<typename T > Point DGtal::CLocalPremetric< T >::myPoint private
Definition at line 126 of file CLocalPremetric.h.
Referenced by DGtal::CLocalPremetric< T >::checkConstConstraints().
template<typename T > Value DGtal::CLocalPremetric< T >::myValue private
Definition at line 128 of file CLocalPremetric.h.
Referenced by DGtal::CLocalPremetric< T >::checkConstConstraints().
template<typename T > T DGtal::CLocalPremetric< T >::myX private
Definition at line 125 of file CLocalPremetric.h.
Referenced by DGtal::CLocalPremetric< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CLocalPremetric.h