DGtal: DGtal::CSeparableMetric< T > Struct Template Reference
DGtal::CSeparableMetric< T > Struct Template Reference
DGtal Concepts
#include <geometry/volumes/distance/CSeparableMetric.h>
Public Types
typedef T::Point Point
Public Types inherited from DGtal::CMetric< T >
typedef T::Point Point
typedef T::Vector Vector
typedef T::Value Value
Public Types inherited from DGtal::CLocalPremetric< T >
typedef T::Space Space
typedef T::Space::Point Point
typedef T::Space::Vector Vector
typedef T::Value Value
Public Member Functions
BOOST_CONCEPT_USAGE (CSeparableMetric)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::CMetric< T >
BOOST_CONCEPT_USAGE (CMetric)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::CLocalPremetric< T >
BOOST_CONCEPT_ASSERT ((CSpace< Space >))
BOOST_CONCEPT_ASSERT ((CQuantity< Value >))
BOOST_CONCEPT_USAGE (CLocalPremetric)
void checkConstConstraints () const
Private Attributes
T myX
Point u
Point v
Point w
Point start
Point end
bool myBool
DGtal::Dimension dim
Detailed Description
template<typename T>
struct DGtal::CSeparableMetric< T >
Aim: defines the concept of separable metrics.
Description of concept 'CSeparableMetric'
Separable metrics are metrics satsifying the monotonicity property. More formally, in dimension 2, consider two points \(p(x,y)\), \(q(x',y')\) with \(x<x\). Let \(r(x'',0)\) be a point on the x-axis such that \(d(p,r) = d(q,r)\) and \(s(u,0)\) be another point on the x-axis. A metric \(d\) is monotonic if
\[ u < x'' \implies d(p,s) \leq d(q,s) \]
and
\[ u > x'' \implies d(p,s) \geq d(q,s) \]
Refinement of
CMetric.
Associated types :
Notation
X : A type that is a model of CSeparableMetric
x, y : object of type X
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
hiddenBy predicate hiddenBy(u,v,w,startingPoint,endPoint,dim) u,v,w,startingPoint,endPoint of type Point, dim of type DGtal::Dimension startingPoint and endPoint only differ by their dim-th coordinate returns true if the intersection between the segment [startingPoint,endPoint] and the Voronoi cell associated with v is empty (hidden on the segment by u and w Voronoi cells). -
Invariants
Models
ExactPredicateLpSeparableMetric, InexactPredicateLpSeparableMetric
Notes
Template Parameters
T the type that should be a model of CSeparableMetric.
Definition at line 99 of file CSeparableMetric.h.
Member Typedef Documentation
template<typename T > typedef T::Point DGtal::CSeparableMetric< T >::Point
Definition at line 103 of file CSeparableMetric.h.
Member Function Documentation
template<typename T > DGtal::CSeparableMetric< T >::BOOST_CONCEPT_USAGE (CSeparableMetric< T >) inline
Definition at line 104 of file CSeparableMetric.h.
References DGtal::CSeparableMetric< T >::checkConstConstraints().
     {
       checkConstConstraints();
     }
template<typename T > void DGtal::CSeparableMetric< T >::checkConstConstraints () const inline
Definition at line 108 of file CSeparableMetric.h.
References DGtal::CSeparableMetric< T >::dim, DGtal::CSeparableMetric< T >::myBool, DGtal::CSeparableMetric< T >::myX, DGtal::ConceptUtils::sameType(), and DGtal::CSeparableMetric< T >::u.
Referenced by DGtal::CSeparableMetric< T >::BOOST_CONCEPT_USAGE().
     {
         // const method dummyConst should take parameter myA of type A and return
         // something of type B
       ConceptUtils::sameType( myBool, myX.hiddenBy(u,v,w,start,end,dim) );
     }
Field Documentation
template<typename T > DGtal::Dimension DGtal::CSeparableMetric< T >::dim private
Definition at line 119 of file CSeparableMetric.h.
Referenced by DGtal::CSeparableMetric< T >::checkConstConstraints().
template<typename T > Point DGtal::CSeparableMetric< T >::end private
Definition at line 117 of file CSeparableMetric.h.
template<typename T > bool DGtal::CSeparableMetric< T >::myBool private
Definition at line 118 of file CSeparableMetric.h.
Referenced by DGtal::CSeparableMetric< T >::checkConstConstraints().
template<typename T > T DGtal::CSeparableMetric< T >::myX private
Definition at line 116 of file CSeparableMetric.h.
Referenced by DGtal::CSeparableMetric< T >::checkConstConstraints().
template<typename T > Point DGtal::CSeparableMetric< T >::start private
Definition at line 117 of file CSeparableMetric.h.
template<typename T > Point DGtal::CSeparableMetric< T >::u private
Definition at line 117 of file CSeparableMetric.h.
Referenced by DGtal::CSeparableMetric< T >::checkConstConstraints().
template<typename T > Point DGtal::CSeparableMetric< T >::v private
Definition at line 117 of file CSeparableMetric.h.
template<typename T > Point DGtal::CSeparableMetric< T >::w private
Definition at line 117 of file CSeparableMetric.h.
The documentation for this struct was generated from the following file:
CSeparableMetric.h