DGtal: DGtal::CPointEmbedder< T > Struct Template Reference
DGtal::CPointEmbedder< T > Struct Template Reference
DGtal Concepts
#include <kernel/CPointEmbedder.h>
Public Types
typedef T::Space Space
typedef T::Point Point
typedef T::RealPoint RealPoint
typedef T::Argument Argument
typedef T::Value Value
Public Member Functions
BOOST_CONCEPT_ASSERT ((CSpace< Space >))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Point, typename Space::Point >::value))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Point, Argument >::value))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< RealPoint, typename Space::RealPoint >::value))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< RealPoint, Value >::value))
BOOST_CONCEPT_USAGE (CPointEmbedder)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::CUnaryFunctor< T, T::Point, T::RealPoint >
BOOST_CONCEPT_USAGE (CUnaryFunctor)
Private Attributes
T myX
Point myP
RealPoint myRP
Detailed Description
template<typename T>
struct DGtal::CPointEmbedder< T >
Aim: A point embedder is a mapping from digital points to Euclidean points. It adds inner types to functor.
Description of concept 'CPointEmbedder'
Refinement of
CUnaryFunctor<T, T::Point, T::RealPoint>
Associated types :
Space: the digital space
Point: same as Space::Point
Argument: type of the argument, same as Space::Point
Value: type of value, same as Space::RealPoint
Notation
X : A type that is a model of CPointEmbedder
x : object of type X
p : object of type Point
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
Apply function x(p) Value return the value of the function x on argument p
Invariants
Models
CanonicEmbedder, RegularPointEmbedder
Notes
Template Parameters
T the type that should be a model of CPointEmbedder.
Definition at line 94 of file CPointEmbedder.h.
Member Typedef Documentation
template<typename T > typedef T::Argument DGtal::CPointEmbedder< T >::Argument
Definition at line 101 of file CPointEmbedder.h.
template<typename T > typedef T::Point DGtal::CPointEmbedder< T >::Point
Definition at line 99 of file CPointEmbedder.h.
template<typename T > typedef T::RealPoint DGtal::CPointEmbedder< T >::RealPoint
Definition at line 100 of file CPointEmbedder.h.
template<typename T > typedef T::Space DGtal::CPointEmbedder< T >::Space
Definition at line 98 of file CPointEmbedder.h.
template<typename T > typedef T::Value DGtal::CPointEmbedder< T >::Value
Definition at line 102 of file CPointEmbedder.h.
Member Function Documentation
template<typename T > DGtal::CPointEmbedder< T >::BOOST_CONCEPT_ASSERT ((CSpace< Space >))
template<typename T > DGtal::CPointEmbedder< T >::BOOST_CONCEPT_USAGE (CPointEmbedder< T >) inline
Definition at line 109 of file CPointEmbedder.h.
References DGtal::CPointEmbedder< T >::checkConstConstraints().
   {
     checkConstConstraints();
   }
template<typename T > DGtal::CPointEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Point, typename Space::Point >::value))
template<typename T > DGtal::CPointEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Point, Argument >::value))
template<typename T > DGtal::CPointEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< RealPoint, typename Space::RealPoint >::value))
template<typename T > DGtal::CPointEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< RealPoint, Value >::value))
template<typename T > void DGtal::CPointEmbedder< T >::checkConstConstraints () const inline
Definition at line 114 of file CPointEmbedder.h.
References DGtal::CPointEmbedder< T >::myP, DGtal::CPointEmbedder< T >::myRP, DGtal::CPointEmbedder< T >::myX, and DGtal::ConceptUtils::sameType().
Referenced by DGtal::CPointEmbedder< T >::BOOST_CONCEPT_USAGE().
   { // operator()
     ConceptUtils::sameType( myRP, myX( myP ) );
   }
Field Documentation
template<typename T > Point DGtal::CPointEmbedder< T >::myP private
Definition at line 121 of file CPointEmbedder.h.
Referenced by DGtal::CPointEmbedder< T >::checkConstConstraints().
template<typename T > RealPoint DGtal::CPointEmbedder< T >::myRP private
Definition at line 122 of file CPointEmbedder.h.
Referenced by DGtal::CPointEmbedder< T >::checkConstConstraints().
template<typename T > T DGtal::CPointEmbedder< T >::myX private
Definition at line 120 of file CPointEmbedder.h.
Referenced by DGtal::CPointEmbedder< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CPointEmbedder.h