DGtal: DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator Class Reference
DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator Class Reference
#include <ImageContainerByHashTree.h>
Public Member Functions
Iterator (Node **data, unsigned int position, unsigned int arraySize)
bool isAtEnd () const
Value & operator* ()
bool operator++ ()
bool operator== (const Iterator &it)
bool operator!= (const Iterator &it)
HashKey getKey () const
bool next ()
Protected Attributes
Node * myNode
unsigned int myCurrentCell
unsigned int myArraySize
Node ** myContainerData
Detailed Description
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t>
class DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator
Definition at line 486 of file ImageContainerByHashTree.h.
Constructor & Destructor Documentation
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::Iterator (Node ** data, unsigned int position, unsigned int arraySize) inline
Definition at line 489 of file ImageContainerByHashTree.h.
References DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myArraySize, DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myContainerData, DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myCurrentCell, and DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myNode.
      {
        myArraySize = arraySize;
        myContainerData = data;
        myNode = data[0];
        myCurrentCell = position;
        while ((!myNode) && (myCurrentCell < myArraySize))
          {
            myNode = myContainerData[++myCurrentCell];
          }
      }
Member Function Documentation
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> HashKey DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::getKey () const inline
Definition at line 526 of file ImageContainerByHashTree.h.
References DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getKey(), and DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myNode.
      {
        return myNode->getKey();
      }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> bool DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::isAtEnd () const inline
Definition at line 500 of file ImageContainerByHashTree.h.
References DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myArraySize, and DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myCurrentCell.
Referenced by DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator!=(), and DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator==().
      {
        return myCurrentCell >= myArraySize;
      }
template<typename Domain , typename Value , typename HashKey > bool DGtal::ImageContainerByHashTree< Domain, Value, HashKey >::Iterator::next () inline
Definition at line 427 of file ImageContainerByHashTree.ih.
References DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getNext(), DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myArraySize, DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myContainerData, DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myCurrentCell, and DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myNode.
Referenced by DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator++().
  {
    if ( myNode )
      {
        myNode = myNode->getNext();
        if ( myNode )
          {
            return true;
          }
        else
          {
            do
              {
                myNode = myContainerData[++myCurrentCell];
                if ( myCurrentCell >= myArraySize )
                  return false;
              }
            while ( !myNode );
            return true;
          }
      }
    return false;
  }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> bool DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator!= (const Iterator & it) inline
Definition at line 519 of file ImageContainerByHashTree.h.
References DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::isAtEnd(), and DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myNode.
      {
        if (isAtEnd() && it.isAtEnd())
          return false;
        else
          return (myNode != it.myNode);
      }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Value& DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator* () inline
Definition at line 504 of file ImageContainerByHashTree.h.
References DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getObject(), and DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myNode.
      {
        return myNode->getObject();
      }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> bool DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator++ () inline
Definition at line 508 of file ImageContainerByHashTree.h.
References DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::next().
      {
        return next();
      }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> bool DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator== (const Iterator & it) inline
Definition at line 512 of file ImageContainerByHashTree.h.
References DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::isAtEnd(), and DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myNode.
      {
        if (isAtEnd() && it.isAtEnd())
          return true;
        else
          return (myNode == it.myNode);
      }
Field Documentation
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> unsigned int DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myArraySize protected
Definition at line 534 of file ImageContainerByHashTree.h.
Referenced by DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::isAtEnd(), DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::Iterator(), and DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::next().
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Node** DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myContainerData protected
Definition at line 535 of file ImageContainerByHashTree.h.
Referenced by DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::Iterator(), and DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::next().
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> unsigned int DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myCurrentCell protected
Definition at line 533 of file ImageContainerByHashTree.h.
Referenced by DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::isAtEnd(), DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::Iterator(), and DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::next().
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Node* DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::myNode protected
Definition at line 532 of file ImageContainerByHashTree.h.
Referenced by DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::getKey(), DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::Iterator(), DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::next(), DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator!=(), DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator*(), and DGtal::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator==().
The documentation for this class was generated from the following files:
ImageContainerByHashTree.h
ImageContainerByHashTree.ih