DGtal: DGtal::GridCurve< TKSpace > Class Template Reference
DGtal::GridCurve< TKSpace > Class Template Reference
#include <GridCurve.h>
Public Types
typedef TKSpace KSpace
typedef KSpace::Point Point
typedef KSpace::Point Vector
typedef KSpace::SCell SCell
typedef std::vector< SCell > Storage
typedef Storage::const_iterator const_iterator
typedef Storage::const_iterator ConstIterator
typedef
Storage::const_reverse_iterator const_reverse_iterator
typedef
Storage::const_reverse_iterator ConstReverseIterator
Public Member Functions
BOOST_CONCEPT_ASSERT ((CCellularGridSpaceND< KSpace >))
~GridCurve ()
GridCurve (const KSpace &aKSpace)
GridCurve ()
GridCurve (const GridCurve &other)
GridCurve & operator= (const GridCurve &other)
void selfDisplay (std::ostream &out) const
bool isValid () const
bool initFromVectorStream (std::istream &in)
void writeVectorToStream (std::ostream &out)
bool initFromVector (const std::vector< Point > &aVectorOfPoints)
bool initFromPointsVector (const std::vector< Point > &aVectorOfPoints)
template<typename TIterator >
bool initFromPointsRange (const TIterator &itb, const TIterator &ite)
bool initFromSCellsVector (const std::vector< SCell > &aVectorOfSCells)
template<typename TIterator >
bool initFromSCellsRange (const TIterator &itb, const TIterator &ite)
bool isClosed () const
bool isOpen () const
ConstIterator begin () const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rend () const
SCell back () const
void push_back (const SCell &aSCell)
void pushBack (const SCell &aSCell)
Storage::size_type size () const
DrawableWithBoard2D * defaultStyle (std::string mode="") const
std::string className () const
void selfDraw (Board2D &board) const
GridCurve::SCellsRange getSCellsRange () const
GridCurve::PointsRange getPointsRange () const
GridCurve::MidPointsRange getMidPointsRange () const
GridCurve::ArrowsRange getArrowsRange () const
GridCurve::InnerPointsRange getInnerPointsRange () const
GridCurve::OuterPointsRange getOuterPointsRange () const
GridCurve::IncidentPointsRange getIncidentPointsRange () const
GridCurve::CodesRange getCodesRange () const
Private Member Functions
SCell PointVectorTo1SCell (const Point &aPoint, const Vector &aVector)
bool isInside (const SCell &aSCell) const
Private Attributes
const KSpace * myKPtr
bool myFlagIsOwned
Storage mySCells
Friends
DGtal::DrawableWithBoard2D * defaultStyle (const DGtal::GridCurve< TKSpace > &aGC, std::string mode="")
void draw (Board2D &aBoard, const DGtal::GridCurve< TKSpace > &aGC)
Detailed Description
template<typename TKSpace = KhalimskySpaceND<2>>
class DGtal::GridCurve< TKSpace >
Aim: describes, in a cellular space of dimension n, a closed of open sequence of signed d-cells (or d-scells), d being either equal to 1 or (n-1).
For instance, the topological boundary of a simply connected digital set is a closed sequence of 1-scells in 2d.
Template Parameters:
TKSpace Khalimsky space, a model of CCellularGridSpaceND
Using the namespace Z2i, defined in StdDefs.h, you can instanciate a grid curve as follows:
  //default construction
  Curve c1;
  //from a Khalimsky space
  K2 ks; ks.init( lowerBound, upperBound, true );
  Curve c2( ks );
This object provides several IO services. For instance, you can read a grid curve from a data file, which contains the (digital) coordinates of the 0-cells (pointels) in nd:
    fstream inputStream;
    inputStream.open (square.c_str(), ios::in);
    c1.initFromVectorStream(inputStream);
    inputStream.close();
Note that if the first and last 0-scells of the file have the same coordinates (i) or if only one of their coordinates differ by 1 (ii), then the grid curve is considered as closed, ie. scells directly incident to the last signed cell and indirectly incident to the first signed cell are the same.
You can also build a grid curve from the contour of a digital set as follows:
    vector<SCell> contour;                           //contour
    SurfelAdjacency<K2::dimension> sAdj( true );     //adjacency
    SetPredicate<DigitalSet> predicate( set );       //predicate (from the digital set)
    //tracking and init grid curve
    SCell s = Surfaces<KSpace>::findABel( ks, predicate, 1000 );
    Surfaces<KSpace>::track2DBoundary( contour, ks, sAdj, predicate, s );
    c2.initFromSCellsVector( contour );
To save a grid curve in a data file, GridCurve provides the special method writeVectorToStream():
    ofstream outputStream("myGridCurve.dat");
    if (outputStream.is_open())
      c2.writeVectorToStream(outputStream);
    outputStream.close();
The stream mechanism is used to display the true content of the grid curve:
    trace.info() << c1 << std::endl;
In 2d, the grid curve can be drawn in a vector graphics file as follows:
    Board2D aBoard;
    aBoard.setUnit(Board2D::UCentimeter);
    aBoard << c2;
    aBoard.saveEPS( "myGridCurve.eps", Board2D::BoundingBox, 5000 );
See Board2D: a stream mechanism for displaying 2D digital objects to learn more about the 2d drawing mechanism used in DGtal.
Moreover, this object provides several ranges as nested types:
SCellsRange to iterate over the d-scells
PointsRange to iterate over the digital coordinates of the 0-scells that are directly incident to the d-scells
MidPointsRange to iterate over the real coordinates of the d-scells
ArrowsRange to iterate over the arrows coding the 1-scells. Note that an arrow is a pair point-vector: the point codes the digital coordinates of the 1-scell, the vector gives the topology and sign of the 1-scell.
InnerPointsRange to iterate over the digital coordinates of the n-scells that are directly incident to the (n-1)-scells.
OuterPointsRange to iterate over the digital coordinates of the n-scells that are indirectly incident to the (n-1)-scells.
IncidentPointsRange to iterate over the pairs of inner and outer points (defined as above)
CodesRange to iterate over the codes {0,1,2,3} of the 1-scells (only available if n = 2)
You can get an access to these eight ranges through the following methods:
getSCellsRange()
getPointsRange()
getMidPointsRange()
getArrowsRange()
getInnerPointsRange()
getOuterPointsRange()
getIncidentPointsRange()
getCodesRange()
Each range can be displayed in the standard output or can be drawn (except CodesRange) in a vector graphics file as shown in the following snippet:
      Curve::IncidentPointsRange r = c1.getIncidentPointsRange();
      trace.info() << r << endl;
      aBoard << SetMode(aDomain.className(), "Grid") << aDomain;
      aBoard << r;
      aBoard.saveEPS( "MyIncidentPointsRange.eps", Board2D::BoundingBox, 5000 );
Moreover, each range has the following inner types:
ConstIterator
ConstReverseIterator
ConstCirculator
ConstReverseCirculator
And each range provides these (circular)iterator services:
begin() : begin ConstIterator
end() : end ConstIterator
rbegin() : begin ConstReverseIterator
rend() : end ConstReverseIterator
c() : ConstCirculator
rc() : ConstReverseCirculator
You can use these services to iterate over the elements of a given range as follows:
    trace.info() << "\t iterate over the range" << endl;
    Range::ConstIterator it = r.begin();
    Range::ConstIterator itEnd = r.end();
    for ( ; it != itEnd; ++it)
    {
      trace.info() << *it;
    }
    trace.info() << endl;
    trace.info() << "\t iterate over the range in the reverse way" << endl;
    Range::ConstReverseIterator rit = r.rbegin();
    Range::ConstReverseIterator ritEnd = r.rend();
    for ( ; rit != ritEnd; ++rit)
    {
      trace.info() << *rit;
    }
    trace.info() << endl;
    trace.info() << "\t iterate over the range in a circular way" << endl;
    Range::ConstCirculator c = r.c();
    //set the starting element wherever you want...
    for (unsigned i = 0; i < 20; ++i) ++c;
    //... and circulate
    Range::ConstCirculator cend( c );
    do
    {
      trace.info() << *c;
      c++;
    } while (c!=cend);
    trace.info() << endl;
See also:
exampleGridCurve2d.cpp testGridCurve.cpp
Definition at line 171 of file GridCurve.h.
Member Typedef Documentation
template<typename TKSpace = KhalimskySpaceND<2>> typedef Storage::const_iterator DGtal::GridCurve< TKSpace >::const_iterator
Definition at line 305 of file GridCurve.h.
template<typename TKSpace = KhalimskySpaceND<2>> typedef Storage::const_reverse_iterator DGtal::GridCurve< TKSpace >::const_reverse_iterator
Definition at line 307 of file GridCurve.h.
template<typename TKSpace = KhalimskySpaceND<2>> typedef Storage::const_iterator DGtal::GridCurve< TKSpace >::ConstIterator
Definition at line 306 of file GridCurve.h.
template<typename TKSpace = KhalimskySpaceND<2>> typedef Storage::const_reverse_iterator DGtal::GridCurve< TKSpace >::ConstReverseIterator
Definition at line 308 of file GridCurve.h.
template<typename TKSpace = KhalimskySpaceND<2>> typedef TKSpace DGtal::GridCurve< TKSpace >::KSpace
Definition at line 175 of file GridCurve.h.
template<typename TKSpace = KhalimskySpaceND<2>> typedef KSpace::Point DGtal::GridCurve< TKSpace >::Point
Definition at line 178 of file GridCurve.h.
template<typename TKSpace = KhalimskySpaceND<2>> typedef KSpace::SCell DGtal::GridCurve< TKSpace >::SCell
Definition at line 181 of file GridCurve.h.
template<typename TKSpace = KhalimskySpaceND<2>> typedef std::vector<SCell> DGtal::GridCurve< TKSpace >::Storage
Definition at line 182 of file GridCurve.h.
template<typename TKSpace = KhalimskySpaceND<2>> typedef KSpace::Point DGtal::GridCurve< TKSpace >::Vector
Definition at line 179 of file GridCurve.h.
Constructor & Destructor Documentation
template<typename TKSpace > DGtal::GridCurve< TKSpace >::~GridCurve ()
Destructor.
Definition at line 44 of file GridCurve.ih.
{
  if (myFlagIsOwned)
    delete myKPtr;
}
template<typename TKSpace > DGtal::GridCurve< TKSpace >::GridCurve (const KSpace & aKSpace)
Constructor.
Parameters:
aKSpace the Khalimsky space where the grid curve lies.
Definition at line 57 of file GridCurve.ih.
  : myKPtr( &aKSpace ), myFlagIsOwned( false )
{
}
template<typename TKSpace > DGtal::GridCurve< TKSpace >::GridCurve ()
Default Constructor. (the underlying Khalimsky space is default constructed).
Definition at line 51 of file GridCurve.ih.
  : myKPtr( new KSpace() ), myFlagIsOwned( true )
{
}
template<typename TKSpace > DGtal::GridCurve< TKSpace >::GridCurve (const GridCurve< TKSpace > & other)
Copy constructor.
Parameters:
other the object to clone.
Definition at line 63 of file GridCurve.ih.
References DGtal::GridCurve< TKSpace >::myFlagIsOwned, and DGtal::GridCurve< TKSpace >::myKPtr.
  : myFlagIsOwned( aOther.myFlagIsOwned ), mySCells( aOther.mySCells )
{
  if (myFlagIsOwned)
    myKPtr = new KSpace( *aOther.myKPtr ); //owned copy
  else
    myKPtr = aOther.myKPtr; //copy of the alias
}
Member Function Documentation
template<typename TKSpace > DGtal::GridCurve< TKSpace >::SCell DGtal::GridCurve< TKSpace >::back () const inline
Returns:
last scell
Definition at line 358 of file GridCurve.ih.
References DGtal::GridCurve< TKSpace >::back().
Referenced by DGtal::GridCurve< TKSpace >::back().
{
  return mySCells.back();
}
template<typename TKSpace > DGtal::GridCurve< TKSpace >::ConstIterator DGtal::GridCurve< TKSpace >::begin () const inline
Returns:
begin iterator on scells
Definition at line 326 of file GridCurve.ih.
References DGtal::GridCurve< TKSpace >::begin().
Referenced by DGtal::GridCurve< TKSpace >::begin(), and DGtal::GridCurve< TKSpace >::isClosed().
{
  return mySCells.begin();
}
template<typename TKSpace = KhalimskySpaceND<2>> DGtal::GridCurve< TKSpace >::BOOST_CONCEPT_ASSERT ((CCellularGridSpaceND< KSpace >))
template<typename TKSpace > std::string DGtal::GridCurve< TKSpace >::className () const inline
Returns:
the style name used for drawing this object.
Definition at line 414 of file GridCurve.ih.
{
  return "GridCurve";
}
template<typename TKSpace > DGtal::DrawableWithBoard2D * DGtal::GridCurve< TKSpace >::defaultStyle (std::string mode = "") const inline
Default drawing style object.
Returns:
the dyn. alloc. default style for this object.
Definition at line 406 of file GridCurve.ih.
{
  return new DrawableWithBoard2D;
}
template<typename TKSpace > DGtal::GridCurve< TKSpace >::ConstIterator DGtal::GridCurve< TKSpace >::end () const inline
Returns:
end iterator on scells
Definition at line 334 of file GridCurve.ih.
References DGtal::GridCurve< TKSpace >::end().
Referenced by DGtal::GridCurve< TKSpace >::end().
{
  return mySCells.end();
}
template<typename TKSpace = KhalimskySpaceND<2>> GridCurve::ArrowsRange DGtal::GridCurve< TKSpace >::getArrowsRange () const inline
Accessor to the range of the pairs point - shift vector (of integer coordinates) associated to the 1-cells of the grid curve
Returns:
an instance of ArrowsRange
Definition at line 464 of file GridCurve.h.
{
      return ArrowsRange(this);
    }
template<typename TKSpace = KhalimskySpaceND<2>> GridCurve::CodesRange DGtal::GridCurve< TKSpace >::getCodesRange () const inline
Returns:
an instance of CodesRange
Definition at line 492 of file GridCurve.h.
{
      return CodesRange(this);
    }
template<typename TKSpace = KhalimskySpaceND<2>> GridCurve::IncidentPointsRange DGtal::GridCurve< TKSpace >::getIncidentPointsRange () const inline
Returns:
an instance of IncidentPointsRange
Definition at line 485 of file GridCurve.h.
{
      return IncidentPointsRange(this);
    }
template<typename TKSpace = KhalimskySpaceND<2>> GridCurve::InnerPointsRange DGtal::GridCurve< TKSpace >::getInnerPointsRange () const inline
Returns:
an instance of InnerPointsRange
Definition at line 471 of file GridCurve.h.
{
      return InnerPointsRange(this);
    }
template<typename TKSpace = KhalimskySpaceND<2>> GridCurve::MidPointsRange DGtal::GridCurve< TKSpace >::getMidPointsRange () const inline
Accessor to the range of the (real coordinates of the) midpoints of each 1-cell
Returns:
an instance of MidPointsRange
Definition at line 455 of file GridCurve.h.
{
      return MidPointsRange(this);
    }
template<typename TKSpace = KhalimskySpaceND<2>> GridCurve::OuterPointsRange DGtal::GridCurve< TKSpace >::getOuterPointsRange () const inline
Returns:
an instance of OuterPointsRange
Definition at line 478 of file GridCurve.h.
{
      return OuterPointsRange(this);
    }
template<typename TKSpace = KhalimskySpaceND<2>> GridCurve::PointsRange DGtal::GridCurve< TKSpace >::getPointsRange () const inline
Accessor to the range of the points of integer coordinates, which are associated to 0-cells of the grid curve
Returns:
an instance of PointsRange
Definition at line 447 of file GridCurve.h.
{
      return PointsRange(this);
    }
template<typename TKSpace = KhalimskySpaceND<2>> GridCurve::SCellsRange DGtal::GridCurve< TKSpace >::getSCellsRange () const inline
Accessor to the range of signed cells
Returns:
an instance of SCellsRange
Definition at line 438 of file GridCurve.h.
References DGtal::GridCurve< TKSpace >::mySCells.
{
      return SCellsRange(mySCells);
    }
template<typename TKSpace > template<typename TIterator > bool DGtal::GridCurve< TKSpace >::initFromPointsRange (const TIterator & itb, const TIterator & ite) inline
Init from a range of points.
Parameters:
itb begin iterator
ite end iterator
Definition at line 164 of file GridCurve.ih.
References DGtal::PointVector< 2, Integer >::L_1.
{
  mySCells.clear();
  TIterator i = itb;
  TIterator j = itb;
  ++j;
  for ( ; j != ite; ++i, ++j) {
    Point p = *i;
    Vector v = *j - p;
    if (v.norm(Vector::L_1) != 1) { //disconnected !
      throw ConnectivityException();
    }
    SCell s = PointVectorTo1SCell(p,v);
    if ( ! isInside( s ) ) { //out of space !
      throw InputException();
    }
    mySCells.push_back( s );
  }
  Point first = *itb;
  Point last = *i;
  Vector v(first - last);
  if (v.norm(Vector::L_1) == 1) {
    SCell s = PointVectorTo1SCell(last,v);
    ASSERT( isInside( s ) ); //never out of space
    mySCells.push_back( PointVectorTo1SCell(last,v) );
  }
  return true;
}
template<typename TKSpace > bool DGtal::GridCurve< TKSpace >::initFromPointsVector (const std::vector< Point > & aVectorOfPoints) inline
Init from a STL vector of points.
Parameters:
aVectorOfPoints the vector containing a sequence of grid points (digital coordinates).
See also:
initFromPointsRange
Definition at line 147 of file GridCurve.ih.
{
  try {
    return initFromPointsRange( aVectorOfPoints.begin(), aVectorOfPoints.end() );
  } catch (DGtal::ConnectivityException& /*ce*/) {
    throw ConnectivityException();
    return false;
  } catch (DGtal::InputException& /*ie*/) {
    throw InputException();
    return false;
  }
}
template<typename TKSpace > template<typename TIterator > bool DGtal::GridCurve< TKSpace >::initFromSCellsRange (const TIterator & itb, const TIterator & ite) inline
Init from a range of signed cells.
Parameters:
itb begin iterator
ite end iterator
Definition at line 223 of file GridCurve.ih.
References DGtal::GridCurve< TKSpace >::push_back().
{
  mySCells.clear();
  //first scell
  TIterator it = itb;
  if (it != ite)
    {
      SCell currentSCell = *it;
      mySCells.push_back( currentSCell );
      //other scells
      for (++it; it != ite; ++it)
        {
          SCell expectedS( myKPtr->sDirectIncident( currentSCell, *myKPtr->sDirs( currentSCell ) ) );
          currentSCell = *it;
          SCell s( myKPtr->sIndirectIncident( currentSCell, *myKPtr->sDirs( currentSCell ) ) );
          if ( myKPtr->sKCoords(s) != myKPtr->sKCoords(expectedS) )
            { //disconnected !
              throw ConnectivityException();
            }
          if ( isInside( currentSCell ) )
            { //out of space !
              throw InputException();
            }
          mySCells.push_back( currentSCell );
        }
      return true;
    } else return false; //empty range
}
template<typename TKSpace > bool DGtal::GridCurve< TKSpace >::initFromSCellsVector (const std::vector< SCell > & aVectorOfSCells) inline
Init from a STL vector of signed cells.
Parameters:
aVectorOfSCells the vector containing the sequence of signed cells.
See also:
initFromSCellsRange
Definition at line 206 of file GridCurve.ih.
{
  try {
    return initFromSCellsRange( aVectorOfSCells.begin(), aVectorOfSCells.end() );
  } catch (DGtal::ConnectivityException& /*ce*/) {
    throw ConnectivityException();
    return false;
  } catch (DGtal::InputException& /*ie*/) {
    throw InputException();
    return false;
  }
}
template<typename TKSpace > bool DGtal::GridCurve< TKSpace >::initFromVector (const std::vector< Point > & aVectorOfPoints) inline
Deprecated name, use initFromPointsVector instead Init.
Parameters:
aVectorOfPoints the vector containing a sequence of grid points (digital coordinates).
See also:
initFromPointsRange
Definition at line 139 of file GridCurve.ih.
{
  return initFromPointsVector( aVectorOfPoints );
}
template<typename TKSpace > bool DGtal::GridCurve< TKSpace >::initFromVectorStream (std::istream & in) inline
Init.
Parameters:
in any input stream,
Definition at line 264 of file GridCurve.ih.
References DGtal::PointListReader< TPoint >::getPointsFromInputStream().
{
  std::vector<Point> v = PointListReader<Point>
    ::getPointsFromInputStream(in);
  if (v.size() == 0) throw IOException();
  try {
    return initFromPointsVector(v);
  } catch (DGtal::ConnectivityException& /*ce*/) {
    throw ConnectivityException();
    return false;
  } catch (DGtal::InputException& /*ie*/) {
    throw InputException();
    return false;
  }
}
template<typename TKSpace > bool DGtal::GridCurve< TKSpace >::isClosed () const inline
Checks whether the grid curve is open or closed. Signed cells directly incident to the last scell and indirectly incident to the first scell should be the same in case of a closed grid curve.
Returns:
'true' if grid curve is closed, 'false' otherwise
Definition at line 305 of file GridCurve.ih.
References DGtal::GridCurve< TKSpace >::begin().
{
  SCell first = *mySCells.begin();
  SCell last = *mySCells.rbegin();
  SCell nextLast( myKPtr->sDirectIncident( last , *myKPtr->sDirs( last ) ) );
  SCell previousFirst( myKPtr->sIndirectIncident( first, *myKPtr->sDirs( first ) ) );
  return ( myKPtr->sKCoords(nextLast) == myKPtr->sKCoords(previousFirst) );
}
template<typename TKSpace > bool DGtal::GridCurve< TKSpace >::isInside (const SCell & aSCell) const inline private
Parameters:
aSCell any signed cell
Returns:
'true' if aSCell is within the underlying Khalimsky space and 'false' otherwise
Definition at line 123 of file GridCurve.ih.
{
  bool flag = true;
  for (Dimension k = 0; ( (k < KSpace::dimension)&&(flag) ); ++k)
    {
      flag = myKPtr->sIsInside( aSCell, k );
    }
  return flag;
}
template<typename TKSpace > bool DGtal::GridCurve< TKSpace >::isOpen () const inline
Returns:
'true' if the grid curve is not closed, 'false' otherwise
See also:
isClosed
Definition at line 317 of file GridCurve.ih.
{
  return (! isClosed() );
}
template<typename TKSpace > bool DGtal::GridCurve< TKSpace >::isValid () const inline
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
Definition at line 96 of file GridCurve.ih.
{
  return ( (myKPtr != NULL)
    && ( mySCells.size() > 0 ) );
}
template<typename TKSpace > DGtal::GridCurve< TKSpace > & DGtal::GridCurve< TKSpace >::operator= (const GridCurve< TKSpace > & other)
Assignment.
Parameters:
other the object to copy.
Returns:
a reference on 'this'.
Definition at line 74 of file GridCurve.ih.
References DGtal::GridCurve< TKSpace >::myFlagIsOwned, DGtal::GridCurve< TKSpace >::myKPtr, and DGtal::GridCurve< TKSpace >::mySCells.
{
  if ( this != &aOther )
    {
      mySCells = aOther.mySCells;
      //free old space
      if (myFlagIsOwned)
        delete myKPtr;
      //acquire new space
      myFlagIsOwned = aOther.myFlagIsOwned;
      if (myFlagIsOwned)
        myKPtr = new KSpace( *aOther.myKPtr ); //owned copy
      else
        myKPtr = aOther.myKPtr; //copy of the alias
    }
  return *this;
}
template<typename TKSpace > DGtal::GridCurve< TKSpace >::SCell DGtal::GridCurve< TKSpace >::PointVectorTo1SCell (const Point & aPoint, const Vector & aVector) inline private
Parameters:
aPoint any point
aVector any vector of L1 norm equal to 1
Returns:
the signed 1-cell associated to a pair point - shift vector (both in digital coordinates)
Definition at line 109 of file GridCurve.ih.
References DGtal::PointVector< 2, Integer >::L_1.
{
  ASSERT( (aVector.norm(Vector::L_1) == 1) );
  SCell pointel( myKPtr->sPointel(aPoint,myKPtr->NEG) );
  typename KSpace::Space::Dimension d = 0;
  while ( aVector[d] == 0 ) ++d;
  return myKPtr->sIncident( pointel,d,(aVector[d]>0)?myKPtr->POS:myKPtr->NEG );
}
template<typename TKSpace > void DGtal::GridCurve< TKSpace >::push_back (const SCell & aSCell) inline
Back insertion of aSCell
Parameters:
aSCell any signed cell
See also:
pushBack NB: this alias is kept for STL compliance
Definition at line 366 of file GridCurve.ih.
Referenced by DGtal::GridCurve< TKSpace >::initFromSCellsRange(), and DGtal::GridCurve< TKSpace >::pushBack().
{
  pushBack(aSCell);
}
template<typename TKSpace > void DGtal::GridCurve< TKSpace >::pushBack (const SCell & aSCell) inline
Back insertion of aSCell
Parameters:
aSCell any signed cell
Definition at line 374 of file GridCurve.ih.
References DGtal::GridCurve< TKSpace >::push_back().
{
  mySCells.push_back(aSCell);
}
template<typename TKSpace > DGtal::GridCurve< TKSpace >::ConstReverseIterator DGtal::GridCurve< TKSpace >::rbegin () const inline
Returns:
reverse begin iterator on scells
Definition at line 342 of file GridCurve.ih.
References DGtal::GridCurve< TKSpace >::rbegin().
Referenced by DGtal::GridCurve< TKSpace >::rbegin().
{
  return mySCells.rbegin();
}
template<typename TKSpace > DGtal::GridCurve< TKSpace >::ConstReverseIterator DGtal::GridCurve< TKSpace >::rend () const inline
Returns:
reverse end iterator on scells
Definition at line 350 of file GridCurve.ih.
References DGtal::GridCurve< TKSpace >::rend().
Referenced by DGtal::GridCurve< TKSpace >::rend().
{
  return mySCells.rend();
}
template<typename TKSpace > void DGtal::GridCurve< TKSpace >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
Definition at line 393 of file GridCurve.ih.
Referenced by DGtal::operator<<().
{
  out << "[" << className() << "]" << std::endl;
  for(unsigned int i=0; i< mySCells.size(); i++){
    out << mySCells.at(i) << " ";
  }
  out << std::endl;
}
template<typename TKSpace > void DGtal::GridCurve< TKSpace >::selfDraw (Board2D & board) const inline
Draw the object on a Board2D board
Parameters:
board the output board where the object is drawn.
Definition at line 422 of file GridCurve.ih.
{
  for(unsigned int i=0; i< mySCells.size(); i++){
    aBoard << mySCells.at(i);
  }
}
template<typename TKSpace > DGtal::GridCurve< TKSpace >::Storage::size_type DGtal::GridCurve< TKSpace >::size () const inline
Returns:
number of scells
Definition at line 382 of file GridCurve.ih.
References DGtal::GridCurve< TKSpace >::size().
Referenced by DGtal::GridCurve< TKSpace >::size().
{
  return mySCells.size();
}
template<typename TKSpace > void DGtal::GridCurve< TKSpace >::writeVectorToStream (std::ostream & out) inline
Outputs the grid curve to the stream out.
Parameters:
out any output stream,
Definition at line 286 of file GridCurve.ih.
References PointsRange::begin(), and PointsRange::end().
{
  PointsRange r = getPointsRange();
  for (typename PointsRange::ConstIterator it = r.begin(), itEnd = r.end();
       it != itEnd; ++it)
    {
      Point p = *it;
      for (unsigned int k = 0; k < Point::dimension; ++k) {
        out << p[k] << " ";
      }
      out << std::endl;
    }
}
Friends And Related Function Documentation
template<typename TKSpace = KhalimskySpaceND<2>> DGtal::DrawableWithBoard2D* defaultStyle (const DGtal::GridCurve< TKSpace > & aGC, std::string mode = "") friend
Definition at line 404 of file GridCurve.h.
    {
      return aGC.defaultStyle(mode);
    }
template<typename TKSpace = KhalimskySpaceND<2>> void draw (Board2D & aBoard, const DGtal::GridCurve< TKSpace > & aGC) friend
Definition at line 421 of file GridCurve.h.
    {
      aGC.selfDraw(aBoard);
    }
Field Documentation
template<typename TKSpace = KhalimskySpaceND<2>> bool DGtal::GridCurve< TKSpace >::myFlagIsOwned private
bool equal to 'true' if this owns the Khalimsky space but 'false' otherwise
Definition at line 364 of file GridCurve.h.
Referenced by DGtal::GridCurve< TKSpace >::GridCurve(), and DGtal::GridCurve< TKSpace >::operator=().
template<typename TKSpace = KhalimskySpaceND<2>> const KSpace* DGtal::GridCurve< TKSpace >::myKPtr private
Pointer on a Khalimsky space
Definition at line 359 of file GridCurve.h.
Referenced by DGtal::GridCurve< TKSpace >::GridCurve(), and DGtal::GridCurve< TKSpace >::operator=().
template<typename TKSpace = KhalimskySpaceND<2>> Storage DGtal::GridCurve< TKSpace >::mySCells private
list of signed cells
Definition at line 369 of file GridCurve.h.
Referenced by DGtal::GridCurve< TKSpace >::getSCellsRange(), and DGtal::GridCurve< TKSpace >::operator=().
The documentation for this class was generated from the following files:
GridCurve.h
GridCurve.ih