DGtal: DGtal::IVector< T, TAlloc, usePointers > Class Template Reference
DGtal::IVector< T, TAlloc, usePointers > Class Template Reference
#include <MPolynomial.h>
Public Types
typedef TAlloc Alloc
typedef std::vector< T, Alloc >
::size_type Size
Public Member Functions
IVector (const Alloc &allocator=Alloc())
IVector (Size aSize, const Alloc &allocator=Alloc())
IVector (Size aSize, const T &entry, const Alloc &allocator=Alloc())
Size size () const
void resize (Size aSize, const T &entry=T())
const T & operator[] (Size i) const
T & operator[] (Size i)
const T & back () const
T & back ()
void swap (IVector &v)
Alloc get_allocator () const
Alloc getAllocator () const
Private Attributes
std::vector< T, Alloc > myVec
Detailed Description
template<typename T, typename TAlloc = std::allocator<T>, bool usePointers = false>
class DGtal::IVector< T, TAlloc, usePointers >
Next, we want to define the storage class IVector<T, Alloc, usePointers>. It behaves like a subset of std::vector<T>'s capabilities (i.e. access elements, get size, set size, get last element, swap with other storage of same type), but uses std::vector<T*> in case usePointers is true.
The advantage of this approach is that if T is a more complex object, reallocation done with resize() can be very costly.
This generic version is just using std::vector<T>.
Definition at line 721 of file MPolynomial.h.
Member Typedef Documentation
template<typename T , typename TAlloc = std::allocator<T>, bool usePointers = false> typedef TAlloc DGtal::IVector< T, TAlloc, usePointers >::Alloc
Definition at line 724 of file MPolynomial.h.
template<typename T , typename TAlloc = std::allocator<T>, bool usePointers = false> typedef std::vector<T, Alloc>::size_type DGtal::IVector< T, TAlloc, usePointers >::Size
Definition at line 725 of file MPolynomial.h.
Constructor & Destructor Documentation
template<typename T , typename TAlloc = std::allocator<T>, bool usePointers = false> DGtal::IVector< T, TAlloc, usePointers >::IVector (const Alloc & allocator = Alloc()) inline
Definition at line 730 of file MPolynomial.h.
      : myVec(allocator)
    {}
template<typename T , typename TAlloc = std::allocator<T>, bool usePointers = false> DGtal::IVector< T, TAlloc, usePointers >::IVector (Size aSize, const Alloc & allocator = Alloc()) inline
Definition at line 734 of file MPolynomial.h.
      : myVec( aSize, T(), allocator )
    {}
template<typename T , typename TAlloc = std::allocator<T>, bool usePointers = false> DGtal::IVector< T, TAlloc, usePointers >::IVector (Size aSize, const T & entry, const Alloc & allocator = Alloc()) inline
Definition at line 738 of file MPolynomial.h.
      : myVec(aSize, entry, allocator)
    {}
Member Function Documentation
template<typename T , typename TAlloc = std::allocator<T>, bool usePointers = false> const T& DGtal::IVector< T, TAlloc, usePointers >::back () const inline
Definition at line 762 of file MPolynomial.h.
References DGtal::IVector< T, TAlloc, usePointers >::myVec.
Referenced by DGtal::MPolynomial< 3, Ring >::leading().
    {
      return myVec.back();
    }
template<typename T , typename TAlloc = std::allocator<T>, bool usePointers = false> T& DGtal::IVector< T, TAlloc, usePointers >::back () inline
Definition at line 767 of file MPolynomial.h.
References DGtal::IVector< T, TAlloc, usePointers >::myVec.
    {
      return myVec.back();
    }
template<typename T , typename TAlloc = std::allocator<T>, bool usePointers = false> Alloc DGtal::IVector< T, TAlloc, usePointers >::get_allocator () const inline
Definition at line 777 of file MPolynomial.h.
References DGtal::IVector< T, TAlloc, usePointers >::myVec.
    {
        return myVec.get_allocator();
    }
template<typename T , typename TAlloc = std::allocator<T>, bool usePointers = false> Alloc DGtal::IVector< T, TAlloc, usePointers >::getAllocator () const inline
Definition at line 782 of file MPolynomial.h.
References DGtal::IVector< T, TAlloc, usePointers >::myVec.
Referenced by DGtal::MPolynomial< 3, Ring >::getAllocator().
    {
        return myVec.get_allocator();
    }
template<typename T , typename TAlloc = std::allocator<T>, bool usePointers = false> const T& DGtal::IVector< T, TAlloc, usePointers >::operator[] (Size i) const inline
Definition at line 752 of file MPolynomial.h.
References DGtal::IVector< T, TAlloc, usePointers >::myVec.
    {
      return myVec[i];
    }
template<typename T , typename TAlloc = std::allocator<T>, bool usePointers = false> T& DGtal::IVector< T, TAlloc, usePointers >::operator[] (Size i) inline
Definition at line 757 of file MPolynomial.h.
References DGtal::IVector< T, TAlloc, usePointers >::myVec.
    {
      return myVec[i];
    }
template<typename T , typename TAlloc = std::allocator<T>, bool usePointers = false> void DGtal::IVector< T, TAlloc, usePointers >::resize (Size aSize, const T & entry = T()) inline
Definition at line 747 of file MPolynomial.h.
References DGtal::IVector< T, TAlloc, usePointers >::myVec.
Referenced by DGtal::MPolynomialDerivativeComputer< 0, n, Ring, Alloc >::computeDerivative(), DGtal::MPolynomialDerivativeComputer< N, n, Ring, Alloc >::computeDerivative(), DGtal::MPolynomial< 3, Ring >::normalize(), DGtal::MPolynomial< 3, Ring >::operator+(), DGtal::MPolynomial< 3, Ring >::operator+=(), DGtal::MPolynomial< 3, Ring >::operator-(), DGtal::MPolynomial< 3, Ring >::operator-=(), DGtal::MPolynomial< 3, Ring >::operator=(), and DGtal::MPolynomial< 3, Ring >::operator[]().
    {
      myVec.resize(aSize, entry);
    }
template<typename T , typename TAlloc = std::allocator<T>, bool usePointers = false> Size DGtal::IVector< T, TAlloc, usePointers >::size () const inline
Definition at line 742 of file MPolynomial.h.
References DGtal::IVector< T, TAlloc, usePointers >::myVec.
Referenced by DGtal::MPolynomial< 3, Ring >::degree(), DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::evaluate(), DGtal::MPolynomial< 3, Ring >::isZero(), DGtal::MPolynomial< 3, Ring >::leading(), DGtal::MPolynomial< 3, Ring >::MPolynomial(), DGtal::MPolynomial< 3, Ring >::normalize(), DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::operator MPolyNM1(), DGtal::MPolynomialEvaluator< 1, TRing, TAlloc, TX >::operator X(), DGtal::MPolynomialEvaluatorImpl< 1, TRing, TOwner, TAlloc, TX >::EvalFun::operator()(), DGtal::MPolynomialEvaluatorImpl< n, TRing, TOwner, TAlloc, TX >::EvalFun< XX, Fun >::operator()(), DGtal::MPolynomialEvaluatorImpl< n, TRing, TOwner, TAlloc, TX >::EvalFun2::operator()(), DGtal::MPolynomial< 3, Ring >::operator*(), DGtal::MPolynomial< 3, Ring >::operator*=(), DGtal::MPolynomial< 3, Ring >::operator+(), DGtal::MPolynomial< 3, Ring >::operator+=(), DGtal::MPolynomial< 3, Ring >::operator-(), DGtal::MPolynomial< 3, Ring >::operator-=(), DGtal::MPolynomial< 3, Ring >::operator/(), DGtal::MPolynomial< 3, Ring >::operator/=(), DGtal::IVector< T, TAlloc, true >::operator=(), DGtal::MPolynomial< 3, Ring >::operator=(), DGtal::MPolynomial< 3, Ring >::operator==(), DGtal::MPolynomial< 3, Ring >::operator[](), and DGtal::MPolynomial< 3, Ring >::selfDisplay().
    {
      return myVec.size();
    }
template<typename T , typename TAlloc = std::allocator<T>, bool usePointers = false> void DGtal::IVector< T, TAlloc, usePointers >::swap (IVector< T, TAlloc, usePointers > & v) inline
Definition at line 772 of file MPolynomial.h.
References DGtal::IVector< T, TAlloc, usePointers >::myVec.
Referenced by DGtal::MPolynomial< 3, Ring >::swap().
    {
      myVec.swap( v.myVec );
    }
Field Documentation
template<typename T , typename TAlloc = std::allocator<T>, bool usePointers = false> std::vector<T, Alloc> DGtal::IVector< T, TAlloc, usePointers >::myVec private
Definition at line 727 of file MPolynomial.h.
Referenced by DGtal::IVector< T, TAlloc, usePointers >::back(), DGtal::IVector< T, TAlloc, true >::back(), DGtal::IVector< T, TAlloc, true >::copy_from(), DGtal::IVector< T, TAlloc, true >::create(), DGtal::IVector< T, TAlloc, true >::free(), DGtal::IVector< T, TAlloc, usePointers >::get_allocator(), DGtal::IVector< T, TAlloc, true >::get_allocator(), DGtal::IVector< T, TAlloc, usePointers >::getAllocator(), DGtal::IVector< T, TAlloc, true >::getAllocator(), DGtal::IVector< T, TAlloc, true >::IVector(), DGtal::IVector< T, TAlloc, true >::operator=(), DGtal::IVector< T, TAlloc, usePointers >::operator[](), DGtal::IVector< T, TAlloc, true >::operator[](), DGtal::IVector< T, TAlloc, usePointers >::resize(), DGtal::IVector< T, TAlloc, true >::resize(), DGtal::IVector< T, TAlloc, usePointers >::size(), DGtal::IVector< T, TAlloc, true >::size(), DGtal::IVector< T, TAlloc, usePointers >::swap(), DGtal::IVector< T, TAlloc, true >::swap(), and DGtal::IVector< T, TAlloc, true >::~IVector().
The documentation for this class was generated from the following file:
MPolynomial.h