DGtal: DGtal::CurvatureFromDSSLengthFunctor< DSSComputer > Class Template Reference
DGtal::CurvatureFromDSSLengthFunctor< DSSComputer > Class Template Reference
#include <SegmentComputerFunctor.h>
Public Types
typedef double Value
Public Member Functions
~CurvatureFromDSSLengthFunctor ()
CurvatureFromDSSLengthFunctor ()
CurvatureFromDSSLengthFunctor (const CurvatureFromDSSLengthFunctor &)
Value operator() (const typename DSSComputer::Point &, const DSSComputer &aDSS, const double &h=1, const bool &isExtendableAtBack=false, const bool &isExtendableAtFront=false) const
bool isValid () const
Private Member Functions
Value getLength (const DSSComputer &aDSS) const
Value getValue (const Value &l=1) const
Detailed Description
template<typename DSSComputer>
class DGtal::CurvatureFromDSSLengthFunctor< DSSComputer >
Description of class 'CurvatureFromDSSLengthFunctor'
Aim: computes the curvature k from the length l of a DSS as follow: 1/k = l*l/8 + 1/2
Note:
Adaption from Coeurjolly, D. and Miguet, S. and Tougne, L. "Discrete Curvature Based on Osculating Circle Estimation", Proc. IWVF, LNCS, vol 2059, pp.303-312, 2001
Template Parameters:
DSSComputer a model for concept CSegmentComputer.
Definition at line 270 of file SegmentComputerFunctor.h.
Member Typedef Documentation
template<typename DSSComputer > typedef double DGtal::CurvatureFromDSSLengthFunctor< DSSComputer >::Value
Definition at line 276 of file SegmentComputerFunctor.h.
Constructor & Destructor Documentation
template<typename DSSComputer > DGtal::CurvatureFromDSSLengthFunctor< DSSComputer >::~CurvatureFromDSSLengthFunctor () inline
Destructor.
Definition at line 284 of file SegmentComputerFunctor.h.
{};
template<typename DSSComputer > DGtal::CurvatureFromDSSLengthFunctor< DSSComputer >::CurvatureFromDSSLengthFunctor () inline
Default Constructor.
Definition at line 289 of file SegmentComputerFunctor.h.
{};
template<typename DSSComputer > DGtal::CurvatureFromDSSLengthFunctor< DSSComputer >::CurvatureFromDSSLengthFunctor (const CurvatureFromDSSLengthFunctor< DSSComputer > &) inline
Copy constructor.
Parameters:
other the object to clone.
Definition at line 295 of file SegmentComputerFunctor.h.
{};
Member Function Documentation
template<typename DSSComputer > Value DGtal::CurvatureFromDSSLengthFunctor< DSSComputer >::getLength (const DSSComputer & aDSS) const inline private
Definition at line 411 of file SegmentComputerFunctor.h.
References DGtal::PointVector< 2, Integer >::L_2, and DGtal::PointVector< dim, TEuclideanRing >::norm().
Referenced by DGtal::CurvatureFromDSSLengthFunctor< DSSComputer >::operator()().
{
      typedef typename DSSComputer::Vector Vector;
      Vector v(aDSS.getFrontPoint() - aDSS.getBackPoint());
      return v.norm(Vector::L_2);
   }
template<typename DSSComputer > Value DGtal::CurvatureFromDSSLengthFunctor< DSSComputer >::getValue (const Value & l = 1) const inline private
Definition at line 422 of file SegmentComputerFunctor.h.
Referenced by DGtal::CurvatureFromDSSLengthFunctor< DSSComputer >::operator()().
{
      return 1/( (l*l)/8 + 0.5 );
   }
template<typename DSSComputer > bool DGtal::CurvatureFromDSSLengthFunctor< DSSComputer >::isValid () const inline
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
Definition at line 390 of file SegmentComputerFunctor.h.
    {
      return true;
    };
template<typename DSSComputer > Value DGtal::CurvatureFromDSSLengthFunctor< DSSComputer >::operator() (const typename DSSComputer::Point & , const DSSComputer & aDSS, const double & h = 1, const bool & isExtendableAtBack = false, const bool & isExtendableAtFront = false) const inline
Operator()
Returns:
the curvature at [aPoint]
Parameters:
aPoint the point at which the curvature is estimated.
aDSS a DSSComputer.
isExtendableAtBack a bool equal to 'true' if [aDSS] can be extended at back and false otherwise.
isExtendableAtFront a bool equal to 'true' if [aDSS] can be extended at front and false otherwise.
Definition at line 312 of file SegmentComputerFunctor.h.
References DGtal::CurvatureFromDSSLengthFunctor< DSSComputer >::getLength(), and DGtal::CurvatureFromDSSLengthFunctor< DSSComputer >::getValue().
{
      //types
      typedef typename DSSComputer::Integer Integer;
      typedef typename DSSComputer::ConstIterator ConstIterator;
      //curvature value
      Value k = 0;
      //begin and end iterators
      //(back point on the first point)
      //(front point after the last point)
      ConstIterator front = aDSS.getFront();
      ConstIterator back = aDSS.getBack();
      if (isExtendableAtBack) {
        if (isExtendableAtFront) {
          --back;
          ++front;
          //parameters
          Integer mu = aDSS.getMu();
          Integer omega = aDSS.getOmega();
          //cases
          if ( (aDSS.getRemainder(*back)<=mu-1)&&
               (aDSS.getRemainder(*front)<=mu-1) ) {                //convex
            k = getValue( getLength(aDSS) )/h;
          } else if ( (aDSS.getRemainder(*back)>=mu+omega)&&
                (aDSS.getRemainder(*front)>=mu+omega) ) {           //concave
            k = -getValue( getLength(aDSS) )/h;
          } //else                                                  //inflection
        } else {
          --back;
          //parameters
          Integer mu = aDSS.getMu();
          Integer omega = aDSS.getOmega();
          //cases
          if ( (aDSS.getRemainder(*back)<=mu-1) ) {                //convex
            k = getValue( getLength(aDSS) )/h;
          } else if ( (aDSS.getRemainder(*back)>=mu+omega) ) {     //concave
            k = -getValue( getLength(aDSS) )/h;
          } //else                                                 //inflection
        }
      } else if (isExtendableAtFront) {
          ++front;
          //parameters
          Integer mu = aDSS.getMu();
          Integer omega = aDSS.getOmega();
          //cases
          if ( (aDSS.getRemainder(*front)<=mu-1) ) {                //convex
            k = getValue( getLength(aDSS) )/h;
          } else if ( (aDSS.getRemainder(*front)>=mu+omega) ) {     //concave
            k = -getValue( getLength(aDSS) )/h;
          } //else                                                  //inflection
      } //else cannot be extended: k is set to 0
      return k;
    };
The documentation for this class was generated from the following file:
SegmentComputerFunctor.h