DGtal: PointsRange Class Reference
PointsRange Class Reference
Public Types
typedef GridCurve::Storage Storage
typedef Storage::const_iterator ConstIteratorOnSCells
typedef SCellToPoint< KSpace > Functor
typedef ConstIteratorAdapter
< ConstIteratorOnSCells,
Functor, Point > ConstIterator
typedef std::reverse_iterator
< ConstIterator > ConstReverseIterator
typedef Circulator< ConstIterator > ConstCirculator
typedef std::reverse_iterator
< ConstCirculator > ConstReverseCirculator
Public Member Functions
PointsRange (const GridCurve *aGridCurve)
PointsRange (const PointsRange &aOther)
PointsRange & operator= (const PointsRange &other)
~PointsRange ()
Storage::size_type size () const
bool isValid () const
void selfDisplay (std::ostream &out) const
DGtal::DrawableWithBoard2D * defaultStyle () const
DGtal::DrawableWithBoard2D * defaultStyle (std::string) const
std::string className () const
void selfDraw (Board2D &aBoard) const
ConstIterator begin () const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rend () const
ConstCirculator c () const
ConstReverseCirculator rc () const
Private Attributes
const GridCurve * myC
Functor myFunctor
Friends
ostream & operator<< (ostream &out, const PointsRange &object)
DGtal::DrawableWithBoard2D * defaultStyle (const PointsRange &pr)
DGtal::DrawableWithBoard2D * defaultStyle (const PointsRange &pr, std::string)
void draw (Board2D &aBoard, const PointsRange &pr)
Detailed Description
Aim: model of CConstRange that provides services to (circularly)iterate over the 0-cells of a grid curve, viewed as points of integer coordinates.
(Included in GridCurve.h)
See also:
GridCurve.h exampleGridCurve2d.cpp testGridCurve.cpp
Definition at line 263 of file GridCurveRanges.ih.
Member Typedef Documentation
typedef Circulator<ConstIterator> PointsRange::ConstCirculator
Definition at line 277 of file GridCurveRanges.ih.
typedef ConstIteratorAdapter<ConstIteratorOnSCells,Functor,Point> PointsRange::ConstIterator
Definition at line 274 of file GridCurveRanges.ih.
typedef Storage::const_iterator PointsRange::ConstIteratorOnSCells
Definition at line 270 of file GridCurveRanges.ih.
typedef std::reverse_iterator<ConstCirculator> PointsRange::ConstReverseCirculator
Definition at line 278 of file GridCurveRanges.ih.
typedef std::reverse_iterator<ConstIterator> PointsRange::ConstReverseIterator
Definition at line 275 of file GridCurveRanges.ih.
typedef SCellToPoint<KSpace> PointsRange::Functor
Definition at line 272 of file GridCurveRanges.ih.
typedef GridCurve::Storage PointsRange::Storage
Definition at line 269 of file GridCurveRanges.ih.
Constructor & Destructor Documentation
PointsRange::PointsRange (const GridCurve * aGridCurve) inline
Constructor.
Parameters:
aGridCurve a grid curve.
Definition at line 287 of file GridCurveRanges.ih.
: myC(aGridCurve), myFunctor(Functor(*myC->myKPtr)) {}
PointsRange::PointsRange (const PointsRange & aOther) inline
Copy constructor.
Parameters:
other the iterator to clone.
Definition at line 293 of file GridCurveRanges.ih.
    : myC( aOther.myC ), myFunctor( aOther.myFunctor) {}
PointsRange::~PointsRange () inline
Destructor. Does nothing.
Definition at line 314 of file GridCurveRanges.ih.
{}
Member Function Documentation
ConstIterator PointsRange::begin () const inline
Iterator service.
Returns:
begin iterator
Definition at line 426 of file GridCurveRanges.ih.
References myC, and myFunctor.
Referenced by c(), rend(), selfDisplay(), selfDraw(), and DGtal::GridCurve< TKSpace >::writeVectorToStream().
{
    return ConstIterator( myC->mySCells.begin(), myFunctor );
  }
ConstCirculator PointsRange::c () const inline
Circulator service.
Returns:
a circulator
Definition at line 458 of file GridCurveRanges.ih.
References begin(), and end().
Referenced by rc().
{
    return ConstCirculator( this->begin(), this->begin(), this->end() );
  }
std::string PointsRange::className () const inline
Returns:
the style name used for drawing this object.
Definition at line 384 of file GridCurveRanges.ih.
  {
    return "PointsRange";
  }
DGtal::DrawableWithBoard2D* PointsRange::defaultStyle () const inline
Default drawing style object.
Returns:
the dyn. alloc. default style for this object.
Definition at line 359 of file GridCurveRanges.ih.
  {
    return new DrawableWithBoard2D;
  }
DGtal::DrawableWithBoard2D* PointsRange::defaultStyle (std::string) const inline
Default drawing style object.
Parameters:
mode the drawing mode
Returns:
the dyn. alloc. default style for this object.
Definition at line 372 of file GridCurveRanges.ih.
  {
    return new DrawableWithBoard2D;
  }
ConstIterator PointsRange::end () const inline
Iterator service.
Returns:
end iterator
Definition at line 434 of file GridCurveRanges.ih.
References myC, and myFunctor.
Referenced by c(), rbegin(), selfDisplay(), selfDraw(), and DGtal::GridCurve< TKSpace >::writeVectorToStream().
{
    return ConstIterator( myC->mySCells.end(), myFunctor );
  }
bool PointsRange::isValid () const inline
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
Definition at line 327 of file GridCurveRanges.ih.
{ return true; }
PointsRange& PointsRange::operator= (const PointsRange & other) inline
Assignment.
Parameters:
other the iterator to copy.
Returns:
a reference on 'this'.
Definition at line 301 of file GridCurveRanges.ih.
References myC, and myFunctor.
  {
    if ( this != &other )
      {
        myC = other.myC;
        myFunctor = other.myFunctor;
      }
    return *this;
  }
ConstReverseIterator PointsRange::rbegin () const inline
Iterator service.
Returns:
rbegin iterator
Definition at line 442 of file GridCurveRanges.ih.
References end().
{
    return ConstReverseIterator(this->end());
  }
ConstReverseCirculator PointsRange::rc () const inline
Circulator service.
Returns:
a reverse circulator
Definition at line 466 of file GridCurveRanges.ih.
References c().
{
    return ConstReverseCirculator( this->c() );
  }
ConstReverseIterator PointsRange::rend () const inline
Iterator service.
Returns:
rend iterator
Definition at line 450 of file GridCurveRanges.ih.
References begin().
{
    return ConstReverseIterator(this->begin());
  }
void PointsRange::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
Definition at line 334 of file GridCurveRanges.ih.
References begin(), and end().
  {
    typedef typename IteratorCirculatorTraits<ConstIterator>::Value Value;
    out << "[PointsRange]" << std::endl;
    out << "\t";
    std::copy( this->begin(), this->end(), ostream_iterator<Value>(out, ", ") );
    out << std::endl;
  }
void PointsRange::selfDraw (Board2D & aBoard) const inline
Draw the object on a Board2D board
Parameters:
board the output board where the object is drawn.
Definition at line 393 of file GridCurveRanges.ih.
References begin(), and end().
  {
    ConstIterator it ( this->begin() );
    ConstIterator itEnd ( this->end() );
    for( ; it != itEnd; ++it)
      {
        aBoard << SetMode(it->className(),"Grid")
               << *it;
      }
  }
Storage::size_type PointsRange::size () const inline
Returns:
the size of the range
Definition at line 319 of file GridCurveRanges.ih.
References myC.
  {
    return myC->mySCells.size();
  }
Friends And Related Function Documentation
DGtal::DrawableWithBoard2D* defaultStyle (const PointsRange & pr) friend
Definition at line 363 of file GridCurveRanges.ih.
  {
    return pr.defaultStyle();
  }
DGtal::DrawableWithBoard2D* defaultStyle (const PointsRange & pr, std::string) friend
Definition at line 376 of file GridCurveRanges.ih.
  {
    return pr.defaultStyle();
  }
void draw (Board2D & aBoard, const PointsRange & pr) friend
Definition at line 403 of file GridCurveRanges.ih.
  {
    pr.selfDraw(aBoard);
  }
ostream& operator<< (ostream & out, const PointsRange & object) friend
Overloads 'operator<<' for displaying objects of class 'PointsRange'.
Parameters:
out the output stream where the object is written.
object the object of class 'PointsRange' to write.
Returns:
the output stream after the writing.
Definition at line 349 of file GridCurveRanges.ih.
  {
    object.selfDisplay( out );
    return out;
  }
Field Documentation
const GridCurve* PointsRange::myC private
Private member myC is an aliasing pointer to any grid curve
Definition at line 413 of file GridCurveRanges.ih.
Referenced by begin(), end(), operator=(), and size().
Functor PointsRange::myFunctor private
Functor transforming a signed cell into a digital point
Definition at line 417 of file GridCurveRanges.ih.
Referenced by begin(), end(), and operator=().
The documentation for this class was generated from the following file:
GridCurveRanges.ih