DGtal: DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker Class Reference
DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker Class Reference
#include <DigitalSetBoundary.h>
Public Types
typedef Tracker Self
typedef DigitalSetBoundary
< TKSpace, TDigitalSet > DigitalSurfaceContainer
typedef TKSpace::SCell Surfel
typedef TKSpace KSpace
typedef SurfelNeighborhood
< KSpace > Neighborhood
Public Member Functions
Tracker (const DigitalSurfaceContainer &aSurface, const Surfel &s)
Tracker (const Tracker &other)
~Tracker ()
const DigitalSurfaceContainer & surface () const
const Surfel & current () const
Dimension orthDir () const
void move (const Surfel &s)
uint8_t adjacent (Surfel &s, Dimension d, bool pos) const
Private Attributes
const DigitalSurfaceContainer & mySurface
Neighborhood myNeighborhood
Detailed Description
template<typename TKSpace, typename TDigitalSet>
class DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker
A model of CDigitalSurfaceTracker for DigitalSetBoundary.
Definition at line 75 of file DigitalSetBoundary.h.
Member Typedef Documentation
template<typename TKSpace, typename TDigitalSet> typedef DigitalSetBoundary<TKSpace,TDigitalSet> DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::DigitalSurfaceContainer
Definition at line 80 of file DigitalSetBoundary.h.
template<typename TKSpace, typename TDigitalSet> typedef TKSpace DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::KSpace
Definition at line 84 of file DigitalSetBoundary.h.
template<typename TKSpace, typename TDigitalSet> typedef SurfelNeighborhood<KSpace> DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::Neighborhood
Definition at line 85 of file DigitalSetBoundary.h.
template<typename TKSpace, typename TDigitalSet> typedef Tracker DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::Self
Definition at line 79 of file DigitalSetBoundary.h.
template<typename TKSpace, typename TDigitalSet> typedef TKSpace::SCell DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::Surfel
Definition at line 81 of file DigitalSetBoundary.h.
Constructor & Destructor Documentation
template<typename TKSpace , typename TDigitalSet > DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::Tracker (const DigitalSurfaceContainer & aSurface, const Surfel & s) inline
Constructor from surface container and surfel.
Parameters:
aSurface the container describing the surface.
s the surfel on which the tracker is initialized.
Definition at line 51 of file DigitalSetBoundary.ih.
References DGtal::SurfelNeighborhood< TKSpace >::init(), DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::myNeighborhood, DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::space(), DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::surface(), and DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::surfelAdjacency().
  : mySurface( aSurface ), myNeighborhood()
{
  myNeighborhood.init( & surface().space(),
                       & surface().surfelAdjacency(),
                       s );
}
template<typename TKSpace , typename TDigitalSet > DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::Tracker (const Tracker & other) inline
Copy constructor.
Parameters:
other the object to clone.
Definition at line 63 of file DigitalSetBoundary.ih.
  : mySurface( other.mySurface ), myNeighborhood( other.myNeighborhood )
{
}
template<typename TKSpace , typename TDigitalSet > DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::~Tracker () inline
Destructor.
Definition at line 45 of file DigitalSetBoundary.ih.
{}
Member Function Documentation
template<typename TKSpace , typename TDigitalSet > DGtal::uint8_t DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::adjacent (Surfel & s, Dimension d, bool pos) const inline
Computes the surfel adjacent to 'current()' in the direction [d] along orientation [pos].
Parameters:
s (modified) set to the adjacent surfel in the specified direction d and orientation pos if it exists. Otherwise unchanged (method returns 0 in this case).
d any direction different from 'orthDir()'.
pos when 'true' look in positive direction along [track_dir] axis, 'false' look in negative direction.
Returns:
the move code (n=0-3). When 0: no adjacent surfel, otherwise 1-3: adjacent surfel is n-th follower.
Definition at line 111 of file DigitalSetBoundary.ih.
References DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::digitalSet().
{
  SetPredicate<DigitalSet> isInSet( surface().digitalSet() );
  return static_cast<uint8_t>
    ( myNeighborhood.getAdjacentOnPointPredicate( s, isInSet, d, pos ) );
}
template<typename TKSpace , typename TDigitalSet > const DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::Surfel & DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::current () const inline
Returns:
the current surfel on which the tracker is.
Definition at line 83 of file DigitalSetBoundary.ih.
{
  return myNeighborhood.surfel();
}
template<typename TKSpace , typename TDigitalSet > void DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::move (const Surfel & s) inline
Moves the tracker to the given valid surfel.
Precondition:
'surface().isInside(s)'
Parameters:
s the surfel on which the tracker is moved.
Definition at line 101 of file DigitalSetBoundary.ih.
References DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::isInside().
{
  ASSERT( surface().isInside( s ) );
  myNeighborhood.setSurfel( s );
}
template<typename TKSpace , typename TDigitalSet > DGtal::Dimension DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::orthDir () const inline
Returns:
the orthogonal direction to the current surfel.
Definition at line 92 of file DigitalSetBoundary.ih.
{
  return myNeighborhood.orthDir();
}
template<typename TKSpace , typename TDigitalSet > const DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::DigitalSurfaceContainer & DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::surface () const inline
Returns:
the surface container that the Tracker is tracking.
Definition at line 73 of file DigitalSetBoundary.ih.
Referenced by DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::Tracker().
{
  return mySurface;
}
Field Documentation
template<typename TKSpace, typename TDigitalSet> Neighborhood DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::myNeighborhood private
the current surfel neighborhood, the object that holds the necessary information for determining neighbors.
Definition at line 145 of file DigitalSetBoundary.h.
Referenced by DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::Tracker().
template<typename TKSpace, typename TDigitalSet> const DigitalSurfaceContainer& DGtal::DigitalSetBoundary< TKSpace, TDigitalSet >::Tracker::mySurface private
a reference to the digital surface container on which is the tracker.
Definition at line 142 of file DigitalSetBoundary.h.
The documentation for this class was generated from the following files:
DigitalSetBoundary.h
DigitalSetBoundary.ih