DGtal: SCellsRange Class Reference
SCellsRange Class Reference
Public Types
typedef GridCurve::Storage Storage
typedef
GridCurve::Storage::const_iterator ConstIterator
typedef
GridCurve::Storage::const_reverse_iterator ConstReverseIterator
typedef Circulator< ConstIterator > ConstCirculator
typedef std::reverse_iterator
< ConstCirculator > ConstReverseCirculator
Public Member Functions
SCellsRange ()
SCellsRange (const Storage &aStorage)
SCellsRange (const SCellsRange &aOther)
SCellsRange & operator= (const SCellsRange &other)
~SCellsRange ()
Storage::size_type size () const
bool isValid () const
void selfDisplay (std::ostream &out) const
DGtal::DrawableWithBoard2D * defaultStyle () const
DGtal::DrawableWithBoard2D * defaultStyle (std::string) const
std::string className () const
void selfDraw (Board2D &aBoard) const
ConstIterator begin () const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rend () const
ConstCirculator c () const
ConstReverseCirculator rc () const
Private Attributes
const GridCurve::Storage * myData
Friends
ostream & operator<< (ostream &out, const SCellsRange &object)
DGtal::DrawableWithBoard2D * defaultStyle (const SCellsRange &scr)
DGtal::DrawableWithBoard2D * defaultStyle (const SCellsRange &scr, std::string)
void draw (Board2D &aBoard, const SCellsRange &scr)
Detailed Description
Aim: model of CConstRange that provides services to (circularly)iterate over the signed d-cells of a grid curve.
(Included in GridCurve.h)
See also:
GridCurve.h exampleGridCurve2d.cpp testGridCurve.cpp
Definition at line 48 of file GridCurveRanges.ih.
Member Typedef Documentation
typedef Circulator<ConstIterator> SCellsRange::ConstCirculator
Definition at line 56 of file GridCurveRanges.ih.
typedef GridCurve::Storage::const_iterator SCellsRange::ConstIterator
Definition at line 54 of file GridCurveRanges.ih.
typedef std::reverse_iterator<ConstCirculator> SCellsRange::ConstReverseCirculator
Definition at line 57 of file GridCurveRanges.ih.
typedef GridCurve::Storage::const_reverse_iterator SCellsRange::ConstReverseIterator
Definition at line 55 of file GridCurveRanges.ih.
typedef GridCurve::Storage SCellsRange::Storage
Definition at line 53 of file GridCurveRanges.ih.
Constructor & Destructor Documentation
SCellsRange::SCellsRange () inline
Default Constructor.
Definition at line 62 of file GridCurveRanges.ih.
{}
SCellsRange::SCellsRange (const Storage & aStorage) inline
Constructor.
Parameters:
aStorage a range of cells.
Definition at line 68 of file GridCurveRanges.ih.
: myData(&aStorage){}
SCellsRange::SCellsRange (const SCellsRange & aOther) inline
Copy constructor.
Parameters:
other the iterator to clone.
Definition at line 74 of file GridCurveRanges.ih.
    : myData( aOther.myData ){}
SCellsRange::~SCellsRange () inline
Destructor. Does nothing.
Definition at line 94 of file GridCurveRanges.ih.
{}
Member Function Documentation
ConstIterator SCellsRange::begin () const inline
Iterator service.
Returns:
begin iterator
Definition at line 199 of file GridCurveRanges.ih.
References myData.
Referenced by selfDisplay(), and selfDraw().
{
    return myData->begin();
  }
ConstCirculator SCellsRange::c () const inline
Circulator service.
Returns:
a circulator
Definition at line 231 of file GridCurveRanges.ih.
References myData.
Referenced by rc().
{
    return ConstCirculator( myData->begin(), myData->begin(), myData->end() );
  }
std::string SCellsRange::className () const inline
Returns:
the style name used for drawing this object.
Definition at line 162 of file GridCurveRanges.ih.
  {
    return "SCellsRange";
  }
DGtal::DrawableWithBoard2D* SCellsRange::defaultStyle () const inline
Default drawing style object.
Returns:
the dyn. alloc. default style for this object.
Definition at line 138 of file GridCurveRanges.ih.
  {
    return new DrawableWithBoard2D;
  }
DGtal::DrawableWithBoard2D* SCellsRange::defaultStyle (std::string) const inline
Default drawing style object.
Parameters:
mode the drawing mode
Returns:
the dyn. alloc. default style for this object.
Definition at line 151 of file GridCurveRanges.ih.
  {
    return new DrawableWithBoard2D;
  }
ConstIterator SCellsRange::end () const inline
Iterator service.
Returns:
end iterator
Definition at line 207 of file GridCurveRanges.ih.
References myData.
Referenced by selfDisplay(), and selfDraw().
{
    return myData->end();
  }
bool SCellsRange::isValid () const inline
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
Definition at line 107 of file GridCurveRanges.ih.
{ return true; }
SCellsRange& SCellsRange::operator= (const SCellsRange & other) inline
Assignment.
Parameters:
other the iterator to copy.
Returns:
a reference on 'this'.
Definition at line 82 of file GridCurveRanges.ih.
References myData.
  {
    if ( this != &other )
      {
        myData = other.myData;
      }
    return *this;
  }
ConstReverseIterator SCellsRange::rbegin () const inline
Iterator service.
Returns:
rbegin iterator
Definition at line 215 of file GridCurveRanges.ih.
References myData.
{
    return myData->rbegin();
  }
ConstReverseCirculator SCellsRange::rc () const inline
Circulator service.
Returns:
a reverse circulator
Definition at line 239 of file GridCurveRanges.ih.
References c().
{
    return ConstReverseCirculator( this->c() );
  }
ConstReverseIterator SCellsRange::rend () const inline
Iterator service.
Returns:
rend iterator
Definition at line 223 of file GridCurveRanges.ih.
References myData.
{
    return myData->rend();
  }
void SCellsRange::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
Definition at line 113 of file GridCurveRanges.ih.
References begin(), and end().
  {
    typedef typename IteratorCirculatorTraits<ConstIterator>::Value Value;
    out << "[SCellsRange]" << std::endl;
    out << "\t";
    std::copy( this->begin(), this->end(), ostream_iterator<Value>(out, ", ") );
    out << std::endl;
  }
void SCellsRange::selfDraw (Board2D & aBoard) const inline
Draw the object on a Board2D board
Parameters:
board the output board where the object is drawn.
Definition at line 171 of file GridCurveRanges.ih.
References begin(), and end().
  {
    ConstIterator it ( this->begin() );
    ConstIterator itEnd ( this->end() );
    for( ; it != itEnd; ++it)
      {
        aBoard << *it;
      }
  }
Storage::size_type SCellsRange::size () const inline
Returns:
the size of the range
Definition at line 99 of file GridCurveRanges.ih.
References myData.
{
    return myData->size();
  }
Friends And Related Function Documentation
DGtal::DrawableWithBoard2D* defaultStyle (const SCellsRange & scr) friend
Definition at line 142 of file GridCurveRanges.ih.
  {
    return scr.defaultStyle();
  }
DGtal::DrawableWithBoard2D* defaultStyle (const SCellsRange & scr, std::string) friend
Definition at line 155 of file GridCurveRanges.ih.
  {
    return scr.defaultStyle();
  }
void draw (Board2D & aBoard, const SCellsRange & scr) friend
Definition at line 180 of file GridCurveRanges.ih.
  {
    scr.selfDraw(aBoard);
  }
ostream& operator<< (ostream & out, const SCellsRange & object) friend
Overloads 'operator<<' for displaying objects of class 'SCellsRange'.
Parameters:
out the output stream where the object is written.
object the object of class 'SCellsRange' to write.
Returns:
the output stream after the writing.
Definition at line 128 of file GridCurveRanges.ih.
  {
    object.selfDisplay( out );
    return out;
  }
Field Documentation
const GridCurve::Storage* SCellsRange::myData private
Pointer to the range of cells.
Definition at line 190 of file GridCurveRanges.ih.
Referenced by begin(), c(), end(), operator=(), rbegin(), rend(), and size().
The documentation for this class was generated from the following file:
GridCurveRanges.ih