DGtal: DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor > Class Template Reference
DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor > Class Template Reference
#include <DGtal/geometry/curves/estimation/TrueLocalEstimatorOnPoints.h>
Public Types
typedef TConstIteratorOnPoints ConstIterator
typedef TParametricShape ParametricShape
typedef TParametricShape::RealPoint RealPoint
typedef TParametricShapeFunctor ParametricShapeFunctor
typedef ParametricShapeFunctor::Quantity Quantity
Public Member Functions
TrueLocalEstimatorOnPoints ()
~TrueLocalEstimatorOnPoints ()
void init (const double h, const ConstIterator &itb, const ConstIterator &ite)
void attach (ParametricShape *aShapePtr)
Quantity eval (const ConstIterator &it) const
template<typename OutputIterator >
OutputIterator eval (const ConstIterator &itb, const ConstIterator &ite, OutputIterator result) const
bool isValid () const
Private Member Functions
TrueLocalEstimatorOnPoints (const TrueLocalEstimatorOnPoints &other)
TrueLocalEstimatorOnPoints & operator= (const TrueLocalEstimatorOnPoints &other)
Private Attributes
double myH
ConstIterator myBegin
ConstIterator myEnd
ParametricShapeFunctor * myFunctorPtr
Detailed Description
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor>
class DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >
Aim: Computes the true quantity to each element of a range associated to a parametric shape.
Description of template class 'TrueLocalEstimatorOnPoints'
Template Parameters
TConstIteratorOnPoints type of iterator on points used as query points.
TParametricShape type of the parametric shape.
TParametricShapeFunctor type of Functor used to evaluate the quantity.
Definition at line 68 of file TrueLocalEstimatorOnPoints.h.
Member Typedef Documentation
ConstIterator
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> typedef TConstIteratorOnPoints DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::ConstIterator
Definition at line 74 of file TrueLocalEstimatorOnPoints.h.
ParametricShape
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> typedef TParametricShape DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::ParametricShape
Definition at line 76 of file TrueLocalEstimatorOnPoints.h.
ParametricShapeFunctor
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> typedef TParametricShapeFunctor DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::ParametricShapeFunctor
Definition at line 79 of file TrueLocalEstimatorOnPoints.h.
Quantity
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> typedef ParametricShapeFunctor::Quantity DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::Quantity
Definition at line 80 of file TrueLocalEstimatorOnPoints.h.
RealPoint
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> typedef TParametricShape::RealPoint DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::RealPoint
Definition at line 77 of file TrueLocalEstimatorOnPoints.h.
Constructor & Destructor Documentation
TrueLocalEstimatorOnPoints() [1/2]
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::TrueLocalEstimatorOnPoints ()
Default constructor.
~TrueLocalEstimatorOnPoints()
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::~TrueLocalEstimatorOnPoints ()
Destructor.
TrueLocalEstimatorOnPoints() [2/2]
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::TrueLocalEstimatorOnPoints (const TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor > & other) private
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
Member Function Documentation
attach()
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> void DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::attach (ParametricShape * aShapePtr)
Attach a shape
Parameters
aShapePtr parametric shape
Referenced by testTrueLocalEstimatorOnShapeDigitization().
eval() [1/2]
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> Quantity DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::eval (const ConstIterator & it) const
Estimation at *it
Returns
the estimated quantity at *it
Referenced by testTrueLocalEstimatorOnShapeDigitization().
eval() [2/2]
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> template<typename OutputIterator > OutputIterator DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::eval (const ConstIterator & itb, const ConstIterator & ite, OutputIterator result) const
Estimation at each element of [itb , ite)
Parameters
itb begin iterator
ite end iterator
result the output iterator to the results.
Returns
the estimated quantity from itb till ite (excluded)
init()
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> void DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::init (const double h, const ConstIterator & itb, const ConstIterator & ite)
Initialisation.
Parameters
h grid size (must be >0).
itb begin iterator
ite end iterator
Referenced by testCompareEstimator(), and testTrueLocalEstimatorOnShapeDigitization().
isValid()
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> bool DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
operator=()
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> TrueLocalEstimatorOnPoints& DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::operator= (const TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor > & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
Field Documentation
myBegin
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> ConstIterator DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::myBegin private
Copy of the begin iterator.
Definition at line 152 of file TrueLocalEstimatorOnPoints.h.
myEnd
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> ConstIterator DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::myEnd private
Copy of the end iterator.
Definition at line 155 of file TrueLocalEstimatorOnPoints.h.
myFunctorPtr
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> ParametricShapeFunctor* DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::myFunctorPtr private
Owning pointer on a parametric shape functor.
Definition at line 158 of file TrueLocalEstimatorOnPoints.h.
myH
template<typename TConstIteratorOnPoints, typename TParametricShape, typename TParametricShapeFunctor> double DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::myH private
Grid size.
Definition at line 149 of file TrueLocalEstimatorOnPoints.h.
The documentation for this class was generated from the following file:
TrueLocalEstimatorOnPoints.h