DGtal: DGtal::SpaceND< dim, TInteger, TSize, TDimension > Class Template Reference
DGtal::SpaceND< dim, TInteger, TSize, TDimension > Class Template Reference
#include <SpaceND.h>
Data Structures
struct Subcospace
struct Subspace
Public Types
typedef TInteger Integer
typedef IntegerTraits< Integer >
::UnsignedVersion UnsignedInteger
typedef TSize Size
typedef TDimension Dimension
typedef PointVector< dim, Integer > Point
typedef PointVector< dim, Integer > Vector
typedef SpaceND< dim, Integer,
Size > Space
Public Member Functions
BOOST_CONCEPT_ASSERT ((CInteger< TInteger >))
BOOST_CONCEPT_ASSERT ((CUnsignedInteger< TSize >))
BOOST_CONCEPT_ASSERT ((CUnsignedInteger< TDimension >))
SpaceND ()
~SpaceND ()
Static Public Member Functions
template<std::size_t subdimension>
static Subspace< subdimension >
::Type subspace ()
template<std::size_t codimension>
static Subcospace< codimension >
::Type subcospace ()
static Dimension dimension ()
static void selfDisplay (std::ostream &out)
Static Public Attributes
static const Dimension staticDimension = dim
Private Member Functions
SpaceND & operator= (const SpaceND &other)
Detailed Description
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t>
class DGtal::SpaceND< dim, TInteger, TSize, TDimension >
Description of class 'SpaceND'
Aim: SpaceND defines the fundamental structure of a Digital Space in ND.
Todo:
documentation here!
Template Parameters:
Dimension the dimension of the Digital Space.
Integer the Integer class used to specify the arithmetic (default type = int).
Member Typedef Documentation
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> typedef TDimension DGtal::SpaceND< dim, TInteger, TSize, TDimension >::Dimension
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> typedef TInteger DGtal::SpaceND< dim, TInteger, TSize, TDimension >::Integer
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> typedef PointVector<dim,Integer> DGtal::SpaceND< dim, TInteger, TSize, TDimension >::Point
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> typedef TSize DGtal::SpaceND< dim, TInteger, TSize, TDimension >::Size
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> typedef SpaceND<dim, Integer, Size> DGtal::SpaceND< dim, TInteger, TSize, TDimension >::Space
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> typedef IntegerTraits<Integer>::UnsignedVersion DGtal::SpaceND< dim, TInteger, TSize, TDimension >::UnsignedInteger
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> typedef PointVector<dim,Integer> DGtal::SpaceND< dim, TInteger, TSize, TDimension >::Vector
Constructor & Destructor Documentation
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> DGtal::SpaceND< dim, TInteger, TSize, TDimension >::SpaceND () [inline]
Constructor
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> DGtal::SpaceND< dim, TInteger, TSize, TDimension >::~SpaceND () [inline]
Destructor.
Member Function Documentation
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> DGtal::SpaceND< dim, TInteger, TSize, TDimension >::BOOST_CONCEPT_ASSERT ((CInteger< TInteger >))
Todo:
fixer des concept check sur Integer
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> DGtal::SpaceND< dim, TInteger, TSize, TDimension >::BOOST_CONCEPT_ASSERT ((CUnsignedInteger< TSize >))
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> DGtal::SpaceND< dim, TInteger, TSize, TDimension >::BOOST_CONCEPT_ASSERT ((CUnsignedInteger< TDimension >))
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> static Dimension DGtal::SpaceND< dim, TInteger, TSize, TDimension >::dimension () [inline, static]
Returns:
the dimension of the digital space.
Referenced by DGtal::SpaceND< dim, TInteger, TSize, TDimension >::selfDisplay().
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> SpaceND& DGtal::SpaceND< dim, TInteger, TSize, TDimension >::operator= (const SpaceND< dim, TInteger, TSize, TDimension > & other) [private]
Assignment.
Parameters:
other the object to copy.
Returns:
a reference on 'this'. Forbidden by default.
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> static void DGtal::SpaceND< dim, TInteger, TSize, TDimension >::selfDisplay (std::ostream & out) [inline, static]
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
References DGtal::SpaceND< dim, TInteger, TSize, TDimension >::dimension().
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> template<std::size_t codimension> static Subcospace<codimension>::Type DGtal::SpaceND< dim, TInteger, TSize, TDimension >::subcospace () [inline, static]
Returns:
the digital space of specified codimension of this space.
References ASSERT, and dim.
Referenced by testSimpleSpace().
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> template<std::size_t subdimension> static Subspace<subdimension>::Type DGtal::SpaceND< dim, TInteger, TSize, TDimension >::subspace () [inline, static]
Returns:
the digital space of specified subdimension of this space.
References ASSERT, and dim.
Field Documentation
template<std::size_t dim, typename TInteger = DGtal::int32_t, typename TSize = DGtal::uint32_t, typename TDimension = DGtal::uint32_t> const Dimension DGtal::SpaceND< dim, TInteger, TSize, TDimension >::staticDimension = dim [static]
The documentation for this class was generated from the following file:
SpaceND.h