DGtal: DGtal::Space< TInt, Dimension > Class Template Reference
DGtal::Space< TInt, Dimension > Class Template Reference
#include <Space.h>
Classes
struct Subcospace
struct Subspace
Public Types
typedef TInt TInteger
typedef std::size_t TDimension
typedef Point< TInt, Dimension > TPoint
typedef Vector< TInt, Dimension > TVector
typedef Space< TInt, Dimension > TSpace
Public Member Functions
BOOST_CONCEPT_ASSERT ((boost::EqualityComparable< TInt >))
BOOST_CONCEPT_ASSERT ((boost::Assignable< TInt >))
Space ()
~Space ()
Static Public Member Functions
template<std::size_t Subdimension>
static Subspace< Subdimension >
::Type subspace ()
template<std::size_t Codimension>
static Subcospace< Codimension >
::Type subcospace ()
static TDimension dimension ()
static void selfDisplay (std::ostream &out)
Static Public Attributes
static const TDimension staticDimension = Dimension
Private Member Functions
Space & operator= (const Space &other)
Detailed Description
template<class TInt, std::size_t Dimension>
class DGtal::Space< TInt, Dimension >
Description of class 'Space'
Aim: Space defines the fundamental structure of a Digital Space.
Member Typedef Documentation
template<class TInt, std::size_t Dimension> typedef std::size_t DGtal::Space< TInt, Dimension >::TDimension
template<class TInt, std::size_t Dimension> typedef TInt DGtal::Space< TInt, Dimension >::TInteger
template<class TInt, std::size_t Dimension> typedef Point<TInt, Dimension> DGtal::Space< TInt, Dimension >::TPoint
template<class TInt, std::size_t Dimension> typedef Space<TInt,Dimension> DGtal::Space< TInt, Dimension >::TSpace
template<class TInt, std::size_t Dimension> typedef Vector<TInt,Dimension> DGtal::Space< TInt, Dimension >::TVector
Constructor & Destructor Documentation
template<class TInt, std::size_t Dimension> DGtal::Space< TInt, Dimension >::Space () [inline]
Constructor
template<class TInt, std::size_t Dimension> DGtal::Space< TInt, Dimension >::~Space () [inline]
Destructor.
Member Function Documentation
template<class TInt, std::size_t Dimension> DGtal::Space< TInt, Dimension >::BOOST_CONCEPT_ASSERT ((boost::Assignable< TInt >))
template<class TInt, std::size_t Dimension> DGtal::Space< TInt, Dimension >::BOOST_CONCEPT_ASSERT ((boost::EqualityComparable< TInt >))
Todo:
fixer des concept check sur TInt
template<class TInt, std::size_t Dimension> static TDimension DGtal::Space< TInt, Dimension >::dimension () [inline, static]
Returns:
the dimension of the digital space.
Referenced by DGtal::Space< TInt, Dimension >::selfDisplay().
template<class TInt, std::size_t Dimension> Space& DGtal::Space< TInt, Dimension >::operator= (const Space< TInt, Dimension > & other) [private]
Assignment.
Parameters:
other the object to copy.
Returns:
a reference on 'this'. Forbidden by default.
template<class TInt, std::size_t Dimension> static void DGtal::Space< TInt, Dimension >::selfDisplay (std::ostream & out) [inline, static]
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
References DGtal::Space< TInt, Dimension >::dimension().
template<class TInt, std::size_t Dimension> template<std::size_t Codimension> static Subcospace<Codimension>::Type DGtal::Space< TInt, Dimension >::subcospace () [inline, static]
Returns:
the digital space of specified codimension of this space.
References ASSERT.
Referenced by testSimpleSpace().
template<class TInt, std::size_t Dimension> template<std::size_t Subdimension> static Subspace<Subdimension>::Type DGtal::Space< TInt, Dimension >::subspace () [inline, static]
Returns:
the digital space of specified subdimension of this space.
References ASSERT.
Member Data Documentation
template<class TInt, std::size_t Dimension> const TDimension DGtal::Space< TInt, Dimension >::staticDimension = Dimension [static]
The documentation for this class was generated from the following file:
Space.h