DGtal: DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator Class Reference
DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator Class Reference
#include <ImageContainer_vector.h>
Public Types
typedef
std::bidirectional_iterator_tag iterator_category
typedef TValue value_type
typedef ptrdiff_t difference_type
typedef TValue * pointer
typedef TValue & reference
Public Member Functions
SpanIterator (const TPoint &p, const std::size_t aDim, ImageContainer_vector< TPoint, TValue > *aMap)
const TValue & operator* () const
void setValue (const TValue &v)
bool operator== (const SpanIterator &it) const
bool operator!= (const SpanIterator &it) const
void next ()
void prev ()
SpanIterator & operator++ ()
SpanIterator & operator++ (int)
SpanIterator & operator-- ()
SpanIterator & operator-- (int)
Private Attributes
TSizeType myPos
ImageContainer_vector< TPoint,
TValue > * myMap
std::size_t myDimension
TSizeType shift
Friends
class ImageContainer_vector< TPoint, TValue >
template<class TPoint, typename TValue>
class DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator
Member Typedef Documentation
template<class TPoint, typename TValue> typedef ptrdiff_t DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::difference_type
template<class TPoint, typename TValue> typedef std::bidirectional_iterator_tag DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::iterator_category
template<class TPoint, typename TValue> typedef TValue* DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::pointer
template<class TPoint, typename TValue> typedef TValue& DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::reference
template<class TPoint, typename TValue> typedef TValue DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::value_type
Todo:
construct a RANDOM-ACCESS iterator
Constructor & Destructor Documentation
template<class TPoint, typename TValue> DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::SpanIterator (const TPoint & p, const std::size_t aDim, ImageContainer_vector< TPoint, TValue > * aMap) [inline]
References DGtal::ImageContainer_vector< TPoint, TValue >::linearized(), DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::myDimension, DGtal::ImageContainer_vector< TPoint, TValue >::myLowerBound, DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::myPos, DGtal::ImageContainer_vector< TPoint, TValue >::myUpperBound, and DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::shift.
Member Function Documentation
template<class TPoint, typename TValue> void DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::next () [inline]
Implements the next() method
References DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::myPos, and DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::shift.
Referenced by DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::operator++().
template<class TPoint, typename TValue> bool DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::operator!= (const SpanIterator & it) const [inline]
Operator !=
References DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::myPos.
template<class TPoint, typename TValue> const TValue& DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::operator* () const [inline]
References DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::myMap, and DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::myPos.
template<class TPoint, typename TValue> SpanIterator& DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::operator++ (int) [inline]
Operator ++ (it++)
template<class TPoint, typename TValue> SpanIterator& DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::operator++ () [inline]
Operator ++ (++it)
References DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::next().
template<class TPoint, typename TValue> SpanIterator& DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::operator-- (int) [inline]
Operator -- (it--)
template<class TPoint, typename TValue> SpanIterator& DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::operator-- () [inline]
Operator -- (--it)
References DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::prev().
template<class TPoint, typename TValue> bool DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::operator== (const SpanIterator & it) const [inline]
Operator ==
References DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::myPos.
template<class TPoint, typename TValue> void DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::prev () [inline]
Implements the prev() method
References ASSERT, DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::myPos, and DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::shift.
Referenced by DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::operator--().
template<class TPoint, typename TValue> void DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::setValue (const TValue & v) [inline]
References DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::myPos.
Referenced by DGtal::ImageContainer_vector< TPoint, TValue >::setValue().
Friends And Related Function Documentation
template<class TPoint, typename TValue> friend class ImageContainer_vector< TPoint, TValue > [friend]
Member Data Documentation
template<class TPoint, typename TValue> std::size_t DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::myDimension [private]
Dimension on which the iterator must iterate.
Referenced by DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::SpanIterator().
template<class TPoint, typename TValue> ImageContainer_vector<TPoint,TValue>* DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::myMap [private]
Copy of the underlying images.
Referenced by DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::operator*().
template<class TPoint, typename TValue> TSizeType DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::myPos [private]
Current Point in the domain.
Referenced by DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::next(), DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::operator!=(), DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::operator*(), DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::operator==(), DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::prev(), DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::setValue(), and DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::SpanIterator().
template<class TPoint, typename TValue> TSizeType DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::shift [private]
Padding variable.
Referenced by DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::next(), DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::prev(), and DGtal::ImageContainer_vector< TPoint, TValue >::SpanIterator::SpanIterator().
The documentation for this class was generated from the following file:
ImageContainer_vector.h