DGtal: DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node Class Reference
DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node Class Reference
#include <ImageContainerByHashTreedav.h>
Public Member Functions
Node (ValueType object, HashKey key)
Node * getNext ()
void setNext (Node *next)
HashKey getKey ()
ValueType & getObject ()
~Node ()
Protected Attributes
HashKey myKey
Node * myNext
ValueType myData
template<typename TDomain, typename TValueType, typename THashKey = unsigned int>
class DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node
Constructor & Destructor Documentation
template<typename TDomain, typename TValueType, typename THashKey = unsigned int> DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::Node (ValueType object, HashKey key) [inline]
References DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::myData, and DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::myKey.
template<typename TDomain, typename TValueType, typename THashKey = unsigned int> DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::~Node () [inline]
Member Function Documentation
template<typename TDomain, typename TValueType, typename THashKey = unsigned int> HashKey DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::getKey () [inline]
References DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::myKey.
Referenced by DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Iterator::getKey(), and DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::getNode().
template<typename TDomain, typename TValueType, typename THashKey = unsigned int> Node* DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::getNext () [inline]
References DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::myNext.
Referenced by DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::getNode().
template<typename TDomain, typename TValueType, typename THashKey = unsigned int> ValueType& DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::getObject () [inline]
References DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::myData.
Referenced by DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::addNode(), and DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Iterator::operator*().
template<typename TDomain, typename TValueType, typename THashKey = unsigned int> void DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::setNext (Node * next) [inline]
References DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::myNext.
Referenced by DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::addNode().
Field Documentation
template<typename TDomain, typename TValueType, typename THashKey = unsigned int> ValueType DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::myData [protected]
Referenced by DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::getObject(), and DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::Node().
template<typename TDomain, typename TValueType, typename THashKey = unsigned int> HashKey DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::myKey [protected]
Referenced by DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::getKey(), and DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::Node().
template<typename TDomain, typename TValueType, typename THashKey = unsigned int> Node* DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::myNext [protected]
Referenced by DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::getNext(), and DGtal::ImageContainerByHashTree< TDomain, TValueType, THashKey >::Node::setNext().
The documentation for this class was generated from the following file:
ImageContainerByHashTreedav.h