DGtal: koch.cpp File Reference
koch.cpp File Reference
Draw a random complete graph.
#include <cstdlib>
#include <ctime>
#include <iostream>
#include <fstream>
#include <cmath>
#include <vector>
#include <utility>
#include "Board/Board.h"
Functions
int coordinate (int width)
void Koch (ShapeList &board, const Color &color, Point p1, Point p2, int depth)
int main (int, char *[])
Variables
const int HALF_RAND = RAND_MAX/16
const double dy = 10
Detailed Description
Draw a random complete graph.
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
Sebastien Fourey <http://www.greyc.ensicaen.fr/~seb>
Date:
Tue Aug 21
This source code is part of the Board project, a C++ library whose purpose is to allow simple drawings in EPS, FIG or SVG files. Copyright (C) 2007 Sebastien Fourey <http://www.greyc.ensicaen.fr/~seb/>
Function Documentation
int coordinate (int width)
Examples:
koch.cpp.
void Koch (ShapeList & board, const Color & color, Point p1, Point p2, int depth)
Examples:
koch.cpp.
References LibBoard::Color::blue(), LibBoard::Color::green(), LibBoard::Color::red(), LibBoard::Point::rotated(), and LibBoard::Color::setRGBi().
Referenced by main().
int main (int , char * [])
References LibBoard::Shape::bbox(), LibBoard::Board::clear(), LibBoard::ShapeList::dup(), Koch(), LibBoard::ShapeList::last(), LibBoard::Rect::left, LibBoard::Point::rotated(), LibBoard::Board::saveEPS(), LibBoard::Board::saveFIG(), LibBoard::Board::saveSVG(), and LibBoard::Rect::width.
Variable Documentation
const double dy = 10
Examples:
koch.cpp.
const int HALF_RAND = RAND_MAX/16
Examples:
koch.cpp.