DGtal: logo.cpp File Reference
logo.cpp File Reference
Sample drawing using the board library.
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <cmath>
#include "Board/Board.h"
Defines
#define M_PI 3.14159265358979323846
Functions
int main (int, char *[])
Detailed Description
Sample drawing using the board library.
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
Sebastien Fourey <http://www.greyc.ensicaen.fr/~seb>
Date:
Tue Aug 21
This source code is part of the Board project, a C++ library whose purpose is to allow simple drawings in EPS, FIG or SVG files. Copyright (C) 2007 Sebastien Fourey <http://www.greyc.ensicaen.fr/~seb/>
Define Documentation
#define M_PI 3.14159265358979323846
Examples:
logo.cpp.
Referenced by main(), and testExpander().
Function Documentation
int main (int , char * [])
References LibBoard::Board::A4, LibBoard::Board::addDuplicates(), LibBoard::Board::drawLine(), f(), LibBoard::Color::Green, LibBoard::Fonts::Helvetica, LibBoard::ShapeList::last(), M_PI, LibBoard::Shape::MiterJoin, LibBoard::Shape::RoundCap, LibBoard::Board::saveEPS(), LibBoard::Board::saveFIG(), LibBoard::Board::saveSVG(), LibBoard::Board::scale(), LibBoard::Board::setLineCap(), LibBoard::Board::setLineJoin(), LibBoard::Board::setLineStyle(), LibBoard::Board::setLineWidth(), LibBoard::Board::setPenColorRGBi(), and LibBoard::Shape::SolidStyle.