DGtal: MyDrawStyleCustomGreen Struct Reference
MyDrawStyleCustomGreen Struct Reference
Public Member Functions
virtual void selfDraw (LibBoard::Board &aBoard) const
virtual void selfDraw (DGtalBoard &aboard) const
Detailed Description
Custom style.
Member Function Documentation
virtual void MyDrawStyleCustomGreen::selfDraw (LibBoard::Board & aBoard) const [inline, virtual]
References LibBoard::Board::setFillColorRGBi(), and LibBoard::Board::setPenColorRGBi().
virtual void MyDrawStyleCustomGreen::selfDraw (DGtalBoard &) const [inline, virtual]
Operation to override. Does nothing by default.
Parameters:
board any object of type Board.
Reimplemented from DGtal::DrawableWithDGtalBoard.
References LibBoard::Board::setFillColorRGBi(), LibBoard::Board::setLineStyle(), LibBoard::Board::setLineWidth(), and LibBoard::Board::setPenColorRGBi().
The documentation for this struct was generated from the following files:
testDGtalBoardCustomStyle.cpp
testObjectBorder.cpp