DGtal: DGtal::ArithmeticalDSS< TDSS >::DigitalPointsStyle Struct Reference
DGtal::ArithmeticalDSS< TDSS >::DigitalPointsStyle Struct Reference
Public Member Functions
DigitalPointsStyle (LibBoard::Board &aBoard)
Detailed Description
template<typename TDSS>
struct DGtal::ArithmeticalDSS< TDSS >::DigitalPointsStyle
Default Style Functor for digital points drawing
Parameters:
aBoard
Constructor & Destructor Documentation
template<typename TDSS > DGtal::ArithmeticalDSS< TDSS >::DigitalPointsStyle::DigitalPointsStyle (LibBoard::Board & aBoard) [inline]
References LibBoard::Color::Black, LibBoard::Color::None, LibBoard::Board::setFillColor(), LibBoard::Board::setLineWidth(), and LibBoard::Board::setPenColor().
The documentation for this struct was generated from the following file:
ArithmeticalDSS.h