DGtal: DGtal::HyperRectDomain< TSpace >::SelfDrawStylePaving Struct Reference
DGtal::HyperRectDomain< TSpace >::SelfDrawStylePaving Struct Reference
Public Member Functions
SelfDrawStylePaving (LibBoard::Board &aboard)
template<typename TSpace>
struct DGtal::HyperRectDomain< TSpace >::SelfDrawStylePaving
Constructor & Destructor Documentation
template<typename TSpace> DGtal::HyperRectDomain< TSpace >::SelfDrawStylePaving::SelfDrawStylePaving (LibBoard::Board & aboard) [inline]
References LibBoard::Board::setFillColorRGBi(), LibBoard::Board::setLineStyle(), LibBoard::Board::setPenColorRGBi(), and LibBoard::Shape::SolidStyle.
The documentation for this struct was generated from the following file:
HyperRectDomain.h