DGtal: MyDrawStyleCustomFillColor Struct Reference
MyDrawStyleCustomFillColor Struct Reference
Public Member Functions
MyDrawStyleCustomFillColor (const Color &c)
virtual void selfDraw (DGtalBoard &aboard) const
Data Fields
Color myColor
Constructor & Destructor Documentation
MyDrawStyleCustomFillColor::MyDrawStyleCustomFillColor (const Color & c) [inline]
Member Function Documentation
virtual void MyDrawStyleCustomFillColor::selfDraw (DGtalBoard &) const [inline, virtual]
Operation to override. Does nothing by default.
Parameters:
board any object of type Board.
Reimplemented from DGtal::DrawableWithDGtalBoard.
References LibBoard::Board::setFillColor(), LibBoard::Board::setLineStyle(), LibBoard::Board::setLineWidth(), LibBoard::Board::setPenColorRGBi(), and LibBoard::Shape::SolidStyle.
Field Documentation
Color MyDrawStyleCustomFillColor::myColor
The documentation for this struct was generated from the following file:
testObject.cpp