DGtal: testGeneric.cpp File Reference
testGeneric.cpp File Reference
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/kernel/images/ImageSelector.h"
#include "DGtal/io/writers/GenericWriter.h"
#include "DGtal/io/readers/GenericReader.h"
#include "ConfigTest.h"
Functions
bool testGenericWriterReader ()
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testGenericWriterReader(), and DGtal::trace.
bool testGenericWriterReader ()
Example of a test. To be completed.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), and DGtal::trace.
Referenced by main().