DGtal: testExpander-benchmark.cpp File Reference
testExpander-benchmark.cpp File Reference
#include <iostream>
#include <sstream>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/DomainPredicate.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/kernel/sets/DigitalSetSelector.h"
#include "DGtal/kernel/sets/DigitalSetConverter.h"
#include "DGtal/topology/MetricAdjacency.h"
#include "DGtal/topology/DomainMetricAdjacency.h"
#include "DGtal/topology/DomainAdjacency.h"
#include "DGtal/topology/DigitalTopology.h"
#include "DGtal/topology/Object.h"
#include "DGtal/topology/Expander.h"
Defines
#define INBLOCK_TEST(x)
#define INBLOCK_TEST2(x, y)
Functions
bool testExpander ()
int main (int argc, char **argv)
Define Documentation
#define INBLOCK_TEST (x)
Value:
nbok += (x) ? 1 : 0; \
  nb++; \
  trace.info() << "(" << nbok << "/" << nb << ") " \
               << #x << std::endl;
Referenced by testExpander().
#define INBLOCK_TEST2 (x, y)
Value:
nbok += (x) ? 1 : 0; \
  nb++; \
  trace.info() << "(" << nbok << "/" << nb << ") " \
  << y << std::endl;
Function Documentation
int main (int argc, char ** argv)
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testExpander(), and DGtal::trace.
bool testExpander ()
Example of a test. To be completed.
References DGtal::Z3i::adj18, DGtal::Z3i::adj6, DGtal::Trace::beginBlock(), DGtal::Z3i::dt6_18, DGtal::Trace::endBlock(), INBLOCK_TEST, DGtal::Trace::info(), DGtal::JORDAN_DT, M_PI, and DGtal::trace.
Referenced by main().