DGtal: testDGtalBoardCustomStyle.cpp File Reference
testDGtalBoardCustomStyle.cpp File Reference
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/kernel/sets/DigitalSetBySTLVector.h"
#include "DGtal/kernel/sets/DigitalSetBySTLSet.h"
#include "DGtal/kernel/sets/DigitalSetSelector.h"
#include "DGtal/io/DGtalBoard.h"
Data Structures
struct MyDrawStyleCustomGreen
Functions
bool testDGtalBoardCustomStyle ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
davidcoeurjolly (login) (Unknown) Unknown
Date:
2010/10/24
Functions for testing class DGtalBoardCustomStyle.
This file is part of the DGtal library.
Function Documentation
int main (int argc, char ** argv)
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testDGtalBoardCustomStyle(), and DGtal::trace.
bool testDGtalBoardCustomStyle ()
Example of a test. To be completed.
References DGtal::BIG_DS, LibBoard::Board::clear(), DGtal::HIGH_BEL_DS, DGtal::HIGH_ITER_DS, LibBoard::Board::saveSVG(), LibBoard::Board::setUnit(), and LibBoard::Board::UCentimeter.
Referenced by main().