DGtal: testObjectBorder.cpp File Reference
testObjectBorder.cpp File Reference
#include <iostream>
#include <iterator>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/DomainPredicate.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/kernel/sets/DigitalSetSelector.h"
#include "DGtal/kernel/sets/DigitalSetConverter.h"
#include "DGtal/topology/MetricAdjacency.h"
#include "DGtal/topology/DomainMetricAdjacency.h"
#include "DGtal/topology/DomainAdjacency.h"
#include "DGtal/topology/DigitalTopology.h"
#include "DGtal/topology/Object.h"
#include "DGtal/topology/Expander.h"
#include "DGtal/io/DGtalBoard.h"
Data Structures
struct MyObjectStyleCustom
struct MyObjectStyleCustomRed
struct MyDrawStyleCustomRed
struct MyDrawStyleCustomBlue
struct MyDrawStyleCustomGreen
Functions
bool testObjectBorder ()
bool testDGtalBoard ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
David Coeurjolly (david.coeurjolly@liris.cnrs.fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date:
2010/09/17
Functions for testing class ObjectBorder.
This file is part of the DGtal library.
Function Documentation
int main (int argc, char ** argv)
References testDGtalBoard(), and testObjectBorder().
bool testDGtalBoard ()
Simple test of DGtalBoard. Illustrates the border extraction of a simple 2D object considering different topologies.
References DGtal::Z2i::adj4, DGtal::Z2i::adj8, DGtal::Trace::beginBlock(), LibBoard::Board::clear(), DGtal::Z2i::dt8_4, DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::JORDAN_DT, LibBoard::Board::saveSVG(), LibBoard::Board::setUnit(), and DGtal::trace.
Referenced by main().
bool testObjectBorder ()
Simple test to illustrate the border extraction of a simple 2D object considering different topologies.
References DGtal::Z2i::adj4, DGtal::Z2i::adj8, DGtal::Trace::beginBlock(), LibBoard::Board::clear(), DGtal::Z2i::dt4_8, DGtal::Z2i::dt8_4, DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::JORDAN_DT, LibBoard::Board::saveSVG(), LibBoard::Board::setUnit(), and DGtal::trace.
Referenced by main().