DGtal: test_DomainSpanIterator.cpp File Reference
test_DomainSpanIterator.cpp File Reference
#include <cstdio>
#include <cmath>
#include <iostream>
#include <fstream>
#include <algorithm>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/Space.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
Functions
bool testIterator ()
int main ()
Detailed Description
Author:
David Coeurjolly (david.coeurjolly@liris.cnrs.fr)
Date:
2010/05/30
This file is part of the DGtal library
Function Documentation
int main ()
References testIterator().
bool testIterator ()
Simple test of Span iterators on a 4D digital domain
Domain construction
iterates from {1, 2,1,1} to { 3,6,3,3} along the dimension 1
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::HyperRectDomain< TSpace >::isValid(), DGtal::HyperRectDomain< TSpace >::span_begin(), DGtal::HyperRectDomain< TSpace >::span_end(), and DGtal::trace.
Referenced by main().