DGtal: testIVViewer.cpp File Reference
testIVViewer.cpp File Reference
#include <iostream>
#include <Qt/qapplication.h>
#include <Inventor/nodes/SoCube.h>
#include "DGtal/inventor/DGtalInventor.h"
#include "DGtal/inventor/IVViewer.h"
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/helpers/Shapes.h"
Functions
bool testIVViewerSimpleWdw (int argc, char **argv)
bool testIVViewer (int argc, char **argv)
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
Jacques-Olivier Lachaud (jacques-olivier.lachaud@univ-savoie.fr) Laboratory of Mathematics (CNRS, UMR 5807), University of Savoie, France
Date:
2010/12/04
Functions for testing class IVViewer.
This file is part of the DGtal library.
Function Documentation
int main (int argc, char ** argv)
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testIVViewer(), and DGtal::trace.
bool testIVViewer (int argc, char ** argv)
Example of a test. To be completed.
References DGtal::DigitalSetBySTLSet< Domain >::begin(), DGtal::Trace::beginBlock(), DGtal::DGtalInventor< TSpace >::drawPoint(), DGtal::DigitalSetBySTLSet< Domain >::end(), DGtal::Trace::endBlock(), DGtal::DGtalInventor< TSpace >::generate(), DGtal::Trace::info(), DGtal::IVViewer::root(), DGtal::IVViewer::setCamera(), DGtal::DGtalInventor< TSpace >::setDiffuseColor(), DGtal::IVViewer::setTitle(), DGtal::IVViewer::show(), and DGtal::trace.
Referenced by main().
bool testIVViewerSimpleWdw (int argc, char ** argv)
Example of a test. To be completed.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::IVViewer::show(), and DGtal::trace.