DGtal: testSimpleBoard.cpp File Reference
testSimpleBoard.cpp File Reference
#include "DGtal/base/Common.h"
#include "DGtal/kernel/PointVector.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/io/DGtalBoard.h"
Functions
bool testSimpleBoard ()
bool testDomain ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
David Coeurjolly (david.coeurjolly@liris.cnrs.fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date:
2010/07/16
Functions for testing class SimpleBoard.
This file is part of the DGtal library.
Function Documentation
int main (int argc, char ** argv)
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testDomain(), testSimpleBoard(), and DGtal::trace.
bool testDomain ()
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), LibBoard::Board::saveSVG(), LibBoard::Board::scale(), and DGtal::trace.
Referenced by main().
bool testSimpleBoard ()
Example of a test. To be completed.
References LibBoard::Board::drawRectangle(), DGtal::Trace::endBlock(), LibBoard::Board::fillCircle(), LibBoard::Board::saveEPS(), LibBoard::Board::saveFIG(), LibBoard::Board::saveSVG(), LibBoard::Board::scale(), LibBoard::Board::setPenColorRGBi(), and DGtal::trace.
Referenced by main().