DGtal: test_HyperRectImage.cpp File Reference
test_HyperRectImage.cpp File Reference
#include <cstdio>
#include <cmath>
#include <iostream>
#include <fstream>
#include <algorithm>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/Space.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/kernel/domains/HyperRectImage.h"
Functions
bool testSimpleHyperRectImage ()
int main ()
Detailed Description
Author:
David Coeurjolly (david.coeurjolly@liris.cnrs.fr)
Date:
2010/05/25
This file is part of the DGtal library
Function Documentation
int main ()
References testSimpleHyperRectImage().
bool testSimpleHyperRectImage ()
Simple test of HyperRectImage construction.
Domain characterized by points a and b
References DGtal::Trace::beginBlock(), and DGtal::trace.
Referenced by main().