DGtal: 3dKSSurfaceExtraction.cpp File Reference
3dKSSurfaceExtraction.cpp File Reference
DGtal examples
#include <iostream>
#include "DGtal/base/Common.h"
#include <QtGui/qapplication.h>
#include "DGtal/io/readers/VolReader.h"
#include "DGtal/io/viewers/Viewer3D.h"
#include "DGtal/io/DrawWithDisplay3DModifier.h"
#include "DGtal/io/Color.h"
#include "DGtal/images/ImageSelector.h"
#include "DGtal/helpers/StdDefs.h"
#include "ConfigExamples.h"
#include "DGtal/io/colormaps/GradientColorMap.h"
#include "DGtal/topology/KhalimskySpaceND.h"
#include "DGtal/topology/helpers/Surfaces.h"
Functions
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
Bertrand Kerautret (kerautre@loria.fr) LORIA (CNRS, UMR 7503), University of Nancy, France
Date:
2011/06/27
An example file named 3dKSSurfaceExtraction.
This file is part of the DGtal library.
Definition in file 3dKSSurfaceExtraction.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 58 of file 3dKSSurfaceExtraction.cpp.
References DGtal::GradientColorMap< PValue, PDefaultPreset, PDefaultFirstColor, PDefaultLastColor >::addColor(), DGtal::HyperRectDomain< TSpace >::begin(), DGtal::Color::blue(), DGtal::HyperRectDomain< TSpace >::end(), DGtal::Trace::endBlock(), DGtal::Color::green(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), DGtal::DigitalSetBySTLSet< TDomain >::insertNew(), DGtal::HyperRectDomain< TSpace >::isInside(), DGtal::Color::red(), and DGtal::trace.