DGtal: Board3DTo2D.cpp File Reference
Board3DTo2D.cpp File Reference
Implementation of methods defined in Board3DTo2D.h.
#include "DGtal/io/boards/Board3DTo2D.h"
#include <limits>
#include <cairo.h>
#include <cairo-pdf.h>
#include <cairo-ps.h>
#include <cairo-svg.h>
Functions
static void TransposeMt (float tmat[16], float mat[16])
static void MulMt (float v[4], float mat[16], float b[4])
static void LookAtMt (float mat[16], float eyex, float eyey, float eyez, float dirx, float diry, float dirz, float upx, float upy, float upz)
Detailed Description
Implementation of methods defined in Board3DTo2D.h.
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
Martial Tola <http://liris.cnrs.fr/martial.tola/>
Date:
mercredi 22 juin 2011
This file is part of the DGtal library.
Definition in file Board3DTo2D.cpp.
Function Documentation
static void LookAtMt (float mat[16], float eyex, float eyey, float eyez, float dirx, float diry, float dirz, float upx, float upy, float upz) [static]
Compute 4x4 LookAt matrix.
Parameters:
mat destination matrix.
eyex x position of eye.
eyey y position of eye.
eyez z position of eye.
dirx x direction of eye.
diry y direction of eye.
dirz z director of eye.
upx x coordinate of up-vector.
upy y coordinate of up-vector.
upz z coordinate of up-vector.
Definition at line 124 of file Board3DTo2D.cpp.
References DGtal::cross(), MulMt(), DGtal::normalize(), and TransposeMt().
Referenced by DGtal::Board3DTo2D::precompute_projection_matrix().
static void MulMt (float v[4], float mat[16], float b[4]) [static]
Multiply a 3d vector by a 4x4 matrix.
Parameters:
v destination vector.
mat source matrix.
b source vector.
Definition at line 103 of file Board3DTo2D.cpp.
Referenced by LookAtMt().
static void TransposeMt (float tmat[16], float mat[16]) [static]
Transpose a 4x4 matrix.
Parameters:
tmat destination matrix.
mat source matrix.
Definition at line 89 of file Board3DTo2D.cpp.
Referenced by LookAtMt().