DGtal: DGtal::HyperRectDomain< TSpace > Class Template Reference
DGtal::HyperRectDomain< TSpace > Class Template Reference
Aim: Parallelepidec region of a digital space, model of a 'CDomain'.
#include <HyperRectDomain.h>
Data Structures
struct ConstSubRange
Aim: range through some subdomain of all the points in the domain. Defines a constructor taking a domain in parameter plus some additional parameters to specify the subdomain, begin and end methods returning ConstIterator, and rbegin and rend methods returning ConstReverseIterator.
struct DefaultDrawStyleGrid
struct DefaultDrawStylePaving
Public Types
typedef HyperRectDomain< TSpace > Self
typedef TSpace Space
typedef HyperRectDomain< Space > Domain
typedef Space::Point Point
typedef Space::Integer Integer
typedef Space::Vector Vector
typedef Space::Dimension Dimension
typedef Space::Size Size
typedef Point::Coordinate Coordinate
typedef
HyperRectDomain_Iterator
< Point > Iterator
typedef myreverse_iterator
< Iterator > ReverseIterator
typedef Iterator ConstIterator
typedef ReverseIterator ConstReverseIterator
typedef IsWithinPointPredicate
< Point > Predicate
Public Member Functions
HyperRectDomain ()
HyperRectDomain (const Point &aPointA, const Point &aPointB)
~HyperRectDomain ()
HyperRectDomain (const HyperRectDomain &other)
HyperRectDomain & operator= (const HyperRectDomain &other)
const ConstIterator & begin () const
ConstIterator begin (const Point &aPoint) const
const ConstIterator & end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rbegin (const Point &aPoint) const
ConstReverseIterator rend () const
ConstSubRange subRange (const std::vector< Dimension > &permutation) const
ConstSubRange subRange (const std::vector< Dimension > &permutation, const Point &startingPoint) const
ConstSubRange subRange (Dimension adim, const Point &startingPoint) const
ConstSubRange subRange (Dimension adim1, Dimension adim2, const Point &startingPoint) const
ConstSubRange subRange (Dimension adim1, Dimension adim2, Dimension adim3, const Point &startingPoint) const
Point size () const
const Point & lowerBound () const
const Point & upperBound () const
bool isInside (const Point &p) const
const Predicate & predicate () const
DrawableWithBoard2D * defaultStyle (std::string mode="") const
std::string styleName () const
void selfDraw (Board2D &board) const
void selfDrawAsGrid (Board2D &board) const
void selfDrawAsPaving (Board2D &board) const
DrawableWithDisplay3D * defaultStyleDisplay3D (std::string mode="") const
void selfDrawDisplay3D (Display3D &display) const
void selfDrawAsGridDisplay3D (Display3D &display) const
void selfDrawAsPavingDisplay3D (Display3D &display) const
void selfDrawAsPavingPointsDisplay3D (Display3D &display) const
void selfDrawAsBoundingBoxDisplay3D (Display3D &display) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Static Public Attributes
static const Space::Dimension dimension = Space::dimension
Private Member Functions
BOOST_CONCEPT_ASSERT ((CSpace< TSpace >))
Private Attributes
Point myLowerBound
Point myUpperBound
Predicate myPredicate
ConstIterator myIteratorBegin
ConstIterator myIteratorEnd
Detailed Description
template<typename TSpace>
class DGtal::HyperRectDomain< TSpace >
Aim: Parallelepidec region of a digital space, model of a 'CDomain'.
Description of class 'HyperRectDomain'
The following code snippet demonstrates how to use HyperRectDomain
  #include <DGtal/kernel/Space.h>
  #include <DGtal/kernel/domains/HyperRectDomain.h>
 ...
 //We create a digital Space based on 'int' integers and in dimension 4
 typedef DGtal::Space<4> Space4D;
 typedef Space4D::TPoint Point4D;
 const int rawA[ ] = { 1, 2, 3 ,4};
 const int rawB[ ] = { 5, 5, 3 ,4};
 Point4D A ( rawA );
 Point4D B ( rawB );
 //Domain construction from two points
 DGtal::HyperRectDomain<Space4D> myDomain ( A, B );
 //We iterate on the Domain points and print out the point coordinates.
 std::copy ( myDomain.begin(),
             myDomain.end(),
             std::ostream_iterator<Point4D> ( std::cout, " " ) );
See also:
testHyperRectDomain.cpp
testHyperRectDomain-snippet.cpp
Examples:
3dBorderExtraction.cpp, ctopo-1-3d.cpp, ctopo-1.cpp, ctopo-1s-3d.cpp, dgtalBoard2D-1-points.cpp, dgtalBoard2D-3-custom-classes.cpp, dgtalBoard2D-3-custom-points.cpp, distancetransform3D.cpp, and khalimskySpaceScanner.cpp.
Definition at line 94 of file HyperRectDomain.h.
Member Typedef Documentation
template<typename TSpace> typedef Iterator DGtal::HyperRectDomain< TSpace >::ConstIterator
Definition at line 121 of file HyperRectDomain.h.
template<typename TSpace> typedef ReverseIterator DGtal::HyperRectDomain< TSpace >::ConstReverseIterator
Definition at line 122 of file HyperRectDomain.h.
template<typename TSpace> typedef Point::Coordinate DGtal::HyperRectDomain< TSpace >::Coordinate
Definition at line 116 of file HyperRectDomain.h.
template<typename TSpace> typedef Space::Dimension DGtal::HyperRectDomain< TSpace >::Dimension
Definition at line 114 of file HyperRectDomain.h.
template<typename TSpace> typedef HyperRectDomain<Space> DGtal::HyperRectDomain< TSpace >::Domain
Definition at line 110 of file HyperRectDomain.h.
template<typename TSpace> typedef Space::Integer DGtal::HyperRectDomain< TSpace >::Integer
Definition at line 112 of file HyperRectDomain.h.
template<typename TSpace> typedef HyperRectDomain_Iterator<Point> DGtal::HyperRectDomain< TSpace >::Iterator
Typedef of domain iterators.
Definition at line 119 of file HyperRectDomain.h.
template<typename TSpace> typedef Space::Point DGtal::HyperRectDomain< TSpace >::Point
Definition at line 111 of file HyperRectDomain.h.
template<typename TSpace> typedef IsWithinPointPredicate<Point> DGtal::HyperRectDomain< TSpace >::Predicate
Definition at line 124 of file HyperRectDomain.h.
template<typename TSpace> typedef myreverse_iterator<Iterator> DGtal::HyperRectDomain< TSpace >::ReverseIterator
Definition at line 120 of file HyperRectDomain.h.
template<typename TSpace> typedef HyperRectDomain<TSpace> DGtal::HyperRectDomain< TSpace >::Self
Definition at line 101 of file HyperRectDomain.h.
template<typename TSpace> typedef Space::Size DGtal::HyperRectDomain< TSpace >::Size
Definition at line 115 of file HyperRectDomain.h.
template<typename TSpace> typedef TSpace DGtal::HyperRectDomain< TSpace >::Space
Definition at line 105 of file HyperRectDomain.h.
template<typename TSpace> typedef Space::Vector DGtal::HyperRectDomain< TSpace >::Vector
Definition at line 113 of file HyperRectDomain.h.
Constructor & Destructor Documentation
template<typename TSpace > DGtal::HyperRectDomain< TSpace >::HyperRectDomain () [inline]
Default Constructor.
Definition at line 40 of file HyperRectDomain.ih.
References DGtal::HyperRectDomain< TSpace >::myIteratorEnd.
  : myLowerBound(Point::zero),
    myUpperBound(Point::zero),
    myPredicate( myLowerBound, myUpperBound ),
    myIteratorBegin(myLowerBound,
        myLowerBound,
        myUpperBound),
    myIteratorEnd(myUpperBound,
      myLowerBound,
      myUpperBound)
{ ++myIteratorEnd; }
template<typename TSpace > DGtal::HyperRectDomain< TSpace >::HyperRectDomain (const Point & aPointA, const Point & aPointB) [inline]
Constructor from two points
Parameters:
aPointA and
aPointB defining the space diagonal.
Definition at line 54 of file HyperRectDomain.ih.
References DGtal::HyperRectDomain< TSpace >::myIteratorEnd.
                                     :
    myLowerBound(std::min(aPointA, aPointB)),
    myUpperBound(std::max(aPointA, aPointB)),
    myPredicate( myLowerBound, myUpperBound ),
    myIteratorBegin(myLowerBound,
        myLowerBound,
        myUpperBound),
    myIteratorEnd(myUpperBound,
      myLowerBound,
      myUpperBound)
{ ++myIteratorEnd; }
template<typename TSpace > DGtal::HyperRectDomain< TSpace >::~HyperRectDomain () [inline]
Destructor.
Definition at line 85 of file HyperRectDomain.ih.
{}
template<typename TSpace> DGtal::HyperRectDomain< TSpace >::HyperRectDomain (const HyperRectDomain< TSpace > & other)
Copy constructor.
Parameters:
other the object to clone. Forbidden by default.
Member Function Documentation
template<typename TSpace> const ConstIterator& DGtal::HyperRectDomain< TSpace >::begin () const [inline]
Definition at line 164 of file HyperRectDomain.h.
References DGtal::HyperRectDomain< TSpace >::myIteratorBegin.
Referenced by DGtal::HyperRectDomain< TSpace >::rbegin(), and DGtal::HyperRectDomain< TSpace >::rend().
    { return myIteratorBegin; }
template<typename TSpace> ConstIterator DGtal::HyperRectDomain< TSpace >::begin (const Point & aPoint) const [inline]
Definition at line 173 of file HyperRectDomain.h.
References DGtal::HyperRectDomain< TSpace >::isInside(), DGtal::HyperRectDomain< TSpace >::myLowerBound, and DGtal::HyperRectDomain< TSpace >::myUpperBound.
    { ASSERT(isInside(aPoint));
      return ConstIterator(aPoint,
         myLowerBound, myUpperBound); }
template<typename TSpace> DGtal::HyperRectDomain< TSpace >::BOOST_CONCEPT_ASSERT ((CSpace< TSpace >)) [private]
template<typename TSpace > DGtal::DrawableWithBoard2D * DGtal::HyperRectDomain< TSpace >::defaultStyle (std::string mode = "") const [inline]
Default drawing style object.
Returns:
the dyn. alloc. default style for this object.
Definition at line 168 of file HyperRectDomain.ih.
{
  if ( ( mode == "" ) || ( mode == "Both" ) || ( mode == "Grid" ) )
    return new DefaultDrawStyleGrid;
  else // mode == "Paving"
    return new DefaultDrawStylePaving;
}
template<typename TSpace> DrawableWithDisplay3D* DGtal::HyperRectDomain< TSpace >::defaultStyleDisplay3D (std::string mode = "") const
Default drawing style object.
Returns:
the dyn. alloc. default style for this object.
template<typename TSpace> const ConstIterator& DGtal::HyperRectDomain< TSpace >::end () const [inline]
Definition at line 182 of file HyperRectDomain.h.
References DGtal::HyperRectDomain< TSpace >::myIteratorEnd.
Referenced by DGtal::HyperRectDomain< TSpace >::rbegin().
    { return myIteratorEnd; }
template<typename TSpace > bool DGtal::HyperRectDomain< TSpace >::isInside (const Point & p) const [inline]
Parameters:
p any point.
Returns:
'true' if point [p] is inside this domain.
Definition at line 126 of file HyperRectDomain.ih.
Referenced by DGtal::HyperRectDomain< TSpace >::begin(), and DGtal::HyperRectDomain< TSpace >::rbegin().
{
  return myPredicate( p );
  //LowerBound.isLower( p ) && myUpperBound.isUpper( p );
}
template<typename TSpace > bool DGtal::HyperRectDomain< TSpace >::isValid () const [inline]
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
Definition at line 160 of file HyperRectDomain.ih.
{
  return true;
}
template<typename TSpace > const DGtal::HyperRectDomain< TSpace >::Point & DGtal::HyperRectDomain< TSpace >::lowerBound () const [inline]
Returns the lowest point of the space diagonal.
Examples:
khalimskySpaceScanner.cpp.
Definition at line 118 of file HyperRectDomain.ih.
Referenced by Exporter< Set, Image >::exportSignature().
{
  return myLowerBound;
}
template<typename TSpace> HyperRectDomain& DGtal::HyperRectDomain< TSpace >::operator= (const HyperRectDomain< TSpace > & other)
Assignment.
Parameters:
other the object to copy.
Returns:
a reference on 'this'. Forbidden by default.
template<typename TSpace > const DGtal::HyperRectDomain< TSpace >::Predicate & DGtal::HyperRectDomain< TSpace >::predicate () const [inline]
Returns:
a const reference to the "IsInside" predicate.
NB: Could have used template class DomainPredicate but, for performance reason, directly used the IsWithinPointPredicate which fits perfectly.
Definition at line 135 of file HyperRectDomain.ih.
{
  return myPredicate;
}
template<typename TSpace> ConstReverseIterator DGtal::HyperRectDomain< TSpace >::rbegin (const Point & aPoint) const [inline]
Definition at line 198 of file HyperRectDomain.h.
References DGtal::HyperRectDomain< TSpace >::begin(), and DGtal::HyperRectDomain< TSpace >::isInside().
    {  ASSERT(isInside(aPoint));
      ConstIterator it(begin(aPoint)); ++it;
      return ConstReverseIterator(it); }
template<typename TSpace> ConstReverseIterator DGtal::HyperRectDomain< TSpace >::rbegin () const [inline]
Definition at line 189 of file HyperRectDomain.h.
References DGtal::HyperRectDomain< TSpace >::end().
    { return ConstReverseIterator(end()); }
template<typename TSpace> ConstReverseIterator DGtal::HyperRectDomain< TSpace >::rend () const [inline]
Definition at line 207 of file HyperRectDomain.h.
References DGtal::HyperRectDomain< TSpace >::begin().
    { return ConstReverseIterator(begin()); }
template<typename TSpace > void DGtal::HyperRectDomain< TSpace >::selfDisplay (std::ostream & out) const [inline]
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
Definition at line 151 of file HyperRectDomain.ih.
{
  out << "[HyperRectDomain] = [" << myLowerBound << "]x["
  << myUpperBound << "]";
}
template<typename TSpace > void DGtal::HyperRectDomain< TSpace >::selfDraw (Board2D & board) const [inline]
Draw the object on a Board2D board.
Parameters:
board the output board where the object is drawn.
Definition at line 187 of file HyperRectDomain.ih.
References DGtal::Board2D::getMode().
{
  std::string mode = board.getMode( this->styleName() );
  ASSERT((mode=="" || mode=="Grid" || mode=="Paving") ||
   ("DGtal::HyperRectDomain<TSpace>::selfDraw: Unknown mode "+mode)=="");
  if ( ( mode == "" ) || ( mode == "Grid" ) )
    selfDrawAsGrid( board );
  else if ( mode == "Paving" )
    selfDrawAsPaving( board );
  // selfDrawAsGrid( board );
}
template<typename TSpace > void DGtal::HyperRectDomain< TSpace >::selfDrawAsBoundingBoxDisplay3D (Display3D & display) const [inline]
Definition at line 283 of file HyperRectDomain.ih.
References DGtal::Display3D::addQuad().
{
  ASSERT(TSpace::dimension == 3 || "selfDraw-NOT-YET-IMPLEMENTED-in-ND");
  DGtal::Color colDef(250,250,250,10);
  float shiftSize=0.01;
  if (TSpace::dimension == 3)
    {
      //Z upper face
      display.addQuad(myUpperBound[0]+(0.5+shiftSize), myUpperBound[1]+(0.5+shiftSize), myUpperBound[2]+(0.5+shiftSize),
         myLowerBound[0]-(0.5+shiftSize), myUpperBound[1]+(0.5+shiftSize), myUpperBound[2]+(0.5+shiftSize),
         myLowerBound[0]-(0.5+shiftSize), myLowerBound[1]-(0.5+shiftSize), myUpperBound[2]+(0.5+shiftSize),
         myUpperBound[0]+(0.5+shiftSize), myLowerBound[1]-(0.5+shiftSize), myUpperBound[2]+(0.5+shiftSize),
         colDef);
      //Z lower face
      display.addQuad(myUpperBound[0]+(0.5+shiftSize), myUpperBound[1]+(0.5+shiftSize), myLowerBound[2]-(0.5+shiftSize),
         myUpperBound[0]+(0.5+shiftSize), myLowerBound[1]-(0.5+shiftSize), myLowerBound[2]-(0.5+shiftSize),
         myLowerBound[0]-(0.5+shiftSize), myLowerBound[1]-(0.5+shiftSize), myLowerBound[2]-(0.5+shiftSize),
         myLowerBound[0]-(0.5+shiftSize), myUpperBound[1]+(0.5+shiftSize), myLowerBound[2]-(0.5+shiftSize),
         colDef);
      //Y upper face
      display.addQuad(myUpperBound[0]+(0.5+shiftSize), myUpperBound[1]+(0.5+shiftSize),myUpperBound[2]+(0.5+shiftSize),
         myUpperBound[0]+(0.5+shiftSize), myUpperBound[1]+(0.5+shiftSize),myLowerBound[2]-(0.5+shiftSize),
         myLowerBound[0]-(0.5+shiftSize), myUpperBound[1]+(0.5+shiftSize),myLowerBound[2]-(0.5+shiftSize),
         myLowerBound[0]-(0.5+shiftSize), myUpperBound[1]+(0.5+shiftSize),myUpperBound[2]+(0.5+shiftSize),
         colDef);
      //Y lower face
      display.addQuad(myUpperBound[0]+(0.5+shiftSize), myLowerBound[1]-(0.5+shiftSize),myUpperBound[2]+(0.5+shiftSize),
         myLowerBound[0]-(0.5+shiftSize), myLowerBound[1]-(0.5+shiftSize),myUpperBound[2]+(0.5+shiftSize),
         myLowerBound[0]-(0.5+shiftSize), myLowerBound[1]-(0.5+shiftSize),myLowerBound[2]-(0.5+shiftSize),
         myUpperBound[0]+(0.5+shiftSize), myLowerBound[1]-(0.5+shiftSize),myLowerBound[2]-(0.5+shiftSize),
         colDef);
      // X upper face
      display.addQuad(myUpperBound[0]+(0.5+shiftSize), myUpperBound[1]+(0.5+shiftSize),myUpperBound[2]+(0.5+shiftSize),
         myUpperBound[0]+(0.5+shiftSize), myLowerBound[1]-(0.5+shiftSize),myUpperBound[2]+(0.5+shiftSize),
         myUpperBound[0]+(0.5+shiftSize), myLowerBound[1]-(0.5+shiftSize),myLowerBound[2]-(0.5+shiftSize),
         myUpperBound[0]+(0.5+shiftSize), myUpperBound[1]+(0.5+shiftSize),myLowerBound[2]-(0.5+shiftSize),
         colDef);
      //  X lower face
      display.addQuad(myLowerBound[0]-(0.5+shiftSize), myUpperBound[1]+(0.5+shiftSize),myUpperBound[2]+(0.5+shiftSize),
         myLowerBound[0]-(0.5+shiftSize), myUpperBound[1]+(0.5+shiftSize),myLowerBound[2]-(0.5+shiftSize),
         myLowerBound[0]-(0.5+shiftSize), myLowerBound[1]-(0.5+shiftSize),myLowerBound[2]-(0.5+shiftSize),
         myLowerBound[0]-(0.5+shiftSize), myLowerBound[1]-(0.5+shiftSize),myUpperBound[2]+(0.5+shiftSize),
         colDef);
    }
}
template<typename TSpace > void DGtal::HyperRectDomain< TSpace >::selfDrawAsGrid (Board2D & board) const [inline]
Draw the object (as a Grid) on a LiBoard board.
Parameters:
board the output board where the object is drawn.
asGrid to choose between paving vs. grid representation.
Definition at line 206 of file HyperRectDomain.ih.
References LibBoard::Board::drawLine(), and LibBoard::Board::fillCircle().
{
  ASSERT(TSpace::dimension == 2 || "selfDraw-NOT-YET-IMPLEMENTED-in-ND");
  if (TSpace::dimension == 2)
  {
    for (double x = NumberTraits<Integer>::castToDouble(myLowerBound[0]);
   x <=  NumberTraits<Integer>::castToDouble(myUpperBound[0]); x++)
      aboard.drawLine(x,
          NumberTraits<Integer>::castToDouble(myLowerBound[1]) -
          0.5,
          x,
          NumberTraits<Integer>::castToDouble(myUpperBound[1]) +
          0.5);
    for (double y =  NumberTraits<Integer>::castToDouble(myLowerBound[1]);
   y <=  NumberTraits<Integer>::castToDouble(myUpperBound[1]); y++)
      aboard.drawLine(NumberTraits<Integer>::castToDouble(myLowerBound[0]) -
          0.5,
          y,
          NumberTraits<Integer>::castToDouble(myUpperBound[0]) +
          0.5,
          y);
    for (double x =  NumberTraits<Integer>::castToDouble(myLowerBound[0]);
   x <=  NumberTraits<Integer>::castToDouble(myUpperBound[0]); x++)
      for (double y =  NumberTraits<Integer>::castToDouble(myLowerBound[1]);
     y <=  NumberTraits<Integer>::castToDouble(myUpperBound[1]); y++)
        aboard.fillCircle(x, y, 0.1);
  }
}
template<typename TSpace > void DGtal::HyperRectDomain< TSpace >::selfDrawAsGridDisplay3D (Display3D & display) const [inline]
Definition at line 337 of file HyperRectDomain.ih.
References DGtal::Display3D::addLine(), and DGtal::Display3D::getLineColor().
{
  ASSERT(TSpace::dimension == 3 || "selfDraw-NOT-YET-IMPLEMENTED-in-ND");
  if (TSpace::dimension == 3)
  {
    // Face XY
    for (int64_t z = NumberTraits<Integer>::castToInt64_t(myLowerBound[2]);
   z <=  NumberTraits<Integer>::castToInt64_t(myUpperBound[2]); z++){
      for (int64_t x = NumberTraits<Integer>::castToInt64_t(myLowerBound[0]);
     x <=  NumberTraits<Integer>::castToInt64_t(myUpperBound[0]); x++){
  display.addLine(x, NumberTraits<Integer>::castToInt64_t(myLowerBound[1])-0.5,z,
           x, NumberTraits<Integer>::castToInt64_t(myUpperBound[1])+0.5,z,display.getLineColor() );
      }
      for (int64_t y =  NumberTraits<Integer>::castToInt64_t(myLowerBound[1]);
     y <=  NumberTraits<Integer>::castToInt64_t(myUpperBound[1]); y++){
  display.addLine(NumberTraits<Integer>::castToInt64_t(myLowerBound[0])-0.5,y ,z,
           NumberTraits<Integer>::castToInt64_t(myUpperBound[0])+0.5,y,z,  display.getLineColor());
      }
    }
    // Faces XZ
    for (int64_t y = NumberTraits<Integer>::castToInt64_t(myLowerBound[1]);
   y <=  NumberTraits<Integer>::castToInt64_t(myUpperBound[1]); y++){
      for (int64_t x = NumberTraits<Integer>::castToInt64_t(myLowerBound[0]);
     x <=  NumberTraits<Integer>::castToInt64_t(myUpperBound[0]); x++){
  display.addLine(x, y ,NumberTraits<Integer>::castToInt64_t(myLowerBound[2])-0.5,
           x, y ,NumberTraits<Integer>::castToInt64_t(myLowerBound[2])+0.5,display.getLineColor());
      }
      for (int64_t z =  NumberTraits<Integer>::castToInt64_t(myLowerBound[2]);
     z <=  NumberTraits<Integer>::castToInt64_t(myUpperBound[2]); z++){
  display.addLine(NumberTraits<Integer>::castToInt64_t(myLowerBound[0])-0.5,y ,z,
           NumberTraits<Integer>::castToInt64_t(myUpperBound[0])+0.5,y, z, display.getLineColor());
      }
    }
    // Faces YZ
    for (int64_t x = NumberTraits<Integer>::castToInt64_t(myLowerBound[0]);
   x <=  NumberTraits<Integer>::castToInt64_t(myUpperBound[0]); x++){
      for (int64_t y = NumberTraits<Integer>::castToInt64_t(myLowerBound[1]);
     y <=  NumberTraits<Integer>::castToInt64_t(myUpperBound[1]); y++){
  display.addLine(x, y ,NumberTraits<Integer>::castToInt64_t(myLowerBound[2])-0.5,
           x, y ,NumberTraits<Integer>::castToInt64_t(myUpperBound[2])+0.5, display.getLineColor());
      }
      for (int64_t z =  NumberTraits<Integer>::castToInt64_t(myLowerBound[2]);
     z <=  NumberTraits<Integer>::castToInt64_t(myUpperBound[2]); z++){
  display.addLine(x, NumberTraits<Integer>::castToInt64_t(myLowerBound[1])-0.5 ,z,
           x, NumberTraits<Integer>::castToInt64_t(myUpperBound[1])+0.5, z, display.getLineColor());
      }
    }
  }
}
template<typename TSpace > void DGtal::HyperRectDomain< TSpace >::selfDrawAsPaving (Board2D & board) const [inline]
Draw the object (as a Grid) on a LiBoard board.
Parameters:
board the output board where the object is drawn.
asGrid to choose between paving vs. grid representation.
Definition at line 468 of file HyperRectDomain.ih.
References LibBoard::Board::drawRectangle().
{
  ASSERT(TSpace::dimension==2 || "selfDraw-NOT-YET-IMPLEMENTED-in-ND" );
  if (TSpace::dimension == 2)
  {
    for (int64_t x = NumberTraits<Integer>::castToInt64_t(myLowerBound[0]);
   x <= NumberTraits<Integer>::castToInt64_t(myUpperBound[0]); x++)
      for (int64_t y = NumberTraits<Integer>::castToInt64_t(myLowerBound[1]);
     y <= NumberTraits<Integer>::castToInt64_t(myUpperBound[1]); y++)
        aboard.drawRectangle(x - 0.5, y + 0.5, 1, 1);
  }
}
template<typename TSpace > void DGtal::HyperRectDomain< TSpace >::selfDrawAsPavingDisplay3D (Display3D & display) const [inline]
Definition at line 428 of file HyperRectDomain.ih.
References DGtal::Display3D::addVoxel().
{
  ASSERT(TSpace::dimension == 3 || "selfDraw-NOT-YET-IMPLEMENTED-in-ND");
  if (TSpace::dimension == 3)
    {
    // Face XY
    for (int64_t z = NumberTraits<Integer>::castToInt64_t(myLowerBound[2]);
   z <=  NumberTraits<Integer>::castToInt64_t(myUpperBound[2]); z++){
      for (int64_t x = NumberTraits<Integer>::castToInt64_t(myLowerBound[0]);
     x <=  NumberTraits<Integer>::castToInt64_t(myUpperBound[0]); x++){
  for (int64_t y =  NumberTraits<Integer>::castToInt64_t(myLowerBound[1]);
       y <=  NumberTraits<Integer>::castToInt64_t(myUpperBound[1]); y++){
    display.addVoxel(x, y , z, DGtal::Color(255, 255 ,255, 15),0.51);
  }
      }
    }
    }
}
template<typename TSpace > void DGtal::HyperRectDomain< TSpace >::selfDrawAsPavingPointsDisplay3D (Display3D & display) const [inline]
Definition at line 398 of file HyperRectDomain.ih.
References DGtal::Display3D::addPoint().
{
  ASSERT(TSpace::dimension == 3 || "selfDraw-NOT-YET-IMPLEMENTED-in-ND");
  if (TSpace::dimension == 3)
  {
    // Face XY
    for (int64_t z = NumberTraits<Integer>::castToInt64_t(myLowerBound[2]);
   z <=  NumberTraits<Integer>::castToInt64_t(myUpperBound[2]); z++){
      for (int64_t x = NumberTraits<Integer>::castToInt64_t(myLowerBound[0]);
     x <=  NumberTraits<Integer>::castToInt64_t(myUpperBound[0]); x++){
  for (int64_t y =  NumberTraits<Integer>::castToInt64_t(myLowerBound[1]);
       y <=  NumberTraits<Integer>::castToInt64_t(myUpperBound[1]); y++){
    display.addPoint(x, y , z, DGtal::Color(255, 0 ,0));
  }
      }
    }
  }
}
template<typename TSpace > void DGtal::HyperRectDomain< TSpace >::selfDrawDisplay3D (Display3D & display) const [inline]
Draw the object on a Board2D board.
Parameters:
board the output board where the object is drawn.
Definition at line 245 of file HyperRectDomain.ih.
References DGtal::Display3D::createNewLineList(), DGtal::Display3D::createNewPointList(), DGtal::Display3D::createNewVoxelList(), and DGtal::Display3D::getMode().
{
  std::string mode = display.getMode( this->styleName() );
  ASSERT((mode=="" || mode=="Grid" || mode=="Paving"|| mode=="PavingPoints"|| mode=="PavingGrids" ||
    mode=="BoundingBox")||
   ("DGtal::HyperRectDomain<TSpace>::selfDraw: Unknown mode "+mode)=="");
  if (  mode == "BoundingBox"  ){
    display.createNewLineList();
    selfDrawAsBoundingBoxDisplay3D( display );
  }else if( ( mode == "" ) ||  (mode == "Grid")){
    display.createNewLineList();
    selfDrawAsGridDisplay3D( display );
  }
  else if ( mode == "Paving" ){
    display.createNewVoxelList(false);
    selfDrawAsPavingDisplay3D( display );
  } else if ( mode == "PavingPoints" ){
    display.createNewPointList();
    selfDrawAsPavingPointsDisplay3D( display );
  }else if ( mode == "PavingGrids" ){
    display.createNewLineList();
    display.createNewVoxelList(false);
    selfDrawAsGridDisplay3D( display );
    selfDrawAsPavingDisplay3D( display );
  }
  // selfDrawAsGrid( board );
}
template<typename TSpace> Point DGtal::HyperRectDomain< TSpace >::size () const [inline]
Returns:
the size of the HyperRectDomain
Definition at line 490 of file HyperRectDomain.h.
References DGtal::HyperRectDomain< TSpace >::myLowerBound, and DGtal::HyperRectDomain< TSpace >::myUpperBound.
    {
      Point p;
      for(typename Point::Iterator it=p.begin(), itend=p.end();
    it != itend; ++it)
        (*it) = 1;
      return (myUpperBound - myLowerBound) + p;
    }
template<typename TSpace > std::string DGtal::HyperRectDomain< TSpace >::styleName () const [inline]
Returns:
the style name used for drawing this object.
Examples:
ctopo-1-3d.cpp, ctopo-1.cpp, ctopo-1s-3d.cpp, and khalimskySpaceScanner.cpp.
Definition at line 179 of file HyperRectDomain.ih.
{
  return "HyperRectDomain";
}
template<typename TSpace> ConstSubRange DGtal::HyperRectDomain< TSpace >::subRange (const std::vector< Dimension > & permutation) const [inline]
get a subRange.
Parameters:
permutation a vector containing the dimensions used for the subrange. Dimensions are iterated in the given order.
Returns:
a sub-range of the domain for the given permutation.
Definition at line 410 of file HyperRectDomain.h.
References DGtal::HyperRectDomain< TSpace >::myLowerBound.
    { return ConstSubRange(*this, permutation, myLowerBound); }
template<typename TSpace> ConstSubRange DGtal::HyperRectDomain< TSpace >::subRange (const std::vector< Dimension > & permutation, const Point & startingPoint) const [inline]
get a subRange from an initial point.
Parameters:
permutation a vector containing the dimensions used for the subrange. Dimensions are iterated in the given order.
startingPoint the initial point.
Returns:
a sub-range of the domain for the given permutation.
Precondition:
startingPoint must belong to the range.
Definition at line 421 of file HyperRectDomain.h.
    { return ConstSubRange(*this, permutation, startingPoint); }
template<typename TSpace> ConstSubRange DGtal::HyperRectDomain< TSpace >::subRange (Dimension adim, const Point & startingPoint) const [inline]
get a subRange of one dimension.
Parameters:
adim the dimension of the subrange.
startingPoint the initial point.
Returns:
a sub-range of the domain for the given dimension.
Precondition:
startingPoint must belong to the range.
Definition at line 432 of file HyperRectDomain.h.
    { return ConstSubRange(*this, adim, startingPoint); }
template<typename TSpace> ConstSubRange DGtal::HyperRectDomain< TSpace >::subRange (Dimension adim1, Dimension adim2, Dimension adim3, const Point & startingPoint) const [inline]
get a subRange of three dimensions.
Parameters:
adim1 the first dimension of the subrange.
adim2 the second dimension of the subrange.
adim3 the third dimension of the subrange.
startingPoint the initial point.
Returns:
a sub-range of the domain for the given three dimensions.
Precondition:
startingPoint must belong to the range.
Definition at line 457 of file HyperRectDomain.h.
    { return ConstSubRange(*this, adim1, adim2, adim3, startingPoint); }
template<typename TSpace> ConstSubRange DGtal::HyperRectDomain< TSpace >::subRange (Dimension adim1, Dimension adim2, const Point & startingPoint) const [inline]
get a subRange of two dimensions.
Parameters:
adim1 the first dimension of the subrange.
adim2 the second dimension of the subrange.
startingPoint the initial point.
Returns:
a sub-range of the domain for the given two dimensions.
Precondition:
startingPoint must belong to the range.
Definition at line 444 of file HyperRectDomain.h.
    { return ConstSubRange(*this, adim1, adim2, startingPoint); }
template<typename TSpace > const DGtal::HyperRectDomain< TSpace >::Point & DGtal::HyperRectDomain< TSpace >::upperBound () const [inline]
Returns the highest point of the space diagonal.
Examples:
khalimskySpaceScanner.cpp.
Definition at line 143 of file HyperRectDomain.ih.
Referenced by Exporter< Set, Image >::exportSignature().
{
  return myUpperBound;
}
Field Documentation
template<typename TSpace> const Space::Dimension DGtal::HyperRectDomain< TSpace >::dimension = Space::dimension [static]
Definition at line 108 of file HyperRectDomain.h.
template<typename TSpace> ConstIterator DGtal::HyperRectDomain< TSpace >::myIteratorBegin [private]
Begin iterator.
Definition at line 641 of file HyperRectDomain.h.
Referenced by DGtal::HyperRectDomain< TSpace >::begin().
template<typename TSpace> ConstIterator DGtal::HyperRectDomain< TSpace >::myIteratorEnd [private]
End iterator.
Definition at line 643 of file HyperRectDomain.h.
Referenced by DGtal::HyperRectDomain< TSpace >::end(), and DGtal::HyperRectDomain< TSpace >::HyperRectDomain().
template<typename TSpace> Point DGtal::HyperRectDomain< TSpace >::myLowerBound [private]
The lowest point of the space diagonal.
Definition at line 633 of file HyperRectDomain.h.
Referenced by DGtal::HyperRectDomain< TSpace >::begin(), DGtal::HyperRectDomain< TSpace >::size(), and DGtal::HyperRectDomain< TSpace >::subRange().
template<typename TSpace> Predicate DGtal::HyperRectDomain< TSpace >::myPredicate [private]
"IsInside" predicate.
Definition at line 638 of file HyperRectDomain.h.
template<typename TSpace> Point DGtal::HyperRectDomain< TSpace >::myUpperBound [private]
The highest point of the space diagonal.
Definition at line 635 of file HyperRectDomain.h.
Referenced by DGtal::HyperRectDomain< TSpace >::begin(), and DGtal::HyperRectDomain< TSpace >::size().
The documentation for this class was generated from the following files:
HyperRectDomain.h
HyperRectDomain.ih