DGtal: DGtal::GrayscaleColorMap< PValue > Class Template Reference
DGtal::GrayscaleColorMap< PValue > Class Template Reference
Aim: This class template may be used to (linearly) convert scalar values in a given range into gray levels.
#include <GrayScaleColorMap.h>
Public Types
typedef PValue Value
Public Member Functions
GrayscaleColorMap (const PValue &min, const PValue &max)
Color operator() (const PValue &value) const
~GrayscaleColorMap ()
GrayscaleColorMap (const GrayscaleColorMap &other)
GrayscaleColorMap & operator= (const GrayscaleColorMap &other)
void selfDisplay (std::ostream &out) const
bool isValid () const
const PValue & min () const
const PValue & max () const
Static Public Member Functions
static Color getColor (const PValue &min, const PValue &max, const PValue &value)
Protected Member Functions
GrayscaleColorMap ()
Protected Attributes
PValue myMin
PValue myMax
Detailed Description
template<typename PValue>
class DGtal::GrayscaleColorMap< PValue >
Aim: This class template may be used to (linearly) convert scalar values in a given range into gray levels.
Description of template class 'GrayscaleColorMap'
The GrayscaleColorMap can be used either as a functor object (the value range is given at the object's construction) which converts a value into a Color structure, or it can be used through a static method taking both the range and the value as parameters.
The code below shows a possible use of this class.
 #include "DGtal/io/Color.h"
 #include "GrayscaleColorMap.h"
 // ...
 {
   GrayscaleColorMap<float> grayShade(0.0f,1.0f);
   Color white = grayShade(1.0f);
   Color gray1 = grayShade(0.5f);
   // Or, equivalently:
   Color gray2 = GrayscaleColorMap<float>::getColor(0.0f,1.0f,0.5f);
 }
Template Parameters:
PValue The type of the range values.
Definition at line 81 of file GrayScaleColorMap.h.
Member Typedef Documentation
template<typename PValue> typedef PValue DGtal::GrayscaleColorMap< PValue >::Value
Definition at line 86 of file GrayScaleColorMap.h.
Constructor & Destructor Documentation
template<typename Value > DGtal::GrayscaleColorMap< Value >::GrayscaleColorMap (const PValue & min, const PValue & max) [inline]
Constructor.
Parameters:
min The lower bound of the value range.
max The upper bound of the value range.
Definition at line 43 of file GrayScaleColorMap.ih.
  : myMin( aMin ), myMax( aMax )
{ }
template<typename Value > DGtal::GrayscaleColorMap< Value >::~GrayscaleColorMap () [inline]
Destructor.
Definition at line 58 of file GrayScaleColorMap.ih.
{
}
template<typename Value > DGtal::GrayscaleColorMap< Value >::GrayscaleColorMap (const GrayscaleColorMap< PValue > & other) [inline]
Copy constructor.
Parameters:
other the object to clone.
Definition at line 51 of file GrayScaleColorMap.ih.
  : myMin( other.myMin ), myMax( other.myMax )
{
}
template<typename PValue> DGtal::GrayscaleColorMap< PValue >::GrayscaleColorMap () [protected]
Constructor. Forbidden by default (protected to avoid g++ warnings).
Member Function Documentation
template<typename Value > Color DGtal::GrayscaleColorMap< Value >::getColor (const PValue & min, const PValue & max, const PValue & value) [inline, static]
Computes the gray level associated with a value in a given range.
Parameters:
min The lower bound of the value range.
max The upper bound of the value range.
value A value within the value range.
Returns:
A gray level (as a Color) which linearly depends on the position of [value] within the range [min]..[max].
Definition at line 133 of file GrayScaleColorMap.ih.
References DGtal::min().
Referenced by DGtal::GrayscaleColorMap< PValue >::operator()().
{
  double range = static_cast<double>( max - min );
  double scale = static_cast<double>( value - min );
  unsigned char gray = static_cast<unsigned char>( 255.0 * ( scale / range  ) );
  return Color( gray );
}
template<typename Value > bool DGtal::GrayscaleColorMap< Value >::isValid () const [inline]
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
Definition at line 124 of file GrayScaleColorMap.ih.
{
    return true;
}
template<typename Value > const Value & DGtal::GrayscaleColorMap< Value >::max () const [inline]
Returns the upper bound of the value range.
Returns:
The upper bound of the value range.
Definition at line 89 of file GrayScaleColorMap.ih.
{
  return myMax;
}
template<typename Value > const Value & DGtal::GrayscaleColorMap< Value >::min () const [inline]
Returns the lower bound of the value range.
Returns:
The lower bound of the value range.
Definition at line 81 of file GrayScaleColorMap.ih.
{
  return myMin;
}
template<typename Value > Color DGtal::GrayscaleColorMap< Value >::operator() (const PValue & value) const [inline]
Computes the gray level associated with a value in a given range.
Parameters:
value A value within the value range.
Returns:
A gray level (as a Color) which linearly depends on the position of [value] within the current range.
Definition at line 97 of file GrayScaleColorMap.ih.
References DGtal::GrayscaleColorMap< PValue >::getColor().
{
  return GrayscaleColorMap<Value>::getColor( myMin, myMax, value );
}
template<typename PValue> GrayscaleColorMap& DGtal::GrayscaleColorMap< PValue >::operator= (const GrayscaleColorMap< PValue > & other)
Assignment.
Parameters:
other the object to copy.
Returns:
a reference on 'this'.
template<typename Value > void DGtal::GrayscaleColorMap< Value >::selfDisplay (std::ostream & out) const [inline]
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
Definition at line 109 of file GrayScaleColorMap.ih.
{
  out << "[GrayscaleColorMap "
      << " min=" << myMin
      << " max=" << myMax
      << " ]";
}
Field Documentation
template<typename PValue> PValue DGtal::GrayscaleColorMap< PValue >::myMax [protected]
The lower bound of the value range.
Definition at line 183 of file GrayScaleColorMap.h.
template<typename PValue> PValue DGtal::GrayscaleColorMap< PValue >::myMin [protected]
The lower bound of the value range.
Definition at line 182 of file GrayScaleColorMap.h.
The documentation for this class was generated from the following files:
GrayScaleColorMap.h
GrayScaleColorMap.ih