DGtal: DGtal::GridCurve< KSpace >::PointsRange Class Reference
DGtal::GridCurve< KSpace >::PointsRange Class Reference
#include <GridCurve.h>
Data Structures
class ConstIterator
Public Types
typedef GridCurve::Storage Storage
typedef
GridCurve::Storage::const_iterator ConstIteratorOnPointels
typedef GridCurve::Point Point
typedef std::reverse_iterator
< ConstIterator > ConstReverseIterator
Public Member Functions
PointsRange ()
PointsRange (const GridCurve *aGridCurve)
PointsRange (const PointsRange &aOther)
PointsRange & operator= (const PointsRange &other)
~PointsRange ()
Storage::size_type size () const
ConstIterator begin () const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rend () const
Private Attributes
const GridCurve * myC
Detailed Description
template<typename KSpace>
class DGtal::GridCurve< KSpace >::PointsRange
This class is a model of CRange and provides a ConstIterator to scan the integer coordinates of the pointels of a grid curve
Definition at line 413 of file GridCurve.h.
Member Typedef Documentation
template<typename KSpace> typedef GridCurve::Storage::const_iterator DGtal::GridCurve< KSpace >::PointsRange::ConstIteratorOnPointels
Definition at line 420 of file GridCurve.h.
template<typename KSpace> typedef std::reverse_iterator<ConstIterator> DGtal::GridCurve< KSpace >::PointsRange::ConstReverseIterator
Definition at line 580 of file GridCurve.h.
template<typename KSpace> typedef GridCurve::Point DGtal::GridCurve< KSpace >::PointsRange::Point
Definition at line 422 of file GridCurve.h.
template<typename KSpace> typedef GridCurve::Storage DGtal::GridCurve< KSpace >::PointsRange::Storage
Definition at line 419 of file GridCurve.h.
Constructor & Destructor Documentation
template<typename KSpace> DGtal::GridCurve< KSpace >::PointsRange::PointsRange () [inline]
Default Constructor.
Definition at line 588 of file GridCurve.h.
{}
template<typename KSpace> DGtal::GridCurve< KSpace >::PointsRange::PointsRange (const GridCurve * aGridCurve) [inline]
Constructor.
Definition at line 594 of file GridCurve.h.
: myC(aGridCurve){}
template<typename KSpace> DGtal::GridCurve< KSpace >::PointsRange::PointsRange (const PointsRange & aOther) [inline]
Copy constructor.
Parameters:
other the iterator to clone.
Definition at line 601 of file GridCurve.h.
        : myC( aOther.myC ){}
template<typename KSpace> DGtal::GridCurve< KSpace >::PointsRange::~PointsRange () [inline]
Destructor. Does nothing.
Definition at line 623 of file GridCurve.h.
{}
Member Function Documentation
template<typename KSpace> ConstIterator DGtal::GridCurve< KSpace >::PointsRange::begin () const [inline]
Iterator service.
Returns:
begin iterator
Definition at line 644 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::my0SCells, and DGtal::GridCurve< KSpace >::PointsRange::myC.
Referenced by DGtal::GridCurve< KSpace >::PointsRange::rend().
{
        return ConstIterator( myC, myC->my0SCells.begin() );
      }
template<typename KSpace> ConstIterator DGtal::GridCurve< KSpace >::PointsRange::end () const [inline]
Iterator service.
Returns:
end iterator
Definition at line 652 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::my0SCells, and DGtal::GridCurve< KSpace >::PointsRange::myC.
Referenced by DGtal::GridCurve< KSpace >::PointsRange::rbegin().
{
        return ConstIterator( myC, myC->my0SCells.end() );
      }
template<typename KSpace> PointsRange& DGtal::GridCurve< KSpace >::PointsRange::operator= (const PointsRange & other) [inline]
Assignment.
Parameters:
other the iterator to copy.
Returns:
a reference on 'this'.
Definition at line 610 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::PointsRange::myC.
      {
        if ( this != &other )
          {
            myC = other.myC;
          }
        return *this;
      }
template<typename KSpace> ConstReverseIterator DGtal::GridCurve< KSpace >::PointsRange::rbegin () const [inline]
Iterator service.
Returns:
rbegin iterator
Definition at line 660 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::PointsRange::end().
{
        return ConstReverseIterator(this->end());
      }
template<typename KSpace> ConstReverseIterator DGtal::GridCurve< KSpace >::PointsRange::rend () const [inline]
Iterator service.
Returns:
rend iterator
Definition at line 668 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::PointsRange::begin().
{
        return ConstReverseIterator(this->begin());
      }
template<typename KSpace> Storage::size_type DGtal::GridCurve< KSpace >::PointsRange::size () const [inline]
Returns:
the size of the range
Definition at line 629 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::my0SCells, and DGtal::GridCurve< KSpace >::PointsRange::myC.
{
        return myC->my0SCells.size();
      }
Field Documentation
template<typename KSpace> const GridCurve* DGtal::GridCurve< KSpace >::PointsRange::myC [private]
Definition at line 635 of file GridCurve.h.
Referenced by DGtal::GridCurve< KSpace >::PointsRange::begin(), DGtal::GridCurve< KSpace >::PointsRange::end(), DGtal::GridCurve< KSpace >::PointsRange::operator=(), and DGtal::GridCurve< KSpace >::PointsRange::size().
The documentation for this class was generated from the following file:
GridCurve.h