DGtal: DGtal::DomainAdjacency< TDomain, TAdjacency > Class Template Reference
DGtal::DomainAdjacency< TDomain, TAdjacency > Class Template Reference
Aim: Given a domain and an adjacency, limits the given adjacency to the specified domain for all adjacency and neighborhood computations.
#include <DomainAdjacency.h>
Public Types
typedef TDomain::Space Space
typedef TAdjacency Adjacency
typedef TDomain::Point Point
typedef TDomain Domain
typedef DomainPredicate< Domain > Predicate
Public Member Functions
DomainAdjacency (const Domain &aDomain, const Adjacency &adjacency)
DomainAdjacency (const DomainAdjacency &other)
~DomainAdjacency ()
const Domain & domain () const
const Predicate & predicate () const
bool isAdjacentTo (const Point &p1, const Point &p2) const
bool isProperlyAdjacentTo (const Point &p1, const Point &p2) const
template<typename OutputIterator , typename PointPredicate >
void writeNeighborhood (const Point &p, OutputIterator &out_it, const PointPredicate &pred) const
template<typename OutputIterator >
void writeNeighborhood (const Point &p, OutputIterator &out_it) const
template<typename OutputIterator , typename PointPredicate >
void writeProperNeighborhood (const Point &p, OutputIterator &out_it, const PointPredicate &pred) const
template<typename OutputIterator >
void writeProperNeighborhood (const Point &p, OutputIterator &out_it) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Protected Member Functions
DomainAdjacency ()
Private Member Functions
BOOST_CONCEPT_ASSERT ((CDomain< TDomain >))
BOOST_CONCEPT_ASSERT ((CAdjacency< TAdjacency >))
DomainAdjacency & operator= (const DomainAdjacency &other)
Private Attributes
Predicate myPred
const Adjacency & myAdjacency
Detailed Description
template<typename TDomain, typename TAdjacency>
class DGtal::DomainAdjacency< TDomain, TAdjacency >
Aim: Given a domain and an adjacency, limits the given adjacency to the specified domain for all adjacency and neighborhood computations.
Description of template class 'DomainAdjacency'
This class is useful for limiting adjacencies that are defined for unlimited spaces.
Model of CAdjacency.
Template Parameters:
TDomain the type of the domain.
TAdjacency the type of the adjacency.
Definition at line 70 of file DomainAdjacency.h.
Member Typedef Documentation
template<typename TDomain, typename TAdjacency> typedef TAdjacency DGtal::DomainAdjacency< TDomain, TAdjacency >::Adjacency
Definition at line 78 of file DomainAdjacency.h.
template<typename TDomain, typename TAdjacency> typedef TDomain DGtal::DomainAdjacency< TDomain, TAdjacency >::Domain
Definition at line 82 of file DomainAdjacency.h.
template<typename TDomain, typename TAdjacency> typedef TDomain::Point DGtal::DomainAdjacency< TDomain, TAdjacency >::Point
Definition at line 79 of file DomainAdjacency.h.
template<typename TDomain, typename TAdjacency> typedef DomainPredicate< Domain > DGtal::DomainAdjacency< TDomain, TAdjacency >::Predicate
Definition at line 83 of file DomainAdjacency.h.
template<typename TDomain, typename TAdjacency> typedef TDomain::Space DGtal::DomainAdjacency< TDomain, TAdjacency >::Space
Definition at line 77 of file DomainAdjacency.h.
Constructor & Destructor Documentation
template<typename TDomain , typename TAdjacency > DGtal::DomainAdjacency< TDomain, TAdjacency >::DomainAdjacency (const Domain & aDomain, const Adjacency & adjacency) [inline]
Constructor.
Parameters:
aDomain the domain which restricts the given adjacency.
adjacency any adjacency whose range contains the given domain aDomain.
Definition at line 50 of file DomainAdjacency.ih.
  : myPred( aDomain ), myAdjacency( adjacency )
{
}
template<typename TDomain , typename TAdjacency > DGtal::DomainAdjacency< TDomain, TAdjacency >::DomainAdjacency (const DomainAdjacency< TDomain, TAdjacency > & other) [inline]
Copy constructor.
Parameters:
other the object to clone.
Definition at line 59 of file DomainAdjacency.ih.
  : myPred( other.myPred ), myAdjacency( other.myAdjacency )
{
}
template<typename TDomain , typename TAdjacency > DGtal::DomainAdjacency< TDomain, TAdjacency >::~DomainAdjacency () [inline]
Destructor.
Definition at line 44 of file DomainAdjacency.ih.
{}
template<typename TDomain, typename TAdjacency> DGtal::DomainAdjacency< TDomain, TAdjacency >::DomainAdjacency () [protected]
Constructor. Forbidden by default (protected to avoid g++ warnings).
Member Function Documentation
template<typename TDomain, typename TAdjacency> DGtal::DomainAdjacency< TDomain, TAdjacency >::BOOST_CONCEPT_ASSERT ((CDomain< TDomain >)) [private]
template<typename TDomain, typename TAdjacency> DGtal::DomainAdjacency< TDomain, TAdjacency >::BOOST_CONCEPT_ASSERT ((CAdjacency< TAdjacency >)) [private]
template<typename TDomain , typename TAdjacency > const TDomain & DGtal::DomainAdjacency< TDomain, TAdjacency >::domain () const [inline]
Returns:
a const reference to the associated domain.
Definition at line 68 of file DomainAdjacency.ih.
References DGtal::DomainAdjacency< TDomain, TAdjacency >::domain().
Referenced by DGtal::DomainAdjacency< TDomain, TAdjacency >::domain().
{
  return myPred.domain();
}
template<typename TDomain , typename TAdjacency > bool DGtal::DomainAdjacency< TDomain, TAdjacency >::isAdjacentTo (const Point & p1, const Point & p2) const [inline]
Parameters:
p1 any point in this space.
p2 any point in this space.
Returns:
'true' iff p1 is adjacent to p2 according to this adjacency relation.
Definition at line 86 of file DomainAdjacency.ih.
{
  ASSERT( myPred( p1 ) );
  ASSERT( myPred( p2 ) );
  return isAdjacentTo( p1, p2 );
}
template<typename TDomain , typename TAdjacency > bool DGtal::DomainAdjacency< TDomain, TAdjacency >::isProperlyAdjacentTo (const Point & p1, const Point & p2) const [inline]
Parameters:
p1 any point in this space.
p2 any point in this space.
Returns:
'true' iff p1 is adjacent to p2 according to this adjacency relation and p1 != p2.
Definition at line 97 of file DomainAdjacency.ih.
{
  ASSERT( myPred( p1 ) );
  ASSERT( myPred( p2 ) );
  return isProperlyAdjacentTo( p1, p2 );
}
template<typename TDomain , typename TAdjacency > bool DGtal::DomainAdjacency< TDomain, TAdjacency >::isValid () const [inline]
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
Definition at line 171 of file DomainAdjacency.ih.
{
    return true;
}
template<typename TDomain, typename TAdjacency> DomainAdjacency& DGtal::DomainAdjacency< TDomain, TAdjacency >::operator= (const DomainAdjacency< TDomain, TAdjacency > & other) [private]
Assignment.
Parameters:
other the object to copy.
Returns:
a reference on 'this'. Forbidden by default.
template<typename TDomain , typename TAdjacency > const DGtal::DomainAdjacency< TDomain, TAdjacency >::Predicate & DGtal::DomainAdjacency< TDomain, TAdjacency >::predicate () const [inline]
Returns:
a const reference on the predicate which can check if a given point belongs to the domain.
Useful if you want to restrict your neighborhood.
Definition at line 77 of file DomainAdjacency.ih.
{
  return myPred;
}
template<typename TDomain , typename TAdjacency > void DGtal::DomainAdjacency< TDomain, TAdjacency >::selfDisplay (std::ostream & out) const [inline]
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
Definition at line 162 of file DomainAdjacency.ih.
{
  out << "[DomainAdjacency]";
}
template<typename TDomain , typename TAdjacency > template<typename OutputIterator > void DGtal::DomainAdjacency< TDomain, TAdjacency >::writeNeighborhood (const Point & p, OutputIterator & out_it) const [inline]
Outputs the whole neighborhood of point [p] (restricted to this domain) as a sequence of *out_it++ = ...
Template Parameters:
OutputIterator any output iterator (like std::back_insert_iterator< std::vector<int> >).
Parameters:
p any point of this space.
out_it any output iterator.
Definition at line 125 of file DomainAdjacency.ih.
References DGtal::DomainAdjacency< TDomain, TAdjacency >::writeNeighborhood().
{
  myAdjacency.writeNeighborhood( p, out_it, myPred );
}
template<typename TDomain , typename TAdjacency > template<typename OutputIterator , typename PointPredicate > void DGtal::DomainAdjacency< TDomain, TAdjacency >::writeNeighborhood (const Point & p, OutputIterator & out_it, const PointPredicate & pred) const [inline]
Outputs the whole neighborhood of point [p] satisfying the given predicate as a sequence of *out_it++ = ...
Template Parameters:
OutputIterator any output iterator (like std::back_insert_iterator< std::vector<int> >).
PointPredicate any predicate object.
Parameters:
p any point of this space.
out_it any output iterator.
pred the predicate.
NB: It is up to the user to add a predicate to guarantee that the neighborhood is included in the domain. To do so, you may just mix your predicate with the object predicate() with a BinaryPointPredicate AND.
Definition at line 109 of file DomainAdjacency.ih.
References DGtal::DomainAdjacency< TDomain, TAdjacency >::writeNeighborhood().
Referenced by DGtal::DomainAdjacency< TDomain, TAdjacency >::writeNeighborhood().
{
  // typedef BinaryPointPredicate< PointPredicate, DomainPredicateType >
  //   Predicate;
  // Predicate combinedPred( pred, myPred, andBF2 );
  // myAdjacency.writeNeighborhood( p, out_it, combinedPred );
  myAdjacency.writeNeighborhood( p, out_it, pred );
}
template<typename TDomain , typename TAdjacency > template<typename OutputIterator > void DGtal::DomainAdjacency< TDomain, TAdjacency >::writeProperNeighborhood (const Point & p, OutputIterator & out_it) const [inline]
Outputs the whole neighborhood of point [p] (except p itself, restricted to this domain) as a sequence of *out_it++ = ...
Template Parameters:
OutputIterator any output iterator (like std::back_insert_iterator< std::vector<int> >).
Parameters:
p any point of this space.
out_it any output iterator.
Definition at line 152 of file DomainAdjacency.ih.
References DGtal::DomainAdjacency< TDomain, TAdjacency >::writeProperNeighborhood().
{
  myAdjacency.writeProperNeighborhood( p, out_it, myPred );
}
template<typename TDomain , typename TAdjacency > template<typename OutputIterator , typename PointPredicate > void DGtal::DomainAdjacency< TDomain, TAdjacency >::writeProperNeighborhood (const Point & p, OutputIterator & out_it, const PointPredicate & pred) const [inline]
Outputs the whole neighborhood of point [p] (except p itself) satisfying the given predicate as a sequence of *out_it++ = ...
Template Parameters:
OutputIterator any output iterator (like std::back_insert_iterator< std::vector<int> >).
PointPredicate any predicate object
Parameters:
p any point of this space.
out_it any output iterator.
pred the predicate.
NB: It is up to the user to add a predicate to guarantee that the neighborhood is included in the domain. To do so, you may just mix your predicate with the object predicate() with a BinaryPointPredicate AND.
Definition at line 136 of file DomainAdjacency.ih.
References DGtal::DomainAdjacency< TDomain, TAdjacency >::writeProperNeighborhood().
Referenced by DGtal::DomainAdjacency< TDomain, TAdjacency >::writeProperNeighborhood().
{
  // typedef BinaryPointPredicate< PointPredicate, DomainPredicateType >
  //   Predicate;
  // Predicate combinedPred( pred, myPred, andBF2 );
  // myAdjacency.writeProperNeighborhood( p, out_it, combinedPred );
  myAdjacency.writeProperNeighborhood( p, out_it, pred );
}
Field Documentation
template<typename TDomain, typename TAdjacency> const Adjacency& DGtal::DomainAdjacency< TDomain, TAdjacency >::myAdjacency [private]
The adjacency relation.
Definition at line 246 of file DomainAdjacency.h.
template<typename TDomain, typename TAdjacency> Predicate DGtal::DomainAdjacency< TDomain, TAdjacency >::myPred [private]
The predicate for testing if a point belongs to the domain.
Definition at line 241 of file DomainAdjacency.h.
The documentation for this class was generated from the following files:
DomainAdjacency.h
DomainAdjacency.ih