DGtal: DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node Class Reference
DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node Class Reference
#include <ImageContainerByHashTree.h>
Public Member Functions
Node (Value aValue, HashKey key)
Node * getNext ()
void setNext (Node *next)
HashKey getKey ()
Value & getObject ()
~Node ()
Protected Attributes
HashKey myKey
Node * myNext
Value myData
Detailed Description
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t>
class DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node
An internal class that corresponds to a node of a linked list (as the hashTable points to linked lists to handle collisions). Each element in the container is placed in a Node.
Definition at line 539 of file ImageContainerByHashTree.h.
Constructor & Destructor Documentation
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::Node (Value aValue, HashKey key) [inline]
Construtctor: create pair (aValue, key)
Parameters:
aValue First value
key key in the hashtree
Definition at line 549 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myData, and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myKey.
        {
          myData = aValue;
          myKey = key;
        }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::~Node () [inline]
Definition at line 591 of file ImageContainerByHashTree.h.
{ }
Member Function Documentation
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> HashKey DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getKey () [inline]
Returns:
the key associated to a Node.
Definition at line 578 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myKey.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::getKey(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNode(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::removeNode(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::upwardGet().
        {
          return myKey;
        }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Node* DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getNext () [inline]
Returns:
the next pair (aValue, key) in the list.
Definition at line 558 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myNext.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNbNodes(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::getNode(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInternalState(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::removeNode(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::upwardGet().
        {
          return myNext;
        }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Value& DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getObject () [inline]
Returns:
the object (aValue) associated to a Node.
Definition at line 587 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myData.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::addNode(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::blendChildren(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::get(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Iterator::operator*(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printInternalState(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::printTree(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::recursiveDraw(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::reverseGet(), DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::setValue(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::upwardGet().
        {
          return myData;
        }
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> void DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::setNext (Node * next) [inline]
Insert the pair (value,key) next in the node list
Parameters:
next a pointer to a pair (value,key) (Node).
Definition at line 569 of file ImageContainerByHashTree.h.
References DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myNext.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::addNode(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::removeNode().
        {
          myNext = next;
        }
Field Documentation
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Value DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myData [protected]
Definition at line 595 of file ImageContainerByHashTree.h.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getObject(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::Node().
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> HashKey DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myKey [protected]
Definition at line 593 of file ImageContainerByHashTree.h.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getKey(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::Node().
template<typename TDomain, typename TValue, typename THashKey = typename DGtal::uint64_t> Node* DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::myNext [protected]
Definition at line 594 of file ImageContainerByHashTree.h.
Referenced by DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::getNext(), and DGtal::experimental::ImageContainerByHashTree< TDomain, TValue, THashKey >::Node::setNext().
The documentation for this class was generated from the following file:
ImageContainerByHashTree.h