DGtal: DGtal::GridCurve< KSpace >::ArrowsRange Class Reference
DGtal::GridCurve< KSpace >::ArrowsRange Class Reference
#include <GridCurve.h>
Data Structures
class ConstIterator
Public Types
typedef GridCurve::SCell SCell
typedef GridCurve::Point Point
typedef GridCurve::Point Vector
typedef std::pair< Point, Vector > Arrow
typedef GridCurve::Storage Storage
typedef
GridCurve::Storage::const_iterator ConstIteratorOnSCells
typedef std::reverse_iterator
< ConstIterator > ConstReverseIterator
Public Member Functions
ArrowsRange ()
ArrowsRange (const GridCurve *aGridCurve)
ArrowsRange (const ArrowsRange &aOther)
ArrowsRange & operator= (const ArrowsRange &other)
~ArrowsRange ()
Storage::size_type size () const
ConstIterator begin () const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rend () const
Private Attributes
const GridCurve * myC
Detailed Description
template<typename KSpace>
class DGtal::GridCurve< KSpace >::ArrowsRange
This class is a model of CRange and provides a ConstIterator to scan the 1-cells and return the integer coordinates of the associated point and displacement vector
Definition at line 975 of file GridCurve.h.
Member Typedef Documentation
template<typename KSpace> typedef std::pair<Point,Vector> DGtal::GridCurve< KSpace >::ArrowsRange::Arrow
Definition at line 984 of file GridCurve.h.
template<typename KSpace> typedef GridCurve::Storage::const_iterator DGtal::GridCurve< KSpace >::ArrowsRange::ConstIteratorOnSCells
Definition at line 987 of file GridCurve.h.
template<typename KSpace> typedef std::reverse_iterator<ConstIterator> DGtal::GridCurve< KSpace >::ArrowsRange::ConstReverseIterator
Definition at line 1143 of file GridCurve.h.
template<typename KSpace> typedef GridCurve::Point DGtal::GridCurve< KSpace >::ArrowsRange::Point
Definition at line 982 of file GridCurve.h.
template<typename KSpace> typedef GridCurve::SCell DGtal::GridCurve< KSpace >::ArrowsRange::SCell
Definition at line 981 of file GridCurve.h.
template<typename KSpace> typedef GridCurve::Storage DGtal::GridCurve< KSpace >::ArrowsRange::Storage
Definition at line 986 of file GridCurve.h.
template<typename KSpace> typedef GridCurve::Point DGtal::GridCurve< KSpace >::ArrowsRange::Vector
Definition at line 983 of file GridCurve.h.
Constructor & Destructor Documentation
template<typename KSpace> DGtal::GridCurve< KSpace >::ArrowsRange::ArrowsRange () [inline]
Default Constructor.
Definition at line 1151 of file GridCurve.h.
{}
template<typename KSpace> DGtal::GridCurve< KSpace >::ArrowsRange::ArrowsRange (const GridCurve * aGridCurve) [inline]
Constructor.
Definition at line 1157 of file GridCurve.h.
: myC(aGridCurve){}
template<typename KSpace> DGtal::GridCurve< KSpace >::ArrowsRange::ArrowsRange (const ArrowsRange & aOther) [inline]
Copy constructor.
Parameters:
other the iterator to clone.
Definition at line 1164 of file GridCurve.h.
        : myC( aOther.myC ){}
template<typename KSpace> DGtal::GridCurve< KSpace >::ArrowsRange::~ArrowsRange () [inline]
Destructor. Does nothing.
Definition at line 1186 of file GridCurve.h.
{}
Member Function Documentation
template<typename KSpace> ConstIterator DGtal::GridCurve< KSpace >::ArrowsRange::begin () const [inline]
Iterator service.
Returns:
begin iterator
Definition at line 1207 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::my1SCells, and DGtal::GridCurve< KSpace >::ArrowsRange::myC.
Referenced by DGtal::GridCurve< KSpace >::ArrowsRange::rend().
{
        return ConstIterator( myC, myC->my1SCells.begin() );
      }
template<typename KSpace> ConstIterator DGtal::GridCurve< KSpace >::ArrowsRange::end () const [inline]
Iterator service.
Returns:
end iterator
Definition at line 1215 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::my1SCells, and DGtal::GridCurve< KSpace >::ArrowsRange::myC.
Referenced by DGtal::GridCurve< KSpace >::ArrowsRange::rbegin().
{
        return ConstIterator( myC, myC->my1SCells.end() );
      }
template<typename KSpace> ArrowsRange& DGtal::GridCurve< KSpace >::ArrowsRange::operator= (const ArrowsRange & other) [inline]
Assignment.
Parameters:
other the iterator to copy.
Returns:
a reference on 'this'.
Definition at line 1173 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::ArrowsRange::myC.
      {
        if ( this != &other )
          {
            myC = other.myC;
          }
        return *this;
      }
template<typename KSpace> ConstReverseIterator DGtal::GridCurve< KSpace >::ArrowsRange::rbegin () const [inline]
Iterator service.
Returns:
rbegin iterator
Definition at line 1223 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::ArrowsRange::end().
{
        return ConstReverseIterator(this->end());
      }
template<typename KSpace> ConstReverseIterator DGtal::GridCurve< KSpace >::ArrowsRange::rend () const [inline]
Iterator service.
Returns:
rend iterator
Definition at line 1231 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::ArrowsRange::begin().
{
        return ConstReverseIterator(this->begin());
      }
template<typename KSpace> Storage::size_type DGtal::GridCurve< KSpace >::ArrowsRange::size () const [inline]
Returns:
the size of the range
Definition at line 1192 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::my1SCells, and DGtal::GridCurve< KSpace >::ArrowsRange::myC.
{
        return myC->my1SCells.size();
      }
Field Documentation
template<typename KSpace> const GridCurve* DGtal::GridCurve< KSpace >::ArrowsRange::myC [private]
Definition at line 1198 of file GridCurve.h.
Referenced by DGtal::GridCurve< KSpace >::ArrowsRange::begin(), DGtal::GridCurve< KSpace >::ArrowsRange::end(), DGtal::GridCurve< KSpace >::ArrowsRange::operator=(), and DGtal::GridCurve< KSpace >::ArrowsRange::size().
The documentation for this class was generated from the following file:
GridCurve.h