DGtal: contourGenerator.cpp File Reference
contourGenerator.cpp File Reference
#include <cmath>
#include <iostream>
#include <iomanip>
#include <vector>
#include <string>
#include <boost/program_options/options_description.hpp>
#include <boost/program_options/parsers.hpp>
#include <boost/program_options/variables_map.hpp>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/shapes/ShapeFactory.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/io/colormaps/GrayScaleColorMap.h"
#include "DGtal/images/imagesSetsUtils/ImageFromSet.h"
#include "DGtal/images/imagesSetsUtils/SetFromImage.h"
#include "DGtal/images/ImageContainerBySTLVector.h"
#include "DGtal/io/writers/PNMWriter.h"
#include "DGtal/io/writers/RawWriter.h"
#include "DGtal/io/writers/VolWriter.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/geometry/nd/GaussDigitizer.h"
#include "DGtal/geometry/2d/GridCurve.h"
#include "DGtal/geometry/2d/estimators/TrueLocalEstimatorOnPoints.h"
#include "DGtal/geometry/2d/estimators/TrueGlobalEstimatorOnPoints.h"
#include "DGtal/geometry/2d/estimators/ParametricShapeCurvatureFunctor.h"
#include "DGtal/geometry/2d/estimators/ParametricShapeTangentFunctor.h"
#include "DGtal/geometry/2d/estimators/ParametricShapeArcLengthFunctor.h"
#include "DGtal/topology/helpers/Surfaces.h"
Functions
void createList ()
void displayList ()
unsigned int checkAndReturnIndex (const std::string &shapeName)
template<typename Estimator , typename ConstIterator >
std::vector< typename
Estimator::Quantity > estimateQuantity (Estimator &estimator, ConstIterator it, ConstIterator it_end)
template<typename Shape , typename Range , typename Point , typename Quantity >
void estimateGeometry (Shape &s, const double &h, const Range &r, vector< Point > &points, vector< Point > &tangents, vector< Quantity > &curvatures)
template<typename Space , typename Shape >
bool generateContour (Shape &aShape, double h, const std::string &outputFormat, const std::string &outputFileName)
void missingParam (std::string param)
int main (int argc, char **argv)
Variables
std::vector< std::string > shapes2D
std::vector< std::string > shapesDesc
std::vector< std::string > shapesParam1
std::vector< std::string > shapesParam2
std::vector< std::string > shapesParam3
std::vector< std::string > shapesParam4
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
Jacques-Olivier Lachaud (jacques-olivier.lachaud@univ-savoie.fr) Laboratory of Mathematics (CNRS, UMR 5807), University of Savoie, France
David Coeurjolly (david.coeurjolly@liris.cnrs.fr) LIRIS (CNRS, UMR 5205),
Date:
2011/07/04
DGtal shape generator
This file is part of the DGtal library.
Definition in file contourGenerator.cpp.
Function Documentation
unsigned int checkAndReturnIndex (const std::string & shapeName)
Check if a given shape is available. If not, we exist with an error. If it is, we return the corresponding index in the global vectors.
Parameters:
shapeName name of the shape to search.
Returns:
index of the shape in the shape vectors.
Definition at line 171 of file contourGenerator.cpp.
References DGtal::Trace::error(), DGtal::Trace::info(), shapes2D, and DGtal::trace.
void createList ()
Create the static list of shapes.
Definition at line 90 of file contourGenerator.cpp.
References shapes2D, shapesDesc, shapesParam1, shapesParam2, shapesParam3, and shapesParam4.
void displayList ()
Display the shape list with parameters.
Definition at line 148 of file contourGenerator.cpp.
References DGtal::Trace::emphase(), DGtal::Trace::info(), shapes2D, shapesDesc, shapesParam1, shapesParam2, shapesParam3, shapesParam4, and DGtal::trace.
template<typename Shape , typename Range , typename Point , typename Quantity > void estimateGeometry (Shape & s, const double & h, const Range & r, vector< Point > & points, vector< Point > & tangents, vector< Quantity > & curvatures)
Definition at line 204 of file contourGenerator.cpp.
References DGtal::FreemanChain< TInteger >::begin(), DGtal::FreemanChain< TInteger >::end(), estimateQuantity(), and DGtal::TrueLocalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::init().
template<typename Estimator , typename ConstIterator > std::vector<typename Estimator::Quantity> estimateQuantity (Estimator & estimator, ConstIterator it, ConstIterator it_end)
Definition at line 190 of file contourGenerator.cpp.
template<typename Space , typename Shape > bool generateContour (Shape & aShape, double h, const std::string & outputFormat, const std::string & outputFileName)
Definition at line 236 of file contourGenerator.cpp.
References DGtal::GaussDigitizer< TSpace, TEuclideanShape >::attach(), DGtal::FreemanChain< TInteger >::begin(), DGtal::FreemanChain< TInteger >::end(), DGtal::Surfaces< TKSpace >::findABel(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getDomain(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getLowerBound(), DGtal::GridCurve< KSpace >::getMidPointsRange(), DGtal::GridCurve< KSpace >::getPointsRange(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getUpperBound(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::init(), DGtal::GridCurve< KSpace >::initFromVector(), and DGtal::Surfaces< TKSpace >::track2DBoundaryPoints().
int main (int argc, char ** argv)
Definition at line 390 of file contourGenerator.cpp.
References checkAndReturnIndex(), createList(), displayList(), DGtal::Trace::error(), DGtal::Trace::info(), missingParam(), and DGtal::trace.
void missingParam (std::string param)
Missing parameter error message.
Parameters:
param
Definition at line 380 of file contourGenerator.cpp.
References DGtal::Trace::error(), DGtal::Trace::info(), and DGtal::trace.
Variable Documentation
std::vector<std::string> shapes2D
Global vectors to describe the available shapes and their parameters.
Definition at line 78 of file contourGenerator.cpp.
std::vector<std::string> shapesDesc
Definition at line 79 of file contourGenerator.cpp.
std::vector<std::string> shapesParam1
Definition at line 80 of file contourGenerator.cpp.
std::vector<std::string> shapesParam2
Definition at line 81 of file contourGenerator.cpp.
std::vector<std::string> shapesParam3
Definition at line 82 of file contourGenerator.cpp.
std::vector<std::string> shapesParam4
Definition at line 83 of file contourGenerator.cpp.