DGtal: displayContours.cpp File Reference
displayContours.cpp File Reference
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/shapes/ShapeFactory.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/topology/helpers/Surfaces.h"
#include "DGtal/images/imagesSetsUtils/ImageFromSet.h"
#include "DGtal/images/imagesSetsUtils/SetFromImage.h"
#include "DGtal/images/ImageContainerBySTLVector.h"
#include "DGtal/images/ImageSelector.h"
#include "DGtal/io/readers/PointListReader.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/io/Color.h"
#include "DGtal/kernel/RealPointVector.h"
#include "DGtal/geometry/2d/FreemanChain.h"
#include "DGtal/geometry/2d/ArithmeticalDSS.h"
#include "DGtal/geometry/2d/GreedyDecomposition.h"
#include "DGtal/geometry/2d/MaximalSegments.h"
#include "DGtal/geometry/2d/FP.h"
#include <boost/program_options/options_description.hpp>
#include <boost/program_options/parsers.hpp>
#include <boost/program_options/variables_map.hpp>
#include <vector>
#include <string>
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 82 of file displayContours.cpp.
References DGtal::abs(), DGtal::PointVector< dim, TComponent >::at(), DGtal::Color::Black, LibBoard::Board::CairoEPS, LibBoard::Board::CairoPDF, LibBoard::Board::CairoPNG, LibBoard::Board::drawImage(), LibBoard::Board::drawPolyline(), LibBoard::Board::fillCircle(), DGtal::PointListReader< TPoint >::getPointsFromFile(), DGtal::Color::Gray, DGtal::MagickReader< TImageContainer >::importImage(), DGtal::Trace::info(), DGtal::Color::None, DGtal::Color::Red, LibBoard::Board::saveEPS(), LibBoard::Board::saveFIG(), LibBoard::Board::saveSVG(), LibBoard::Board::setLineStyle(), LibBoard::Board::setLineWidth(), LibBoard::Board::setPenColor(), LibBoard::Board::setUnit(), LibBoard::Shape::SolidStyle, DGtal::DrawWithBoardModifier::styleName(), DGtal::trace, and LibBoard::Board::UCentimeter.