DGtal: initializer_list.cpp File Reference
initializer_list.cpp File Reference
#include <iostream>
Functions
template<typename T >
void f (std::initializer_list< T > init)
int main ()
Function Documentation
template<typename T > void f (std::initializer_list< T > init)
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Definition at line 20 of file initializer_list.cpp.
Referenced by compareShapeEstimators(), DGtal::getMiddleIterator(), iRand(), main(), DGtal::Board3DTo2D::precompute_projection_matrix(), DGtal::Color::setRGBf(), DGtal::Color::svgAlpha(), testCellularGridSpaceND(), testCompareEstimator(), testEval(), and testTangentFromDSS().
int main ()
Definition at line 28 of file initializer_list.cpp.
References f().