DGtal: lengthEstimators.cpp File Reference
lengthEstimators.cpp File Reference
#include <cmath>
#include <iostream>
#include <iomanip>
#include <vector>
#include <string>
#include <boost/program_options/options_description.hpp>
#include <boost/program_options/parsers.hpp>
#include <boost/program_options/variables_map.hpp>
#include "DGtal/base/Common.h"
#include "DGtal/base/Clock.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/topology/KhalimskySpaceND.h"
#include "DGtal/shapes/ShapeFactory.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/topology/helpers/Surfaces.h"
#include "DGtal/geometry/nd/GaussDigitizer.h"
#include "DGtal/geometry/2d/GridCurve.h"
#include "DGtal/geometry/2d/estimators/TrueLocalEstimatorOnPoints.h"
#include "DGtal/geometry/2d/estimators/TrueGlobalEstimatorOnPoints.h"
#include "DGtal/geometry/2d/estimators/ParametricShapeArcLengthFunctor.h"
#include "DGtal/geometry/2d/estimators/L1LengthEstimator.h"
#include "DGtal/geometry/2d/estimators/BLUELocalLengthEstimator.h"
#include "DGtal/geometry/2d/estimators/RosenProffittLocalLengthEstimator.h"
#include "DGtal/geometry/2d/estimators/MLPLengthEstimator.h"
#include "DGtal/geometry/2d/estimators/FPLengthEstimator.h"
#include "DGtal/geometry/2d/estimators/DSSLengthEstimator.h"
Functions
void createList ()
void displayList ()
unsigned int checkAndRetrunIndex (const std::string &shapeName)
void missingParam (std::string param)
template<typename Shape , typename Space >
bool lengthEstimators (const string &name, Shape &aShape, double h)
int main (int argc, char **argv)
Variables
std::vector< std::string > shapes2D
std::vector< std::string > shapesDesc
std::vector< std::string > shapesParam1
std::vector< std::string > shapesParam2
std::vector< std::string > shapesParam3
std::vector< std::string > shapesParam4
Function Documentation
unsigned int checkAndRetrunIndex (const std::string & shapeName)
Check if a given shape is available. If not, we exist with an error. If it is, we return the corresponding index in the global vectors.
Parameters:
shapeName name of the shape to search.
Returns:
index of the shape in the shape vectors.
Definition at line 173 of file lengthEstimators.cpp.
References DGtal::Trace::error(), DGtal::Trace::info(), shapes2D, and DGtal::trace.
Referenced by main().
void createList ()
Create the static list of shapes.
Definition at line 92 of file lengthEstimators.cpp.
References shapes2D, shapesDesc, shapesParam1, shapesParam2, shapesParam3, and shapesParam4.
void displayList ()
Display the shape list with parameters.
Definition at line 150 of file lengthEstimators.cpp.
References DGtal::Trace::emphase(), DGtal::Trace::info(), shapes2D, shapesDesc, shapesParam1, shapesParam2, shapesParam3, shapesParam4, and DGtal::trace.
template<typename Shape , typename Space > bool lengthEstimators (const string & name, Shape & aShape, double h)
Definition at line 205 of file lengthEstimators.cpp.
References DGtal::GaussDigitizer< TSpace, TEuclideanShape >::attach(), DGtal::FPLengthEstimator< TConstIterator >::eval(), DGtal::MLPLengthEstimator< TConstIterator >::eval(), DGtal::DSSLengthEstimator< TConstIterator >::eval(), DGtal::TwoStepLocalLengthEstimator< TConstIterator >::eval(), DGtal::L1LengthEstimator< TConstIterator >::eval(), DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::eval(), DGtal::Surfaces< TKSpace >::findABel(), DGtal::GridCurve< KSpace >::getArrowsRange(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getDomain(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getLowerBound(), DGtal::GridCurve< KSpace >::getPointsRange(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getUpperBound(), DGtal::FPLengthEstimator< TConstIterator >::init(), DGtal::MLPLengthEstimator< TConstIterator >::init(), DGtal::DSSLengthEstimator< TConstIterator >::init(), DGtal::TwoStepLocalLengthEstimator< TConstIterator >::init(), DGtal::L1LengthEstimator< TConstIterator >::init(), DGtal::TrueGlobalEstimatorOnPoints< TConstIteratorOnPoints, TParametricShape, TParametricShapeFunctor >::init(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::init(), DGtal::GridCurve< KSpace >::initFromVector(), DGtal::GridCurve< KSpace >::isClosed(), DGtal::Clock::startClock(), DGtal::Clock::stopClock(), and DGtal::Surfaces< TKSpace >::track2DBoundaryPoints().
int main (int argc, char ** argv)
ball
Definition at line 328 of file lengthEstimators.cpp.
References checkAndRetrunIndex(), createList(), displayList(), DGtal::Trace::error(), DGtal::Trace::info(), missingParam(), and DGtal::trace.
void missingParam (std::string param)
Missing parameter error message.
Parameters:
param
Definition at line 195 of file lengthEstimators.cpp.
References DGtal::Trace::error(), DGtal::Trace::info(), and DGtal::trace.
Variable Documentation
std::vector<std::string> shapes2D
Global vectors to describe the available shapes and their parameters.
Definition at line 80 of file lengthEstimators.cpp.
std::vector<std::string> shapesDesc
Definition at line 81 of file lengthEstimators.cpp.
std::vector<std::string> shapesParam1
Definition at line 82 of file lengthEstimators.cpp.
std::vector<std::string> shapesParam2
Definition at line 83 of file lengthEstimators.cpp.
std::vector<std::string> shapesParam3
Definition at line 84 of file lengthEstimators.cpp.
std::vector<std::string> shapesParam4
Definition at line 85 of file lengthEstimators.cpp.