DGtal: pgm2freeman.cpp File Reference
pgm2freeman.cpp File Reference
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/topology/KhalimskySpaceND.h"
#include "DGtal/shapes/ShapeFactory.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/geometry/helpers/ContourHelper.h"
#include "DGtal/io/colormaps/GrayScaleColorMap.h"
#include "DGtal/images/imagesSetsUtils/ImageFromSet.h"
#include "DGtal/images/imagesSetsUtils/SetFromImage.h"
#include "DGtal/images/ImageContainerBySTLVector.h"
#include "DGtal/images/ImageSelector.h"
#include "DGtal/io/readers/PNMReader.h"
#include "DGtal/geometry/2d/FreemanChain.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/topology/helpers/Surfaces.h"
#include <boost/program_options/options_description.hpp>
#include <boost/program_options/parsers.hpp>
#include <boost/program_options/variables_map.hpp>
#include <vector>
#include <string>
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 69 of file pgm2freeman.cpp.
References DGtal::Trace::error(), DGtal::Surfaces< TKSpace >::extractAllPointContours4C(), DGtal::ContourHelper::getMeanPoint(), DGtal::PNMReader< TImageContainer >::importPGMImage(), DGtal::Trace::info(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), DGtal::max(), DGtal::min(), DGtal::trace, and DGtal::FreemanChain< TInteger >::x0.