DGtal: DGtal::VolWriter< TImage, TColormap > Struct Template Reference
DGtal::VolWriter< TImage, TColormap > Struct Template Reference
Aim: Export a 3D Image using the Vol formats.
#include <VolWriter.h>
Public Types
typedef TImage Image
typedef TImage::Value Value
typedef TColormap Colormap
Public Member Functions
BOOST_CONCEPT_ASSERT ((CColorMap< TColormap >))
BOOST_STATIC_ASSERT (TImage::Domain::dimension==3)
BOOST_STATIC_ASSERT ((boost::is_same< typename TColormap::Value, typename TImage::Value >::value))
Static Public Member Functions
static bool exportVol (const std::string &filename, const Image &aImage, const Value &minV, const Value &maxV) throw (DGtal::IOException)
Detailed Description
template<typename TImage, typename TColormap>
struct DGtal::VolWriter< TImage, TColormap >
Aim: Export a 3D Image using the Vol formats.
Description of template struct 'VolWriter'
Template Parameters:
TImage the Image type.
TColormap the type of the colormap to use in the export.
Definition at line 64 of file VolWriter.h.
Member Typedef Documentation
template<typename TImage , typename TColormap > typedef TColormap DGtal::VolWriter< TImage, TColormap >::Colormap
Definition at line 77 of file VolWriter.h.
template<typename TImage , typename TColormap > typedef TImage DGtal::VolWriter< TImage, TColormap >::Image
Definition at line 75 of file VolWriter.h.
template<typename TImage , typename TColormap > typedef TImage::Value DGtal::VolWriter< TImage, TColormap >::Value
Definition at line 76 of file VolWriter.h.
Member Function Documentation
template<typename TImage , typename TColormap > DGtal::VolWriter< TImage, TColormap >::BOOST_CONCEPT_ASSERT ((CColorMap< TColormap >))
template<typename TImage , typename TColormap > DGtal::VolWriter< TImage, TColormap >::BOOST_STATIC_ASSERT (TImage::Domain::dimension = =3)
template<typename TImage , typename TColormap > DGtal::VolWriter< TImage, TColormap >::BOOST_STATIC_ASSERT ((boost::is_same< typename TColormap::Value, typename TImage::Value >::value))
template<typename TImage , typename TColormap > bool DGtal::VolWriter< I, C >::exportVol (const std::string & filename, const Image & aImage, const Value & minV, const Value & maxV) throw (DGtal::IOException) [static]
Export an Image with the Vol format.
Parameters:
filename name of the output file
aImage the image to export
minV the minimum value of aImage (for colormap)
maxV the maximum value of aImage (for colormap)
Returns:
true if no errors occur.
Definition at line 44 of file VolWriter.ih.
References DGtal::Color::blue(), DGtal::Color::green(), and DGtal::Color::red().
{
 DGtal::IOException dgtalio;
  ofstream out;
  typename I::Domain::Vector ext = aImage.extent();
  typename I::Domain domain(aImage.lowerBound(), aImage.upperBound());
  typename I::Value val;
  C colormap(minV,maxV);
  Color col;
  try
    {
      out.open(filename.c_str());
      //Vol format
      out << "X: "<< ext[0]<<endl;
      out << "Y: "<< ext[1]<<endl;
      out << "Z: "<< ext[2]<<endl;
      out << "Voxel-Size: 1"<<endl;
      out << "Alpha-Color: 0"<<endl;
      out << "Voxel-Endian: 0"<<endl;
      out << "Int-Endian: 0123"<<endl;
      out << "Version: 2"<<endl;
      out << "."<<endl;
      //We scan the domain instead of the image because we cannot
      //trust the image container Iterator
      for(typename I::Domain::ConstIterator it = domain.begin(), itend=domain.end();
    it!=itend;
    ++it)
  {
    val = aImage( (*it) );
    col = colormap( val );
    out.put((unsigned char) (((int)col.red()+(int)col.green() + (int)col.blue())/3));
  }
      out.close();
    }
  catch( ... )
    {
      std::cout << "Vol writer IO error on export " << filename << endl;
      throw dgtalio;
    }
  return true;
}
The documentation for this struct was generated from the following files:
VolWriter.h
VolWriter.ih