DGtal: DGtal::LongvolWriter< TImage, TColormap > Struct Template Reference
DGtal::LongvolWriter< TImage, TColormap > Struct Template Reference
Aim: Export a 3D Image using the Longvol formats (volumetric image with DGtal::uint64_t value type).
#include <LongvolWriter.h>
Public Types
typedef TImage Image
typedef TImage::Value Value
typedef TColormap Colormap
Public Member Functions
BOOST_CONCEPT_ASSERT ((CColorMap< TColormap >))
BOOST_STATIC_ASSERT (TImage::Domain::dimension==3)
BOOST_STATIC_ASSERT ((boost::is_same< typename TColormap::Value, typename TImage::Value >::value))
Static Public Member Functions
static bool exportLongvol (const std::string &filename, const Image &aImage, const Value &minV, const Value &maxV) throw (DGtal::IOException)
Static Private Member Functions
template<typename Word >
static ostream & write_word (ostream &outs, Word value)
Detailed Description
template<typename TImage, typename TColormap>
struct DGtal::LongvolWriter< TImage, TColormap >
Aim: Export a 3D Image using the Longvol formats (volumetric image with DGtal::uint64_t value type).
Description of template struct 'LongvolWriter'
The file format contains an ASCII header and a raw binary array (little-endian uint64t).
Template Parameters:
TImage the Image type.
TColormap the type of the colormap to use in the export.
See also:
testLongvol.cpp
Definition at line 68 of file LongvolWriter.h.
Member Typedef Documentation
template<typename TImage , typename TColormap > typedef TColormap DGtal::LongvolWriter< TImage, TColormap >::Colormap
Definition at line 79 of file LongvolWriter.h.
template<typename TImage , typename TColormap > typedef TImage DGtal::LongvolWriter< TImage, TColormap >::Image
Definition at line 77 of file LongvolWriter.h.
template<typename TImage , typename TColormap > typedef TImage::Value DGtal::LongvolWriter< TImage, TColormap >::Value
Definition at line 78 of file LongvolWriter.h.
Member Function Documentation
template<typename TImage , typename TColormap > DGtal::LongvolWriter< TImage, TColormap >::BOOST_CONCEPT_ASSERT ((CColorMap< TColormap >))
template<typename TImage , typename TColormap > DGtal::LongvolWriter< TImage, TColormap >::BOOST_STATIC_ASSERT (TImage::Domain::dimension = =3)
template<typename TImage , typename TColormap > DGtal::LongvolWriter< TImage, TColormap >::BOOST_STATIC_ASSERT ((boost::is_same< typename TColormap::Value, typename TImage::Value >::value))
template<typename TImage , typename TColormap > bool DGtal::LongvolWriter< I, C >::exportLongvol (const std::string & filename, const Image & aImage, const Value & minV, const Value & maxV) throw (DGtal::IOException) [static]
Export an Image with the Longvol format. A DGtal::IOException is thrown in case of io problems.
Parameters:
filename name of the output file
aImage the image to export
minV the minimum value of aImage (for colormap)
maxV the maximum value of aImage (for colormap)
Returns:
true if no errors occur.
Todo:
catch IOerror excpetion
Definition at line 44 of file LongvolWriter.ih.
References DGtal::Color::blue(), DGtal::Color::green(), and DGtal::Color::red().
{
  DGtal::IOException dgtalio;
  ofstream out;
  typename I::Domain::Vector ext = aImage.extent();
  typename I::Domain domain(aImage.lowerBound(), aImage.upperBound());
  typename I::Value val;
  C colormap(minV,maxV);
  Color col;
  try
    {
      out.open(filename.c_str());
      //Longvol format
      out << "X: "<< ext[0]<<endl;
      out << "Y: "<< ext[1]<<endl;
      out << "Z: "<< ext[2]<<endl;
      out << "Lvoxel-Size: 4"<<endl; //not used in liblongvol but required
      out << "Alpha-Color: 0"<<endl;
      out << "Lvoxel-Endian: 0"<<endl;//not used in liblongvol but required
      out << "Int-Endian: 0123"<<endl;
      out << "Version: 2"<<endl;
      out << "."<<endl;
      out.close();
      out.open(filename.c_str(),ios_base::binary | ios_base::app);
      DGtal::uint64_t longval;
      //We scan the domain instead of the image because we cannot
      //trust the image container Iterator
      for(typename I::Domain::ConstIterator it = domain.begin(), itend=domain.end();
    it!=itend;
    ++it)
  {
    val = aImage( (*it) );
    col = colormap( val );
    longval = (DGtal::uint64_t) (((int)col.red()+(int)col.green() + (int)col.blue())/3);
    write_word(out,longval);
  }
      out.close();
    }
  catch( ... )
    {
      std::cout << "LongVol writer IO error on export " << filename << endl;
      throw dgtalio;
    }
  return true;
}
template<typename TImage , typename TColormap > template<typename Word > static ostream& DGtal::LongvolWriter< TImage, TColormap >::write_word (ostream & outs, Word value) [inline, static, private]
Generic write word (binary mode) in little-endian.
Parameters:
outs output stream.
value value to write.
Returns:
modified stream.
Definition at line 109 of file LongvolWriter.h.
    {
      for (unsigned size = sizeof( Word ); size; --size, value >>= 8)
  outs.put( static_cast <char> (value & 0xFF) );
      return outs;
    }
The documentation for this struct was generated from the following files:
LongvolWriter.h
LongvolWriter.ih