DGtal: Exporter< Set, Image > Struct Template Reference
Exporter< Set, Image > Struct Template Reference
Public Types
typedef GrayscaleColorMap
< unsigned char > Gray
Static Public Member Functions
static void save (const Set &aSet, const std::string outputName, const std::string outputFormat)
template<typename Shape >
static void exportSignature (const Shape &aShape, const Set &aSet, const Z2i::Domain &aDomain)
Detailed Description
template<typename Set, typename Image>
struct Exporter< Set, Image >
Functor to export a given shape into an image file (pgm,raw,pdf,svg,...) and to extract its signature.
Template Parameters:
Set type of the input Set
Image type of the input Image.
Definition at line 183 of file shapeGenerator.cpp.
Member Typedef Documentation
template<typename Set , typename Image > typedef GrayscaleColorMap<unsigned char> Exporter< Set, Image >::Gray
Definition at line 185 of file shapeGenerator.cpp.
Member Function Documentation
template<typename Set , typename Image > template<typename Shape > static void Exporter< Set, Image >::exportSignature (const Shape & aShape, const Set & aSet, const Z2i::Domain & aDomain) [inline, static]
Compute and export (std::cout) the boundary of the set and export the signature (normal vector, curvature) at each point of the 2D contour.
Parameters:
aShape the shape
aSet input set corresponding to the shape
aDomain the domain used to construct the set.
Export
Definition at line 255 of file shapeGenerator.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), DGtal::HyperRectDomain< TSpace >::lowerBound(), DGtal::trace, and DGtal::HyperRectDomain< TSpace >::upperBound().
  {
    SetPredicate<Set> aSetPredicate( aSet );
    trace.beginBlock("Extracting the boundary");
    Z2i::KSpace ks;
    bool space_ok = ks.init( aDomain.lowerBound(),aDomain.upperBound(), true );
    SurfelAdjacency<2> sAdj( true );
    ASSERT(space_ok);
    trace.info() << aSet << std::endl;
    trace.info() << ks
                 << ( space_ok ? " Successfully instantiated" : " Error" )
                 << std::endl;
    std::vector< std::vector< Z2i::Point >  >  vectContoursBdryPointels;
    Surfaces<Z2i::KSpace>::extractAllPointContours4C( vectContoursBdryPointels,
                                                      ks, aSetPredicate, sAdj );
    trace.endBlock();
    std::cout<<"## shapeGenerator signature export"<<std::endl;
    std::cout<<"## shape: "<<aShape<<std::endl;
    std::cout<<"## x\ty\tdx\tdy\tddx\tddy"<<std::endl;
    for(unsigned int i=0; i<vectContoursBdryPointels.size(); i++)
      for(unsigned int j=0 ; j< vectContoursBdryPointels.at(i).size() - 1; j++)
        {
          Z2i::Space::Point point = (vectContoursBdryPointels.at(i).at(j)
                                     + vectContoursBdryPointels.at(i).at(j+1));
          Z2i::Space::RealPoint midpoint (point[0]/2.0,point[1]/2.0);
          Z2i::Space::RealPoint xp,xpp;
          double t = aShape.parameter(midpoint);
          xp = aShape.xp( t );
          xpp = aShape.xpp( t );
          std::cout<< midpoint[0]<<"\t"<<midpoint[1]<<"\t"
                   << xp[0]<<"\t"<<xp[1]<<"\t"
                   << xpp[0]<<"\t"<<xpp[1]<<std::endl;
        }
  }
template<typename Set , typename Image > static void Exporter< Set, Image >::save (const Set & aSet, const std::string outputName, const std::string outputFormat) [inline, static]
Export a given Set into an image file.
Parameters:
aSet input set.
outputName output file name.
outputFormat output file format.
Definition at line 197 of file shapeGenerator.cpp.
References LibBoard::Board::CairoPDF, LibBoard::Board::CairoPNG, DGtal::Trace::error(), LibBoard::Board::saveSVG(), and DGtal::trace.
  {
    Image  image = ImageFromSet<Image>::template create<Set>(aSet, 255, true);
    if  (outputFormat == "pgm")
      PNMWriter<Image,Gray>::exportPGM(outputName+"."+outputFormat,image,0,255);
    else
      if (outputFormat == "raw")
        RawWriter<Image,Gray>::exportRaw8(outputName+"."+outputFormat,image,0,255);
      else
        if (outputFormat == "svg")
          {
            Board2D board;
            board << aSet;
            board.saveSVG((outputName+"."+outputFormat).c_str());
          }
        else
#ifdef WITH_CAIRO
          if (outputFormat == "pdf")
            {
              Board2D board;
              board << aSet;
              board.saveCairo((outputName+"."+outputFormat).c_str(), Board2D::CairoPDF);
            }
          else
            if (outputFormat == "png")
              {
                Board2D board;
                board << aSet;
                board.saveCairo((outputName+"."+outputFormat).c_str(), Board2D::CairoPNG);
              }
            else
#endif
              {
                trace.error()<< "Output format: "<<outputFormat<< " not recognized."<<std::endl;
                exit(1);
              }
  }
The documentation for this struct was generated from the following file:
shapeGenerator.cpp