DGtal: testRealPointVector.cpp File Reference
testRealPointVector.cpp File Reference
#include <cstdio>
#include <cmath>
#include <iostream>
#include <fstream>
#include <vector>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/RealPointVector.h"
#include "DGtal/helpers/StdDefs.h"
Functions
bool testComparison ()
bool testNormalise ()
bool testSimplePoint ()
bool testNorms ()
bool testSimpleVector ()
bool testIterator ()
bool testOperators ()
int main ()
Function Documentation
int main ()
Definition at line 234 of file testRealPointVector.cpp.
References testComparison(), testIterator(), testNormalise(), testNorms(), testOperators(), testSimplePoint(), and testSimpleVector().
bool testComparison ()
Definition at line 49 of file testRealPointVector.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.
bool testIterator ()
Definition at line 190 of file testRealPointVector.cpp.
References DGtal::PointVector< dim, double >::at(), DGtal::PointVector< dim, double >::begin(), DGtal::Trace::beginBlock(), DGtal::PointVector< dim, double >::end(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.
bool testNormalise ()
Definition at line 83 of file testRealPointVector.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::RealPointVector< dim >::normalize(), and DGtal::trace.
Referenced by main().
bool testNorms ()
Definition at line 145 of file testRealPointVector.cpp.
References DGtal::PointVector< dim, TComponent >::at(), DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.
bool testOperators ()
Definition at line 212 of file testRealPointVector.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::PointVector< dim, double >::inf(), DGtal::Trace::info(), DGtal::PointVector< dim, double >::sup(), and DGtal::trace.
bool testSimplePoint ()
Test instanciation of Points
Definition at line 105 of file testRealPointVector.cpp.
References DGtal::Trace::beginBlock(), DGtal::RealPointVector< dim >::dimension, DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.
bool testSimpleVector ()
Test instancition of Vectors
Definition at line 170 of file testRealPointVector.cpp.
References DGtal::Trace::beginBlock(), DGtal::RealPointVector< dim >::dimension, DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.