DGtal: testFreemanChain.cpp File Reference
testFreemanChain.cpp File Reference
DGtal test files
#include <iostream>
#include <fstream>
#include <sstream>
#include <boost/program_options.hpp>
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/base/Common.h"
#include "DGtal/geometry/2d/FreemanChain.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/io/boards/Board2D.h"
#include "ConfigTest.h"
Typedefs
typedef SpaceND< 2 > Space2Type
typedef HyperRectDomain
< Space2Type > Domain2D
typedef Space2Type::Point Point
Functions
bool testFreemanChainIterator (const std::string &code)
bool testFreemanChain (const string &code)
bool testDisplayFreemanChain (const string &file)
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
Bertrand Kerautret (kerautre@loria.fr) LORIA (CNRS, UMR 7503), University of Nancy, France
Date:
2010/07/05
Functions for testing class FreemanChain.
This file is part of the DGtal library.
Definition in file testFreemanChain.cpp.
Typedef Documentation
typedef HyperRectDomain<Space2Type> Domain2D
Definition at line 52 of file testFreemanChain.cpp.
typedef Space2Type::Point Point
Examples:
3dBorderExtraction.cpp, 3dKSSurfaceExtraction.cpp, ctopo-1-3d.cpp, ctopo-1.cpp, ctopo-1s-3d.cpp, distancetransform2D.cpp, distancetransform3D.cpp, viewer3D-2-sets.cpp, viewer3D-3-objects.cpp, and viewer3D-6-clipping.cpp.
Definition at line 53 of file testFreemanChain.cpp.
typedef SpaceND<2> Space2Type
Definition at line 51 of file testFreemanChain.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 200 of file testFreemanChain.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testDisplayFreemanChain(), testFreemanChain(), testFreemanChainIterator(), testPath, and DGtal::trace.
bool testDisplayFreemanChain (const string & file)
Example of a test. To be completed.
Definition at line 158 of file testFreemanChain.cpp.
References LibBoard::Board::saveEPS(), LibBoard::Board::saveFIG(), LibBoard::Board::saveSVG(), LibBoard::Board::setPenColor(), LibBoard::Board::setUnit(), LibBoard::Shape::shiftDepth(), and testPath.
Referenced by main().
bool testFreemanChain (const string & code)
Example of a test. To be completed.
Definition at line 99 of file testFreemanChain.cpp.
References DGtal::Trace::beginBlock(), DGtal::FreemanChain< TInteger >::computeBoundingBox(), DGtal::Trace::endBlock(), DGtal::FreemanChain< TInteger >::getContourPoints(), DGtal::Trace::info(), DGtal::FreemanChain< TInteger >::isClosed(), and DGtal::trace.
Referenced by main().
bool testFreemanChainIterator (const std::string & code)
test reverse iterator
Definition at line 59 of file testFreemanChain.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.
Referenced by main().