DGtal: testDecomposition.cpp File Reference
testDecomposition.cpp File Reference
DGtal test files
#include <cstdio>
#include <cmath>
#include <fstream>
#include <vector>
#include <iostream>
#include <iterator>
#include "DGtal/base/Common.h"
#include "DGtal/base/Exceptions.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/io/Color.h"
#include "DGtal/geometry/2d/ArithmeticalDSS.h"
#include "DGtal/geometry/2d/FreemanChain.h"
#include "DGtal/geometry/2d/GreedyDecomposition.h"
#include "ConfigTest.h"
Functions
bool testDec4 ()
bool testDec8 ()
bool testDisconnectedCurve ()
bool testClosedCurvesProcessedAsClosed ()
bool testClosedCurvesProcessedAsOpen ()
bool testOpenCurvesProcessedAsClosed ()
bool testNoPoint ()
bool testOnePoint ()
bool testTwoEndIterators ()
bool testOneDSS ()
bool testDec8Reverse ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
Tristan Roussillon (tristan.roussillon@liris.cnrs.fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date:
2010/07/02
This file is part of the DGtal library
Definition in file testDecomposition.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 621 of file testDecomposition.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testClosedCurvesProcessedAsClosed(), testClosedCurvesProcessedAsOpen(), testDec4(), testDec8(), testDec8Reverse(), testDisconnectedCurve(), testNoPoint(), testOneDSS(), testOnePoint(), testOpenCurvesProcessedAsClosed(), testTwoEndIterators(), and DGtal::trace.
bool testClosedCurvesProcessedAsClosed ()
Test for closed curves processed as closed
Definition at line 257 of file testDecomposition.cpp.
References DGtal::Trace::beginBlock(), DGtal::Color::Blue, DGtal::Trace::endBlock(), and DGtal::trace.
Referenced by main().
bool testClosedCurvesProcessedAsOpen ()
Test for closed curves processed as closed
Definition at line 305 of file testDecomposition.cpp.
References DGtal::Trace::beginBlock(), DGtal::Color::Blue, DGtal::Trace::endBlock(), DGtal::false, and DGtal::trace.
Referenced by main().
bool testDec4 ()
Test for the segmentation of 4-connected digital curves into DSS
Definition at line 69 of file testDecomposition.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), LibBoard::Board::setUnit(), testPath, and DGtal::trace.
Referenced by main().
bool testDec8 ()
Test for the segmentation of 8-connected digital curves into DSS
Definition at line 124 of file testDecomposition.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), LibBoard::Board::setUnit(), and DGtal::trace.
Referenced by main().
bool testDec8Reverse ()
Test for the segmentation of 8-connected digital curves into DSS
Definition at line 563 of file testDecomposition.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), LibBoard::Board::setUnit(), and DGtal::trace.
Referenced by main().
bool testDisconnectedCurve ()
Test for the segmentation of disconnected digital curves into DSS
Definition at line 188 of file testDecomposition.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), LibBoard::Board::setUnit(), and DGtal::trace.
Referenced by main().
bool testNoPoint ()
Test with no point
Definition at line 399 of file testDecomposition.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), and DGtal::trace.
Referenced by main().
bool testOneDSS ()
Test for the segmentation of one DSS into DSSs
Definition at line 508 of file testDecomposition.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), LibBoard::Board::setUnit(), and DGtal::trace.
Referenced by main().
bool testOnePoint ()
Test with one point
Definition at line 430 of file testDecomposition.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.
Referenced by main().
bool testOpenCurvesProcessedAsClosed ()
Test for open curves processed as closed
Definition at line 352 of file testDecomposition.cpp.
References DGtal::Trace::beginBlock(), DGtal::Color::Blue, DGtal::Trace::endBlock(), and DGtal::trace.
Referenced by main().
bool testTwoEndIterators ()
Test when init with two end iterators
Definition at line 472 of file testDecomposition.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), and DGtal::trace.
Referenced by main().