DGtal: testBasicBoolFunctions.cpp File Reference
testBasicBoolFunctions.cpp File Reference
DGtal test files
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/base/BasicBoolFunctions.h"
Defines
#define INBLOCK_TEST(x)
#define INBLOCK_TEST2(x, y)
Functions
bool testBasicBoolFunctions ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
Jacques-Olivier Lachaud (jacques-olivier.lachaud@univ-savoie.fr) Laboratory of Mathematics (CNRS, UMR 5807), University of Savoie, France
Date:
2010/07/10
Functions for testing class BasicBoolFunctions.
This file is part of the DGtal library.
Definition in file testBasicBoolFunctions.cpp.
Define Documentation
#define INBLOCK_TEST (x)
Value:
nbok += (x) ? 1 : 0; \
  nb++; \
  trace.info() << "(" << nbok << "/" << nb << ") " \
               << #x << std::endl;
Definition at line 39 of file testBasicBoolFunctions.cpp.
#define INBLOCK_TEST2 (x, y)
Value:
nbok += (x) ? 1 : 0; \
  nb++; \
  trace.info() << "(" << nbok << "/" << nb << ") " \
  << y << std::endl;
Definition at line 45 of file testBasicBoolFunctions.cpp.
Referenced by testBasicBoolFunctions().
Function Documentation
int main (int argc, char ** argv)
Examples:
/home/dcoeurjo/Sources/DGtal/examples/io/boards/dgtalBoard2D-1-points.cpp, 3dBorderExtraction.cpp, 3dBorderExtractionImg.cpp, 3dKSSurfaceExtraction.cpp, ctopo-1-3d.cpp, ctopo-1.cpp, ctopo-1s-3d.cpp, ctopo-2-3d.cpp, ctopo-2.cpp, digitalSetFromPointList.cpp, digitalSetFromVol.cpp, distancetransform2D.cpp, distancetransform3D.cpp, freemanChainFromImage.cpp, homotopicThinning3D.cpp, khalimskySpaceScanner.cpp, viewer3D-1-points.cpp, viewer3D-2-sets.cpp, viewer3D-3-objects.cpp, viewer3D-4-modes.cpp, viewer3D-5-custom.cpp, and viewer3D-6-clipping.cpp.
Definition at line 156 of file testBasicBoolFunctions.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testBasicBoolFunctions(), and DGtal::trace.
bool testBasicBoolFunctions ()
Example of a test. To be completed.
Definition at line 58 of file testBasicBoolFunctions.cpp.
References DGtal::andBF2, DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::falseBF0, DGtal::identityBF1, DGtal::impliesBF2, INBLOCK_TEST2, DGtal::Trace::info(), DGtal::notBF1, DGtal::orBF2, DGtal::trace, DGtal::trueBF0, and DGtal::xorBF2.
Referenced by main().