DGtal: testGridCurve.cpp File Reference
testGridCurve.cpp File Reference
#include <iostream>
#include <fstream>
#include <sstream>
#include <exception>
#include <boost/program_options.hpp>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/kernel/sets/DigitalSetSelector.h"
#include "DGtal/topology/KhalimskySpaceND.h"
#include "DGtal/topology/SurfelAdjacency.h"
#include "DGtal/topology/SurfelNeighborhood.h"
#include "DGtal/geometry/2d/GridCurve.h"
#include "DGtal/io/boards/Board2D.h"
#include "ConfigTest.h"
Functions
template<typename KSpace >
bool testIOGridCurve (const string &filename)
bool testIsOpen (const string &filename, const bool &aFlag)
bool testExceptions (const string &filename)
bool testDisplay (const string &filename)
template<typename Range >
bool testRange (const Range &aRange)
template<typename Range >
bool testArrowsRange (const Range &aRange)
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
Tristan Roussillon (tristan.roussillon@liris.cnrs.fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date:
2011/06/27
Functions for testing class GridCurve
This file is part of the DGtal library.
Definition in file testGridCurve.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 256 of file testGridCurve.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::GridCurve< KSpace >::get0SCellsRange(), DGtal::GridCurve< KSpace >::get1SCellsRange(), DGtal::GridCurve< KSpace >::getArrowsRange(), DGtal::GridCurve< KSpace >::getMidPointsRange(), DGtal::GridCurve< KSpace >::getPointsRange(), DGtal::Trace::info(), DGtal::GridCurve< KSpace >::initFromVectorStream(), testDisplay(), testExceptions(), testIsOpen(), testPath, and DGtal::trace.
template<typename Range > bool testArrowsRange (const Range & aRange)
Definition at line 226 of file testGridCurve.cpp.
References DGtal::FreemanChain< TInteger >::begin(), DGtal::FreemanChain< TInteger >::end(), DGtal::Trace::info(), DGtal::FreemanChain< TInteger >::size(), and DGtal::trace.
bool testDisplay (const string & filename)
Display
Definition at line 160 of file testGridCurve.cpp.
References DGtal::Trace::info(), DGtal::GridCurve< KSpace >::initFromVectorStream(), LibBoard::Board::saveEPS(), LibBoard::Board::setUnit(), DGtal::GridCurve< KSpace >::styleName(), and DGtal::trace.
Referenced by main().
bool testExceptions (const string & filename)
Exceptions
Definition at line 129 of file testGridCurve.cpp.
References DGtal::Trace::info(), DGtal::GridCurve< KSpace >::initFromVectorStream(), DGtal::trace, DGtal::InputException::what(), and DGtal::ConnectivityException::what().
Referenced by main().
template<typename KSpace > bool testIOGridCurve (const string & filename)
IO Tests
Definition at line 70 of file testGridCurve.cpp.
References DGtal::Trace::info(), DGtal::GridCurve< KSpace >::initFromVectorStream(), DGtal::trace, and DGtal::GridCurve< KSpace >::writeVectorToStream().
bool testIsOpen (const string & filename, const bool & aFlag)
Open/Closed
Definition at line 108 of file testGridCurve.cpp.
References DGtal::Trace::info(), DGtal::GridCurve< KSpace >::initFromVectorStream(), DGtal::GridCurve< KSpace >::isOpen(), and DGtal::trace.
Referenced by main().
template<typename Range > bool testRange (const Range & aRange)
Ranges
Definition at line 199 of file testGridCurve.cpp.
References DGtal::FreemanChain< TInteger >::begin(), DGtal::FreemanChain< TInteger >::end(), DGtal::Trace::info(), DGtal::FreemanChain< TInteger >::size(), and DGtal::trace.