DGtal: testLengthEstimators.cpp File Reference
testLengthEstimators.cpp File Reference
#include <cmath>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/topology/KhalimskySpaceND.h"
#include "DGtal/shapes/ShapeFactory.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/topology/helpers/Surfaces.h"
#include "DGtal/geometry/nd/GaussDigitizer.h"
#include "DGtal/geometry/2d/GridCurve.h"
#include "DGtal/geometry/2d/estimators/TrueLocalEstimatorOnPoints.h"
#include "DGtal/geometry/2d/estimators/TrueGlobalEstimatorOnPoints.h"
#include "DGtal/geometry/2d/estimators/ParametricShapeCurvatureFunctor.h"
#include "DGtal/geometry/2d/estimators/ParametricShapeTangentFunctor.h"
#include "DGtal/geometry/2d/estimators/ParametricShapeArcLengthFunctor.h"
#include "DGtal/geometry/2d/estimators/L1LengthEstimator.h"
#include "DGtal/geometry/2d/estimators/TwoStepLocalLengthEstimator.h"
#include "DGtal/geometry/2d/estimators/BLUELocalLengthEstimator.h"
#include "DGtal/geometry/2d/estimators/RosenProffittLocalLengthEstimator.h"
#include "DGtal/geometry/2d/estimators/MLPLengthEstimator.h"
#include "DGtal/geometry/2d/estimators/FPLengthEstimator.h"
#include "DGtal/geometry/2d/estimators/DSSLengthEstimator.h"
#include "ConfigTest.h"
Functions
bool testLengthEstimatorsOnBall (double radius, double h)
bool testDisplay (double radius, double h)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 295 of file testLengthEstimators.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testDisplay(), testLengthEstimatorsOnBall(), and DGtal::trace.
bool testDisplay (double radius, double h)
Definition at line 176 of file testLengthEstimators.cpp.
References DGtal::GaussDigitizer< TSpace, TEuclideanShape >::attach(), LibBoard::Board::clear(), DGtal::GridCurve< KSpace >::get1SCellsRange(), DGtal::GridCurve< KSpace >::getArrowsRange(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getDomain(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getLowerBound(), DGtal::GridCurve< KSpace >::getPointsRange(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getUpperBound(), DGtal::Trace::info(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::init(), DGtal::GridCurve< KSpace >::initFromVector(), LibBoard::Board::saveSVG(), DGtal::PointVector< dim, TComponent >::selfDraw(), LibBoard::Board::setPenColor(), and DGtal::trace.
bool testLengthEstimatorsOnBall (double radius, double h)
Definition at line 77 of file testLengthEstimators.cpp.
References DGtal::GaussDigitizer< TSpace, TEuclideanShape >::attach(), DGtal::FPLengthEstimator< TConstIterator >::eval(), DGtal::MLPLengthEstimator< TConstIterator >::eval(), DGtal::DSSLengthEstimator< TConstIterator >::eval(), DGtal::TwoStepLocalLengthEstimator< TConstIterator >::eval(), DGtal::L1LengthEstimator< TConstIterator >::eval(), DGtal::GridCurve< KSpace >::getArrowsRange(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getDomain(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getLowerBound(), DGtal::GridCurve< KSpace >::getPointsRange(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getUpperBound(), DGtal::Trace::info(), DGtal::FPLengthEstimator< TConstIterator >::init(), DGtal::MLPLengthEstimator< TConstIterator >::init(), DGtal::DSSLengthEstimator< TConstIterator >::init(), DGtal::TwoStepLocalLengthEstimator< TConstIterator >::init(), DGtal::L1LengthEstimator< TConstIterator >::init(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::init(), DGtal::GridCurve< KSpace >::initFromVector(), DGtal::GridCurve< KSpace >::isClosed(), M_PI, and DGtal::trace.
Referenced by main().