DGtalTools: MainWindow Class Reference
MainWindow Class Reference
#include <visualisation/sliceViewer.h>
Inherits QMainWindow.
Data Structures
struct ColorMapFunctor
Public Types
enum ColorMapType { Id , GradientMapHot , GradientMapCool , HueshadeCM }
typedef DGtal::ImageContainerBySTLVector< DGtal::Z3i::Domain, unsigned char > Image3D
typedef DGtal::ImageContainerBySTLVector< DGtal::Z2i::Domain, unsigned char > Image2D
typedef DGtal::ConstImageAdapter< Image3D, Image2D::Domain, DGtal::functors::Projector< DGtal::Z3i::Space >, Image3D::Value, DGtal::functors::Identity > SliceImageAdapter
typedef DGtal::ConstImageAdapter< Image3D, Image2D::Domain, DGtal::functors::Projector< DGtal::Z3i::Space >, Image3D::Value, ColorMapFunctor > SliceImageAdapterFct
Public Slots
void updateSliceImageX ()
void updateSliceImageY ()
void updateSliceImageZ ()
void updateZoomImageX ()
void updateZoomImageY ()
void updateZoomImageZ ()
void setScale1_1_ImageX ()
void setScale1_1_ImageY ()
void setScale1_1_ImageZ ()
void changeNormalColorMap ()
void changeCoolColorMap ()
void changeHueColorMap ()
void changeHotColorMap ()
Public Member Functions
MainWindow (DGtal::Viewer3D<> *viewer, DGtal::ImageContainerBySTLVector< DGtal::Z3i::Domain, unsigned char > *myImage3D, const ColorMapFunctor &aFunctor, QWidget *parent=0, Qt::WindowFlags flags=0)
~MainWindow ()
void setImageProjX (const QPixmap &aPixMap)
void setImageProjY (const QPixmap &aPixMap)
void setImageProjZ (const QPixmap &aPixMap)
void updateSliceImageX (int sliceNumber, bool init)
void updateSliceImageY (int sliceNumber, bool init)
void updateSliceImageZ (int sliceNumber, bool init)
void updateZoomImageX (int sliceNumber, double gridSize)
void updateZoomImageY (int sliceNumber, double gridSize)
void updateZoomImageZ (int sliceNumber, double gridSize)
void updateAllDisplayedImages ()
Private Attributes
Ui::MainWindow * ui
DGtal::Viewer3D * myViewer
Image3D * myImage3D
ColorMapFunctor myColorMap
Detailed Description
Definition at line 48 of file sliceViewer.h.
Member Typedef Documentation
Image2D
typedef DGtal::ImageContainerBySTLVector< DGtal::Z2i::Domain, unsigned char > MainWindow::Image2D
Definition at line 96 of file sliceViewer.h.
Image3D
typedef DGtal::ImageContainerBySTLVector< DGtal::Z3i::Domain, unsigned char > MainWindow::Image3D
Definition at line 95 of file sliceViewer.h.
SliceImageAdapter
typedef DGtal::ConstImageAdapter<Image3D, Image2D::Domain, DGtal::functors::Projector< DGtal::Z3i::Space>, Image3D::Value, DGtal::functors::Identity > MainWindow::SliceImageAdapter
Definition at line 98 of file sliceViewer.h.
SliceImageAdapterFct
typedef DGtal::ConstImageAdapter<Image3D, Image2D::Domain, DGtal::functors::Projector< DGtal::Z3i::Space>, Image3D::Value, ColorMapFunctor > MainWindow::SliceImageAdapterFct
Definition at line 100 of file sliceViewer.h.
Member Enumeration Documentation
ColorMapType
enum MainWindow::ColorMapType
Enumerator
Id
GradientMapHot
GradientMapCool
HueshadeCM
Definition at line 54 of file sliceViewer.h.
 {Id, GradientMapHot, GradientMapCool,  HueshadeCM};
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (DGtal::Viewer3D<> * viewer, DGtal::ImageContainerBySTLVector< DGtal::Z3i::Domain, unsigned char > * myImage3D, const ColorMapFunctor & aFunctor, QWidget * parent = 0, Qt::WindowFlags flags = 0) explicit
Definition at line 133 of file sliceViewer.cpp.
                                                                                               :
   QMainWindow(parent),
   ui(new Ui::MainWindow),
   myViewer(aViewer),
   myImage3D(anImage),
   myColorMap(aFunctor)
 {
   ui->setupUi(this);
   ui->verticalLayout_5->addWidget(aViewer);
   ui->_horizontalSliderZ->setMinimum(anImage->domain().lowerBound()[2]);
   ui->_horizontalSliderZ->setMaximum(anImage->domain().upperBound()[2]);
   ui->_horizontalSliderZ->setValue(anImage->domain().lowerBound()[2]);
   ui->_horizontalSliderY->setMinimum(anImage->domain().lowerBound()[1]);
   ui->_horizontalSliderY->setMaximum(anImage->domain().upperBound()[1]);
   ui->_horizontalSliderY->setValue(anImage->domain().lowerBound()[1]);
   ui->_horizontalSliderX->setMinimum(anImage->domain().lowerBound()[0]);
   ui->_horizontalSliderX->setMaximum(anImage->domain().upperBound()[0]);
   ui->_horizontalSliderX->setValue(anImage->domain().lowerBound()[0]);
   ui->_zoomXSlider->setMinimum( MIN_ZOOM_FACTOR);
   ui->_zoomXSlider->setMaximum( MAX_ZOOM_FACTOR);
   ui->_zoomXSlider->setValue(INIT_SCALE1_ZOOM_FACTOR);
   ui->_zoomYSlider->setMinimum(MIN_ZOOM_FACTOR);
   ui->_zoomYSlider->setMaximum(MAX_ZOOM_FACTOR);
   ui->_zoomYSlider->setValue(INIT_SCALE1_ZOOM_FACTOR);
   ui->_zoomZSlider->setMinimum(MIN_ZOOM_FACTOR);
   ui->_zoomZSlider->setMaximum(MAX_ZOOM_FACTOR);
   ui->_zoomZSlider->setValue(INIT_SCALE1_ZOOM_FACTOR);
   QObject::connect(ui->_horizontalSliderX, SIGNAL(valueChanged(int)), this, SLOT(updateSliceImageX()));
   QObject::connect(ui->_horizontalSliderY, SIGNAL(valueChanged(int)), this, SLOT(updateSliceImageY()));
   QObject::connect(ui->_horizontalSliderZ, SIGNAL(valueChanged(int)), this, SLOT(updateSliceImageZ()));
   QObject::connect(ui->_zoomXSlider, SIGNAL(valueChanged(int)), this, SLOT(updateZoomImageX()));
   QObject::connect(ui->_zoomYSlider, SIGNAL(valueChanged(int)), this, SLOT(updateZoomImageY()));
   QObject::connect(ui->_zoomZSlider, SIGNAL(valueChanged(int)), this, SLOT(updateZoomImageZ()));
   QObject::connect(ui->_scale1ButtonX, SIGNAL(clicked()), this, SLOT(setScale1_1_ImageX()));
   QObject::connect(ui->_scale1ButtonY, SIGNAL(clicked()), this, SLOT(setScale1_1_ImageY()));
   QObject::connect(ui->_scale1ButtonZ, SIGNAL(clicked()), this, SLOT(setScale1_1_ImageZ()));
   QObject::connect(ui->_CoolButton, SIGNAL(clicked()), this, SLOT(changeCoolColorMap()));
   QObject::connect(ui->_HotButton, SIGNAL(clicked()), this, SLOT(changeHotColorMap()));
   QObject::connect(ui->_HueButton, SIGNAL(clicked()), this, SLOT(changeHueColorMap()));
   QObject::connect(ui->_NormalButton, SIGNAL(clicked()), this, SLOT(changeNormalColorMap()));
 }
References changeCoolColorMap(), changeHotColorMap(), changeHueColorMap(), changeNormalColorMap(), setScale1_1_ImageX(), setScale1_1_ImageY(), setScale1_1_ImageZ(), ui, updateSliceImageX(), updateSliceImageY(), updateSliceImageZ(), updateZoomImageX(), updateZoomImageY(), and updateZoomImageZ().
~MainWindow()
MainWindow::~MainWindow ()
Definition at line 190 of file sliceViewer.cpp.
 {
   delete ui;
 }
References ui.
Member Function Documentation
changeCoolColorMap
void MainWindow::changeCoolColorMap () slot
Definition at line 205 of file sliceViewer.cpp.
{
   myColorMap = MainWindow::GradientMapCool;
   updateAllDisplayedImages();
 }
References GradientMapCool, myColorMap, and updateAllDisplayedImages().
Referenced by MainWindow().
changeHotColorMap
void MainWindow::changeHotColorMap () slot
Definition at line 213 of file sliceViewer.cpp.
{
   myColorMap = MainWindow::GradientMapHot;
   updateAllDisplayedImages();
 }
References GradientMapHot, myColorMap, and updateAllDisplayedImages().
Referenced by MainWindow().
changeHueColorMap
void MainWindow::changeHueColorMap () slot
Definition at line 209 of file sliceViewer.cpp.
{
   myColorMap = MainWindow::HueshadeCM;
   updateAllDisplayedImages();
 }
References HueshadeCM, myColorMap, and updateAllDisplayedImages().
Referenced by MainWindow().
changeNormalColorMap
void MainWindow::changeNormalColorMap () slot
Definition at line 200 of file sliceViewer.cpp.
{
   myColorMap = MainWindow::Id ;
   updateAllDisplayedImages();
 }
References Id, myColorMap, and updateAllDisplayedImages().
Referenced by MainWindow().
setImageProjX()
void MainWindow::setImageProjX (const QPixmap & aPixMap)
Definition at line 219 of file sliceViewer.cpp.
{
   ui->ImageProjX->setPixmap(aPixMap);
 }
References ui.
Referenced by updateSliceImageX(), and updateZoomImageX().
setImageProjY()
void MainWindow::setImageProjY (const QPixmap & aPixMap)
Definition at line 222 of file sliceViewer.cpp.
{
   ui->ImageProjY->setPixmap(aPixMap);
 }
References ui.
Referenced by updateSliceImageY(), and updateZoomImageY().
setImageProjZ()
void MainWindow::setImageProjZ (const QPixmap & aPixMap)
Definition at line 225 of file sliceViewer.cpp.
{
   ui->ImageProjZ->setPixmap(aPixMap);
 }
References ui.
Referenced by updateSliceImageZ(), and updateZoomImageZ().
setScale1_1_ImageX
void MainWindow::setScale1_1_ImageX () slot
Definition at line 243 of file sliceViewer.cpp.
{
   ui->_zoomXSlider->setValue(INIT_SCALE1_ZOOM_FACTOR);
   updateZoomImageX();
 }
References ui, and updateZoomImageX().
Referenced by MainWindow().
setScale1_1_ImageY
void MainWindow::setScale1_1_ImageY () slot
Definition at line 248 of file sliceViewer.cpp.
{
   ui->_zoomYSlider->setValue(INIT_SCALE1_ZOOM_FACTOR);
   updateZoomImageY();
 }
References ui, and updateZoomImageY().
Referenced by MainWindow().
setScale1_1_ImageZ
void MainWindow::setScale1_1_ImageZ () slot
Definition at line 253 of file sliceViewer.cpp.
{
   ui->_zoomZSlider->setValue(INIT_SCALE1_ZOOM_FACTOR);
   updateZoomImageZ();
 }
References ui, and updateZoomImageZ().
Referenced by MainWindow().
updateAllDisplayedImages()
void MainWindow::updateAllDisplayedImages ()
Definition at line 195 of file sliceViewer.cpp.
{
   updateSliceImageX();
   updateSliceImageY();
   updateSliceImageZ();
 }
References updateSliceImageX(), updateSliceImageY(), and updateSliceImageZ().
Referenced by changeCoolColorMap(), changeHotColorMap(), changeHueColorMap(), and changeNormalColorMap().
updateSliceImageX [1/2]
void MainWindow::updateSliceImageX () slot
Definition at line 230 of file sliceViewer.cpp.
{
   updateSliceImageX(ui->_horizontalSliderX->value(), false);
 }
References ui.
Referenced by MainWindow(), and updateAllDisplayedImages().
updateSliceImageX() [2/2]
void MainWindow::updateSliceImageX (int sliceNumber, bool init)
Definition at line 324 of file sliceViewer.cpp.
{
   DGtal::functors::Projector<DGtal::Z2i::Space>  invFunctor; invFunctor.initRemoveOneDim(0);
   DGtal::Z2i::Domain domain2D(invFunctor(myImage3D->domain().lowerBound()),
                               invFunctor(myImage3D->domain().upperBound()));
   DGtal::functors::Projector<DGtal::Z3i::Space> aSliceFunctor(sliceNumber); aSliceFunctor.initAddOneDim(0);
   const functors::Identity identityFunctor{};
   SliceImageAdapter sliceImage ( *myImage3D, domain2D, aSliceFunctor, identityFunctor );
   double gridSize = ((double)INIT_SCALE1_ZOOM_FACTOR)/ui->_zoomXSlider->value();
   QImage anImage = getImage(sliceImage, gridSize,myColorMap);
   setImageProjX(QPixmap::fromImage(anImage));
   Z3i::Point imageOrigin = myImage3D->domain().lowerBound();
   if(init){
     (*myViewer) << DGtal::AddTextureImage2DWithFunctor<SliceImageAdapter, ColorMapFunctor, Z3i::Space, Z3i::KSpace>(sliceImage, myColorMap, DGtal::Viewer3D<Z3i::Space, Z3i::KSpace>::RGBMode);
     (*myViewer) << DGtal::UpdateImagePosition< Space, KSpace >(0, DGtal::Viewer3D<>::xDirection, sliceNumber,
                                                                imageOrigin[1], imageOrigin[2]);
     (*myViewer) << Viewer3D<>::updateDisplay;
   }else{
     (*myViewer) << DGtal::UpdateImageData< SliceImageAdapter, ColorMapFunctor > (0, sliceImage, 0, 0, 0 ,0,  DGtal::Viewer3D<>::xDirection, myColorMap);
     (*myViewer) << DGtal::UpdateImagePosition< Space, KSpace >(0, DGtal::Viewer3D<>::xDirection, sliceNumber, imageOrigin[1],
                                                                imageOrigin[2]);
     (*myViewer).updateList(init);
     (*myViewer).update();
   }
 }
References myColorMap, myImage3D, setImageProjX(), and ui.
updateSliceImageY [1/2]
void MainWindow::updateSliceImageY () slot
Definition at line 234 of file sliceViewer.cpp.
{
   updateSliceImageY(ui->_horizontalSliderY->value(), false);
 }
References ui.
Referenced by MainWindow(), and updateAllDisplayedImages().
updateSliceImageY() [2/2]
void MainWindow::updateSliceImageY (int sliceNumber, bool init)
Definition at line 354 of file sliceViewer.cpp.
{
   DGtal::functors::Projector<DGtal::Z2i::Space>  invFunctor; invFunctor.initRemoveOneDim(1);
   DGtal::Z2i::Domain domain2D(invFunctor(myImage3D->domain().lowerBound()),
                               invFunctor(myImage3D->domain().upperBound()));
   DGtal::functors::Projector<DGtal::Z3i::Space> aSliceFunctor(sliceNumber); aSliceFunctor.initAddOneDim(1);
   const functors::Identity identityFunctor{};
   SliceImageAdapter sliceImage( *myImage3D, domain2D, aSliceFunctor, identityFunctor );
   double gridSize = ((double)INIT_SCALE1_ZOOM_FACTOR)/ui->_zoomYSlider->value();
   QImage anImage = getImage(sliceImage, gridSize, myColorMap);
   setImageProjY(QPixmap::fromImage(anImage));
   Z3i::Point imageOrigin = myImage3D->domain().lowerBound();
   if(init){
     (*myViewer) << DGtal::AddTextureImage2DWithFunctor<SliceImageAdapter, ColorMapFunctor, Z3i::Space, Z3i::KSpace>(sliceImage, myColorMap, DGtal::Viewer3D<Z3i::Space, Z3i::KSpace>::RGBMode);
     (*myViewer) << DGtal::UpdateImagePosition< Space, KSpace >(1, DGtal::Viewer3D<>::yDirection, imageOrigin[0],
                                                                sliceNumber, imageOrigin[2]);
     (*myViewer) << Viewer3D<>::updateDisplay;
   }else{
     (*myViewer) << DGtal::UpdateImageData< SliceImageAdapter, ColorMapFunctor > (1, sliceImage, 0,0, 0, 0,  DGtal::Viewer3D<>::yDirection, myColorMap);
     (*myViewer) << DGtal::UpdateImagePosition< Space, KSpace >(1, DGtal::Viewer3D<>::yDirection, imageOrigin[0],
                                                                sliceNumber, imageOrigin[2]);
     (*myViewer).updateList(init);
     (*myViewer).update();
   }
 }
References myColorMap, myImage3D, setImageProjY(), and ui.
updateSliceImageZ [1/2]
void MainWindow::updateSliceImageZ () slot
Definition at line 238 of file sliceViewer.cpp.
{
   updateSliceImageZ(ui->_horizontalSliderZ->value(), false);
 }
References ui.
Referenced by MainWindow(), and updateAllDisplayedImages().
updateSliceImageZ() [2/2]
void MainWindow::updateSliceImageZ (int sliceNumber, bool init)
Definition at line 383 of file sliceViewer.cpp.
{
   DGtal::functors::Projector<DGtal::Z2i::Space>  invFunctor; invFunctor.initRemoveOneDim(2);
   DGtal::Z2i::Domain domain2D(invFunctor(myImage3D->domain().lowerBound()),
                               invFunctor(myImage3D->domain().upperBound()));
   DGtal::functors::Projector<DGtal::Z3i::Space> aSliceFunctor(sliceNumber); aSliceFunctor.initAddOneDim(2);
   const functors::Identity identityFunctor{};
   SliceImageAdapter sliceImage( *myImage3D, domain2D, aSliceFunctor, identityFunctor );
   double gridSize = (double)INIT_SCALE1_ZOOM_FACTOR/ui->_zoomZSlider->value();
   QImage anImage = getImage(sliceImage, gridSize, myColorMap);
   setImageProjZ(QPixmap::fromImage(anImage));
   Z3i::Point imageOrigin = myImage3D->domain().lowerBound();
   if(init){
     (*myViewer) << DGtal::AddTextureImage2DWithFunctor<SliceImageAdapter, ColorMapFunctor, Z3i::Space, Z3i::KSpace>(sliceImage, myColorMap, DGtal::Viewer3D<Z3i::Space, Z3i::KSpace>::RGBMode);
     (*myViewer) << DGtal::UpdateImagePosition< Space, KSpace >(2, DGtal::Viewer3D<>::zDirection, imageOrigin[0],
                                                                imageOrigin[1], sliceNumber);
     (*myViewer) << Viewer3D<>::updateDisplay;
   }else{
     (*myViewer) << DGtal::UpdateImageData< SliceImageAdapter,ColorMapFunctor > (2, sliceImage, 0,0, 0, 0,  DGtal::Viewer3D<>::zDirection,
                                                                                 myColorMap);
     (*myViewer) << DGtal::UpdateImagePosition< Space, KSpace >(2, DGtal::Viewer3D<>::zDirection, imageOrigin[0],
                                                                imageOrigin[1], sliceNumber);
     (*myViewer).updateList(init);
     (*myViewer).update();
   }
 }
References myColorMap, myImage3D, setImageProjZ(), and ui.
updateZoomImageX [1/2]
void MainWindow::updateZoomImageX () slot
Definition at line 260 of file sliceViewer.cpp.
{
   double gridSize = (double)INIT_SCALE1_ZOOM_FACTOR/ui->_zoomXSlider->value();
   updateZoomImageX(ui->_horizontalSliderX->value(), gridSize );
   QString gridStr = QString::number(gridSize, 'f', 3);
   QString scaleStr = QString::number(1.0/gridSize, 'f', 3);
   ui->_groupBoxX->setTitle(QString("Slice View X: sampling grid size: ").append(gridStr).
                            append(QString(" (zoom x "). append(scaleStr).append(QString(")") )));
 }
References ui.
Referenced by MainWindow(), and setScale1_1_ImageX().
updateZoomImageX() [2/2]
void MainWindow::updateZoomImageX (int sliceNumber, double gridSize)
Definition at line 288 of file sliceViewer.cpp.
{
   DGtal::functors::Projector<DGtal::Z2i::Space>  invFunctor; invFunctor.initRemoveOneDim(0);
   DGtal::Z2i::Domain domain2D(invFunctor(myImage3D->domain().lowerBound()),
                               invFunctor(myImage3D->domain().upperBound()));
   DGtal::functors::Projector<DGtal::Z3i::Space> aSliceFunctor(sliceNumber); aSliceFunctor.initAddOneDim(0);
   const functors::Identity identityFunctor{};
   SliceImageAdapter sliceImage( *myImage3D, domain2D, aSliceFunctor, identityFunctor );
   QImage anImage = getImage(sliceImage, gridSize, myColorMap);
   setImageProjX(QPixmap::fromImage(anImage));
 }
References myColorMap, myImage3D, and setImageProjX().
updateZoomImageY [1/2]
void MainWindow::updateZoomImageY () slot
Definition at line 268 of file sliceViewer.cpp.
{
   double gridSize = (double)INIT_SCALE1_ZOOM_FACTOR/ui->_zoomYSlider->value();
   updateZoomImageY(ui->_horizontalSliderY->value(), gridSize );
   QString gridStr = QString::number(gridSize, 'f', 3);
   QString scaleStr = QString::number(1.0/gridSize, 'f', 3);
   ui->_groupBoxY->setTitle(QString("Slice View Y: sampling grid size: ").append(gridStr).
                            append(QString(" (zoom x "). append(scaleStr).append(QString(")") )));
 }
References ui.
Referenced by MainWindow(), and setScale1_1_ImageY().
updateZoomImageY() [2/2]
void MainWindow::updateZoomImageY (int sliceNumber, double gridSize)
Definition at line 299 of file sliceViewer.cpp.
{
   DGtal::functors::Projector<DGtal::Z2i::Space>  invFunctor; invFunctor.initRemoveOneDim(1);
   DGtal::Z2i::Domain domain2D(invFunctor(myImage3D->domain().lowerBound()),
                               invFunctor(myImage3D->domain().upperBound()));
   DGtal::functors::Projector<DGtal::Z3i::Space> aSliceFunctor(sliceNumber); aSliceFunctor.initAddOneDim(1);
   const functors::Identity identityFunctor{};
   SliceImageAdapter sliceImage( *myImage3D, domain2D, aSliceFunctor, identityFunctor );
   QImage anImage = getImage(sliceImage, gridSize, myColorMap);
   setImageProjY(QPixmap::fromImage(anImage));
 }
References myColorMap, myImage3D, and setImageProjY().
updateZoomImageZ [1/2]
void MainWindow::updateZoomImageZ () slot
Definition at line 277 of file sliceViewer.cpp.
{
   double gridSize = (double)INIT_SCALE1_ZOOM_FACTOR/ui->_zoomZSlider->value();
   updateZoomImageZ(ui->_horizontalSliderZ->value(), gridSize );
   QString gridStr = QString::number(gridSize, 'f', 3);
   QString scaleStr = QString::number(1.0/gridSize, 'f', 3);
   ui->_groupBoxZ->setTitle(QString("Slice View Z: sampling grid size: ").append(gridStr).
                            append(QString(" (zoom x "). append(scaleStr).append(QString(")") )));
 }
References ui.
Referenced by MainWindow(), and setScale1_1_ImageZ().
updateZoomImageZ() [2/2]
void MainWindow::updateZoomImageZ (int sliceNumber, double gridSize)
Definition at line 312 of file sliceViewer.cpp.
{
   DGtal::functors::Projector<DGtal::Z2i::Space>  invFunctor; invFunctor.initRemoveOneDim(2);
   DGtal::Z2i::Domain domain2D(invFunctor(myImage3D->domain().lowerBound()),
                               invFunctor(myImage3D->domain().upperBound()));
   DGtal::functors::Projector<DGtal::Z3i::Space> aSliceFunctor(sliceNumber); aSliceFunctor.initAddOneDim(2);
   const functors::Identity identityFunctor{};
   SliceImageAdapter sliceImage( *myImage3D, domain2D, aSliceFunctor, identityFunctor );
   QImage anImage = getImage(sliceImage, gridSize, myColorMap );
   setImageProjZ(QPixmap::fromImage(anImage));
 }
References myColorMap, myImage3D, and setImageProjZ().
Field Documentation
myColorMap
ColorMapFunctor MainWindow::myColorMap private
Definition at line 145 of file sliceViewer.h.
Referenced by changeCoolColorMap(), changeHotColorMap(), changeHueColorMap(), changeNormalColorMap(), updateSliceImageX(), updateSliceImageY(), updateSliceImageZ(), updateZoomImageX(), updateZoomImageY(), and updateZoomImageZ().
myImage3D
Image3D* MainWindow::myImage3D private
Definition at line 144 of file sliceViewer.h.
Referenced by updateSliceImageX(), updateSliceImageY(), updateSliceImageZ(), updateZoomImageX(), updateZoomImageY(), and updateZoomImageZ().
myViewer
DGtal::Viewer3D* MainWindow::myViewer private
Definition at line 143 of file sliceViewer.h.
ui
Ui::MainWindow* MainWindow::ui private
Definition at line 142 of file sliceViewer.h.
Referenced by MainWindow(), setImageProjX(), setImageProjY(), setImageProjZ(), setScale1_1_ImageX(), setScale1_1_ImageY(), setScale1_1_ImageZ(), updateSliceImageX(), updateSliceImageY(), updateSliceImageZ(), updateZoomImageX(), updateZoomImageY(), updateZoomImageZ(), and ~MainWindow().
The documentation for this class was generated from the following files:
sliceViewer.h
sliceViewer.cpp