DGtal: DGtal::LabelledMap< TData, L, TWord, N, M >::ValueCompare Class Reference
DGtal::LabelledMap< TData, L, TWord, N, M >::ValueCompare Class Reference
#include <DGtal/base/LabelledMap.h>
Public Member Functions
ValueCompare ()
bool operator() (const Value &v1, const Value &v2) const
Detailed Description
template<typename TData, unsigned int L, typename TWord, unsigned int N, unsigned int M>
class DGtal::LabelledMap< TData, L, TWord, N, M >::ValueCompare
Value comparator class. Always natural ordering between keys.
Definition at line 741 of file LabelledMap.h.
Constructor & Destructor Documentation
ValueCompare()
template<typename TData, unsigned int L, typename TWord, unsigned int N, unsigned int M> DGtal::LabelledMap< TData, L, TWord, N, M >::ValueCompare::ValueCompare () inline
Definition at line 743 of file LabelledMap.h.
 {}
Member Function Documentation
operator()()
template<typename TData, unsigned int L, typename TWord, unsigned int N, unsigned int M> bool DGtal::LabelledMap< TData, L, TWord, N, M >::ValueCompare::operator() (const Value & v1, const Value & v2) const inline
Definition at line 744 of file LabelledMap.h.
References DGtal::LabelledMap< TData, L, TWord, N, M >::begin(), DGtal::LabelledMap< TData, L, TWord, N, M >::blockAt(), DGtal::LabelledMap< TData, L, TWord, N, M >::blockBegin(), DGtal::LabelledMap< TData, L, TWord, N, M >::blockClear(), DGtal::LabelledMap< TData, L, TWord, N, M >::blockEnd(), DGtal::LabelledMap< TData, L, TWord, N, M >::blockErase(), DGtal::LabelledMap< TData, L, TWord, N, M >::blockInsert(), DGtal::LabelledMap< TData, L, TWord, N, M >::capacity(), DGtal::LabelledMap< TData, L, TWord, N, M >::clear(), DGtal::LabelledMap< TData, L, TWord, N, M >::count(), DGtal::LabelledMap< TData, L, TWord, N, M >::empty(), DGtal::LabelledMap< TData, L, TWord, N, M >::end(), DGtal::LabelledMap< TData, L, TWord, N, M >::equal_range(), DGtal::LabelledMap< TData, L, TWord, N, M >::erase(), DGtal::LabelledMap< TData, L, TWord, N, M >::fastAt(), DGtal::LabelledMap< TData, L, TWord, N, M >::find(), DGtal::LabelledMap< TData, L, TWord, N, M >::insert(), DGtal::LabelledMap< TData, L, TWord, N, M >::isValid(), DGtal::LabelledMap< TData, L, TWord, N, M >::key_comp(), DGtal::LabelledMap< TData, L, TWord, N, M >::LabelledMap(), DGtal::LabelledMap< TData, L, TWord, N, M >::labels(), DGtal::LabelledMap< TData, L, TWord, N, M >::lower_bound(), DGtal::LabelledMap< TData, L, TWord, N, M >::max_size(), DGtal::LabelledMap< TData, L, TWord, N, M >::operator=(), DGtal::LabelledMap< TData, L, TWord, N, M >::operator[](), DGtal::LabelledMap< TData, L, TWord, N, M >::selfDisplay(), DGtal::LabelledMap< TData, L, TWord, N, M >::size(), DGtal::LabelledMap< TData, L, TWord, N, M >::swap(), DGtal::LabelledMap< TData, L, TWord, N, M >::upper_bound(), DGtal::LabelledMap< TData, L, TWord, N, M >::value_comp(), and DGtal::LabelledMap< TData, L, TWord, N, M >::~LabelledMap().
       {
         return v1.first < v2.first;
       }
The documentation for this class was generated from the following file:
LabelledMap.h