DGtal: DGtal::Flower2D< TSpace > Class Template Reference
DGtal::Flower2D< TSpace > Class Template Reference
#include <DGtal/shapes/parametric/Flower2D.h>
Public Types
typedef TSpace Space
typedef Space::Point Point
typedef Space::RealPoint RealPoint2D
typedef Space::RealVector RealVector2D
Public Types inherited from DGtal::StarShaped2D< TSpace >
typedef TSpace Space
typedef Space::Point Point
typedef Space::RealPoint RealPoint
Public Member Functions
~Flower2D ()
Flower2D (const double x0, const double y0, const double r, const double smallr, const unsigned int k, const double phi)
Flower2D (const RealPoint2D &aPoint, const double r, const double smallr, const unsigned int k, const double phi)
Flower2D (const Point &aPoint, const double r, const double smallr, const unsigned int k, const double phi)
RealPoint2D getLowerBound () const
RealPoint2D getUpperBound () const
RealPoint2D center () const
double parameter (const RealPoint2D &p) const
RealPoint2D x (const double t) const
RealVector2D xp (const double t) const
RealVector2D xpp (const double t) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Public Member Functions inherited from DGtal::StarShaped2D< TSpace >
StarShaped2D ()
~StarShaped2D ()
virtual RealPoint interiorPoint () const
Orientation orientation (const RealPoint &p) const
RealPoint tangent (double t) const
RealPoint normal (double t) const
double curvature (double t) const
double arclength (double t1, double t2, unsigned int nb) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Protected Member Functions
Flower2D ()
Private Member Functions
Flower2D & operator= (const Flower2D &other)
Private Attributes
RealPoint2D myCenter
double myRadius
double myVarRadius
unsigned int myK
double myPhi
Detailed Description
template<typename TSpace>
class DGtal::Flower2D< TSpace >
Aim: Model of the concept StarShaped represents any flower with k-petals in the plane.
Description of template class 'Flower2D'
NB: A backport from ImaGene.
Examples:
geometry/curves/estimation/exampleCurvature.cpp, and topology/digitalSetToCubicalComplexes2D.cpp.
Definition at line 64 of file Flower2D.h.
Member Typedef Documentation
Point
template<typename TSpace> typedef Space::Point DGtal::Flower2D< TSpace >::Point
Definition at line 70 of file Flower2D.h.
RealPoint2D
template<typename TSpace> typedef Space::RealPoint DGtal::Flower2D< TSpace >::RealPoint2D
Definition at line 71 of file Flower2D.h.
RealVector2D
template<typename TSpace> typedef Space::RealVector DGtal::Flower2D< TSpace >::RealVector2D
Definition at line 72 of file Flower2D.h.
Space
template<typename TSpace> typedef TSpace DGtal::Flower2D< TSpace >::Space
Definition at line 69 of file Flower2D.h.
Constructor & Destructor Documentation
~Flower2D()
template<typename TSpace> DGtal::Flower2D< TSpace >::~Flower2D ()
Destructor.
Flower2D() [1/4]
template<typename TSpace> DGtal::Flower2D< TSpace >::Flower2D (const double x0, const double y0, const double r, const double smallr, const unsigned int k, const double phi)
Constructor.
Parameters
x0 the x-coordinate of the flower center.
y0 the y-coordinate of the flower center.
r the radius of the flower.
smallr the variable small radius of the flower.
k the number of flower extremeties.
phi the phase of the flower (in radian).
Flower2D() [2/4]
template<typename TSpace> DGtal::Flower2D< TSpace >::Flower2D (const RealPoint2D & aPoint, const double r, const double smallr, const unsigned int k, const double phi)
Constructor.
Parameters
aPoint the flower center.
r the radius of the flower.
smallr the variable small radius of the flower.
k the number of flower extremeties.
phi the phase of the flower (in radian).
Flower2D() [3/4]
template<typename TSpace> DGtal::Flower2D< TSpace >::Flower2D (const Point & aPoint, const double r, const double smallr, const unsigned int k, const double phi)
Constructor.
Parameters
aPoint the flower center.
r the radius of the flower.
smallr the variable small radius of the flower.
k the number of flower extremeties.
phi the phase of the flower (in radian).
Flower2D() [4/4]
template<typename TSpace> DGtal::Flower2D< TSpace >::Flower2D () protected
Constructor. Forbidden by default (protected to avoid g++ warnings).
Member Function Documentation
center()
template<typename TSpace> RealPoint2D DGtal::Flower2D< TSpace >::center () const inline virtual
Returns
the center of the star-shaped object.
Implements DGtal::StarShaped2D< TSpace >.
Definition at line 146 of file Flower2D.h.
References DGtal::Flower2D< TSpace >::myCenter, DGtal::Flower2D< TSpace >::parameter(), DGtal::Flower2D< TSpace >::x(), DGtal::Flower2D< TSpace >::xp(), and DGtal::Flower2D< TSpace >::xpp().
     {
       return myCenter;
     }
getLowerBound()
template<typename TSpace> RealPoint2D DGtal::Flower2D< TSpace >::getLowerBound () const inline virtual
Returns
the lower bound of the shape bounding box.
Implements DGtal::StarShaped2D< TSpace >.
Definition at line 129 of file Flower2D.h.
References DGtal::Flower2D< TSpace >::myCenter, DGtal::Flower2D< TSpace >::myRadius, and DGtal::Flower2D< TSpace >::myVarRadius.
     {
       return RealPoint2D(myCenter[0] - myRadius - myVarRadius, myCenter[1] - myRadius - myVarRadius);
     }
getUpperBound()
template<typename TSpace> RealPoint2D DGtal::Flower2D< TSpace >::getUpperBound () const inline virtual
Returns
the upper bound of the shape bounding box.
Implements DGtal::StarShaped2D< TSpace >.
Definition at line 138 of file Flower2D.h.
References DGtal::Flower2D< TSpace >::myCenter, DGtal::Flower2D< TSpace >::myRadius, and DGtal::Flower2D< TSpace >::myVarRadius.
     {
       return RealPoint2D(myCenter[0] + myRadius + myVarRadius, myCenter[1] + myRadius + myVarRadius);
     }
isValid()
template<typename TSpace> bool DGtal::Flower2D< TSpace >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
operator=()
template<typename TSpace> Flower2D& DGtal::Flower2D< TSpace >::operator= (const Flower2D< TSpace > & other) private
Copy constructor.
Parameters
other the object to clone. Forbidden by default. Assignment.
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
parameter()
template<typename TSpace> double DGtal::Flower2D< TSpace >::parameter (const RealPoint2D & p) const virtual
Parameters
p any point in the plane.
Returns
the angle parameter between 0 and 2*Pi corresponding to this point for the shape.
Implements DGtal::StarShaped2D< TSpace >.
Referenced by DGtal::Flower2D< TSpace >::center().
selfDisplay()
template<typename TSpace> void DGtal::Flower2D< TSpace >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
x()
template<typename TSpace> RealPoint2D DGtal::Flower2D< TSpace >::x (const double t) const virtual
Parameters
t any angle between 0 and 2*Pi.
Returns
the vector (x(t),y(t)) which is the position on the shape boundary.
Implements DGtal::StarShaped2D< TSpace >.
Referenced by DGtal::Flower2D< TSpace >::center().
xp()
template<typename TSpace> RealVector2D DGtal::Flower2D< TSpace >::xp (const double t) const virtual
Parameters
t any angle between 0 and 2*Pi.
Returns
the vector (x'(t),y'(t)) which is the tangent to the shape boundary.
Implements DGtal::StarShaped2D< TSpace >.
Referenced by DGtal::Flower2D< TSpace >::center().
xpp()
template<typename TSpace> RealVector2D DGtal::Flower2D< TSpace >::xpp (const double t) const virtual
Parameters
t any angle between 0 and 2*Pi.
Returns
the vector (x''(t),y''(t)).
Implements DGtal::StarShaped2D< TSpace >.
Referenced by DGtal::Flower2D< TSpace >::center().
Field Documentation
myCenter
template<typename TSpace> RealPoint2D DGtal::Flower2D< TSpace >::myCenter private
Center of the flower.
Definition at line 190 of file Flower2D.h.
Referenced by DGtal::Flower2D< TSpace >::center(), DGtal::Flower2D< TSpace >::getLowerBound(), and DGtal::Flower2D< TSpace >::getUpperBound().
myK
template<typename TSpace> unsigned int DGtal::Flower2D< TSpace >::myK private
the number of flower extremeties.
Definition at line 205 of file Flower2D.h.
myPhi
template<typename TSpace> double DGtal::Flower2D< TSpace >::myPhi private
the phase of the flower (in radian).
Definition at line 210 of file Flower2D.h.
myRadius
template<typename TSpace> double DGtal::Flower2D< TSpace >::myRadius private
Radius of the flower.
Definition at line 195 of file Flower2D.h.
Referenced by DGtal::Flower2D< TSpace >::getLowerBound(), and DGtal::Flower2D< TSpace >::getUpperBound().
myVarRadius
template<typename TSpace> double DGtal::Flower2D< TSpace >::myVarRadius private
the variable small radius of the flower.
Definition at line 200 of file Flower2D.h.
Referenced by DGtal::Flower2D< TSpace >::getLowerBound(), and DGtal::Flower2D< TSpace >::getUpperBound().
The documentation for this class was generated from the following file:
Flower2D.h