DGtal: DerivativeTester< Calculus, -1 > Struct Template Reference
DerivativeTester< Calculus, -1 > Struct Template Reference
#include </Users/davidcoeurjolly/Sources/DGtal/tests/dec/DECCommon.h>
Static Public Member Functions
static bool test (const Calculus &)
Detailed Description
template<typename Calculus>
struct DerivativeTester< Calculus, -1 >
Definition at line 254 of file DECCommon.h.
Member Function Documentation
test()
template<typename Calculus > static bool DerivativeTester< Calculus, -1 >::test (const Calculus &) inline static
Definition at line 256 of file DECCommon.h.
References DGtal::HyperRectDomain< TSpace >::begin(), DGtal::Trace::beginBlock(), HodgeTester< Calculus, order >::BOOST_STATIC_ASSERT(), domain(), DGtal::DUAL, DGtal::HyperRectDomain< TSpace >::end(), DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::PRIMAL, DGtal::HyperRectDomain< TSpace >::size(), HodgeTester< Calculus, order >::test(), and DGtal::trace.
     {
         return true;
     }
The documentation for this struct was generated from the following file:
DECCommon.h