DGtal: DGtal::Viewer3D< Space, KSpace >::TextureImage Struct Reference
DGtal::Viewer3D< Space, KSpace >::TextureImage Struct Reference
#include <DGtal/io/viewers/Viewer3D.h>
Public Member Functions
~TextureImage ()
TextureImage (const TextureImage &img)
template<typename TImageType , typename TFunctor >
TextureImage (const TImageType &image, const TFunctor &aFunctor, ImageDirection normalDir=zDirection, double xBottomLeft=0.0, double yBottomLeft=0.0, double zBottomLeft=0.0, TextureMode aMode=GrayScaleMode)
void updateImageOrientation (ImageDirection normalDir, double xBottomLeft, double yBottomLeft, double zBottomLeft)
void updateImage3DEmbedding (RealPoint aPoint1, RealPoint aPoint2, RealPoint aPoint3, RealPoint aPoint4)
template<typename TImageType , typename TFunctor >
void updateImageDataAndParam (const TImageType &image, const TFunctor &aFunctor, double xTranslation=0.0, double yTranslation=0.0, double zTranslation=0.0)
std::string className () const
Data Fields
RealPoint point1
RealPoint point2
RealPoint point3
RealPoint point4
ImageDirection myDirection
unsigned int myImageWidth
unsigned int myImageHeight
unsigned int * myTabImage
bool myDrawDomain
unsigned int myIndexDomain
TextureMode myMode
Private Member Functions
TextureImage ()
Detailed Description
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>>
struct DGtal::Viewer3D< Space, KSpace >::TextureImage
Used to display an image as a textured quad image.
Definition at line 406 of file Viewer3D.h.
Constructor & Destructor Documentation
~TextureImage()
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> DGtal::Viewer3D< Space, KSpace >::TextureImage::~TextureImage () inline
the mode of representation of the image
Destructor
Definition at line 428 of file Viewer3D.h.
       {
         delete [] myTabImage;
       };
TextureImage() [1/3]
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> DGtal::Viewer3D< Space, KSpace >::TextureImage::TextureImage (const TextureImage & img) inline
Copy constructor (needed due to myTabImage)
Parameters
img the image
Definition at line 437 of file Viewer3D.h.
References DGtal::Viewer3D< Space, KSpace >::TextureImage::myImageHeight, DGtal::Viewer3D< Space, KSpace >::TextureImage::myImageWidth, and DGtal::Viewer3D< Space, KSpace >::TextureImage::myTabImage.
                                             : point1(img.point1), point2(img.point2),
                 point3(img.point3), point4(img.point4),
                 myDirection(img.myDirection), myImageWidth(img.myImageWidth),
                 myImageHeight(img.myImageHeight),
                 myTabImage(img.myTabImage),
                 myDrawDomain(img.myDrawDomain),
                 myIndexDomain(img.myIndexDomain),
                 myMode(img.myMode)
       {
         if(img.myImageHeight>0 && img.myImageWidth>0)
           {
             myTabImage = new unsigned int [img.myImageWidth*img.myImageHeight];
             for(unsigned int i=0; i<img.myImageWidth*img.myImageHeight; i++)
               {
                 myTabImage[i] = img.myTabImage[i];
               }
           }else
           {
             myTabImage=img.myTabImage;
           }
       };
TextureImage() [2/3]
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> template<typename TImageType , typename TFunctor > DGtal::Viewer3D< Space, KSpace >::TextureImage::TextureImage (const TImageType & image, const TFunctor & aFunctor, ImageDirection normalDir = zDirection, double xBottomLeft = 0.0, double yBottomLeft = 0.0, double zBottomLeft = 0.0, TextureMode aMode = GrayScaleMode) inline
Constructor that fills image parameters from std image (image buffer, dimensions, vertex coordinates, orientation)
Template Parameters
TImageType the type of the image given for the constructor (should follow the CConstImage concept).
TFunctor the functor type (should follow the CUnaryFunctor concept with image value type as input type and unsigned int as output type).
Parameters
image the source image.
aFunctor a functor to transform input values to the output displayed values.
normalDir the direction of normal vector of the image plane (xDirection, yDirection or zDirection (default)) .
xBottomLeft the x coordinate of bottom left image point (default 0).
yBottomLeft the x coordinate of bottom left image point (default 0).
zBottomLeft the x coordinate of bottom left image point (default 0).
aMode the mode of representation (default GrayScaleMode).
Definition at line 483 of file Viewer3D.h.
References DGtal::Viewer3D< Space, KSpace >::BOOST_CONCEPT_ASSERT().
       {
         BOOST_CONCEPT_ASSERT(( concepts::CConstImage < TImageType > ));
         BOOST_CONCEPT_ASSERT(( concepts::CUnaryFunctor<TFunctor, typename TImageType::Value, unsigned int> )) ;
         myDrawDomain=false;
         myDirection=normalDir;
         myImageWidth = (image.domain().upperBound())[0]-(image.domain().lowerBound())[0]+1;
         myImageHeight = (image.domain().upperBound())[1]-(image.domain().lowerBound())[1]+1;
         myTabImage = new unsigned int [myImageWidth*myImageHeight];
         updateImageOrientation(normalDir, xBottomLeft, yBottomLeft, zBottomLeft);
         myMode=aMode;
         updateImageDataAndParam(image, aFunctor);
       }
TextureImage() [3/3]
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> DGtal::Viewer3D< Space, KSpace >::TextureImage::TextureImage () inline private
default constructor TextureImage
Definition at line 579 of file Viewer3D.h.
References DGtal::Viewer3D< Space, KSpace >::addImage2DDomainD3D(), DGtal::Viewer3D< Space, KSpace >::addTextureImage(), DGtal::Viewer3D< Space, KSpace >::compute2DDomainLineRepresentation(), DGtal::Viewer3D< Space, KSpace >::getCurrentDomainNumber(), DGtal::Viewer3D< Space, KSpace >::getCurrentGLImageNumber(), DGtal::Viewer3D< Space, KSpace >::glDrawGLBall(), DGtal::Viewer3D< Space, KSpace >::isValid(), DGtal::Viewer3D< Space, KSpace >::keyPressEvent(), DGtal::Viewer3D< Space, KSpace >::mouseMoveEvent(), DGtal::Viewer3D< Space, KSpace >::mousePressEvent(), DGtal::Viewer3D< Space, KSpace >::mouseReleaseEvent(), DGtal::Viewer3D< Space, KSpace >::operator<<(), DGtal::Viewer3D< Space, KSpace >::paintGL(), DGtal::Color::Red, DGtal::Viewer3D< Space, KSpace >::rotateDomain(), DGtal::Viewer3D< Space, KSpace >::rotateLineD3D(), DGtal::Viewer3D< Space, KSpace >::selfDisplay(), DGtal::Viewer3D< Space, KSpace >::show(), DGtal::Viewer3D< Space, KSpace >::sortPolygonFromCamera(), DGtal::Viewer3D< Space, KSpace >::sortQuadFromCamera(), DGtal::Viewer3D< Space, KSpace >::sortSurfelFromCamera(), DGtal::Viewer3D< Space, KSpace >::sortTriangleFromCamera(), DGtal::Viewer3D< Space, KSpace >::translateAn2DDomain(), DGtal::Viewer3D< Space, KSpace >::updateAn2DDomainOrientation(), DGtal::Viewer3D< Space, KSpace >::updateEmbeddingTextureImage(), DGtal::Viewer3D< Space, KSpace >::updateList(), DGtal::Viewer3D< Space, KSpace >::updateOrientationTextureImage(), DGtal::Viewer3D< Space, KSpace >::updateTextureImage(), and DGtal::Viewer3D< Space, KSpace >::zDirection.
       {};
Member Function Documentation
className()
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> std::string DGtal::Viewer3D< Space, KSpace >::TextureImage::className () const
return the class name to implement the CDrawableWithViewer3D concept.
updateImage3DEmbedding()
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> void DGtal::Viewer3D< Space, KSpace >::TextureImage::updateImage3DEmbedding (RealPoint aPoint1, RealPoint aPoint2, RealPoint aPoint3, RealPoint aPoint4) inline
Update the embedding of the image by updating the image 3D vertex.
Parameters
aPoint1 the first image point (lower bound point)
aPoint2 the second image point (upper bound point in first dimension and lower in the second dimentsion)
aPoint3 the third image point (upper bound point in first second dimentsion)
aPoint4 the fourth image point (lower bound point in first dimension and upper in the second dimentsion)
Definition at line 521 of file Viewer3D.h.
References DGtal::Viewer3D< Space, KSpace >::undefDirection.
       {
         point1 = aPoint1;  point2 = aPoint2; point3 = aPoint3;   point4 = aPoint4;
         myDirection=undefDirection;
       }
updateImageDataAndParam()
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> template<typename TImageType , typename TFunctor > void DGtal::Viewer3D< Space, KSpace >::TextureImage::updateImageDataAndParam (const TImageType & image, const TFunctor & aFunctor, double xTranslation = 0.0, double yTranslation = 0.0, double zTranslation = 0.0) inline
Update the image parameters from std image (image buffer, vertex coordinates) The new image should be with same dimension than the original.
Template Parameters
TImageType the type of the image given for the constructor (should follow the CConstImage concept).
TFunctor the functor type (should follow the CUnaryFunctor concept with image value type as input type and unsigned int as output type).
Parameters
image the source image.
aFunctor a functor to transform input values to the output displayed values.
xTranslation the image translation in the x direction (default 0).
yTranslation the image translation in the y direction (default 0).
zTranslation the image translation in the z direction (default 0).
Definition at line 547 of file Viewer3D.h.
References DGtal::Viewer3D< Space, KSpace >::BOOST_CONCEPT_ASSERT(), and image().
       {
         BOOST_CONCEPT_ASSERT(( concepts::CConstImage < TImageType > ));
         BOOST_CONCEPT_ASSERT(( concepts::CUnaryFunctor<TFunctor, typename TImageType::Value, unsigned int> )) ;
         assert ( (image.domain().upperBound())[0]-(image.domain().lowerBound())[0]+1== static_cast<int>(myImageWidth) &&
                  (image.domain().upperBound())[1]-(image.domain().lowerBound())[1]+1== static_cast<int>(myImageHeight));
         point1[0] += xTranslation; point1[1] += yTranslation; point1[2] += zTranslation;
         point2[0] += xTranslation; point2[1] +=yTranslation; point2[2] += zTranslation;
         point3[0] += xTranslation; point3[1] += yTranslation; point3[2] += zTranslation;
         point4[0] += xTranslation; point4[1] += yTranslation; point4[2] += zTranslation;
         unsigned int pos=0;
         for(typename TImageType::Domain::ConstIterator it = image.domain().begin(), itend=image.domain().end();
             it!=itend; ++it)
           {
             myTabImage[pos]= aFunctor(image(*it));
             pos++;
           }
       }
updateImageOrientation()
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> void DGtal::Viewer3D< Space, KSpace >::TextureImage::updateImageOrientation (ImageDirection normalDir, double xBottomLeft, double yBottomLeft, double zBottomLeft)
Update the image direction from a specific normal direction (Viewer3D::xDirection, Viewer3D::yDirection or Viewer3D::zDirection) and image position from the botton left point.
Parameters
normalDir give a predifined normal orientation can be (Viewer3D::xDirection, Viewer3D::yDirection or Viewer3D::zDirection)
xBottomLeft the x coordinate of bottom left image point.
yBottomLeft the x coordinate of bottom left image point.
zBottomLeft the x coordinate of bottom left image point.
Field Documentation
myDirection
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> ImageDirection DGtal::Viewer3D< Space, KSpace >::TextureImage::myDirection
Definition at line 414 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< Space, KSpace >::GLTextureImage::GLTextureImage().
myDrawDomain
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> bool DGtal::Viewer3D< Space, KSpace >::TextureImage::myDrawDomain
for each pixel of the image, color or height ?
Definition at line 421 of file Viewer3D.h.
myImageHeight
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> unsigned int DGtal::Viewer3D< Space, KSpace >::TextureImage::myImageHeight
the width of the image
Definition at line 417 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< Space, KSpace >::GLTextureImage::GLTextureImage(), and DGtal::Viewer3D< Space, KSpace >::TextureImage::TextureImage().
myImageWidth
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> unsigned int DGtal::Viewer3D< Space, KSpace >::TextureImage::myImageWidth
direction of the image (x, y or z axe)
Definition at line 416 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< Space, KSpace >::GLTextureImage::GLTextureImage(), and DGtal::Viewer3D< Space, KSpace >::TextureImage::TextureImage().
myIndexDomain
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> unsigned int DGtal::Viewer3D< Space, KSpace >::TextureImage::myIndexDomain
true if the draw have a domain
Definition at line 422 of file Viewer3D.h.
myMode
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> TextureMode DGtal::Viewer3D< Space, KSpace >::TextureImage::myMode
index of the image domain if exist
Definition at line 423 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< Space, KSpace >::GLTextureImage::GLTextureImage().
myTabImage
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> unsigned int* DGtal::Viewer3D< Space, KSpace >::TextureImage::myTabImage
the height of the image
Definition at line 419 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< Space, KSpace >::GLTextureImage::GLTextureImage(), and DGtal::Viewer3D< Space, KSpace >::TextureImage::TextureImage().
point1
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> RealPoint DGtal::Viewer3D< Space, KSpace >::TextureImage::point1
Definition at line 409 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< Space, KSpace >::GLTextureImage::GLTextureImage().
point2
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> RealPoint DGtal::Viewer3D< Space, KSpace >::TextureImage::point2
Definition at line 410 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< Space, KSpace >::GLTextureImage::GLTextureImage().
point3
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> RealPoint DGtal::Viewer3D< Space, KSpace >::TextureImage::point3
Definition at line 411 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< Space, KSpace >::GLTextureImage::GLTextureImage().
point4
template<typename Space = SpaceND<3>, typename KSpace = KhalimskySpaceND<3>> RealPoint DGtal::Viewer3D< Space, KSpace >::TextureImage::point4
Definition at line 412 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< Space, KSpace >::GLTextureImage::GLTextureImage().
The documentation for this struct was generated from the following file:
Viewer3D.h