DGtal: HodgeTester< Calculus, -1 > Struct Template Reference
HodgeTester< Calculus, -1 > Struct Template Reference
#include </Users/davidcoeurjolly/Sources/DGtal/tests/dec/DECCommon.h>
Static Public Member Functions
static bool test (const Calculus &calculus)
Detailed Description
template<typename Calculus>
struct HodgeTester< Calculus, -1 >
Definition at line 109 of file DECCommon.h.
Member Function Documentation
test()
template<typename Calculus > static bool HodgeTester< Calculus, -1 >::test (const Calculus & calculus) inline static
Definition at line 111 of file DECCommon.h.
References DGtal::HyperRectDomain< TSpace >::begin(), DGtal::Trace::beginBlock(), DGtal::DiscreteExteriorCalculusFactory< TLinearAlgebraBackend, TInteger >::createFromDigitalSet(), domain(), DGtal::DUAL, DGtal::HyperRectDomain< TSpace >::end(), DGtal::Trace::endBlock(), index(), DGtal::Trace::info(), DGtal::PRIMAL, DGtal::HyperRectDomain< TSpace >::size(), HodgeTester< Calculus, order >::test(), and DGtal::trace.
   {
     boost::ignore_unused_variable_warning( calculus );
     return true;
   }
The documentation for this struct was generated from the following file:
DECCommon.h