DGtal: DGtal::SimpleConstRange< TConstIterator > Class Template Reference
DGtal::SimpleConstRange< TConstIterator > Class Template Reference
Aim: model of CConstRange that adapts any range of elements bounded by two iterators [itb, ite) and provides services to (circularly)iterate over it (in a read-only manner).
#include <DGtal/base/SimpleConstRange.h>
Public Types
typedef TConstIterator ConstIterator
typedef std::reverse_iterator< ConstIterator > ConstReverseIterator
typedef Circulator< ConstIterator > ConstCirculator
typedef std::reverse_iterator< ConstCirculator > ConstReverseCirculator
Public Member Functions
SimpleConstRange (const TConstIterator &itb, const TConstIterator &ite)
SimpleConstRange (const SimpleConstRange &other)
SimpleConstRange & operator= (const SimpleConstRange &other)
~SimpleConstRange ()
bool isValid () const
void selfDisplay (std::ostream &out) const
std::string className () const
ConstIterator begin () const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rend () const
ConstCirculator c () const
ConstReverseCirculator rc () const
Private Member Functions
BOOST_CONCEPT_ASSERT ((boost::BidirectionalIterator< TConstIterator >))
Private Attributes
TConstIterator myBegin
TConstIterator myEnd
Detailed Description
template<typename TConstIterator>
class DGtal::SimpleConstRange< TConstIterator >
Aim: model of CConstRange that adapts any range of elements bounded by two iterators [itb, ite) and provides services to (circularly)iterate over it (in a read-only manner).
Template Parameters
TConstIterator the type of the iterator to adapt (at least bidirectional)
See also
ConstRangeAdapter
Definition at line 72 of file SimpleConstRange.h.
Member Typedef Documentation
ConstCirculator
template<typename TConstIterator > typedef Circulator<ConstIterator> DGtal::SimpleConstRange< TConstIterator >::ConstCirculator
Definition at line 83 of file SimpleConstRange.h.
ConstIterator
template<typename TConstIterator > typedef TConstIterator DGtal::SimpleConstRange< TConstIterator >::ConstIterator
Definition at line 80 of file SimpleConstRange.h.
ConstReverseCirculator
template<typename TConstIterator > typedef std::reverse_iterator<ConstCirculator> DGtal::SimpleConstRange< TConstIterator >::ConstReverseCirculator
Definition at line 84 of file SimpleConstRange.h.
ConstReverseIterator
template<typename TConstIterator > typedef std::reverse_iterator<ConstIterator> DGtal::SimpleConstRange< TConstIterator >::ConstReverseIterator
Definition at line 81 of file SimpleConstRange.h.
Constructor & Destructor Documentation
SimpleConstRange() [1/2]
template<typename TConstIterator > DGtal::SimpleConstRange< TConstIterator >::SimpleConstRange (const TConstIterator & itb, const TConstIterator & ite) inline
Standard constructor from two iterators and one functor.
Parameters
itb begin iterator.
ite end iterator.
Definition at line 95 of file SimpleConstRange.h.
       : myBegin(itb), myEnd(ite) {}
SimpleConstRange() [2/2]
template<typename TConstIterator > DGtal::SimpleConstRange< TConstIterator >::SimpleConstRange (const SimpleConstRange< TConstIterator > & other) inline
Copy constructor.
Parameters
other the iterator to clone.
Definition at line 102 of file SimpleConstRange.h.
       : myBegin(other.myBegin), myEnd(other.myEnd) {}
~SimpleConstRange()
template<typename TConstIterator > DGtal::SimpleConstRange< TConstIterator >::~SimpleConstRange () inline
Destructor. Does nothing.
Definition at line 123 of file SimpleConstRange.h.
 {}
Member Function Documentation
begin()
template<typename TConstIterator > ConstIterator DGtal::SimpleConstRange< TConstIterator >::begin () const inline
Iterator service.
Returns
begin iterator
Definition at line 172 of file SimpleConstRange.h.
{
       return ConstIterator( myBegin );
     }
References DGtal::SimpleConstRange< TConstIterator >::myBegin.
Referenced by DGtal::SimpleConstRange< TConstIterator >::c(), and DGtal::SimpleConstRange< TConstIterator >::rend().
BOOST_CONCEPT_ASSERT()
template<typename TConstIterator > DGtal::SimpleConstRange< TConstIterator >::BOOST_CONCEPT_ASSERT ((boost::BidirectionalIterator< TConstIterator >)) private
c()
template<typename TConstIterator > ConstCirculator DGtal::SimpleConstRange< TConstIterator >::c () const inline
Circulator service.
Returns
a circulator
Definition at line 204 of file SimpleConstRange.h.
{
       return ConstCirculator( this->begin(), this->begin(), this->end() );
     }
References DGtal::SimpleConstRange< TConstIterator >::begin(), and DGtal::SimpleConstRange< TConstIterator >::end().
Referenced by DGtal::SimpleConstRange< TConstIterator >::rc().
className()
template<typename TConstIterator > std::string DGtal::SimpleConstRange< TConstIterator >::className () const inline
Returns
the style name used for drawing this object.
Definition at line 148 of file SimpleConstRange.h.
     {
       return "SimpleConstRange";
     }
end()
template<typename TConstIterator > ConstIterator DGtal::SimpleConstRange< TConstIterator >::end () const inline
Iterator service.
Returns
end iterator
Definition at line 180 of file SimpleConstRange.h.
{
       return ConstIterator( myEnd );
     }
References DGtal::SimpleConstRange< TConstIterator >::myEnd.
Referenced by DGtal::SimpleConstRange< TConstIterator >::c(), and DGtal::SimpleConstRange< TConstIterator >::rbegin().
isValid()
template<typename TConstIterator > bool DGtal::SimpleConstRange< TConstIterator >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 129 of file SimpleConstRange.h.
 { return true; }
operator=()
template<typename TConstIterator > SimpleConstRange& DGtal::SimpleConstRange< TConstIterator >::operator= (const SimpleConstRange< TConstIterator > & other) inline
Assignment.
Parameters
other the iterator to copy.
Returns
a reference on 'this'.
Definition at line 110 of file SimpleConstRange.h.
     {
       if ( this != &other )
         {
           myBegin = other.myBegin;
           myEnd = other.myEnd;
         }
       return *this;
     }
References DGtal::SimpleConstRange< TConstIterator >::myBegin, and DGtal::SimpleConstRange< TConstIterator >::myEnd.
rbegin()
template<typename TConstIterator > ConstReverseIterator DGtal::SimpleConstRange< TConstIterator >::rbegin () const inline
Iterator service.
Returns
rbegin iterator
Definition at line 188 of file SimpleConstRange.h.
{
       return ConstReverseIterator(this->end());
     }
References DGtal::SimpleConstRange< TConstIterator >::end().
rc()
template<typename TConstIterator > ConstReverseCirculator DGtal::SimpleConstRange< TConstIterator >::rc () const inline
Circulator service.
Returns
a reverse circulator
Definition at line 212 of file SimpleConstRange.h.
{
       return ConstReverseCirculator( this->c() );
     }
References DGtal::SimpleConstRange< TConstIterator >::c().
rend()
template<typename TConstIterator > ConstReverseIterator DGtal::SimpleConstRange< TConstIterator >::rend () const inline
Iterator service.
Returns
rend iterator
Definition at line 196 of file SimpleConstRange.h.
{
       return ConstReverseIterator(this->begin());
     }
References DGtal::SimpleConstRange< TConstIterator >::begin().
selfDisplay()
template<typename TConstIterator > void DGtal::SimpleConstRange< TConstIterator >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 136 of file SimpleConstRange.h.
     {
       typedef typename IteratorCirculatorTraits<ConstIterator>::Value Value;
       out << "[SimpleConstRange]" << std::endl;
       out << "\t";
       std::copy( myBegin, myEnd, std::ostream_iterator<Value>(out, ", ") );
       out << std::endl;
     }
References DGtal::SimpleConstRange< TConstIterator >::myBegin, and DGtal::SimpleConstRange< TConstIterator >::myEnd.
Field Documentation
myBegin
template<typename TConstIterator > TConstIterator DGtal::SimpleConstRange< TConstIterator >::myBegin private
Begin underlying iterator
Definition at line 159 of file SimpleConstRange.h.
Referenced by DGtal::SimpleConstRange< TConstIterator >::begin(), DGtal::SimpleConstRange< TConstIterator >::operator=(), and DGtal::SimpleConstRange< TConstIterator >::selfDisplay().
myEnd
template<typename TConstIterator > TConstIterator DGtal::SimpleConstRange< TConstIterator >::myEnd private
End underlying iterator
Definition at line 163 of file SimpleConstRange.h.
Referenced by DGtal::SimpleConstRange< TConstIterator >::end(), DGtal::SimpleConstRange< TConstIterator >::operator=(), and DGtal::SimpleConstRange< TConstIterator >::selfDisplay().
The documentation for this class was generated from the following file:
SimpleConstRange.h