DGtal: DGtal::CellGeometryFunctions< TKSpace, 2, 3 > Struct Template Reference
DGtal::CellGeometryFunctions< TKSpace, 2, 3 > Struct Template Reference
#include <DGtal/geometry/volumes/CellGeometry.h>
Public Types
typedef TKSpace KSpace
typedef KSpace::Space Space
typedef KSpace::Cell Cell
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CCellularGridSpaceND< TKSpace >))
BOOST_STATIC_ASSERT (TKSpace::dimension==2)
Static Public Member Functions
template<typename PointelIterator >
static std::unordered_set< typename KSpace::Cell > getIncidentCellsToPointels (const KSpace &K, PointelIterator itB, PointelIterator itE)
template<typename PointIterator >
static std::unordered_set< typename KSpace::Cell > getIncidentCellsToPoints (const KSpace &K, PointIterator itB, PointIterator itE)
template<typename PointIterator >
static UnorderedSetByBlock< typename KSpace::Point, Splitter< typename KSpace::Point, uint64_t > > getIncidentKPointsToPoints (const KSpace &K, PointIterator itB, PointIterator itE)
Detailed Description
template<typename TKSpace>
struct DGtal::CellGeometryFunctions< TKSpace, 2, 3 >
Specialization for 2-cells in 3D.
Template Parameters
TKSpace an arbitrary model of CCellularGridSpaceND.
Definition at line 767 of file CellGeometry.h.
Member Typedef Documentation
Cell
template<typename TKSpace > typedef KSpace::Cell DGtal::CellGeometryFunctions< TKSpace, 2, 3 >::Cell
Definition at line 773 of file CellGeometry.h.
KSpace
template<typename TKSpace > typedef TKSpace DGtal::CellGeometryFunctions< TKSpace, 2, 3 >::KSpace
Definition at line 771 of file CellGeometry.h.
Space
template<typename TKSpace > typedef KSpace::Space DGtal::CellGeometryFunctions< TKSpace, 2, 3 >::Space
Definition at line 772 of file CellGeometry.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename TKSpace > DGtal::CellGeometryFunctions< TKSpace, 2, 3 >::BOOST_CONCEPT_ASSERT ((concepts::CCellularGridSpaceND< TKSpace >))
BOOST_STATIC_ASSERT()
template<typename TKSpace > DGtal::CellGeometryFunctions< TKSpace, 2, 3 >::BOOST_STATIC_ASSERT (TKSpace::dimension = =2)
getIncidentCellsToPointels()
template<typename TKSpace > template<typename PointelIterator > static std::unordered_set<typename KSpace::Cell> DGtal::CellGeometryFunctions< TKSpace, 2, 3 >::getIncidentCellsToPointels (const KSpace & K, PointelIterator itB, PointelIterator itE) inline static
Template Parameters
PointelIterator any model of forward iterator on pointels.
Parameters
K a valid cellular grid space large enough to hold the cells.
itB the start of a range of pointels.
itE past the end of a range of pointels.
Returns
the incident 2-cells to the given range of pointels [itB, itE).
Definition at line 783 of file CellGeometry.h.
     {
       std::unordered_set<typename KSpace::Cell> cells;
       for ( auto it = itB; it != itE; ++it )
         {
           auto pointel = *it;
           auto linelxp = K.uIncident( pointel, 0, true );
           auto linelxm = K.uIncident( pointel, 0, false );
           auto linelyp = K.uIncident( pointel, 1, true );
           auto linelym = K.uIncident( pointel, 1, false );
           cells.insert( K.uIncident( linelxp, 1, true ) );
           cells.insert( K.uIncident( linelxp, 1, false ) );
           cells.insert( K.uIncident( linelxp, 2, true ) );
           cells.insert( K.uIncident( linelxp, 2, false ) );
           cells.insert( K.uIncident( linelxm, 1, true ) );
           cells.insert( K.uIncident( linelxm, 1, false ) );
           cells.insert( K.uIncident( linelxm, 2, true ) );
           cells.insert( K.uIncident( linelxm, 2, false ) );
           cells.insert( K.uIncident( linelyp, 2, true ) );
           cells.insert( K.uIncident( linelyp, 2, false ) );
           cells.insert( K.uIncident( linelym, 2, true ) );
           cells.insert( K.uIncident( linelym, 2, false ) );
         }
       return cells;
     }
References K, and DGtal::KhalimskySpaceND< dim, TInteger >::uIncident().
getIncidentCellsToPoints()
template<typename TKSpace > template<typename PointIterator > static std::unordered_set<typename KSpace::Cell> DGtal::CellGeometryFunctions< TKSpace, 2, 3 >::getIncidentCellsToPoints (const KSpace & K, PointIterator itB, PointIterator itE) inline static
Template Parameters
PointIterator any model of forward iterator on points.
Parameters
K a valid cellular grid space large enough to hold the cells.
itB the start of a range of points.
itE past the end of a range of points.
Returns
the incident 2-cells to the given range of points [itB, itE).
Note
General method. Note as efficient as specializations.
Definition at line 819 of file CellGeometry.h.
     {
       std::cout << "<2,3> specialization" << std::endl;
       std::unordered_set<typename KSpace::Cell> cells;
       for ( auto it = itB; it != itE; ++it )
         {
           auto pointel = K.uPointel( *it );
           auto linelxp = K.uIncident( pointel, 0, true );
           auto linelxm = K.uIncident( pointel, 0, false );
           auto linelyp = K.uIncident( pointel, 1, true );
           auto linelym = K.uIncident( pointel, 1, false );
           cells.insert( K.uIncident( linelxp, 1, true ) );
           cells.insert( K.uIncident( linelxp, 1, false ) );
           cells.insert( K.uIncident( linelxp, 2, true ) );
           cells.insert( K.uIncident( linelxp, 2, false ) );
           cells.insert( K.uIncident( linelxm, 1, true ) );
           cells.insert( K.uIncident( linelxm, 1, false ) );
           cells.insert( K.uIncident( linelxm, 2, true ) );
           cells.insert( K.uIncident( linelxm, 2, false ) );
           cells.insert( K.uIncident( linelyp, 2, true ) );
           cells.insert( K.uIncident( linelyp, 2, false ) );
           cells.insert( K.uIncident( linelym, 2, true ) );
           cells.insert( K.uIncident( linelym, 2, false ) );
         }
       return cells;
     }
References K, DGtal::KhalimskySpaceND< dim, TInteger >::uIncident(), and DGtal::KhalimskySpaceND< dim, TInteger >::uPointel().
getIncidentKPointsToPoints()
template<typename TKSpace > template<typename PointIterator > static UnorderedSetByBlock< typename KSpace::Point, Splitter< typename KSpace::Point, uint64_t> > DGtal::CellGeometryFunctions< TKSpace, 2, 3 >::getIncidentKPointsToPoints (const KSpace & K, PointIterator itB, PointIterator itE) inline static
Template Parameters
PointIterator any model of forward iterator on points.
Parameters
K a valid cellular grid space large enough to hold the cells.
itB the start of a range of points.
itE past the end of a range of points.
Returns
the incident 2-kpoints to the given range of points [itB, itE).
Definition at line 856 of file CellGeometry.h.
     {
       UnorderedSetByBlock< typename KSpace::Point,
                            Splitter< typename KSpace::Point, uint64_t> > kpoints;
       for ( auto it = itB; it != itE; ++it )
         {
           auto kp = K.uKCoords( K.uPointel( *it ) );
           kpoints.emplace( kp[ 0 ] - 1, kp[ 1 ] - 1, kp[ 2 ]     );
           kpoints.emplace( kp[ 0 ] + 1, kp[ 1 ] - 1, kp[ 2 ]     );
           kpoints.emplace( kp[ 0 ] - 1, kp[ 1 ] + 1, kp[ 2 ]     );
           kpoints.emplace( kp[ 0 ] + 1, kp[ 1 ] + 1, kp[ 2 ]     );
           kpoints.emplace( kp[ 0 ] - 1, kp[ 1 ]    , kp[ 2 ] - 1 );
           kpoints.emplace( kp[ 0 ] + 1, kp[ 1 ]    , kp[ 2 ] - 1 );
           kpoints.emplace( kp[ 0 ] - 1, kp[ 1 ]    , kp[ 2 ] + 1 );
           kpoints.emplace( kp[ 0 ] + 1, kp[ 1 ]    , kp[ 2 ] + 1 );
           kpoints.emplace( kp[ 0 ]    , kp[ 1 ] - 1, kp[ 2 ] - 1 );
           kpoints.emplace( kp[ 0 ]    , kp[ 1 ] + 1, kp[ 2 ] - 1 );
           kpoints.emplace( kp[ 0 ]    , kp[ 1 ] - 1, kp[ 2 ] + 1 );
           kpoints.emplace( kp[ 0 ]    , kp[ 1 ] + 1, kp[ 2 ] + 1 );
         }
       return kpoints;
     }
References K, DGtal::KhalimskySpaceND< dim, TInteger >::uKCoords(), and DGtal::KhalimskySpaceND< dim, TInteger >::uPointel().
The documentation for this struct was generated from the following file:
CellGeometry.h