DGtal: DGtal::concepts::CConstBidirectionalRange< T > Struct Template Reference
DGtal::concepts::CConstBidirectionalRange< T > Struct Template Reference
DGtal Concepts
Aim: Defines the concept describing a bidirectional const range.
#include <DGtal/base/CConstBidirectionalRange.h>
Public Types
typedef T::ConstReverseIterator ConstReverseIterator
Public Types inherited from DGtal::concepts::CConstSinglePassRange< T >
typedef T::ConstIterator ConstIterator
Public Member Functions
BOOST_CONCEPT_ASSERT ((boost_concepts::SinglePassIteratorConcept< ConstReverseIterator >))
BOOST_CONCEPT_USAGE (CConstBidirectionalRange)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::concepts::CConstSinglePassRange< T >
BOOST_CONCEPT_ASSERT ((boost_concepts::SinglePassIteratorConcept< ConstIterator >))
BOOST_CONCEPT_USAGE (CConstSinglePassRange)
void checkConstConstraints () const
Private Attributes
T i
ConstReverseIterator it
Detailed Description
template<typename T>
struct DGtal::concepts::CConstBidirectionalRange< T >
Aim: Defines the concept describing a bidirectional const range.
Description of concept 'CConstBidirectionalRange'
Refinement of
CConstSinglePassRange
Provided types
ConstReverseIterator: the const reverse iterator type, a model of const iterator concept.
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
rbegin of range x.rbegin() ConstReverseIterator returns a reverse forward iterator on the beginning of the range
rend of range x.rend() ConstReverseIterator returns a reverse forward iterator after the end of the range
Invariants
Models
Notes
Template Parameters
T the type that is checked. T should be a model of CConstBidirectionalRange.
Definition at line 89 of file CConstBidirectionalRange.h.
Member Typedef Documentation
ConstReverseIterator
template<typename T > typedef T::ConstReverseIterator DGtal::concepts::CConstBidirectionalRange< T >::ConstReverseIterator
Definition at line 93 of file CConstBidirectionalRange.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename T > DGtal::concepts::CConstBidirectionalRange< T >::BOOST_CONCEPT_ASSERT ((boost_concepts::SinglePassIteratorConcept< ConstReverseIterator >))
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CConstBidirectionalRange< T >::BOOST_CONCEPT_USAGE (CConstBidirectionalRange< T >) inline
Definition at line 97 of file CConstBidirectionalRange.h.
       {
         checkConstConstraints();
       }
References DGtal::concepts::CConstBidirectionalRange< T >::checkConstConstraints().
checkConstConstraints()
template<typename T > void DGtal::concepts::CConstBidirectionalRange< T >::checkConstConstraints () const inline
Definition at line 101 of file CConstBidirectionalRange.h.
       {
         concepts::ConceptUtils::sameType( it, i.rbegin() );
         concepts::ConceptUtils::sameType( it, i.rend() );
       }
References DGtal::concepts::CConstBidirectionalRange< T >::i, DGtal::concepts::CConstBidirectionalRange< T >::it, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::concepts::CConstBidirectionalRange< T >::BOOST_CONCEPT_USAGE().
Field Documentation
i
template<typename T > T DGtal::concepts::CConstBidirectionalRange< T >::i private
Definition at line 108 of file CConstBidirectionalRange.h.
Referenced by DGtal::concepts::CConstBidirectionalRange< T >::checkConstConstraints().
it
template<typename T > ConstReverseIterator DGtal::concepts::CConstBidirectionalRange< T >::it private
Definition at line 109 of file CConstBidirectionalRange.h.
Referenced by DGtal::concepts::CConstBidirectionalRange< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CConstBidirectionalRange.h