DGtal: testImageSpanIterators.cpp File Reference
testImageSpanIterators.cpp File Reference
DGtal Test Files
#include <cstdio>
#include <cmath>
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/images/ImageContainerBySTLVector.h"
Functions
bool testSpanIterators ()
int main ()
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr)
Date
2010/05/25
This file is part of the DGtal library
Definition in file testImageSpanIterators.cpp.
Function Documentation
main()
int main ()
Definition at line 124 of file testImageSpanIterators.cpp.
 {
     if ( testSpanIterators())
         return 0;
     else
         return 1;
 }
References testSpanIterators().
testSpanIterators()
bool testSpanIterators ()
Definition at line 46 of file testImageSpanIterators.cpp.
 {
     typedef SpaceND<3> Space3Type;
     typedef Space3Type::Point Point;
     typedef HyperRectDomain<Space3Type> TDomain;
     typedef ImageContainerBySTLVector<TDomain, double> TContainerV;
     const Point::Component t[ ] = { 0, 0, 0};
     const Point::Component t2[ ] = { 5, 5, 5};
     const Point::Component t3[ ] = { 0, 0, 0};
     Point a ( t );
     Point b ( t2 );
     Point c( t3 );
     trace.beginBlock("Test of Concepts");
     TContainerV myImageV ( TDomain(a,b ));
     double cpt=0;
     //Image Construction
     for ( TContainerV::Iterator it = myImageV.begin();
             it != myImageV.end();
             ++it)
     {
       (*it) = cpt ;
       cpt++;
     }
     //We process a 1D slice
     trace.info()<<"Slice dim 0 ";
     for ( TContainerV::SpanIterator it = myImageV.spanBegin(c,0), itend = myImageV.spanEnd(c,0);
     it != itend;
     ++it)
       trace.info() << (*it)<<" ";
     trace.info() << endl;
     //We process a 1D slice
     trace.info()<<"Slice dim 1 ";
     for ( TContainerV::SpanIterator it = myImageV.spanBegin(c,1), itend = myImageV.spanEnd(c,1);
     it != itend;
     ++it)
       trace.info() << (*it)<<" ";
     trace.info() << endl;
     //We process a 1D slice
     trace.info()<<"Slice dim 2 ";
     for ( TContainerV::SpanIterator it = myImageV.spanBegin(c,2), itend = myImageV.spanEnd(c,2);
     it != itend;
     ++it)
       trace.info() << (*it)<<" ";
     trace.info() << endl;
     //We process a 1D slice to set a value
     trace.info()<<"SetValue Slice dim 1 "<<endl;
     for ( TContainerV::SpanIterator it = myImageV.spanBegin(c,1), itend = myImageV.spanEnd(c,1);
     it != itend;
     ++it)
       myImageV.setValue(it, 12);
     //We check the a 1D slice
     trace.info()<<"Check Slice dim 1 ";
     for ( TContainerV::SpanIterator it = myImageV.spanBegin(c,1), itend = myImageV.spanEnd(c,1);
     it != itend;
     ++it)
       trace.info() << (*it)<<" ";
     trace.info() << endl;
     trace.endBlock();
     return true;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.
Referenced by main().