DGtal: testPointVectorContainers.cpp File Reference
testPointVectorContainers.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/PointVector.h"
#include <boost/array.hpp>
#include <vector>
#include <array>
Functions
bool testPointVectorContainers ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2012/09/28
Functions for testing class PointVectorContainers.
This file is part of the DGtal library.
Definition in file testPointVectorContainers.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 72 of file testPointVectorContainers.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testPointVectorContainers(), and DGtal::trace.
 {
   trace.beginBlock ( "Testing class PointVectorContainers" );
   trace.info() << "Args:";
   for ( int i = 0; i < argc; ++i )
     trace.info() << " " << argv[ i ];
   trace.info() << endl;
   bool res = testPointVectorContainers(); // && ... other tests
   trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
   trace.endBlock();
   return res ? 0 : 1;
 }
testPointVectorContainers()
bool testPointVectorContainers ()
Example of a test. To be completed.
Definition at line 51 of file testPointVectorContainers.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.
Referenced by main().
 {
   trace.beginBlock ( "Testing different point containers ..." );
   typedef PointVector<3, int, boost::array<int, 3> > PA6;
   PA6 pa(2,3,4);
   trace.info() <<"boost::array container "<< pa<<std::endl;
   typedef PointVector<3, int, std::array<int, 3> > PV6;
   PV6 pv(1,3,4);
   trace.info() <<"std::array container "<< pv<<std::endl;
   trace.endBlock();
   return true;
 }