DGtal: testClock.cpp File Reference
testClock.cpp File Reference
DGtal Test Files
#include <cstdio>
#include <cmath>
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/base/Clock.h"
Functions
bool test_minimalTick ()
Minimal tick must be >=0.
bool test_loopTick ()
Loop ticks must be >=0.
bool test_MultipleLoop ()
Test several loops.
bool test_RestartClock ()
Test restart.
int main ()
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr)
Date
2009/12/13
This file is part of the DGtal library
Definition in file testClock.cpp.
Function Documentation
main()
int main ()
Definition at line 144 of file testClock.cpp.
 {
   if (test_minimalTick() && test_loopTick() && test_MultipleLoop() && test_RestartClock())
     return 0;
   else
     return 1;
 }
References test_loopTick(), test_minimalTick(), test_MultipleLoop(), and test_RestartClock().
test_loopTick()
bool test_loopTick ()
Loop ticks must be >=0.
Definition at line 58 of file testClock.cpp.
 {
   double tick,tmp=0;
   Clock c;
   c.startClock();
   for (unsigned int i=0 ; i< 4334450; i++)
     tmp = cos(tmp+i);
   tick = c.stopClock();
   trace.info()<< "Loop tick: "<< tick <<endl;
   return (tick >= 0);
 }
References DGtal::Trace::info(), DGtal::Clock::startClock(), and DGtal::trace.
Referenced by main().
test_minimalTick()
bool test_minimalTick ()
Minimal tick must be >=0.
Definition at line 44 of file testClock.cpp.
 {
   double tick;
   Clock c;
   trace.info() << c <<std::endl;
   c.startClock();
   tick = c.stopClock();
   trace.info() << "Minimal tick: "<< tick <<endl;
   return (tick >= 0);
 }
References DGtal::Trace::info(), and DGtal::trace.
Referenced by main().
test_MultipleLoop()
bool test_MultipleLoop ()
Test several loops.
Definition at line 73 of file testClock.cpp.
 {
   double tick1,tick2,tick3,tmp=0;
   Clock c,c2,c3;
   c3.startClock();
   c.startClock();
   for (unsigned int i=0 ; i< 43350; i++)
     tmp = cos(tmp+i);
   c2.startClock();
   for (unsigned int i=0 ; i< 43350; i++)
     tmp = cos(tmp+i);
   tick2 = c2.stopClock();
   for (unsigned int i=0 ; i< 43450; i++)
     tmp = cos(tmp+i);
   tick1 = c.stopClock();
   tick3=c3.stopClock();
   trace.info()<< "Loop tick1: "<< tick1
               <<" Loop tick2: "<< tick2
               << " total: "<< tick3 <<endl;
   return ((tick3 >= tick1) && (tick1 >= 0));
 }
References DGtal::Trace::info(), DGtal::Clock::startClock(), DGtal::Clock::stopClock(), and DGtal::trace.
Referenced by main().
test_RestartClock()
bool test_RestartClock ()
Test restart.
Definition at line 103 of file testClock.cpp.
 {
   double tmp = 0.0;
   double tick_total=0., tick_accum=0.;
   Clock c_total, c_accum;
   c_total.startClock();
   c_accum.startClock();
 #if !defined(WIN32)
   for (unsigned int i=0 ; i< 43350; i++)
     tmp = cos(tmp+i);
         usleep(20000);
   tick_accum += c_accum.restartClock();
   for (unsigned int i=0 ; i< 43350; i++)
     tmp = cos(tmp+i);
         usleep(20000);
   tick_accum += c_accum.restartClock();
   for (unsigned int i=0 ; i< 43350; i++)
     tmp = cos(tmp+i);
         usleep(20000);
   tick_accum += c_accum.restartClock();
   tick_total = c_total.stopClock();
         double delta = tick_total-tick_accum;
   trace.info()<< "Loop tick_total: " << tick_total
               << " Loop tick_accum: " << tick_accum
               << " Delta = "<<delta << endl;
   //return delta>=0 && delta<1e-4;
 #endif
   return true;
 }
References DGtal::Trace::info(), DGtal::Clock::restartClock(), DGtal::Clock::startClock(), DGtal::Clock::stopClock(), and DGtal::trace.
Referenced by main().