DGtal: approximation.cpp File Reference
approximation.cpp File Reference
DGtal Examples
#include <cstdlib>
#include <cmath>
#include <iostream>
#include <iomanip>
#include "DGtal/arithmetic/LighterSternBrocot.h"
#include "DGtal/base/StdRebinders.h"
Functions
void usage (int, char **argv)
int main (int argc, char **argv)
Detailed Description
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2012/02/06
An example file named approximation.
This file is part of the DGtal library.
Definition in file approximation.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Main.
[approximation-types]
[approximation-types]
[approximation-process]
[approximation-process]
Definition at line 73 of file approximation.cpp.
 {
   if ( argc < 2 )
     {
       usage( argc, argv );
       return 1;
     }
   typedef DGtal::int64_t Integer;
   typedef DGtal::int64_t Quotient;
   typedef LighterSternBrocot<Integer, Quotient, StdMapRebinder> SB; // the type of the Stern-Brocot tree
   typedef SB::Fraction Fraction; // the type for fractions
   typedef std::back_insert_iterator< Fraction > OutputIterator;
   long double epsilon = 1e-14;
   long double number0 = strtold( argv[ 1 ], 0 );
   long double number = number0;
   ASSERT( number >= 0.0 );
   Fraction f;
   OutputIterator itback = std::back_inserter( f );
   Quotient i = 0;
   while ( true )
     {
       long double int_part = floorl( number );
       Quotient u = NumberTraits<long double>::castToInt64_t( int_part );
       *itback++ = std::make_pair( u, i++ );
       long double approx =
         ( (long double) NumberTraits<Integer>::castToDouble( f.p() ) )
         / ( (long double) NumberTraits<Integer>::castToDouble( f.q() ) );
       std::cout << "z = " << f.p() << " / " << f.q()
                 << " =~ " << std::setprecision( 16 ) << approx << std::endl;
       number -= int_part;
       if ( ( (number0 - epsilon ) < approx )
            && ( approx < (number0 + epsilon ) ) ) break;
       number = 1.0 / number;
     }
   std::cout << "z = " << f.p() << " / " << f.q() << std::endl;
   return 0;
 }
References DGtal::NumberTraitsImpl< std::decay< T >::type >::castToInt64_t(), and usage().
usage()
void usage (int , char ** argv)
Examples
arithmetic/approximation.cpp, arithmetic/convergents-biginteger.cpp, arithmetic/convergents.cpp, arithmetic/extended-euclid.cpp, arithmetic/fraction.cpp, arithmetic/lower-integer-convex-hull.cpp, arithmetic/pattern.cpp, graph/volDistanceTraversal.cpp, math/polynomial-derivative.cpp, math/polynomial2-derivative.cpp, shapes/viewMarchingCubes.cpp, shapes/viewPolygonalMarchingCubes.cpp, topology/trackImplicitPolynomialSurfaceToOFF.cpp, topology/volBreadthFirstTraversal.cpp, topology/volMarchingCubes.cpp, topology/volScanBoundary.cpp, topology/volToOFF.cpp, and topology/volTrackBoundary.cpp.
Definition at line 64 of file approximation.cpp.
 {
   std::cerr << "Usage: " << argv[ 0 ] << " <floating point number>" << std::endl;
   std::cerr << "\t - computes the successive rational approximation of this number, up to a precision of 1e-14." << std::endl;
 }
Referenced by main().