DGtal: DGtal::functors::SCellToInnerPoint< KSpace > Class Template Reference
DGtal::functors::SCellToInnerPoint< KSpace > Class Template Reference
Aim: transforms a signed cell c into a point corresponding to the signed cell of greater dimension that is indirectly incident to c.
#include <DGtal/topology/SCellsFunctors.h>
Public Types
typedef KSpace::Point Output
typedef KSpace::SCell Input
Public Member Functions
SCellToInnerPoint ()
SCellToInnerPoint (ConstAlias< KSpace > aK)
SCellToInnerPoint (const SCellToInnerPoint &other)
SCellToInnerPoint & operator= (const SCellToInnerPoint &other)
Output operator() (const Input &s) const
Private Attributes
const KSpace * myK
Detailed Description
template<typename KSpace>
class DGtal::functors::SCellToInnerPoint< KSpace >
Aim: transforms a signed cell c into a point corresponding to the signed cell of greater dimension that is indirectly incident to c.
Description of template class 'SCellToInnerPoint'
For instance, a linel is mapped into the indirect incident pixel center and a surfel is mapped into the indirect incident voxel center.
Template Parameters
KSpace the Khalimsky space
See also
SCellToPoint SCellToOuterPoint ConstIteratorAdapter KhalimskySpaceND PointVector
Examples
tutorial-examples/FMMErosion.cpp.
Definition at line 323 of file SCellsFunctors.h.
Member Typedef Documentation
Input
template<typename KSpace > typedef KSpace::SCell DGtal::functors::SCellToInnerPoint< KSpace >::Input
Definition at line 329 of file SCellsFunctors.h.
Output
template<typename KSpace > typedef KSpace::Point DGtal::functors::SCellToInnerPoint< KSpace >::Output
Definition at line 328 of file SCellsFunctors.h.
Constructor & Destructor Documentation
SCellToInnerPoint() [1/3]
template<typename KSpace > DGtal::functors::SCellToInnerPoint< KSpace >::SCellToInnerPoint () inline
Default constructor.
Definition at line 342 of file SCellsFunctors.h.
 : myK(NULL) { }
SCellToInnerPoint() [2/3]
template<typename KSpace > DGtal::functors::SCellToInnerPoint< KSpace >::SCellToInnerPoint (ConstAlias< KSpace > aK) inline
Constructor.
Parameters
aK a Khalimsky space
Definition at line 347 of file SCellsFunctors.h.
 : myK(&aK) { }
SCellToInnerPoint() [3/3]
template<typename KSpace > DGtal::functors::SCellToInnerPoint< KSpace >::SCellToInnerPoint (const SCellToInnerPoint< KSpace > & other) inline
Copy constructor.
Parameters
other any SCellToInnerPoint functor
Definition at line 353 of file SCellsFunctors.h.
     : myK(other.myK) { }
Member Function Documentation
operator()()
template<typename KSpace > Output DGtal::functors::SCellToInnerPoint< KSpace >::operator() (const Input & s) const inline
Return a point (integer coordinates) from a scell (khalimsky coordinates)
Parameters
s a linel
Returns
the inner pixel center
Definition at line 375 of file SCellsFunctors.h.
     {
       ASSERT( myK );
       Input pixel( myK->sDirectIncident( s, *myK->sOrthDirs( s ) ) );
       return Output( myK->sCoords( pixel ) ); //integer coordinates
     }
References DGtal::functors::SCellToInnerPoint< KSpace >::myK, DGtal::KhalimskySpaceND< dim, TInteger >::sCoords(), DGtal::KhalimskySpaceND< dim, TInteger >::sDirectIncident(), and DGtal::KhalimskySpaceND< dim, TInteger >::sOrthDirs().
operator=()
template<typename KSpace > SCellToInnerPoint& DGtal::functors::SCellToInnerPoint< KSpace >::operator= (const SCellToInnerPoint< KSpace > & other) inline
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'.
Definition at line 361 of file SCellsFunctors.h.
     {
       if (this != &other)
         {
           myK = other.myK;
         }
       return *this;
     }
References DGtal::functors::SCellToInnerPoint< KSpace >::myK.
Field Documentation
myK
template<typename KSpace > const KSpace* DGtal::functors::SCellToInnerPoint< KSpace >::myK private
Aliasing pointer on the Khalimsky space.
Definition at line 335 of file SCellsFunctors.h.
Referenced by DGtal::functors::SCellToInnerPoint< KSpace >::operator()(), and DGtal::functors::SCellToInnerPoint< KSpace >::operator=().
The documentation for this class was generated from the following file:
SCellsFunctors.h