DGtal: DGtal::FreemanChain< TInteger >::CodesRange Class Reference
DGtal::FreemanChain< TInteger >::CodesRange Class Reference
Aim: model of CRange that provides services to (circularly)iterate over the letters of the freeman chain.
#include <DGtal/geometry/curves/FreemanChain.h>
Public Types
typedef std::string::const_iterator ConstIterator
typedef std::string::const_reverse_iterator ConstReverseIterator
typedef Circulator< ConstIterator > ConstCirculator
typedef std::reverse_iterator< ConstCirculator > ConstReverseCirculator
Public Member Functions
CodesRange ()
CodesRange (const std::string &aChain)
CodesRange (const CodesRange &aOther)
CodesRange & operator= (const CodesRange &other)
~CodesRange ()
std::string::size_type size () const
bool isValid () const
void selfDisplay (std::ostream &out) const
ConstIterator begin () const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rend () const
ConstCirculator c () const
ConstReverseCirculator rc () const
Private Attributes
const std::string myChain
Friends
std::ostream & operator<< (std::ostream &out, const CodesRange &object)
Detailed Description
template<typename TInteger>
class DGtal::FreemanChain< TInteger >::CodesRange
Aim: model of CRange that provides services to (circularly)iterate over the letters of the freeman chain.
See also
FreemanChain.h testFreemanChain.cpp
Definition at line 387 of file FreemanChain.h.
Member Typedef Documentation
ConstCirculator
template<typename TInteger > typedef Circulator<ConstIterator> DGtal::FreemanChain< TInteger >::CodesRange::ConstCirculator
Definition at line 395 of file FreemanChain.h.
ConstIterator
template<typename TInteger > typedef std::string::const_iterator DGtal::FreemanChain< TInteger >::CodesRange::ConstIterator
Definition at line 393 of file FreemanChain.h.
ConstReverseCirculator
template<typename TInteger > typedef std::reverse_iterator<ConstCirculator> DGtal::FreemanChain< TInteger >::CodesRange::ConstReverseCirculator
Definition at line 396 of file FreemanChain.h.
ConstReverseIterator
template<typename TInteger > typedef std::string::const_reverse_iterator DGtal::FreemanChain< TInteger >::CodesRange::ConstReverseIterator
Definition at line 394 of file FreemanChain.h.
Constructor & Destructor Documentation
CodesRange() [1/3]
template<typename TInteger > DGtal::FreemanChain< TInteger >::CodesRange::CodesRange () inline
Default Constructor.
Definition at line 403 of file FreemanChain.h.
 {}
CodesRange() [2/3]
template<typename TInteger > DGtal::FreemanChain< TInteger >::CodesRange::CodesRange (const std::string & aChain) inline
Constructor.
Definition at line 408 of file FreemanChain.h.
 : myChain(aChain){}
CodesRange() [3/3]
template<typename TInteger > DGtal::FreemanChain< TInteger >::CodesRange::CodesRange (const CodesRange & aOther) inline
Copy constructor.
Parameters
aOther the iterator to clone.
Definition at line 414 of file FreemanChain.h.
     : myChain( aOther.myChain ){}
~CodesRange()
template<typename TInteger > DGtal::FreemanChain< TInteger >::CodesRange::~CodesRange () inline
Destructor. Does nothing.
Definition at line 434 of file FreemanChain.h.
 {}
Member Function Documentation
begin()
template<typename TInteger > ConstIterator DGtal::FreemanChain< TInteger >::CodesRange::begin () const inline
Iterator service.
Returns
begin iterator
Definition at line 488 of file FreemanChain.h.
{
     return myChain.begin();
   }
References DGtal::FreemanChain< TInteger >::CodesRange::myChain.
Referenced by DGtal::FreemanChain< TInteger >::CodesRange::c(), and DGtal::FreemanChain< TInteger >::CodesRange::selfDisplay().
c()
template<typename TInteger > ConstCirculator DGtal::FreemanChain< TInteger >::CodesRange::c () const inline
Circulator service.
Returns
a circulator
Definition at line 520 of file FreemanChain.h.
{
     return ConstCirculator( this->begin(), this->begin(), this->end() );
   }
References DGtal::FreemanChain< TInteger >::CodesRange::begin(), and DGtal::FreemanChain< TInteger >::CodesRange::end().
Referenced by DGtal::FreemanChain< TInteger >::CodesRange::rc().
end()
template<typename TInteger > ConstIterator DGtal::FreemanChain< TInteger >::CodesRange::end () const inline
Iterator service.
Returns
end iterator
Definition at line 496 of file FreemanChain.h.
{
     return myChain.end();
   }
References DGtal::FreemanChain< TInteger >::CodesRange::myChain.
Referenced by DGtal::FreemanChain< TInteger >::CodesRange::c(), and DGtal::FreemanChain< TInteger >::CodesRange::selfDisplay().
isValid()
template<typename TInteger > bool DGtal::FreemanChain< TInteger >::CodesRange::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 448 of file FreemanChain.h.
 { return true; }
operator=()
template<typename TInteger > CodesRange& DGtal::FreemanChain< TInteger >::CodesRange::operator= (const CodesRange & other) inline
Assignment.
Parameters
other the iterator to copy.
Returns
a reference on 'this'.
Definition at line 422 of file FreemanChain.h.
   {
     if ( this != &other )
     {
       myChain = other.myChain;
     }
   return *this;
   }
References DGtal::FreemanChain< TInteger >::CodesRange::myChain.
rbegin()
template<typename TInteger > ConstReverseIterator DGtal::FreemanChain< TInteger >::CodesRange::rbegin () const inline
Iterator service.
Returns
rbegin iterator
Definition at line 504 of file FreemanChain.h.
{
     return myChain.rbegin();
   }
References DGtal::FreemanChain< TInteger >::CodesRange::myChain.
rc()
template<typename TInteger > ConstReverseCirculator DGtal::FreemanChain< TInteger >::CodesRange::rc () const inline
Circulator service.
Returns
a reverse circulator
Definition at line 528 of file FreemanChain.h.
{
     return ConstReverseCirculator( this->c() );
   }
References DGtal::FreemanChain< TInteger >::CodesRange::c().
rend()
template<typename TInteger > ConstReverseIterator DGtal::FreemanChain< TInteger >::CodesRange::rend () const inline
Iterator service.
Returns
rend iterator
Definition at line 512 of file FreemanChain.h.
{
     return myChain.rend();
   }
References DGtal::FreemanChain< TInteger >::CodesRange::myChain.
selfDisplay()
template<typename TInteger > void DGtal::FreemanChain< TInteger >::CodesRange::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 455 of file FreemanChain.h.
   {
     typedef typename IteratorCirculatorTraits<ConstIterator>::Value Value;
     out << "[FreemanChainCodes]" << std::endl;
     out << "\t";
     std::copy( this->begin(), this->end(), std::ostream_iterator<Value>(out, "") );
     out << std::endl;
   }
References DGtal::FreemanChain< TInteger >::CodesRange::begin(), and DGtal::FreemanChain< TInteger >::CodesRange::end().
size()
template<typename TInteger > std::string::size_type DGtal::FreemanChain< TInteger >::CodesRange::size () const inline
Returns
the size of the range
Definition at line 439 of file FreemanChain.h.
   {
     return myChain.size();
   }
References DGtal::FreemanChain< TInteger >::CodesRange::myChain.
Friends And Related Function Documentation
operator<<
template<typename TInteger > std::ostream& operator<< (std::ostream & out, const CodesRange & object) friend
Overloads 'operator<<' for displaying objects of class 'CodesRange'.
Parameters
out the output stream where the object is written.
object the object of class 'CodesRange' to write.
Returns
the output stream after the writing.
Definition at line 470 of file FreemanChain.h.
     {
       object.selfDisplay( out );
       return out;
     }
Field Documentation
myChain
template<typename TInteger > const std::string DGtal::FreemanChain< TInteger >::CodesRange::myChain private
Private member myChain is a string of letters
Definition at line 480 of file FreemanChain.h.
Referenced by DGtal::FreemanChain< TInteger >::CodesRange::begin(), DGtal::FreemanChain< TInteger >::CodesRange::end(), DGtal::FreemanChain< TInteger >::CodesRange::operator=(), DGtal::FreemanChain< TInteger >::CodesRange::rbegin(), DGtal::FreemanChain< TInteger >::CodesRange::rend(), and DGtal::FreemanChain< TInteger >::CodesRange::size().
The documentation for this class was generated from the following file:
FreemanChain.h