DGtal: DGtal::DigitalShapesCSG< ShapeA, ShapeB > Class Template Reference
DGtal::DigitalShapesCSG< ShapeA, ShapeB > Class Template Reference
Aim: Constructive Solid Geometry (CSG) between models of CDigitalBoundedShape and CDigitalOrientedShape Use CSG operation (union, intersection, minus) from a shape of Type ShapeA with one (or more) shapes of Type ShapeB. Can combine differents operations. Limitations: Since we don't have a class derived by all shapes, operations can be done by only one type of shapes. Use CSG of CSG to go beyond this limitation.
#include <DGtal/shapes/DigitalShapesDecorator.h>
Public Types
typedef ShapeA::Space Space
typedef ShapeA::Point Point
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CDigitalBoundedShape< ShapeA >))
BOOST_CONCEPT_ASSERT ((concepts::CDigitalOrientedShape< ShapeA >))
DigitalShapesCSG ()
DigitalShapesCSG (const DigitalShapesCSG &other)
DigitalShapesCSG (ConstAlias< ShapeA > a)
DigitalShapesCSG & operator= (const DigitalShapesCSG &other)
void setParams (ConstAlias< ShapeA > a)
void plus (ConstAlias< ShapeB > b)
void intersection (ConstAlias< ShapeB > b)
void minus (ConstAlias< ShapeB > b)
Point getLowerBound () const
Point getUpperBound () const
Orientation orientation (const Point &p) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Protected Types
enum e_operator { e_plus, e_intersection, e_minus }
Private Attributes
CountedConstPtrOrConstPtr< ShapeA > myShapeA
Base Shape.
std::vector< std::pair< e_operator, CountedConstPtrOrConstPtr< ShapeB > > > v_shapes
Vector of all operations (ordered) of ShapeB.
Point myLowerBound
Domain lower bound.
Point myUpperBound
Domain upper bound.
bool bIsValid
if the CSG is valid.
Detailed Description
template<typename ShapeA, typename ShapeB>
class DGtal::DigitalShapesCSG< ShapeA, ShapeB >
Aim: Constructive Solid Geometry (CSG) between models of CDigitalBoundedShape and CDigitalOrientedShape Use CSG operation (union, intersection, minus) from a shape of Type ShapeA with one (or more) shapes of Type ShapeB. Can combine differents operations. Limitations: Since we don't have a class derived by all shapes, operations can be done by only one type of shapes. Use CSG of CSG to go beyond this limitation.
Description of template class 'DigitalShapesCSG'
Template Parameters
ShapeA type of a first shape. Must be a model of CDigitalBoundedShape and CDigitalOrientedShape
ShapeB type of a second shape. Must be a model of CDigitalBoundedShape and CDigitalOrientedShape
Definition at line 67 of file DigitalShapesDecorator.h.
Member Typedef Documentation
Point
template<typename ShapeA , typename ShapeB > typedef ShapeA::Point DGtal::DigitalShapesCSG< ShapeA, ShapeB >::Point
Definition at line 82 of file DigitalShapesDecorator.h.
Space
template<typename ShapeA , typename ShapeB > typedef ShapeA::Space DGtal::DigitalShapesCSG< ShapeA, ShapeB >::Space
Definition at line 81 of file DigitalShapesDecorator.h.
Member Enumeration Documentation
e_operator
template<typename ShapeA , typename ShapeB > enum DGtal::DigitalShapesCSG::e_operator protected
Enumerator
e_plus
e_intersection
e_minus
Definition at line 70 of file DigitalShapesDecorator.h.
     {
       e_plus,
       e_intersection,
       e_minus
     };
Constructor & Destructor Documentation
DigitalShapesCSG() [1/3]
template<typename ShapeA , typename ShapeB > DGtal::DigitalShapesCSG< ShapeA, ShapeB >::DigitalShapesCSG () inline
Default constructor. DigitalShapesCSG will be not valid without setParams(ShapeA).
Definition at line 88 of file DigitalShapesDecorator.h.
       : bIsValid(false)
     {}
DigitalShapesCSG() [2/3]
template<typename ShapeA , typename ShapeB > DGtal::DigitalShapesCSG< ShapeA, ShapeB >::DigitalShapesCSG (const DigitalShapesCSG< ShapeA, ShapeB > & other) inline
Copy constructor.
Parameters
[in] other a DigitalShapesCSG to copy
Definition at line 97 of file DigitalShapesDecorator.h.
       : myShapeA(other.myShapeA), v_shapes(other.v_shapes),
         myLowerBound(other.myLowerBound), myUpperBound(other.myUpperBound),
         bIsValid(other.bIsValid)
     {}
DigitalShapesCSG() [3/3]
template<typename ShapeA , typename ShapeB > DGtal::DigitalShapesCSG< ShapeA, ShapeB >::DigitalShapesCSG (ConstAlias< ShapeA > a) inline
Constructor. DigitalShapesCSG will be valid.
Parameters
[in] a a model of CDigitalBoundedShape and CDigitalOrientedShape
Definition at line 109 of file DigitalShapesDecorator.h.
       : myShapeA( a )
     {
       myLowerBound = myShapeA->getLowerBound();
       myUpperBound = myShapeA->getUpperBound();
       bIsValid = true;
     }
References DGtal::DigitalShapesCSG< ShapeA, ShapeB >::bIsValid, DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myLowerBound, DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myShapeA, and DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myUpperBound.
Member Function Documentation
BOOST_CONCEPT_ASSERT() [1/2]
template<typename ShapeA , typename ShapeB > DGtal::DigitalShapesCSG< ShapeA, ShapeB >::BOOST_CONCEPT_ASSERT ((concepts::CDigitalBoundedShape< ShapeA >))
Referenced by DGtal::DigitalShapesCSG< ShapeA, ShapeB >::intersection(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::minus(), and DGtal::DigitalShapesCSG< ShapeA, ShapeB >::plus().
BOOST_CONCEPT_ASSERT() [2/2]
template<typename ShapeA , typename ShapeB > DGtal::DigitalShapesCSG< ShapeA, ShapeB >::BOOST_CONCEPT_ASSERT ((concepts::CDigitalOrientedShape< ShapeA >))
getLowerBound()
template<typename ShapeA , typename ShapeB > Point DGtal::DigitalShapesCSG< ShapeA, ShapeB >::getLowerBound () const inline
Returns
the lower bound of the shape bounding box.
Definition at line 224 of file DigitalShapesDecorator.h.
     {
       FATAL_ERROR_MSG( isValid(), "Operation invalid. Maybe you don't set a ShapeA object." );
       return myLowerBound;
     }
References DGtal::DigitalShapesCSG< ShapeA, ShapeB >::isValid(), and DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myLowerBound.
getUpperBound()
template<typename ShapeA , typename ShapeB > Point DGtal::DigitalShapesCSG< ShapeA, ShapeB >::getUpperBound () const inline
Returns
the upper bound of the shape bounding box.
Definition at line 235 of file DigitalShapesDecorator.h.
     {
       FATAL_ERROR_MSG( isValid(), "Operation invalid. Maybe you don't set a ShapeA object." );
       return myUpperBound;
     }
References DGtal::DigitalShapesCSG< ShapeA, ShapeB >::isValid(), and DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myUpperBound.
intersection()
template<typename ShapeA , typename ShapeB > void DGtal::DigitalShapesCSG< ShapeA, ShapeB >::intersection (ConstAlias< ShapeB > b) inline
Intersection between a (ShapeA) and b (ShapeB). If an operation was already set, the intersection will be between the CSG shape and b (ShapeB).
Parameters
[in] b a ShapeB, model of CDigitalBoundedShape and CDigitalOrientedShape
Definition at line 183 of file DigitalShapesDecorator.h.
     {
       BOOST_CONCEPT_ASSERT (( concepts::CDigitalBoundedShape< ShapeB > ));
       BOOST_CONCEPT_ASSERT (( concepts::CDigitalOrientedShape< ShapeB > ));
       FATAL_ERROR_MSG( isValid(), "Operation invalid. Maybe you don't set a ShapeA object." );
       std::pair<e_operator, CountedConstPtrOrConstPtr< ShapeB > > shape( e_intersection, b );
       for(Dimension i=0; i < Space::dimension; ++i)
       {
         myLowerBound[i] = std::max(myLowerBound[i], b->getLowerBound()[i]);
         myUpperBound[i] = std::min(myUpperBound[i], b->getUpperBound()[i]);
       }
       v_shapes.push_back(shape);
     }
References DGtal::DigitalShapesCSG< ShapeA, ShapeB >::BOOST_CONCEPT_ASSERT(), DGtal::SpaceND< dim, TInteger >::dimension, DGtal::DigitalShapesCSG< ShapeA, ShapeB >::e_intersection, DGtal::DigitalShapesCSG< ShapeA, ShapeB >::isValid(), max(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myLowerBound, DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myUpperBound, and DGtal::DigitalShapesCSG< ShapeA, ShapeB >::v_shapes.
isValid()
template<typename ShapeA , typename ShapeB > bool DGtal::DigitalShapesCSG< ShapeA, ShapeB >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 316 of file DigitalShapesDecorator.h.
     {
       return bIsValid;
     }
References DGtal::DigitalShapesCSG< ShapeA, ShapeB >::bIsValid.
Referenced by DGtal::DigitalShapesCSG< ShapeA, ShapeB >::getLowerBound(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::getUpperBound(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::intersection(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::minus(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::orientation(), and DGtal::DigitalShapesCSG< ShapeA, ShapeB >::plus().
minus()
template<typename ShapeA , typename ShapeB > void DGtal::DigitalShapesCSG< ShapeA, ShapeB >::minus (ConstAlias< ShapeB > b) inline
Minus between a (ShapeA) and b (ShapeB). If an operation was already set, the minus will be between the CSG shape and b (ShapeB).
Parameters
[in] b a ShapeB, model of CDigitalBoundedShape and CDigitalOrientedShape
Definition at line 207 of file DigitalShapesDecorator.h.
     {
       BOOST_CONCEPT_ASSERT (( concepts::CDigitalBoundedShape< ShapeB > ));
       BOOST_CONCEPT_ASSERT (( concepts::CDigitalOrientedShape< ShapeB > ));
       FATAL_ERROR_MSG( isValid(), "Operation invalid. Maybe you don't set a ShapeA object." );
       std::pair<e_operator, CountedConstPtrOrConstPtr< ShapeB > > shape( e_minus, b );
       v_shapes.push_back(shape);
     }
References DGtal::DigitalShapesCSG< ShapeA, ShapeB >::BOOST_CONCEPT_ASSERT(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::e_minus, DGtal::DigitalShapesCSG< ShapeA, ShapeB >::isValid(), and DGtal::DigitalShapesCSG< ShapeA, ShapeB >::v_shapes.
operator=()
template<typename ShapeA , typename ShapeB > DigitalShapesCSG& DGtal::DigitalShapesCSG< ShapeA, ShapeB >::operator= (const DigitalShapesCSG< ShapeA, ShapeB > & other) inline
Copy operator.
Parameters
[in] other a DigitalShapesCSG to copy
Returns
this
Definition at line 125 of file DigitalShapesDecorator.h.
     {
       myShapeA = other.myShapeA;
       v_shapes = other.v_shapes;
       myLowerBound = other.myLowerBound;
       myUpperBound = other.myUpperBound;
       bIsValid = other.bIsValid;
       return *this;
     }
References DGtal::DigitalShapesCSG< ShapeA, ShapeB >::bIsValid, DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myLowerBound, DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myShapeA, DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myUpperBound, and DGtal::DigitalShapesCSG< ShapeA, ShapeB >::v_shapes.
orientation()
template<typename ShapeA , typename ShapeB > Orientation DGtal::DigitalShapesCSG< ShapeA, ShapeB >::orientation (const Point & p) const inline
Return the orientation of a point with respect to a shape. Resolve all operations done with operators in the order they are set.
Parameters
[in] p input point
Returns
the orientation of the point (0 = INSIDE, 1 = ON, 2 = OUTSIDE)
e_plus
Definition at line 250 of file DigitalShapesDecorator.h.
     {
       FATAL_ERROR_MSG( isValid(), "Operation invalid. Maybe you don't set a ShapeA object." );
       Orientation orient = myShapeA->orientation( p );
       for(unsigned int i = 0; i < v_shapes.size(); ++i)
       {
         if( v_shapes[i].first == e_minus )
         {
           if (( v_shapes[i].second->orientation( p ) == INSIDE ) || ( v_shapes[i].second->orientation( p ) == ON ))
           {
             orient = OUTSIDE;
           }
         }
         else if( v_shapes[i].first == e_intersection )
         {
           if (( orient == ON ) && ( v_shapes[i].second->orientation( p ) != OUTSIDE ))
           {
             orient = ON;
           }
           else if (( v_shapes[i].second->orientation( p ) == ON ) && ( orient != OUTSIDE ))
           {
             orient = ON;
           }
           else if (( orient == INSIDE ) && ( v_shapes[i].second->orientation( p ) == INSIDE ))
           {
             orient = INSIDE;
           }
           else
           {
             orient = OUTSIDE;
           }
         }
         else
         {
           if (( orient == INSIDE ) || ( v_shapes[i].second->orientation( p ) == INSIDE ))
           {
             orient = INSIDE;
           }
           else if (( orient == ON ) || ( v_shapes[i].second->orientation( p ) == ON ))
           {
             orient = ON;
           }
           else
           {
             orient = OUTSIDE;
           }
         }
       }
       return orient;
     }
References DGtal::DigitalShapesCSG< ShapeA, ShapeB >::e_intersection, DGtal::DigitalShapesCSG< ShapeA, ShapeB >::e_minus, DGtal::INSIDE, DGtal::DigitalShapesCSG< ShapeA, ShapeB >::isValid(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myShapeA, DGtal::ON, DGtal::OUTSIDE, and DGtal::DigitalShapesCSG< ShapeA, ShapeB >::v_shapes.
plus()
template<typename ShapeA , typename ShapeB > void DGtal::DigitalShapesCSG< ShapeA, ShapeB >::plus (ConstAlias< ShapeB > b) inline
Union between a shape (ShapeA, gived at construction) and b (ShapeB). If an operation was already set, the union will be between the CSG shape and b (ShapeB).
Parameters
[in] b a ShapeB, model of CDigitalBoundedShape and CDigitalOrientedShape
Definition at line 159 of file DigitalShapesDecorator.h.
     {
       BOOST_CONCEPT_ASSERT (( concepts::CDigitalBoundedShape< ShapeB > ));
       BOOST_CONCEPT_ASSERT (( concepts::CDigitalOrientedShape< ShapeB > ));
       FATAL_ERROR_MSG( isValid(), "Operation invalid. Maybe you don't set a ShapeA object." );
       std::pair<e_operator, CountedConstPtrOrConstPtr< ShapeB > > shape( e_plus, b );
       for(Dimension i =0; i < Space::dimension; ++i)
       {
         myLowerBound[i] = std::min(myLowerBound[i], b->getLowerBound()[i]);
         myUpperBound[i] = std::max(myUpperBound[i], b->getUpperBound()[i]);
       }
       v_shapes.push_back(shape);
     }
References DGtal::DigitalShapesCSG< ShapeA, ShapeB >::BOOST_CONCEPT_ASSERT(), DGtal::SpaceND< dim, TInteger >::dimension, DGtal::DigitalShapesCSG< ShapeA, ShapeB >::e_plus, DGtal::DigitalShapesCSG< ShapeA, ShapeB >::isValid(), max(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myLowerBound, DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myUpperBound, and DGtal::DigitalShapesCSG< ShapeA, ShapeB >::v_shapes.
selfDisplay()
template<typename ShapeA , typename ShapeB > void DGtal::DigitalShapesCSG< ShapeA, ShapeB >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
setParams()
template<typename ShapeA , typename ShapeB > void DGtal::DigitalShapesCSG< ShapeA, ShapeB >::setParams (ConstAlias< ShapeA > a) inline
Add a (unique) ShapeA for the CSG computation. DigitalShapesCSG will be valid after. If a ShapeA was already set, the previous one will be override.
Parameters
[in] a a ShapeA, model of CDigitalBoundedShape and CDigitalOrientedShape
Definition at line 143 of file DigitalShapesDecorator.h.
     {
       myShapeA = a;
       myLowerBound = myShapeA->getLowerBound();
       myUpperBound = myShapeA->getUpperBound();
       bIsValid = true;
     }
References DGtal::DigitalShapesCSG< ShapeA, ShapeB >::bIsValid, DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myLowerBound, DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myShapeA, and DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myUpperBound.
Field Documentation
bIsValid
template<typename ShapeA , typename ShapeB > bool DGtal::DigitalShapesCSG< ShapeA, ShapeB >::bIsValid private
if the CSG is valid.
Definition at line 337 of file DigitalShapesDecorator.h.
Referenced by DGtal::DigitalShapesCSG< ShapeA, ShapeB >::DigitalShapesCSG(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::isValid(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::operator=(), and DGtal::DigitalShapesCSG< ShapeA, ShapeB >::setParams().
myLowerBound
template<typename ShapeA , typename ShapeB > Point DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myLowerBound private
Domain lower bound.
Definition at line 331 of file DigitalShapesDecorator.h.
Referenced by DGtal::DigitalShapesCSG< ShapeA, ShapeB >::DigitalShapesCSG(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::getLowerBound(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::intersection(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::operator=(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::plus(), and DGtal::DigitalShapesCSG< ShapeA, ShapeB >::setParams().
myShapeA
template<typename ShapeA , typename ShapeB > CountedConstPtrOrConstPtr< ShapeA > DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myShapeA private
Base Shape.
Definition at line 325 of file DigitalShapesDecorator.h.
Referenced by DGtal::DigitalShapesCSG< ShapeA, ShapeB >::DigitalShapesCSG(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::operator=(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::orientation(), and DGtal::DigitalShapesCSG< ShapeA, ShapeB >::setParams().
myUpperBound
template<typename ShapeA , typename ShapeB > Point DGtal::DigitalShapesCSG< ShapeA, ShapeB >::myUpperBound private
Domain upper bound.
Definition at line 334 of file DigitalShapesDecorator.h.
Referenced by DGtal::DigitalShapesCSG< ShapeA, ShapeB >::DigitalShapesCSG(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::getUpperBound(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::intersection(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::operator=(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::plus(), and DGtal::DigitalShapesCSG< ShapeA, ShapeB >::setParams().
v_shapes
template<typename ShapeA , typename ShapeB > std::vector< std::pair<e_operator, CountedConstPtrOrConstPtr< ShapeB > > > DGtal::DigitalShapesCSG< ShapeA, ShapeB >::v_shapes private
Vector of all operations (ordered) of ShapeB.
Definition at line 328 of file DigitalShapesDecorator.h.
Referenced by DGtal::DigitalShapesCSG< ShapeA, ShapeB >::intersection(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::minus(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::operator=(), DGtal::DigitalShapesCSG< ShapeA, ShapeB >::orientation(), and DGtal::DigitalShapesCSG< ShapeA, ShapeB >::plus().
The documentation for this class was generated from the following file:
DigitalShapesDecorator.h