DGtal: DGtal::functors::SCellToIncidentPoints< KSpace > Class Template Reference
DGtal::functors::SCellToIncidentPoints< KSpace > Class Template Reference
Aim: transforms a signed cell c into a pair of points corresponding to the signed cells of greater dimension that are indirectly and directly incident to c.
#include <DGtal/topology/SCellsFunctors.h>
Public Types
typedef KSpace::Point Point
typedef std::pair< Point, Point > Output
typedef KSpace::SCell Input
Public Member Functions
SCellToIncidentPoints ()
SCellToIncidentPoints (ConstAlias< KSpace > aK)
SCellToIncidentPoints (const SCellToIncidentPoints &other)
SCellToIncidentPoints & operator= (const SCellToIncidentPoints &other)
Output operator() (const Input &s) const
Private Attributes
const KSpace * myK
Detailed Description
template<typename KSpace>
class DGtal::functors::SCellToIncidentPoints< KSpace >
Aim: transforms a signed cell c into a pair of points corresponding to the signed cells of greater dimension that are indirectly and directly incident to c.
Description of template class 'SCellToIncidentPoints'
For instance, a linel is mapped into the pair of incident pixel centers and a surfel is mapped into the pair of incident voxel centers.
Template Parameters
KSpace the Khalimsky space
See also
SCellToInnerPoint SCellToOuterPoint ConstIteratorAdapter KhalimskySpaceND PointVector
Examples
geometry/volumes/distance/exampleFMM3D.cpp, and tutorial-examples/FMMErosion.cpp.
Definition at line 474 of file SCellsFunctors.h.
Member Typedef Documentation
Input
template<typename KSpace > typedef KSpace::SCell DGtal::functors::SCellToIncidentPoints< KSpace >::Input
Definition at line 481 of file SCellsFunctors.h.
Output
template<typename KSpace > typedef std::pair<Point,Point> DGtal::functors::SCellToIncidentPoints< KSpace >::Output
Definition at line 480 of file SCellsFunctors.h.
Point
template<typename KSpace > typedef KSpace::Point DGtal::functors::SCellToIncidentPoints< KSpace >::Point
Definition at line 479 of file SCellsFunctors.h.
Constructor & Destructor Documentation
SCellToIncidentPoints() [1/3]
template<typename KSpace > DGtal::functors::SCellToIncidentPoints< KSpace >::SCellToIncidentPoints () inline
Default constructor.
Definition at line 494 of file SCellsFunctors.h.
 : myK(NULL) { }
SCellToIncidentPoints() [2/3]
template<typename KSpace > DGtal::functors::SCellToIncidentPoints< KSpace >::SCellToIncidentPoints (ConstAlias< KSpace > aK) inline
Constructor.
Parameters
aK a Khalimsky space
Definition at line 499 of file SCellsFunctors.h.
 : myK(&aK) { }
SCellToIncidentPoints() [3/3]
template<typename KSpace > DGtal::functors::SCellToIncidentPoints< KSpace >::SCellToIncidentPoints (const SCellToIncidentPoints< KSpace > & other) inline
Copy constructor.
Parameters
other any SCellToIncidentPoints functor
Definition at line 505 of file SCellsFunctors.h.
     : myK(other.myK) { }
Member Function Documentation
operator()()
template<typename KSpace > Output DGtal::functors::SCellToIncidentPoints< KSpace >::operator() (const Input & s) const inline
Get a pair of point (integer coordinates) from a scell (khalimsky coordinates)
Parameters
s a linel
Returns
the pair of points
Definition at line 527 of file SCellsFunctors.h.
     {
       ASSERT( myK );
       //inner point
       Input innerPixel( myK->sDirectIncident( s, *myK->sOrthDirs( s ) ) );
       //outer point
       Input outerPixel( myK->sIndirectIncident( s, *myK->sOrthDirs( s ) ) );
       return Output(myK->sCoords( innerPixel ),myK->sCoords( outerPixel ));
     }
References DGtal::functors::SCellToIncidentPoints< KSpace >::myK, DGtal::KhalimskySpaceND< dim, TInteger >::sCoords(), DGtal::KhalimskySpaceND< dim, TInteger >::sDirectIncident(), DGtal::KhalimskySpaceND< dim, TInteger >::sIndirectIncident(), and DGtal::KhalimskySpaceND< dim, TInteger >::sOrthDirs().
operator=()
template<typename KSpace > SCellToIncidentPoints& DGtal::functors::SCellToIncidentPoints< KSpace >::operator= (const SCellToIncidentPoints< KSpace > & other) inline
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'.
Definition at line 513 of file SCellsFunctors.h.
     {
       if (this != &other)
         {
           myK = other.myK;
         }
       return *this;
     }
References DGtal::functors::SCellToIncidentPoints< KSpace >::myK.
Field Documentation
myK
template<typename KSpace > const KSpace* DGtal::functors::SCellToIncidentPoints< KSpace >::myK private
Aliasing pointer on the Khalimsky space.
Definition at line 487 of file SCellsFunctors.h.
Referenced by DGtal::functors::SCellToIncidentPoints< KSpace >::operator()(), and DGtal::functors::SCellToIncidentPoints< KSpace >::operator=().
The documentation for this class was generated from the following file:
SCellsFunctors.h