DGtal: DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor > Class Template Reference
DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor > Class Template Reference
Aim: model of CConstBidirectionalRangeFromPoint that adapts any range of elements bounded by two iterators [itb, ite) and provides services to (circularly)iterate over it (in a read-only manner).
#include <DGtal/base/SimpleRandomAccessConstRangeFromPoint.h>
Public Types
typedef DistanceFunctor::Point Point
typedef TConstIterator ConstIterator
typedef std::reverse_iterator< ConstIterator > ConstReverseIterator
typedef Circulator< ConstIterator > ConstCirculator
typedef std::reverse_iterator< ConstCirculator > ConstReverseCirculator
Public Member Functions
SimpleRandomAccessConstRangeFromPoint (const TConstIterator &itb, const TConstIterator &ite, const DistanceFunctor &aDistance)
SimpleRandomAccessConstRangeFromPoint (const SimpleRandomAccessConstRangeFromPoint &other)
SimpleRandomAccessConstRangeFromPoint & operator= (const SimpleRandomAccessConstRangeFromPoint &other)
~SimpleRandomAccessConstRangeFromPoint ()
bool isValid () const
void selfDisplay (std::ostream &out) const
std::string className () const
ConstIterator begin () const
ConstIterator begin (const Point &aPoint) const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rbegin (const Point &aPoint) const
ConstReverseIterator rend () const
ConstCirculator c () const
ConstReverseCirculator rc () const
Private Member Functions
BOOST_CONCEPT_ASSERT ((boost::RandomAccessIterator< TConstIterator >))
BOOST_CONCEPT_ASSERT ((boost::UnaryFunction< DistanceFunctor, typename DistanceFunctor::Difference, typename DistanceFunctor::Point >))
Private Attributes
TConstIterator myBegin
TConstIterator myEnd
DistanceFunctor myDistance
Detailed Description
template<typename TConstIterator, typename DistanceFunctor>
class DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >
Aim: model of CConstBidirectionalRangeFromPoint that adapts any range of elements bounded by two iterators [itb, ite) and provides services to (circularly)iterate over it (in a read-only manner).
Template Parameters
TConstIterator the type of the iterator to adapt (at least bidirectional)
DistanceFunctor type of distance from point functor for random access container models. Models must have a Point and a Difference inner types. operator() returns a number of type Difference on instances of Point)
See also
ConstRangeAdapter
Definition at line 73 of file SimpleRandomAccessConstRangeFromPoint.h.
Member Typedef Documentation
ConstCirculator
template<typename TConstIterator , typename DistanceFunctor > typedef Circulator<ConstIterator> DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::ConstCirculator
Definition at line 89 of file SimpleRandomAccessConstRangeFromPoint.h.
ConstIterator
template<typename TConstIterator , typename DistanceFunctor > typedef TConstIterator DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::ConstIterator
Definition at line 86 of file SimpleRandomAccessConstRangeFromPoint.h.
ConstReverseCirculator
template<typename TConstIterator , typename DistanceFunctor > typedef std::reverse_iterator<ConstCirculator> DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::ConstReverseCirculator
Definition at line 90 of file SimpleRandomAccessConstRangeFromPoint.h.
ConstReverseIterator
template<typename TConstIterator , typename DistanceFunctor > typedef std::reverse_iterator<ConstIterator> DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::ConstReverseIterator
Definition at line 87 of file SimpleRandomAccessConstRangeFromPoint.h.
Point
template<typename TConstIterator , typename DistanceFunctor > typedef DistanceFunctor::Point DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::Point
Definition at line 84 of file SimpleRandomAccessConstRangeFromPoint.h.
Constructor & Destructor Documentation
SimpleRandomAccessConstRangeFromPoint() [1/2]
template<typename TConstIterator , typename DistanceFunctor > DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::SimpleRandomAccessConstRangeFromPoint (const TConstIterator & itb, const TConstIterator & ite, const DistanceFunctor & aDistance) inline
Standard constructor from two iterators and one functor.
Parameters
itb begin iterator.
ite end iterator.
aDistance functor used to adapt on-the-fly the elements of the range
Definition at line 102 of file SimpleRandomAccessConstRangeFromPoint.h.
           : myBegin ( itb ), myEnd ( ite ), myDistance ( aDistance ) {}
SimpleRandomAccessConstRangeFromPoint() [2/2]
template<typename TConstIterator , typename DistanceFunctor > DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::SimpleRandomAccessConstRangeFromPoint (const SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor > & other) inline
Copy constructor.
Parameters
other the iterator to clone.
Definition at line 109 of file SimpleRandomAccessConstRangeFromPoint.h.
           : myBegin ( other.myBegin ), myEnd ( other.myEnd ), myDistance ( other.myDistance ) {}
~SimpleRandomAccessConstRangeFromPoint()
template<typename TConstIterator , typename DistanceFunctor > DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::~SimpleRandomAccessConstRangeFromPoint () inline
Destructor. Does nothing.
Definition at line 132 of file SimpleRandomAccessConstRangeFromPoint.h.
 {}
Member Function Documentation
begin() [1/2]
template<typename TConstIterator , typename DistanceFunctor > ConstIterator DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::begin () const inline
Iterator service.
Returns
begin iterator
Definition at line 191 of file SimpleRandomAccessConstRangeFromPoint.h.
       {
         return ConstIterator ( myBegin );
       }
References DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::myBegin.
Referenced by DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::c(), SECTION(), testImage(), and testImageFromSet().
begin() [2/2]
template<typename TConstIterator , typename DistanceFunctor > ConstIterator DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::begin (const Point & aPoint) const inline
Iterator service.
Parameters
aPoint a Point
Returns
begin iterator
Definition at line 202 of file SimpleRandomAccessConstRangeFromPoint.h.
       {
         return ConstIterator ( myBegin ) + myDistance ( aPoint );
       }
References aPoint(), DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::myBegin, and DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::myDistance.
BOOST_CONCEPT_ASSERT() [1/2]
template<typename TConstIterator , typename DistanceFunctor > DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::BOOST_CONCEPT_ASSERT ((boost::RandomAccessIterator< TConstIterator >)) private
BOOST_CONCEPT_ASSERT() [2/2]
template<typename TConstIterator , typename DistanceFunctor > DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::BOOST_CONCEPT_ASSERT ((boost::UnaryFunction< DistanceFunctor, typename DistanceFunctor::Difference, typename DistanceFunctor::Point >)) private
c()
template<typename TConstIterator , typename DistanceFunctor > ConstCirculator DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::c () const inline
Circulator service.
Returns
a circulator
Definition at line 249 of file SimpleRandomAccessConstRangeFromPoint.h.
       {
         return ConstCirculator ( this->begin(), this->begin(), this->end() );
       }
References DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::begin(), and DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::end().
Referenced by DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::rc(), and SECTION().
className()
template<typename TConstIterator , typename DistanceFunctor > std::string DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::className () const inline
Returns
the style name used for drawing this object.
Definition at line 160 of file SimpleRandomAccessConstRangeFromPoint.h.
       {
         return "SimpleRandomAccessConstRangeFromPoint";
       }
end()
template<typename TConstIterator , typename DistanceFunctor > ConstIterator DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::end () const inline
Iterator service.
Returns
end iterator
Definition at line 211 of file SimpleRandomAccessConstRangeFromPoint.h.
       {
         return ConstIterator ( myEnd );
       }
References DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::myEnd.
Referenced by DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::c(), DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::rbegin(), SECTION(), testImage(), and testImageFromSet().
isValid()
template<typename TConstIterator , typename DistanceFunctor > bool DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 138 of file SimpleRandomAccessConstRangeFromPoint.h.
       {
         return true;
       }
operator=()
template<typename TConstIterator , typename DistanceFunctor > SimpleRandomAccessConstRangeFromPoint& DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::operator= (const SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor > & other) inline
Assignment.
Parameters
other the iterator to copy.
Returns
a reference on 'this'.
Definition at line 117 of file SimpleRandomAccessConstRangeFromPoint.h.
       {
         if ( this != &other )
         {
           myBegin = other.myBegin;
           myEnd = other.myEnd;
           myDistance = other.myDistance;
         }
         return *this;
       }
References DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::myBegin, DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::myDistance, and DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::myEnd.
rbegin() [1/2]
template<typename TConstIterator , typename DistanceFunctor > ConstReverseIterator DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::rbegin () const inline
Iterator service.
Returns
rbegin iterator
Definition at line 220 of file SimpleRandomAccessConstRangeFromPoint.h.
       {
         return ConstReverseIterator ( this->end() );
       }
References DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::end().
Referenced by SECTION().
rbegin() [2/2]
template<typename TConstIterator , typename DistanceFunctor > ConstReverseIterator DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::rbegin (const Point & aPoint) const inline
Iterator service.
Parameters
aPoint a Point
Returns
rbegin iterator
Definition at line 230 of file SimpleRandomAccessConstRangeFromPoint.h.
       {
         return ConstReverseIterator ( myBegin + myDistance ( aPoint ) + 1 );
       }
References aPoint(), DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::myBegin, and DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::myDistance.
rc()
template<typename TConstIterator , typename DistanceFunctor > ConstReverseCirculator DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::rc () const inline
Circulator service.
Returns
a reverse circulator
Definition at line 258 of file SimpleRandomAccessConstRangeFromPoint.h.
       {
         return ConstReverseCirculator ( this->c() );
       }
References DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::c().
Referenced by SECTION().
rend()
template<typename TConstIterator , typename DistanceFunctor > ConstReverseIterator DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::rend () const inline
Iterator service.
Returns
rend iterator
Definition at line 240 of file SimpleRandomAccessConstRangeFromPoint.h.
       {
         return ConstReverseIterator ( myBegin );
       }
References DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::myBegin.
Referenced by SECTION().
selfDisplay()
template<typename TConstIterator , typename DistanceFunctor > void DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 148 of file SimpleRandomAccessConstRangeFromPoint.h.
       {
         typedef typename IteratorCirculatorTraits<ConstIterator>::Value Value;
         out << "[SimpleRandomAccessConstRangeFromPoint]" << std::endl;
         out << "\t";
         std::copy ( myBegin, myEnd, std::ostream_iterator<Value> ( out, ", " ) );
         out << std::endl;
       }
References DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::myBegin, and DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::myEnd.
Field Documentation
myBegin
template<typename TConstIterator , typename DistanceFunctor > TConstIterator DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::myBegin private
Begin underlying iterator
Definition at line 172 of file SimpleRandomAccessConstRangeFromPoint.h.
Referenced by DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::begin(), DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::operator=(), DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::rbegin(), DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::rend(), and DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::selfDisplay().
myDistance
template<typename TConstIterator , typename DistanceFunctor > DistanceFunctor DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::myDistance private
Underlying distance function
Definition at line 181 of file SimpleRandomAccessConstRangeFromPoint.h.
Referenced by DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::begin(), DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::operator=(), and DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::rbegin().
myEnd
template<typename TConstIterator , typename DistanceFunctor > TConstIterator DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::myEnd private
End underlying iterator
Definition at line 176 of file SimpleRandomAccessConstRangeFromPoint.h.
Referenced by DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::end(), DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::operator=(), and DGtal::SimpleRandomAccessConstRangeFromPoint< TConstIterator, DistanceFunctor >::selfDisplay().
The documentation for this class was generated from the following file:
SimpleRandomAccessConstRangeFromPoint.h