DGtal: DGtal::Astroid2D< TSpace > Class Template Reference
DGtal::Astroid2D< TSpace > Class Template Reference
Aim: Model of the concept StarShaped represents an astroid.
#include <DGtal/shapes/parametric/Astroid2D.h>
Public Types
typedef TSpace Space
typedef Space::RealPoint RealPoint
typedef Space::RealVector RealVector
Public Types inherited from DGtal::StarShaped2D< TSpace >
typedef TSpace Space
typedef Space::RealPoint RealPoint
Public Member Functions
Astroid2D ()=delete
Astroid2D (const double x0, const double y0, const double a, const double b)
Astroid2D (const RealPoint &aPoint, const double a, const double b)
Astroid2D (const Astroid2D &other)
Astroid2D & operator= (const Astroid2D &other)=delete
~Astroid2D ()=default
RealPoint getLowerBound () const
RealPoint getUpperBound () const
RealPoint center () const
void moveTo (const RealPoint &newCenter)
double parameter (const RealPoint &p) const
RealPoint x (const double t) const
RealVector xp (const double t) const
RealVector xpp (const double t) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Public Member Functions inherited from DGtal::StarShaped2D< TSpace >
StarShaped2D ()=default
StarShaped2D (const StarShaped2D &other)=delete
StarShaped2D & operator= (const StarShaped2D &other)=delete
virtual ~StarShaped2D ()=default
virtual RealPoint interiorPoint () const
Orientation orientation (const RealPoint &p) const
RealPoint tangent (const double t) const
RealPoint normal (const double t) const
double curvature (const double t) const
double arclength (const double t1, double t2, const unsigned int nb) const
RealPoint findIntersection (const RealPoint &inner, const RealPoint &outer, const double epsilon) const
RealPoint closestPointWithWitnesses (const RealPoint &p, const RealPoint &left, const RealPoint &right, const int step) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Private Member Functions
template<typename T >
bool isAlmostEqual (T x, T y) const
Private Attributes
RealPoint myCenter
double myA
double myB
Detailed Description
template<typename TSpace>
class DGtal::Astroid2D< TSpace >
Aim: Model of the concept StarShaped represents an astroid.
Description of template class 'Astroid2D'
Definition at line 61 of file Astroid2D.h.
Member Typedef Documentation
RealPoint
template<typename TSpace > typedef Space::RealPoint DGtal::Astroid2D< TSpace >::RealPoint
Definition at line 67 of file Astroid2D.h.
RealVector
template<typename TSpace > typedef Space::RealVector DGtal::Astroid2D< TSpace >::RealVector
Definition at line 68 of file Astroid2D.h.
Space
template<typename TSpace > typedef TSpace DGtal::Astroid2D< TSpace >::Space
Definition at line 66 of file Astroid2D.h.
Constructor & Destructor Documentation
Astroid2D() [1/4]
template<typename TSpace > DGtal::Astroid2D< TSpace >::Astroid2D () delete
Constructor. Forbidden by default.
Astroid2D() [2/4]
template<typename TSpace > DGtal::Astroid2D< TSpace >::Astroid2D (const double x0, const double y0, const double a, const double b)
Constructor. The absolute value of radii parameters is used.
Parameters
x0 the x-coordinate of the astroid center.
y0 the y-coordinate of the astroid center.
a coefficient along x-axis
b coefficient along y-axis
Astroid2D() [3/4]
template<typename TSpace > DGtal::Astroid2D< TSpace >::Astroid2D (const RealPoint & aPoint, const double a, const double b)
Constructor. The absolute value of radii parameters is used.
Parameters
aPoint the astroid center
a coefficient along x-axis
b coefficient along y-axis
Astroid2D() [4/4]
template<typename TSpace > DGtal::Astroid2D< TSpace >::Astroid2D (const Astroid2D< TSpace > & other)
Copy constructor.
Parameters
other the object to clone.
~Astroid2D()
template<typename TSpace > DGtal::Astroid2D< TSpace >::~Astroid2D () default
Destructor.
Member Function Documentation
center()
template<typename TSpace > RealPoint DGtal::Astroid2D< TSpace >::center () const inline virtual
Returns
the center of the star-shaped object.
Implements DGtal::StarShaped2D< TSpace >.
Definition at line 139 of file Astroid2D.h.
     {
       return myCenter;
     }
Referenced by TEST_CASE().
getLowerBound()
template<typename TSpace > RealPoint DGtal::Astroid2D< TSpace >::getLowerBound () const inline virtual
Returns
the lower bound of the shape bounding box.
Implements DGtal::StarShaped2D< TSpace >.
Definition at line 122 of file Astroid2D.h.
     {
       return RealPoint( myCenter[0] - myA, myCenter[1] - myB );
     }
Referenced by digitize(), laplacian(), TEST_CASE(), and testDigitization().
getUpperBound()
template<typename TSpace > RealPoint DGtal::Astroid2D< TSpace >::getUpperBound () const inline virtual
Returns
the upper bound of the shape bounding box.
Implements DGtal::StarShaped2D< TSpace >.
Definition at line 131 of file Astroid2D.h.
     {
       return RealPoint( myCenter[0] + myA, myCenter[1] + myB );
     }
Referenced by digitize(), laplacian(), TEST_CASE(), and testDigitization().
isAlmostEqual()
template<typename TSpace > template<typename T > bool DGtal::Astroid2D< TSpace >::isAlmostEqual (T x, T y) const inline private
Equality test using relative tolerance.
Definition at line 229 of file Astroid2D.h.
     {
       return std::abs(x - y) <= std::numeric_limits<T>::epsilon();
     }
isValid()
template<typename TSpace > bool DGtal::Astroid2D< TSpace >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
moveTo()
template<typename TSpace > void DGtal::Astroid2D< TSpace >::moveTo (const RealPoint & newCenter) inline virtual
Modify the shape center
Parameters
newCenter the new center position
Implements DGtal::StarShaped2D< TSpace >.
Definition at line 149 of file Astroid2D.h.
     {
       myCenter = newCenter;
     }
operator=()
template<typename TSpace > Astroid2D& DGtal::Astroid2D< TSpace >::operator= (const Astroid2D< TSpace > & other) delete
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
parameter()
template<typename TSpace > double DGtal::Astroid2D< TSpace >::parameter (const RealPoint & p) const virtual
Parameters
p any point in the plane.
Returns
the angle parameter between 0 and 2*Pi corresponding to this point for the shape.
Implements DGtal::StarShaped2D< TSpace >.
Referenced by TEST_CASE().
selfDisplay()
template<typename TSpace > void DGtal::Astroid2D< TSpace >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
x()
template<typename TSpace > RealPoint DGtal::Astroid2D< TSpace >::x (const double t) const virtual
Parameters
t any angle between 0 and 2*Pi.
Returns
the vector (x(t),y(t)) which is the position on the shape boundary.
Implements DGtal::StarShaped2D< TSpace >.
Referenced by TEST_CASE().
xp()
template<typename TSpace > RealVector DGtal::Astroid2D< TSpace >::xp (const double t) const virtual
Parameters
t any angle between 0 and 2*Pi.
Returns
the vector (x'(t),y'(t)) which is the tangent to the shape boundary.
Implements DGtal::StarShaped2D< TSpace >.
Referenced by TEST_CASE().
xpp()
template<typename TSpace > RealVector DGtal::Astroid2D< TSpace >::xpp (const double t) const virtual
Parameters
t any angle between 0 and 2*Pi.
Returns
the vector (x''(t),y''(t)).
Implements DGtal::StarShaped2D< TSpace >.
Field Documentation
myA
template<typename TSpace > double DGtal::Astroid2D< TSpace >::myA private
Coefficient along x-axis
Definition at line 198 of file Astroid2D.h.
Referenced by DGtal::Astroid2D< Space >::getLowerBound(), and DGtal::Astroid2D< Space >::getUpperBound().
myB
template<typename TSpace > double DGtal::Astroid2D< TSpace >::myB private
Coefficient along y-axis
Definition at line 203 of file Astroid2D.h.
Referenced by DGtal::Astroid2D< Space >::getLowerBound(), and DGtal::Astroid2D< Space >::getUpperBound().
myCenter
template<typename TSpace > RealPoint DGtal::Astroid2D< TSpace >::myCenter private
Center of the circle.
Definition at line 193 of file Astroid2D.h.
Referenced by DGtal::Astroid2D< Space >::center(), DGtal::Astroid2D< Space >::getLowerBound(), DGtal::Astroid2D< Space >::getUpperBound(), and DGtal::Astroid2D< Space >::moveTo().
The documentation for this class was generated from the following file:
Astroid2D.h