DGtal: DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX > Class Template Reference
DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX > Class Template Reference
#include <DGtal/math/MPolynomial.h>
Public Types
typedef TRing Ring
typedef TAlloc Alloc
typedef TX X
typedef MPolynomial< n, Ring, Alloc > MPolyN
typedef MPolynomial< n - 1, X, typename Alloc::template rebind< X >::other > MPolyNM1
Public Member Functions
operator MPolyNM1 () const
template<typename XX >
MPolynomialEvaluatorImpl< n - 1, Ring, MPolynomialEvaluator< n, Ring, Alloc, X >, Alloc, XX > operator() (const XX &x) const
Private Member Functions
MPolynomialEvaluator (const MPolyN &poly, const X &evalpoint)
template<typename XX , typename Fun >
void evaluate (XX &res, const Fun &evalfun) const
Private Attributes
const MPolyN & myPoly
The polynomial in question.
const X & myEvalPoint
the evaluation point
Friends
class MPolynomial< n, TRing, TAlloc >
template<int nn, class TT , class HLHL , class AA , class SS >
class MPolynomialEvaluatorImpl
Detailed Description
template<int n, typename TRing, typename TAlloc, typename TX>
class DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >
The top level polynomial evaluation class, in case n > 1, i.e. in case the coefficients are polynomials by themselves.
This class is a backport from Spielwiese.
Definition at line 400 of file MPolynomial.h.
Member Typedef Documentation
Alloc
template<int n, typename TRing , typename TAlloc , typename TX > typedef TAlloc DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::Alloc
Definition at line 409 of file MPolynomial.h.
MPolyN
template<int n, typename TRing , typename TAlloc , typename TX > typedef MPolynomial< n, Ring, Alloc > DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::MPolyN
Definition at line 411 of file MPolynomial.h.
MPolyNM1
template<int n, typename TRing , typename TAlloc , typename TX > typedef MPolynomial< n - 1, X, typename Alloc::template rebind<X>::other > DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::MPolyNM1
Definition at line 413 of file MPolynomial.h.
Ring
template<int n, typename TRing , typename TAlloc , typename TX > typedef TRing DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::Ring
Definition at line 408 of file MPolynomial.h.
X
template<int n, typename TRing , typename TAlloc , typename TX > typedef TX DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::X
Definition at line 410 of file MPolynomial.h.
Constructor & Destructor Documentation
MPolynomialEvaluator()
template<int n, typename TRing , typename TAlloc , typename TX > DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::MPolynomialEvaluator (const MPolyN & poly, const X & evalpoint) inline private
Definition at line 419 of file MPolynomial.h.
         : myPoly( poly ), myEvalPoint( evalpoint )
     {}
Member Function Documentation
evaluate()
template<int n, typename TRing , typename TAlloc , typename TX > template<typename XX , typename Fun > void DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::evaluate (XX & res, const Fun & evalfun) const inline private
Will be called by "child". Evaluates the polynomial into an element of XX (which must not necessarily be X, it can also be MPolynomial<k, X> for some k < n - 1) using the given functor to evaluate the coefficients, which are of type MPolynomial<n-1, Ring>.
Definition at line 431 of file MPolynomial.h.
     {
       X xx = (X) 1;
       for ( int i = 0; i < (int) myPoly.myValue.size(); ++i )
         {
           res += evalfun( myPoly.myValue[i] ) * xx;
           xx = xx * myEvalPoint;
         }
     }
References DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::myEvalPoint, DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::myPoly, DGtal::MPolynomial< n, TRing, TAlloc >::myValue, and DGtal::IVector< T, TAlloc, usePointers >::size().
operator MPolyNM1()
template<int n, typename TRing , typename TAlloc , typename TX > DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::operator MPolyNM1 () const inline
Evaluate to polynomial of type MPolynomial< n-1, X>.
Definition at line 446 of file MPolynomial.h.
     {
       MPolyNM1 res( myPoly.getAllocator() );
       X xx = (X) 1;
       for ( int i = 0; i < (int) myPoly.myValue.size(); ++i )
         {
           res += MPolyNM1( myPoly.myValue[i] ) * xx;
           xx = xx * myEvalPoint;
         }
       return res;
     }
References DGtal::MPolynomial< n, TRing, TAlloc >::getAllocator(), DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::myEvalPoint, DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::myPoly, DGtal::MPolynomial< n, TRing, TAlloc >::myValue, and DGtal::IVector< T, TAlloc, usePointers >::size().
operator()()
template<int n, typename TRing , typename TAlloc , typename TX > template<typename XX > MPolynomialEvaluatorImpl< n - 1, Ring, MPolynomialEvaluator< n, Ring, Alloc, X >, Alloc, XX > DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::operator() (const XX & x) const inline
Continue evaluation to lower level.
Definition at line 465 of file MPolynomial.h.
     {
       return MPolynomialEvaluatorImpl
         < n - 1, Ring, MPolynomialEvaluator< n, Ring, Alloc, X >, Alloc, XX >
         ( *this, x );
     }
Friends And Related Function Documentation
MPolynomial< n, TRing, TAlloc >
template<int n, typename TRing , typename TAlloc , typename TX > friend class MPolynomial< n, TRing, TAlloc > friend
Definition at line 384 of file MPolynomial.h.
MPolynomialEvaluatorImpl
template<int n, typename TRing , typename TAlloc , typename TX > template<int nn, class TT , class HLHL , class AA , class SS > friend class MPolynomialEvaluatorImpl friend
Definition at line 405 of file MPolynomial.h.
Field Documentation
myEvalPoint
template<int n, typename TRing , typename TAlloc , typename TX > const X& DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::myEvalPoint private
the evaluation point
Definition at line 416 of file MPolynomial.h.
Referenced by DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::evaluate(), DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::operator MPolyNM1(), and DGtal::MPolynomialEvaluator< 1, TRing, TAlloc, TX >::operator X().
myPoly
template<int n, typename TRing , typename TAlloc , typename TX > const MPolyN& DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::myPoly private
The polynomial in question.
Definition at line 415 of file MPolynomial.h.
Referenced by DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::evaluate(), DGtal::MPolynomialEvaluator< n, TRing, TAlloc, TX >::operator MPolyNM1(), and DGtal::MPolynomialEvaluator< 1, TRing, TAlloc, TX >::operator X().
The documentation for this class was generated from the following file:
MPolynomial.h