DGtal: DGtal::functors::SCellToCode< KSpace > Class Template Reference
DGtal::functors::SCellToCode< KSpace > Class Template Reference
Aim: transforms a 2d signed cell, basically a linel, into a code (0,1,2 or 3),.
#include <DGtal/topology/SCellsFunctors.h>
Public Types
typedef KSpace::Point Point
typedef KSpace::Vector Vector
typedef char Output
typedef KSpace::SCell Input
Public Member Functions
SCellToCode ()
SCellToCode (ConstAlias< KSpace > aK)
SCellToCode (const SCellToCode &other)
SCellToCode & operator= (const SCellToCode &other)
Output operator() (const Input &s) const
Private Member Functions
BOOST_STATIC_ASSERT (KSpace::dimension==2)
Private Attributes
const KSpace * myK
Detailed Description
template<typename KSpace>
class DGtal::functors::SCellToCode< KSpace >
Aim: transforms a 2d signed cell, basically a linel, into a code (0,1,2 or 3),.
Description of template class 'SCellToCode'
Template Parameters
KSpace the 2d Khalimsky space
See also
ConstIteratorAdapter KhalimskySpaceND
Definition at line 550 of file SCellsFunctors.h.
Member Typedef Documentation
Input
template<typename KSpace > typedef KSpace::SCell DGtal::functors::SCellToCode< KSpace >::Input
Definition at line 561 of file SCellsFunctors.h.
Output
template<typename KSpace > typedef char DGtal::functors::SCellToCode< KSpace >::Output
Definition at line 559 of file SCellsFunctors.h.
Point
template<typename KSpace > typedef KSpace::Point DGtal::functors::SCellToCode< KSpace >::Point
Definition at line 557 of file SCellsFunctors.h.
Vector
template<typename KSpace > typedef KSpace::Vector DGtal::functors::SCellToCode< KSpace >::Vector
Definition at line 558 of file SCellsFunctors.h.
Constructor & Destructor Documentation
SCellToCode() [1/3]
template<typename KSpace > DGtal::functors::SCellToCode< KSpace >::SCellToCode () inline
Default constructor.
Definition at line 574 of file SCellsFunctors.h.
 : myK(NULL) { }
SCellToCode() [2/3]
template<typename KSpace > DGtal::functors::SCellToCode< KSpace >::SCellToCode (ConstAlias< KSpace > aK) inline
Constructor.
Parameters
aK a Khalimsky space
Definition at line 579 of file SCellsFunctors.h.
 : myK(&aK) { }
SCellToCode() [3/3]
template<typename KSpace > DGtal::functors::SCellToCode< KSpace >::SCellToCode (const SCellToCode< KSpace > & other) inline
Copy constructor.
Parameters
other any SCellToCode modifier
Definition at line 585 of file SCellsFunctors.h.
     : myK(other.myK) { }
Member Function Documentation
BOOST_STATIC_ASSERT()
template<typename KSpace > DGtal::functors::SCellToCode< KSpace >::BOOST_STATIC_ASSERT (KSpace::dimension = =2) private
operator()()
template<typename KSpace > Output DGtal::functors::SCellToCode< KSpace >::operator() (const Input & s) const inline
Return a code from a linel
Parameters
s a linel
Returns
the corresponding code
Definition at line 607 of file SCellsFunctors.h.
     {
       ASSERT( myK );
       //starting point of the arrow
       Input pointel( myK->sIndirectIncident( s, *myK->sDirs( s ) ) );
       Point p( myK->sCoords( pointel ) );   //integer coordinates
       //displacement vector
       Vector v( myK->sKCoords( s ) - myK->sKCoords( pointel ) );
       if (v == Vector(1,0)) return '0';
       else if (v == Vector(0,1)) return '1';
       else if (v == Vector(-1,0)) return '2';
       else if (v == Vector(0,-1)) return '3';
       else return 'e'; //e for error!
     }
References DGtal::functors::SCellToCode< KSpace >::myK, DGtal::KhalimskySpaceND< dim, TInteger >::sCoords(), DGtal::KhalimskySpaceND< dim, TInteger >::sDirs(), DGtal::KhalimskySpaceND< dim, TInteger >::sIndirectIncident(), and DGtal::KhalimskySpaceND< dim, TInteger >::sKCoords().
operator=()
template<typename KSpace > SCellToCode& DGtal::functors::SCellToCode< KSpace >::operator= (const SCellToCode< KSpace > & other) inline
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'.
Definition at line 593 of file SCellsFunctors.h.
     {
       if (this != &other)
         {
           myK = other.myK;
         }
       return *this;
     }
References DGtal::functors::SCellToCode< KSpace >::myK.
Field Documentation
myK
template<typename KSpace > const KSpace* DGtal::functors::SCellToCode< KSpace >::myK private
Aliasing pointer on the Khalimsky space.
Definition at line 567 of file SCellsFunctors.h.
Referenced by DGtal::functors::SCellToCode< KSpace >::operator()(), and DGtal::functors::SCellToCode< KSpace >::operator=().
The documentation for this class was generated from the following file:
SCellsFunctors.h