DGtal: DGtal::EuclideanShapesCSG< ShapeA, ShapeB > Class Template Reference
DGtal::EuclideanShapesCSG< ShapeA, ShapeB > Class Template Reference
Aim: Constructive Solid Geometry (CSG) between models of CEuclideanBoundedShape and CEuclideanOrientedShape Use CSG operation (union, intersection, minus) from a shape of Type ShapeA with one (or more) shapes of Type ShapeB. Can combine differents operations. Limitations: Since we don't have a class derived by all shapes, operations can be done by only one type of shapes. Use CSG of CSG to go beyond this limitation.
#include <DGtal/shapes/EuclideanShapesDecorator.h>
Public Types
typedef ShapeA::Space Space
typedef ShapeA::RealPoint RealPoint
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CEuclideanBoundedShape< ShapeA >))
BOOST_CONCEPT_ASSERT ((concepts::CEuclideanOrientedShape< ShapeA >))
EuclideanShapesCSG ()
EuclideanShapesCSG (const EuclideanShapesCSG &other)
EuclideanShapesCSG (ConstAlias< ShapeA > a)
EuclideanShapesCSG & operator= (const EuclideanShapesCSG &other)
void setParams (ConstAlias< ShapeA > a)
void plus (ConstAlias< ShapeB > b)
void intersection (ConstAlias< ShapeB > b)
void minus (ConstAlias< ShapeB > b)
RealPoint getLowerBound () const
RealPoint getUpperBound () const
Orientation orientation (const RealPoint &p) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Protected Types
enum e_operator { e_plus, e_intersection, e_minus }
Private Attributes
CountedConstPtrOrConstPtr< ShapeA > myShapeA
Base Shape.
std::vector< std::pair< e_operator, CountedConstPtrOrConstPtr< ShapeB > > > v_shapes
Vector of all operations (ordered) of ShapeB.
RealPoint myLowerBound
Domain lower bound.
RealPoint myUpperBound
Domain upper bound.
bool bIsValid
if the CSG is valid.
Detailed Description
template<typename ShapeA, typename ShapeB>
class DGtal::EuclideanShapesCSG< ShapeA, ShapeB >
Aim: Constructive Solid Geometry (CSG) between models of CEuclideanBoundedShape and CEuclideanOrientedShape Use CSG operation (union, intersection, minus) from a shape of Type ShapeA with one (or more) shapes of Type ShapeB. Can combine differents operations. Limitations: Since we don't have a class derived by all shapes, operations can be done by only one type of shapes. Use CSG of CSG to go beyond this limitation.
Description of template class 'EuclideanShapesCSG'
Template Parameters
ShapeA type of a first shape. Must be a model of CEuclideanBoundedShape and CEuclideanOrientedShape
ShapeB type of a second shape. Must be a model of CEuclideanBoundedShape and CEuclideanOrientedShape
Examples
shapes/exampleEuclideanShapesDecorator.cpp.
Definition at line 67 of file EuclideanShapesDecorator.h.
Member Typedef Documentation
RealPoint
template<typename ShapeA , typename ShapeB > typedef ShapeA::RealPoint DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::RealPoint
Definition at line 82 of file EuclideanShapesDecorator.h.
Space
template<typename ShapeA , typename ShapeB > typedef ShapeA::Space DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::Space
Definition at line 81 of file EuclideanShapesDecorator.h.
Member Enumeration Documentation
e_operator
template<typename ShapeA , typename ShapeB > enum DGtal::EuclideanShapesCSG::e_operator protected
Enumerator
e_plus
e_intersection
e_minus
Definition at line 70 of file EuclideanShapesDecorator.h.
     {
       e_plus,
       e_intersection,
       e_minus
     };
Constructor & Destructor Documentation
EuclideanShapesCSG() [1/3]
template<typename ShapeA , typename ShapeB > DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::EuclideanShapesCSG () inline
Default constructor. EuclideanShapesCSG will be not valid without setParams(ShapeA).
Definition at line 88 of file EuclideanShapesDecorator.h.
       : bIsValid(false)
     {}
EuclideanShapesCSG() [2/3]
template<typename ShapeA , typename ShapeB > DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::EuclideanShapesCSG (const EuclideanShapesCSG< ShapeA, ShapeB > & other) inline
Copy constructor.
Parameters
[in] other a EuclideanShapesCSG to copy
Definition at line 97 of file EuclideanShapesDecorator.h.
       : myShapeA(other.myShapeA), v_shapes(other.v_shapes),
         myLowerBound(other.myLowerBound), myUpperBound(other.myUpperBound),
         bIsValid(other.bIsValid)
     {}
EuclideanShapesCSG() [3/3]
template<typename ShapeA , typename ShapeB > DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::EuclideanShapesCSG (ConstAlias< ShapeA > a) inline
Constructor. EuclideanShapesCSG will be valid.
Parameters
[in] a a model of CEuclideanBoundedShape and CEuclideanOrientedShape
Definition at line 108 of file EuclideanShapesDecorator.h.
       : myShapeA( a )
     {
       myLowerBound = myShapeA->getLowerBound();
       myUpperBound = myShapeA->getUpperBound();
       bIsValid = true;
     }
References DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::bIsValid, DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myLowerBound, DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myShapeA, and DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myUpperBound.
Member Function Documentation
BOOST_CONCEPT_ASSERT() [1/2]
template<typename ShapeA , typename ShapeB > DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::BOOST_CONCEPT_ASSERT ((concepts::CEuclideanBoundedShape< ShapeA >))
Referenced by DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::intersection(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::minus(), and DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::plus().
BOOST_CONCEPT_ASSERT() [2/2]
template<typename ShapeA , typename ShapeB > DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::BOOST_CONCEPT_ASSERT ((concepts::CEuclideanOrientedShape< ShapeA >))
getLowerBound()
template<typename ShapeA , typename ShapeB > RealPoint DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::getLowerBound () const inline
Returns
the lower bound of the shape bounding box.
Definition at line 222 of file EuclideanShapesDecorator.h.
     {
       FATAL_ERROR_MSG( isValid(), "Operation invalid. Maybe you don't set a ShapeA object." );
       return myLowerBound;
     }
References DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::isValid(), and DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myLowerBound.
getUpperBound()
template<typename ShapeA , typename ShapeB > RealPoint DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::getUpperBound () const inline
Returns
the upper bound of the shape bounding box.
Definition at line 233 of file EuclideanShapesDecorator.h.
     {
       FATAL_ERROR_MSG( isValid(), "Operation invalid. Maybe you don't set a ShapeA object." );
       return myUpperBound;
     }
References DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::isValid(), and DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myUpperBound.
intersection()
template<typename ShapeA , typename ShapeB > void DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::intersection (ConstAlias< ShapeB > b) inline
Intersection between a (ShapeA) and b (ShapeB). If an operation was already set, the intersection will be between the CSG shape and b (ShapeB).
Parameters
[in] b a ShapeB, model of CEuclideanBoundedShape and CEuclideanOrientedShape
Definition at line 182 of file EuclideanShapesDecorator.h.
     {
       BOOST_CONCEPT_ASSERT (( concepts::CEuclideanBoundedShape< ShapeB > ));
       BOOST_CONCEPT_ASSERT (( concepts::CEuclideanOrientedShape< ShapeB > ));
       FATAL_ERROR_MSG( isValid(), "Operation invalid. Maybe you don't set a ShapeA object." );
       std::pair<e_operator, CountedConstPtrOrConstPtr< ShapeB > > shape( e_intersection, b );
       for(Dimension i=0; i < Space::dimension; ++i)
       {
         myLowerBound[i] = std::max(myLowerBound[i], b->getLowerBound()[i]);
         myUpperBound[i] = std::min(myUpperBound[i], b->getUpperBound()[i]);
       }
       v_shapes.push_back(shape);
     }
References DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::BOOST_CONCEPT_ASSERT(), DGtal::SpaceND< dim, TInteger >::dimension, DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::e_intersection, DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::isValid(), max(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myLowerBound, DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myUpperBound, and DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::v_shapes.
isValid()
template<typename ShapeA , typename ShapeB > bool DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 314 of file EuclideanShapesDecorator.h.
     {
       return bIsValid;
     }
References DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::bIsValid.
Referenced by DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::getLowerBound(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::getUpperBound(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::intersection(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::minus(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::orientation(), and DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::plus().
minus()
template<typename ShapeA , typename ShapeB > void DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::minus (ConstAlias< ShapeB > b) inline
Minus between a (ShapeA) and b (ShapeB). If an operation was already set, the minus will be between the CSG shape and b (ShapeB).
Parameters
[in] b a ShapeB, model of CEuclideanBoundedShape and CEuclideanOrientedShape
Definition at line 206 of file EuclideanShapesDecorator.h.
     {
       BOOST_CONCEPT_ASSERT (( concepts::CEuclideanBoundedShape< ShapeB > ));
       BOOST_CONCEPT_ASSERT (( concepts::CEuclideanOrientedShape< ShapeB > ));
       FATAL_ERROR_MSG( isValid(), "Operation invalid. Maybe you don't set a ShapeA object." );
       std::pair<e_operator, CountedConstPtrOrConstPtr< ShapeB > > shape( e_minus, b );
       v_shapes.push_back(shape);
     }
References DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::BOOST_CONCEPT_ASSERT(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::e_minus, DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::isValid(), and DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::v_shapes.
operator=()
template<typename ShapeA , typename ShapeB > EuclideanShapesCSG& DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::operator= (const EuclideanShapesCSG< ShapeA, ShapeB > & other) inline
Copy operator.
Parameters
[in] other a EuclideanShapesCSG to copy
Returns
this
Definition at line 124 of file EuclideanShapesDecorator.h.
     {
       myShapeA = other.myShapeA;
       v_shapes = other.v_shapes;
       myLowerBound = other.myLowerBound;
       myUpperBound = other.myUpperBound;
       bIsValid = other.bIsValid;
       return *this;
     }
References DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::bIsValid, DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myLowerBound, DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myShapeA, DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myUpperBound, and DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::v_shapes.
orientation()
template<typename ShapeA , typename ShapeB > Orientation DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::orientation (const RealPoint & p) const inline
Return the orientation of a point with respect to a shape. Resolve all operations done with operators in the order they are set.
Parameters
[in] p input point
Returns
the orientation of the point (0 = INSIDE, 1 = ON, 2 = OUTSIDE)
e_plus
Definition at line 248 of file EuclideanShapesDecorator.h.
     {
       FATAL_ERROR_MSG( isValid(), "Operation invalid. Maybe you don't set a ShapeA object." );
       Orientation orient = myShapeA->orientation( p );
       for(unsigned int i = 0; i < v_shapes.size(); ++i)
       {
         if( v_shapes[i].first == e_minus )
         {
           if (( v_shapes[i].second->orientation( p ) == INSIDE ) || ( v_shapes[i].second->orientation( p ) == ON ))
           {
             orient = OUTSIDE;
           }
         }
         else if( v_shapes[i].first == e_intersection )
         {
           if (( orient == ON ) && ( v_shapes[i].second->orientation( p ) != OUTSIDE ))
           {
             orient = ON;
           }
           else if (( v_shapes[i].second->orientation( p ) == ON ) && ( orient != OUTSIDE ))
           {
             orient = ON;
           }
           else if (( orient == INSIDE ) && ( v_shapes[i].second->orientation( p ) == INSIDE ))
           {
             orient = INSIDE;
           }
           else
           {
             orient = OUTSIDE;
           }
         }
         else
         {
           if (( orient == INSIDE ) || ( v_shapes[i].second->orientation( p ) == INSIDE ))
           {
             orient = INSIDE;
           }
           else if (( orient == ON ) || ( v_shapes[i].second->orientation( p ) == ON ))
           {
             orient = ON;
           }
           else
           {
             orient = OUTSIDE;
           }
         }
       }
       return orient;
     }
References DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::e_intersection, DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::e_minus, DGtal::INSIDE, DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::isValid(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myShapeA, DGtal::ON, DGtal::OUTSIDE, and DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::v_shapes.
plus()
template<typename ShapeA , typename ShapeB > void DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::plus (ConstAlias< ShapeB > b) inline
Union between a shape (ShapeA, gived at construction) and b (ShapeB). If an operation was already set, the union will be between the CSG shape and b (ShapeB).
Parameters
[in] b a ShapeB, model of CEuclideanBoundedShape and CEuclideanOrientedShape
Definition at line 158 of file EuclideanShapesDecorator.h.
     {
       BOOST_CONCEPT_ASSERT (( concepts::CEuclideanBoundedShape< ShapeB > ));
       BOOST_CONCEPT_ASSERT (( concepts::CEuclideanOrientedShape< ShapeB > ));
       FATAL_ERROR_MSG( isValid(), "Operation invalid. Maybe you don't set a ShapeA object." );
       std::pair<e_operator, CountedConstPtrOrConstPtr< ShapeB > > shape( e_plus, b );
       for(Dimension i =0; i < Space::dimension; ++i)
       {
         myLowerBound[i] = std::min(myLowerBound[i], b->getLowerBound()[i]);
         myUpperBound[i] = std::max(myUpperBound[i], b->getUpperBound()[i]);
       }
       v_shapes.push_back(shape);
     }
References DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::BOOST_CONCEPT_ASSERT(), DGtal::SpaceND< dim, TInteger >::dimension, DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::e_plus, DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::isValid(), max(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myLowerBound, DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myUpperBound, and DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::v_shapes.
selfDisplay()
template<typename ShapeA , typename ShapeB > void DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
setParams()
template<typename ShapeA , typename ShapeB > void DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::setParams (ConstAlias< ShapeA > a) inline
Add a (unique) ShapeA for the CSG computation. EuclideanShapesCSG will be valid after. If a ShapeA was already set, the previous one will be override.
Parameters
[in] a a ShapeA, model of CEuclideanBoundedShape and CEuclideanOrientedShape
Definition at line 142 of file EuclideanShapesDecorator.h.
     {
       myShapeA = a;
       myLowerBound = myShapeA->getLowerBound();
       myUpperBound = myShapeA->getUpperBound();
       bIsValid = true;
     }
References DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::bIsValid, DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myLowerBound, DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myShapeA, and DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myUpperBound.
Field Documentation
bIsValid
template<typename ShapeA , typename ShapeB > bool DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::bIsValid private
if the CSG is valid.
Definition at line 335 of file EuclideanShapesDecorator.h.
Referenced by DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::EuclideanShapesCSG(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::isValid(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::operator=(), and DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::setParams().
myLowerBound
template<typename ShapeA , typename ShapeB > RealPoint DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myLowerBound private
Domain lower bound.
Definition at line 329 of file EuclideanShapesDecorator.h.
Referenced by DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::EuclideanShapesCSG(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::getLowerBound(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::intersection(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::operator=(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::plus(), and DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::setParams().
myShapeA
template<typename ShapeA , typename ShapeB > CountedConstPtrOrConstPtr< ShapeA > DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myShapeA private
Base Shape.
Definition at line 323 of file EuclideanShapesDecorator.h.
Referenced by DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::EuclideanShapesCSG(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::operator=(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::orientation(), and DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::setParams().
myUpperBound
template<typename ShapeA , typename ShapeB > RealPoint DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::myUpperBound private
Domain upper bound.
Definition at line 332 of file EuclideanShapesDecorator.h.
Referenced by DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::EuclideanShapesCSG(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::getUpperBound(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::intersection(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::operator=(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::plus(), and DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::setParams().
v_shapes
template<typename ShapeA , typename ShapeB > std::vector< std::pair<e_operator, CountedConstPtrOrConstPtr< ShapeB > > > DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::v_shapes private
Vector of all operations (ordered) of ShapeB.
Definition at line 326 of file EuclideanShapesDecorator.h.
Referenced by DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::intersection(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::minus(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::operator=(), DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::orientation(), and DGtal::EuclideanShapesCSG< ShapeA, ShapeB >::plus().
The documentation for this class was generated from the following file:
EuclideanShapesDecorator.h