DGtal: DGtal::ImplicitRoundedHyperCube< TSpace > Class Template Reference
DGtal::ImplicitRoundedHyperCube< TSpace > Class Template Reference
Aim: model of CEuclideanOrientedShape and CEuclideanBoundedShape concepts to create a rounded hypercube in nD..
#include <DGtal/shapes/implicit/ImplicitRoundedHyperCube.h>
Public Types
typedef ImplicitRoundedHyperCube< TSpace > Self
typedef TSpace Space
typedef Space::RealPoint RealPoint
typedef double Value
Public Member Functions
ImplicitRoundedHyperCube (const RealPoint &aCenter, const double &aHalfWidth, const double aPower)
~ImplicitRoundedHyperCube ()
double operator() (const RealPoint &aPoint) const
bool isInside (const RealPoint &aPoint) const
Orientation orientation (const RealPoint &aPoint) const
RealPoint getLowerBound () const
RealPoint getUpperBound () const
RealPoint center () const
void moveTo (const RealPoint &newCenter)
void selfDisplay (std::ostream &out) const
bool isValid () const
Protected Member Functions
ImplicitRoundedHyperCube ()
Private Member Functions
ImplicitRoundedHyperCube & operator= (const ImplicitRoundedHyperCube &other)
Private Attributes
RealPoint myCenter
Cube center.
double myHalfWidth
Cube HalfWidth.
double myPower
Cube Power.
Detailed Description
template<typename TSpace>
class DGtal::ImplicitRoundedHyperCube< TSpace >
Aim: model of CEuclideanOrientedShape and CEuclideanBoundedShape concepts to create a rounded hypercube in nD..
Description of template class 'ImplicitRoundedHyperCube'
Rounded hypercubes corresponds to balls for the \(l_p\) norm.
Template Parameters
TSpace the Digital space definition.
Definition at line 62 of file ImplicitRoundedHyperCube.h.
Member Typedef Documentation
RealPoint
template<typename TSpace > typedef Space::RealPoint DGtal::ImplicitRoundedHyperCube< TSpace >::RealPoint
Definition at line 68 of file ImplicitRoundedHyperCube.h.
Self
template<typename TSpace > typedef ImplicitRoundedHyperCube<TSpace> DGtal::ImplicitRoundedHyperCube< TSpace >::Self
Definition at line 66 of file ImplicitRoundedHyperCube.h.
Space
template<typename TSpace > typedef TSpace DGtal::ImplicitRoundedHyperCube< TSpace >::Space
Definition at line 67 of file ImplicitRoundedHyperCube.h.
Value
template<typename TSpace > typedef double DGtal::ImplicitRoundedHyperCube< TSpace >::Value
Definition at line 69 of file ImplicitRoundedHyperCube.h.
Constructor & Destructor Documentation
ImplicitRoundedHyperCube() [1/2]
template<typename TSpace > DGtal::ImplicitRoundedHyperCube< TSpace >::ImplicitRoundedHyperCube (const RealPoint & aCenter, const double & aHalfWidth, const double aPower) inline
Constructor. Contructs a rounded hypercube with center aCenter and width aWidth.
Parameters
aCenter the cube center.
aHalfWidth the cube half-width.
aPower the cube power.
Definition at line 79 of file ImplicitRoundedHyperCube.h.
                                                  :
       myCenter(aCenter),
       myHalfWidth(aHalfWidth),
       myPower(aPower)
     {};
~ImplicitRoundedHyperCube()
template<typename TSpace > DGtal::ImplicitRoundedHyperCube< TSpace >::~ImplicitRoundedHyperCube ()
Destructor.
ImplicitRoundedHyperCube() [2/2]
template<typename TSpace > DGtal::ImplicitRoundedHyperCube< TSpace >::ImplicitRoundedHyperCube () protected
Constructor. Forbidden by default (protected to avoid g++ warnings).
Member Function Documentation
center()
template<typename TSpace > RealPoint DGtal::ImplicitRoundedHyperCube< TSpace >::center () const inline
Returns
the center of the star-shaped object.
Definition at line 175 of file ImplicitRoundedHyperCube.h.
     {
       return myCenter;
     }
References DGtal::ImplicitRoundedHyperCube< TSpace >::myCenter.
getLowerBound()
template<typename TSpace > RealPoint DGtal::ImplicitRoundedHyperCube< TSpace >::getLowerBound () const inline
Returns the lower bound of the Shape bounding box.
Returns
the lower bound point.
Definition at line 155 of file ImplicitRoundedHyperCube.h.
     {
       return (myCenter - RealPoint::diagonal(myHalfWidth));
     }
References DGtal::PointVector< dim, TEuclideanRing, TContainer >::diagonal(), DGtal::ImplicitRoundedHyperCube< TSpace >::myCenter, and DGtal::ImplicitRoundedHyperCube< TSpace >::myHalfWidth.
getUpperBound()
template<typename TSpace > RealPoint DGtal::ImplicitRoundedHyperCube< TSpace >::getUpperBound () const inline
Returns the upper bound of the Shape bounding box.
Returns
the upper bound point.
Definition at line 167 of file ImplicitRoundedHyperCube.h.
     {
       return (myCenter + RealPoint::diagonal(myHalfWidth));
     }
References DGtal::PointVector< dim, TEuclideanRing, TContainer >::diagonal(), DGtal::ImplicitRoundedHyperCube< TSpace >::myCenter, and DGtal::ImplicitRoundedHyperCube< TSpace >::myHalfWidth.
isInside()
template<typename TSpace > bool DGtal::ImplicitRoundedHyperCube< TSpace >::isInside (const RealPoint & aPoint) const inline
Return true if the given point belongs to the shape.
Parameters
aPoint the point to evalute the function at.
Returns
true if aPoint belongs to the shape.
Definition at line 123 of file ImplicitRoundedHyperCube.h.
     {
       return this->operator()(aPoint) >0.0;
     }
References DGtal::ImplicitRoundedHyperCube< TSpace >::operator()().
isValid()
template<typename TSpace > bool DGtal::ImplicitRoundedHyperCube< TSpace >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
moveTo()
template<typename TSpace > void DGtal::ImplicitRoundedHyperCube< TSpace >::moveTo (const RealPoint & newCenter) inline
Modify the shape center
Parameters
newCenter the new center position
Definition at line 185 of file ImplicitRoundedHyperCube.h.
     {
       myCenter = newCenter;
     }
References DGtal::ImplicitRoundedHyperCube< TSpace >::myCenter.
operator()()
template<typename TSpace > double DGtal::ImplicitRoundedHyperCube< TSpace >::operator() (const RealPoint & aPoint) const inline
Operator() of the implicit function. Given a point, it returns the function value at p. In Shapes, positive values are used to construct a set.
Parameters
aPoint the point to evalute the function at.
Returns
the distance of aPoint to the ball center.
Definition at line 106 of file ImplicitRoundedHyperCube.h.
     {
       RealPoint dec = (aPoint - myCenter);
       double partialpower=0;
       for(Dimension i = 0; i < RealPoint::dimension; ++i)
         partialpower +=  std::pow(std::abs((double)dec[i]),  myPower);
     return std::pow(myHalfWidth, myPower) - partialpower;
     }
References aPoint(), DGtal::PointVector< dim, TEuclideanRing, TContainer >::dimension, DGtal::ImplicitRoundedHyperCube< TSpace >::myCenter, DGtal::ImplicitRoundedHyperCube< TSpace >::myHalfWidth, and DGtal::ImplicitRoundedHyperCube< TSpace >::myPower.
Referenced by DGtal::ImplicitRoundedHyperCube< TSpace >::isInside().
operator=()
template<typename TSpace > ImplicitRoundedHyperCube& DGtal::ImplicitRoundedHyperCube< TSpace >::operator= (const ImplicitRoundedHyperCube< TSpace > & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
orientation()
template<typename TSpace > Orientation DGtal::ImplicitRoundedHyperCube< TSpace >::orientation (const RealPoint & aPoint) const inline
orientation predicate (see CEuclideanOrientedShape).
Parameters
aPoint an input point.
Returns
the orientation of the point.
Definition at line 136 of file ImplicitRoundedHyperCube.h.
     {
       if (this->operator()(aPoint) > 0.0)
         return INSIDE;
       else
         if (this->operator()(aPoint) < 0.0)
           return OUTSIDE;
         else
           return ON;
     }
References DGtal::INSIDE, DGtal::ON, and DGtal::OUTSIDE.
selfDisplay()
template<typename TSpace > void DGtal::ImplicitRoundedHyperCube< TSpace >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Field Documentation
myCenter
template<typename TSpace > RealPoint DGtal::ImplicitRoundedHyperCube< TSpace >::myCenter private
Cube center.
Definition at line 211 of file ImplicitRoundedHyperCube.h.
Referenced by DGtal::ImplicitRoundedHyperCube< TSpace >::center(), DGtal::ImplicitRoundedHyperCube< TSpace >::getLowerBound(), DGtal::ImplicitRoundedHyperCube< TSpace >::getUpperBound(), DGtal::ImplicitRoundedHyperCube< TSpace >::moveTo(), and DGtal::ImplicitRoundedHyperCube< TSpace >::operator()().
myHalfWidth
template<typename TSpace > double DGtal::ImplicitRoundedHyperCube< TSpace >::myHalfWidth private
Cube HalfWidth.
Definition at line 214 of file ImplicitRoundedHyperCube.h.
Referenced by DGtal::ImplicitRoundedHyperCube< TSpace >::getLowerBound(), DGtal::ImplicitRoundedHyperCube< TSpace >::getUpperBound(), and DGtal::ImplicitRoundedHyperCube< TSpace >::operator()().
myPower
template<typename TSpace > double DGtal::ImplicitRoundedHyperCube< TSpace >::myPower private
Cube Power.
Definition at line 217 of file ImplicitRoundedHyperCube.h.
Referenced by DGtal::ImplicitRoundedHyperCube< TSpace >::operator()().
The documentation for this class was generated from the following file:
ImplicitRoundedHyperCube.h