DGtal: DGtal::Ball2D< TSpace > Class Template Reference
DGtal::Ball2D< TSpace > Class Template Reference final
Aim: Model of the concept StarShaped represents any circle in the plane.
#include <DGtal/shapes/parametric/Ball2D.h>
Public Types
typedef TSpace Space
typedef Space::RealPoint RealPoint
typedef Space::RealVector RealVector
Public Types inherited from DGtal::StarShaped2D< TSpace >
typedef TSpace Space
typedef Space::RealPoint RealPoint
Public Member Functions
Ball2D ()=delete
Ball2D (const double x0, const double y0, const double r)
Ball2D (const RealPoint &aPoint, const double r)
Ball2D (const Ball2D &other)
Ball2D & operator= (const Ball2D &other)=delete
~Ball2D ()=default
RealPoint getLowerBound () const
RealPoint getUpperBound () const
RealPoint center () const
void moveTo (const RealPoint &newCenter)
double parameter (const RealPoint &p) const
RealPoint x (const double t) const
RealVector xp (const double t) const
RealVector xpp (const double t) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Public Member Functions inherited from DGtal::StarShaped2D< TSpace >
StarShaped2D ()=default
StarShaped2D (const StarShaped2D &other)=delete
StarShaped2D & operator= (const StarShaped2D &other)=delete
virtual ~StarShaped2D ()=default
virtual RealPoint interiorPoint () const
Orientation orientation (const RealPoint &p) const
RealPoint tangent (const double t) const
RealPoint normal (const double t) const
double curvature (const double t) const
double arclength (const double t1, double t2, const unsigned int nb) const
RealPoint findIntersection (const RealPoint &inner, const RealPoint &outer, const double epsilon) const
RealPoint closestPointWithWitnesses (const RealPoint &p, const RealPoint &left, const RealPoint &right, const int step) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Private Attributes
double myRadius
RealPoint myCenter
Detailed Description
template<typename TSpace>
class DGtal::Ball2D< TSpace >
Aim: Model of the concept StarShaped represents any circle in the plane.
Description of template class 'Ball2D'
Examples
dec/exampleHeatLaplace.cpp, geometry/curves/estimation/exampleCurvature.cpp, geometry/tools/exampleAlphaShape.cpp, and geometry/tools/exampleConvexHull2D.cpp.
Definition at line 60 of file Ball2D.h.
Member Typedef Documentation
RealPoint
template<typename TSpace > typedef Space::RealPoint DGtal::Ball2D< TSpace >::RealPoint
Definition at line 66 of file Ball2D.h.
RealVector
template<typename TSpace > typedef Space::RealVector DGtal::Ball2D< TSpace >::RealVector
Definition at line 67 of file Ball2D.h.
Space
template<typename TSpace > typedef TSpace DGtal::Ball2D< TSpace >::Space
Definition at line 65 of file Ball2D.h.
Constructor & Destructor Documentation
Ball2D() [1/4]
template<typename TSpace > DGtal::Ball2D< TSpace >::Ball2D () delete
Constructor. Forbidden by default.
Ball2D() [2/4]
template<typename TSpace > DGtal::Ball2D< TSpace >::Ball2D (const double x0, const double y0, const double r)
Constructor.
Parameters
x0 the x-coordinate of the circle center.
y0 the y-coordinate of the circle center.
r the radius of the circle.
Ball2D() [3/4]
template<typename TSpace > DGtal::Ball2D< TSpace >::Ball2D (const RealPoint & aPoint, const double r)
Constructor.
Parameters
aPoint the circle center.
r the radius of the circle.
Ball2D() [4/4]
template<typename TSpace > DGtal::Ball2D< TSpace >::Ball2D (const Ball2D< TSpace > & other)
Copy constructor.
Parameters
other the object to clone.
~Ball2D()
template<typename TSpace > DGtal::Ball2D< TSpace >::~Ball2D () default
Destructor.
Member Function Documentation
center()
template<typename TSpace > RealPoint DGtal::Ball2D< TSpace >::center () const inline virtual
Returns
the center of the star-shaped object.
Implements DGtal::StarShaped2D< TSpace >.
Definition at line 133 of file Ball2D.h.
     {
       return myCenter;
     }
References DGtal::Ball2D< TSpace >::myCenter.
getLowerBound()
template<typename TSpace > RealPoint DGtal::Ball2D< TSpace >::getLowerBound () const inline virtual
Returns
the lower bound of the shape bounding box.
Implements DGtal::StarShaped2D< TSpace >.
Definition at line 116 of file Ball2D.h.
     {
       return myCenter - myRadius;
     }
References DGtal::Ball2D< TSpace >::myCenter, and DGtal::Ball2D< TSpace >::myRadius.
Referenced by alphaShape(), convexHull(), and laplace_sphere().
getUpperBound()
template<typename TSpace > RealPoint DGtal::Ball2D< TSpace >::getUpperBound () const inline virtual
Returns
the upper bound of the shape bounding box.
Implements DGtal::StarShaped2D< TSpace >.
Definition at line 125 of file Ball2D.h.
     {
       return myCenter + myRadius;
     }
References DGtal::Ball2D< TSpace >::myCenter, and DGtal::Ball2D< TSpace >::myRadius.
Referenced by alphaShape(), convexHull(), and laplace_sphere().
isValid()
template<typename TSpace > bool DGtal::Ball2D< TSpace >::isValid () const
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
moveTo()
template<typename TSpace > void DGtal::Ball2D< TSpace >::moveTo (const RealPoint & newCenter) inline virtual
Modify the shape center
Parameters
newCenter the new center position
Implements DGtal::StarShaped2D< TSpace >.
Definition at line 143 of file Ball2D.h.
     {
       myCenter = newCenter;
     }
References DGtal::Ball2D< TSpace >::myCenter.
operator=()
template<typename TSpace > Ball2D& DGtal::Ball2D< TSpace >::operator= (const Ball2D< TSpace > & other) delete
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
parameter()
template<typename TSpace > double DGtal::Ball2D< TSpace >::parameter (const RealPoint & p) const virtual
Parameters
p any point in the plane.
Returns
the angle parameter between 0 and 2*Pi corresponding to this point for the shape.
Implements DGtal::StarShaped2D< TSpace >.
selfDisplay()
template<typename TSpace > void DGtal::Ball2D< TSpace >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
x()
template<typename TSpace > RealPoint DGtal::Ball2D< TSpace >::x (const double t) const virtual
Parameters
t any angle between 0 and 2*Pi.
Returns
the vector (x(t),y(t)) which is the position on the shape boundary.
Implements DGtal::StarShaped2D< TSpace >.
xp()
template<typename TSpace > RealVector DGtal::Ball2D< TSpace >::xp (const double t) const virtual
Parameters
t any angle between 0 and 2*Pi.
Returns
the vector (x'(t),y'(t)) which is the tangent to the shape boundary.
Implements DGtal::StarShaped2D< TSpace >.
xpp()
template<typename TSpace > RealVector DGtal::Ball2D< TSpace >::xpp (const double t) const virtual
Parameters
t any angle between 0 and 2*Pi.
Returns
the vector (x''(t),y''(t)).
Implements DGtal::StarShaped2D< TSpace >.
Field Documentation
myCenter
template<typename TSpace > RealPoint DGtal::Ball2D< TSpace >::myCenter private
Center of the circle.
Definition at line 192 of file Ball2D.h.
Referenced by DGtal::Ball2D< TSpace >::center(), DGtal::Ball2D< TSpace >::getLowerBound(), DGtal::Ball2D< TSpace >::getUpperBound(), and DGtal::Ball2D< TSpace >::moveTo().
myRadius
template<typename TSpace > double DGtal::Ball2D< TSpace >::myRadius private
Radius of the circle.
Definition at line 187 of file Ball2D.h.
Referenced by DGtal::Ball2D< TSpace >::getLowerBound(), and DGtal::Ball2D< TSpace >::getUpperBound().
The documentation for this class was generated from the following file:
Ball2D.h