DGtal: DGtal::OrderedLinearRegression Class Reference
DGtal::OrderedLinearRegression Class Reference
Description of class 'OrderedLinearRegression'.
#include <DGtal/math/OrderedLinearRegression.h>
Public Member Functions
~OrderedLinearRegression ()
OrderedLinearRegression (double eps_zero=1e-8)
void clear ()
template<class XIterator , class YIterator >
void addSamples (XIterator begin_x, XIterator end_x, YIterator begin_y)
void addSample (const double x, const double y)
void forwardSLR (SimpleLinearRegression &linearModel, const unsigned int n=4, const double alpha=0.01) const
void backwardSLR (SimpleLinearRegression &linearModel, const unsigned int n=4, const double alpha=0.01) const
void selfDisplay (std::ostream &that_stream) const
bool isValid () const
Private Member Functions
OrderedLinearRegression (const OrderedLinearRegression &other)
OrderedLinearRegression & operator= (const OrderedLinearRegression &other)
Private Attributes
double myEpsilonZero
Epsilon zero value.
unsigned int myN
Number of samples.
std::vector< double > myY
Ordinate values of sample points.
std::vector< double > myX
Abscissa values of sample points.
Detailed Description
Description of class 'OrderedLinearRegression'.
Aim: Utility based on SimpleLinearRegression to compute regression on ordered data. Hence, we can obtain linear fitting with interval trust from the left to the right (resp. from the right to the left) of the data.
Note
backport from ImaGene.
Definition at line 65 of file OrderedLinearRegression.h.
Constructor & Destructor Documentation
~OrderedLinearRegression()
DGtal::OrderedLinearRegression::~OrderedLinearRegression () inline
Destructor.
Definition at line 73 of file OrderedLinearRegression.h.
     {}
OrderedLinearRegression() [1/2]
DGtal::OrderedLinearRegression::OrderedLinearRegression (double eps_zero = 1e-8) inline
Constructor. The object is empty (and invalid for regression).
Parameters
[in] eps_zero the value below which the absolute value of the determinant is considered null.
Definition at line 83 of file OrderedLinearRegression.h.
                                                      :
       myEpsilonZero(eps_zero),
       myN(0)
     {}
OrderedLinearRegression() [2/2]
DGtal::OrderedLinearRegression::OrderedLinearRegression (const OrderedLinearRegression & other) private
Copy constructor.
Parameters
other the object to clone. Forbidden by default.
Member Function Documentation
addSample()
void DGtal::OrderedLinearRegression::addSample (const double x, const double y) inline
Adds the sample (x,y). Does not compute immediately the regression but copies the data. See 'forwardSLR' or 'backwardSLR' for computing the regression with the current samples.
Parameters
[in] x the x data.
[in] y the y data.
See also
forwardSLR backwardSLR
Definition at line 131 of file OrderedLinearRegression.h.
     {
       myX.push_back( x );
       myY.push_back( y );
       ++myN;
     }
References myN, myX, and myY.
Referenced by addSamples().
addSamples()
template<class XIterator , class YIterator > void DGtal::OrderedLinearRegression::addSamples (XIterator begin_x, XIterator end_x, YIterator begin_y) inline
Adds the samples (x,y). Does not compute immediately the regression but copies the data. See 'forwardSLR' or 'backwardSLR' for computing the regression with the current samples.
Parameters
[in] begin_x an iterator on the first x-data
[in] end_x an iterator after the last x-data
[in] begin_y an iterator on the first y-data
See also
forwardSLR backwardSLR
Definition at line 111 of file OrderedLinearRegression.h.
       {
         for ( ; begin_x != end_x; ++begin_x, ++begin_y )
           {
             addSample( *begin_x, *begin_y );
           }
       }
References addSample().
Referenced by testSimpleRegressionOrdered().
backwardSLR()
void DGtal::OrderedLinearRegression::backwardSLR (SimpleLinearRegression & linearModel, const unsigned int n = 4, const double alpha = 0.01) const inline
Returns the slope of the last straight part of the data. The straightness is evaluated through a statistic test based on a simple linear regression (SLR) model. It requires two parameters: n is the minimum number of samples to fit a linear model, 1-[ alpha] is the proportion of accepted linear model of the test (99%, alpha=0.01, means that 99% of all linear model with a Gaussian noise are accepted).
Parameters
[in] n the minimum number of samples greater than 3 (default value is 4).
[in] alpha is the proportion of rejected linear model (the ones with big variance, default value is 0.01).
[out] linearModel the SLR instance of the last straight part of the data.
Definition at line 200 of file OrderedLinearRegression.h.
     {
       linearModel.setEpsilonZero(myEpsilonZero);
       linearModel.clear();
       std::vector<double>::const_reverse_iterator itx = myX.rbegin();
       std::vector<double>::const_reverse_iterator itxe = myX.rend();
       std::vector<double>::const_reverse_iterator ity = myY.rbegin();
       linearModel.addSamples( itx, itx + n, ity );
       linearModel.computeRegression();
       itx += n;
       ity += n;
       unsigned int l = myX.size() - n + 1;
       for ( ; itx != itxe; ++itx, ++ity, --l )
         {
           std::pair<double,double> ic;
           ic = linearModel.trustIntervalForY( *itx, alpha );
           if ( ( *ity < ic.first ) || ( *ity > ic.second ) )
             break;
           linearModel.addSample( *itx, *ity );
           linearModel.computeRegression();
         }
     }
References DGtal::SimpleLinearRegression::addSample(), DGtal::SimpleLinearRegression::addSamples(), DGtal::SimpleLinearRegression::clear(), DGtal::SimpleLinearRegression::computeRegression(), myEpsilonZero, myX, myY, DGtal::SimpleLinearRegression::setEpsilonZero(), and DGtal::SimpleLinearRegression::trustIntervalForY().
Referenced by testSimpleRegressionOrdered().
clear()
void DGtal::OrderedLinearRegression::clear () inline
Clears the data.
Definition at line 91 of file OrderedLinearRegression.h.
     {
       myX.clear();
       myY.clear();
       myN = 0;
     }
References myN, myX, and myY.
forwardSLR()
void DGtal::OrderedLinearRegression::forwardSLR (SimpleLinearRegression & linearModel, const unsigned int n = 4, const double alpha = 0.01) const inline
Returns the slope of the first straight part of the data. The straightness is evaluated through a statistic test based on a simple linear regression (SLR) model. It requires two parameters: n is the minimum number of samples to fit a linear model, 1-[ alpha] is the proportion of accepted linear model of the test (99%, alpha=0.01, means that 99% of all linear model with a Gaussian noise are accepted).
Parameters
[in] n the minimum number of samples greater than 3 (default value is 4).
[in] alpha is the proportion of rejected linear model (the ones with big variance, default value is 0.01).
[out] linearModel the SLR instance of the first straight part of the data.
Definition at line 157 of file OrderedLinearRegression.h.
     {
       linearModel.setEpsilonZero(myEpsilonZero);
       linearModel.clear();
       std::vector<double>::const_iterator itx = myX.begin();
       std::vector<double>::const_iterator itxe = myX.end();
       std::vector<double>::const_iterator ity = myY.begin();
       linearModel.addSamples( itx, itx + n, ity );
       linearModel.computeRegression();
       itx += n;
       ity += n;
       unsigned int l = myX.size() - n + 1;
       for ( ; itx != itxe; ++itx, ++ity, --l )
         {
           std::pair<double,double> ic;
           ic = linearModel.trustIntervalForY( *itx, alpha );
           if ( ( *ity < ic.first ) || ( *ity > ic.second ) )
             break;
           linearModel.addSample( *itx, *ity );
           linearModel.computeRegression();
         }
     }
References DGtal::SimpleLinearRegression::addSample(), DGtal::SimpleLinearRegression::addSamples(), DGtal::SimpleLinearRegression::clear(), DGtal::SimpleLinearRegression::computeRegression(), myEpsilonZero, myX, myY, DGtal::SimpleLinearRegression::setEpsilonZero(), and DGtal::SimpleLinearRegression::trustIntervalForY().
Referenced by testSimpleRegressionOrdered().
isValid()
bool DGtal::OrderedLinearRegression::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 241 of file OrderedLinearRegression.h.
     {
       return true;
     }
operator=()
OrderedLinearRegression& DGtal::OrderedLinearRegression::operator= (const OrderedLinearRegression & other) private
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'. Forbidden by default.
selfDisplay()
void DGtal::OrderedLinearRegression::selfDisplay (std::ostream & that_stream) const inline
Writes/Displays the object on an output stream.
Parameters
that_stream the output stream where the object is written.
Definition at line 232 of file OrderedLinearRegression.h.
     {
       that_stream << "[OrderedLinearRegression]  Number of samples="<< myN;
     }
References myN.
Field Documentation
myEpsilonZero
double DGtal::OrderedLinearRegression::myEpsilonZero private
Epsilon zero value.
Definition at line 252 of file OrderedLinearRegression.h.
Referenced by backwardSLR(), and forwardSLR().
myN
unsigned int DGtal::OrderedLinearRegression::myN private
Number of samples.
Definition at line 255 of file OrderedLinearRegression.h.
Referenced by addSample(), clear(), and selfDisplay().
myX
std::vector<double> DGtal::OrderedLinearRegression::myX private
Abscissa values of sample points.
Definition at line 261 of file OrderedLinearRegression.h.
Referenced by addSample(), backwardSLR(), clear(), and forwardSLR().
myY
std::vector<double> DGtal::OrderedLinearRegression::myY private
Ordinate values of sample points.
Definition at line 258 of file OrderedLinearRegression.h.
Referenced by addSample(), backwardSLR(), clear(), and forwardSLR().
The documentation for this class was generated from the following file:
OrderedLinearRegression.h