DGtal: DGtal::functors::SCellToArrow< KSpace > Class Template Reference
DGtal::functors::SCellToArrow< KSpace > Class Template Reference
Aim: transforms a signed cell into an arrow, ie. a pair point-vector.
#include <DGtal/topology/SCellsFunctors.h>
Public Types
typedef KSpace::Point Point
typedef KSpace::Vector Vector
typedef std::pair< Point, Vector > Output
typedef KSpace::SCell Input
Public Member Functions
SCellToArrow ()
SCellToArrow (ConstAlias< KSpace > aK)
SCellToArrow (const SCellToArrow &other)
SCellToArrow & operator= (const SCellToArrow &other)
Output operator() (const Input &s) const
Private Attributes
const KSpace * myK
Detailed Description
template<typename KSpace>
class DGtal::functors::SCellToArrow< KSpace >
Aim: transforms a signed cell into an arrow, ie. a pair point-vector.
Description of template class 'SCellToArrow'
Template Parameters
KSpace the Khalimsky space
See also
SCellToPoint ConstIteratorAdapter KhalimskySpaceND PointVector
Definition at line 240 of file SCellsFunctors.h.
Member Typedef Documentation
Input
template<typename KSpace > typedef KSpace::SCell DGtal::functors::SCellToArrow< KSpace >::Input
Definition at line 248 of file SCellsFunctors.h.
Output
template<typename KSpace > typedef std::pair<Point,Vector> DGtal::functors::SCellToArrow< KSpace >::Output
Definition at line 247 of file SCellsFunctors.h.
Point
template<typename KSpace > typedef KSpace::Point DGtal::functors::SCellToArrow< KSpace >::Point
Definition at line 245 of file SCellsFunctors.h.
Vector
template<typename KSpace > typedef KSpace::Vector DGtal::functors::SCellToArrow< KSpace >::Vector
Definition at line 246 of file SCellsFunctors.h.
Constructor & Destructor Documentation
SCellToArrow() [1/3]
template<typename KSpace > DGtal::functors::SCellToArrow< KSpace >::SCellToArrow () inline
Default constructor.
Definition at line 261 of file SCellsFunctors.h.
 : myK(NULL) { }
SCellToArrow() [2/3]
template<typename KSpace > DGtal::functors::SCellToArrow< KSpace >::SCellToArrow (ConstAlias< KSpace > aK) inline
Constructor.
Parameters
aK a Khalimsky space
Definition at line 266 of file SCellsFunctors.h.
 : myK(&aK) { }
SCellToArrow() [3/3]
template<typename KSpace > DGtal::functors::SCellToArrow< KSpace >::SCellToArrow (const SCellToArrow< KSpace > & other) inline
Copy constructor.
Parameters
other any SCellToArrow modifier
Definition at line 272 of file SCellsFunctors.h.
     : myK(other.myK) { }
Member Function Documentation
operator()()
template<typename KSpace > Output DGtal::functors::SCellToArrow< KSpace >::operator() (const Input & s) const inline
Get an arrow, ie a pair point-vector with integer coordinates from a scell in khalimsky coordinates
Parameters
s a scell
Returns
the corresponding point.
Definition at line 295 of file SCellsFunctors.h.
     {
       ASSERT( myK );
       //starting point of the arrow
       Input pointel( myK->sIndirectIncident( s, *myK->sDirs( s ) ) );
       Point p( myK->sCoords( pointel ) );   //integer coordinates
       //displacement vector
       Vector v( myK->sKCoords( s ) - myK->sKCoords( pointel ) );
       return Output(p,v);
     }
References DGtal::functors::SCellToArrow< KSpace >::myK, DGtal::KhalimskySpaceND< dim, TInteger >::sCoords(), DGtal::KhalimskySpaceND< dim, TInteger >::sDirs(), DGtal::KhalimskySpaceND< dim, TInteger >::sIndirectIncident(), and DGtal::KhalimskySpaceND< dim, TInteger >::sKCoords().
operator=()
template<typename KSpace > SCellToArrow& DGtal::functors::SCellToArrow< KSpace >::operator= (const SCellToArrow< KSpace > & other) inline
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'.
Definition at line 280 of file SCellsFunctors.h.
     {
       if (this != &other)
         {
           myK = other.myK;
         }
       return *this;
     }
References DGtal::functors::SCellToArrow< KSpace >::myK.
Field Documentation
myK
template<typename KSpace > const KSpace* DGtal::functors::SCellToArrow< KSpace >::myK private
Aliasing pointer on the Khalimsky space.
Definition at line 254 of file SCellsFunctors.h.
Referenced by DGtal::functors::SCellToArrow< KSpace >::operator()(), and DGtal::functors::SCellToArrow< KSpace >::operator=().
The documentation for this class was generated from the following file:
SCellsFunctors.h