DGtal: DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage > Class Template Reference
DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage > Class Template Reference
Aim: model of CConstBidirectionalRangeFromPoint that adapts a TiledImage range of elements bounded by two iterators [itb, ite) and provides services to (circularly)iterate over it (in a read-only manner).
#include <DGtal/base/TiledImageBidirectionalConstRangeFromPoint.h>
Public Types
typedef TTiledImage TiledImage
typedef TiledImage::Point Point
typedef TiledImage::ConstIterator ConstIterator
typedef std::reverse_iterator< ConstIterator > ConstReverseIterator
typedef Circulator< ConstIterator > ConstCirculator
typedef std::reverse_iterator< ConstCirculator > ConstReverseCirculator
Public Member Functions
TiledImageBidirectionalConstRangeFromPoint (const TiledImage *ti)
TiledImageBidirectionalConstRangeFromPoint (const TiledImageBidirectionalConstRangeFromPoint &other)
TiledImageBidirectionalConstRangeFromPoint & operator= (const TiledImageBidirectionalConstRangeFromPoint &other)
~TiledImageBidirectionalConstRangeFromPoint ()
bool isValid () const
void selfDisplay (std::ostream &out) const
std::string className () const
ConstIterator begin () const
ConstIterator begin (const Point &aPoint) const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rbegin (const Point &aPoint) const
ConstReverseIterator rend () const
ConstCirculator c () const
ConstReverseCirculator rc () const
Private Member Functions
BOOST_CONCEPT_ASSERT ((boost::BidirectionalIterator< typename TTiledImage::ConstIterator >))
Private Attributes
const TTiledImage * myti
Detailed Description
template<typename TTiledImage>
class DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >
Aim: model of CConstBidirectionalRangeFromPoint that adapts a TiledImage range of elements bounded by two iterators [itb, ite) and provides services to (circularly)iterate over it (in a read-only manner).
Template Parameters
TTiledImage the type of the TiledImage with his const iterator to adapt (at least bidirectional)
See also
ConstRangeAdapter
Definition at line 71 of file TiledImageBidirectionalConstRangeFromPoint.h.
Member Typedef Documentation
ConstCirculator
template<typename TTiledImage > typedef Circulator<ConstIterator> DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::ConstCirculator
Definition at line 87 of file TiledImageBidirectionalConstRangeFromPoint.h.
ConstIterator
template<typename TTiledImage > typedef TiledImage::ConstIterator DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::ConstIterator
Definition at line 84 of file TiledImageBidirectionalConstRangeFromPoint.h.
ConstReverseCirculator
template<typename TTiledImage > typedef std::reverse_iterator<ConstCirculator> DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::ConstReverseCirculator
Definition at line 88 of file TiledImageBidirectionalConstRangeFromPoint.h.
ConstReverseIterator
template<typename TTiledImage > typedef std::reverse_iterator<ConstIterator> DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::ConstReverseIterator
Definition at line 85 of file TiledImageBidirectionalConstRangeFromPoint.h.
Point
template<typename TTiledImage > typedef TiledImage::Point DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::Point
Definition at line 82 of file TiledImageBidirectionalConstRangeFromPoint.h.
TiledImage
template<typename TTiledImage > typedef TTiledImage DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::TiledImage
Definition at line 80 of file TiledImageBidirectionalConstRangeFromPoint.h.
Constructor & Destructor Documentation
TiledImageBidirectionalConstRangeFromPoint() [1/2]
template<typename TTiledImage > DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::TiledImageBidirectionalConstRangeFromPoint (const TiledImage * ti) inline
Standard constructor from a TiledImage.
Parameters
ti pointer on a TiledImage.
Definition at line 96 of file TiledImageBidirectionalConstRangeFromPoint.h.
         : myti ( ti ) {}
TiledImageBidirectionalConstRangeFromPoint() [2/2]
template<typename TTiledImage > DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::TiledImageBidirectionalConstRangeFromPoint (const TiledImageBidirectionalConstRangeFromPoint< TTiledImage > & other) inline
Copy constructor.
Parameters
other the iterator to clone.
Definition at line 103 of file TiledImageBidirectionalConstRangeFromPoint.h.
           : myti ( other.myti ) {}
~TiledImageBidirectionalConstRangeFromPoint()
template<typename TTiledImage > DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::~TiledImageBidirectionalConstRangeFromPoint () inline
Destructor. Does nothing.
Definition at line 124 of file TiledImageBidirectionalConstRangeFromPoint.h.
 {}
Member Function Documentation
begin() [1/2]
template<typename TTiledImage > ConstIterator DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::begin () const inline
Iterator service.
Returns
begin iterator
Definition at line 172 of file TiledImageBidirectionalConstRangeFromPoint.h.
       {
         return ConstIterator ( myti->begin() );
       }
References DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::myti.
Referenced by DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::c(), and DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::rend().
begin() [2/2]
template<typename TTiledImage > ConstIterator DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::begin (const Point & aPoint) const inline
Iterator service.
Returns
begin iterator
Definition at line 181 of file TiledImageBidirectionalConstRangeFromPoint.h.
       {
         return ConstIterator ( myti->begin(aPoint) );
       }
References aPoint(), and DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::myti.
BOOST_CONCEPT_ASSERT()
template<typename TTiledImage > DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::BOOST_CONCEPT_ASSERT ((boost::BidirectionalIterator< typename TTiledImage::ConstIterator >)) private
c()
template<typename TTiledImage > ConstCirculator DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::c () const inline
Circulator service.
Returns
a circulator
Definition at line 226 of file TiledImageBidirectionalConstRangeFromPoint.h.
       {
         return ConstCirculator ( this->begin(), this->begin(), this->end() );
       }
References DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::begin(), and DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::end().
Referenced by DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::rc().
className()
template<typename TTiledImage > std::string DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::className () const inline
Returns
the style name used for drawing this object.
Definition at line 152 of file TiledImageBidirectionalConstRangeFromPoint.h.
       {
         return "TiledImageBidirectionalConstRangeFromPoint";
       }
end()
template<typename TTiledImage > ConstIterator DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::end () const inline
Iterator service.
Returns
end iterator
Definition at line 190 of file TiledImageBidirectionalConstRangeFromPoint.h.
       {
         return ConstIterator ( myti->end() );
       }
References DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::myti.
Referenced by DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::c(), and DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::rbegin().
isValid()
template<typename TTiledImage > bool DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::isValid () const inline
Checks the validity/consistency of the object.
Returns
'true' if the object is valid, 'false' otherwise.
Definition at line 130 of file TiledImageBidirectionalConstRangeFromPoint.h.
       {
         return true;
       }
operator=()
template<typename TTiledImage > TiledImageBidirectionalConstRangeFromPoint& DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::operator= (const TiledImageBidirectionalConstRangeFromPoint< TTiledImage > & other) inline
Assignment.
Parameters
other the iterator to copy.
Returns
a reference on 'this'.
Definition at line 111 of file TiledImageBidirectionalConstRangeFromPoint.h.
       {
         if ( this != &other )
         {
           myti = other.myti;
         }
         return *this;
       }
References DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::myti.
rbegin() [1/2]
template<typename TTiledImage > ConstReverseIterator DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::rbegin () const inline
Iterator service.
Returns
rbegin iterator
Definition at line 199 of file TiledImageBidirectionalConstRangeFromPoint.h.
       {
         return ConstReverseIterator ( this->end() );
       }
References DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::end().
rbegin() [2/2]
template<typename TTiledImage > ConstReverseIterator DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::rbegin (const Point & aPoint) const inline
Iterator service.
Returns
rbegin iterator
Definition at line 208 of file TiledImageBidirectionalConstRangeFromPoint.h.
       {
         return ConstReverseIterator ( myti->rbegin(aPoint) );
       }
References aPoint(), and DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::myti.
rc()
template<typename TTiledImage > ConstReverseCirculator DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::rc () const inline
Circulator service.
Returns
a reverse circulator
Definition at line 235 of file TiledImageBidirectionalConstRangeFromPoint.h.
       {
         return ConstReverseCirculator ( this->c() );
       }
References DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::c().
rend()
template<typename TTiledImage > ConstReverseIterator DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::rend () const inline
Iterator service.
Returns
rend iterator
Definition at line 217 of file TiledImageBidirectionalConstRangeFromPoint.h.
       {
         return ConstReverseIterator ( this->begin() );
       }
References DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::begin().
selfDisplay()
template<typename TTiledImage > void DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
Definition at line 140 of file TiledImageBidirectionalConstRangeFromPoint.h.
       {
         typedef typename IteratorCirculatorTraits<ConstIterator>::Value Value;
         out << "[TiledImageBidirectionalConstRangeFromPoint]" << std::endl;
         out << "\t";
         std::copy ( myti->begin(), myti->end(), std::ostream_iterator<Value> ( out, ", " ) );
         out << std::endl;
       }
References DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::myti.
Field Documentation
myti
template<typename TTiledImage > const TTiledImage* DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::myti private
Definition at line 162 of file TiledImageBidirectionalConstRangeFromPoint.h.
Referenced by DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::begin(), DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::end(), DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::operator=(), DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::rbegin(), and DGtal::TiledImageBidirectionalConstRangeFromPoint< TTiledImage >::selfDisplay().
The documentation for this class was generated from the following file:
TiledImageBidirectionalConstRangeFromPoint.h