DGtal: LibBoard::Board Class Reference
LibBoard::Board Class Reference
Class for EPS, FIG or SVG drawings.
#include <Board/Board.h>
Data Structures
struct State
Public Types
enum CairoType {
CairoPDF, CairoPNG, CairoPS, CairoEPS,
CairoSVG
}
enum PageSize { BoundingBox, A4, Letter }
enum Unit { UPoint, UInche, UCentimeter, UMillimeter }
Public Types inherited from LibBoard::Shape
enum LineCap { ButtCap = 0, RoundCap, SquareCap }
enum LineJoin { MiterJoin = 0, RoundJoin, BevelJoin }
enum LineStyle {
SolidStyle = 0, DashStyle, DotStyle, DashDotStyle,
DashDotDotStyle, DashDotDotDotStyle
}
Public Member Functions
Board (const DGtal::Color &backgroundColor=DGtal::Color::None)
Board (const Board &other)
~Board ()
Board & operator= (const Board &other)
Board & operator<< (const Shape &shape)
Board & operator<< (Unit unit)
void clear (const DGtal::Color &color=DGtal::Color::None)
void clear (unsigned char red, unsigned char green, unsigned char blue)
Shape & rotate (double angle, const Point &center)
Shape & rotate (double angle)
Shape & translate (double dx, double dy)
Shape & scale (double sx, double sy)
Shape & scale (double s)
Board rotated (double angle, const Point &center)
Board rotated (double angle)
Board translated (double dx, double dy)
Board scaled (double sx, double sy)
Board scaled (double s)
void setUnit (Unit unit)
void setUnit (double factor, Unit unit)
void drawDot (double x, double y, int depthValue=-1)
void drawLine (double x1, double y1, double x2, double y2, int depthValue=-1)
void drawQuadraticBezierCurve (double x1, double y1, double x2, double y2, double x3, double y3, int depthValue=-1)
void drawArrow (double x1, double y1, double x2, double y2, bool filled=true, int depthValue=-1)
void drawTriangle (double x1, double y1, double x2, double y2, double x3, double y3, int depthValue=-1)
void drawTriangle (const Point &p1, const Point &p2, const Point &p3, int depthValue=-1)
void drawArc (double x, double y, double radius, double angle1, double angle2, bool neg, int depthValue=-1)
void fillTriangle (double x1, double y1, double x2, double y2, double x3, double y3, int depthValue=-1)
void fillGouraudTriangle (const Point &p1, const DGtal::Color &color1, const Point &p2, const DGtal::Color &color2, const Point &p3, const DGtal::Color &color3, unsigned char divisions=3, int depthValue=-1)
void fillGouraudTriangle (const double x1, const double y1, const DGtal::Color &color1, const double x2, const double y2, const DGtal::Color &color2, const double x3, const double y3, const DGtal::Color &color3, unsigned char divisions=3, int depthValue=-1)
void fillGouraudTriangle (const Point &p1, const float brightness1, const Point &p2, const float brightness2, const Point &p3, const float brightness3, unsigned char divisions=3, int depthValue=-1)
void fillGouraudTriangle (const double x1, const double y1, const float brightness1, const double x2, const double y2, const float brightness2, const double x3, const double y3, const float brightness3, unsigned char divisions=3, int depthValue=-1)
void fillTriangle (const Point &p1, const Point &p2, const Point &p3, int depthValue=-1)
void drawRectangle (double x, double y, double width, double height, int depthValue=-1)
void drawImage (std::string filename, double x, double y, double width, double height, int depthValue=-1, double alpha=1.0)
void fillRectangle (double x, double y, double width, double height, int depthValue=-1)
void drawCircle (double x, double y, double radius, int depthValue=-1)
void fillCircle (double x, double y, double radius, int depthValue=-1)
void drawEllipse (double x, double y, double xRadius, double yRadius, int depthValue=-1)
void fillEllipse (double x, double y, double xRadius, double yRadius, int depthValue=-1)
void drawPolyline (const std::vector< Point > &points, int depthValue=-1)
void drawClosedPolyline (const std::vector< Point > &points, int depthValue=-1)
void fillPolyline (const std::vector< Point > &points, int depthValue=-1)
void drawText (double x, double y, const char *text, int depthValue=-1)
void drawText (double x, double y, const std::string &str, int depthValue=-1)
Board & setFont (const Fonts::Font font, double fontSize)
Board & setFontSize (double fontSize)
Board & setPenColorRGBi (unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha=255)
Board & setPenColorRGBf (float red, float green, float blue, float alpha=1.0f)
Board & setPenColor (const DGtal::Color &color)
Board & setFillColorRGBi (unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha=255)
Board & setFillColorRGBf (float red, float green, float blue, float alpha=1.0f)
Board & setFillColor (const DGtal::Color &color)
Board & setLineWidth (double width)
Board & setLineStyle (Shape::LineStyle style)
Board & setLineCap (Shape::LineCap cap)
Board & setLineJoin (Shape::LineJoin join)
void backgroundColor (const DGtal::Color &color)
void drawBoundingBox (int depthValue=-1)
void setClippingRectangle (double x, double y, double width, double height)
void setClippingPath (const std::vector< Point > &points)
void setClippingPath (const Path &path)
void addDuplicates (const Shape &shape, unsigned int times, double dx, double dy, double scale=1.0)
void addDuplicates (const Shape &shape, unsigned int times, double dx, double dy, double scaleX, double scaleY, double angle=0.0)
void save (const char *filename, PageSize size=Board::BoundingBox, double margin=10.0) const
void save (const char *filename, double pageWidth, double pageHeight, double margin=10.0) const
void saveEPS (const char *filename, PageSize size=Board::BoundingBox, double margin=10.0) const
void saveEPS (std::ostream &out, PageSize size=Board::BoundingBox, double margin=10.0) const
void saveEPS (const char *filename, double pageWidth, double pageHeight, double margin=10.0) const
void saveEPS (std::ostream &out, double pageWidth, double pageHeight, double margin=10.0) const
void saveFIG (const char *filename, PageSize size=Board::BoundingBox, double margin=10.0, bool includeFIGHeader=true) const
void saveFIG (std::ostream &out, PageSize size=Board::BoundingBox, double margin=10.0, bool includeFIGHeader=true) const
void saveFIG (const char *filename, double pageWidth, double pageHeight, double margin=10.0, bool includeFIGHeader=true) const
void saveFIG (std::ostream &out, double pageWidth, double pageHeight, double margin=10.0, bool includeFIGHeader=true) const
void saveSVG (const char *filename, PageSize size=Board::BoundingBox, double margin=10.0) const
void saveSVG (std::ostream &out, PageSize size=Board::BoundingBox, double margin=10.0) const
void saveSVG (const char *filename, double pageWidth, double pageHeight, double margin=10.0) const
void saveSVG (std::ostream &out, double pageWidth, double pageHeight, double margin=10.0, std::string filename="output.svg") const
void saveCairo (const char *filename, CairoType type=CairoPNG, PageSize size=Board::BoundingBox, double margin=10.0) const
void saveCairo (const char *filename, CairoType type, double pageWidth, double pageHeight, double margin=10.0) const
void saveTikZ (const char *filename, PageSize size=Board::BoundingBox, double margin=10.0) const
void saveTikZ (std::ostream &out, PageSize size=Board::BoundingBox, double margin=10.0) const
void saveTikZ (const char *filename, double pageWidth, double pageHeight, double margin=10.0) const
void saveTikZ (std::ostream &out, double pageWidth, double pageHeight, double margin=10.0) const
Public Member Functions inherited from LibBoard::ShapeList
ShapeList (int depth=-1)
ShapeList (const ShapeList &other)
~ShapeList ()
const std::string & name () const
ShapeList & clear ()
Point center () const
Shape & rotate (double angle, const Point &center)
ShapeList rotated (double angle, const Point &center)
Shape & rotate (double angle)
ShapeList rotated (double angle)
Shape & translate (double dx, double dy)
ShapeList translated (double dx, double dy)
Shape & scale (double sx, double sy)
Shape & scale (double s)
ShapeList scaled (double sx, double sy)
ShapeList scaled (double s)
void scaleAll (double s)
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
Rect boundingBox () const
virtual int minDepth () const
virtual int maxDepth () const
void shiftDepth (int shift)
Shape * clone () const
ShapeList & operator= (const ShapeList &other)
ShapeList & operator<< (const Shape &shape)
ShapeList & operator+= (const Shape &shape)
ShapeList & insert (const Shape &shape, int depth)
ShapeList & dup (unsigned int copies=1)
template<typename T >
T & last (const unsigned int position=0)
Shape & last (const unsigned int position=0)
Shape & top ()
Public Member Functions inherited from LibBoard::Shape
Shape (DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, LineStyle style, const LineCap cap, const LineJoin join, int depth)
virtual ~Shape ()
bool filled () const
Shape & rotateDeg (double angle, const Point &center)
Shape & rotateDeg (double angle)
Rect bbox ()
Shape & operator-- ()
Shape & operator++ ()
int depth () const
virtual void depth (int)
const DGtal::Color & penColor () const
const DGtal::Color & fillColor () const
Static Public Attributes
static const double Degree = 3.14159265358979323846 / 180.0
Protected Attributes
State _state
DGtal::Color _backgroundColor
Path _clippingPath
Protected Attributes inherited from LibBoard::ShapeList
std::vector< Shape * > _shapes
int _nextDepth
Protected Attributes inherited from LibBoard::Shape
int _depth
DGtal::Color _penColor
DGtal::Color _fillColor
double _lineWidth
LineStyle _lineStyle
LineCap _lineCap
LineJoin _lineJoin
Additional Inherited Members
Protected Member Functions inherited from LibBoard::ShapeList
void addShape (const Shape &shape, double scaleFactor)
void free ()
Protected Member Functions inherited from LibBoard::Shape
std::string svgProperties (const TransformSVG &transform) const
std::string postscriptProperties () const
void setCairoDashStyle (cairo_t *cr, LineStyle type) const
std::string tikzProperties (const TransformTikZ &transform) const
Detailed Description
Class for EPS, FIG or SVG drawings.
The Board class.
Version
0.5
Definition at line 35 of file Board.h.
Member Enumeration Documentation
CairoType
enum LibBoard::Board::CairoType
Enumerator
CairoPDF
CairoPNG
CairoPS
CairoEPS
CairoSVG
Definition at line 40 of file Board.h.
 { CairoPDF, CairoPNG, CairoPS, CairoEPS, CairoSVG };
PageSize
enum LibBoard::Board::PageSize
Enumerator
BoundingBox
A4
Letter
Definition at line 42 of file Board.h.
 { BoundingBox, A4, Letter };
Unit
enum LibBoard::Board::Unit
Enumerator
UPoint
UInche
UCentimeter
UMillimeter
Definition at line 43 of file Board.h.
 { UPoint, UInche, UCentimeter, UMillimeter };
Constructor & Destructor Documentation
Board() [1/2]
LibBoard::Board::Board (const DGtal::Color & backgroundColor = DGtal::Color::None)
Constructs a new board and sets the background color, if any.
Parameters
backgroundColor A color for the drawing's background.
Definition at line 104 of file Board.cpp.
   : _backgroundColor( bgColor )
 {
 }
Referenced by rotated(), scaled(), and translated().
Board() [2/2]
LibBoard::Board::Board (const Board & other)
Copy constructor.
Parameters
other The object to be copied.
Definition at line 109 of file Board.cpp.
   : ShapeList( other ),
     _state( other._state ),
     _backgroundColor( other._backgroundColor )
 {
 }
~Board()
LibBoard::Board::~Board ()
Definition at line 146 of file Board.cpp.
 {
 }
Member Function Documentation
addDuplicates() [1/2]
void LibBoard::Board::addDuplicates (const Shape & shape, unsigned int times, double dx, double dy, double scale = 1.0)
Insert duplicates of a shape, n times, starting at its current position and iterating given translations and scalings.
Parameters
shape The shape to be duplicated.
times The number of duplicates.
dx The x shift.
dy The y shift.
scale A scale factor between each copy.
Definition at line 767 of file Board.cpp.
 {
   Shape * s = shape.clone();
   while ( times-- ) {
     (*this) << (*s);
     if ( scaleValue != 1.0 )
       s->scale( scaleValue );
     s->translate( dx, dy );
   }
   delete s;
 }
References LibBoard::Shape::clone(), LibBoard::Shape::scale(), and LibBoard::Shape::translate().
addDuplicates() [2/2]
void LibBoard::Board::addDuplicates (const Shape & shape, unsigned int times, double dx, double dy, double scaleX, double scaleY, double angle = 0.0)
Insert duplicates of a shape, n times, starting at its current position and iterating a given translation.
Parameters
shape The shape to be duplicated.
times The number of duplicates.
dx The x shift.
dy The y shift.
scaleX An x scale factor between each copy.
scaleY A y scale factor between each copy.
angle An angular increment.
Definition at line 782 of file Board.cpp.
 {
   Shape * s = shape.clone();
   while ( times-- ) {
     (*this) << (*s);
     if ( scaleX != 1.0 || scaleY != 1.0 ) s->scale( scaleX, scaleY );
     if ( dx != 0.0 || dy != 0.0 ) s->translate( dx, dy );
     if ( angle != 0.0 ) s->rotate( angle );
   }
   delete s;
 }
References LibBoard::Shape::clone(), LibBoard::Shape::rotate(), LibBoard::Shape::scale(), and LibBoard::Shape::translate().
backgroundColor()
void LibBoard::Board::backgroundColor (const DGtal::Color & color)
Changes the background color of the whole drawing.
Parameters
color A color (may be Color::None).
Definition at line 351 of file Board.cpp.
 {
   _backgroundColor = color;
 }
References _backgroundColor.
clear() [1/2]
void LibBoard::Board::clear (const DGtal::Color & color = DGtal::Color::None)
Clears the board with a given background color.
Parameters
color The board background color (may be Color::None).
Examples
arithmetic/lower-integer-convex-hull.cpp, doc-examples/kernelDomain.cpp, geometry/curves/exampleArithmeticalDSS.cpp, geometry/curves/exampleGridCurve2d.cpp, geometry/tools/exampleConvexHull2D.cpp, geometry/volumes/distance/distancetransform2D.cpp, geometry/volumes/distance/voronoimap2D.cpp, graph/graphTraversal.cpp, images/exampleConstImageAdapter.cpp, images/exampleTiledImage.cpp, io/boards/dgtalBoard2D-2-sets.cpp, io/boards/exampleBezierCurve.cpp, topology/cubical-complex-illustrations.cpp, and topology/generateSimplicityTables2D.cpp.
Definition at line 152 of file Board.cpp.
 {
   ShapeList::clear();
   _backgroundColor = color;
 }
References _backgroundColor, and LibBoard::ShapeList::clear().
Referenced by checkCut(), checkOutputConvexHullBorder(), convexHull(), drawComplex(), exampleStandardDSS(), main(), moduleImages_example(), specificTestLatticePolytope2D(), testBoard2D(), testBoard2DCustomStyle(), testCellDrawOnBoard(), testChessboard(), testCMAP(), testDepthFirstPropagation(), testDigitalSetBoardSnippet(), testDistanceTransformation(), testDistanceTransformationBorder(), testDistanceTransformationNeg(), testDTFromSet(), testGetSetVal(), testImageAdapter(), testImplicitShape(), testKanungo2D(), testLatticePolytope2D(), testLayers(), testObjectBorder(), testSimpleExpander(), testSimplePoints2D(), and testVoronoiMap().
clear() [2/2]
void LibBoard::Board::clear (unsigned char red, unsigned char green, unsigned char blue)
Clears the board and set the background color from an RGB triple.
Parameters
red red
green green
blue blue
drawArc()
void LibBoard::Board::drawArc (double x, double y, double radius, double angle1, double angle2, bool neg, int depthValue = -1)
Draws an arc.
Parameters
x First coordinate of the arc center.
y Second coordinate of the arc center.
radius arc radius.
angle1 first angle.
angle2 second angle.
neg neg
depthValue Depth of the arc.
Definition at line 461 of file Board.cpp.
{
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   _shapes.push_back( new Arc( _state.unit(x), _state.unit(y), _state.unit(radius),
                               angle1, angle2, neg,_state.penColor,
                               DGtal::Color::None, _state.lineWidth, _state.lineStyle, d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::lineStyle, LibBoard::Board::State::lineWidth, DGtal::Color::None, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
drawArrow()
void LibBoard::Board::drawArrow (double x1, double y1, double x2, double y2, bool filled = true, int depthValue = -1)
Draws a line from (x1,y1) to (x2,y2) with an arrow at (x2,y2).
Parameters
x1 First coordinate of the first extremity.
y1 Second coordinate of the first extremity.
x2 First coordinate of the second extremity.
y2 Second coordinate of the second extremity.
filled Whether or not the arrow is filled.
depthValue Depth of the line.
Examples
geometry/curves/exampleArithmeticalDSL.cpp, and geometry/curves/exampleArithmeticalDSS.cpp.
Definition at line 400 of file Board.cpp.
 {
   if ( depthValue != -1 )
     _shapes.push_back( new Arrow( _state.unit(x1), _state.unit(y1),
           _state.unit(x2), _state.unit(y2),
           _state.penColor, filledArrow ? _state.penColor : DGtal::Color::None,
           _state.lineWidth, _state.lineStyle, _state.lineCap, _state.lineJoin, depthValue ) );
   else
     _shapes.push_back( new Arrow( _state.unit(x1), _state.unit(y1),
           _state.unit(x2), _state.unit(y2),
           _state.penColor, filledArrow ? _state.penColor : DGtal::Color::None,
           _state.lineWidth, _state.lineStyle, _state.lineCap, _state.lineJoin, _nextDepth-- ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::lineCap, LibBoard::Board::State::lineJoin, LibBoard::Board::State::lineStyle, LibBoard::Board::State::lineWidth, DGtal::Color::None, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
Referenced by drawArithmeticalDSL(), exampleNaiveDSL(), exampleStandardDSL(), and exampleUpdate().
drawBoundingBox()
void LibBoard::Board::drawBoundingBox (int depthValue = -1)
Draws the current drawing's bounding box as a rectangle.
Parameters
depthValue The depth of the rectangle.
Definition at line 710 of file Board.cpp.
 {
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   Rect box = boundingBox();
   _shapes.push_back( new Rectangle( _state.unit(box.left),
             _state.unit(box.top),
             _state.unit(box.width),
             _state.unit(box.height),
             _state.penColor,
             _state.fillColor,
             _state.lineWidth,
             _state.lineStyle,
             _state.lineCap,
             _state.lineJoin,
             d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::ShapeList::boundingBox(), LibBoard::Board::State::fillColor, LibBoard::Rect::height, LibBoard::Rect::left, LibBoard::Board::State::lineCap, LibBoard::Board::State::lineJoin, LibBoard::Board::State::lineStyle, LibBoard::Board::State::lineWidth, LibBoard::Board::State::penColor, LibBoard::Rect::top, LibBoard::Board::State::unit(), and LibBoard::Rect::width.
drawCircle()
void LibBoard::Board::drawCircle (double x, double y, double radius, int depthValue = -1)
Draws a circle.
Parameters
x First coordinate of the circle's center.
y Second coordinate of the circle's center.
radius Radius of the circle.
depthValue Depth of the circle.
Examples
geometry/tools/exampleConvexHull2D.cpp.
Definition at line 451 of file Board.cpp.
 {
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   _shapes.push_back( new Circle( _state.unit(x), _state.unit(y), _state.unit(radius),
          _state.penColor, _state.fillColor,
          _state.lineWidth, _state.lineStyle, d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::fillColor, LibBoard::Board::State::lineStyle, LibBoard::Board::State::lineWidth, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
Referenced by convexHull(), testAlphaThickSegmentFreeman(), testConvexHullCompThickness(), and testThicknessDefinitions().
drawClosedPolyline()
void LibBoard::Board::drawClosedPolyline (const std::vector< Point > & points, int depthValue = -1)
Draws a closed polygonal line.
Parameters
points A vector of points.
depthValue The depth of the polyline.
Definition at line 531 of file Board.cpp.
 {
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   std::vector<Point> v = points;
   std::vector<Point>::iterator it = v.begin();
   std::vector<Point>::iterator end = v.end();
   while ( it != end ) {
     (*it) = _state.unit( *it );
     ++it;
   }
   _shapes.push_back( new Polyline( v, true, _state.penColor, _state.fillColor,
            _state.lineWidth,
            _state.lineStyle,
            _state.lineCap,
            _state.lineJoin,
            d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::fillColor, LibBoard::Board::State::lineCap, LibBoard::Board::State::lineJoin, LibBoard::Board::State::lineStyle, LibBoard::Board::State::lineWidth, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
drawDot()
void LibBoard::Board::drawDot (double x, double y, int depthValue = -1)
Draws a dot at coordinates (x,y).
Parameters
x First coordinate of the dot.
y Second coordinate of the dot.
depthValue Depth of the line.
Definition at line 357 of file Board.cpp.
 {
   if ( depthValue != -1 )
     _shapes.push_back( new Dot( _state.unit(x), _state.unit(y),
         _state.penColor, _state.lineWidth, depthValue ) );
   else
     _shapes.push_back( new Dot( _state.unit(x), _state.unit(y),
         _state.penColor, _state.lineWidth, _nextDepth-- ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::lineWidth, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
drawEllipse()
void LibBoard::Board::drawEllipse (double x, double y, double xRadius, double yRadius, int depthValue = -1)
Draws an ellipse.
Parameters
x First coordinate of the circle's center.
y Second coordinate of the circle's center.
xRadius Radius of the circle.
yRadius Radius of the circle.
depthValue Depth of the circle.
Definition at line 482 of file Board.cpp.
 {
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   _shapes.push_back( new Ellipse( _state.unit(x), _state.unit(y),
           _state.unit(xRadius), _state.unit(yRadius),
           _state.penColor,
           _state.fillColor,
           _state.lineWidth,
           _state.lineStyle,
           d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::fillColor, LibBoard::Board::State::lineStyle, LibBoard::Board::State::lineWidth, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
drawImage()
void LibBoard::Board::drawImage (std::string filename, double x, double y, double width, double height, int depthValue = -1, double alpha = 1.0)
Draws an image.
Parameters
filename filename
x First coordinate of the upper left corner.
y Second coordinate of the upper left corner.
width Width of the rectangle.
height Height of the rectangle.
depthValue Depth of the rectangle.
alpha Transparency used in the image display.
Definition at line 428 of file Board.cpp.
 {
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   _shapes.push_back( new Image( _state.unit(x), _state.unit(y), _state.unit(width), _state.unit(height),
         filename, d, alpha ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, and LibBoard::Board::State::unit().
Referenced by main().
drawLine()
void LibBoard::Board::drawLine (double x1, double y1, double x2, double y2, int depthValue = -1)
Draws a line from (x1,y1) to (x2,y2).
Parameters
x1 First coordinate of the first extremity.
y1 Second coordinate of the first extremity.
x2 First coordinate of the second extremity.
y2 Second coordinate of the second extremity.
depthValue Depth of the line.
Examples
geometry/curves/exampleAlphaThickSegmentNoisy.cpp, geometry/curves/exampleDigitalConvexity.cpp, geometry/curves/exampleRationalConvexity.cpp, and geometry/tools/exampleConvexHull2D.cpp.
Definition at line 368 of file Board.cpp.
 {
   if ( depthValue != -1 )
     _shapes.push_back( new Line( _state.unit(x1), _state.unit(y1),
          _state.unit(x2), _state.unit(y2),
          _state.penColor, _state.lineWidth,
          _state.lineStyle, _state.lineCap, _state.lineJoin, depthValue ) );
   else
     _shapes.push_back( new Line( _state.unit(x1), _state.unit(y1),
          _state.unit(x2), _state.unit(y2),
          _state.penColor, _state.lineWidth,
          _state.lineStyle, _state.lineCap, _state.lineJoin, _nextDepth-- ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::lineCap, LibBoard::Board::State::lineJoin, LibBoard::Board::State::lineStyle, LibBoard::Board::State::lineWidth, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
Referenced by convexHull(), main(), testAlphaThickSegmentComputerFloatingPointContour(), testAlphaThickSegmentConvexHullAndBox(), testAlphaThickSpecialInit(), testConvexHullCompThickness(), and testThicknessDefinitions().
drawPolyline()
void LibBoard::Board::drawPolyline (const std::vector< Point > & points, int depthValue = -1)
Draws a polygonal line.
Parameters
points A vector of points.
depthValue The depth of the polyline.
Definition at line 511 of file Board.cpp.
 {
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   std::vector<Point> v = points;
   std::vector<Point>::iterator it = v.begin();
   std::vector<Point>::iterator end = v.end();
   while ( it != end ) {
     (*it) = _state.unit( *it );
     ++it;
   }
   _shapes.push_back( new Polyline( v, false, _state.penColor, _state.fillColor,
            _state.lineWidth,
            _state.lineStyle,
            _state.lineCap,
            _state.lineJoin,
            d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::fillColor, LibBoard::Board::State::lineCap, LibBoard::Board::State::lineJoin, LibBoard::Board::State::lineStyle, LibBoard::Board::State::lineWidth, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
drawQuadraticBezierCurve()
void LibBoard::Board::drawQuadraticBezierCurve (double x1, double y1, double x2, double y2, double x3, double y3, int depthValue = -1)
Draws a quadratic Bezier curve from (x1,y1) to (x3,y3), with (x2,y2) as middle control point.
Parameters
x1 First coordinate of the first point.
y1 Second coordinate of the first point.
x2 First coordinate of the middle point.
y2 Second coordinate of the middle point.
x3 First coordinate of the last point.
y3 Second coordinate of the last point.
depthValue Depth of the line.
Examples
io/boards/exampleBezierCurve.cpp.
Definition at line 384 of file Board.cpp.
 {
   if ( depthValue != -1 )
     _shapes.push_back( new QuadraticBezierCurve( _state.unit(x1), _state.unit(y1),
          _state.unit(x2), _state.unit(y2), _state.unit(x3), _state.unit(y3),
          _state.penColor, _state.fillColor, _state.lineWidth,
          _state.lineStyle, _state.lineCap, _state.lineJoin, depthValue ) );
   else
     _shapes.push_back( new QuadraticBezierCurve( _state.unit(x1), _state.unit(y1),
          _state.unit(x2), _state.unit(y2), _state.unit(x3), _state.unit(y3),
          _state.penColor, _state.fillColor, _state.lineWidth,
          _state.lineStyle, _state.lineCap, _state.lineJoin, _nextDepth-- ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::fillColor, LibBoard::Board::State::lineCap, LibBoard::Board::State::lineJoin, LibBoard::Board::State::lineStyle, LibBoard::Board::State::lineWidth, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
Referenced by main().
drawRectangle()
void LibBoard::Board::drawRectangle (double x, double y, double width, double height, int depthValue = -1)
Draws a rectangle.
Parameters
x First coordinate of the upper left corner.
y Second coordinate of the upper left corner.
width Width of the rectangle.
height Height of the rectangle.
depthValue Depth of the rectangle.
Definition at line 417 of file Board.cpp.
 {
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   _shapes.push_back( new Rectangle( _state.unit(x), _state.unit(y), _state.unit(width), _state.unit(height),
             _state.penColor, _state.fillColor,
             _state.lineWidth, _state.lineStyle, _state.lineCap, _state.lineJoin, d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::fillColor, LibBoard::Board::State::lineCap, LibBoard::Board::State::lineJoin, LibBoard::Board::State::lineStyle, LibBoard::Board::State::lineWidth, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
Referenced by addColorMapSample().
drawText() [1/2]
void LibBoard::Board::drawText (double x, double y, const char * text, int depthValue = -1)
Draws a string of text.
Parameters
x The first coordinates of the lower left corner.
y The second coordinates of the lower left corner.
text The text.
depthValue The depth of the text.
Definition at line 693 of file Board.cpp.
 {
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   _shapes.push_back( new Text( _state.unit(x), _state.unit(y), text,
              _state.font, _state.fontSize, _state.penColor, d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::font, LibBoard::Board::State::fontSize, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
Referenced by addColorMapSample().
drawText() [2/2]
void LibBoard::Board::drawText (double x, double y, const std::string & str, int depthValue = -1)
Draws a string of text.
Parameters
x The first coordinates of the lower left corner.
y The second coordinates of the lower left corner.
str The text.
depthValue The depth of the text.
Definition at line 702 of file Board.cpp.
 {
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   _shapes.push_back( new Text( _state.unit(x), _state.unit(y), str,
              _state.font, _state.fontSize, _state.penColor, d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::font, LibBoard::Board::State::fontSize, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
drawTriangle() [1/2]
void LibBoard::Board::drawTriangle (const Point & p1, const Point & p2, const Point & p3, int depthValue = -1)
Draws a triangle.
Parameters
p1 First vertex.
p2 Second vertex.
p3 Third vertex.
depthValue Depth of the triangle.
Definition at line 590 of file Board.cpp.
 {
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   std::vector<Point> points;
   points.push_back( Point( _state.unit(p1.x), _state.unit(p1.y) ) );
   points.push_back( Point( _state.unit(p2.x), _state.unit(p2.y) ) );
   points.push_back( Point( _state.unit(p3.x), _state.unit(p3.y) ) );
   _shapes.push_back( new Polyline( points, true, _state.penColor, _state.fillColor,
            _state.lineWidth,
            _state.lineStyle,
            _state.lineCap,
            _state.lineJoin,
            d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::fillColor, LibBoard::Board::State::lineCap, LibBoard::Board::State::lineJoin, LibBoard::Board::State::lineStyle, LibBoard::Board::State::lineWidth, LibBoard::Board::State::penColor, LibBoard::Board::State::unit(), LibBoard::Point::x, and LibBoard::Point::y.
drawTriangle() [2/2]
void LibBoard::Board::drawTriangle (double x1, double y1, double x2, double y2, double x3, double y3, int depthValue = -1)
Draws a triangle.
Parameters
x1 First coordinate of the first vertex.
y1 Second coordinate of the first vertex.
x2 First coordinate of the second vertex.
y2 Second coordinate of the second vertex.
x3 First coordinate of the third vertex.
y3 Second coordinate of the third vertex.
depthValue Depth of the triangle.
Definition at line 571 of file Board.cpp.
 {
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   std::vector<Point> points;
   points.push_back( Point( _state.unit(x1), _state.unit(y1) ) );
   points.push_back( Point( _state.unit(x2), _state.unit(y2) ) );
   points.push_back( Point( _state.unit(x3), _state.unit(y3) ) );
   _shapes.push_back( new Polyline( points, true, _state.penColor, _state.fillColor,
            _state.lineWidth,
            _state.lineStyle,
            _state.lineCap,
            _state.lineJoin,
            d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::fillColor, LibBoard::Board::State::lineCap, LibBoard::Board::State::lineJoin, LibBoard::Board::State::lineStyle, LibBoard::Board::State::lineWidth, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
fillCircle()
void LibBoard::Board::fillCircle (double x, double y, double radius, int depthValue = -1)
Draws a circle filled with the current pen color.
Parameters
x First coordinate of the circle's center.
y Second coordinate of the circle's center.
radius Radius of the circle.
depthValue Depth of the circle.
Examples
geometry/curves/exampleAlphaThickSegmentTgtCover.cpp.
Definition at line 471 of file Board.cpp.
 {
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   _shapes.push_back( new Circle( _state.unit(x), _state.unit(y), _state.unit(radius),
          DGtal::Color::None, _state.penColor,
          0.0f, _state.lineStyle, d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::lineStyle, DGtal::Color::None, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
Referenced by main(), testAlphaThickSegmentConvexHullAndBox(), testAlphaThickSegmentFreeman(), and testAlphaThickSpecialInit().
fillEllipse()
void LibBoard::Board::fillEllipse (double x, double y, double xRadius, double yRadius, int depthValue = -1)
Draws an ellipse filled with the current pen color.
Parameters
x First coordinate of the circle's center.
y Second coordinate of the circle's center.
xRadius X axis radius of the ellipse.
yRadius Y axis radius of the ellipse.
depthValue Depth of the circle.
Definition at line 497 of file Board.cpp.
 {
   int d = depthValue ? depthValue : _nextDepth--;
   _shapes.push_back( new Ellipse( _state.unit(x), _state.unit(y), _state.unit(xRadius), _state.unit(yRadius),
           DGtal::Color::None,
           _state.penColor,
           0.0f,
           _state.lineStyle,
           d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::lineStyle, DGtal::Color::None, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
fillGouraudTriangle() [1/4]
void LibBoard::Board::fillGouraudTriangle (const double x1, const double y1, const DGtal::Color & color1, const double x2, const double y2, const DGtal::Color & color2, const double x3, const double y3, const DGtal::Color & color3, unsigned char divisions = 3, int depthValue = -1)
Draws a triangle with Gouraud-like shaded colors.
Parameters
x1 x1
y1 y1
color1 color1
x2 x2
y2 y2
color2 color2
x3 x3
y3 y3
color3 color3
divisions number of subdivisions
depthValue depth
fillGouraudTriangle() [2/4]
void LibBoard::Board::fillGouraudTriangle (const double x1, const double y1, const float brightness1, const double x2, const double y2, const float brightness2, const double x3, const double y3, const float brightness3, unsigned char divisions = 3, int depthValue = -1)
Draws a triangle with a Gouraud-like shaded color according to the current fill color and a brightness value given for each vertex.
Parameters
x1 x1
y1 y1
brightness1 b1
x2 x2
y2 y2
brightness2 b2
x3 x3
y3 y3
brightness3 b3
divisions number of sudivisions
depthValue depth
fillGouraudTriangle() [3/4]
void LibBoard::Board::fillGouraudTriangle (const Point & p1, const DGtal::Color & color1, const Point & p2, const DGtal::Color & color2, const Point & p3, const DGtal::Color & color3, unsigned char divisions = 3, int depthValue = -1)
Draws a triangle with Gouraud-like shaded colors.
Parameters
p1 p1
color1 color1
p2 p2
color2 color2
p3 p3
color3 color3
divisions number of triangle subdivisions.
depthValue The depth of the triangle.
Definition at line 647 of file Board.cpp.
 {
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   _shapes.push_back( new GouraudTriangle( Point( _state.unit(p1.x), _state.unit(p1.y) ), color1,
             Point( _state.unit(p2.x), _state.unit(p2.y) ), color2,
             Point( _state.unit(p3.x), _state.unit(p3.y) ), color3,
             divisions, d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::unit(), LibBoard::Point::x, and LibBoard::Point::y.
Referenced by fillGouraudTriangle().
fillGouraudTriangle() [4/4]
void LibBoard::Board::fillGouraudTriangle (const Point & p1, const float brightness1, const Point & p2, const float brightness2, const Point & p3, const float brightness3, unsigned char divisions = 3, int depthValue = -1)
Draws a triangle with a Gouraud-like shaded color according to the current fill color and a brightness value given for each vertex.
Parameters
p1 p1
brightness1 brightness1
p2 p2
brightness2 brightness2
p3 p3
brightness3 brightness3
divisions number of triangle subdivisions.
depthValue The depth of the triangle.
Definition at line 664 of file Board.cpp.
 {
   DGtal::Color color1( _state.penColor );
   DGtal::Color color2( _state.penColor );
   DGtal::Color color3( _state.penColor );
   color1.red( static_cast<unsigned char>( std::min( 255.0f, color1.red() * brightness1 ) ) );
   color1.green( static_cast<unsigned char>( std::min( 255.0f, color1.green() * brightness1 ) ) );
   color1.blue( static_cast<unsigned char>( std::min( 255.0f, color1.blue() * brightness1 ) ) );
   color2.red( static_cast<unsigned char>( std::min( 255.0f, color2.red() * brightness2 ) ) );
   color2.green( static_cast<unsigned char>( std::min( 255.0f, color2.green() * brightness2 ) ) );
   color2.blue( static_cast<unsigned char>( std::min( 255.0f, color2.blue() * brightness2 ) ) );
   color3.red( static_cast<unsigned char>( std::min( 255.0f, color3.red() * brightness3 ) ) );
   color3.green( static_cast<unsigned char>( std::min( 255.0f, color3.green() * brightness3 ) ) );
   color3.blue( static_cast<unsigned char>( std::min( 255.0f, color3.blue() * brightness3 ) ) );
   fillGouraudTriangle( Point( _state.unit(p1.x), _state.unit(p1.y) ), color1,
            Point( _state.unit(p2.x), _state.unit(p2.y) ), color2,
            Point( _state.unit(p3.x), _state.unit(p3.y) ), color3,
            divisions,
            depthValue );
 }
References _state, DGtal::Color::blue(), fillGouraudTriangle(), DGtal::Color::green(), LibBoard::Board::State::penColor, DGtal::Color::red(), LibBoard::Board::State::unit(), LibBoard::Point::x, and LibBoard::Point::y.
fillPolyline()
void LibBoard::Board::fillPolyline (const std::vector< Point > & points, int depthValue = -1)
Draws a filled polygon.
Parameters
points A vector of points.
depthValue The depth of the polygon.
Examples
geometry/curves/exampleAlphaThickSegmentTgtCover.cpp, and geometry/curves/greedyAlphaThickDecomposition.cpp.
Definition at line 551 of file Board.cpp.
 {
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   std::vector<Point> v = points;
   std::vector<Point>::iterator it = v.begin();
   std::vector<Point>::iterator end = v.end();
   while ( it != end ) {
     (*it) = _state.unit( *it );
     ++it;
   }
   _shapes.push_back( new Polyline( v, true, DGtal::Color::None, _state.penColor,
            0.0f,
            _state.lineStyle,
            _state.lineCap,
            _state.lineJoin,
            d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::lineCap, LibBoard::Board::State::lineJoin, LibBoard::Board::State::lineStyle, DGtal::Color::None, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
Referenced by main().
fillRectangle()
void LibBoard::Board::fillRectangle (double x, double y, double width, double height, int depthValue = -1)
Draws a rectangle filled with the current pen color.
Parameters
x First coordinate of the upper left corner.
y Second coordinate of the upper left corner.
width Width of the rectangle.
height Height of the rectangle.
depthValue Depth of the rectangle.
Definition at line 439 of file Board.cpp.
 {
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   _shapes.push_back( new Rectangle( _state.unit(x), _state.unit(y), _state.unit(width), _state.unit(height),
             DGtal::Color::None, _state.penColor,
             0.0f, _state.lineStyle, _state.lineCap, _state.lineJoin,
             d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::lineCap, LibBoard::Board::State::lineJoin, LibBoard::Board::State::lineStyle, DGtal::Color::None, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
fillTriangle() [1/2]
void LibBoard::Board::fillTriangle (const Point & p1, const Point & p2, const Point & p3, int depthValue = -1)
Draws a filled triangle.
Parameters
p1 First vertex.
p2 Second vertex.
p3 Third vertex.
depthValue Depth of the triangle.
Definition at line 628 of file Board.cpp.
 {
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   std::vector<Point> points;
   points.push_back( Point( _state.unit(p1.x), _state.unit(p1.y) ) );
   points.push_back( Point( _state.unit(p2.x), _state.unit(p2.y) ) );
   points.push_back( Point( _state.unit(p3.x), _state.unit(p3.y) ) );
   _shapes.push_back( new Polyline( points, true, DGtal::Color::None, _state.penColor,
            0.0f,
            _state.lineStyle,
            _state.lineCap,
            _state.lineJoin,
            d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::lineCap, LibBoard::Board::State::lineJoin, LibBoard::Board::State::lineStyle, DGtal::Color::None, LibBoard::Board::State::penColor, LibBoard::Board::State::unit(), LibBoard::Point::x, and LibBoard::Point::y.
fillTriangle() [2/2]
void LibBoard::Board::fillTriangle (double x1, double y1, double x2, double y2, double x3, double y3, int depthValue = -1)
Draws a filled triangle.
Parameters
x1 First coordinate of the first vertex.
y1 Second coordinate of the first vertex.
x2 First coordinate of the second vertex.
y2 Second coordinate of the second vertex.
x3 First coordinate of the third vertex.
y3 Second coordinate of the third vertex.
depthValue Depth of the triangle.
Definition at line 609 of file Board.cpp.
 {
   int d = (depthValue != -1) ? depthValue : _nextDepth--;
   std::vector<Point> points;
   points.push_back( Point( _state.unit(x1), _state.unit(y1) ) );
   points.push_back( Point( _state.unit(x2), _state.unit(y2) ) );
   points.push_back( Point( _state.unit(x3), _state.unit(y3) ) );
   _shapes.push_back( new Polyline( points, true, DGtal::Color::None, _state.penColor,
            0.0f,
            _state.lineStyle,
            _state.lineCap,
            _state.lineJoin,
            d ) );
 }
References LibBoard::ShapeList::_nextDepth, LibBoard::ShapeList::_shapes, _state, LibBoard::Board::State::lineCap, LibBoard::Board::State::lineJoin, LibBoard::Board::State::lineStyle, DGtal::Color::None, LibBoard::Board::State::penColor, and LibBoard::Board::State::unit().
operator<<() [1/2]
Board & LibBoard::Board::operator<< (const Shape & shape)
Add a shape to the board, using the current unit factor.
Parameters
shape A shape. (Might be a list of shapes, actually!)
Returns
The board itself, as a ShapeList.
Definition at line 132 of file Board.cpp.
 {
   ShapeList::addShape( shape, _state.unitFactor );
   return *this;
 }
References _state, LibBoard::ShapeList::addShape(), and LibBoard::Board::State::unitFactor.
operator<<() [2/2]
Board & LibBoard::Board::operator<< (Unit unit)
Overloaded operator to set the current unit.
Parameters
unit The unit to be used in next drawing functions and shape insertions.
Returns
The board itself, as a ShapeList.
Definition at line 139 of file Board.cpp.
 {
   setUnit( unit );
   return *this;
 }
References setUnit().
operator=()
Board & LibBoard::Board::operator= (const Board & other)
The operator =
Parameters
other The object to be copied.
Returns
A reference to the left operand.
Definition at line 117 of file Board.cpp.
 {
   free();
   if ( ! other._shapes.size() ) return (*this);
   _shapes.resize( other._shapes.size(), 0 );
   std::vector<Shape*>::iterator t = _shapes.begin();
   std::vector<Shape*>::const_iterator i = other._shapes.begin();
   std::vector<Shape*>::const_iterator end = other._shapes.end();
   while ( i != end ) {
     *t = (*i)->clone();
     ++i; ++t;
   }
   return *this;
 }
References LibBoard::ShapeList::_shapes, and LibBoard::ShapeList::free().
Referenced by DGtal::Board2D::operator=().
rotate() [1/2]
Shape & LibBoard::Board::rotate (double angle) virtual
Rotate the shape around its center.
Parameters
angle The rotation angle in radian.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Definition at line 168 of file Board.cpp.
 {
   ShapeList::rotate( angle );
   _clippingPath.rotate( angle, center() );
   return (*this);
 }
References _clippingPath, LibBoard::ShapeList::center(), LibBoard::Path::rotate(), and LibBoard::ShapeList::rotate().
rotate() [2/2]
Shape & LibBoard::Board::rotate (double angle, const Point & center) virtual
Rotate the shape around a given center of rotation.
Parameters
angle The rotation angle in radian.
center The center of rotation.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Definition at line 160 of file Board.cpp.
 {
   ShapeList::rotate( angle, aCenter );
   _clippingPath.rotate( angle, aCenter );
   return (*this);
 }
References _clippingPath, LibBoard::Path::rotate(), and LibBoard::ShapeList::rotate().
rotated() [1/2]
Board LibBoard::Board::rotated (double angle)
Definition at line 215 of file Board.cpp.
 {
   return static_cast<const Board &>( Board( *this ).rotate( angle ) );
 }
References Board().
rotated() [2/2]
Board LibBoard::Board::rotated (double angle, const Point & center)
Definition at line 209 of file Board.cpp.
 {
   return static_cast<const Board &>( Board( *this ).rotate( angle, aCenter ) );
 }
References Board().
save() [1/2]
void LibBoard::Board::save (const char * filename, double pageWidth, double pageHeight, double margin = 10.0) const
Save the drawing in an EPS, XFIG or SVG file depending on the filename extension. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
filename Path of the file to be created.
pageWidth Width of the page in millimeters.
pageHeight Height of the page in millimeters.
margin Minimal margin around the figure in the page, in millimeters.
Definition at line 1108 of file Board.cpp.
 {
   const char * extension = filename + strlen( filename );
   while ( extension > filename && *extension != '.' )
     --extension;
   if ( !(strcmp( extension, ".eps" )) || !(strcmp( extension, ".EPS" )) ) {
     saveEPS( filename, pageWidth, pageHeight, margin );
     return;
   }
   if ( !(strcmp( extension, ".fig" )) || !(strcmp( extension, ".FIG" )) ) {
     saveFIG( filename, pageWidth, pageHeight, margin );
     return;
   }
   if ( !(strcmp( extension, ".svg" )) || !(strcmp( extension, ".SVG" )) ) {
     saveSVG( filename, pageWidth, pageHeight, margin );
     return;
   }
   if ( !(strcmp( extension, ".tikz" )) || !(strcmp( extension, ".TIKZ" )) ) {
     saveTikZ( filename, pageWidth, pageHeight, margin );
     return;
   }
 }
References saveEPS(), saveFIG(), saveSVG(), and saveTikZ().
save() [2/2]
void LibBoard::Board::save (const char * filename, PageSize size = Board::BoundingBox, double margin = 10.0) const
Save the drawing in an EPS, XFIG or SVG file depending on the filename extension. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
filename Path of the file to be created.
size Page size (Either BoundingBox (default), A4 or Letter).
margin Minimal margin around the figure in the page, in millimeters.
Definition at line 1132 of file Board.cpp.
 {
   save( filename, pageSizes[size][0], pageSizes[size][1], margin );
 }
saveCairo() [1/2]
void LibBoard::Board::saveCairo (const char * filename, CairoType type, double pageWidth, double pageHeight, double margin = 10.0) const
Save the drawing with cairo. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
filename The name of the file.
type Output type: CairoPDF, CairoPNG, CairoPS, CairoSVG.
pageWidth Width of the page in millimeters.
pageHeight Height of the page in millimeters.
margin Minimal margin around the figure in the page, in millimeters.
Definition at line 1144 of file Board.cpp.
 {
   cairo_surface_t *surface;
   cairo_t *cr;
   double cairoWidth, cairoHeight;
   TransformCairo transform;
   Rect box = boundingBox();
   bool clipping = _clippingPath.size() > 2;
   if ( clipping )
     box = box && _clippingPath.boundingBox();
   transform.setBoundingBox( box, pageWidth, pageHeight, margin );
   if ( pageWidth > 0 && pageHeight > 0 )
   {
     cairoWidth = pageWidth;
     cairoHeight = pageHeight;
   }
   else
   {
     cairoWidth = box.width;
     cairoHeight = box.height;
   }
   switch (type)
   {
   case CairoPDF:
       surface = cairo_pdf_surface_create (filename, cairoWidth, cairoHeight); break;
   case CairoPS:
       surface = cairo_ps_surface_create (filename, cairoWidth, cairoHeight); break;
   case CairoEPS:
     surface = cairo_ps_surface_create (filename, cairoWidth, cairoHeight);
     cairo_ps_surface_set_eps(surface, true); break;
   case CairoSVG:
       surface = cairo_svg_surface_create (filename, cairoWidth, cairoHeight); break;
     case CairoPNG:
     default:
       surface = cairo_image_surface_create (CAIRO_FORMAT_ARGB32, (int)cairoWidth, (int)cairoHeight);
   }
   cr = cairo_create (surface);
   /* For 1.0 x 1.0 coordinate space */
   //cairo_scale (cr, cairoWidth, cairoHeight);
   //temp: http://zetcode.com/tutorials/cairographicstutorial/basicdrawing/
   //temp: http://www.graphviz.org/pub/scm/graphviz-cairo/plugin/cairo/gvrender_cairo.c
   // Draw the background color if needed.
   if ( _backgroundColor != DGtal::Color::None ) {
     Rectangle r( box, DGtal::Color::None, _backgroundColor, 0.0 );
     r.flushCairo( cr, transform );
   }
   // Draw the shapes.
   std::vector< Shape* > shapes = _shapes;
   stable_sort( shapes.begin(), shapes.end(), shapeGreaterDepth );
   std::vector< Shape* >::const_iterator i = shapes.begin();
   std::vector< Shape* >::const_iterator end = shapes.end();
   while ( i != end ) {
     (*i)->flushCairo( cr, transform );
     ++i;
   }
   if (type==CairoPNG)
     cairo_surface_write_to_png (surface, filename);
   cairo_destroy (cr);
   cairo_surface_destroy (surface);
 }
References _backgroundColor, _clippingPath, LibBoard::ShapeList::_shapes, LibBoard::Path::boundingBox(), LibBoard::ShapeList::boundingBox(), CairoEPS, CairoPDF, CairoPNG, CairoPS, CairoSVG, LibBoard::Rect::height, DGtal::Color::None, LibBoard::shapeGreaterDepth(), LibBoard::Path::size(), and LibBoard::Rect::width.
saveCairo() [2/2]
void LibBoard::Board::saveCairo (const char * filename, CairoType type = CairoPNG, PageSize size = Board::BoundingBox, double margin = 10.0) const
Save the drawing with cairo. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
filename The name of the file.
type Output type: CairoPDF, CairoPNG, CairoPS, CairoSVG.
size the page size.
margin Minimal margin around the figure in the page, in millimeters.
Examples
geometry/curves/convex-and-concave-parts.cpp, geometry/curves/exampleArithmeticalDSL.cpp, geometry/curves/exampleArithmeticalDSS.cpp, geometry/curves/exampleFrechetShortcut.cpp, geometry/curves/greedy-dss-decomposition.cpp, geometry/tools/exampleAlphaShape.cpp, geometry/tools/exampleConvexHull2D.cpp, geometry/tools/examplePreimage.cpp, images/exampleTiledImage.cpp, io/boards/dgtalBoard2D-1-points.cpp, io/boards/dgtalBoard2D-2-sets.cpp, io/boards/dgtalBoard2D-3-custom-classes.cpp, io/boards/dgtalBoard2D-3-custom-points.cpp, io/boards/dgtalBoard2D-4-colormaps.cpp, and io/boards/exampleBezierCurve.cpp.
Definition at line 1139 of file Board.cpp.
 {
   saveCairo( filename, type, pageSizes[size][0], pageSizes[size][1], margin );
 }
Referenced by alphaShape(), convexHull(), drawArithmeticalDSL(), exampleNaiveDSL(), exampleNaiveDSS(), exampleStandardDSL(), exampleStandardDSS(), exampleUpdate(), main(), testDisplay(), testExactMetricBalls(), testImageAdapter(), and testInexactMetricBalls().
saveEPS() [1/4]
void LibBoard::Board::saveEPS (const char * filename, double pageWidth, double pageHeight, double margin = 10.0) const
Saves the drawing in an EPS file. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
filename The EPS file name.
pageWidth Width of the page in millimeters.
pageHeight Height of the page in millimeters.
margin Minimal margin around the figure in the page, in millimeters.
Definition at line 812 of file Board.cpp.
 {
   std::ofstream file( filename );
   saveEPS(file, pageWidth, pageHeight, margin);
   file.close();
 }
References saveEPS().
saveEPS() [2/4]
void LibBoard::Board::saveEPS (const char * filename, PageSize size = Board::BoundingBox, double margin = 10.0) const
Saves the drawing in an EPS file. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
filename The EPS file name.
size Page size (Either BoundingBox (default), A4 or Letter).
margin Minimal margin around the figure in the page, in millimeters.
Examples
arithmetic/lower-integer-convex-hull.cpp, doc-examples/demo-kernel-1.cpp, geometry/curves/exampleAlphaThickSegment.cpp, geometry/curves/exampleAlphaThickSegmentNoisy.cpp, geometry/curves/exampleAlphaThickSegmentTgtCover.cpp, geometry/curves/exampleDigitalConvexity.cpp, geometry/curves/exampleFrechetShortcut.cpp, geometry/curves/exampleGridCurve2d.cpp, geometry/curves/exampleRationalConvexity.cpp, geometry/curves/greedy-dss-decomposition.cpp, geometry/curves/greedyAlphaThickDecomposition.cpp, geometry/tools/examplePreimage.cpp, graph/graphTraversal.cpp, io/boards/dgtalBoard2D-1-points.cpp, io/boards/dgtalBoard2D-2-sets.cpp, io/boards/dgtalBoard2D-3-custom-classes.cpp, io/boards/dgtalBoard2D-3-custom-points.cpp, io/boards/dgtalBoard2D-4-colormaps.cpp, io/boards/exampleBezierCurve.cpp, topology/ctopo-1.cpp, topology/ctopo-2.cpp, topology/ctopo-fillContours.cpp, topology/digitalSetToCubicalComplexes2D.cpp, topology/generateSimplicityTables2D.cpp, and tutorial-examples/freemanChainFromImage.cpp.
Definition at line 805 of file Board.cpp.
 {
   saveEPS( filename, pageSizes[size][0], pageSizes[size][1], margin );
 }
Referenced by checkCut(), checkOutputConvexHullBorder(), drawingTestStabbingCircleComputer(), drawingTestStabbingLineComputer(), greedySegmentationVisualTest(), main(), SaturatedSegmentationVisualTest(), save(), saveEPS(), specificTestLatticePolytope2D(), testAlphaThickSegmentComputerFloatingPointContour(), testAlphaThickSegmentConvexHullAndBox(), testAlphaThickSegmentFreeman(), testAlphaThickSpecialInit(), testAngleLinearMinimizer(), testBreadthFirstPropagation(), testCellDrawOnBoard(), testCMAP(), testComputeInterior(), testConvexHullCompThickness(), testDepthFirstPropagation(), testDigitization(), testDisplay(), testDistancePropagation(), testLatticePolytope2D(), testMultiWidth(), testPNMReader(), testSegmentation(), testSurfelAdjacency(), and testThicknessDefinitions().
saveEPS() [3/4]
void LibBoard::Board::saveEPS (std::ostream & out, double pageWidth, double pageHeight, double margin = 10.0) const
Saves the drawing in an EPS format through an output stream. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
out The output stream.
pageWidth Width of the page in millimeters.
pageHeight Height of the page in millimeters.
margin Minimal margin around the figure in the page, in millimeters.
Definition at line 820 of file Board.cpp.
 {
   Rect box = boundingBox();
   bool clipping = _clippingPath.size() > 2;
   if ( clipping )
     box = box && _clippingPath.boundingBox();
   TransformEPS transform;
   transform.setBoundingBox( box, pageWidth, pageHeight, margin );
   out << "%!PS-Adobe-2.0 EPSF-2.0" << std::endl;
   out << "%%Title:  output.eps " << std::endl;
   out << "%%Creator: Board library (Copyleft)2007 Sebastien Fourey" << std::endl;
   {
     time_t t = time(0);
     char str_time[255];
     secured_ctime( str_time, &t, 255 );
     out << "%%CreationDate: " << str_time;
   }
   out << "%%BoundingBox: " << std::setprecision( 8 )
        << transform.mapX( box.left ) << " "
        << transform.mapY( box.top - box.height ) << " "
        << transform.mapX( box.left + box.width ) << " "
        << transform.mapY( box.top ) << std::endl;
   out << "%Magnification: 1.0000" << std::endl;
   out << "%%EndComments" << std::endl;
   out << std::endl;
   out << "/cp {closepath} bind def" << std::endl;
   out << "/ef {eofill} bind def" << std::endl;
   out << "/gr {grestore} bind def" << std::endl;
   out << "/gs {gsave} bind def" << std::endl;
   out << "/sa {save} bind def" << std::endl;
   out << "/rs {restore} bind def" << std::endl;
   out << "/l {lineto} bind def" << std::endl;
   out << "/m {moveto} bind def" << std::endl;
   out << "/rm {rmoveto} bind def" << std::endl;
   out << "/n {newpath} bind def" << std::endl;
   out << "/s {stroke} bind def" << std::endl;
   out << "/sh {show} bind def" << std::endl;
   out << "/slc {setlinecap} bind def" << std::endl;
   out << "/slj {setlinejoin} bind def" << std::endl;
   out << "/slw {setlinewidth} bind def" << std::endl;
   out << "/srgb {setrgbcolor} bind def" << std::endl;
   out << "/rot {rotate} bind def" << std::endl;
   out << "/sc {scale} bind def" << std::endl;
   out << "/sd {setdash} bind def" << std::endl;
   out << "/ff {findfont} bind def" << std::endl;
   out << "/sf {setfont} bind def" << std::endl;
   out << "/scf {scalefont} bind def" << std::endl;
   out << "/sw {stringwidth} bind def" << std::endl;
   out << "/sd {setdash} bind def" << std::endl;
   out << "/tr {translate} bind def" << std::endl;
   out << " 0.5 setlinewidth" << std::endl;
   if ( clipping ) {
     out << " newpath ";
     _clippingPath.flushPostscript( out, transform );
     out << " 0 slw clip " << std::endl;
   }
   // Draw the background color if needed.
   if ( _backgroundColor != DGtal::Color::None ) {
     Rectangle r( box, DGtal::Color::None, _backgroundColor, 0.0f );
     r.flushPostscript( out, transform );
   }
   // Draw the shapes
   std::vector< Shape* > shapes = _shapes;
   stable_sort( shapes.begin(), shapes.end(), shapeGreaterDepth );
   std::vector< Shape* >::const_iterator i = shapes.begin();
   std::vector< Shape* >::const_iterator end = shapes.end();
   while ( i != end ) {
     (*i)->flushPostscript( out, transform );
     ++i;
   }
   out << "showpage" << std::endl;
   out << "%%Trailer" << std::endl;
   out << "%EOF" << std::endl;
 }
References _backgroundColor, _clippingPath, LibBoard::ShapeList::_shapes, LibBoard::Path::boundingBox(), LibBoard::ShapeList::boundingBox(), LibBoard::Path::flushPostscript(), LibBoard::Rect::height, LibBoard::Rect::left, DGtal::Color::None, LibBoard::secured_ctime(), LibBoard::TransformEPS::setBoundingBox(), LibBoard::shapeGreaterDepth(), LibBoard::Path::size(), LibBoard::Rect::top, and LibBoard::Rect::width.
saveEPS() [4/4]
void LibBoard::Board::saveEPS (std::ostream & out, PageSize size = Board::BoundingBox, double margin = 10.0) const
Saves the drawing in EPS format through an output stream. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
out The output stream.
size Page size (Either BoundingBox (default), A4 or Letter).
margin Minimal margin around the figure in the page, in millimeters.
Definition at line 799 of file Board.cpp.
 {
   saveEPS( out, pageSizes[size][0], pageSizes[size][1], margin );
 }
References saveEPS().
saveFIG() [1/4]
void LibBoard::Board::saveFIG (const char * filename, double pageWidth, double pageHeight, double margin = 10.0, bool includeFIGHeader = true) const
Saves the drawing in an XFig file. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
filename The XFig file name.
pageWidth Width of the page in millimeters.
pageHeight Height of the page in millimeters.
margin Minimal margin around the figure in the page, in millimeters.
includeFIGHeader Indicates if the header is included in the output stream. Useful to merge several XFIG figures (default true)
Definition at line 917 of file Board.cpp.
 {
   std::ofstream file( filename );
   saveFIG( file, pageWidth, pageHeight, margin, includeFIGHeader);
   file.close();
 }
References saveFIG().
saveFIG() [2/4]
void LibBoard::Board::saveFIG (const char * filename, PageSize size = Board::BoundingBox, double margin = 10.0, bool includeFIGHeader = true) const
Saves the drawing in an XFig file. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
filename The name of the FIG file.
size Page size (Either BoundingBox (default), A4 or Letter).
margin Minimal margin around the figure in the page, in millimeters.
includeFIGHeader Indicates if the header is included in the exported file. Useful to merge several XFIG figures (default true)
Examples
io/boards/exampleBezierCurve.cpp, topology/ctopo-2.cpp, topology/ctopo-fillContours.cpp, and topology/khalimskySpaceScanner.cpp.
Definition at line 907 of file Board.cpp.
 {
   saveFIG( filename, pageSizes[size][0], pageSizes[size][1], margin, includeFIGHeader );
 }
Referenced by main(), save(), saveFIG(), and testDisplay().
saveFIG() [3/4]
void LibBoard::Board::saveFIG (std::ostream & out, double pageWidth, double pageHeight, double margin = 10.0, bool includeFIGHeader = true) const
Saves the drawing in an XFig format through an output stream. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
out out The output stream.
pageWidth Width of the page in millimeters.
pageHeight Height of the page in millimeters.
margin Minimal margin around the figure in the page, in millimeters.
includeFIGHeader Indicates if the header is included in the output stream. Useful to merge several XFIG figures (default true)
Definition at line 926 of file Board.cpp.
 {
   TransformFIG transform;
   Rect box = boundingBox();
   transform.setBoundingBox( box, pageWidth, pageHeight, margin  );
   transform.setDepthRange( *this );
   if(includeFIGHeader){
     file << "#FIG 3.2  Produced by the Board library (Copyleft)2007 Sebastien Fourey\n";
     file << "Portrait\n";
     file << "Center\n";
     file << "Metric\n";
     file << "A4\n";
     file << "100.00\n";
     file << "Single\n";
     file << "-2\n";
     file << "1200 2\n";
   }else{
     file << "\n";
   }
   std::map<DGtal::Color,int> colormap;
   int maxColor = 32;
   colormap[DGtal::Color(0,0,0)] = 0;
   colormap[DGtal::Color(0,0,255)] = 1;
   colormap[DGtal::Color(0,255,0)] = 2;
   colormap[DGtal::Color(0,255,255)] = 0;
   colormap[DGtal::Color(255,0,0)] = 4;
   colormap[DGtal::Color(255,0,255)] = 0;
   colormap[DGtal::Color(255,255,0)] = 6;
   colormap[DGtal::Color(255,255,255)] = 7;
   std::vector< Shape* > shapes = _shapes;
   stable_sort( shapes.begin(), shapes.end(), shapeGreaterDepth );
   std::vector< Shape* >::const_iterator i = shapes.begin();
   std::vector< Shape* >::const_iterator end = shapes.end();
   while ( i != end ) {
     if ( colormap.find( (*i)->penColor() ) == colormap.end()
    && (*i)->penColor().valid() )
       colormap[ (*i)->penColor() ] = maxColor++;
     if ( colormap.find( (*i)->fillColor() ) == colormap.end()
    && (*i)->fillColor().valid() )
       colormap[ (*i)->fillColor() ] = maxColor++;
     ++i;
   }
   if ( colormap.find( _backgroundColor ) == colormap.end()
        && _backgroundColor.valid() )
     colormap[ _backgroundColor ] = maxColor++;
   // Write the colormap
   std::map<DGtal::Color,int>::const_iterator iColormap = colormap.begin();
   std::map<DGtal::Color,int>::const_iterator endColormap = colormap.end();
   char colorString[255];
   while ( iColormap != endColormap ) {
     secured_sprintf( colorString, 255,
                  "0 %d #%02x%02x%02x\n",
                  iColormap->second,
                    iColormap->first.red(),
                    iColormap->first.green(),
                    iColormap->first.blue() );
     if ( iColormap->second >= 32 ) file << colorString;
     ++iColormap;
   }
   // Draw the background color if needed.
   if ( _backgroundColor != DGtal::Color::None ) {
     Rectangle r( box, DGtal::Color::None, _backgroundColor, 0.0f );
     r.depth( std::numeric_limits<int>::max() );
     r.flushFIG( file, transform, colormap );
   }
   // Draw the shapes.
   i = shapes.begin();
   while ( i != end ) {
     // notice << (*i)->name() << " " << (*i)->depth() <<  '\n';
     (*i)->flushFIG( file, transform, colormap );
     ++i;
   }
 }
References _backgroundColor, LibBoard::ShapeList::_shapes, LibBoard::ShapeList::boundingBox(), max(), DGtal::Color::None, LibBoard::shapeGreaterDepth(), and DGtal::Color::valid().
saveFIG() [4/4]
void LibBoard::Board::saveFIG (std::ostream & out, PageSize size = Board::BoundingBox, double margin = 10.0, bool includeFIGHeader = true) const
Saves the drawing in XFig format through an output stream. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
out The output stream.
size Page size (Either BoundingBox (default), A4 or Letter).
margin Minimal margin around the figure in the page, in millimeters.
includeFIGHeader Indicates if the header is included in the output stream. Useful to merge several XFIG figures (default true)
Definition at line 912 of file Board.cpp.
 {
   saveFIG( out, pageSizes[size][0], pageSizes[size][1], margin, includeFIGHeader );
 }
References saveFIG().
saveSVG() [1/4]
void LibBoard::Board::saveSVG (const char * filename, double pageWidth, double pageHeight, double margin = 10.0) const
Saves the drawing in an SVG file. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
filename The SVG file name.
pageWidth Width of the page in millimeters.
pageHeight Height of the page in millimeters.
margin Minimal margin around the figure in the page, in millimeters.
Definition at line 1025 of file Board.cpp.
 {
   std::ofstream file( filename );
   saveSVG(file, pageWidth, pageHeight, margin);
   file.close();
 }
References saveSVG().
saveSVG() [2/4]
void LibBoard::Board::saveSVG (const char * filename, PageSize size = Board::BoundingBox, double margin = 10.0) const
Save the drawing in an SVG file. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
filename The name of the file.
size Page size (Either BoundingBox (default), A4 or Letter).
margin Minimal margin around the figure in the page, in millimeters.
Examples
dec/exampleDiscreteExteriorCalculusChladni.cpp, dec/exampleDiscreteExteriorCalculusSolve.cpp, dec/exampleDiscreteExteriorCalculusUsage.cpp, dec/examplePropagation.cpp, doc-examples/demo-kernel-1.cpp, doc-examples/kernelDomain.cpp, geometry/curves/convex-and-concave-parts.cpp, geometry/curves/exampleArithmeticalDSL.cpp, geometry/curves/exampleArithmeticalDSS.cpp, geometry/curves/greedy-dss-decomposition.cpp, geometry/surfaces/dvcm-2d-curvature.cpp, geometry/tools/exampleAlphaShape.cpp, geometry/tools/exampleConvexHull2D.cpp, geometry/tools/examplePreimage.cpp, geometry/volumes/distance/distancetransform2D.cpp, geometry/volumes/distance/toricdomainvolumetric.cpp, geometry/volumes/distance/voronoimap2D.cpp, geometry/volumes/dvcm-2d.cpp, images/exampleConstImageAdapter.cpp, images/exampleTiledImage.cpp, io/boards/dgtalBoard2D-1-points.cpp, io/boards/dgtalBoard2D-2-sets.cpp, io/boards/dgtalBoard2D-3-custom-classes.cpp, io/boards/dgtalBoard2D-3-custom-points.cpp, io/boards/dgtalBoard2D-4-colormaps.cpp, io/boards/exampleBezierCurve.cpp, io/boards/logoDGtal.cpp, shapes/exampleEuclideanShapesDecorator.cpp, topology/ctopo-1.cpp, and topology/khalimskySpaceScanner.cpp.
Definition at line 1012 of file Board.cpp.
 {
   saveSVG( filename, pageSizes[size][0], pageSizes[size][1], margin );
 }
Referenced by alphaShape(), convexHull(), exampleNaiveDSL(), exampleNaiveDSS(), exampleStandardDSL(), exampleStandardDSS(), exampleUpdate(), main(), moduleImages_example(), save(), saveSVG(), saveVoroMap(), showGreedySegmantation(), TEST_CASE(), test_linear_ring(), test_linear_structure(), test_manual_operators_2d(), testBIGINTEGERSpace(), testBoard2D(), testBoard2DCustomStyle(), testCellDrawOnBoard(), testChessboard(), testDigitalSetBoardSnippet(), testDigitalSetDraw(), testDigitization(), testDisplay(), testDistanceTransformation(), testDistanceTransformationBorder(), testDistanceTransformationNeg(), testDraw(), testDSS4drawing(), testDSS8drawing(), testDTFromSet(), testGetSetVal(), testImageAdapter(), testImplicitShape(), testKanungo2D(), testLatticePolytope2D(), testLayers(), testObjectBorder(), testPNMWriter(), testSegmentation(), testSimpleExpander(), testSimplePoints2D(), testSurfelAdjacency(), and testVoronoiMap().
saveSVG() [3/4]
void LibBoard::Board::saveSVG (std::ostream & out, double pageWidth, double pageHeight, double margin = 10.0, std::string filename = "output.svg") const
Saves the drawing in an SVG format through an output stream. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
out The output stream.
pageWidth Width of the page in millimeters.
pageHeight Height of the page in millimeters.
margin Minimal margin around the figure in the page, in millimeters.
filename default filename
Definition at line 1035 of file Board.cpp.
 {
   TransformSVG transform;
   Rect box = boundingBox();
   bool clipping = _clippingPath.size() > 2;
   if ( clipping )
     box = box && _clippingPath.boundingBox();
   transform.setBoundingBox( box, pageWidth, pageHeight, margin );
   file << "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" standalone=\"no\"?>" << std::endl;
   file << "<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"" << std::endl;
   file << " \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">" << std::endl;
   if ( pageWidth > 0 && pageHeight > 0 ) {
     file << "<svg width=\""
    << pageWidth << "mm\" height=\""
    << pageHeight << "mm\" " << std::endl;
     file << "     viewBox=\"0 0 "
     << pageWidth * ppmm  << " "
     << pageHeight * ppmm  << "\" " << std::endl;
     file << "     xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" >" << std::endl;
   } else {
     file << "<svg width=\""
    << ( box.width / ppmm )  << "mm"
    << "\" height=\""
    << ( box.height / ppmm ) << "mm"
    << "\" " << std::endl;
     file << "     viewBox=\"0 0 "
    << box.width  << " "
    << box.height << "\" " << std::endl;
     file << "     xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" >" << std::endl;
   }
   file << "<desc>" << filename
        << ", created with the Board library (Copyleft) 2007 Sebastien Fourey"
        << "</desc>" << std::endl;
   if ( clipping  ) {
     file << "<g clip-rule=\"nonzero\">\n"
    << " <clipPath id=\"GlobalClipPath\">\n"
    << "  <path clip-rule=\"evenodd\"  d=\"";
     _clippingPath.flushSVGCommands( file, transform );
     file << "\" />\n";
     file << " </clipPath>\n";
     file << "<g clip-path=\"url(#GlobalClipPath)\">\n";
   }
   // Draw the background color if needed.
   if ( _backgroundColor != DGtal::Color::None ) {
     Rectangle r( box, DGtal::Color::None, _backgroundColor, 0.0 );
     r.flushSVG( file, transform );
   }
   // Draw the shapes.
   std::vector< Shape* > shapes = _shapes;
   stable_sort( shapes.begin(), shapes.end(), shapeGreaterDepth );
   std::vector< Shape* >::const_iterator i = shapes.begin();
   std::vector< Shape* >::const_iterator end = shapes.end();
   while ( i != end ) {
     (*i)->flushSVG( file, transform );
     ++i;
   }
   if ( clipping )
     file << "</g>\n</g>";
   file << "</svg>" << std::endl;
 }
References _backgroundColor, _clippingPath, LibBoard::ShapeList::_shapes, LibBoard::Path::boundingBox(), LibBoard::ShapeList::boundingBox(), LibBoard::Path::flushSVGCommands(), LibBoard::Rect::height, DGtal::Color::None, LibBoard::shapeGreaterDepth(), LibBoard::Path::size(), and LibBoard::Rect::width.
saveSVG() [4/4]
void LibBoard::Board::saveSVG (std::ostream & out, PageSize size = Board::BoundingBox, double margin = 10.0) const
Save the drawing in an SVG format through an output stream. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
out The output stream.
size Page size (Either BoundingBox (default), A4 or Letter).
margin Minimal margin around the figure in the page, in millimeters.
Definition at line 1018 of file Board.cpp.
 {
   saveSVG( out, pageSizes[size][0], pageSizes[size][1], margin );
 }
References saveSVG().
saveTikZ() [1/4]
void LibBoard::Board::saveTikZ (const char * filename, double pageWidth, double pageHeight, double margin = 10.0) const
Save the drawing in an TikZ file. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
filename The name of the file.
pageWidth Width of the page in millimeters.
pageHeight Height of the page in millimeters.
margin Minimal margin around the figure in the page, in millimeters.
Definition at line 1231 of file Board.cpp.
 {
   std::ofstream file( filename );
   saveTikZ(file, pageHeight, pageHeight, margin);
   file.close();
 }
References saveTikZ().
saveTikZ() [2/4]
void LibBoard::Board::saveTikZ (const char * filename, PageSize size = Board::BoundingBox, double margin = 10.0) const
Save the drawing in an TikZ file. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
filename The name of the file.
size Page size (Either BoundingBox (default), A4 or Letter).
margin Minimal margin around the figure in the page, in millimeters.
Examples
io/boards/dgtalBoard2D-1-points.cpp, io/boards/dgtalBoard2D-2-sets.cpp, io/boards/dgtalBoard2D-3-custom-classes.cpp, io/boards/dgtalBoard2D-3-custom-points.cpp, io/boards/dgtalBoard2D-4-colormaps.cpp, io/boards/exampleBezierCurve.cpp, and topology/cubical-complex-illustrations.cpp.
Definition at line 1219 of file Board.cpp.
 {
   saveTikZ( filename, pageSizes[size][0], pageSizes[size][1], margin );
 }
Referenced by main(), save(), and saveTikZ().
saveTikZ() [3/4]
void LibBoard::Board::saveTikZ (std::ostream & out, double pageWidth, double pageHeight, double margin = 10.0) const
Save the drawing in an TikZ format through an output stream. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
out The output stream.
pageWidth Width of the page in millimeters.
pageHeight Height of the page in millimeters.
margin Minimal margin around the figure in the page, in millimeters.
Definition at line 1239 of file Board.cpp.
 {
   TransformTikZ transform;
   Rect box = boundingBox();
   bool clipping = _clippingPath.size() > 2;
   if ( clipping )
     box = box && _clippingPath.boundingBox();
   transform.setBoundingBox( box, pageWidth, pageHeight, margin );
   out << "\\begin{tikzpicture}[anchor=south west,text depth=0,x={(1pt,0pt)},y={(0pt,-1pt)}]" << std::endl;
   if ( clipping  ) {
     out << "\\clip ";
     _clippingPath.flushSVGCommands( out, transform );
     out << "\n";
   }
   // Draw the background color if needed.
   if ( _backgroundColor != DGtal::Color::None ) {
     Rectangle r( box, DGtal::Color::None, _backgroundColor, 0.0 );
     r.flushTikZ( out, transform );
   }
   // Draw the shapes.
   std::vector< Shape* > shapes = _shapes;
   stable_sort( shapes.begin(), shapes.end(), shapeGreaterDepth );
   std::vector< Shape* >::const_iterator i = shapes.begin();
   std::vector< Shape* >::const_iterator end = shapes.end();
   while ( i != end ) {
     (*i)->flushTikZ( out, transform );
     ++i;
   }
   //if ( clipping )
   //  out << "</g>\n</g>";
   out << "\\end{tikzpicture}" << std::endl;
 }
References _backgroundColor, _clippingPath, LibBoard::ShapeList::_shapes, LibBoard::Path::boundingBox(), LibBoard::ShapeList::boundingBox(), LibBoard::Path::flushSVGCommands(), DGtal::Color::None, LibBoard::shapeGreaterDepth(), and LibBoard::Path::size().
saveTikZ() [4/4]
void LibBoard::Board::saveTikZ (std::ostream & out, PageSize size = Board::BoundingBox, double margin = 10.0) const
Save the drawing in an TikZ file format through an output stream. When a size is given (not BoundingBox), the drawing is scaled (up or down) so that it fits within the dimension while keeping its aspect ratio.
Parameters
out The output stream.
size Page size (Either BoundingBox (default), A4 or Letter).
margin Minimal margin around the figure in the page, in millimeters.
Definition at line 1225 of file Board.cpp.
 {
   saveTikZ( out, pageSizes[size][0], pageSizes[size][1], margin );
 }
References saveTikZ().
scale() [1/2]
Shape & LibBoard::Board::scale (double s) virtual
Scale the shape along both axis.
Parameters
s The scale factor along both axis.
Returns
The shape itself.
Implements LibBoard::Shape.
Definition at line 197 of file Board.cpp.
 {
   Point delta = _clippingPath.center() - center();
   delta *= s;
   _clippingPath.scale( s );
   ShapeList::scale( s );
   delta = ( center() + delta ) - _clippingPath.center();
   _clippingPath.translate( delta.x, delta.y );
   return (*this);
 }
References _clippingPath, LibBoard::Path::center(), LibBoard::ShapeList::center(), LibBoard::Path::scale(), LibBoard::ShapeList::scale(), LibBoard::Path::translate(), LibBoard::Point::x, and LibBoard::Point::y.
scale() [2/2]
Shape & LibBoard::Board::scale (double sx, double sy) virtual
Scale the shape along the x an y axis.
Parameters
sx The scale factor along the x axis.
sy The scale factor along the y axis.
Returns
The shape itself.
Implements LibBoard::Shape.
Definition at line 184 of file Board.cpp.
 {
   Point delta = _clippingPath.center() - center();
   delta.x *= sx;
   delta.y *= sy;
   _clippingPath.scale( sx, sy );
   ShapeList::scale( sx, sy );
   delta = ( center() + delta ) - _clippingPath.center();
   _clippingPath.translate( delta.x, delta.y );
   return (*this);
 }
References _clippingPath, LibBoard::Path::center(), LibBoard::ShapeList::center(), LibBoard::Path::scale(), LibBoard::ShapeList::scale(), LibBoard::Path::translate(), LibBoard::Point::x, and LibBoard::Point::y.
Referenced by testDigitalSetDraw().
scaled() [1/2]
Board LibBoard::Board::scaled (double s)
Definition at line 233 of file Board.cpp.
 {
   return static_cast<const Board &>( Board( *this ).scale( s ) );
 }
References Board().
scaled() [2/2]
Board LibBoard::Board::scaled (double sx, double sy)
Definition at line 227 of file Board.cpp.
 {
   return static_cast<const Board &>( Board( *this ).scale( sx, sy ) );
 }
References Board().
setClippingPath() [1/2]
void LibBoard::Board::setClippingPath (const Path & path)
Define a clipping path for the whole drawing.
Parameters
path A path.
Definition at line 751 of file Board.cpp.
 {
   _clippingPath = path;
   _clippingPath.setClosed( true );
   if ( _clippingPath.size() > 1 ) {
     if ( _clippingPath[0] == _clippingPath[ _clippingPath.size() - 1 ] )
       _clippingPath.pop_back();
   }
   unsigned int n = _clippingPath.size();
   for ( unsigned int i = 0; i < n; ++i ) {
     _clippingPath[i] = _state.unit( _clippingPath[i] );
   }
 }
References _clippingPath, _state, LibBoard::Path::pop_back(), LibBoard::Path::setClosed(), LibBoard::Path::size(), and LibBoard::Board::State::unit().
setClippingPath() [2/2]
void LibBoard::Board::setClippingPath (const std::vector< Point > & points)
Define a clipping path for the whole drawing.
Parameters
points A path.
Definition at line 739 of file Board.cpp.
 {
   _clippingPath.clear();
   std::vector<Point>::const_iterator it = points.begin();
   std::vector<Point>::const_iterator end = points.end();
   while ( it != end ) {
     _clippingPath << _state.unit( *it );
     ++it;
   }
 }
References _clippingPath, _state, LibBoard::Path::clear(), and LibBoard::Board::State::unit().
setClippingRectangle()
void LibBoard::Board::setClippingRectangle (double x, double y, double width, double height)
Define a clipping rectangle for the whole drawing.
Parameters
x x
y y
width width
height height
Definition at line 728 of file Board.cpp.
 {
   _clippingPath.clear();
   _clippingPath << _state.unit( Point( xLeft, yTop ) );
   _clippingPath << _state.unit( Point( xLeft + rectWidth, yTop ) );
   _clippingPath << _state.unit( Point( xLeft + rectWidth, yTop - rectHeight) );
   _clippingPath << _state.unit( Point( xLeft , yTop - rectHeight ) );
 }
References _clippingPath, _state, LibBoard::Path::clear(), and LibBoard::Board::State::unit().
setFillColor()
Board & LibBoard::Board::setFillColor (const DGtal::Color & color)
Changes the current fill color.
In order to use no fill color, one may set this color to Color::None.
Parameters
color The fill color.
Returns
The board itself.
Examples
io/boards/dgtalBoard2D-3-custom-points.cpp, and io/boards/exampleBezierCurve.cpp.
Definition at line 322 of file Board.cpp.
 {
   _state.fillColor = color;
   return *this;
 }
References _state, and LibBoard::Board::State::fillColor.
Referenced by addColorMapSample(), main(), DGtal::CustomColors::setStyle(), DGtal::CustomFillColor::setStyle(), and DGtal::CustomPen::setStyle().
setFillColorRGBf()
Board & LibBoard::Board::setFillColorRGBf (float red, float green, float blue, float alpha = 1.0f)
Changes the current fill color.
Parameters
red Red component.
green Green component.
blue Blue component.
alpha The opacity.
Returns
The board itself.
Definition at line 315 of file Board.cpp.
 {
   _state.fillColor.setRGBf( red, green, blue, alpha );
   return *this;
 }
References _state, LibBoard::Board::State::fillColor, and DGtal::Color::setRGBf().
setFillColorRGBi()
Board & LibBoard::Board::setFillColorRGBi (unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha = 255)
Changes the current fill color.
Parameters
red Red component.
green Green component.
blue Blue component.
alpha The opacity.
Returns
The board itself.
Definition at line 305 of file Board.cpp.
 {
   _state.fillColor.setRGBi( red, green, blue, alpha );
   return *this;
 }
References _state, LibBoard::Board::State::fillColor, and DGtal::Color::setRGBi().
setFont()
Board & LibBoard::Board::setFont (const Fonts::Font font, double fontSize)
Changes the current font and font size.
Parameters
font The name of the font.
fontSize The new font size. (The unit is 1pt = 1/72 in).
Returns
The board itself.
Definition at line 336 of file Board.cpp.
 {
   _state.font = font;
   _state.fontSize = fontSize;
   return *this;
 }
References _state, LibBoard::Board::State::font, and LibBoard::Board::State::fontSize.
Referenced by addColorMapSample().
setFontSize()
Board & LibBoard::Board::setFontSize (double fontSize)
Changes the font size.
Parameters
fontSize The new font size. (The unit is 1pt = 1/72 in).
Returns
The board itself.
Definition at line 344 of file Board.cpp.
 {
   _state.fontSize = fontSize;
   return *this;
 }
References _state, and LibBoard::Board::State::fontSize.
setLineCap()
Board& LibBoard::Board::setLineCap (Shape::LineCap cap)
Set the line cap style.
Parameters
cap The cap-style which can be Shape::ButtCap, Shape::RoundCap or Shape::SquareCap.
Returns
The board itself.
Referenced by DGtal::CustomPen::setStyle().
setLineJoin()
Board& LibBoard::Board::setLineJoin (Shape::LineJoin join)
Set the line joine style.
Parameters
join The join-style which can be Shape::MiterJoin, Shape::RoundJoin or Shape::BevelJoin.
Returns
The board itself.
Referenced by DGtal::CustomPen::setStyle().
setLineStyle()
Board& LibBoard::Board::setLineStyle (Shape::LineStyle style)
Changes the current line style.
Parameters
style The new line style.
Returns
The board itself.
Referenced by DGtal::CustomPen::setStyle().
setLineWidth()
Board & LibBoard::Board::setLineWidth (double width)
Changes the current line thickness (1/72 inche unit).
Parameters
width The new line thickness.
Returns
The board itself.
Examples
geometry/curves/exampleRationalConvexity.cpp.
Definition at line 329 of file Board.cpp.
 {
   _state.lineWidth = width;
   return *this;
 }
References _state, and LibBoard::Board::State::lineWidth.
Referenced by DGtal::CustomPen::setStyle(), testAlphaThickSegmentComputerFloatingPointContour(), testAlphaThickSegmentConvexHullAndBox(), and testThicknessDefinitions().
setPenColor()
Board & LibBoard::Board::setPenColor (const DGtal::Color & color)
Changes the current pen color.
In order to use no pen, one may set the pen color to Color::None.
Parameters
color The pen color.
Returns
The board itself.
Examples
geometry/curves/exampleAlphaThickSegmentTgtCover.cpp, geometry/curves/exampleDigitalConvexity.cpp, geometry/curves/exampleRationalConvexity.cpp, geometry/curves/greedyAlphaThickDecomposition.cpp, geometry/tools/exampleConvexHull2D.cpp, io/boards/dgtalBoard2D-3-custom-points.cpp, and topology/khalimskySpaceScanner.cpp.
Definition at line 298 of file Board.cpp.
 {
   _state.penColor = color;
   return *this;
 }
References _state, and LibBoard::Board::State::penColor.
Referenced by addColorMapSample(), convexHull(), main(), DGtal::CustomColors::setStyle(), DGtal::CustomPenColor::setStyle(), DGtal::CustomPen::setStyle(), testAlphaThickSegmentComputerFloatingPointContour(), testAlphaThickSegmentConvexHullAndBox(), testAlphaThickSegmentFreeman(), testAlphaThickSpecialInit(), testConvexHullCompThickness(), testDisplay(), and testThicknessDefinitions().
setPenColorRGBf()
Board & LibBoard::Board::setPenColorRGBf (float red, float green, float blue, float alpha = 1.0f)
Changes the current pen color.
Parameters
red Red
green green
blue blue
alpha alpha
Returns
The board itself.
Definition at line 288 of file Board.cpp.
 {
   _state.penColor.setRGBf( red, green, blue, alpha );
   return *this;
 }
References _state, LibBoard::Board::State::penColor, and DGtal::Color::setRGBf().
setPenColorRGBi()
Board & LibBoard::Board::setPenColorRGBi (unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha = 255)
Changes the current pen color.
Parameters
red Red component.
green Green component.
blue Blue component.
alpha alpha component.
Returns
The board itself.
Examples
geometry/curves/exampleArithmeticalDSL.cpp, geometry/curves/exampleDigitalConvexity.cpp, and geometry/curves/exampleRationalConvexity.cpp.
Definition at line 278 of file Board.cpp.
 {
   _state.penColor.setRGBi( red, green, blue, alpha );
   return *this;
 }
References _state, LibBoard::Board::State::penColor, and DGtal::Color::setRGBi().
Referenced by drawArithmeticalDSL(), and main().
setUnit() [1/2]
void LibBoard::Board::setUnit (double factor, Unit unit)
Set the unit used by the drawSomething methods.
Parameters
factor The factor of the unit.
unit The unit to be used in { PT, IN, CM, MM }.
Definition at line 259 of file Board.cpp.
 {
   switch ( unit ) {
   case UPoint:
     _state.unitFactor = factor;
     break;
   case UInche:
     _state.unitFactor = 720.0f * factor;
     break;
   case UCentimeter:
     _state.unitFactor = 10.0f * ppmm * factor;
     break;
   case UMillimeter:
     _state.unitFactor = ppmm * factor;
     break;
   }
 }
References _state, UCentimeter, UInche, UMillimeter, LibBoard::Board::State::unitFactor, and UPoint.
setUnit() [2/2]
void LibBoard::Board::setUnit (Unit unit)
Set the unit used by the drawSomething methods.
Parameters
unit The unit to be used in { PT, IN, CM, MM }.
Examples
geometry/curves/exampleDigitalConvexity.cpp, geometry/curves/exampleGridCurve2d.cpp, geometry/curves/exampleRationalConvexity.cpp, geometry/tools/examplePreimage.cpp, geometry/volumes/distance/distancetransform2D.cpp, geometry/volumes/distance/exampleFMM2D.cpp, and geometry/volumes/distance/toricdomainvolumetric.cpp.
Definition at line 240 of file Board.cpp.
 {
   switch ( unit ) {
   case UPoint:
     _state.unitFactor = 1.0;
     break;
   case UInche:
     _state.unitFactor = 25.4f * ppmm;
     break;
   case UCentimeter:
     _state.unitFactor = 10.0f * ppmm;
     break;
   case UMillimeter:
     _state.unitFactor = ppmm;
     break;
   }
 }
References _state, UCentimeter, UInche, UMillimeter, LibBoard::Board::State::unitFactor, and UPoint.
Referenced by DGtal::Board2D::Board2D(), draw(), main(), operator<<(), TEST_CASE(), testBadKeySizes(), testBoard2D(), testBoard2DCustomStyle(), testCellDrawOnBoard(), testChessboard(), testDigitalSetBoardSnippet(), testDigitization(), testDisplay(), testDisplayDT3d(), testDistanceTransformation(), testDistanceTransformationBorder(), testDistanceTransformationNeg(), testDraw(), testDSS4drawing(), testDSS8drawing(), testExactMetricBalls(), testGetSetVal(), testInexactMetricBalls(), testLayers(), testObjectBorder(), testPNMWriter(), testSetTable(), testSimpleExpander(), testSimplePoints2D(), and testSurfelAdjacency().
translate()
Shape & LibBoard::Board::translate (double dx, double dy) virtual
Translate the shape by a given offset.
Parameters
dx The x offset.
dy The y offset.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Definition at line 176 of file Board.cpp.
 {
   ShapeList::translate( dx, dy );
   _clippingPath.translate( dx, dy );
   return (*this);
 }
References _clippingPath, LibBoard::Path::translate(), and LibBoard::ShapeList::translate().
Referenced by addColorMapSample().
translated()
Board LibBoard::Board::translated (double dx, double dy)
Definition at line 221 of file Board.cpp.
 {
   return static_cast<const Board &>( Board( *this ).translate( dx, dy ) );
 }
References Board().
Field Documentation
_backgroundColor
DGtal::Color LibBoard::Board::_backgroundColor protected
The color of the background.
Definition at line 956 of file Board.h.
Referenced by backgroundColor(), clear(), saveCairo(), saveEPS(), saveFIG(), saveSVG(), and saveTikZ().
_clippingPath
Path LibBoard::Board::_clippingPath protected
Definition at line 957 of file Board.h.
Referenced by rotate(), saveCairo(), saveEPS(), saveSVG(), saveTikZ(), scale(), setClippingPath(), setClippingRectangle(), and translate().
_state
State LibBoard::Board::_state protected
The current state.
Definition at line 955 of file Board.h.
Referenced by drawArc(), drawArrow(), drawBoundingBox(), drawCircle(), drawClosedPolyline(), drawDot(), drawEllipse(), drawImage(), drawLine(), drawPolyline(), drawQuadraticBezierCurve(), drawRectangle(), drawText(), drawTriangle(), fillCircle(), fillEllipse(), fillGouraudTriangle(), fillPolyline(), fillRectangle(), fillTriangle(), operator<<(), setClippingPath(), setClippingRectangle(), setFillColor(), setFillColorRGBf(), setFillColorRGBi(), setFont(), setFontSize(), setLineWidth(), setPenColor(), setPenColorRGBf(), setPenColorRGBi(), and setUnit().
Degree
const double LibBoard::Board::Degree = 3.14159265358979323846 / 180.0 static
Definition at line 44 of file Board.h.
The documentation for this class was generated from the following files:
Board.h
Board.cpp