DGtal: cubicalComplexThinning.cpp File Reference
cubicalComplexThinning.cpp File Reference
DGtal Examples
#include "ConfigExamples.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/topology/CubicalComplex.h"
#include "DGtal/topology/ParDirCollapse.h"
#include "DGtal/shapes/GaussDigitizer.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/shapes/EuclideanShapesDecorator.h"
#include "DGtal/shapes/parametric/Flower2D.h"
#include "DGtal/io/boards/Board2D.h"
Functions
template<typename CC , typename KSpace >
void getComplex (CC &complex, KSpace &K)
template<typename CC >
void drawComplex (Board2D &board, CC &complex)
int main (int, char **)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Kacper Pluta (kacpe.nosp@m.r.pl.nosp@m.uta@e.nosp@m.siee.nosp@m..fr) Laboratoire d'Informatique Gaspard-Monge - LIGM, France
Date
2016/01/16
An example file named cubicalComplexThinning.
This file is part of the DGtal library.
Definition in file cubicalComplexThinning.cpp.
Function Documentation
drawComplex()
template<typename CC > void drawComplex (Board2D & board, CC & complex)
Definition at line 73 of file cubicalComplexThinning.cpp.
 {
     board.clear();
     typedef typename CC::CellMapConstIterator CellMapConstIterator;
     for ( Dimension d = 0; d <= 2; ++d )
         for ( CellMapConstIterator it = complex.begin( d ), itE = complex.end( d );
                 it != itE; ++it )
         {
             if ( d == 0 )
                 board << CustomStyle( it->first.className(),
                         new CustomColors( Color( 0, 0, 0 ),
                             Color( 0, 0, 0 ) ) );
             else if ( d == 1 )
                 board << CustomStyle( it->first.className(),
                         new CustomColors( Color( 200, 0, 0 ),
                             Color( 100, 255, 100 ) ) );
             else
                 board << CustomStyle( it->first.className(),
                         new CustomColors( Color( 0, 0, 200 ),
                             Color( 100, 255, 100 ) ) );
             board << it->first;
         }
 }
References DGtal::CubicalComplex< TKSpace, TCellContainer >::begin(), LibBoard::Board::clear(), and DGtal::CubicalComplex< TKSpace, TCellContainer >::end().
getComplex()
template<typename CC , typename KSpace > void getComplex (CC & complex, KSpace & K)
Definition at line 54 of file cubicalComplexThinning.cpp.
 {
   typedef Flower2D< Space > MyEuclideanShape;
   MyEuclideanShape shape( RealPoint( 0.0, 0.0 ), 16, 5, 5, M_PI_2/2. );
   typedef GaussDigitizer< Space, MyEuclideanShape > MyGaussDigitizer;
   MyGaussDigitizer digShape;
   digShape.attach( shape );
   digShape.init ( shape.getLowerBound(), shape.getUpperBound(), 1.0 );
   Domain domainShape = digShape.getDomain();
   DigitalSet aSet( domainShape );
   Shapes<Domain>::digitalShaper( aSet, digShape );
   K.init ( domainShape.lowerBound(), domainShape.upperBound(), true );
   complex.clear();
   complex.construct ( aSet );
 }
References DGtal::GaussDigitizer< TSpace, TEuclideanShape >::attach(), DGtal::CubicalComplex< TKSpace, TCellContainer >::clear(), DGtal::CubicalComplex< TKSpace, TCellContainer >::construct(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), K, DGtal::HyperRectDomain< TSpace >::lowerBound(), and DGtal::HyperRectDomain< TSpace >::upperBound().
main()
int main (int , char **)
[create]
[create]
[init]
[init]
[thinn]
[thinn]
[thinnSurface]
[thinnSurface]
[thinnIsthmus]
[thinnIsthmus]
Definition at line 101 of file cubicalComplexThinning.cpp.
 {
   typedef map<Cell, CubicalCellData>   Map;
   typedef CubicalComplex< KSpace, Map >     CC;
   Board2D board;
   KSpace K;
   CC complex ( K );
   ParDirCollapse < CC > thinning ( K );
   trace.beginBlock ( "ParDirCollapse -- 2 iterations." );
     getComplex< CC, KSpace > ( complex, K );
     drawComplex<CC> ( board, complex );
     board.saveEPS ( "ComplexBeforeThinning.eps" );
     thinning.attach ( &complex );
     thinning.eval ( 2 );
     drawComplex<CC> ( board, complex );
     board.saveEPS ( "ParDirCollapse_2.eps" );
   trace.endBlock();
   trace.beginBlock ( "ParDirCollapse -- collapseSurface." );
     getComplex< CC, KSpace > ( complex, K );
     thinning.attach ( &complex );
     thinning.collapseSurface ();
     drawComplex<CC> ( board, complex );
     board.saveEPS ( "ParDirCollapse_collapseSurface.eps" );
   trace.endBlock();
   trace.beginBlock ( "ParDirCollapse -- collapseIsthmus." );
     getComplex< CC, KSpace > ( complex, K );
     thinning.attach ( &complex );
     thinning.collapseIsthmus ();
     drawComplex<CC> ( board, complex );
     board.saveEPS ( "ParDirCollapse_collapseIsthmus.eps" );
   trace.endBlock();
   return 0;
 }
References DGtal::ParDirCollapse< CC >::attach(), DGtal::Trace::beginBlock(), DGtal::ParDirCollapse< CC >::collapseIsthmus(), DGtal::ParDirCollapse< CC >::collapseSurface(), DGtal::Trace::endBlock(), DGtal::ParDirCollapse< CC >::eval(), K, LibBoard::Board::saveEPS(), and DGtal::trace.