DGtal: dgtalBoard3D-1-points.cpp File Reference
dgtalBoard3D-1-points.cpp File Reference
DGtal Examples
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/io/boards/Board3D.h"
#include "DGtal/helpers/StdDefs.h"
Functions
int main ()
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Aline MARTIN (aline.nosp@m..mar.nosp@m.tin@i.nosp@m.nsa-.nosp@m.lyon..nosp@m.fr)
Date
2013/06/16
An example file named dgtalBoard3D-1-points.
Definition in file dgtalBoard3D-1-points.cpp.
Function Documentation
main()
int main ()
[ExampleBoard3DExport]
[ExampleBoard3DExport]
Definition at line 50 of file dgtalBoard3D-1-points.cpp.
 {
   trace.beginBlock ( "Example dgtalBoard3D-1-points" );
   Point p1( -3, -2, 0 );
   Point p2( 7, 3 , 6);
   Point p3( -1, -1, -1);
   Point p4(-1, -1, 0 );
   Point p5( 5, 2 , 4);
   Point p6(-3, -6, 0 );
   Point p7( 5, 2 , 3);
   Domain domain(p4, p5);
   DigitalSet shape_set( domain );
   shape_set.insertNew(p6);
   shape_set.insertNew(p7);
   Board3D<> board;
   board << SetMode3D(domain.className(), "Paving");
   board << p1 << p2 << p3;
   board << shape_set;
   board.saveOBJ("dgtalBoard3D-1-points.obj");
   trace.info()<<" Second"<<std::endl;
   Board3D<> board2;
   board2 << SetMode3D(domain.className(), "Paving");
   board2 << CustomColors3D(Color(250, 0,0),Color(250, 0,0));
   board2 << p1 ;
   board2 << CustomColors3D(Color(0, 255,0),Color(0, 0,255));
   board2 << p2 << p3;
   board2 <<  CustomColors3D(Color(250, 0,0),Color(250, 0,0));
   board2 << p6;
   board2.saveOBJ("dgtalBoard3D-1bis-points.obj");
   trace.endBlock();
   return 0;
 }
References DGtal::Trace::beginBlock(), DGtal::HyperRectDomain< TSpace >::className(), domain, DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::insertNew(), DGtal::Board3D< Space, KSpace >::saveOBJ(), and DGtal::trace.