DGtal: exampleFMM2D.cpp File Reference
exampleFMM2D.cpp File Reference
DGtal Examples
Computation of a distance field from a given point
#include <iostream>
#include <iomanip>
#include <functional>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/kernel/sets/DigitalSetFromMap.h"
#include "DGtal/images/ImageContainerBySTLMap.h"
#include "DGtal/topology/SCellsFunctors.h"
#include "DGtal/shapes/ShapeFactory.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/topology/helpers/Surfaces.h"
#include "DGtal/shapes/GaussDigitizer.h"
#include "DGtal/geometry/volumes/distance/FMM.h"
#include "DGtal/io/colormaps/HueShadeColorMap.h"
#include "DGtal/io/boards/Board2D.h"
Functions
template<typename TImage >
void draw (const TImage aImg, const double &aMaxValue, std::string aBasename)
void example ()
We use FMM to compute a distance field from a given point.
int main (int argc, char **argv)
Detailed Description
Computation of a distance field from a given point
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Tristan Roussillon (trist.nosp@m.an.r.nosp@m.oussi.nosp@m.llon.nosp@m.@liri.nosp@m.s.cn.nosp@m.rs.fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2012/02/23
This file is part of the DGtal library.
Definition in file exampleFMM2D.cpp.
Function Documentation
draw()
template<typename TImage > void draw (const TImage aImg, const double & aMaxValue, std::string aBasename)
Function that displays an image with Board2D
Parameters
aImg an image
aMaxValue maximal value used in the color map
aBasename base name of the file
Template Parameters
TImage a model of CImage
Definition at line 89 of file exampleFMM2D.cpp.
 {
   typedef typename TImage::Domain::ConstIterator ConstIteratorOnPoints;
   typedef typename TImage::Domain::Point Point;
   HueShadeColorMap<double, 2> colorMap(0,aMaxValue);
   Board2D b;
   b.setUnit ( LibBoard::Board::UCentimeter );
   for (ConstIteratorOnPoints it = aImg.domain().begin(), itEnd = aImg.domain().end();
        it != itEnd; ++it)
     {
       Point p = *it;
       b << CustomStyle( p.className(), new CustomFillColor( colorMap( aImg(p) ) ) );
       b << p;
     }
   {
     std::stringstream s;
     s << aBasename << ".eps";
     b.saveEPS(s.str().c_str());
   }
   #ifdef WITH_CAIRO
   {
     std::stringstream s;
     s << aBasename << ".png";
     b.saveCairo(s.str().c_str(), Board2D::CairoPNG);
   }
   #endif
 }
References LibBoard::Board::setUnit(), and LibBoard::Board::UCentimeter.
Referenced by example().
example()
void example ()
We use FMM to compute a distance field from a given point.
[FMMSimpleTypeDef]
[FMMSimpleTypeDef]
[FMMSimpleExternalData]
[FMMSimpleExternalData]
[FMMSimpleInit]
[FMMSimpleInit]
[FMMSimpleCtor]
[FMMSimpleCtor]
[FMMSimpleComputation]
[FMMSimpleComputation]
Examples
geometry/volumes/distance/exampleFMM2D.cpp.
Definition at line 124 of file exampleFMM2D.cpp.
 {
   trace.beginBlock ( "DT by FMM from one point" );
   //Typedefs
   typedef ImageContainerBySTLMap<Z2i::Domain,double> DistanceImage;
   typedef DigitalSetFromMap<DistanceImage> AcceptedPointSet;
   typedef Z2i::Domain::Predicate DomainPredicate;
   typedef FMM<DistanceImage, AcceptedPointSet, DomainPredicate> FMM;
   //Constructions
   int size = 25;
   Z2i::Domain domain(Z2i::Point::diagonal(-size),
                      Z2i::Point::diagonal(size) );
   DistanceImage distanceImage( domain );
   AcceptedPointSet set( distanceImage );
   Z2i::Point origin = Z2i::Point::diagonal(0);
   set.insert( origin );
   distanceImage.setValue( origin, 0.0 );
   FMM fmm( distanceImage, set, domain.predicate() );
   trace.info() << "Init: " << fmm << std::endl;
   fmm.compute();
   trace.info() << "End: " << fmm << std::endl;
   //display - you should see concentric circles
   //around the center point.
   std::stringstream s;
   s << "DTbyFMM-" << size;
   draw(distanceImage, fmm.max(), s.str());
   trace.endBlock();
 }
References DGtal::Trace::beginBlock(), DGtal::FMM< TImage, TSet, TPointPredicate, TPointFunctor >::compute(), domain, draw(), DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::FMM< TImage, TSet, TPointPredicate, TPointFunctor >::max(), DGtal::HyperRectDomain< TSpace >::predicate(), and DGtal::trace.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 181 of file exampleFMM2D.cpp.
 {
   trace.beginBlock ( "Example 2d FMM" );
   trace.info() << "Args:";
   for ( int i = 0; i < argc; ++i )
     trace.info() << " " << argv[ i ];
   trace.info() << endl;
   //computation
   example();
   trace.endBlock();
   return 1;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), example(), DGtal::Trace::info(), and DGtal::trace.