DGtal: exampleInHalfPlane.cpp File Reference
exampleInHalfPlane.cpp File Reference
DGtal Examples
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/geometry/tools/determinant/Simple2x2DetComputer.h"
#include "DGtal/geometry/tools/determinant/SimpleIncremental2x2DetComputer.h"
#include "DGtal/geometry/tools/determinant/AvnaimEtAl2x2DetSignComputer.h"
#include "DGtal/geometry/tools/determinant/Filtered2x2DetComputer.h"
#include "DGtal/geometry/tools/determinant/InHalfPlaneBy2x2DetComputer.h"
#include "DGtal/geometry/tools/determinant/PredicateFromOrientationFunctor2.h"
#include "DGtal/geometry/tools/determinant/InHalfPlaneBySimple3x3Matrix.h"
Functions
bool basicUsage ()
void advice ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Tristan Roussillon (trist.nosp@m.an.r.nosp@m.oussi.nosp@m.llon.nosp@m.@liri.nosp@m.s.cn.nosp@m.rs.fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2013/11/28
An example file named exampleInHalfPlane.
This file is part of the DGtal library.
Definition in file exampleInHalfPlane.cpp.
Function Documentation
advice()
void advice ()
[FunctorDefinition30]
[FunctorDefinition30]
[FunctorDefinition52]
[FunctorDefinition52]
[FunctorDefinition62]
[FunctorDefinition62]
[FunctorDefinition62bis]
[FunctorDefinition62bis]
[FunctorDefinition62plus]
[FunctorDefinition62plus]
Examples
geometry/tools/determinant/exampleInHalfPlane.cpp.
Definition at line 112 of file exampleInHalfPlane.cpp.
 {
   {
   //for coordinates of 30 (not zero) bits
   typedef PointVector<2, DGtal::int32_t> Point;
   typedef InHalfPlaneBySimple3x3Matrix<Point, DGtal::int64_t> Functor;
   Functor *a = new Functor();
   BOOST_VERIFY(a);
   delete a;
   }
   {
   //for coordinates of 52 (not zero) bits
   typedef PointVector<2, DGtal::int64_t> Point;
   typedef AvnaimEtAl2x2DetSignComputer<double> DetComputer;
   typedef Filtered2x2DetComputer<DetComputer> FDetComputer;
   typedef InHalfPlaneBy2x2DetComputer<Point, FDetComputer> Functor;
   Functor *a = new Functor();
   BOOST_VERIFY(a);
   delete a;
   //NB. using double as coordinate type is slightly faster than using DGtal::int64_t
   //typedef PointVector<2, double> Point;
   }
   {
   //for coordinates of 62 (not zero) bits
   typedef PointVector<2, DGtal::int64_t> Point;
   typedef AvnaimEtAl2x2DetSignComputer<DGtal::int64_t> DetComputer;
   typedef InHalfPlaneBy2x2DetComputer<Point, DetComputer> Functor;
   Functor *a= new Functor();
   BOOST_VERIFY( a);
   delete a;
   }
   {
   //for coordinates of 62 (not zero) bits
   //if long double is implemented as the 80-bit extended precision type
   typedef PointVector<2, DGtal::int64_t> Point;
   typedef AvnaimEtAl2x2DetSignComputer<long double> DetComputer;
   typedef Filtered2x2DetComputer<DetComputer> FDetComputer;
   typedef InHalfPlaneBy2x2DetComputer<Point, FDetComputer> Functor;
   Functor *a = new Functor();
   BOOST_VERIFY(a == a);
   delete a;
   }
 #ifdef WITH_BIGINTEGER
   {
   //for arbitrary coordinates
   typedef PointVector<2, DGtal::BigInteger> Point;
   typedef Simple2x2DetComputer<DGtal::BigInteger> DetComputer;
   typedef InHalfPlaneBy2x2DetComputer<Point, DetComputer> Functor;
   Functor *a= new Functor();
   BOOST_VERIFY( a);
   delete a;
   }
 #endif
 }
Referenced by main().
basicUsage()
bool basicUsage ()
[DomainDefinition]
[DomainDefinition]
[ProblemStatement]
[ProblemStatement]
[FunctorDefinition]
[FunctorDefinition]
[PredicateDefinition]
[PredicateDefinition]
[FunctorInitialization]
[FunctorInitialization]
[PredicateUsage]
[PredicateUsage]
Definition at line 62 of file exampleInHalfPlane.cpp.
 {
   //domain definition
   typedef SpaceND< 2, DGtal::int16_t > DigitalSpace;
   typedef HyperRectDomain< DigitalSpace > Domain;
   typedef Domain::Point Point;
   Domain domain( Point(-32767,-32767), Point(32767,32767) );
   Point P, Q, R;
   P = Point(0,0);
   Q = Point(5,2);
   R = Point(2,1);
   //problem: are P, Q, R counter-clockwise oriented ?
   //orientation functor
   typedef InHalfPlaneBySimple3x3Matrix<Point, DGtal::int32_t> OrientationFunctor;
   OrientationFunctor orientationFunctor;
   //geometric predicate
   PredicateFromOrientationFunctor2<OrientationFunctor>
     pointPredicate( orientationFunctor );
   //initialization
   pointPredicate.init( P, Q );
   //which is equivalent to
   //orientationFunctor.init( P, Q );
   //because the predicate stores a pointer to the functor
   bool isCCW;
   //decision
   isCCW = pointPredicate( R );
   //which is equivalent to the following shortcut:
   //isCCW = pointPredicate( P, Q, R );
   return isCCW;
 }
References domain, and DGtal::PredicateFromOrientationFunctor2< TOrientationFunctor, acceptNeg, acceptZero >::init().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 182 of file exampleInHalfPlane.cpp.
 {
   trace.beginBlock ( "Example exampleInHalfPlane" );
   trace.info() << "Args:";
   for ( int i = 0; i < argc; ++i )
     trace.info() << " " << argv[ i ];
   trace.info() << endl;
   basicUsage();
   advice();
   trace.endBlock();
   return 0;
 }
References advice(), basicUsage(), DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.