DGtal: exampleRigidtransformation3d.cpp File Reference
exampleRigidtransformation3d.cpp File Reference
DGtal Examples
#include <iostream>
#include <cmath>
#include "DGtal/images/ImageSelector.h"
#include "DGtal/images/ImageContainerBySTLVector.h"
#include "DGtal/images/ConstImageAdapter.h"
#include "ConfigExamples.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/base/Common.h"
#include "DGtal/io/readers/VolReader.h"
#include "DGtal/io/writers/GenericWriter.h"
#include "DGtal/kernel/BasicPointFunctors.h"
#include "DGtal/images/RigidTransformation3D.h"
Functions
int main (int, char **)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Kacper Pluta (kacpe.nosp@m.r.pl.nosp@m.uta@e.nosp@m.siee.nosp@m..fr) Laboratoire d'Informatique Gaspard-Monge - LIGM, France
Date
2014/06/28
An example file named rigidtransformation3d.
This file is part of the DGtal library.
Definition in file exampleRigidtransformation3d.cpp.
Function Documentation
main()
int main (int , char **)
[def]
[def]
[trans]
[trans] [init_domain_helper]
[init_domain_helper]
[domain]
[domain]
[backward]
[backward]
[forward]
[forward]
Definition at line 63 of file exampleRigidtransformation3d.cpp.
 {
   typedef ImageSelector<Domain, unsigned char >::Type Image;
   typedef ForwardRigidTransformation3D < Space > ForwardTrans;
   typedef BackwardRigidTransformation3D < Space > BackwardTrans;
   typedef ConstImageAdapter<Image, Domain, BackwardTrans, Image::Value, Identity > MyImageBackwardAdapter;
   typedef DomainRigidTransformation3D < Domain, ForwardTrans > MyTransformedDomain;
   typedef MyTransformedDomain::Bounds Bounds;
   trace.beginBlock ( "Example rigidtransformation3d" );
     ForwardTrans forwardTrans( Point ( 5, 5, 5 ), RealVector ( 1, 0, 1 ), M_PI_4, RealVector( 3, -3, 3 ) );
     BackwardTrans backwardTrans( Point ( 5, 5, 5 ), RealVector ( 1, 0, 1 ), M_PI_4, RealVector( 3, -3, 3 ) );
     MyTransformedDomain domainForwardTrans ( forwardTrans );
     Identity idD;
     Image image = VolReader<Image>::importVol ( examplesPath + "samples/cat10.vol" );
     Bounds bounds = domainForwardTrans ( image.domain() );
     Domain transformedDomain ( bounds.first, bounds.second );
     trace.beginBlock ( "Backward - Eulerian model" );
       MyImageBackwardAdapter adapter ( image, transformedDomain, backwardTrans, idD );
       adapter >> "backward_transform.pgm3d";
     trace.endBlock();
     trace.beginBlock( "Forward - Lagrangian model" );
       Image transformed ( transformedDomain );
       for ( Domain::ConstIterator it = image.domain().begin(); it != image.domain().end(); ++it )
       {
         transformed.setValue ( forwardTrans ( *it ), image ( *it ) );
       }
       transformed >> "forward_transform.pgm3d";
     trace.endBlock();
   trace.endBlock();
   return 0;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Image< TImageContainer >::setValue(), and DGtal::trace.