DGtal: exampleAlphaThickSegmentNoisy.cpp File Reference
exampleAlphaThickSegmentNoisy.cpp File Reference
DGtal Examples
#include <iostream>
#include "ConfigExamples.h"
#include "DGtal/base/Common.h"
#include "DGtal/geometry/curves/AlphaThickSegmentComputer.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/io/readers/PointListReader.h"
#include "DGtal/io/boards/Board2D.h"
Functions
int main ()
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Bertrand Kerautret (kerau.nosp@m.tre@.nosp@m.loria.nosp@m..fr) LORIA (CNRS, UMR 7503), University of Nancy, France
Date
2015/01/30
An example file named exampleAlphaThickSegmentNoisy.
This file is part of the DGtal library.
Definition in file exampleAlphaThickSegmentNoisy.cpp.
Function Documentation
main()
int main ()
[exampleAlphaThickSegmentNoisyTypedef]
[exampleAlphaThickSegmentNoisyTypedef]
[exampleAlphaThickSegmentNoisyReadFile]
[exampleAlphaThickSegmentNoisyReadFile]
[exampleAlphaThickSegmentNoisInitAndReco] [exampleAlphaThickSegmentNoisInit]
[exampleAlphaThickSegmentNoisInit] [exampleAlphaThickSegmentNoisReco]
[exampleAlphaThickSegmentNoisReco] [exampleAlphaThickSegmentNoisInitAndReco]
[exampleAlphaThickSegmentDisplay]
[exampleAlphaThickSegmentDisplay]
[exampleAlphaThickSegmentNoisInitAndReco2]
[exampleAlphaThickSegmentNoisInitAndReco2]
[exampleAlphaThickSegmentNoisCustomColor]
[exampleAlphaThickSegmentNoisCustomColor]
Definition at line 59 of file exampleAlphaThickSegmentNoisy.cpp.
 {
   trace.beginBlock ( "Example exampleAlphaThickSegment" );
   typedef  AlphaThickSegmentComputer< Z2i::RealPoint > AlphaThickSegmentComputer2D;
   Board2D aBoard;
   std::string file = examplesPath + "samples/contourSnoisy.sdp";
   std::vector<Z2i::RealPoint> aContour = PointListReader<Z2i::RealPoint>::getPointsFromFile(file);
   // displaying contour
   aBoard << SetMode(aContour[0].className(), "Grid");
   for (unsigned int i = 0; i< aContour.size(); i++){
       aBoard << aContour[i];
       aBoard.drawLine(aContour[i][0], aContour[i][1],
                   aContour[(i+1)%aContour.size()][0], aContour[(i+1)%aContour.size()][1]);
   }
   //initialisation of an AlphaThickSegmentComputer2D of thickness 10 and forward recognition.
   AlphaThickSegmentComputer2D anAlphaSegment(15);
   std::vector<Z2i::RealPoint>::const_iterator it =  aContour.begin();
   while (anAlphaSegment.extendFront(*it)) {
     it++;
   }
   aBoard << anAlphaSegment;
   AlphaThickSegmentComputer2D anAlphaSegment2(9);
   anAlphaSegment2.init(aContour.begin());
   while (anAlphaSegment2.end() != aContour.end() &&
          anAlphaSegment2.extendFront()) {
   }
   aBoard << CustomStyle( anAlphaSegment2.className(), new CustomColors( DGtal::Color::Blue, DGtal::Color::None ) );
   aBoard << anAlphaSegment2;
   AlphaThickSegmentComputer2D  anAlphaSegment3(2);
   anAlphaSegment3.init(aContour.begin());
   while (anAlphaSegment3.end() != aContour.end() &&
          anAlphaSegment3.extendFront()) {
   }
   aBoard  << CustomStyle( anAlphaSegment3.className(), new CustomColors( DGtal::Color::Green, DGtal::Color::None ) );
   aBoard << anAlphaSegment3;
   aBoard.saveEPS("exampleAlphaThickSegmentNoisy.eps");
   trace.endBlock();
   return 0;
 }
References DGtal::Trace::beginBlock(), DGtal::Color::Blue, LibBoard::Board::drawLine(), DGtal::Trace::endBlock(), DGtal::Color::Green, DGtal::Color::None, LibBoard::Board::saveEPS(), and DGtal::trace.