DGtal: exampleGridCurve3d.cpp File Reference
exampleGridCurve3d.cpp File Reference
DGtal Examples
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "ConfigExamples.h"
#include "DGtal/io/viewers/Viewer3D.h"
#include "DGtal/geometry/curves/GridCurve.h"
Functions
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Tristan Roussillon (trist.nosp@m.an.r.nosp@m.oussi.nosp@m.llon.nosp@m.@liri.nosp@m.s.cn.nosp@m.rs.fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2012/06/03
An example file for GridCurve, defined as a sequence of 1-scells, in a 3d Khalimsky space.
This file is part of the DGtal library.
Definition in file exampleGridCurve3d.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
[GridCurveDeclaration]
[GridCurveDeclaration]
[GridCurveFromDataFile]
[GridCurveFromDataFile]
Definition at line 73 of file exampleGridCurve3d.cpp.
 {
   trace.info() << "exampleGridCurve3d: the type of data to be displayed "
                << "may be given as argument as follows: "
                << argv[0] << " scells" << endl;
   trace.info() << "Available types are: gridcurve (default), scells, points, midpoints, arrows" << endl;
   string type = (argc > 1) ? string(argv[1]) : "gridcurve";
   trace.info() << "Chosen type: " << type << endl;
   //curve
   string sinus = examplesPath + "samples/sinus.dat";
   // domain
   Point lowerBound = Point::diagonal( -100 );
   Point upperBound = Point::diagonal( 100 );
   K3 ks; ks.init( lowerBound, upperBound, true );
   GridCurve<K3> gc( ks );
   fstream inputStream;
   inputStream.open (sinus.c_str(), ios::in);
   gc.initFromVectorStream(inputStream);
   inputStream.close();
   bool flag = false;
 #ifdef WITH_VISU3D_QGLVIEWER
   QApplication application(argc,argv);
   Viewer3D<Space,K3> viewer(ks);
   viewer.show();
   if (type == "gridcurve")
     {
       viewer  << gc;
     }
   else if (type == "scells")
     {
       viewer << gc.getSCellsRange();
     }
   else if (type == "points")
     {
       viewer << gc.getPointsRange();
     }
   else if (type == "midpoints")
     {
       viewer << gc.getMidPointsRange();
     }
   else if (type == "arrows")
     {
       viewer << gc.getArrowsRange();
     }
   else
     {
       trace.info() << "Display type not known." << std::endl;
     }
   viewer << Viewer3D<Space,K3>::updateDisplay;
   flag = application.exec();
 #endif
   return flag;
 }
References DGtal::GridCurve< TKSpace >::getArrowsRange(), DGtal::GridCurve< TKSpace >::getMidPointsRange(), DGtal::GridCurve< TKSpace >::getPointsRange(), DGtal::GridCurve< TKSpace >::getSCellsRange(), DGtal::Trace::info(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), DGtal::GridCurve< TKSpace >::initFromVectorStream(), DGtal::Viewer3D< TSpace, TKSpace >::show(), and DGtal::trace.