DGtal: exampleTrofoliKnot.cpp File Reference
exampleTrofoliKnot.cpp File Reference
DGtal Examples
#include <iostream>
#include <iterator>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "ConfigExamples.h"
#include "DGtal/io/viewers/Viewer3D.h"
#include "DGtal/geometry/curves/parametric/Knot_3_1.h"
#include "DGtal/geometry/curves/parametric/NaiveParametricCurveDigitizer3D.h"
Functions
template<typename T >
unsigned char findMainAxis (const T &curve, const long double &t)
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Kacper Pluta (kacper.pluta@esiee.fr) Laboratoire d'Informatique Gaspard-Monge - LIGM, A3SI, France
Date
2018/08/03
An example file for ParametriCurveDigitizer3D.
This file is part of the DGtal library.
Definition in file exampleTrofoliKnot.cpp.
Function Documentation
findMainAxis()
template<typename T > unsigned char findMainAxis (const T & curve, const long double & t) inline
Definition at line 54 of file exampleTrofoliKnot.cpp.
 {
  RealPoint value;
  value[0] = std::abs ( curve.xp ( t )[0] );
  value[1] = std::abs ( curve.xp ( t )[1] );
  value[2] = std::abs ( curve.xp ( t )[2] );
  if ( value[0] >= value[1] && value[0] >= value[2] )
   return 0;
  else if ( value[1] >= value[0] && value[1] >= value[2] )
   return 1;
  else
   return 2;
 }
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 70 of file exampleTrofoliKnot.cpp.
 {
  QApplication application(argc,argv);
  typedef Knot_3_1< Space > MyKnot;
  typedef NaiveParametricCurveDigitizer3D < MyKnot >  Digitizer;
  typedef NaiveParametricCurveDigitizer3D < MyKnot >::DigitalCurve MyDigitalCurve;
  typedef NaiveParametricCurveDigitizer3D < MyKnot >::MetaData MyMetaData;
  trace.info() << "exampleParamCurve3dDigitization" << endl;
  Viewer3D<> viewer;
  MyDigitalCurve digitalCurve;
  MyMetaData metaData;
  MyKnot knot ( 10, 10, 10 );
  Digitizer digitize;
  digitize.attach ( &knot );
  digitize.init ( -2.1, 2.1, 0.0001 );
  digitize.digitize( back_insert_iterator < MyDigitalCurve> ( digitalCurve ), back_insert_iterator < MyMetaData > ( metaData ) );
  trace.info() << "Number of points: " << digitalCurve.size () << " number of metadata: " << metaData.size () << endl;
  viewer.show();
  for ( unsigned int i = 0; i < digitalCurve.size ( ); i++ )
  {
   if ( findMainAxis ( knot, metaData.at ( i ).first ) == 0 )
    viewer.setFillColor ( Color ( 255, 0, 0, 128 ) );
   if ( findMainAxis ( knot, metaData.at ( i ).first ) == 1 )
    viewer.setFillColor ( Color ( 0, 255, 0, 128 ) );
   if ( findMainAxis ( knot, metaData.at ( i ).first ) == 2 )
    viewer.setFillColor ( Color ( 0, 0, 255, 128 ) );
   viewer << SetMode3D ( digitalCurve.at ( i ).className ( ), "PavingWired" ) << digitalCurve.at ( i );
  }
  viewer << Viewer3D<>::updateDisplay;
  return application.exec();
 }
References digitize(), findMainAxis(), DGtal::Trace::info(), DGtal::Display3D< SpaceND< 3 >, KhalimskySpaceND< 3 > >::setFillColor(), DGtal::Viewer3D< TSpace, TKSpace >::show(), and DGtal::trace.