DGtal: meshFromOFF.cpp File Reference
meshFromOFF.cpp File Reference
DGtal Examples
#include "DGtal/io/readers/MeshReader.h"
#include "DGtal/io/Display3D.h"
#include "DGtal/io/viewers/Viewer3D.h"
#include "DGtal/base/Common.h"
#include "DGtal/io/Color.h"
#include "ConfigExamples.h"
Functions
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Bertrand Kerautret (kerau.nosp@m.tre@.nosp@m.loria.nosp@m..fr) LORIA (CNRS, UMR 7503), University of Nancy, France
Date
2012/07/05
An example file named meshFromOFF.
This file is part of the DGtal library.
Definition in file meshFromOFF.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
[ImportOFFfile]
[ImportOFFfile]
[displayOFFfile]
[displayOFFfile]
Definition at line 60 of file meshFromOFF.cpp.
 {
   QApplication application(argc,argv);
   Viewer3D<> viewer;
   viewer.show();
   std::string inputFilename = examplesPath + "samples/tref.off";
   // Since the input points are not necessary integers we use the PointD3D from Display3D.
   Mesh<Viewer3D<>::RealPoint> anImportedMesh;
   anImportedMesh << inputFilename;
   trace.info()<< "importating done..."<< endl;
   viewer.setLineColor(DGtal::Color(150,0,0,254));
   viewer << anImportedMesh;
   viewer << Viewer3D<>::updateDisplay;
   return application.exec();
 }
References DGtal::Trace::info(), DGtal::Display3D< SpaceND< 3 >, KhalimskySpaceND< 3 > >::setLineColor(), DGtal::Viewer3D< TSpace, TKSpace >::show(), and DGtal::trace.