DGtal: boost Namespace Reference
boost Namespace Reference
Data Structures
struct AdaptableBinaryFunction
Go to http://www.sgi.com/tech/stl/AdaptableBinaryFunction.html.
struct AdaptableBinaryPredicate
Go to http://www.sgi.com/tech/stl/AdaptableBinaryPredicate.html.
struct AdaptableGenerator
Go to http://www.sgi.com/tech/stl/AdaptableGenerator.html.
struct AdaptablePredicate
Go to http://www.sgi.com/tech/stl/AdaptablePredicate.html.
struct AdaptableUnaryFunction
Go to http://www.sgi.com/tech/stl/AdaptableUnaryFunction.html.
struct AdjacencyGraphConcept
Go to http://www.boost.org/doc/libs/1_52_0/libs/graph/doc/AdjacencyGraph.html.
struct Assignable
Go to http://www.sgi.com/tech/stl/Assignable.html.
struct AssociativeContainer
Go to http://www.sgi.com/tech/stl/AssociativeContainer.html.
struct BackInsertionSequence
Go to http://www.sgi.com/tech/stl/BackInsertionSequence.html.
struct BidirectionalIterator
Go to http://www.sgi.com/tech/stl/BidirectionalIterator.html.
struct BinaryFunction
Go to http://www.sgi.com/tech/stl/BinaryFunction.html.
struct BinaryPredicate
Go to http://www.sgi.com/tech/stl/BinaryPredicate.html.
struct Collection
Go to http://www.sgi.com/tech/stl/Collection.html.
struct Const_BinaryPredicate
Go to http://www.boost.org/libs/concept_check/reference.htm.
struct Container
Go to http://www.sgi.com/tech/stl/Container.html.
struct Convertible
Go to http://www.boost.org/libs/concept_check/reference.htm.
struct CopyConstructible
Go to http://www.sgi.com/tech/stl/CopyConstructible.html.
struct DefaultConstructible
Go to http://www.sgi.com/tech/stl/DefaultConstructible.html.
struct DigitalSurface_graph_traversal_category
struct EdgeListGraphConcept
Go to http://www.boost.org/doc/libs/1_52_0/libs/graph/doc/EdgeListGraph.html.
struct EqualityComparable
Go to http://www.sgi.com/tech/stl/EqualityComparable.html.
struct ForwardContainer
Go to http://www.sgi.com/tech/stl/ForwardContainer.html.
struct ForwardIterator
Go to http://www.sgi.com/tech/stl/ForwardIterator.html.
struct FrontInsertionSequence
Go to http://www.sgi.com/tech/stl/FrontInsertionSequence.html.
struct Generator
Go to http://www.sgi.com/tech/stl/Generator.html.
struct graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >
struct graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >
struct GraphConcept
Go to http://www.boost.org/doc/libs/1_52_0/libs/graph/doc/Graph.html.
struct hash< DGtal::BigInteger >
struct hash< DGtal::KhalimskyCell< dim, TInteger > >
Extend boost namespace to define a boost::hash function on DGtal::KhalimskyCell.
struct hash< DGtal::SignedKhalimskyCell< dim, TInteger > >
Extend boost namespace to define a boost::hash function on DGtal::SignedKhalimskyCell.
struct IncidenceGraphConcept
Go to http://www.boost.org/doc/libs/1_52_0/libs/graph/doc/IncidenceGraph.html.
struct InputIterator
Go to http://www.sgi.com/tech/stl/InputIterator.html.
struct Integer
Go to http://www.boost.org/libs/concept_check/reference.htm.
struct is_integral
Go to http://www.boost.org/doc/libs/1_52_0/libs/type_traits/doc/html/index.html.
struct is_unsigned
Go to http://www.boost.org/doc/libs/1_52_0/libs/type_traits/doc/html/index.html.
struct LessThanComparable
Go to http://www.sgi.com/tech/stl/LessThanComparable.html.
struct MultiPassInputIterator
Go to http://www.boost.org/doc/libs/1_52_0/libs/utility/MultiPassInputIterator.html.
struct MultipleAssociativeContainer
Go to http://www.sgi.com/tech/stl/MultipleAssociativeContainer.html.
struct Mutable_BidirectionalIterator
Go to http://www.boost.org/libs/concept_check/reference.htm.
struct Mutable_Container
Go to http://www.boost.org/libs/concept_check/reference.htm.
struct Mutable_ForwardContainer
Go to http://www.boost.org/libs/concept_check/reference.htm.
struct Mutable_ForwardIterator
Go to http://www.boost.org/libs/concept_check/reference.htm.
struct Mutable_RandomAccessContainer
Go to http://www.boost.org/libs/concept_check/reference.htm.
struct Mutable_RandomAccessIterator
Go to http://www.boost.org/libs/concept_check/reference.htm.
struct Mutable_ReversibleContainer
Go to http://www.boost.org/libs/concept_check/reference.htm.
struct Object_graph_traversal_category
struct OutputIterator
Go to http://www.sgi.com/tech/stl/OutputIterator.html.
struct PairAssociativeContainer
Go to http://www.sgi.com/tech/stl/PairAssociativeContainer.html.
struct RandomAccessContainer
Go to http://www.sgi.com/tech/stl/RandomAccessContainer.html.
struct RandomAccessIterator
Go to http://www.sgi.com/tech/stl/RandomAccessIterator.html.
struct ReversibleContainer
Go to http://www.sgi.com/tech/stl/ReversibleContainer.html.
struct Sequence
Go to http://www.sgi.com/tech/stl/Sequence.html.
struct SGIAssignable
Go to http://www.boost.org/libs/concept_check/reference.htm.
struct SignedInteger
Go to http://www.sgi.com/tech/stl/SignedInteger.html.
struct SimpleAssociativeContainer
Go to http://www.sgi.com/tech/stl/SimpleAssociativeContainer.html.
struct SortedAssociativeContainer
Go to http://www.sgi.com/tech/stl/SortedAssociativeContainer.html.
struct UnaryFunction
Go to http://www.sgi.com/tech/stl/UnaryFunction.html.
struct UnaryPredicate
Go to http://www.sgi.com/tech/stl/Predicate.html.
struct UniqueAssociativeContainer
Go to http://www.sgi.com/tech/stl/UniqueAssociativeContainer.html.
struct UnsignedInteger
Go to http://www.boost.org/libs/concept_check/reference.htm.
struct VertexListGraphConcept
Go to http://www.boost.org/doc/libs/1_52_0/libs/graph/doc/VertexListGraph.html.
Functions
template<class TDigitalSurfaceContainer >
graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::vertex_descriptor source (typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::edge_descriptor edge, const DGtal::DigitalSurface< TDigitalSurfaceContainer > &digSurf)
template<class TDigitalSurfaceContainer >
graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::vertex_descriptor target (typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::edge_descriptor edge, const DGtal::DigitalSurface< TDigitalSurfaceContainer > &digSurf)
template<class TDigitalSurfaceContainer >
std::pair< typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::vertex_iterator, typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::vertex_iterator > vertices (const DGtal::DigitalSurface< TDigitalSurfaceContainer > &digSurf)
template<class TDigitalSurfaceContainer >
graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::vertices_size_type num_vertices (const DGtal::DigitalSurface< TDigitalSurfaceContainer > &digSurf)
template<class TDigitalSurfaceContainer >
std::pair< typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::adjacency_iterator, typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::adjacency_iterator > adjacent_vertices (typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::vertex_descriptor u, const DGtal::DigitalSurface< TDigitalSurfaceContainer > &digSurf)
template<class TDigitalSurfaceContainer >
std::pair< typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::out_edge_iterator, typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::out_edge_iterator > out_edges (typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::vertex_descriptor u, const DGtal::DigitalSurface< TDigitalSurfaceContainer > &digSurf)
template<class TDigitalSurfaceContainer >
graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::degree_size_type out_degree (typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::vertex_descriptor u, const DGtal::DigitalSurface< TDigitalSurfaceContainer > &digSurf)
template<class TDigitalSurfaceContainer >
std::pair< typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::edge_iterator, typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::edge_iterator > edges (const DGtal::DigitalSurface< TDigitalSurfaceContainer > &digSurf)
template<class TDigitalSurfaceContainer >
graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::edges_size_type num_edges (const DGtal::DigitalSurface< TDigitalSurfaceContainer > &digSurf)
template<class TDigitalTopology , class TDigitalSet >
graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::vertex_descriptor source (typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::edge_descriptor edge, const DGtal::Object< TDigitalTopology, TDigitalSet > &obj)
template<class TDigitalTopology , class TDigitalSet >
graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::vertex_descriptor target (typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::edge_descriptor edge, const DGtal::Object< TDigitalTopology, TDigitalSet > &obj)
template<class TDigitalTopology , class TDigitalSet >
std::pair< typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::vertex_iterator, typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::vertex_iterator > vertices (const DGtal::Object< TDigitalTopology, TDigitalSet > &obj)
template<class TDigitalTopology , class TDigitalSet >
graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::vertices_size_type num_vertices (const DGtal::Object< TDigitalTopology, TDigitalSet > &obj)
template<class TDigitalTopology , class TDigitalSet >
std::pair< typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::adjacency_iterator, typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::adjacency_iterator > adjacent_vertices (typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::vertex_descriptor u, const DGtal::Object< TDigitalTopology, TDigitalSet > &obj)
template<class TDigitalTopology , class TDigitalSet >
std::pair< typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::out_edge_iterator, typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::out_edge_iterator > out_edges (typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::vertex_descriptor u, const DGtal::Object< TDigitalTopology, TDigitalSet > &obj)
template<class TDigitalTopology , class TDigitalSet >
graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::degree_size_type out_degree (typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::vertex_descriptor u, const DGtal::Object< TDigitalTopology, TDigitalSet > &obj)
template<class TDigitalTopology , class TDigitalSet >
std::pair< typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::edge_iterator, typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::edge_iterator > edges (const DGtal::Object< TDigitalTopology, TDigitalSet > &obj)
template<class TDigitalTopology , class TDigitalSet >
graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::edges_size_type num_edges (const DGtal::Object< TDigitalTopology, TDigitalSet > &obj)
Detailed Description
Dummy namespace used for generating the documentation. Gathers boost concept definitions and refers to the corresponding documentation.
More generally, you may also want to look at
the STL main page: http://www.sgi.com/tech/stl/index.html
the BOOST concept check main page http://www.boost.org/libs/concept_check/concept_check.htm
the BOOST iterator library main page http://www.boost.org/doc/libs/1_52_0/libs/iterator/doc/index.html
the BOOST graph library main page http://www.boost.org/doc/libs/1_52_0/libs/graph/doc/index.html
the BOOST graph concepts main page http://www.boost.org/doc/libs/1_52_0/libs/graph/doc/graph_concepts.html
the BOOST type traits main page http://www.boost.org/doc/libs/1_52_0/libs/type_traits/doc/html/index.html
Function Documentation
adjacent_vertices() [1/2]
template<class TDigitalSurfaceContainer > std::pair< typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::adjacency_iterator, typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::adjacency_iterator > boost::adjacent_vertices (typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::vertex_descriptor u, const DGtal::DigitalSurface< TDigitalSurfaceContainer > & digSurf) inline
Parameters
u a vertex belonging to digSurf.
digSurf a valid digital surface.
Returns
a pair< adjacency_iterator, adjacency_iterator > that represents a range to visit the adjacent vertices of vertex u.
Definition at line 434 of file DigitalSurfaceBoostGraphInterface.h.
   {
     typedef typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >
       ::adjacency_iterator Iterator;
     typedef typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >
       ::AdjacentVertexContainer Container;
     DGtal::CountedPtr<Container> ptrAdjVertices( new Container );
     std::back_insert_iterator< Container > outIt = std::back_inserter( *ptrAdjVertices );
     digSurf.writeNeighbors( outIt, u );
     return std::make_pair( Iterator( ptrAdjVertices->begin(), ptrAdjVertices ),
                            Iterator( ptrAdjVertices->end(), ptrAdjVertices ) );
   }
References DGtal::DigitalSurface< TDigitalSurfaceContainer >::writeNeighbors().
Referenced by TEST_CASE_METHOD().
adjacent_vertices() [2/2]
template<class TDigitalTopology , class TDigitalSet > std::pair< typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::adjacency_iterator, typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::adjacency_iterator > boost::adjacent_vertices (typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::vertex_descriptor u, const DGtal::Object< TDigitalTopology, TDigitalSet > & obj) inline
Parameters
u a vertex belonging to obj.
obj a valid object.
Returns
a pair< adjacency_iterator, adjacency_iterator > that represents a range to visit the adjacent vertices of vertex u.
Definition at line 524 of file ObjectBoostGraphInterface.h.
   {
     typedef typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >
       ::adjacency_iterator Iterator;
     typedef typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >
       ::AdjacentVertexContainer Container;
     DGtal::CountedPtr<Container> ptrAdjVertices( new Container );
     std::back_insert_iterator< Container > outIt = std::back_inserter( *ptrAdjVertices );
     obj.writeNeighbors( outIt, u );
     return std::make_pair( Iterator( ptrAdjVertices->begin(), ptrAdjVertices ),
                            Iterator( ptrAdjVertices->end(), ptrAdjVertices ) );
   }
edges() [1/2]
template<class TDigitalSurfaceContainer > std::pair< typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::edge_iterator, typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::edge_iterator > boost::edges (const DGtal::DigitalSurface< TDigitalSurfaceContainer > & digSurf) inline
Parameters
digSurf a valid digital surface.
Returns
a pair< out_edge_iterator, out_edge_iterator > that represents a range to visit the out edges of vertex u. Each out edge is a tuple (u,t) of vertices, where t != u.
Definition at line 503 of file DigitalSurfaceBoostGraphInterface.h.
   {
     typedef typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::edge_iterator
       edge_iterator;
     return std::make_pair( edge_iterator( digSurf, digSurf.begin(), digSurf.end() ),
                            edge_iterator( digSurf, digSurf.end(), digSurf.end() ) );
   }
References DGtal::DigitalSurface< TDigitalSurfaceContainer >::begin(), and DGtal::DigitalSurface< TDigitalSurfaceContainer >::end().
Referenced by num_edges(), TEST_CASE_METHOD(), and testDigitalSurfaceBoostGraphInterface().
edges() [2/2]
template<class TDigitalTopology , class TDigitalSet > std::pair< typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::edge_iterator, typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::edge_iterator > boost::edges (const DGtal::Object< TDigitalTopology, TDigitalSet > & obj) inline
Parameters
obj a valid Object.
Returns
a pair< edge_iterator, edge_iterator > that represents a range to visit all the edges of obj . Each edge is a tuple (u,t) of vertices, where t != u.
Definition at line 593 of file ObjectBoostGraphInterface.h.
   {
     typedef typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::edge_iterator
       edge_iterator;
     return std::make_pair( edge_iterator( obj, obj.begin(), obj.end() ),
                            edge_iterator( obj, obj.end(), obj.end() ) );
   }
num_edges() [1/2]
template<class TDigitalSurfaceContainer > graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::edges_size_type boost::num_edges (const DGtal::DigitalSurface< TDigitalSurfaceContainer > & digSurf) inline
Parameters
digSurf a valid digital surface.
Returns
the number of vertices of digSurf.
Definition at line 518 of file DigitalSurfaceBoostGraphInterface.h.
   {
     typedef typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::edge_iterator
       edge_iterator;
     typedef typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::edges_size_type
       edges_size_type;
     edges_size_type nbEdges = 0;
     for ( std::pair< edge_iterator, edge_iterator > ve = boost::edges( digSurf );
           ve.first != ve.second; ++ve.first )
       ++nbEdges;
     return nbEdges;
   }
References edges().
Referenced by TEST_CASE_METHOD().
num_edges() [2/2]
template<class TDigitalTopology , class TDigitalSet > graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::edges_size_type boost::num_edges (const DGtal::Object< TDigitalTopology, TDigitalSet > & obj) inline
Parameters
obj a valid object.
Returns
the number of edges of obj.
Definition at line 608 of file ObjectBoostGraphInterface.h.
   {
     typedef typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::edge_iterator
       edge_iterator;
     typedef typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::edges_size_type
       edges_size_type;
     edges_size_type nbEdges = 0;
     for ( std::pair< edge_iterator, edge_iterator > ve = boost::edges( obj );
           ve.first != ve.second; ++ve.first )
       ++nbEdges;
     return nbEdges;
   }
References edges().
num_vertices() [1/2]
template<class TDigitalSurfaceContainer > graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::vertices_size_type boost::num_vertices (const DGtal::DigitalSurface< TDigitalSurfaceContainer > & digSurf) inline
Parameters
digSurf a valid digital surface.
Returns
the number of vertices of digSurf.
Definition at line 416 of file DigitalSurfaceBoostGraphInterface.h.
   {
     return digSurf.size();
   }
References DGtal::DigitalSurface< TDigitalSurfaceContainer >::size().
Referenced by TEST_CASE_METHOD(), and testDigitalSurfaceBoostGraphInterface().
num_vertices() [2/2]
template<class TDigitalTopology , class TDigitalSet > graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::vertices_size_type boost::num_vertices (const DGtal::Object< TDigitalTopology, TDigitalSet > & obj) inline
Parameters
obj a valid object.
Returns
the number of vertices of obj.
Definition at line 506 of file ObjectBoostGraphInterface.h.
   {
     return obj.size();
   }
out_degree() [1/2]
template<class TDigitalSurfaceContainer > graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::degree_size_type boost::out_degree (typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::vertex_descriptor u, const DGtal::DigitalSurface< TDigitalSurfaceContainer > & digSurf) inline
Parameters
u a vertex belonging to digSurf.
digSurf a valid digital surface.
Returns
the number of out edges at vertex u. Each out edge is a tuple (u,t) of vertices, where t != u.
Definition at line 485 of file DigitalSurfaceBoostGraphInterface.h.
   {
     return digSurf.degree( u );
   }
References DGtal::DigitalSurface< TDigitalSurfaceContainer >::degree().
Referenced by TEST_CASE_METHOD().
out_degree() [2/2]
template<class TDigitalTopology , class TDigitalSet > graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::degree_size_type boost::out_degree (typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::vertex_descriptor u, const DGtal::Object< TDigitalTopology, TDigitalSet > & obj) inline
Parameters
u a vertex belonging to obj
obj a valid Object.
Returns
the number of out edges at vertex u.
Definition at line 575 of file ObjectBoostGraphInterface.h.
   {
     return obj.degree( u );
   }
out_edges() [1/2]
template<class TDigitalSurfaceContainer > std::pair< typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::out_edge_iterator, typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::out_edge_iterator > boost::out_edges (typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::vertex_descriptor u, const DGtal::DigitalSurface< TDigitalSurfaceContainer > & digSurf) inline
Parameters
u a vertex belonging to digSurf.
digSurf a valid digital surface.
Returns
a pair< out_edge_iterator, out_edge_iterator > that represents a range to visit the out edges of vertex u. Each out edge is a tuple (u,t) of vertices, where t != u.
Definition at line 463 of file DigitalSurfaceBoostGraphInterface.h.
   {
     typedef typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >
       ::out_edge_iterator Iterator;
     typedef typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >
       ::OutEdgeContainer Container;
     DGtal::CountedPtr<Container> ptrOutEdges( new Container( digSurf.outArcs( u ) ) );
     return std::make_pair( Iterator( ptrOutEdges->begin(), ptrOutEdges ),
                            Iterator( ptrOutEdges->end(), ptrOutEdges ) );
   }
References DGtal::DigitalSurface< TDigitalSurfaceContainer >::outArcs().
Referenced by TEST_CASE_METHOD(), and testDigitalSurfaceBoostGraphInterface().
out_edges() [2/2]
template<class TDigitalTopology , class TDigitalSet > std::pair< typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::out_edge_iterator, typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::out_edge_iterator > boost::out_edges (typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::vertex_descriptor u, const DGtal::Object< TDigitalTopology, TDigitalSet > & obj) inline
Parameters
u a vertex belonging to obj.
obj a valid object.
Returns
a pair< out_edge_iterator, out_edge_iterator > that represents a range to visit the out edges of vertex u. Each out edge is a tuple (u,t) of vertices, where t != u.
Definition at line 553 of file ObjectBoostGraphInterface.h.
   {
     typedef typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >
       ::out_edge_iterator Iterator;
     typedef typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >
       ::OutEdgeContainer Container;
     DGtal::CountedPtr<Container> ptrEdges( new Container( obj.outEdges( u ) ) );
     return std::make_pair( Iterator( ptrEdges->begin(), ptrEdges ),
                            Iterator( ptrEdges->end(), ptrEdges ) );
   }
source() [1/2]
template<class TDigitalSurfaceContainer > graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::vertex_descriptor boost::source (typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::edge_descriptor edge, const DGtal::DigitalSurface< TDigitalSurfaceContainer > & digSurf) inline
Defines the property map traits for any kind of digital surface.
Template Parameters
TDigitalSurfaceContainer the container chosen for the digital surface.
Parameters
edge an arc (s,t) on digSurf.
digSurf a valid digital surface.
Returns
the vertex s.
Definition at line 378 of file DigitalSurfaceBoostGraphInterface.h.
   {
     return digSurf.tail( edge );
   }
References DGtal::DigitalSurface< TDigitalSurfaceContainer >::tail().
Referenced by TEST_CASE_METHOD(), and testDigitalSurfaceBoostGraphInterface().
source() [2/2]
template<class TDigitalTopology , class TDigitalSet > graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::vertex_descriptor boost::source (typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::edge_descriptor edge, const DGtal::Object< TDigitalTopology, TDigitalSet > & obj) inline
Parameters
edge an edge (s,t) on obj.
obj a valid object.
Returns
the vertex s.
Definition at line 468 of file ObjectBoostGraphInterface.h.
   {
     return obj.tail( edge );
   }
target() [1/2]
template<class TDigitalSurfaceContainer > graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::vertex_descriptor boost::target (typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::edge_descriptor edge, const DGtal::DigitalSurface< TDigitalSurfaceContainer > & digSurf) inline
Parameters
edge an arc (s,t) on digSurf.
digSurf a valid digital surface.
Returns
the vertex t.
Definition at line 391 of file DigitalSurfaceBoostGraphInterface.h.
   {
     return digSurf.head( edge );
   }
References DGtal::DigitalSurface< TDigitalSurfaceContainer >::head().
Referenced by TEST_CASE_METHOD(), and testDigitalSurfaceBoostGraphInterface().
target() [2/2]
template<class TDigitalTopology , class TDigitalSet > graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::vertex_descriptor boost::target (typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::edge_descriptor edge, const DGtal::Object< TDigitalTopology, TDigitalSet > & obj) inline
Parameters
edge an edge (s,t) on obj.
obj a valid object.
Returns
the vertex t.
Definition at line 481 of file ObjectBoostGraphInterface.h.
   {
     return obj.head( edge );
   }
vertices() [1/2]
template<class TDigitalSurfaceContainer > std::pair< typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::vertex_iterator, typename graph_traits< DGtal::DigitalSurface< TDigitalSurfaceContainer > >::vertex_iterator > boost::vertices (const DGtal::DigitalSurface< TDigitalSurfaceContainer > & digSurf)
Parameters
digSurf a valid digital surface.
Returns
a pair< vertex_iterator, vertex_iterator > that represents a range to visit all the vertices of digSurf.
Referenced by TEST_CASE_METHOD(), and testDigitalSurfaceBoostGraphInterface().
vertices() [2/2]
template<class TDigitalTopology , class TDigitalSet > std::pair< typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::vertex_iterator, typename graph_traits< DGtal::Object< TDigitalTopology, TDigitalSet > >::vertex_iterator > boost::vertices (const DGtal::Object< TDigitalTopology, TDigitalSet > & obj)
Parameters
obj a valid object.
Returns
a pair< vertex_iterator, vertex_iterator > that represents a range to visit all the vertices of obj.