DGtal: DGtal::concepts::ConceptUtils Namespace Reference
DGtal::concepts::ConceptUtils Namespace Reference
Data Structures
struct CheckFalse
struct CheckTag
struct CheckTrue
struct CheckTrue< TagTrue >
struct CheckTrueOrFalse
struct CheckUnknown
struct CheckUnknown< TagUnknown >
struct SameType
struct SameType< T, T >
Functions
template<typename T >
void sameType (const T &, const T &)
void checkTrue (const TagTrue &tag)
void checkFalse (const TagFalse &tag)
void checkUnknown (const TagUnknown &tag)
void checkTag (const TagUnknown &tag)
void checkTag (const TagTrue &tag)
void checkTag (const TagFalse &tag)
void checkTrueOrFalse (const TagFalse &tag)
void checkTrueOrFalse (const TagTrue &tag)
Function Documentation
checkFalse()
void DGtal::concepts::ConceptUtils::checkFalse (const TagFalse & tag)
Type deduction will fail unless the argument type is exactly TagFalse.
Parameters
tag the type to check.
checkTag() [1/3]
void DGtal::concepts::ConceptUtils::checkTag (const TagFalse & tag)
Type deduction will fail unless the argument type is a tag (TagTrue, TagFalse or TagUnknown).
Parameters
tag the type to check.
checkTag() [2/3]
void DGtal::concepts::ConceptUtils::checkTag (const TagTrue & tag)
Type deduction will fail unless the argument type is a tag (TagTrue, TagFalse or TagUnknown).
Parameters
tag the type to check.
checkTag() [3/3]
void DGtal::concepts::ConceptUtils::checkTag (const TagUnknown & tag)
Type deduction will fail unless the argument type is a tag (TagTrue, TagFalse or TagUnknown).
Parameters
tag the type to check.
checkTrue()
void DGtal::concepts::ConceptUtils::checkTrue (const TagTrue & tag)
Type deduction will fail unless the argument type is exactly TagTrue.
Parameters
tag the type to check.
Referenced by DGtal::concepts::CBoundedNumber< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CIntegralNumber< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CSignedNumber< T >::BOOST_CONCEPT_USAGE(), and DGtal::concepts::CUnsignedNumber< T >::BOOST_CONCEPT_USAGE().
checkTrueOrFalse() [1/2]
void DGtal::concepts::ConceptUtils::checkTrueOrFalse (const TagFalse & tag)
Type deduction will fail unless the argument type is the tag TagTrue or TagFalse.
Parameters
tag the type to check.
checkTrueOrFalse() [2/2]
void DGtal::concepts::ConceptUtils::checkTrueOrFalse (const TagTrue & tag)
Type deduction will fail unless the argument type is the tag TagTrue or TagFalse.
Parameters
tag the type to check.
checkUnknown()
void DGtal::concepts::ConceptUtils::checkUnknown (const TagUnknown & tag)
Type deduction will fail unless the argument type is exactly TagUnknown.
Parameters
tag the type to check.
sameType()
template<typename T > void DGtal::concepts::ConceptUtils::sameType (const T & , const T &)
Type deduction will fail unless the arguments have the same type.
Definition at line 117 of file ConceptUtils.h.
 {}
Referenced by DGtal::C2x2DetComputer< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CAdditivePrimitiveComputer< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CAdjacency< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CBidirectionalRange< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CBidirectionalRangeFromPoint< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CBidirectionalRangeWithWritableIterator< T, Value >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CBidirectionalRangeWithWritableIteratorFromPoint< T, Value >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CBidirectionalSegmentComputer< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CCellularGridSpaceND< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CColorMap< CMap >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CCommutativeRing< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CConstImage< I >::BOOST_CONCEPT_USAGE(), DGtal::deprecated::concepts::CConvolutionWeights< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CCurveLocalGeometricEstimator< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CDigitalBoundedShape< TShape >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CDigitalOrientedShape< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CDomain< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CDomainAdjacency< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CDrawableWithBoard2D< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CDrawableWithBoard3DTo2D< T, S, KS >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CDrawableWithDisplay3D< T, S, KS >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CDrawableWithViewer3D< T, S, KS >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CDynamicBidirectionalSegmentComputer< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CDynamicSegmentComputer< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CEuclideanBoundedShape< TShape >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CEuclideanOrientedShape< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CEuclideanRing< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CGlobalGeometricEstimator< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CImage< I >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CImageCacheReadPolicy< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CImageFactory< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CIncrementalPrimitiveComputer< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CIncrementalSegmentComputer< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CLMSTDSSFilter< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CLMSTTangentFromDSS< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CLocalEstimatorFromSurfelFunctor< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CNormalVectorEstimator< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::COrientationFunctor< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CPositiveIrreducibleFraction< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CPreCellularGridSpaceND< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CSegment< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CSegmentFactory< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CSinglePassRangeFromPoint< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CSinglePassRangeWithWritableIterator< T, Value >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CSinglePassRangeWithWritableIteratorFromPoint< T, Value >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CSpace< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CStack< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CStaticMatrix< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CStaticVector< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CSurfelLocalEstimator< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CTrivialConstImage< I >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CUnaryFunctor< T, T::Point, bool >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CUnaryFunctor< X, A &, R & >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CVertexMap< T >::BOOST_CONCEPT_USAGE(), DGtal::concepts::CSurfelLocalEstimator< T >::check_const_constraints(), DGtal::concepts::CPositiveIrreducibleFraction< T >::checkConstConstraints(), DGtal::concepts::CConstBidirectionalRange< T >::checkConstConstraints(), DGtal::concepts::CConstBidirectionalRangeFromPoint< T >::checkConstConstraints(), DGtal::concepts::CConstSinglePassRange< T >::checkConstConstraints(), DGtal::concepts::CConstSinglePassRangeFromPoint< T, Value >::checkConstConstraints(), DGtal::concepts::CStack< T >::checkConstConstraints(), DGtal::concepts::CLMSTDSSFilter< T >::checkConstConstraints(), DGtal::concepts::CLMSTTangentFromDSS< T >::checkConstConstraints(), DGtal::concepts::C3DParametricCurve< T >::checkConstConstraints(), DGtal::concepts::C3DParametricCurveDecorator< T >::checkConstConstraints(), DGtal::concepts::CAdditivePrimitiveComputer< T >::checkConstConstraints(), DGtal::concepts::CIncrementalPrimitiveComputer< T >::checkConstConstraints(), DGtal::concepts::CPrimitiveComputer< T >::checkConstConstraints(), DGtal::concepts::CPolarPointComparator2D< T >::checkConstConstraints(), DGtal::concepts::CMetricSpace< T >::checkConstConstraints(), DGtal::concepts::CPowerMetric< T >::checkConstConstraints(), DGtal::concepts::CPowerSeparableMetric< T >::checkConstConstraints(), DGtal::concepts::CSeparableMetric< T >::checkConstConstraints(), DGtal::concepts::CGraphVisitor< T >::checkConstConstraints(), DGtal::concepts::CUndirectedSimpleGraph< T >::checkConstConstraints(), DGtal::concepts::CUndirectedSimpleLocalGraph< Adj >::checkConstConstraints(), DGtal::concepts::CPointEmbedder< T >::checkConstConstraints(), DGtal::concepts::CWithGradientMap< T >::checkConstConstraints(), DGtal::concepts::CDigitalSet< T >::checkConstConstraints(), DGtal::concepts::CBinner< T >::checkConstConstraints(), DGtal::concepts::CMatrix< T >::checkConstConstraints(), DGtal::concepts::CVector< T >::checkConstConstraints(), DGtal::concepts::CImplicitFunctionDiff1< T >::checkConstConstraints(), DGtal::concepts::CCellEmbedder< T >::checkConstConstraints(), DGtal::concepts::CCellularGridSpaceND< T >::checkConstConstraints(), DGtal::concepts::CDigitalSurfaceContainer< T >::checkConstConstraints(), DGtal::concepts::CDigitalSurfaceEmbedder< T >::checkConstConstraints(), DGtal::concepts::CDigitalSurfaceTracker< T >::checkConstConstraints(), DGtal::concepts::CPreCellularGridSpaceND< T >::checkConstConstraints(), DGtal::concepts::CSCellEmbedder< T >::checkConstConstraints(), and DGtal::concepts::CDigitalSet< T >::checkNonConstConstraints().