DGtal: DGtal::concepts::CVector< T > Struct Template Reference
DGtal::concepts::CVector< T > Struct Template Reference
DGtal Concepts
Aim: Represent any static or dynamic sized column vector having sparse or dense representation.
#include <DGtal/math/linalg/CVector.h>
Public Types
typedef T::Scalar Scalar
typedef T::Index Index
Public Types inherited from DGtal::concepts::CVectorSpace< T >
typedef T::Scalar Scalar
Public Member Functions
BOOST_CONCEPT_USAGE (CVector)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::concepts::CVectorSpace< T >
BOOST_CONCEPT_ASSERT ((concepts::CEuclideanRing< Scalar >))
BOOST_CONCEPT_USAGE (CVectorSpace)
Private Attributes
T z
Index i
Detailed Description
template<typename T>
struct DGtal::concepts::CVector< T >
Aim: Represent any static or dynamic sized column vector having sparse or dense representation.
Description of concept 'CVector'
Refinement of
CVectorSpace
Associated types
Notation
Vector : A type that is a model of CVector
x : const object of type Vector
z : object of type Vector
i : object of type Vector::Index
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
Number of rows x.rows() Index Returns the size of the vector
Invariants
Models
EigenLinearAlgebraBackend::DenseVector, SimpleMatrix::Vector
Notes
Template Parameters
T the type that should be a model of CVector.
Definition at line 90 of file CVector.h.
Member Typedef Documentation
Index
template<typename T > typedef T::Index DGtal::concepts::CVector< T >::Index
Definition at line 95 of file CVector.h.
Scalar
template<typename T > typedef T::Scalar DGtal::concepts::CVector< T >::Scalar
Definition at line 94 of file CVector.h.
Member Function Documentation
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CVector< T >::BOOST_CONCEPT_USAGE (CVector< T >) inline
Definition at line 97 of file CVector.h.
     {
         checkConstConstraints();
     }
References DGtal::concepts::CVector< T >::checkConstConstraints().
checkConstConstraints()
template<typename T > void DGtal::concepts::CVector< T >::checkConstConstraints () const inline
Definition at line 102 of file CVector.h.
     {
         ConceptUtils::sameType(i, z.rows());
     }
References DGtal::concepts::CVector< T >::i, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::concepts::CVector< T >::BOOST_CONCEPT_USAGE().
Field Documentation
i
template<typename T > Index DGtal::concepts::CVector< T >::i private
Definition at line 110 of file CVector.h.
Referenced by DGtal::concepts::CVector< T >::checkConstConstraints().
z
template<typename T > T DGtal::concepts::CVector< T >::z private
Definition at line 109 of file CVector.h.
The documentation for this struct was generated from the following file:
CVector.h