DGtal: DGtal::concepts::CConstSinglePassRange< T > Struct Template Reference
DGtal::concepts::CConstSinglePassRange< T > Struct Template Reference
DGtal Concepts
Aim: Defines the concept describing a const single pass range.
#include <DGtal/base/CConstSinglePassRange.h>
Public Types
typedef T::ConstIterator ConstIterator
Public Member Functions
BOOST_CONCEPT_ASSERT ((boost_concepts::SinglePassIteratorConcept< ConstIterator >))
BOOST_CONCEPT_USAGE (CConstSinglePassRange)
void checkConstConstraints () const
Private Attributes
T i
ConstIterator it
Detailed Description
template<typename T>
struct DGtal::concepts::CConstSinglePassRange< T >
Aim: Defines the concept describing a const single pass range.
Description of concept 'CConstSinglePassRange'
Template Parameters
T the type that should be a model of CConstSinglePassRange.
Refinement of
Associated types
ConstIterator: the const iterator type, a model of const iterator concept (see boost_concepts::SinglePassIteratorConcept).
Notation
T : A type that is a model of CConstSinglePassRange
x : object of type T
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
begin of range x.begin() ConstIterator returns a forward iterator on the beginning of the range
end of range x.end() ConstIterator returns a forward iterator after the end of the range
Invariants
Valid range. For any Range x, [x.begin(), x.end()) is a valid range, that is, x.end() is reachable from x.begin() in a finite number of increments.
Completeness. An algorithm that iterates through the range [x.begin(), x.end()) will pass through every element of x.
Models
Definition at line 92 of file CConstSinglePassRange.h.
Member Typedef Documentation
ConstIterator
template<typename T > typedef T::ConstIterator DGtal::concepts::CConstSinglePassRange< T >::ConstIterator
Definition at line 96 of file CConstSinglePassRange.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename T > DGtal::concepts::CConstSinglePassRange< T >::BOOST_CONCEPT_ASSERT ((boost_concepts::SinglePassIteratorConcept< ConstIterator >))
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CConstSinglePassRange< T >::BOOST_CONCEPT_USAGE (CConstSinglePassRange< T >) inline
Definition at line 100 of file CConstSinglePassRange.h.
       {
         checkConstConstraints();
       }
References DGtal::concepts::CConstSinglePassRange< T >::checkConstConstraints().
checkConstConstraints()
template<typename T > void DGtal::concepts::CConstSinglePassRange< T >::checkConstConstraints () const inline
Definition at line 104 of file CConstSinglePassRange.h.
       {
         concepts::ConceptUtils::sameType( it, i.begin() );
         concepts::ConceptUtils::sameType( it, i.end() );
       }
References DGtal::concepts::CConstSinglePassRange< T >::i, DGtal::concepts::CConstSinglePassRange< T >::it, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::concepts::CConstSinglePassRange< T >::BOOST_CONCEPT_USAGE().
Field Documentation
i
template<typename T > T DGtal::concepts::CConstSinglePassRange< T >::i private
Definition at line 111 of file CConstSinglePassRange.h.
Referenced by DGtal::concepts::CConstSinglePassRange< T >::checkConstConstraints().
it
template<typename T > ConstIterator DGtal::concepts::CConstSinglePassRange< T >::it private
Definition at line 112 of file CConstSinglePassRange.h.
Referenced by DGtal::concepts::CSinglePassRange< T >::BOOST_CONCEPT_USAGE(), and DGtal::concepts::CConstSinglePassRange< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CConstSinglePassRange.h