DGtal: DGtal::Shortcuts< TKSpace >::SCellWriter Struct Reference
DGtal::Shortcuts< TKSpace >::SCellWriter Struct Reference
#include <DGtal/helpers/Shortcuts.h>
Public Member Functions
void operator() (std::ostream &output, const KSpace &K, const SCell &scell)
Detailed Description
template<typename TKSpace>
struct DGtal::Shortcuts< TKSpace >::SCellWriter
Definition at line 2982 of file Shortcuts.h.
Member Function Documentation
operator()()
template<typename TKSpace > void DGtal::Shortcuts< TKSpace >::SCellWriter::operator() (std::ostream & output, const KSpace & K, const SCell & scell) inline
Definition at line 2983 of file Shortcuts.h.
         {
           CellWriter::operator()( output, K, K.unsigns( scell ) );
           output << " " << K.sSign( scell );
         }
References K, DGtal::Shortcuts< TKSpace >::CellWriter::operator()(), DGtal::KhalimskySpaceND< dim, TInteger >::sSign(), and DGtal::KhalimskySpaceND< dim, TInteger >::unsigns().
The documentation for this struct was generated from the following file:
Shortcuts.h