DGtal: DGtal::concepts::CSeparableMetric< T > Struct Template Reference
DGtal::concepts::CSeparableMetric< T > Struct Template Reference
DGtal Concepts
Aim: defines the concept of separable metrics.
#include <DGtal/geometry/volumes/distance/CSeparableMetric.h>
Public Types
typedef T::Point Point
Public Types inherited from DGtal::concepts::CMetricSpace< T >
typedef T::Point Point
typedef T::Space Space
typedef T::Value Value
typedef T::RawValue RawValue
Public Member Functions
BOOST_CONCEPT_USAGE (CSeparableMetric)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::concepts::CMetricSpace< T >
BOOST_CONCEPT_ASSERT ((CSpace< Space >))
BOOST_CONCEPT_ASSERT ((CQuantity< Value >))
BOOST_CONCEPT_ASSERT ((CQuantity< RawValue >))
BOOST_CONCEPT_USAGE (CMetricSpace)
void checkConstConstraints () const
Private Attributes
T myX
Point u
Point v
Point w
Point start
Point end
bool myBool
DGtal::Dimension dim
Detailed Description
template<typename T>
struct DGtal::concepts::CSeparableMetric< T >
Aim: defines the concept of separable metrics.
Description of concept 'CSeparableMetric'
Separable metrics are metrics satsifying the monotonicity property. More formally, in dimension 2, consider two points \(p(x,y)\), \(q(x',y')\) with \(x<x\). Let \(r(x'',0)\) be a point on the x-axis such that \(d(p,r) = d(q,r)\) and \(s(u,0)\) be another point on the x-axis. A metric \(d\) is monotonic if
\[ u < x'' \implies d(p,s) \leq d(q,s) \]
and
\[ u > x'' \implies d(p,s) \geq d(q,s) \]
Refinement of
concepts::CMetricSpace.
Associated types
Notation
X : A type that is a model of CSeparableMetric
x, y : object of type X
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
hiddenBy predicate hiddenBy(u,v,w,startingPoint,endPoint,dim) u,v,w,startingPoint,endPoint of type Point, dim of type DGtal::Dimension startingPoint and endPoint only differ by their dim-th coordinate returns true if the intersection between the segment [startingPoint,endPoint] and the Voronoi cell associated with v is empty (hidden on the segment by u and w Voronoi cells). -
Invariants
Models
ExactPredicateLpSeparableMetric, InexactPredicateLpSeparableMetric
Notes
Template Parameters
T the type that should be a model of concepts::CSeparableMetric.
Definition at line 101 of file CSeparableMetric.h.
Member Typedef Documentation
Point
template<typename T > typedef T::Point DGtal::concepts::CSeparableMetric< T >::Point
Definition at line 105 of file CSeparableMetric.h.
Member Function Documentation
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CSeparableMetric< T >::BOOST_CONCEPT_USAGE (CSeparableMetric< T >) inline
Definition at line 106 of file CSeparableMetric.h.
     {
       checkConstConstraints();
     }
References DGtal::concepts::CSeparableMetric< T >::checkConstConstraints().
checkConstConstraints()
template<typename T > void DGtal::concepts::CSeparableMetric< T >::checkConstConstraints () const inline
Definition at line 110 of file CSeparableMetric.h.
     {
         // const method dummyConst should take parameter myA of type A and return
         // something of type B
       ConceptUtils::sameType( myBool, myX.hiddenBy(u,v,w,start,end,dim) );
     }
References DGtal::concepts::CSeparableMetric< T >::dim, DGtal::concepts::CSeparableMetric< T >::myBool, DGtal::concepts::CSeparableMetric< T >::myX, DGtal::concepts::ConceptUtils::sameType(), and DGtal::concepts::CSeparableMetric< T >::u.
Referenced by DGtal::concepts::CSeparableMetric< T >::BOOST_CONCEPT_USAGE().
Field Documentation
dim
template<typename T > DGtal::Dimension DGtal::concepts::CSeparableMetric< T >::dim private
Definition at line 121 of file CSeparableMetric.h.
Referenced by DGtal::concepts::CSeparableMetric< T >::checkConstConstraints().
end
template<typename T > Point DGtal::concepts::CSeparableMetric< T >::end private
Definition at line 119 of file CSeparableMetric.h.
myBool
template<typename T > bool DGtal::concepts::CSeparableMetric< T >::myBool private
Definition at line 120 of file CSeparableMetric.h.
Referenced by DGtal::concepts::CSeparableMetric< T >::checkConstConstraints().
myX
template<typename T > T DGtal::concepts::CSeparableMetric< T >::myX private
Definition at line 118 of file CSeparableMetric.h.
Referenced by DGtal::concepts::CSeparableMetric< T >::checkConstConstraints().
start
template<typename T > Point DGtal::concepts::CSeparableMetric< T >::start private
Definition at line 119 of file CSeparableMetric.h.
u
template<typename T > Point DGtal::concepts::CSeparableMetric< T >::u private
Definition at line 119 of file CSeparableMetric.h.
Referenced by DGtal::concepts::CSeparableMetric< T >::checkConstConstraints().
v
template<typename T > Point DGtal::concepts::CSeparableMetric< T >::v private
Definition at line 119 of file CSeparableMetric.h.
w
template<typename T > Point DGtal::concepts::CSeparableMetric< T >::w private
Definition at line 119 of file CSeparableMetric.h.
The documentation for this struct was generated from the following file:
CSeparableMetric.h