DGtal: DGtal::detail::BoundedRationalPolytopeSpecializer< 3, TInteger > Struct Template Reference
DGtal::detail::BoundedRationalPolytopeSpecializer< 3, TInteger > Struct Template Reference
Aim: 3D specialization for BoundedRationalPolytope to add dimension specific static methods.
#include <DGtal/geometry/volumes/BoundedRationalPolytope.h>
Public Types
typedef TInteger Integer
typedef SpaceND< 3, Integer > Space
typedef Space::Point Point
typedef Space::Vector Vector
typedef BoundedRationalPolytope< Space > Polytope
Static Public Member Functions
static void addEdgeConstraint (Polytope &P, unsigned int i, unsigned int j, const std::vector< Point > &pts)
static Vector crossProduct (const Vector &v1, const Vector &v2)
Static Public Attributes
static const Dimension dimension = Space::dimension
Detailed Description
template<typename TInteger>
struct DGtal::detail::BoundedRationalPolytopeSpecializer< 3, TInteger >
Aim: 3D specialization for BoundedRationalPolytope to add dimension specific static methods.
Description of template class 'BoundedRationalPolytopeSpecializer'
Template Parameters
TInteger any model of integer.
Definition at line 734 of file BoundedRationalPolytope.h.
Member Typedef Documentation
Integer
template<typename TInteger > typedef TInteger DGtal::detail::BoundedRationalPolytopeSpecializer< 3, TInteger >::Integer
Definition at line 735 of file BoundedRationalPolytope.h.
Point
template<typename TInteger > typedef Space::Point DGtal::detail::BoundedRationalPolytopeSpecializer< 3, TInteger >::Point
Definition at line 737 of file BoundedRationalPolytope.h.
Polytope
template<typename TInteger > typedef BoundedRationalPolytope< Space > DGtal::detail::BoundedRationalPolytopeSpecializer< 3, TInteger >::Polytope
Definition at line 739 of file BoundedRationalPolytope.h.
Space
template<typename TInteger > typedef SpaceND< 3, Integer> DGtal::detail::BoundedRationalPolytopeSpecializer< 3, TInteger >::Space
Definition at line 736 of file BoundedRationalPolytope.h.
Vector
template<typename TInteger > typedef Space::Vector DGtal::detail::BoundedRationalPolytopeSpecializer< 3, TInteger >::Vector
Definition at line 738 of file BoundedRationalPolytope.h.
Member Function Documentation
addEdgeConstraint()
template<typename TInteger > static void DGtal::detail::BoundedRationalPolytopeSpecializer< 3, TInteger >::addEdgeConstraint (Polytope & P, unsigned int i, unsigned int j, const std::vector< Point > & pts) inline static
This method add extremal constraints for simplex edges. Each constraint is a half-space bounded by the edge and one axis. Such constraints are useful when computing the Minkowski sum.
Parameters
[in,out] P any polytope.
[in] i any index in the vector of points pts.
[in] j any index in the vector of points pts.
[in] pts a vector of points defining a simplex.
Definition at line 752 of file BoundedRationalPolytope.h.
       {
         Vector ab = pts[ i ] - pts[ j ];
         for ( int s = 0; s < 2; s++ )
           for ( Dimension k = 0; k < dimension; ++k )
             {
               Vector  n = ab.crossProduct( Point::base( k, (s == 0) ? 1 : -1 ) );
               Integer b = n.dot( pts[ i ] );
               int nb_in = 0;
               for ( auto p : pts ) {
                 Integer v = n.dot( p );
                 if ( v < b )  nb_in++;
               }
               if ( nb_in == dimension - 1 ) {
                 P.cut( n, b, true, true );
               }
             }
       }
References DGtal::PointVector< dim, Integer >::base(), DGtal::PointVector< dim, TEuclideanRing, TContainer >::crossProduct(), DGtal::BoundedRationalPolytope< TSpace >::cut(), and DGtal::detail::BoundedRationalPolytopeSpecializer< N, TInteger >::dimension.
crossProduct()
template<typename TInteger > static Vector DGtal::detail::BoundedRationalPolytopeSpecializer< 3, TInteger >::crossProduct (const Vector & v1, const Vector & v2) inline static
Generic method for cross product, only implemented in 3D.
Parameters
v1 any vector
v2 any vector
Returns
their cross product.
Definition at line 776 of file BoundedRationalPolytope.h.
       {
         return v1.crossProduct( v2 );
       }
References DGtal::PointVector< dim, TEuclideanRing, TContainer >::crossProduct().
Field Documentation
dimension
template<typename TInteger > const Dimension DGtal::detail::BoundedRationalPolytopeSpecializer< 3, TInteger >::dimension = Space::dimension static
Definition at line 740 of file BoundedRationalPolytope.h.
The documentation for this struct was generated from the following file:
BoundedRationalPolytope.h