DGtal: DGtal::concepts::CPrimitiveComputer< T > Struct Template Reference
DGtal::concepts::CPrimitiveComputer< T > Struct Template Reference
DGtal Concepts
Aim: Defines the concept describing an object that computes some primitive from input points, while keeping some internal state. At any moment, the object is supposed to store at least one valid primitive for the formerly given input points. A primitive is an informal word that describes some family of objects that share common characteristics. Often, the primitives are geometric, e.g. digital planes.
#include <DGtal/geometry/surfaces/CPrimitiveComputer.h>
Public Types
typedef T::Primitive Primitive
typedef T::Space Space
Public Member Functions
BOOST_CONCEPT_USAGE (CPrimitiveComputer)
void checkConstConstraints () const
Private Attributes
T myX
Primitive myP
Detailed Description
template<typename T>
struct DGtal::concepts::CPrimitiveComputer< T >
Aim: Defines the concept describing an object that computes some primitive from input points, while keeping some internal state. At any moment, the object is supposed to store at least one valid primitive for the formerly given input points. A primitive is an informal word that describes some family of objects that share common characteristics. Often, the primitives are geometric, e.g. digital planes.
Description of concept 'CPrimitiveComputer'
Refinement of boost::DefaultConstructible<T>, boost::CopyConstructible<T>, boost::Assignable<T>
Associated types
Space, the type that defines the digital space.
Primitive, the type that defines the primitive.
Notation
X : A type that is a model of CPrimitiveComputer
x : object of type X
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
access to primitive x.primitive() Primitive returns a primitive that represents the current solution O(1)
Invariants
Models
COBANaivePlaneComputer, COBAGenericNaivePlaneComputer, ChordNaivePlaneComputer, ChordGenericNaivePlaneComputer, COBAGenericStandardPlaneComputer
Notes
Template Parameters
T the type that should be a model of CPrimitiveComputer.
Definition at line 95 of file CPrimitiveComputer.h.
Member Typedef Documentation
Primitive
template<typename T > typedef T::Primitive DGtal::concepts::CPrimitiveComputer< T >::Primitive
Definition at line 100 of file CPrimitiveComputer.h.
Space
template<typename T > typedef T::Space DGtal::concepts::CPrimitiveComputer< T >::Space
Definition at line 101 of file CPrimitiveComputer.h.
Member Function Documentation
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CPrimitiveComputer< T >::BOOST_CONCEPT_USAGE (CPrimitiveComputer< T >) inline
Definition at line 104 of file CPrimitiveComputer.h.
     {
       checkConstConstraints();
     }
References DGtal::concepts::CPrimitiveComputer< T >::checkConstConstraints().
checkConstConstraints()
template<typename T > void DGtal::concepts::CPrimitiveComputer< T >::checkConstConstraints () const inline
Definition at line 108 of file CPrimitiveComputer.h.
     {
       ConceptUtils::sameType( myP, myX.primitive() );
     }
References DGtal::concepts::CPrimitiveComputer< T >::myP, DGtal::concepts::CPrimitiveComputer< T >::myX, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::concepts::CPrimitiveComputer< T >::BOOST_CONCEPT_USAGE().
Field Documentation
myP
template<typename T > Primitive DGtal::concepts::CPrimitiveComputer< T >::myP private
Definition at line 115 of file CPrimitiveComputer.h.
Referenced by DGtal::concepts::CPrimitiveComputer< T >::checkConstConstraints().
myX
template<typename T > T DGtal::concepts::CPrimitiveComputer< T >::myX private
Definition at line 114 of file CPrimitiveComputer.h.
Referenced by DGtal::concepts::CPrimitiveComputer< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CPrimitiveComputer.h