DGtal: DGtal::GenericReader< TContainer, Tdim, TValue > Struct Template Reference
DGtal::GenericReader< TContainer, Tdim, TValue > Struct Template Reference
Aim: Provide a mechanism to load with the bestloader according to an image (2D or 3D) filename (by parsing the extension).
#include <DGtal/io/readers/GenericReader.h>
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CImage< TContainer >))
Static Public Member Functions
static TContainer import (const std::string &filename, std::vector< unsigned int > dimSpace=std::vector< unsigned int >())
template<typename TFunctor >
static TContainer importWithValueFunctor (const std::string &filename, const TFunctor &aFunctor, std::vector< unsigned int > dimSpace=std::vector< unsigned int >())
template<typename TFunctor >
static TContainer importWithColorFunctor (const std::string &filename, const TFunctor &aFunctor, std::vector< unsigned int > dimSpace=std::vector< unsigned int >())
Detailed Description
template<typename TContainer, int Tdim = TContainer::Point::dimension, typename TValue = typename TContainer::Value>
struct DGtal::GenericReader< TContainer, Tdim, TValue >
Aim: Provide a mechanism to load with the bestloader according to an image (2D or 3D) filename (by parsing the extension).
Description of template class 'GenericReader'
The typical use is very simple:
First include the header of the generic reader (and StdDefs) and define image type:
#include "DGTal/io/readers/GenericReader.h"
#include "DGtal/helpers/StdDefs.h"
typedef DGtal::ImageContainerBySTLMap<DGtal::Z3i::Domain, unsigned int> Image3D;
typedef DGtal::ImageContainerBySTLMap<DGtal::Z2i::Domain, unsigned int> Image2D;
Use the same import function for both 2D or 3D images:
Image3D an3Dimage= DGtal::GenericReader<Image3D>::import("example.vol");
Image2D an2Dimage= DGtal::GenericReader<Image2D>::import("example.pgm");
Advanced:
the file format value type will be cast to TContainer::Value. For instance, VOL file format deals with "unsigned char" and if the TContainer::Value type is different, you could have type conversion issues.
Template Parameters
TContainer the container (mainly an ImageContainer like ImageContainerBySTLVector or ImageContainerBySTLMap).
Tdim the dimension of the container (by default given by the container).
Examples
geometry/surfaces/dvcm-3d.cpp, images/imageBasicSubsampling.cpp, io/viewers/viewer3D-9-3Dimages.cpp, and tutorial-examples/2DSliceImageFromVol.cpp.
Definition at line 101 of file GenericReader.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename TContainer , int Tdim = TContainer::Point::dimension, typename TValue = typename TContainer::Value> DGtal::GenericReader< TContainer, Tdim, TValue >::BOOST_CONCEPT_ASSERT ((concepts::CImage< TContainer >))
Referenced by DGtal::GenericReader< TContainer, Tdim, TValue >::importWithColorFunctor(), DGtal::GenericReader< TContainer, 2, TValue >::importWithColorFunctor(), DGtal::GenericReader< TContainer, 2, DGtal::uint32_t >::importWithColorFunctor(), DGtal::GenericReader< TContainer, Tdim, TValue >::importWithValueFunctor(), DGtal::GenericReader< TContainer, 2, TValue >::importWithValueFunctor(), DGtal::GenericReader< TContainer, 2, DGtal::uint32_t >::importWithValueFunctor(), DGtal::GenericReader< TContainer, 3, TValue >::importWithValueFunctor(), and DGtal::GenericReader< TContainer, 3, DGtal::uint32_t >::importWithValueFunctor().
import()
template<typename TContainer , int Tdim = TContainer::Point::dimension, typename TValue = typename TContainer::Value> static TContainer DGtal::GenericReader< TContainer, Tdim, TValue >::import (const std::string & filename, std::vector< unsigned int > dimSpace = std::vector< unsigned int >()) static
Import a volume nd image file. For the special format of raw image, the default parameter of the image size must be given in the optional function vector parameter (dimSpace).
Parameters
filename the image filename to imported.
dimSpace a vector containing the n dimensional image size.
Referenced by get_mean_binarizer_from_an_image(), main(), DGtal::Shortcuts< TKSpace >::makeBinaryImage(), DGtal::Shortcuts< TKSpace >::makeDoubleImage(), DGtal::Shortcuts< TKSpace >::makeFloatImage(), DGtal::Shortcuts< TKSpace >::makeGrayScaleImage(), testGenericReader(), and testGenericWriter().
importWithColorFunctor()
template<typename TContainer , int Tdim = TContainer::Point::dimension, typename TValue = typename TContainer::Value> template<typename TFunctor > static TContainer DGtal::GenericReader< TContainer, Tdim, TValue >::importWithColorFunctor (const std::string & filename, const TFunctor & aFunctor, std::vector< unsigned int > dimSpace = std::vector<unsigned int>()) inline static
Import a volume nd image file by specifying a value functor.
Template Parameters
TFunctor The type of the functor (should verify the concept CUnaryFunctor<TFunctor, TValue , TContainer::Value >)
Parameters
dimSpace a vector containing the n dimensional image size.
filename the image filename to be imported.
aFunctor an ColorRGBEncoder. The type of the functor (should verify the concept CUnaryFunctor<TFunctor, TContainer::Value, DGtal::Color >).
Definition at line 176 of file GenericReader.h.
     {
       BOOST_CONCEPT_ASSERT(
       (concepts::CUnaryFunctor<TFunctor, DGtal::Color,
                                typename TContainer::Value>));
       DGtal::IOException dgtalio;
       const std::string extension =
       filename.substr( filename.find_last_of( "." ) + 1 );
       if ( extension == "raw" )
       {
         for ( unsigned int i = 0; i < dimSpace.size(); i++ )
           ASSERT( dimSpace[ i ] != 0 );
         typename TContainer::Point const pt;
         for ( unsigned int i = 0; i < dimSpace.size(); i++ )
           pt[ i ]            = dimSpace[ i ];
         return RawReader<TContainer, TFunctor>::template importRaw<
         DGtal::Color>( filename, pt, aFunctor );
       }
       trace.error() << "Extension " << extension
                     << " not yet implemented in DGtal GenericReader."
                     << std::endl;
       throw dgtalio;
     }
References DGtal::GenericReader< TContainer, Tdim, TValue >::BOOST_CONCEPT_ASSERT(), DGtal::Trace::error(), and DGtal::trace.
importWithValueFunctor()
template<typename TContainer , int Tdim = TContainer::Point::dimension, typename TValue = typename TContainer::Value> template<typename TFunctor > static TContainer DGtal::GenericReader< TContainer, Tdim, TValue >::importWithValueFunctor (const std::string & filename, const TFunctor & aFunctor, std::vector< unsigned int > dimSpace = std::vector<unsigned int>()) inline static
Import a volume nd image file by specifying a value functor.
Template Parameters
TFunctor The type of the functor (should verify the concept CUnaryFunctor<TFunctor, TValue , TContainer::Value >)
Parameters
dimSpace a vector containing the n dimensional image size..
filename the image filename to be imported.
aFunctor to transform the input type of image value (TValue) into the given image type (TContainer::Value).
Definition at line 131 of file GenericReader.h.
     {
       BOOST_CONCEPT_ASSERT(
       (concepts::CUnaryFunctor<TFunctor, TValue, typename TContainer::Value>));
       DGtal::IOException dgtalio;
       const std::string extension =
       filename.substr( filename.find_last_of( "." ) + 1 );
       if ( extension == "raw" )
       {
         for ( unsigned int i = 0; i < dimSpace.size(); i++ )
           ASSERT( dimSpace[ i ] != 0 );
         typename TContainer::Point const pt;
         for ( unsigned int i = 0; i < dimSpace.size(); i++ )
           pt[ i ]            = dimSpace[ i ];
         return RawReader<TContainer, TFunctor>::template importRaw<TValue>(
         filename, pt, aFunctor );
       }
       trace.error() << "Extension " << extension
                     << " not yet implemented in DGtal GenericReader."
                     << std::endl;
       throw dgtalio;
     }
References DGtal::GenericReader< TContainer, Tdim, TValue >::BOOST_CONCEPT_ASSERT(), DGtal::Trace::error(), and DGtal::trace.
Referenced by testGenericReader().
The documentation for this struct was generated from the following file:
GenericReader.h