DGtal: DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D Struct Reference
DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D Struct Reference
#include <DGtal/io/viewers/Viewer3D.h>
Public Member Functions
template<typename TDomain >
Image2DDomainD3D (TDomain aDomain, ImageDirection normalDir=zDirection, double xBottomLeft=0.0, double yBottomLeft=0.0, double zBottomLeft=0.0, std::string mode="BoundingBox")
void updateDomainOrientation (ImageDirection normalDir, double xBottomLeft, double yBottomLeft, double zBottomLeft)
void translateDomain (double xTranslation=0.0, double yTranslation=0.0, double zTranslation=0.0)
Data Fields
RealPoint point1
The image domain coordinates.
RealPoint point2
RealPoint point3
RealPoint point4
DGtal::Color color
The image domain color.
unsigned int myDomainWidth
the width of the image domain
unsigned int myDomainHeight
the height of the image domain
ImageDirection myDirection
the direction of the domain (x, y or z axe)
std::string myMode
the mode of representation of the image domain
std::size_t myLineSetIndex
the index of the line of the domain in the lineSetList of the viewer
Detailed Description
template<typename TSpace = SpaceND<3>, typename TKSpace = KhalimskySpaceND<3>>
struct DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D
Used to display the 2D domain of an image.
Note
has to be public because of external functions
Definition at line 494 of file Viewer3D.h.
Constructor & Destructor Documentation
Image2DDomainD3D()
template<typename TSpace = SpaceND<3>, typename TKSpace = KhalimskySpaceND<3>> template<typename TDomain > DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::Image2DDomainD3D (TDomain aDomain, ImageDirection normalDir = zDirection, double xBottomLeft = 0.0, double yBottomLeft = 0.0, double zBottomLeft = 0.0, std::string mode = "BoundingBox") inline
Constructor
Parameters
aDomain a domain
normalDir the normal vector direction
xBottomLeft the x coordinate of bottom left image point.
yBottomLeft the y coordinate of bottom left image point.
zBottomLeft the z coordinate of bottom left image point.
mode the mode of representation
Definition at line 525 of file Viewer3D.h.
       {
         BOOST_CONCEPT_ASSERT(( concepts::CDomain < TDomain >));
         myMode = mode;
         myDirection=normalDir;
         myDomainWidth = (aDomain.upperBound())[0]-(aDomain.lowerBound())[0]+1;
         myDomainHeight = (aDomain.upperBound())[1]-(aDomain.lowerBound())[1]+1;
         updateDomainOrientation(normalDir, xBottomLeft, yBottomLeft, zBottomLeft);
       }
References DGtal::Viewer3D< TSpace, TKSpace >::BOOST_CONCEPT_ASSERT(), DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::myDirection, DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::myDomainHeight, DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::myDomainWidth, DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::myMode, and DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::updateDomainOrientation().
Member Function Documentation
translateDomain()
template<typename TSpace = SpaceND<3>, typename TKSpace = KhalimskySpaceND<3>> void DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::translateDomain (double xTranslation = 0.0, double yTranslation = 0.0, double zTranslation = 0.0)
Translate domain postion.
Parameters
xTranslation the image translation in the x direction (default 0).
yTranslation the image translation in the y direction (default 0).
zTranslation the image translation in the z direction (default 0).
updateDomainOrientation()
template<typename TSpace = SpaceND<3>, typename TKSpace = KhalimskySpaceND<3>> void DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::updateDomainOrientation (ImageDirection normalDir, double xBottomLeft, double yBottomLeft, double zBottomLeft)
Update the domain direction from a specific normal direction (Viewer3D::xDirection, Viewer3D::yDirection or Viewer3D::zDirection) and image position from the botton left point.
Parameters
normalDir give a predifined normal orientation can be (Viewer3D::xDirection, Viewer3D::yDirection or Viewer3D::zDirection)
xBottomLeft the x coordinate of bottom left image point.
yBottomLeft the x coordinate of bottom left image point.
zBottomLeft the x coordinate of bottom left image point.
Referenced by DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::Image2DDomainD3D().
Field Documentation
color
template<typename TSpace = SpaceND<3>, typename TKSpace = KhalimskySpaceND<3>> DGtal::Color DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::color
The image domain color.
Definition at line 503 of file Viewer3D.h.
myDirection
template<typename TSpace = SpaceND<3>, typename TKSpace = KhalimskySpaceND<3>> ImageDirection DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::myDirection
the direction of the domain (x, y or z axe)
Definition at line 509 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::Image2DDomainD3D().
myDomainHeight
template<typename TSpace = SpaceND<3>, typename TKSpace = KhalimskySpaceND<3>> unsigned int DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::myDomainHeight
the height of the image domain
Definition at line 507 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::Image2DDomainD3D().
myDomainWidth
template<typename TSpace = SpaceND<3>, typename TKSpace = KhalimskySpaceND<3>> unsigned int DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::myDomainWidth
the width of the image domain
Definition at line 505 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::Image2DDomainD3D().
myLineSetIndex
template<typename TSpace = SpaceND<3>, typename TKSpace = KhalimskySpaceND<3>> std::size_t DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::myLineSetIndex
the index of the line of the domain in the lineSetList of the viewer
Definition at line 513 of file Viewer3D.h.
myMode
template<typename TSpace = SpaceND<3>, typename TKSpace = KhalimskySpaceND<3>> std::string DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::myMode
the mode of representation of the image domain
Definition at line 511 of file Viewer3D.h.
Referenced by DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::Image2DDomainD3D().
point1
template<typename TSpace = SpaceND<3>, typename TKSpace = KhalimskySpaceND<3>> RealPoint DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::point1
The image domain coordinates.
Definition at line 498 of file Viewer3D.h.
point2
template<typename TSpace = SpaceND<3>, typename TKSpace = KhalimskySpaceND<3>> RealPoint DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::point2
Definition at line 499 of file Viewer3D.h.
point3
template<typename TSpace = SpaceND<3>, typename TKSpace = KhalimskySpaceND<3>> RealPoint DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::point3
Definition at line 500 of file Viewer3D.h.
point4
template<typename TSpace = SpaceND<3>, typename TKSpace = KhalimskySpaceND<3>> RealPoint DGtal::Viewer3D< TSpace, TKSpace >::Image2DDomainD3D::point4
Definition at line 501 of file Viewer3D.h.
The documentation for this struct was generated from the following file:
Viewer3D.h