DGtal: LibBoard::Text Struct Reference
LibBoard::Text Struct Reference
A piece of text.
#include <Board/Shapes.h>
Public Member Functions
Text (double x, double y, const std::string &text, const Fonts::Font font, double size, DGtal::Color color=DGtal::Color::Black, int depthValue=-1)
Text (double x, double y, const std::string &text, const Fonts::Font font, const std::string &svgFont, double size, DGtal::Color color=DGtal::Color::Black, int depthValue=-1)
const std::string & name () const
Point center () const
Text & rotate (double angle, const Point &center)
Text rotated (double angle, const Point &center) const
Text & rotate (double angle)
Text rotated (double angle) const
Text & translate (double dx, double dy)
Text translated (double dx, double dy) const
Shape & scale (double sx, double sy)
Shape & scale (double s)
Text scaled (double sx, double sy) const
Text scaled (double s) const
void scaleAll (double s)
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
Rect boundingBox () const
Text * clone () const
Public Member Functions inherited from LibBoard::Shape
Shape (DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, LineStyle style, const LineCap cap, const LineJoin join, int depth)
virtual ~Shape ()
bool filled () const
Shape & rotateDeg (double angle, const Point &center)
Shape & rotateDeg (double angle)
Rect bbox ()
Shape & operator-- ()
Shape & operator++ ()
int depth () const
virtual void depth (int)
virtual void shiftDepth (int shift)
const DGtal::Color & penColor () const
const DGtal::Color & fillColor () const
Protected Attributes
Point _position
std::string _text
Fonts::Font _font
std::string _svgFont
double _angle
double _size
double _xScale
double _yScale
Protected Attributes inherited from LibBoard::Shape
int _depth
DGtal::Color _penColor
DGtal::Color _fillColor
double _lineWidth
LineStyle _lineStyle
LineCap _lineCap
LineJoin _lineJoin
Static Private Attributes
static const std::string _name
Additional Inherited Members
Public Types inherited from LibBoard::Shape
enum LineCap { ButtCap = 0, RoundCap, SquareCap }
enum LineJoin { MiterJoin = 0, RoundJoin, BevelJoin }
enum LineStyle {
SolidStyle = 0, DashStyle, DotStyle, DashDotStyle,
DashDotDotStyle, DashDotDotDotStyle
}
Protected Member Functions inherited from LibBoard::Shape
std::string svgProperties (const TransformSVG &transform) const
std::string postscriptProperties () const
void setCairoDashStyle (cairo_t *cr, LineStyle type) const
std::string tikzProperties (const TransformTikZ &transform) const
Detailed Description
A piece of text.
The text structure.
Definition at line 1574 of file Board/Shapes.h.
Constructor & Destructor Documentation
Text() [1/2]
LibBoard::Text::Text (double x, double y, const std::string & text, const Fonts::Font font, double size, DGtal::Color color = DGtal::Color::Black, int depthValue = -1) inline
Create a Text sctucture.
Parameters
x x
y y
text text
font font
size The font size expressed in 1/72 inches.
color color
depthValue depth
Definition at line 1588 of file Board/Shapes.h.
     : Shape( color, DGtal::Color::None, 1.0, SolidStyle, ButtCap, MiterJoin, depthValue ),
       _position( x, y ), _text( text ), _font( font ),
       _angle( 0.0 ), _size( size ),
       _xScale( 1.0 ), _yScale( 1.0 ) { }
Referenced by clone(), rotated(), scaled(), and translated().
Text() [2/2]
LibBoard::Text::Text (double x, double y, const std::string & text, const Fonts::Font font, const std::string & svgFont, double size, DGtal::Color color = DGtal::Color::Black, int depthValue = -1) inline
Create a Text sctucture.
Parameters
x x
y y
text text
font font
svgFont The font family for an SVG file. (E.g. "Verdana, Arial" or "'Time New Roman', Serif")
size The font size expressed in 1/72 inches.
color color
depthValue depth
Definition at line 1613 of file Board/Shapes.h.
     : Shape( color, DGtal::Color::None, 1.0, SolidStyle, ButtCap, MiterJoin, depthValue ),
       _position( x, y ),
       _text( text ), _font( font ), _svgFont( svgFont ),
       _angle( 0.0 ),
       _size( size ),
       _xScale( 1.0 ), _yScale( 1.0 ) { }
Member Function Documentation
boundingBox()
Rect LibBoard::Text::boundingBox () const virtual
Returns the bounding box of the figure.
Returns
The rectangle of the bounding box.
Implements LibBoard::Shape.
Definition at line 2759 of file Shapes.cpp.
 {
     return Rect( _position.x, _position.y, 0, 0 );
 }
References _position, LibBoard::Point::x, and LibBoard::Point::y.
center()
Point LibBoard::Text::center () const virtual
Returns the gravity center of the shape.
Returns
The center of the shape.
Implements LibBoard::Shape.
Definition at line 2535 of file Shapes.cpp.
                    {
     return _position;
 }
References _position.
clone()
Text * LibBoard::Text::clone () const virtual
Return a copy of the shape.
Returns
copye of the shape.
Implements LibBoard::Shape.
Definition at line 2623 of file Shapes.cpp.
                   {
     return new Text(*this);
 }
References Text().
flushCairo()
void LibBoard::Text::flushCairo (cairo_t * cr, const TransformCairo & transform) const virtual
Writes the cairo code of the shape in a cairo drawing context according to a transform.
Parameters
cr The cairo drawing context.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 2694 of file Shapes.cpp.
 {
 }
flushFIG()
void LibBoard::Text::flushFIG (std::ostream & stream, const TransformFIG & transform, std::map< DGtal::Color, int > & colormap) const virtual
Writes the FIG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
colormap A colormap.
Implements LibBoard::Shape.
Definition at line 2641 of file Shapes.cpp.
 {
     stream << "4 0 " ;
     // Color, depth, unused, Font
     stream << colormap[ _penColor ] <<  " " << transform.mapDepth( _depth ) << " -1 " << _font << " ";
     // Font size, Angle, Font flags
     stream << _size << " " << _angle << " 4 ";
     // Height
     stream << static_cast<int>(  _size * 135 / 12.0 ) << " ";
     // Width
     stream << static_cast<int>( _text.size() * _size * 135 / 12.0 ) << " ";
     // x y
     stream << static_cast<int>( transform.mapX( _position.x ) ) << " "
     << static_cast<int>( transform.mapY( _position.y ) ) << " ";
     stream << _text << "\\001\n";
 }
References _angle, LibBoard::Shape::_depth, _font, LibBoard::Shape::_penColor, _position, _size, _text, LibBoard::Point::x, and LibBoard::Point::y.
flushPostscript()
void LibBoard::Text::flushPostscript (std::ostream & stream, const TransformEPS & transform) const virtual
Writes the EPS code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 2628 of file Shapes.cpp.
 {
     stream << "\n% Text\n";
     stream << "gs /" << PSFontNames[ _font ] << " ff " << _size << " scf sf";
     stream << " " << transform.mapX( _position.x ) << " " << transform.mapY( _position.y ) << " m";
     if ( _angle != 0.0 ) stream << " " << (_angle/M_PI)*180.0 << " rot ";
     stream << " (" << _text << ")"
     << " " << _penColor.postscript() << " srgb"
     << " sh gr" << std::endl;
 }
References _angle, _font, LibBoard::Shape::_penColor, _position, _size, _text, DGtal::Color::postscript(), LibBoard::PSFontNames, LibBoard::Point::x, and LibBoard::Point::y.
flushSVG()
void LibBoard::Text::flushSVG (std::ostream & stream, const TransformSVG & transform) const virtual
Writes the SVG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 2661 of file Shapes.cpp.
 {
     if ( _angle != 0.0f ) {
         stream << "<g transform=\"translate("
         << transform.mapX( _position.x ) << ","
         << transform.mapY( _position.y ) << ")\" >"
         << "<g transform=\"rotate(" << (-_angle*180.0/M_PI) << ")\" >"
         << "<text x=\"0\" y=\"0\""
         << " font-family=\"" << ( _svgFont.length() ? _svgFont : PSFontNames[ _font ] ) << "\""
         << " font-size=\"" << _size << "\""
         << " fill=\"" << _penColor.svg() << "\""
         << _fillColor.svgAlpha( " fill" )
         << _penColor.svgAlpha( " stroke" )
         << ">"
         << _text
         << "</text></g></g>" << std::endl;
     } else {
         stream << "<text x=\"" << transform.mapX( _position.x )
         << "\" y=\"" << transform.mapY( _position.y ) << "\" "
         << " font-family=\"" << ( _svgFont.length() ? _svgFont : PSFontNames[ _font ] ) << "\""
         << " font-size=\"" << _size << "\""
         << " fill=\"" << _penColor.svg() << "\""
         << _fillColor.svgAlpha( " fill" )
         << _penColor.svgAlpha( " stroke" )
         << ">"
         << _text
         << "</text>" << std::endl;
     }
 }
References _angle, LibBoard::Shape::_fillColor, _font, LibBoard::Shape::_penColor, _position, _size, _svgFont, _text, LibBoard::PSFontNames, DGtal::Color::svg(), DGtal::Color::svgAlpha(), LibBoard::Point::x, and LibBoard::Point::y.
flushTikZ()
void LibBoard::Text::flushTikZ (std::ostream & stream, const TransformTikZ & transform) const virtual
Writes the TikZ code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Definition at line 2701 of file Shapes.cpp.
 {
   // FIXME: honor font-size
 #define BOLD_FONT       0x01
 #define ITALIC_FONT     0x02
 #define MONOSPACE_FONT  0x04
 #define SANSSERIF_FONT  0x08
     char fontTraits[] = {
         0,                                              // TimesRoman,
         ITALIC_FONT,                                    // TimesItalic,
         BOLD_FONT,                                      // TimesBold,
         BOLD_FONT | ITALIC_FONT,                        // TimesBoldItalic,
         SANSSERIF_FONT,                                 // AvantGardeBook,
         SANSSERIF_FONT | ITALIC_FONT,                   // AvantGardeBookOblique,
         SANSSERIF_FONT,                                 // AvantGardeDemi,
         SANSSERIF_FONT | ITALIC_FONT,                   // AvantGardeDemiOblique,
         0,                                              // BookmanLight,
         ITALIC_FONT,                                    // BookmanLightItalic,
         0,                                              // BookmanDemi,
         ITALIC_FONT,                                    // BookmanDemiItalic,
         MONOSPACE_FONT,                                 // Courier,
         MONOSPACE_FONT | ITALIC_FONT,                   // CourierOblique,
         MONOSPACE_FONT | BOLD_FONT,                     // CourierBold,
         MONOSPACE_FONT | BOLD_FONT | ITALIC_FONT,       // CourierBoldOblique,
         SANSSERIF_FONT,                                 // Helvetica,
         SANSSERIF_FONT | ITALIC_FONT,                   // HelveticaOblique,
         SANSSERIF_FONT | BOLD_FONT,                     // HelveticaBold,
         SANSSERIF_FONT | BOLD_FONT | ITALIC_FONT,       // HelveticaBoldOblique,
         SANSSERIF_FONT,                                 // HelveticaNarrow,
         SANSSERIF_FONT | ITALIC_FONT,                   // HelveticaNarrowOblique,
         SANSSERIF_FONT | BOLD_FONT,                     // HelveticaNarrowBold,
         SANSSERIF_FONT | BOLD_FONT | ITALIC_FONT,       // HelveticaNarrowBoldOblique,
         0,                                              // NewCenturySchoolbookRoman,
         ITALIC_FONT,                                    // NewCenturySchoolbookItalic,
         BOLD_FONT,                                      // NewCenturySchoolbookBold,
         BOLD_FONT | ITALIC_FONT,                        // NewCenturySchoolbookBoldItalic,
         0,                                              // PalatinoRoman,
         ITALIC_FONT,                                    // PalatinoItalic,
         BOLD_FONT,                                      // PalatinoBold,
         BOLD_FONT | ITALIC_FONT,                        // PalatinoBoldItalic,
         0,                                              // Symbol,
         ITALIC_FONT,                                    // ZapfChanceryMediumItalic,
         0                                               // ZapfDingbats
     };
     stream << "\\path[" << tikzProperties(transform) << "] ("
            << transform.mapX( _position.x ) << ',' << transform.mapY( _position.y )
            << ") node {"
            << (fontTraits[ _font ] & ITALIC_FONT ? "\\itshape " : "")
            << (fontTraits[ _font ] & BOLD_FONT ? "\\bfseries " : "")
            << (fontTraits[ _font ] & MONOSPACE_FONT ? "\\ttfamily " : "")
            << (fontTraits[ _font ] & SANSSERIF_FONT ? "\\sffamily " : "")
            << _text
            << "};" << std::endl;
 }
References _font, _position, _text, LibBoard::Shape::tikzProperties(), LibBoard::Point::x, and LibBoard::Point::y.
name()
const std::string & LibBoard::Text::name () const virtual
Returns the generic name of the shape (e.g., Circle, Rectangle, etc.)
Returns
object name
Reimplemented from LibBoard::Shape.
Definition at line 2529 of file Shapes.cpp.
 {
     return _name;
 }
References _name.
rotate() [1/2]
Text & LibBoard::Text::rotate (double angle) virtual
Rotate the shape around its center.
Parameters
angle The rotation angle in radian.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Definition at line 2560 of file Shapes.cpp.
 {
     _angle += angle;
     if ( _angle < 0 )
         while ( _angle < M_PI ) _angle += 2 * M_PI;
     if ( _angle > 0 )
         while ( _angle > M_PI ) _angle -= 2 * M_PI;
     return *this;
 }
References _angle, and angle().
rotate() [2/2]
Text & LibBoard::Text::rotate (double angle, const Point & center) virtual
Rotate the shape around a given center of rotation.
Parameters
angle The rotation angle in radian.
center The center of rotation.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Definition at line 2540 of file Shapes.cpp.
 {
     Point endPos = _position + Point( 10000 * cos( _angle ), 10000 * sin( _angle ) );
     _position.rotate( angle, rotCenter );
     endPos.rotate( angle, rotCenter );
     Point v = endPos - _position;
     v /= v.norm();
     if ( v.x >= 0 ) _angle = asin( v.y );
     else if ( v.y > 0 ) _angle = (M_PI/2.0) + acos( v.y );
     else _angle = (-M_PI/2.0) - acos( -v.y );
     return *this;
 }
References _angle, _position, LibBoard::Point::norm(), and LibBoard::Point::rotate().
rotated() [1/2]
Text LibBoard::Text::rotated (double angle) const
Definition at line 2571 of file Shapes.cpp.
 {
     return Text(*this).rotate( angle );
 }
References Text().
rotated() [2/2]
Text LibBoard::Text::rotated (double angle, const Point & center) const
Definition at line 2554 of file Shapes.cpp.
 {
     return Text(*this).rotate( angle, rotCenter );
 }
References Text().
scale() [1/2]
Shape & LibBoard::Text::scale (double s) virtual
Scale the shape along both axis.
Parameters
s The scale factor along both axis.
Returns
The shape itself.
Implements LibBoard::Shape.
Definition at line 2598 of file Shapes.cpp.
 {
     _xScale = _yScale = s;
     return *this;
 }
References _xScale, and _yScale.
scale() [2/2]
Shape & LibBoard::Text::scale (double sx, double sy) virtual
Scale the shape along the x an y axis.
Parameters
sx The scale factor along the x axis.
sy The scale factor along the y axis.
Returns
The shape itself.
Implements LibBoard::Shape.
Definition at line 2590 of file Shapes.cpp.
 {
     _xScale = sx;
     _yScale = sy;
     return *this;
 }
References _xScale, and _yScale.
scaleAll()
void LibBoard::Text::scaleAll (double s) virtual
Scales all the values (positions, dimensions, etc.) associated with the shape.
Parameters
s The scaling factor.
Implements LibBoard::Shape.
Definition at line 2617 of file Shapes.cpp.
 {
     _position *= s;
 }
References _position.
scaled() [1/2]
Text LibBoard::Text::scaled (double s) const
Definition at line 2611 of file Shapes.cpp.
 {
     return static_cast<Text &>( Text(*this).scale( s, s ) );
 }
References Text().
scaled() [2/2]
Text LibBoard::Text::scaled (double sx, double sy) const
Definition at line 2605 of file Shapes.cpp.
 {
     return static_cast<Text &>( Text(*this).scale( sx, sy ) );
 }
References Text().
translate()
Text & LibBoard::Text::translate (double dx, double dy) virtual
Translate the shape by a given offset.
Parameters
dx The x offset.
dy The y offset.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Definition at line 2577 of file Shapes.cpp.
 {
     _position += Point( dx, dy );
     return *this;
 }
References _position.
translated()
Text LibBoard::Text::translated (double dx, double dy) const
Definition at line 2584 of file Shapes.cpp.
 {
     return static_cast<Text&>( Text(*this).translate( dx, dy ) );
 }
References Text().
Field Documentation
_angle
double LibBoard::Text::_angle protected
Definition at line 1694 of file Board/Shapes.h.
Referenced by flushFIG(), flushPostscript(), flushSVG(), and rotate().
_font
Fonts::Font LibBoard::Text::_font protected
Definition at line 1692 of file Board/Shapes.h.
Referenced by flushFIG(), flushPostscript(), flushSVG(), and flushTikZ().
_name
const std::string LibBoard::Text::_name static private
The generic name of the shape.
Definition at line 1687 of file Board/Shapes.h.
Referenced by name().
_position
Point LibBoard::Text::_position protected
Definition at line 1690 of file Board/Shapes.h.
Referenced by boundingBox(), center(), flushFIG(), flushPostscript(), flushSVG(), flushTikZ(), rotate(), scaleAll(), and translate().
_size
double LibBoard::Text::_size protected
Definition at line 1695 of file Board/Shapes.h.
Referenced by flushFIG(), flushPostscript(), and flushSVG().
_svgFont
std::string LibBoard::Text::_svgFont protected
Definition at line 1693 of file Board/Shapes.h.
Referenced by flushSVG().
_text
std::string LibBoard::Text::_text protected
Definition at line 1691 of file Board/Shapes.h.
Referenced by flushFIG(), flushPostscript(), flushSVG(), and flushTikZ().
_xScale
double LibBoard::Text::_xScale protected
Definition at line 1696 of file Board/Shapes.h.
Referenced by scale().
_yScale
double LibBoard::Text::_yScale protected
Definition at line 1697 of file Board/Shapes.h.
Referenced by scale().
The documentation for this struct was generated from the following files:
Board/Shapes.h
Shapes.cpp