DGtal: DGtal::concepts::CMatrix< T > Struct Template Reference
DGtal::concepts::CMatrix< T > Struct Template Reference
DGtal Concepts
Aim: Represent any static or dynamic sized matrix having sparse or dense representation.
#include <DGtal/math/linalg/CMatrix.h>
Public Types
typedef T::Scalar Scalar
typedef T::Index Index
Public Types inherited from DGtal::concepts::CVectorSpace< T >
typedef T::Scalar Scalar
Public Member Functions
BOOST_CONCEPT_USAGE (CMatrix)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::concepts::CVectorSpace< T >
BOOST_CONCEPT_ASSERT ((concepts::CEuclideanRing< Scalar >))
BOOST_CONCEPT_USAGE (CVectorSpace)
Private Attributes
T z
Index i
Index j
Detailed Description
template<typename T>
struct DGtal::concepts::CMatrix< T >
Aim: Represent any static or dynamic sized matrix having sparse or dense representation.
Description of concept 'CMatrix'
Refinement of
CVectorSpace
Associated types
Notation
Matrix : A type that is a model of CMatrix
x : const object of type Matrix
z : object of type Matrix
i, j : object of type Matrix::Index
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
Identity setter x.setIdentity()
Number of rows x.rows() Index
Number of columns x.cols() Index
Invariants
Models
Notes
Template Parameters
T the type that should be a model of CMatrix.
Definition at line 90 of file CMatrix.h.
Member Typedef Documentation
Index
template<typename T > typedef T::Index DGtal::concepts::CMatrix< T >::Index
Definition at line 95 of file CMatrix.h.
Scalar
template<typename T > typedef T::Scalar DGtal::concepts::CMatrix< T >::Scalar
Definition at line 94 of file CMatrix.h.
Member Function Documentation
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CMatrix< T >::BOOST_CONCEPT_USAGE (CMatrix< T >) inline
Definition at line 97 of file CMatrix.h.
     {
         z.setIdentity();
         checkConstConstraints();
     }
References DGtal::concepts::CMatrix< T >::checkConstConstraints().
checkConstConstraints()
template<typename T > void DGtal::concepts::CMatrix< T >::checkConstConstraints () const inline
Definition at line 103 of file CMatrix.h.
     {
         ConceptUtils::sameType(i, z.rows());
         ConceptUtils::sameType(j, z.cols());
     }
References DGtal::concepts::CMatrix< T >::i, DGtal::concepts::CMatrix< T >::j, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::concepts::CMatrix< T >::BOOST_CONCEPT_USAGE().
Field Documentation
i
template<typename T > Index DGtal::concepts::CMatrix< T >::i private
Definition at line 111 of file CMatrix.h.
Referenced by DGtal::concepts::CMatrix< T >::checkConstConstraints().
j
template<typename T > Index DGtal::concepts::CMatrix< T >::j private
Definition at line 111 of file CMatrix.h.
Referenced by DGtal::concepts::CMatrix< T >::checkConstConstraints().
z
template<typename T > T DGtal::concepts::CMatrix< T >::z private
Definition at line 110 of file CMatrix.h.
The documentation for this struct was generated from the following file:
CMatrix.h