DGtal: DGtal::concepts::CConstBidirectionalRangeFromPoint< T > Struct Template Reference
DGtal::concepts::CConstBidirectionalRangeFromPoint< T > Struct Template Reference
DGtal Concepts
Aim: refined concept of const bidirectional range with a begin() method from a point.
#include <DGtal/base/CConstBidirectionalRangeFromPoint.h>
Public Types
typedef T::Point Point
Public Types inherited from DGtal::concepts::CConstBidirectionalRange< T >
typedef T::ConstReverseIterator ConstReverseIterator
Public Types inherited from DGtal::concepts::CConstSinglePassRange< T >
typedef T::ConstIterator ConstIterator
Public Member Functions
BOOST_CONCEPT_USAGE (CConstBidirectionalRangeFromPoint)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::concepts::CConstBidirectionalRange< T >
BOOST_CONCEPT_ASSERT ((boost_concepts::SinglePassIteratorConcept< ConstReverseIterator >))
BOOST_CONCEPT_USAGE (CConstBidirectionalRange)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::concepts::CConstSinglePassRange< T >
BOOST_CONCEPT_ASSERT ((boost_concepts::SinglePassIteratorConcept< ConstIterator >))
BOOST_CONCEPT_USAGE (CConstSinglePassRange)
void checkConstConstraints () const
Private Attributes
T myX
Point myPoint
T::ConstReverseIterator myB
Detailed Description
template<typename T>
struct DGtal::concepts::CConstBidirectionalRangeFromPoint< T >
Aim: refined concept of const bidirectional range with a begin() method from a point.
DescriptionDescription of concept 'CConstBidirectionalRangeFromPoint'
Refinement of CConstBidirectionalRange
Associated types
Notation
X : A type that is a model of CConstBidirectionalRangeFromPoint
x, y : object of type X
Point: A type of Point
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
reverse begin rbegin(const Point &aPoint) aPoint of type Point ConstIterator Returns a const reverse iterator on the range first element
Invariants
Models
ImageContainerBySTLVector::Range
Notes
Template Parameters
T the type that should be a model of CConstBidirectionalRangeFromPoint.
Definition at line 93 of file CConstBidirectionalRangeFromPoint.h.
Member Typedef Documentation
Point
template<typename T > typedef T::Point DGtal::concepts::CConstBidirectionalRangeFromPoint< T >::Point
Definition at line 98 of file CConstBidirectionalRangeFromPoint.h.
Member Function Documentation
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CConstBidirectionalRangeFromPoint< T >::BOOST_CONCEPT_USAGE (CConstBidirectionalRangeFromPoint< T >) inline
Definition at line 101 of file CConstBidirectionalRangeFromPoint.h.
       {
         checkConstConstraints();
       }
References DGtal::concepts::CConstBidirectionalRangeFromPoint< T >::checkConstConstraints().
checkConstConstraints()
template<typename T > void DGtal::concepts::CConstBidirectionalRangeFromPoint< T >::checkConstConstraints () const inline
Definition at line 105 of file CConstBidirectionalRangeFromPoint.h.
       {
         // const method dummyConst should take parameter myA of type A and return
         // something of type B
         concepts::ConceptUtils::sameType( myB, myX.rbegin( myPoint ) );
       }
References DGtal::concepts::CConstBidirectionalRangeFromPoint< T >::myB, DGtal::concepts::CConstBidirectionalRangeFromPoint< T >::myPoint, DGtal::concepts::CConstBidirectionalRangeFromPoint< T >::myX, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::concepts::CConstBidirectionalRangeFromPoint< T >::BOOST_CONCEPT_USAGE().
Field Documentation
myB
template<typename T > T::ConstReverseIterator DGtal::concepts::CConstBidirectionalRangeFromPoint< T >::myB private
Definition at line 115 of file CConstBidirectionalRangeFromPoint.h.
Referenced by DGtal::concepts::CConstBidirectionalRangeFromPoint< T >::checkConstConstraints().
myPoint
template<typename T > Point DGtal::concepts::CConstBidirectionalRangeFromPoint< T >::myPoint private
Definition at line 114 of file CConstBidirectionalRangeFromPoint.h.
Referenced by DGtal::concepts::CConstBidirectionalRangeFromPoint< T >::checkConstConstraints().
myX
template<typename T > T DGtal::concepts::CConstBidirectionalRangeFromPoint< T >::myX private
Definition at line 113 of file CConstBidirectionalRangeFromPoint.h.
Referenced by DGtal::concepts::CConstBidirectionalRangeFromPoint< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CConstBidirectionalRangeFromPoint.h