DGtal: DGtal::concepts::CPointEmbedder< T > Struct Template Reference
DGtal::concepts::CPointEmbedder< T > Struct Template Reference
DGtal Concepts
Aim: A point embedder is a mapping from digital points to Euclidean points. It adds inner types to functor.
#include <DGtal/kernel/CPointEmbedder.h>
Public Types
typedef T::Space Space
typedef T::Point Point
typedef T::RealPoint RealPoint
typedef T::Argument Argument
typedef T::Value Value
Public Member Functions
BOOST_CONCEPT_ASSERT ((CSpace< Space >))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Point, typename Space::Point >::value))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Point, Argument >::value))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< RealPoint, typename Space::RealPoint >::value))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< RealPoint, Value >::value))
BOOST_CONCEPT_USAGE (CPointEmbedder)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::concepts::CUnaryFunctor< T, T::Point, T::RealPoint >
BOOST_CONCEPT_USAGE (CUnaryFunctor)
Private Attributes
T myX
Point myP
RealPoint myRP
Detailed Description
template<typename T>
struct DGtal::concepts::CPointEmbedder< T >
Aim: A point embedder is a mapping from digital points to Euclidean points. It adds inner types to functor.
Description of concept 'CPointEmbedder'
Refinement of
CUnaryFunctor<T, T::Point, T::RealPoint>
Associated types
Space: the digital space
Point: same as Space::Point
Argument: type of the argument, same as Space::Point
Value: type of value, same as Space::RealPoint
Notation
X : A type that is a model of CPointEmbedder
x : object of type X
p : object of type Point
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
Apply function x(p) Value return the value of the function x on argument p
Invariants
Models
CanonicEmbedder, RegularPointEmbedder
Notes
Template Parameters
T the type that should be a model of CPointEmbedder.
Definition at line 95 of file CPointEmbedder.h.
Member Typedef Documentation
Argument
template<typename T > typedef T::Argument DGtal::concepts::CPointEmbedder< T >::Argument
Definition at line 102 of file CPointEmbedder.h.
Point
template<typename T > typedef T::Point DGtal::concepts::CPointEmbedder< T >::Point
Definition at line 100 of file CPointEmbedder.h.
RealPoint
template<typename T > typedef T::RealPoint DGtal::concepts::CPointEmbedder< T >::RealPoint
Definition at line 101 of file CPointEmbedder.h.
Space
template<typename T > typedef T::Space DGtal::concepts::CPointEmbedder< T >::Space
Definition at line 99 of file CPointEmbedder.h.
Value
template<typename T > typedef T::Value DGtal::concepts::CPointEmbedder< T >::Value
Definition at line 103 of file CPointEmbedder.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename T > DGtal::concepts::CPointEmbedder< T >::BOOST_CONCEPT_ASSERT ((CSpace< Space >))
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CPointEmbedder< T >::BOOST_CONCEPT_USAGE (CPointEmbedder< T >) inline
Definition at line 110 of file CPointEmbedder.h.
   {
     checkConstConstraints();
   }
References DGtal::concepts::CPointEmbedder< T >::checkConstConstraints().
BOOST_STATIC_ASSERT() [1/4]
template<typename T > DGtal::concepts::CPointEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Point, Argument >::value))
BOOST_STATIC_ASSERT() [2/4]
template<typename T > DGtal::concepts::CPointEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Point, typename Space::Point >::value))
BOOST_STATIC_ASSERT() [3/4]
template<typename T > DGtal::concepts::CPointEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< RealPoint, typename Space::RealPoint >::value))
BOOST_STATIC_ASSERT() [4/4]
template<typename T > DGtal::concepts::CPointEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< RealPoint, Value >::value))
checkConstConstraints()
template<typename T > void DGtal::concepts::CPointEmbedder< T >::checkConstConstraints () const inline
Definition at line 115 of file CPointEmbedder.h.
   { // operator()
     ConceptUtils::sameType( myRP, myX( myP ) );
   }
References DGtal::concepts::CPointEmbedder< T >::myP, DGtal::concepts::CPointEmbedder< T >::myRP, DGtal::concepts::CPointEmbedder< T >::myX, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::concepts::CPointEmbedder< T >::BOOST_CONCEPT_USAGE().
Field Documentation
myP
template<typename T > Point DGtal::concepts::CPointEmbedder< T >::myP private
Definition at line 122 of file CPointEmbedder.h.
Referenced by DGtal::concepts::CPointEmbedder< T >::checkConstConstraints().
myRP
template<typename T > RealPoint DGtal::concepts::CPointEmbedder< T >::myRP private
Definition at line 123 of file CPointEmbedder.h.
Referenced by DGtal::concepts::CPointEmbedder< T >::checkConstConstraints().
myX
template<typename T > T DGtal::concepts::CPointEmbedder< T >::myX private
Definition at line 121 of file CPointEmbedder.h.
Referenced by DGtal::concepts::CPointEmbedder< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CPointEmbedder.h