DGtal: DGtal::concepts::CAdditivePrimitiveComputer< T > Struct Template Reference
DGtal::concepts::CAdditivePrimitiveComputer< T > Struct Template Reference
DGtal Concepts
Aim: Defines the concept describing an object that computes some primitive from input points given group by group, while keeping some internal state. At any moment, the object is supposed to store at least one valid primitive for the formerly given input points. A primitive is an informal word that describes some family of objects that share common characteristics. Often, the primitives are geometric, e.g. digital planes.
#include <DGtal/geometry/surfaces/CAdditivePrimitiveComputer.h>
Public Types
typedef T::Point Point
Public Types inherited from DGtal::concepts::CIncrementalPrimitiveComputer< T >
typedef T::Point Point
Public Types inherited from DGtal::concepts::CPrimitiveComputer< T >
typedef T::Primitive Primitive
typedef T::Space Space
Public Member Functions
BOOST_CONCEPT_USAGE (CAdditivePrimitiveComputer)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::concepts::CIncrementalPrimitiveComputer< T >
BOOST_CONCEPT_USAGE (CIncrementalPrimitiveComputer)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::concepts::CPrimitiveComputer< T >
BOOST_CONCEPT_USAGE (CPrimitiveComputer)
void checkConstConstraints () const
Private Attributes
T myX
bool myBool
CForwardIteratorArchetype< Point > myIt
Detailed Description
template<typename T>
struct DGtal::concepts::CAdditivePrimitiveComputer< T >
Aim: Defines the concept describing an object that computes some primitive from input points given group by group, while keeping some internal state. At any moment, the object is supposed to store at least one valid primitive for the formerly given input points. A primitive is an informal word that describes some family of objects that share common characteristics. Often, the primitives are geometric, e.g. digital planes.
Description of concept 'CAdditivePrimitiveComputer'
Refinement of CIncrementalPrimitiveComputer
Associated types
Primitive, the type that defines the primitive.
Point: the type of the input points.
Notation
X : A type that is a model of CAdditivePrimitiveComputer
x : object of type X
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
insert new points x.extend(it, itE) ForwardIterator it, itE: the type of iterator on points, a model of boost::ForwardIterator on Point bool tries to find a primitive that matches the new points in range [it, itE) and all formerly given input points, return true on success (state may change), false otherwise (state is unchanged)
check new points x.isExtendable(it, itE) ForwardIterator it, itE: the type of iterator on points, a model of boost::ForwardIterator bool tries to find a primitive that matches the new points in range [it, itE) and all formerly given input points, return true only if it possible, the state is always unchanged
Invariants
Models
COBANaivePlaneComputer, COBAGenericNaivePlaneComputer, ChordNaivePlaneComputer, ChordGenericNaivePlaneComputer, COBAGenericStandardPlaneComputer
Notes
Template Parameters
T the type that should be a model of CAdditivePrimitiveComputer.
Definition at line 99 of file CAdditivePrimitiveComputer.h.
Member Typedef Documentation
Point
template<typename T > typedef T::Point DGtal::concepts::CAdditivePrimitiveComputer< T >::Point
Definition at line 104 of file CAdditivePrimitiveComputer.h.
Member Function Documentation
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CAdditivePrimitiveComputer< T >::BOOST_CONCEPT_USAGE (CAdditivePrimitiveComputer< T >) inline
Definition at line 106 of file CAdditivePrimitiveComputer.h.
     {
       ConceptUtils::sameType( myBool, myX.extend( myIt, myIt ) );
       checkConstConstraints();
     }
References DGtal::concepts::CAdditivePrimitiveComputer< T >::checkConstConstraints(), DGtal::concepts::CAdditivePrimitiveComputer< T >::myBool, DGtal::concepts::CAdditivePrimitiveComputer< T >::myIt, DGtal::concepts::CAdditivePrimitiveComputer< T >::myX, and DGtal::concepts::ConceptUtils::sameType().
checkConstConstraints()
template<typename T > void DGtal::concepts::CAdditivePrimitiveComputer< T >::checkConstConstraints () const inline
Definition at line 111 of file CAdditivePrimitiveComputer.h.
     {
       ConceptUtils::sameType( myBool, myX.isExtendable( myIt, myIt ) );
     }
References DGtal::concepts::CAdditivePrimitiveComputer< T >::myBool, DGtal::concepts::CAdditivePrimitiveComputer< T >::myIt, DGtal::concepts::CAdditivePrimitiveComputer< T >::myX, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::concepts::CAdditivePrimitiveComputer< T >::BOOST_CONCEPT_USAGE().
Field Documentation
myBool
template<typename T > bool DGtal::concepts::CAdditivePrimitiveComputer< T >::myBool private
Definition at line 118 of file CAdditivePrimitiveComputer.h.
Referenced by DGtal::concepts::CAdditivePrimitiveComputer< T >::BOOST_CONCEPT_USAGE(), and DGtal::concepts::CAdditivePrimitiveComputer< T >::checkConstConstraints().
myIt
template<typename T > CForwardIteratorArchetype<Point> DGtal::concepts::CAdditivePrimitiveComputer< T >::myIt private
Definition at line 119 of file CAdditivePrimitiveComputer.h.
Referenced by DGtal::concepts::CAdditivePrimitiveComputer< T >::BOOST_CONCEPT_USAGE(), and DGtal::concepts::CAdditivePrimitiveComputer< T >::checkConstConstraints().
myX
template<typename T > T DGtal::concepts::CAdditivePrimitiveComputer< T >::myX private
Definition at line 117 of file CAdditivePrimitiveComputer.h.
Referenced by DGtal::concepts::CAdditivePrimitiveComputer< T >::BOOST_CONCEPT_USAGE(), and DGtal::concepts::CAdditivePrimitiveComputer< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CAdditivePrimitiveComputer.h