DGtal: DGtal::concepts::CUndirectedSimpleGraph< T > Struct Template Reference
DGtal::concepts::CUndirectedSimpleGraph< T > Struct Template Reference
DGtal Concepts
Aim: Represents the concept of local graph: each vertex has neighboring vertices, but we do not necessarily know all the vertices.
#include <DGtal/graph/CUndirectedSimpleGraph.h>
Public Types
typedef T::Edge Edge
typedef T::Size Size
Public Types inherited from DGtal::concepts::CUndirectedSimpleLocalGraph< T >
typedef T::Vertex Vertex
typedef T::Size Size
typedef T::VertexSet VertexSet
Public Types inherited from DGtal::concepts::CConstSinglePassRange< T >
typedef T::ConstIterator ConstIterator
Public Member Functions
BOOST_CONCEPT_USAGE (CUndirectedSimpleGraph)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::concepts::CUndirectedSimpleLocalGraph< T >
BOOST_CONCEPT_ASSERT ((CIntegralNumber< Size >))
BOOST_CONCEPT_ASSERT ((boost::DefaultConstructible< Vertex >))
BOOST_CONCEPT_ASSERT ((boost::Assignable< Vertex >))
BOOST_CONCEPT_ASSERT ((boost::CopyConstructible< Vertex >))
BOOST_CONCEPT_USAGE (CUndirectedSimpleLocalGraph)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::concepts::CConstSinglePassRange< T >
BOOST_CONCEPT_ASSERT ((boost_concepts::SinglePassIteratorConcept< ConstIterator >))
BOOST_CONCEPT_USAGE (CConstSinglePassRange)
void checkConstConstraints () const
Private Attributes
T myX
Size mySize
Detailed Description
template<typename T>
struct DGtal::concepts::CUndirectedSimpleGraph< T >
Aim: Represents the concept of local graph: each vertex has neighboring vertices, but we do not necessarily know all the vertices.
Description of concept 'CUndirectedSimpleGraph'
Refinement of
CUndirectedSimpleLocalGraph, CSinglePassConstRange
Associated types
Edge: the type for the edges of the graph.
The following types are defined in CSinglePassConstRange
ConstIterator: const iterator on Vertex
The following types are defined in CUndirectedSimpleLocalGraph
Size: an integral type to count the number of vertices.
Vertex: the type for the vertices of the graph.
VertexSet: the type for storing a set of vertices.
VertexMap: a rebinding structure to associate Value to vertices of model CVertexMap.
Notation
X : A type that is a model of CUndirectedSimpleGraph
x : object of type X
v : object of type Vertex
out : an output iterator of type OutputIterator (model of boost::OutputIterator).
p : a predicate on vertex of type VertexPredicate (model of CVertexPredicate).
Definitions
Valid expressions and
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
Size x.size() Size Returns the number of vertices of this graph
Invariants
Models
DigitalSurface, Object, IndexedDigitalSurface
Notes
Template Parameters
T the type that should be a model of CUndirectedSimpleGraph.
Examples
graph/graphTraversal.cpp.
Definition at line 102 of file CUndirectedSimpleGraph.h.
Member Typedef Documentation
Edge
template<typename T > typedef T::Edge DGtal::concepts::CUndirectedSimpleGraph< T >::Edge
Definition at line 109 of file CUndirectedSimpleGraph.h.
Size
template<typename T > typedef T::Size DGtal::concepts::CUndirectedSimpleGraph< T >::Size
Definition at line 110 of file CUndirectedSimpleGraph.h.
Member Function Documentation
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CUndirectedSimpleGraph< T >::BOOST_CONCEPT_USAGE (CUndirectedSimpleGraph< T >) inline
Definition at line 113 of file CUndirectedSimpleGraph.h.
     {
       // check const methods.
       checkConstConstraints();
     }
References DGtal::concepts::CUndirectedSimpleGraph< T >::checkConstConstraints().
checkConstConstraints()
template<typename T > void DGtal::concepts::CUndirectedSimpleGraph< T >::checkConstConstraints () const inline
Definition at line 118 of file CUndirectedSimpleGraph.h.
     {
       ConceptUtils::sameType( mySize, myX.size() );
     }
References DGtal::concepts::CUndirectedSimpleGraph< T >::mySize, DGtal::concepts::CUndirectedSimpleGraph< T >::myX, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::concepts::CUndirectedSimpleGraph< T >::BOOST_CONCEPT_USAGE().
Field Documentation
mySize
template<typename T > Size DGtal::concepts::CUndirectedSimpleGraph< T >::mySize private
Definition at line 126 of file CUndirectedSimpleGraph.h.
Referenced by DGtal::concepts::CUndirectedSimpleGraph< T >::checkConstConstraints().
myX
template<typename T > T DGtal::concepts::CUndirectedSimpleGraph< T >::myX private
Definition at line 125 of file CUndirectedSimpleGraph.h.
Referenced by DGtal::concepts::CUndirectedSimpleGraph< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CUndirectedSimpleGraph.h