DGtal: DGtal::concepts::CCellEmbedder< T > Struct Template Reference
DGtal::concepts::CCellEmbedder< T > Struct Template Reference
DGtal Concepts
Aim: A cell embedder is a mapping from unsigned cells to Euclidean points. It adds inner types to functor.
#include <DGtal/topology/CCellEmbedder.h>
Public Types
typedef T::KSpace KSpace
typedef T::Cell Cell
typedef T::RealPoint RealPoint
typedef T::Argument Argument
typedef T::Value Value
Public Member Functions
BOOST_CONCEPT_ASSERT ((CCellularGridSpaceND< KSpace >))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Cell, typename KSpace::Cell >::value))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Cell, Argument >::value))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< RealPoint, Value >::value))
BOOST_CONCEPT_USAGE (CCellEmbedder)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::concepts::CUnaryFunctor< T, T::Cell, T::RealPoint >
BOOST_CONCEPT_USAGE (CUnaryFunctor)
Private Attributes
T myX
Cell myP
RealPoint myRP
Detailed Description
template<typename T>
struct DGtal::concepts::CCellEmbedder< T >
Aim: A cell embedder is a mapping from unsigned cells to Euclidean points. It adds inner types to functor.
Description of concept 'CCellEmbedder'
Refinement of
CUnaryFunctor<T, T::Cell, T::RealPoint>
Associated types
KSpace: the cellular grid space
Cell: same as KSpace::Cell
RealPoint: the type of Euclidean point
Argument: type of the argument, same as KSpace::Cell
Value: type of value, same as RealPoint
Notation
X : A type that is a model of CCellEmbedder
x : object of type X
p : object of type Cell
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
Apply function x(p) Value return the value of the function x on argument p
Invariants
Models
CanonicCellEmbedder, ImageLinearCellEmbedder, ImplicitFunctionLinearCellEmbedder, ImplicitFunctionDiff1LinearCellEmbedder
Notes
Template Parameters
T the type that should be a model of CCellEmbedder.
Definition at line 96 of file CCellEmbedder.h.
Member Typedef Documentation
Argument
template<typename T > typedef T::Argument DGtal::concepts::CCellEmbedder< T >::Argument
Definition at line 103 of file CCellEmbedder.h.
Cell
template<typename T > typedef T::Cell DGtal::concepts::CCellEmbedder< T >::Cell
Definition at line 101 of file CCellEmbedder.h.
KSpace
template<typename T > typedef T::KSpace DGtal::concepts::CCellEmbedder< T >::KSpace
Definition at line 100 of file CCellEmbedder.h.
RealPoint
template<typename T > typedef T::RealPoint DGtal::concepts::CCellEmbedder< T >::RealPoint
Definition at line 102 of file CCellEmbedder.h.
Value
template<typename T > typedef T::Value DGtal::concepts::CCellEmbedder< T >::Value
Definition at line 104 of file CCellEmbedder.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename T > DGtal::concepts::CCellEmbedder< T >::BOOST_CONCEPT_ASSERT ((CCellularGridSpaceND< KSpace >))
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CCellEmbedder< T >::BOOST_CONCEPT_USAGE (CCellEmbedder< T >) inline
Definition at line 110 of file CCellEmbedder.h.
   {
     checkConstConstraints();
   }
References DGtal::concepts::CCellEmbedder< T >::checkConstConstraints().
BOOST_STATIC_ASSERT() [1/3]
template<typename T > DGtal::concepts::CCellEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Cell, Argument >::value))
BOOST_STATIC_ASSERT() [2/3]
template<typename T > DGtal::concepts::CCellEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< Cell, typename KSpace::Cell >::value))
BOOST_STATIC_ASSERT() [3/3]
template<typename T > DGtal::concepts::CCellEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< RealPoint, Value >::value))
checkConstConstraints()
template<typename T > void DGtal::concepts::CCellEmbedder< T >::checkConstConstraints () const inline
Definition at line 115 of file CCellEmbedder.h.
   { // operator()
     ConceptUtils::sameType( myRP, myX( myP ) );
   }
References DGtal::concepts::CCellEmbedder< T >::myP, DGtal::concepts::CCellEmbedder< T >::myRP, DGtal::concepts::CCellEmbedder< T >::myX, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::concepts::CCellEmbedder< T >::BOOST_CONCEPT_USAGE().
Field Documentation
myP
template<typename T > Cell DGtal::concepts::CCellEmbedder< T >::myP private
Definition at line 122 of file CCellEmbedder.h.
Referenced by DGtal::concepts::CCellEmbedder< T >::checkConstConstraints().
myRP
template<typename T > RealPoint DGtal::concepts::CCellEmbedder< T >::myRP private
Definition at line 123 of file CCellEmbedder.h.
Referenced by DGtal::concepts::CCellEmbedder< T >::checkConstConstraints().
myX
template<typename T > T DGtal::concepts::CCellEmbedder< T >::myX private
Definition at line 121 of file CCellEmbedder.h.
Referenced by DGtal::concepts::CCellEmbedder< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CCellEmbedder.h