DGtal: LibBoard::Path Struct Reference
LibBoard::Path Struct Reference
A path, according to Postscript and SVG definition.
#include <Board/Path.h>
Public Member Functions
Path ()
Path (const std::vector< Point > &points, bool closedPath)
Path (bool closedPath)
void clear ()
bool closed () const
bool empty () const
unsigned int size () const
void setClosed (bool closed)
Point center () const
Path & operator<< (const Point &p)
Path & pop_back ()
Point & operator[] (const unsigned int n)
const Point & operator[] (const unsigned int n) const
Path & rotate (double angle, const Point &center)
Path rotated (double angle, const Point &center) const
Path & rotate (double angle)
Path rotated (double angle) const
Path & translate (double dx, double dy)
Path translated (double dx, double dy) const
Path & scale (double sx, double sy)
Path & scale (double s)
Path scaled (double sx, double sy) const
Path scaled (double s) const
void scaleAll (double s)
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
void flushFIG (std::ostream &stream, const TransformFIG &transform) const
void flushSVGPoints (std::ostream &stream, const TransformSVG &transform) const
void flushSVGCommands (std::ostream &stream, const TransformSVG &transform) const
void flushCairoPoints (cairo_t *cr, const TransformCairo &transform) const
void flushTikZPoints (std::ostream &stream, const TransformTikZ &transform) const
Rect boundingBox () const
Protected Attributes
std::vector< Point > _points
bool _closed
Detailed Description
A path, according to Postscript and SVG definition.
The path structure.
Definition at line 43 of file Path.h.
Constructor & Destructor Documentation
Path() [1/3]
LibBoard::Path::Path () inline
Definition at line 45 of file Path.h.
 : _closed( false ) { }
Referenced by scaled().
Path() [2/3]
LibBoard::Path::Path (const std::vector< Point > & points, bool closedPath) inline
Definition at line 47 of file Path.h.
     : _points( points ), _closed( closedPath ) { }
Path() [3/3]
LibBoard::Path::Path (bool closedPath) inline
Definition at line 50 of file Path.h.
 : _closed( closedPath ) { }
Member Function Documentation
boundingBox()
Rect LibBoard::Path::boundingBox () const
Definition at line 272 of file Path.cpp.
 {
   if ( _points.empty() )
     return Rect( 0, 0, 0, 0 );
   Rect rect;
   std::vector< Point >::const_iterator i = _points.begin();
   std::vector< Point >::const_iterator end = _points.end();
   rect.top = i->y;
   rect.left = i->x;
   rect.width = 0.0;
   rect.height = 0.0;
   ++i;
   while ( i != end ) {
     if ( i->x < rect.left ) {
       double dw = rect.left - i->x;
       rect.left = i->x;
       rect.width += dw;
     } else if ( i->x > rect.left + rect.width ) {
       rect.width = i->x - rect.left;
     }
     if ( i->y > rect.top ) {
       double dh = i->y - rect.top;
       rect.top = i->y;
       rect.height += dh;
     } else if ( i->y < rect.top - rect.height ) {
       rect.height = rect.top - i->y;
     }
     ++i;
   }
   return rect;
 }
References _points, LibBoard::Rect::height, LibBoard::Rect::left, LibBoard::Rect::top, and LibBoard::Rect::width.
Referenced by LibBoard::Group::boundingBox(), LibBoard::Polyline::boundingBox(), center(), LibBoard::Board::saveCairo(), LibBoard::Board::saveEPS(), LibBoard::Board::saveSVG(), and LibBoard::Board::saveTikZ().
center()
Point LibBoard::Path::center () const
Barycenter of the path
Returns
a point
Definition at line 36 of file Path.cpp.
                    {
   Rect bbox = boundingBox();
   return Point( bbox.left + bbox.width/2.0,
     bbox.top  - bbox.height/2.0 );
 }
References boundingBox(), LibBoard::Rect::height, LibBoard::Rect::left, LibBoard::Rect::top, and LibBoard::Rect::width.
Referenced by LibBoard::Polyline::center(), rotate(), rotated(), LibBoard::Board::scale(), scale(), and LibBoard::Group::scale().
clear()
void LibBoard::Path::clear () inline
Definition at line 231 of file Path.h.
 {
   _points.clear();
 }
References _points.
Referenced by LibBoard::Board::setClippingPath(), LibBoard::Group::setClippingPath(), LibBoard::Board::setClippingRectangle(), and LibBoard::Group::setClippingRectangle().
closed()
bool LibBoard::Path::closed () const inline
Definition at line 237 of file Path.h.
 {
   return _closed;
 }
References _closed.
Referenced by LibBoard::Polyline::flushCairo(), LibBoard::Polyline::flushFIG(), LibBoard::Polyline::flushSVG(), and LibBoard::Polyline::flushTikZ().
empty()
bool LibBoard::Path::empty () const inline
Definition at line 243 of file Path.h.
 {
   return _points.empty();
 }
References _points.
Referenced by LibBoard::Polyline::flushCairo(), LibBoard::Polyline::flushFIG(), LibBoard::Polyline::flushPostscript(), LibBoard::Polyline::flushSVG(), and LibBoard::Polyline::flushTikZ().
flushCairoPoints()
void LibBoard::Path::flushCairoPoints (cairo_t * cr, const TransformCairo & transform) const
Definition at line 235 of file Path.cpp.
 {
   if ( _points.empty() )
     return;
   std::vector<Point>::const_iterator i = _points.begin();
   std::vector<Point>::const_iterator end = _points.end();
   int count = 0;
   cairo_move_to (cr, transform.mapX( i->x ), transform.mapY( i->y ));
   ++i;
   while ( i != end ) {
     cairo_line_to (cr, transform.mapX( i->x ), transform.mapY( i->y ));
     ++i;
     count = ( count + 1 ) % 6;
     //if ( !count ) stream << "\n                  ";
   }
 }
References _points.
Referenced by LibBoard::Polyline::flushCairo().
flushFIG()
void LibBoard::Path::flushFIG (std::ostream & stream, const TransformFIG & transform) const
Definition at line 173 of file Path.cpp.
 {
   if ( _points.empty() )
     return;
   std::vector<Point>::const_iterator i = _points.begin();
   std::vector<Point>::const_iterator end = _points.end();
   while ( i != end ) {
     stream << " " << static_cast<int>( transform.mapX( i->x ) )
      << " " << static_cast<int>( transform.mapY( i->y ) );
     ++i;
   }
   if ( _closed ) {
     stream << " " << static_cast<int>( transform.mapX( _points.begin()->x ) )
      << " " << static_cast<int>( transform.mapY( _points.begin()->y ) );
   }
 }
References _closed, and _points.
Referenced by LibBoard::Polyline::flushFIG(), LibBoard::Rectangle::flushFIG(), and LibBoard::Image::flushFIG().
flushPostscript()
void LibBoard::Path::flushPostscript (std::ostream & stream, const TransformEPS & transform) const
Definition at line 154 of file Path.cpp.
 {
   if ( _points.empty() )
     return;
   std::vector<Point>::const_iterator i = _points.begin();
   std::vector<Point>::const_iterator end = _points.end();
   stream << transform.mapX( i->x ) << " " << transform.mapY( i->y ) << " m";
   ++i;
   while ( i != end ) {
     stream << " " << transform.mapX( i->x ) << " " << transform.mapY( i->y ) << " l";
     ++i;
   }
   if ( _closed ) stream << " cp";
   stream << " ";
 }
References _closed, and _points.
Referenced by LibBoard::Group::flushPostscript(), LibBoard::Polyline::flushPostscript(), and LibBoard::Board::saveEPS().
flushSVGCommands()
void LibBoard::Path::flushSVGCommands (std::ostream & stream, const TransformSVG & transform) const
Definition at line 193 of file Path.cpp.
 {
   if ( _points.empty() )
     return;
   std::vector<Point>::const_iterator i = _points.begin();
   std::vector<Point>::const_iterator end = _points.end();
   int count = 0;
   stream << "M " << transform.mapX( i->x ) << " " << transform.mapY( i->y );
   ++i;
   while ( i != end ) {
     stream << " L " << transform.mapX( i->x ) << " " << transform.mapY( i->y );
     ++i;
     count = ( count + 1 ) % 6;
     if ( !count ) stream << "\n                  ";
   }
   if ( _closed )
     stream << " Z" << std::endl;
 }
References _closed, and _points.
Referenced by LibBoard::Group::flushSVG(), LibBoard::Board::saveSVG(), and LibBoard::Board::saveTikZ().
flushSVGPoints()
void LibBoard::Path::flushSVGPoints (std::ostream & stream, const TransformSVG & transform) const
Definition at line 215 of file Path.cpp.
 {
   if ( _points.empty() )
     return;
   std::vector<Point>::const_iterator i = _points.begin();
   std::vector<Point>::const_iterator end = _points.end();
   int count = 0;
   stream << transform.mapX( i->x ) << "," << transform.mapY( i->y );
   ++i;
   while ( i != end ) {
     stream << " " << transform.mapX( i->x ) << "," << transform.mapY( i->y );
     ++i;
     count = ( count + 1 ) % 6;
     if ( !count ) stream << "\n                  ";
   }
 }
References _points.
Referenced by LibBoard::Polyline::flushSVG().
flushTikZPoints()
void LibBoard::Path::flushTikZPoints (std::ostream & stream, const TransformTikZ & transform) const
Definition at line 255 of file Path.cpp.
 {
   if ( _points.empty() )
     return;
   std::vector<Point>::const_iterator i = _points.begin();
   std::vector<Point>::const_iterator end = _points.end();
   stream << '(' << transform.mapX( i->x ) << "," << transform.mapY( i->y ) << ')';
   ++i;
   while ( i != end ) {
     stream << " -- "
     << '(' << transform.mapX( i->x ) << "," << transform.mapY( i->y ) << ')';
     ++i;
   }
 }
References _points.
Referenced by LibBoard::Polyline::flushTikZ().
operator<<()
Path & LibBoard::Path::operator<< (const Point & p)
Add a point at the end of the path.
Parameters
p the point to add
Returns
a path
Definition at line 28 of file Path.cpp.
 {
   _points.push_back( p );
   return *this;
 }
References _points.
operator[]() [1/2]
Point& LibBoard::Path::operator[] (const unsigned int n) inline
Returns the n-th point of the polyline.
Parameters
n n
Returns
a point
Definition at line 92 of file Path.h.
{
     return _points[ n ];
   }
References _points.
operator[]() [2/2]
const Point& LibBoard::Path::operator[] (const unsigned int n) const inline
Returns the n-th point of the polyline.
Parameters
n n
Returns
a point
Definition at line 103 of file Path.h.
{
     return _points[ n ];
   }
References _points.
pop_back()
Path & LibBoard::Path::pop_back ()
Returns
path
Definition at line 22 of file Path.cpp.
 {
   _points.pop_back();
   return *this;
 }
References _points.
Referenced by LibBoard::Board::setClippingPath(), and LibBoard::Group::setClippingPath().
rotate() [1/2]
Path & LibBoard::Path::rotate (double angle)
Parameters
angle angle
Returns
a Path
Definition at line 68 of file Path.cpp.
 {
   return Path::rotate( angle, center() );
 }
References center(), and rotate().
rotate() [2/2]
Path & LibBoard::Path::rotate (double angle, const Point & center)
Parameters
angle angle
center center
Returns
a path
Definition at line 43 of file Path.cpp.
 {
   std::vector<Point>::iterator i = _points.begin();
   std::vector<Point>::iterator end = _points.end();
   while ( i != end ) {
     i->rotate( angle, rotCenter );
     ++i;
   }
   return *this;
 }
References _points.
Referenced by rotate(), LibBoard::Board::rotate(), LibBoard::Group::rotate(), LibBoard::Polyline::rotate(), and LibBoard::GouraudTriangle::rotate().
rotated() [1/2]
Path LibBoard::Path::rotated (double angle) const
Parameters
angle angle
Returns
rotated path
Definition at line 74 of file Path.cpp.
 {
   Path res(*this);
   return static_cast<Path&>( res.rotate( angle, center() ) );
 }
References center().
rotated() [2/2]
Path LibBoard::Path::rotated (double angle, const Point & center) const
Parameters
angle angle
center center
Returns
a Path
Definition at line 55 of file Path.cpp.
 {
   Path res(*this);
   std::vector<Point>::iterator i = res._points.begin();
   std::vector<Point>::iterator end = res._points.end();
   while ( i != end ) {
     i->rotate( angle, rotCenter );
     ++i;
   }
   return res;
 }
scale() [1/2]
Path & LibBoard::Path::scale (double s)
Parameters
s scale factor
Returns
scaled path
Definition at line 125 of file Path.cpp.
 {
   return Path::scale( s, s );
 }
References scale().
scale() [2/2]
Path & LibBoard::Path::scale (double sx, double sy)
Parameters
sx scale factor
sy scale factor
Returns
scaled path
Definition at line 108 of file Path.cpp.
 {
   Point c = center();
   translate( -c.x, -c.y );
   std::vector<Point>::iterator i = _points.begin();
   std::vector<Point>::iterator end = _points.end();
   while ( i != end ) {
     i->x *= sx;
     i->y *= sy;
     ++i;
   }
   Point delta = c - center();
   translate( delta.x, delta.y );
   return *this;
 }
References _points, center(), translate(), LibBoard::Point::x, and LibBoard::Point::y.
Referenced by scale(), LibBoard::Board::scale(), LibBoard::Group::scale(), and LibBoard::Polyline::scale().
scaleAll()
void LibBoard::Path::scaleAll (double s)
Scales all the points.
Parameters
s The scaling factor.
Definition at line 143 of file Path.cpp.
 {
   std::vector<Point>::iterator it = _points.begin();
   std::vector<Point>::iterator end = _points.end();
   while ( it != end ) {
     (*it) *= s;
     ++it;
   }
 }
References _points.
Referenced by LibBoard::Polyline::scaleAll(), LibBoard::Rectangle::scaleAll(), and LibBoard::GouraudTriangle::scaleAll().
scaled() [1/2]
Path LibBoard::Path::scaled (double s) const
Definition at line 137 of file Path.cpp.
 {
   return Path(*this).scale( s, s );
 }
References Path().
scaled() [2/2]
Path LibBoard::Path::scaled (double sx, double sy) const
Parameters
sx scale factor
sy scale factor
Returns
a Path
Definition at line 131 of file Path.cpp.
 {
   return Path(*this).scale( sx, sy );
 }
References Path().
setClosed()
void LibBoard::Path::setClosed (bool closed) inline
Definition at line 255 of file Path.h.
 {
   _closed = closedPath;
 }
References _closed.
Referenced by LibBoard::Board::setClippingPath(), and LibBoard::Group::setClippingPath().
size()
unsigned int LibBoard::Path::size () const inline
Definition at line 249 of file Path.h.
 {
   return (unsigned int)_points.size();
 }
References _points.
Referenced by LibBoard::Group::boundingBox(), LibBoard::Polyline::flushFIG(), LibBoard::Group::flushPostscript(), LibBoard::Group::flushSVG(), LibBoard::Board::saveCairo(), LibBoard::Board::saveEPS(), LibBoard::Board::saveSVG(), LibBoard::Board::saveTikZ(), LibBoard::Board::setClippingPath(), and LibBoard::Group::setClippingPath().
translate()
Path & LibBoard::Path::translate (double dx, double dy)
Parameters
dx translation vector
dy translation vector
Returns
translated path
Definition at line 81 of file Path.cpp.
 {
   std::vector<Point>::iterator i = _points.begin();
   std::vector<Point>::iterator end = _points.end();
   Point delta( dx, dy );
   while ( i != end ) {
     (*i) += delta;
     ++i;
   }
   return *this;
 }
References _points.
Referenced by LibBoard::Board::scale(), scale(), LibBoard::Group::scale(), LibBoard::Board::translate(), LibBoard::Group::translate(), and LibBoard::Polyline::translate().
translated()
Path LibBoard::Path::translated (double dx, double dy) const
Parameters
dx translation vector
dy translation vector
Returns
a Path
Definition at line 94 of file Path.cpp.
 {
   Path res(*this);
   std::vector<Point>::iterator i = res._points.begin();
   std::vector<Point>::iterator end = res._points.end();
   Point delta( dx, dy );
   while ( i != end ) {
     (*i) += delta;
     ++i;
   }
   return res;
 }
Field Documentation
_closed
bool LibBoard::Path::_closed protected
Definition at line 227 of file Path.h.
Referenced by closed(), flushFIG(), flushPostscript(), flushSVGCommands(), and setClosed().
_points
std::vector<Point> LibBoard::Path::_points protected
Definition at line 226 of file Path.h.
Referenced by boundingBox(), clear(), empty(), flushCairoPoints(), flushFIG(), flushPostscript(), flushSVGCommands(), flushSVGPoints(), flushTikZPoints(), operator<<(), operator[](), pop_back(), rotate(), scale(), scaleAll(), size(), and translate().
The documentation for this struct was generated from the following files:
Path.h
Path.cpp