DGtal: DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData > Struct Template Reference
DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData > Struct Template Reference
#include <DGtal/topology/IndexedDigitalSurface.h>
Public Types
typedef Index Argument
typedef TData Data
typedef std::vector< Data > Storage
Public Member Functions
IndexedPropertyMap ()
Default constructor. The object is invalid.
IndexedPropertyMap (const Self &aSurface, Size s, Data def_data=Data())
IndexedPropertyMap (const Self &aSurface, Storage &aStorage)
const Self & surface () const
const Data & operator() (Argument v) const
const Data & operator[] (Argument v) const
Data & operator[] (Argument v)
bool isValid () const
Size size () const
Storage & storage ()
const Storage & storage () const
Private Attributes
const Self * mySurface
The associated indexed digital surface.
OwningOrAliasingPtr< Storage > myData
An owned or aliased pointer to the vector of data.
Detailed Description
template<typename TDigitalSurfaceContainer>
template<typename TData>
struct DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >
This structure is used to define efficient maps between vertices and any data specified by type TData. The indexed digital surface provides a default vertex map for vertex positions.
Template Parameters
TData the value type for the map.
See also
positions
makeVertexMap
Note
This property map uses a vector structure as storage.
Definition at line 149 of file IndexedDigitalSurface.h.
Member Typedef Documentation
Argument
template<typename TDigitalSurfaceContainer > template<typename TData > typedef Index DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::Argument
Definition at line 150 of file IndexedDigitalSurface.h.
Data
template<typename TDigitalSurfaceContainer > template<typename TData > typedef TData DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::Data
Definition at line 151 of file IndexedDigitalSurface.h.
Storage
template<typename TDigitalSurfaceContainer > template<typename TData > typedef std::vector<Data> DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::Storage
Definition at line 152 of file IndexedDigitalSurface.h.
Constructor & Destructor Documentation
IndexedPropertyMap() [1/3]
template<typename TDigitalSurfaceContainer > template<typename TData > DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::IndexedPropertyMap () inline
Default constructor. The object is invalid.
Definition at line 155 of file IndexedDigitalSurface.h.
 : mySurface( 0 ), myData( 0 ) {}
IndexedPropertyMap() [2/3]
template<typename TDigitalSurfaceContainer > template<typename TData > DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::IndexedPropertyMap (const Self & aSurface, Size s, Data def_data = Data()) inline
Creates an empty vertex property map
Parameters
aSurface the corresponding indexed digital surface.
s one more than the maximal allowed index (i.e. nb of elements).
def_data the default value at initialization.
Definition at line 161 of file IndexedDigitalSurface.h.
         : mySurface( &aSurface ),
           myData( Storage( s, def_data ) )
       {}
IndexedPropertyMap() [3/3]
template<typename TDigitalSurfaceContainer > template<typename TData > DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::IndexedPropertyMap (const Self & aSurface, Storage & aStorage) inline
Creates the IndexedPropertyMap that points to one that exists already.
Parameters
aSurface the corresponding indexed digital surface.
aStorage the map to reference in this property map.
Note
This method is used to give to a user the map vertex -> position that is stored within the indexed digital surface.
Definition at line 173 of file IndexedDigitalSurface.h.
         : mySurface( &aSurface ),
           myData( &aStorage, false )
       {}
Member Function Documentation
isValid()
template<typename TDigitalSurfaceContainer > template<typename TData > bool DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::isValid () const inline
Returns
if the object was properly initialized.
Definition at line 214 of file IndexedDigitalSurface.h.
 { return mySurface != 0; }
References DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::mySurface.
Referenced by DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::operator()(), DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::operator[](), and DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::surface().
operator()()
template<typename TDigitalSurfaceContainer > template<typename TData > const Data& DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::operator() (Argument v) const inline
This object is a function : Argument -> Data
Parameters
v any index
Returns
the associated data
Definition at line 189 of file IndexedDigitalSurface.h.
       {
         ASSERT( isValid() && v < myData->size() );
         return (*myData)[ v ];
       }
References DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::isValid(), DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::myData, and DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::size().
operator[]() [1/2]
template<typename TDigitalSurfaceContainer > template<typename TData > Data& DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::operator[] (Argument v) inline
mutable array access.
Parameters
v any index
Returns
the associated data
Definition at line 207 of file IndexedDigitalSurface.h.
       {
         ASSERT( isValid() && v < myData->size() );
         return (*myData)[ v ];
       }
References DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::isValid(), DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::myData, and DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::size().
operator[]() [2/2]
template<typename TDigitalSurfaceContainer > template<typename TData > const Data& DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::operator[] (Argument v) const inline
Non-mutable array access.
Parameters
v any index
Returns
the associated data
Definition at line 198 of file IndexedDigitalSurface.h.
       {
         ASSERT( isValid() && v < myData->size() );
         return (*myData)[ v ];
       }
References DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::isValid(), DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::myData, and DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::size().
size()
template<typename TDigitalSurfaceContainer > template<typename TData > Size DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::size () const inline
Returns
the size of the indexed map (i.e., size of associated vector).
Definition at line 217 of file IndexedDigitalSurface.h.
 { return myData->size(); }
References DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::myData.
Referenced by DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::operator()(), and DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::operator[]().
storage() [1/2]
template<typename TDigitalSurfaceContainer > template<typename TData > Storage& DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::storage () inline
Returns
a reference to the storage class (a vector of Data).
Definition at line 220 of file IndexedDigitalSurface.h.
 { return *myData; }
References DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::myData.
storage() [2/2]
template<typename TDigitalSurfaceContainer > template<typename TData > const Storage& DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::storage () const inline
Returns
a const reference to the storage class (a vector of Data).
Definition at line 223 of file IndexedDigitalSurface.h.
 { return *myData; }
References DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::myData.
surface()
template<typename TDigitalSurfaceContainer > template<typename TData > const Self& DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::surface () const inline
Returns
the associated indexed digital surface.
Definition at line 180 of file IndexedDigitalSurface.h.
       {
         ASSERT( isValid() );
         return *mySurface;
       }
References DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::isValid(), and DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::mySurface.
Field Documentation
myData
template<typename TDigitalSurfaceContainer > template<typename TData > OwningOrAliasingPtr<Storage> DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::myData private
An owned or aliased pointer to the vector of data.
Definition at line 229 of file IndexedDigitalSurface.h.
Referenced by DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::operator()(), DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::operator[](), DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::size(), and DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::storage().
mySurface
template<typename TDigitalSurfaceContainer > template<typename TData > const Self* DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::mySurface private
The associated indexed digital surface.
Definition at line 227 of file IndexedDigitalSurface.h.
Referenced by DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::isValid(), and DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::IndexedPropertyMap< TData >::surface().
The documentation for this struct was generated from the following file:
IndexedDigitalSurface.h