DGtal: DGtal::concepts::CWithGradientMap< T > Struct Template Reference
DGtal::concepts::CWithGradientMap< T > Struct Template Reference
DGtal Concepts
Aim: Such object provides a gradient map that associates to each argument some real vector.
#include <DGtal/kernel/CWithGradientMap.h>
Public Types
typedef T::Argument Argument
typedef T::RealVector RealVector
typedef T::GradientMap GradientMap
Public Member Functions
BOOST_CONCEPT_ASSERT ((boost::CopyConstructible< GradientMap >))
BOOST_CONCEPT_ASSERT ((CUnaryFunctor< GradientMap, Argument, RealVector >))
BOOST_CONCEPT_USAGE (CWithGradientMap)
void checkConstConstraints () const
Private Attributes
T myX
GradientMap myGMap
Detailed Description
template<typename T>
struct DGtal::concepts::CWithGradientMap< T >
Aim: Such object provides a gradient map that associates to each argument some real vector.
Description of concept 'CWithGradientMap'
Refinement of
Associated types
Argument : the type of each element of the domain
RealVector : the type for representing the gradient values.
GradientMap : functor Argument -> RealVector, a model of CUnaryFunctor<T, Argument, RealVector > and boost::CopyConstructible.
gradientMap() const: returns a GradientMap.
Notation
X : A type that is a model of CWithGradientMap
x : object of type X
Definitions
Valid expressions and semantics
| Name | Expression | Type requirements | Return type | Precondition | Semantics | Post condition | Complexity | |----—|---------—|----------------—|------------—|-----------—|--------—|-------------—|---------—| | Gets the gradient map |x.gradientMap()| |GradientMap | | returns the gradient functor | | | |
Invariants
Models
ImplicitFunctionDiff1LinearCellEmbedder, DigitalSurfaceEmbedderWithNormalVectorEstimator
Notes
Template Parameters
T the type that should be a model of CWithGradientMap.
Definition at line 91 of file CWithGradientMap.h.
Member Typedef Documentation
Argument
template<typename T > typedef T::Argument DGtal::concepts::CWithGradientMap< T >::Argument
Definition at line 95 of file CWithGradientMap.h.
GradientMap
template<typename T > typedef T::GradientMap DGtal::concepts::CWithGradientMap< T >::GradientMap
Definition at line 97 of file CWithGradientMap.h.
RealVector
template<typename T > typedef T::RealVector DGtal::concepts::CWithGradientMap< T >::RealVector
Definition at line 96 of file CWithGradientMap.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT() [1/2]
template<typename T > DGtal::concepts::CWithGradientMap< T >::BOOST_CONCEPT_ASSERT ((boost::CopyConstructible< GradientMap >))
BOOST_CONCEPT_ASSERT() [2/2]
template<typename T > DGtal::concepts::CWithGradientMap< T >::BOOST_CONCEPT_ASSERT ((CUnaryFunctor< GradientMap, Argument, RealVector >))
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CWithGradientMap< T >::BOOST_CONCEPT_USAGE (CWithGradientMap< T >) inline
Definition at line 100 of file CWithGradientMap.h.
   {
     checkConstConstraints();
   }
References DGtal::concepts::CWithGradientMap< T >::checkConstConstraints().
checkConstConstraints()
template<typename T > void DGtal::concepts::CWithGradientMap< T >::checkConstConstraints () const inline
Definition at line 104 of file CWithGradientMap.h.
     {
       ConceptUtils::sameType( myGMap, myX.gradientMap() );
     }
References DGtal::concepts::CWithGradientMap< T >::myGMap, DGtal::concepts::CWithGradientMap< T >::myX, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::concepts::CWithGradientMap< T >::BOOST_CONCEPT_USAGE().
Field Documentation
myGMap
template<typename T > GradientMap DGtal::concepts::CWithGradientMap< T >::myGMap private
Definition at line 111 of file CWithGradientMap.h.
Referenced by DGtal::concepts::CWithGradientMap< T >::checkConstConstraints().
myX
template<typename T > T DGtal::concepts::CWithGradientMap< T >::myX private
Definition at line 110 of file CWithGradientMap.h.
Referenced by DGtal::concepts::CWithGradientMap< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CWithGradientMap.h