DGtal: DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor > Struct Template Reference
DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor > Struct Template Reference
#include <DGtal/graph/GraphVisitorRange.h>
Public Types
typedef GenericConstIterator< TAccessor > Self
typedef TAccessor Accessor
typedef std::input_iterator_tag iterator_category
typedef Accessor::value value_type
typedef std::ptrdiff_t difference_type
typedef Accessor::pointer pointer
typedef Accessor::reference reference
Public Member Functions
GenericConstIterator ()
GenericConstIterator (CountedPtr< GraphVisitor > ptrV)
GenericConstIterator (const Self &other)
Self & operator= (const Self &other)
reference operator* () const
pointer operator-> () const
Self & operator++ ()
Self operator++ (int)
bool operator== (const Self &other) const
bool operator!= (const Self &other) const
Data Fields
CountedPtr< GraphVisitor > myVisitor
Smart pointer to a Visitor.
Detailed Description
template<typename TGraphVisitor>
template<typename TAccessor>
struct DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >
A single-pass input iterator that adapts a visitor to explore vertices. The default iterator is equivalent to an end().
Template Parameters
TAccessor type of accessor for the iterator, either NodeAccessor or VertexAccessor.
Todo:
Complete boost::iterator_traversal<> accordingly.
Examples
tutorial-examples/AreaSurfaceEstimation-final.cpp.
Definition at line 117 of file GraphVisitorRange.h.
Member Typedef Documentation
Accessor
template<typename TGraphVisitor > template<typename TAccessor > typedef TAccessor DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::Accessor
Definition at line 120 of file GraphVisitorRange.h.
difference_type
template<typename TGraphVisitor > template<typename TAccessor > typedef std::ptrdiff_t DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::difference_type
Definition at line 125 of file GraphVisitorRange.h.
iterator_category
template<typename TGraphVisitor > template<typename TAccessor > typedef std::input_iterator_tag DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::iterator_category
Definition at line 123 of file GraphVisitorRange.h.
pointer
template<typename TGraphVisitor > template<typename TAccessor > typedef Accessor::pointer DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::pointer
Definition at line 126 of file GraphVisitorRange.h.
reference
template<typename TGraphVisitor > template<typename TAccessor > typedef Accessor::reference DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::reference
Definition at line 127 of file GraphVisitorRange.h.
Self
template<typename TGraphVisitor > template<typename TAccessor > typedef GenericConstIterator<TAccessor> DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::Self
Definition at line 119 of file GraphVisitorRange.h.
value_type
template<typename TGraphVisitor > template<typename TAccessor > typedef Accessor::value DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::value_type
Definition at line 124 of file GraphVisitorRange.h.
Constructor & Destructor Documentation
GenericConstIterator() [1/3]
template<typename TGraphVisitor > template<typename TAccessor > DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::GenericConstIterator () inline
Definition at line 133 of file GraphVisitorRange.h.
         : myVisitor( 0 ) {}
GenericConstIterator() [2/3]
template<typename TGraphVisitor > template<typename TAccessor > DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::GenericConstIterator (CountedPtr< GraphVisitor > ptrV) inline
Definition at line 136 of file GraphVisitorRange.h.
         : myVisitor( ptrV ) {}
GenericConstIterator() [3/3]
template<typename TGraphVisitor > template<typename TAccessor > DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::GenericConstIterator (const Self & other) inline
Definition at line 139 of file GraphVisitorRange.h.
         : myVisitor( other.myVisitor ) {}
Member Function Documentation
operator!=()
template<typename TGraphVisitor > template<typename TAccessor > bool DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::operator!= (const Self & other) const inline
Definition at line 197 of file GraphVisitorRange.h.
       {
         return ! ( this->operator==( other ) );
       }
References DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::operator==().
operator*()
template<typename TGraphVisitor > template<typename TAccessor > reference DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::operator* () const inline
Definition at line 152 of file GraphVisitorRange.h.
       {
         ASSERT( ( myVisitor.get() != 0 )
                 && "DGtal::GraphVisitorRange<>::GenericConstIterator<>::operator*(): you cannot dereferenced a null visitor (i.e. end()).");
         return Accessor::get( myVisitor->current() );
       }
References DGtal::CountedPtr< T >::get(), and DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::myVisitor.
operator++() [1/2]
template<typename TGraphVisitor > template<typename TAccessor > Self& DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::operator++ () inline
Definition at line 170 of file GraphVisitorRange.h.
       {
         myVisitor->expand();
         return *this;
       }
References DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::myVisitor.
operator++() [2/2]
template<typename TGraphVisitor > template<typename TAccessor > Self DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::operator++ (int) inline
Definition at line 178 of file GraphVisitorRange.h.
       {
         Self __tmp = *this;
         myVisitor->expand();
         return __tmp;
       }
References DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::myVisitor.
operator->()
template<typename TGraphVisitor > template<typename TAccessor > pointer DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::operator-> () const inline
Definition at line 161 of file GraphVisitorRange.h.
       {
         ASSERT( ( myVisitor.get() != 0 )
                 && "DGtal::GraphVisitorRange<>::GenericConstIterator<>::operator->(): you cannot dereferenced a null visitor (i.e. end()).");
         return & Accessor::get( operator*() );
       }
References DGtal::CountedPtr< T >::get(), and DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::myVisitor.
operator=()
template<typename TGraphVisitor > template<typename TAccessor > Self& DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::operator= (const Self & other) inline
Definition at line 143 of file GraphVisitorRange.h.
       {
         if ( this != &other )
           myVisitor = other.myVisitor;
         return *this;
       }
References DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::myVisitor.
operator==()
template<typename TGraphVisitor > template<typename TAccessor > bool DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::operator== (const Self & other) const inline
Definition at line 186 of file GraphVisitorRange.h.
       {
         if ( ( myVisitor.get() == 0 ) || myVisitor->finished() )
           return ( other.myVisitor.get() == 0 ) || other.myVisitor->finished();
         else if ( other.myVisitor.get() == 0 )
           return false;
         else
           return &(myVisitor->current()) == &(other.myVisitor->current());
       }
References DGtal::CountedPtr< T >::get(), and DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::myVisitor.
Referenced by DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::operator!=().
Field Documentation
myVisitor
template<typename TGraphVisitor > template<typename TAccessor > CountedPtr< GraphVisitor > DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::myVisitor
Smart pointer to a Visitor.
Definition at line 130 of file GraphVisitorRange.h.
Referenced by DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::operator*(), DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::operator++(), DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::operator->(), DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::operator=(), and DGtal::GraphVisitorRange< TGraphVisitor >::GenericConstIterator< TAccessor >::operator==().
The documentation for this struct was generated from the following file:
GraphVisitorRange.h