DGtal: LibBoard::Ellipse Struct Reference
LibBoard::Ellipse Struct Reference
An ellipse.
#include <Board/Shapes.h>
Public Member Functions
Ellipse (double x, double y, double xRadius, double yRadius, DGtal::Color pen, DGtal::Color fill, double lineWidth, const LineStyle lineStyle=SolidStyle, int depthValue=-1)
const std::string & name () const
Point center () const
Ellipse & rotate (double angle, const Point &center)
Ellipse rotated (double angle, const Point &center) const
Ellipse & rotate (double angle)
Ellipse rotated (double angle) const
Ellipse & translate (double dx, double dy)
Ellipse translated (double dx, double dy) const
Shape & scale (double sx, double sy)
Shape & scale (double s)
Ellipse scaled (double sx, double sy) const
Ellipse scaled (double s) const
void scaleAll (double s)
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
Rect boundingBox () const
Ellipse * clone () const
Public Member Functions inherited from LibBoard::Shape
Shape (DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, LineStyle style, const LineCap cap, const LineJoin join, int depth)
virtual ~Shape ()
bool filled () const
Shape & rotateDeg (double angle, const Point &center)
Shape & rotateDeg (double angle)
Rect bbox ()
Shape & operator-- ()
Shape & operator++ ()
int depth () const
virtual void depth (int)
virtual void shiftDepth (int shift)
const DGtal::Color & penColor () const
const DGtal::Color & fillColor () const
Protected Attributes
Point _center
double _xRadius
double _yRadius
double _angle
bool _circle
Protected Attributes inherited from LibBoard::Shape
int _depth
DGtal::Color _penColor
DGtal::Color _fillColor
double _lineWidth
LineStyle _lineStyle
LineCap _lineCap
LineJoin _lineJoin
Static Private Attributes
static const std::string _name
Additional Inherited Members
Public Types inherited from LibBoard::Shape
enum LineCap { ButtCap = 0, RoundCap, SquareCap }
enum LineJoin { MiterJoin = 0, RoundJoin, BevelJoin }
enum LineStyle {
SolidStyle = 0, DashStyle, DotStyle, DashDotStyle,
DashDotDotStyle, DashDotDotDotStyle
}
Protected Member Functions inherited from LibBoard::Shape
std::string svgProperties (const TransformSVG &transform) const
std::string postscriptProperties () const
void setCairoDashStyle (cairo_t *cr, LineStyle type) const
std::string tikzProperties (const TransformTikZ &transform) const
Detailed Description
An ellipse.
The ellipse structure.
Definition at line 1338 of file Board/Shapes.h.
Constructor & Destructor Documentation
Ellipse()
LibBoard::Ellipse::Ellipse (double x, double y, double xRadius, double yRadius, DGtal::Color pen, DGtal::Color fill, double lineWidth, const LineStyle lineStyle = SolidStyle, int depthValue = -1) inline
Definition at line 1340 of file Board/Shapes.h.
     : Shape( pen, fill,
        lineWidth, lineStyle, ButtCap, MiterJoin, depthValue ),
       _center( x, y ), _xRadius( xRadius ), _yRadius( yRadius ),
       _angle( 0.0 ),
       _circle( false ) {
     while ( _angle > M_PI_2 ) _angle -= M_PI;
     while ( _angle < -M_PI_2 ) _angle += M_PI;
   }
References _angle.
Referenced by clone(), rotated(), scaled(), and translated().
Member Function Documentation
boundingBox()
Rect LibBoard::Ellipse::boundingBox () const virtual
Returns the bounding box of the figure.
Returns
The rectangle of the bounding box.
Implements LibBoard::Shape.
Definition at line 1291 of file Shapes.cpp.
 {
     if ( _angle == 0.0 )
         return Rect( _center.x - _xRadius, _center.y + _yRadius,
                      2 * _xRadius, 2 * _yRadius );
     double angleXmax = -atan( (_yRadius/_xRadius)*(tan(_angle) ) );
     double angleXmin = -atan( (_yRadius/_xRadius)*(tan(_angle) ) ) + M_PI;
     double angleYmax =  atan( (_yRadius/_xRadius)*(1/tan(_angle) ) );
     double angleYmin =  M_PI + atan( (_yRadius/_xRadius)*(1/tan(_angle) ) );
     if ( _angle < 0.0 ) {
         angleYmax += M_PI;
         angleYmin -= M_PI;
     }
     return Rect( _center.x + _xRadius*cos(angleXmin)*cos(_angle) - _yRadius*sin(angleXmin)*sin(_angle),
                  _center.y + _xRadius*cos(angleYmax)*sin(_angle) + _yRadius*sin(angleYmax)*cos(_angle),
                  ( _xRadius*cos(angleXmax)*cos(_angle) - _yRadius*sin(angleXmax)*sin(_angle) ) -
                  ( _xRadius*cos(angleXmin)*cos(_angle) - _yRadius*sin(angleXmin)*sin(_angle) ),
                  ( _xRadius*cos(angleYmax)*sin(_angle) + _yRadius*sin(angleYmax)*cos(_angle) ) -
                  ( _xRadius*cos(angleYmin)*sin(_angle) + _yRadius*sin(angleYmin)*cos(_angle) ) );
 }
References _angle, _center, _xRadius, _yRadius, LibBoard::Point::x, and LibBoard::Point::y.
center()
Point LibBoard::Ellipse::center () const virtual
Returns the gravity center of the shape.
Returns
The center of the shape.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Circle.
Definition at line 1026 of file Shapes.cpp.
                       {
     return _center;
 }
References _center.
Referenced by rotate(), and rotated().
clone()
Ellipse * LibBoard::Ellipse::clone () const virtual
Return a copy of the shape.
Returns
copye of the shape.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Circle.
Definition at line 1151 of file Shapes.cpp.
                      {
     return new Ellipse(*this);
 }
References Ellipse().
flushCairo()
void LibBoard::Ellipse::flushCairo (cairo_t * cr, const TransformCairo & transform) const virtual
Writes the cairo code of the shape in a cairo drawing context according to a transform.
Parameters
cr The cairo drawing context.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Arc, and LibBoard::Circle.
Definition at line 1232 of file Shapes.cpp.
 {
   cairo_save (cr);
     cairo_set_source_rgba (cr, _fillColor.red()/255.0, _fillColor.green()/255.0, _fillColor.blue()/255.0, 1.);
     // tr
     cairo_translate (cr, transform.mapX( _center.x ), transform.mapY( _center.y ));
     if ( _angle != 0.0 )
       cairo_rotate (cr, _angle);
     cairo_scale (cr, transform.scale( _xRadius ), transform.scale( _yRadius ));
     // tr
     cairo_arc (cr, 0, 0, 1, 0, 2*M_PI);
     if ( filled() )
     {
       if ( _penColor != DGtal::Color::None )
   cairo_fill_preserve (cr);
       else
   cairo_fill (cr);
     }
     //
     if ( _penColor != DGtal::Color::None )
     {
       cairo_set_source_rgba (cr, _penColor.red()/255.0, _penColor.green()/255.0, _penColor.blue()/255.0, 1.);
       cairo_set_line_width (cr, _lineWidth);
       cairo_set_line_cap (cr, cairoLineCap[_lineCap]);
       cairo_set_line_join (cr, cairoLineJoin[_lineJoin]);
       setCairoDashStyle (cr, _lineStyle);
       cairo_stroke (cr);
     }
   cairo_restore (cr);
 }
References _angle, _center, LibBoard::Shape::_fillColor, LibBoard::Shape::_lineCap, LibBoard::Shape::_lineJoin, LibBoard::Shape::_lineStyle, LibBoard::Shape::_lineWidth, LibBoard::Shape::_penColor, _xRadius, _yRadius, DGtal::Color::blue(), LibBoard::Shape::filled(), DGtal::Color::green(), DGtal::Color::None, DGtal::Color::red(), LibBoard::Shape::setCairoDashStyle(), LibBoard::Point::x, and LibBoard::Point::y.
Referenced by LibBoard::Circle::flushCairo().
flushFIG()
void LibBoard::Ellipse::flushFIG (std::ostream & stream, const TransformFIG & transform, std::map< DGtal::Color, int > & colormap) const virtual
Writes the FIG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
colormap A colormap.
Implements LibBoard::Shape.
Definition at line 1185 of file Shapes.cpp.
 {
     // Ellipse, Sub type, Line style, Thickness
     if ( _circle )
         stream << "1 3 " << _lineStyle << " ";
     else
         stream << "1 1 " << _lineStyle << " ";
     stream << ( _penColor.valid()?transform.mapWidth( _lineWidth ):0 ) << " ";
     // Pen color, Fill color
     stream << colormap[ _penColor ] << " " << colormap[ _fillColor ] << " ";
     // Depth, Pen style, Area fill, Style val, Direction, angle
     if ( filled() )
         stream << transform.mapDepth( _depth ) << " -1 20 " << (_lineStyle?"4.000 ":"0.000 ") << "  1 " << _angle << " ";
     else
         stream << transform.mapDepth( _depth ) << " -1 -1 " << (_lineStyle?"4.000 ":"0.000 ") << " 1 " << _angle << " ";
     stream << static_cast<int>( transform.mapX( _center.x ) ) << " "
     << static_cast<int>( transform.mapY( _center.y ) ) << " "
     << static_cast<int>( transform.scale( _xRadius ) ) << " "
     << static_cast<int>( transform.scale( _yRadius ) ) << " "
     << static_cast<int>( transform.mapX( _center.x ) ) << " "
     << static_cast<int>( transform.mapY( _center.y ) ) << " "
     << static_cast<int>( transform.mapX( _center.x ) + transform.scale( _xRadius ) ) << " "
     << static_cast<int>( transform.mapY( _center.y ) ) << "\n";
 }
References _angle, _center, _circle, LibBoard::Shape::_depth, LibBoard::Shape::_fillColor, LibBoard::Shape::_lineStyle, LibBoard::Shape::_lineWidth, LibBoard::Shape::_penColor, _xRadius, _yRadius, LibBoard::Shape::filled(), DGtal::Color::valid(), LibBoard::Point::x, and LibBoard::Point::y.
flushPostscript()
void LibBoard::Ellipse::flushPostscript (std::ostream & stream, const TransformEPS & transform) const virtual
Writes the EPS code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Arc.
Definition at line 1156 of file Shapes.cpp.
 {
     double yScale = _yRadius / _xRadius;
     stream << "\n% Ellipse\n";
     if ( filled() ) {
         stream << "gs "
         << transform.mapX( _center.x ) << " " << transform.mapY( _center.y ) << " tr";
         if ( _angle != 0.0 ) stream << " " << (_angle*180/M_PI) << " rot ";
         if ( ! _circle ) stream << " " << 1.0 << " " << yScale << " sc";
         stream << " n " << transform.scale( _xRadius ) << " 0 m "
         << " 0 0 " << transform.scale( _xRadius ) << " 0.0 360.0 arc ";
         stream << " " << _fillColor.postscript() << " srgb";
         stream << " fill gr" << std::endl;
     }
     if ( _penColor != DGtal::Color::None ) {
         stream << postscriptProperties() << "\n";
         stream << "gs " << transform.mapX( _center.x ) << " " << transform.mapY( _center.y ) << " tr";
         if ( _angle != 0.0 ) stream << " " << (_angle*180/M_PI) << " rot ";
         if ( ! _circle ) stream << " " << 1.0 << " " << yScale << " sc";
         stream << " n " << transform.scale( _xRadius ) << " 0 m "
         << " 0 0 " << transform.scale( _xRadius ) << " 0.0 360.0 arc ";
         stream << " " << _penColor.postscript() << " srgb";
         stream << " stroke gr" << std::endl;
     }
 }
References _angle, _center, _circle, LibBoard::Shape::_fillColor, LibBoard::Shape::_penColor, _xRadius, _yRadius, LibBoard::Shape::filled(), DGtal::Color::None, DGtal::Color::postscript(), LibBoard::Shape::postscriptProperties(), LibBoard::Point::x, and LibBoard::Point::y.
flushSVG()
void LibBoard::Ellipse::flushSVG (std::ostream & stream, const TransformSVG & transform) const virtual
Writes the SVG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Arc, and LibBoard::Circle.
Definition at line 1213 of file Shapes.cpp.
 {
     stream << "<ellipse cx=\"" << transform.mapX( _center.x ) << '"'
     << " cy=\"" << transform.mapY( _center.y ) << '"'
     << " rx=\"" << transform.scale( _xRadius ) << '"'
     << " ry=\"" << transform.scale( _yRadius ) << '"'
     << svgProperties( transform ) ;
     if ( _angle != 0.0 ) {
         stream << " transform=\"rotate( "
         << -(_angle*180/M_PI) << ", "
         << transform.mapX( _center.x ) << ", "
         << transform.mapY( _center.y ) << " )\" ";
     }
     stream << " />" << std::endl;
 }
References _angle, _center, _xRadius, _yRadius, LibBoard::Shape::svgProperties(), LibBoard::Point::x, and LibBoard::Point::y.
Referenced by LibBoard::Circle::flushSVG().
flushTikZ()
void LibBoard::Ellipse::flushTikZ (std::ostream & stream, const TransformTikZ & transform) const virtual
Writes the TikZ code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Arc, and LibBoard::Circle.
Definition at line 1275 of file Shapes.cpp.
 {
   // FIXME: unimplemented
   stream << "% FIXME: Ellipse::flushTikZ unimplemented" << std::endl;
   stream << "\\path[" << tikzProperties(transform) << "] ("
          << transform.mapX( _center.x ) << ','
          << transform.mapY( _center.y ) << ')'
          << " circle [x radius=" << transform.scale( _xRadius ) << ','
          <<          "y radius=" << transform.scale( _yRadius ) << ','
          <<          "rotate=" << -(_angle*180/M_PI)
          << "];"
          << std::endl;
 }
References _angle, _center, _xRadius, _yRadius, LibBoard::Shape::tikzProperties(), LibBoard::Point::x, and LibBoard::Point::y.
Referenced by LibBoard::Circle::flushTikZ().
name()
const std::string & LibBoard::Ellipse::name () const virtual
Returns the generic name of the shape (e.g., Circle, Rectangle, etc.)
Returns
object name
Reimplemented from LibBoard::Shape.
Reimplemented in LibBoard::Arc, and LibBoard::Circle.
Definition at line 1020 of file Shapes.cpp.
 {
     return _name;
 }
References _name.
rotate() [1/2]
Ellipse & LibBoard::Ellipse::rotate (double angle) virtual
Rotate the shape around its center.
Parameters
angle The rotation angle in radian.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Circle.
Definition at line 1050 of file Shapes.cpp.
 {
     return Ellipse::rotate( angle, center() );
 }
References center(), and rotate().
rotate() [2/2]
Ellipse & LibBoard::Ellipse::rotate (double angle, const Point & center) virtual
Rotate the shape around a given center of rotation.
Parameters
angle The rotation angle in radian.
center The center of rotation.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Circle.
Definition at line 1031 of file Shapes.cpp.
 {
     Point c( _center );
     Point e = (c + Point( _xRadius, 0 )).rotate( _angle, c );
     Point rc = c.rotated( angle, rotCenter );
     Point re = e.rotated( angle, rotCenter );
     Point axis = re - rc;
     _angle = atan( axis.y / axis.x );
     _center = rc;
     return *this;
 }
References _angle, _center, _xRadius, re, LibBoard::Point::rotated(), LibBoard::Point::x, and LibBoard::Point::y.
Referenced by rotate(), and LibBoard::Circle::rotate().
rotated() [1/2]
Ellipse LibBoard::Ellipse::rotated (double angle) const
Parameters
angle angle
Returns
an ellipse
Definition at line 1056 of file Shapes.cpp.
 {
     return Ellipse(*this).rotate( angle, center() );
 }
References center(), and Ellipse().
rotated() [2/2]
Ellipse LibBoard::Ellipse::rotated (double angle, const Point & center) const
Parameters
angle angle
center center
Returns
an ellipse
Definition at line 1044 of file Shapes.cpp.
 {
     return Ellipse(*this).rotate( angle, rotCenter );
 }
References Ellipse().
scale() [1/2]
Shape & LibBoard::Ellipse::scale (double s) virtual
Scale the shape along both axis.
Parameters
s The scale factor along both axis.
Returns
The shape itself.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Circle.
Definition at line 1125 of file Shapes.cpp.
 {
     return Ellipse::scale( s, s );
 }
References scale().
scale() [2/2]
Shape & LibBoard::Ellipse::scale (double sx, double sy) virtual
Scale the shape along the x an y axis.
Parameters
sx The scale factor along the x axis.
sy The scale factor along the y axis.
Returns
The shape itself.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Circle.
Definition at line 1075 of file Shapes.cpp.
 {
   // Thanks to Freddie Exall for pointing an error with the first version
   // of this function, and for pointing to a fix as well!
   if ( _angle != 0 ) {
     double co = cos( _angle );
     double si = sin( _angle );
     // current transformation matrix
     double m00 = ( 1 / _xRadius ) * co;
     double m01 = ( 1 / _xRadius ) * si;
     double m10 = - ( 1 / _yRadius ) * si;
     double m11 = ( 1 / _yRadius ) * co;
     // Implicit function of ellipse at current
     // ax^2 + bxy + cy^2 = 1
     double a = ( m00 * m00 ) + ( m10 * m10 );
     double b = 2 * ( ( m00 * m01 ) + ( m10 * m11 ) );
     double c = ( m01 * m01 ) + ( m11 * m11 );
     // Scale coefficients ( x_new = sx * x, y_new = sy * y )
     a = a / ( sx * sx );
     b = b / ( sx * sy );
     c = c / ( sy * sy );
     if ( b == 0 ) {
       _angle = 0;
     } else if ( a == c ) {
       _angle = M_PI / 4;
       a += ( b / 2 );
       c -= ( b / 2 );
     } else {
       _angle = 0.5 * atan( b / ( a - c ) );
       double k = 1 + ( ( b * b ) / ( ( a - c ) * ( a - c ) ) );
       k = sqrt( k );
       k *= ( a - c );
       c += a;
       a = 0.5 * ( c + k );
       c = 0.5 * ( c - k );
     }
     _xRadius = 1 / sqrt( a );
     _yRadius = 1 / sqrt( c );
   } else {
     _xRadius = _xRadius * sx;
     _yRadius = _yRadius * sy;
   }
   return *this;
 }
References _angle, _xRadius, and _yRadius.
Referenced by scale(), and LibBoard::Circle::scale().
scaleAll()
void LibBoard::Ellipse::scaleAll (double s) virtual
Scales all the values (positions, dimensions, etc.) associated with the shape.
Parameters
s The scaling factor.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Circle.
Definition at line 1143 of file Shapes.cpp.
 {
     _xRadius *= s;
     _yRadius *= s;
     _center *= s;
 }
References _center, _xRadius, and _yRadius.
scaled() [1/2]
Ellipse LibBoard::Ellipse::scaled (double s) const
Definition at line 1137 of file Shapes.cpp.
 {
     return static_cast<Ellipse &>( Ellipse(*this).scale( s, s ) );
 }
References Ellipse().
scaled() [2/2]
Ellipse LibBoard::Ellipse::scaled (double sx, double sy) const
Parameters
sx scale factor
sy scale factor
Returns
scaled ellipse
Definition at line 1131 of file Shapes.cpp.
 {
     return static_cast<Ellipse &>( Ellipse(*this).scale( sx, sy ) );
 }
References Ellipse().
translate()
Ellipse & LibBoard::Ellipse::translate (double dx, double dy) virtual
Translate the shape by a given offset.
Parameters
dx The x offset.
dy The y offset.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Reimplemented in LibBoard::Circle.
Definition at line 1062 of file Shapes.cpp.
 {
     _center += Point( dx, dy );
     return *this;
 }
References _center.
translated()
Ellipse LibBoard::Ellipse::translated (double dx, double dy) const
Parameters
dx translation along x-axis
dy translation along the y-axis
Returns
translated ellipse.
Definition at line 1069 of file Shapes.cpp.
 {
     return Ellipse(*this).translate( dx, dy );
 }
References Ellipse().
Field Documentation
_angle
double LibBoard::Ellipse::_angle protected
Definition at line 1452 of file Board/Shapes.h.
Referenced by boundingBox(), Ellipse(), flushCairo(), flushFIG(), flushPostscript(), flushSVG(), flushTikZ(), rotate(), and scale().
_center
Point LibBoard::Ellipse::_center protected
Definition at line 1449 of file Board/Shapes.h.
Referenced by boundingBox(), center(), LibBoard::Circle::center(), flushCairo(), LibBoard::Circle::flushCairo(), LibBoard::Arc::flushCairo(), flushFIG(), flushPostscript(), LibBoard::Arc::flushPostscript(), flushSVG(), LibBoard::Circle::flushSVG(), LibBoard::Arc::flushSVG(), flushTikZ(), LibBoard::Circle::flushTikZ(), LibBoard::Arc::flushTikZ(), rotate(), LibBoard::Circle::rotate(), scaleAll(), LibBoard::Circle::scaleAll(), translate(), and LibBoard::Circle::translate().
_circle
bool LibBoard::Ellipse::_circle protected
Definition at line 1453 of file Board/Shapes.h.
Referenced by LibBoard::Circle::Circle(), LibBoard::Circle::flushCairo(), flushFIG(), flushPostscript(), LibBoard::Circle::flushSVG(), LibBoard::Circle::flushTikZ(), and LibBoard::Circle::rotate().
_name
const std::string LibBoard::Ellipse::_name static private
The generic name of the shape.
Definition at line 1446 of file Board/Shapes.h.
Referenced by name().
_xRadius
double LibBoard::Ellipse::_xRadius protected
Definition at line 1450 of file Board/Shapes.h.
Referenced by boundingBox(), flushCairo(), LibBoard::Circle::flushCairo(), LibBoard::Arc::flushCairo(), flushFIG(), flushPostscript(), LibBoard::Arc::flushPostscript(), flushSVG(), LibBoard::Circle::flushSVG(), LibBoard::Arc::flushSVG(), flushTikZ(), LibBoard::Circle::flushTikZ(), LibBoard::Arc::flushTikZ(), rotate(), scale(), scaleAll(), and LibBoard::Circle::scaleAll().
_yRadius
double LibBoard::Ellipse::_yRadius protected
Definition at line 1451 of file Board/Shapes.h.
Referenced by boundingBox(), flushCairo(), flushFIG(), flushPostscript(), flushSVG(), flushTikZ(), scale(), scaleAll(), and LibBoard::Circle::scaleAll().
The documentation for this struct was generated from the following files:
Board/Shapes.h
Shapes.cpp