DGtal: DGtal::concepts::CImageFactory< T > Struct Template Reference
DGtal::concepts::CImageFactory< T > Struct Template Reference
DGtal Concepts
Aim: Defines the concept describing an image factory.
#include <DGtal/images/CImageFactory.h>
Public Types
typedef T::OutputImage OutputImage
Public Member Functions
BOOST_CONCEPT_ASSERT ((CImage< OutputImage >))
BOOST_CONCEPT_USAGE (CImageFactory)
void checkConstConstraints () const
Private Attributes
T myT
OutputImage * myOI
T::Domain myDomain
Detailed Description
template<typename T>
struct DGtal::concepts::CImageFactory< T >
Aim: Defines the concept describing an image factory.
Description of concept 'CImageFactory'
Refinement of
Associated types
OutputImage : type of the image created by the factory, model of concept CImage
Domain : type of the image domain, model of concept CDomain
Notation
X : A type that is a model of CImageFactory
x : object of type X
d : object of type Domain
o : object of type OutputImage
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
Request image x.requestImage(d) d of type Domain OutputImage returns a pointer of an OutputImage created with the Domain d
Flush image x.flushImage(o) o of type OutputImage flush (i.e. write/synchronize) an OutputImage o
Detach image x.detachImage(o) o of type OutputImage free (i.e. delete) an OutputImage o
Invariants
Models
ImageFactoryFromImage ImageFactoryFromHDF5
Notes
Template Parameters
T the type that should be a model of CImageFactory.
Definition at line 90 of file CImageFactory.h.
Member Typedef Documentation
OutputImage
template<typename T > typedef T::OutputImage DGtal::concepts::CImageFactory< T >::OutputImage
Definition at line 95 of file CImageFactory.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename T > DGtal::concepts::CImageFactory< T >::BOOST_CONCEPT_ASSERT ((CImage< OutputImage >))
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CImageFactory< T >::BOOST_CONCEPT_USAGE (CImageFactory< T >) inline
Definition at line 99 of file CImageFactory.h.
     {
         ConceptUtils::sameType( myOI, myT.requestImage(myDomain) );
         myT.flushImage(myOI);
         myT.detachImage(myOI);
         // check const methods.
         checkConstConstraints();
     }
References DGtal::concepts::CImageFactory< T >::checkConstConstraints(), DGtal::concepts::CImageFactory< T >::myDomain, DGtal::concepts::CImageFactory< T >::myOI, DGtal::concepts::CImageFactory< T >::myT, and DGtal::concepts::ConceptUtils::sameType().
checkConstConstraints()
template<typename T > void DGtal::concepts::CImageFactory< T >::checkConstConstraints () const inline
Definition at line 108 of file CImageFactory.h.
     {
     }
Referenced by DGtal::concepts::CImageFactory< T >::BOOST_CONCEPT_USAGE().
Field Documentation
myDomain
template<typename T > T::Domain DGtal::concepts::CImageFactory< T >::myDomain private
Definition at line 116 of file CImageFactory.h.
Referenced by DGtal::concepts::CImageFactory< T >::BOOST_CONCEPT_USAGE().
myOI
template<typename T > OutputImage* DGtal::concepts::CImageFactory< T >::myOI private
Definition at line 115 of file CImageFactory.h.
Referenced by DGtal::concepts::CImageFactory< T >::BOOST_CONCEPT_USAGE().
myT
template<typename T > T DGtal::concepts::CImageFactory< T >::myT private
Definition at line 114 of file CImageFactory.h.
Referenced by DGtal::concepts::CImageFactory< T >::BOOST_CONCEPT_USAGE().
The documentation for this struct was generated from the following file:
CImageFactory.h