DGtal: DGtal::SignedKhalimskyCell< dim, TInteger > Struct Template Reference
DGtal::SignedKhalimskyCell< dim, TInteger > Struct Template Reference
Represents a signed cell in a cellular grid space by its Khalimsky coordinates and a boolean value.
#include <DGtal/topology/KhalimskySpaceND.h>
Public Types
using Integer = TInteger
using UnsignedInteger = typename NumberTraits< Integer >::UnsignedVersion
using Point = PointVector< dim, Integer >
using SPreCell = SignedKhalimskyPreCell< dim, Integer >
using CellularGridSpace = KhalimskySpaceND< dim, TInteger >
using PreCellularGridSpace = KhalimskyPreSpaceND< dim, TInteger >
using Self = SignedKhalimskyCell< dim, Integer >
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CInteger< TInteger >))
Integer must be a model of the concept CInteger.
operator SPreCell const & () const
Constant conversion to SignedKhalimskyPreCell.
SPreCell const & preCell () const
Returns the underlying constant signed pre-cell.
SignedKhalimskyCell (Integer dummy=0)
Default constructor.
SignedKhalimskyCell (const SignedKhalimskyCell &other)=default
Copy constructor.
SignedKhalimskyCell & operator= (const SignedKhalimskyCell &other)=default
Copy operator.
SignedKhalimskyCell (SignedKhalimskyCell &&other)=default
Move constructor.
SignedKhalimskyCell & operator= (SignedKhalimskyCell &&other)=default
Move operator.
bool operator== (const SignedKhalimskyCell &other) const
Equality operator.
bool operator!= (const SignedKhalimskyCell &other) const
Difference operator.
bool operator< (const SignedKhalimskyCell &other) const
Inferior operator. (lexicographic order).
std::string className () const
Return the style name used for drawing this object.
Private Member Functions
SignedKhalimskyCell (const Point &aPoint, bool positive)
Explicit constructor from its Khalimsky coordinates.
SignedKhalimskyCell (const SPreCell &aCell)
Explicit constructor from a SignedKhalimskyPreCell.
operator SPreCell & ()
Mutable conversion to SignedKhalimskyPreCell.
Private Attributes
SPreCell mySPreCell
Underlying signed pre-cell.
Friends
class KhalimskySpaceND< dim, TInteger >
class KhalimskySpaceNDHelper< CellularGridSpace >
Detailed Description
template<Dimension dim, typename TInteger = DGtal::int32_t>
struct DGtal::SignedKhalimskyCell< dim, TInteger >
Represents a signed cell in a cellular grid space by its Khalimsky coordinates and a boolean value.
Template Parameters
dim the dimension of the digital space.
TInteger the Integer class used to specify the arithmetic computations (default type = int32).
Examples
dec/exampleDECSurface.cpp, examples/tutorial-examples/polyhedralizer.cpp, geometry/curves/estimation/exampleCurvature.cpp, geometry/curves/exampleGridCurve2d.cpp, geometry/curves/exampleGridCurve3d-2.cpp, geometry/surfaces/dvcm-3d.cpp, geometry/volumes/distance/exampleFMM3D.cpp, graph/volDistanceTraversal.cpp, io/boards/dgtalBoard3D-2-ks.cpp, io/boards/dgtalBoard3DTo2D-KSCell.cpp, io/viewers/viewer3D-10-interaction.cpp, io/viewers/viewer3D-4bis-illustrationMode.cpp, topology/ctopo-1s-3d.cpp, topology/ctopo-2-3d.cpp, topology/ctopo-2.cpp, topology/ctopo-fillContours.cpp, topology/digitalSurfaceSlice.cpp, topology/frontierAndBoundary.cpp, topology/trackImplicitPolynomialSurfaceToOFF.cpp, topology/volBreadthFirstTraversal.cpp, topology/volScanBoundary.cpp, topology/volTrackBoundary.cpp, tutorial-examples/AreaSurfaceEstimation-final.cpp, tutorial-examples/FMMErosion.cpp, and tutorial-examples/polyhedralizer.cpp.
Definition at line 208 of file KhalimskySpaceND.h.
Member Typedef Documentation
CellularGridSpace
template<Dimension dim, typename TInteger = DGtal::int32_t> using DGtal::SignedKhalimskyCell< dim, TInteger >::CellularGridSpace = KhalimskySpaceND< dim, TInteger >
Definition at line 219 of file KhalimskySpaceND.h.
Integer
template<Dimension dim, typename TInteger = DGtal::int32_t> using DGtal::SignedKhalimskyCell< dim, TInteger >::Integer = TInteger
Definition at line 215 of file KhalimskySpaceND.h.
Point
template<Dimension dim, typename TInteger = DGtal::int32_t> using DGtal::SignedKhalimskyCell< dim, TInteger >::Point = PointVector< dim, Integer >
Definition at line 217 of file KhalimskySpaceND.h.
PreCellularGridSpace
template<Dimension dim, typename TInteger = DGtal::int32_t> using DGtal::SignedKhalimskyCell< dim, TInteger >::PreCellularGridSpace = KhalimskyPreSpaceND< dim, TInteger >
Definition at line 220 of file KhalimskySpaceND.h.
Self
template<Dimension dim, typename TInteger = DGtal::int32_t> using DGtal::SignedKhalimskyCell< dim, TInteger >::Self = SignedKhalimskyCell< dim, Integer >
Definition at line 221 of file KhalimskySpaceND.h.
SPreCell
template<Dimension dim, typename TInteger = DGtal::int32_t> using DGtal::SignedKhalimskyCell< dim, TInteger >::SPreCell = SignedKhalimskyPreCell< dim, Integer >
Definition at line 218 of file KhalimskySpaceND.h.
UnsignedInteger
template<Dimension dim, typename TInteger = DGtal::int32_t> using DGtal::SignedKhalimskyCell< dim, TInteger >::UnsignedInteger = typename NumberTraits<Integer>::UnsignedVersion
Definition at line 216 of file KhalimskySpaceND.h.
Constructor & Destructor Documentation
SignedKhalimskyCell() [1/5]
template<Dimension dim, typename TInteger = DGtal::int32_t> DGtal::SignedKhalimskyCell< dim, TInteger >::SignedKhalimskyCell (const Point & aPoint, bool positive) explicit private
Explicit constructor from its Khalimsky coordinates.
Parameters
aPoint any point.
positive if cell has positive sign.
SignedKhalimskyCell() [2/5]
template<Dimension dim, typename TInteger = DGtal::int32_t> DGtal::SignedKhalimskyCell< dim, TInteger >::SignedKhalimskyCell (const SPreCell & aCell) explicit private
Explicit constructor from a SignedKhalimskyPreCell.
Parameters
aCell a pre-cell.
SignedKhalimskyCell() [3/5]
template<Dimension dim, typename TInteger = DGtal::int32_t> DGtal::SignedKhalimskyCell< dim, TInteger >::SignedKhalimskyCell (Integer dummy = 0) explicit
Default constructor.
SignedKhalimskyCell() [4/5]
template<Dimension dim, typename TInteger = DGtal::int32_t> DGtal::SignedKhalimskyCell< dim, TInteger >::SignedKhalimskyCell (const SignedKhalimskyCell< dim, TInteger > & other) default
Copy constructor.
Parameters
other any other cell.
SignedKhalimskyCell() [5/5]
template<Dimension dim, typename TInteger = DGtal::int32_t> DGtal::SignedKhalimskyCell< dim, TInteger >::SignedKhalimskyCell (SignedKhalimskyCell< dim, TInteger > && other) default
Move constructor.
Parameters
other any other cell.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<Dimension dim, typename TInteger = DGtal::int32_t> DGtal::SignedKhalimskyCell< dim, TInteger >::BOOST_CONCEPT_ASSERT ((concepts::CInteger< TInteger >))
Integer must be a model of the concept CInteger.
className()
template<Dimension dim, typename TInteger = DGtal::int32_t> std::string DGtal::SignedKhalimskyCell< dim, TInteger >::className () const
Return the style name used for drawing this object.
Default drawing style object.
Returns
the dyn. alloc. default style for this object.
the style name used for drawing this object.
Examples
graph/volDistanceTraversal.cpp, io/viewers/viewer3D-10-interaction.cpp, topology/volScanBoundary.cpp, and topology/volTrackBoundary.cpp.
Referenced by main(), testCellDrawOnBoard(), and testDigitization().
operator SPreCell &()
template<Dimension dim, typename TInteger = DGtal::int32_t> DGtal::SignedKhalimskyCell< dim, TInteger >::operator SPreCell & () explicit private
Mutable conversion to SignedKhalimskyPreCell.
operator SPreCell const &()
template<Dimension dim, typename TInteger = DGtal::int32_t> DGtal::SignedKhalimskyCell< dim, TInteger >::operator SPreCell const & () const
Constant conversion to SignedKhalimskyPreCell.
operator!=()
template<Dimension dim, typename TInteger = DGtal::int32_t> bool DGtal::SignedKhalimskyCell< dim, TInteger >::operator!= (const SignedKhalimskyCell< dim, TInteger > & other) const
Difference operator.
Parameters
other any other cell.
operator<()
template<Dimension dim, typename TInteger = DGtal::int32_t> bool DGtal::SignedKhalimskyCell< dim, TInteger >::operator< (const SignedKhalimskyCell< dim, TInteger > & other) const
Inferior operator. (lexicographic order).
Parameters
other any other cell.
operator=() [1/2]
template<Dimension dim, typename TInteger = DGtal::int32_t> SignedKhalimskyCell& DGtal::SignedKhalimskyCell< dim, TInteger >::operator= (const SignedKhalimskyCell< dim, TInteger > & other) default
Copy operator.
Parameters
other any other cell.
operator=() [2/2]
template<Dimension dim, typename TInteger = DGtal::int32_t> SignedKhalimskyCell& DGtal::SignedKhalimskyCell< dim, TInteger >::operator= (SignedKhalimskyCell< dim, TInteger > && other) default
Move operator.
Parameters
other any other cell.
operator==()
template<Dimension dim, typename TInteger = DGtal::int32_t> bool DGtal::SignedKhalimskyCell< dim, TInteger >::operator== (const SignedKhalimskyCell< dim, TInteger > & other) const
Equality operator.
Parameters
other any other cell.
preCell()
template<Dimension dim, typename TInteger = DGtal::int32_t> SPreCell const& DGtal::SignedKhalimskyCell< dim, TInteger >::preCell () const
Returns the underlying constant signed pre-cell.
Referenced by std::hash< DGtal::SignedKhalimskyCell< dim, TInteger > >::operator()(), boost::hash< DGtal::SignedKhalimskyCell< dim, TInteger > >::operator()(), and DGtal::TransformedPrism::TransformedPrism().
Friends And Related Function Documentation
KhalimskySpaceND< dim, TInteger >
template<Dimension dim, typename TInteger = DGtal::int32_t> friend class KhalimskySpaceND< dim, TInteger > friend
Definition at line 211 of file KhalimskySpaceND.h.
KhalimskySpaceNDHelper< CellularGridSpace >
template<Dimension dim, typename TInteger = DGtal::int32_t> friend class KhalimskySpaceNDHelper< CellularGridSpace > friend
Definition at line 211 of file KhalimskySpaceND.h.
Field Documentation
mySPreCell
template<Dimension dim, typename TInteger = DGtal::int32_t> SPreCell DGtal::SignedKhalimskyCell< dim, TInteger >::mySPreCell private
Underlying signed pre-cell.
Definition at line 229 of file KhalimskySpaceND.h.
The documentation for this struct was generated from the following file:
KhalimskySpaceND.h