DGtal: DGtal::concepts::CSCellEmbedder< T > Struct Template Reference
DGtal::concepts::CSCellEmbedder< T > Struct Template Reference
DGtal Concepts
Aim: A cell embedder is a mapping from signed cells to Euclidean points. It adds inner types to functor.
#include <DGtal/topology/CSCellEmbedder.h>
Public Types
typedef T::KSpace KSpace
typedef T::SCell SCell
typedef T::RealPoint RealPoint
typedef T::Argument Argument
typedef T::Value Value
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CCellularGridSpaceND< KSpace >))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< SCell, typename KSpace::SCell >::value))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< SCell, Argument >::value))
BOOST_STATIC_ASSERT ((ConceptUtils::SameType< RealPoint, Value >::value))
BOOST_CONCEPT_USAGE (CSCellEmbedder)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::concepts::CUnaryFunctor< T, T::SCell, T::RealPoint >
BOOST_CONCEPT_USAGE (CUnaryFunctor)
Private Attributes
T myX
SCell myP
RealPoint myRP
const KSpace myK
Detailed Description
template<typename T>
struct DGtal::concepts::CSCellEmbedder< T >
Aim: A cell embedder is a mapping from signed cells to Euclidean points. It adds inner types to functor.
Description of concept 'CSCellEmbedder'
Refinement of
CUnaryFunctor<T, T::SCell, T::RealPoint>
Associated types
KSpace: the cellular grid space
SCell: same as KSpace::SCell
RealPoint: the type of Euclidean point
Argument: type of the argument, same as KSpace::SCell
Value: type of value, same as RealPoint
Notation
X : A type that is a model of CSCellEmbedder
x : object of type X
p : object of type SCell
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
Apply function x(p) Value return the value of the function x on argument p
Khalimsky space x.space()) const KSpace & return a reference to the the Kalimsky space
Invariants
Models
CanonicSCellEmbedder, CanonicDigitalSurfaceEmbedder, DigitalSurfaceEmbedderWithNormalVectorEstimator
Notes
Template Parameters
T the type that should be a model of CSCellEmbedder.
Definition at line 97 of file CSCellEmbedder.h.
Member Typedef Documentation
Argument
template<typename T > typedef T::Argument DGtal::concepts::CSCellEmbedder< T >::Argument
Definition at line 104 of file CSCellEmbedder.h.
KSpace
template<typename T > typedef T::KSpace DGtal::concepts::CSCellEmbedder< T >::KSpace
Definition at line 101 of file CSCellEmbedder.h.
RealPoint
template<typename T > typedef T::RealPoint DGtal::concepts::CSCellEmbedder< T >::RealPoint
Definition at line 103 of file CSCellEmbedder.h.
SCell
template<typename T > typedef T::SCell DGtal::concepts::CSCellEmbedder< T >::SCell
Definition at line 102 of file CSCellEmbedder.h.
Value
template<typename T > typedef T::Value DGtal::concepts::CSCellEmbedder< T >::Value
Definition at line 105 of file CSCellEmbedder.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename T > DGtal::concepts::CSCellEmbedder< T >::BOOST_CONCEPT_ASSERT ((concepts::CCellularGridSpaceND< KSpace >))
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CSCellEmbedder< T >::BOOST_CONCEPT_USAGE (CSCellEmbedder< T >) inline
Definition at line 111 of file CSCellEmbedder.h.
   {
     checkConstConstraints();
   }
References DGtal::concepts::CSCellEmbedder< T >::checkConstConstraints().
BOOST_STATIC_ASSERT() [1/3]
template<typename T > DGtal::concepts::CSCellEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< RealPoint, Value >::value))
BOOST_STATIC_ASSERT() [2/3]
template<typename T > DGtal::concepts::CSCellEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< SCell, Argument >::value))
BOOST_STATIC_ASSERT() [3/3]
template<typename T > DGtal::concepts::CSCellEmbedder< T >::BOOST_STATIC_ASSERT ((ConceptUtils::SameType< SCell, typename KSpace::SCell >::value))
checkConstConstraints()
template<typename T > void DGtal::concepts::CSCellEmbedder< T >::checkConstConstraints () const inline
Definition at line 116 of file CSCellEmbedder.h.
   { // operator()
     ConceptUtils::sameType( myRP, myX( myP ) );
     ConceptUtils::sameType( myK, myX.space() );
   }
References DGtal::concepts::CSCellEmbedder< T >::myK, DGtal::concepts::CSCellEmbedder< T >::myP, DGtal::concepts::CSCellEmbedder< T >::myRP, DGtal::concepts::CSCellEmbedder< T >::myX, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::concepts::CSCellEmbedder< T >::BOOST_CONCEPT_USAGE().
Field Documentation
myK
template<typename T > const KSpace DGtal::concepts::CSCellEmbedder< T >::myK private
Definition at line 126 of file CSCellEmbedder.h.
Referenced by DGtal::concepts::CSCellEmbedder< T >::checkConstConstraints().
myP
template<typename T > SCell DGtal::concepts::CSCellEmbedder< T >::myP private
Definition at line 124 of file CSCellEmbedder.h.
Referenced by DGtal::concepts::CSCellEmbedder< T >::checkConstConstraints().
myRP
template<typename T > RealPoint DGtal::concepts::CSCellEmbedder< T >::myRP private
Definition at line 125 of file CSCellEmbedder.h.
Referenced by DGtal::concepts::CSCellEmbedder< T >::checkConstConstraints().
myX
template<typename T > T DGtal::concepts::CSCellEmbedder< T >::myX private
Definition at line 123 of file CSCellEmbedder.h.
Referenced by DGtal::concepts::CSCellEmbedder< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CSCellEmbedder.h