DGtal: LibBoard::Polyline Struct Reference
LibBoard::Polyline Struct Reference
A polygonal line described by a series of 2D points.
#include <Board/Shapes.h>
Public Member Functions
Polyline (const std::vector< Point > &points, bool closed, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
Polyline (const Path &path, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
Polyline (bool closed, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
const std::string & name () const
Point center () const
Polyline & operator<< (const Point &p)
Point & operator[] (const unsigned int n)
Polyline & rotate (double angle, const Point &center)
Polyline rotated (double angle, const Point &center) const
Polyline & rotate (double angle)
Polyline rotated (double angle) const
Polyline & translate (double dx, double dy)
Polyline translated (double dx, double dy) const
Shape & scale (double sx, double sy)
Shape & scale (double s)
Polyline scaled (double sx, double sy) const
Polyline scaled (double s) const
void scaleAll (double s)
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
Rect boundingBox () const
Polyline * clone () const
Public Member Functions inherited from LibBoard::Shape
Shape (DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, LineStyle style, const LineCap cap, const LineJoin join, int depth)
virtual ~Shape ()
bool filled () const
Shape & rotateDeg (double angle, const Point &center)
Shape & rotateDeg (double angle)
Rect bbox ()
Shape & operator-- ()
Shape & operator++ ()
int depth () const
virtual void depth (int)
virtual void shiftDepth (int shift)
const DGtal::Color & penColor () const
const DGtal::Color & fillColor () const
Protected Attributes
Path _path
Protected Attributes inherited from LibBoard::Shape
int _depth
DGtal::Color _penColor
DGtal::Color _fillColor
double _lineWidth
LineStyle _lineStyle
LineCap _lineCap
LineJoin _lineJoin
Static Private Attributes
static const std::string _name
Additional Inherited Members
Public Types inherited from LibBoard::Shape
enum LineCap { ButtCap = 0, RoundCap, SquareCap }
enum LineJoin { MiterJoin = 0, RoundJoin, BevelJoin }
enum LineStyle {
SolidStyle = 0, DashStyle, DotStyle, DashDotStyle,
DashDotDotStyle, DashDotDotDotStyle
}
Protected Member Functions inherited from LibBoard::Shape
std::string svgProperties (const TransformSVG &transform) const
std::string postscriptProperties () const
void setCairoDashStyle (cairo_t *cr, LineStyle type) const
std::string tikzProperties (const TransformTikZ &transform) const
Detailed Description
A polygonal line described by a series of 2D points.
The polyline structure.
Definition at line 765 of file Board/Shapes.h.
Constructor & Destructor Documentation
Polyline() [1/3]
LibBoard::Polyline::Polyline (const std::vector< Point > & points, bool closed, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle = SolidStyle, const LineCap cap = ButtCap, const LineJoin join = MiterJoin, int depth = -1) inline
Referenced by clone(), LibBoard::GouraudTriangle::flushFIG(), rotated(), scaled(), and translated().
Polyline() [2/3]
LibBoard::Polyline::Polyline (const Path & path, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle = SolidStyle, const LineCap cap = ButtCap, const LineJoin join = MiterJoin, int depth = -1) inline
Polyline() [3/3]
LibBoard::Polyline::Polyline (bool closed, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle = SolidStyle, const LineCap cap = ButtCap, const LineJoin join = MiterJoin, int depth = -1) inline
Member Function Documentation
boundingBox()
Rect LibBoard::Polyline::boundingBox () const virtual
Returns the bounding box of the figure.
Returns
The rectangle of the bounding box.
Implements LibBoard::Shape.
Definition at line 1867 of file Shapes.cpp.
 {
     return _path.boundingBox();
 }
References _path, and LibBoard::Path::boundingBox().
center()
Point LibBoard::Polyline::center () const virtual
Returns the gravity center of the shape.
Returns
The center of the shape.
Implements LibBoard::Shape.
Reimplemented in LibBoard::GouraudTriangle.
Definition at line 1655 of file Shapes.cpp.
{
     return _path.center();
 }
References _path, and LibBoard::Path::center().
Referenced by rotate(), rotated(), and LibBoard::Rectangle::rotated().
clone()
Polyline * LibBoard::Polyline::clone () const virtual
Return a copy of the shape.
Returns
copye of the shape.
Implements LibBoard::Shape.
Reimplemented in LibBoard::GouraudTriangle, LibBoard::Triangle, LibBoard::Image, and LibBoard::Rectangle.
Definition at line 1731 of file Shapes.cpp.
                       {
     return new Polyline(*this);
 }
References Polyline().
flushCairo()
void LibBoard::Polyline::flushCairo (cairo_t * cr, const TransformCairo & transform) const virtual
Writes the cairo code of the shape in a cairo drawing context according to a transform.
Parameters
cr The cairo drawing context.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Reimplemented in LibBoard::GouraudTriangle, LibBoard::QuadraticBezierCurve, LibBoard::Image, and LibBoard::Rectangle.
Definition at line 1809 of file Shapes.cpp.
 {
     if ( _path.empty() )
         return;
     cairo_save (cr);
       cairo_set_source_rgba (cr, _fillColor.red()/255.0, _fillColor.green()/255.0, _fillColor.blue()/255.0, 1.);
       _path.flushCairoPoints( cr, transform );
       if ( _path.closed() )
   cairo_close_path (cr);
       if ( filled() )
       {
   if ( _penColor != DGtal::Color::None )
     cairo_fill_preserve (cr);
   else
     cairo_fill (cr);
       }
       //
       if ( _penColor != DGtal::Color::None )
       {
   cairo_set_source_rgba (cr, _penColor.red()/255.0, _penColor.green()/255.0, _penColor.blue()/255.0, 1.);
   cairo_set_line_width (cr, _lineWidth);
   cairo_set_line_cap (cr, cairoLineCap[_lineCap]);
   cairo_set_line_join (cr, cairoLineJoin[_lineJoin]);
   setCairoDashStyle (cr, _lineStyle);
   cairo_stroke (cr);
       }
     cairo_restore (cr);
 }
References LibBoard::Shape::_fillColor, LibBoard::Shape::_lineCap, LibBoard::Shape::_lineJoin, LibBoard::Shape::_lineStyle, LibBoard::Shape::_lineWidth, _path, LibBoard::Shape::_penColor, DGtal::Color::blue(), LibBoard::Path::closed(), LibBoard::Path::empty(), LibBoard::Shape::filled(), LibBoard::Path::flushCairoPoints(), DGtal::Color::green(), DGtal::Color::None, DGtal::Color::red(), and LibBoard::Shape::setCairoDashStyle().
Referenced by LibBoard::Rectangle::flushCairo().
flushFIG()
void LibBoard::Polyline::flushFIG (std::ostream & stream, const TransformFIG & transform, std::map< DGtal::Color, int > & colormap) const virtual
Writes the FIG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
colormap A colormap.
Implements LibBoard::Shape.
Reimplemented in LibBoard::GouraudTriangle, LibBoard::QuadraticBezierCurve, LibBoard::Image, and LibBoard::Rectangle.
Definition at line 1760 of file Shapes.cpp.
 {
     if ( _path.empty() )
         return;
     if ( _path.closed() )
         stream << "2 3 " << _lineStyle << " ";
     else
         stream << "2 1 " << _lineStyle << " ";
     // Thickness
     stream << ( _penColor.valid()?transform.mapWidth( _lineWidth ):0 ) << " ";
     // Pen color
     stream << colormap[ _penColor ] << " ";
     // Fill color
     stream << colormap[ _fillColor ] << " ";
     // Depth
     stream << transform.mapDepth( _depth ) << " ";
     // Pen style
     stream <<  "-1 ";
     // Area fill, style val, join style, cap style, radius, f_arrow, b_arrow
     if ( filled() )
         stream << "20 " << (_lineStyle?"4.000 ":"0.000 ") << _lineJoin << " " << _lineCap << " -1 0 0 ";
     else
         stream << "-1 " << (_lineStyle?"4.000 ":"0.000 ")  << _lineJoin << " " << _lineCap << " -1 0 0 ";
     // Number of points
     stream << _path.size() + _path.closed() << std::endl;
     _path.flushFIG( stream << "         ", transform );
     stream << std::endl;
 }
References LibBoard::Shape::_depth, LibBoard::Shape::_fillColor, LibBoard::Shape::_lineCap, LibBoard::Shape::_lineJoin, LibBoard::Shape::_lineStyle, LibBoard::Shape::_lineWidth, _path, LibBoard::Shape::_penColor, LibBoard::Path::closed(), LibBoard::Path::empty(), LibBoard::Shape::filled(), LibBoard::Path::flushFIG(), LibBoard::Path::size(), and DGtal::Color::valid().
Referenced by LibBoard::Rectangle::flushFIG(), and LibBoard::QuadraticBezierCurve::flushFIG().
flushPostscript()
void LibBoard::Polyline::flushPostscript (std::ostream & stream, const TransformEPS & transform) const virtual
Writes the EPS code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Reimplemented in LibBoard::GouraudTriangle, and LibBoard::QuadraticBezierCurve.
Definition at line 1736 of file Shapes.cpp.
 {
     if ( _path.empty() ) return;
     stream << "\n% Polyline\n";
     if ( filled() ) {
         stream << "n ";
         _path.flushPostscript( stream, transform );
         stream << " ";
         _fillColor.flushPostscript( stream );
   stream << " " << postscriptProperties();
         stream << " fill" << std::endl;
     }
     if ( _penColor != DGtal::Color::None ) {
         stream << " " << postscriptProperties() << "\n";
         stream << "n ";
         _path.flushPostscript( stream, transform );
         stream << " ";
         _penColor.flushPostscript( stream );
         stream << " stroke" << std::endl;
     }
 }
References LibBoard::Shape::_fillColor, _path, LibBoard::Shape::_penColor, LibBoard::Path::empty(), LibBoard::Shape::filled(), DGtal::Color::flushPostscript(), LibBoard::Path::flushPostscript(), DGtal::Color::None, and LibBoard::Shape::postscriptProperties().
Referenced by LibBoard::GouraudTriangle::flushPostscript().
flushSVG()
void LibBoard::Polyline::flushSVG (std::ostream & stream, const TransformSVG & transform) const virtual
Writes the SVG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Reimplemented in LibBoard::GouraudTriangle, LibBoard::QuadraticBezierCurve, LibBoard::Image, and LibBoard::Rectangle.
Definition at line 1792 of file Shapes.cpp.
 {
     if ( _path.empty() )
         return;
     if ( _path.closed() )
         stream << "<polygon";
     else
         stream << "<polyline";
     stream << svgProperties( transform ) << std::endl;
     stream << "          points=\"";
     _path.flushSVGPoints( stream, transform );
     stream << "\" />" << std::endl;
 }
References _path, LibBoard::Path::closed(), LibBoard::Path::empty(), LibBoard::Path::flushSVGPoints(), and LibBoard::Shape::svgProperties().
Referenced by LibBoard::Rectangle::flushSVG(), and LibBoard::GouraudTriangle::flushSVG().
flushTikZ()
void LibBoard::Polyline::flushTikZ (std::ostream & stream, const TransformTikZ & transform) const virtual
Writes the TikZ code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Implements LibBoard::Shape.
Reimplemented in LibBoard::GouraudTriangle, LibBoard::QuadraticBezierCurve, LibBoard::Image, and LibBoard::Rectangle.
Definition at line 1850 of file Shapes.cpp.
 {
     if ( _path.empty() )
         return;
     stream << "\\path[" << tikzProperties(transform) << "] ";
     //stream << svgProperties( transform ) << std::endl;
     _path.flushTikZPoints( stream, transform );
     if ( _path.closed() )
         stream << " -- cycle";
     stream << ";" << std::endl;
 }
References _path, LibBoard::Path::closed(), LibBoard::Path::empty(), LibBoard::Path::flushTikZPoints(), and LibBoard::Shape::tikzProperties().
Referenced by LibBoard::Rectangle::flushTikZ().
name()
const std::string & LibBoard::Polyline::name () const virtual
Returns the generic name of the shape (e.g., Circle, Rectangle, etc.)
Returns
object name
Reimplemented from LibBoard::Shape.
Reimplemented in LibBoard::GouraudTriangle, LibBoard::QuadraticBezierCurve, LibBoard::Triangle, LibBoard::Image, and LibBoard::Rectangle.
Definition at line 1642 of file Shapes.cpp.
 {
     return _name;
 }
References _name.
operator<<()
Polyline & LibBoard::Polyline::operator<< (const Point & p)
Add a point to the polyline.
Parameters
p point to add
Returns
a polyline
Definition at line 1647 of file Shapes.cpp.
 {
     _path << p;
     return *this;
 }
References _path.
operator[]()
Point& LibBoard::Polyline::operator[] (const unsigned int n) inline
Returns the n-th point of the polyline.
Parameters
n index
Returns
n-th point
Definition at line 815 of file Board/Shapes.h.
{
     return _path[ n ];
   }
References _path.
rotate() [1/2]
Polyline & LibBoard::Polyline::rotate (double angle) virtual
Rotate the shape around its center.
Parameters
angle The rotation angle in radian.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Reimplemented in LibBoard::GouraudTriangle.
Definition at line 1673 of file Shapes.cpp.
 {
     _path.rotate( angle, center() );
     return *this;
 }
References _path, center(), and LibBoard::Path::rotate().
rotate() [2/2]
Polyline & LibBoard::Polyline::rotate (double angle, const Point & center) virtual
Rotate the shape around a given center of rotation.
Parameters
angle The rotation angle in radian.
center The center of rotation.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Reimplemented in LibBoard::GouraudTriangle.
Definition at line 1660 of file Shapes.cpp.
 {
     _path.rotate( angle, rotCenter );
     return *this;
 }
References _path, and LibBoard::Path::rotate().
rotated() [1/2]
Polyline LibBoard::Polyline::rotated (double angle) const
Parameters
angle angle
Returns
rotated polyline
Definition at line 1680 of file Shapes.cpp.
 {
     return Polyline(*this).rotate( angle, center() );
 }
References center(), and Polyline().
rotated() [2/2]
Polyline LibBoard::Polyline::rotated (double angle, const Point & center) const
Parameters
angle angle
center center
Returns
a polyline
Definition at line 1667 of file Shapes.cpp.
 {
     return Polyline(*this).rotate( angle, rotCenter );
 }
References Polyline().
scale() [1/2]
Shape & LibBoard::Polyline::scale (double s) virtual
Scale the shape along both axis.
Parameters
s The scale factor along both axis.
Returns
The shape itself.
Implements LibBoard::Shape.
Definition at line 1706 of file Shapes.cpp.
 {
     Polyline::scale( s, s );
     return *this;
 }
References scale().
scale() [2/2]
Shape & LibBoard::Polyline::scale (double sx, double sy) virtual
Scale the shape along the x an y axis.
Parameters
sx The scale factor along the x axis.
sy The scale factor along the y axis.
Returns
The shape itself.
Implements LibBoard::Shape.
Definition at line 1699 of file Shapes.cpp.
 {
     _path.scale( sx, sy );
     return *this;
 }
References _path, and LibBoard::Path::scale().
Referenced by scale().
scaleAll()
void LibBoard::Polyline::scaleAll (double s) virtual
Scales all the values (positions, dimensions, etc.) associated with the shape.
Parameters
s The scaling factor.
Implements LibBoard::Shape.
Reimplemented in LibBoard::GouraudTriangle, and LibBoard::Rectangle.
Definition at line 1725 of file Shapes.cpp.
 {
     _path.scaleAll( s );
 }
References _path, and LibBoard::Path::scaleAll().
scaled() [1/2]
Polyline LibBoard::Polyline::scaled (double s) const
Definition at line 1719 of file Shapes.cpp.
 {
     return static_cast<Polyline &>( Polyline(*this).scale( s, s ) );
 }
References Polyline().
scaled() [2/2]
Polyline LibBoard::Polyline::scaled (double sx, double sy) const
Parameters
sx sx
sy sy
Returns
polyline
Definition at line 1713 of file Shapes.cpp.
 {
     return static_cast<Polyline &>( Polyline(*this).scale( sx, sy ) );
 }
References Polyline().
translate()
Polyline & LibBoard::Polyline::translate (double dx, double dy) virtual
Translate the shape by a given offset.
Parameters
dx The x offset.
dy The y offset.
Returns
A reference to the shape itself.
Implements LibBoard::Shape.
Definition at line 1686 of file Shapes.cpp.
 {
     _path.translate( dx, dy );
     return *this;
 }
References _path, and LibBoard::Path::translate().
translated()
Polyline LibBoard::Polyline::translated (double dx, double dy) const
Parameters
dx dx
dy dy
Returns
polyline
Definition at line 1693 of file Shapes.cpp.
 {
     return Polyline(*this).translate( dx, dy );
 }
References Polyline().
Field Documentation
_name
const std::string LibBoard::Polyline::_name static private
The generic name of the shape.
Definition at line 902 of file Board/Shapes.h.
Referenced by name().
_path
Path LibBoard::Polyline::_path protected
Definition at line 905 of file Board/Shapes.h.
Referenced by LibBoard::Rectangle::bottomLeft(), LibBoard::Rectangle::bottomRight(), boundingBox(), center(), LibBoard::GouraudTriangle::center(), flushCairo(), LibBoard::Rectangle::flushCairo(), LibBoard::Image::flushCairo(), LibBoard::QuadraticBezierCurve::flushCairo(), flushFIG(), LibBoard::Rectangle::flushFIG(), LibBoard::Image::flushFIG(), LibBoard::GouraudTriangle::flushFIG(), flushPostscript(), LibBoard::QuadraticBezierCurve::flushPostscript(), LibBoard::GouraudTriangle::flushPostscript(), flushSVG(), LibBoard::Rectangle::flushSVG(), LibBoard::Image::flushSVG(), LibBoard::QuadraticBezierCurve::flushSVG(), LibBoard::GouraudTriangle::flushSVG(), flushTikZ(), LibBoard::Rectangle::flushTikZ(), LibBoard::Image::flushTikZ(), LibBoard::QuadraticBezierCurve::flushTikZ(), LibBoard::GouraudTriangle::GouraudTriangle(), LibBoard::Rectangle::height(), operator<<(), operator[](), rotate(), LibBoard::GouraudTriangle::rotate(), scale(), scaleAll(), LibBoard::Rectangle::scaleAll(), LibBoard::GouraudTriangle::scaleAll(), LibBoard::Rectangle::topLeft(), LibBoard::Rectangle::topRight(), translate(), LibBoard::Triangle::Triangle(), LibBoard::Rectangle::width(), LibBoard::Rectangle::x(), and LibBoard::Rectangle::y().
The documentation for this struct was generated from the following files:
Board/Shapes.h
Shapes.cpp