DGtal: LibBoard::Group Struct Reference
LibBoard::Group Struct Reference
A group of shapes. A group is basically a ShapeList except that when rendered in either an SVG of a FIG file, it is a true compound element.
#include <Board/ShapeList.h>
Public Member Functions
Group (int depthValue=-1)
Group (const Group &other)
~Group ()
const std::string & name () const
Shape & rotate (double angle, const Point &center)
Shape & rotate (double angle)
Group rotated (double angle, const Point &center)
Group rotated (double angle)
Shape & translate (double dx, double dy)
Group translated (double dx, double dy)
Shape & scale (double sx, double sy)
Shape & scale (double s)
Group scaled (double sx, double sy)
Group scaled (double s)
void setClippingRectangle (float x, float y, float width, float height)
void setClippingPath (const std::vector< Point > &points)
void setClippingPath (const Path &path)
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
Group & operator= (const Group &other)
Shape * clone () const
Rect boundingBox () const
Public Member Functions inherited from LibBoard::ShapeList
ShapeList (int depth=-1)
ShapeList (const ShapeList &other)
~ShapeList ()
ShapeList & clear ()
Point center () const
ShapeList rotated (double angle, const Point &center)
ShapeList rotated (double angle)
ShapeList translated (double dx, double dy)
ShapeList scaled (double sx, double sy)
ShapeList scaled (double s)
void scaleAll (double s)
virtual int minDepth () const
virtual int maxDepth () const
void shiftDepth (int shift)
ShapeList & operator= (const ShapeList &other)
ShapeList & operator<< (const Shape &shape)
ShapeList & operator+= (const Shape &shape)
ShapeList & insert (const Shape &shape, int depth)
ShapeList & dup (unsigned int copies=1)
template<typename T >
T & last (const unsigned int position=0)
Shape & last (const unsigned int position=0)
Shape & top ()
Public Member Functions inherited from LibBoard::Shape
Shape (DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, LineStyle style, const LineCap cap, const LineJoin join, int depth)
virtual ~Shape ()
bool filled () const
Shape & rotateDeg (double angle, const Point &center)
Shape & rotateDeg (double angle)
Rect bbox ()
Shape & operator-- ()
Shape & operator++ ()
int depth () const
virtual void depth (int)
const DGtal::Color & penColor () const
const DGtal::Color & fillColor () const
Private Attributes
Path _clippingPath
Static Private Attributes
static const std::string _name
static unsigned int _clippingCount = 0
Additional Inherited Members
Public Types inherited from LibBoard::Shape
enum LineCap { ButtCap = 0, RoundCap, SquareCap }
enum LineJoin { MiterJoin = 0, RoundJoin, BevelJoin }
enum LineStyle {
SolidStyle = 0, DashStyle, DotStyle, DashDotStyle,
DashDotDotStyle, DashDotDotDotStyle
}
Protected Member Functions inherited from LibBoard::ShapeList
void addShape (const Shape &shape, double scaleFactor)
void free ()
Protected Member Functions inherited from LibBoard::Shape
std::string svgProperties (const TransformSVG &transform) const
std::string postscriptProperties () const
void setCairoDashStyle (cairo_t *cr, LineStyle type) const
std::string tikzProperties (const TransformTikZ &transform) const
Protected Attributes inherited from LibBoard::ShapeList
std::vector< Shape * > _shapes
int _nextDepth
Protected Attributes inherited from LibBoard::Shape
int _depth
DGtal::Color _penColor
DGtal::Color _fillColor
double _lineWidth
LineStyle _lineStyle
LineCap _lineCap
LineJoin _lineJoin
Detailed Description
A group of shapes. A group is basically a ShapeList except that when rendered in either an SVG of a FIG file, it is a true compound element.
The Group structure.
Definition at line 183 of file ShapeList.h.
Constructor & Destructor Documentation
Group() [1/2]
LibBoard::Group::Group (int depthValue = -1) inline
Definition at line 185 of file ShapeList.h.
     : ShapeList( depthValue ), _clippingPath( true /* closed path */ ) { }
Referenced by clone(), rotated(), scaled(), and translated().
Group() [2/2]
LibBoard::Group::Group (const Group & other) inline
Definition at line 188 of file ShapeList.h.
     : ShapeList( other ), _clippingPath( other._clippingPath ) { }
~Group()
LibBoard::Group::~Group () inline
Definition at line 191 of file ShapeList.h.
 { };
Member Function Documentation
boundingBox()
Rect LibBoard::Group::boundingBox () const virtual
Returns the bounding box of the figure.
Returns
The rectangle of the bounding box.
Reimplemented from LibBoard::ShapeList.
Definition at line 680 of file ShapeList.cpp.
 {
     if ( _clippingPath.size() > 2 )
         return ShapeList::boundingBox() && _clippingPath.boundingBox();
     else
         return ShapeList::boundingBox();
 }
References _clippingPath, LibBoard::Path::boundingBox(), LibBoard::ShapeList::boundingBox(), and LibBoard::Path::size().
Referenced by flushFIG().
clone()
Shape * LibBoard::Group::clone () const virtual
Return a copy of the shape.
Returns
copye of the shape.
Reimplemented from LibBoard::ShapeList.
Definition at line 690 of file ShapeList.cpp.
 {
     return new Group( *this );
 }
References Group().
flushCairo()
void LibBoard::Group::flushCairo (cairo_t * cr, const TransformCairo & transform) const virtual
Writes the cairo code of the shape in a cairo drawing context according to a transform.
Parameters
cr The cairo drawing context.
transform A 2D transform to be applied.
Reimplemented from LibBoard::ShapeList.
Definition at line 661 of file ShapeList.cpp.
 {
     //todo
     //ShapeList::flushCairo( cr, transform );
 }
flushFIG()
void LibBoard::Group::flushFIG (std::ostream & stream, const TransformFIG & transform, std::map< DGtal::Color, int > & colormap) const virtual
Writes the FIG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
colormap A colormap.
Reimplemented from LibBoard::ShapeList.
Definition at line 620 of file ShapeList.cpp.
 {
     Rect box = boundingBox();
     stream << "# Begin group\n";
     stream << "6 "
     << transform.mapX( box.left ) << " "
     << transform.mapY( box.top ) << " "
     << transform.mapX( box.left + box.width ) << " "
     << transform.mapY( box.top - box.height ) << "\n";
     ShapeList::flushFIG( stream, transform, colormap );
     stream << "-6\n";
     stream << "# End Group\n";
 }
References boundingBox(), LibBoard::ShapeList::flushFIG(), LibBoard::Rect::height, LibBoard::Rect::left, LibBoard::Rect::top, and LibBoard::Rect::width.
flushPostscript()
void LibBoard::Group::flushPostscript (std::ostream & stream, const TransformEPS & transform) const virtual
Writes the EPS code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Reimplemented from LibBoard::ShapeList.
Definition at line 600 of file ShapeList.cpp.
 {
     if ( _clippingPath.size() > 2 ) {
         stream << "%%% Begin Clipped Group " << _clippingCount << "\n";
         stream << " gsave n ";
         _clippingPath.flushPostscript( stream, transform );
         stream << " 0 slw clip " << std::endl;
         ShapeList::flushPostscript( stream, transform );
         stream << " grestore\n";
         stream << "%%% End Clipped Group " << _clippingCount << "\n";
         ++ _clippingCount;
     } else {
         stream << "%%% Begin Group\n";
         ShapeList::flushPostscript( stream, transform );
         stream << "%%% End Group\n";
     }
 }
References _clippingCount, _clippingPath, LibBoard::Path::flushPostscript(), LibBoard::ShapeList::flushPostscript(), and LibBoard::Path::size().
flushSVG()
void LibBoard::Group::flushSVG (std::ostream & stream, const TransformSVG & transform) const virtual
Writes the SVG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Reimplemented from LibBoard::ShapeList.
Definition at line 637 of file ShapeList.cpp.
 {
     if ( _clippingPath.size() > 2 ) {
         stream << "<g clip-rule=\"nonzero\">\n"
         << " <clipPath id=\"LocalClipPath" << _clippingCount << "\">\n"
         << "  <path clip-rule=\"evenodd\"  d=\"";
         _clippingPath.flushSVGCommands( stream, transform );
         stream << "\" />\n";
         stream << " </clipPath>\n";
         stream << "<g clip-path=\"url(#LocalClipPath" << _clippingCount <<")\">\n";
         ++ _clippingCount;
         ShapeList::flushSVG( stream, transform );
         stream << "</g>\n";
         stream << "</g>\n";
     } else {
         stream << "<g>\n";
         ShapeList::flushSVG( stream, transform );
         stream << "</g>\n";
     }
 }
References _clippingCount, _clippingPath, LibBoard::ShapeList::flushSVG(), LibBoard::Path::flushSVGCommands(), and LibBoard::Path::size().
flushTikZ()
void LibBoard::Group::flushTikZ (std::ostream & stream, const TransformTikZ & transform) const virtual
Writes the TikZ code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Reimplemented from LibBoard::ShapeList.
Definition at line 670 of file ShapeList.cpp.
 {
   // FIXME: implement clipping
   stream << "\\begin{scope}\n";
   ShapeList::flushTikZ( stream, transform );
   stream << "\\end{scope}\n";
 }
References LibBoard::ShapeList::flushTikZ().
name()
const std::string & LibBoard::Group::name () const virtual
Returns the generic name of the shape (e.g., Circle, Rectangle, etc.)
Returns
object name
Reimplemented from LibBoard::ShapeList.
Definition at line 481 of file ShapeList.cpp.
 {
     return _name;
 }
References _name.
operator=()
Group & LibBoard::Group::operator= (const Group & other)
Definition at line 696 of file ShapeList.cpp.
 {
     ShapeList::operator=( other );
     return *this;
 }
References LibBoard::ShapeList::operator=().
rotate() [1/2]
Shape & LibBoard::Group::rotate (double angle) virtual
Rotate the shape around its center.
Parameters
angle The rotation angle in radian.
Returns
A reference to the shape itself.
Reimplemented from LibBoard::ShapeList.
Definition at line 495 of file ShapeList.cpp.
 {
     ShapeList::rotate( angle );
     _clippingPath.rotate( angle, center() );
     return (*this);
 }
References _clippingPath, LibBoard::ShapeList::center(), LibBoard::Path::rotate(), and LibBoard::ShapeList::rotate().
rotate() [2/2]
Shape & LibBoard::Group::rotate (double angle, const Point & center) virtual
Rotate the shape around a given center of rotation.
Parameters
angle The rotation angle in radian.
center The center of rotation.
Returns
A reference to the shape itself.
Reimplemented from LibBoard::ShapeList.
Definition at line 487 of file ShapeList.cpp.
 {
     ShapeList::rotate( angle, rotCenter );
     _clippingPath.rotate( angle, rotCenter );
     return (*this);
 }
References _clippingPath, LibBoard::Path::rotate(), and LibBoard::ShapeList::rotate().
rotated() [1/2]
Group LibBoard::Group::rotated (double angle)
Definition at line 542 of file ShapeList.cpp.
 {
     return static_cast<const Group &>( Group( *this ).rotate( angle ) );
 }
References Group().
rotated() [2/2]
Group LibBoard::Group::rotated (double angle, const Point & center)
Definition at line 536 of file ShapeList.cpp.
 {
     return static_cast<const Group &>( Group( *this ).rotate( angle, rotCenter ) );
 }
References Group().
scale() [1/2]
Shape & LibBoard::Group::scale (double s) virtual
Scale the shape along both axis.
Parameters
s The scale factor along both axis.
Returns
The shape itself.
Reimplemented from LibBoard::ShapeList.
Definition at line 524 of file ShapeList.cpp.
 {
     Point delta = _clippingPath.center() - center();
     delta *= s;
     _clippingPath.scale( s );
     ShapeList::scale( s );
     delta = ( center() + delta ) - _clippingPath.center();
     _clippingPath.translate( delta.x, delta.y );
     return (*this);
 }
References _clippingPath, LibBoard::Path::center(), LibBoard::ShapeList::center(), LibBoard::Path::scale(), LibBoard::ShapeList::scale(), LibBoard::Path::translate(), LibBoard::Point::x, and LibBoard::Point::y.
scale() [2/2]
Shape & LibBoard::Group::scale (double sx, double sy) virtual
Scale the shape along the x an y axis.
Parameters
sx The scale factor along the x axis.
sy The scale factor along the y axis.
Returns
The shape itself.
Reimplemented from LibBoard::ShapeList.
Definition at line 511 of file ShapeList.cpp.
 {
     Point delta = _clippingPath.center() - center();
     delta.x *= sx;
     delta.y *= sy;
     _clippingPath.scale( sx, sy );
     ShapeList::scale( sx, sy );
     delta = ( center() + delta ) - _clippingPath.center();
     _clippingPath.translate( delta.x, delta.y );
     return (*this);
 }
References _clippingPath, LibBoard::Path::center(), LibBoard::ShapeList::center(), LibBoard::Path::scale(), LibBoard::ShapeList::scale(), LibBoard::Path::translate(), LibBoard::Point::x, and LibBoard::Point::y.
scaled() [1/2]
Group LibBoard::Group::scaled (double s)
Definition at line 560 of file ShapeList.cpp.
 {
     return static_cast<const Group &>( Group( *this ).scale( s ) );
 }
References Group().
scaled() [2/2]
Group LibBoard::Group::scaled (double sx, double sy)
Definition at line 554 of file ShapeList.cpp.
 {
     return static_cast<const Group &>( Group( *this ).scale( sx, sy ) );
 }
References Group().
setClippingPath() [1/2]
void LibBoard::Group::setClippingPath (const Path & path)
Define a clipping path for the group.
Parameters
path A path.
Definition at line 589 of file ShapeList.cpp.
 {
     _clippingPath = path;
     _clippingPath.setClosed( true );
     if ( _clippingPath.size() > 1 ) {
         if ( _clippingPath[0] == _clippingPath[ _clippingPath.size() - 1 ] )
             _clippingPath.pop_back();
     }
 }
References _clippingPath, LibBoard::Path::pop_back(), LibBoard::Path::setClosed(), and LibBoard::Path::size().
setClippingPath() [2/2]
void LibBoard::Group::setClippingPath (const std::vector< Point > & points)
Define a clipping path for the group.
Parameters
points A path.
Definition at line 577 of file ShapeList.cpp.
 {
     _clippingPath.clear();
     std::vector<Point>::const_iterator it = points.begin();
     std::vector<Point>::const_iterator end = points.end();
     while ( it != end ) {
         _clippingPath <<  *it;
         ++it;
     }
 }
References _clippingPath, and LibBoard::Path::clear().
setClippingRectangle()
void LibBoard::Group::setClippingRectangle (float x, float y, float width, float height)
Define a clipping rectangle for the group.
Parameters
x lower corner of the rectangle
y lower corner of the rectangle
width width
height height
Definition at line 567 of file ShapeList.cpp.
 {
     _clippingPath.clear();
     _clippingPath << Point( x, y );
     _clippingPath << Point( x + width, y );
     _clippingPath << Point( x + width, y - height);
     _clippingPath << Point( x , y - height );
 }
References _clippingPath, and LibBoard::Path::clear().
translate()
Shape & LibBoard::Group::translate (double dx, double dy) virtual
Translate the shape by a given offset.
Parameters
dx The x offset.
dy The y offset.
Returns
A reference to the shape itself.
Reimplemented from LibBoard::ShapeList.
Definition at line 503 of file ShapeList.cpp.
 {
     ShapeList::translate( dx, dy );
     _clippingPath.translate( dx, dy );
     return (*this);
 }
References _clippingPath, LibBoard::Path::translate(), and LibBoard::ShapeList::translate().
translated()
Group LibBoard::Group::translated (double dx, double dy)
Definition at line 548 of file ShapeList.cpp.
 {
     return static_cast<const Group &>( Group( *this ).translate( dx, dy ) );
 }
References Group().
Field Documentation
_clippingCount
unsigned int LibBoard::Group::_clippingCount = 0 static private
Definition at line 273 of file ShapeList.h.
Referenced by flushPostscript(), and flushSVG().
_clippingPath
Path LibBoard::Group::_clippingPath private
Definition at line 272 of file ShapeList.h.
Referenced by boundingBox(), flushPostscript(), flushSVG(), rotate(), scale(), setClippingPath(), setClippingRectangle(), and translate().
_name
const std::string LibBoard::Group::_name static private
The generic name of the shape.
Definition at line 271 of file ShapeList.h.
Referenced by name().
The documentation for this struct was generated from the following files:
ShapeList.h
ShapeList.cpp