DGtal: testContainerTraits.cpp File Reference
testContainerTraits.cpp File Reference
DGtal Test Files
#include <vector>
#include <list>
#include <deque>
#include <set>
#include <map>
#include <boost/unordered_set.hpp>
#include <boost/unordered_map.hpp>
#include <forward_list>
#include <array>
#include <unordered_set>
#include <unordered_map>
#include "DGtal/base/Common.h"
#include "DGtal/base/ContainerTraits.h"
#include "DGtalCatch.h"
Functions
TEST_CASE ("int container traits", "[int][traits]")
TEST_CASE ("std::vector<> container traits", "[vector][traits]")
TEST_CASE ("std::list<> container traits", "[list][traits]")
TEST_CASE ("std::deque<> container traits", "[deque][traits]")
TEST_CASE ("std::forward_list<> container traits", "[forward_list][traits]")
TEST_CASE ("std::array<> container traits", "[array][traits]")
TEST_CASE ("std::set<> container traits", "[set][traits]")
TEST_CASE ("std::multiset<> container traits", "[multiset][traits]")
TEST_CASE ("std::map<> container traits", "[map][traits]")
TEST_CASE ("std::multimap<> container traits", "[multimap][traits]")
TEST_CASE ("boost::unordered_set<> container traits", "[unordered_set][traits]")
TEST_CASE ("boost::unordered_map<> container traits", "[unordered_map][traits]")
TEST_CASE ("boost::unordered_multiset<> container traits", "[unordered_multiset][traits]")
TEST_CASE ("boost::unordered_multimap<> container traits", "[unordered_multimap][traits]")
TEST_CASE ("std::unordered_set<> container traits", "[unordered_set][traits]")
TEST_CASE ("std::unordered_multiset<> container traits", "[unordered_multiset][traits]")
TEST_CASE ("std::unordered_map<> container traits", "[unordered_map][traits]")
TEST_CASE ("std::unordered_multimap<> container traits", "[unordered_multimap][traits]")
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2015/08/28
This file is part of the DGtal library
Definition in file testContainerTraits.cpp.
Function Documentation
TEST_CASE() [1/18]
TEST_CASE ("boost::unordered_map<> container traits" , "" [unordered_map][traits])
Definition at line 240 of file testContainerTraits.cpp.
 {
   typedef boost::unordered_map<int,int> Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == true) );
       REQUIRE( (IsSequenceContainer< Container >::value == false) );
       REQUIRE( (IsAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == false) );
     }
 }
References REQUIRE(), and SECTION().
TEST_CASE() [2/18]
TEST_CASE ("boost::unordered_multimap<> container traits" , "" [unordered_multimap][traits])
Definition at line 274 of file testContainerTraits.cpp.
 {
   typedef boost::unordered_multimap<int,int> Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == true) );
       REQUIRE( (IsSequenceContainer< Container >::value == false) );
       REQUIRE( (IsAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == true) );
     }
 }
References REQUIRE(), and SECTION().
TEST_CASE() [3/18]
TEST_CASE ("boost::unordered_multiset<> container traits" , "" [unordered_multiset][traits])
Definition at line 257 of file testContainerTraits.cpp.
 {
   typedef boost::unordered_multiset<int> Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == true) );
       REQUIRE( (IsSequenceContainer< Container >::value == false) );
       REQUIRE( (IsAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == true) );
     }
 }
References REQUIRE(), and SECTION().
TEST_CASE() [4/18]
TEST_CASE ("boost::unordered_set<> container traits" , "" [unordered_set][traits])
Definition at line 223 of file testContainerTraits.cpp.
 {
   typedef boost::unordered_set<int> Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == true) );
       REQUIRE( (IsSequenceContainer< Container >::value == false) );
       REQUIRE( (IsAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == false) );
     }
 }
References REQUIRE(), and SECTION().
TEST_CASE() [5/18]
TEST_CASE ("int container traits" , "" [int][traits])
Examples
doc-examples/exampleCatch.cpp.
Definition at line 53 of file testContainerTraits.cpp.
 {
   typedef int Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == false) );
       REQUIRE( (IsSequenceContainer< Container >::value == false) );
       REQUIRE( (IsAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == false) );
     }
 }
References REQUIRE(), and SECTION().
TEST_CASE() [6/18]
TEST_CASE ("std::array<> container traits" , "" [array][traits])
Definition at line 138 of file testContainerTraits.cpp.
 {
   typedef std::array<int, 10> Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == true) );
       REQUIRE( (IsSequenceContainer< Container >::value == true) );
       REQUIRE( (IsAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == false) );
     }
 }
References REQUIRE(), and SECTION().
TEST_CASE() [7/18]
TEST_CASE ("std::deque<> container traits" , "" [deque][traits])
Definition at line 104 of file testContainerTraits.cpp.
 {
   typedef std::deque<int> Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == true) );
       REQUIRE( (IsSequenceContainer< Container >::value == true) );
       REQUIRE( (IsAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == false) );
     }
 }
References REQUIRE(), and SECTION().
TEST_CASE() [8/18]
TEST_CASE ("std::forward_list<> container traits" , "" [forward_list][traits])
Definition at line 121 of file testContainerTraits.cpp.
 {
   typedef std::forward_list<int> Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == true) );
       REQUIRE( (IsSequenceContainer< Container >::value == true) );
       REQUIRE( (IsAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == false) );
     }
 }
References REQUIRE(), and SECTION().
TEST_CASE() [9/18]
TEST_CASE ("std::list<> container traits" , "" [list][traits])
Definition at line 87 of file testContainerTraits.cpp.
 {
   typedef std::list<int> Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == true) );
       REQUIRE( (IsSequenceContainer< Container >::value == true) );
       REQUIRE( (IsAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == false) );
     }
 }
References REQUIRE(), and SECTION().
TEST_CASE() [10/18]
TEST_CASE ("std::map<> container traits" , "" [map][traits])
Definition at line 189 of file testContainerTraits.cpp.
 {
   typedef std::map<int,int> Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == true) );
       REQUIRE( (IsSequenceContainer< Container >::value == false) );
       REQUIRE( (IsAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == false) );
     }
 }
References REQUIRE(), and SECTION().
TEST_CASE() [11/18]
TEST_CASE ("std::multimap<> container traits" , "" [multimap][traits])
Definition at line 206 of file testContainerTraits.cpp.
 {
   typedef std::multimap<int,int> Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == true) );
       REQUIRE( (IsSequenceContainer< Container >::value == false) );
       REQUIRE( (IsAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == true) );
     }
 }
References REQUIRE(), and SECTION().
TEST_CASE() [12/18]
TEST_CASE ("std::multiset<> container traits" , "" [multiset][traits])
Definition at line 172 of file testContainerTraits.cpp.
 {
   typedef std::multiset<int> Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == true) );
       REQUIRE( (IsSequenceContainer< Container >::value == false) );
       REQUIRE( (IsAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == true) );
     }
 }
References REQUIRE(), and SECTION().
TEST_CASE() [13/18]
TEST_CASE ("std::set<> container traits" , "" [set][traits])
Definition at line 155 of file testContainerTraits.cpp.
 {
   typedef std::set<int> Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == true) );
       REQUIRE( (IsSequenceContainer< Container >::value == false) );
       REQUIRE( (IsAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == false) );
     }
 }
References REQUIRE(), and SECTION().
TEST_CASE() [14/18]
TEST_CASE ("std::unordered_map<> container traits" , "" [unordered_map][traits])
Definition at line 324 of file testContainerTraits.cpp.
 {
   typedef std::unordered_map<int,int> Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == true) );
       REQUIRE( (IsSequenceContainer< Container >::value == false) );
       REQUIRE( (IsAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == false) );
     }
 }
References REQUIRE(), and SECTION().
TEST_CASE() [15/18]
TEST_CASE ("std::unordered_multimap<> container traits" , "" [unordered_multimap][traits])
Definition at line 341 of file testContainerTraits.cpp.
 {
   typedef std::unordered_multimap<int,int> Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == true) );
       REQUIRE( (IsSequenceContainer< Container >::value == false) );
       REQUIRE( (IsAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == true) );
     }
 }
References REQUIRE(), and SECTION().
TEST_CASE() [16/18]
TEST_CASE ("std::unordered_multiset<> container traits" , "" [unordered_multiset][traits])
Definition at line 307 of file testContainerTraits.cpp.
 {
   typedef std::unordered_multiset<int> Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == true) );
       REQUIRE( (IsSequenceContainer< Container >::value == false) );
       REQUIRE( (IsAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == true) );
     }
 }
References REQUIRE(), and SECTION().
TEST_CASE() [17/18]
TEST_CASE ("std::unordered_set<> container traits" , "" [unordered_set][traits])
Definition at line 291 of file testContainerTraits.cpp.
 {
   typedef std::unordered_set<int> Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == true) );
       REQUIRE( (IsSequenceContainer< Container >::value == false) );
       REQUIRE( (IsAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == true) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == false) );
     }
 }
References REQUIRE(), and SECTION().
TEST_CASE() [18/18]
TEST_CASE ("std::vector<> container traits" , "" [vector][traits])
Definition at line 70 of file testContainerTraits.cpp.
 {
   typedef std::vector<int> Container;
   SECTION( "Checking container traits" )
     {
       REQUIRE( (IsContainer< Container >::value == true) );
       REQUIRE( (IsSequenceContainer< Container >::value == true) );
       REQUIRE( (IsAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsOrderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUnorderedAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsSimpleAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsPairAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsUniqueAssociativeContainer< Container >::value == false) );
       REQUIRE( (IsMultipleAssociativeContainer< Container >::value == false) );
     }
 }
References REQUIRE(), and SECTION().