DGtal: testDigitalMetricAdapter.cpp File Reference
testDigitalMetricAdapter.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "ConfigTest.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/geometry/volumes/distance/CDigitalMetricSpace.h"
#include "DGtal/geometry/volumes/distance/DigitalMetricAdapter.h"
Functions
bool testConcepts ()
bool testVal ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systemes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2014/07/02
Functions for testing class DigitalMetricAdapter.
This file is part of the DGtal library.
Definition in file testDigitalMetricAdapter.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 93 of file testDigitalMetricAdapter.cpp.
 {
   trace.beginBlock ( "Testing class DigitalMetricAdapter" );
   trace.info() << "Args:";
   for ( int i = 0; i < argc; ++i )
     trace.info() << " " << argv[ i ];
   trace.info() << endl;
   bool res = testConcepts() && testVal(); // && ... other tests
   trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
   trace.endBlock();
   return res ? 0 : 1;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testConcepts(), testVal(), and DGtal::trace.
testConcepts()
bool testConcepts ()
Example of a test. To be completed.
Definition at line 49 of file testDigitalMetricAdapter.cpp.
 {
   unsigned int nbok = 0;
   unsigned int nb = 0;
   typedef Z2i::L2Metric L2;
   L2 l2;
   typedef DigitalMetricAdapter<L2> Adapted;
   Adapted adapted(l2);
   BOOST_CONCEPT_ASSERT(( concepts::CDigitalMetricSpace<Adapted> ));
   return nbok == nb;
 }
Referenced by main().
testVal()
bool testVal ()
Example of a test. To be completed.
Definition at line 67 of file testDigitalMetricAdapter.cpp.
 {
   unsigned int nbok = 0;
   unsigned int nb = 0;
   typedef Z2i::L2Metric L2;
   L2 l2;
   typedef DigitalMetricAdapter<L2> Adapted;
   Adapted adapted(l2);
   BOOST_CONCEPT_ASSERT(( concepts::CDigitalMetricSpace<Adapted> ));
   L2::Point a(0,0), b(5,2);
   Adapted::Value d = adapted(a,b);
   trace.info() << "distance= "<< l2(a,b)<< " and adapted= "<< d << std::endl;
   nbok += (d == 6) ? 1 : 0;
   nb++;
   trace.info() << "(" << nbok << "/" << nb << ") "
                << std::endl;
   return nbok == nb;
 }
References DGtal::Trace::info(), and DGtal::trace.
Referenced by main().