DGtal: testSTLMapToVertexMapAdapter.cpp File Reference
testSTLMapToVertexMapAdapter.cpp File Reference
DGtal Test Files
#include <iostream>
#include <vector>
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/base/Common.h"
#include "DGtal/graph/CVertexMap.h"
#include "DGtal/graph/STLMapToVertexMapAdapter.h"
#include <map>
Functions
bool testMapToVertexMap ()
int main (int, char **)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jérémy Gaillard (jerem.nosp@m.y.ga.nosp@m.illar.nosp@m.d@in.nosp@m.sa-ly.nosp@m.on.f.nosp@m.r) Institut National des Sciences Appliquées - INSA, France
Date
2012/07/12
Functions for testing class STLMapToVertexMapAdapter.
This file is part of the DGtal library.
Definition in file testSTLMapToVertexMapAdapter.cpp.
Function Documentation
main()
int main (int , char **)
Definition at line 77 of file testSTLMapToVertexMapAdapter.cpp.
 {
   trace.beginBlock ( "Testing class STLMapToVertexMapAdapter" );
   bool res = testMapToVertexMap(); // && ... other tests
   trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
   trace.endBlock();
   return res ? 0 : 1;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), testMapToVertexMap(), and DGtal::trace.
testMapToVertexMap()
bool testMapToVertexMap ()
This file tests the adaptation of a STL map to a vertex map.
Definition at line 57 of file testSTLMapToVertexMapAdapter.cpp.
 {
   typedef  Z2i::Point Point;
   typedef  Z2i::Point Vertex;
   typedef int Value;
   typedef map<Vertex, Value> Map;
   typedef STLMapToVertexMapAdapter<Map> VertexMap;
   VertexMap myMap;
   BOOST_CONCEPT_ASSERT((CVertexMap<VertexMap>));
   myMap.setValue(Point(1,1), 10);
   myMap.setValue(Point(2,3), 2);
   return (myMap(Point(1,1)) == 10 && myMap(Point(2,3)) == 2);
 }
Referenced by main().