DGtal: testPNMRawWriter.cpp File Reference
testPNMRawWriter.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/images/ImageSelector.h"
#include "DGtal/io/colormaps/GrayscaleColorMap.h"
#include "DGtal/io/colormaps/HueShadeColorMap.h"
#include "DGtal/io/colormaps/GradientColorMap.h"
#include "DGtal/io/colormaps/ColorBrightnessColorMap.h"
#include "DGtal/io/colormaps/RandomColorMap.h"
#include "DGtal/io/colormaps/BasicColorToScalarFunctors.h"
#include "DGtal/base/BasicFunctors.h"
#include "DGtal/io/writers/PGMWriter.h"
#include "DGtal/io/writers/PPMWriter.h"
#include "DGtal/io/readers/PGMReader.h"
#include "DGtal/io/writers/RawWriter.h"
#include "DGtal/io/boards/Board2D.h"
Functions
bool testPNMWriter ()
bool testRWIssue254 ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2010/07/22
Functions for testing class PNMWriter.
This file is part of the DGtal library.
Definition in file testPNMRawWriter.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 157 of file testPNMRawWriter.cpp.
 {
   trace.beginBlock ( "Testing class PNMWriter" );
   trace.info() << "Args:";
   for ( int i = 0; i < argc; ++i )
     trace.info() << " " << argv[ i ];
   trace.info() << std::endl;
   bool res = testPNMWriter() && testRWIssue254(); // && ... other tests
   trace.emphase() << ( res ? "Passed." : "Error." ) << std::endl;
   trace.endBlock();
   return res ? 0 : 1;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testPNMWriter(), testRWIssue254(), and DGtal::trace.
testPNMWriter()
bool testPNMWriter ()
Example of a test. To be completed.
Definition at line 60 of file testPNMRawWriter.cpp.
 {
   trace.beginBlock ( "Testing block ..." );
   typedef SpaceND<2> TSpace;
   typedef TSpace::Point Point;
   typedef HyperRectDomain<TSpace> Domain;
   typedef HueShadeColorMap<unsigned char> Hue;
   typedef HueShadeColorMap<unsigned char,2> HueTwice;
   typedef GrayscaleColorMap<unsigned char> Gray;
   // Gradient using the "Jet" preset.
   typedef GradientColorMap<unsigned char, CMAP_JET > Jet;
   // Gradient from black to red.
   const int BlackColor = DGTAL_RGB2INT(0,0,0);
   const int RedColor = DGTAL_RGB2INT(255,0,0);
   typedef GradientColorMap< unsigned char, CMAP_CUSTOM, BlackColor, RedColor > RedShade1;
   // Gradient from black to red, using a ColorBrightnessColorMap.
   typedef ColorBrightnessColorMap< unsigned char, RedColor > RedShade2;
   Point a ( 1, 1);
   Point b ( 16, 16);
   typedef ImageSelector<Domain, unsigned char>::Type Image;
   Image image(Domain(a,b));
   for(unsigned int i=0 ; i < 256; i++)
     image[i] = i;
   PPMWriter<Image,Hue>::exportPPM("export-hue.ppm",image, Hue(0,255) );
   PPMWriter<Image,HueTwice>::exportPPM("export-hue-twice.ppm",image,HueTwice(0,255));
   PGMWriter<Image>::exportPGM("export-hue-twice.pgm",image);
   PPMWriter<Image,Gray>::exportPPM("export-gray.ppm",image, Gray(0,255));
   PPMWriter<Image,Jet>::exportPPM("export-jet.ppm",image,Jet(0,255));
   PPMWriter<Image,RedShade1>::exportPPM("export-red1.ppm",image,RedShade1(0,255));
   PPMWriter<Image,RedShade2>::exportPPM("export-red2.ppm",image,RedShade2(0,255));
   //TestingFunctor
   typedef DGtal::functors::Composer< Jet, functors::RedChannel, unsigned char> RedFunctor;
   Jet jf( 0, 255 );
   functors::RedChannel rf;
   RedFunctor redFunctor( jf, rf );
   PGMWriter<Image, RedFunctor>::exportPGM("export-jet-red.pgm", image, redFunctor);
   //test Raw export
   RawWriter<Image>::exportRaw8("export-hue-twice.raw",image);
   //test Image export with libboard
   Board2D  board;
   board.setUnit(LibBoard::Board::UCentimeter);
   Display2DFactory::drawImage<HueTwice>(board, image, (unsigned char)0, (unsigned char)255);
   board.saveSVG("export-hue-twice.svg");
   trace.endBlock();
   return true;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::PGMWriter< TImage, TFunctor >::exportPGM(), DGtal::PPMWriter< TImage, TFunctor >::exportPPM(), DGtal::RawWriter< TImage, TFunctor >::exportRaw8(), image(), LibBoard::Board::saveSVG(), LibBoard::Board::setUnit(), DGtal::trace, and LibBoard::Board::UCentimeter.
Referenced by main().
testRWIssue254()
bool testRWIssue254 ()
Definition at line 117 of file testPNMRawWriter.cpp.
 {
    trace.beginBlock ( "Testing R/W on PPM Writer (issue 254) ..." );
   typedef SpaceND<2> TSpace;
   typedef TSpace::Point Point;
   typedef HyperRectDomain<TSpace> Domain;
   Point a ( 0, 0);
   Point b ( 15, 15);
   typedef ImageSelector<Domain, unsigned char>::Type Image;
   Domain domain(a,b);
   Image image(domain);
   for(unsigned int i=0 ; i < 256; i++)
     image[i] = i;
   PGMWriter<Image>::exportPGM("export-gray-first.pgm",image);
   Image imageRead = PGMReader<Image>::importPGM("export-gray-first.pgm");
   PGMWriter<Image>::exportPGM("export-gray-second.pgm",imageRead);
   trace.info() << image<<std::endl;
   trace.info() << imageRead<<std::endl;
   bool ok = true;
   for(Image::Domain::ConstIterator it = image.domain().begin(),
         itend = image.domain().end();
       it != itend;
       ++it)
     ok = (image(*it) == imageRead(*it));
   trace.endBlock();
   return ok;
 }
References DGtal::Trace::beginBlock(), domain, DGtal::Trace::endBlock(), DGtal::PGMWriter< TImage, TFunctor >::exportPGM(), image(), DGtal::PGMReader< TImageContainer, TFunctor >::importPGM(), DGtal::Trace::info(), and DGtal::trace.
Referenced by main().