DGtal: testEigenSolver.cpp File Reference
testEigenSolver.cpp File Reference
DGtal Test Files
#include <iostream>
#include <vector>
#include <list>
#include "DGtal/base/Common.h"
#include "ConfigTest.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/math/linalg/CLinearAlgebraSolver.h"
#include "DGtal/math/linalg/CSparseMatrix.h"
#include "DGtal/math/linalg/CDynamicMatrix.h"
#include "DGtal/math/linalg/CDenseVector.h"
#include "DGtal/math/linalg/CDynamicVector.h"
#include "DGtal/math/linalg/EigenSupport.h"
Functions
bool testEigenSolverConcepts ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Pierre Gueth (pierr.nosp@m.e.gu.nosp@m.eth@l.nosp@m.iris.nosp@m..cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systemes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2014/03/26
Functions for testing class EigenSolver.
This file is part of the DGtal library.
Definition in file testEigenSolver.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 81 of file testEigenSolver.cpp.
 {
   trace.beginBlock ( "Testing class EigenSolver" );
   trace.info() << "Args:";
   for ( int i = 0; i < argc; ++i )
     trace.info() << " " << argv[ i ];
   trace.info() << endl;
   bool res = testEigenSolverConcepts();
   trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
   trace.endBlock();
   return res ? 0 : 1;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testEigenSolverConcepts(), and DGtal::trace.
testEigenSolverConcepts()
bool testEigenSolverConcepts ()
Test eigen linear algebra concepts
Definition at line 55 of file testEigenSolver.cpp.
 {
     typedef EigenLinearAlgebraBackend LAB;
     typedef LAB::DenseVector Vector;
     typedef LAB::SparseMatrix Matrix;
     typedef LAB::Triplet Triplet;
     typedef std::vector<Triplet> TripletsVector;
     typedef std::list<Triplet> TripletsList;
     BOOST_CONCEPT_ASSERT(( concepts::CDynamicVector<Vector> ));
     BOOST_CONCEPT_ASSERT(( concepts::CDenseVector<Vector> ));
     BOOST_CONCEPT_ASSERT(( concepts::CDynamicMatrix<Matrix> ));
     BOOST_CONCEPT_ASSERT(( concepts::CSparseMatrix<Matrix, TripletsVector::const_iterator> ));
     BOOST_CONCEPT_ASSERT(( concepts::CSparseMatrix<Matrix, TripletsList::const_iterator> ));
     BOOST_CONCEPT_ASSERT(( concepts::CLinearAlgebraSolver<LAB::SolverSimplicialLLT, Vector, Matrix> ));
     BOOST_CONCEPT_ASSERT(( concepts::CLinearAlgebraSolver<LAB::SolverSimplicialLDLT, Vector, Matrix> ));
     BOOST_CONCEPT_ASSERT(( concepts::CLinearAlgebraSolver<LAB::SolverConjugateGradient, Vector, Matrix> ));
     BOOST_CONCEPT_ASSERT(( concepts::CLinearAlgebraSolver<LAB::SolverBiCGSTAB, Vector, Matrix> ));
     BOOST_CONCEPT_ASSERT(( concepts::CLinearAlgebraSolver<LAB::SolverSparseLU, Vector, Matrix> ));
     BOOST_CONCEPT_ASSERT(( concepts::CLinearAlgebraSolver<LAB::SolverSparseQR, Vector, Matrix> ));
     return true;
 }
Referenced by main().