DGtal: testParDirCollapse.cpp File Reference
testParDirCollapse.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "ConfigTest.h"
#include "DGtalCatch.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/topology/CubicalComplex.h"
#include "DGtal/topology/ParDirCollapse.h"
#include "DGtal/shapes/GaussDigitizer.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/shapes/EuclideanShapesDecorator.h"
#include "DGtal/shapes/parametric/Flower2D.h"
Functions
template<typename CC , typename KSpace >
void getComplex (CC &complex, KSpace &K)
TEST_CASE ("Testing ParDirCollapse")
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Kacper Pluta (kacpe.nosp@m.r.pl.nosp@m.uta@e.nosp@m.siee.nosp@m..fr) Laboratoire d'Informatique Gaspard-Monge - LIGM, France
Date
2016/01/16
Functions for testing class ParDirCollapse.
This file is part of the DGtal library.
Definition in file testParDirCollapse.cpp.
Function Documentation
getComplex()
template<typename CC , typename KSpace > void getComplex (CC & complex, KSpace & K)
Definition at line 55 of file testParDirCollapse.cpp.
 {
   typedef Flower2D< Space > MyEuclideanShape;
   MyEuclideanShape shape( RealPoint( 0.0, 0.0 ), 16, 5, 5, M_PI_2/2. );
   typedef GaussDigitizer< Space, MyEuclideanShape > MyGaussDigitizer;
   MyGaussDigitizer digShape;
   digShape.attach( shape );
   digShape.init ( shape.getLowerBound(), shape.getUpperBound(), 1.0 );
   Domain domainShape = digShape.getDomain();
   DigitalSet aSet( domainShape );
   Shapes<Domain>::digitalShaper( aSet, digShape );
   K.init ( domainShape.lowerBound(), domainShape.upperBound(), true );
   complex.clear();
   complex.construct ( aSet );
 }
References DGtal::GaussDigitizer< TSpace, TEuclideanShape >::attach(), DGtal::CubicalComplex< TKSpace, TCellContainer >::clear(), DGtal::CubicalComplex< TKSpace, TCellContainer >::construct(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), K, DGtal::HyperRectDomain< TSpace >::lowerBound(), and DGtal::HyperRectDomain< TSpace >::upperBound().
TEST_CASE()
TEST_CASE ("Testing ParDirCollapse")
Definition at line 73 of file testParDirCollapse.cpp.
 {
   typedef map<Cell, CubicalCellData>   Map;
   typedef CubicalComplex< KSpace, Map >     CC;
   KSpace K;
   CC complex ( K );
   ParDirCollapse < CC > thinning ( K );
   SECTION("Testing the basic algorithm of ParDirCollapse")
     {
       getComplex< CC, KSpace > ( complex, K );
       int eulerBefore = complex.euler();
       thinning.attach ( &complex );
       REQUIRE( ( thinning.eval ( 2 ) != 0 ) );
       REQUIRE( (eulerBefore == complex.euler()) );
     }
   SECTION("Testing ParDirCollapse::collapseSurface")
     {
       getComplex< CC, KSpace > ( complex, K );
       int eulerBefore = complex.euler();
       thinning.attach ( &complex );
       thinning.collapseSurface ();
       REQUIRE( (eulerBefore == complex.euler()) );
     }
   SECTION("Testing ParDirCollapse::collapseIsthmus")
     {
       getComplex< CC, KSpace > ( complex, K );
       int eulerBefore = complex.euler();
       thinning.attach ( &complex );
       thinning.collapseIsthmus ();
       REQUIRE( (eulerBefore == complex.euler()) );
     }
 }
References DGtal::ParDirCollapse< CC >::attach(), DGtal::ParDirCollapse< CC >::collapseIsthmus(), DGtal::ParDirCollapse< CC >::collapseSurface(), DGtal::CubicalComplex< TKSpace, TCellContainer >::euler(), DGtal::ParDirCollapse< CC >::eval(), K, REQUIRE(), and SECTION().