DGtal: testLinearAlgebra.cpp File Reference
testLinearAlgebra.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/LinearAlgebra.h"
Functions
bool testLinearAlgebra ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2010/12/14
Functions for testing class LinearAlgebra.
This file is part of the DGtal library.
Definition in file testLinearAlgebra.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 77 of file testLinearAlgebra.cpp.
 {
   trace.beginBlock ( "Testing class LinearAlgebra" );
   trace.info() << "Args:";
   for ( int i = 0; i < argc; ++i )
     trace.info() << " " << argv[ i ];
   trace.info() << endl;
   bool res = testLinearAlgebra(); // && ... other tests
   trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
   trace.endBlock();
   return res ? 0 : 1;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testLinearAlgebra(), and DGtal::trace.
testLinearAlgebra()
bool testLinearAlgebra ()
Example of a test. To be completed.
Definition at line 47 of file testLinearAlgebra.cpp.
 {
   unsigned int nbok = 0;
   unsigned int nb = 0;
   trace.beginBlock ( "Testing block ..." );
   typedef SpaceND<2,DGtal::int32_t> Space2Int;
   typedef Space2Int::Point Point;
   typedef SpaceND<2,DGtal::int64_t > Space2LongInt;
   typedef Space2LongInt::Point Pointlong;
   Point a,b;
   Pointlong c,d;
   LinearAlgebra<Space2Int>::determinant(a,b);
   LinearAlgebra<Space2LongInt>::determinant(c,d);
   nbok += true ? 1 : 0;
   nb++;
   trace.info() << "(" << nbok << "/" << nb << ") "
          << "true == true" << std::endl;
   trace.endBlock();
   return nbok == nb;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.
Referenced by main().