DGtal: testProgressBar.cpp File Reference
testProgressBar.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
Functions
bool testProgressBar ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2011/12/03
Functions for testing class ProgressBar.
This file is part of the DGtal library.
Definition in file testProgressBar.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 71 of file testProgressBar.cpp.
 {
   trace.beginBlock ( "Testing class ProgressBar" );
   trace.info() << "Args:";
   for ( int i = 0; i < argc; ++i )
     trace.info() << " " << argv[ i ];
   trace.info() << endl;
   bool res = testProgressBar(); // && ... other tests
   trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
   trace.endBlock();
   return res ? 0 : 1;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testProgressBar(), and DGtal::trace.
testProgressBar()
bool testProgressBar ()
Example of a test. To be completed.
Running a progressbar
Definition at line 50 of file testProgressBar.cpp.
 {
   trace.beginBlock ( "Testing progress ..." );
   for(unsigned int i=0; i <= 10  ; ++i)
     {
       trace.progressBar(i,10);
 #ifdef UNIX
       usleep(50000);
 #endif
     }
   trace.info() << std::endl;
   trace.endBlock();
  return true;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::Trace::progressBar(), and DGtal::trace.
Referenced by main().