DGtal: testMetrics-benchmark.cpp File Reference
testMetrics-benchmark.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/geometry/volumes/distance/ExactPredicateLpSeparableMetric.h"
#include "DGtal/geometry/volumes/distance/InexactPredicateLpSeparableMetric.h"
#include <boost/lexical_cast.hpp>
Functions
template<int p>
bool runATest (unsigned int maxTest)
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2012/11/03
Functions for testing class Metrics-benchmark.
This file is part of the DGtal library.
Definition in file testMetrics-benchmark.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 97 of file testMetrics-benchmark.cpp.
 {
   trace.beginBlock ( "Testing class Metrics-benchmark" );
   trace.info() << "Args:";
   for ( int i = 0; i < argc; ++i )
     trace.info() << " " << argv[ i ];
   trace.info() << endl;
   bool res = runATest<2>(1000000) &&
     runATest<4>(10000000);
     runATest<6>(1000000);
   trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
   trace.endBlock();
   return res ? 0 : 1;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.
runATest()
template<int p> bool runATest (unsigned int maxTest)
Definition at line 47 of file testMetrics-benchmark.cpp.
 {
   ExactPredicateLpSeparableMetric<Z3i::Space, p> exactMetric;
   InexactPredicateLpSeparableMetric<Z3i::Space> approxMetric(p);
   double sum=0.0, d=0,d2=0, MSE=0;
   std::string txt = "Testing Exponent" +   boost::lexical_cast<string>(p);
   DGtal::Dimension dim = 1000;
   trace.beginBlock(txt);
   trace.beginBlock("Exact Predicate run");
   for(unsigned int i=0; i< maxTest; ++i)
     {
       Z3i::Point P( rand() % dim,rand() % dim ,rand() % dim );
       Z3i::Point Q( rand() % dim, rand() % dim, rand() % dim);
       sum += exactMetric(P,Q);
     }
   trace.endBlock();
   trace.beginBlock("Inexact Predicate run");
  for(unsigned int i=0; i< maxTest; ++i)
     {
       Z3i::Point P( rand() % dim,rand() % dim ,rand() % dim );
       Z3i::Point Q( rand() % dim, rand() % dim, rand() % dim);
       sum += approxMetric(P,Q);
     }
   trace.endBlock();
   trace.beginBlock("Both with comparison run");
   for(unsigned int i=0; i< maxTest; ++i)
     {
       Z3i::Point P( rand() % dim,rand() % dim ,rand() % dim );
       Z3i::Point Q( rand() % dim, rand() % dim, rand() % dim);
       d = exactMetric(P,Q);
       d2 = approxMetric(P,Q);
       MSE += (d-d2)*(d-d2);
     }
   trace.endBlock();
   trace.info() << "Mean Square Error = "<<MSE<<std::endl;
   trace.endBlock();
   return true;
 }
References DGtal::Trace::beginBlock(), dim(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.