DGtal: testTriangulatedSurface.cpp File Reference
testTriangulatedSurface.cpp File Reference
DGtal Test Files
#include <iostream>
#include <algorithm>
#include "DGtal/base/Common.h"
#include "ConfigTest.h"
#include "DGtalCatch.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/kernel/PointVector.h"
#include "DGtal/graph/CUndirectedSimpleGraph.h"
#include "DGtal/graph/BreadthFirstVisitor.h"
#include "DGtal/shapes/TriangulatedSurface.h"
#include "DGtal/shapes/MeshHelpers.h"
Typedefs
typedef PointVector< 3, double > RealPoint
typedef TriangulatedSurface< RealPoint > TriMesh
typedef TriMesh::VertexRange VertexRange
typedef TriMesh::ArcRange ArcRange
typedef TriMesh::Arc ArcT
typedef TriMesh::Face Face
typedef TriMesh::Vertex Vertex
typedef TriMesh::PositionsMap PositionsMap
Functions
TriMesh makeTwoTriangles ()
SCENARIO ("TriangulatedSurface< RealPoint3 > build tests", "[trisurf][build]")
SCENARIO ("TriangulatedSurface< RealPoint3 > flip tests", "[trisurf][flip]")
SCENARIO ("TriangulatedSurface< RealPoint3 > concept check tests", "[trisurf][concepts]")
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2017/02/06
Functions for testing class TriangulatedSurface.
This file is part of the DGtal library.
Definition in file testTriangulatedSurface.cpp.
Typedef Documentation
ArcRange
typedef TriMesh::ArcRange ArcRange
Definition at line 54 of file testTriangulatedSurface.cpp.
ArcT
typedef TriMesh::Arc ArcT
Definition at line 55 of file testTriangulatedSurface.cpp.
Face
typedef TriMesh::Face Face
Examples
shapes/exampleSurfaceMesh.cpp.
Definition at line 56 of file testTriangulatedSurface.cpp.
PositionsMap
typedef TriMesh::PositionsMap PositionsMap
Definition at line 58 of file testTriangulatedSurface.cpp.
RealPoint
typedef PointVector<3,double> RealPoint
Definition at line 51 of file testTriangulatedSurface.cpp.
TriMesh
typedef TriangulatedSurface< RealPoint > TriMesh
Examples
shapes/viewMarchingCubes.cpp.
Definition at line 52 of file testTriangulatedSurface.cpp.
Vertex
typedef TriMesh::Vertex Vertex
Examples
geometry/surfaces/greedy-plane-segmentation-ex2.cpp, geometry/surfaces/greedy-plane-segmentation.cpp, and graph/graphTraversal.cpp.
Definition at line 57 of file testTriangulatedSurface.cpp.
VertexRange
typedef TriMesh::VertexRange VertexRange
Examples
examples/tutorial-examples/polyhedralizer.cpp, and tutorial-examples/polyhedralizer.cpp.
Definition at line 53 of file testTriangulatedSurface.cpp.
Function Documentation
makeTwoTriangles()
TriMesh makeTwoTriangles ()
Definition at line 60 of file testTriangulatedSurface.cpp.
 {
   TriMesh mesh;
   mesh.addVertex( RealPoint( 0, 0, 0 ) );
   mesh.addVertex( RealPoint( 1, 0, 0 ) );
   mesh.addVertex( RealPoint( 0, 1, 0 ) );
   mesh.addVertex( RealPoint( 1, 1, 1 ) );
   mesh.addTriangle( 0, 1, 2 );
   mesh.addTriangle( 2, 1, 3 );
   mesh.build();
   return mesh;
 }
References DGtal::TriangulatedSurface< TPoint >::addTriangle(), DGtal::TriangulatedSurface< TPoint >::addVertex(), and DGtal::TriangulatedSurface< TPoint >::build().
Referenced by SCENARIO().
SCENARIO() [1/3]
SCENARIO ("TriangulatedSurface< RealPoint3 > build tests" , "" [trisurf][build])
Definition at line 73 of file testTriangulatedSurface.cpp.
 {
   GIVEN( "Two triangles incident by an edge" ) {
     TriMesh trimesh = makeTwoTriangles();
     THEN( "The mesh has 4 vertices, v0 has 2 neighbors, v1 has 3 neighbors, etc" ) {
       REQUIRE( trimesh.size() == 4 );
       REQUIRE( trimesh.degree( 0 ) == 2 );
       REQUIRE( trimesh.degree( 1 ) == 3 );
       REQUIRE( trimesh.degree( 2 ) == 3 );
       REQUIRE( trimesh.degree( 3 ) == 2 );
     }
     THEN( "Euler number is 1 as is the Euler number of a disk." )
       {
         REQUIRE( trimesh.nbVertices() == 4 );
         REQUIRE( trimesh.nbEdges() == 5 );
         REQUIRE( trimesh.nbFaces() == 2 );
         REQUIRE( trimesh.Euler() == 1 );
       }
     THEN( "Breadth-first visiting the mesh from vertex 3, visit 3, then {1,2}, then 0." )
       {
         BreadthFirstVisitor< TriMesh > visitor( trimesh, 3 );
         std::vector<unsigned long> vertices;
         std::vector<unsigned long> distances;
         while ( ! visitor.finished() )
           {
             vertices.push_back( visitor.current().first );
             distances.push_back( visitor.current().second );
             visitor.expand();
           }
         REQUIRE( vertices.size() == 4 );
         REQUIRE( distances.size() == 4 );
         int expected_vertices1[] = { 3, 1, 2, 0};
         int expected_vertices2[] = { 3, 2, 1, 0};
         int expected_distance [] = { 0, 1, 1, 2};
         bool vertices_ok
           = std::equal( vertices.begin(), vertices.end(), expected_vertices1 )
           || std::equal( vertices.begin(), vertices.end(), expected_vertices2 );
         REQUIRE( vertices_ok );
         bool distances_ok
           = std::equal( distances.begin(), distances.end(), expected_distance );
         REQUIRE( distances_ok );
       }
     THEN( "The mesh has 4 boundary vertices" ) {
       VertexRange bv = trimesh.allBoundaryVertices();
       std::sort( bv.begin(), bv.end() );
       int expected_bv [] = { 0, 1, 2, 3};
       REQUIRE( bv.size() == 4 );
       bool bv_ok = std::equal( bv.begin(), bv.end(), expected_bv );
       REQUIRE( bv_ok );
     }
     THEN( "The mesh has 4 boundary arcs" ) {
       ArcRange ba = trimesh.allBoundaryArcs();
       REQUIRE( ba.size() == 4 );
     }
     THEN( "The face along (1,2) is a triangle (0,1,2)" ) {
       ArcT  a12     = trimesh.arc( 1, 2 );
       Face f        = trimesh.faceAroundArc( a12 );
       ArcRange    A = trimesh.arcsAroundFace( f );
       VertexRange T = trimesh.verticesAroundFace( f );
       REQUIRE( A.size() == 3 );
       REQUIRE( T.size() == 3 );
       REQUIRE( trimesh.head( A[ 0 ] ) == T[ 0 ] );
       REQUIRE( trimesh.head( A[ 1 ] ) == T[ 1 ] );
       REQUIRE( trimesh.head( A[ 2 ] ) == T[ 2 ] );
       std::sort( T.begin(), T.end() );
       REQUIRE( T[ 0 ] == 0 );
       REQUIRE( T[ 1 ] == 1 );
       REQUIRE( T[ 2 ] == 2 );
     }
     THEN( "The face along (2,1) is a triangle (2,1,3)" ) {
       ArcT  a21     = trimesh.arc( 2, 1 );
       Face f        = trimesh.faceAroundArc( a21 );
       VertexRange T = trimesh.verticesAroundFace( f );
       REQUIRE( T.size() == 3 );
       std::sort( T.begin(), T.end() );
       REQUIRE( T[ 0 ] == 1 );
       REQUIRE( T[ 1 ] == 2 );
       REQUIRE( T[ 2 ] == 3 );
     }
     THEN( "The mesh has the barycenter (0.5, 0.5, 0.25) " ) {
       PositionsMap positions = trimesh.positions();
       RealPoint b;
       for ( Vertex v = 0; v < trimesh.size(); ++v )
         b += positions( v );
       b /= 4;
       REQUIRE( b[ 0 ] == 0.5 );
       REQUIRE( b[ 1 ] == 0.5 );
       REQUIRE( b[ 2 ] == 0.25 );
     }
     THEN( "We can convert the triangulated surface to a mesh and vice versa" ) {
       Mesh<RealPoint> mesh;
       MeshHelpers::triangulatedSurface2Mesh( trimesh, mesh );
       TriMesh trimesh2;
       MeshHelpers::mesh2TriangulatedSurface( mesh, trimesh2 );
       REQUIRE( mesh.nbVertex() == trimesh.nbVertices() );
       REQUIRE( mesh.nbFaces()  == trimesh.nbFaces() );
       REQUIRE( trimesh2.nbVertices() == trimesh.nbVertices() );
       REQUIRE( trimesh2.nbArcs()     == trimesh.nbArcs() );
       REQUIRE( trimesh2.nbFaces()    == trimesh.nbFaces() );
     }
     THEN( "We can iterate over the vertices" ) {
       PositionsMap positions       = trimesh.positions();
       RealPoint    exp_positions[] = { { 0,0,0 }, { 1,0,0 }, { 0,1,0 }, { 1,1,1 } };
       for ( auto it = trimesh.begin(), itE = trimesh.end(); it != itE; ++it ) {
         REQUIRE( positions[ *it ] == exp_positions[ *it ] );
       }
     }
   }
 }
References DGtal::TriangulatedSurface< TPoint >::allBoundaryArcs(), DGtal::TriangulatedSurface< TPoint >::allBoundaryVertices(), DGtal::TriangulatedSurface< TPoint >::arc(), DGtal::TriangulatedSurface< TPoint >::arcsAroundFace(), DGtal::TriangulatedSurface< TPoint >::begin(), DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::current(), DGtal::TriangulatedSurface< TPoint >::degree(), DGtal::TriangulatedSurface< TPoint >::end(), DGtal::TriangulatedSurface< TPoint >::Euler(), DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::expand(), DGtal::TriangulatedSurface< TPoint >::faceAroundArc(), DGtal::BreadthFirstVisitor< TGraph, TMarkSet >::finished(), GIVEN(), DGtal::TriangulatedSurface< TPoint >::head(), makeTwoTriangles(), DGtal::TriangulatedSurface< TPoint >::nbArcs(), DGtal::TriangulatedSurface< TPoint >::nbEdges(), DGtal::Mesh< TPoint >::nbFaces(), DGtal::TriangulatedSurface< TPoint >::nbFaces(), DGtal::Mesh< TPoint >::nbVertex(), DGtal::TriangulatedSurface< TPoint >::nbVertices(), DGtal::TriangulatedSurface< TPoint >::positions(), REQUIRE(), DGtal::TriangulatedSurface< TPoint >::size(), and DGtal::TriangulatedSurface< TPoint >::verticesAroundFace().
SCENARIO() [2/3]
SCENARIO ("TriangulatedSurface< RealPoint3 > concept check tests" , "" [trisurf][concepts])
Definition at line 216 of file testTriangulatedSurface.cpp.
 {
   BOOST_CONCEPT_ASSERT(( concepts::CUndirectedSimpleGraph< TriMesh > ));
 }
SCENARIO() [3/3]
SCENARIO ("TriangulatedSurface< RealPoint3 > flip tests" , "" [trisurf][flip])
Definition at line 183 of file testTriangulatedSurface.cpp.
 {
   GIVEN( "Two triangles incident by an edge" ) {
     TriMesh trimesh = makeTwoTriangles();
     auto nbv = trimesh.nbVertices();
     auto nbe = trimesh.nbEdges();
     auto nbf = trimesh.nbFaces();
     int nbfl = 0;
     ArcT  afl = 0;
     for ( ArcT a = 0; a < trimesh.nbArcs(); a++ )
       if ( trimesh.isFlippable( a ) ) {
         nbfl++;
         afl = a;
       }
     THEN( "Only two arcs are flippable" ){
       REQUIRE( nbfl == 2 );
     }
     THEN( "The mesh has same number of vertices, edges, faces after flip." ) {
       trimesh.flip( afl );
       REQUIRE( trimesh.nbVertices() == nbv );
       REQUIRE( trimesh.nbEdges() == nbe );
       REQUIRE( trimesh.nbFaces() == nbf );
     }
     THEN( "Edge (1,2) has 4 vertices around, in order (2,0,1,3)." ) {
       VertexRange V = trimesh.verticesOfFacesAroundArc( trimesh.arc( 1, 2 ) );
       int expected_V [] = { 2, 0, 1, 3};
       REQUIRE( V.size() == 4 );
       bool V_ok = std::equal( V.begin(), V.end(), expected_V );
       REQUIRE( V_ok );
     }
   }
 }
References DGtal::TriangulatedSurface< TPoint >::arc(), DGtal::TriangulatedSurface< TPoint >::flip(), GIVEN(), DGtal::TriangulatedSurface< TPoint >::isFlippable(), makeTwoTriangles(), DGtal::TriangulatedSurface< TPoint >::nbArcs(), DGtal::TriangulatedSurface< TPoint >::nbEdges(), DGtal::TriangulatedSurface< TPoint >::nbFaces(), DGtal::TriangulatedSurface< TPoint >::nbVertices(), REQUIRE(), and DGtal::TriangulatedSurface< TPoint >::verticesOfFacesAroundArc().