DGtal: testArithDSSIterator.cpp File Reference
testArithDSSIterator.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/geometry/curves/ArithDSSIterator.h"
#include "DGtal/geometry/curves/ArithmeticalDSSComputer.h"
Functions
bool testArithDSSIterator ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Isabelle Sivignon (isabe.nosp@m.lle..nosp@m.sivig.nosp@m.non@.nosp@m.gipsa.nosp@m.-lab.nosp@m..gren.nosp@m.oble.nosp@m.-inp..nosp@m.fr) gipsa-lab Grenoble Images Parole Signal Automatique (CNRS, UMR 5216), CNRS, France
Date
2012/11/26
Functions for testing class ArithDSSIterator.
This file is part of the DGtal library.
Definition in file testArithDSSIterator.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 74 of file testArithDSSIterator.cpp.
 {
   trace.beginBlock ( "Testing class ArithDSSIterator" );
   trace.info() << "Args:";
   for ( int i = 0; i < argc; ++i )
     trace.info() << " " << argv[ i ];
   trace.info() << endl;
   bool res = testArithDSSIterator(); // && ... other tests
   trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
   trace.endBlock();
   return res ? 0 : 1;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testArithDSSIterator(), and DGtal::trace.
testArithDSSIterator()
bool testArithDSSIterator ()
Example of a test. To be completed.
Definition at line 47 of file testArithDSSIterator.cpp.
 {
   typedef PointVector<2,int> Point;
   typedef ArithDSSIterator<int,8> MyIterator;
   Point p(3,2);
   MyIterator it(2,5,-4,p);
   typedef NaiveDSS8<int> ArithDSS;
   ArithDSS myDSS(p, p);
   int absMax=8;
   while ( (*it)[0] <=absMax && myDSS.extendFront(*++it))
     {}
   std::cout << myDSS.a() << " " << myDSS.b() << " " << myDSS.mu() << " " <<   std::endl;
   return ( (myDSS.a() == 2) &&
            (myDSS.b() == 5) &&
            (myDSS.mu() == -4) );
 }
Referenced by main().