DGtal: testDigitalSetToCellularGridConverter.cpp File Reference
testDigitalSetToCellularGridConverter.cpp File Reference
DGtal Test Files
#include <iostream>
#include <map>
#include "DGtal/base/Common.h"
#include "ConfigTest.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/topology/CubicalComplex.h"
#include "DGtal/shapes/GaussDigitizer.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/shapes/EuclideanShapesDecorator.h"
#include "DGtal/shapes/parametric/Flower2D.h"
Functions
int main (int, char **)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Kacper Pluta (kacpe.nosp@m.r.pl.nosp@m.uta@e.nosp@m.siee.nosp@m..fr) Laboratoire d'Informatique Gaspard-Monge - LIGM, A3SI, France
Date
2015/11/03
Functions for testing class digitalSetToCubicalComplexes.
This file is part of the DGtal library.
Definition in file testDigitalSetToCellularGridConverter.cpp.
Function Documentation
main()
int main (int , char **)
Definition at line 82 of file testDigitalSetToCellularGridConverter.cpp.
 {
     bool res = true;
     testDigitalSetToCellularGridConverter test;
     trace.beginBlock ( "DigitalSetToCellularGridConverter" );
         trace.beginBlock ( "Testing extraction of 0D cells" );
           res &= test.extractCells();
         trace.endBlock();
     trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
     trace.endBlock();
     return res ? 0 : 1;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), test(), and DGtal::trace.