DGtal: testCheckImageConcept.cpp File Reference
testCheckImageConcept.cpp File Reference
DGtal Test Files
#include "DGtal/helpers/StdDefs.h"
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/images/ImageContainerBySTLVector.h"
#include "DGtal/images/ImageContainerBySTLMap.h"
#include "DGtal/images/ImageContainerByITKImage.h"
#include "DGtal/images/ImageContainerByHashTree.h"
#include "DGtal/images/CImage.h"
Functions
bool testCheckImageConcept ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2010/11/28
Functions for testing the models of the Image concept.
This file is part of the DGtal library.
Definition in file testCheckImageConcept.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 84 of file testCheckImageConcept.cpp.
 {
   trace.beginBlock ( "Testing class CheckImageConcept" );
   trace.info() << "Args:";
   for ( int i = 0; i < argc; ++i )
     trace.info() << " " << argv[ i ];
   trace.info() << std::endl;
   bool res = testCheckImageConcept(); // && ... other tests
   trace.emphase() << ( res ? "Passed." : "Error." ) << std::endl;
   trace.endBlock();
   return res ? 0 : 1;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testCheckImageConcept(), and DGtal::trace.
testCheckImageConcept()
bool testCheckImageConcept ()
Example of a test. To be completed.
Definition at line 54 of file testCheckImageConcept.cpp.
 {
   trace.beginBlock ( "Testing block ..." );
   typedef ImageContainerBySTLVector<Domain, int> ImageVector;
   typedef ImageContainerBySTLVector<Domain, int> ImageMap;
 #ifdef WITH_ITK
  typedef ImageContainerByITKImage<Domain, int> ImageITK;
 #endif
   //HashTree is not (yet) a model of CImage
   typedef experimental::ImageContainerByHashTree<Domain, int>  ImageHash;
   BOOST_CONCEPT_ASSERT(( concepts::CImage< ImageVector >));
   BOOST_CONCEPT_ASSERT(( concepts::CImage< ImageMap >));
 #ifdef WITH_ITK
   BOOST_CONCEPT_ASSERT(( concepts::CImage< ImageITK >));
 #endif
   BOOST_CONCEPT_ASSERT(( concepts::CImage< ImageHash >));
   trace.endBlock();
   return true;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), and DGtal::trace.
Referenced by main().