DGtal: testStatistics.cpp File Reference
testStatistics.cpp File Reference
DGtal Test Files
#include <iostream>
#include <vector>
#include "DGtal/math/Statistic.h"
Functions
bool testStatistics ()
bool testStatisticsSaving ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2011/06/24
Functions for testing class Statistics.
This file is part of the DGtal library.
Definition in file testStatistics.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 118 of file testStatistics.cpp.
 {
   trace.beginBlock ( "Testing class Statistics" );
   trace.info() << "Args:";
   for ( int i = 0; i < argc; ++i )
     trace.info() << " " << argv[ i ];
   trace.info() << endl;
   bool res = testStatistics(); // && ... other tests
   trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
   trace.beginBlock ( "Testing class Statistics (with option for saving samples)" );
   trace.info() << "Args:";
   for ( int i = 0; i < argc; ++i )
     trace.info() << " " << argv[ i ];
   trace.info() << endl;
   bool res2 = testStatisticsSaving(); // && ... other tests
   trace.emphase() << ( res2 ? "Passed." : "Error." ) << endl;
   trace.endBlock();
   return (res &&res2) ? 0 : 1;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testStatistics(), testStatisticsSaving(), and DGtal::trace.
testStatistics()
bool testStatistics ()
Example of a test. To be completed.
Definition at line 47 of file testStatistics.cpp.
 {
   unsigned int nbok = 0;
   unsigned int nb = 3;
   trace.beginBlock ( "Testing Statistics ..." );
   Statistic<double> stat;
   for(unsigned int k=0; k < 1000; k++)
     stat.addValue((double)k);
   stat.terminate();
   trace.info() << "Mean value = "<<stat.mean()  << std::endl;
   nbok += (stat.mean()==499.5) ? 1 : 0;
   trace.info() << "Variance value = "<<stat.variance()<<std::endl;
   trace.info() << "Max value = "<<stat.max()<<std::endl;
   nbok += (stat.max()==999) ? 1 : 0;
   trace.info() << "Min value = "<<stat.min()<<std::endl;
   nbok += (stat.min()==0)  ? 1 : 0;
   trace.info() << "(" << nbok << "/" << nb << ") "
          << "true == true" << std::endl;
   trace.endBlock();
   return nbok == nb;
 }
References DGtal::Statistic< TQuantity >::addValue(), DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::Statistic< TQuantity >::max(), DGtal::Statistic< TQuantity >::mean(), DGtal::Statistic< TQuantity >::min(), DGtal::Statistic< TQuantity >::terminate(), DGtal::trace, and DGtal::Statistic< TQuantity >::variance().
Referenced by main().
testStatisticsSaving()
bool testStatisticsSaving ()
Example of a test. To be completed.
Definition at line 80 of file testStatistics.cpp.
 {
   unsigned int nbok = 0;
   unsigned int nb = 4;
   trace.beginBlock ( "Testing Statistics with saving option ..." );
   Statistic<double> stat(true);
   for(unsigned int k=0; k < 100; k++)
     stat.addValue(99);
   stat.addValue(88);
   for(unsigned int k=0; k < 100; k++)
     stat.addValue(77);
   stat.terminate();
   trace.info() << "Mean value = "<<stat.mean()  << std::endl;
   nbok += (stat.mean()==88) ? 1 : 0;
   trace.info() << "Variance value = "<<stat.variance()<<std::endl;
   trace.info() << "Max value = "<<stat.max()<<std::endl;
   nbok += (stat.max()==99) ? 1 : 0;
   trace.info() << "Min value = "<<stat.min()<<std::endl;
   nbok += (stat.min()==77)  ? 1 : 0;
   trace.info() << "Median value = "<<stat.median()<<std::endl;
   nbok += (stat.median()==88)  ? 1 : 0;
   trace.info() << "(" << nbok << "/" << nb << ") "
          << "true == true" << std::endl;
   trace.endBlock();
   return nbok == nb;
 }
References DGtal::Statistic< TQuantity >::addValue(), DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::Statistic< TQuantity >::max(), DGtal::Statistic< TQuantity >::mean(), DGtal::Statistic< TQuantity >::median(), DGtal::Statistic< TQuantity >::min(), DGtal::Statistic< TQuantity >::terminate(), DGtal::trace, and DGtal::Statistic< TQuantity >::variance().
Referenced by main().