DGtal: voronoimap2D.cpp File Reference
voronoimap2D.cpp File Reference
DGtal Examples
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/kernel/BasicPointPredicates.h"
#include "DGtal/images/SimpleThresholdForegroundPredicate.h"
#include "DGtal/geometry/volumes/distance/ExactPredicateLpSeparableMetric.h"
#include "DGtal/geometry/volumes/distance/VoronoiMap.h"
#include "DGtal/geometry/volumes/distance/DistanceTransformation.h"
#include "DGtal/io/colormaps/HueShadeColorMap.h"
#include "DGtal/io/boards/Board2D.h"
Functions
int main (int, char **)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2013/01/17
An example file named voronoimap2D.
This file is part of the DGtal library.
Definition in file voronoimap2D.cpp.
Function Documentation
main()
int main (int , char **)
[Voro2D-Metric]
[Voro2D-Metric]
[Voro2D-SmallImage]
[Voro2D-SmallImage]
[Voro2D-Predicate]
[Voro2D-Predicate]
[Voro2D-Voro]
[Voro2D-Voro]
[Voro2D-trace]
[Voro2D-trace]
[Voro2D-traceCell]
[Voro2D-traceCell]
[Voro2D-l8Metric]
[Voro2D-l8Metric]
[Voro2D-DT]
[Voro2D-DT]
Definition at line 63 of file voronoimap2D.cpp.
 {
   trace.beginBlock ( "Example voronoimap2D" );
   typedef ExactPredicateLpSeparableMetric<Z2i::Space, 2> L2Metric;
   L2Metric l2;
   Z2i::Point lower(0,0);
   Z2i::Point upper(16,16);
   Z2i::Domain domain(lower,upper);
   Z2i::DigitalSet set(domain);
   set.insertNew(Z2i::Point(2,3));
   set.insertNew(Z2i::Point(7,15));
   set.insertNew(Z2i::Point(12,5));
   Board2D board;
   board<< domain << set;
   board.saveSVG("voronoimap-inputset.svg");
   typedef NotPointPredicate<Z2i::DigitalSet> NotPredicate;
   NotPredicate notSetPred(set);
   typedef VoronoiMap<Z2i::Space, NotPredicate, L2Metric > Voronoi2D;
   Voronoi2D voronoimap(domain,notSetPred,l2);
   board.clear();
   board << domain;
   for(Voronoi2D::Domain::ConstIterator it = voronoimap.domain().begin(),
       itend = voronoimap.domain().end(); it != itend; ++it)
   {
     Voronoi2D::Value site = voronoimap( *it );   //closest site to (*it)
     if (site != (*it))
       Display2DFactory::draw( board,   site - (*it), (*it)); //Draw an arrow
   }
   board.saveSVG("voronoimap-voro.svg");
   board.clear();
   for(Voronoi2D::Domain::ConstIterator it = voronoimap.domain().begin(),
       itend = voronoimap.domain().end(); it != itend; ++it)
   {
     Voronoi2D::Value site = voronoimap( *it );   //closest site to (*it)
     unsigned char c = (site[1]*13 + site[0] * 7) % 256; //basic hashfunction
     board << CustomStyle( (*it).className(), new CustomColors(Color(c,c,c),Color(c,c,c)))
       << (*it);
   }
   board.saveSVG("voronoimap-cells.svg");
   typedef ExactPredicateLpSeparableMetric<Z2i::Space, 8> L8Metric;
   L8Metric l8;
   typedef VoronoiMap<Z2i::Space, NotPredicate, L8Metric > Voronoi2D_l8;
   Voronoi2D_l8 voronoimap_l8(domain,notSetPred,l8);
   board.clear();
   board << domain;
   for(Voronoi2D_l8::Domain::ConstIterator it = voronoimap_l8.domain().begin(),
       itend = voronoimap_l8.domain().end(); it != itend; ++it)
   {
     Voronoi2D::Value site = voronoimap_l8( *it );   //closest site to (*it)
     unsigned char c = (site[1]*13 + site[0] * 7) % 256; //basic hashfunction
     board << CustomStyle( (*it).className(), new CustomColors(Color(c,c,c),Color(c,c,c)))
           << (*it);
   }
   board.saveSVG("voronoimap-vorol8.svg");
   typedef DistanceTransformation<Z2i::Space, NotPredicate, L2Metric > DT;
   DT dt(domain,notSetPred,l2);
   board.clear();
   board << domain;
   //Fast max computation on the range value
   DT::Value maxDT=0.0;
   for(DT::ConstRange::ConstIterator it = dt.constRange().begin(), itend = dt.constRange().end();
       it != itend ; ++it)
     if ((*it)>maxDT) maxDT = (*it);
   //Colormap
   HueShadeColorMap<DT::Value,1> hueMap(0.0,maxDT);
   //Drawing
   for(DT::Domain::ConstIterator it = dt.domain().begin(),
       itend = dt.domain().end(); it != itend; ++it)
   {
     DT::Value dist = dt( *it );   //distance to closest site to (*it)
     board << CustomStyle( (*it).className(), new CustomColors( hueMap(dist), hueMap(dist)))
           << (*it);
   }
   board.saveSVG("voronoimap-dt.svg");
   trace.endBlock();
   return 0;
 }
References DGtal::Trace::beginBlock(), LibBoard::Board::clear(), domain, draw(), DGtal::Trace::endBlock(), DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::insertNew(), lower(), LibBoard::Board::saveSVG(), DGtal::trace, and upper().