DGtal: DGtal::functions::setops Namespace Reference
DGtal::functions::setops Namespace Reference
Functions
template<typename Container >
bool operator== (const Container &S1, const Container &S2)
template<typename Container >
bool operator!= (const Container &S1, const Container &S2)
template<typename Container >
bool operator<= (const Container &S1, const Container &S2)
template<typename Container >
bool operator>= (const Container &S1, const Container &S2)
template<typename Container >
Container & operator-= (Container &S1, const Container &S2)
template<typename Container >
Container operator- (const Container &S1, const Container &S2)
template<typename Container >
Container operator| (const Container &S1, const Container &S2)
template<typename Container >
Container & operator|= (Container &S1, const Container &S2)
template<typename Container >
Container operator& (const Container &S1, const Container &S2)
template<typename Container >
Container & operator&= (Container &S1, const Container &S2)
template<typename Container >
Container operator^ (const Container &S1, const Container &S2)
template<typename Container >
Container & operator^= (Container &S1, const Container &S2)
Detailed Description
Contains set operator union |, intersection &, difference -, symmetric difference ^.
Function Documentation
template<typename Container > bool DGtal::functions::setops::operator!= (const Container & S1, const Container & S2)
Difference test.
Parameters
[in] S1 an input set.
[in] S2 another input set.
Returns
true iff S1 is not equal to S2 (i.e. either S1 is not a subset of S2 or S2 is not a subset of S1).
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1297 of file SetFunctions.h.
References DGtal::functions::isEqual().
       {
         return ! isEqual( S1, S2 );
       }
template<typename Container > Container DGtal::functions::setops::operator& (const Container & S1, const Container & S2) inline
Set intersection operation. Returns the set \(S1 \cap S2 \).
Parameters
[in] S1 an input set.
[in] S2 another input set.
Returns
the set \(S1 \cap S2 \).
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1404 of file SetFunctions.h.
References DGtal::functions::makeIntersection().
       {
         return makeIntersection( S1, S2 );
       }
template<typename Container > Container& DGtal::functions::setops::operator&= (Container & S1, const Container & S2) inline
Set intersection operation. Updates the set S1 as \(S1 \cap S2 \).
Parameters
[in,out] S1 an input set, \(S1 \cap S2 \) as output.
[in] S2 another input set.
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1418 of file SetFunctions.h.
References DGtal::functions::assignIntersection().
       {
         return assignIntersection( S1, S2 );
       }
template<typename Container > Container DGtal::functions::setops::operator- (const Container & S1, const Container & S2) inline
Set difference operation. Returns the difference of S1 - S2.
Parameters
[in] S1 an input set
[in] S2 another input set.
Returns
the set S1 - S2.
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1360 of file SetFunctions.h.
References DGtal::functions::makeDifference().
       {
         return makeDifference( S1, S2 );
       }
template<typename Container > Container& DGtal::functions::setops::operator-= (Container & S1, const Container & S2) inline
Set difference operation. Updates the set S1 as S1 - S2.
Parameters
[in,out] S1 an input set, S1 - S2 as output.
[in] S2 another input set.
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1344 of file SetFunctions.h.
References DGtal::functions::assignDifference().
       {
         return assignDifference( S1, S2 );
       }
template<typename Container > bool DGtal::functions::setops::operator<= (const Container & S1, const Container & S2)
Inclusion test (subset of).
Parameters
[in] S1 an input set.
[in] S2 another input set.
Returns
true iff S1 is a subset of S2.
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1314 of file SetFunctions.h.
References DGtal::functions::isSubset().
       {
         return isSubset( S1, S2 );
       }
template<typename Container > bool DGtal::functions::setops::operator== (const Container & S1, const Container & S2)
Equality test.
Parameters
[in] S1 an input set.
[in] S2 another input set.
Returns
true iff S1 is equal to S2 (i.e. S1 is a subset of S2 and S2 is a subset of S1).
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1277 of file SetFunctions.h.
References DGtal::functions::isEqual().
       {
         return isEqual( S1, S2 );
       }
template<typename Container > bool DGtal::functions::setops::operator>= (const Container & S1, const Container & S2)
Inclusion test (supset of).
Parameters
[in] S1 an input set.
[in] S2 another input set.
Returns
true iff S2 is a subset of S1.
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1330 of file SetFunctions.h.
References DGtal::functions::isSubset().
       {
         return isSubset( S2, S1 );
       }
template<typename Container > Container DGtal::functions::setops::operator^ (const Container & S1, const Container & S2) inline
Set symmetric difference operation. Returns the set \(S1 \Delta S2 \).
Parameters
[in] S1 an input set.
[in] S2 another input set.
Returns
the set \(S1 \Delta S2 \).
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1434 of file SetFunctions.h.
References DGtal::functions::makeSymmetricDifference().
       {
         return makeSymmetricDifference( S1, S2 );
       }
template<typename Container > Container& DGtal::functions::setops::operator^= (Container & S1, const Container & S2) inline
Set symmetric difference operation. Updates the set S1 as \(S1 \Delta S2 \).
Parameters
[in,out] S1 an input set, \(S1 \Delta S2 \) as output.
[in] S2 another input set.
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1450 of file SetFunctions.h.
References DGtal::functions::assignSymmetricDifference().
       {
         return assignSymmetricDifference( S1, S2 );
       }
template<typename Container > Container DGtal::functions::setops::operator| (const Container & S1, const Container & S2) inline
Set union operation. Returns the set \(S1 \cup S2 \).
Parameters
[in] S1 an input set.
[in] S2 another input set.
Returns
the set \(S1 \cup S2 \).
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1375 of file SetFunctions.h.
References DGtal::functions::makeUnion().
       {
         return makeUnion( S1, S2 );
       }
template<typename Container > Container& DGtal::functions::setops::operator|= (Container & S1, const Container & S2) inline
Set union operation. Updates the set S1 as \(S1 \cup S2 \).
Parameters
[in,out] S1 an input set, \(S1 \cup S2 \) as output.
[in] S2 another input set.
Template Parameters
Container any type of container (even a sequence, a set, an unordered_set, a map, etc).
Definition at line 1389 of file SetFunctions.h.
References DGtal::functions::assignUnion().
       {
         return assignUnion( S1, S2 );
       }