DGtal: DGtal::functions::ccops Namespace Reference
DGtal::functions::ccops Namespace Reference
Functions
template<typename TKSpace , typename TCellContainer >
CubicalComplex< TKSpace, TCellContainer > & operator|= (CubicalComplex< TKSpace, TCellContainer > &, const CubicalComplex< TKSpace, TCellContainer > &)
template<typename TKSpace , typename TCellContainer >
CubicalComplex< TKSpace, TCellContainer > & operator&= (CubicalComplex< TKSpace, TCellContainer > &, const CubicalComplex< TKSpace, TCellContainer > &)
template<typename TKSpace , typename TCellContainer >
CubicalComplex< TKSpace, TCellContainer > & operator^= (CubicalComplex< TKSpace, TCellContainer > &, const CubicalComplex< TKSpace, TCellContainer > &)
template<typename TKSpace , typename TCellContainer >
CubicalComplex< TKSpace, TCellContainer > & operator-= (CubicalComplex< TKSpace, TCellContainer > &, const CubicalComplex< TKSpace, TCellContainer > &)
template<typename TKSpace , typename TCellContainer >
CubicalComplex< TKSpace, TCellContainer > operator| (const CubicalComplex< TKSpace, TCellContainer > &, const CubicalComplex< TKSpace, TCellContainer > &)
template<typename TKSpace , typename TCellContainer >
CubicalComplex< TKSpace, TCellContainer > operator& (const CubicalComplex< TKSpace, TCellContainer > &, const CubicalComplex< TKSpace, TCellContainer > &)
template<typename TKSpace , typename TCellContainer >
CubicalComplex< TKSpace, TCellContainer > operator^ (const CubicalComplex< TKSpace, TCellContainer > &, const CubicalComplex< TKSpace, TCellContainer > &)
template<typename TKSpace , typename TCellContainer >
CubicalComplex< TKSpace, TCellContainer > operator- (const CubicalComplex< TKSpace, TCellContainer > &, const CubicalComplex< TKSpace, TCellContainer > &)
template<typename TKSpace , typename TCellContainer >
CubicalComplex< TKSpace, TCellContainer > operator~ (const CubicalComplex< TKSpace, TCellContainer > &)
template<typename TKSpace , typename TCellContainer >
CubicalComplex< TKSpace, TCellContainer > operator* (const CubicalComplex< TKSpace, TCellContainer > &)
template<typename TKSpace , typename TCellContainer >
bool operator== (const CubicalComplex< TKSpace, TCellContainer > &, const CubicalComplex< TKSpace, TCellContainer > &)
template<typename TKSpace , typename TCellContainer >
bool operator!= (const CubicalComplex< TKSpace, TCellContainer > &, const CubicalComplex< TKSpace, TCellContainer > &)
template<typename TKSpace , typename TCellContainer >
bool operator<= (const CubicalComplex< TKSpace, TCellContainer > &, const CubicalComplex< TKSpace, TCellContainer > &)
template<typename TKSpace , typename TCellContainer >
bool operator>= (const CubicalComplex< TKSpace, TCellContainer > &, const CubicalComplex< TKSpace, TCellContainer > &)
template<typename TCubicalComplex , typename CellConstIterator , typename CellMapIteratorPriority >
uint64_t collapse (TCubicalComplex &K, CellConstIterator S_itB, CellConstIterator S_itE, const CellMapIteratorPriority &priority, bool hintIsSClosed=false, bool hintIsKClosed=false, bool verbose=false)
template<typename TCubicalComplex , typename BdryCellOutputIterator , typename InnerCellOutputIterator >
void filterCellsWithinBounds (const TCubicalComplex &K, const typename TCubicalComplex::Point &kLow, const typename TCubicalComplex::Point &kUp, BdryCellOutputIterator itBdry, InnerCellOutputIterator itInner)
Detailed Description
CubicalComplex operators.
Function Documentation
template<typename TCubicalComplex , typename CellConstIterator , typename CellMapIteratorPriority > uint64_t DGtal::functions::ccops::collapse (TCubicalComplex & K, CellConstIterator S_itB, CellConstIterator S_itE, const CellMapIteratorPriority & priority, bool hintIsSClosed = false, bool hintIsKClosed = false, bool verbose = false)
Collapse a user-specified part of complex K, collapsing cells following priority [priority], in a decreasing sequence until no more collapse is feasible. The range [S_itb,S_itE) provides the starting cells, generally (but not compulsory) maximal cells. The resulting complex is guaranteed to keep the same homotopy type (a kind of topology equivalence).
Note
Cells whose data has been marked as FIXED are not removed.
Only cells that are in the closure of [S_itb,S_itE) may be removed, and only if they are not marked as FIXED.
Advanced:
If you use a DefaultCellMapIteratorPriority object as priority, then the VALUE part of each cell data defines the priority (the highest value the soonest are these cells collapsed). You may thus fill these cell values before calling this method.
Template Parameters
TCubicalComplex any instantiated type of CubicalComplex< Space, CellContainer >.
CellConstIterator any forward const iterator on Cell.
CellMapIteratorPriority any type defining a method 'bool operator()(const Cell&, const Cell&) const'. Defines the order in which cells are collapsed.
See also
DefaultCellMapIteratorPriority
Parameters
[in,out] K the complex that is collapsed.
S_itB the start of a range of cells which is included in [K].
S_itE the end of a range of cells which is included in [K].
priority the object that assign a priority to each cell.
hintIsSClosed indicates if [S_itb,S_ite) is a closed set (faster in this case).
hintIsKClosed indicates that complex K is closed.
verbose outputs some information during processing when 'true'.
Returns
the number of cells removed from complex K.
See also
topology/cubical-complex-collapse.cpp
template<typename TCubicalComplex , typename BdryCellOutputIterator , typename InnerCellOutputIterator > void DGtal::functions::ccops::filterCellsWithinBounds (const TCubicalComplex & K, const typename TCubicalComplex::Point & kLow, const typename TCubicalComplex::Point & kUp, BdryCellOutputIterator itBdry, InnerCellOutputIterator itInner)
Computes the cells of the given complex K that lies on the boundary or inside the parallelepiped specified by bounds kLow and kUp.
Template Parameters
TCubicalComplex any instantiated type of CubicalComplex< Space, CellContainer >.
BdryCellOutputIterator any output iterator on TCubicalComplex::Cell.
InnerCellOutputIterator any output iterator on TCubicalComplex::Cell.
Parameters
[in] K any cubical complex.
[in] kLow any Khalimsky coordinate representing the lowest possible cell.
[in] kUp any Khalimsky coordinate representing the uppermost possible cell.
[in,out] itBdry An output iterator on Cell that outputs all the cells of K that lie on the boundary of the parallelepiped specified by bounds kLow and kUp.
[in,out] itInner An output iterator on Cell that outputs all the cells of K that lie in the interior of the parallelepiped specified by bounds kLow and kUp.
Note
Complexity is linear in the number of cells of K (but the constant is also linear in the dimension of K).
template<typename TKSpace , typename TCellContainer > bool DGtal::functions::ccops::operator!= (const CubicalComplex< TKSpace, TCellContainer > & S1, const CubicalComplex< TKSpace, TCellContainer > & S2)
Difference test.
Parameters
[in] S1 an input cubical complex.
[in] S2 another input cubical complex.
Returns
true iff S1 is not equal to S2 (i.e. either S1 is not a subcomplex of S2 or S2 is not a subcomplex of S1).
Definition at line 258 of file CubicalComplexFunctions.h.
References DGtal::CubicalComplex< TKSpace, TCellContainer >::dimension, DGtal::CubicalComplex< TKSpace, TCellContainer >::myCells, and DGtal::CubicalComplex< TKSpace, TCellContainer >::space().
       {
         typedef CubicalComplex< TKSpace, TCellContainer > CC;
         ASSERT( &(S1.space()) == &(S2.space()) );
         for ( Dimension i = 0; i <= CC::dimension; ++i )
           if ( setops::operator!=( S1.myCells[ i ], S2.myCells[ i ] ) )
             return true;
         return false;
       }
template<typename TKSpace , typename TCellContainer > CubicalComplex< TKSpace, TCellContainer > DGtal::functions::ccops::operator& (const CubicalComplex< TKSpace, TCellContainer > & S1, const CubicalComplex< TKSpace, TCellContainer > & S2) inline
Cubical Complex intersection operation. Returns the cubical complex \(S1 \cap S2 \).
Parameters
[in] S1 an input cubical complex.
[in] S2 another input cubical complex.
Returns
the cubical complex \(S1 \cap S2 \).
Definition at line 159 of file CubicalComplexFunctions.h.
References DGtal::CubicalComplex< TKSpace, TCellContainer >::dimension, and DGtal::CubicalComplex< TKSpace, TCellContainer >::myCells.
       {
         typedef CubicalComplex< TKSpace, TCellContainer > CC;
         CC S( S1 );
         for ( Dimension i = 0; i <= CC::dimension; ++i )
           setops::operator&=( S.myCells[ i ], S2.myCells[ i ] );
         return S;
       }
template<typename TKSpace , typename TCellContainer > CubicalComplex< TKSpace, TCellContainer > & DGtal::functions::ccops::operator&= (CubicalComplex< TKSpace, TCellContainer > & S1, const CubicalComplex< TKSpace, TCellContainer > & S2) inline
Cubical Complex intersection operation. Updates the cubical complex S1 as \(S1 \cap S2 \).
Parameters
[in,out] S1 an input cubical complex, \(S1 \cap S2 \) as output.
[in] S2 another input cubical complex.
Definition at line 176 of file CubicalComplexFunctions.h.
References DGtal::CubicalComplex< TKSpace, TCellContainer >::dimension, and DGtal::CubicalComplex< TKSpace, TCellContainer >::myCells.
       {
         typedef CubicalComplex< TKSpace, TCellContainer > CC;
         for ( Dimension i = 0; i <= CC::dimension; ++i )
           setops::operator&=( S1.myCells[ i ], S2.myCells[ i ] );
         return S1;
       }
template<typename TKSpace , typename TCellContainer > CubicalComplex< TKSpace, TCellContainer > DGtal::functions::ccops::operator* (const CubicalComplex< TKSpace, TCellContainer > & S1) inline
Cubical Complex open operation.
Parameters
[in] S1 an input cubical complex
Returns
a new cubical complex that is the opening of S1.
Definition at line 75 of file CubicalComplexFunctions.h.
References DGtal::CubicalComplex< TKSpace, TCellContainer >::open().
       {
         CubicalComplex< TKSpace, TCellContainer > S( S1 );
         S.open();
         return S;
       }
template<typename TKSpace , typename TCellContainer > CubicalComplex< TKSpace, TCellContainer > DGtal::functions::ccops::operator- (const CubicalComplex< TKSpace, TCellContainer > & S1, const CubicalComplex< TKSpace, TCellContainer > & S2) inline
Cubical Complex difference operation. Returns the difference of S1 - S2.
Parameters
[in] S1 an input cubical complex
[in] S2 another input cubical complex.
Returns
the cubical complex S1 - S2.
Definition at line 107 of file CubicalComplexFunctions.h.
References DGtal::CubicalComplex< TKSpace, TCellContainer >::dimension, and DGtal::CubicalComplex< TKSpace, TCellContainer >::myCells.
       {
         typedef CubicalComplex< TKSpace, TCellContainer > CC;
         CC S( S1 );
         for ( Dimension i = 0; i <= CC::dimension; ++i )
           setops::operator-=( S.myCells[ i ],S2.myCells[ i ] );
         return S;
       }
template<typename TKSpace , typename TCellContainer > CubicalComplex< TKSpace, TCellContainer > & DGtal::functions::ccops::operator-= (CubicalComplex< TKSpace, TCellContainer > & S1, const CubicalComplex< TKSpace, TCellContainer > & S2) inline
Cubical Complex difference operation. Updates the cubical complex S1 as S1 - S2.
Parameters
[in,out] S1 an input cubical complex, S1 - S2 as output.
[in] S2 another input cubical complex.
Definition at line 89 of file CubicalComplexFunctions.h.
References DGtal::CubicalComplex< TKSpace, TCellContainer >::dimension, and DGtal::CubicalComplex< TKSpace, TCellContainer >::myCells.
       {
         typedef CubicalComplex< TKSpace, TCellContainer > CC;
         for ( Dimension i = 0; i <= CC::dimension; ++i )
           setops::operator-=( S1.myCells[ i ],S2.myCells[ i ] );
         return S1;
       }
template<typename TKSpace , typename TCellContainer > bool DGtal::functions::ccops::operator<= (const CubicalComplex< TKSpace, TCellContainer > & S1, const CubicalComplex< TKSpace, TCellContainer > & S2)
Inclusion test (subset of).
Parameters
[in] S1 an input cubical complex.
[in] S2 another input cubical complex.
Returns
true iff S1 is a subcomplex of S2.
Definition at line 279 of file CubicalComplexFunctions.h.
References DGtal::CubicalComplex< TKSpace, TCellContainer >::dimension.
       {
         typedef CubicalComplex< TKSpace, TCellContainer > CC;
         ASSERT( &(S1.space()) == &(S2.space()) );
         for ( Dimension i = 0; i <= CC::dimension; ++i )
           if ( ! setops::operator<=( S1.myCells[ i ], S2.myCells[ i ] ) )
             return false;
         return true;
       }
template<typename TKSpace , typename TCellContainer > bool DGtal::functions::ccops::operator== (const CubicalComplex< TKSpace, TCellContainer > & S1, const CubicalComplex< TKSpace, TCellContainer > & S2)
Equality test.
Parameters
[in] S1 an input cubical complex.
[in] S2 another input cubical complex.
Returns
true iff S1 is equal to S2 (i.e. S1 is a subcomplex of S2 and S2 is a subcomplex of S1).
Definition at line 234 of file CubicalComplexFunctions.h.
References DGtal::CubicalComplex< TKSpace, TCellContainer >::dimension, DGtal::CubicalComplex< TKSpace, TCellContainer >::myCells, and DGtal::CubicalComplex< TKSpace, TCellContainer >::space().
       {
         typedef CubicalComplex< TKSpace, TCellContainer > CC;
         ASSERT( &(S1.space()) == &(S2.space()) );
         for ( Dimension i = 0; i <= CC::dimension; ++i )
           if ( setops::operator!=( S1.myCells[ i ], S2.myCells[ i ] ) )
             return false;
         return true;
       }
template<typename TKSpace , typename TCellContainer > bool DGtal::functions::ccops::operator>= (const CubicalComplex< TKSpace, TCellContainer > & S1, const CubicalComplex< TKSpace, TCellContainer > & S2)
Inclusion test (supset of).
Parameters
[in] S1 an input cubical complex.
[in] S2 another input cubical complex.
Returns
true iff S2 is a subcomplex of S1.
Definition at line 299 of file CubicalComplexFunctions.h.
References DGtal::CubicalComplex< TKSpace, TCellContainer >::dimension, DGtal::CubicalComplex< TKSpace, TCellContainer >::myCells, and DGtal::CubicalComplex< TKSpace, TCellContainer >::space().
       {
         typedef CubicalComplex< TKSpace, TCellContainer > CC;
         ASSERT( &(S1.space()) == &(S2.space()) );
         for ( Dimension i = 0; i <= CC::dimension; ++i )
           if ( ! setops::operator<=( S2.myCells[ i ], S1.myCells[ i ] ) )
             return false;
         return true;
       }
template<typename TKSpace , typename TCellContainer > CubicalComplex< TKSpace, TCellContainer > DGtal::functions::ccops::operator^ (const CubicalComplex< TKSpace, TCellContainer > & S1, const CubicalComplex< TKSpace, TCellContainer > & S2) inline
Cubical Complex symmetric difference operation. Returns the cubical complex \(S1 \Delta S2 \).
Parameters
[in] S1 an input cubical complex.
[in] S2 another input cubical complex.
Returns
the cubical complex \(S1 \Delta S2 \).
Definition at line 194 of file CubicalComplexFunctions.h.
References DGtal::CubicalComplex< TKSpace, TCellContainer >::dimension, and DGtal::CubicalComplex< TKSpace, TCellContainer >::myCells.
       {
         typedef CubicalComplex< TKSpace, TCellContainer > CC;
         CC S( S1 );
         for ( Dimension i = 0; i <= CC::dimension; ++i )
           setops::operator^=( S.myCells[ i ], S2.myCells[ i ] );
         return S;
       }
template<typename TKSpace , typename TCellContainer > CubicalComplex< TKSpace, TCellContainer > & DGtal::functions::ccops::operator^= (CubicalComplex< TKSpace, TCellContainer > & S1, const CubicalComplex< TKSpace, TCellContainer > & S2) inline
Cubical Complex symmetric difference operation. Updates the cubical complex S1 as \(S1 \Delta S2 \).
Parameters
[in,out] S1 an input cubical complex, \(S1 \Delta S2 \) as output.
[in] S2 another input cubical complex.
Definition at line 213 of file CubicalComplexFunctions.h.
References DGtal::CubicalComplex< TKSpace, TCellContainer >::dimension, and DGtal::CubicalComplex< TKSpace, TCellContainer >::myCells.
       {
         typedef CubicalComplex< TKSpace, TCellContainer > CC;
         for ( Dimension i = 0; i <= CC::dimension; ++i )
           setops::operator^=( S1.myCells[ i ], S2.myCells[ i ] );
         return S1;
       }
template<typename TKSpace , typename TCellContainer > CubicalComplex< TKSpace, TCellContainer > DGtal::functions::ccops::operator| (const CubicalComplex< TKSpace, TCellContainer > & S1, const CubicalComplex< TKSpace, TCellContainer > & S2) inline
Cubical Complex union operation. Returns the cubical complex \(S1 \cup S2 \).
Parameters
[in] S1 an input cubical complex.
[in] S2 another input cubical complex.
Returns
the cubical complex \(S1 \cup S2 \).
Definition at line 125 of file CubicalComplexFunctions.h.
References DGtal::CubicalComplex< TKSpace, TCellContainer >::dimension, and DGtal::CubicalComplex< TKSpace, TCellContainer >::myCells.
       {
         typedef CubicalComplex< TKSpace, TCellContainer > CC;
         CC S( S1 );
         for ( Dimension i = 0; i <= CC::dimension; ++i )
           setops::operator|=( S.myCells[ i ],S2.myCells[ i ] );
         return S;
       }
template<typename TKSpace , typename TCellContainer > CubicalComplex< TKSpace, TCellContainer > & DGtal::functions::ccops::operator|= (CubicalComplex< TKSpace, TCellContainer > & S1, const CubicalComplex< TKSpace, TCellContainer > & S2) inline
Cubical Complex union operation. Updates the cubical complex S1 as \(S1 \cup S2 \).
Parameters
[in,out] S1 an input cubical complex, \(S1 \cup S2 \) as output.
[in] S2 another input cubical complex.
Definition at line 142 of file CubicalComplexFunctions.h.
References DGtal::CubicalComplex< TKSpace, TCellContainer >::dimension, and DGtal::CubicalComplex< TKSpace, TCellContainer >::myCells.
       {
         typedef CubicalComplex< TKSpace, TCellContainer > CC;
         for ( Dimension i = 0; i <= CC::dimension; ++i )
           setops::operator|=( S1.myCells[ i ], S2.myCells[ i ] );
         return S1;
       }
template<typename TKSpace , typename TCellContainer > CubicalComplex< TKSpace, TCellContainer > DGtal::functions::ccops::operator~ (const CubicalComplex< TKSpace, TCellContainer > & S1) inline
Cubical Complex close operation.
Parameters
[in] S1 an input cubical complex
Returns
a new cubical complex that is the closing of S1.
Definition at line 61 of file CubicalComplexFunctions.h.
References DGtal::CubicalComplex< TKSpace, TCellContainer >::close().
       {
         CubicalComplex< TKSpace, TCellContainer > S( S1 );
         S.close();
         return S;
       }