DGtal: LibBoard::TransformEPS Struct Reference
LibBoard::TransformEPS Struct Reference
#include </Users/davidcoeurjolly/Sources/DGtal/src/Board/Transforms.h>
Public Member Functions
double mapY (double y) const
void setBoundingBox (const Rect &rect, const double pageWidth, const double pageHeight, const double margin)
Public Member Functions inherited from LibBoard::Transform
Transform ()
virtual ~Transform ()
virtual double mapX (double x) const
virtual void apply (double &x, double &y) const
virtual double scale (double x) const
virtual double rounded (double x) const
Additional Inherited Members
Static Public Member Functions inherited from LibBoard::Transform
static double round (const double &x)
Protected Attributes inherited from LibBoard::Transform
double _scale
double _deltaX
double _deltaY
double _height
Detailed Description
Structure representing a scaling and translation suitable for an EPS output.
The TransformEPS structure.
Definition at line 59 of file Transforms.h.
Member Function Documentation
double LibBoard::TransformEPS::mapY (double y) const virtual
Implements LibBoard::Transform.
Definition at line 62 of file Transforms.cpp.
References LibBoard::Transform::_deltaY, LibBoard::Transform::_scale, and LibBoard::Transform::rounded().
Referenced by LibBoard::Path::flushPostscript(), LibBoard::Dot::flushPostscript(), LibBoard::Line::flushPostscript(), LibBoard::Arrow::flushPostscript(), LibBoard::QuadraticBezierCurve::flushPostscript(), LibBoard::Ellipse::flushPostscript(), LibBoard::Arc::flushPostscript(), LibBoard::Text::flushPostscript(), and LibBoard::Board::saveEPS().
 {
   return rounded( y * _scale + _deltaY );
 }
void LibBoard::TransformEPS::setBoundingBox (const Rect & rect, const double pageWidth, const double pageHeight, const double margin) virtual
Implements LibBoard::Transform.
Definition at line 68 of file Transforms.cpp.
References LibBoard::Transform::_deltaX, LibBoard::Transform::_deltaY, LibBoard::Transform::_height, LibBoard::Transform::_scale, LibBoard::Rect::height, LibBoard::Rect::left, LibBoard::Rect::top, and LibBoard::Rect::width.
Referenced by LibBoard::Board::saveEPS().
 {
   if ( pageWidth <= 0 || pageHeight <= 0 ) {
     _scale = 1.0f;
     // _deltaX = - rect.left;
     _deltaX = 0.5 * 210 * ppmm - ( rect.left + 0.5 * rect.width );
     // _deltaY = - ( rect.top - rect.height );
     _deltaY = 0.5 * 297 * ppmm - ( rect.top - 0.5 * rect.height );
     _height = rect.height;
   } else {
     const double w = pageWidth - 2 * margin;
     const double h = pageHeight - 2 * margin;
     if ( ( rect.height / rect.width ) > ( h / w ) ) {
       _scale = h * ppmm / rect.height;
     } else {
       _scale = w * ppmm / rect.width;
     }
     _deltaX = 0.5 * pageWidth * ppmm - _scale * ( rect.left + 0.5 * rect.width );
     _deltaY = 0.5 * pageHeight * ppmm - _scale * ( rect.top - 0.5 * rect.height );
     _height = pageHeight * ppmm;
   }
 }
The documentation for this struct was generated from the following files:
Transforms.h
Transforms.cpp