DGtal: MidPointsRange Class Reference
MidPointsRange Class Reference
Public Types
typedef GridCurve::Storage Storage
typedef Storage::const_iterator ConstIteratorOnSCells
typedef SCellToMidPoint< KSpace > Functor
typedef ConstIteratorAdapter
< ConstIteratorOnSCells,
Functor, typename
KSpace::Space::RealPoint > ConstIterator
typedef std::reverse_iterator
< ConstIterator > ConstReverseIterator
typedef Circulator< ConstIterator > ConstCirculator
typedef std::reverse_iterator
< ConstCirculator > ConstReverseCirculator
Public Member Functions
MidPointsRange (const GridCurve *aGridCurve)
MidPointsRange (const MidPointsRange &aOther)
MidPointsRange & operator= (const MidPointsRange &other)
~MidPointsRange ()
Storage::size_type size () const
bool isValid () const
void selfDisplay (std::ostream &out) const
DGtal::DrawableWithBoard2D * defaultStyle () const
DGtal::DrawableWithBoard2D * defaultStyle (std::string) const
std::string className () const
void selfDraw (Board2D &aBoard) const
ConstIterator begin () const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rend () const
ConstCirculator c () const
ConstReverseCirculator rc () const
Private Attributes
const GridCurve * myC
Functor myFunctor
Friends
ostream & operator<< (ostream &out, const MidPointsRange &object)
DGtal::DrawableWithBoard2D * defaultStyle (const MidPointsRange &mpr)
DGtal::DrawableWithBoard2D * defaultStyle (const MidPointsRange &mpr, std::string)
void draw (Board2D &aBoard, const MidPointsRange &mpr)
Detailed Description
Aim: model of CConstRange that provides services to (circularly)iterate over the signed 1-cells of a grid curve, viewed as points of half-integer coordinates.
(Included in GridCurve.h)
See also:
GridCurve.h exampleGridCurve2d.cpp testGridCurve.cpp
Definition at line 490 of file GridCurveRanges.ih.
Member Typedef Documentation
typedef Circulator<ConstIterator> MidPointsRange::ConstCirculator
Definition at line 505 of file GridCurveRanges.ih.
typedef ConstIteratorAdapter<ConstIteratorOnSCells,Functor, typename KSpace::Space::RealPoint> MidPointsRange::ConstIterator
Definition at line 502 of file GridCurveRanges.ih.
typedef Storage::const_iterator MidPointsRange::ConstIteratorOnSCells
Definition at line 497 of file GridCurveRanges.ih.
typedef std::reverse_iterator<ConstCirculator> MidPointsRange::ConstReverseCirculator
Definition at line 506 of file GridCurveRanges.ih.
typedef std::reverse_iterator<ConstIterator> MidPointsRange::ConstReverseIterator
Definition at line 503 of file GridCurveRanges.ih.
typedef SCellToMidPoint<KSpace> MidPointsRange::Functor
Definition at line 499 of file GridCurveRanges.ih.
typedef GridCurve::Storage MidPointsRange::Storage
Definition at line 496 of file GridCurveRanges.ih.
Constructor & Destructor Documentation
MidPointsRange::MidPointsRange (const GridCurve * aGridCurve) [inline]
Constructor.
Parameters:
aGridCurve a grid curve.
Definition at line 514 of file GridCurveRanges.ih.
: myC(aGridCurve), myFunctor(Functor(myC->myK)){}
MidPointsRange::MidPointsRange (const MidPointsRange & aOther) [inline]
Copy constructor.
Parameters:
other the iterator to clone.
Definition at line 520 of file GridCurveRanges.ih.
    : myC( aOther.myC ), myFunctor( aOther.myFunctor) {}
MidPointsRange::~MidPointsRange () [inline]
Destructor. Does nothing.
Definition at line 541 of file GridCurveRanges.ih.
{}
Member Function Documentation
ConstIterator MidPointsRange::begin () const [inline]
Iterator service.
Returns:
begin iterator
Definition at line 654 of file GridCurveRanges.ih.
References myC, and myFunctor.
Referenced by c(), rend(), selfDisplay(), and selfDraw().
{
    return ConstIterator( myC->my1SCells.begin(), myFunctor );
  }
ConstCirculator MidPointsRange::c () const [inline]
Circulator service.
Returns:
a circulator
Definition at line 686 of file GridCurveRanges.ih.
References begin(), and end().
Referenced by rc().
{
    return ConstCirculator( this->begin(), this->begin(), this->end() );
  }
std::string MidPointsRange::className () const [inline]
Returns:
the style name used for drawing this object.
Definition at line 610 of file GridCurveRanges.ih.
  {
    return "MidPointsRange";
  }
DGtal::DrawableWithBoard2D* MidPointsRange::defaultStyle () const [inline]
Default drawing style object.
Returns:
the dyn. alloc. default style for this object.
Definition at line 586 of file GridCurveRanges.ih.
  {
    return new DrawableWithBoard2D;
  }
DGtal::DrawableWithBoard2D* MidPointsRange::defaultStyle (std::string) const [inline]
Default drawing style object.
Parameters:
mode the drawing mode
Returns:
the dyn. alloc. default style for this object.
Definition at line 599 of file GridCurveRanges.ih.
  {
    return new DrawableWithBoard2D;
  }
ConstIterator MidPointsRange::end () const [inline]
Iterator service.
Returns:
end iterator
Definition at line 662 of file GridCurveRanges.ih.
References myC, and myFunctor.
Referenced by c(), rbegin(), selfDisplay(), and selfDraw().
{
    return ConstIterator( myC->my1SCells.end(), myFunctor );
  }
bool MidPointsRange::isValid () const [inline]
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
Definition at line 554 of file GridCurveRanges.ih.
{ return true; }
MidPointsRange& MidPointsRange::operator= (const MidPointsRange & other) [inline]
Assignment.
Parameters:
other the iterator to copy.
Returns:
a reference on 'this'.
Definition at line 528 of file GridCurveRanges.ih.
References myC, and myFunctor.
  {
    if ( this != &other )
      {
        myC = other.myC;
        myFunctor = other.myFunctor;
      }
    return *this;
  }
ConstReverseIterator MidPointsRange::rbegin () const [inline]
Iterator service.
Returns:
rbegin iterator
Definition at line 670 of file GridCurveRanges.ih.
References end().
{
    return ConstReverseIterator(this->end());
  }
ConstReverseCirculator MidPointsRange::rc () const [inline]
Circulator service.
Returns:
a reverse circulator
Definition at line 694 of file GridCurveRanges.ih.
References c().
{
    return ConstReverseCirculator( this->c() );
  }
ConstReverseIterator MidPointsRange::rend () const [inline]
Iterator service.
Returns:
rend iterator
Definition at line 678 of file GridCurveRanges.ih.
References begin().
{
    return ConstReverseIterator(this->begin());
  }
void MidPointsRange::selfDisplay (std::ostream & out) const [inline]
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
Definition at line 561 of file GridCurveRanges.ih.
References begin(), and end().
  {
    typedef typename IteratorCirculatorTraits<ConstIterator>::Value Value;
    out << "[MidPointsRange]" << std::endl;
    out << "\t";
    std::copy( this->begin(), this->end(), ostream_iterator<Value>(out, ", ") );
    out << std::endl;
  }
void MidPointsRange::selfDraw (Board2D & aBoard) const [inline]
Draw the object on a Board2D board
Parameters:
board the output board where the object is drawn.
Definition at line 619 of file GridCurveRanges.ih.
References begin(), and end().
  {
    ConstIterator it ( this->begin() );
    ConstIterator itEnd ( this->end() );
    for( ; it != itEnd; ++it)
      {
        typename IteratorCirculatorTraits<ConstIterator>::Value p(*it);
        double s = 0.1;
        aBoard.drawLine( p[0]-s, p[1]-s, p[0]+s, p[1]+s );
        aBoard.drawLine( p[0]-s, p[1]+s, p[0]+s, p[1]-s );
      }
  }
Storage::size_type MidPointsRange::size () const [inline]
Returns:
the size of the range
Definition at line 546 of file GridCurveRanges.ih.
References myC.
  {
    return myC->my1SCells.size();
  }
Friends And Related Function Documentation
DGtal::DrawableWithBoard2D* defaultStyle (const MidPointsRange & mpr) [friend]
Definition at line 590 of file GridCurveRanges.ih.
  {
    return mpr.defaultStyle();
  }
DGtal::DrawableWithBoard2D* defaultStyle (const MidPointsRange & mpr, std::string) [friend]
Definition at line 603 of file GridCurveRanges.ih.
  {
    return mpr.defaultStyle();
  }
void draw (Board2D & aBoard, const MidPointsRange & mpr) [friend]
Definition at line 631 of file GridCurveRanges.ih.
  {
    mpr.selfDraw(aBoard);
  }
ostream& operator<< (ostream & out, const MidPointsRange & object) [friend]
Overloads 'operator<<' for displaying objects of class 'MidPointsRange'.
Parameters:
out the output stream where the object is written.
object the object of class 'MidPointsRange' to write.
Returns:
the output stream after the writing.
Definition at line 576 of file GridCurveRanges.ih.
  {
    object.selfDisplay( out );
    return out;
  }
Field Documentation
const GridCurve* MidPointsRange::myC [private]
Private member myC is an aliasing pointer to any grid curve
Definition at line 641 of file GridCurveRanges.ih.
Referenced by begin(), end(), operator=(), and size().
Functor MidPointsRange::myFunctor [private]
Functor transforming a signed cell into a real point
Definition at line 645 of file GridCurveRanges.ih.
Referenced by begin(), end(), and operator=().
The documentation for this class was generated from the following file:
GridCurveRanges.ih