DGtal: CodesRange Class Reference
CodesRange Class Reference
Public Types
typedef GridCurve::Storage Storage
typedef Storage::const_iterator ConstIteratorOnSCells
typedef SCellToCode< KSpace > Functor
typedef ConstIteratorAdapter
< ConstIteratorOnSCells,
Functor, char > ConstIterator
typedef std::reverse_iterator
< ConstIterator > ConstReverseIterator
typedef Circulator< ConstIterator > ConstCirculator
typedef std::reverse_iterator
< ConstCirculator > ConstReverseCirculator
Public Member Functions
CodesRange (const GridCurve *aGridCurve)
CodesRange (const CodesRange &aOther)
CodesRange & operator= (const CodesRange &other)
~CodesRange ()
Storage::size_type size () const
bool isValid () const
void selfDisplay (std::ostream &out) const
ConstIterator begin () const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rend () const
ConstCirculator c () const
ConstReverseCirculator rc () const
Private Attributes
const GridCurve * myC
Functor myFunctor
Friends
class GridCurve< KSpace >
ostream & operator<< (ostream &out, const CodesRange &object)
Detailed Description
Aim: model of CConstRange that provides services to (circularly)iterate over the 1-cells of a 2d grid curve, viewed as chain codes:
0 for a shift to the right
2 for a shift to the left
1 for a shift to the up
3 for a shift to the bottom
(Included in GridCurve.h)
See also:
GridCurve.h exampleGridCurve2d.cpp testGridCurve.cpp
Definition at line 1655 of file GridCurveRanges.ih.
Member Typedef Documentation
typedef Circulator<ConstIterator> CodesRange::ConstCirculator
Definition at line 1671 of file GridCurveRanges.ih.
typedef ConstIteratorAdapter<ConstIteratorOnSCells,Functor,char> CodesRange::ConstIterator
Definition at line 1668 of file GridCurveRanges.ih.
typedef Storage::const_iterator CodesRange::ConstIteratorOnSCells
Definition at line 1664 of file GridCurveRanges.ih.
typedef std::reverse_iterator<ConstCirculator> CodesRange::ConstReverseCirculator
Definition at line 1672 of file GridCurveRanges.ih.
typedef std::reverse_iterator<ConstIterator> CodesRange::ConstReverseIterator
Definition at line 1669 of file GridCurveRanges.ih.
typedef SCellToCode<KSpace> CodesRange::Functor
Definition at line 1666 of file GridCurveRanges.ih.
typedef GridCurve::Storage CodesRange::Storage
Definition at line 1663 of file GridCurveRanges.ih.
Constructor & Destructor Documentation
CodesRange::CodesRange (const GridCurve * aGridCurve) [inline]
Constructor.
Definition at line 1678 of file GridCurveRanges.ih.
: myC(aGridCurve), myFunctor(Functor(myC->myK)){}
CodesRange::CodesRange (const CodesRange & aOther) [inline]
Copy constructor.
Parameters:
other the iterator to clone.
Definition at line 1684 of file GridCurveRanges.ih.
    : myC( aOther.myC ), myFunctor( aOther.myFunctor ){}
CodesRange::~CodesRange () [inline]
Destructor. Does nothing.
Definition at line 1705 of file GridCurveRanges.ih.
{}
Member Function Documentation
ConstIterator CodesRange::begin () const [inline]
Iterator service.
Returns:
begin iterator
Definition at line 1764 of file GridCurveRanges.ih.
References myC, and myFunctor.
Referenced by c(), rend(), and selfDisplay().
{
    return ConstIterator( myC->my1SCells.begin(), myFunctor );
  }
ConstCirculator CodesRange::c () const [inline]
Circulator service.
Returns:
a circulator
Definition at line 1796 of file GridCurveRanges.ih.
References begin(), and end().
Referenced by rc().
{
    return ConstCirculator( this->begin(), this->begin(), this->end() );
  }
ConstIterator CodesRange::end () const [inline]
Iterator service.
Returns:
end iterator
Definition at line 1772 of file GridCurveRanges.ih.
References myC, and myFunctor.
Referenced by c(), rbegin(), and selfDisplay().
{
    return ConstIterator( myC->my1SCells.end(), myFunctor );
  }
bool CodesRange::isValid () const [inline]
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
Definition at line 1719 of file GridCurveRanges.ih.
{ return true; }
CodesRange& CodesRange::operator= (const CodesRange & other) [inline]
Assignment.
Parameters:
other the iterator to copy.
Returns:
a reference on 'this'.
Definition at line 1692 of file GridCurveRanges.ih.
References myC, and myFunctor.
  {
    if ( this != &other )
      {
        myC = other.myC;
        myFunctor = other.myFunctor;
      }
    return *this;
  }
ConstReverseIterator CodesRange::rbegin () const [inline]
Iterator service.
Returns:
rbegin iterator
Definition at line 1780 of file GridCurveRanges.ih.
References end().
{
    return ConstReverseIterator(this->end());
  }
ConstReverseCirculator CodesRange::rc () const [inline]
Circulator service.
Returns:
a reverse circulator
Definition at line 1804 of file GridCurveRanges.ih.
References c().
{
    return ConstReverseCirculator( this->c() );
  }
ConstReverseIterator CodesRange::rend () const [inline]
Iterator service.
Returns:
rend iterator
Definition at line 1788 of file GridCurveRanges.ih.
References begin().
{
    return ConstReverseIterator(this->begin());
  }
void CodesRange::selfDisplay (std::ostream & out) const [inline]
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
Definition at line 1726 of file GridCurveRanges.ih.
References begin(), and end().
  {
    typedef typename IteratorCirculatorTraits<ConstIterator>::Value Value;
    out << "[CodesRange]" << std::endl;
    out << "\t";
    std::copy( this->begin(), this->end(), ostream_iterator<Value>(out, "") );
    out << std::endl;
  }
Storage::size_type CodesRange::size () const [inline]
Returns:
the size of the range
Definition at line 1710 of file GridCurveRanges.ih.
References myC.
  {
    return myC->my1SCells.size();
  }
Friends And Related Function Documentation
friend class GridCurve< KSpace > [friend]
Definition at line 1661 of file GridCurveRanges.ih.
ostream& operator<< (ostream & out, const CodesRange & object) [friend]
Overloads 'operator<<' for displaying objects of class 'CodesRange'.
Parameters:
out the output stream where the object is written.
object the object of class 'CodesRange' to write.
Returns:
the output stream after the writing.
Definition at line 1741 of file GridCurveRanges.ih.
  {
    object.selfDisplay( out );
    return out;
  }
Field Documentation
const GridCurve* CodesRange::myC [private]
Private member myC is an aliasing pointer to any grid curve
Definition at line 1751 of file GridCurveRanges.ih.
Referenced by begin(), end(), operator=(), and size().
Functor CodesRange::myFunctor [private]
Functor transforming a signed cell into a char containing its code
Definition at line 1755 of file GridCurveRanges.ih.
Referenced by begin(), end(), and operator=().
The documentation for this class was generated from the following file:
GridCurveRanges.ih