DGtal: InnerPointsRange Class Reference
InnerPointsRange Class Reference
Public Types
typedef GridCurve::Storage Storage
typedef Storage::const_iterator ConstIteratorOnSCells
typedef SCellToInnerPoint< KSpace > Functor
typedef ConstIteratorAdapter
< ConstIteratorOnSCells,
Functor, Point > ConstIterator
typedef std::reverse_iterator
< ConstIterator > ConstReverseIterator
typedef Circulator< ConstIterator > ConstCirculator
typedef std::reverse_iterator
< ConstCirculator > ConstReverseCirculator
Public Member Functions
InnerPointsRange (const GridCurve *aGridCurve)
InnerPointsRange (const InnerPointsRange &aOther)
InnerPointsRange & operator= (const InnerPointsRange &other)
~InnerPointsRange ()
Storage::size_type size () const
bool isValid () const
void selfDisplay (std::ostream &out) const
DGtal::DrawableWithBoard2D * defaultStyle () const
DGtal::DrawableWithBoard2D * defaultStyle (std::string) const
std::string className () const
void selfDraw (Board2D &aBoard) const
ConstIterator begin () const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rend () const
ConstCirculator c () const
ConstReverseCirculator rc () const
Private Attributes
const GridCurve * myC
Functor myFunctor
Friends
ostream & operator<< (ostream &out, const InnerPointsRange &object)
DGtal::DrawableWithBoard2D * defaultStyle (const InnerPointsRange &ipr)
DGtal::DrawableWithBoard2D * defaultStyle (const InnerPointsRange &ipr, std::string)
void draw (Board2D &aBoard, const InnerPointsRange &ipr)
Detailed Description
Aim: model of CConstRange that provides services to (circularly)iterate over the 2-cells (viewed as points of integer coordinates) that are directly incident to the signed 1-cells of a 2d grid curve.
(Included in GridCurve.h)
See also:
GridCurve.h exampleGridCurve2d.cpp testGridCurve.cpp
Definition at line 956 of file GridCurveRanges.ih.
Member Typedef Documentation
typedef Circulator<ConstIterator> InnerPointsRange::ConstCirculator
Definition at line 970 of file GridCurveRanges.ih.
typedef ConstIteratorAdapter<ConstIteratorOnSCells,Functor,Point> InnerPointsRange::ConstIterator
Definition at line 967 of file GridCurveRanges.ih.
typedef Storage::const_iterator InnerPointsRange::ConstIteratorOnSCells
Definition at line 963 of file GridCurveRanges.ih.
typedef std::reverse_iterator<ConstCirculator> InnerPointsRange::ConstReverseCirculator
Definition at line 971 of file GridCurveRanges.ih.
typedef std::reverse_iterator<ConstIterator> InnerPointsRange::ConstReverseIterator
Definition at line 968 of file GridCurveRanges.ih.
typedef SCellToInnerPoint<KSpace> InnerPointsRange::Functor
Definition at line 965 of file GridCurveRanges.ih.
typedef GridCurve::Storage InnerPointsRange::Storage
Definition at line 962 of file GridCurveRanges.ih.
Constructor & Destructor Documentation
InnerPointsRange::InnerPointsRange (const GridCurve * aGridCurve) [inline]
Constructor.
Parameters:
aGridCurve a grid curve.
Definition at line 980 of file GridCurveRanges.ih.
: myC(aGridCurve), myFunctor(Functor(myC->myK)){}
InnerPointsRange::InnerPointsRange (const InnerPointsRange & aOther) [inline]
Copy constructor.
Parameters:
other the iterator to clone.
Definition at line 986 of file GridCurveRanges.ih.
    : myC( aOther.myC ), myFunctor( aOther.myFunctor) {}
InnerPointsRange::~InnerPointsRange () [inline]
Destructor. Does nothing.
Definition at line 1007 of file GridCurveRanges.ih.
{}
Member Function Documentation
ConstIterator InnerPointsRange::begin () const [inline]
Iterator service.
Returns:
begin iterator
Definition at line 1122 of file GridCurveRanges.ih.
References myC, and myFunctor.
Referenced by c(), rend(), selfDisplay(), and selfDraw().
{
    return ConstIterator( myC->my1SCells.begin(), myFunctor );
  }
ConstCirculator InnerPointsRange::c () const [inline]
Circulator service.
Returns:
a circulator
Definition at line 1154 of file GridCurveRanges.ih.
References begin(), and end().
Referenced by rc().
{
    return ConstCirculator( this->begin(), this->begin(), this->end() );
  }
std::string InnerPointsRange::className () const [inline]
Returns:
the style name used for drawing this object.
Definition at line 1078 of file GridCurveRanges.ih.
  {
    return "InnerPointsRange";
  }
DGtal::DrawableWithBoard2D* InnerPointsRange::defaultStyle () const [inline]
Default drawing style object.
Returns:
the dyn. alloc. default style for this object.
Definition at line 1053 of file GridCurveRanges.ih.
  {
    return new DrawableWithBoard2D;
  }
DGtal::DrawableWithBoard2D* InnerPointsRange::defaultStyle (std::string) const [inline]
Default drawing style object.
Parameters:
mode the drawing mode
Returns:
the dyn. alloc. default style for this object.
Definition at line 1066 of file GridCurveRanges.ih.
  {
    return new DrawableWithBoard2D;
  }
ConstIterator InnerPointsRange::end () const [inline]
Iterator service.
Returns:
end iterator
Definition at line 1130 of file GridCurveRanges.ih.
References myC, and myFunctor.
Referenced by c(), rbegin(), selfDisplay(), and selfDraw().
{
    return ConstIterator( myC->my1SCells.end(), myFunctor );
  }
bool InnerPointsRange::isValid () const [inline]
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
Definition at line 1021 of file GridCurveRanges.ih.
{ return true; }
InnerPointsRange& InnerPointsRange::operator= (const InnerPointsRange & other) [inline]
Assignment.
Parameters:
other the iterator to copy.
Returns:
a reference on 'this'.
Definition at line 994 of file GridCurveRanges.ih.
References myC, and myFunctor.
  {
    if ( this != &other )
      {
        myC = other.myC;
        myFunctor = other.myFunctor;
      }
    return *this;
  }
ConstReverseIterator InnerPointsRange::rbegin () const [inline]
Iterator service.
Returns:
rbegin iterator
Definition at line 1138 of file GridCurveRanges.ih.
References end().
{
    return ConstReverseIterator(this->end());
  }
ConstReverseCirculator InnerPointsRange::rc () const [inline]
Circulator service.
Returns:
a reverse circulator
Definition at line 1162 of file GridCurveRanges.ih.
References c().
{
    return ConstReverseCirculator( this->c() );
  }
ConstReverseIterator InnerPointsRange::rend () const [inline]
Iterator service.
Returns:
rend iterator
Definition at line 1146 of file GridCurveRanges.ih.
References begin().
{
    return ConstReverseIterator(this->begin());
  }
void InnerPointsRange::selfDisplay (std::ostream & out) const [inline]
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
Definition at line 1028 of file GridCurveRanges.ih.
References begin(), and end().
  {
    typedef typename IteratorCirculatorTraits<ConstIterator>::Value Value;
    out << "[InnerPointsRange]" << std::endl;
    out << "\t";
    std::copy( this->begin(), this->end(), ostream_iterator<Value>(out, ", ") );
    out << std::endl;
  }
void InnerPointsRange::selfDraw (Board2D & aBoard) const [inline]
Draw the object on a Board2D board
Parameters:
board the output board where the object is drawn.
Definition at line 1087 of file GridCurveRanges.ih.
References begin(), and end().
  {
    ConstIterator it ( this->begin() );
    ConstIterator itEnd ( this->end() );
    for( ; it != itEnd; ++it)
      {
        aBoard << SetMode( it->className(), "Both" )
               << CustomStyle( it->className(),
                               new CustomFillColor( Color::Blue ) )
               << *it;
      }
  }
Storage::size_type InnerPointsRange::size () const [inline]
Returns:
the size of the range
Definition at line 1012 of file GridCurveRanges.ih.
References myC.
  {
    return myC->my1SCells.size();
  }
Friends And Related Function Documentation
DGtal::DrawableWithBoard2D* defaultStyle (const InnerPointsRange & ipr) [friend]
Definition at line 1057 of file GridCurveRanges.ih.
  {
    return ipr.defaultStyle();
  }
DGtal::DrawableWithBoard2D* defaultStyle (const InnerPointsRange & ipr, std::string) [friend]
Definition at line 1070 of file GridCurveRanges.ih.
  {
    return ipr.defaultStyle();
  }
void draw (Board2D & aBoard, const InnerPointsRange & ipr) [friend]
Definition at line 1099 of file GridCurveRanges.ih.
  {
    ipr.selfDraw(aBoard);
  }
ostream& operator<< (ostream & out, const InnerPointsRange & object) [friend]
Overloads 'operator<<' for displaying objects of class 'InnerPointsRange'.
Parameters:
out the output stream where the object is written.
object the object of class 'InnerPointsRange' to write.
Returns:
the output stream after the writing.
Definition at line 1043 of file GridCurveRanges.ih.
  {
    object.selfDisplay( out );
    return out;
  }
Field Documentation
const GridCurve* InnerPointsRange::myC [private]
Private member myC is an aliasing pointer to any grid curve
Definition at line 1109 of file GridCurveRanges.ih.
Referenced by begin(), end(), operator=(), and size().
Functor InnerPointsRange::myFunctor [private]
Functor transforming a signed cell into a digital point
Definition at line 1113 of file GridCurveRanges.ih.
Referenced by begin(), end(), and operator=().
The documentation for this class was generated from the following file:
GridCurveRanges.ih