DGtal: ArrowsRange Class Reference
ArrowsRange Class Reference
Public Types
typedef GridCurve::Storage Storage
typedef Storage::const_iterator ConstIteratorOnSCells
typedef SCellToArrow< KSpace > Functor
typedef ConstIteratorAdapter
< ConstIteratorOnSCells,
Functor, std::pair< Point,
Vector > > ConstIterator
typedef std::reverse_iterator
< ConstIterator > ConstReverseIterator
typedef Circulator< ConstIterator > ConstCirculator
typedef std::reverse_iterator
< ConstCirculator > ConstReverseCirculator
Public Member Functions
ArrowsRange (const GridCurve *aGridCurve)
ArrowsRange (const ArrowsRange &aOther)
ArrowsRange & operator= (const ArrowsRange &other)
~ArrowsRange ()
Storage::size_type size () const
bool isValid () const
void selfDisplay (std::ostream &out) const
DGtal::DrawableWithBoard2D * defaultStyle () const
DGtal::DrawableWithBoard2D * defaultStyle (std::string) const
std::string className () const
void selfDraw (Board2D &aBoard) const
ConstIterator begin () const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rend () const
ConstCirculator c () const
ConstReverseCirculator rc () const
Private Attributes
const GridCurve * myC
Functor myFunctor
Friends
ostream & operator<< (ostream &out, const ArrowsRange &object)
DGtal::DrawableWithBoard2D * defaultStyle (const ArrowsRange &ar)
DGtal::DrawableWithBoard2D * defaultStyle (const ArrowsRange &ar, std::string)
void draw (Board2D &aBoard, const ArrowsRange &ar)
Detailed Description
Aim: model of CConstRange that provides services to (circularly)iterate over the signed 1-cells of a grid curve, viewed as pairs (point - shift vector), both in integer coordinates.
(Included in GridCurve.h)
See also:
GridCurve.h exampleGridCurve2d.cpp testGridCurve.cpp
Definition at line 717 of file GridCurveRanges.ih.
Member Typedef Documentation
typedef Circulator<ConstIterator> ArrowsRange::ConstCirculator
Definition at line 732 of file GridCurveRanges.ih.
typedef ConstIteratorAdapter<ConstIteratorOnSCells,Functor, std::pair<Point,Vector> > ArrowsRange::ConstIterator
Definition at line 729 of file GridCurveRanges.ih.
typedef Storage::const_iterator ArrowsRange::ConstIteratorOnSCells
Definition at line 724 of file GridCurveRanges.ih.
typedef std::reverse_iterator<ConstCirculator> ArrowsRange::ConstReverseCirculator
Definition at line 733 of file GridCurveRanges.ih.
typedef std::reverse_iterator<ConstIterator> ArrowsRange::ConstReverseIterator
Definition at line 730 of file GridCurveRanges.ih.
typedef SCellToArrow<KSpace> ArrowsRange::Functor
Definition at line 726 of file GridCurveRanges.ih.
typedef GridCurve::Storage ArrowsRange::Storage
Definition at line 723 of file GridCurveRanges.ih.
Constructor & Destructor Documentation
ArrowsRange::ArrowsRange (const GridCurve * aGridCurve) [inline]
Constructor.
Parameters:
aGridCurve a grid curve.
Definition at line 741 of file GridCurveRanges.ih.
: myC(aGridCurve), myFunctor(Functor(myC->myK)) {}
ArrowsRange::ArrowsRange (const ArrowsRange & aOther) [inline]
Copy constructor.
Parameters:
other the iterator to clone.
Definition at line 747 of file GridCurveRanges.ih.
    : myC( aOther.myC ), myFunctor( aOther.myFunctor ){}
ArrowsRange::~ArrowsRange () [inline]
Destructor. Does nothing.
Definition at line 768 of file GridCurveRanges.ih.
{}
Member Function Documentation
ConstIterator ArrowsRange::begin () const [inline]
Iterator service.
Returns:
begin iterator
Definition at line 892 of file GridCurveRanges.ih.
References myC, and myFunctor.
Referenced by c(), rend(), selfDisplay(), and selfDraw().
{
    return ConstIterator( myC->my1SCells.begin(), myFunctor );
  }
ConstCirculator ArrowsRange::c () const [inline]
Circulator service.
Returns:
a circulator
Definition at line 924 of file GridCurveRanges.ih.
References begin(), and end().
Referenced by rc().
{
    return ConstCirculator( this->begin(), this->begin(), this->end() );
  }
std::string ArrowsRange::className () const [inline]
Returns:
the style name used for drawing this object.
Definition at line 844 of file GridCurveRanges.ih.
  {
    return "ArrowsRange";
  }
DGtal::DrawableWithBoard2D* ArrowsRange::defaultStyle () const [inline]
Default drawing style object.
Returns:
the dyn. alloc. default style for this object.
Definition at line 819 of file GridCurveRanges.ih.
  {
    return new DrawableWithBoard2D;
  }
DGtal::DrawableWithBoard2D* ArrowsRange::defaultStyle (std::string) const [inline]
Default drawing style object.
Parameters:
mode the drawing mode
Returns:
the dyn. alloc. default style for this object.
Definition at line 832 of file GridCurveRanges.ih.
  {
    return new DrawableWithBoard2D;
  }
ConstIterator ArrowsRange::end () const [inline]
Iterator service.
Returns:
end iterator
Definition at line 900 of file GridCurveRanges.ih.
References myC, and myFunctor.
Referenced by c(), rbegin(), selfDisplay(), and selfDraw().
{
    return ConstIterator( myC->my1SCells.end(), myFunctor );
  }
bool ArrowsRange::isValid () const [inline]
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
Definition at line 782 of file GridCurveRanges.ih.
{ return true; }
ArrowsRange& ArrowsRange::operator= (const ArrowsRange & other) [inline]
Assignment.
Parameters:
other the iterator to copy.
Returns:
a reference on 'this'.
Definition at line 755 of file GridCurveRanges.ih.
References myC, and myFunctor.
  {
    if ( this != &other )
      {
        myC = other.myC;
        myFunctor = other.myFunctor;
      }
    return *this;
  }
ConstReverseIterator ArrowsRange::rbegin () const [inline]
Iterator service.
Returns:
rbegin iterator
Definition at line 908 of file GridCurveRanges.ih.
References end().
{
    return ConstReverseIterator(this->end());
  }
ConstReverseCirculator ArrowsRange::rc () const [inline]
Circulator service.
Returns:
a reverse circulator
Definition at line 932 of file GridCurveRanges.ih.
References c().
{
    return ConstReverseCirculator( this->c() );
  }
ConstReverseIterator ArrowsRange::rend () const [inline]
Iterator service.
Returns:
rend iterator
Definition at line 916 of file GridCurveRanges.ih.
References begin().
{
    return ConstReverseIterator(this->begin());
  }
void ArrowsRange::selfDisplay (std::ostream & out) const [inline]
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
Definition at line 789 of file GridCurveRanges.ih.
References begin(), and end().
  {
    ConstIterator it( this->begin() );
    ConstIterator itEnd( this->end() );
    out << "[ArrowsRange]" << std::endl;
    out << "\t";
    for ( ; it != itEnd; ++it)
      {
        typename IteratorCirculatorTraits<ConstIterator>::Value pair(*it);
        out << pair.first << pair.second << ", ";
      }
    out << std::endl;
  }
void ArrowsRange::selfDraw (Board2D & aBoard) const [inline]
Draw the object on a Board2D board
Parameters:
board the output board where the object is drawn.
Definition at line 853 of file GridCurveRanges.ih.
References begin(), DGtal::PointVector< dim, TEuclideanRing >::className(), draw, and end().
  {
    ConstIterator it ( this->begin() );
    ConstIterator itEnd ( this->end() );
    for( ; it != itEnd; ++it)
      {
        typename IteratorCirculatorTraits<ConstIterator>::Value pair(*it);
        Vector shift( pair.second );
        aBoard << CustomStyle( shift.className(),
                               new CustomPen( Color::Black, Color::Black, 1.0,
                                              Board2D::Shape::SolidStyle,
                                              Board2D::Shape::RoundCap,
                                              Board2D::Shape::RoundJoin ) );
        draw(aBoard, shift, pair.first);
      }
  }
Storage::size_type ArrowsRange::size () const [inline]
Returns:
the size of the range
Definition at line 773 of file GridCurveRanges.ih.
References myC.
  {
    return myC->my1SCells.size();
  }
Friends And Related Function Documentation
DGtal::DrawableWithBoard2D* defaultStyle (const ArrowsRange & ar) [friend]
Definition at line 823 of file GridCurveRanges.ih.
  {
    return ar.defaultStyle();
  }
DGtal::DrawableWithBoard2D* defaultStyle (const ArrowsRange & ar, std::string) [friend]
Definition at line 836 of file GridCurveRanges.ih.
  {
    return ar.defaultStyle();
  }
void draw (Board2D & aBoard, const ArrowsRange & ar) [friend]
Definition at line 869 of file GridCurveRanges.ih.
Referenced by selfDraw().
  {
    ar.selfDraw(aBoard);
  }
ostream& operator<< (ostream & out, const ArrowsRange & object) [friend]
Overloads 'operator<<' for displaying objects of class 'ArrowsRange'.
Parameters:
out the output stream where the object is written.
object the object of class 'ArrowsRange' to write.
Returns:
the output stream after the writing.
Definition at line 809 of file GridCurveRanges.ih.
  {
    object.selfDisplay( out );
    return out;
  }
Field Documentation
const GridCurve* ArrowsRange::myC [private]
Private member myC is an aliasing pointer to any grid curve
Definition at line 879 of file GridCurveRanges.ih.
Referenced by begin(), end(), operator=(), and size().
Functor ArrowsRange::myFunctor [private]
Functor transforming a signed cell into an arrow (pair point-vector)
Definition at line 883 of file GridCurveRanges.ih.
Referenced by begin(), end(), and operator=().
The documentation for this class was generated from the following file:
GridCurveRanges.ih