DGtal: IncidentPointsRange Class Reference
IncidentPointsRange Class Reference
Public Types
typedef GridCurve::Storage Storage
typedef Storage::const_iterator ConstIteratorOnSCells
typedef SCellToIncidentPoints
< KSpace > Functor
typedef ConstIteratorAdapter
< ConstIteratorOnSCells,
Functor, std::pair< Point,
Point > > ConstIterator
typedef std::reverse_iterator
< ConstIterator > ConstReverseIterator
typedef Circulator< ConstIterator > ConstCirculator
typedef std::reverse_iterator
< ConstCirculator > ConstReverseCirculator
Public Member Functions
IncidentPointsRange (const GridCurve *aGridCurve)
IncidentPointsRange (const IncidentPointsRange &aOther)
IncidentPointsRange & operator= (const IncidentPointsRange &other)
~IncidentPointsRange ()
Storage::size_type size () const
bool isValid () const
void selfDisplay (std::ostream &out) const
DGtal::DrawableWithBoard2D * defaultStyle () const
DGtal::DrawableWithBoard2D * defaultStyle (std::string) const
std::string className () const
void selfDraw (Board2D &aBoard) const
ConstIterator begin () const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rend () const
ConstCirculator c () const
ConstReverseCirculator rc () const
Private Attributes
const GridCurve * myC
Functor myFunctor
Friends
class GridCurve< KSpace >
ostream & operator<< (ostream &out, const IncidentPointsRange &object)
DGtal::DrawableWithBoard2D * defaultStyle (const IncidentPointsRange &ipr)
DGtal::DrawableWithBoard2D * defaultStyle (const IncidentPointsRange &ipr, std::string)
void draw (Board2D &aBoard, const IncidentPointsRange &ipr)
Detailed Description
Aim: model of CConstRange that provides services to (circularly)iterate over the two 2-cells (viewed as points of integer coordinates) that are (directly and indirectly) incident to the signed 1-cells of a 2d grid curve.
(Included in GridCurve.h)
See also:
GridCurve.h exampleGridCurve2d.cpp testGridCurve.cpp
Definition at line 1413 of file GridCurveRanges.ih.
Member Typedef Documentation
typedef Circulator<ConstIterator> IncidentPointsRange::ConstCirculator
Definition at line 1430 of file GridCurveRanges.ih.
typedef ConstIteratorAdapter<ConstIteratorOnSCells,Functor, std::pair<Point,Point> > IncidentPointsRange::ConstIterator
Definition at line 1427 of file GridCurveRanges.ih.
typedef Storage::const_iterator IncidentPointsRange::ConstIteratorOnSCells
Definition at line 1422 of file GridCurveRanges.ih.
typedef std::reverse_iterator<ConstCirculator> IncidentPointsRange::ConstReverseCirculator
Definition at line 1431 of file GridCurveRanges.ih.
typedef std::reverse_iterator<ConstIterator> IncidentPointsRange::ConstReverseIterator
Definition at line 1428 of file GridCurveRanges.ih.
typedef SCellToIncidentPoints<KSpace> IncidentPointsRange::Functor
Definition at line 1424 of file GridCurveRanges.ih.
typedef GridCurve::Storage IncidentPointsRange::Storage
Definition at line 1421 of file GridCurveRanges.ih.
Constructor & Destructor Documentation
IncidentPointsRange::IncidentPointsRange (const GridCurve * aGridCurve) [inline]
Constructor.
Parameters:
aGridCurve a grid curve.
Definition at line 1439 of file GridCurveRanges.ih.
: myC(aGridCurve), myFunctor(Functor(myC->myK)){}
IncidentPointsRange::IncidentPointsRange (const IncidentPointsRange & aOther) [inline]
Copy constructor.
Parameters:
other the iterator to clone.
Definition at line 1445 of file GridCurveRanges.ih.
    : myC( aOther.myC ), myFunctor( aOther.myFunctor ){}
IncidentPointsRange::~IncidentPointsRange () [inline]
Destructor. Does nothing.
Definition at line 1466 of file GridCurveRanges.ih.
{}
Member Function Documentation
ConstIterator IncidentPointsRange::begin () const [inline]
Iterator service.
Returns:
begin iterator
Definition at line 1589 of file GridCurveRanges.ih.
References myC, and myFunctor.
Referenced by c(), rend(), selfDisplay(), and selfDraw().
{
    return ConstIterator( myC->my1SCells.begin(), myFunctor );
  }
ConstCirculator IncidentPointsRange::c () const [inline]
Circulator service.
Returns:
a circulator
Definition at line 1621 of file GridCurveRanges.ih.
References begin(), and end().
Referenced by rc().
{
    return ConstCirculator( this->begin(), this->begin(), this->end() );
  }
std::string IncidentPointsRange::className () const [inline]
Returns:
the style name used for drawing this object.
Definition at line 1541 of file GridCurveRanges.ih.
  {
    return "IncidentPointsRange";
  }
DGtal::DrawableWithBoard2D* IncidentPointsRange::defaultStyle () const [inline]
Default drawing style object.
Returns:
the dyn. alloc. default style for this object.
Definition at line 1517 of file GridCurveRanges.ih.
  {
    return new DrawableWithBoard2D;
  }
DGtal::DrawableWithBoard2D* IncidentPointsRange::defaultStyle (std::string) const [inline]
Default drawing style object.
Parameters:
mode the drawing mode
Returns:
the dyn. alloc. default style for this object.
Definition at line 1530 of file GridCurveRanges.ih.
  {
    return new DrawableWithBoard2D;
  }
ConstIterator IncidentPointsRange::end () const [inline]
Iterator service.
Returns:
end iterator
Definition at line 1597 of file GridCurveRanges.ih.
References myC, and myFunctor.
Referenced by c(), rbegin(), selfDisplay(), and selfDraw().
{
    return ConstIterator( myC->my1SCells.end(), myFunctor );
  }
bool IncidentPointsRange::isValid () const [inline]
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
Definition at line 1480 of file GridCurveRanges.ih.
{ return true; }
IncidentPointsRange& IncidentPointsRange::operator= (const IncidentPointsRange & other) [inline]
Assignment.
Parameters:
other the iterator to copy.
Returns:
a reference on 'this'.
Definition at line 1453 of file GridCurveRanges.ih.
References myC, and myFunctor.
  {
    if ( this != &other )
      {
        myC = other.myC;
        myFunctor = other.myFunctor;
      }
    return *this;
  }
ConstReverseIterator IncidentPointsRange::rbegin () const [inline]
Iterator service.
Returns:
rbegin iterator
Definition at line 1605 of file GridCurveRanges.ih.
References end().
{
    return ConstReverseIterator(this->end());
  }
ConstReverseCirculator IncidentPointsRange::rc () const [inline]
Circulator service.
Returns:
a reverse circulator
Definition at line 1629 of file GridCurveRanges.ih.
References c().
{
    return ConstReverseCirculator( this->c() );
  }
ConstReverseIterator IncidentPointsRange::rend () const [inline]
Iterator service.
Returns:
rend iterator
Definition at line 1613 of file GridCurveRanges.ih.
References begin().
{
    return ConstReverseIterator(this->begin());
  }
void IncidentPointsRange::selfDisplay (std::ostream & out) const [inline]
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
Definition at line 1487 of file GridCurveRanges.ih.
References begin(), and end().
  {
    ConstIterator it( this->begin() );
    ConstIterator itEnd( this->end() );
    out << "[IncidentPointsRange]" << std::endl;
    out << "\t";
    for ( ; it != itEnd; ++it)
      {
        typename IteratorCirculatorTraits<ConstIterator>::Value pair(*it);
        out << pair.first << pair.second << ", ";
      }
    out << std::endl;
  }
void IncidentPointsRange::selfDraw (Board2D & aBoard) const [inline]
Draw the object on a Board2D board
Parameters:
board the output board where the object is drawn.
Definition at line 1550 of file GridCurveRanges.ih.
References begin(), and end().
  {
    ConstIterator it ( this->begin() );
    ConstIterator itEnd ( this->end() );
    for( ; it != itEnd; ++it)
      {
        typename IteratorCirculatorTraits<ConstIterator>::Value pair(*it);
        aBoard << SetMode( pair.first.className(), "Both" )
               << CustomStyle( pair.first.className(),
                               new CustomFillColor( Color::Blue ) )
               << pair.first
               << CustomStyle( pair.second.className(),
                               new CustomFillColor( Color::Green ) )
               << pair.second;
      }
  }
Storage::size_type IncidentPointsRange::size () const [inline]
Returns:
the size of the range
Definition at line 1471 of file GridCurveRanges.ih.
References myC.
  {
    return myC->my1SCells.size();
  }
Friends And Related Function Documentation
DGtal::DrawableWithBoard2D* defaultStyle (const IncidentPointsRange & ipr) [friend]
Definition at line 1521 of file GridCurveRanges.ih.
  {
    return ipr.defaultStyle();
  }
DGtal::DrawableWithBoard2D* defaultStyle (const IncidentPointsRange & ipr, std::string) [friend]
Definition at line 1534 of file GridCurveRanges.ih.
  {
    return ipr.defaultStyle();
  }
void draw (Board2D & aBoard, const IncidentPointsRange & ipr) [friend]
Definition at line 1566 of file GridCurveRanges.ih.
  {
    ipr.selfDraw(aBoard);
  }
friend class GridCurve< KSpace > [friend]
Definition at line 1419 of file GridCurveRanges.ih.
ostream& operator<< (ostream & out, const IncidentPointsRange & object) [friend]
Overloads 'operator<<' for displaying objects of class 'IncidentPointsRange'.
Parameters:
out the output stream where the object is written.
object the object of class 'IncidentPointsRange' to write.
Returns:
the output stream after the writing.
Definition at line 1507 of file GridCurveRanges.ih.
  {
    object.selfDisplay( out );
    return out;
  }
Field Documentation
const GridCurve* IncidentPointsRange::myC [private]
Private member myC is an aliasing pointer to any grid curve
Definition at line 1576 of file GridCurveRanges.ih.
Referenced by begin(), end(), operator=(), and size().
Functor IncidentPointsRange::myFunctor [private]
Functor transforming a signed cell into a pair of digital points
Definition at line 1580 of file GridCurveRanges.ih.
Referenced by begin(), end(), and operator=().
The documentation for this class was generated from the following file:
GridCurveRanges.ih