DGtal: OuterPointsRange Class Reference
OuterPointsRange Class Reference
Public Types
typedef GridCurve::Storage Storage
typedef Storage::const_iterator ConstIteratorOnSCells
typedef SCellToOuterPoint< KSpace > Functor
typedef ConstIteratorAdapter
< ConstIteratorOnSCells,
Functor, Point > ConstIterator
typedef std::reverse_iterator
< ConstIterator > ConstReverseIterator
typedef Circulator< ConstIterator > ConstCirculator
typedef std::reverse_iterator
< ConstCirculator > ConstReverseCirculator
Public Member Functions
OuterPointsRange (const GridCurve *aGridCurve)
OuterPointsRange (const OuterPointsRange &aOther)
OuterPointsRange & operator= (const OuterPointsRange &other)
~OuterPointsRange ()
Storage::size_type size () const
bool isValid () const
void selfDisplay (std::ostream &out) const
DGtal::DrawableWithBoard2D * defaultStyle () const
DGtal::DrawableWithBoard2D * defaultStyle (std::string) const
std::string className () const
void selfDraw (Board2D &aBoard) const
ConstIterator begin () const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rend () const
ConstCirculator c () const
ConstReverseCirculator rc () const
Private Attributes
const GridCurve * myC
Functor myFunctor
Friends
class GridCurve< KSpace >
ostream & operator<< (ostream &out, const OuterPointsRange &object)
DGtal::DrawableWithBoard2D * defaultStyle (const OuterPointsRange &opr)
DGtal::DrawableWithBoard2D * defaultStyle (const OuterPointsRange &opr, std::string)
void draw (Board2D &aBoard, const OuterPointsRange &opr)
Detailed Description
Aim: model of CConstRange that provides services to (circularly)iterate over the 2-cells (viewed as points of integer coordinates) that are indirectly incident to the signed 1-cells of a 2d grid curve.
(Included in GridCurve.h)
See also:
GridCurve.h exampleGridCurve2d.cpp testGridCurve.cpp
Definition at line 1185 of file GridCurveRanges.ih.
Member Typedef Documentation
typedef Circulator<ConstIterator> OuterPointsRange::ConstCirculator
Definition at line 1201 of file GridCurveRanges.ih.
typedef ConstIteratorAdapter<ConstIteratorOnSCells,Functor,Point> OuterPointsRange::ConstIterator
Definition at line 1198 of file GridCurveRanges.ih.
typedef Storage::const_iterator OuterPointsRange::ConstIteratorOnSCells
Definition at line 1194 of file GridCurveRanges.ih.
typedef std::reverse_iterator<ConstCirculator> OuterPointsRange::ConstReverseCirculator
Definition at line 1202 of file GridCurveRanges.ih.
typedef std::reverse_iterator<ConstIterator> OuterPointsRange::ConstReverseIterator
Definition at line 1199 of file GridCurveRanges.ih.
typedef SCellToOuterPoint<KSpace> OuterPointsRange::Functor
Definition at line 1196 of file GridCurveRanges.ih.
typedef GridCurve::Storage OuterPointsRange::Storage
Definition at line 1193 of file GridCurveRanges.ih.
Constructor & Destructor Documentation
OuterPointsRange::OuterPointsRange (const GridCurve * aGridCurve) [inline]
Constructor.
Parameters:
aGridCurve a grid curve.
Definition at line 1210 of file GridCurveRanges.ih.
: myC(aGridCurve), myFunctor(Functor(myC->myK)){}
OuterPointsRange::OuterPointsRange (const OuterPointsRange & aOther) [inline]
Copy constructor.
Parameters:
other the iterator to clone.
Definition at line 1216 of file GridCurveRanges.ih.
    : myC( aOther.myC ), myFunctor( aOther.myFunctor ){}
OuterPointsRange::~OuterPointsRange () [inline]
Destructor. Does nothing.
Definition at line 1237 of file GridCurveRanges.ih.
{}
Member Function Documentation
ConstIterator OuterPointsRange::begin () const [inline]
Iterator service.
Returns:
begin iterator
Definition at line 1350 of file GridCurveRanges.ih.
References myC, and myFunctor.
Referenced by c(), rend(), selfDisplay(), and selfDraw().
{
    return ConstIterator( myC->my1SCells.begin(), myFunctor );
  }
ConstCirculator OuterPointsRange::c () const [inline]
Circulator service.
Returns:
a circulator
Definition at line 1382 of file GridCurveRanges.ih.
References begin(), and end().
Referenced by rc().
{
    return ConstCirculator( this->begin(), this->begin(), this->end() );
  }
std::string OuterPointsRange::className () const [inline]
Returns:
the style name used for drawing this object.
Definition at line 1306 of file GridCurveRanges.ih.
  {
    return "OuterPointsRange";
  }
DGtal::DrawableWithBoard2D* OuterPointsRange::defaultStyle () const [inline]
Default drawing style object.
Returns:
the dyn. alloc. default style for this object.
Definition at line 1282 of file GridCurveRanges.ih.
  {
    return new DrawableWithBoard2D;
  }
DGtal::DrawableWithBoard2D* OuterPointsRange::defaultStyle (std::string) const [inline]
Default drawing style object.
Parameters:
mode the drawing mode
Returns:
the dyn. alloc. default style for this object.
Definition at line 1295 of file GridCurveRanges.ih.
  {
    return new DrawableWithBoard2D;
  }
ConstIterator OuterPointsRange::end () const [inline]
Iterator service.
Returns:
end iterator
Definition at line 1358 of file GridCurveRanges.ih.
References myC, and myFunctor.
Referenced by c(), rbegin(), selfDisplay(), and selfDraw().
{
    return ConstIterator( myC->my1SCells.end(), myFunctor );
  }
bool OuterPointsRange::isValid () const [inline]
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
Definition at line 1251 of file GridCurveRanges.ih.
{ return true; }
OuterPointsRange& OuterPointsRange::operator= (const OuterPointsRange & other) [inline]
Assignment.
Parameters:
other the iterator to copy.
Returns:
a reference on 'this'.
Definition at line 1224 of file GridCurveRanges.ih.
References myC, and myFunctor.
  {
    if ( this != &other )
      {
        myC = other.myC;
        myFunctor = other.myFunctor;
      }
    return *this;
  }
ConstReverseIterator OuterPointsRange::rbegin () const [inline]
Iterator service.
Returns:
rbegin iterator
Definition at line 1366 of file GridCurveRanges.ih.
References end().
{
    return ConstReverseIterator(this->end());
  }
ConstReverseCirculator OuterPointsRange::rc () const [inline]
Circulator service.
Returns:
a reverse circulator
Definition at line 1390 of file GridCurveRanges.ih.
References c().
{
    return ConstReverseCirculator( this->c() );
  }
ConstReverseIterator OuterPointsRange::rend () const [inline]
Iterator service.
Returns:
rend iterator
Definition at line 1374 of file GridCurveRanges.ih.
References begin().
{
    return ConstReverseIterator(this->begin());
  }
void OuterPointsRange::selfDisplay (std::ostream & out) const [inline]
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
Definition at line 1258 of file GridCurveRanges.ih.
References begin(), and end().
  {
    typedef typename IteratorCirculatorTraits<ConstIterator>::Value Value;
    out << "[OuterPointsRange]" << std::endl;
    out << "\t";
    std::copy( this->begin(), this->end(), ostream_iterator<Value>(out, ", ") );
    out << std::endl;
  }
void OuterPointsRange::selfDraw (Board2D & aBoard) const [inline]
Draw the object on a Board2D board
Parameters:
board the output board where the object is drawn.
Definition at line 1315 of file GridCurveRanges.ih.
References begin(), and end().
  {
    ConstIterator it ( this->begin() );
    ConstIterator itEnd ( this->end() );
    for( ; it != itEnd; ++it)
      {
        aBoard << SetMode( it->className(), "Both" )
               << CustomStyle( it->className(),
                               new CustomFillColor( Color::Green ) )
               << *it;
      }
  }
Storage::size_type OuterPointsRange::size () const [inline]
Returns:
the size of the range
Definition at line 1242 of file GridCurveRanges.ih.
References myC.
  {
    return myC->my1SCells.size();
  }
Friends And Related Function Documentation
DGtal::DrawableWithBoard2D* defaultStyle (const OuterPointsRange & opr) [friend]
Definition at line 1286 of file GridCurveRanges.ih.
  {
    return opr.defaultStyle();
  }
DGtal::DrawableWithBoard2D* defaultStyle (const OuterPointsRange & opr, std::string) [friend]
Definition at line 1299 of file GridCurveRanges.ih.
  {
    return opr.defaultStyle();
  }
void draw (Board2D & aBoard, const OuterPointsRange & opr) [friend]
Definition at line 1327 of file GridCurveRanges.ih.
  {
    opr.selfDraw(aBoard);
  }
friend class GridCurve< KSpace > [friend]
Definition at line 1191 of file GridCurveRanges.ih.
ostream& operator<< (ostream & out, const OuterPointsRange & object) [friend]
Overloads 'operator<<' for displaying objects of class 'OuterPointsRange'.
Parameters:
out the output stream where the object is written.
object the object of class 'OuterPointsRange' to write.
Returns:
the output stream after the writing.
Definition at line 1272 of file GridCurveRanges.ih.
  {
    object.selfDisplay( out );
    return out;
  }
Field Documentation
const GridCurve* OuterPointsRange::myC [private]
Private member myC is an aliasing pointer to any grid curve
Definition at line 1337 of file GridCurveRanges.ih.
Referenced by begin(), end(), operator=(), and size().
Functor OuterPointsRange::myFunctor [private]
Functor transforming a signed cell into a digital point
Definition at line 1341 of file GridCurveRanges.ih.
Referenced by begin(), end(), and operator=().
The documentation for this class was generated from the following file:
GridCurveRanges.ih