DGtal: DGtal::DistanceTransformation< Image, p, IntegerLong > Class Template Reference
DGtal::DistanceTransformation< Image, p, IntegerLong > Class Template Reference
#include <DistanceTransformation.h>
Public Types
typedef
ImageContainerBySTLVector
< HyperRectDomain< typename
Image::Domain::Space >
, IntegerLong > OutputImage
typedef Image::Value Value
typedef Image::Vector Vector
typedef Image::Point Point
typedef Image::Dimension Dimension
typedef Image::Size Size
typedef Image::Domain Domain
typedef
Image::Domain::Space::Point::Coordinate Abscissa
typedef SeparableMetricHelper
< Abscissa, IntegerLong, p > SeparableMetric
Public Member Functions
BOOST_CONCEPT_ASSERT ((CSignedInteger< IntegerLong >))
DistanceTransformation ()
~DistanceTransformation ()
bool checkTypesValidity (const Image &aImage)
template<typename ForegroundPredicate >
OutputImage compute (const Image &inputImage, const ForegroundPredicate &predicate)
OutputImage compute (const Image &inputImage)
template<typename DigitalSet >
OutputImage compute (const DigitalSet &inputSet, const bool addBoundary=true)
template<typename Functor >
DGtal::DistanceTransformation
< I, p, IntLong >::OutputImage compute (const I &aImage, const Functor &predicate)
template<typename Functor >
void computeFirstStep (OutputImage &output, const Functor &predicate) const
Private Member Functions
template<typename ForegroundPredicate >
void computeFirstStep (OutputImage &output, const ForegroundPredicate &predicate) const
template<typename ForegroundPredicate >
void computeFirstStep1D (OutputImage &output, const Point &startingPoint, const ForegroundPredicate &predicate) const
void computeOtherSteps (const OutputImage &inputImage, OutputImage &output, const Dimension dim) const
void computeOtherStep1D (const OutputImage &input, OutputImage &output, const Point &row, const Size dim, Abscissa s[], Abscissa t[]) const
Private Attributes
SeparableMetric myMetric
Point myLowerBoundCopy
Point myUpperBoundCopy
Vector myDisplacementVector
Point myExtent
IntegerLong myInfinity
Detailed Description
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t>
class DGtal::DistanceTransformation< Image, p, IntegerLong >
Aim: Implementation of the linear in time distance transformation.
Description of template class 'DistanceTransformation'
Template Parameters:
Image an input image type.
p the static integer value to define the l_p metric.
IntegerLong (optional) type used to represent exact distance value according to p (default: DGtal::uint64_t)
Example:
 //Types definition
 typedef ImageSelector<Domain, unsigned int>::Type Image; //image with "unsigned in value type
 //Distance transformation for the l_2 metric
 typedef DistanceTransformation<Image, 2> DTl2;
 DTl2 dt;
 // ...
 //Construction of an instance "image" of Image (with an io reader for instance)
 // ...
 //EDT computation
 DTl2::OutputImage result = dt.compute(image);
Definition at line 94 of file DistanceTransformation.h.
Member Typedef Documentation
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> typedef Image::Domain::Space::Point::Coordinate DGtal::DistanceTransformation< Image, p, IntegerLong >::Abscissa
Definition at line 112 of file DistanceTransformation.h.
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> typedef Image::Dimension DGtal::DistanceTransformation< Image, p, IntegerLong >::Dimension
Definition at line 109 of file DistanceTransformation.h.
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> typedef Image::Domain DGtal::DistanceTransformation< Image, p, IntegerLong >::Domain
Definition at line 111 of file DistanceTransformation.h.
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> typedef ImageContainerBySTLVector< HyperRectDomain<typename Image::Domain::Space> , IntegerLong > DGtal::DistanceTransformation< Image, p, IntegerLong >::OutputImage
Type of resulting image.
Definition at line 104 of file DistanceTransformation.h.
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> typedef Image::Point DGtal::DistanceTransformation< Image, p, IntegerLong >::Point
Definition at line 108 of file DistanceTransformation.h.
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> typedef SeparableMetricHelper< Abscissa , IntegerLong , p > DGtal::DistanceTransformation< Image, p, IntegerLong >::SeparableMetric
We construct the type associated to the separable metric.
Definition at line 115 of file DistanceTransformation.h.
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> typedef Image::Size DGtal::DistanceTransformation< Image, p, IntegerLong >::Size
Definition at line 110 of file DistanceTransformation.h.
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> typedef Image::Value DGtal::DistanceTransformation< Image, p, IntegerLong >::Value
Definition at line 106 of file DistanceTransformation.h.
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> typedef Image::Vector DGtal::DistanceTransformation< Image, p, IntegerLong >::Vector
Definition at line 107 of file DistanceTransformation.h.
Constructor & Destructor Documentation
template<typename I , DGtal::uint32_t p, typename IntLong > DGtal::DistanceTransformation< I, p, IntLong >::DistanceTransformation () [inline]
Default Constructor
Constructor.
Definition at line 47 of file DistanceTransformation.ih.
{
}
template<typename I , DGtal::uint32_t p, typename IntLong > DGtal::DistanceTransformation< I, p, IntLong >::~DistanceTransformation () [inline]
Default destructor
Destructor.
Definition at line 56 of file DistanceTransformation.ih.
{
}
Member Function Documentation
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> DGtal::DistanceTransformation< Image, p, IntegerLong >::BOOST_CONCEPT_ASSERT ((CSignedInteger< IntegerLong >))
template<typename I, DGtal::uint32_t p, typename IntLong > bool DGtal::DistanceTransformation< I, p, IntLong >::checkTypesValidity (const I & aImage) [inline]
Check the validity of the transformation. For instance, we check that the output image pixel range is ok with respect to the input image range and the SeparableMetric.
Warning and advices are printed in the trace system.
Parameters:
aImage the image used to check the type consistency.
Returns:
true if a warning has been raised.
Definition at line 66 of file DistanceTransformation.ih.
References DGtal::trace, and DGtal::Trace::warning().
{
  typename I::Point::UnsignedComponent maxExtent = ( aImage.domain().upperBound() -
                                                     aImage.domain().lowerBound() ).normInfinity();
  //Estimate worst-case bit size (special case for p=0 == Linfinity
  double bitSize;
  if (SeparableMetric::p != 0)
    bitSize = SeparableMetric::p * (log ((double) I::dimension * 2 * maxExtent ) / log(2.0));
  else
    bitSize =  sizeof ( typename I::Value ) * 8;
  if ( bitSize > sizeof ( typename OutputImage::Value ) * 8 )
    {
      trace.warning() << "(DistanceTransformation) The output image Value range may"
                      <<" not be sufficient to store the exact values  according to"
                      <<" the input image extent." << endl;
      return false;
    }
  return true;
}
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> template<typename Functor > DGtal::DistanceTransformation<I, p, IntLong>::OutputImage DGtal::DistanceTransformation< Image, p, IntegerLong >::compute (const I & aImage, const Functor & predicate) [inline]
Definition at line 107 of file DistanceTransformation.ih.
References DGtal::ImageContainerBySTLVector< TDomain, TValue >::translateDomain().
{
  //We trace type validdity check result;
  checkTypesValidity ( aImage );
  //We copy the image extent and translate the image domains to (0,..0)x(Upper-Lower)
  myLowerBoundCopy = Point(); //(O,O,...O)
  myUpperBoundCopy = aImage.domain().upperBound() - aImage.domain().lowerBound();
  myDisplacementVector = aImage.domain().lowerBound();
  myExtent = myUpperBoundCopy - myLowerBoundCopy;
  myInfinity  = myMetric.power(static_cast<typename I::Integer>(I::dimension) *
                               myExtent.normInfinity() + 1);
  OutputImage output ( typename I::Domain(myLowerBoundCopy, myUpperBoundCopy ));
  OutputImage swap ( typename I::Domain(myLowerBoundCopy, myUpperBoundCopy ));
  bool isSwap = true;
  //First step
  computeFirstStep ( output, predicate );
  //We process the dimensions swaping the temporary buffers
  for ( Dimension dim = 1; dim < I::dimension ; dim++ )
    {
      if ( isSwap )
        computeOtherSteps ( output, swap, dim );
      else
        computeOtherSteps ( swap, output, dim );
      isSwap = !isSwap;
    }
  //We translate the output image to the correct position and return.
  if ( !isSwap )
    {
      swap.translateDomain(myDisplacementVector);
      return swap;
    }
  else
    {
      output.translateDomain(myDisplacementVector);
      return output;
    }
}
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> template<typename ForegroundPredicate > OutputImage DGtal::DistanceTransformation< Image, p, IntegerLong >::compute (const Image & inputImage, const ForegroundPredicate & predicate)
Compute the Distance Transformation of an image with the SeparableMetric metric. The method associates to each point with value satisfying the foreground predicate, its distance to the closest background point. This algorithm is O(d.|inputImage|).
Precondition:
the foregroundPredicate must have been constructed from a reference to inputImage.
Parameters:
inputImage the input image
foregroundPredicate a predicate to detect foreground point from the image valuetype
Returns:
the distance transformation image with the Internal format.
Referenced by DGtal::DistanceTransformation< Image, p, IntegerLong >::compute().
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> OutputImage DGtal::DistanceTransformation< Image, p, IntegerLong >::compute (const Image & inputImage) [inline]
Compute the Distance Transformation of an image with the SeparableMetric metric. The method associates to each point with value satisfying the foreground predicate (by default, values greater than 0), its distance to the closest background point. This algorithm is O(d.|inputImage|).
Parameters:
inputImage the input image
Returns:
the distance transformation image with the Internal format.
Definition at line 170 of file DistanceTransformation.h.
References DGtal::DistanceTransformation< Image, p, IntegerLong >::compute().
    {
      typedef Thresholder<typename Image::Value,false,false> Binarizer;
      Binarizer b(0);
      PointFunctorPredicate<Image,Binarizer> predicate(inputImage, b);
      return compute(inputImage, predicate);
    };
template<typename I, DGtal::uint32_t p, typename IntLong > template<typename DigitalSet > DGtal::DistanceTransformation< I, p, IntLong >::OutputImage DGtal::DistanceTransformation< I, p, IntLong >::compute (const DigitalSet & inputSet, const bool addBoundary = true) [inline]
Compute the Distance Transformation of a Set with the SeparableMetric metric. This method first converts the digital set of an image and compute the DT in O(d.N) where N is the number of grid points of the bounding box of the set (and d the dimension). The bounding box is enlarged by 1 point in each direction if the addBoundary parameter is true (default value).
Parameters:
inputSet the input set of grid points.
addBoundary if true (default value), we add a boundary of thickness one to the bounding box (to make sure that all grid points of aSet belonging to the boundary have a DT of value 1 (for the L2 and L1 case).
Returns:
the distance transformation image with the Internal format.
Definition at line 93 of file DistanceTransformation.ih.
References DGtal::Trace::info(), and DGtal::trace.
{
  //We convert the set to an image and run the image-based algorithm
  I image = ImageFromSet<I>::template create<DigitalSet>(aSet, 128, addBoundary);
  trace.info() <<"Temp image="<<image<<std::endl;
  return compute( image  );
}
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> template<typename Functor > void DGtal::DistanceTransformation< Image, p, IntegerLong >::computeFirstStep (OutputImage & output, const Functor & predicate) const [inline]
Definition at line 161 of file DistanceTransformation.ih.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), and DGtal::trace.
{
  trace.beginBlock ( "DT dimension 0" );
  Point startingPoint = myLowerBoundCopy;
  typedef typename Domain::ConstSubRange::ConstIterator ConstDomIt;
  //We setup the subdomain iterator
  //the iterator will scan dimension using the order:
  // {n-1, n-2, ... 1} (we skip the '0' dimension.
  std::vector<Size> subdomain;
  subdomain.reserve(I::dimension - 1);
  for (Dimension k = I::dimension-1; k>0 ; --k)
    subdomain.push_back( k );
  Domain localDomain(myLowerBoundCopy, myUpperBoundCopy);
  //We process the dimensions to construct a Point
  for (ConstDomIt it = localDomain.subRange( subdomain ).begin(),
         itend = localDomain.subRange( subdomain ).end(); it != itend; ++it)
    {
      // trace.info()  << "Processing 1D slice starting at =" << (*it) << endl;
      computeFirstStep1D (output, (*it), predicate );
    }
  trace.endBlock();
}
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> template<typename ForegroundPredicate > void DGtal::DistanceTransformation< Image, p, IntegerLong >::computeFirstStep (OutputImage & output, const ForegroundPredicate & predicate) const [private]
Compute the first step of the separable distance transformation.
Parameters:
output the output image with the first step DT values
predicate the predicate to characterize the foreground (e.g. !=0, see DefaultForegroundPredicate)
template<typename I , DGtal::uint32_t p, typename IntLong > template<typename ForegroundPredicate > void DGtal::DistanceTransformation< I, p, IntLong >::computeFirstStep1D (OutputImage & output, const Point & startingPoint, const ForegroundPredicate & predicate) const [private]
Compute the 1D DT associated to the first step.
Parameters:
output the output image with the first step DT values
startingPoint a point to specify the starting point of the 1D row
predicate the predicate to characterize the foreground (e.g. !=0, see DefaultForegroundPredicate)
Definition at line 242 of file DistanceTransformation.ih.
References DGtal::ImageContainerBySTLVector< TDomain, TValue >::setValue().
{
  Point prec = startingPoint;
  Point point = startingPoint;
  //PRECOND : output can store 2*(myUpperBoundCopy[0] -  myLowerBoundCopy[0]) in its valuetype
  //INFTY = something > myUpperBoundCopy[0] -  myLowerBoundCopy[0]
  if ( isForeground ( point + myDisplacementVector ) )
    output.setValue ( point, myInfinity );
  else
    output.setValue ( point, 0 );
  //Forward scan
  for ( point[0] = 1; point[0] <= myUpperBoundCopy[0]; point[0]++ )
    {
      // trace.warning() << point << " ";
      if ( isForeground ( point  + myDisplacementVector ))
        output.setValue ( point, 1 + output ( prec ) );
      else
        output.setValue ( point, 0 );
      prec[0] = point[0];
    }
  //prec is the the rightmost point of "point'
  prec[0] =  myUpperBoundCopy[0];
  //Backward scan
  for ( point[0] = myUpperBoundCopy[0] - 1; point[0] >= 0 ; point[0]-- )
    {
      if ( output ( prec ) < output ( point ) )
        output.setValue ( point, 1 + output ( prec ) );
      prec[0] = point[0];
    }
  //final computation
  for ( point[0] = 0; point[0] <= myUpperBoundCopy[0]; point[0]++ )
    if (output( point ) < myInfinity)
      output.setValue ( point, myMetric.power( (const int)output ( point ) ));
    else
      output.setValue ( point, myInfinity);
}
template<typename I , DGtal::uint32_t p, typename IntLong > void DGtal::DistanceTransformation< I, p, IntLong >::computeOtherStep1D (const OutputImage & input, OutputImage & output, const Point & row, const Size dim, Abscissa s[], Abscissa t[]) const [private]
Compute the 1D DT associated to the steps except the first one.
Parameters:
aImage the input image
output the output image with the DT values
row a point to specify the starting point of the 1D row
dim the dimension to process
predicate the predicate to characterize the foreground (e.g. !=0, see DefaultForegroundPredicate)
Todo:
optimize the test here
Definition at line 293 of file DistanceTransformation.ih.
References DGtal::ImageContainerBySTLVector< TDomain, TValue >::setValue(), DGtal::ImageContainerBySTLVector< TDomain, TValue >::spanBegin(), and DGtal::ImageContainerBySTLVector< TDomain, TValue >::spanEnd().
{
  Abscissa w;
  Abscissa q = 0;  //index for the stack "head"
  Point sQ = startingPoint;
  Point pU = startingPoint;
  // We look for the first point in the 1D column with distance different from
  // myInfinity
  pU[dim] = myLowerBoundCopy[dim];
  while ((pU[dim] <= myUpperBoundCopy[dim]) && (input ( pU ) == myInfinity))
    pU[dim] ++;
  // All points are set to +infinity, we just copy the infinity value and return
  if ( pU[dim] > myUpperBoundCopy[dim] )
    {
      for(typename OutputImage::SpanIterator it= output.spanBegin(startingPoint,dim),
            itend=output.spanEnd(startingPoint,dim);
          it != itend; ++it)
        output.setValue(it, myInfinity);
      return;
    }
  //Stack structure
  q = 0;
  s[q] = pU[dim]; // first point with DT!=infinity
  sQ[dim] = s[q]; // nD Point corresponding to the head of the stack
  t[q] = myLowerBoundCopy[dim];
  //Forward Scan
  //We scan all the pixels
  for ( Abscissa u = pU[dim] + 1; u <= myUpperBoundCopy[dim] ; u++ )
    {
      pU[ dim ] = u;
      if ( input( pU ) == myInfinity )
        {
          continue;
        }
      while ( ( q >= 0 ) &&
              ( myMetric.F ( t[q], s[q], input ( sQ ) ) >
                myMetric.F ( t[q], u, input ( pU ) ) ) )
        {
          q--;
          if (q>=0)
            sQ[dim] = s[q];
        }
      if ( q < 0 )
        {
          q = 0;
          s[0] = u;
          sQ[dim] = u;
          t[0] = myLowerBoundCopy[dim];
        }
      else
        {
          sQ[dim] = s[q];
          w = 1 + myMetric.Sep ( s[q],
                                 input ( sQ ),
                                 u,
                                 input ( pU ) );
          if (( w <= myUpperBoundCopy[dim] )
              && (w>= myLowerBoundCopy[dim]))
            {
              q++;
              s[q] = u;
              sQ[dim] = u;
              t[q] = w;
            }
        }
    }
  Point last = startingPoint;
  ASSERT(q>=0);
  sQ[dim] = s[q];
  //Backward Scan
  for (last[dim] = myUpperBoundCopy[dim];
       last[dim] >= myLowerBoundCopy[dim] ;
       last[dim]-- )
    {
      output.setValue ( last, myMetric.F ( last[dim] , s[q], input ( sQ ) ) );
      if (( last[dim] == t[q] ) && (q > 0))
        {
          q--;
          sQ[dim] = s[q];
        }
    }
}
template<typename I , DGtal::uint32_t p, typename IntLong > void DGtal::DistanceTransformation< I, p, IntLong >::computeOtherSteps (const OutputImage & inputImage, OutputImage & output, const Dimension dim) const [inline, private]
Compute the other steps of the separable distance transformation.
Parameters:
inputImage the image resulting of the first (or intermediate) step
output the output image
dim the dimension to process
Definition at line 194 of file DistanceTransformation.ih.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), and DGtal::trace.
{
  std::string title = "DT dimension " +  boost::lexical_cast<string>( dim ) ;
  trace.beginBlock ( title );
  typedef typename Domain::ConstSubRange::ConstIterator ConstDomIt;
  //We setup the subdomain iterator
  //the iterator will scan dimension using the order:
  // {n-1, n-2, ... 1} (we skip the '0' dimension.
  std::vector<Size> subdomain;
  subdomain.reserve(I::dimension - 1);
  for (unsigned int k = 0; k < I::dimension ; k++)
    if ( (I::dimension - 1 - k) != dim)
      subdomain.push_back( I::dimension - 1 - k );
  Domain localDomain(myLowerBoundCopy, myUpperBoundCopy);
  Size maxSize = myExtent.normInfinity();
  //Stacks used in the envelope computation
  Abscissa *s = new Abscissa[maxSize+1];
  Abscissa *t = new Abscissa[maxSize+1];
  ASSERT( s != NULL);
  ASSERT( t != NULL);
  //We process the dimensions to construct a Point
  for (ConstDomIt it = localDomain.subRange( subdomain ).begin(),
         itend = localDomain.subRange( subdomain ).end();
       it != itend; ++it)
    {
      computeOtherStep1D ( input, output, (*it), dim, s, t );
    }
  delete[] s;
  delete[] t;
  trace.endBlock();
}
Field Documentation
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> Vector DGtal::DistanceTransformation< Image, p, IntegerLong >::myDisplacementVector [private]
Displacement vector to translate temporary images.
Definition at line 266 of file DistanceTransformation.h.
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> Point DGtal::DistanceTransformation< Image, p, IntegerLong >::myExtent [private]
Copy of the image extent.
Definition at line 269 of file DistanceTransformation.h.
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> IntegerLong DGtal::DistanceTransformation< Image, p, IntegerLong >::myInfinity [private]
Value to act as a +infinity value.
Definition at line 272 of file DistanceTransformation.h.
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> Point DGtal::DistanceTransformation< Image, p, IntegerLong >::myLowerBoundCopy [private]
Copy of the image lower bound.
Definition at line 260 of file DistanceTransformation.h.
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> SeparableMetric DGtal::DistanceTransformation< Image, p, IntegerLong >::myMetric [private]
The separable metric instance.
Definition at line 257 of file DistanceTransformation.h.
template<typename Image, DGtal::uint32_t p, typename IntegerLong = DGtal::int64_t> Point DGtal::DistanceTransformation< Image, p, IntegerLong >::myUpperBoundCopy [private]
Copy of the image lower bound.
Definition at line 263 of file DistanceTransformation.h.
The documentation for this class was generated from the following files:
DistanceTransformation.h
DistanceTransformation.ih