DGtal: DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType > Class Template Reference
DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType > Class Template Reference
#include <IteratorAdapter.h>
Public Types
typedef IteratorAdapter
< TIterator, TFunctor,
TReturnType > Self
typedef TIterator Iterator
typedef TFunctor Functor
typedef TReturnType value_type
typedef value_type * pointer
typedef value_type & reference
typedef iterator_traits
< TIterator >::difference_type difference_type
typedef iterator_traits
< TIterator >
::iterator_category iterator_category
Public Member Functions
IteratorAdapter ()
IteratorAdapter (const Iterator &it, const Functor &f)
IteratorAdapter (const IteratorAdapter &other)
IteratorAdapter & operator= (const IteratorAdapter &other)
~IteratorAdapter ()
Iterator base () const
bool isValid () const
const reference operator* () const
pointer operator-> () const
reference operator* ()
pointer operator-> ()
Self & operator++ ()
Self operator++ (int)
Self & operator-- ()
Self operator-- (int)
Self & operator+= (difference_type d)
Self operator+ (difference_type d) const
Self operator- (difference_type d) const
Self & operator-= (difference_type d)
difference_type operator- (const Self &other) const
reference operator[] (difference_type d) const
bool operator== (const Self &other) const
bool operator!= (const Self &other) const
bool operator< (const Self &other) const
bool operator<= (const Self &other) const
bool operator> (const Self &other) const
bool operator>= (const Self &other) const
Protected Attributes
Iterator myCurrentIt
FunctorPtr myFunctorPtr
Private Types
typedef
IteratorCirculatorTraits
< TIterator >::Value TArgument
typedef const Functor * FunctorPtr
Private Member Functions
BOOST_CONCEPT_ASSERT ((boost::ForwardIterator< TIterator >))
Detailed Description
template<typename TIterator, typename TFunctor, typename TReturnType>
class DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >
This class adapts any iterator (at least forward) so that operator* returns a member on the element pointed to by the iterator, instead the element itself.
Description of template class 'IteratorAdapter'
Template Parameters:
TIterator the type of the iterator to adapt (at least forward)
To achieve this goal, the adapter is based on a functor f given at construction so that operator* calls f(<em>it), instead of calling directly operator of the underlying iterator it. This operation returns a reference (or constant reference) on a member of the element pointed to by the iterator, which can be read as well as assigned (if the member is not constant).
Template Parameters:
TFunctor the type of functor that transforms the pointed element into another one
TReturnType the type of the element returned by the underlying functor
NB: the underlying functor is stored in the adapter as aliasing pointer in order to avoid copies. As a consequence the pointed object must exist and must not be deleted during the use of the adapter.
Definition at line 81 of file IteratorAdapter.h.
Member Typedef Documentation
template<typename TIterator, typename TFunctor, typename TReturnType> typedef iterator_traits<TIterator>::difference_type DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::difference_type
Definition at line 97 of file IteratorAdapter.h.
template<typename TIterator, typename TFunctor, typename TReturnType> typedef TFunctor DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::Functor
Definition at line 92 of file IteratorAdapter.h.
template<typename TIterator, typename TFunctor, typename TReturnType> typedef const Functor* DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::FunctorPtr [private]
Definition at line 102 of file IteratorAdapter.h.
template<typename TIterator, typename TFunctor, typename TReturnType> typedef TIterator DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::Iterator
Definition at line 91 of file IteratorAdapter.h.
template<typename TIterator, typename TFunctor, typename TReturnType> typedef iterator_traits<TIterator>::iterator_category DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::iterator_category
Definition at line 98 of file IteratorAdapter.h.
template<typename TIterator, typename TFunctor, typename TReturnType> typedef value_type* DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::pointer
Definition at line 95 of file IteratorAdapter.h.
template<typename TIterator, typename TFunctor, typename TReturnType> typedef value_type& DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::reference
Definition at line 96 of file IteratorAdapter.h.
template<typename TIterator, typename TFunctor, typename TReturnType> typedef IteratorAdapter<TIterator, TFunctor, TReturnType> DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::Self
Definition at line 90 of file IteratorAdapter.h.
template<typename TIterator, typename TFunctor, typename TReturnType> typedef IteratorCirculatorTraits<TIterator>::Value DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::TArgument [private]
Definition at line 85 of file IteratorAdapter.h.
template<typename TIterator, typename TFunctor, typename TReturnType> typedef TReturnType DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::value_type
Definition at line 94 of file IteratorAdapter.h.
Constructor & Destructor Documentation
template<typename TIterator, typename TFunctor, typename TReturnType> DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::IteratorAdapter () [inline]
The default constructor default-initializes the members
Definition at line 123 of file IteratorAdapter.h.
      : myCurrentIt(), myFunctorPtr() { }
template<typename TIterator, typename TFunctor, typename TReturnType> DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::IteratorAdapter (const Iterator & it, const Functor & f) [inline]
Constructor.
Parameters:
it an iterator to adapt
f the functor that transforms the pointed element into another element
Definition at line 132 of file IteratorAdapter.h.
      : myCurrentIt(it), myFunctorPtr(&f) { }
template<typename TIterator, typename TFunctor, typename TReturnType> DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::IteratorAdapter (const IteratorAdapter< TIterator, TFunctor, TReturnType > & other) [inline]
Copy constructor.
Parameters:
other an iterator adapter
Definition at line 139 of file IteratorAdapter.h.
      : myCurrentIt(other.myCurrentIt),
        myFunctorPtr(other.myFunctorPtr) { }
template<typename TIterator, typename TFunctor, typename TReturnType> DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::~IteratorAdapter () [inline]
Destructor.
Definition at line 161 of file IteratorAdapter.h.
{}
Member Function Documentation
template<typename TIterator, typename TFunctor, typename TReturnType> Iterator DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::base () const [inline]
Returns:
member myCurrentIt, the underlying iterator.
Definition at line 169 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::myCurrentIt.
    { return myCurrentIt; }
template<typename TIterator, typename TFunctor, typename TReturnType> DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::BOOST_CONCEPT_ASSERT ((boost::ForwardIterator< TIterator >)) [private]
Referenced by DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator*().
template<typename TIterator, typename TFunctor, typename TReturnType> bool DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::isValid () const [inline]
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
Definition at line 177 of file IteratorAdapter.h.
{ return true;}
template<typename TIterator, typename TFunctor, typename TReturnType> bool DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator!= (const Self & other) const [inline]
difference_type operator
Definition at line 288 of file IteratorAdapter.h.
    {
      return !(*this == other);
    }
template<typename TIterator, typename TFunctor, typename TReturnType> const reference DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator* () const [inline]
Returns:
constant reference on a member of the element pointed to by myCurrentIt.
Definition at line 182 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::BOOST_CONCEPT_ASSERT(), and DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::myFunctorPtr.
Referenced by DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator->().
    {
      BOOST_CONCEPT_ASSERT(( CUnaryFunctor<TFunctor, const TArgument&, const TReturnType& > ));
      return myFunctorPtr->operator()(*myCurrentIt);
    }
template<typename TIterator, typename TFunctor, typename TReturnType> reference DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator* () [inline]
Returns:
reference on a member of the element pointed to by myCurrentIt.
Definition at line 199 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::BOOST_CONCEPT_ASSERT(), and DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::myFunctorPtr.
    {
      BOOST_CONCEPT_ASSERT(( CUnaryFunctor<TFunctor, TArgument&, TReturnType& > ));
      return myFunctorPtr->operator()(*myCurrentIt);
    }
template<typename TIterator, typename TFunctor, typename TReturnType> Self DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator+ (difference_type d) const [inline]
Definition at line 259 of file IteratorAdapter.h.
{
      Self tmp = *this;
      return tmp += d;
    }
template<typename TIterator, typename TFunctor, typename TReturnType> Self& DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator++ () [inline]
Pre-increment
Definition at line 216 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::myCurrentIt.
Referenced by DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator++().
    {
      ++myCurrentIt;
      return *this;
    }
template<typename TIterator, typename TFunctor, typename TReturnType> Self DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator++ (int) [inline]
Post-increment
Definition at line 225 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator++().
    {
      Self tmp = *this;
      operator++();
      return tmp;
    }
template<typename TIterator, typename TFunctor, typename TReturnType> Self& DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator+= (difference_type d) [inline]
Definition at line 255 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::myCurrentIt.
Referenced by DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator-=().
{
      myCurrentIt += d;
      return *this;
    }
template<typename TIterator, typename TFunctor, typename TReturnType> Self DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator- (difference_type d) const [inline]
Definition at line 263 of file IteratorAdapter.h.
{
      Self tmp = *this;
      return tmp += -d;
    }
template<typename TIterator, typename TFunctor, typename TReturnType> difference_type DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator- (const Self & other) const [inline]
Definition at line 269 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::myCurrentIt.
{
      return myCurrentIt - other.myCurrentIt;
    }
template<typename TIterator, typename TFunctor, typename TReturnType> Self& DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator-- () [inline]
Pre-decrement
Definition at line 236 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::myCurrentIt.
Referenced by DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator--().
    {
      --myCurrentIt;
      return *this;
    }
template<typename TIterator, typename TFunctor, typename TReturnType> Self DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator-- (int) [inline]
Post-decrement
Definition at line 245 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator--().
    {
      Self tmp = *this;
      operator--();
      return tmp;
    }
template<typename TIterator, typename TFunctor, typename TReturnType> Self& DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator-= (difference_type d) [inline]
Definition at line 267 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator+=().
{ return operator+=(-d); }
template<typename TIterator, typename TFunctor, typename TReturnType> pointer DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator-> () const [inline]
Returns:
constant pointer on a member of the element pointed to by myCurrentIt.
Definition at line 191 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator*().
    {
      return & this->operator*();
    }
template<typename TIterator, typename TFunctor, typename TReturnType> pointer DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator-> () [inline]
Returns:
pointer on a member of the element pointed to by myCurrentIt.
Definition at line 208 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator*().
    {
      return & this->operator*();
    }
template<typename TIterator, typename TFunctor, typename TReturnType> bool DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator< (const Self & other) const [inline]
Less operator
Definition at line 297 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::myCurrentIt.
    {
      return (myCurrentIt < other.myCurrentIt);
    }
template<typename TIterator, typename TFunctor, typename TReturnType> bool DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator<= (const Self & other) const [inline]
Less or equal operator
Definition at line 304 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::myCurrentIt.
    {
      return (myCurrentIt <= other.myCurrentIt);
    }
template<typename TIterator, typename TFunctor, typename TReturnType> IteratorAdapter& DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator= (const IteratorAdapter< TIterator, TFunctor, TReturnType > & other) [inline]
Assignment.
Parameters:
other the object to copy.
Returns:
a reference on 'this'.
Definition at line 148 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::myCurrentIt, and DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::myFunctorPtr.
    {
      if ( this != &other )
        {
          myCurrentIt = other.myCurrentIt;
          myFunctorPtr = other.myFunctorPtr;
        }
      return *this;
    }
template<typename TIterator, typename TFunctor, typename TReturnType> bool DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator== (const Self & other) const [inline]
Equality operator
Definition at line 281 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::myCurrentIt.
    {
      return (myCurrentIt == other.myCurrentIt);
    }
template<typename TIterator, typename TFunctor, typename TReturnType> bool DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator> (const Self & other) const [inline]
Greater
Definition at line 311 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::myCurrentIt.
    {
      return (myCurrentIt > other.myCurrentIt);
    }
template<typename TIterator, typename TFunctor, typename TReturnType> bool DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator>= (const Self & other) const [inline]
Greater or equal operator
Definition at line 318 of file IteratorAdapter.h.
References DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::myCurrentIt.
    {
      return (myCurrentIt >= other.myCurrentIt);
    }
template<typename TIterator, typename TFunctor, typename TReturnType> reference DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator[] (difference_type d) const [inline]
Definition at line 272 of file IteratorAdapter.h.
{
      Self tmp = *this;
      tmp += d;
      return *tmp;
    }
Field Documentation
template<typename TIterator, typename TFunctor, typename TReturnType> Iterator DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::myCurrentIt [protected]
Underlying iterator
Definition at line 109 of file IteratorAdapter.h.
Referenced by DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::base(), DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator++(), DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator+=(), DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator-(), DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator--(), DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator<(), DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator<=(), DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator=(), DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator==(), DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator>(), and DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator>=().
template<typename TIterator, typename TFunctor, typename TReturnType> FunctorPtr DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::myFunctorPtr [protected]
Aliasing pointer on a (constant) functor
Definition at line 113 of file IteratorAdapter.h.
Referenced by DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator*(), and DGtal::IteratorAdapter< TIterator, TFunctor, TReturnType >::operator=().
The documentation for this class was generated from the following file:
IteratorAdapter.h