DGtal: DGtal::PNMWriter< TImage, TColormap > Struct Template Reference
DGtal::PNMWriter< TImage, TColormap > Struct Template Reference
#include <PNMWriter.h>
Public Types
typedef TImage Image
typedef TImage::Value Value
typedef TColormap Colormap
Public Member Functions
BOOST_CONCEPT_ASSERT ((CColorMap< TColormap >))
BOOST_STATIC_ASSERT ((TImage::Domain::dimension==2)||(TImage::Domain::dimension==3))
BOOST_STATIC_ASSERT ((boost::is_same< typename TColormap::Value, typename TImage::Value >::value))
Static Public Member Functions
static bool exportPPM (const std::string &filename, const Image &aImage, const Value &minV, const Value &maxV, bool topbotomOrder=true)
static bool exportPPM3D (const std::string &filename, const Image &aImage, const Value &minV, const Value &maxV)
static bool exportPGM (const std::string &filename, const Image &aImage, const Value &minV, const Value &maxV, bool saveASCII=false, bool topbotomOrder=true)
static bool exportPGM3D (const std::string &filename, const Image &aImage, const Value &minV, const Value &maxV)
Detailed Description
template<typename TImage, typename TColormap>
struct DGtal::PNMWriter< TImage, TColormap >
Aim: Export a 2D and a 3D Image using the Netpbm formats (ASCII mode).
Description of template struct 'PNMWriter'
PPM: RGB
PGM: grayscale
PPM3D: 3D variant of PPM
PGM3D: 3D variant of PGM
Usage example:
 ...
 typedef SpaceND<int,2> TSpace;
 typedef TSpace::Point Point;
 typedef HyperRectDomain<TSpace> Domain;
 typedef HueShadeColorMap<unsigned char> Hue;
 typedef ImageSelector<Domain, unsigned char>::Type Image;
 ...
 Point a ( 1, 1);
 Point b ( 16, 16);
 Image image(a,b);
 ... //Do something in image
 PNMWriter<Image,Hue>::exportPPM("export-hue.ppm",image,0,255);
Template Parameters:
TImage the Image type.
TColormap the type of the colormap to use in the export.
Todo:
check if a magick number exists for PGM3D/PPM3D.
See also:
testPNMRawWriter.cpp
Definition at line 89 of file PNMWriter.h.
Member Typedef Documentation
template<typename TImage , typename TColormap > typedef TColormap DGtal::PNMWriter< TImage, TColormap >::Colormap
Definition at line 103 of file PNMWriter.h.
template<typename TImage , typename TColormap > typedef TImage DGtal::PNMWriter< TImage, TColormap >::Image
Definition at line 101 of file PNMWriter.h.
template<typename TImage , typename TColormap > typedef TImage::Value DGtal::PNMWriter< TImage, TColormap >::Value
Definition at line 102 of file PNMWriter.h.
Member Function Documentation
template<typename TImage , typename TColormap > DGtal::PNMWriter< TImage, TColormap >::BOOST_CONCEPT_ASSERT ((CColorMap< TColormap >))
template<typename TImage , typename TColormap > DGtal::PNMWriter< TImage, TColormap >::BOOST_STATIC_ASSERT ((TImage::Domain::dimension==2)||(TImage::Domain::dimension==3))
template<typename TImage , typename TColormap > DGtal::PNMWriter< TImage, TColormap >::BOOST_STATIC_ASSERT ((boost::is_same< typename TColormap::Value, typename TImage::Value >::value))
template<typename TImage , typename TColormap > bool DGtal::PNMWriter< I, C >::exportPGM (const std::string & filename, const Image & aImage, const Value & minV, const Value & maxV, bool saveASCII = false, bool topbotomOrder = true) [static]
Export an Image with PGM format. The colormap specified in the template arguments is used to convert Value to RBG colors. Then, a RGB to Grayscale conversion is performed.
Parameters:
filename name of the output file
aImage the image to export
minV the minimum value of aImage (for colormap)
maxV the maximum value of aImage (for colormap)
saveASCII used to save image with ASCII pixel value and with white space. (default= false since ASCII mode is not efficient).
Returns:
true if no errors occur.
Todo:
the Value of I should match with the one in C
Todo:
catch IOerror excpetion
Definition at line 104 of file PNMWriter.ih.
References DGtal::Color::blue(), DGtal::Color::green(), and DGtal::Color::red().
{
  BOOST_STATIC_ASSERT(I::Domain::dimension == 2);
  ofstream out;
  typename I::Domain::Vector ext = aImage.extent();
  typename I::Domain domain = aImage.domain();
  typename I::Value val;
  C colormap(minV,maxV);
  Color col;
  out.open(filename.c_str());
  //PPM format
  if(saveASCII){
    out << "P2"<<endl;
  }else{
    out << "P5"<<endl;
  }
  out << "#DGtal PNM Writer"<<endl<<endl;
  out << ext[0]<<" "<< ext[1]<<endl;
  out << "255" <<endl;
  if(!topbotomOrder){
    //We scan the domain instead of the image becaus we cannot
    //trust the image container Iterator
    for(typename I::Domain::ConstIterator it = domain.begin(), itend=domain.end();
        it!=itend;
        ++it)
      {
        val = aImage( (*it) );
        col = colormap( val );
        if(saveASCII){
          out << ((int) (col.red()+(int)col.green()+(int)col.blue()) / 3)<<" ";
        }else{
          out << ((char)((int) (col.red()+(int)col.green()+(int)col.blue()) / 3));
        }
      }
  }else{
    typename I::Domain::Point ptUpper=  domain.upperBound();
    for(typename HyperRectDomain<typename I::Domain::Space>::ConstSubRange::ConstReverseIterator itY = domain.subRange(1, ptUpper).rbegin(), itYend=domain.subRange(1, ptUpper).rend();  itY!=itYend; ++itY)
      {
        typename I::Domain::Point ptUpperY=  *itY;
        for(typename HyperRectDomain<typename I::Domain::Space>::ConstSubRange::ConstIterator it = domain.subRange(0, ptUpperY).begin(), itend=domain.subRange(0, ptUpperY).end();
            it!=itend;
            ++it)
          {
            val = aImage( (*it) );
            col = colormap( val );
            if(saveASCII){
              out << ((int) (col.red()+(int)col.green()+(int)col.blue()) / 3)<<" ";
            }else{
              out << ((char)((int) (col.red()+(int)col.green()+(int)col.blue()) / 3));
            }
          }
      }
  }
  out.close();
  return true;
}
template<typename TImage , typename TColormap > bool DGtal::PNMWriter< I, C >::exportPGM3D (const std::string & filename, const Image & aImage, const Value & minV, const Value & maxV) [static]
Export an Image with PGM3D format. The colormap specified in the template arguments is used to convert Value to RBG colors. Then, a RGB to Grayscale conversion is performed.
Parameters:
filename name of the output file
aImage the image to export
minV the minimum value of aImage (for colormap)
maxV the maximum value of aImage (for colormap)
Returns:
true if no errors occur.
Todo:
the Value of I should match with the one in C
Todo:
catch IOerror excpetion
Definition at line 220 of file PNMWriter.ih.
References DGtal::Color::blue(), DGtal::Color::green(), and DGtal::Color::red().
{
  BOOST_STATIC_ASSERT(I::Domain::dimension == 3);
  ofstream out;
  typename I::Domain::Vector ext = aImage.extent();
  typename I::Domain domain(aImage.lowerBound(), aImage.upperBound());
  typename I::Value val;
  C colormap(minV,maxV);
  Color col;
  out.open(filename.c_str());
  //PPM format
  out << "P2-3D"<<endl;
  out << "#DGtal PNM Writer"<<endl<<endl;
  out << ext[0]<<" "<< ext[1]<<" "<< ext[2]<<endl;
  out << "255" <<endl;
  //We scan the domain instead of the image becaus we cannot
  //trust the image container Iterator
  for(typename I::Domain::ConstIterator it = domain.begin(), itend=domain.end();
      it!=itend;
      ++it)
    {
      val = aImage( (*it) );
      col = colormap( val );
      out << ((int) (col.red()+(int)col.green()+(int)col.blue()) / 3)<<" ";
    }
  out.close();
  return true;
}
template<typename TImage , typename TColormap > bool DGtal::PNMWriter< I, C >::exportPPM (const std::string & filename, const Image & aImage, const Value & minV, const Value & maxV, bool topbotomOrder = true) [static]
Export an Image with PPM format. The colormap specified in the template arguments is used to convert Value to RBG colors.
Parameters:
filename name of the output file
aImage the image to export
minV the minimum value of aImage (for colormap)
maxV the maximum value of aImage (for colormap)
Returns:
true if no errors occur.
Todo:
the Value of I should match with the one in C
Todo:
catch IOerror excpetion
Definition at line 44 of file PNMWriter.ih.
References DGtal::Color::blue(), DGtal::Color::green(), and DGtal::Color::red().
{
  BOOST_STATIC_ASSERT(I::Domain::dimension == 2);
  ofstream out;
  typename I::Domain::Vector ext = aImage.extent();
  typename I::Domain domain = aImage.domain();
  typename I::Value val;
  C colormap(minV,maxV);
  Color col;
  out.open(filename.c_str());
  //PPM format
  out << "P3"<<endl;
  out << "#DGtal PNM Writer"<<endl<<endl;
  out << ext[0]<<" "<< ext[1]<<endl;
  out << "255" <<endl;
 if(!topbotomOrder){
   //We scan the domain instead of the image becaus we cannot
   //trust the image container Iterator
   for(typename I::Domain::ConstIterator it = domain.begin(), itend=domain.end();
       it!=itend;
       ++it)
     {
       val = aImage( (*it) );
       col = colormap( val );
       out << (int)col.red()<<" "<<(int)col.green()<<" "<<(int)col.blue()<<" ";
     }
 }else{
     typename I::Domain::Point ptUpper=  domain.upperBound();
    for(typename HyperRectDomain<typename I::Domain::Space>::ConstSubRange::ConstReverseIterator itY = domain.subRange(1, ptUpper).rbegin(), itYend=domain.subRange(1, ptUpper).rend();  itY!=itYend; ++itY)
      {
        typename I::Domain::Point ptUpperY=  *itY;
        for(typename HyperRectDomain<typename I::Domain::Space>::ConstSubRange::ConstIterator it = domain.subRange(0, ptUpperY).begin(), itend=domain.subRange(0, ptUpperY).end();
            it!=itend;
            ++it)
          {
             val = aImage( (*it) );
             col = colormap( val );
             out << (int)col.red()<<" "<<(int)col.green()<<" "<<(int)col.blue()<<" ";
          }
      }
 }
  out.close();
  return true;
}
template<typename TImage , typename TColormap > bool DGtal::PNMWriter< I, C >::exportPPM3D (const std::string & filename, const Image & aImage, const Value & minV, const Value & maxV) [static]
Export an Image with PPM3Dformat. The colormap specified in the template arguments is used to convert Value to RBG colors.
Parameters:
filename name of the output file
aImage the image to export
minV the minimum value of aImage (for colormap)
maxV the maximum value of aImage (for colormap)
Returns:
true if no errors occur.
Todo:
the Value of I should match with the one in C
Todo:
catch IOerror excpetion
Definition at line 178 of file PNMWriter.ih.
References DGtal::Color::blue(), DGtal::Color::green(), and DGtal::Color::red().
{
  BOOST_STATIC_ASSERT(I::Domain::dimension == 3);
  ofstream out;
  typename I::Domain::Vector ext = aImage.extent();
  typename I::Domain domain(aImage.lowerBound(), aImage.upperBound());
  typename I::Value val;
  C colormap(minV,maxV);
  Color col;
  out.open(filename.c_str());
  //PPM format
  out << "P3-3D"<<endl;
  out << "#DGtal PNM Writer"<<endl<<endl;
  out << ext[0]<<" "<< ext[1]<<" "<< ext[2] <<endl;
  out << "255" <<endl;
  //We scan the domain instead of the image becaus we cannot
  //trust the image container Iterator
  for(typename I::Domain::ConstIterator it = domain.begin(), itend=domain.end();
      it!=itend;
      ++it)
    {
      val = aImage( (*it) );
      col = colormap( val );
      out << (int)col.red()<<" "<<(int)col.green()<<" "<<(int)col.blue()<<" ";
    }
  out.close();
  return true;
}
The documentation for this struct was generated from the following files:
PNMWriter.h
PNMWriter.ih