DGtal: DGtal::RawWriter< TImage, TColormap > Struct Template Reference
DGtal::RawWriter< TImage, TColormap > Struct Template Reference
#include <RawWriter.h>
Public Types
typedef TImage Image
typedef TImage::Value Value
typedef TColormap Colormap
Public Member Functions
BOOST_CONCEPT_ASSERT ((CColorMap< TColormap >))
BOOST_STATIC_ASSERT ((boost::is_same< typename TColormap::Value, typename TImage::Value >::value))
Static Public Member Functions
static bool exportRaw8 (const std::string &filename, const Image &aImage, const Value &minV, const Value &maxV)
Detailed Description
template<typename TImage, typename TColormap>
struct DGtal::RawWriter< TImage, TColormap >
Aim: Raw binary export of an Image.
Description of template struct 'RawWriter'
Template Parameters:
TImage the Image type.
TColormap the type of the colormap to use in the export.
Definition at line 64 of file RawWriter.h.
Member Typedef Documentation
template<typename TImage , typename TColormap > typedef TColormap DGtal::RawWriter< TImage, TColormap >::Colormap
Definition at line 75 of file RawWriter.h.
template<typename TImage , typename TColormap > typedef TImage DGtal::RawWriter< TImage, TColormap >::Image
Definition at line 73 of file RawWriter.h.
template<typename TImage , typename TColormap > typedef TImage::Value DGtal::RawWriter< TImage, TColormap >::Value
Definition at line 74 of file RawWriter.h.
Member Function Documentation
template<typename TImage , typename TColormap > DGtal::RawWriter< TImage, TColormap >::BOOST_CONCEPT_ASSERT ((CColorMap< TColormap >))
template<typename TImage , typename TColormap > DGtal::RawWriter< TImage, TColormap >::BOOST_STATIC_ASSERT ((boost::is_same< typename TColormap::Value, typename TImage::Value >::value))
template<typename TImage , typename TColormap > bool DGtal::RawWriter< I, C >::exportRaw8 (const std::string & filename, const Image & aImage, const Value & minV, const Value & maxV) [static]
Export an Image to Raw format (8bits). The pipeline can be sketched as follows: Value --<colormap>--> Board::Color ----> unsigned char.
Parameters:
filename name of the output file
aImage the image to export
minV the minimum value of aImage (for colormap)
maxV the maximum value of aImage (for colormap)
Returns:
true if no errors occur.
Todo:
the Value of I should match with the one in C
Todo:
catch IOerror excpetion
Definition at line 44 of file RawWriter.ih.
References DGtal::Color::blue(), DGtal::Color::green(), and DGtal::Color::red().
{
  ofstream out;
  typename I::Domain::Vector ext = aImage.extent();
  typename I::Domain domain = aImage.domain();
  typename I::Value val;
  C colormap(minV,maxV);
  Color col;
  out.open(filename.c_str(), ios_base::binary);
  //We scan the domain
  for(typename I::Domain::ConstIterator it = domain.begin(), itend=domain.end();
      it!=itend;
      ++it)
    {
      val = aImage( (*it) );
      col = colormap( val );
      out.put((unsigned char) (((int)col.red()+(int)col.green() + (int)col.blue())/3));
    }
  out.close();
  return true;
}
The documentation for this struct was generated from the following files:
RawWriter.h
RawWriter.ih