DGtal: MyDrawStyleCustomRed Struct Reference
MyDrawStyleCustomRed Struct Reference
Public Member Functions
virtual void setStyle (Board2D &aboard) const
virtual void setStyle (Board2D &aboard) const
Detailed Description
Definition at line 513 of file testObject.cpp.
Member Function Documentation
virtual void MyDrawStyleCustomRed::setStyle (Board2D &) const [inline, virtual]
Operation to override. Does nothing by default.
Parameters:
board any object of type Board.
Reimplemented from DGtal::DrawableWithBoard2D.
Definition at line 76 of file testObjectBorder.cpp.
References LibBoard::Board::setFillColorRGBi(), LibBoard::Board::setLineStyle(), LibBoard::Board::setLineWidth(), and LibBoard::Board::setPenColorRGBi().
    {
        aboard.setFillColorRGBi ( 169, 150, 150 );
        aboard.setPenColorRGBi ( 0, 0, 0 );
        aboard.setLineStyle ( Board2D::Shape::SolidStyle );
        aboard.setLineWidth ( 1.5 );
    }
virtual void MyDrawStyleCustomRed::setStyle (Board2D &) const [inline, virtual]
Operation to override. Does nothing by default.
Parameters:
board any object of type Board.
Reimplemented from DGtal::DrawableWithBoard2D.
Definition at line 515 of file testObject.cpp.
References LibBoard::Board::setFillColor(), LibBoard::Board::setLineStyle(), LibBoard::Board::setLineWidth(), LibBoard::Board::setPenColorRGBi(), and LibBoard::Shape::SolidStyle.
  {
    aboard.setFillColor( Color::Red);
    aboard.setPenColorRGBi(200,0,0);
    aboard.setLineStyle(LibBoard::Shape::SolidStyle);
    aboard.setLineWidth( 2 );
  }
The documentation for this struct was generated from the following files:
testObject.cpp
testObjectBorder.cpp