---
title: "General statistics"
layout: post
---

Here is a collection of entry level statistics and research resources. As the education environment changes with the development of computational advances there are now many many on-line learning tools. Until recently, I have been a big advocate for DataCamp. However, since the recent [sexual harrassment](https://medium.com/@heathernolis/on-datacamp-aafd82f94e60/) violations I personally have no desire to advocate for DataCamp. I have therefore removed my class subscription to the DataCamp website which means that the current students will not have access to the paid content.

## Courses and Tutorials


During the time between then and now, I found many other subscription based learning sites like DataCamp:

- [LinkedIn Learning](https://www.linkedin.com/learning/)

- [Udemy](https://www.udemy.com/)

- [Khan Academy](https://www.khanacademy.org/)

- [Coursa](https://www.coursera.org/)

- [Codecademy](https://www.codecademy.com/)

- [EdX](https://www.edx.org/)

#### Online databases

- [Class central](https://www.classcentral.com/): A database of on-line courses

- [Australian open universities database](https://www.open.edu.au/online-courses/)

- [Even SEEK](https://www.seek.com.au/learning/search/courses/mode-online/)

## Open-source

I also found many more open-source tutorials, vignettes and courses tucked away in the depths of github and Google so I have build a simple webpage with a collection of open-sources tools covering the same or similar content that we covered in the DataCamp classes. To build this, send through the analysis or statistical methods you use and I will see what I can do if it is not below.

#### [Data Carpentry](https://datacarpentry.org/)

This is an open source community that teaches R and other data tools. They also run workshops and classes at many Australian Universities. IN there words

"Data Carpentry develops and teaches workshops on the fundamental data skills needed to conduct research. Our mission is to provide researchers high-quality, domain-specific training covering the full life cycle of data-driven research."

#### [Data Science (DS)](https://www.rfordatasci.com/)

These resources are very helpful but take a slightly different approach to ecological studies however the pay is much better as a "data scientist" [DS](https://www.rfordatasci.com/) in the current job market. 

The DS community is great and even have there own [slack channel](). I still haven't found a great resource for this but here are a few general videos to start here; [basic](https://www.youtube.com/watch?v=poQ61RZKzwE) overview but has a boring intro *or*  [microsoft](https://www.youtube.com/watch?v=gNV9EqwXCpw) video here but its pretty dry.

#### More specific resources

- [Ecological statistics]()

- Health (coming)

- Hierarchical modelling (coming)

- Bayesian modelling (coming)

- [Invasive species modelling]()
  - Mostly just my PhD work at the moment