PREFECTURES = {
    '北海道': 'Hokkaido',
    '青森県': 'Aomori',
    '岩手県': 'Iwate',
    '宮城県': 'Miyagi',
    '秋田県': 'Akita',
    '山形県': 'Yamagata',
    '福島県': 'Fukushima',
    '茨城県': 'Ibaraki',
    '栃木県': 'Tochigi',
    '群馬県': 'Gunma',
    '埼玉県': 'Saitama',
    '千葉県': 'Chiba',
    '東京都': 'Tokyo',
    '神奈川県': 'Kanagawa',
    '新潟県': 'Niigata',
    '富山県': 'Toyama',
    '石川県': 'Ishikawa',
    '福井県': 'Fukui',
    '山梨県': 'Yamanashi',
    '長野県': 'Nagano',
    '岐阜県': 'Gifu',
    '静岡県': 'Shizuoka',
    '愛知県': 'Aichi',
    '三重県': 'Mie',
    '滋賀県': 'Shiga',
    '京都府': 'Kyoto',
    '大阪府': 'Osaka',
    '兵庫県': 'Hyogo',
    '奈良県': 'Nara',
    '和歌山県': 'Wakayama',
    '鳥取県': 'Tottori',
    '島根県': 'Shimane',
    '岡山県': 'Okayama',
    '広島県': 'Hiroshima',
    '山口県': 'Yamaguchi',
    '徳島県': 'Tokushima',
    '香川県': 'Kagawa',
    '愛媛県': 'Ehime',
    '高知県': 'Kochi',
    '福岡県': 'Fukuoka',
    '佐賀県': 'Saga',
    '長崎県': 'Nagasaki',
    '熊本県': 'Kumamoto',
    '大分県': 'Oita',
    '宮崎県': 'Miyazaki',
    '鹿児島県': 'Kagoshima',
    '沖縄県': 'Okinawa',
}

TOKYO_CITIES = {
    '千代田区': 'Chiyoda',
    '中央区': 'Chuo',
    '港区': 'Minato',
    '新宿区': 'Shinjuku',
    '文京区': 'Bunkyo',
    '台東区': 'Taito',
    '墨田区': 'Sumida',
    '江東区': 'Koto',
    '品川区': 'Shinagawa',
    '目黒区': 'Meguro',
    '大田区': 'Ota',
    '世田谷区': 'Setagaya',
    '渋谷区': 'Shibuya',
    '中野区': 'Nakano',
    '杉並区': 'Suginami',
    '豊島区': 'Toshima',
    '北区': 'Kita',
    '荒川区': 'Arakawa',
    '板橋区': 'Itabashi',
    '練馬区': 'Nerima',
    '足立区': 'Adachi',
    '葛飾区': 'Katsushika',
    '江戸川区': 'Edogawa',
    '八王子市': 'Hachioji',
    '立川市': 'Tachikawa',
    '武蔵野市': 'Musashino',
    '三鷹市': 'Mitaka',
    '青梅市': 'Ome',
    '府中市': 'Fuchu',
    '昭島市': 'Akishima',
    '調布市': 'Chofu',
    '町田市': 'Machida',
    '小金井市': 'Koganei',
    '小平市': 'Kodaira',
    '日野市': 'Hino',
    '東村山市': 'Higashimurayama',
    '国分寺市': 'Kokubunji',
    '国立市': 'Kunitachi',
    '福生市': 'Fussa',
    '狛江市': 'Komae',
    '東大和市': 'Higashiyamato',
    '清瀬市': 'Kiyose',
    '東久留米市': 'Higashikurume',
    '武蔵村山市': 'Musashimurayama',
    '多摩市': 'Tama',
    '稲城市': 'Inagi',
    '羽村市': 'Hamura',
    'あきる野市': 'Akiruno',
    '西東京市': 'Nishitokyo',
    '瑞穂町': 'Thị trấn Mizuho',
    '日の出町': 'Thị trấn Hinode',
    '檜原村': 'Làng Hinohara',
    '奥多摩町': 'Thị trấn Okutama',
    '大島町': 'Đảo Oshima',
    '利島村': 'Đảo Toshima',
    '新島村': 'Đảo Niijima',
    '神津島村': 'Đảo Kozushima',
    '三宅村': 'Đảo Miyake',
    '御蔵島村': 'Đảo Mikurajima',
    '八丈町': 'Đảo Hachijo',
    '青ヶ島村': 'Đảo Aogashima',
    '小笠原村': 'Đảo Ogasawara',
}

OSAKA_CITIES = {
    '大阪市': 'Thành phố Osaka',
    '枚方市': 'Hirakata',
    '守口市': 'Moriguchi',
    '箕面市': 'Mino',
    '東大阪': 'Higashiosaka',
    '東大阪市': 'Higashiosaka',
    '吹田市': 'Suita',
    '松原市': 'Matsubara',
    '大東市': 'Daito',
    '堺市': 'Sakai',
    '高槻市': 'Takatsuki',
    '摂津市': 'Settsu',
    '茨木市': 'Ibaraki',
    '門真市': 'Kadoma',
    '豊中市': 'Toyonaka',
    '八尾市': 'Yao',
    '貝塚市': 'Kaizuka',
    '池田市': 'Ikeda',
    '和泉市': 'Izumi',
    '泉佐野市': 'Izumisano',
    '岸和田': 'Kishiwada',
    '岸和田市': 'Kishiwada',
    '泉大津市': 'Izumiotsu',
    '羽曳野市': 'Habikino',
    '河内長野市': 'Kawachinagano',
    '田尻町': 'Thị trấn Tajiri',
    '寝屋川市': 'Thị trấn Neyagawa',
    '藤井寺市': 'Fujidera',
    '交野市': 'Kano',
    '熊取町': 'Thị trấn Kumatori',
    '柏原市': 'Kashiwara',
    '四條畷市': 'Shijonawate',
    '高石市': 'Takaishi',
    '能勢町': 'Thị trấn Nose',
    '大阪狭山市': 'Osakasayama',
    '泉南市': 'Sennan',
    '富田林市': 'Tondabayashi',
    '阪南市': 'Hannan',
    '豊能町': 'Thị trấn Toyono',
    '河南町': 'Thị trấn Kanan',
    '羽曳野': 'Habikino',
}

SAITAMA_CITIES = {
    '川口市': 'Kawaguchi',
    '川越市': 'Kawagoe',
    '八潮市': 'Yashio',
    '朝霞市': 'Asaka',
    '所沢市': 'Tokorozawa',
    '入間市': 'Iruma',
    '春日部市': 'Kasukabe',
    '和光市': 'Wako',
    '鴻巣市': 'Konosu',
    '蕨市': 'Warabi',
    '戸田市': 'Toda',
    '新座市': 'Niiza',
    '草加市': 'Soka',
    '志木市': 'Shiki',
    '東松山市': 'Higashimatsuyama',
    '本庄市': 'Honjo',
    'さいたま市': 'Thành phố Saitama',
    '越谷市': 'Koshigaya',
    '小川町': 'Thị trấn Ogawa',
    '寄居町': 'Thị trấn Yorii',
    '吉川市': 'Yoshikawa',
    '宮代町': 'Thị trấn Miyashiro',
    '川島町': 'Thị trấn Kawajima',
    '坂戸市': 'Sakado',
    '桶川市': 'Okegawa',
    '狭山市': 'Sayama',
    '日高市': 'Hidaka',
    '美里町': 'Thị trấn Misato',
    '上尾市': 'Ageo',
    '加須市': 'Kazo',
    '幸手市': 'Satte',
    '富士見市': 'Fujimi',
    '鶴ヶ島市': 'Tsurugashima',
    '熊谷市': 'Kumagaya',
    '深谷市': 'Fukaya',
    '飯能市': 'Hanno',
    '三郷市': 'Misato',
    '白岡市': 'Shiraoka',
    '三芳町': 'Thị trấn Miyoshi',
    '蓮田市': 'Hasuda',
    '羽生市': 'Hanyu',
    '吉見町': 'Thị trấn Yoshimi',
    '伊奈町': 'Thị trấn Ina',
    'ふじみ野市': 'Fujimino',
    '久喜市': 'Kuki',
    '毛呂山町': 'Thị trấn Moroyama',
    '杉戸町': 'Thị trấn Sugito',
    '秩父市': 'Chichibu',
    '上里町': 'Thị trấn Kamisato',
    '神川町': 'Thị trấn Kamikawa',
    'ときがわ町': 'Thị trấn Tokigawa',
    '行田市': 'Gyoda',
}

KANAGAWA_CITIES = {
    '相模原市': 'Sagamihara',
    '横浜市': 'Yokohama',
    '鎌倉市': 'Kamakura',
    '厚木市': 'Atsugi',
    '小田原市': 'Odawara',
    '平塚市': 'Hiratsuka',
    '藤沢市': 'Fujisawa',
    '川崎市': 'Kawasaki',
    '茅ヶ崎市': 'Chigasaki',
    '茅ケ崎市': 'Chigasaki',
    '横須賀市': 'Yokosuka',
}

CHIBA_CITIES = {
    '市川市': 'Ichikawa',
    '柏市': 'Kashiwa',
    '松戸市': 'Matsudo',
    'いすみ市': 'Isumi',
    '四街道市': 'Yotsukaido',
    '船橋市': 'Funabashi',
    '匝瑳市': 'Sosa',
    '印西市': 'Inzai',
    '浦安市': 'Urayasu',
    '木更津市': 'Kisarazu',
    '我孫子市': 'Abiko',
    '成田市': 'Narita',
    '流山市': 'Nagareyama',
    '習志野市': 'Narashino',
    '香取市': 'Katori',
    '山武市': 'Sammu',
    '佐倉市': 'Sakura',
    '東庄町': 'Thị trấn Tonosho',
    '旭市': 'Asahi',
    '八街市': 'Yachimata',
    '茂原市': 'Mobara',
    '酒々井町': 'Thị trấn Shisui',
    '一宮町': 'Thị trấn Ichinomiya',
    '南房総市': 'Minamiboso',
    '白井市': 'Shiroi',
    '八千代市': 'Yachiyo',
    '野田市': 'Noda',
    '富里市': 'Tomisato',
    '市原市': 'Ichihara',
    '東金市': 'Togane',
    '銚子市': 'Choshi',
    '鎌ケ谷市': 'Kamagaya',
    '袖ケ浦市': 'Sodegaura',
    '横芝光町': 'Thị trấn Yokoshibahikari',
    '芝山町': 'Thị trấn Shibayama',
    '勝浦市': 'Katsuura',
    '君津市': 'Kimitsu',
}
