DGtal: DGtal::CConstSinglePassRange< T > Struct Template Reference
DGtal::CConstSinglePassRange< T > Struct Template Reference
DGtal Concepts
#include <base/CConstSinglePassRange.h>
Public Types
typedef T::ConstIterator ConstIterator
Public Member Functions
BOOST_CONCEPT_ASSERT ((boost_concepts::SinglePassIteratorConcept< ConstIterator >))
BOOST_CONCEPT_USAGE (CConstSinglePassRange)
void checkConstConstraints () const
Private Attributes
T i
ConstIterator it
Detailed Description
template<typename T>
struct DGtal::CConstSinglePassRange< T >
Aim: Defines the concept describing a const single pass range.
Description of concept 'CConstSinglePassRange'
Template Parameters
T the type that should be a model of CConstSinglePassRange.
Refinement of
Associated types :
ConstIterator: the const iterator type, a model of const iterator concept (see boost_concepts::SinglePassIteratorConcept).
Notation
T : A type that is a model of CConstSinglePassRange
x : object of type T
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
begin of range x.begin() ConstIterator returns a forward iterator on the beginning of the range
end of range x.end() ConstIterator returns a forward iterator after the end of the range
Invariants
Valid range. For any Range x, [x.begin(), x.end()) is a valid range, that is, x.end() is reachable from x.begin() in a finite number of increments.
Completeness. An algorithm that iterates through the range [x.begin(), x.end()) will pass through every element of x.
Models
Definition at line 90 of file CConstSinglePassRange.h.
Member Typedef Documentation
template<typename T > typedef T::ConstIterator DGtal::CConstSinglePassRange< T >::ConstIterator
Definition at line 94 of file CConstSinglePassRange.h.
Member Function Documentation
template<typename T > DGtal::CConstSinglePassRange< T >::BOOST_CONCEPT_ASSERT ((boost_concepts::SinglePassIteratorConcept< ConstIterator >))
template<typename T > DGtal::CConstSinglePassRange< T >::BOOST_CONCEPT_USAGE (CConstSinglePassRange< T >) inline
Definition at line 98 of file CConstSinglePassRange.h.
References DGtal::CConstSinglePassRange< T >::checkConstConstraints().
     {
       checkConstConstraints();
     }
template<typename T > void DGtal::CConstSinglePassRange< T >::checkConstConstraints () const inline
Definition at line 102 of file CConstSinglePassRange.h.
References DGtal::CConstSinglePassRange< T >::i, DGtal::CConstSinglePassRange< T >::it, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::CConstSinglePassRange< T >::BOOST_CONCEPT_USAGE().
     {
       concepts::ConceptUtils::sameType( it, i.begin() );
       concepts::ConceptUtils::sameType( it, i.end() );
     }
Field Documentation
template<typename T > T DGtal::CConstSinglePassRange< T >::i private
Definition at line 109 of file CConstSinglePassRange.h.
Referenced by DGtal::CConstSinglePassRange< T >::checkConstConstraints().
template<typename T > ConstIterator DGtal::CConstSinglePassRange< T >::it private
Definition at line 110 of file CConstSinglePassRange.h.
Referenced by DGtal::CSinglePassRange< T >::BOOST_CONCEPT_USAGE(), and DGtal::CConstSinglePassRange< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CConstSinglePassRange.h