DGtal: DGtal::CStack< T > Struct Template Reference
DGtal::CStack< T > Struct Template Reference
DGtal Concepts
#include <base/CStack.h>
Public Types
typedef T::value_type Value
typedef T::size_type Size
Public Member Functions
BOOST_CONCEPT_USAGE (CStack)
void checkConstConstraints () const
Private Attributes
T myX
Value myV
Size myS
bool myB
Detailed Description
template<typename T>
struct DGtal::CStack< T >
Aim: This concept gathers classes that provide a stack interface.
Description of concept 'CStack'
Refinement of copy constructible and assignable
Inner types :
Value type of element stored in the stack
Size type that represents the number of elements
Notation
X : A type that is a model of CStack
x : object of type X
v : object of type Value
Definitions
Valid expressions and semantics
| Name | Expression | Type requirements | Return type | Precondition | Semantics | Post condition | Complexity | |----—+---------—+----------------—+---------------------—+-----------—+---------------------------------—+-------------—+---------—| | size | x.size() | | Size | | returns the number of elements | | O(1) | | empty | x.empty() | | bool | | 'true' is empty, 'false' otherwise | | O(1) | | top | x.top() | | Value& or const Value& | | returns the top element | | O(1) | | push | x.push(v) | | void | | inserts a new element at the top | | O(1) | | pop | x.pop() | | void | | removes the top element | | O(1) |
Models
std::stack, BackInsertionSequenceToStackAdapter, FrontInsertionSequenceToStackAdapter are the usual models of CStack.
Template Parameters
T the type that should be a model of CStack.
Definition at line 90 of file CStack.h.
Member Typedef Documentation
template<typename T > typedef T::size_type DGtal::CStack< T >::Size
Definition at line 95 of file CStack.h.
template<typename T > typedef T::value_type DGtal::CStack< T >::Value
Definition at line 94 of file CStack.h.
Member Function Documentation
template<typename T > DGtal::CStack< T >::BOOST_CONCEPT_USAGE (CStack< T >) inline
Definition at line 97 of file CStack.h.
References DGtal::CStack< T >::checkConstConstraints(), DGtal::CStack< T >::myV, DGtal::CStack< T >::myX, and DGtal::concepts::ConceptUtils::sameType().
     {
       concepts::ConceptUtils::sameType( myV, myX.top() );
       myX.push( myV );
       myX.pop();
       // check const methods.
       checkConstConstraints();
     }
template<typename T > void DGtal::CStack< T >::checkConstConstraints () const inline
Definition at line 106 of file CStack.h.
References DGtal::CStack< T >::myB, DGtal::CStack< T >::myS, DGtal::CStack< T >::myV, DGtal::CStack< T >::myX, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::CStack< T >::BOOST_CONCEPT_USAGE().
     {
       concepts::ConceptUtils::sameType( myS, myX.size() );
       concepts::ConceptUtils::sameType( myB, myX.empty() );
       concepts::ConceptUtils::sameType( myV, myX.top() );
     }
Field Documentation
template<typename T > bool DGtal::CStack< T >::myB private
Definition at line 117 of file CStack.h.
Referenced by DGtal::CStack< T >::checkConstConstraints().
template<typename T > Size DGtal::CStack< T >::myS private
Definition at line 116 of file CStack.h.
Referenced by DGtal::CStack< T >::checkConstConstraints().
template<typename T > Value DGtal::CStack< T >::myV private
Definition at line 115 of file CStack.h.
Referenced by DGtal::CStack< T >::BOOST_CONCEPT_USAGE(), and DGtal::CStack< T >::checkConstConstraints().
template<typename T > T DGtal::CStack< T >::myX private
Definition at line 114 of file CStack.h.
Referenced by DGtal::CStack< T >::BOOST_CONCEPT_USAGE(), and DGtal::CStack< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CStack.h