DGtalTools: Viewer3DImage< Space, KSpace > Class Template Reference
Viewer3DImage< Space, KSpace > Class Template Reference
#include <visualisation/specificClasses/Viewer3DImage.h>
Public Types
enum ModeVisu { BoundingBox, InterGrid, Grid, Empty }
Public Types inherited from DGtal::Viewer3D< Space, KSpace >
enum RenderingMode
enum ImageDirection
enum TextureMode
typedef Display3D< Space, KSpace > Display
typedef Display::SelectCallbackFct SelectCallbackFct
typedef Display::RealPoint RealPoint
Public Types inherited from DGtal::Display3D< Space, KSpace >
enum StreamKey
typedef Display3D< Space, KSpace > Self
typedef Space::RealPoint RealPoint
typedef Space::RealVector RealVector
typedef CanonicEmbedder< Space > Embedder
typedef CanonicCellEmbedder< KSpace > CellEmbedder
typedef CanonicSCellEmbedder< KSpace > SCellEmbedder
typedef int(* SelectCallbackFct) (void *viewer, DGtal::int32_t name, void *data)
typedef std::map< DGtal::int32_t, std::vector< QuadD3D > > QuadsMap
typedef std::map< DGtal::int32_t, std::vector< CubeD3D > > CubesMap
typedef std::map< std::string, std::string > ModeMapping
typedef std::map< std::string, CountedPtr< DrawableWithDisplay3D > > StyleMapping
Public Member Functions
Viewer3DImage (ModeVisu aMode=BoundingBox)
Viewer3DImage (Image3D *an3DImage)
void setVolImage (Image3D *an3DImage)
Public Member Functions inherited from DGtal::Viewer3D< Space, KSpace >
Viewer3D ()
Viewer3D (const KSpace &KSEmb)
void setCameraPosition (double ax, double ay, double az)
void setCameraDirection (double ax, double ay, double az)
void setCameraUpVector (double ax, double ay, double az)
void setNearFar (double _near, double _far)
void setGLScale (float sx, float sy, float sz)
void setGLDoubleRenderingMode (bool doubleSidedRendering)
void setGLMaterialShininessCoefficient (const GLfloat matShininessCoeff)
void setGLLightAmbientCoefficients (const GLfloat lightAmbientCoeffs[4])
void setGLLightDiffuseCoefficients (const GLfloat lightDiffuseCoeffs[4])
void setGLLightSpecularCoefficients (const GLfloat lightSpecularCoeffs[4])
void setUseGLPointForBalls (bool useOpenGLPt)
void updateRenderingCoefficients (const RenderingMode aRenderMode, bool displayState=true)
Viewer3D< Space, KSpace > & operator<< (const DGtal::Color &aColor)
Viewer3D< Space, KSpace > & operator<< (const typename Viewer3D< Space, KSpace >::StreamKey &key)
void sortSurfelFromCamera ()
void sortTriangleFromCamera ()
void sortQuadFromCamera ()
void sortPolygonFromCamera ()
Viewer3D< Space, KSpace > & operator<< (const TDrawableWithViewer3D &object)
void selfDisplay (std::ostream &out) const
bool isValid () const
virtual unsigned int getCurrentDomainNumber ()
virtual unsigned int getCurrentGLImageNumber ()
virtual void paintGL ()
virtual void show ()
void addTextureImage (const TextureImage &image)
void updateTextureImage (unsigned int imageIndex, const TImageType &image, const TFunctor &aFunctor, double xTranslation=0.0, double yTranslation=0.0, double zTranslation=0.0, double rotationAngle=0.0, ImageDirection rotationDir=zDirection)
void updateOrientationTextureImage (unsigned int imageIndex, double xPosition, double yPosition, double zPosition, ImageDirection newDirection)
void updateEmbeddingTextureImage (unsigned int anImageIndex, typename Space::Point aPoint1, typename Space::Point aPoint2, typename Space::Point aPoint3, typename Space::Point aPoint4)
void addImage2DDomainD3D (const TDomain &anImageDomain, std::string mode, const DGtal::Color &aColor=DGtal::Color::Red)
void updateAn2DDomainOrientation (unsigned int imageIndex, double xPosition, double yPosition, double zPosition, ImageDirection newDirection)
void translateAn2DDomain (unsigned int domainIndex, double xTranslation, double yTranslation, double zTranslation)
std::vector< typename DGtal::Viewer3D< Space, KSpace >::LineD3D > compute2DDomainLineRepresentation (Image2DDomainD3D &anImageDomain, double delta)
std::vector< typename DGtal::Viewer3D< Space, KSpace >::LineD3D > compute2DDomainLineRepresentation (Image2DDomainD3D &anImageDomain)
void rotateLineD3D (typename DGtal::Display3D< Space, KSpace >::LineD3D &aLine, DGtal::PointVector< 3, int > pt, double angleRotation, ImageDirection dirRotation)
void rotateDomain (Image2DDomainD3D &anDom, double angle, ImageDirection rotationDir)
void updateList (bool needToUpdateBoundingBox=true)
void glDrawGLBall (const typename Viewer3D< Space, KSpace >::BallD3D &aBall)
virtual void mouseMoveEvent (QMouseEvent *e)
virtual void mousePressEvent (QMouseEvent *e)
virtual void mouseReleaseEvent (QMouseEvent *e)
virtual void drawWithNames ()
virtual void draw ()
virtual void postSelection (const QPoint &point)
virtual QDomElement domElement (const QString &name, QDomDocument &document) const
virtual void initFromDOMElement (const QDomElement &element)
Public Member Functions inherited from DGtal::Display3D< Space, KSpace >
BOOST_CONCEPT_ASSERT ((concepts::CSpace< Space >))
virtual ~Display3D ()
Display3D (const KSpace &KSEmb)
Display3D ()
Display3D (const Display3D &)=delete
Display3D (Display3D &&)=delete
Display3D & operator= (const Display3D &)=delete
Display3D & operator= (Display3D &&)=delete
const Embedder & embedder () const
const CellEmbedder & cellEmbedder () const
const SCellEmbedder & sCellEmbedder () const
const KSpace & space () const
virtual void setFillColor (DGtal::Color aColor)
virtual void setFillTransparency (unsigned char alpha)
virtual void setLineColor (DGtal::Color aColor)
virtual DGtal::Color getFillColor ()
virtual DGtal::Color getLineColor ()
virtual void setKSpace (const KSpace &aKSpace)
void setName3d (DGtal::int32_t name=-1)
DGtal::int32_t name3d () const
void setSelectCallback3D (SelectCallbackFct fct, void *data, DGtal::int32_t min_name, DGtal::int32_t max_name)
SelectCallbackFct getSelectCallback3D (DGtal::int32_t aName, void *&data) const
void addClippingPlane (double a, double b, double c, double d, bool drawPlane)
std::string getMode (const std::string &objectName) const
void createNewLineList (std::string s="")
void createNewBallList (std::string s="")
DGtal::int32_t createNewCubeList ()
bool deleteCubeList (const DGtal::int32_t name)
DGtal::int32_t createNewQuadList ()
bool deleteQuadList (const DGtal::int32_t name)
void createNewTriangleList (std::string s="")
void createNewPolygonList (std::string s="")
void addQuad (const RealPoint &p1, const RealPoint &p2, const RealPoint &p3, const RealPoint &p4)
void addQuadWithNormal (const RealPoint &p1, const RealPoint &p2, const RealPoint &p3, const RealPoint &p4, const RealPoint &n, const bool enableReorientation, const bool enableDoubleFace=false)
void addQuadFromSurfelCenter (const RealPoint &baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel)
void addQuadFromSurfelCenterWithNormal (const RealPoint &baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel, const RealVector &aNormal, const bool enableReorientation, const bool sign, const bool enableDoubleFace=false)
void addTriangle (const RealPoint &p1, const RealPoint &p2, const RealPoint &p3)
void addPolygon (const std::vector< RealPoint > &vertices)
void addLine (const RealPoint &p1, const RealPoint &p2, const double width=0.03)
void addCube (const RealPoint &center, double width=1.0)
void addBall (const RealPoint &center, const double radius=0.5, const unsigned int resolution=30)
void addPrism (const RealPoint &baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel, double sizeShiftFactor, double sizeFactor=1.0, bool isSigned=false, bool aSign=true)
void addBasicSurfel (const RealPoint &baseQuadCenter, bool xSurfel, bool ySurfel, bool zSurfel)
void addCone (const RealPoint &p1, const RealPoint &p2, double width=0.08)
void addCylinder (const RealPoint &p1, const RealPoint &p2, const double width=0.02)
void updateBoundingBox (const RealPoint &point)
void exportToMesh (Mesh< RealPoint > &aMesh) const
Display3D & operator<< (const TDrawableWithDisplay3D &object)
void selfDisplay (std::ostream &out) const
bool isValid () const
void clear ()
RealPoint embed (const typename Space::Point &dp) const
RealPoint embedKS (const typename KSpace::SCell &cell) const
RealPoint embedKS (const DGtal::TransformedPrism &aTrans) const
RealPoint embedK (const typename KSpace::Cell &cell) const
Protected Member Functions
virtual QString helpString () const
virtual void keyPressEvent (QKeyEvent *e)
virtual void init ()
Protected Member Functions inherited from DGtal::Viewer3D< Space, KSpace >
virtual void closeEvent (QCloseEvent *e)
Protected Attributes
Image3D * my3dImage
float myScaleX
float myScaleY
float myScaleZ
int mySliceXPos
int mySliceYPos
int mySliceZPos
int myCurrentSliceDim
double myAngleRotation
double myTotalAngleRotationX
double myTotalAngleRotationY
double myTotalAngleRotationZ
bool myDisplayingInfo
DGtal::Z3i::Point myImageOrigin
ModeVisu myMode
Protected Attributes inherited from DGtal::Display3D< Space, KSpace >
KSpace myKSpace
Embedder * myEmbedder
CellEmbedder * myCellEmbedder
SCellEmbedder * mySCellEmbedder
DGtal::Color myCurrentFillColor
DGtal::Color myCurrentLineColor
double myCurrentfShiftVisuPrisms
std::vector< std::vector< LineD3D > > myLineSetList
std::vector< std::vector< BallD3D > > myBallSetList
std::vector< ClippingPlaneD3D > myClippingPlaneList
std::vector< QuadD3D > myPrismList
QuadsMap myQuadsMap
std::vector< std::vector< TriangleD3D > > myTriangleSetList
std::vector< std::vector< PolygonD3D > > myPolygonSetList
CubesMap myCubesMap
std::vector< std::string > myCubeSetNameList
std::vector< std::string > myLineSetNameList
std::vector< std::string > myBallSetNameList
std::vector< std::string > myClippingPlaneNameList
std::vector< std::string > myPrismNameList
std::vector< std::string > myQuadSetNameList
std::vector< std::string > myTriangleSetNameList
std::vector< std::string > myPolygonSetNameList
DGtal::int32_t myName3d
std::set< SelectCallbackFctStore > mySelectCallBackFcts
Private Types
typedef DGtal::ImageContainerBySTLVector< DGtal::Z3i::Domain, unsigned char > Image3D
typedef DGtal::ImageContainerBySTLVector< DGtal::Z2i::Domain, unsigned char > Image2D
typedef DGtal::ConstImageAdapter< Image3D, Image2D::Domain, DGtal::functors::Projector< DGtal::Z3i::Space >, Image3D::Value, DGtal::functors::Identity > SliceImageAdapter
typedef DGtal::ConstImageAdapter< Image3D, DGtal::Z2i::Domain, DGtal::functors::SliceRotator2D< DGtal::Z3i::Domain >, Image3D::Value, DGtal::functors::Identity > MyRotatorSliceImageAdapter
Additional Inherited Members
Static Public Member Functions inherited from DGtal::Viewer3D< Space, KSpace >
static void rotateImageVertex (TImageORDomain &anImageOrDom, double angle, ImageDirection rotationDir)
static void rotatePoint (TValues &x, TValues &y, TValues &z, double cx, double cy, double cz, double rotationAngle, ImageDirection rotationDir)
Data Fields inherited from DGtal::Viewer3D< Space, KSpace >
RenderingDefault
RenderingMetallic
RenderingPlastic
RenderingLambertian
xDirection
yDirection
zDirection
undefDirection
RGBMode
GrayScaleMode
DGtal::Color myDefaultBackgroundColor
DGtal::Color myDefaultColor
bool myIsBackgroundDefault
bool myViewWire
double myGLPointMinWidth
double myGLLineMinWidth
bool myAutoSaveState
RenderingMode myRenderingMode
Data Fields inherited from DGtal::Display3D< Space, KSpace >
addNewList
updateDisplay
shiftSurfelVisu
ModeMapping myModes
StyleMapping myStyles
bool myBoundingPtEmptyTag
double myBoundingPtUp [3]
double myBoundingPtLow [3]
Static Protected Member Functions inherited from DGtal::Display3D< Space, KSpace >
static void cross (double dst[3], double srcA[3], double srcB[3])
static void normalize (double vec[3])
Detailed Description
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace>
class Viewer3DImage< Space, KSpace >
Prevents repeated inclusion of headers.
Definition at line 23 of file Viewer3DImage.h.
Member Typedef Documentation
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> typedef DGtal::ImageContainerBySTLVector<DGtal::Z2i::Domain, unsigned char> Viewer3DImage< Space, KSpace >::Image2D private
Definition at line 27 of file Viewer3DImage.h.
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> typedef DGtal::ImageContainerBySTLVector<DGtal::Z3i::Domain, unsigned char> Viewer3DImage< Space, KSpace >::Image3D private
Definition at line 26 of file Viewer3DImage.h.
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> typedef DGtal::ConstImageAdapter<Image3D, DGtal::Z2i::Domain, DGtal::functors::SliceRotator2D< DGtal::Z3i::Domain >, Image3D::Value, DGtal::functors::Identity > Viewer3DImage< Space, KSpace >::MyRotatorSliceImageAdapter private
Definition at line 33 of file Viewer3DImage.h.
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> typedef DGtal::ConstImageAdapter<Image3D, Image2D::Domain, DGtal::functors::Projector< DGtal::Z3i::Space>, Image3D::Value, DGtal::functors::Identity > Viewer3DImage< Space, KSpace >::SliceImageAdapter private
Definition at line 30 of file Viewer3DImage.h.
Member Enumeration Documentation
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> enum Viewer3DImage::ModeVisu
Enumerator
BoundingBox
InterGrid
Grid
Empty
Definition at line 38 of file Viewer3DImage.h.
 { BoundingBox, InterGrid, Grid, Empty};
Constructor & Destructor Documentation
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> Viewer3DImage< Space, KSpace >::Viewer3DImage (ModeVisu aMode = BoundingBox) inline
Definition at line 40 of file Viewer3DImage.h.
References Viewer3DImage< Space, KSpace >::myAngleRotation, Viewer3DImage< Space, KSpace >::myCurrentSliceDim, Viewer3DImage< Space, KSpace >::myDisplayingInfo, Viewer3DImage< Space, KSpace >::myMode, Viewer3DImage< Space, KSpace >::mySliceXPos, Viewer3DImage< Space, KSpace >::mySliceYPos, Viewer3DImage< Space, KSpace >::mySliceZPos, Viewer3DImage< Space, KSpace >::myTotalAngleRotationX, Viewer3DImage< Space, KSpace >::myTotalAngleRotationY, and Viewer3DImage< Space, KSpace >::myTotalAngleRotationZ.
Referenced by Viewer3DImage< Space, KSpace >::Viewer3DImage().
                                             : DGtal::Viewer3D<Space, KSpace>(), myImageOrigin(DGtal::Z3i::Point(0,0,0)){
     mySliceXPos=0;
     mySliceYPos=0;
     mySliceZPos=0;
     myTotalAngleRotationX=0.0;
     myTotalAngleRotationY=0.0;
     myTotalAngleRotationZ=0.0;
     myAngleRotation=0.0;
     myCurrentSliceDim=0;
     myMode=aMode;
     myDisplayingInfo=true;
   }
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> Viewer3DImage< Space, KSpace >::Viewer3DImage (Image3D * an3DImage) inline
Definition at line 54 of file Viewer3DImage.h.
References Viewer3DImage< Space, KSpace >::my3dImage, and Viewer3DImage< Space, KSpace >::Viewer3DImage().
{
     my3dImage = an3DImage;
     Viewer3DImage();
   }
Member Function Documentation
template<typename Space , typename KSpace > QString Viewer3DImage< Space, KSpace >::helpString () const protected virtual
Reimplemented from DGtal::Viewer3D< Space, KSpace >.
Definition at line 128 of file Viewer3DImage.cpp.
 {
   QString text ( "<h2> Viewer3DImage</h2>" );
   text += "Use the mouse to move the camera around the object. ";
   text += "You can respectively revolve around, zoom and translate with the three mouse buttons. ";
   text += "Left and middle buttons pressed together rotate around the camera view direction axis<br><br>";
   text += "Pressing <b>Alt</b> and one of the function keys (<b>F1</b>..<b>F12</b>) defines a camera keyFrame. ";
   text += "Simply press the function key again to restore it. Several keyFrames define a ";
   text += "camera path. Paths are saved when you quit the application and restored at next start.<br><br>";
   text += "Press <b>F</b> to display the frame rate, <b>A</b> for the world axis, ";
   text += "<b>Alt+Return</b> for full screen mode and <b>Control+S</b> to save a snapshot. ";
   text += "See the <b>Keyboard</b> tab in this window for a complete shortcut list.<br><br>";
   text += "Double clicks automates single click actions: A left button double click aligns the closer axis with the camera (if close enough). ";
   text += "A middle button double click fits the zoom of the camera and the right button re-centers the scene.<br><br>";
   text += "A left button double click while holding right button pressed defines the camera <i>Revolve Around Point</i>. ";
   text += "See the <b>Mouse</b> tab and the documentation web pages for details.<br><br>";
   text += "Press <b>Escape</b> to exit the viewer.";
   return text;
 }
template<typename Space , typename KSpace > void Viewer3DImage< Space, KSpace >::init () protected virtual
Reimplemented from DGtal::Viewer3D< Space, KSpace >.
Definition at line 40 of file Viewer3DImage.cpp.
References DGtal::Viewer3D< Space, KSpace >::init().
{
    DGtal::Viewer3D<>::init();
    QGLViewer::setKeyDescription ( Qt::Key_X, "Change the current axis to X for the current 2D image slice setting." );
    QGLViewer::setKeyDescription ( Qt::Key_Y, "Change the current axis to Y for the current 2D image slice setting." );
    QGLViewer::setKeyDescription ( Qt::Key_Z, "Change the current axis to Z for the current 2D image slice setting." );
    QGLViewer::setKeyDescription ( Qt::Key_Up, "Move the current 2D image slice to 5 in the positive direction of the current axis." );
    QGLViewer::setKeyDescription ( Qt::Key_Down, "Move the current 2D image slice to 5 in the negative direction of the current axis." );
    QGLViewer::setKeyDescription ( Qt::Key_Shift, "Change the slice move with step 1 (5 by default)" );
    QGLViewer::setKeyDescription ( Qt::Key_M, "Hide/Display message informations (slice numbers, selected axis)" );
 }
template<typename Space , typename KSpace > void Viewer3DImage< Space, KSpace >::keyPressEvent (QKeyEvent * e) protected virtual
Reimplemented from DGtal::Viewer3D< Space, KSpace >.
Definition at line 154 of file Viewer3DImage.cpp.
References DGtal::Viewer3D< Space, KSpace >::keyPressEvent().
 {
   bool handled = false;
   if( e->key() == Qt::Key_M){
     myDisplayingInfo = !myDisplayingInfo;
     handled=true;
   }
   if( e->key() == Qt::Key_I){
     std::cout << "Image generation" << std::endl;
     handled=true;
   }
   if( e->key() == Qt::Key_X){
     std::cout << "Current axis set to X" << std::endl;
     (*this).displayMessage(QString("Current axis set to X"), 100000);
     myCurrentSliceDim=0;
     handled=true;
   }
   if( e->key() == Qt::Key_Y){
     (*this).displayMessage(QString("Current axis set to Y"), 100000);
     myCurrentSliceDim=1;
     handled=true;
   }
   if( e->key() == Qt::Key_Z){
     (*this).displayMessage(QString("Current axis set to Z"), 100000);
     myCurrentSliceDim=2;
     handled=true;
   }
   if( e->key() == Qt::Key_Up ||  e->key() == Qt::Key_Down){
     int dirStep = (e->key() == Qt::Key_Up)? 5: -5;
     if((e->modifiers() & Qt::ShiftModifier)){
       dirStep/=5;
     }
     if((e->modifiers() & Qt::MetaModifier)){
       myAngleRotation =(e->key() == Qt::Key_Down)? 0.1: -0.1;
       dirStep=0;
     }else{
       myAngleRotation=0.0;
     }
     int aSliceNum=0;
     int aSliceMax=0;
     bool stoped=false;
     if(myCurrentSliceDim==0){
       aSliceMax=my3dImage->domain().upperBound()[0]+1;
       if(mySliceXPos+dirStep<aSliceMax&&mySliceXPos+dirStep>=myImageOrigin[0]){
          mySliceXPos+=dirStep;
       }else{
         stoped=true;
       }
       aSliceNum=mySliceXPos;
     }else if(myCurrentSliceDim==1){
       aSliceMax=my3dImage->domain().upperBound()[1]+1;
       if(mySliceYPos+dirStep<aSliceMax&&mySliceYPos+dirStep>=myImageOrigin[1]){
          mySliceYPos+=dirStep;
       }else{
         stoped=true;
       }
       aSliceNum=mySliceYPos;
     }else if(myCurrentSliceDim==2){
       aSliceMax=my3dImage->domain().upperBound()[2]+1;
        if(mySliceZPos+dirStep<aSliceMax&&mySliceZPos+dirStep>=myImageOrigin[2]){
          mySliceZPos+=dirStep;
        }else{
          stoped=true;
        }
        aSliceNum=mySliceZPos;
     }
     if(!stoped){
       double myTotalAngleRotation=0.0;
       if(myCurrentSliceDim==0){
         myTotalAngleRotationX+=myAngleRotation;
         myTotalAngleRotation = myTotalAngleRotationX;
       }else if (myCurrentSliceDim==1){
         myTotalAngleRotationY+=myAngleRotation;
         myTotalAngleRotation = myTotalAngleRotationY;
       }else if (myCurrentSliceDim==2){
         myTotalAngleRotationZ+=myAngleRotation;
         myTotalAngleRotation = myTotalAngleRotationZ;
       }
       DGtal::functors::SliceRotator2D<DGtal::Z3i::Domain> aSliceFunctor(myCurrentSliceDim, my3dImage->domain(),
                                                               aSliceNum, 2, myTotalAngleRotation);
       // Adding X slice in the viewer.
       DGtal::functors::Projector<DGtal::Z2i::Space>  invFunctor; invFunctor.initRemoveOneDim(myCurrentSliceDim);
       DGtal::Z2i::Domain domain2D(invFunctor(my3dImage->domain().lowerBound()),
                                   invFunctor(my3dImage->domain().upperBound()));
       const DGtal::functors::Identity identityFunctor{};
       MyRotatorSliceImageAdapter sliceImage( *my3dImage, domain2D, aSliceFunctor, identityFunctor );
       (*this) << DGtal::UpdateImageData<MyRotatorSliceImageAdapter>(myCurrentSliceDim, sliceImage,
                                                                    (myCurrentSliceDim==0)? dirStep: 0.0,
                                                                    (myCurrentSliceDim==1)? dirStep: 0.0,
                                                                    (myCurrentSliceDim==2)? dirStep: 0.0,
                                                            myAngleRotation, DGtal::Viewer3D<>::zDirection);
       (*this).updateList(false);
       (*this).update();
     }
     if(myDisplayingInfo){
       std::stringstream sstring;
       sstring << "slice X: " << mySliceXPos ;
       sstring << " slice Y: " << mySliceYPos ;
       sstring << " slice Z: " << mySliceZPos ;
       (*this).displayMessage(QString(sstring.str().c_str()), 100000);
     }
     handled=true;
   }
   if ( !handled )
     DGtal::Viewer3D<>::keyPressEvent ( e );
 }
template<typename Space , typename KSpace > void Viewer3DImage< Space, KSpace >::setVolImage (Image3D * an3DImage)
Definition at line 55 of file Viewer3DImage.cpp.
References DGtal::ConstImageAdapter< TImageContainer, TNewDomain, TFunctorD, TNewValue, TFunctorV >::className(), DGtal::functors::Projector< S >::initAddOneDim(), and DGtal::functors::Projector< S >::initRemoveOneDim().
{
   my3dImage = an3DImage;
   switch (myMode) {
   case BoundingBox:
     (*this) << DGtal::SetMode3D("ConstImageAdapter", "BoundingBox");
     break;
   case InterGrid:
     (*this) << DGtal::SetMode3D("ConstImageAdapter", "InterGrid");
     break;
   case Grid:
     (*this) << DGtal::SetMode3D("ConstImageAdapter", "Grid");
     break;
   case Empty:
     (*this) << DGtal::SetMode3D("ConstImageAdapter", "");
     break;
   }
   myImageOrigin = my3dImage->domain().lowerBound();
   (*this).updateList(false);
   (*this).update();
   mySliceXPos=myImageOrigin[0];
   mySliceYPos=myImageOrigin[1];
   mySliceZPos=myImageOrigin[2];
  // Adding X slice in the viewer.
   DGtal::functors::Projector<DGtal::Z2i::Space>  invFunctorX; invFunctorX.initRemoveOneDim(0);
   DGtal::Z2i::Domain domain2DX(invFunctorX(my3dImage->domain().lowerBound()),
                                invFunctorX(my3dImage->domain().upperBound()));
   DGtal::functors::SliceRotator2D<DGtal::Z3i::Domain> aSliceFunctorX(0, my3dImage->domain(), mySliceXPos,2, myAngleRotation );
   const DGtal::functors::Identity identityFunctor{};
   MyRotatorSliceImageAdapter sliceImageX( *my3dImage, domain2DX, aSliceFunctorX, identityFunctor );
   std::cout << "image:" << sliceImageX.className();
   (*this) << sliceImageX;
   (*this) << DGtal::UpdateImagePosition< Space, KSpace >(0, DGtal::Viewer3D<>::xDirection, mySliceXPos,myImageOrigin[1], myImageOrigin[2]);
   // Adding Y slice in the viewer.
   DGtal::functors::Projector<DGtal::Z2i::Space>  invFunctorY; invFunctorY.initRemoveOneDim(1);
   DGtal::Z2i::Domain domain2DY(invFunctorY(my3dImage->domain().lowerBound()),
                                invFunctorY(my3dImage->domain().upperBound()));
   DGtal::functors::Projector<DGtal::Z3i::Space> aSliceFunctorY(mySliceYPos); aSliceFunctorY.initAddOneDim(1);
   SliceImageAdapter sliceImageY(*my3dImage, domain2DY, aSliceFunctorY, identityFunctor );
   (*this) << sliceImageY;
   (*this) << DGtal::UpdateImagePosition< Space, KSpace >(1, DGtal::Viewer3D<>::yDirection, myImageOrigin[0], mySliceYPos, myImageOrigin[2]);
    // Adding Z slice in the viewer.
   DGtal::functors::Projector<DGtal::Z2i::Space>  invFunctorZ; invFunctorZ.initRemoveOneDim(2);
   DGtal::Z2i::Domain domain2DZ(invFunctorZ(my3dImage->domain().lowerBound()),
                                invFunctorZ(my3dImage->domain().upperBound()));
   DGtal::Z3i::Point centerZ((my3dImage->domain().upperBound())[0]/2, (my3dImage->domain().upperBound())[1]/2, mySliceZPos);
   DGtal::functors::SliceRotator2D<DGtal::Z3i::Domain> aSliceFunctorZ(2, my3dImage->domain(), mySliceZPos, 2, myAngleRotation, centerZ );
   MyRotatorSliceImageAdapter sliceImageZ( *my3dImage, domain2DZ, aSliceFunctorZ, identityFunctor );
   (*this) << sliceImageZ;
   (*this) << DGtal::UpdateImagePosition< Space, KSpace > (2, DGtal::Viewer3D<>::zDirection, myImageOrigin[0], myImageOrigin[1], mySliceZPos);
   (*this) << DGtal::Viewer3D<>::updateDisplay;
 }
Field Documentation
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> Image3D* Viewer3DImage< Space, KSpace >::my3dImage protected
Definition at line 68 of file Viewer3DImage.h.
Referenced by Viewer3DImage< Space, KSpace >::Viewer3DImage().
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> double Viewer3DImage< Space, KSpace >::myAngleRotation protected
Definition at line 76 of file Viewer3DImage.h.
Referenced by Viewer3DImage< Space, KSpace >::Viewer3DImage().
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> int Viewer3DImage< Space, KSpace >::myCurrentSliceDim protected
Definition at line 75 of file Viewer3DImage.h.
Referenced by Viewer3DImage< Space, KSpace >::Viewer3DImage().
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> bool Viewer3DImage< Space, KSpace >::myDisplayingInfo protected
Definition at line 80 of file Viewer3DImage.h.
Referenced by Viewer3DImage< Space, KSpace >::Viewer3DImage().
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> DGtal::Z3i::Point Viewer3DImage< Space, KSpace >::myImageOrigin protected
Definition at line 81 of file Viewer3DImage.h.
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> ModeVisu Viewer3DImage< Space, KSpace >::myMode protected
Definition at line 82 of file Viewer3DImage.h.
Referenced by Viewer3DImage< Space, KSpace >::Viewer3DImage().
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> float Viewer3DImage< Space, KSpace >::myScaleX protected
Definition at line 69 of file Viewer3DImage.h.
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> float Viewer3DImage< Space, KSpace >::myScaleY protected
Definition at line 70 of file Viewer3DImage.h.
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> float Viewer3DImage< Space, KSpace >::myScaleZ protected
Definition at line 71 of file Viewer3DImage.h.
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> int Viewer3DImage< Space, KSpace >::mySliceXPos protected
Definition at line 72 of file Viewer3DImage.h.
Referenced by Viewer3DImage< Space, KSpace >::Viewer3DImage().
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> int Viewer3DImage< Space, KSpace >::mySliceYPos protected
Definition at line 73 of file Viewer3DImage.h.
Referenced by Viewer3DImage< Space, KSpace >::Viewer3DImage().
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> int Viewer3DImage< Space, KSpace >::mySliceZPos protected
Definition at line 74 of file Viewer3DImage.h.
Referenced by Viewer3DImage< Space, KSpace >::Viewer3DImage().
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> double Viewer3DImage< Space, KSpace >::myTotalAngleRotationX protected
Definition at line 77 of file Viewer3DImage.h.
Referenced by Viewer3DImage< Space, KSpace >::Viewer3DImage().
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> double Viewer3DImage< Space, KSpace >::myTotalAngleRotationY protected
Definition at line 78 of file Viewer3DImage.h.
Referenced by Viewer3DImage< Space, KSpace >::Viewer3DImage().
template<typename Space = DGtal::Z3i::Space, typename KSpace = DGtal::Z3i::KSpace> double Viewer3DImage< Space, KSpace >::myTotalAngleRotationZ protected
Definition at line 79 of file Viewer3DImage.h.
Referenced by Viewer3DImage< Space, KSpace >::Viewer3DImage().
The documentation for this class was generated from the following files:
Viewer3DImage.h
Viewer3DImage.cpp