DGtalTools: DGtal::functions::dec Namespace Reference
DGtal::functions::dec Namespace Reference
Functions
template<typename Calculus , DGtal::Dimension dim, DGtal::Duality duality>
DGtal::LinearOperator< Calculus, dim, duality, dim, duality > diagonal (const DGtal::KForm< Calculus, dim, duality > &kform)
template<typename Calculus , DGtal::Dimension dim, DGtal::Duality duality>
void squares (DGtal::KForm< Calculus, dim, duality > &kform)
template<typename Calculus , DGtal::Dimension dim, DGtal::Duality duality>
DGtal::LinearOperator< Calculus, dim, duality, dim, duality > squaredDiagonal (const DGtal::KForm< Calculus, dim, duality > &kform)
template<typename Image >
void writePixel (Image &image, typename Image::Point pt, typename Image::Value val, int pixel_size=1)
template<typename Image >
void writePrimalLinel (Image &image, typename Image::Point pt, typename Image::Value val, int pixel_size=1)
template<typename Image >
void writeDualLinel (Image &image, typename Image::Point pt, typename Image::Value val, int pixel_size=1)
template<typename Calculus , typename AnyForm2 , typename Image , typename Function >
void form2ToImage (const Calculus &calculus, const AnyForm2 &u, Image &image, const Function &functor, double cut_low=0.0, double cut_up=1.0, int pixel_size=1)
template<typename Calculus , typename Form1 , typename Image , typename Function , typename Predicate >
void form1ToImage (const Calculus &calculus, const Form1 &v, bool primal, Image &image, const Function &functor, const Predicate &predicate, double cut_low=0.0, double cut_up=1.0, int pixel_size=1)
template<typename Calculus , typename Image , typename Function , typename Predicate >
void dualForm1ToImage (const Calculus &calculus, const typename Calculus::DualForm1 &v, Image &image, const Function &functor, const Predicate &predicate, double cut_low=0.0, double cut_up=1.0, int pixel_size=1)
template<typename Calculus , typename Image , typename Function , typename Predicate >
void primalForm1ToImage (const Calculus &calculus, const typename Calculus::PrimalForm1 &v, Image &image, const Function &functor, const Predicate &predicate, double cut_low=0.0, double cut_up=1.0, int pixel_size=1)
template<typename Calculus , typename AnyForm2 , typename Image , typename Function >
void threeForms2ToImage (const Calculus &calculus, const AnyForm2 &u0, const AnyForm2 &u1, const AnyForm2 &u2, Image &image, const Function &functor, double cut_low=0.0, double cut_up=1.0, int pixel_size=1)
template<typename Calculus , typename AnyForm2 , typename Image >
void form2ToGreyLevelImage (const Calculus &calculus, const AnyForm2 &u, Image &image, double cut_low=0.0, double cut_up=1.0, int pixel_size=1)
template<typename Calculus , typename Image >
void primalForm1ToGreyLevelImage (const Calculus &calculus, const typename Calculus::PrimalForm1 &v, Image &image, double cut_low=0.0, double cut_up=1.0, int pixel_size=1)
template<typename Calculus , typename Image >
void dualForm1ToGreyLevelImage (const Calculus &calculus, const typename Calculus::DualForm1 &v, Image &image, double cut_low=0.0, double cut_up=1.0, int pixel_size=1)
template<typename Calculus , typename Image >
void primalForm1ToRGBColorImage (const Calculus &calculus, const typename Calculus::PrimalForm1 &v, Image &image, Color color, double cut_low=0.0, double cut_up=1.0, int pixel_size=1)
template<typename Calculus , typename Image >
void dualForm1ToRGBColorImage (const Calculus &calculus, const typename Calculus::DualForm1 &v, Image &image, Color color, double cut_low=0.0, double cut_up=1.0, int pixel_size=1)
template<typename Calculus , typename AnyForm2 , typename Image >
void threeForms2ToRGBColorImage (const Calculus &calculus, const AnyForm2 &u0, const AnyForm2 &u1, const AnyForm2 &u2, Image &image, double cut_low=0.0, double cut_up=1.0, int pixel_size=1)
Function Documentation
template<typename Calculus , DGtal::Dimension dim, DGtal::Duality duality> DGtal::LinearOperator<Calculus, dim, duality, dim, duality> DGtal::functions::dec::diagonal (const DGtal::KForm< Calculus, dim, duality > & kform)
Builds a diagonal linear operator from a k-form. These operators arise naturally when differentiating with respect to another variable (e.g. d/dx (vx)^t (vx) = diag(v^2) x).
Parameters
[in] kform any kform w.
Returns
the corresponding linear operator diag(w)
Template Parameters
Calculus any discrete exterior calculus.
dim the dimension of the form.
duality either PRIMAL for a primal form or DUAL for a dual form.
Definition at line 72 of file DECImageHelpers.h.
References DGtal::KForm< TCalculus, order, duality >::length(), DGtal::KForm< TCalculus, order, duality >::myCalculus, and DGtal::KForm< TCalculus, order, duality >::myContainer.
Referenced by squaredDiagonal().
       {
         typedef DGtal::LinearOperator<Calculus,dim, duality, dim, duality> Operator;
         typedef typename Calculus::LinearAlgebraBackend::Triplet           Triplet;
         typedef typename Calculus::Index                                   Index;
         typedef std::vector<Triplet>                                       Triplets;
         Triplets triplets;
         for (Index index=0; index<kform.length(); index++)
           triplets.push_back(Triplet(index, index, kform.myContainer(index)));
         Operator op( kform.myCalculus );
         op.myContainer.setFromTriplets( triplets.begin(), triplets.end() );
         return op;
       }
template<typename Calculus , typename Image > void DGtal::functions::dec::dualForm1ToGreyLevelImage (const Calculus & calculus, const typename Calculus::DualForm1 & v, Image & image, double cut_low = 0.0, double cut_up = 1.0, int pixel_size = 1)
Standard method to output a dual 1-form into a grey-level image.
Displays the dual 1-form v in the given image. Scalar values of v are first cut up and low according to cut_low and cut_up, and then rescaled according to max and min value. If this value is belows 0.25, it is written in the image as a "line" of size pixel_size x 1 or 1 x pixel_size, depending on position.
Parameters
calculus the discrete exterior calculus containing the 1-form v.
v any dual 1-form defined in calculus.
[in,out] image the image where v is written.
cut_low every value of u below is set to cut_low.
cut_up every value of u above is set to cut_up.
pixel_size every value of a 1-form is mapped into image as pixel_size x 1 pixels or 1 x pixel_size pixels.
Template Parameters
Calculus any discrete exterior calculus type.
Image any image type (see concepts::CImage).
Definition at line 578 of file DECImageHelpers.h.
References dualForm1ToImage().
       {
         BOOST_CONCEPT_ASSERT(( concepts::CImage<Image> ));
         // Threshold is 0.25 instead of 0.5 because an edge connecting
         // two vertices with v=0 and v=1 should not belong to the
         // discontinuity set.
         dualForm1ToImage( calculus, v, image,
                           [] ( double x ) { return (unsigned char) ( round( x * 255.0 ) ); },
                           [] ( double x ) { return x < 0.25; },
                           cut_low, cut_up, pixel_size );
       }
template<typename Calculus , typename Image , typename Function , typename Predicate > void DGtal::functions::dec::dualForm1ToImage (const Calculus & calculus, const typename Calculus::DualForm1 & v, Image & image, const Function & functor, const Predicate & predicate, double cut_low = 0.0, double cut_up = 1.0, int pixel_size = 1)
Displays the dual 1-form v in the given image. Scalar values of v are first cut up and low according to cut_low and cut_up, and then rescaled according to max and min value. Then these values are transformed to image values with the function functor. They are written in the image as "lines" of size pixel_size x 1 or 1 x pixel_size, depending on position and duality.
Parameters
calculus the discrete exterior calculus containing the 1-form v.
v any dual 1-form defined in calculus.
[in,out] image the image where v is written.
functor the function transforming scalar values to image values.
predicate the predicate telling for a value if it must be displayed (returns true in this case).
cut_low every value of u below is set to cut_low.
cut_up every value of u above is set to cut_up.
pixel_size every value of a 1-form is mapped into image as pixel_size x 1 pixels or 1 x pixel_size pixels.
Template Parameters
Calculus any discrete exterior calculus type.
Image any image type (see concepts::CImage).
Function any function type (double) -> typename Image::Value to convert form value to Image value.
Predicate any function type (double) -> bool to select 1-forms to display.
Definition at line 360 of file DECImageHelpers.h.
References form1ToImage().
Referenced by dualForm1ToGreyLevelImage(), and dualForm1ToRGBColorImage().
       {
         BOOST_CONCEPT_ASSERT(( concepts::CImage<Image> ));
         form1ToImage( calculus, v, false, image, functor, predicate,
                       cut_low, cut_up, pixel_size );
       }
template<typename Calculus , typename Image > void DGtal::functions::dec::dualForm1ToRGBColorImage (const Calculus & calculus, const typename Calculus::DualForm1 & v, Image & image, Color color, double cut_low = 0.0, double cut_up = 1.0, int pixel_size = 1)
Standard method to output a dual 1-form into a color image.
Displays the dual 1-form v in the given image. Scalar values of v are first cut up and low according to cut_low and cut_up, and then rescaled according to max and min value. If this value is belows 0.25, it is written in the image as a "line" of size pixel_size x 1 or 1 x pixel_size, depending on position, and of color color.
Parameters
calculus the discrete exterior calculus containing the 1-form v.
v any dual 1-form defined in calculus.
[in,out] image the image where v is written.
color the color for displaying 1-forms below 0.25.
cut_low every value of u below is set to cut_low.
cut_up every value of u above is set to cut_up.
pixel_size every value of a 1-form is mapped into image as pixel_size x 1 pixels or 1 x pixel_size pixels.
Template Parameters
Calculus any discrete exterior calculus type.
Image any image type (see concepts::CImage).
Definition at line 656 of file DECImageHelpers.h.
References dualForm1ToImage().
       {
         BOOST_CONCEPT_ASSERT(( concepts::CImage<Image> ));
         // Threshold is 0.25 instead of 0.5 because an edge connecting
         // two vertices with v=0 and v=1 should not belong to the
         // discontinuity set.
         dualForm1ToImage( calculus, v, image,
                           [color] ( double x ) { return color; },
                           [] ( double x ) { return x < 0.25; },
                           cut_low, cut_up, pixel_size );
       }
template<typename Calculus , typename Form1 , typename Image , typename Function , typename Predicate > void DGtal::functions::dec::form1ToImage (const Calculus & calculus, const Form1 & v, bool primal, Image & image, const Function & functor, const Predicate & predicate, double cut_low = 0.0, double cut_up = 1.0, int pixel_size = 1)
Displays the primal or dual 1-form v in the given image. Scalar values of v are first cut up and low according to cut_low and cut_up, and then rescaled according to max and min value. Then these values are transformed to image values with the function functor. They are written in the image as "lines" of size pixel_size x 1 or 1 x pixel_size, depending on position and duality.
Parameters
calculus the discrete exterior calculus containing the 1-form v.
v any primal 1-form defined in calculus if primal is true, otherwise a dual 1-form.
primal tells if v is a primal 1-form (true), or a dual 1-form (false).
[in,out] image the image where v is written.
functor the function transforming scalar values to image values.
predicate the predicate telling for a value if it must be displayed (returns true in this case).
cut_low every value of u below is set to cut_low.
cut_up every value of u above is set to cut_up.
pixel_size every value of a 1-form is mapped into image as pixel_size x 1 pixels or 1 x pixel_size pixels.
Template Parameters
Calculus any discrete exterior calculus type.
Form1 either a primal 1-form if primal is true, or dual 1-form is primal is false.
Image any image type (see concepts::CImage).
Function any function type (double) -> typename Image::Value to convert form value to Image value.
Predicate any function type (double) -> bool to select 1-forms to display.
Definition at line 298 of file DECImageHelpers.h.
References DGtal::NumberTraits< T >::castToDouble(), DGtal::DiscreteExteriorCalculus< dimEmbedded, dimAmbient, TLinearAlgebraBackend, TInteger >::myKSpace, DGtal::KhalimskySpaceND< dim, TInteger >::sKCoords(), writeDualLinel(), and writePrimalLinel().
Referenced by dualForm1ToImage(), and primalForm1ToImage().
       {
         BOOST_CONCEPT_ASSERT(( concepts::CImage<Image> ));
         typedef typename Calculus::Index  Index;
         typedef typename Calculus::SCell  SCell;
         typedef typename Calculus::Scalar Scalar;
         typedef typename Calculus::KSpace KSpace;
         typedef typename KSpace::Point    Point;
         typedef typename KSpace::Integer  Integer;
         double min_v = NumberTraits<Scalar>::castToDouble( v.myContainer[ 0 ] );
         double max_v = min_v;
         for ( Index index = 0; index < v.myContainer.rows(); index++)
           {
             double w = NumberTraits<Scalar>::castToDouble( v.myContainer[ index ] );
             min_v = std::min( min_v, w );
             max_v = std::max( max_v, w );
           }
         if ( min_v < cut_low ) min_v = cut_low;
         if ( max_v > cut_up  ) max_v = cut_up;
         for ( Index index = 0; index < v.myContainer.rows(); index++)
           {
             SCell cell = v.getSCell( index );
             double u = NumberTraits<Scalar>::castToDouble( v.myContainer[ index ] );
             if ( ! predicate( u ) ) continue;
             double w = std::min( cut_up, std::max( cut_low, u ) );
             if ( min_v != max_v ) w = ( w - min_v ) / ( max_v - min_v );
             Point kpt = calculus.myKSpace.sKCoords( cell );
             if ( primal ) writePrimalLinel( image, kpt, functor( w ), pixel_size );
             else          writeDualLinel  ( image, kpt, functor( w ), pixel_size );
           }
       }
template<typename Calculus , typename AnyForm2 , typename Image > void DGtal::functions::dec::form2ToGreyLevelImage (const Calculus & calculus, const AnyForm2 & u, Image & image, double cut_low = 0.0, double cut_up = 1.0, int pixel_size = 1)
Standard method to output a 2-form into a grey-level image.
Displays the 2-form u in the given image. Scalar values of u are first cut up and low according to cut_low and cut_up, and then rescaled according to max and min value. They are written in the image as grey-level "pixels" of size pixel_size x pixel_size.
Parameters
calculus the discrete exterior calculus containing the 2-form u.
u any primal or dual 2-form defined in calculus.
[in,out] image the image where u is written.
cut_low every value of u below is set to cut_low.
cut_up every value of u above is set to cut_up.
pixel_size every value of a 2-form is mapped into image as pixel_size x pixel_size pixels.
Template Parameters
Calculus any discrete exterior calculus type.
AnyForm2 either a primal 2-form type or a dual 2-form type of the given Calculus.
Image any image type (see concepts::CImage).
Definition at line 506 of file DECImageHelpers.h.
References form2ToImage().
       {
         BOOST_CONCEPT_ASSERT(( concepts::CImage<Image> ));
         form2ToImage( calculus, u, image,
                       [] ( double x ) { return (unsigned char) ( round( x * 255.0 ) ); },
                       cut_low, cut_up, pixel_size );
       }
template<typename Calculus , typename AnyForm2 , typename Image , typename Function > void DGtal::functions::dec::form2ToImage (const Calculus & calculus, const AnyForm2 & u, Image & image, const Function & functor, double cut_low = 0.0, double cut_up = 1.0, int pixel_size = 1)
Displays the 2-form u in the given image. Scalar values of u are first cut up and low according to cut_low and cut_up, and then rescaled according to max and min value. Then these values are transformed to image values with the function functor. They are written in the image as "pixels" of size pixel_size x pixel_size.
Parameters
calculus the discrete exterior calculus containing the 2-form u.
u any primal or dual 2-form defined in calculus.
[in,out] image the image where u is written.
functor the function transforming scalar values to image values.
cut_low every value of u below is set to cut_low.
cut_up every value of u above is set to cut_up.
pixel_size every value of a 2-form is mapped into image as pixel_size x pixel_size pixels.
Template Parameters
Calculus any discrete exterior calculus type.
AnyForm2 either a primal 2-form type or a dual 2-form type of the given Calculus.
Image any image type (see concepts::CImage).
Function any function type (double) -> typename Image::Value to convert form value to Image value.
Definition at line 238 of file DECImageHelpers.h.
References DGtal::NumberTraits< T >::castToDouble(), DGtal::DiscreteExteriorCalculus< dimEmbedded, dimAmbient, TLinearAlgebraBackend, TInteger >::myKSpace, DGtal::KhalimskySpaceND< dim, TInteger >::sCoords(), and writePixel().
Referenced by form2ToGreyLevelImage().
       {
         BOOST_CONCEPT_ASSERT(( concepts::CImage<Image> ));
         typedef typename Calculus::Index  Index;
         typedef typename Calculus::SCell  SCell;
         typedef typename Calculus::Scalar Scalar;
         typedef typename Calculus::KSpace KSpace;
         typedef typename KSpace::Point    Point;
         typedef typename KSpace::Integer  Integer;
         double min_u = NumberTraits<Scalar>::castToDouble( u.myContainer[ 0 ] );
         double max_u = min_u;
         for ( Index index = 0; index < u.myContainer.rows(); index++)
           {
             double v = NumberTraits<Scalar>::castToDouble( u.myContainer[ index ] );
             min_u = std::min( min_u, v );
             max_u = std::max( max_u, v );
           }
         if ( min_u < cut_low ) min_u = cut_low;
         if ( max_u > cut_up  ) max_u = cut_up;
         for ( Index index = 0; index < u.myContainer.rows(); index++)
           {
             SCell cell = u.getSCell( index );
             double v = NumberTraits<Scalar>::castToDouble( u.myContainer[ index ] );
             double w = std::min( cut_up, std::max( cut_low, v ) );
             if ( min_u != max_u ) w = ( w - min_u ) / ( max_u - min_u );
             writePixel( image, calculus.myKSpace.sCoords( cell ), functor( w ), pixel_size );
           }
       }
template<typename Calculus , typename Image > void DGtal::functions::dec::primalForm1ToGreyLevelImage (const Calculus & calculus, const typename Calculus::PrimalForm1 & v, Image & image, double cut_low = 0.0, double cut_up = 1.0, int pixel_size = 1)
Standard method to output a primal 1-form into a grey-level image.
Displays the primal 1-form v in the given image. Scalar values of v are first cut up and low according to cut_low and cut_up, and then rescaled according to max and min value. If this value is belows 0.25, it is written in the image as a "line" of size pixel_size x 1 or 1 x pixel_size, depending on position.
Parameters
calculus the discrete exterior calculus containing the 1-form v.
v any primal 1-form defined in calculus.
[in,out] image the image where v is written.
cut_low every value of u below is set to cut_low.
cut_up every value of u above is set to cut_up.
pixel_size every value of a 1-form is mapped into image as pixel_size x 1 pixels or 1 x pixel_size pixels.
Template Parameters
Calculus any discrete exterior calculus type.
Image any image type (see concepts::CImage).
Definition at line 540 of file DECImageHelpers.h.
References primalForm1ToImage().
       {
         BOOST_CONCEPT_ASSERT(( concepts::CImage<Image> ));
         // Threshold is 0.25 instead of 0.5 because an edge connecting
         // two vertices with v=0 and v=1 should not belong to the
         // discontinuity set.
         primalForm1ToImage( calculus, v, image,
                             [] ( double x ) { return (unsigned char) ( round( x * 255.0 ) ); },
                             [] ( double x ) { return x < 0.25; },
                             cut_low, cut_up, pixel_size );
       }
template<typename Calculus , typename Image , typename Function , typename Predicate > void DGtal::functions::dec::primalForm1ToImage (const Calculus & calculus, const typename Calculus::PrimalForm1 & v, Image & image, const Function & functor, const Predicate & predicate, double cut_low = 0.0, double cut_up = 1.0, int pixel_size = 1)
Displays the primal 1-form v in the given image. Scalar values of v are first cut up and low according to cut_low and cut_up, and then rescaled according to max and min value. Then these values are transformed to image values with the function functor. They are written in the image as "lines" of size pixel_size x 1 or 1 x pixel_size, depending on position and duality.
Parameters
calculus the discrete exterior calculus containing the 1-form v.
v any primal 1-form defined in calculus.
[in,out] image the image where v is written.
functor the function transforming scalar values to image values.
predicate the predicate telling for a value if it must be displayed (returns true in this case).
cut_low every value of u below is set to cut_low.
cut_up every value of u above is set to cut_up.
pixel_size every value of a 1-form is mapped into image as pixel_size x 1 pixels or 1 x pixel_size pixels.
Template Parameters
Calculus any discrete exterior calculus type.
Image any image type (see concepts::CImage).
Function any function type (double) -> typename Image::Value to convert form value to Image value.
Predicate any function type (double) -> bool to select 1-forms to display.
Definition at line 397 of file DECImageHelpers.h.
References form1ToImage().
Referenced by primalForm1ToGreyLevelImage(), and primalForm1ToRGBColorImage().
       {
         BOOST_CONCEPT_ASSERT(( concepts::CImage<Image> ));
         form1ToImage( calculus, v, true, image, functor, predicate,
                       cut_low, cut_up, pixel_size );
       }
template<typename Calculus , typename Image > void DGtal::functions::dec::primalForm1ToRGBColorImage (const Calculus & calculus, const typename Calculus::PrimalForm1 & v, Image & image, Color color, double cut_low = 0.0, double cut_up = 1.0, int pixel_size = 1)
Standard method to output a primal 1-form into a color image.
Displays the primal 1-form v in the given image. Scalar values of v are first cut up and low according to cut_low and cut_up, and then rescaled according to max and min value. If this value is belows 0.25, it is written in the image as a "line" of size pixel_size x 1 or 1 x pixel_size, depending on position, and of color color.
Parameters
calculus the discrete exterior calculus containing the 1-form v.
v any primal 1-form defined in calculus.
[in,out] image the image where v is written.
color the color for displaying 1-forms below 0.25.
cut_low every value of u below is set to cut_low.
cut_up every value of u above is set to cut_up.
pixel_size every value of a 1-form is mapped into image as pixel_size x 1 pixels or 1 x pixel_size pixels.
Template Parameters
Calculus any discrete exterior calculus type.
Image any image type (see concepts::CImage).
Definition at line 617 of file DECImageHelpers.h.
References primalForm1ToImage().
       {
         BOOST_CONCEPT_ASSERT(( concepts::CImage<Image> ));
         // Threshold is 0.25 instead of 0.5 because an edge connecting
         // two vertices with v=0 and v=1 should not belong to the
         // discontinuity set.
         primalForm1ToImage( calculus, v, image,
                             [color] ( double x ) { return color; },
                             [] ( double x ) { return x < 0.25; },
                             cut_low, cut_up, pixel_size );
       }
template<typename Calculus , DGtal::Dimension dim, DGtal::Duality duality> DGtal::LinearOperator<Calculus, dim, duality, dim, duality> DGtal::functions::dec::squaredDiagonal (const DGtal::KForm< Calculus, dim, duality > & kform)
Builds a diagonal linear operator from a k-form and squares it. These operators arise naturally when differentiating with respect to another variable (e.g. d/dx (vx)^t (vx) = diag(v^2) x).
Parameters
[in] kform any kform v
Returns
the corresponding linear operator diag(v^2)
Template Parameters
Calculus any discrete exterior calculus.
dim the dimension of the form.
duality either PRIMAL for a primal form or DUAL for a dual form.
Definition at line 118 of file DECImageHelpers.h.
References diagonal(), and squares().
       {
         auto v2 = kform;
         squares( v2 );
         return diagonal( v2 );
       }
template<typename Calculus , DGtal::Dimension dim, DGtal::Duality duality> void DGtal::functions::dec::squares (DGtal::KForm< Calculus, dim, duality > & kform)
Squares the given k-form.
Parameters
[in,out] kform any kform.
Template Parameters
Calculus any discrete exterior calculus.
dim the dimension of the form.
duality either PRIMAL for a primal form or DUAL for a dual form.
Definition at line 99 of file DECImageHelpers.h.
References DGtal::KForm< TCalculus, order, duality >::myContainer.
Referenced by squaredDiagonal().
       {
         kform.myContainer.array() = kform.myContainer.array().square();
       }
template<typename Calculus , typename AnyForm2 , typename Image , typename Function > void DGtal::functions::dec::threeForms2ToImage (const Calculus & calculus, const AnyForm2 & u0, const AnyForm2 & u1, const AnyForm2 & u2, Image & image, const Function & functor, double cut_low = 0.0, double cut_up = 1.0, int pixel_size = 1)
Displays the three 2-forms u0, u1, u2 in the given image. Scalar values of u0, u1, u2 are first cut up and low according to cut_low and cut_up, and then rescaled according to max and min value. Then these values are transformed to image values with the function functor. They are written in the image as "pixels" of size pixel_size x pixel_size.
Parameters
calculus the discrete exterior calculus containing the 2-forms u0, u1, u2.
u0 any primal or dual 2-form defined in calculus.
u1 any primal or dual 2-form defined in calculus.
u2 any primal or dual 2-form defined in calculus.
[in,out] image the image where u is written.
functor the function transforming three scalar values to image values.
cut_low every value of u0, u1, u2 below is set to cut_low.
cut_up every value of u0, u1, u2 above is set to cut_up.
pixel_size every value of 2-forms is mapped into image as pixel_size x pixel_size pixels.
Template Parameters
Calculus any discrete exterior calculus type.
AnyForm2 either a primal 2-form type or a dual 2-form type of the given Calculus.
Image any image type (see concepts::CImage).
Function any function type (double,double,double) -> typename Image::Value to convert form value to Image value.
Definition at line 434 of file DECImageHelpers.h.
References DGtal::NumberTraits< T >::castToDouble(), DGtal::DiscreteExteriorCalculus< dimEmbedded, dimAmbient, TLinearAlgebraBackend, TInteger >::myKSpace, DGtal::KhalimskySpaceND< dim, TInteger >::sCoords(), and writePixel().
Referenced by threeForms2ToRGBColorImage().
       {
         BOOST_CONCEPT_ASSERT(( concepts::CImage<Image> ));
         typedef typename Calculus::Index  Index;
         typedef typename Calculus::SCell  SCell;
         typedef typename Calculus::Scalar Scalar;
         double min_u = NumberTraits<Scalar>::castToDouble( u0.myContainer[ 0 ] );
         double max_u = min_u;
         for ( Index index = 0; index < u0.myContainer.rows(); index++)
           {
             double v = NumberTraits<Scalar>::castToDouble( u0.myContainer[ index ] );
             min_u = std::min( min_u, v );
             max_u = std::max( max_u, v );
           }
         for ( Index index = 0; index < u1.myContainer.rows(); index++)
           {
             double v = NumberTraits<Scalar>::castToDouble( u1.myContainer[ index ] );
             min_u = std::min( min_u, v );
             max_u = std::max( max_u, v );
           }
         for ( Index index = 0; index < u2.myContainer.rows(); index++)
           {
             double v = NumberTraits<Scalar>::castToDouble( u2.myContainer[ index ] );
             min_u = std::min( min_u, v );
             max_u = std::max( max_u, v );
           }
         if ( min_u < cut_low ) min_u = cut_low;
         if ( max_u > cut_up  ) max_u = cut_up;
         for ( Index index = 0; index < u0.myContainer.rows(); index++)
           {
             SCell cell = u0.getSCell( index );
             double v0 = NumberTraits<Scalar>::castToDouble( u0.myContainer[ index ] );
             double w0 = std::min( cut_up, std::max( cut_low, v0 ) );
             if ( min_u != max_u ) w0 = ( w0 - min_u ) / ( max_u - min_u );
             double v1 = NumberTraits<Scalar>::castToDouble( u1.myContainer[ index ] );
             double w1 = std::min( cut_up, std::max( cut_low, v1 ) );
             if ( min_u != max_u ) w1 = ( w1 - min_u ) / ( max_u - min_u );
             double v2 = NumberTraits<Scalar>::castToDouble( u2.myContainer[ index ] );
             double w2 = std::min( cut_up, std::max( cut_low, v2 ) );
             if ( min_u != max_u ) w2 = ( w2 - min_u ) / ( max_u - min_u );
             writePixel( image, calculus.myKSpace.sCoords( cell ), functor( w0, w1, w2 ), pixel_size );
           }
       }
template<typename Calculus , typename AnyForm2 , typename Image > void DGtal::functions::dec::threeForms2ToRGBColorImage (const Calculus & calculus, const AnyForm2 & u0, const AnyForm2 & u1, const AnyForm2 & u2, Image & image, double cut_low = 0.0, double cut_up = 1.0, int pixel_size = 1)
Standard method to output three 2-forms into a RGB Color image.
Displays the three 2-forms u0, u1, u2 in the given image as RGB colors. Scalar values of u0, u1, u2 are first cut up and low according to cut_low and cut_up, and then rescaled according to max and min value. Then these values are transformed to RGB color image values (u0 defines the intensity of the red channel, u1 the green channel, u2, the blue channel). They are written in the image as "pixels" of size pixel_size x pixel_size.
Parameters
calculus the discrete exterior calculus containing the 2-forms u0, u1, u2.
u0 any primal or dual 2-form defined in calculus.
u1 any primal or dual 2-form defined in calculus.
u2 any primal or dual 2-form defined in calculus.
[in,out] image the image where u is written.
cut_low every value of u0, u1, u2 below is set to cut_low.
cut_up every value of u0, u1, u2 above is set to cut_up.
pixel_size every value of 2-forms is mapped into image as pixel_size x pixel_size pixels.
Template Parameters
Calculus any discrete exterior calculus type.
AnyForm2 either a primal 2-form type or a dual 2-form type of the given Calculus.
Image any image type (see concepts::CImage).
Definition at line 699 of file DECImageHelpers.h.
References threeForms2ToImage().
       {
         BOOST_CONCEPT_ASSERT(( concepts::CImage<Image> ));
         threeForms2ToImage
           ( calculus, u0, u1, u2, image,
             [] ( double r, double g, double b )
             { return Color( (unsigned char) ( round( r * 255.0 ) ),
                             (unsigned char) ( round( g * 255.0 ) ),
                             (unsigned char) ( round( b * 255.0 ) ) ); },
             cut_low, cut_up, pixel_size );
       }
template<typename Image > void DGtal::functions::dec::writeDualLinel (Image & image, typename Image::Point pt, typename Image::Value val, int pixel_size = 1)
Considers an image image to have pixels of size pixel_size x pixel_size, and writes the value val at the specified linel position pt.
Parameters
[in,out] image any image of sufficient size.
pt a linel Khalimsky coordinates.
val the value to write in pixel_size x 1 pixels (if horizontal) or 1 x pixel_size pixels (if vertical).
pixel_size the chosen pixel_size (when 1, this is the normal setValue of an image).
Template Parameters
Image any image type (see concepts::CImage).
Definition at line 197 of file DECImageHelpers.h.
References DGtal::NumberTraits< T >::even(), and DGtal::Image< class >::setValue().
Referenced by form1ToImage().
       {
         BOOST_CONCEPT_ASSERT(( concepts::CImage<Image> ));
         typedef typename Image::Point      Point;
         typedef typename Point::Coordinate Coordinate;
         int pixel_size_x = NumberTraits<Coordinate>::even( pt[ 0 ] ) ? 0 : pixel_size-1;
         int pixel_size_y = NumberTraits<Coordinate>::even( pt[ 1 ] ) ? 0 : pixel_size-1;
         pt /= 2;
         pt *= pixel_size;
         for ( int y = pixel_size_y; y < pixel_size; y++ )
           for ( int x = pixel_size_x; x < pixel_size; x++ )
             {
               Point q( (Coordinate) x, (Coordinate) y );
               image.setValue( pt + q, val );
             }
       }
template<typename Image > void DGtal::functions::dec::writePixel (Image & image, typename Image::Point pt, typename Image::Value val, int pixel_size = 1)
Considers an image image to have pixels of size pixel_size x pixel_size, and writes the value val at the specified pixel position pt.
Parameters
[in,out] image any image of sufficient size.
pt a pixel coordinate (which is multiplied by pixel_size within).
val the value to write in pixel_size x pixel_size pixels.
pixel_size the chosen pixel_size (when 1, this is the normal setValue of an image).
Template Parameters
Image any image type (see concepts::CImage).
Definition at line 138 of file DECImageHelpers.h.
References DGtal::Image< class >::setValue().
Referenced by form2ToImage(), and threeForms2ToImage().
       {
         BOOST_CONCEPT_ASSERT(( concepts::CImage<Image> ));
         typedef typename Image::Point      Point;
         typedef typename Point::Coordinate Coordinate;
         pt *= pixel_size;
         for ( int y = 0; y < pixel_size; y++ )
           for ( int x = 0; x < pixel_size; x++ )
             {
               Point q( (Coordinate) x, (Coordinate) y );
               image.setValue( pt + q, val );
             }
       }
template<typename Image > void DGtal::functions::dec::writePrimalLinel (Image & image, typename Image::Point pt, typename Image::Value val, int pixel_size = 1)
Considers an image image to have pixels of size pixel_size x pixel_size, and writes the value val at the specified linel position pt.
Parameters
[in,out] image any image of sufficient size.
pt a linel Khalimsky coordinates.
val the value to write in pixel_size x 1 pixels (if horizontal) or 1 x pixel_size pixels (if vertical).
pixel_size the chosen pixel_size (when 1, this is the normal setValue of an image).
Template Parameters
Image any image type (see concepts::CImage).
Definition at line 166 of file DECImageHelpers.h.
References DGtal::NumberTraits< T >::even(), and DGtal::Image< class >::setValue().
Referenced by form1ToImage().
       {
         BOOST_CONCEPT_ASSERT(( concepts::CImage<Image> ));
         typedef typename Image::Point      Point;
         typedef typename Point::Coordinate Coordinate;
         int pixel_size_x = NumberTraits<Coordinate>::even( pt[ 0 ] ) ? 1 : pixel_size;
         int pixel_size_y = NumberTraits<Coordinate>::even( pt[ 1 ] ) ? 1 : pixel_size;
         pt /= 2;
         pt *= pixel_size;
         for ( int y = 0; y < pixel_size_y; y++ )
           for ( int x = 0; x < pixel_size_x; x++ )
             {
               Point q( (Coordinate) x, (Coordinate) y );
               image.setValue( pt + q, val );
             }
       }