DGtal: DGtal::HalfEdgeDataStructure Class Reference
DGtal::HalfEdgeDataStructure Class Reference
Aim: This class represents an half-edge data structure, which is a structure for representing the topology of a combinatorial 2-dimensional surface or an embedding of a planar graph in the plane. It does not store any geometry. As a minimal example, these lines of code build two triangles connected by the edge {1,2}.
#include <DGtal/topology/HalfEdgeDataStructure.h>
Data Structures
struct Edge
struct HalfEdge
struct Triangle
Represents an unoriented triangle as three vertices.
Public Types
typedef std::size_t Size
The type for counting elements.
typedef std::size_t Index
The type used for numbering half-edges (an offset an the half-edges structure).
typedef Index HalfEdgeIndex
The type used for numbering half-edges (alias)
typedef Index VertexIndex
The type for numbering vertices.
typedef Index EdgeIndex
The type for numbering edges.
typedef Index FaceIndex
The type for numbering faces.
typedef std::vector< HalfEdgeIndex > HalfEdgeIndexRange
typedef std::vector< VertexIndex > VertexIndexRange
typedef std::vector< EdgeIndex > EdgeIndexRange
typedef std::vector< FaceIndex > FaceIndexRange
typedef std::pair< VertexIndex, VertexIndex > Arc
An arc is a directed edge from a first vertex to a second vertex.
typedef std::map< Arc, Index > Arc2Index
typedef std::map< Arc, FaceIndex > Arc2FaceIndex
typedef std::vector< VertexIndex > PolygonalFace
Public Member Functions
HalfEdgeDataStructure ()
Default constructor. The data structure is empty.
bool build (const Size num_vertices, const std::vector< Triangle > &triangles, const std::vector< Edge > &edges)
bool build (const Size num_vertices, const std::vector< PolygonalFace > &polygonal_faces, const std::vector< Edge > &edges)
bool build (const std::vector< Triangle > &triangles)
bool build (const std::vector< PolygonalFace > &polygonal_faces)
void clear ()
Clears the data structure.
Size nbHalfEdges () const
Size nbVertices () const
Size nbEdges () const
Size nbFaces () const
long Euler () const
const HalfEdge & halfEdge (const Index i) const
Arc arcFromHalfEdgeIndex (const Index i) const
Index halfEdgeIndexFromArc (const VertexIndex i, const VertexIndex j) const
Index halfEdgeIndexFromArc (const Arc &arc) const
Index findHalfEdgeIndexFromArc (const VertexIndex i, const VertexIndex j) const
Index findHalfEdgeIndexFromArc (const Arc &arc) const
Index halfEdgeIndexFromVertexIndex (const VertexIndex vi) const
Index halfEdgeIndexFromFaceIndex (const FaceIndex fi) const
Index halfEdgeIndexFromEdgeIndex (const EdgeIndex ei) const
void getNeighboringVertices (const VertexIndex vi, VertexIndexRange &result) const
VertexIndexRange neighboringVertices (const VertexIndex vi) const
Size nbNeighboringVertices (const Index vi) const
void getNeighboringFaces (const VertexIndex vi, FaceIndexRange &result) const
FaceIndexRange neighboringFaces (const VertexIndex vi) const
bool isVertexBoundary (const VertexIndex vi) const
VertexIndexRange boundaryVertices () const
std::vector< Index > boundaryHalfEdgeIndices () const
std::vector< Arc > boundaryArcs () const
Size nbSides (Index hei) const
Size nbSidesOfFace (const FaceIndex f) const
VertexIndexRange verticesOfFace (const FaceIndex f) const
bool isFlippable (const Index hei) const
void flip (const Index hei, bool update_arc2index=true)
VertexIndex split (const Index i, bool update_arc2index=true)
bool isMergeable (const Index hei) const
VertexIndex merge (const Index hei, bool update_arc2index=true)
bool isValid (bool check_arc2index=true) const
bool isValidTriangulation () const
void selfDisplay (std::ostream &out) const
Static Public Member Functions
static Size getUnorderedEdgesFromTriangles (const std::vector< Triangle > &triangles, std::vector< Edge > &edges_out)
static Size getUnorderedEdgesFromPolygonalFaces (const std::vector< PolygonalFace > &polygonal_faces, std::vector< Edge > &edges_out)
Protected Member Functions
void renumberVertex (const VertexIndex vi, bool update_arc2index=true)
void renumberEdge (const EdgeIndex ei)
void renumberFace (const FaceIndex fi)
void renumberHalfEdge (const Index i, bool update_arc2index=true)
Static Protected Member Functions
static FaceIndex arc2FaceIndex (const Arc2FaceIndex &de2fi, VertexIndex vi, VertexIndex vj)
Protected Attributes
std::vector< HalfEdge > myHalfEdges
Stores all the half-edges.
std::vector< Index > myVertexHalfEdges
std::vector< Index > myFaceHalfEdges
std::vector< Index > myEdgeHalfEdges
Arc2Index myArc2Index
The mapping between arcs to their half-edge index.
Detailed Description
Aim: This class represents an half-edge data structure, which is a structure for representing the topology of a combinatorial 2-dimensional surface or an embedding of a planar graph in the plane. It does not store any geometry. As a minimal example, these lines of code build two triangles connected by the edge {1,2}.
Description of template class 'HalfEdgeDataStructure'
std::vector< HalfEdgeDataStructure::Triangle > triangles(2);
triangles[0].v = { 0, 1, 2 };
triangles[1].v = { 2, 1, 3 };
HalfEdgeDataStructure mesh;
mesh.build(triangles);
std::cout << mesh << std::endl;
Note
Large parts of this class are taken from https://github.com/yig/halfedge, written by Yotam Gingold.
Definition at line 82 of file HalfEdgeDataStructure.h.
Member Typedef Documentation
Arc
typedef std::pair<VertexIndex, VertexIndex> DGtal::HalfEdgeDataStructure::Arc
An arc is a directed edge from a first vertex to a second vertex.
Definition at line 116 of file HalfEdgeDataStructure.h.
Arc2FaceIndex
typedef std::map< Arc, FaceIndex > DGtal::HalfEdgeDataStructure::Arc2FaceIndex
Definition at line 122 of file HalfEdgeDataStructure.h.
Arc2Index
typedef std::map< Arc, Index > DGtal::HalfEdgeDataStructure::Arc2Index
Definition at line 119 of file HalfEdgeDataStructure.h.
EdgeIndex
typedef Index DGtal::HalfEdgeDataStructure::EdgeIndex
The type for numbering edges.
Definition at line 95 of file HalfEdgeDataStructure.h.
EdgeIndexRange
typedef std::vector<EdgeIndex> DGtal::HalfEdgeDataStructure::EdgeIndexRange
Definition at line 112 of file HalfEdgeDataStructure.h.
FaceIndex
typedef Index DGtal::HalfEdgeDataStructure::FaceIndex
The type for numbering faces.
Definition at line 97 of file HalfEdgeDataStructure.h.
FaceIndexRange
typedef std::vector<FaceIndex> DGtal::HalfEdgeDataStructure::FaceIndexRange
Definition at line 113 of file HalfEdgeDataStructure.h.
HalfEdgeIndex
typedef Index DGtal::HalfEdgeDataStructure::HalfEdgeIndex
The type used for numbering half-edges (alias)
Definition at line 91 of file HalfEdgeDataStructure.h.
HalfEdgeIndexRange
typedef std::vector<HalfEdgeIndex> DGtal::HalfEdgeDataStructure::HalfEdgeIndexRange
Definition at line 110 of file HalfEdgeDataStructure.h.
Index
typedef std::size_t DGtal::HalfEdgeDataStructure::Index
The type used for numbering half-edges (an offset an the half-edges structure).
Definition at line 89 of file HalfEdgeDataStructure.h.
PolygonalFace
typedef std::vector<VertexIndex> DGtal::HalfEdgeDataStructure::PolygonalFace
Defines an arbitrary polygonal face as a vector of vertex indices. To be valid, its size must be at least 3.
Definition at line 182 of file HalfEdgeDataStructure.h.
Size
typedef std::size_t DGtal::HalfEdgeDataStructure::Size
The type for counting elements.
Definition at line 87 of file HalfEdgeDataStructure.h.
VertexIndex
typedef Index DGtal::HalfEdgeDataStructure::VertexIndex
The type for numbering vertices.
Definition at line 93 of file HalfEdgeDataStructure.h.
VertexIndexRange
typedef std::vector<VertexIndex> DGtal::HalfEdgeDataStructure::VertexIndexRange
Definition at line 111 of file HalfEdgeDataStructure.h.
Constructor & Destructor Documentation
HalfEdgeDataStructure()
DGtal::HalfEdgeDataStructure::HalfEdgeDataStructure () inline
Default constructor. The data structure is empty.
See also
build
Definition at line 213 of file HalfEdgeDataStructure.h.
 {}
Member Function Documentation
arc2FaceIndex()
static FaceIndex DGtal::HalfEdgeDataStructure::arc2FaceIndex (const Arc2FaceIndex & de2fi, VertexIndex vi, VertexIndex vj) inline static protected
Definition at line 1413 of file HalfEdgeDataStructure.h.
     {
       ASSERT( !de2fi.empty() );
       Arc2FaceIndex::const_iterator it = de2fi.find( Arc( vi, vj ) );
       // If no such directed edge exists, then there's no such face in the mesh.
       // The edge must be a boundary edge.
       // In this case, the reverse orientation edge must have a face.
       if( it == de2fi.end() )
         {
           ASSERT( de2fi.find( Arc( vj, vi ) ) != de2fi.end() );
           return HALF_EDGE_INVALID_INDEX;
         }
       return it->second;
     }
References DGtal::HALF_EDGE_INVALID_INDEX.
arcFromHalfEdgeIndex()
Arc DGtal::HalfEdgeDataStructure::arcFromHalfEdgeIndex (const Index i) const inline
Parameters
i any valid half-edge index.
Returns
the corresponding directed edge as an arc (v(opp(i)), v(i)).
Definition at line 388 of file HalfEdgeDataStructure.h.
     {
       const HalfEdge& he = myHalfEdges[ i ];
       return std::make_pair( myHalfEdges[ he.opposite ].toVertex, he.toVertex );
     }
References myHalfEdges, DGtal::HalfEdgeDataStructure::HalfEdge::opposite, and DGtal::HalfEdgeDataStructure::HalfEdge::toVertex.
Referenced by boundaryArcs().
boundaryArcs()
std::vector< Arc > DGtal::HalfEdgeDataStructure::boundaryArcs () const inline
Returns
a sequence containing the arcs lying on the boundary.
Note
O(nb half-edges) operation.
no particular order.
Definition at line 566 of file HalfEdgeDataStructure.h.
     {
         std::vector< Arc > result;
         for( Index hei = 0; hei < myHalfEdges.size(); ++hei )
           {
             const HalfEdge& he = halfEdge( hei );
             if( HALF_EDGE_INVALID_INDEX == he.face )
               result.push_back( arcFromHalfEdgeIndex( hei ) );
           }
         return result;
     }
References arcFromHalfEdgeIndex(), DGtal::HalfEdgeDataStructure::HalfEdge::face, DGtal::HALF_EDGE_INVALID_INDEX, halfEdge(), and myHalfEdges.
Referenced by SCENARIO().
boundaryHalfEdgeIndices()
std::vector< Index > DGtal::HalfEdgeDataStructure::boundaryHalfEdgeIndices () const inline
Returns
a sequence containing the indices of half-edges lying on the boundary.
Note
O(nb half-edges) operation.
no particular order.
Definition at line 552 of file HalfEdgeDataStructure.h.
     {
       std::vector< Index > result;
       for( Index hei = 0; hei < myHalfEdges.size(); ++hei )
         {
           const HalfEdge& he = halfEdge( hei );
           if( HALF_EDGE_INVALID_INDEX == he.face )
             result.push_back( hei );
         }
       return result;
     }
References DGtal::HalfEdgeDataStructure::HalfEdge::face, DGtal::HALF_EDGE_INVALID_INDEX, halfEdge(), and myHalfEdges.
boundaryVertices()
VertexIndexRange DGtal::HalfEdgeDataStructure::boundaryVertices () const inline
Returns
a sequence containing the indices of the vertices lying on the boundary.
Note
O(nb half-edges) operation.
no particular order.
Definition at line 536 of file HalfEdgeDataStructure.h.
     {
       VertexIndexRange result;
       // std::set< VertexIndex > result;
       for( Index hei = 0; hei < myHalfEdges.size(); ++hei )
         {
           const HalfEdge& he = halfEdge( hei );
           if( HALF_EDGE_INVALID_INDEX == he.face )
             result.push_back( he.toVertex );
         }
       return result;
     }
References DGtal::HalfEdgeDataStructure::HalfEdge::face, DGtal::HALF_EDGE_INVALID_INDEX, halfEdge(), myHalfEdges, and DGtal::HalfEdgeDataStructure::HalfEdge::toVertex.
Referenced by isValid(), and SCENARIO().
build() [1/4]
bool DGtal::HalfEdgeDataStructure::build (const Size num_vertices, const std::vector< PolygonalFace > & polygonal_faces, const std::vector< Edge > & edges)
Builds the half-edge data structures from the given polygonal faces and edges. It keeps the numbering of vertices given in the input polygonal_faces as well as the numbering of faces in the vector polygonal_faces.
Note
Parameter edges can be computed from polygonal_faces by calling getUnorderedEdgesFromPolygonalFaces() before.
Both polygonal_faces and edges are not needed after the call to build() completes and may be destroyed.
Parameters
[in] num_vertices the number of vertices (one more than the maximal vertex index).
[in] polygonal_faces the vector of input polygonal_faces.
[in] edges the vector of input unoriented edges.
Returns
'true' if everything went well, 'false' if their was error in the given topology (for instance, three triangles sharing an edge).
build() [2/4]
bool DGtal::HalfEdgeDataStructure::build (const Size num_vertices, const std::vector< Triangle > & triangles, const std::vector< Edge > & edges)
Builds the half-edge data structures from the given triangles and edges. It keeps the numbering of vertices given in the input triangles as well as the numbering of triangles in the vector triangles.
Note
Parameter edges can be computed from triangles by calling getUnorderedEdgesFromTriangles() before.
Both triangles and edges are not needed after the call to build() completes and may be destroyed.
Parameters
[in] num_vertices the number of vertices (one more than the maximal vertex index).
[in] triangles the vector of input triangles.
[in] edges the vector of input unoriented edges.
Returns
'true' if everything went well, 'false' if their was error in the given topology (for instance, three triangles sharing an edge).
Referenced by build(), makeBox(), makeCube(), makeOctahedron(), makePyramid(), makeRibbonWithHole(), makeTetrahedron(), makeThreeTriangles(), makeTriangulatedDisk(), and makeTwoTriangles().
build() [3/4]
bool DGtal::HalfEdgeDataStructure::build (const std::vector< PolygonalFace > & polygonal_faces) inline
Builds the half-edge data structure from the given polygonal faces. It keeps the numbering of vertices given in the input polygonal_faces as well as the numbering of faces in the vector polygonal_faces.
Parameters
[in] polygonal_faces the vector of input polygonal faces.
Definition at line 349 of file HalfEdgeDataStructure.h.
     {
       std::vector<Edge> edges;
       const Size nbVtx = getUnorderedEdgesFromPolygonalFaces( polygonal_faces, edges );
       return build( nbVtx, polygonal_faces, edges );
     }
References build(), and getUnorderedEdgesFromPolygonalFaces().
build() [4/4]
bool DGtal::HalfEdgeDataStructure::build (const std::vector< Triangle > & triangles) inline
Builds the half-edge data structure from the given triangles. It keeps the numbering of vertices given in the input triangles as well as the numbering of triangles in the vector triangles.
Parameters
[in] triangles the vector of input triangles.
Definition at line 334 of file HalfEdgeDataStructure.h.
     {
       std::vector<Edge> edges;
       const Size nbVtx = getUnorderedEdgesFromTriangles( triangles, edges );
       return build( nbVtx, triangles, edges );
     }
References build(), and getUnorderedEdgesFromTriangles().
clear()
void DGtal::HalfEdgeDataStructure::clear () inline
Clears the data structure.
Definition at line 357 of file HalfEdgeDataStructure.h.
     {
       myHalfEdges.clear();
       myVertexHalfEdges.clear();
       myFaceHalfEdges.clear();
       myEdgeHalfEdges.clear();
       myArc2Index.clear();
     }
References myArc2Index, myEdgeHalfEdges, myFaceHalfEdges, myHalfEdges, and myVertexHalfEdges.
Euler()
long DGtal::HalfEdgeDataStructure::Euler () const inline
Returns
the euler characteristic of the corresponding combinatorial mesh.
Definition at line 379 of file HalfEdgeDataStructure.h.
     { return (long) nbVertices() - (long) nbEdges() + (long) nbFaces(); }
References nbEdges(), nbFaces(), and nbVertices().
Referenced by DGtal::PolygonalSurface< TPoint >::Euler(), DGtal::TriangulatedSurface< TPoint >::Euler(), and DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::Euler().
findHalfEdgeIndexFromArc() [1/2]
Index DGtal::HalfEdgeDataStructure::findHalfEdgeIndexFromArc (const Arc & arc) const inline
Note
In opposition with halfEdgeIndexFromArc, this method does not use the map myArc2Index to find the half-edge associated with arc (v1,v2), but rather gets an half-edge originating from v1, and turn around to find the one pointing to v2. This method is useful if you do not update myArc2Index when flipping.
Parameters
arc any directed edge (i,j)
Returns
the index of the half-edge from i to j or HALF_EDGE_INVALID_INDEX if not found.
Definition at line 430 of file HalfEdgeDataStructure.h.
     {
       const Index s = halfEdgeIndexFromVertexIndex( arc.first );
       Index       i = s;
       do {
         const HalfEdge& he = myHalfEdges[ i ];
         if ( he.toVertex == arc.second ) return i;
         i = halfEdge( he.opposite ).next;
       } while ( i != s );
       return HALF_EDGE_INVALID_INDEX;
     }
References DGtal::HALF_EDGE_INVALID_INDEX, halfEdge(), halfEdgeIndexFromVertexIndex(), myHalfEdges, DGtal::HalfEdgeDataStructure::HalfEdge::next, DGtal::HalfEdgeDataStructure::HalfEdge::opposite, and DGtal::HalfEdgeDataStructure::HalfEdge::toVertex.
findHalfEdgeIndexFromArc() [2/2]
Index DGtal::HalfEdgeDataStructure::findHalfEdgeIndexFromArc (const VertexIndex i, const VertexIndex j) const inline
Note
In opposition with halfEdgeIndexFromArc, this method does not use the map myArc2Index to find the half-edge associated with arc (v1,v2), but rather gets an half-edge originating from v1, and turn around to find the one pointing to v2. This method is useful if you do not update myArc2Index when flipping.
Parameters
i the vertex index of some vertex.
j the vertex index of some other vertex.
Returns
the index of the half-edge from i to j or HALF_EDGE_INVALID_INDEX if not found.
Definition at line 418 of file HalfEdgeDataStructure.h.
     { return findHalfEdgeIndexFromArc( std::make_pair( i, j ) ); }
Referenced by isValid(), and SCENARIO().
flip()
void DGtal::HalfEdgeDataStructure::flip (const Index hei, bool update_arc2index = true) inline
Tries to flip the edge containing hei.
Parameters
hei any valid half-edge index.
update_arc2index (optimisation parameter), when 'true' updates everything consistently; when 'false' do not update myArc2Index map, which means you cannot get an half edge from two vertices afterwards. Use 'false' only if you know that you never use this mapping (e.g. no call to halfEdgeIndexFromArc)
Precondition
the edge must be flippable, isFlippable(hei) == true
See also
isFlippable
Note
Time complexity is O(1) if update_arc2index is false, otherwise it is O(log n) is n is the number of arcs.
Definition at line 664 of file HalfEdgeDataStructure.h.
     {
       const Index       i1 = hei;
       HalfEdge&        he1 = myHalfEdges[ i1 ];
       const Index       i2 = he1.opposite;
       HalfEdge&        he2 = myHalfEdges[ i2 ];
       const VertexIndex v2 = he1.toVertex;
       const VertexIndex v1 = he2.toVertex;
       const Index  i1_next = he1.next;
       const Index  i2_next = he2.next;
       HalfEdge&   he1_next = myHalfEdges[ i1_next ];
       HalfEdge&   he2_next = myHalfEdges[ i2_next ];
       const Index i1_next2 = he1_next.next;
       const Index i2_next2 = he2_next.next;
       myHalfEdges[ i1_next2 ].next = i2_next;
       myHalfEdges[ i2_next2 ].next = i1_next;
       he2_next.next  = i1;
       he1_next.next  = i2;
       he2_next.face  = he1.face;
       he1_next.face  = he2.face;
       he1.next       = i1_next2;
       he2.next       = i2_next2;
       he1.toVertex   = he1_next.toVertex;
       he2.toVertex   = he2_next.toVertex;
       // Reassign the mapping vertex v -> index of half edge starting from v
       // (JOL): must check before reassign for boundary vertices.
       if ( myVertexHalfEdges[ v1 ] == i1 ) myVertexHalfEdges[ v1 ] = i2_next;
       if ( myVertexHalfEdges[ v2 ] == i2 ) myVertexHalfEdges[ v2 ] = i1_next;
       // Reassign the mapping face f -> index of half edge contained in f
       myFaceHalfEdges[ he1.face ] = i1;
       myFaceHalfEdges[ he2.face ] = i2;
       // No need to reassign edge... it has just changed of vertices
       // but is still based on half-edges i1 and i2
       // Now taking care of mapping (vertex,vertex) -> half-edge.
       if ( update_arc2index )
         {
           myArc2Index.erase( Arc( v1, v2 ) );
           myArc2Index.erase( Arc( v2, v1 ) );
           const VertexIndex v2p = he1.toVertex;
           const VertexIndex v1p = he2.toVertex;
           myArc2Index[ Arc( v1p, v2p ) ] = i1;
           myArc2Index[ Arc( v2p, v1p ) ] = i2;
         }
     }
References DGtal::HalfEdgeDataStructure::HalfEdge::face, myArc2Index, myFaceHalfEdges, myHalfEdges, myVertexHalfEdges, DGtal::HalfEdgeDataStructure::HalfEdge::next, DGtal::HalfEdgeDataStructure::HalfEdge::opposite, and DGtal::HalfEdgeDataStructure::HalfEdge::toVertex.
Referenced by SCENARIO().
getNeighboringFaces()
void DGtal::HalfEdgeDataStructure::getNeighboringFaces (const VertexIndex vi, FaceIndexRange & result) const inline
Parameters
[in] vi any vertex index.
[out] result the sequence of neighboring faces of the given vertex vi .
Definition at line 501 of file HalfEdgeDataStructure.h.
     {
       result.clear();
       const Index start_hei = halfEdgeIndexFromVertexIndex( vi );
       Index hei = start_hei;
       do
         {
           const HalfEdge& he = halfEdge( hei );
           if( HALF_EDGE_INVALID_INDEX != he.face ) result.push_back( he.face );
           hei = halfEdge( he.opposite ).next;
         }
       while ( hei != start_hei );
     }
References DGtal::HalfEdgeDataStructure::HalfEdge::face, DGtal::HALF_EDGE_INVALID_INDEX, halfEdge(), halfEdgeIndexFromVertexIndex(), DGtal::HalfEdgeDataStructure::HalfEdge::next, and DGtal::HalfEdgeDataStructure::HalfEdge::opposite.
Referenced by neighboringFaces().
getNeighboringVertices()
void DGtal::HalfEdgeDataStructure::getNeighboringVertices (const VertexIndex vi, VertexIndexRange & result) const inline
Parameters
[in] vi any vertex index.
[out] result the sequence of vertex neighbors of the given vertex vi (clockwise if triangles were given ccw).
Definition at line 459 of file HalfEdgeDataStructure.h.
     {
       result.clear();
       const Index start_hei = halfEdgeIndexFromVertexIndex( vi );
       Index hei = start_hei;
       do
         {
           const HalfEdge& he = halfEdge( hei );
           result.push_back( he.toVertex );
           hei = halfEdge( he.opposite ).next;
         }
       while ( hei != start_hei );
     }
References halfEdge(), halfEdgeIndexFromVertexIndex(), DGtal::HalfEdgeDataStructure::HalfEdge::next, DGtal::HalfEdgeDataStructure::HalfEdge::opposite, and DGtal::HalfEdgeDataStructure::HalfEdge::toVertex.
Referenced by neighboringVertices(), and SCENARIO().
getUnorderedEdgesFromPolygonalFaces()
static Size DGtal::HalfEdgeDataStructure::getUnorderedEdgesFromPolygonalFaces (const std::vector< PolygonalFace > & polygonal_faces, std::vector< Edge > & edges_out) static
Computes all the unoriented edges of the given polygonal faces.
Note
Method build() needs the unordered edges of the mesh. If you don't have them, call this first.
Parameters
[in] polygonal_faces the vector of input oriented polygonal faces.
[out] edges_out the vector of all the unoriented edges of the given triangles.
Returns
the total number of different vertices (note that the vertex numbering should be between 0 and this number minus one).
Referenced by build().
getUnorderedEdgesFromTriangles()
static Size DGtal::HalfEdgeDataStructure::getUnorderedEdgesFromTriangles (const std::vector< Triangle > & triangles, std::vector< Edge > & edges_out) inline static
Computes all the unoriented edges of the given triangles.
Note
Method build() needs the unordered edges of the mesh. If you don't have them, call this first.
Parameters
[in] triangles the vector of input oriented triangles.
[out] edges_out the vector of all the unoriented edges of the given triangles.
Returns
the total number of different vertices (note that the vertex numbering should be between 0 and this number minus one).
Definition at line 230 of file HalfEdgeDataStructure.h.
     {
       typedef std::set< Edge > EdgeSet;
       typedef std::set< VertexIndex > VertexIndexSet;
       VertexIndexSet vertexSet;
       EdgeSet edgeSet;
       for( const Triangle& T : triangles )
         {
           edgeSet.insert( Edge( T.i(), T.j() ) );
           edgeSet.insert( Edge( T.j(), T.k() ) );
           edgeSet.insert( Edge( T.k(), T.i() ) );
           vertexSet.insert( T.i() );
           vertexSet.insert( T.j() );
           vertexSet.insert( T.k() );
         }
       edges_out.resize( edgeSet.size() );
       Size e = 0;
       for ( const Edge& edge : edgeSet )
         {
           edges_out.at(e) = edge;
           ++e;
         }
       return vertexSet.size();
     }
Referenced by build(), makeRibbonWithHole(), and makeTriangulatedDisk().
halfEdge()
const HalfEdge& DGtal::HalfEdgeDataStructure::halfEdge (const Index i) const inline
Parameters
i any valid half-edge index.
Returns
the half-edge of index i.
Definition at line 384 of file HalfEdgeDataStructure.h.
 { return myHalfEdges.at( i ); }
References myHalfEdges.
Referenced by boundaryArcs(), boundaryHalfEdgeIndices(), boundaryVertices(), findHalfEdgeIndexFromArc(), getNeighboringFaces(), getNeighboringVertices(), isFlippable(), isMergeable(), isValid(), isValidTriangulation(), isVertexBoundary(), merge(), nbNeighboringVertices(), nbSides(), renumberHalfEdge(), renumberVertex(), and verticesOfFace().
halfEdgeIndexFromArc() [1/2]
Index DGtal::HalfEdgeDataStructure::halfEdgeIndexFromArc (const Arc & arc) const inline
Parameters
arc any directed edge (i,j)
Returns
the index of the half-edge from i to j or HALF_EDGE_INVALID_INDEX if not found.
Definition at line 402 of file HalfEdgeDataStructure.h.
     {
       auto result = myArc2Index.find( arc );
       return ( result == myArc2Index.end() ) ? HALF_EDGE_INVALID_INDEX : result->second;
     }
References DGtal::HALF_EDGE_INVALID_INDEX, and myArc2Index.
halfEdgeIndexFromArc() [2/2]
Index DGtal::HalfEdgeDataStructure::halfEdgeIndexFromArc (const VertexIndex i, const VertexIndex j) const inline
Parameters
i the vertex index of some vertex.
j the vertex index of some other vertex.
Returns
the index of the half-edge from i to j or HALF_EDGE_INVALID_INDEX if not found.
Definition at line 397 of file HalfEdgeDataStructure.h.
     { return halfEdgeIndexFromArc( std::make_pair( i, j ) ); }
Referenced by SCENARIO().
halfEdgeIndexFromEdgeIndex()
Index DGtal::HalfEdgeDataStructure::halfEdgeIndexFromEdgeIndex (const EdgeIndex ei) const inline
Parameters
[in] ei any edge index.
Returns
the index of an half-edge that borders the edge ei.
Definition at line 454 of file HalfEdgeDataStructure.h.
     { return myEdgeHalfEdges[ ei ]; }
References myEdgeHalfEdges.
Referenced by SCENARIO().
halfEdgeIndexFromFaceIndex()
Index DGtal::HalfEdgeDataStructure::halfEdgeIndexFromFaceIndex (const FaceIndex fi) const inline
Parameters
[in] fi any face index.
Returns
the index of an half-edge that borders the face fi.
Definition at line 449 of file HalfEdgeDataStructure.h.
     { return myFaceHalfEdges[ fi ]; }
References myFaceHalfEdges.
Referenced by nbSidesOfFace(), and verticesOfFace().
halfEdgeIndexFromVertexIndex()
Index DGtal::HalfEdgeDataStructure::halfEdgeIndexFromVertexIndex (const VertexIndex vi) const inline
Parameters
[in] vi any vertex index.
Returns
the index of an half-edge originating from vi.
Definition at line 444 of file HalfEdgeDataStructure.h.
     { return myVertexHalfEdges[ vi ]; }
References myVertexHalfEdges.
Referenced by findHalfEdgeIndexFromArc(), getNeighboringFaces(), getNeighboringVertices(), isValid(), and nbNeighboringVertices().
isFlippable()
bool DGtal::HalfEdgeDataStructure::isFlippable (const Index hei) const inline
An edge is (topologically) flippable iff: (1) it does not lie on the boundary, (2) it is bordered by two triangles, (3) the two other vertices of the quad are not already neighbors.
Parameters
hei any valid half-edge index.
Returns
'true' if the edge containing hei is topologically flippable.
Note
Time complexity is O(1).
Definition at line 628 of file HalfEdgeDataStructure.h.
     {
       ASSERT( hei != HALF_EDGE_INVALID_INDEX );
       const HalfEdge&   he = halfEdge( hei );
       const Index     hei2 = he.opposite;
       const HalfEdge&  he2 = halfEdge( hei2 );
       // check if hei borders an infinite face.
       if ( he.face  == HALF_EDGE_INVALID_INDEX ) return false;
       // check if hei2 borders an infinite face.
       if ( he2.face == HALF_EDGE_INVALID_INDEX ) return false;
       // Checks that he1 and he2 border a triangle.
       if ( ( nbSides( hei ) != 3 ) || ( nbSides( hei2 ) != 3 ) ) return false;
       // Checks that the two other vertices of the two surrounding
       // triangles are not already neighbors
       const VertexIndex v1 = halfEdge( he.next  ).toVertex;
       const VertexIndex v2 = halfEdge( he2.next ).toVertex;
       const auto neighb_v1 = neighboringVertices( v1 );
       const auto     it_v2 = std::find( neighb_v1.cbegin(), neighb_v1.cend(), v2 );
       return it_v2 == neighb_v1.cend();
     }
References DGtal::HalfEdgeDataStructure::HalfEdge::face, DGtal::HALF_EDGE_INVALID_INDEX, halfEdge(), nbSides(), neighboringVertices(), DGtal::HalfEdgeDataStructure::HalfEdge::next, DGtal::HalfEdgeDataStructure::HalfEdge::opposite, and DGtal::HalfEdgeDataStructure::HalfEdge::toVertex.
Referenced by SCENARIO().
isMergeable()
bool DGtal::HalfEdgeDataStructure::isMergeable (const Index hei) const inline
An edge is (topologically) mergeable iff: (1) it is bordered by two triangles, (2) there is no boundary vertex in the two triangles bordering the edge.
Parameters
hei any valid half-edge index.
Returns
'true' if the edge containing hei is topologically mergeable.
Note
Time complexity is O(1).
Definition at line 827 of file HalfEdgeDataStructure.h.
{
       ASSERT( hei != HALF_EDGE_INVALID_INDEX );
       const HalfEdge&  he = halfEdge( hei );
       const Index    hei2 = he.opposite;
       const HalfEdge& he2 = halfEdge( hei2 );
       // check if hei borders an infinite face.
       if ( ( he.face == HALF_EDGE_INVALID_INDEX )
            || ( he2.face == HALF_EDGE_INVALID_INDEX ) )
         return false;
       // Checks that he1 and he2 border a triangle.
       if ( ( nbSides( hei ) != 3 ) || ( nbSides( hei2 ) != 3) )
         return false;
       // Checks that no vertices around lie on the boundary.
       return ( ! isVertexBoundary( he.toVertex ) )
         &&   ( ! isVertexBoundary( he2.toVertex ) )
         &&   ( ! isVertexBoundary( halfEdge( he.next ).toVertex ) )
         &&   ( ! isVertexBoundary( halfEdge( he2.next ).toVertex ) );
     }
References DGtal::HalfEdgeDataStructure::HalfEdge::face, DGtal::HALF_EDGE_INVALID_INDEX, halfEdge(), isVertexBoundary(), nbSides(), DGtal::HalfEdgeDataStructure::HalfEdge::next, DGtal::HalfEdgeDataStructure::HalfEdge::opposite, and DGtal::HalfEdgeDataStructure::HalfEdge::toVertex.
Referenced by SCENARIO().
isValid()
bool DGtal::HalfEdgeDataStructure::isValid (bool check_arc2index = true) const inline
Checks the whole half-edge structure for consistency. Complexity is at O(n log n) if n in the number of half-edges.
Parameters
check_arc2index (optimisation parameter), when 'true' checks everything, otherwise does not check that the mapping myArc2Index is correct. This is used in conjunction with flip method when using the optimisation.
Returns
'true' iff all checks have passed.
See also
flip
Definition at line 1109 of file HalfEdgeDataStructure.h.
     {
       bool ok = true;
       // Checks that indices are within range
       for ( Index i = 0; i < nbHalfEdges(); i++ )
         {
           const HalfEdge& he = myHalfEdges[ i ];
           if ( he.next >= nbHalfEdges() ) {
             trace.warning() << "[HalfEdgeDataStructure::isValid] "
                             << "half-edge " << i
                             << " has invalid next half-edge " << he.next
                             << std::endl;
             ok = false;
           }
           if ( he.opposite >= nbHalfEdges() ) {
             trace.warning() << "[HalfEdgeDataStructure::isValid] "
                             << "half-edge " << i
                             << " has invalid opposite half-edge " << he.opposite
                             << std::endl;
             ok = false;
           }
           if ( he.toVertex >= nbVertices() ) {
             trace.warning() << "[HalfEdgeDataStructure::isValid] "
                             << "half-edge " << i
                             << " has invalid toVertex " << he.toVertex
                             << std::endl;
             ok = false;
           }
           if ( he.face >= nbFaces() && he.face != HALF_EDGE_INVALID_INDEX ) {
             trace.warning() << "[HalfEdgeDataStructure::isValid] "
                             << "half-edge " << i
                             << " has invalid face " << he.face
                             << std::endl;
             ok = false;
           }
         }
       // Checks that opposite are correct
       for ( Index i = 0; i < nbHalfEdges(); i++ )
         {
           const Index j = myHalfEdges[ i ].opposite;
           if ( j == HALF_EDGE_INVALID_INDEX ) {
             trace.warning() << "[HalfEdgeDataStructure::isValid] "
                             << "half-edge " << i << " has invalid opposite half-edge." << std::endl;
             ok = false;
           }
           if ( myHalfEdges[ j ].opposite != i ) {
             trace.warning() << "[HalfEdgeDataStructure::isValid] "
                             << "half-edge " << i << " has opposite half-edge " << j
                             << " but the latter has opposite half-edge " << myHalfEdges[ j ].opposite << std::endl;
             ok = false;
           }
           const VertexIndex vi = myHalfEdges[ i ].toVertex;
           const VertexIndex vj = myHalfEdges[ j ].toVertex;
           if ( vi == vj ) {
             trace.warning() << "[HalfEdgeDataStructure::isValid] "
                             << "half-edge " << i << " and its opposite half-edge " << j
                             << " have the same toVertex " << vi << std::endl;
             ok = false;
           }
           if ( vi >= nbVertices()  ) {
             trace.warning() << "[HalfEdgeDataStructure::isValid] "
                             << "half-edge " << i
                             << " points to an invalid vertex " << vi << std::endl;
             ok = false;
           }
           if ( vj >= nbVertices()  ) {
             trace.warning() << "[HalfEdgeDataStructure::isValid] "
                             << "opposite half-edge " << j
                             << " points to an invalid vertex " << vj << std::endl;
             ok = false;
           }
         }
       // Checks that vertices have a correct starting half-edge.
       for ( VertexIndex i = 0; i < nbVertices(); i++ )
         {
           const Index        j = myVertexHalfEdges[ i ];
           const Index     jopp = myHalfEdges[ j ].opposite;
           const VertexIndex ip = myHalfEdges[ jopp ].toVertex;
           if ( ip != i ) {
             trace.warning() << "[HalfEdgeDataStructure::isValid] "
                             << "vertex " << i << " is associated to half-edge " << j
                             << " but its opposite half-edge " << jopp << " points to vertex " << ip << std::endl;
             ok = false;
           }
         }
       // Checks that faces have a correct bordering half-edge.
       for ( FaceIndex f = 0; f < nbFaces(); f++ )
         {
           const Index        i = myFaceHalfEdges[ f ];
           if ( myHalfEdges[ i ].face != f ) {
             trace.warning() << "[HalfEdgeDataStructure::isValid] "
                             << "face " << f << " is associated to half-edge " << i
                             << " but its associated face is " << myHalfEdges[ i ].face << std::endl;
             ok = false;
           }
         }
       // Checks that following next half-edges turns around the same face.
       for ( FaceIndex f = 0; f < nbFaces(); f++ )
         {
           Index           i = myFaceHalfEdges[ f ];
           const Index start = i;
           do {
             const HalfEdge& he = halfEdge( i );
             if ( he.face != f ) {
               trace.warning() << "[HalfEdgeDataStructure::isValid] "
                               << "when turning around face " << f << ", half-edge " << i
                               << " is associated to face " << he.face << std::endl;
               ok = false;
             }
             i = he.next;
           }
           while ( i != start );
         }
       // Checks that turning around a vertex gives half-edges associated to this vertex.
       for ( VertexIndex v = 0; v < nbVertices(); v++ )
         {
           const Index s = halfEdgeIndexFromVertexIndex( v );
           Index       i = s;
           do
             {
               const HalfEdge&  he = halfEdge( i );
               const VertexIndex w = halfEdge( he.opposite ).toVertex;
               if ( v != w ) {
                 trace.warning() << "[HalfEdgeDataStructure::isValid] "
                                 << "when turning around vertex " << v << ", some opposite half-edge "
                                 << he.opposite << " points to " << w << std::endl;
                 ok = false;
               }
               i = halfEdge( he.opposite ).next;
             }
           while ( i != s );
         }
       // Checks that boundary vertices have specific associated half-edges.
       VertexIndexRange bdryV = boundaryVertices();
       for ( VertexIndex i : bdryV ) {
         const Index j = myVertexHalfEdges[ i ];
         if ( halfEdge( j ).face != HALF_EDGE_INVALID_INDEX ) {
           trace.warning() << "[HalfEdgeDataStructure::isValid] "
                           << "boundary vertex " << i << " is associated to the half-edge " << j
                           << " that does not lie on the boundary but on face " << halfEdge( j ).face
                           << std::endl;
           ok = false;
         }
       }
       // Checks that that we can find arcs.
       for ( Index i = 0; i < nbHalfEdges(); i++ ) {
         const HalfEdge&   he = halfEdge( i );
         const VertexIndex v2 = he.toVertex;
         const VertexIndex v1 = halfEdge( he.opposite ).toVertex;
         const Index        j = findHalfEdgeIndexFromArc( v1, v2 );
         const HalfEdge&  he2 = halfEdge( j );
         if ( he2.toVertex != v2 ) {
           trace.warning() << "[HalfEdgeDataStructure::isValid] "
                           << "arc (" << v1 << "," << v2 << ") was found to be half-edge " << j
                           << " but it should be half-edge " << i << std::endl;
           ok = false;
         }
       }
       // Checks that edges have two correct associated half-edges.
       for ( EdgeIndex ei = 0; ei < nbEdges(); ei++ ) {
         const Index        i = myEdgeHalfEdges[ ei ];
         const HalfEdge&  hei = halfEdge( i );
         const Index        j = hei.opposite;
         const HalfEdge&  hej = halfEdge( j );
         if ( hei.edge != ei ) {
           trace.warning() << "[HalfEdgeDataStructure::isValid] "
                           << "edge " << ei << " is associated to half-edge " << i
                           << " but its edge is " << hei.edge << std::endl;
           ok = false;
         }
         if ( hej.edge != ei ) {
           trace.warning() << "[HalfEdgeDataStructure::isValid] "
                           << "edge " << ei << " is associated to half-edge " << i
                           << " of opposite half-edge " << j
                           << " but its edge is " << hej.edge << std::endl;
           ok = false;
         }
       }
       // Checks that arcs have a correct associated half-edge.
       if ( check_arc2index )
         {
           for ( auto arc2idx : myArc2Index )
             {
               const VertexIndex v1 = arc2idx.first.first;
               const VertexIndex v2 = arc2idx.first.second;
               const Index        i = arc2idx.second;
               if ( myHalfEdges[ i ].toVertex != v2 ) {
                 trace.warning() << "[HalfEdgeDataStructure::isValid] "
                                 << "arc (" << v1 << "," << v2 << ") is associated to half-edge " << i
                                 << " but it points to vertex " << myHalfEdges[ i ].toVertex << std::endl;
                 ok = false;
               }
               const Index       i2 = myHalfEdges[ i ].opposite;
               if ( myHalfEdges[ i2 ].toVertex != v1 ) {
                 trace.warning() << "[HalfEdgeDataStructure::isValid] "
                                 << "arc (" << v1 << "," << v2 << ") is associated to half-edge " << i
                                 << " but its opposite half-edge " << i2 << " points to vertex " << myHalfEdges[ i2 ].toVertex
                                 << std::endl;
                 ok = false;
               }
             }
         }
       return ok;
     }
References boundaryVertices(), DGtal::HalfEdgeDataStructure::HalfEdge::edge, DGtal::HalfEdgeDataStructure::HalfEdge::face, findHalfEdgeIndexFromArc(), DGtal::HALF_EDGE_INVALID_INDEX, halfEdge(), halfEdgeIndexFromVertexIndex(), myArc2Index, myEdgeHalfEdges, myFaceHalfEdges, myHalfEdges, myVertexHalfEdges, nbEdges(), nbFaces(), nbHalfEdges(), nbVertices(), DGtal::HalfEdgeDataStructure::HalfEdge::next, DGtal::HalfEdgeDataStructure::HalfEdge::opposite, DGtal::HalfEdgeDataStructure::HalfEdge::toVertex, DGtal::trace, and DGtal::Trace::warning().
Referenced by SCENARIO().
isValidTriangulation()
bool DGtal::HalfEdgeDataStructure::isValidTriangulation () const inline
Specific checks that are meaningful only for a triangulation (i.e. faces have three vertices).
Returns
'true' if all checks have passed.
Definition at line 1322 of file HalfEdgeDataStructure.h.
     {
       bool ok = true;
       // Checks that indices are within range
       // Checks that following next half-edges turns around the same face.
       for ( FaceIndex f = 0; f < nbFaces(); f++ )
         {
           Index           i = myFaceHalfEdges[ f ];
           const Index start = i;
           int           nbv = 0;
           std::set<VertexIndex> V;
           std::set<EdgeIndex>   E;
           do {
             const HalfEdge& he = halfEdge( i );
             if ( he.face != f ) {
               trace.warning() << "[HalfEdgeDataStructure::isValidTriangulation] "
                               << "when turning around face " << f
                               << ", half-edge " << i
                               << " is associated to face " << he.face
                               << std::endl;
               ok = false;
             }
             V.insert( he.toVertex );
             E.insert( he.edge );
             nbv++;
             i = he.next;
           }
           while ( i != start );
           if ( nbv != 3 ) {
             trace.warning() << "[HalfEdgeDataStructure::isValidTriangulation] "
                             << "when turning around face " << f
                             << ", we had to visit " << nbv
                             << " half-edges to loop (instead of 3)" << std::endl;
             ok = false;
           }
           if ( V.size() != 3 ) {
             trace.warning() << "[HalfEdgeDataStructure::isValidTriangulation] "
                             << "when turning around face " << f
                             << ", the set of vertices has not a size 3:";
             for ( auto v : V ) trace.warning() << " " << v;
             trace.warning() << std::endl;
             ok = false;
           }
           if ( E.size() != 3 ) {
             trace.warning() << "[HalfEdgeDataStructure::isValidTriangulation] "
                             << "when turning around face " << f
                             << ", the set of edges has not a size 3:";
             for ( auto e : E ) trace.warning() << " " << e;
             trace.warning() << std::endl;
             ok = false;
           }
         }
       return ok;
     }
References DGtal::HalfEdgeDataStructure::HalfEdge::edge, DGtal::HalfEdgeDataStructure::HalfEdge::face, halfEdge(), myFaceHalfEdges, nbFaces(), DGtal::HalfEdgeDataStructure::HalfEdge::next, DGtal::HalfEdgeDataStructure::HalfEdge::toVertex, DGtal::trace, and DGtal::Trace::warning().
Referenced by SCENARIO().
isVertexBoundary()
bool DGtal::HalfEdgeDataStructure::isVertexBoundary (const VertexIndex vi) const inline
Parameters
[in] vi any vertex index.
Returns
true if and only if the vertex vi lies on the boundary.
Definition at line 526 of file HalfEdgeDataStructure.h.
     {
       return HALF_EDGE_INVALID_INDEX == halfEdge( myVertexHalfEdges[ vi ] ).face;
     }
References DGtal::HalfEdgeDataStructure::HalfEdge::face, DGtal::HALF_EDGE_INVALID_INDEX, halfEdge(), and myVertexHalfEdges.
Referenced by isMergeable().
merge()
VertexIndex DGtal::HalfEdgeDataStructure::merge (const Index hei, bool update_arc2index = true) inline
Merges the edge specified by the half-edge hei.
Parameters
hei any valid half-edge index.
update_arc2index (optimisation parameter), when 'true' updates everything consistently; when 'false' do not update myArc2Index map, which means you cannot get an half edge from two vertices afterwards. Use 'false' only if you know that you never use this mapping (e.g. no call to halfEdgeIndexFromArc)
Returns
the index of the merged vertex.
Precondition
the edge must be mergeable, isMergeable(hei) == true
See also
isMergeable
Note
Time complexity is O(1) if update_arc2index is false, otherwise it is O(log n) is n is the number of arcs.
Todo:
We could also merge boundary triangles or more general faces.
Definition at line 865 of file HalfEdgeDataStructure.h.
{
       const Index       i1 = hei;             // arc (v1,v2)
       const HalfEdge&  he1 = halfEdge( i1 );
       const Index      i1n = he1.next;
       const HalfEdge& he1n = halfEdge( i1n );
       const Index     i1nn = he1n.next;
       const Index       i2 = he1.opposite;    // arc (v2,v1)
       const HalfEdge&  he2 = halfEdge( i2 );
       const Index      i2n = he2.next;
       const HalfEdge& he2n = halfEdge( i2n );
       const Index     i2nn = he2n.next;
       const Index  iext1nn = halfEdge( i1nn ).opposite;
       const Index   iext1n = halfEdge( i1n  ).opposite;
       const Index  iext2nn = halfEdge( i2nn ).opposite;
       const Index   iext2n = halfEdge( i2n  ).opposite;
       const VertexIndex v1 = he2.toVertex;
       // Storing v2 the deleted vertex.
       const VertexIndex v2 = he1.toVertex;
       const VertexIndex v3 = he1n.toVertex;
       const VertexIndex v4 = he2n.toVertex;
       // Storing deleted face indices f1 and f2
       const FaceIndex   f1 = he1.face;
       const FaceIndex   f2 = he2.face;
       // Storing deleted edge indices (v1,v2), (v2,v3) and (v2,v3').
       const EdgeIndex   e1 = he1.edge;
       const EdgeIndex   e2 = he1n.edge;
       const EdgeIndex   e3 = halfEdge( i2nn ).edge;
       const EdgeIndex ev13 = halfEdge( iext1nn ).edge;
       const EdgeIndex ev14 = halfEdge( iext2n ).edge;
       // For debug
       int nbV1 = nbNeighboringVertices( v1 );
       int nbV2 = nbNeighboringVertices( v2 );
       int nbV3 = nbNeighboringVertices( v3 );
       int nbV4 = nbNeighboringVertices( v4 );
       // Changes toVertex field of half-edges pointing to v2
       std::vector<VertexIndex> outer_v;  // stores vertices around v2
       std::vector<Index>       inner_he; // stores half-edges from v2
       std::vector<Index>       outer_he; // stores half-edges toward v2
       Index i = i1n;
       do {
         const HalfEdge& he = halfEdge( i );
         const Index   iopp = he.opposite;
         outer_v. push_back( he.toVertex );
         inner_he.push_back( i );
         outer_he.push_back( iopp );
         HalfEdge&    heopp = myHalfEdges[ iopp ];
         ASSERT( heopp.toVertex == v2 );
         heopp.toVertex = v1;
         i = heopp.next;
       } while ( i != i1n ); // i2 precedes i1n around the vertex v2.
       // std::cout << "#outer_v=" << outer_v.size() << std::endl;
       // Gluing arcs around the two triangles
       // std::cout << "Gluing arcs around the two triangles" << std::endl;
       myHalfEdges[ iext1nn ].opposite = iext1n;
       myHalfEdges[ iext1n  ].opposite = iext1nn;
       myHalfEdges[ iext2nn ].opposite = iext2n;
       myHalfEdges[ iext2n  ].opposite = iext2nn;
       // Changing edges of merged edges
       // std::cout << "Changing edges of merged edges" << std::endl;
       myHalfEdges[ iext1n  ].edge     = ev13;
       myHalfEdges[ iext2nn ].edge     = ev14;
       // Taking care of look-up tables.
       // (1) myVertexHalfEdges
       // std::cout << "(1) myVertexHalfEdges" << std::endl;
       myVertexHalfEdges[ v1 ] = iext1nn;
       if ( myVertexHalfEdges[ v3 ] == i1nn )
         myVertexHalfEdges[ v3 ] = iext1n;
       if ( myVertexHalfEdges[ v4 ] == i2nn )
         myVertexHalfEdges[ v4 ] = iext2n;
       // (2) myFaceHalfEdges -> nothing to do.
       // (3) myEdgeHalfEdges
       // std::cout << "(3) myEdgeHalfEdges" << std::endl;
       myEdgeHalfEdges[ ev13 ] = iext1nn;
       myEdgeHalfEdges[ ev14 ] = iext2n;
       // (4) myArc2Index only if asked
       if ( update_arc2index ) {
         for ( std::size_t j = 0; j < outer_v.size(); ++j ) {
           myArc2Index.erase( Arc( v2, outer_v[ j ] ) );
           myArc2Index.erase( Arc( outer_v[ j ], v2 ) );
         }
         for ( std::size_t j = 1; j < ( outer_v.size() - 2 ); ++j ) {
           myArc2Index[ Arc( v1, outer_v[ j ] ) ] = inner_he[ j ];
           myArc2Index[ Arc( outer_v[ j ], v1 ) ] = outer_he[ j ];
         }
         myArc2Index[ Arc( v3, v1 ) ] = iext1n;
         myArc2Index[ Arc( v1, v4 ) ] = iext2nn;
       }
       // Debug
       int new_nbV1 = nbNeighboringVertices( v1 );
       int new_nbV3 = nbNeighboringVertices( v3 );
       int new_nbV4 = nbNeighboringVertices( v4 );
       if ( ( new_nbV1 != nbV1+nbV2-4 )
            || ( new_nbV3 != nbV3 -1 )
            || ( new_nbV4 != nbV4 -1 ) )
         trace.warning() << "Invalid nb of neighbors: "
                         << " nbV1=" << nbV1
                         << " nbV2=" << nbV2
                         << " nbV3=" << nbV3
                         << " nbV4=" << nbV4 << std::endl
                         << " new_nbV1=" << new_nbV1
                         << " new_nbV3=" << new_nbV3
                         << " new_nbV4=" << new_nbV4 << std::endl;
       // Renumbering of 1 vertex, 3 edges, 2 faces, 6 half-edges
       renumberVertex( v2, update_arc2index );
       std::array< EdgeIndex, 3 > E = { e1, e2, e3 };
       std::sort( E.begin(), E.end(), std::greater<EdgeIndex>() );
       for ( Index e : E ) {
         renumberEdge( e );
       }
       std::array< FaceIndex, 2 > F = { f1, f2 };
       std::sort( F.begin(), F.end(), std::greater<FaceIndex>() );
       for ( Index f : F ) {
         renumberFace( f );
       }
       std::array< Index, 6 > T = { i1, i1n, i1nn, i2, i2n, i2nn };
       std::sort( T.begin(), T.end(), std::greater<Index>() );
       for ( Index t : T ) {
         renumberHalfEdge( t );
       }
       return v1;
     }
References DGtal::HalfEdgeDataStructure::HalfEdge::edge, DGtal::HalfEdgeDataStructure::HalfEdge::face, halfEdge(), myArc2Index, myEdgeHalfEdges, myHalfEdges, myVertexHalfEdges, nbNeighboringVertices(), DGtal::HalfEdgeDataStructure::HalfEdge::next, DGtal::HalfEdgeDataStructure::HalfEdge::opposite, renumberEdge(), renumberFace(), renumberHalfEdge(), renumberVertex(), DGtal::HalfEdgeDataStructure::HalfEdge::toVertex, DGtal::trace, and DGtal::Trace::warning().
Referenced by SCENARIO().
nbEdges()
Size DGtal::HalfEdgeDataStructure::nbEdges () const inline
Returns
the number of unoriented edges in the structure.
Definition at line 373 of file HalfEdgeDataStructure.h.
 { return myEdgeHalfEdges.size(); }
References myEdgeHalfEdges.
Referenced by Euler(), isValid(), DGtal::PolygonalSurface< TPoint >::nbEdges(), DGtal::TriangulatedSurface< TPoint >::nbEdges(), DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::nbEdges(), renumberEdge(), and SCENARIO().
nbFaces()
Size DGtal::HalfEdgeDataStructure::nbFaces () const inline
Returns
the number of faces in the structure.
Definition at line 376 of file HalfEdgeDataStructure.h.
 { return myFaceHalfEdges.size(); }
References myFaceHalfEdges.
Referenced by Euler(), isValid(), isValidTriangulation(), DGtal::PolygonalSurface< TPoint >::nbFaces(), DGtal::TriangulatedSurface< TPoint >::nbFaces(), DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::nbFaces(), renumberFace(), and SCENARIO().
nbHalfEdges()
Size DGtal::HalfEdgeDataStructure::nbHalfEdges () const inline
Returns
the number of half edges in the structure.
Definition at line 367 of file HalfEdgeDataStructure.h.
 { return myHalfEdges.size(); }
References myHalfEdges.
Referenced by isValid(), DGtal::PolygonalSurface< TPoint >::nbArcs(), DGtal::TriangulatedSurface< TPoint >::nbArcs(), DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::nbArcs(), renumberHalfEdge(), and SCENARIO().
nbNeighboringVertices()
Size DGtal::HalfEdgeDataStructure::nbNeighboringVertices (const Index vi) const inline
Parameters
[in] vi any vertex index.
Returns
the number of vertex neighbors to vi.
Definition at line 484 of file HalfEdgeDataStructure.h.
     {
       Size nb = 0;
       const Index start_hei = halfEdgeIndexFromVertexIndex( vi );
       Index hei = start_hei;
       do
         {
           const HalfEdge& he = halfEdge( hei );
           nb++;
           hei = halfEdge( he.opposite ).next;
         }
       while ( hei != start_hei );
       return nb;
     }
References halfEdge(), halfEdgeIndexFromVertexIndex(), DGtal::HalfEdgeDataStructure::HalfEdge::next, and DGtal::HalfEdgeDataStructure::HalfEdge::opposite.
Referenced by merge().
nbSides()
Size DGtal::HalfEdgeDataStructure::nbSides (Index hei) const inline
Parameters
hei any valid half-edge index.
Returns
the number of sides of the face that contains the half-edge hei.
Definition at line 580 of file HalfEdgeDataStructure.h.
     {
        ASSERT( hei != HALF_EDGE_INVALID_INDEX );
        Size nb = 0;
        const Index start = hei;
        do {
          hei = halfEdge( hei ).next;
          nb++;
        }
        while ( hei != start );
        return nb;
     }
References DGtal::HALF_EDGE_INVALID_INDEX, halfEdge(), and DGtal::HalfEdgeDataStructure::HalfEdge::next.
Referenced by isFlippable(), isMergeable(), and nbSidesOfFace().
nbSidesOfFace()
Size DGtal::HalfEdgeDataStructure::nbSidesOfFace (const FaceIndex f) const inline
Parameters
f any valid face index.
Returns
the number of sides of the face f.
Definition at line 595 of file HalfEdgeDataStructure.h.
     {
       return nbSides( halfEdgeIndexFromFaceIndex( f ) );
     }
References halfEdgeIndexFromFaceIndex(), and nbSides().
nbVertices()
Size DGtal::HalfEdgeDataStructure::nbVertices () const inline
Returns
the number of vertices in the structure.
Definition at line 370 of file HalfEdgeDataStructure.h.
 { return myVertexHalfEdges.size(); }
References myVertexHalfEdges.
Referenced by Euler(), isValid(), DGtal::PolygonalSurface< TPoint >::nbVertices(), DGtal::TriangulatedSurface< TPoint >::nbVertices(), DGtal::IndexedDigitalSurface< TDigitalSurfaceContainer >::nbVertices(), renumberVertex(), and SCENARIO().
neighboringFaces()
FaceIndexRange DGtal::HalfEdgeDataStructure::neighboringFaces (const VertexIndex vi) const inline
Parameters
[in] vi any vertex index.
Returns
the sequence of neighboring faces of the given vertex vi .
Definition at line 517 of file HalfEdgeDataStructure.h.
     {
       FaceIndexRange result;
       getNeighboringFaces( vi, result );
       return result;
     }
References getNeighboringFaces().
neighboringVertices()
VertexIndexRange DGtal::HalfEdgeDataStructure::neighboringVertices (const VertexIndex vi) const inline
Parameters
[in] vi any vertex index.
Returns
the sequence of vertex neighbors of the given vertex vi (clockwise if triangles were given ccw).
Definition at line 475 of file HalfEdgeDataStructure.h.
     {
       VertexIndexRange result;
       getNeighboringVertices( vi, result );
       return result;
     }
References getNeighboringVertices().
Referenced by isFlippable(), and SCENARIO().
renumberEdge()
void DGtal::HalfEdgeDataStructure::renumberEdge (const EdgeIndex ei) inline protected
Renumber the last edge of the triangulated surface as edge ei (this replaces it). The number of edges of the data structure is decreased by 1.
Definition at line 1023 of file HalfEdgeDataStructure.h.
{
       const EdgeIndex     ej = nbEdges() - 1;
       if ( ei != ej ) {
         const Index    j = myEdgeHalfEdges[ ej ];
         HalfEdge&    hej = myHalfEdges[ j ];
         const Index jopp = hej.opposite;
         HalfEdge& hejopp = myHalfEdges[ jopp ];
         ASSERT( hej.edge == ej );
         ASSERT( hejopp.edge == ej );
         hej.edge    = ei;
         hejopp.edge = ei;
         myEdgeHalfEdges[ ei ]  = j;
       }
       myEdgeHalfEdges.pop_back();
     }
References DGtal::HalfEdgeDataStructure::HalfEdge::edge, myEdgeHalfEdges, myHalfEdges, nbEdges(), and DGtal::HalfEdgeDataStructure::HalfEdge::opposite.
Referenced by merge().
renumberFace()
void DGtal::HalfEdgeDataStructure::renumberFace (const FaceIndex fi) inline protected
Renumber the last face of the triangulated surface as face fi (this replaces it). The number of faces of the data structure is decreased by 1.
Definition at line 1042 of file HalfEdgeDataStructure.h.
{
       const FaceIndex     fj = nbFaces() - 1;
       if ( fi != fj ) {
         const Index          j = myFaceHalfEdges[ fj ];
         Index k = j;
         do {
           HalfEdge&    hek = myHalfEdges[ k ];
           ASSERT( hek.face == fj );
           hek.face         = fi;
           k = hek.next;
         } while ( k != j );
         myFaceHalfEdges[ fi ] = j;
       }
       myFaceHalfEdges.pop_back();
     }
References DGtal::HalfEdgeDataStructure::HalfEdge::face, myFaceHalfEdges, myHalfEdges, nbFaces(), and DGtal::HalfEdgeDataStructure::HalfEdge::next.
Referenced by merge().
renumberHalfEdge()
void DGtal::HalfEdgeDataStructure::renumberHalfEdge (const Index i, bool update_arc2index = true) inline protected
Renumber the last half-edge of the triangulated surface as half-edge i (this replaces it). The number of half-edges of the data structure is decreased by 1.
Definition at line 1061 of file HalfEdgeDataStructure.h.
{
       const Index          j = nbHalfEdges() - 1;
       if ( i != j ) {
         // std::cout << "renumberHalfEdge j=" << j  << std::endl;
         const HalfEdge&    hej = halfEdge( j );
         const Index       jopp = hej.opposite;
         // std::cout << "renumberHalfEdge jopp=" << jopp << std::endl;
         HalfEdge&       hejopp = myHalfEdges[ jopp ];
         const VertexIndex   vj = hejopp.toVertex; // hej corresponds to (vj,vk)
         const VertexIndex   vk = hej.toVertex;    // hejopp corresponds to (vk,vj)
         // Update opposite and previous
         Index k = hej.next;
         while ( halfEdge( k ).next != j ) k = halfEdge( k ).next;
         myHalfEdges[ k ].next = i;
         hejopp.opposite       = i;
         // Take care of look-up tables
         // std::cout << "myVertexHalfEdges[" << vj << "]" << std::endl;
         if ( myVertexHalfEdges[ vj ] == j )
           myVertexHalfEdges[ vj ] = i;
         // std::cout << "myEdgeHalfEdges[" << hej.edge << "]" << std::endl;
         if ( myEdgeHalfEdges[ hej.edge ] == j )
           myEdgeHalfEdges[ hej.edge ] = i;
         // std::cout << "myFaceHalfEdges[" << hej.face << "]" << std::endl;
         if ( myFaceHalfEdges[ hej.face ] == j )
           myFaceHalfEdges[ hej.face ] = i;
         // std::cout << "myArc2Index[" << vj << "," << vk << "]" << std::endl;
         if ( update_arc2index ) {
           myArc2Index[ Arc( vj, vk ) ] = i;
         }
         // Copy last half-edge into i-th half-edge.
         myHalfEdges[ i ] = hej;
       }
       myHalfEdges.pop_back();
     }
References DGtal::HalfEdgeDataStructure::HalfEdge::edge, DGtal::HalfEdgeDataStructure::HalfEdge::face, halfEdge(), myArc2Index, myEdgeHalfEdges, myFaceHalfEdges, myHalfEdges, myVertexHalfEdges, nbHalfEdges(), DGtal::HalfEdgeDataStructure::HalfEdge::next, DGtal::HalfEdgeDataStructure::HalfEdge::opposite, and DGtal::HalfEdgeDataStructure::HalfEdge::toVertex.
Referenced by merge().
renumberVertex()
void DGtal::HalfEdgeDataStructure::renumberVertex (const VertexIndex vi, bool update_arc2index = true) inline protected
Renumber the last vertex of the triangulated surface as vertex i (this replaces it). The number of vertices of the data structure is decreased by 1.
Definition at line 994 of file HalfEdgeDataStructure.h.
{
       // Vertex j becomes vertex i
       const VertexIndex vj = nbVertices() - 1;
       if ( vi != vj ) {
         const Index        j = myVertexHalfEdges[ vj ];
         Index              k = j;
         // Turns around vertex vj to modify toVertex fields.
         do {
           const HalfEdge&    hek = halfEdge( k );
           const Index       kopp = hek.opposite;
           HalfEdge&       hekopp = myHalfEdges[ kopp ];
           ASSERT( hekopp.toVertex == vj );
           hekopp.toVertex = vi;
           if ( update_arc2index ) {
             myArc2Index.erase( Arc( vj, hek.toVertex ) );
             myArc2Index.erase( Arc( hek.toVertex, vj ) );
             myArc2Index[ Arc( vi, hek.toVertex ) ] = k;
             myArc2Index[ Arc( hek.toVertex, vi ) ] = kopp;
           }
           k = hekopp.next;
         } while ( k != j );
         myVertexHalfEdges[ vi ] = j;
       }
       myVertexHalfEdges.pop_back();
     }
References halfEdge(), myArc2Index, myHalfEdges, myVertexHalfEdges, nbVertices(), DGtal::HalfEdgeDataStructure::HalfEdge::next, DGtal::HalfEdgeDataStructure::HalfEdge::opposite, and DGtal::HalfEdgeDataStructure::HalfEdge::toVertex.
Referenced by merge().
selfDisplay()
void DGtal::HalfEdgeDataStructure::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters
out the output stream where the object is written.
split()
VertexIndex DGtal::HalfEdgeDataStructure::split (const Index i, bool update_arc2index = true) inline
Splits the edge specified by the half-edge i.
Parameters
i any valid half-edge index.
update_arc2index (optimisation parameter), when 'true' updates everything consistently; when 'false' do not update myArc2Index map, which means you cannot get an half edge from two vertices afterwards. Use 'false' only if you know that you never use this mapping (e.g. no call to halfEdgeIndexFromArc)
Returns
the index of the created vertex.
Precondition
the edge must be flippable, isFlippable(i) == true
See also
isFlippable
Todo:
We could also split boundary triangles or more general faces.
Note
Time complexity is O(1) if update_arc2index is false, otherwise it is O(log n) is n is the number of arcs.
Definition at line 727 of file HalfEdgeDataStructure.h.
     {
       Index        new_hei = myHalfEdges.size();
       VertexIndex new_vtxi = myVertexHalfEdges.size();
       EdgeIndex  new_edgei = myEdgeHalfEdges.size();
       FaceIndex  new_facei = myFaceHalfEdges.size();
       myHalfEdges.resize( new_hei + 6 );
       myVertexHalfEdges.push_back( new_hei );
       HalfEdge&       hei = myHalfEdges[ i ];
       HalfEdge&  hei_next = myHalfEdges[ hei.next ];
       Index             j = hei.opposite;
       HalfEdge&       hej = myHalfEdges[ j ];
       HalfEdge&  hej_next = myHalfEdges[ hej.next ];
       HalfEdge&       he0 = myHalfEdges[ new_hei ];
       HalfEdge&       he1 = myHalfEdges[ new_hei + 1 ];
       HalfEdge&       he2 = myHalfEdges[ new_hei + 2 ];
       HalfEdge&       he3 = myHalfEdges[ new_hei + 3 ];
       HalfEdge&       he4 = myHalfEdges[ new_hei + 4 ];
       HalfEdge&       he5 = myHalfEdges[ new_hei + 5 ];
       // HalfEdge = { toVertex, face, edge, opposite, next }
       // Taking care of new half-edges
       he0.toVertex = hei_next.toVertex;
       he0.face     = hei.face;
       he0.edge     = new_edgei;
       he0.opposite = new_hei + 1;
       he0.next     = hei_next.next;
       he1.toVertex = new_vtxi;
       he1.face     = new_facei;
       he1.edge     = new_edgei;
       he1.opposite = new_hei;
       he1.next     = new_hei + 2;
       he2.toVertex = hei.toVertex;
       he2.face     = new_facei;
       he2.edge     = new_edgei + 1;
       he2.opposite = j;
       he2.next     = hei.next;
       he3.toVertex = hej_next.toVertex;
       he3.face     = hej.face;
       he3.edge     = new_edgei + 2;
       he3.opposite = new_hei + 4;
       he3.next     = hej_next.next;
       he4.toVertex = new_vtxi;
       he4.face     = new_facei + 1;
       he4.edge     = new_edgei + 2;
       he4.opposite = new_hei + 3;
       he4.next     = new_hei + 5;
       he5.toVertex = hej.toVertex;
       he5.face     = new_facei + 1;
       he5.edge     = hei.edge;
       he5.opposite = i;
       he5.next     = hej.next;
       // Updating existing half-edges
       hei.toVertex = new_vtxi;
       hei.opposite = new_hei + 5;
       hei.next     = new_hei;
       hej.toVertex = new_vtxi;
       hej.edge     = new_edgei + 1;
       hej.opposite = new_hei + 2;
       hej.next     = new_hei + 3;
       hei_next.face     = new_facei;
       hei_next.next     = new_hei + 1;
       hej_next.face     = new_facei + 1;
       hej_next.next     = new_hei + 4;
       // Updating other arrays
       myEdgeHalfEdges.push_back( new_hei );
       myEdgeHalfEdges.push_back( j );
       myEdgeHalfEdges.push_back( new_hei + 3 );
       myFaceHalfEdges.push_back( new_hei + 1 );
       myFaceHalfEdges.push_back( new_hei + 4 );
       myFaceHalfEdges[ hei.face ] = i;
       myFaceHalfEdges[ hej.face ] = j;
       myEdgeHalfEdges[ hei.edge ] = i;
       if ( update_arc2index )
         {
           const VertexIndex vi = he5.toVertex;
           const VertexIndex vk = hei_next.toVertex;
           const VertexIndex vj = he2.toVertex;
           const VertexIndex vl = hej_next.toVertex;
           myArc2Index.erase( Arc( vi, vj ) );
           myArc2Index.erase( Arc( vj, vi ) );
           myArc2Index[ Arc( vi, new_vtxi ) ] = i;
           myArc2Index[ Arc( new_vtxi, vi ) ] = new_hei + 5;
           myArc2Index[ Arc( vj, new_vtxi ) ] = j;
           myArc2Index[ Arc( new_vtxi, vj ) ] = new_hei + 2;
           myArc2Index[ Arc( vk, new_vtxi ) ] = new_hei + 1;
           myArc2Index[ Arc( new_vtxi, vk ) ] = new_hei;
           myArc2Index[ Arc( vl, new_vtxi ) ] = new_hei + 4;
           myArc2Index[ Arc( new_vtxi, vl ) ] = new_hei + 3;
         }
       return new_vtxi;
     }
References DGtal::HalfEdgeDataStructure::HalfEdge::edge, DGtal::HalfEdgeDataStructure::HalfEdge::face, myArc2Index, myEdgeHalfEdges, myFaceHalfEdges, myHalfEdges, myVertexHalfEdges, DGtal::HalfEdgeDataStructure::HalfEdge::next, DGtal::HalfEdgeDataStructure::HalfEdge::opposite, and DGtal::HalfEdgeDataStructure::HalfEdge::toVertex.
Referenced by SCENARIO().
verticesOfFace()
VertexIndexRange DGtal::HalfEdgeDataStructure::verticesOfFace (const FaceIndex f) const inline
Parameters
f any valid face index.
Returns
the sequence of vertices of the face f.
Definition at line 602 of file HalfEdgeDataStructure.h.
     {
       VertexIndexRange result;
       result.reserve( 3 );
       Index hei = halfEdgeIndexFromFaceIndex( f );
       const Index start = hei;
        do {
          const HalfEdge& he = halfEdge( hei );
          result.push_back( he.toVertex );
          hei = he.next;
        }
        while ( hei != start );
        return result;
     }
References halfEdge(), halfEdgeIndexFromFaceIndex(), DGtal::HalfEdgeDataStructure::HalfEdge::next, and DGtal::HalfEdgeDataStructure::HalfEdge::toVertex.
Field Documentation
myArc2Index
Arc2Index DGtal::HalfEdgeDataStructure::myArc2Index protected
The mapping between arcs to their half-edge index.
Definition at line 1393 of file HalfEdgeDataStructure.h.
Referenced by clear(), flip(), halfEdgeIndexFromArc(), isValid(), merge(), renumberHalfEdge(), renumberVertex(), and split().
myEdgeHalfEdges
std::vector< Index > DGtal::HalfEdgeDataStructure::myEdgeHalfEdges protected
Offset into the 'halfedges' sequence, one per edge (unordered pair of vertex indices). Associates to each edge index the index of an half-edge on this edge.
Definition at line 1391 of file HalfEdgeDataStructure.h.
Referenced by clear(), halfEdgeIndexFromEdgeIndex(), isValid(), merge(), nbEdges(), renumberEdge(), renumberHalfEdge(), and split().
myFaceHalfEdges
std::vector< Index > DGtal::HalfEdgeDataStructure::myFaceHalfEdges protected
Offset into the 'halfedges' sequence, one per face. Associates to each face index the index of an half-edge lying on the border of this face.
Definition at line 1387 of file HalfEdgeDataStructure.h.
Referenced by clear(), flip(), halfEdgeIndexFromFaceIndex(), isValid(), isValidTriangulation(), nbFaces(), renumberFace(), renumberHalfEdge(), and split().
myHalfEdges
std::vector< HalfEdge > DGtal::HalfEdgeDataStructure::myHalfEdges protected
Stores all the half-edges.
Definition at line 1379 of file HalfEdgeDataStructure.h.
Referenced by arcFromHalfEdgeIndex(), boundaryArcs(), boundaryHalfEdgeIndices(), boundaryVertices(), clear(), findHalfEdgeIndexFromArc(), flip(), halfEdge(), isValid(), merge(), nbHalfEdges(), renumberEdge(), renumberFace(), renumberHalfEdge(), renumberVertex(), and split().
myVertexHalfEdges
std::vector< Index > DGtal::HalfEdgeDataStructure::myVertexHalfEdges protected
Offsets into the 'halfedges' sequence, one per vertex. Associates to each vertex index the index of an half-edge originating from this vertex.
Definition at line 1383 of file HalfEdgeDataStructure.h.
Referenced by clear(), flip(), halfEdgeIndexFromVertexIndex(), isValid(), isVertexBoundary(), merge(), nbVertices(), renumberHalfEdge(), renumberVertex(), and split().
The documentation for this class was generated from the following file:
HalfEdgeDataStructure.h