DGtal: DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange Class Reference
DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange Class Reference
Constant range on a ConstImageFunctorHolder.
#include <DGtal/images/ConstImageFunctorHolder.h>
Public Types
using ConstIterator = typename Self::ConstIterator
using ConstReverseIterator = typename Self::ConstReverseIterator
using Point = typename Self::Point
Public Member Functions
ConstRange (Self const &aConstImageFunctorHolder)
ConstIterator begin () const
ConstIterator begin (Point const &aPoint) const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rbegin (Point const &aPoint) const
ConstReverseIterator rend () const
Private Attributes
Self const & myConstImageFunctorHolder
Detailed Description
template<typename TDomain, typename TValue, typename TFunctor>
class DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange
Constant range on a ConstImageFunctorHolder.
Definition at line 222 of file ConstImageFunctorHolder.h.
Member Typedef Documentation
ConstIterator
template<typename TDomain , typename TValue , typename TFunctor > using DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::ConstIterator = typename Self::ConstIterator
Definition at line 229 of file ConstImageFunctorHolder.h.
ConstReverseIterator
template<typename TDomain , typename TValue , typename TFunctor > using DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::ConstReverseIterator = typename Self::ConstReverseIterator
Definition at line 230 of file ConstImageFunctorHolder.h.
Point
template<typename TDomain , typename TValue , typename TFunctor > using DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::Point = typename Self::Point
Definition at line 231 of file ConstImageFunctorHolder.h.
Constructor & Destructor Documentation
ConstRange()
template<typename TDomain , typename TValue , typename TFunctor > DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::ConstRange (Self const & aConstImageFunctorHolder) inline
Definition at line 225 of file ConstImageFunctorHolder.h.
         : myConstImageFunctorHolder( aConstImageFunctorHolder )
       {}
Member Function Documentation
begin() [1/2]
template<typename TDomain , typename TValue , typename TFunctor > ConstIterator DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::begin () const inline
Definition at line 233 of file ConstImageFunctorHolder.h.
 { return { myConstImageFunctorHolder.myDomain.begin(), myConstImageFunctorHolder }; }
References DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::myConstImageFunctorHolder, and DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::myDomain.
Referenced by DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::rbegin(), and DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::rend().
begin() [2/2]
template<typename TDomain , typename TValue , typename TFunctor > ConstIterator DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::begin (Point const & aPoint) const inline
Definition at line 234 of file ConstImageFunctorHolder.h.
 { return { myConstImageFunctorHolder.myDomain.begin(aPoint), myConstImageFunctorHolder }; }
References aPoint(), DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::myConstImageFunctorHolder, and DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::myDomain.
end()
template<typename TDomain , typename TValue , typename TFunctor > ConstIterator DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::end () const inline
Definition at line 235 of file ConstImageFunctorHolder.h.
 { return { myConstImageFunctorHolder.myDomain.end(), myConstImageFunctorHolder }; }
References DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::myConstImageFunctorHolder, and DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::myDomain.
Referenced by DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::rbegin().
rbegin() [1/2]
template<typename TDomain , typename TValue , typename TFunctor > ConstReverseIterator DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::rbegin () const inline
Definition at line 237 of file ConstImageFunctorHolder.h.
 { return ConstReverseIterator( end() ); }
References DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::end().
rbegin() [2/2]
template<typename TDomain , typename TValue , typename TFunctor > ConstReverseIterator DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::rbegin (Point const & aPoint) const inline
Definition at line 238 of file ConstImageFunctorHolder.h.
 { return ConstReverseIterator( ++begin(aPoint) ); }
References aPoint(), and DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::begin().
rend()
template<typename TDomain , typename TValue , typename TFunctor > ConstReverseIterator DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::rend () const inline
Definition at line 239 of file ConstImageFunctorHolder.h.
 { return ConstReverseIterator( begin() ); }
References DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::begin().
Field Documentation
myConstImageFunctorHolder
template<typename TDomain , typename TValue , typename TFunctor > Self const& DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::myConstImageFunctorHolder private
Definition at line 242 of file ConstImageFunctorHolder.h.
Referenced by DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::begin(), and DGtal::functors::ConstImageFunctorHolder< TDomain, TValue, TFunctor >::ConstRange::end().
The documentation for this class was generated from the following file:
ConstImageFunctorHolder.h