DGtal: DGtal::functors::SCellToPoint< KSpace > Class Template Reference
DGtal::functors::SCellToPoint< KSpace > Class Template Reference
Aim: transforms a scell into a point.
#include <DGtal/topology/SCellsFunctors.h>
Public Types
typedef KSpace::Point Output
typedef KSpace::SCell Input
Public Member Functions
SCellToPoint ()
SCellToPoint (ConstAlias< KSpace > aK)
SCellToPoint (const SCellToPoint &other)
SCellToPoint & operator= (const SCellToPoint &other)
Output operator() (const Input &aSCell) const
Private Attributes
const KSpace * myK
Detailed Description
template<typename KSpace>
class DGtal::functors::SCellToPoint< KSpace >
Aim: transforms a scell into a point.
Description of template class 'SCellToPoint'
Template Parameters
KSpace the Khalimsky space
KSpace aKSpace;
typename KSpace::SCell aSCell;
typename KSpace::Point aPoint;
SCellToPoint<KSpace> f(aKSpace);
...
aPoint = f(aSCell);
See also
ConstIteratorAdapter KhalimskySpaceND PointVector
Definition at line 74 of file SCellsFunctors.h.
Member Typedef Documentation
Input
template<typename KSpace > typedef KSpace::SCell DGtal::functors::SCellToPoint< KSpace >::Input
Definition at line 78 of file SCellsFunctors.h.
Output
template<typename KSpace > typedef KSpace::Point DGtal::functors::SCellToPoint< KSpace >::Output
Definition at line 77 of file SCellsFunctors.h.
Constructor & Destructor Documentation
SCellToPoint() [1/3]
template<typename KSpace > DGtal::functors::SCellToPoint< KSpace >::SCellToPoint () inline
Default constructor.
Definition at line 91 of file SCellsFunctors.h.
 : myK(NULL) { }
SCellToPoint() [2/3]
template<typename KSpace > DGtal::functors::SCellToPoint< KSpace >::SCellToPoint (ConstAlias< KSpace > aK) inline
Constructor.
Parameters
aK a Khalimsky space
Definition at line 96 of file SCellsFunctors.h.
 : myK(&aK) { }
SCellToPoint() [3/3]
template<typename KSpace > DGtal::functors::SCellToPoint< KSpace >::SCellToPoint (const SCellToPoint< KSpace > & other) inline
Copy constructor.
Parameters
other any SCellToPoint functor
Definition at line 102 of file SCellsFunctors.h.
     : myK(other.myK) { }
Member Function Documentation
operator()()
template<typename KSpace > Output DGtal::functors::SCellToPoint< KSpace >::operator() (const Input & aSCell) const inline
Returns a point (with integer coordinates) from a scell (with khalimsky coordinates)
Parameters
aSCell a scell
Returns
the corresponding point.
Definition at line 126 of file SCellsFunctors.h.
     {
       ASSERT( myK );
       Input s = aSCell;
       while ( myK->sDim(s) > 0 )
         {
           Input tmp( myK->sIndirectIncident( s, *myK->sDirs( s ) ) );
           ASSERT( myK->sDim(tmp) < myK->sDim(s) );
           s = tmp;
         }
       return Output( myK->sCoords(s) );
     }
References DGtal::functors::SCellToPoint< KSpace >::myK, DGtal::KhalimskySpaceND< dim, TInteger >::sCoords(), DGtal::KhalimskySpaceND< dim, TInteger >::sDim(), DGtal::KhalimskySpaceND< dim, TInteger >::sDirs(), and DGtal::KhalimskySpaceND< dim, TInteger >::sIndirectIncident().
operator=()
template<typename KSpace > SCellToPoint& DGtal::functors::SCellToPoint< KSpace >::operator= (const SCellToPoint< KSpace > & other) inline
Assignment.
Parameters
other the object to copy.
Returns
a reference on 'this'.
Definition at line 111 of file SCellsFunctors.h.
     {
       if (this != &other)
         {
           myK = other.myK;
         }
       return *this;
     }
References DGtal::functors::SCellToPoint< KSpace >::myK.
Field Documentation
myK
template<typename KSpace > const KSpace* DGtal::functors::SCellToPoint< KSpace >::myK private
Aliasing pointer on the Khalimsky space.
Definition at line 84 of file SCellsFunctors.h.
Referenced by DGtal::functors::SCellToPoint< KSpace >::operator()(), and DGtal::functors::SCellToPoint< KSpace >::operator=().
The documentation for this class was generated from the following file:
SCellsFunctors.h