DGtal: exampleParamCurve3dDigitizationTransformationDecorator.cpp File Reference
exampleParamCurve3dDigitizationTransformationDecorator.cpp File Reference
DGtal Examples
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "ConfigExamples.h"
#include "DGtal/io/viewers/Viewer3D.h"
#include "DGtal/geometry/curves/parametric/EllipticHelix.h"
#include "DGtal/geometry/curves/parametric/NaiveParametricCurveDigitizer3D.h"
#include "DGtal/geometry/curves/parametric/DecoratorParametricCurveTransformation.h"
#include "DGtal/images/RigidTransformation3D.h"
Functions
template<typename T >
unsigned char findMainAxis (const T &curve, const long double &t)
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Kacper Pluta (kacper.pluta@esiee.fr) Laboratoire d'Informatique Gaspard-Monge - LIGM, A3SI, France
Date
2018/08/03
An example file for DecoratorParametricCurveTransformation.h.
This file is part of the DGtal library.
Definition in file exampleParamCurve3dDigitizationTransformationDecorator.cpp.
Function Documentation
findMainAxis()
template<typename T > unsigned char findMainAxis (const T & curve, const long double & t) inline
Definition at line 57 of file exampleParamCurve3dDigitizationTransformationDecorator.cpp.
 {
  RealPoint value;
  value[0] = std::abs ( curve.xp ( t )[0] );
  value[1] = std::abs ( curve.xp ( t )[1] );
  value[2] = std::abs ( curve.xp ( t )[2] );
  if ( value[0] >= value[1] && value[0] >= value[2] )
   return 0;
  else if ( value[1] >= value[0] && value[1] >= value[2] )
   return 1;
  else
   return 2;
 }
Referenced by main().
main()
int main (int argc, char ** argv)
[DigiRotHelixConstr]
[DigiRotHelixConstr]
[DigiRotHelixConstrCurve]
[DigiRotHelixConstrCurve]
[DigiRotHelixConstrRot]
[DigiRotHelixConstrRot]
[DigiRotHelixDigitize]
[DigiRotHelixDigitize]
Definition at line 73 of file exampleParamCurve3dDigitizationTransformationDecorator.cpp.
 {
  QApplication application(argc,argv);
  typedef EllipticHelix < Space > MyHelix;
  typedef ForwardRigidTransformation3D < Space, RealPoint, RealPoint, Identity > ForwardTrans;
  typedef DecoratorParametricCurveTransformation < MyHelix, ForwardTrans > MyRotatedCurve;
  typedef NaiveParametricCurveDigitizer3D < MyRotatedCurve >  Digitizer;
  typedef typename NaiveParametricCurveDigitizer3D < MyRotatedCurve >::DigitalCurve MyDigitalCurve;
  typedef NaiveParametricCurveDigitizer3D < MyRotatedCurve >::MetaData MyMetaData;
  trace.info() << "exampleParamCurve3dDigitizationTransformationDecorator" << endl;
  Viewer3D<> viewer;
  MyMetaData metaData;
  MyDigitalCurve digitalCurve;
  MyHelix helix( 30, 20, 1 );
  double angle = M_PI/3.;
  RealVector axis ( 1., 0., 1. );
  ForwardTrans trans ( RealPoint ( 0, 0, 0 ), axis, angle, RealVector ( 0, 0, 0 ) );
  MyRotatedCurve rotCurve ( helix, trans );
  Digitizer digitize;
  digitize.attach ( &rotCurve );
  digitize.init ( 0, MyHelix::getPeriod() * 10., 0.0001 );
  digitize.digitize( back_insert_iterator < MyDigitalCurve> ( digitalCurve ), back_insert_iterator < MyMetaData > ( metaData ) );
  trace.info() << "Number of points: " << digitalCurve.size () << " number of metadata: " << metaData.size () << endl;
  viewer.show();
  for ( unsigned int i = 0; i < digitalCurve.size ( ); i++ )
  {
   if ( findMainAxis ( rotCurve, metaData.at ( i ).first ) == 0 )
    viewer.setFillColor ( Color ( 255, 0, 0, 128 ) );
   if ( findMainAxis ( rotCurve, metaData.at ( i ).first ) == 1 )
    viewer.setFillColor ( Color ( 0, 255, 0, 128 ) );
   if ( findMainAxis ( rotCurve, metaData.at ( i ).first ) == 2 )
    viewer.setFillColor ( Color ( 0, 0, 255, 128 ) );
   viewer << SetMode3D ( digitalCurve.at ( i ).className ( ), "PavingWired" ) << digitalCurve.at ( i );
  }
  viewer << Viewer3D<>::updateDisplay;
  return application.exec();
 }
References digitize(), findMainAxis(), DGtal::Trace::info(), DGtal::Display3D< Space, KSpace >::setFillColor(), DGtal::Viewer3D< TSpace, TKSpace >::show(), and DGtal::trace.