DGtal: exampleArrayImageAdapter.cpp File Reference
exampleArrayImageAdapter.cpp File Reference
DGtal Examples
An example file for ArrayImageAdapter.
#include <iostream>
#include <DGtal/base/Common.h>
#include <DGtal/helpers/StdDefs.h>
#include <DGtal/io/boards/Board2D.h>
#include <new>
#include <cmath>
#include <algorithm>
#include <DGtal/io/colormaps/HueShadeColorMap.h>
#include <DGtal/images/ImageContainerBySTLVector.h>
#include <DGtal/images/ArrayImageAdapter.h>
Functions
void ArrayImageAdapter_example ()
void moduleImages_example ()
int main ()
Detailed Description
An example file for ArrayImageAdapter.
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Roland Denis (rolan.nosp@m.d.de.nosp@m.nis@u.nosp@m.niv-.nosp@m.smb.f.nosp@m.r) LAboratory of MAthematics - LAMA (CNRS, UMR 5127), University of Savoie, France
Date
2015/10/14
This file is part of the DGtal library.
Definition in file exampleArrayImageAdapter.cpp.
Function Documentation
ArrayImageAdapter_example()
void ArrayImageAdapter_example ()
[ArrayImageAdapter_example]
[ArrayImageAdapter_example]
Definition at line 53 of file exampleArrayImageAdapter.cpp.
 {
   using Space = SpaceND<2>;
   using Domain = HyperRectDomain<Space>;
   using Point = Domain::Point;
   using Value = double;
   const Domain domain( Point(0, 1), Point(4, 3) );
   Value* data = new Value[ domain.size() ];
   // Convert this allocated memory to a CImage model.
   ArrayImageAdapter< Value*, Domain > image( data, domain );
   // Alternative syntax using the helpers:
   // auto image = makeArrayImageAdapterFromIterator( data, domain );
   // Fill the image with first coordinate of the point
   for ( auto it = image.begin(); it != image.end(); ++it )
     {
       *it = it.getPoint()[0];
     }
   // Get a constant view on a sub-domain.
   const Domain sub_domain( Point(1, 1), Point(3, 2) );
   ArrayImageAdapter< Value const*, Domain > cst_image( data, domain, sub_domain );
   // Alternative syntax using the helpers:
   // auto const cst_image = makeArrayImageAdapterFromImage( image, sub_domain );
   // Display it.
   for ( auto value : cst_image )
     {
       std::cout << value << " ";
     }
   std::cout << std::endl;
 }
References domain, image(), and DGtal::HyperRectDomain< TSpace >::size().
Referenced by main().
main()
int main (void)
Definition at line 209 of file exampleArrayImageAdapter.cpp.
 {
   ArrayImageAdapter_example();
   moduleImages_example();
   return 0;
 }
References ArrayImageAdapter_example(), and moduleImages_example().
moduleImages_example()
void moduleImages_example ()
[def]
[def]
[raw_image_creation]
[raw_image_creation]
[image_filling]
[image_filling]
[ConstArrayImageAdapterForSubImage_creation]
[ConstArrayImageAdapterForSubImage_creation]
[ArrayImageAdapterForSubImage_creation]
[ArrayImageAdapterForSubImage_creation]
[ArrayImageAdapterForSubImage_alternateCreation]
[ArrayImageAdapterForSubImage_alternateCreation]
[ArrayImageAdapterForSubImage_modifByDomain]
[ArrayImageAdapterForSubImage_modifByDomain]
[ArrayImageAdapterForSubImage_modifByImage]
[ArrayImageAdapterForSubImage_modifByImage]
[ImageSTL_creation]
[ImageSTL_creation]
[ArrayImageAdapterFromImageSTL]
[ArrayImageAdapterFromImageSTL]
[ArrayImageAdapterFromImageSTL_alternate]
[ArrayImageAdapterFromImageSTL_alternate]
[ArrayImageAdapterFromImageSTL_copy]
[ArrayImageAdapterFromImageSTL_copy]
Definition at line 91 of file exampleArrayImageAdapter.cpp.
 {
   using namespace Z2i;
   Board2D aBoard;
   using Value = double; // value type  of the image
   using HueShadeDouble = HueShadeColorMap<Value>;   // a simple HueShadeColorMap varying on 'double' values
   trace.beginBlock("image");
   const Domain domain(Point(1,1), Point(16,16));
   Value* data = new Value[ domain.size() ];
   ArrayImageAdapter< Value*, Domain > image( data, domain );
   Value i = 0;
   for ( auto & value : image )
     value = i++;
   aBoard.clear();
   Display2DFactory::drawImage<HueShadeDouble>(aBoard, image, 0, domain.size()-1);
   aBoard.saveSVG("ArrayImageAdapter_image.svg");
   trace.endBlock();
   trace.beginBlock("subImage");
   Domain subDomain(Point(1,1), Point(8,8));
   ArrayImageAdapter< Value const*, Domain > constSubImage( data, domain, subDomain );
   aBoard.clear();
   Display2DFactory::drawImage<HueShadeDouble>(aBoard, constSubImage, 0, domain.size()-1);
   aBoard.saveSVG("ArrayImageAdapter_subImage.svg");
   trace.endBlock();
   trace.beginBlock("modifying subImage through domain iterator");
   {
   ArrayImageAdapter< Value*, Domain > subImage( data, domain, subDomain );
   }
   auto subImage = makeArrayImageAdapterFromIterator( data, domain, subDomain );
   for ( auto point : subImage.domain() )
     {
       Value coord = (point - Point(4,4)).norm();
       subImage.setValue( point, 25*(cos(coord)+1) );
     }
   aBoard.clear();
   Display2DFactory::drawImage<HueShadeDouble>(aBoard, image, 0, domain.size()-1);
   aBoard.saveSVG("ArrayImageAdapter_subImage_modifByDomain.svg");
   trace.endBlock();
   trace.beginBlock("modifying subImage through image iterator");
   for ( auto it = subImage.begin(), it_end = subImage.end(); it != it_end; ++it )
     {
       Value coord = (it.getPoint() - Point(4,4)).norm();
       *it = 25*(sin(coord)+1);
     }
   aBoard.clear();
   Display2DFactory::drawImage<HueShadeDouble>(aBoard, image, 0, domain.size()-1);
   aBoard.saveSVG("ArrayImageAdapter_subImage_modifByImage.svg");
   trace.endBlock();
   trace.beginBlock("subImage from an ImageContainerBySTLVector");
   ImageContainerBySTLVector<Domain, Value> anIterableImage(domain);
   for (auto& value : anIterableImage)
     value = 0;
   {
   ArrayImageAdapter< ImageContainerBySTLVector<Domain,Value>::Iterator, Domain > subImageSTL( anIterableImage.begin(), domain, subDomain );
   }
   auto subImageSTL = makeArrayImageAdapterFromImage( anIterableImage, subDomain );
   trace.endBlock();
   trace.beginBlock("using std::copy on ArrayImageAdapter");
   std::copy( subImage.cbegin(), subImage.cend(), subImageSTL.begin() );
   aBoard.clear();
   Display2DFactory::drawImage<HueShadeDouble>(aBoard, anIterableImage, 0, domain.size()-1);
   aBoard.saveSVG("ArrayImageAdapter_subImage_copyToImageSTL.svg");
   trace.endBlock();
   delete[] data;
 }
References DGtal::Trace::beginBlock(), LibBoard::Board::clear(), domain, DGtal::Trace::endBlock(), image(), DGtal::makeArrayImageAdapterFromImage(), DGtal::makeArrayImageAdapterFromIterator(), LibBoard::Board::saveSVG(), DGtal::HyperRectDomain< TSpace >::size(), and DGtal::trace.
Referenced by main().