DGtal: examplePlaneProbingSurfaceLocalEstimator.cpp File Reference
examplePlaneProbingSurfaceLocalEstimator.cpp File Reference
DGtal Examples
#include <iostream>
#include <unordered_map>
#include "ConfigExamples.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/base/Common.h"
#include "DGtal/geometry/surfaces/estimation/PlaneProbingTetrahedronEstimator.h"
#include "DGtal/geometry/surfaces/estimation/PlaneProbingParallelepipedEstimator.h"
#include "DGtal/geometry/surfaces/DigitalSurfacePredicate.h"
#include "DGtal/geometry/surfaces/estimation/PlaneProbingDigitalSurfaceLocalEstimator.h"
#include "DGtal/helpers/Shortcuts.h"
#include "DGtal/helpers/ShortcutsGeometry.h"
#include "DGtal/io/viewers/Viewer3D.h"
Typedefs
using KSpace = Z3i::KSpace
using SH3 = Shortcuts< KSpace >
using SHG3 = ShortcutsGeometry< KSpace >
using Surface = SH3::DigitalSurface
using Surfel = SH3::Surfel
using Point = SH3::Point
using RealPoint = SH3::RealPoint
using Integer = Point::Coordinate
Functions
RealPoint centerSurfel (KSpace const &K, SH3::SCell const &s)
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jocelyn Meyron (jocel.nosp@m.yn.m.nosp@m.eyron.nosp@m.@lir.nosp@m.is.cn.nosp@m.rs.f.nosp@m.r) Laboratoire d'InfoRmatique en Image et Systemes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2020/12/07
An example file that shows how to construct and use a PlaneProbingDigitalSurfaceLocalEstimator.
This file is part of the DGtal library.
Definition in file examplePlaneProbingSurfaceLocalEstimator.cpp.
Typedef Documentation
Integer
using Integer = Point::Coordinate
Definition at line 55 of file examplePlaneProbingSurfaceLocalEstimator.cpp.
KSpace
using KSpace = Z3i::KSpace
Definition at line 48 of file examplePlaneProbingSurfaceLocalEstimator.cpp.
Point
using Point = SH3::Point
Definition at line 53 of file examplePlaneProbingSurfaceLocalEstimator.cpp.
RealPoint
using RealPoint = SH3::RealPoint
Definition at line 54 of file examplePlaneProbingSurfaceLocalEstimator.cpp.
SH3
using SH3 = Shortcuts<KSpace>
Definition at line 49 of file examplePlaneProbingSurfaceLocalEstimator.cpp.
SHG3
using SHG3 = ShortcutsGeometry<KSpace>
Definition at line 50 of file examplePlaneProbingSurfaceLocalEstimator.cpp.
Surface
using Surface = SH3::DigitalSurface
Definition at line 51 of file examplePlaneProbingSurfaceLocalEstimator.cpp.
Surfel
using Surfel = SH3::Surfel
Definition at line 52 of file examplePlaneProbingSurfaceLocalEstimator.cpp.
Function Documentation
centerSurfel()
RealPoint centerSurfel (KSpace const & K, SH3::SCell const & s)
Definition at line 57 of file examplePlaneProbingSurfaceLocalEstimator.cpp.
 {
     auto pointels = SH3::getPrimalVertices(K, s, true);
     Point p = K.uCoords(pointels[0]),
           u = K.uCoords(pointels[1]) - p,
           v = K.uCoords(pointels[3]) - p;
     static const RealPoint shift(-0.5, -0.5, -0.5);
     return p + 0.5 * u + 0.5 * v + shift;
 }
References DGtal::Shortcuts< TKSpace >::getPrimalVertices(), K, and DGtal::KhalimskySpaceND< dim, TInteger >::uCoords().
Referenced by main().
main()
int main (int argc, char ** argv)
[PlaneProbingDigitalSurfaceLocalEstimatorConstruction]
[PlaneProbingDigitalSurfaceLocalEstimatorConstruction]
[PlaneProbingDigitalSurfaceLocalEstimatorUsage]
[PlaneProbingDigitalSurfaceLocalEstimatorUsage]
Definition at line 72 of file examplePlaneProbingSurfaceLocalEstimator.cpp.
 {
     QApplication application(argc, argv);
     std::string volfile = (argc > 1) ? argv[1] : (examplesPath + "samples/cat10.vol");
     auto params    = SH3::defaultParameters() | SHG3::defaultParameters();
     auto bimage    = SH3::makeBinaryImage(volfile, params);
     auto K         = SH3::getKSpace(bimage, params);
     auto surface   = SH3::makeDigitalSurface(bimage, K, params);
     auto surfels   = SH3::getSurfelRange(surface);
     Integer bound = params["maxAABB"].as<Integer>();
     double gridstep = params["gridstep"].as<double>();
     Viewer3D<> viewer(K);
     viewer << SetMode3D(Surfel().className(), "Basic");
     viewer.show();
     using SurfacePredicate = DigitalSurfacePredicate<Surface>;
     using ProbingAlgorithm = PlaneProbingParallelepipedEstimator<SurfacePredicate, ProbingMode::R1>;
     // The general form is PlaneProbingDigitalSurfaceLocalEstimator<SurfaceType, ProbingAlgorithm>
     using Estimator        = PlaneProbingDigitalSurfaceLocalEstimator<Surface, ProbingAlgorithm>;
     // Parameters of the estimator:
     // - the probing factory
     Estimator::ProbingFactory probingFactory = [&bound](const Estimator::ProbingFrame& frame, const SurfacePredicate& surfacePredicate) {
         // If the base estimator is a PlaneProbingTetrahedronEstimator
         // return new ProbingAlgorithm(frame.p, { frame.b1, frame.b2, frame.normal }, surfacePredicate);
         // For a PlaneProbingParallelepipedEstimator
         return new ProbingAlgorithm(frame.p, { frame.b1, frame.b2, frame.normal }, surfacePredicate, bound);
     };
     // - an optional hashmap of pre-estimations
     std::unordered_map<Surfel, RealPoint> preEstimations;
     // The user can provide the pre-estimation
     // auto preEstimationsVector = SHG3::getCTrivialNormalVectors(surface, surfels, params);
     // for (std::size_t i = 0; i < surfels.size(); ++i)
     // {
     //     preEstimations[surfels[i]] = preEstimationsVector[i];
     // }
     // Or if it is not given, it is implicitly done inside the Estimator::eval function (using the MaximalSegmentSliceEstimation estimator)
     // - a verbosity flag
     bool verbose = true;
     Estimator estimator(surface, probingFactory, preEstimations, verbose);
     estimator.init(gridstep, surfels.begin(), surfels.end());
     // Evaluation on a range of surfels
     std::vector<Estimator::Quantity> quantities;
     estimator.eval(surfels.begin(), surfels.end(), std::back_inserter(quantities));
     // Or on one surfel 's'
     // Estimator::Quantity q = estiamtor.eval(s);
     Color fillColor = viewer.getFillColor();
     int i = 0;
     for (auto it = surfels.begin(); it != surfels.end(); ++it, ++i)
     {
         const Surfel& s = *it;
         const Estimator::Quantity& n = quantities[i];
         RealPoint origin = centerSurfel(K, s);
         viewer.setFillColor(fillColor);
         viewer << s;
         // Pre-estimation in red
         RealPoint const& preEstimation = estimator.getPreEstimation(it);
         viewer.setLineColor(Color::Red);
         viewer.addLine(origin, origin + 1.5 * preEstimation.getNormalized(), 0.3);
         // Estimated normal in green;
         viewer.setLineColor(Color::Green);
         viewer.addLine(origin, origin + 1.5 * n.getNormalized(), 0.3);
     }
     viewer << Viewer3D<>::updateDisplay;
     application.exec();
     return 0;
 }
References centerSurfel(), DGtal::Shortcuts< TKSpace >::defaultParameters(), DGtal::ShortcutsGeometry< TKSpace >::defaultParameters(), DGtal::Shortcuts< TKSpace >::getKSpace(), DGtal::PointVector< dim, TEuclideanRing, TContainer >::getNormalized(), DGtal::Shortcuts< TKSpace >::getSurfelRange(), K, DGtal::Shortcuts< TKSpace >::makeBinaryImage(), and DGtal::Shortcuts< TKSpace >::makeDigitalSurface().