DGtal: exampleLatticeBallDelaunay3D.cpp File Reference
exampleLatticeBallDelaunay3D.cpp File Reference
DGtal Examples | DGtal Examples
#include "DGtal/base/Common.h"
#include "DGtal/kernel/PointVector.h"
#include "DGtal/shapes/SurfaceMesh.h"
#include "DGtal/io/writers/SurfaceMeshWriter.h"
#include "DGtal/geometry/volumes/ConvexityHelper.h"
Functions
int main (int argc, char *argv[])
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2021/02/06
An example file named exampleLatticeBallDelaunay3D.
This file is part of the DGtal library.
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2021/02/06
An example file named exampleRationalBallDelaunay3D.
This file is part of the DGtal library.
Definition in file exampleLatticeBallDelaunay3D.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 60 of file exampleLatticeBallDelaunay3D.cpp.
 {
   int     nb = argc > 1 ? atoi( argv[ 1 ] ) : 100; // nb points
   double dR  = argc > 2 ? atof( argv[ 2 ] ) : 10.;  // radius of balla
   double eps = argc > 3 ? atof( argv[ 3 ] ) : 0.1; // retraction
   typedef ConvexCellComplex< Point >::Index Index;
   ConvexCellComplex< Point > dcomplex;
   // (1) create range of random points in ball
   std::vector< Point > V;
   const auto R2 = dR * dR;
   const int  R  = ceil( dR );
   for ( int i = 0; i < nb; ) {
     Point p( rand() % (2*R+1) - R, rand() % (2*R+1) - R, rand() % (2*R+1) - R );
     if ( p.squaredNorm() <= R2 ) { V.push_back( p ); i++; }
   }
   // (2) compute convex hull
   bool ok =
     ConvexityHelper< 3 >::computeDelaunayCellComplex( dcomplex, V, true );
   if ( ! ok )
     {
       trace.error() << "Input set of points is not full dimensional." << std::endl;
       return 1;
     }
   dcomplex.requireFaceGeometry();
   std::cout << dcomplex << std::endl;
   // (3) build the mesh that is made of the exploded 3d cells
   std::vector< RealPoint > positions;
   std::vector< std::vector< Index > > facets;
   Index idxv = 0;
   for ( auto c = 0; c < dcomplex.nbCells(); ++c )
     {
       RealPoint b = dcomplex.cellBarycenter( c );
       auto c_vtcs = dcomplex.cellVertices( c );
       std::map< Index, Index > v2v;
       for ( auto v : c_vtcs ) {
         RealPoint x = dcomplex.toReal( dcomplex.position( v ) );
         v2v[ v ] = idxv++;
         positions.push_back( b + ( x - b ) * ( 1.0 - eps ) );
       }
       for ( const auto& f : dcomplex.cellFaces( c ) ) {
         auto f_vtcs = dcomplex.faceVertices( f );
         for ( auto& vertex : f_vtcs )
           vertex = v2v[ vertex ];
         facets.push_back( f_vtcs );
       }
     }
   typedef DGtal::SurfaceMesh< Z3::RealPoint, Z3::RealVector> SMesh;
   SMesh mesh( positions.cbegin(), positions.cend(),
               facets.cbegin(), facets.cend() );
   // (4) output result as OBJ file
   std::ofstream out( "delaunay3d.obj" );
   DGtal::SurfaceMeshWriter< Z3::RealPoint, Z3::RealVector >
     ::writeOBJ( out, mesh );
   out.close();
   return 0;
 }
References DGtal::ConvexCellComplex< TPoint >::cellBarycenter(), DGtal::ConvexCellComplex< TPoint >::cellFaces(), DGtal::ConvexCellComplex< TPoint >::cellVertices(), DGtal::ConvexityHelper< dim, TInteger, TInternalInteger >::computeDelaunayCellComplex(), DGtal::Trace::error(), DGtal::ConvexCellComplex< TPoint >::faceVertices(), DGtal::ConvexCellComplex< TPoint >::nbCells(), DGtal::ConvexCellComplex< TPoint >::position(), DGtal::R, DGtal::ConvexCellComplex< TPoint >::requireFaceGeometry(), DGtal::ConvexCellComplex< TPoint >::toReal(), DGtal::trace, and DGtal::SurfaceMeshWriter< TRealPoint, TRealVector >::writeOBJ().