DGtal: greedyAlphaThickDecomposition.cpp File Reference
greedyAlphaThickDecomposition.cpp File Reference
DGtal Examples
#include <iostream>
#include "ConfigExamples.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/base/Common.h"
#include "DGtal/geometry/curves/AlphaThickSegmentComputer.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/geometry/curves/GreedySegmentation.h"
#include <DGtal/io/readers/GenericReader.h>
Functions
int main ()
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Bertrand Kerautret (kerau.nosp@m.tre@.nosp@m.loria.nosp@m..fr) LORIA (CNRS, UMR 7503), University of Nancy, France
Date
2015/01/30
An example file named exampleAlphaThickSegment
This file is part of the DGtal library.
Definition in file greedyAlphaThickDecomposition.cpp.
Function Documentation
main()
int main (void)
[greedyAlphaThickDecompositionModeDisplay]
[greedyAlphaThickDecompositionModeDisplay]
[greedyAlphaThickDecompositionAlgo]
[greedyAlphaThickDecompositionAlgo]
[greedyAlphaThickDecompositionDisplay]
[greedyAlphaThickDecompositionDisplay]
Definition at line 57 of file greedyAlphaThickDecomposition.cpp.
 {
   trace.beginBlock ( "Example of greedy alpha thick segment  decompotion" );
   typedef  std::vector<Z2i::RealPoint>::const_iterator ConstIterator;
   typedef  AlphaThickSegmentComputer<Z2i::RealPoint, ConstIterator > AlphaThickSegmentComputer2D;
   Board2D aBoard;
   std::string file = examplesPath + "samples/contourSnoisy.sdp";
   std::vector<Z2i::RealPoint> aContour = PointListReader<Z2i::RealPoint>::getPointsFromFile (file);
   typedef GreedySegmentation<AlphaThickSegmentComputer2D> DecompositionAT;
   // displaying contour
   aBoard << SetMode(aContour[0].className(), "Grid");
   std::vector<LibBoard::Point> poly;
   for (unsigned int i = 0; i< aContour.size(); i++)  poly.push_back(LibBoard::Point(aContour[i][0], aContour[i][1]));
   aBoard.setPenColor(DGtal::Color::Gray);
   aBoard.fillPolyline(poly);
   // Computing greedy Alpha Thick decomposition.
   aBoard << SetMode("AlphaThickSegment", "BoundingBox");
   DecompositionAT theDecomposition(aContour.begin(), aContour.end(), AlphaThickSegmentComputer2D(4));
   for ( DecompositionAT::SegmentComputerIterator
            it = theDecomposition.begin(),
            itEnd = theDecomposition.end();
          it != itEnd; ++it )
      {
        aBoard << CustomStyle( (*it).className(),
                               new CustomPenColor( Color::Blue ) );
        aBoard<< *it;
      }
   aBoard.saveEPS("greedyAlphaThickDecomposition.eps");
   trace.endBlock();
   return 0;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), LibBoard::Board::fillPolyline(), DGtal::Color::Gray, LibBoard::Board::saveEPS(), LibBoard::Board::setPenColor(), and DGtal::trace.