DGtal: DGtal::concepts::CStack< T > Struct Template Reference
DGtal::concepts::CStack< T > Struct Template Reference
DGtal Concepts
Aim: This concept gathers classes that provide a stack interface.
#include <DGtal/base/CStack.h>
Public Types
typedef T::value_type Value
typedef T::size_type Size
Public Member Functions
BOOST_CONCEPT_USAGE (CStack)
void checkConstConstraints () const
Private Attributes
T myX
Value myV
Size myS
bool myB
Detailed Description
template<typename T>
struct DGtal::concepts::CStack< T >
Aim: This concept gathers classes that provide a stack interface.
Description of concept 'CStack'
Refinement of copy constructible and assignable
Inner types
Value type of element stored in the stack
Size type that represents the number of elements
Notation
X : A type that is a model of CStack
x : object of type X
v : object of type Value
Definitions
Valid expressions and semantics
| Name | Expression | Type requirements | Return type | Precondition | Semantics | Post condition | Complexity | |----—+---------—+----------------—+---------------------—+-----------—+---------------------------------—+-------------—+---------—| | size | x.size() | | Size | | returns the number of elements | | O(1) | | empty | x.empty() | | bool | | 'true' is empty, 'false' otherwise | | O(1) | | top | x.top() | | Value& or const Value& | | returns the top element | | O(1) | | push | x.push(v) | | void | | inserts a new element at the top | | O(1) | | pop | x.pop() | | void | | removes the top element | | O(1) |
Models
std::stack, BackInsertionSequenceToStackAdapter, FrontInsertionSequenceToStackAdapter are the usual models of CStack.
Template Parameters
T the type that should be a model of CStack.
Definition at line 91 of file CStack.h.
Member Typedef Documentation
Size
template<typename T > typedef T::size_type DGtal::concepts::CStack< T >::Size
Definition at line 96 of file CStack.h.
Value
template<typename T > typedef T::value_type DGtal::concepts::CStack< T >::Value
Definition at line 95 of file CStack.h.
Member Function Documentation
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CStack< T >::BOOST_CONCEPT_USAGE (CStack< T >) inline
Definition at line 98 of file CStack.h.
       {
         concepts::ConceptUtils::sameType( myV, myX.top() );
         myX.push( myV );
         myX.pop();
         // check const methods.
         checkConstConstraints();
       }
References DGtal::concepts::CStack< T >::checkConstConstraints(), DGtal::concepts::CStack< T >::myV, DGtal::concepts::CStack< T >::myX, and DGtal::concepts::ConceptUtils::sameType().
checkConstConstraints()
template<typename T > void DGtal::concepts::CStack< T >::checkConstConstraints () const inline
Definition at line 107 of file CStack.h.
       {
         concepts::ConceptUtils::sameType( myS, myX.size() );
         concepts::ConceptUtils::sameType( myB, myX.empty() );
         concepts::ConceptUtils::sameType( myV, myX.top() );
       }
References DGtal::concepts::CStack< T >::myB, DGtal::concepts::CStack< T >::myS, DGtal::concepts::CStack< T >::myV, DGtal::concepts::CStack< T >::myX, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::concepts::CStack< T >::BOOST_CONCEPT_USAGE().
Field Documentation
myB
template<typename T > bool DGtal::concepts::CStack< T >::myB private
Definition at line 118 of file CStack.h.
Referenced by DGtal::concepts::CStack< T >::checkConstConstraints().
myS
template<typename T > Size DGtal::concepts::CStack< T >::myS private
Definition at line 117 of file CStack.h.
Referenced by DGtal::concepts::CStack< T >::checkConstConstraints().
myV
template<typename T > Value DGtal::concepts::CStack< T >::myV private
Definition at line 116 of file CStack.h.
Referenced by DGtal::concepts::CStack< T >::BOOST_CONCEPT_USAGE(), and DGtal::concepts::CStack< T >::checkConstConstraints().
myX
template<typename T > T DGtal::concepts::CStack< T >::myX private
Definition at line 115 of file CStack.h.
Referenced by DGtal::concepts::CStack< T >::BOOST_CONCEPT_USAGE(), and DGtal::concepts::CStack< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CStack.h