DGtal: DGtal::IntegerConverter< dim, DGtal::BigInteger > Struct Template Reference
DGtal::IntegerConverter< dim, DGtal::BigInteger > Struct Template Reference
#include <DGtal/kernel/IntegerConverter.h>
Public Types
typedef DGtal::BigInteger Integer
Static Public Member Functions
static DGtal::BigInteger cast (DGtal::int32_t i)
static PointVector< dim, DGtal::BigInteger > cast (PointVector< dim, DGtal::int32_t > p)
static DGtal::BigInteger cast (DGtal::int64_t i)
static PointVector< dim, DGtal::BigInteger > cast (PointVector< dim, DGtal::int64_t > p)
static DGtal::BigInteger cast (DGtal::BigInteger i)
static PointVector< dim, DGtal::BigInteger > cast (PointVector< dim, DGtal::BigInteger > p)
Detailed Description
template<DGtal::Dimension dim>
struct DGtal::IntegerConverter< dim, DGtal::BigInteger >
Allows seamless conversion of integral types and lattice points, while checking for errors when going from a more precise to a less precise type.
Specialized version for BigInteger
Template Parameters
dim static constant of type DGtal::Dimension that specifies the static dimension of the space and thus the number of elements of the Point or Vector.
Definition at line 321 of file IntegerConverter.h.
Member Typedef Documentation
Integer
template<DGtal::Dimension dim> typedef DGtal::BigInteger DGtal::IntegerConverter< dim, DGtal::BigInteger >::Integer
Definition at line 322 of file IntegerConverter.h.
Member Function Documentation
cast() [1/6]
template<DGtal::Dimension dim> static DGtal::BigInteger DGtal::IntegerConverter< dim, DGtal::BigInteger >::cast (DGtal::BigInteger i) inline static
Parameters
i any integer
Returns
the same integer
Definition at line 370 of file IntegerConverter.h.
     {
       return i;
     }
cast() [2/6]
template<DGtal::Dimension dim> static DGtal::BigInteger DGtal::IntegerConverter< dim, DGtal::BigInteger >::cast (DGtal::int32_t i) inline static
Parameters
i any integer
Returns
the same integer
Definition at line 326 of file IntegerConverter.h.
     {
       return DGtal::BigInteger( i );
     }
cast() [3/6]
template<DGtal::Dimension dim> static DGtal::BigInteger DGtal::IntegerConverter< dim, DGtal::BigInteger >::cast (DGtal::int64_t i) inline static
Parameters
i any integer
Returns
the same integer
Definition at line 347 of file IntegerConverter.h.
     {
       DGtal::BigInteger tmp;
       detail::mpz_set_sll( tmp.get_mpz_t(), i );
       return tmp;
     }
References DGtal::detail::mpz_set_sll().
cast() [4/6]
template<DGtal::Dimension dim> static PointVector< dim, DGtal::BigInteger > DGtal::IntegerConverter< dim, DGtal::BigInteger >::cast (PointVector< dim, DGtal::BigInteger > p) inline static
Conversion of a lattice point.
Parameters
p any point
Returns
the same point
Definition at line 381 of file IntegerConverter.h.
     {
       return p;
     }
cast() [5/6]
template<DGtal::Dimension dim> static PointVector< dim, DGtal::BigInteger > DGtal::IntegerConverter< dim, DGtal::BigInteger >::cast (PointVector< dim, DGtal::int32_t > p) inline static
Conversion of a lattice point.
Parameters
p any point
Returns
the same point
Definition at line 337 of file IntegerConverter.h.
     {
       PointVector< dim, DGtal::BigInteger > q;
       for ( DGtal::Dimension i = 0; i < dim; i++ )
         q[ i ] = cast( p[ i ] );
       return q;
     }
References DGtal::IntegerConverter< dim, TInteger >::cast(), and dim().
cast() [6/6]
template<DGtal::Dimension dim> static PointVector< dim, DGtal::BigInteger > DGtal::IntegerConverter< dim, DGtal::BigInteger >::cast (PointVector< dim, DGtal::int64_t > p) inline static
Conversion of a lattice point.
Parameters
p any point
Returns
the same point
Definition at line 360 of file IntegerConverter.h.
     {
       PointVector< dim, DGtal::BigInteger > q;
       for ( DGtal::Dimension i = 0; i < dim; i++ )
         q[ i ] = cast( p[ i ] );
       return q;
     }
References DGtal::IntegerConverter< dim, TInteger >::cast(), and dim().
The documentation for this struct was generated from the following file:
IntegerConverter.h