DGtal: DGtal::details::NumberTraitsImplFundamental< T > Struct Template Reference
DGtal::details::NumberTraitsImplFundamental< T > Struct Template Reference
NumberTraits common part for fundamental integer and floating-point types.
#include <DGtal/kernel/NumberTraits.h>
Public Types
using IsBounded = typename BoolToTag< NL::is_bounded >::type
Is the number bounded.
using IsUnsigned = typename BoolToTag<!NL::is_signed >::type
Is the number unsigned.
using IsSigned = typename BoolToTag< NL::is_signed >::type
Is the number signed.
using IsIntegral = typename BoolToTag< NL::is_integer >::type
Is the number of integral type.
using IsSpecialized = TagTrue
Is that a number type with specific traits.
using ReturnType = T
Alias to the type that should be used as return type.
using ParamType = typename boost::call_traits< T >::param_type
Defines a type that represents the "best" way to pass a parameter of type T to a function.
Static Public Member Functions
static constexpr ReturnType zero () noexcept
Return the zero of this integer.
static constexpr ReturnType one () noexcept
Return the one of this integer.
static constexpr ReturnType min () noexcept
Return the minimum possible value for this type of number.
static constexpr ReturnType max () noexcept
Return the maximum possible value for this type of number.
static constexpr unsigned int digits () noexcept
Return the number of significant binary digits for this type of number.
static constexpr BoundEnum isBounded () noexcept
Return the bounding type of the number.
static constexpr SignEnum isSigned () noexcept
Return the sign type of the number.
static constexpr DGtal::int64_t castToInt64_t (const T &aT) noexcept
Cast method to DGtal::int64_t (for I/O or board export uses only).
static constexpr double castToDouble (const T &aT) noexcept
Cast method to double (for I/O or board export uses only).
static constexpr bool even (ParamType aT) noexcept
Check the parity of a number.
static constexpr bool odd (ParamType aT) noexcept
Check the parity of a number.
Static Public Attributes
static constexpr T ZERO = T(0)
Constant Zero.
static constexpr T ONE = T(1)
Constant One.
Private Types
using NL = std::numeric_limits< T >
Type alias to std::numeric_limits.
Detailed Description
template<typename T>
struct DGtal::details::NumberTraitsImplFundamental< T >
NumberTraits common part for fundamental integer and floating-point types.
Definition at line 203 of file NumberTraits.h.
Member Typedef Documentation
IsBounded
template<typename T > using DGtal::details::NumberTraitsImplFundamental< T >::IsBounded = typename BoolToTag<NL::is_bounded>::type
Is the number bounded.
Definition at line 210 of file NumberTraits.h.
IsIntegral
template<typename T > using DGtal::details::NumberTraitsImplFundamental< T >::IsIntegral = typename BoolToTag<NL::is_integer>::type
Is the number of integral type.
Definition at line 213 of file NumberTraits.h.
IsSigned
template<typename T > using DGtal::details::NumberTraitsImplFundamental< T >::IsSigned = typename BoolToTag<NL::is_signed>::type
Is the number signed.
Definition at line 212 of file NumberTraits.h.
IsSpecialized
template<typename T > using DGtal::details::NumberTraitsImplFundamental< T >::IsSpecialized = TagTrue
Is that a number type with specific traits.
Definition at line 214 of file NumberTraits.h.
IsUnsigned
template<typename T > using DGtal::details::NumberTraitsImplFundamental< T >::IsUnsigned = typename BoolToTag<!NL::is_signed>::type
Is the number unsigned.
Definition at line 211 of file NumberTraits.h.
NL
template<typename T > using DGtal::details::NumberTraitsImplFundamental< T >::NL = std::numeric_limits<T> private
Type alias to std::numeric_limits.
Definition at line 206 of file NumberTraits.h.
ParamType
template<typename T > using DGtal::details::NumberTraitsImplFundamental< T >::ParamType = typename boost::call_traits<T>::param_type
Defines a type that represents the "best" way to pass a parameter of type T to a function.
Definition at line 221 of file NumberTraits.h.
ReturnType
template<typename T > using DGtal::details::NumberTraitsImplFundamental< T >::ReturnType = T
Alias to the type that should be used as return type.
Definition at line 216 of file NumberTraits.h.
Member Function Documentation
castToDouble()
template<typename T > static constexpr double DGtal::details::NumberTraitsImplFundamental< T >::castToDouble (const T & aT) inline static constexpr noexcept
Cast method to double (for I/O or board export uses only).
Definition at line 299 of file NumberTraits.h.
       {
         return static_cast<double>(aT);
       }
castToInt64_t()
template<typename T > static constexpr DGtal::int64_t DGtal::details::NumberTraitsImplFundamental< T >::castToInt64_t (const T & aT) inline static constexpr noexcept
Cast method to DGtal::int64_t (for I/O or board export uses only).
Definition at line 289 of file NumberTraits.h.
       {
         return static_cast<DGtal::int64_t>(aT);
       }
digits()
template<typename T > static constexpr unsigned int DGtal::details::NumberTraitsImplFundamental< T >::digits () inline static constexpr noexcept
Return the number of significant binary digits for this type of number.
Definition at line 259 of file NumberTraits.h.
       {
         return static_cast<unsigned int>(NL::digits);
       }
even()
template<typename T > static constexpr bool DGtal::details::NumberTraitsImplFundamental< T >::even (ParamType aT) inline static constexpr noexcept
Check the parity of a number.
Parameters
aT any number.
Returns
'true' iff the number is even.
Definition at line 310 of file NumberTraits.h.
       {
         return ( aT & ONE ) == ZERO;
       }
References DGtal::details::NumberTraitsImplFundamental< T >::ONE, and DGtal::details::NumberTraitsImplFundamental< T >::ZERO.
isBounded()
template<typename T > static constexpr BoundEnum DGtal::details::NumberTraitsImplFundamental< T >::isBounded () inline static constexpr noexcept
Return the bounding type of the number.
Returns
BOUNDED, UNBOUNDED, or BOUND_UNKNOWN.
Definition at line 269 of file NumberTraits.h.
       {
         return NL::is_bounded ? BOUNDED : UNBOUNDED;
       }
References DGtal::BOUNDED, and DGtal::UNBOUNDED.
isSigned()
template<typename T > static constexpr SignEnum DGtal::details::NumberTraitsImplFundamental< T >::isSigned () inline static constexpr noexcept
Return the sign type of the number.
Returns
SIGNED, UNSIGNED or SIGN_UNKNOWN.
Definition at line 279 of file NumberTraits.h.
       {
         return NL::is_signed ? SIGNED : UNSIGNED;
       }
References DGtal::SIGNED, and DGtal::UNSIGNED.
max()
template<typename T > static constexpr ReturnType DGtal::details::NumberTraitsImplFundamental< T >::max () inline static constexpr noexcept
Return the maximum possible value for this type of number.
Definition at line 252 of file NumberTraits.h.
       {
         return NL::max();
       }
References max().
min()
template<typename T > static constexpr ReturnType DGtal::details::NumberTraitsImplFundamental< T >::min () inline static constexpr noexcept
Return the minimum possible value for this type of number.
Definition at line 245 of file NumberTraits.h.
       {
         return NL::min();
       }
odd()
template<typename T > static constexpr bool DGtal::details::NumberTraitsImplFundamental< T >::odd (ParamType aT) inline static constexpr noexcept
Check the parity of a number.
Parameters
aT any number.
Returns
'true' iff the number is odd.
Definition at line 321 of file NumberTraits.h.
       {
         return ( aT & ONE ) != ZERO;
       }
References DGtal::details::NumberTraitsImplFundamental< T >::ONE, and DGtal::details::NumberTraitsImplFundamental< T >::ZERO.
one()
template<typename T > static constexpr ReturnType DGtal::details::NumberTraitsImplFundamental< T >::one () inline static constexpr noexcept
Return the one of this integer.
Definition at line 238 of file NumberTraits.h.
       {
         return ONE;
       }
References DGtal::details::NumberTraitsImplFundamental< T >::ONE.
zero()
template<typename T > static constexpr ReturnType DGtal::details::NumberTraitsImplFundamental< T >::zero () inline static constexpr noexcept
Return the zero of this integer.
Definition at line 231 of file NumberTraits.h.
       {
         return ZERO;
       }
References DGtal::details::NumberTraitsImplFundamental< T >::ZERO.
Field Documentation
ONE
template<typename T > constexpr T DGtal::details::NumberTraitsImplFundamental< T >::ONE = T(1) static constexpr
Constant One.
Definition at line 227 of file NumberTraits.h.
Referenced by DGtal::details::NumberTraitsImplFundamental< T >::even(), DGtal::details::NumberTraitsImplFundamental< T >::odd(), and DGtal::details::NumberTraitsImplFundamental< T >::one().
ZERO
template<typename T > constexpr T DGtal::details::NumberTraitsImplFundamental< T >::ZERO = T(0) static constexpr
Constant Zero.
Definition at line 224 of file NumberTraits.h.
Referenced by DGtal::details::NumberTraitsImplFundamental< T >::even(), DGtal::details::NumberTraitsImplFundamental< T >::odd(), and DGtal::details::NumberTraitsImplFundamental< T >::zero().
The documentation for this struct was generated from the following file:
NumberTraits.h