DGtal: DGtal::concepts::C3DParametricCurveDecorator< T > Struct Template Reference
DGtal::concepts::C3DParametricCurveDecorator< T > Struct Template Reference
DGtal Concepts
Aim:
#include <DGtal/geometry/curves/parametric/C3DParametricCurve.h>
Public Member Functions
BOOST_CONCEPT_USAGE (C3DParametricCurveDecorator)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::concepts::C3DParametricCurve< T >
BOOST_CONCEPT_ASSERT ((concepts::CSpace< Space >))
BOOST_STATIC_ASSERT ((Space::dimension==3))
BOOST_CONCEPT_USAGE (C3DParametricCurve)
Protected Attributes
T self
T::TypeCurve curve
Protected Attributes inherited from DGtal::concepts::C3DParametricCurve< T >
T self
RealPoint x
Point y
double c
Additional Inherited Members
Public Types inherited from DGtal::concepts::C3DParametricCurve< T >
typedef T::Space Space
typedef T::RealPoint RealPoint
typedef T::Point Point
Detailed Description
template<typename T>
struct DGtal::concepts::C3DParametricCurveDecorator< T >
Aim:
Description of concept '3DParametricCurveDecorator'
Refinement of 3DParametricCurve
Associated types
Notation
X : A type that is a model of DParametricCurveDecorator
x, y : object of type X
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
Invariants
Models
A dummy model (for concept checking) is C3DParametricCurveDecoratorArchtype.
Notes
Template Parameters
T the type that should be a model of 3DParametricCurve.
Definition at line 155 of file C3DParametricCurve.h.
Member Function Documentation
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::C3DParametricCurveDecorator< T >::BOOST_CONCEPT_USAGE (C3DParametricCurveDecorator< T >) inline
Definition at line 160 of file C3DParametricCurve.h.
   {
     // check const methods.
     checkConstConstraints();
   }
References DGtal::concepts::C3DParametricCurveDecorator< T >::checkConstConstraints().
checkConstConstraints()
template<typename T > void DGtal::concepts::C3DParametricCurveDecorator< T >::checkConstConstraints () const inline virtual
Reimplemented from DGtal::concepts::C3DParametricCurve< T >.
Definition at line 165 of file C3DParametricCurve.h.
   {
     ConceptUtils::sameType( curve, self.curve );
   }
References DGtal::concepts::C3DParametricCurveDecorator< T >::curve, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::concepts::C3DParametricCurveDecorator< T >::BOOST_CONCEPT_USAGE().
Field Documentation
curve
template<typename T > T::TypeCurve DGtal::concepts::C3DParametricCurveDecorator< T >::curve protected
Definition at line 172 of file C3DParametricCurve.h.
Referenced by DGtal::concepts::C3DParametricCurveDecorator< T >::checkConstConstraints().
self
template<typename T > T DGtal::concepts::C3DParametricCurveDecorator< T >::self protected
Definition at line 171 of file C3DParametricCurve.h.
The documentation for this struct was generated from the following file:
C3DParametricCurve.h