DGtal: DGtal::concepts::CImageCacheReadPolicy< T > Struct Template Reference
DGtal::concepts::CImageCacheReadPolicy< T > Struct Template Reference
DGtal Concepts
Aim: Defines the concept describing a cache read policy.
#include <DGtal/images/CImageCacheReadPolicy.h>
Public Types
typedef T::ImageContainer ImageContainer
Public Member Functions
BOOST_CONCEPT_USAGE (CImageCacheReadPolicy)
void checkConstConstraints () const
Private Attributes
T myT
ImageContainer * myIC
T::Point myPoint
T::Domain myDomain
Detailed Description
template<typename T>
struct DGtal::concepts::CImageCacheReadPolicy< T >
Aim: Defines the concept describing a cache read policy.
Description of concept 'CImageCacheReadPolicy'
Refinement of
Associated types
ImageContainer : type of the image in the cache, model of concept CImage
Point : type of the image point
Domain : type of the image domain, model of concept CDomain
Notation
X : A type that is a model of CImageCacheReadPolicy
x : object of type X
p : object of type Point
d : object of type Domain
Definitions
Valid expressions and semantics
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
Get page x.getPage(p) p of type Point ImageContainer p should be in a domain of the cache get the alias on the image that contains the point p
Get page x.getPage(d) d of type Domain ImageContainer d should be in a domain of the cache get the alias on the image that matchs the domain d
Get page to detach x.getPageToDetach() ImageContainer get the alias on the image that we have to detach
Update cache x.updateCache(d) d of type Domain update the cache with a new Domain d
Clear cache x.clearCache() clear the cache
Invariants
Models
ImageCacheReadPolicyLAST, ImageCacheReadPolicyFIFO
Notes
Template Parameters
T the type that should be a model of CImageCacheReadPolicy.
Definition at line 93 of file CImageCacheReadPolicy.h.
Member Typedef Documentation
ImageContainer
template<typename T > typedef T::ImageContainer DGtal::concepts::CImageCacheReadPolicy< T >::ImageContainer
Definition at line 98 of file CImageCacheReadPolicy.h.
Member Function Documentation
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CImageCacheReadPolicy< T >::BOOST_CONCEPT_USAGE (CImageCacheReadPolicy< T >) inline
Definition at line 100 of file CImageCacheReadPolicy.h.
     {
         ConceptUtils::sameType( myIC, myT.getPage(myDomain) );
         ConceptUtils::sameType( myIC, myT.getPage(myPoint) );
         ConceptUtils::sameType( myIC, myT.getPageToDetach() );
         myT.updateCache(myDomain);
         myT.clearCache();
         // check const methods.
         checkConstConstraints();
     }
References DGtal::concepts::CImageCacheReadPolicy< T >::checkConstConstraints(), DGtal::concepts::CImageCacheReadPolicy< T >::myDomain, DGtal::concepts::CImageCacheReadPolicy< T >::myIC, DGtal::concepts::CImageCacheReadPolicy< T >::myPoint, DGtal::concepts::CImageCacheReadPolicy< T >::myT, and DGtal::concepts::ConceptUtils::sameType().
checkConstConstraints()
template<typename T > void DGtal::concepts::CImageCacheReadPolicy< T >::checkConstConstraints () const inline
Definition at line 112 of file CImageCacheReadPolicy.h.
     {
     }
Referenced by DGtal::concepts::CImageCacheReadPolicy< T >::BOOST_CONCEPT_USAGE().
Field Documentation
myDomain
template<typename T > T::Domain DGtal::concepts::CImageCacheReadPolicy< T >::myDomain private
Definition at line 121 of file CImageCacheReadPolicy.h.
Referenced by DGtal::concepts::CImageCacheReadPolicy< T >::BOOST_CONCEPT_USAGE().
myIC
template<typename T > ImageContainer* DGtal::concepts::CImageCacheReadPolicy< T >::myIC private
Definition at line 119 of file CImageCacheReadPolicy.h.
Referenced by DGtal::concepts::CImageCacheReadPolicy< T >::BOOST_CONCEPT_USAGE().
myPoint
template<typename T > T::Point DGtal::concepts::CImageCacheReadPolicy< T >::myPoint private
Definition at line 120 of file CImageCacheReadPolicy.h.
Referenced by DGtal::concepts::CImageCacheReadPolicy< T >::BOOST_CONCEPT_USAGE().
myT
template<typename T > T DGtal::concepts::CImageCacheReadPolicy< T >::myT private
Definition at line 118 of file CImageCacheReadPolicy.h.
Referenced by DGtal::concepts::CImageCacheReadPolicy< T >::BOOST_CONCEPT_USAGE().
The documentation for this struct was generated from the following file:
CImageCacheReadPolicy.h