DGtal: LibBoard::QuadraticBezierCurve Struct Reference
LibBoard::QuadraticBezierCurve Struct Reference
A quadratic Bezier curve having 3 control points. NB. It is also a parabola arc.
#include <Board/Shapes.h>
Public Member Functions
QuadraticBezierCurve (double x1, double y1, double x2, double y2, double x3, double y3, DGtal::Color pen, DGtal::Color fill, double lineWidth, const LineStyle style=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depthValue=-1)
void flushPostscript (std::ostream &stream, const TransformEPS &transform) const
void flushFIG (std::ostream &stream, const TransformFIG &transform, std::map< DGtal::Color, int > &colormap) const
void flushSVG (std::ostream &stream, const TransformSVG &transform) const
void flushCairo (cairo_t *cr, const TransformCairo &transform) const
void flushTikZ (std::ostream &stream, const TransformTikZ &transform) const
const std::string & name () const
Public Member Functions inherited from LibBoard::Triangle
Triangle (const Point &p1, const Point &p2, const Point &p3, DGtal::Color pen, DGtal::Color fill, double lineWidth, const LineStyle style=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depthValue=-1)
Triangle (const double x1, const double y1, const double x2, const double y2, const double x3, const double y3, DGtal::Color pen, DGtal::Color fill, double lineWidth, const LineStyle style=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depthValue=-1)
Triangle rotated (double angle) const
Triangle translated (double dx, double dy) const
Triangle scaled (double sx, double sy) const
Triangle scaled (double s) const
Triangle * clone () const
Public Member Functions inherited from LibBoard::Polyline
Polyline (const std::vector< Point > &points, bool closed, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
Polyline (const Path &path, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
Polyline (bool closed, DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, const LineStyle lineStyle=SolidStyle, const LineCap cap=ButtCap, const LineJoin join=MiterJoin, int depth=-1)
Point center () const
Polyline & operator<< (const Point &p)
Point & operator[] (const unsigned int n)
Polyline & rotate (double angle, const Point &center)
Polyline rotated (double angle, const Point &center) const
Polyline & rotate (double angle)
Polyline rotated (double angle) const
Polyline & translate (double dx, double dy)
Polyline translated (double dx, double dy) const
Shape & scale (double sx, double sy)
Shape & scale (double s)
Polyline scaled (double sx, double sy) const
Polyline scaled (double s) const
void scaleAll (double s)
Rect boundingBox () const
Public Member Functions inherited from LibBoard::Shape
Shape (DGtal::Color penColor, DGtal::Color fillColor, double lineWidth, LineStyle style, const LineCap cap, const LineJoin join, int depth)
virtual ~Shape ()
bool filled () const
Shape & rotateDeg (double angle, const Point &center)
Shape & rotateDeg (double angle)
Rect bbox ()
Shape & operator-- ()
Shape & operator++ ()
int depth () const
virtual void depth (int)
virtual void shiftDepth (int shift)
const DGtal::Color & penColor () const
const DGtal::Color & fillColor () const
Static Private Attributes
static const std::string _name
Additional Inherited Members
Public Types inherited from LibBoard::Shape
enum LineCap { ButtCap = 0 , RoundCap , SquareCap }
enum LineJoin { MiterJoin = 0 , RoundJoin , BevelJoin }
enum LineStyle {
SolidStyle = 0 , DashStyle , DotStyle , DashDotStyle ,
DashDotDotStyle , DashDotDotDotStyle
}
Protected Member Functions inherited from LibBoard::Shape
std::string svgProperties (const TransformSVG &transform) const
std::string postscriptProperties () const
void setCairoDashStyle (cairo_t *cr, LineStyle type) const
std::string tikzProperties (const TransformTikZ &transform) const
Protected Attributes inherited from LibBoard::Polyline
Path _path
Protected Attributes inherited from LibBoard::Shape
int _depth
DGtal::Color _penColor
DGtal::Color _fillColor
double _lineWidth
LineStyle _lineStyle
LineCap _lineCap
LineJoin _lineJoin
Detailed Description
A quadratic Bezier curve having 3 control points. NB. It is also a parabola arc.
Definition at line 1160 of file Board/Shapes.h.
Constructor & Destructor Documentation
QuadraticBezierCurve()
LibBoard::QuadraticBezierCurve::QuadraticBezierCurve (double x1, double y1, double x2, double y2, double x3, double y3, DGtal::Color pen, DGtal::Color fill, double lineWidth, const LineStyle style = SolidStyle, const LineCap cap = ButtCap, const LineJoin join = MiterJoin, int depthValue = -1) inline
Constructs a curve.
Parameters
x1 First coordinate of the start point.
y1 Second coordinate of the start point.
x2 First coordinate of the middle point.
y2 Second coordinate of the middle point.
x3 First coordinate of the end point.
y3 Second coordinate of the end point.
pen Color of the curve.
fill Color of the interior.
lineWidth The line thickness.
style Curve style
cap Curve cap
join Curve join
depthValue The depth of the line.
Definition at line 1179 of file Board/Shapes.h.
     : Triangle(x1, y1, x2, y2, x3, y3, pen, fill, lineWidth, style, cap, join, depthValue) {}
Member Function Documentation
flushCairo()
void LibBoard::QuadraticBezierCurve::flushCairo (cairo_t * cr, const TransformCairo & transform) const virtual
Writes the cairo code of the shape in a cairo drawing context according to a transform.
Parameters
cr The cairo drawing context.
transform A 2D transform to be applied.
Reimplemented from LibBoard::Polyline.
Definition at line 2448 of file Shapes.cpp.
 {
   double x1, y1, x2, y2, x3, y3, x4, y4; //coordinates of the control points
   _path[ 0 ].get(x1, y1);
   _path[ 1 ].get(x3, y3);
   _path[ 2 ].get(x4, y4);
   //we compute the two middle control points of a cubic Bezier curve
   //from the three control points of the quadratic Bezier curve
   x2 = x1 + 2/3.0*(x3-x1);
   y2 = y1 + 2/3.0*(y3-y1);
   x3 = x2 + 1/3.0*(x4-x1);
   y3 = y2 + 1/3.0*(y4-y1);
   cairo_save (cr);
   cairo_set_source_rgba (cr, _fillColor.red()/255.0, _fillColor.green()/255.0, _fillColor.blue()/255.0, 1.);
   cairo_move_to( cr, transform.mapX( x1 ), transform.mapY( y1 ) );
   cairo_curve_to( cr, transform.mapX( x2 ), transform.mapY( y2 ),
                   transform.mapX( x3 ), transform.mapY( y3 ),
                   transform.mapX( x4 ), transform.mapY( y4 ) );
   if ( filled() )
     {
       if ( _penColor != DGtal::Color::None )
         cairo_fill_preserve (cr);
       else
         cairo_fill (cr);
     }
   if ( _penColor != DGtal::Color::None )
     {
       cairo_set_source_rgba (cr, _penColor.red()/255.0, _penColor.green()/255.0, _penColor.blue()/255.0, 1.);
       cairo_set_line_width (cr, _lineWidth);
       cairo_set_line_cap (cr, cairoLineCap[_lineCap]);
       cairo_set_line_join (cr, cairoLineJoin[_lineJoin]);
       setCairoDashStyle (cr, _lineStyle);
       cairo_stroke (cr);
     }
   cairo_restore (cr);
 }
References LibBoard::Shape::_fillColor, LibBoard::Shape::_lineCap, LibBoard::Shape::_lineJoin, LibBoard::Shape::_lineStyle, LibBoard::Shape::_lineWidth, LibBoard::Polyline::_path, LibBoard::Shape::_penColor, DGtal::Color::blue(), LibBoard::Shape::filled(), DGtal::Color::green(), DGtal::Color::None, DGtal::Color::red(), and LibBoard::Shape::setCairoDashStyle().
flushFIG()
void LibBoard::QuadraticBezierCurve::flushFIG (std::ostream & stream, const TransformFIG & transform, std::map< DGtal::Color, int > & colormap) const virtual
Writes the FIG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
colormap A colormap.
Reimplemented from LibBoard::Polyline.
Definition at line 2416 of file Shapes.cpp.
 {
   stream << "#FIXME: quadratic Bezier curve unimplemented" << std::endl;
   Triangle::flushFIG(stream, transform, colormap);
 }
References LibBoard::Polyline::flushFIG().
flushPostscript()
void LibBoard::QuadraticBezierCurve::flushPostscript (std::ostream & stream, const TransformEPS & transform) const virtual
Writes the EPS code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Reimplemented from LibBoard::Polyline.
Definition at line 2366 of file Shapes.cpp.
 {
   double x1, y1, x2, y2, x3, y3, x4, y4; //coordinates of the control points
   _path[ 0 ].get(x1, y1);
   _path[ 1 ].get(x3, y3);
   _path[ 2 ].get(x4, y4);
   //we compute the two middle control points of a cubic Bezier curve
   //from the three control points of the quadratic Bezier curve
   x2 = x1 + 2/3.0*(x3-x1);
   y2 = y1 + 2/3.0*(y3-y1);
   x3 = x2 + 1/3.0*(x4-x1);
   y3 = y2 + 1/3.0*(y4-y1);
   stream << std::endl << "% Bezier curve" << std::endl;
   if ( _fillColor != DGtal::Color::None ) {
     stream << "n "
            << transform.mapX( x1 ) << " "
            << transform.mapY( y1 ) << " "
            << "m "
            << transform.mapX( x2 ) << " "
            << transform.mapY( y2 ) << " "
            << transform.mapX( x3 ) << " "
            << transform.mapY( y3 ) << " "
            << transform.mapX( x4 ) << " "
            << transform.mapY( y4 ) << " "
            << "curveto ";
       _fillColor.flushPostscript( stream );
       stream << " " << postscriptProperties();
       stream << " fill" << std::endl;
   }
   if ( _penColor != DGtal::Color::None ) {
     stream << " " << postscriptProperties() << " ";
     stream << "n "
            << transform.mapX( x1 ) << " "
            << transform.mapY( y1 ) << " "
            << "m "
            << transform.mapX( x2 ) << " "
            << transform.mapY( y2 ) << " "
            << transform.mapX( x3 ) << " "
            << transform.mapY( y3 ) << " "
            << transform.mapX( x4 ) << " "
            << transform.mapY( y4 ) << " "
            << "curveto ";
     _penColor.flushPostscript( stream );
     stream << " stroke" << std::endl;
   }
 }
References LibBoard::Shape::_fillColor, LibBoard::Polyline::_path, LibBoard::Shape::_penColor, DGtal::Color::flushPostscript(), DGtal::Color::None, and LibBoard::Shape::postscriptProperties().
flushSVG()
void LibBoard::QuadraticBezierCurve::flushSVG (std::ostream & stream, const TransformSVG & transform) const virtual
Writes the SVG code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Reimplemented from LibBoard::Polyline.
Definition at line 2425 of file Shapes.cpp.
 {
   double x1, y1, x2, y2, x3, y3; //coordinates of the control points
   _path[ 0 ].get(x1, y1);
   _path[ 1 ].get(x2, y2);
   _path[ 2 ].get(x3, y3);
   stream << "<path ";
   stream << svgProperties( transform ) << " ";
   //first point
   stream << "d='M " << transform.mapX( x1 );
   stream << "," << transform.mapY( y1 );
   //arc
   stream << " Q " << transform.mapX( x2 ) << "," << transform.mapY( y2 );
   //last point
   stream << " " << transform.mapX( x3 );
   stream << "," << transform.mapY( y3 );
   stream << "' />";
 }
References LibBoard::Polyline::_path, and LibBoard::Shape::svgProperties().
flushTikZ()
void LibBoard::QuadraticBezierCurve::flushTikZ (std::ostream & stream, const TransformTikZ & transform) const virtual
Writes the TikZ code of the shape in a stream according to a transform.
Parameters
stream The output stream.
transform A 2D transform to be applied.
Reimplemented from LibBoard::Polyline.
Definition at line 2496 of file Shapes.cpp.
 {
   double x1, y1, x2, y2, x3, y3, x4, y4; //coordinates of the control points
   _path[ 0 ].get(x1, y1);
   _path[ 1 ].get(x3, y3);
   _path[ 2 ].get(x4, y4);
   //we compute the two middle control points of a cubic Bezier curve
   //from the three control points of the quadratic Bezier curve
   x2 = x1 + 2/3.0*(x3-x1);
   y2 = y1 + 2/3.0*(y3-y1);
   x3 = x2 + 1/3.0*(x4-x1);
   y3 = y2 + 1/3.0*(y4-y1);
   stream << "\\draw[" << tikzProperties(transform) << "] ("
          << transform.mapX( x1 ) << ',' << transform.mapY( y1 )
          << ") .. controls ("
          << transform.mapX( x2 ) << ',' << transform.mapY( y2 )
          << ") and ("
          << transform.mapX( x3 ) << ',' << transform.mapY( y3 )
          << ") .. ("
          << transform.mapX( x4 ) << ',' << transform.mapY( y4 )
          << ");" << std::endl;
 }
References LibBoard::Polyline::_path, and LibBoard::Shape::tikzProperties().
name()
const std::string & LibBoard::QuadraticBezierCurve::name () const virtual
Returns the name of the shape (QuadraticBezierCurve)
Returns
object name
Reimplemented from LibBoard::Triangle.
Definition at line 2360 of file Shapes.cpp.
 {
     return _name;
 }
References _name.
Field Documentation
_name
const std::string LibBoard::QuadraticBezierCurve::_name static private
name of the shape.
Definition at line 1215 of file Board/Shapes.h.
Referenced by name().
The documentation for this struct was generated from the following files:
Board/Shapes.h
Shapes.cpp