DGtal: DGtal::detail::SetFunctionsImpl< Container, true, false > Struct Template Reference
DGtal::detail::SetFunctionsImpl< Container, true, false > Struct Template Reference
#include <DGtal/base/SetFunctions.h>
Static Public Member Functions
static bool isEqual (const Container &S1, const Container &S2)
static bool isSubset (const Container &S1, const Container &S2)
static Container & assignDifference (Container &S1, const Container &S2)
static Container & assignUnion (Container &S1, const Container &S2)
static Container & assignIntersection (Container &S1, const Container &S2)
static Container & assignSymmetricDifference (Container &S1, const Container &S2)
Detailed Description
template<typename Container>
struct DGtal::detail::SetFunctionsImpl< Container, true, false >
Specialization for associative, unordered containers (unordered_set, unordered_map).
Definition at line 392 of file SetFunctions.h.
Member Function Documentation
assignDifference()
template<typename Container > static Container& DGtal::detail::SetFunctionsImpl< Container, true, false >::assignDifference (Container & S1, const Container & S2) inline static
Updates the set S1 as S1 - S2. This version does not use the fact that the container is ordered.
Parameters
[in,out] S1 an input set, S1 - S2 as output.
[in] S2 another input set.
Definition at line 444 of file SetFunctions.h.
       {
         typedef ComparatorAdapter< Container, true, false,
                                    IsPairAssociativeContainer< Container >::value >
           CompAdapter;
         for ( typename Container::const_iterator it = S2.begin(),
                 itE = S2.end(); it != itE; ++it )
           S1.erase( CompAdapter::key( *it ) );
         return S1;
       }
assignIntersection()
template<typename Container > static Container& DGtal::detail::SetFunctionsImpl< Container, true, false >::assignIntersection (Container & S1, const Container & S2) inline static
Updates the set S1 as \(S1 \cap S2 \). This version does not use the fact that the container is ordered.
Parameters
[in,out] S1 an input set, \(S1 \cap S2 \) as output.
[in] S2 another input set.
Definition at line 477 of file SetFunctions.h.
       {
         typedef ComparatorAdapter< Container, true, false,
                                    IsPairAssociativeContainer< Container >::value >
           CompAdapter;
         for ( typename Container::iterator it = S1.begin(),
                 itE = S1.end(); it != itE; )
           {
             typename Container::iterator itNext = it; ++itNext;
             if ( S2.find( CompAdapter::key( *it ) ) == S2.end() )
               S1.erase( CompAdapter::key( *it ) );
             it = itNext;
           }
         return S1;
       }
assignSymmetricDifference()
template<typename Container > static Container& DGtal::detail::SetFunctionsImpl< Container, true, false >::assignSymmetricDifference (Container & S1, const Container & S2) inline static
Updates the set S1 as \(S1 \Delta S2 \). This version does not use the fact that the container is ordered.
Parameters
[in,out] S1 an input set, \(S1 \Delta S2 \) as output.
[in] S2 another input set.
Definition at line 500 of file SetFunctions.h.
       {
         Container S12( S1 );
         assignIntersection( S12, S2 );
         assignUnion( S1, S2 );
         return assignDifference( S1, S12 );
       }
References DGtal::detail::SetFunctionsImpl< Container, associative, ordered >::assignDifference(), DGtal::detail::SetFunctionsImpl< Container, associative, ordered >::assignIntersection(), and DGtal::detail::SetFunctionsImpl< Container, associative, ordered >::assignUnion().
assignUnion()
template<typename Container > static Container& DGtal::detail::SetFunctionsImpl< Container, true, false >::assignUnion (Container & S1, const Container & S2) inline static
Updates the set S1 as \(S1 \cup S2 \). This version does not use the fact that the container is ordered.
Parameters
[in,out] S1 an input set, \(S1 \cup S2 \) as output.
[in] S2 another input set.
Definition at line 462 of file SetFunctions.h.
       {
         typename Container::iterator itS1 = S1.end();
         for ( typename Container::const_iterator it = S2.begin(),
                 itE = S2.end(); it != itE; ++it )
           itS1 = S1.insert( itS1, *it );
         return S1;
       }
isEqual()
template<typename Container > static bool DGtal::detail::SetFunctionsImpl< Container, true, false >::isEqual (const Container & S1, const Container & S2) inline static
Equality test. This version does not use the fact that the container is ordered.
Parameters
[in] S1 an input set.
[in] S2 another input set.
Returns
true iff S1 is equal to S2 (seen as sets).
Definition at line 402 of file SetFunctions.h.
       {
         typedef ComparatorAdapter< Container, true, false,
                                    IsPairAssociativeContainer< Container >::value >
           CompAdapter;
         // Checks size first.
         if ( S1.size() != S2.size() ) return false;
         // Note that it is critical here that all elements are distinct.
         for ( typename Container::const_iterator it = S1.begin(),
                 itE = S1.end(); it != itE; ++it )
           if ( S2.find( CompAdapter::key( *it ) ) == S2.end() ) return false;
         return true;
       }
isSubset()
template<typename Container > static bool DGtal::detail::SetFunctionsImpl< Container, true, false >::isSubset (const Container & S1, const Container & S2) inline static
Inclusion test. This version does not use the fact that the container is ordered.
Parameters
[in] S1 an input set.
[in] S2 another input set.
Returns
true iff S1 is a subset of S2.
Definition at line 424 of file SetFunctions.h.
       {
         typedef ComparatorAdapter< Container, true, false,
                                    IsPairAssociativeContainer< Container >::value >
           CompAdapter;
         // Checks size first.
         if ( S1.size() > S2.size() ) return false;
         for ( typename Container::const_iterator it = S1.begin(),
                 itE = S1.end(); it != itE; ++it )
           if ( S2.find( CompAdapter::key( *it ) ) == S2.end() ) return false;
         return true;
       }
The documentation for this struct was generated from the following file:
SetFunctions.h