DGtal: DGtal::concepts::CImplicitFunctionDiff1< T > Struct Template Reference
DGtal::concepts::CImplicitFunctionDiff1< T > Struct Template Reference
DGtal Concepts
Aim: Describes a 1-differentiable function of the form f(x), where x is some real point in the given space, and f(x) is some value.
#include <DGtal/shapes/implicit/CImplicitFunctionDiff1.h>
Public Types
typedef T::RealPoint RealPoint
typedef T::RealVector RealVector
Public Types inherited from DGtal::concepts::CImplicitFunction< T >
typedef T::RealPoint RealPoint
typedef T::Value Value
Public Member Functions
BOOST_CONCEPT_USAGE (CImplicitFunctionDiff1)
void checkConstConstraints () const
Public Member Functions inherited from DGtal::concepts::CImplicitFunction< T >
BOOST_CONCEPT_ASSERT ((boost::UnaryFunction< T, Value, RealPoint >))
Private Attributes
T myX
RealPoint myA
RealVector myB
Detailed Description
template<typename T>
struct DGtal::concepts::CImplicitFunctionDiff1< T >
Aim: Describes a 1-differentiable function of the form f(x), where x is some real point in the given space, and f(x) is some value.
Description of concept 'CImplicitFunctionDiff1'
Refinement of CImplicitFunction
Associated types
RealPoint: the type for the domain
RealVector: the type for a vector in the domain
Value: the type for the range
Notation
X : A type that is a model of CImplicitFunctionDiff1
f : objet of type X
a : objet of type RealPoint
Definitions
Valid expressions and
Name Expression Type requirements Return type Precondition Semantics Post condition Complexity
gradient operator gradient(a) RealVector Evaluates the gradient of the function f at point a
Invariants
Models
ImplicitPolynomial3Shape
Notes
Template Parameters
T the type that should be a model of CImplicitFunctionDiff1.
Definition at line 92 of file CImplicitFunctionDiff1.h.
Member Typedef Documentation
RealPoint
template<typename T > typedef T::RealPoint DGtal::concepts::CImplicitFunctionDiff1< T >::RealPoint
Definition at line 97 of file CImplicitFunctionDiff1.h.
RealVector
template<typename T > typedef T::RealVector DGtal::concepts::CImplicitFunctionDiff1< T >::RealVector
Definition at line 98 of file CImplicitFunctionDiff1.h.
Member Function Documentation
BOOST_CONCEPT_USAGE()
template<typename T > DGtal::concepts::CImplicitFunctionDiff1< T >::BOOST_CONCEPT_USAGE (CImplicitFunctionDiff1< T >) inline
Definition at line 100 of file CImplicitFunctionDiff1.h.
     {
       // check const methods.
       checkConstConstraints();
     }
References DGtal::concepts::CImplicitFunctionDiff1< T >::checkConstConstraints().
checkConstConstraints()
template<typename T > void DGtal::concepts::CImplicitFunctionDiff1< T >::checkConstConstraints () const inline
Definition at line 105 of file CImplicitFunctionDiff1.h.
     {
       // const method dummyConst should take parameter myA of type A and return
       // something of type B
       ConceptUtils::sameType( myB, myX.gradient( myA ) );
     }
References DGtal::concepts::CImplicitFunctionDiff1< T >::myA, DGtal::concepts::CImplicitFunctionDiff1< T >::myB, DGtal::concepts::CImplicitFunctionDiff1< T >::myX, and DGtal::concepts::ConceptUtils::sameType().
Referenced by DGtal::concepts::CImplicitFunctionDiff1< T >::BOOST_CONCEPT_USAGE().
Field Documentation
myA
template<typename T > RealPoint DGtal::concepts::CImplicitFunctionDiff1< T >::myA private
Definition at line 114 of file CImplicitFunctionDiff1.h.
Referenced by DGtal::concepts::CImplicitFunctionDiff1< T >::checkConstConstraints().
myB
template<typename T > RealVector DGtal::concepts::CImplicitFunctionDiff1< T >::myB private
Definition at line 115 of file CImplicitFunctionDiff1.h.
Referenced by DGtal::concepts::CImplicitFunctionDiff1< T >::checkConstConstraints().
myX
template<typename T > T DGtal::concepts::CImplicitFunctionDiff1< T >::myX private
Definition at line 113 of file CImplicitFunctionDiff1.h.
Referenced by DGtal::concepts::CImplicitFunctionDiff1< T >::checkConstConstraints().
The documentation for this struct was generated from the following file:
CImplicitFunctionDiff1.h