DGtal: testHistogram.cpp File Reference
testHistogram.cpp File Reference
DGtal Test Files
#include <iostream>
#include <vector>
#include "DGtal/math/Statistic.h"
#include "DGtal/math/Histogram.h"
Functions
double getRandomNumber (double first, double last)
bool testHistogramUniform ()
bool testHistogramGaussian ()
bool testHistogramGaussian2 ()
int main (int, char **)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2013/10/25
Functions for testing class Histogram.
This file is part of the DGtal library.
Definition in file testHistogram.cpp.
Function Documentation
getRandomNumber()
double getRandomNumber (double first, double last)
Example of a test. To be completed.
Definition at line 48 of file testHistogram.cpp.
 {
   double v = ((double)rand()) / (double) RAND_MAX;
   return v * ( last - first ) + first;
 }
Referenced by testHistogramGaussian(), testHistogramGaussian2(), and testHistogramUniform().
main()
int main (int , char **)
Definition at line 116 of file testHistogram.cpp.
 {
   trace.beginBlock ( "Testing class Histogram" );
   bool res = testHistogramUniform()
     && testHistogramGaussian()
     && testHistogramGaussian2();
   trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
   trace.endBlock();
   return res ? 0 : 1;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), testHistogramGaussian(), testHistogramGaussian2(), testHistogramUniform(), and DGtal::trace.
testHistogramGaussian()
bool testHistogramGaussian ()
Definition at line 73 of file testHistogram.cpp.
 {
   unsigned int nbok = 0;
   unsigned int nb = 0;
   Statistic<double> stat( true );
   for(unsigned int k=0; k < 1000; k++)
     stat.addValue( getRandomNumber( -1.0, 1.0 ) + getRandomNumber( -1.0, 1.0 ) );
   stat.terminate();
   Histogram<double> hist;
   hist.init( Histogram<double>::Scott, stat );
   hist.addValues( stat.begin(), stat.end() );
   hist.terminate();
   for ( unsigned int i = 0; i < hist.size(); ++i )
     std::cout << i << " " << hist.pdf( i ) << " " << hist.cdf( i ) << std::endl;
   ++nb; nbok += hist.cdf( hist.size()-1 ) > 0.9999 ? 1 : 0;
   return nbok == nb;
 }
References DGtal::Statistic< TQuantity >::addValue(), DGtal::Histogram< TQuantity, TBinner >::addValues(), DGtal::Statistic< TQuantity >::begin(), DGtal::Histogram< TQuantity, TBinner >::cdf(), DGtal::Statistic< TQuantity >::end(), getRandomNumber(), DGtal::Histogram< TQuantity, TBinner >::init(), DGtal::Histogram< TQuantity, TBinner >::pdf(), DGtal::Histogram< TQuantity, TBinner >::size(), DGtal::Histogram< TQuantity, TBinner >::terminate(), and DGtal::Statistic< TQuantity >::terminate().
Referenced by main().
testHistogramGaussian2()
bool testHistogramGaussian2 ()
Definition at line 92 of file testHistogram.cpp.
 {
   unsigned int nbok = 0;
   unsigned int nb = 0;
   Statistic<double> stat( true );
   for(unsigned int k=0; k < 1000; k++)
     stat.addValue( getRandomNumber( -1.0, 1.0 ) + getRandomNumber( -1.0, 1.0 )
                    + getRandomNumber( -1.0, 1.0 ) );
   stat.terminate();
   Histogram<double> hist;
   hist.init( Histogram<double>::Scott, stat );
   hist.addValues( stat.begin(), stat.end() );
   hist.terminate();
   for ( unsigned int i = 0; i < hist.size(); ++i )
     std::cout << i << " " << hist.pdf( i ) << " " << hist.cdf( i ) << std::endl;
   ++nb; nbok += hist.cdf( hist.size()-1 ) > 0.9999 ? 1 : 0;
   return nbok == nb;
 }
References DGtal::Statistic< TQuantity >::addValue(), DGtal::Histogram< TQuantity, TBinner >::addValues(), DGtal::Statistic< TQuantity >::begin(), DGtal::Histogram< TQuantity, TBinner >::cdf(), DGtal::Statistic< TQuantity >::end(), getRandomNumber(), DGtal::Histogram< TQuantity, TBinner >::init(), DGtal::Histogram< TQuantity, TBinner >::pdf(), DGtal::Histogram< TQuantity, TBinner >::size(), DGtal::Histogram< TQuantity, TBinner >::terminate(), and DGtal::Statistic< TQuantity >::terminate().
Referenced by main().
testHistogramUniform()
bool testHistogramUniform ()
Definition at line 54 of file testHistogram.cpp.
 {
   unsigned int nbok = 0;
   unsigned int nb = 0;
   Statistic<double> stat( true );
   for(unsigned int k=0; k < 1000; k++)
     stat.addValue( getRandomNumber( -1.0, 1.0 ) );
   stat.terminate();
   Histogram<double> hist;
   hist.init( Histogram<double>::Scott, stat );
   hist.addValues( stat.begin(), stat.end() );
   hist.terminate();
   for ( unsigned int i = 0; i < hist.size(); ++i )
     std::cout << i << " " << hist.pdf( i ) << " " << hist.cdf( i ) << std::endl;
   ++nb; nbok += hist.cdf( hist.size()-1 ) > 0.9999 ? 1 : 0;
   return nbok == nb;
 }
References DGtal::Statistic< TQuantity >::addValue(), DGtal::Histogram< TQuantity, TBinner >::addValues(), DGtal::Statistic< TQuantity >::begin(), DGtal::Histogram< TQuantity, TBinner >::cdf(), DGtal::Statistic< TQuantity >::end(), getRandomNumber(), DGtal::Histogram< TQuantity, TBinner >::init(), DGtal::Histogram< TQuantity, TBinner >::pdf(), DGtal::Histogram< TQuantity, TBinner >::size(), DGtal::Histogram< TQuantity, TBinner >::terminate(), and DGtal::Statistic< TQuantity >::terminate().
Referenced by main().