DGtal: testTrace.cpp File Reference
testTrace.cpp File Reference
DGtal Test Files
#include <cstdio>
#include <cmath>
#include <iostream>
#include <fstream>
#include "DGtal/base/Config.h"
#include "DGtal/base/Common.h"
Functions
void testSimple ()
void testIndent ()
void testFileStream ()
void testTimings ()
int main ()
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr)
Date
2009/12/13
This file is part of the DGtal library
Definition in file testTrace.cpp.
Function Documentation
main()
int main (void)
Definition at line 166 of file testTrace.cpp.
 {
     testSimple();
     testIndent();
     testFileStream();
     testTimings();
     return 0;
 }
References testFileStream(), testIndent(), testSimple(), and testTimings().
testFileStream()
void testFileStream ()
We test the Trace class on file stream.
a file "example.txt" must have been created with the traces.
Definition at line 88 of file testTrace.cpp.
 {
     trace.beginBlock("testFileStream");
     trace.info() << "Checking the filestream output.. Please check the 'example.txt' file"<<endl;
     ofstream myfile;
     myfile.open ("example.txt");
     TraceWriterFile traceWriterFile(myfile);
     Trace t2(traceWriterFile);
     t2.info()<< "This is an Info trace"<<endl;
     t2.warning()<< "This is an warning trace"<<endl;
     t2.error()<< "This is an Error trace"<<endl;
     t2.emphase()<< "This is an Emphased trace"<<endl;
     t2.beginBlock("FirstMethod");
     t2.info()<< "This is an Info trace, level 1"<<endl;
     t2.info()<< "This is an Info trace, level 1"<<endl;
     t2.endBlock();
     myfile.close();
     trace.endBlock();
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::error(), DGtal::Trace::info(), DGtal::trace, and DGtal::Trace::warning().
Referenced by main().
testIndent()
void testIndent ()
Definition at line 56 of file testTrace.cpp.
 {
     long tmp=0;
     trace.info()<< "This is an Info trace, level 0"<<endl;
     trace.beginBlock("FirstMethod");
     trace.info()<< "This is an Info trace, level 1"<<endl;
     trace.info()<< "This is an Info trace, level 1"<<endl;
     trace.beginBlock("SecondMethod");
     trace.warning()<< "This is an Warning trace, level 2"<<endl;
     trace.warning()<< "This is an Warning trace, level 2"<<endl;
     trace.info()<< "This is an Info trace, level 2"<<endl;
     trace.error()<< "This is an Error trace, level 2 (followed by a loop)"<<endl;
     for (unsigned int i=0 ; i< 450; i++)
         tmp = (long)cos((double)tmp+i);
     trace.endBlock();
     trace.info()<< "This is an Info trace, level 1 (followed by another loop)"<<endl;
     for (unsigned int i=0 ; i< 430; i++)
         tmp = (long)cos((double)tmp+i);
     trace.endBlock();
     trace.info()<< "This is an Info trace, level 0"<<endl<<endl;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::error(), DGtal::Trace::info(), DGtal::trace, and DGtal::Trace::warning().
Referenced by main().
testSimple()
void testSimple ()
Definition at line 47 of file testTrace.cpp.
 {
     trace.info()<< "This is an Info trace"<<endl;
     trace.warning()<< "This is an warning trace"<<endl;
     trace.error()<< "This is an Error trace"<<endl;
     trace.emphase()<< "This is an Emphased trace"<<endl;
     cerr<<endl;
 }
References DGtal::Trace::emphase(), DGtal::Trace::error(), DGtal::Trace::info(), DGtal::trace, and DGtal::Trace::warning().
Referenced by main().
testTimings()
void testTimings ()
Definition at line 115 of file testTrace.cpp.
 {
   size_t duration;
   trace.beginBlock("Level0");
   double tmp=1.0;
   trace.beginBlock("Level1");
   trace.info()<<"..."<<std::endl;
   for (unsigned int i=0 ; i< 4350; i++)
     tmp = (long)cos((double)tmp+i);
   duration = trace.endBlock();
   trace.beginBlock("Level1B");
   trace.info()<<"..."<<std::endl;
   for (unsigned int i=0 ; i< 4350; i++)
     tmp = (long)cos((double)tmp+i);
   trace.beginBlock("Level2");
   trace.info()<<"..."<<std::endl;
   for (unsigned int i=0 ; i< 4350; i++)
     tmp = (long)cos((double)tmp+i);
   duration += trace.endBlock();
   trace.beginBlock("Level2B");
   trace.info()<<"..."<<std::endl;
   for (unsigned int i=0 ; i< 4350; i++)
     tmp = (long)cos((double)tmp+i);
   duration += trace.endBlock();
   trace.beginBlock("Level2C");
   trace.info()<<"..."<<std::endl;
   for (unsigned int i=0 ; i< 4450; i++)
     tmp = (long)cos((double)tmp+i);
   duration += trace.endBlock();
   duration += trace.endBlock();
   trace.beginBlock("Level1C");
   trace.info()<<"..."<<std::endl;
   for (unsigned int i=0 ; i< 430; i++)
     tmp = (long)cos((double)tmp+i);
   duration += trace.endBlock();
   duration += trace.endBlock();
   trace.info()<<"Duration="<<duration<<std::endl;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.
Referenced by main().