DGtal: testDigitalTopology.cpp File Reference
testDigitalTopology.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/topology/MetricAdjacency.h"
#include "DGtal/topology/DigitalTopology.h"
Functions
bool testDigitalTopologyZ2 ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5807), University of Savoie, France
Date
2010/07/07
Functions for testing class DigitalTopology.
This file is part of the DGtal library.
Definition in file testDigitalTopology.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 75 of file testDigitalTopology.cpp.
 {
   trace.beginBlock ( "Testing class DigitalTopology" );
   trace.info() << "Args:";
   for ( int i = 0; i < argc; ++i )
     trace.info() << " " << argv[ i ];
   trace.info() << endl;
   bool res = testDigitalTopologyZ2(); // && ... other tests
   trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
   trace.endBlock();
   return res ? 0 : 1;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testDigitalTopologyZ2(), and DGtal::trace.
testDigitalTopologyZ2()
bool testDigitalTopologyZ2 ()
Example of a test. To be completed.
Definition at line 48 of file testDigitalTopology.cpp.
 {
   typedef SpaceND< 2 > Zi2;
   typedef MetricAdjacency< Zi2, 1 > Adj4;
   typedef MetricAdjacency< Zi2, 2 > Adj8;
   Adj4 adj4;
   Adj8 adj8;
   trace.beginBlock ( "Testing Digital topology (4,8) in Z2." );
   typedef DigitalTopology< Adj4, Adj8 > DT48;
   DT48 dt( adj4, adj8, JORDAN_DT );
   trace.info() << dt << std::endl;
   typedef DT48::ReverseTopology DT84;
   DT84 opp_dt = dt.reverseTopology();
   trace.info() << opp_dt << std::endl;
   trace.endBlock();
   // should not compile
   // typedef DigitalTopology< Adj4, bool > DTimpossible;
   // DTimpossible dti( adj4, true );
   return true;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::JORDAN_DT, and DGtal::trace.
Referenced by main().