DGtal: testLocalEstimatorFromFunctorAdapter.cpp File Reference
testLocalEstimatorFromFunctorAdapter.cpp File Reference
DGtal Test Files | DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "ConfigTest.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/base/BasicFunctors.h"
#include "DGtal/graph/GraphVisitorRange.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/io/Color.h"
#include "DGtal/io/colormaps/GradientColorMap.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/kernel/CanonicEmbedder.h"
#include "DGtal/topology/CanonicSCellEmbedder.h"
#include "DGtal/graph/DistanceBreadthFirstVisitor.h"
#include "DGtal/geometry/volumes/distance/LpMetric.h"
#include "DGtal/geometry/surfaces/estimation/LocalEstimatorFromSurfelFunctorAdapter.h"
#include "DGtal/geometry/surfaces/estimation/estimationFunctors/BasicEstimatorFromSurfelsFunctors.h"
#include "DGtal/geometry/surfaces/estimation/estimationFunctors/CLocalEstimatorFromSurfelFunctor.h"
#include "DGtal/topology/LightImplicitDigitalSurface.h"
#include "DGtal/topology/DigitalSurface.h"
#include "DGtal/geometry/surfaces/estimation/estimationFunctors/ElementaryConvolutionNormalVectorEstimator.h"
#include "DGtal/geometry/surfaces/estimation/estimationFunctors/MongeJetFittingGaussianCurvatureEstimator.h"
#include "DGtal/geometry/surfaces/estimation/estimationFunctors/MongeJetFittingMeanCurvatureEstimator.h"
#include "DGtal/geometry/surfaces/estimation/estimationFunctors/MongeJetFittingNormalVectorEstimator.h"
#include "DGtal/geometry/surfaces/estimation/estimationFunctors/LinearLeastSquareFittingNormalVectorEstimator.h"
Functions
bool testLocalEstimatorFromFunctorAdapter ()
bool testConcepts ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systemes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2013/05/28
Functions for testing class LocalEstimatorFromFunctorAdapter.
This file is part of the DGtal library.
Definition in file testLocalEstimatorFromFunctorAdapter.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 203 of file testLocalEstimatorFromFunctorAdapter.cpp.
 {
   trace.beginBlock ( "Testing class LocalEstimatorFromFunctorAdapter" );
   trace.info() << "Args:";
   for ( int i = 0; i < argc; ++i )
     trace.info() << " " << argv[ i ];
   trace.info() << endl;
   bool res = testConcepts() &&  testLocalEstimatorFromFunctorAdapter(); // && ... other tests
   trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
   trace.endBlock();
   return res ? 0 : 1;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testConcepts(), testLocalEstimatorFromFunctorAdapter(), and DGtal::trace.
testConcepts()
bool testConcepts ()
Definition at line 181 of file testLocalEstimatorFromFunctorAdapter.cpp.
 {
   typedef Z3i::KSpace::Surfel Surfel;
   typedef CanonicSCellEmbedder<Z3i::KSpace> Embedder;
   trace.beginBlock("Checking concepts");
   BOOST_CONCEPT_ASSERT(( concepts::CLocalEstimatorFromSurfelFunctor< functors::DummyEstimatorFromSurfels<Surfel,Embedder > >));
   BOOST_CONCEPT_ASSERT(( concepts::CLocalEstimatorFromSurfelFunctor< functors::ElementaryConvolutionNormalVectorEstimator<Surfel,Embedder > >));
 #ifdef WITH_CGAL
   BOOST_CONCEPT_ASSERT((  concepts::CLocalEstimatorFromSurfelFunctor< functors::MongeJetFittingNormalVectorEstimator<Surfel,Embedder > >));
   BOOST_CONCEPT_ASSERT((  concepts::CLocalEstimatorFromSurfelFunctor< functors::MongeJetFittingMeanCurvatureEstimator<Surfel,Embedder > >));
   BOOST_CONCEPT_ASSERT((  concepts::CLocalEstimatorFromSurfelFunctor< functors::MongeJetFittingGaussianCurvatureEstimator<Surfel,Embedder > >));
   BOOST_CONCEPT_ASSERT((  concepts::CLocalEstimatorFromSurfelFunctor< functors::LinearLeastSquareFittingNormalVectorEstimator<Surfel,Embedder > >));
 #endif
   trace.endBlock();
   return true;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), and DGtal::trace.
Referenced by main().
testLocalEstimatorFromFunctorAdapter()
bool testLocalEstimatorFromFunctorAdapter ()
Example of a test. To be completed.
Definition at line 96 of file testLocalEstimatorFromFunctorAdapter.cpp.
 {
   unsigned int nbok = 0;
   unsigned int nb = 0;
   trace.beginBlock ( "Testing init ..." );
   using namespace Z3i;
   typedef ImplicitDigitalEllipse3<Point> ImplicitDigitalEllipse;
   typedef LightImplicitDigitalSurface<KSpace,ImplicitDigitalEllipse> SurfaceContainer;
   typedef DigitalSurface< SurfaceContainer > Surface;
   typedef SurfaceContainer::SurfelConstIterator ConstIterator;
   typedef SurfaceContainer::Surfel Surfel;
   trace.beginBlock("Creating Surface");
   Point p1( -10, -10, -10 );
   Point p2( 10, 10, 10 );
   KSpace K;
   nbok += K.init( p1, p2, true ) ? 1 : 0;
   nb++;
   trace.info() << "(" << nbok << "/" << nb << ") "
                << "K.init() is ok" << std::endl;
   ImplicitDigitalEllipse ellipse( 6.0, 4.5, 3.4 );
   Surfel bel = Surfaces<KSpace>::findABel( K, ellipse, 10000 );
   SurfaceContainer* surfaceContainer = new SurfaceContainer
     ( K, ellipse, SurfelAdjacency<KSpace::dimension>( true ), bel );
   Surface surface( surfaceContainer ); // acquired
   unsigned int nbsurfels = 0;
   for ( ConstIterator it = surface.begin(), it_end = surface.end();
        it != it_end; ++it )
   {
     ++nbsurfels;
   }
   trace.info() << nbsurfels << " surfels found." << std::endl;
   trace.endBlock();
   trace.beginBlock("Creating  adapter");
   typedef DGtal::functors::DummyEstimatorFromSurfels<Surfel, CanonicSCellEmbedder<KSpace> > Functor;
   typedef DGtal::functors::ConstValue< double > ConvFunctor;
   typedef LocalEstimatorFromSurfelFunctorAdapter<SurfaceContainer, LpMetric<Z3i::Space>,
                                                  Functor, ConvFunctor> Reporter;
   typedef LocalEstimatorFromSurfelFunctorAdapter<SurfaceContainer, LpMetric<Z3i::Space>,
                                                  Functor, DGtal::functors::GaussianKernel> ReporterGaussian;
   LpMetric<Z3i::Space> l2(2.0);
   CanonicSCellEmbedder<KSpace> embedder(surface.container().space());
   Functor estimator(embedder, 1);
   ConvFunctor convFunc(1.0);
   Reporter reporter;
   reporter.attach(surface);
   reporter.setParams(l2,estimator,convFunc, 5);
   //We just test the init for Gaussian
   DGtal::functors::GaussianKernel gaussKernelFunc(1.0);
   ReporterGaussian reporterGaussian;
   reporterGaussian.attach(surface);
   reporterGaussian.setParams(l2,estimator,gaussKernelFunc, 5.0);
   reporterGaussian.init(1, surface.begin(), surface.end());
   reporter.init(1.0, surface.begin(), surface.end());
   Functor::Quantity val = reporter.eval( surface.begin() );
   trace.info() <<  "Value with radius 5= "<<val << std::endl;
   nbok += ((fabs((double)val - 124.0)) < 40) ? 1 : 0;
   nb++;
   reporter.setParams(l2,estimator,convFunc, 20.0);
   reporter.init(1, surface.begin(), surface.end());
   Functor::Quantity val2 = reporter.eval( surface.begin() );
   trace.info() <<  "Value with radius 20= "<<val2 << std::endl;
   nbok += ((fabs((double)val2 - 398.0)) < 120) ? 1 : 0;
   nb++;
   trace.endBlock();
   trace.endBlock();
   trace.info() << "(" << nbok << "/" << nb << ") "
                << "true == true" << std::endl;
   return nbok == nb;
 }
References DGtal::DigitalSurface< TDigitalSurfaceContainer >::begin(), DGtal::Trace::beginBlock(), DGtal::DigitalSurface< TDigitalSurfaceContainer >::container(), DGtal::DigitalSurface< TDigitalSurfaceContainer >::end(), DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), K, and DGtal::trace.
Referenced by main().