DGtal: testLemniscate2D.cpp File Reference
testLemniscate2D.cpp File Reference
DGtal Test Files
#include <iostream>
#include <random>
#include "DGtalCatch.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/shapes/parametric/Lemniscate2D.h"
Typedefs
typedef Z2i::Space Space
typedef Z2i::Point Point
typedef Z2i::RealPoint RealPoint
typedef Lemniscate2D< Space > Shape
Functions
double notNullValue (std::uniform_real_distribution< double > &unif, std::default_random_engine &re)
RealPoint notNullRealPoint (std::uniform_real_distribution< double > &unif, std::default_random_engine &re)
TEST_CASE ("Lemniscate2D")
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Adrien Krähenbühl (krahe.nosp@m.nbuh.nosp@m.l@uni.nosp@m.stra.nosp@m..fr) Laboratoire ICube, UMR 7357, Université de Strasbourg, France
Date
2019/07/18
Functions for testing the methods of the Lemniscate2D shape. In particular, test the x(), xp() and xpp() methods for cases leadind to a division by 0.
This file is part of the DGtal library.
Definition in file testLemniscate2D.cpp.
Typedef Documentation
Point
typedef Z2i::Point Point
Definition at line 45 of file testLemniscate2D.cpp.
RealPoint
typedef Z2i::RealPoint RealPoint
Definition at line 46 of file testLemniscate2D.cpp.
Shape
typedef Lemniscate2D<Space> Shape
Definition at line 48 of file testLemniscate2D.cpp.
Space
typedef Z2i::Space Space
Definition at line 44 of file testLemniscate2D.cpp.
Function Documentation
notNullRealPoint()
RealPoint notNullRealPoint (std::uniform_real_distribution< double > & unif, std::default_random_engine & re)
Definition at line 62 of file testLemniscate2D.cpp.
 {
   return RealPoint(notNullValue(unif,re),notNullValue(unif,re));
 }
References notNullValue(), re, and unif().
notNullValue()
double notNullValue (std::uniform_real_distribution< double > & unif, std::default_random_engine & re)
Definition at line 50 of file testLemniscate2D.cpp.
 {
   double res;
   do {
     res = unif(re);
   }
   while ( res == Approx(0.) );
   return res;
 }
References re, and unif().
Referenced by notNullRealPoint().
TEST_CASE()
TEST_CASE ("Lemniscate2D")
Definition at line 69 of file testLemniscate2D.cpp.
 {
   std::uniform_real_distribution<double> unif(-10000,10000);
   std::default_random_engine re;
   SECTION("center()")
     {
       const RealPoint center(unif(re),unif(re));
       Shape shape( center, unif(re) );
       REQUIRE( shape.center() == center );
     }
   SECTION("Lower and upper bounds")
     {
       Shape shape( unif(re), unif(re), unif(re) );
       REQUIRE( shape.getLowerBound() <= shape.getUpperBound() );
     }
   SECTION("x() with Pi parameter.")
     {
           Shape shape( unif(re), unif(re), unif(re) );
       REQUIRE_NOTHROW( shape.x(M_PI) );
     }
   SECTION("x() with Pi parameter -> division by 0.")
     {
           Shape shape( unif(re), unif(re), unif(re) );
       REQUIRE_NOTHROW( shape.x(M_PI) );
     }
   SECTION("xp() with Pi parameter -> division by 0.")
     {
           Shape shape( unif(re), unif(re), unif(re) );
       REQUIRE_NOTHROW( shape.xp(M_PI) );
     }
   SECTION("xpp() with Pi parameter -> division by 0.")
     {
           Shape shape( unif(re), unif(re), unif(re) );
       REQUIRE_NOTHROW( shape.xp(M_PI) );
     }
 }
References DGtal::Astroid2D< TSpace >::center(), DGtal::Astroid2D< TSpace >::getLowerBound(), DGtal::Astroid2D< TSpace >::getUpperBound(), re, REQUIRE(), SECTION(), unif(), DGtal::Astroid2D< TSpace >::x(), and DGtal::Astroid2D< TSpace >::xp().