DGtal: testRawReader.cpp File Reference
testRawReader.cpp File Reference
DGtal Test Files
#include "DGtalCatch.h"
#include <DGtal/base/Common.h>
#include <DGtal/kernel/SpaceND.h>
#include <DGtal/kernel/domains/HyperRectDomain.h>
#include <DGtal/images/ImageSelector.h>
#include <DGtal/io/readers/RawReader.h>
#include <DGtal/io/writers/RawWriter.h>
#include <DGtal/kernel/domains/Linearizer.h>
#include <ConfigTest.h>
#include <string>
Functions
template<typename Image >
void testImageOnRef (Image const &anImage)
template<DGtal::Dimension N>
void testRawReaderOnRef ()
template<typename Image >
void generateRefImage (Image &anImage, typename Image::Value aSeed)
template<DGtal::Dimension N, typename T , template< typename > class RawIO>
void testWriteAndRead (T aSeed)
TEST_CASE ("Checking RawReader with reference files in 2D", "[reader][2D][raw][raw32][uint32]")
TEST_CASE ("Checking RawReader with reference files in 3D", "[reader][3D][raw][raw32][uint32]")
TEST_CASE ("Checking writing & reading uint8 in 2D with generic IO", "[reader][writer][2D][raw][uint8]")
TEST_CASE ("Checking writing & reading uint8 in 2D with 8bits IO", "[reader][writer][2D][raw8][uint8]")
TEST_CASE ("Checking writing & reading int8 in 2D with generic IO", "[reader][writer][2D][raw][int8]")
TEST_CASE ("Checking writing & reading uint16 in 2D with generic IO", "[reader][writer][2D][raw][uint16]")
TEST_CASE ("Checking writing & reading uint16 in 2D with 16bits IO", "[reader][writer][2D][raw16][uint16]")
TEST_CASE ("Checking writing & reading int16 in 2D with generic IO", "[reader][writer][2D][raw][int16]")
TEST_CASE ("Checking writing & reading uint32 in 2D with generic IO", "[reader][writer][2D][raw][uint32]")
TEST_CASE ("Checking writing & reading uint32 in 2D with 32bits IO", "[reader][writer][2D][raw32][uint32]")
TEST_CASE ("Checking writing & reading int32 in 2D with generic IO", "[reader][writer][2D][raw][int32]")
TEST_CASE ("Checking writing & reading uint64 in 2D with generic IO", "[reader][writer][2D][raw][uint64]")
TEST_CASE ("Checking writing & reading int64 in 2D with generic IO", "[reader][writer][2D][raw][int64]")
TEST_CASE ("Checking writing & reading double in 1D with generic IO", "[reader][writer][1D][raw][double]")
TEST_CASE ("Checking writing & reading double in 2D with generic IO", "[reader][writer][2D][raw][double]")
TEST_CASE ("Checking writing & reading double in 3D with generic IO", "[reader][writer][3D][raw][double]")
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
David Coeurjolly (david.nosp@m..coe.nosp@m.urjol.nosp@m.ly@l.nosp@m.iris..nosp@m.cnrs.nosp@m..fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Roland Denis (rolan.nosp@m.d.de.nosp@m.nis@u.nosp@m.niv-.nosp@m.smb.f.nosp@m.r) LAboratory of MAthematics - LAMA (CNRS, UMR 5127), University of Savoie, France
Date
10/12/2015
Functions for testing class RawReader.
This file is part of the DGtal library.
Definition in file testRawReader.cpp.
Function Documentation
generateRefImage()
template<typename Image > void generateRefImage (Image & anImage, typename Image::Value aSeed)
Compares an image to a generated data.
Template Parameters
Image Image type.
Parameters
[out] anImage The image.
aSeed Seed for the generator.
Definition at line 130 of file testRawReader.cpp.
 {
   typedef typename Image::Domain  Domain;
   typedef typename Domain::Point  Point;
   const Domain  domain = anImage.domain();
   for ( typename Domain::ConstIterator it = domain.begin(), itEnd = domain.end(); it != itEnd; ++it )
     {
       const Point pt = *it;
       const typename Image::Value refValue = aSeed * Linearizer<Domain, RowMajorStorage>::getIndex( pt, domain );
       anImage.setValue( pt, refValue );
     }
 }
References DGtal::HyperRectDomain< TSpace >::begin(), DGtal::Image< TImageContainer >::domain(), domain, DGtal::HyperRectDomain< TSpace >::end(), and DGtal::Image< TImageContainer >::setValue().
Referenced by testWriteAndRead().
TEST_CASE() [1/16]
TEST_CASE ("Checking RawReader with reference files in 2D" , "" [reader][2D][raw][raw32][uint32])
Definition at line 246 of file testRawReader.cpp.
 {
   testRawReaderOnRef<2>();
 }
TEST_CASE() [2/16]
TEST_CASE ("Checking RawReader with reference files in 3D" , "" [reader][3D][raw][raw32][uint32])
Definition at line 251 of file testRawReader.cpp.
 {
   testRawReaderOnRef<3>();
 }
TEST_CASE() [3/16]
TEST_CASE ("Checking writing & reading double in 1D with generic IO" , "" [reader][writer][1D][raw][double])
Definition at line 316 of file testRawReader.cpp.
 {
   testWriteAndRead<1, double, RawIO>( 1.23456789 );
 }
TEST_CASE() [4/16]
TEST_CASE ("Checking writing & reading double in 2D with generic IO" , "" [reader][writer][2D][raw][double])
Definition at line 321 of file testRawReader.cpp.
 {
   testWriteAndRead<2, double, RawIO>( 1.23456789 );
 }
TEST_CASE() [5/16]
TEST_CASE ("Checking writing & reading double in 3D with generic IO" , "" [reader][writer][3D][raw][double])
Definition at line 326 of file testRawReader.cpp.
 {
   testWriteAndRead<3, double, RawIO>( 1.23456789 );
 }
TEST_CASE() [6/16]
TEST_CASE ("Checking writing & reading int16 in 2D with generic IO" , "" [reader][writer][2D][raw][int16])
Definition at line 283 of file testRawReader.cpp.
 {
   testWriteAndRead<2, DGtal::int16_t, RawIO>( 1 );
 }
TEST_CASE() [7/16]
TEST_CASE ("Checking writing & reading int32 in 2D with generic IO" , "" [reader][writer][2D][raw][int32])
Definition at line 299 of file testRawReader.cpp.
 {
   testWriteAndRead<2, DGtal::int32_t, RawIO>( 1 );
 }
TEST_CASE() [8/16]
TEST_CASE ("Checking writing & reading int64 in 2D with generic IO" , "" [reader][writer][2D][raw][int64])
Definition at line 310 of file testRawReader.cpp.
 {
   testWriteAndRead<2, DGtal::int64_t, RawIO>( 1 );
 }
TEST_CASE() [9/16]
TEST_CASE ("Checking writing & reading int8 in 2D with generic IO" , "" [reader][writer][2D][raw][int8])
Definition at line 267 of file testRawReader.cpp.
 {
   testWriteAndRead<2, DGtal::int8_t, RawIO>( 1 );
 }
TEST_CASE() [10/16]
TEST_CASE ("Checking writing & reading uint16 in 2D with 16bits IO" , "" [reader][writer][2D][raw16][uint16])
Definition at line 278 of file testRawReader.cpp.
 {
   testWriteAndRead<2, DGtal::uint16_t, RawIO>( 1 );
 }
TEST_CASE() [11/16]
TEST_CASE ("Checking writing & reading uint16 in 2D with generic IO" , "" [reader][writer][2D][raw][uint16])
Definition at line 273 of file testRawReader.cpp.
 {
   testWriteAndRead<2, DGtal::uint16_t, RawIO>( 1 );
 }
TEST_CASE() [12/16]
TEST_CASE ("Checking writing & reading uint32 in 2D with 32bits IO" , "" [reader][writer][2D][raw32][uint32])
Definition at line 294 of file testRawReader.cpp.
 {
   testWriteAndRead<2, DGtal::uint32_t, RawIO>( 1 );
 }
TEST_CASE() [13/16]
TEST_CASE ("Checking writing & reading uint32 in 2D with generic IO" , "" [reader][writer][2D][raw][uint32])
Definition at line 289 of file testRawReader.cpp.
 {
   testWriteAndRead<2, DGtal::uint32_t, RawIO>( 1 );
 }
TEST_CASE() [14/16]
TEST_CASE ("Checking writing & reading uint64 in 2D with generic IO" , "" [reader][writer][2D][raw][uint64])
Definition at line 305 of file testRawReader.cpp.
 {
   testWriteAndRead<2, DGtal::uint64_t, RawIO>( 1 );
 }
TEST_CASE() [15/16]
TEST_CASE ("Checking writing & reading uint8 in 2D with 8bits IO" , "" [reader][writer][2D][raw8][uint8])
Definition at line 262 of file testRawReader.cpp.
 {
   testWriteAndRead<2, DGtal::uint8_t, RawIO>( 1 );
 }
TEST_CASE() [16/16]
TEST_CASE ("Checking writing & reading uint8 in 2D with generic IO" , "" [reader][writer][2D][raw][uint8])
Definition at line 257 of file testRawReader.cpp.
 {
   testWriteAndRead<2, DGtal::uint8_t, RawIO>( 1 );
 }
testImageOnRef()
template<typename Image > void testImageOnRef (Image const & anImage)
Compares an image to the reference data.
Template Parameters
Image Image type.
Parameters
anImage The image to test.
Definition at line 62 of file testRawReader.cpp.
 {
   typedef typename Image::Domain  Domain;
   typedef typename Domain::Point  Point;
   // Checking domain
   INFO( "Checking domain" )
   REQUIRE( anImage.domain().lowerBound() == Point::diagonal(0) );
   REQUIRE( anImage.domain().upperBound() == Point::diagonal(4) );
   // Checking values
   INFO( "Checking values" )
   const Domain domain = anImage.domain();
   for ( typename Domain::ConstIterator it = domain.begin(), itEnd = domain.end(); it != itEnd; ++it )
     {
       const Point pt = *it;
       const unsigned int refValue =   anImage.dimension  == 2 ?
             1000000 * pt[0] * pt[1]
           : 250000  * pt[0] * pt[1] * pt[2];
       INFO( "At point " << pt );
       REQUIRE( anImage( pt ) == refValue );
     }
 }
References DGtal::HyperRectDomain< TSpace >::begin(), DGtal::Image< TImageContainer >::domain(), domain, DGtal::HyperRectDomain< TSpace >::end(), and REQUIRE().
Referenced by testRawReaderOnRef().
testRawReaderOnRef()
template<DGtal::Dimension N> void testRawReaderOnRef ()
Reads and compares a raw file to the reference data.
Template Parameters
N Dimension of the image.
Definition at line 93 of file testRawReader.cpp.
 {
   REQUIRE( N >= 2 );
   REQUIRE( N <= 3 );
   typedef SpaceND<N> Space;
   typedef HyperRectDomain<Space> Domain;
   typedef typename ImageSelector<Domain, unsigned int>::Type Image;
   typedef typename Domain::Vector  Vector;
   // Generating file name
   std::string fileName = testPath + "samples/";
   if ( N == 2)
     fileName += "raw32bits5x5.raw";
   else
     fileName += "raw32bits5x5x5.raw";
   // Reading file
   const Vector extent = Vector::diagonal(5);
   INFO( "Reading file with importRaw32" << fileName );
   Image imageRaw32 = RawReader<Image>::importRaw32( fileName, extent );
   testImageOnRef( imageRaw32 );
   INFO( "Reading file with importRaw" << fileName );
   Image imageRaw = RawReader<Image>::template importRaw< unsigned int >( fileName, extent );
   testImageOnRef( imageRaw );
 }
References REQUIRE(), and testImageOnRef().
testWriteAndRead()
template<DGtal::Dimension N, typename T , template< typename > class RawIO> void testWriteAndRead (T aSeed)
Checks reading a previously writed file.
Template Parameters
N Dimension of the image.
T Value type.
RawIO Class with writer and reader, templated by the image type.
Parameters
aSeed Seed to generate image values.
Definition at line 156 of file testRawReader.cpp.
 {
   typedef SpaceND<N> Space;
   typedef HyperRectDomain<Space> Domain;
   typedef typename ImageSelector<Domain, T>::Type Image;
   typedef typename Domain::Point  Point;
   Point upperPt;
   upperPt[ 0 ] = 8;
   for ( Dimension i = 1; i < N; ++i )
     upperPt[ i ] = upperPt[ i-1 ] * ( i == 1 ? 4 : 2 );
   const Domain domain( Point::diagonal(0), upperPt );
   Image refImage( domain );
   generateRefImage( refImage, aSeed );
   INFO( "Writing image" );
   RawIO<Image>::write( "export-raw-writer.raw", refImage );
   INFO( "Reading image" );
   Image image = RawIO<Image>::read( "export-raw-writer.raw", upperPt + Point::diagonal(1) );
   INFO( "Comparing image values" );
   for ( typename Domain::ConstIterator it = domain.begin(), itEnd = domain.end(); it != itEnd; ++it )
     {
       const Point pt = *it;
       INFO( "At point " << pt );
       REQUIRE( image( pt ) == refImage( pt ) );
     }
 }
References DGtal::HyperRectDomain< TSpace >::begin(), domain, DGtal::HyperRectDomain< TSpace >::end(), generateRefImage(), image(), refImage(), and REQUIRE().