DGtal: testArithmeticalDSSComputerOnSurfels.cpp File Reference
testArithmeticalDSSComputerOnSurfels.cpp File Reference
DGtal Test Files
#include <iostream>
#include <string>
#include <iterator>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/helpers/Shortcuts.h"
#include "DGtal/topology/DigitalSurface2DSlice.h"
#include "ConfigTest.h"
#include "DGtalCatch.h"
#include "DGtal/geometry/curves/ArithmeticalDSSComputer.h"
#include "DGtal/geometry/surfaces/ArithmeticalDSSComputerOnSurfels.h"
#include "DGtal/geometry/curves/SaturatedSegmentation.h"
Typedefs
using KSpace = Z3i::KSpace
using SH3 = Shortcuts< KSpace >
using Surfel = KSpace::SCell
using SegmentComputerOnSurfels = ArithmeticalDSSComputerOnSurfels< KSpace, std::vector< Surfel >::const_iterator, int, 4 >
using SegmentationSurfels = SaturatedSegmentation< SegmentComputerOnSurfels >
using SegmentComputer = ArithmeticalDSSComputer< std::vector< Z2i::Point >::const_iterator, int, 4 >
using Segmentation = SaturatedSegmentation< SegmentComputer >
Functions
std::pair< KSpace, Slice > getSlice (std::string const &shape="ellipsoid", double gridstep=1.0)
std::vector< Z2i::Point > extractPoints (SegmentComputerOnSurfels const &sc, Slice const &slice)
TEST_CASE ("Testing ArithmeticalDSSComputerOnSurfels")
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jocelyn Meyron (jocel.nosp@m.yn.m.nosp@m.eyron.nosp@m.@lir.nosp@m.is.cn.nosp@m.rs.f.nosp@m.r) Laboratoire d'InfoRmatique en Image et Systemes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date
2021/02/12
Functions for testing class DGtal::ArithmeticalDSSComputerOnSurfels.
This file is part of the DGtal library.
Definition in file testArithmeticalDSSComputerOnSurfels.cpp.
Typedef Documentation
KSpace
using KSpace = Z3i::KSpace
Examples
dec/exampleHeatLaplace.cpp, geometry/surfaces/dvcm-2d-curvature.cpp, geometry/surfaces/dvcm-3d.cpp, geometry/tools/exampleAlphaShape.cpp, topology/ctopo-2-3d.cpp, topology/ctopo-2.cpp, topology/cubical-complex-collapse.cpp, topology/khalimskySpaceScanner.cpp, and topology/trackImplicitPolynomialSurfaceToOFF.cpp.
Definition at line 48 of file testArithmeticalDSSComputerOnSurfels.cpp.
Segmentation
using Segmentation = SaturatedSegmentation<SegmentComputer>
Examples
geometry/curves/convex-and-concave-parts.cpp, geometry/curves/estimation/exampleLMST2D.cpp, geometry/curves/estimation/exampleLMST3D.cpp, and geometry/curves/exampleFrechetShortcut.cpp.
Definition at line 56 of file testArithmeticalDSSComputerOnSurfels.cpp.
SegmentationSurfels
using SegmentationSurfels = SaturatedSegmentation<SegmentComputerOnSurfels>
Definition at line 53 of file testArithmeticalDSSComputerOnSurfels.cpp.
SegmentComputer
using SegmentComputer = ArithmeticalDSSComputer<std::vector<Z2i::Point>::const_iterator, int, 4>
Examples
geometry/curves/estimation/exampleCurvature.cpp, geometry/curves/estimation/exampleLMST2D.cpp, geometry/curves/estimation/exampleLMST3D.cpp, and geometry/curves/exampleArithDSS3d.cpp.
Definition at line 55 of file testArithmeticalDSSComputerOnSurfels.cpp.
SegmentComputerOnSurfels
using SegmentComputerOnSurfels = ArithmeticalDSSComputerOnSurfels<KSpace, std::vector<Surfel>::const_iterator, int, 4>
Definition at line 52 of file testArithmeticalDSSComputerOnSurfels.cpp.
SH3
using SH3 = Shortcuts<KSpace>
Definition at line 49 of file testArithmeticalDSSComputerOnSurfels.cpp.
Surfel
using Surfel = KSpace::SCell
Examples
examples/tutorial-examples/polyhedralizer.cpp, geometry/curves/exampleGridCurve3d-2.cpp, geometry/surfaces/dvcm-3d.cpp, topology/digitalSurfaceSlice.cpp, topology/trackImplicitPolynomialSurfaceToOFF.cpp, tutorial-examples/AreaSurfaceEstimation-final.cpp, and tutorial-examples/polyhedralizer.cpp.
Definition at line 50 of file testArithmeticalDSSComputerOnSurfels.cpp.
Function Documentation
extractPoints()
std::vector<Z2i::Point> extractPoints (SegmentComputerOnSurfels const & sc, Slice const & slice)
Definition at line 94 of file testArithmeticalDSSComputerOnSurfels.cpp.
 {
     std::vector<Z2i::Point> points;
     auto initialPoints = sc.projectSurfel(slice.start);
     points.push_back(initialPoints.first);
     points.push_back(initialPoints.second);
     int currentIdx = 0;
     bool firstIt = true;
     for (auto sit = slice.contour.begin() + 1; sit != slice.contour.end(); ++sit)
     {
         Surfel s = *sit;
         auto projectedPoints = sc.projectSurfel(s);
         if (firstIt) {
             if (projectedPoints.first == points[currentIdx]) {
                 points.push_back(projectedPoints.second);
             } else if (projectedPoints.first == points[currentIdx + 1]) {
                 points.push_back(projectedPoints.second);
             } else if (projectedPoints.second == points[currentIdx]) {
                 points.push_back(projectedPoints.first);
             } else if (projectedPoints.second == points[currentIdx + 1]) {
                 points.push_back(projectedPoints.first);
             } else {
                 assert(false);
             }
             firstIt = false;
         } else {
             if (projectedPoints.first == points[currentIdx]) {
                 points.push_back(projectedPoints.second);
             } else if (projectedPoints.second == points[currentIdx]) {
                 points.push_back(projectedPoints.first);
             } else {
                 assert(false);
             }
         }
         currentIdx = points.size() - 1;
     }
     return points;
 }
References DGtal::ArithmeticalDSSComputerOnSurfels< TKSpace, TIterator, TInteger, adjacency >::projectSurfel().
Referenced by TEST_CASE().
getSlice()
std::pair<KSpace, Slice> getSlice (std::string const & shape = "ellipsoid", double gridstep = 1.0)
Definition at line 66 of file testArithmeticalDSSComputerOnSurfels.cpp.
 {
     using SurfaceSlice = DigitalSurface2DSlice<SH3::DigitalSurface::DigitalSurfaceTracker>;
     auto params = SH3::defaultParameters();
     params("polynomial", shape)("gridstep", gridstep);
     auto implicit_shape = SH3::makeImplicitShape3D(params);
     auto digitized_shape = SH3::makeDigitizedImplicitShape3D(implicit_shape, params);
     auto binary_image = SH3::makeBinaryImage(digitized_shape, params);
     auto kspace = SH3::getKSpace(binary_image, params);
     auto surface = SH3::makeDigitalSurface(binary_image, kspace, params);
     Surfel surfel = Surfaces<KSpace>::findABel(kspace, *binary_image, 10000);
     KSpace::DirIterator q1 = kspace.sDirs(surfel);
     Dimension dim1 = *q1, dim2 = kspace.sOrthDir(surfel);
     auto tracker = surface->container().newTracker(surfel);
     SurfaceSlice surfaceSlice(tracker, dim1);
     delete tracker;
     std::vector<Surfel> contour(surfaceSlice.begin(), surfaceSlice.end());
     Slice slice{dim1, dim2, surfel, contour};
     return { kspace, slice };
 }
References DGtal::Shortcuts< TKSpace >::defaultParameters(), DGtal::Shortcuts< TKSpace >::getKSpace(), DGtal::Shortcuts< TKSpace >::makeBinaryImage(), DGtal::Shortcuts< TKSpace >::makeDigitalSurface(), DGtal::Shortcuts< TKSpace >::makeDigitizedImplicitShape3D(), and DGtal::Shortcuts< TKSpace >::makeImplicitShape3D().
Referenced by TEST_CASE().
TEST_CASE()
TEST_CASE ("Testing ArithmeticalDSSComputerOnSurfels")
Definition at line 140 of file testArithmeticalDSSComputerOnSurfels.cpp.
 {
     // Construct and extract a slice of a digital surface
     KSpace kspace;
     Slice slice;
     std::tie(kspace, slice) = getSlice();
     // Do a segmentation using the surfel class
     SegmentComputerOnSurfels recognitionAlgorithmSurfels(kspace, slice.dim1, slice.dim2);
     SegmentationSurfels segmentationSurfels(slice.contour.begin(), slice.contour.end(), recognitionAlgorithmSurfels);
     // Extract the projected points
     std::vector<Z2i::Point> points = extractPoints(recognitionAlgorithmSurfels, slice);
     // Do a segmentation on the projected points
     SegmentComputer recognitionAlgorithm;
     Segmentation segmentation(points.begin(), points.end(), recognitionAlgorithm);
     // The two segmentations must be the same
     bool allEqual = true;
     auto segIt = segmentation.begin();
     auto segSurfelIt = segmentationSurfels.begin();
     while (segIt != segmentation.end() && segSurfelIt != segmentationSurfels.end()) {
         allEqual = allEqual && (segIt->primitive() == segSurfelIt->primitive());
         ++segIt;
         ++segSurfelIt;
     }
     REQUIRE(allEqual);
 }
References DGtal::SaturatedSegmentation< TSegmentComputer >::begin(), DGtal::SaturatedSegmentation< TSegmentComputer >::end(), extractPoints(), getSlice(), and REQUIRE().