DGtal: testBoard2DCustomStyle.cpp File Reference
testBoard2DCustomStyle.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/SpaceND.h"
#include "DGtal/kernel/domains/HyperRectDomain.h"
#include "DGtal/kernel/sets/DigitalSetBySTLVector.h"
#include "DGtal/kernel/sets/DigitalSetBySTLSet.h"
#include "DGtal/kernel/sets/DigitalSetSelector.h"
#include "DGtal/io/boards/Board2D.h"
Functions
bool testBoard2DCustomStyle ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
davidcoeurjolly (login) (Unknown) Unknown
Date
2010/10/24
Functions for testing class Board2DCustomStyle.
This file is part of the DGtal library.
Definition in file testBoard2DCustomStyle.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 114 of file testBoard2DCustomStyle.cpp.
 {
   trace.beginBlock ( "Testing class Board2DCustomStyle" );
   trace.info() << "Args:";
   for ( int i = 0; i < argc; ++i )
     trace.info() << " " << argv[ i ];
   trace.info() << endl;
   bool res = testBoard2DCustomStyle(); // && ... other tests
   trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
   trace.endBlock();
   return res ? 0 : 1;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testBoard2DCustomStyle(), and DGtal::trace.
testBoard2DCustomStyle()
bool testBoard2DCustomStyle ()
Example of a test. To be completed.
Definition at line 67 of file testBoard2DCustomStyle.cpp.
 {
   unsigned int nbok = 0;
   unsigned int nb = 0;
   typedef SpaceND<2> Z2;
   typedef HyperRectDomain<Z2> Domain;
   typedef Z2::Point Point;
   Point p1(  -10, -10  );
   Point p2(  10, 10  );
   Domain domain( p1, p2 );
   typedef DigitalSetSelector
     < Domain, BIG_DS + HIGH_ITER_DS + HIGH_BEL_DS >::Type SpecificSet;
   SpecificSet mySet( domain );
   Point c(  0, 0  );
   mySet.insert( c );
   Point d(  5, 2  );
   mySet.insert( d );
   Point e(  1, -3  );
   mySet.insert( e );
   Board2D board;
   board.setUnit(LibBoard::Board::UCentimeter);
   board << SetMode( domain.className(), "Grid" ) << domain
   << domain
   << mySet;
   board.saveSVG("testcustom-prev.svg");
   board.clear();
   board << SetMode( domain.className(), "Grid" ) << domain
   << domain
   << CustomStyle( mySet.className(), new MyDrawStyleCustomGreen )
   << mySet;
   board.saveSVG("testcustom-next.svg");
   return nbok == nb;
 }
References DGtal::BIG_DS, DGtal::HyperRectDomain< TSpace >::className(), LibBoard::Board::clear(), domain, DGtal::HIGH_BEL_DS, DGtal::HIGH_ITER_DS, LibBoard::Board::saveSVG(), LibBoard::Board::setUnit(), and LibBoard::Board::UCentimeter.
Referenced by main().