DGtal: testAngleLinearMinimizer.cpp File Reference
testAngleLinearMinimizer.cpp File Reference
DGtal Test Files
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/math/AngleLinearMinimizer.h"
#include "DGtal/io/boards/Board2D.h"
Functions
bool testAngleLinearMinimizer ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Bertrand Kerautret (kerau.nosp@m.tre@.nosp@m.loria.nosp@m..fr) LORIA (CNRS, UMR 7503), University of Nancy, France
Date
2011/09/01
Functions for testing class AngleLinearMinimizer.
This file is part of the DGtal library.
Definition in file testAngleLinearMinimizer.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 108 of file testAngleLinearMinimizer.cpp.
 {
   trace.beginBlock ( "Testing class AngleLinearMinimizer" );
   trace.info() << "Args:";
   for ( int i = 0; i < argc; ++i )
     trace.info() << " " << argv[ i ];
   trace.info() << endl;
   bool res = testAngleLinearMinimizer(); // && ... other tests
   trace.emphase() << ( res ? "Passed." : "Error." ) << endl;
   trace.endBlock();
   return res ? 0 : 1;
 }
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testAngleLinearMinimizer(), and DGtal::trace.
testAngleLinearMinimizer()
bool testAngleLinearMinimizer ()
Example of a test. To be completed.
[optimization]
[optimization]
Definition at line 47 of file testAngleLinearMinimizer.cpp.
 {
   unsigned int nbok = 0;
   unsigned int nb = 0;
   trace.beginBlock ( "Testing AngleLinearMinimizer ." );
   AngleLinearMinimizer alm;
   alm.init(10);
   alm.setIsCurveOpen(true);
   double valDec [10] = {0.8, 0.3, -0.2, -0.2, -0.1, -0.3, -3.0, -6.0,  -7.0, -8.0};
   double valDecMin [10] = {-0.5, -0.2, -0.5, -0.2, -0.1, -1.0, -1.2, -0.5,  -0.3, -0.2};
   double valDecMax [10] = {0.9, 0.3, 0.2, 1.2, 0.4, 1.0, 0.5, 0.2,  0.1, 0.3};
   for(unsigned int i=0; i<10; i++){
     AngleLinearMinimizer::ValueInfo &vi= alm.rw(i);
     double val = i + valDec[i];
     vi.value = val;
     vi.oldValue = val;
     vi.min = val + valDecMin[i];
     vi.max = val + valDecMax[i];
     vi.distToNext = 4.0;
     alm.rw(i)=vi;
   }
   double delta= alm.optimize();
   double aPrecision=0.00001;
   while(delta >aPrecision){
     delta= alm.optimize();
     cerr << "sum of displacements " << delta << endl;
   }
   cout << "# index distPos valInit valOpt valMin valMax  " << endl;
   double currentPos=0.0;
   cout << -1 << " "<< -4 << " " << 9+valDec[9]  <<  " " << alm.ro(9).value
        << " " << alm.ro(9).min << " " << alm.ro(9).max << endl ;
   for(unsigned int i=0; i<10; i++){
     AngleLinearMinimizer::ValueInfo vi= alm.ro(i);
     cout << i << " "<< currentPos << " " << i+ valDec[i] <<  " " << vi.value
          << " " << vi.min << " " << vi.max << endl ;
     currentPos+=vi.distToNext;
   }
   nbok += (abs(1.59999-alm.ro(0).value)<0.00001) && (abs(1.6-alm.ro(1).value)<0.00001) ? 1 : 0;
   nb++;
   trace.info() << "(" << nbok << "/" << nb << ") "
                << "true == true" << std::endl;
   Board2D aBoard;
   aBoard << alm;
   aBoard.saveEPS("tmp.eps");
   trace.endBlock();
   return nbok == nb;
 }
References DGtal::Trace::beginBlock(), DGtal::AngleLinearMinimizer::ValueInfo::distToNext, DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::AngleLinearMinimizer::init(), DGtal::AngleLinearMinimizer::ValueInfo::max, DGtal::AngleLinearMinimizer::ValueInfo::min, DGtal::AngleLinearMinimizer::ValueInfo::oldValue, DGtal::AngleLinearMinimizer::optimize(), DGtal::AngleLinearMinimizer::ro(), DGtal::AngleLinearMinimizer::rw(), LibBoard::Board::saveEPS(), DGtal::AngleLinearMinimizer::setIsCurveOpen(), DGtal::trace, and DGtal::AngleLinearMinimizer::ValueInfo::value.
Referenced by main().