DGtal: viewMarchingCubes.cpp File Reference
viewMarchingCubes.cpp File Reference
DGtal Examples
#include <iostream>
#include <queue>
#include "DGtal/base/Common.h"
#include "DGtal/kernel/CanonicEmbedder.h"
#include "DGtal/io/readers/VolReader.h"
#include "DGtal/images/ImageSelector.h"
#include "DGtal/images/imagesSetsUtils/SetFromImage.h"
#include "DGtal/images/ImageLinearCellEmbedder.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/topology/helpers/Surfaces.h"
#include "DGtal/topology/DigitalSurface.h"
#include "DGtal/topology/SetOfSurfels.h"
#include "DGtal/shapes/Mesh.h"
#include "DGtal/shapes/TriangulatedSurface.h"
#include "DGtal/shapes/MeshHelpers.h"
#include "DGtal/io/viewers/Viewer3D.h"
Functions
void usage (int, char **argv)
int main (int argc, char **argv)
Detailed Description
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2012/02/06
An example file named viewMarchingCubes to display an isosurface from a vol file.
This file is part of the DGtal library.
Definition in file viewMarchingCubes.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
[viewMarchingCubes-readVol]
[viewMarchingCubes-readVol]
[viewMarchingCubes-KSpace]
[viewMarchingCubes-KSpace]
[viewMarchingCubes-SurfelAdjacency]
[viewMarchingCubes-SurfelAdjacency]
[viewMarchingCubes-ExtractingSurface]
[viewMarchingCubes-ExtractingSurface]
[viewMarchingCubes-makingMesh]
[viewMarchingCubes-makingMesh]
Definition at line 55 of file viewMarchingCubes.cpp.
 {
   if ( argc < 5 )
     {
       usage( argc, argv );
       return 1;
     }
   std::string inputFilename = argv[ 1 ];
   unsigned int minThreshold = atoi( argv[ 2 ] );
   unsigned int maxThreshold = argc > 3 ? atoi( argv[ 3 ] ) : 255;
   bool intAdjacency = argc > 4 ? (atoi( argv[ 4 ] ) == 0) : true;
   typedef ImageSelector < Domain, int>::Type Image;
   trace.beginBlock( "Reading vol file into an image." );
   Image image = VolReader<Image>::importVol(inputFilename);
   DigitalSet set3d (image.domain());
   SetFromImage<DigitalSet>::append<Image>(set3d, image,
                                           minThreshold, maxThreshold);
   trace.endBlock();
   trace.beginBlock( "Construct the Khalimsky space from the image domain." );
   KSpace ks;
   bool space_ok = ks.init( image.domain().lowerBound(),
                            image.domain().upperBound(), true );
   if (!space_ok)
     {
       trace.error() << "Error in the Khamisky space construction."<<std::endl;
       return 2;
     }
   trace.endBlock();
   typedef SurfelAdjacency<KSpace::dimension> MySurfelAdjacency;
   MySurfelAdjacency surfAdj( intAdjacency ); // interior in all directions.
   trace.beginBlock( "Extracting boundary by scanning the space. " );
   typedef KSpace::SurfelSet SurfelSet;
   typedef SetOfSurfels< KSpace, SurfelSet > MySetOfSurfels;
   typedef DigitalSurface< MySetOfSurfels > MyDigitalSurface;
   MySetOfSurfels theSetOfSurfels( ks, surfAdj );
   Surfaces<KSpace>::sMakeBoundary( theSetOfSurfels.surfelSet(),
                                    ks, set3d,
                                    image.domain().lowerBound(),
                                    image.domain().upperBound() );
   MyDigitalSurface digSurf( theSetOfSurfels );
   trace.info() << "Digital surface has " << digSurf.size() << " surfels."
                << std::endl;
   trace.endBlock();
   trace.beginBlock( "Making triangulated surface. " );
   typedef CanonicEmbedder< Space >                                  TrivialEmbedder;
   typedef ImageLinearCellEmbedder< KSpace, Image, TrivialEmbedder > CellEmbedder;
   typedef CellEmbedder::Value                                       RealPoint;
   typedef TriangulatedSurface< RealPoint >                          TriMesh;
   typedef Mesh< RealPoint >                                         ViewMesh;
   typedef std::map< MyDigitalSurface::Vertex, TriMesh::Index >      VertexMap;
   TriMesh         trimesh;
   ViewMesh        viewmesh;
   TrivialEmbedder trivialEmbedder;
   CellEmbedder    cellEmbedder;
   // The +0.5 is to avoid isosurface going exactly through a voxel
   // center, especially for binary volumes.
   cellEmbedder.init( ks, image, trivialEmbedder,
                      ( (double) minThreshold ) + 0.5 );
   VertexMap vmap; // stores the map Vertex -> Index
   MeshHelpers::digitalSurface2DualTriangulatedSurface
     ( digSurf, cellEmbedder, trimesh, vmap );
   trace.info() << "Triangulated surface is " << trimesh << std::endl;
   MeshHelpers::triangulatedSurface2Mesh( trimesh, viewmesh );
   trace.info() << "Mesh has " << viewmesh.nbVertex()
                << " vertices and " << viewmesh.nbFaces() << " faces." << std::endl;
   trace.endBlock();
   QApplication application(argc,argv);
   Viewer3D<> viewer;
   viewer.show();
   viewer.setLineColor(Color(150,0,0,254));
   viewer << viewmesh;
   viewer << Viewer3D<>::updateDisplay;
   application.exec();
 }
References DGtal::Trace::beginBlock(), DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::domain(), DGtal::Trace::endBlock(), DGtal::Trace::error(), DGtal::Trace::info(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), DGtal::Display3D< Space, KSpace >::setLineColor(), DGtal::Viewer3D< TSpace, TKSpace >::show(), DGtal::DigitalSurface< TDigitalSurfaceContainer >::size(), DGtal::trace, and usage().
usage()
void usage (int , char ** argv)
Definition at line 43 of file viewMarchingCubes.cpp.
 {
   std::cerr << "Usage: " << argv[ 0 ] << " <fileName.vol> <minT> [<maxT>=255] [<Adj>=0]" << std::endl;
   std::cerr << "\t - displays the boundary of the shape stored in vol file <fileName.vol>" << std::endl;
   std::cerr << "\t   as a Marching-Cube triangulated surface (more precisely a dual" << std::endl;
   std::cerr << "\t   surface to the digital boundary)." << std::endl;
   std::cerr << "\t - voxel v belongs to the shape iff its value I(v) follows minT < I(v) <= maxT." << std::endl;
   std::cerr << "\t - minT is the iso-surface level." << std::endl;
   std::cerr << "\t - maxT should be equal to the maximum possible value in the image." << std::endl;
   std::cerr << "\t - 0: interior adjacency, 1: exterior adjacency (rules used to connect surface elements unambiguously)." << std::endl;
 }
Referenced by main().