<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>An introduction to R for McGill Epidemiology and Public Health students</title>
  <meta name="description" content="Introduction to R for McGill Epidemiology and Public Health students">
  <meta name="generator" content="bookdown 0.5 and GitBook 2.6.7">

  <meta property="og:title" content="An introduction to R for McGill Epidemiology and Public Health students" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Introduction to R for McGill Epidemiology and Public Health students" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="An introduction to R for McGill Epidemiology and Public Health students" />
  
  <meta name="twitter:description" content="Introduction to R for McGill Epidemiology and Public Health students" />
  

<meta name="author" content="Fei Wang &amp; Jay Brophy">


<meta name="date" content="2018-01-05">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="survival-analysis.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="an-overview-of-r-part-i-ch2.html"><a href="an-overview-of-r-part-i-ch2.html"><i class="fa fa-check"></i><b>2</b> An overview of R: part I {ch2}</a><ul>
<li class="chapter" data-level="2.1" data-path="an-overview-of-r-part-i-ch2.html"><a href="an-overview-of-r-part-i-ch2.html#basic-computations-in-r"><i class="fa fa-check"></i><b>2.1</b> Basic computations in R</a></li>
<li class="chapter" data-level="2.2" data-path="an-overview-of-r-part-i-ch2.html"><a href="an-overview-of-r-part-i-ch2.html#create-an-object"><i class="fa fa-check"></i><b>2.2</b> Create an object</a></li>
<li class="chapter" data-level="2.3" data-path="an-overview-of-r-part-i-ch2.html"><a href="an-overview-of-r-part-i-ch2.html#operators"><i class="fa fa-check"></i><b>2.3</b> Operators</a><ul>
<li class="chapter" data-level="2.3.1" data-path="an-overview-of-r-part-i-ch2.html"><a href="an-overview-of-r-part-i-ch2.html#arithmetic-operators"><i class="fa fa-check"></i><b>2.3.1</b> 2.3.1 Arithmetic operators</a></li>
<li class="chapter" data-level="2.3.2" data-path="an-overview-of-r-part-i-ch2.html"><a href="an-overview-of-r-part-i-ch2.html#relational-operators"><i class="fa fa-check"></i><b>2.3.2</b> Relational operators</a></li>
<li class="chapter" data-level="2.3.3" data-path="an-overview-of-r-part-i-ch2.html"><a href="an-overview-of-r-part-i-ch2.html#logical-operators"><i class="fa fa-check"></i><b>2.3.3</b> Logical operators</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="an-overview-of-r-part-i-ch2.html"><a href="an-overview-of-r-part-i-ch2.html#generate-data"><i class="fa fa-check"></i><b>2.4</b> Generate data</a><ul>
<li class="chapter" data-level="2.4.1" data-path="an-overview-of-r-part-i-ch2.html"><a href="an-overview-of-r-part-i-ch2.html#regular-sequences"><i class="fa fa-check"></i><b>2.4.1</b> Regular sequences</a></li>
<li class="chapter" data-level="2.4.2" data-path="an-overview-of-r-part-i-ch2.html"><a href="an-overview-of-r-part-i-ch2.html#random-sequences"><i class="fa fa-check"></i><b>2.4.2</b> Random sequences</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="an-overview-of-r-part-i-ch2.html"><a href="an-overview-of-r-part-i-ch2.html#data-types"><i class="fa fa-check"></i><b>2.5</b> Data types</a><ul>
<li class="chapter" data-level="2.5.1" data-path="an-overview-of-r-part-i-ch2.html"><a href="an-overview-of-r-part-i-ch2.html#vectors"><i class="fa fa-check"></i><b>2.5.1</b> Vectors</a></li>
<li class="chapter" data-level="2.5.2" data-path="an-overview-of-r-part-i-ch2.html"><a href="an-overview-of-r-part-i-ch2.html#lists"><i class="fa fa-check"></i><b>2.5.2</b> Lists</a></li>
<li class="chapter" data-level="2.5.3" data-path="an-overview-of-r-part-i-ch2.html"><a href="an-overview-of-r-part-i-ch2.html#factors"><i class="fa fa-check"></i><b>2.5.3</b> Factors</a></li>
<li class="chapter" data-level="2.5.4" data-path="an-overview-of-r-part-i-ch2.html"><a href="an-overview-of-r-part-i-ch2.html#matrices"><i class="fa fa-check"></i><b>2.5.4</b> Matrices</a></li>
<li class="chapter" data-level="2.5.5" data-path="an-overview-of-r-part-i-ch2.html"><a href="an-overview-of-r-part-i-ch2.html#arrays"><i class="fa fa-check"></i><b>2.5.5</b> Arrays</a></li>
<li class="chapter" data-level="2.5.6" data-path="an-overview-of-r-part-i-ch2.html"><a href="an-overview-of-r-part-i-ch2.html#data-frames"><i class="fa fa-check"></i><b>2.5.6</b> Data Frames</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="an-overview-of-r-part-ii-ch3.html"><a href="an-overview-of-r-part-ii-ch3.html"><i class="fa fa-check"></i><b>3</b> An overview of R: Part II {ch3}</a><ul>
<li class="chapter" data-level="3.1" data-path="an-overview-of-r-part-ii-ch3.html"><a href="an-overview-of-r-part-ii-ch3.html#assess-the-values-of-an-object"><i class="fa fa-check"></i><b>3.1</b> Assess the values of an object</a><ul>
<li class="chapter" data-level="3.1.1" data-path="an-overview-of-r-part-ii-ch3.html"><a href="an-overview-of-r-part-ii-ch3.html#using-the-index-system"><i class="fa fa-check"></i><b>3.1.1</b> Using the index system</a></li>
<li class="chapter" data-level="3.1.2" data-path="an-overview-of-r-part-ii-ch3.html"><a href="an-overview-of-r-part-ii-ch3.html#using-the-names"><i class="fa fa-check"></i><b>3.1.2</b> Using the names</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="an-overview-of-r-part-ii-ch3.html"><a href="an-overview-of-r-part-ii-ch3.html#get-the-data-into-r"><i class="fa fa-check"></i><b>3.2</b> Get the data into R</a><ul>
<li class="chapter" data-level="3.2.1" data-path="an-overview-of-r-part-ii-ch3.html"><a href="an-overview-of-r-part-ii-ch3.html#direct-data-entering"><i class="fa fa-check"></i><b>3.2.1</b> Direct data entering</a></li>
<li class="chapter" data-level="3.2.2" data-path="an-overview-of-r-part-ii-ch3.html"><a href="an-overview-of-r-part-ii-ch3.html#use-dataset-that-come-with-r-or-r-packages"><i class="fa fa-check"></i><b>3.2.2</b> Use dataset that come with R or R packages</a></li>
<li class="chapter" data-level="3.2.3" data-path="an-overview-of-r-part-ii-ch3.html"><a href="an-overview-of-r-part-ii-ch3.html#read-in-data-files"><i class="fa fa-check"></i><b>3.2.3</b> Read in data files</a></li>
<li class="chapter" data-level="3.2.4" data-path="an-overview-of-r-part-ii-ch3.html"><a href="an-overview-of-r-part-ii-ch3.html#read-in-data-from-the-clipboard"><i class="fa fa-check"></i><b>3.2.4</b> Read in data from the clipboard</a></li>
<li class="chapter" data-level="3.2.5" data-path="an-overview-of-r-part-ii-ch3.html"><a href="an-overview-of-r-part-ii-ch3.html#read-in-remote-data"><i class="fa fa-check"></i><b>3.2.5</b> Read in remote data</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="an-overview-of-r-part-ii-ch3.html"><a href="an-overview-of-r-part-ii-ch3.html#export-data"><i class="fa fa-check"></i><b>3.3</b> Export data</a></li>
<li class="chapter" data-level="3.4" data-path="an-overview-of-r-part-ii-ch3.html"><a href="an-overview-of-r-part-ii-ch3.html#save-and-load-data-in-r"><i class="fa fa-check"></i><b>3.4</b> Save and load data in R</a></li>
<li class="chapter" data-level="3.5" data-path="an-overview-of-r-part-ii-ch3.html"><a href="an-overview-of-r-part-ii-ch3.html#view-data"><i class="fa fa-check"></i><b>3.5</b> View data</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-management-part-i-ch4.html"><a href="data-management-part-i-ch4.html"><i class="fa fa-check"></i><b>4</b> Data management: Part I {ch4}</a><ul>
<li class="chapter" data-level="4.1" data-path="data-management-part-i-ch4.html"><a href="data-management-part-i-ch4.html#control-structure"><i class="fa fa-check"></i><b>4.1</b> Control structure</a><ul>
<li class="chapter" data-level="4.1.1" data-path="data-management-part-i-ch4.html"><a href="data-management-part-i-ch4.html#for-loop"><i class="fa fa-check"></i><b>4.1.1</b> For loop</a></li>
<li class="chapter" data-level="4.1.2" data-path="data-management-part-i-ch4.html"><a href="data-management-part-i-ch4.html#while-loop"><i class="fa fa-check"></i><b>4.1.2</b> While Loop</a></li>
<li class="chapter" data-level="4.1.3" data-path="data-management-part-i-ch4.html"><a href="data-management-part-i-ch4.html#if-else-loop"><i class="fa fa-check"></i><b>4.1.3</b> If-else Loop</a></li>
<li class="chapter" data-level="4.1.4" data-path="data-management-part-i-ch4.html"><a href="data-management-part-i-ch4.html#repeat-loop"><i class="fa fa-check"></i><b>4.1.4</b> Repeat Loop</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="data-management-part-i-ch4.html"><a href="data-management-part-i-ch4.html#missing-values"><i class="fa fa-check"></i><b>4.2</b> Missing values</a></li>
<li class="chapter" data-level="4.3" data-path="data-management-part-i-ch4.html"><a href="data-management-part-i-ch4.html#dates"><i class="fa fa-check"></i><b>4.3</b> Dates</a></li>
<li class="chapter" data-level="4.4" data-path="data-management-part-i-ch4.html"><a href="data-management-part-i-ch4.html#common-useful-functions"><i class="fa fa-check"></i><b>4.4</b> Common useful functions</a><ul>
<li class="chapter" data-level="4.4.1" data-path="data-management-part-i-ch4.html"><a href="data-management-part-i-ch4.html#numeric-functions"><i class="fa fa-check"></i><b>4.4.1</b> Numeric functions</a></li>
<li class="chapter" data-level="4.4.2" data-path="data-management-part-i-ch4.html"><a href="data-management-part-i-ch4.html#character-functions"><i class="fa fa-check"></i><b>4.4.2</b> Character Functions</a></li>
<li class="chapter" data-level="4.4.3" data-path="data-management-part-i-ch4.html"><a href="data-management-part-i-ch4.html#apply-functions-over-a-list-array-dataframe-or-matrix"><i class="fa fa-check"></i><b>4.4.3</b> Apply functions over a list, array, dataframe or matrix</a></li>
<li class="chapter" data-level="4.4.4" data-path="data-management-part-i-ch4.html"><a href="data-management-part-i-ch4.html#other-useful-functions"><i class="fa fa-check"></i><b>4.4.4</b> Other useful functions</a></li>
<li class="chapter" data-level="4.4.5" data-path="data-management-part-i-ch4.html"><a href="data-management-part-i-ch4.html#write-functions"><i class="fa fa-check"></i><b>4.4.5</b> Write functions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-managements-part-ii-reshape-data-ch4.html"><a href="data-managements-part-ii-reshape-data-ch4.html"><i class="fa fa-check"></i><b>5</b> Data managements: Part II- Reshape data {ch4}</a><ul>
<li class="chapter" data-level="5.1" data-path="data-managements-part-ii-reshape-data-ch4.html"><a href="data-managements-part-ii-reshape-data-ch4.html#subset-data"><i class="fa fa-check"></i><b>5.1</b> Subset Data</a><ul>
<li class="chapter" data-level="5.1.1" data-path="data-managements-part-ii-reshape-data-ch4.html"><a href="data-managements-part-ii-reshape-data-ch4.html#select-variables"><i class="fa fa-check"></i><b>5.1.1</b> Select variables</a></li>
<li class="chapter" data-level="5.1.2" data-path="data-managements-part-ii-reshape-data-ch4.html"><a href="data-managements-part-ii-reshape-data-ch4.html#exclude-variables"><i class="fa fa-check"></i><b>5.1.2</b> Exclude variables</a></li>
<li class="chapter" data-level="5.1.3" data-path="data-managements-part-ii-reshape-data-ch4.html"><a href="data-managements-part-ii-reshape-data-ch4.html#select-observations"><i class="fa fa-check"></i><b>5.1.3</b> Select Observations</a></li>
<li class="chapter" data-level="5.1.4" data-path="data-managements-part-ii-reshape-data-ch4.html"><a href="data-managements-part-ii-reshape-data-ch4.html#select-both-variables-and-observations"><i class="fa fa-check"></i><b>5.1.4</b> Select both variables and observations</a></li>
<li class="chapter" data-level="5.1.5" data-path="data-managements-part-ii-reshape-data-ch4.html"><a href="data-managements-part-ii-reshape-data-ch4.html#keep-or-delete-variables-using-dplyr-function"><i class="fa fa-check"></i><b>5.1.5</b> Keep or delete variables using dplyr function</a></li>
<li class="chapter" data-level="5.1.6" data-path="data-managements-part-ii-reshape-data-ch4.html"><a href="data-managements-part-ii-reshape-data-ch4.html#keepdrop-variables-by-name-pattern"><i class="fa fa-check"></i><b>5.1.6</b> Keep/drop variables by name pattern</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="data-managements-part-ii-reshape-data-ch4.html"><a href="data-managements-part-ii-reshape-data-ch4.html#merge-data"><i class="fa fa-check"></i><b>5.2</b> Merge Data</a><ul>
<li class="chapter" data-level="5.2.1" data-path="data-managements-part-ii-reshape-data-ch4.html"><a href="data-managements-part-ii-reshape-data-ch4.html#add-casesobservations-to-a-dataset"><i class="fa fa-check"></i><b>5.2.1</b> Add cases/observations to a dataset</a></li>
<li class="chapter" data-level="5.2.2" data-path="data-managements-part-ii-reshape-data-ch4.html"><a href="data-managements-part-ii-reshape-data-ch4.html#merge-data-frames"><i class="fa fa-check"></i><b>5.2.2</b> Merge Data Frames</a></li>
<li class="chapter" data-level="5.2.3" data-path="data-managements-part-ii-reshape-data-ch4.html"><a href="data-managements-part-ii-reshape-data-ch4.html#add-more-variables-to-a-dataset"><i class="fa fa-check"></i><b>5.2.3</b> Add more variables to a dataset</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="data-managements-part-ii-reshape-data-ch4.html"><a href="data-managements-part-ii-reshape-data-ch4.html#the-reshape-package"><i class="fa fa-check"></i><b>5.3</b> The Reshape package</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="base-graphics-with-r-ch5.html"><a href="base-graphics-with-r-ch5.html"><i class="fa fa-check"></i><b>6</b> Base Graphics with R {ch5}</a><ul>
<li class="chapter" data-level="6.1" data-path="base-graphics-with-r-ch5.html"><a href="base-graphics-with-r-ch5.html#graphical-functions"><i class="fa fa-check"></i><b>6.1</b> Graphical functions</a><ul>
<li class="chapter" data-level="6.1.1" data-path="base-graphics-with-r-ch5.html"><a href="base-graphics-with-r-ch5.html#high-level-graphical-functions"><i class="fa fa-check"></i><b>6.1.1</b> (1) High-level graphical functions</a></li>
<li class="chapter" data-level="6.1.2" data-path="base-graphics-with-r-ch5.html"><a href="base-graphics-with-r-ch5.html#low-level-functions"><i class="fa fa-check"></i><b>6.1.2</b> (2) Low-level functions</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="base-graphics-with-r-ch5.html"><a href="base-graphics-with-r-ch5.html#graphical-parameters"><i class="fa fa-check"></i><b>6.2</b> Graphical parameters</a><ul>
<li class="chapter" data-level="6.2.1" data-path="base-graphics-with-r-ch5.html"><a href="base-graphics-with-r-ch5.html#specify-within-the-high-level-function"><i class="fa fa-check"></i><b>6.2.1</b> 6.2.1 Specify within the high-level function</a></li>
<li class="chapter" data-level="6.2.2" data-path="base-graphics-with-r-ch5.html"><a href="base-graphics-with-r-ch5.html#function-par"><i class="fa fa-check"></i><b>6.2.2</b> Function par()</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="base-graphics-with-r-ch5.html"><a href="base-graphics-with-r-ch5.html#multiple-plots-on-the-one-page"><i class="fa fa-check"></i><b>6.3</b> Multiple plots on the one page</a><ul>
<li class="chapter" data-level="6.3.1" data-path="base-graphics-with-r-ch5.html"><a href="base-graphics-with-r-ch5.html#function-layout"><i class="fa fa-check"></i><b>6.3.1</b> Function layout()</a></li>
<li class="chapter" data-level="6.3.2" data-path="base-graphics-with-r-ch5.html"><a href="base-graphics-with-r-ch5.html#function-par-1"><i class="fa fa-check"></i><b>6.3.2</b> Function par()</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="base-graphics-with-r-ch5.html"><a href="base-graphics-with-r-ch5.html#save-a-plot"><i class="fa fa-check"></i><b>6.4</b> Save a plot</a><ul>
<li class="chapter" data-level="6.4.1" data-path="base-graphics-with-r-ch5.html"><a href="base-graphics-with-r-ch5.html#save-plots-by-menu-click"><i class="fa fa-check"></i><b>6.4.1</b> Save plots by menu click</a></li>
<li class="chapter" data-level="6.4.2" data-path="base-graphics-with-r-ch5.html"><a href="base-graphics-with-r-ch5.html#save-plots-using-functions"><i class="fa fa-check"></i><b>6.4.2</b> Save plots using functions</a></li>
<li class="chapter" data-level="6.4.3" data-path="base-graphics-with-r-ch5.html"><a href="base-graphics-with-r-ch5.html#a-common-method"><i class="fa fa-check"></i><b>6.4.3</b> (1) A common method</a></li>
<li class="chapter" data-level="6.4.4" data-path="base-graphics-with-r-ch5.html"><a href="base-graphics-with-r-ch5.html#another-option"><i class="fa fa-check"></i><b>6.4.4</b> (2)Another option</a></li>
<li class="chapter" data-level="6.4.5" data-path="base-graphics-with-r-ch5.html"><a href="base-graphics-with-r-ch5.html#saving-plots-in-a-loop"><i class="fa fa-check"></i><b>6.4.5</b> (3) Saving plots in a loop</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html"><a href="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html"><i class="fa fa-check"></i><b>7</b> Descriptive statistics with R: Part I-Quantitative variables {ch6}</a><ul>
<li class="chapter" data-level="7.1" data-path="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html"><a href="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html#for-the-whole-dataset"><i class="fa fa-check"></i><b>7.1</b> For the whole dataset</a></li>
<li class="chapter" data-level="7.2" data-path="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html"><a href="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html#for-a-single-quantitative-variable"><i class="fa fa-check"></i><b>7.2</b> For a single quantitative variable</a><ul>
<li class="chapter" data-level="7.2.1" data-path="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html"><a href="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html#numerical-representation"><i class="fa fa-check"></i><b>7.2.1</b> Numerical representation</a></li>
<li class="chapter" data-level="7.2.2" data-path="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html"><a href="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html#graphical-representation"><i class="fa fa-check"></i><b>7.2.2</b> Graphical representation</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html"><a href="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html#for-a-quantitative-variable-by-groups"><i class="fa fa-check"></i><b>7.3</b> For a quantitative variable by groups</a><ul>
<li class="chapter" data-level="7.3.1" data-path="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html"><a href="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html#numerical-representation-1"><i class="fa fa-check"></i><b>7.3.1</b> Numerical representation</a></li>
<li class="chapter" data-level="7.3.2" data-path="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html"><a href="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html#graphical-representation-1"><i class="fa fa-check"></i><b>7.3.2</b> Graphical representation</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html"><a href="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html#for-two-quantitative-variables"><i class="fa fa-check"></i><b>7.4</b> For two quantitative variables</a><ul>
<li class="chapter" data-level="7.4.1" data-path="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html"><a href="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html#numerical-representation-2"><i class="fa fa-check"></i><b>7.4.1</b> Numerical representation</a></li>
<li class="chapter" data-level="7.4.2" data-path="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html"><a href="descriptive-statistics-with-r-part-i-quantitative-variables-ch6.html#graphical-representation-2"><i class="fa fa-check"></i><b>7.4.2</b> Graphical representation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html"><a href="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html"><i class="fa fa-check"></i><b>8</b> Descriptive statistics with R: Part II-Categorical variables and ggplot</a><ul>
<li class="chapter" data-level="8.1" data-path="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html"><a href="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html#numerical-representation-3"><i class="fa fa-check"></i><b>8.1</b> Numerical representation</a></li>
<li class="chapter" data-level="8.2" data-path="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html"><a href="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html#graphical-representation-3"><i class="fa fa-check"></i><b>8.2</b> Graphical representation</a><ul>
<li class="chapter" data-level="8.2.1" data-path="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html"><a href="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html#barplots"><i class="fa fa-check"></i><b>8.2.1</b> (1) Barplots</a></li>
<li class="chapter" data-level="8.2.2" data-path="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html"><a href="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html#dotcharts"><i class="fa fa-check"></i><b>8.2.2</b> (2) Dotcharts</a></li>
<li class="chapter" data-level="8.2.3" data-path="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html"><a href="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html#piecharts"><i class="fa fa-check"></i><b>8.2.3</b> (3) Piecharts</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html"><a href="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html#ggplot2-function"><i class="fa fa-check"></i><b>8.3</b> ggplot2 function</a><ul>
<li class="chapter" data-level="8.3.1" data-path="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html"><a href="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html#a-simple-histogram-for-a-single-quantative-variable"><i class="fa fa-check"></i><b>8.3.1</b> (1)a simple histogram for a single quantative variable</a></li>
<li class="chapter" data-level="8.3.2" data-path="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html"><a href="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html#for-a-quantative-variable-by-groups"><i class="fa fa-check"></i><b>8.3.2</b> (2)for a quantative variable by groups</a></li>
<li class="chapter" data-level="8.3.3" data-path="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html"><a href="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html#for-two-quantitative-variables-1"><i class="fa fa-check"></i><b>8.3.3</b> (3) for two quantitative variables</a></li>
<li class="chapter" data-level="8.3.4" data-path="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html"><a href="descriptive-statistics-with-r-part-ii-categorical-variables-and-ggplot.html#for-categorial-variable"><i class="fa fa-check"></i><b>8.3.4</b> (4) for categorial variable</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html"><i class="fa fa-check"></i><b>9</b> Basic statistical tests with R</a><ul>
<li class="chapter" data-level="9.1" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html#two-sample-tests"><i class="fa fa-check"></i><b>9.1</b> Two-sample tests</a><ul>
<li class="chapter" data-level="9.1.1" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html#t-test"><i class="fa fa-check"></i><b>9.1.1</b> t-test</a></li>
<li class="chapter" data-level="9.1.2" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html#nonparametric-tests"><i class="fa fa-check"></i><b>9.1.2</b> Nonparametric tests</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html#analysis-of-variance"><i class="fa fa-check"></i><b>9.2</b> Analysis Of Variance</a><ul>
<li class="chapter" data-level="9.2.1" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html#assumptions-assessment"><i class="fa fa-check"></i><b>9.2.1</b> Assumptions assessment</a></li>
<li class="chapter" data-level="9.2.2" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html#parametric-test"><i class="fa fa-check"></i><b>9.2.2</b> Parametric test</a></li>
<li class="chapter" data-level="9.2.3" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html#nonparametric-test"><i class="fa fa-check"></i><b>9.2.3</b> Nonparametric test</a></li>
<li class="chapter" data-level="9.2.4" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html#multivariate-analysis-of-variance"><i class="fa fa-check"></i><b>9.2.4</b> Multivariate analysis of variance</a></li>
<li class="chapter" data-level="9.2.5" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html#two-way-analysis-of-variance"><i class="fa fa-check"></i><b>9.2.5</b> Two-way analysis of variance</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html#correlation"><i class="fa fa-check"></i><b>9.3</b> Correlation</a><ul>
<li class="chapter" data-level="9.3.1" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html#spearmans-"><i class="fa fa-check"></i><b>9.3.1</b> Spearman’s ρ</a></li>
<li class="chapter" data-level="9.3.2" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html#kendalls-"><i class="fa fa-check"></i><b>9.3.2</b> Kendall’s τ</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html#tabular-data"><i class="fa fa-check"></i><b>9.4</b> Tabular data</a><ul>
<li class="chapter" data-level="9.4.1" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html#single-proportion"><i class="fa fa-check"></i><b>9.4.1</b> Single proportion</a></li>
<li class="chapter" data-level="9.4.2" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html#two-independent-proportions"><i class="fa fa-check"></i><b>9.4.2</b> Two independent proportions</a></li>
<li class="chapter" data-level="9.4.3" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html#k-proportions"><i class="fa fa-check"></i><b>9.4.3</b> k proportions</a></li>
<li class="chapter" data-level="9.4.4" data-path="basic-statistical-tests-with-r.html"><a href="basic-statistical-tests-with-r.html#r-c-tables"><i class="fa fa-check"></i><b>9.4.4</b> r × c tables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="regressions-with-r-linear-regression.html"><a href="regressions-with-r-linear-regression.html"><i class="fa fa-check"></i><b>10</b> Regressions with R-Linear Regression</a><ul>
<li class="chapter" data-level="10.1" data-path="regressions-with-r-linear-regression.html"><a href="regressions-with-r-linear-regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>10.1</b> Simple linear regression</a><ul>
<li class="chapter" data-level="10.1.1" data-path="regressions-with-r-linear-regression.html"><a href="regressions-with-r-linear-regression.html#function"><i class="fa fa-check"></i><b>10.1.1</b> Function</a></li>
<li class="chapter" data-level="10.1.2" data-path="regressions-with-r-linear-regression.html"><a href="regressions-with-r-linear-regression.html#output-explanation"><i class="fa fa-check"></i><b>10.1.2</b> Output explanation</a></li>
<li class="chapter" data-level="10.1.3" data-path="regressions-with-r-linear-regression.html"><a href="regressions-with-r-linear-regression.html#other-useful-functions-1"><i class="fa fa-check"></i><b>10.1.3</b> Other useful functions</a></li>
<li class="chapter" data-level="10.1.4" data-path="regressions-with-r-linear-regression.html"><a href="regressions-with-r-linear-regression.html#fitted-values-and-residuals"><i class="fa fa-check"></i><b>10.1.4</b> Fitted values and residuals</a></li>
<li class="chapter" data-level="10.1.5" data-path="regressions-with-r-linear-regression.html"><a href="regressions-with-r-linear-regression.html#prediction-and-confidence-intervals"><i class="fa fa-check"></i><b>10.1.5</b> Prediction and confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="regressions-with-r-linear-regression.html"><a href="regressions-with-r-linear-regression.html#multiple-linear-regression"><i class="fa fa-check"></i><b>10.2</b> Multiple linear regression</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>11</b> Survival analysis</a><ul>
<li class="chapter" data-level="11.1" data-path="survival-analysis.html"><a href="survival-analysis.html#create-the-response-variable"><i class="fa fa-check"></i><b>11.1</b> Create the response variable</a></li>
<li class="chapter" data-level="11.2" data-path="survival-analysis.html"><a href="survival-analysis.html#kaplan-meier-estimate"><i class="fa fa-check"></i><b>11.2</b> Kaplan-Meier estimate</a></li>
<li class="chapter" data-level="11.3" data-path="survival-analysis.html"><a href="survival-analysis.html#cumulative-hazard"><i class="fa fa-check"></i><b>11.3</b> Cumulative hazard</a></li>
<li class="chapter" data-level="11.4" data-path="survival-analysis.html"><a href="survival-analysis.html#the-log-rank-test"><i class="fa fa-check"></i><b>11.4</b> The log-rank test</a></li>
<li class="chapter" data-level="11.5" data-path="survival-analysis.html"><a href="survival-analysis.html#cox-proportional-hazards-model"><i class="fa fa-check"></i><b>11.5</b> Cox Proportional Hazards Model</a><ul>
<li class="chapter" data-level="11.5.1" data-path="survival-analysis.html"><a href="survival-analysis.html#regular-cox-proportional-hazards-model"><i class="fa fa-check"></i><b>11.5.1</b> Regular Cox proportional hazards model</a></li>
<li class="chapter" data-level="11.5.2" data-path="survival-analysis.html"><a href="survival-analysis.html#test-for-proportional-hazards"><i class="fa fa-check"></i><b>11.5.2</b> Test for proportional hazards</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="bootstrap-analysis-of-clustered-data-and-non-linear-effects.html"><a href="bootstrap-analysis-of-clustered-data-and-non-linear-effects.html"><i class="fa fa-check"></i><b>12</b> Bootstrap, analysis of clustered data and non-linear effects</a><ul>
<li class="chapter" data-level="12.1" data-path="bootstrap-analysis-of-clustered-data-and-non-linear-effects.html"><a href="bootstrap-analysis-of-clustered-data-and-non-linear-effects.html#bootstrap"><i class="fa fa-check"></i><b>12.1</b> Bootstrap</a></li>
<li class="chapter" data-level="12.2" data-path="bootstrap-analysis-of-clustered-data-and-non-linear-effects.html"><a href="bootstrap-analysis-of-clustered-data-and-non-linear-effects.html#analysis-of-clustered-data"><i class="fa fa-check"></i><b>12.2</b> Analysis of clustered data</a><ul>
<li class="chapter" data-level="12.2.1" data-path="bootstrap-analysis-of-clustered-data-and-non-linear-effects.html"><a href="bootstrap-analysis-of-clustered-data-and-non-linear-effects.html#linear-mixed-effects-models"><i class="fa fa-check"></i><b>12.2.1</b> Linear Mixed Effects Models</a></li>
<li class="chapter" data-level="12.2.2" data-path="bootstrap-analysis-of-clustered-data-and-non-linear-effects.html"><a href="bootstrap-analysis-of-clustered-data-and-non-linear-effects.html#generalized-estimation-equations-gee-models"><i class="fa fa-check"></i><b>12.2.2</b> Generalized Estimation Equations (GEE) models</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="bootstrap-analysis-of-clustered-data-and-non-linear-effects.html"><a href="bootstrap-analysis-of-clustered-data-and-non-linear-effects.html#non-linear-effects"><i class="fa fa-check"></i><b>12.3</b> Non-linear effects</a></li>
<li class="chapter" data-level="12.4" data-path="bootstrap-analysis-of-clustered-data-and-non-linear-effects.html"><a href="bootstrap-analysis-of-clustered-data-and-non-linear-effects.html#epi-packages--epitab"><i class="fa fa-check"></i><b>12.4</b> Epi packages- Epitab()</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An introduction to R for McGill Epidemiology and Public Health students</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="bootstrap-analysis-of-clustered-data-and-non-linear-effects" class="section level1">
<h1><span class="header-section-number">Chapter 12</span> Bootstrap, analysis of clustered data and non-linear effects</h1>
<div id="bootstrap" class="section level2">
<h2><span class="header-section-number">12.1</span> Bootstrap</h2>
<p>Bootstrapping is a nonparametric method which lets us compute estimated standard errors, confidence intervals and hypothesis testing.It is very useful in statistics and can be easily implemented in R.</p>
<pre><code>install.packages(&quot;boot&quot;)</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(boot)</code></pre></div>
<p>Let’s use the dataset city from the boot package as an example oto understand bootstrap.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">city</code></pre></div>
<pre><code>##      u   x
## 1  138 143
## 2   93 104
## 3   61  69
## 4  179 260
## 5   48  75
## 6   37  63
## 7   29  50
## 8   23  48
## 9   30 111
## 10   2  50</code></pre>
<p>Let’s say we want to know the correlation between u and x. Let’s first define a function that will return the statistics that we would like to bootstrap.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mycor&lt;-<span class="cf">function</span>(d, i) {<span class="co">#The first argument of the function is the dataset.  The second argument can be an index vector of the observations in the dataset to use or a frequency or weight vector that informs the sampling probabilities.</span>
  d0&lt;-d[i,]
<span class="kw">return</span>( <span class="kw">cor</span>(d0<span class="op">$</span>u,d0<span class="op">$</span>x) ) <span class="co">#Here, the statistic of interest  is the mean of the variable</span>
}</code></pre></div>
<p>We can do the bootstrap by using loops.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n =<span class="st"> </span><span class="kw">dim</span>(city)[<span class="dv">1</span>]
B =<span class="st"> </span><span class="dv">1000</span>
result =<span class="st"> </span><span class="kw">rep</span>(<span class="ot">NA</span>, B)
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>B) {
boot.sample =<span class="st"> </span><span class="kw">sample</span>(n, <span class="dt">replace =</span> <span class="ot">TRUE</span>)
result[i] =<span class="st"> </span><span class="kw">mycor</span>(city[boot.sample,])
}
result[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>]</code></pre></div>
<pre><code>##  [1] 0.9940604 0.9395998 0.9398458 0.9637804 0.6922869 0.9600877 0.9461347
##  [8] 0.9312356 0.8847873 0.9558545</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#To get the 90% confidence interval</span>
<span class="kw">quantile</span>(result,<span class="kw">c</span>(<span class="fl">0.05</span>,<span class="fl">0.95</span>))</code></pre></div>
<pre><code>##        5%       95% 
## 0.5979012 0.9840924</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#To get the 95% confidence interval</span>
<span class="kw">quantile</span>(result,<span class="kw">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</code></pre></div>
<pre><code>##      2.5%     97.5% 
## 0.4626091 0.9899143</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#To get the 99% confidence interval</span>
<span class="kw">quantile</span>(result,<span class="kw">c</span>(<span class="fl">0.005</span>,<span class="fl">0.995</span>))</code></pre></div>
<pre><code>##      0.5%     99.5% 
## 0.1919849 0.9962879</code></pre>
<p>There is a package boot with a function boot() that does the bootstrap for many situations. We can use the boot command which executes the resampling of the dataset and calculation of the statistics of interest on these samples. Before calling boot, we also need to define a function first. Next, we can use the boot command, providing our dataset name, our function, and the number of bootstrap samples to be drawn.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">myboot&lt;-<span class="st"> </span><span class="kw">boot</span>(city, mycor, <span class="dv">1000</span>)<span class="co">#the three arguments: the data from the original sample; a function to compute the statistics from the data; the number of bootstrap replicates.</span>
myboot</code></pre></div>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = city, statistic = mycor, R = 1000)
## 
## 
## Bootstrap Statistics :
##      original      bias    std. error
## t1* 0.9043448 -0.03486151   0.1489199</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#The object u.boot is a list with many elements. </span>
<span class="kw">summary</span>(myboot)</code></pre></div>
<pre><code>##      R original  bootBias  bootSE bootMed
## 1 1000  0.90434 -0.034862 0.14892 0.91753</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">myboot<span class="op">$</span>t0<span class="co">#the sample mean of the original data.</span></code></pre></div>
<pre><code>## [1] 0.9043448</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#To get the bias</span>
<span class="kw">mean</span>(myboot<span class="op">$</span>t)<span class="op">-</span>myboot<span class="op">$</span>t0</code></pre></div>
<pre><code>## [1] -0.03486151</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#To get the standard error</span>
<span class="kw">sd</span>(myboot<span class="op">$</span>t)</code></pre></div>
<pre><code>## [1] 0.1489199</code></pre>
<p>We can also use the built-in function boot.ci() to calculate bootstrap confidence intervals using multiple methods.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">boot.ci</span>(myboot)</code></pre></div>
<pre><code>## Warning in boot.ci(myboot): bootstrap variances needed for studentized
## intervals</code></pre>
<pre><code>## BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
## Based on 1000 bootstrap replicates
## 
## CALL : 
## boot.ci(boot.out = myboot)
## 
## Intervals : 
## Level      Normal              Basic         
## 95%   ( 0.6473,  1.2311 )   ( 0.8184,  1.4203 )  
## 
## Level     Percentile            BCa          
## 95%   ( 0.3884,  0.9903 )   ( 0.1279,  0.9759 )  
## Calculations and Intervals on Original Scale
## Some BCa intervals may be unstable</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Basic uses the estimated standard error. Percentile uses percentiles. BCa also uses percentiles, but adjusted to account for bias and skewness</span>
<span class="kw">quantile</span>(myboot<span class="op">$</span>t,<span class="kw">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</code></pre></div>
<pre><code>##      2.5%     97.5% 
## 0.3894433 0.9902075</code></pre>
<p>To look at the histogram and normal quantile-quantile plot of the bootstrap estimates, we can use plot with the “boot” object we created. The histogram includes a dotted vertical line indicating the location of the original statistic.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(myboot)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-258-1.png" width="672" /></p>
</div>
<div id="analysis-of-clustered-data" class="section level2">
<h2><span class="header-section-number">12.2</span> Analysis of clustered data</h2>
<p>In many situations we may come across data that include repeated measurements of individuals or measurements of subjects that are expected to be not entirely independent (e.g. family members, individuals living in communities).Clustering can introduce severe problems for statistical inference, in particular in regard to estimated standard errors and associated p-values and confidence intervals.Let’s use the smoking dataset.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mydata&lt;-<span class="kw">read.table</span>(<span class="st">&quot;data/smokingw.txt&quot;</span>,<span class="dt">header=</span>T)
<span class="kw">head</span>(mydata)</code></pre></div>
<pre><code>##   id currsmoker male age fev0 fev3 fev6 fev9
## 1  1          0    1  29  3.4 3.40 3.45 3.20
## 2  2          1    1  34  3.1 3.15 3.50 2.95
## 3  3          1    0  19  3.6 3.45 3.45 3.10
## 4  5          1    0  17  3.4 3.30 2.93 2.30
## 5  6          0    0  17  3.3 3.75 3.50 2.95
## 6  8          1    0  36  3.9 4.00 4.05 3.75</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">NROW</span>(<span class="kw">unique</span>(mydata[,<span class="dv">1</span>]))</code></pre></div>
<pre><code>## [1] 78</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(mydata)</code></pre></div>
<pre><code>## [1] &quot;id&quot;         &quot;currsmoker&quot; &quot;male&quot;       &quot;age&quot;        &quot;fev0&quot;      
## [6] &quot;fev3&quot;       &quot;fev6&quot;       &quot;fev9&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Let&#39;s plot it</span>
<span class="kw">pairs</span>(mydata[,<span class="dv">5</span><span class="op">:</span><span class="dv">8</span>])</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-259-1.png" width="672" /> We may find that different measurements of the FEV are related. In order to conduct the following analysis, we need to reshape the data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">smoking.long&lt;-<span class="kw">reshape</span>(mydata,<span class="dt">varying=</span><span class="kw">c</span>(<span class="st">&quot;fev0&quot;</span>,<span class="st">&quot;fev3&quot;</span>,<span class="st">&quot;fev6&quot;</span>,<span class="st">&quot;fev9&quot;</span>),<span class="dt">v.names=</span><span class="st">&quot;fev&quot;</span>,<span class="dt">timevar=</span><span class="st">&quot;year&quot;</span>,<span class="dt">times=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>),<span class="dt">new.row.names=</span><span class="dv">1</span><span class="op">:</span>(<span class="dv">100</span><span class="op">*</span><span class="dv">4</span>),<span class="dt">direction=</span><span class="st">&quot;long&quot;</span>)
smoking.long&lt;-smoking.long[<span class="kw">order</span>(smoking.long<span class="op">$</span>id),]
<span class="kw">head</span>(smoking.long)</code></pre></div>
<pre><code>##     id currsmoker male age year  fev
## 1    1          0    1  29    0 3.40
## 79   1          0    1  29    1 3.40
## 157  1          0    1  29    2 3.45
## 235  1          0    1  29    3 3.20
## 2    2          1    1  34    0 3.10
## 80   2          1    1  34    1 3.15</code></pre>
<p>Let’s first try a naive model without consideration of the correlation.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model1&lt;-<span class="kw">lm</span>(fev<span class="op">~</span>currsmoker<span class="op">+</span>male<span class="op">+</span>age, <span class="dt">data =</span> smoking.long) 
<span class="kw">summary</span>(model1)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = fev ~ currsmoker + male + age, data = smoking.long)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.54048 -0.33126  0.00864  0.35237  1.61899 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  3.528031   0.122781  28.734  &lt; 2e-16 ***
## currsmoker  -0.288754   0.076215  -3.789 0.000182 ***
## male         0.139980   0.064897   2.157 0.031783 *  
## age         -0.006608   0.003939  -1.677 0.094467 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5445 on 308 degrees of freedom
## Multiple R-squared:  0.06321,    Adjusted R-squared:  0.05408 
## F-statistic: 6.927 on 3 and 308 DF,  p-value: 0.0001586</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">AIC</span>(model1)</code></pre></div>
<pre><code>## [1] 512.1198</code></pre>
<p>However, this model assumes independence. We therefore want to account for the repeated measurement nature of the data. We can do this by fitting a linear mixed effects model.</p>
<div id="linear-mixed-effects-models" class="section level3">
<h3><span class="header-section-number">12.2.1</span> Linear Mixed Effects Models</h3>
<pre><code>install.packages(&quot;lme4&quot;)</code></pre>
<p>Let’s first fit a random intercept model:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(nlme)</code></pre></div>
<pre><code>## 
## Attaching package: &#39;nlme&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     collapse</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model2=<span class="kw">lme</span>(fev<span class="op">~</span>male<span class="op">+</span>age<span class="op">+</span>currsmoker<span class="op">+</span>year,<span class="dt">random=</span><span class="op">~</span><span class="dv">1</span><span class="op">|</span>id,<span class="dt">data=</span>smoking.long)
<span class="kw">summary</span>(model2)</code></pre></div>
<pre><code>## Linear mixed-effects model fit by REML
##  Data: smoking.long 
##        AIC      BIC    logLik
##   178.5472 204.6352 -82.27361
## 
## Random effects:
##  Formula: ~1 | id
##         (Intercept)  Residual
## StdDev:   0.4969424 0.2049207
## 
## Fixed effects: fev ~ male + age + currsmoker + year 
##                 Value  Std.Error  DF    t-value p-value
## (Intercept)  3.703569 0.22933794 233  16.148960  0.0000
## male         0.139980 0.12093960  74   1.157434  0.2508
## age         -0.006608 0.00734131  74  -0.900137  0.3710
## currsmoker  -0.288754 0.14203102  74  -2.033034  0.0456
## year        -0.117026 0.01037656 233 -11.277882  0.0000
##  Correlation: 
##            (Intr) male   age    crrsmk
## male       -0.122                     
## age        -0.805 -0.150              
## currsmoker -0.326 -0.135 -0.126       
## year       -0.068  0.000  0.000  0.000
## 
## Standardized Within-Group Residuals:
##           Min            Q1           Med            Q3           Max 
## -3.8968243611 -0.4787783754 -0.0002484638  0.5597337865  3.3858396419 
## 
## Number of Observations: 312
## Number of Groups: 78</code></pre>
<p>Let’s next fit a random intercept and random slope model:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model3=<span class="kw">lme</span>(fev<span class="op">~</span>male<span class="op">+</span>age<span class="op">+</span>currsmoker<span class="op">+</span>year,<span class="dt">random=</span><span class="op">~</span><span class="dv">1</span><span class="op">+</span>year<span class="op">|</span>id,<span class="dt">data=</span>smoking.long)
<span class="kw">summary</span>(model3)</code></pre></div>
<pre><code>## Linear mixed-effects model fit by REML
##  Data: smoking.long 
##        AIC      BIC    logLik
##   178.5033 212.0449 -80.25165
## 
## Random effects:
##  Formula: ~1 + year | id
##  Structure: General positive-definite, Log-Cholesky parametrization
##             StdDev     Corr  
## (Intercept) 0.51358889 (Intr)
## year        0.05800847 -0.257
## Residual    0.19087252       
## 
## Fixed effects: fev ~ male + age + currsmoker + year 
##                 Value  Std.Error  DF    t-value p-value
## (Intercept)  3.706375 0.22943224 233  16.154554  0.0000
## male         0.132256 0.12078849  74   1.094942  0.2771
## age         -0.006345 0.00733214  74  -0.865417  0.3896
## currsmoker  -0.295860 0.14185355  74  -2.085675  0.0405
## year        -0.117026 0.01168576 233 -10.014380  0.0000
##  Correlation: 
##            (Intr) male   age    crrsmk
## male       -0.122                     
## age        -0.803 -0.150              
## currsmoker -0.325 -0.135 -0.126       
## year       -0.089  0.000  0.000  0.000
## 
## Standardized Within-Group Residuals:
##         Min          Q1         Med          Q3         Max 
## -3.46375991 -0.46458472 -0.02419447  0.51800639  2.89704874 
## 
## Number of Observations: 312
## Number of Groups: 78</code></pre>
<p>We can see that for model1, the AIC is 512.1198; For model 2, the AIC is 178.5472; For model 3, the AIC is 178.5033.Generally, the smaller the AIC, the better the model. Model 2 and model 3 are much better than model 1. But model 3 is not so much better than model 2. We can also do a Chi-square test to compare the goodness of fit for model 2 and model3.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(model2,model3)</code></pre></div>
<pre><code>##        Model df      AIC      BIC    logLik   Test L.Ratio p-value
## model2     1  7 178.5472 204.6352 -82.27361                       
## model3     2  9 178.5033 212.0449 -80.25165 1 vs 2 4.04392  0.1324</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#We can also find that model 3 is not statistically significant better than model 2.</span></code></pre></div>
<p>We can also see that it doesn’t make much sense to include a random slope since the average FEV over time is varied by person but the FEV trajectory (the slope) is assumed to be homogeneous.</p>
</div>
<div id="generalized-estimation-equations-gee-models" class="section level3">
<h3><span class="header-section-number">12.2.2</span> Generalized Estimation Equations (GEE) models</h3>
<p>By using the linear mixed effects model, we are estimating the conditional effects (individual or cluster-specific effects). However, if we are interested in the marginal effects (average population effects), we may want to use the GEE model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(geepack)
model4&lt;-<span class="kw">geeglm</span>(fev<span class="op">~</span>male<span class="op">+</span>age<span class="op">+</span>currsmoker<span class="op">+</span>year,<span class="dt">id=</span>id, <span class="dt">data=</span>smoking.long)
<span class="kw">summary</span>(model4)</code></pre></div>
<pre><code>## 
## Call:
## geeglm(formula = fev ~ male + age + currsmoker + year, data = smoking.long, 
##     id = id)
## 
##  Coefficients:
##              Estimate   Std.err    Wald Pr(&gt;|W|)    
## (Intercept)  3.703569  0.194374 363.048   &lt;2e-16 ***
## male         0.139980  0.127442   1.206   0.2720    
## age         -0.006608  0.007757   0.726   0.3943    
## currsmoker  -0.288754  0.143106   4.071   0.0436 *  
## year        -0.117026  0.011611 101.590   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Estimated Scale Parameters:
##             Estimate Std.err
## (Intercept)   0.2756 0.03786
## 
## Correlation: Structure = independenceNumber of clusters:   78   Maximum cluster size: 4</code></pre>
<p>If we explore more about geeglm, we can do:</p>
<pre><code>?geeglm</code></pre>
<p>We can specify different correlation structure by using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model5&lt;-<span class="kw">geeglm</span>(fev<span class="op">~</span>male<span class="op">+</span>age<span class="op">+</span>currsmoker<span class="op">+</span>year,<span class="dt">id=</span>id, <span class="dt">data=</span>smoking.long,<span class="dt">corstr=</span><span class="st">&quot;ar1&quot;</span>)
<span class="kw">summary</span>(model5)</code></pre></div>
<pre><code>## 
## Call:
## geeglm(formula = fev ~ male + age + currsmoker + year, data = smoking.long, 
##     id = id, corstr = &quot;ar1&quot;)
## 
##  Coefficients:
##             Estimate  Std.err   Wald Pr(&gt;|W|)    
## (Intercept)  3.65631  0.20411 320.88   &lt;2e-16 ***
## male         0.16787  0.12927   1.69    0.194    
## age         -0.00539  0.00803   0.45    0.502    
## currsmoker  -0.31763  0.13966   5.17    0.023 *  
## year        -0.11971  0.01221  96.06   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Estimated Scale Parameters:
##             Estimate Std.err
## (Intercept)    0.276  0.0379
## 
## Correlation: Structure = ar1  Link = identity 
## 
## Estimated Correlation Parameters:
##       Estimate Std.err
## alpha    0.918  0.0151
## Number of clusters:   78   Maximum cluster size: 4</code></pre>
<p>Please note that geeglm can also work for the binary response variable by specifying the family as binomial. We will not discuss this in detail.</p>
<p>If we want to compare these models, we can use QIC.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(MuMIn) 
<span class="kw">model.sel</span>(model4,model5,<span class="dt">rank =</span> QIC)</code></pre></div>
<pre><code>## Model selection table 
##        (Intrc)      age  crrsm  male   year corstr  qLik  QIC delta weight
## model4    3.70 -0.00661 -0.289 0.140 -0.117        -43.0 -371  0.00  0.627
## model5    3.66 -0.00539 -0.318 0.168 -0.120    ar1 -43.1 -370  1.04  0.373
## Models ranked by QIC(x)</code></pre>
<p>Notice that smaller QIC values are better.</p>
</div>
</div>
<div id="non-linear-effects" class="section level2">
<h2><span class="header-section-number">12.3</span> Non-linear effects</h2>
<p>When we are fitting the regression models for continuous indepdendent variables, we are assuming the linearity of the effects.In this section, we use a hypothetical data set.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">time =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">11</span>, <span class="dv">12</span>, <span class="dv">13</span>, 
<span class="dv">14</span>, <span class="dv">15</span>, <span class="dv">16</span>, <span class="dv">18</span>, <span class="dv">19</span>, <span class="dv">20</span>, <span class="dv">21</span>, <span class="dv">22</span>, <span class="dv">24</span>, <span class="dv">25</span>, <span class="dv">26</span>, <span class="dv">27</span>, <span class="dv">28</span>, <span class="dv">29</span>, <span class="dv">30</span>), 
<span class="dt">counts =</span> <span class="kw">c</span>(<span class="fl">126.6</span>, <span class="fl">101.8</span>, <span class="fl">71.6</span>, <span class="fl">101.6</span>, <span class="fl">68.1</span>, <span class="fl">62.9</span>, <span class="fl">45.5</span>, <span class="fl">41.9</span>, 
<span class="fl">46.3</span>, <span class="fl">34.1</span>, <span class="fl">38.2</span>, <span class="fl">41.7</span>, <span class="fl">24.7</span>, <span class="fl">41.5</span>, <span class="fl">36.6</span>, <span class="fl">19.6</span>, 
<span class="fl">22.8</span>, <span class="fl">29.6</span>, <span class="fl">23.5</span>, <span class="fl">15.3</span>, <span class="fl">13.4</span>, <span class="fl">26.8</span>, <span class="fl">9.8</span>, <span class="fl">18.8</span>, <span class="fl">25.9</span>, <span class="fl">19.3</span>))
<span class="co">#To do a simple regression</span>
m1&lt;-<span class="kw">lm</span>(counts <span class="op">~</span><span class="st"> </span>time,<span class="dt">data=</span>x)
<span class="kw">summary</span>(m1)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = counts ~ time, data = x)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -20.08  -9.88  -1.88   8.49  39.44 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   87.155      6.019   14.48  2.3e-13 ***
## time          -2.825      0.332   -8.51  1.0e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 15.2 on 24 degrees of freedom
## Multiple R-squared:  0.751,  Adjusted R-squared:  0.741 
## F-statistic: 72.5 on 1 and 24 DF,  p-value: 1.03e-08</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#The model explains over 74% of the variance and has highly significant coefficients for the intercept and the independent variable and also a highly significant overall model p-value. </span></code></pre></div>
<p>Next, let’s plot the counts over time and superpose our linear model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(x<span class="op">$</span>time,x<span class="op">$</span>counts)
<span class="kw">abline</span>(<span class="kw">lm</span>(counts <span class="op">~</span><span class="st"> </span>time,<span class="dt">data=</span>x), <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-269-1.png" width="672" /></p>
<p>The model looks good, but we can see that the plot has curvature that is not explained well by a linear model. Now let’s fit a quadratic regression splines for time:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x<span class="op">$</span>time2&lt;-x<span class="op">$</span>time<span class="op">^</span><span class="dv">2</span>
m2&lt;-<span class="kw">lm</span>(counts <span class="op">~</span><span class="st"> </span>time<span class="op">+</span>time2,<span class="dt">data=</span>x)
<span class="kw">summary</span>(m2)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = counts ~ time + time2, data = x)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -24.265  -4.921  -0.952   5.586  18.773 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 110.1075     5.4803   20.09  4.4e-16 ***
## time         -7.4225     0.8058   -9.21  3.5e-09 ***
## time2         0.1506     0.0255    5.92  5.0e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.75 on 23 degrees of freedom
## Multiple R-squared:  0.901,  Adjusted R-squared:  0.893 
## F-statistic:  105 on 2 and 23 DF,  p-value: 2.7e-12</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#We can also use the following codes to obtain the same results.</span>
m22&lt;-<span class="kw">lm</span>(counts <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(time,<span class="dv">2</span>),<span class="dt">data=</span>x)
<span class="kw">summary</span>(m22)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = counts ~ poly(time, 2), data = x)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -24.265  -4.921  -0.952   5.586  18.773 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       42.61       1.91   22.28  &lt; 2e-16 ***
## poly(time, 2)1  -129.09       9.75  -13.24  3.1e-12 ***
## poly(time, 2)2    57.71       9.75    5.92  5.0e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.75 on 23 degrees of freedom
## Multiple R-squared:  0.901,  Adjusted R-squared:  0.893 
## F-statistic:  105 on 2 and 23 DF,  p-value: 2.7e-12</code></pre>
<p>We can see that the quadratic model performs even better, explaining 89.3% of the variance(an additional 15% of the variance). Let’s compare the two models:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">AIC</span>(m1)</code></pre></div>
<pre><code>## [1] 219</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">AIC</span>(m2)</code></pre></div>
<pre><code>## [1] 197</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(m1,m2)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: counts ~ time
## Model 2: counts ~ time + time2
##   Res.Df  RSS Df Sum of Sq  F Pr(&gt;F)    
## 1     24 5519                           
## 2     23 2188  1      3331 35  5e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We can see that the quadratic model is statistically significant better than the simple linear model. Now, let’s plot the quadratic model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">intervals &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">30</span>, <span class="dv">1</span>)
new&lt;-<span class="kw">data.frame</span>(<span class="dt">time=</span>intervals, <span class="dt">time2=</span>intervals<span class="op">^</span><span class="dv">2</span>)
new<span class="op">$</span>pre &lt;-<span class="st"> </span><span class="kw">predict</span>(m2,<span class="dt">newdata=</span>new)
<span class="kw">plot</span>(x<span class="op">$</span>time, x<span class="op">$</span>counts, <span class="dt">pch=</span><span class="dv">16</span>, <span class="dt">xlab =</span> <span class="st">&quot;Time (s)&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Counts&quot;</span>, <span class="dt">cex.lab =</span> <span class="fl">1.3</span>)
<span class="kw">lines</span>(new<span class="op">$</span>time, new<span class="op">$</span>pre, <span class="dt">col =</span> <span class="st">&quot;darkgreen&quot;</span>, <span class="dt">lwd =</span> <span class="dv">3</span>)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-272-1.png" width="672" /> The quadratic model appears to fit the data better than the linear model.</p>
<p>If we want to further fit a cubic model:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x<span class="op">$</span>time3&lt;-x<span class="op">$</span>time<span class="op">^</span><span class="dv">3</span>
m3&lt;-<span class="kw">lm</span>(counts <span class="op">~</span><span class="st"> </span>time<span class="op">+</span>time2<span class="op">+</span>time3,<span class="dt">data=</span>x)
<span class="kw">summary</span>(m3)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = counts ~ time + time2 + time3, data = x)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -25.058  -6.395  -0.006   6.458  20.203 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 114.37287    6.45922   17.71  1.7e-14 ***
## time         -9.50357    1.88791   -5.03  4.9e-05 ***
## time2         0.33104    0.15049    2.20    0.039 *  
## time3        -0.00403    0.00332   -1.22    0.237    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.65 on 22 degrees of freedom
## Multiple R-squared:  0.908,  Adjusted R-squared:  0.895 
## F-statistic:   72 on 3 and 22 DF,  p-value: 1.56e-11</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(m2,m3)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: counts ~ time + time2
## Model 2: counts ~ time + time2 + time3
##   Res.Df  RSS Df Sum of Sq    F Pr(&gt;F)
## 1     23 2188                         
## 2     22 2050  1       138 1.48   0.24</code></pre>
<p>We can find that the cubic regression does not improve the model a lot.</p>
<p>There are some other approaches we can choose for the non-linear fitting.For instance, the B-spline basis function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(splines)
m4&lt;-<span class="kw">lm</span>(counts <span class="op">~</span><span class="st"> </span><span class="kw">bs</span>(time),<span class="dt">data=</span>x)
<span class="kw">summary</span>(m4)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = counts ~ bs(time), data = x)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -25.058  -6.395  -0.006   6.458  20.203 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   114.37       6.46   17.71  1.7e-14 ***
## bs(time)1     -95.04      18.88   -5.03  4.9e-05 ***
## bs(time)2     -90.76      13.60   -6.68  1.0e-06 ***
## bs(time)3     -96.05       9.70   -9.90  1.5e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.65 on 22 degrees of freedom
## Multiple R-squared:  0.908,  Adjusted R-squared:  0.895 
## F-statistic:   72 on 3 and 22 DF,  p-value: 1.56e-11</code></pre>
<p>We can specify the degree of freedom and knots by using the df and knots arguments in the bs() function.To know more about the bs() function, please refer to:</p>
<pre><code>?bs</code></pre>
</div>
<div id="epi-packages--epitab" class="section level2">
<h2><span class="header-section-number">12.4</span> Epi packages- Epitab()</h2>
<p>There are some R packages specifically for the epidemiologists, which can be used easily and efficiently. For example, epicalc package and epitools package. We will only discuss the epitools package here.</p>
<pre><code>install.packages(&quot;epitools&quot;)</code></pre>
<p>Package epitools is for training and practicing epidemiologists including methods for twoway and multi-way contingency tables.There are a number of useful functions built-in this package. For instance, the function epitab() can be used to calculates risks, risk ratios, odds ratios and their associated confidence intervals. Here are a few examples.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(epitools)</code></pre></div>
<pre><code>## 
## Attaching package: &#39;epitools&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:survival&#39;:
## 
##     ratetable</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dig&lt;-<span class="kw">read.csv</span>(<span class="st">&quot;data/dig.csv&quot;</span>,<span class="dt">stringsAsFactors=</span>F) <span class="co">#digitalis data</span>
<span class="kw">names</span>(dig)</code></pre></div>
<pre><code>##  [1] &quot;ID&quot;       &quot;TRTMT&quot;    &quot;AGE&quot;      &quot;RACE&quot;     &quot;SEX&quot;      &quot;EJF_PER&quot; 
##  [7] &quot;EJFMETH&quot;  &quot;CHESTX&quot;   &quot;BMI&quot;      &quot;KLEVEL&quot;   &quot;CREAT&quot;    &quot;DIGDOSER&quot;
## [13] &quot;CHFDUR&quot;   &quot;RALES&quot;    &quot;ELEVJVP&quot;  &quot;PEDEMA&quot;   &quot;RESTDYS&quot;  &quot;EXERTDYS&quot;
## [19] &quot;ACTLIMIT&quot; &quot;S3&quot;       &quot;PULCONG&quot;  &quot;NSYM&quot;     &quot;HEARTRTE&quot; &quot;DIABP&quot;   
## [25] &quot;SYSBP&quot;    &quot;FUNCTCLS&quot; &quot;CHFETIOL&quot; &quot;PREVMI&quot;   &quot;ANGINA&quot;   &quot;DIABETES&quot;
## [31] &quot;HYPERTEN&quot; &quot;DIGUSE&quot;   &quot;DIURETK&quot;  &quot;DIURET&quot;   &quot;KSUPP&quot;    &quot;ACEINHIB&quot;
## [37] &quot;NITRATES&quot; &quot;HYDRAL&quot;   &quot;VASOD&quot;    &quot;DIGDOSE&quot;  &quot;CVD&quot;      &quot;CVDDAYS&quot; 
## [43] &quot;WHF&quot;      &quot;WHFDAYS&quot;  &quot;DIG&quot;      &quot;DIGDAYS&quot;  &quot;MI&quot;       &quot;MIDAYS&quot;  
## [49] &quot;UANG&quot;     &quot;UANGDAYS&quot; &quot;STRK&quot;     &quot;STRKDAYS&quot; &quot;SVA&quot;      &quot;SVADAYS&quot; 
## [55] &quot;VENA&quot;     &quot;VENADAYS&quot; &quot;CREV&quot;     &quot;CREVDAYS&quot; &quot;OCVD&quot;     &quot;OCVDDAYS&quot;
## [61] &quot;RINF&quot;     &quot;RINFDAYS&quot; &quot;OTH&quot;      &quot;OTHDAYS&quot;  &quot;HOSP&quot;     &quot;HOSPDAYS&quot;
## [67] &quot;NHOSP&quot;    &quot;DEATH&quot;    &quot;DEATHDAY&quot; &quot;REASON&quot;   &quot;DWHF&quot;     &quot;DWHFDAYS&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mytab&lt;-<span class="kw">xtabs</span>(<span class="op">~</span>TRTMT <span class="op">+</span><span class="st"> </span>DEATH, <span class="dt">data=</span>dig)
<span class="co">#If we want to get the odds ratio, we can use:</span>
OR&lt;-mytab[<span class="dv">1</span>,<span class="dv">1</span>]<span class="op">*</span>mytab[<span class="dv">2</span>,<span class="dv">2</span>]<span class="op">/</span>(mytab[<span class="dv">2</span>,<span class="dv">1</span>]<span class="op">*</span>mytab[<span class="dv">1</span>,<span class="dv">2</span>])
<span class="kw">print</span>(OR)</code></pre></div>
<pre><code>## [1] 0.986</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Or, we can choose to use the epitab()function:</span>
<span class="kw">epitab</span>(mytab)</code></pre></div>
<pre><code>## $tab
##      DEATH
## TRTMT    0    p0    1    p1 oddsratio lower upper p.value
##     0 2209 0.499 1194 0.503     1.000    NA    NA      NA
##     1 2216 0.501 1181 0.497     0.986 0.892  1.09   0.799
## 
## $measure
## [1] &quot;wald&quot;
## 
## $conf.level
## [1] 0.95
## 
## $pvalue
## [1] &quot;fisher.exact&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#There are other ways to use the epitab function:</span>
<span class="kw">epitab</span>(dig<span class="op">$</span>TRTMT,dig<span class="op">$</span>DEATH)</code></pre></div>
<pre><code>## $tab
##          Outcome
## Predictor    0    p0    1    p1 oddsratio lower upper p.value
##         0 2209 0.499 1194 0.503     1.000    NA    NA      NA
##         1 2216 0.501 1181 0.497     0.986 0.892  1.09   0.799
## 
## $measure
## [1] &quot;wald&quot;
## 
## $conf.level
## [1] 0.95
## 
## $pvalue
## [1] &quot;fisher.exact&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">epitab</span>(<span class="kw">c</span>(<span class="dv">2209</span>, <span class="dv">1194</span>, <span class="dv">2216</span>, <span class="dv">1181</span>))</code></pre></div>
<pre><code>## $tab
##           Outcome
## Predictor  Disease1    p0 Disease2    p1 oddsratio lower upper p.value
##   Exposed1     2209 0.499     1194 0.503     1.000    NA    NA      NA
##   Exposed2     2216 0.501     1181 0.497     0.986 0.892  1.09   0.799
## 
## $measure
## [1] &quot;wald&quot;
## 
## $conf.level
## [1] 0.95
## 
## $pvalue
## [1] &quot;fisher.exact&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#We can also use the epitab function to get the risk ratio:</span>
<span class="kw">epitab</span>(mytab,<span class="dt">method=</span><span class="st">&quot;riskratio&quot;</span>)</code></pre></div>
<pre><code>## $tab
##      DEATH
## TRTMT    0    p0    1    p1 riskratio lower upper p.value
##     0 2209 0.649 1194 0.351     1.000    NA    NA      NA
##     1 2216 0.652 1181 0.348     0.991 0.929  1.06   0.799
## 
## $measure
## [1] &quot;wald&quot;
## 
## $conf.level
## [1] 0.95
## 
## $pvalue
## [1] &quot;fisher.exact&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Or we can use directly riskration()function:</span>
<span class="kw">riskratio</span>(mytab)</code></pre></div>
<pre><code>## $data
##        DEATH
## TRTMT      0    1 Total
##   0     2209 1194  3403
##   1     2216 1181  3397
##   Total 4425 2375  6800
## 
## $measure
##      risk ratio with 95% C.I.
## TRTMT estimate lower upper
##     0    1.000    NA    NA
##     1    0.991 0.929  1.06
## 
## $p.value
##      two-sided
## TRTMT midp.exact fisher.exact chi.square
##     0         NA           NA         NA
##     1      0.782        0.799      0.781
## 
## $correction
## [1] FALSE
## 
## attr(,&quot;method&quot;)
## [1] &quot;Unconditional MLE &amp; normal approximation (Wald) CI&quot;</code></pre>
<p>For more information about epitab or riskratio, we can use:</p>
<pre><code>?epitab
?riskratio</code></pre>
<p>For more inforamtion about the epitools package, please refer to (<a href="https://cran.r-project.org/web/packages/epitools/epitools.pdf" class="uri">https://cran.r-project.org/web/packages/epitools/epitools.pdf</a>).</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="survival-analysis.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/11-Bootstrapping.Rmd",
"text": "Edit"
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
