DGtal: 3dVolViewer.cpp File Reference
3dVolViewer.cpp File Reference
#include <iostream>
#include <QtGui/qapplication.h>
#include "DGtal/base/Common.h"
#include "DGtal/io/readers/VolReader.h"
#include "DGtal/io/viewers/Viewer3D.h"
#include "DGtal/io/DrawWithDisplay3DModifier.h"
#include "DGtal/io/Color.h"
#include "DGtal/io/colormaps/GradientColorMap.h"
#include "DGtal/images/ImageSelector.h"
#include <boost/program_options/options_description.hpp>
#include <boost/program_options/parsers.hpp>
#include <boost/program_options/variables_map.hpp>
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 54 of file 3dVolViewer.cpp.
References DGtal::Color::blue(), DGtal::Trace::error(), DGtal::Color::green(), DGtal::Trace::info(), DGtal::Color::red(), and DGtal::trace.