DGtal: ArithmeticalDSS.cpp File Reference
ArithmeticalDSS.cpp File Reference
DGtal examples
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/geometry/2d/ArithmeticalDSS.h"
#include "DGtal/geometry/2d/FreemanChain.h"
#include "DGtal/base/BasicTypes.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/helpers/StdDefs.h"
Functions
int main ()
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
Isabelle Sivignon (isabelle.sivignon@gipsa-lab.grenoble-inp.fr) gipsa-lab Grenoble Images Parole Signal Automatique (CNRS, UMR 5216), CNRS, France
Tristan Roussillon (tristan.roussillon@liris.cnrs.fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date:
2010/11/30
An example file named ArithmeticalDSS.
This file is part of the DGtal library.
Definition in file ArithmeticalDSS.cpp.
Function Documentation
int main ()
Definition at line 49 of file ArithmeticalDSS.cpp.
References DGtal::FreemanChain< TInteger >::begin(), DGtal::FreemanChain< TInteger >::end(), LibBoard::Board::saveSVG(), and DGtal::HyperRectDomain< TSpace >::styleName().