DGtal: DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity > Class Template Reference
DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity > Class Template Reference
Aim: Dynamic recognition of a 3d-digital straight segment (DSS)
#include <ArithmeticalDSS3d.h>
Public Types
typedef TInteger Integer
typedef TIterator ConstIterator
typedef ArithmeticalDSS
< ConstIterator, TInteger,
connectivity > Self
typedef ArithmeticalDSS
< std::reverse_iterator
< ConstIterator >, TInteger,
connectivity > Reverse
typedef
IteratorCirculatorTraits
< ConstIterator >::Value Point3d
typedef
IteratorCirculatorTraits
< ConstIterator >::Value Vector3d
typedef Point3d::Coordinate Coordinate
typedef DGtal::PointVector
< 2, Coordinate > Point2d
typedef DGtal::PointVector
< 2, Coordinate > Vector2d
typedef DGtal::PointVector
< 2, double > PointD2d
typedef DGtal::PointVector
< 3, double > PointD3d
typedef DGtal::PointVector
< 3, double > VectorD3d
typedef Point3dTo2dXY< Coordinate > XYModifier
typedef Point3dTo2dXZ< Coordinate > XZModifier
typedef Point3dTo2dYZ< Coordinate > YZModifier
typedef ConstIteratorAdapter
< ConstIterator, XYModifier > XYIteratorAdapter
typedef ConstIteratorAdapter
< ConstIterator, XZModifier > XZIteratorAdapter
typedef ConstIteratorAdapter
< ConstIterator, YZModifier > YZIteratorAdapter
typedef DGtal::ArithmeticalDSS
< XYIteratorAdapter, TInteger,
connectivity > XYArithmeticalDSS
typedef DGtal::ArithmeticalDSS
< XZIteratorAdapter, TInteger,
connectivity > XZArithmeticalDSS
typedef DGtal::ArithmeticalDSS
< YZIteratorAdapter, TInteger,
connectivity > YZArithmeticalDSS
Public Member Functions
BOOST_CONCEPT_ASSERT ((CInteger< TInteger >))
ArithmeticalDSS3d ()
ArithmeticalDSS3d (const ConstIterator &it)
void init (const ConstIterator &it)
ArithmeticalDSS3d (const ArithmeticalDSS3d &other)
ArithmeticalDSS3d & operator= (const ArithmeticalDSS3d &other)
bool operator== (const ArithmeticalDSS3d &other) const
bool operator!= (const ArithmeticalDSS3d &other) const
~ArithmeticalDSS3d ()
bool extend (const ConstIterator &it)
void getParameters (Vector3d &direction, PointD3d &intercept, PointD3d &thickness) const
bool isValid () const
std::string styleName () const
void selfDisplay (std::ostream &out)
DrawableWithDisplay3D * defaultStyleDisplay3D (std::string mode="") const
void selfDrawDisplay3D (Display3D &display) const
void selfDrawAsPointsDisplay3D (Display3D &display) const
void selfDrawAsBoundingBoxDisplay3D (Display3D &display) const
Protected Attributes
XYArithmeticalDSS myXYalgo
XZArithmeticalDSS myXZalgo
YZArithmeticalDSS myYZalgo
ConstIterator myF
ConstIterator myL
Detailed Description
template<typename TIterator, typename TInteger, int connectivity>
class DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >
Aim: Dynamic recognition of a 3d-digital straight segment (DSS)
Description of class 'ArithmeticalDSS3d'
Definition at line 75 of file ArithmeticalDSS3d.h.
Member Typedef Documentation
template<typename TIterator, typename TInteger, int connectivity> typedef TIterator DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::ConstIterator
Definition at line 91 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef Point3d::Coordinate DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::Coordinate
Definition at line 99 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef TInteger DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::Integer
Definition at line 87 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef DGtal::PointVector<2,Coordinate> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::Point2d
Definition at line 101 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef IteratorCirculatorTraits<ConstIterator>::Value DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::Point3d
Definition at line 97 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef DGtal::PointVector<2,double> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::PointD2d
Definition at line 104 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef DGtal::PointVector<3,double> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::PointD3d
Definition at line 105 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef ArithmeticalDSS<std::reverse_iterator<ConstIterator>,TInteger,connectivity> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::Reverse
Definition at line 93 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef ArithmeticalDSS<ConstIterator,TInteger,connectivity> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::Self
Definition at line 92 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef DGtal::PointVector<2,Coordinate> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::Vector2d
Definition at line 102 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef IteratorCirculatorTraits<ConstIterator>::Value DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::Vector3d
Definition at line 98 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef DGtal::PointVector<3,double> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::VectorD3d
Definition at line 106 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef DGtal::ArithmeticalDSS<XYIteratorAdapter,TInteger,connectivity> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::XYArithmeticalDSS
Definition at line 118 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef ConstIteratorAdapter<ConstIterator,XYModifier> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::XYIteratorAdapter
Definition at line 112 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef Point3dTo2dXY<Coordinate> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::XYModifier
Definition at line 109 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef DGtal::ArithmeticalDSS<XZIteratorAdapter,TInteger,connectivity> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::XZArithmeticalDSS
Definition at line 119 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef ConstIteratorAdapter<ConstIterator,XZModifier> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::XZIteratorAdapter
Definition at line 113 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef Point3dTo2dXZ<Coordinate> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::XZModifier
Definition at line 110 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef DGtal::ArithmeticalDSS<YZIteratorAdapter,TInteger,connectivity> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::YZArithmeticalDSS
Definition at line 120 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef ConstIteratorAdapter<ConstIterator,YZModifier> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::YZIteratorAdapter
Definition at line 114 of file ArithmeticalDSS3d.h.
template<typename TIterator, typename TInteger, int connectivity> typedef Point3dTo2dYZ<Coordinate> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::YZModifier
Definition at line 111 of file ArithmeticalDSS3d.h.
Constructor & Destructor Documentation
template<typename TIterator , typename TInteger , int connectivity> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::ArithmeticalDSS3d () [inline]
Default constructor. not valid
Definition at line 52 of file ArithmeticalDSS3d.ih.
{
}
template<typename TIterator , typename TInteger , int connectivity> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::ArithmeticalDSS3d (const ConstIterator & it) [inline]
Constructor with initialisation
Parameters:
it an iterator
Constructor with initialisation
Definition at line 61 of file ArithmeticalDSS3d.ih.
{
  init(it);
}
template<typename TIterator , typename TInteger , int connectivity> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::ArithmeticalDSS3d (const ArithmeticalDSS3d< TIterator, TInteger, connectivity > & other) [inline]
Copy constructor.
Parameters:
other the object to clone.
Copy constructor.
Parameters:
other the object to clone. Forbidden by default.
Definition at line 94 of file ArithmeticalDSS3d.ih.
                                                                     :
    myXYalgo(other.myXYalgo), myXZalgo(other.myXZalgo), myYZalgo(other.myYZalgo),
    myF(other.myF), myL(other.myL) {}
template<typename TIterator, typename TInteger, int connectivity> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::~ArithmeticalDSS3d () [inline]
Destructor.
Definition at line 179 of file ArithmeticalDSS3d.h.
{};
Member Function Documentation
template<typename TIterator, typename TInteger, int connectivity> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::BOOST_CONCEPT_ASSERT ((CInteger< TInteger >))
template<typename TIterator, typename TInteger, int connectivity> DrawableWithDisplay3D* DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::defaultStyleDisplay3D (std::string mode = "") const
Default drawing style object.
Returns:
the dyn. alloc. default style for this object.
template<typename TIterator , typename TInteger , int connectivity> bool DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::extend (const ConstIterator & it) [inline]
Tests whether the union between a point (adding to the front of the DSS with respect to the scan orientaion) and a DSS is a DSS. Computes the parameters of the new DSS with the adding point if true.
Parameters:
itf an iterator on a sequence of points
Returns:
'true' if the union is a DSS, 'false' otherwise.
Tests whether the union between a point (adding to the front of the DSS with respect to the scan orientaion) and a DSS is a DSS. Computes the parameters of the new DSS with the adding point if true.
Parameters:
it an iterator on a sequence of points
Returns:
'true' if the union is a DSS, 'false' otherwise.
Definition at line 174 of file ArithmeticalDSS3d.ih.
{
//projection on xy-plane
  XYIteratorAdapter XYit(it);
  bool XYflag = true;
  if (myXYalgo.getFrontPoint() != *XYit) {
    XYflag = myXYalgo.isExtendable(XYit);
  }
//projection on xz-plane
  XZIteratorAdapter XZit(it);
  bool XZflag = true;
  if (myXZalgo.getFrontPoint() != *XZit) {
    XZflag = myXZalgo.isExtendable(XZit);
  }
//projection on yz-plane
  YZIteratorAdapter YZit(it);
  bool YZflag = true;
  if (myYZalgo.getFrontPoint() != *YZit) {
    YZflag = myYZalgo.isExtendable(YZit);
  }
  if ( (XYflag)&&(XZflag)&&(YZflag) ) {
    myXYalgo.extend(XYit);
    myXZalgo.extend(XZit);
    myYZalgo.extend(YZit);
    myL = it;
    return true;
  } else return false;
}
template<typename TIterator , typename TInteger , int connectivity> void DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::getParameters (Vector3d & direction, PointD3d & intercept, PointD3d & thickness) const [inline]
Computes the parameters (direction, intercept, thickness) of the DSS
Parameters:
direction
intercept
thickness
Definition at line 236 of file ArithmeticalDSS3d.ih.
{
  //let us take the pair of projection planes for which
  //the common coordinate of the main vector cannot be 0
  if (myXYalgo.getB() != 0) { //XY-plane, XZ-plane
    Integer a1 = myXYalgo.getB();
    Integer b1 = myXYalgo.getA();
    Integer a2 = myXZalgo.getB();
    Integer c1 = myXZalgo.getA();
    direction = Point3d(a1*a2,a2*b1,a1*c1);
    Integer mu1 = myXYalgo.getMu();
    Integer mu2 = myXZalgo.getMu();
    double y = (double) -NumberTraits<TInteger>::castToInt64_t(mu1) / a1;
    double z = (double) -NumberTraits<TInteger>::castToInt64_t(mu2) / a2;
    intercept = PointD3d(0,y,z);
    Integer omega1 = myXYalgo.getOmega()-1;
    Integer omega2 = myXZalgo.getOmega()-1;
    double ty = (double) -NumberTraits<TInteger>::castToInt64_t(omega1) / a1;
    double tz = (double) -NumberTraits<TInteger>::castToInt64_t(omega2) / a2;
    thickness = PointD3d(0,ty,tz);
  } else {
    if (myXYalgo.getA() != 0) {//XY-plane, YZ-plane
      Integer a1 = myXYalgo.getB();
      Integer b1 = myXYalgo.getA();
      Integer b2 = myYZalgo.getB();
      Integer c2 = myYZalgo.getA();
      direction = Point3d(b1*a1,b1*b2,b2*c2);
    Integer mu1 = myXYalgo.getMu();
    Integer mu2 = myYZalgo.getMu();
    double x = (double) NumberTraits<TInteger>::castToInt64_t(mu1) / b1;
    double z = (double) -NumberTraits<TInteger>::castToInt64_t(mu2) / b2;
    intercept = PointD3d(x,0,z);
    Integer omega1 = myXYalgo.getOmega()-1;
    Integer omega2 = myYZalgo.getOmega()-1;
    double tx = (double) NumberTraits<TInteger>::castToInt64_t(omega1) / b1;
    double tz = (double) -NumberTraits<TInteger>::castToInt64_t(omega2) / b2;
    thickness = PointD3d(tx,0,tz);
    } else {
      if (myYZalgo.getA() != 0) {//YZ-plane, XZ-plane
        Integer b2 = myYZalgo.getB();
        Integer c2 = myYZalgo.getA();
        Integer a2 = myXZalgo.getB();
        Integer c1 = myXZalgo.getA();
        direction = Point3d(c2*a2,c1*b2,c1*c2);
        Integer mu1 = myYZalgo.getMu();
        Integer mu2 = myXZalgo.getMu();
        double y = (double) NumberTraits<TInteger>::castToInt64_t(mu1) / c2;
        double x = (double) NumberTraits<TInteger>::castToInt64_t(mu2) / c1;
        intercept = PointD3d(x,y,0);
        Integer omega1 = myYZalgo.getOmega()-1;
        Integer omega2 = myXZalgo.getOmega()-1;
        double ty = (double) NumberTraits<TInteger>::castToInt64_t(omega1) / c2;
        double tx = (double) NumberTraits<TInteger>::castToInt64_t(omega2) / c1;
        thickness = PointD3d(tx,ty,0);
      } else {//degenerated case
        direction = Point3d(0,0,0);
        intercept = PointD3d(0,0,0);
        thickness = PointD3d(0,0,0);
      }
    }
  }
}
template<typename TIterator , typename TInteger , int connectivity> void DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::init (const ConstIterator & it) [inline]
Initialisation.
Parameters:
it an iterator
Initialisation.
Parameters:
it an iterator on a sequence of points
Definition at line 72 of file ArithmeticalDSS3d.ih.
{
  myF = it;
  myL = it;
  XYIteratorAdapter XYit(it);
  myXYalgo.init(XYit);
  XZIteratorAdapter XZit(it);
  myXZalgo.init(XZit);
  YZIteratorAdapter YZit(it);
  myYZalgo.init(YZit);
}
template<typename TIterator , typename TInteger , int connectivity> bool DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::isValid () const [inline]
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
Definition at line 216 of file ArithmeticalDSS3d.ih.
{
  return ( (myXYalgo.isValid())&&
           (myXZalgo.isValid())&&
           (myYZalgo.isValid()) );
}
template<typename TIterator , typename TInteger , int connectivity> bool DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::operator!= (const ArithmeticalDSS3d< TIterator, TInteger, connectivity > & other) const [inline]
Difference operator.
Parameters:
other the object to compare with.
Returns:
'false' if equal 'true' otherwise
Definition at line 152 of file ArithmeticalDSS3d.ih.
{
  return (!(*this == other));
}
template<typename TIterator , typename TInteger , int connectivity> DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity > & DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::operator= (const ArithmeticalDSS3d< TIterator, TInteger, connectivity > & other) [inline]
Assignment.
Parameters:
other the object to copy.
Returns:
a reference on 'this'.
Assignment.
Parameters:
other the object to copy.
Returns:
a reference on 'this'. Forbidden by default.
Definition at line 109 of file ArithmeticalDSS3d.ih.
References DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::myF, DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::myL, DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::myXYalgo, DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::myXZalgo, and DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::myYZalgo.
{
  myXYalgo = other.myXYalgo;
  myXZalgo = other.myXZalgo;
  myYZalgo = other.myYZalgo;
  myF = other.myF;
  myL = other.myL;
  return *this;
}
template<typename TIterator , typename TInteger , int connectivity> bool DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::operator== (const ArithmeticalDSS3d< TIterator, TInteger, connectivity > & other) const [inline]
Equality operator.
Parameters:
other the object to compare with.
Returns:
'true' either if the leaning points perfectly match or if the first leaning points match to the last ones (same DSS scanned in the reverse way) and 'false' otherwise
Equality operator.
Parameters:
other the object to compare with.
Returns:
'true' either if the points perfectly match or if the first points match to the last ones (same DSS scanned in the conversed way) and 'false' otherwise
Definition at line 133 of file ArithmeticalDSS3d.ih.
References DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::myF, DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::myL, DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::myXYalgo, DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::myXZalgo, and DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::myYZalgo.
{
  return (  (   myXYalgo == other.myXYalgo ) &&
            (   myXZalgo == other.myXZalgo ) &&
            (   myYZalgo == other.myYZalgo ) &&
            (*myF == *other.myF) &&
            (*myL == *other.myL) );
}
template<typename TIterator , typename TInteger , int connectivity> void DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::selfDisplay (std::ostream & out) [inline]
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
Definition at line 341 of file ArithmeticalDSS3d.ih.
{
  out << "[ArithmeticalDSS3d]" <<  endl;
  out << "[XYprojection]" <<  endl;
  out << myXYalgo <<  endl;
  out << "[XZprojection]" <<  endl;
  out << myXZalgo <<  endl;
  out << "[YZprojection]" <<  endl;
  out << myYZalgo <<  endl;
  out << "[End ArithmeticalDSS3d]" <<  endl;
}
template<typename TIterator , typename TInteger , int connectivity> void DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::selfDrawAsBoundingBoxDisplay3D (Display3D & display) const [inline]
Definition at line 409 of file ArithmeticalDSS3d.ih.
References DGtal::Display3D::addLine(), and DGtal::Display3D::addQuad().
{
  //get DSS parameters
  Vector3d v; //direction vector
  PointD3d mu; //intercept
  PointD3d omega; //thickness
  getParameters(v,mu,omega);
  //casting coordinates of v in double
  VectorD3d u = VectorD3d(
  (double) NumberTraits<Integer>::castToInt64_t(v[0]),
  (double) NumberTraits<Integer>::castToInt64_t(v[1]),
  (double) NumberTraits<Integer>::castToInt64_t(v[2]) );
  //L2 norm of u
  double n = u[0]*u[0] + u[1]*u[1] + u[2]*u[2];
  //first and last points
  PointD3d f = PointD3d(
  (double) NumberTraits<Integer>::castToInt64_t((*myF)[0]),
  (double) NumberTraits<Integer>::castToInt64_t((*myF)[1]),
  (double) NumberTraits<Integer>::castToInt64_t((*myF)[2]) );
  PointD3d l = PointD3d(
  (double) NumberTraits<Integer>::castToInt64_t((*myL)[0]),
  (double) NumberTraits<Integer>::castToInt64_t((*myL)[1]),
  (double) NumberTraits<Integer>::castToInt64_t((*myL)[2]) );
  if (n != 0) {
    //last coefficient of the normal plane to the DSS direction
    //passing trough f and l
    double df = -u[0]*f[0] -u[1]*f[1] -u[2]*f[2];
    double dl = -u[0]*l[0] -u[1]*l[1] -u[2]*l[2];
    //omega masks
    PointD3d omega1, omega2;
    if (omega[0] == 0) {
      omega1 = PointD3d(0,omega[1],0);
      omega2 = PointD3d(0,0,omega[2]);
    } else {
      if (omega[1] == 0) {
        omega1 = PointD3d(omega[0],0,0);
        omega2 = PointD3d(0,0,omega[2]);
      } else {//omega[2] == 0
        omega1 = PointD3d(omega[0],0,0);
        omega2 = PointD3d(0,omega[1],0);
      }
    }
    double m1 = u[0]*mu[0] + u[1]*mu[1] + u[2]*mu[2];
    double m2 = u[0]*(mu[0]+omega1[0]) + u[1]*(mu[1]+omega1[1]) + u[2]*(mu[2]+omega1[2]);
    double m3 = u[0]*(mu[0]+omega2[0]) + u[1]*(mu[1]+omega2[1]) + u[2]*(mu[2]+omega2[2]);
    double m4 = u[0]*(mu[0]+omega[0]) + u[1]*(mu[1]+omega[1]) + u[2]*(mu[2]+omega[2]);
    //4 lines
    PointD3d pf = PointD3d( mu[0] - ( (m1+df)*u[0] )/n,
                            mu[1] - ( (m1+df)*u[1] )/n,
                            mu[2] - ( (m1+df)*u[2] )/n );
    PointD3d pl = PointD3d( mu[0] - ( (m1+dl)*u[0] )/n,
                            mu[1] - ( (m1+dl)*u[1] )/n,
                            mu[2] - ( (m1+dl)*u[2] )/n );
      display.addLine(pf[0], pf[1], pf[2], pl[0], pl[1], pl[2],
                     Color(250,0,0));
    PointD3d pf2 = PointD3d((mu[0]+omega1[0]) - ( (m2+df)*u[0] )/n,
                            (mu[1]+omega1[1]) - ( (m2+df)*u[1] )/n,
                            (mu[2]+omega1[2]) - ( (m2+df)*u[2] )/n );
    PointD3d pl2 = PointD3d((mu[0]+omega1[0]) - ( (m2+dl)*u[0] )/n,
                            (mu[1]+omega1[1]) - ( (m2+dl)*u[1] )/n,
                            (mu[2]+omega1[2]) - ( (m2+dl)*u[2] )/n );
      display.addLine(pf2[0], pf2[1], pf2[2], pl2[0], pl2[1], pl2[2],
                     Color(250,0,0));
    PointD3d pf3 = PointD3d((mu[0]+omega2[0]) - ( (m3+df)*u[0] )/n,
                            (mu[1]+omega2[1]) - ( (m3+df)*u[1] )/n,
                            (mu[2]+omega2[2]) - ( (m3+df)*u[2] )/n );
    PointD3d pl3 = PointD3d((mu[0]+omega2[0]) - ( (m3+dl)*u[0] )/n,
                            (mu[1]+omega2[1]) - ( (m3+dl)*u[1] )/n,
                            (mu[2]+omega2[2]) - ( (m3+dl)*u[2] )/n );
      display.addLine(pf3[0], pf3[1], pf3[2], pl3[0], pl3[1], pl3[2],
                     Color(250,0,0));
    PointD3d pf4 = PointD3d((mu[0]+omega[0]) - ( (m4+df)*u[0] )/n,
                            (mu[1]+omega[1]) - ( (m4+df)*u[1] )/n,
                            (mu[2]+omega[2]) - ( (m4+df)*u[2] )/n );
    PointD3d pl4 = PointD3d((mu[0]+omega[0]) - ( (m4+dl)*u[0] )/n,
                            (mu[1]+omega[1]) - ( (m4+dl)*u[1] )/n,
                            (mu[2]+omega[2]) - ( (m4+dl)*u[2] )/n );
      display.addLine(pf4[0], pf4[1], pf4[2], pl4[0], pl4[1], pl4[2],
                     Color(250,0,0));
    //two end facets
    display.addQuad(pf[0],pf[1],pf[2],
                   pf2[0],pf2[1],pf2[2],
                   pf4[0],pf4[1],pf4[2],
                   pf3[0],pf3[1],pf3[2],
                   Color(250,0,0));
    display.addQuad(pl[0],pl[1],pl[2],
                   pl2[0],pl2[1],pl2[2],
                   pl4[0],pl4[1],pl4[2],
                   pl3[0],pl3[1],pl3[2],
                   Color(250,0,0));
  }
}
template<typename TIterator , typename TInteger , int connectivity> void DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::selfDrawAsPointsDisplay3D (Display3D & display) const [inline]
Definition at line 368 of file ArithmeticalDSS3d.ih.
References DGtal::Display3D::addLine(), and DGtal::Display3D::getMode().
{
  // Draw points
  display << CustomColors3D(Color(250,250,250,100),Color(250,250,250,100));
  ConstIterator end = myL; ++end;
  for (ConstIterator i = myF; i != end; ++i) {
    Point3d p = *i;
    display << p;
  }
  // Draw a linking polygonal line if the voxels are drawn as points.
  if(display.getMode("PointVector")=="Grid")
    {
      ConstIterator k = myF;
      Point3d prevp = *k;
      double xprevp = (double) NumberTraits<TInteger>::castToInt64_t(prevp[0]);
      double yprevp = (double) NumberTraits<TInteger>::castToInt64_t(prevp[1]);
      double zprevp = (double) NumberTraits<TInteger>::castToInt64_t(prevp[2]);
      ++k;
      for ( ; k != end; ++k) {
        Point3d p = *k;
        double xp = (double) NumberTraits<TInteger>::castToInt64_t(p[0]);
        double yp = (double) NumberTraits<TInteger>::castToInt64_t(p[1]);
        double zp = (double) NumberTraits<TInteger>::castToInt64_t(p[2]);
        display.addLine(xprevp,yprevp,zprevp,
                       xp,yp,zp,
                       Color(0,250,0));
        xprevp = xp;
        yprevp = yp;
        zprevp = zp;
      }
    }
}
template<typename TIterator , typename TInteger , int connectivity> void DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::selfDrawDisplay3D (Display3D & display) const [inline]
Draw the object with QGLViewer
Parameters:
viewer the output where the object is drawn.
Definition at line 529 of file ArithmeticalDSS3d.ih.
References DGtal::Display3D::getMode().
{
  std::string mode = display.getMode( styleName() );
  if ( mode == "BoundingBox" )
    selfDrawAsBoundingBoxDisplay3D( display );
  else if ( mode == "Points" )
    selfDrawAsPointsDisplay3D(display);
  else if ( ( mode == "" ) )
  {
    selfDrawAsPointsDisplay3D(display);
   }
}
template<typename TIterator , typename TInteger , int connectivity> std::string DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::styleName () const [inline]
Returns:
the style name used for drawing this object.
Definition at line 326 of file ArithmeticalDSS3d.ih.
{
  return "ArithmeticalDSS3d";
}
Field Documentation
template<typename TIterator, typename TInteger, int connectivity> ConstIterator DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::myF [protected]
Definition at line 264 of file ArithmeticalDSS3d.h.
Referenced by DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::operator=(), and DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::operator==().
template<typename TIterator, typename TInteger, int connectivity> ConstIterator DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::myL [protected]
Definition at line 264 of file ArithmeticalDSS3d.h.
Referenced by DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::operator=(), and DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::operator==().
template<typename TIterator, typename TInteger, int connectivity> XYArithmeticalDSS DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::myXYalgo [protected]
Definition at line 259 of file ArithmeticalDSS3d.h.
Referenced by DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::operator=(), and DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::operator==().
template<typename TIterator, typename TInteger, int connectivity> XZArithmeticalDSS DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::myXZalgo [protected]
Definition at line 260 of file ArithmeticalDSS3d.h.
Referenced by DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::operator=(), and DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::operator==().
template<typename TIterator, typename TInteger, int connectivity> YZArithmeticalDSS DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::myYZalgo [protected]
Definition at line 261 of file ArithmeticalDSS3d.h.
Referenced by DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::operator=(), and DGtal::ArithmeticalDSS3d< TIterator, TInteger, connectivity >::operator==().
The documentation for this class was generated from the following files:
ArithmeticalDSS3d.h
ArithmeticalDSS3d.ih