DGtal: DGtal::GridCurve< KSpace >::MidPointsRange Class Reference
DGtal::GridCurve< KSpace >::MidPointsRange Class Reference
#include <GridCurve.h>
Data Structures
class ConstIterator
Public Types
typedef DGtal::PointVector
< GridCurve::Point::dimension,
double > Point
typedef GridCurve::Storage Storage
typedef
GridCurve::Storage::const_iterator ConstIteratorOn1SCells
typedef std::reverse_iterator
< ConstIterator > ConstReverseIterator
Public Member Functions
MidPointsRange ()
MidPointsRange (const GridCurve *aGridCurve)
MidPointsRange (const MidPointsRange &aOther)
MidPointsRange & operator= (const MidPointsRange &other)
~MidPointsRange ()
Storage::size_type size () const
ConstIterator begin () const
ConstIterator end () const
ConstReverseIterator rbegin () const
ConstReverseIterator rend () const
Private Attributes
const GridCurve * myC
Detailed Description
template<typename KSpace>
class DGtal::GridCurve< KSpace >::MidPointsRange
This class is a model of CRange and provides a ConstIterator to scan the real coordinates of the midpoints of each 1-cells
Definition at line 697 of file GridCurve.h.
Member Typedef Documentation
template<typename KSpace> typedef GridCurve::Storage::const_iterator DGtal::GridCurve< KSpace >::MidPointsRange::ConstIteratorOn1SCells
Definition at line 706 of file GridCurve.h.
template<typename KSpace> typedef std::reverse_iterator<ConstIterator> DGtal::GridCurve< KSpace >::MidPointsRange::ConstReverseIterator
Definition at line 855 of file GridCurve.h.
template<typename KSpace> typedef DGtal::PointVector<GridCurve::Point::dimension, double> DGtal::GridCurve< KSpace >::MidPointsRange::Point
Definition at line 703 of file GridCurve.h.
template<typename KSpace> typedef GridCurve::Storage DGtal::GridCurve< KSpace >::MidPointsRange::Storage
Definition at line 705 of file GridCurve.h.
Constructor & Destructor Documentation
template<typename KSpace> DGtal::GridCurve< KSpace >::MidPointsRange::MidPointsRange () [inline]
Default Constructor.
Definition at line 863 of file GridCurve.h.
{}
template<typename KSpace> DGtal::GridCurve< KSpace >::MidPointsRange::MidPointsRange (const GridCurve * aGridCurve) [inline]
Constructor.
Definition at line 869 of file GridCurve.h.
: myC(aGridCurve){}
template<typename KSpace> DGtal::GridCurve< KSpace >::MidPointsRange::MidPointsRange (const MidPointsRange & aOther) [inline]
Copy constructor.
Parameters:
other the iterator to clone.
Definition at line 876 of file GridCurve.h.
        : myC( aOther.myC ){}
template<typename KSpace> DGtal::GridCurve< KSpace >::MidPointsRange::~MidPointsRange () [inline]
Destructor. Does nothing.
Definition at line 898 of file GridCurve.h.
{}
Member Function Documentation
template<typename KSpace> ConstIterator DGtal::GridCurve< KSpace >::MidPointsRange::begin () const [inline]
Iterator service.
Returns:
begin iterator
Definition at line 919 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::my1SCells, and DGtal::GridCurve< KSpace >::MidPointsRange::myC.
Referenced by DGtal::GridCurve< KSpace >::MidPointsRange::rend().
{
        return ConstIterator( myC, myC->my1SCells.begin() );
      }
template<typename KSpace> ConstIterator DGtal::GridCurve< KSpace >::MidPointsRange::end () const [inline]
Iterator service.
Returns:
end iterator
Definition at line 927 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::my1SCells, and DGtal::GridCurve< KSpace >::MidPointsRange::myC.
Referenced by DGtal::GridCurve< KSpace >::MidPointsRange::rbegin().
{
        return ConstIterator( myC, myC->my1SCells.end() );
      }
template<typename KSpace> MidPointsRange& DGtal::GridCurve< KSpace >::MidPointsRange::operator= (const MidPointsRange & other) [inline]
Assignment.
Parameters:
other the iterator to copy.
Returns:
a reference on 'this'.
Definition at line 885 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::MidPointsRange::myC.
      {
        if ( this != &other )
          {
            myC = other.myC;
          }
        return *this;
      }
template<typename KSpace> ConstReverseIterator DGtal::GridCurve< KSpace >::MidPointsRange::rbegin () const [inline]
Iterator service.
Returns:
rbegin iterator
Definition at line 935 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::MidPointsRange::end().
{
        return ConstReverseIterator(this->end());
      }
template<typename KSpace> ConstReverseIterator DGtal::GridCurve< KSpace >::MidPointsRange::rend () const [inline]
Iterator service.
Returns:
rend iterator
Definition at line 943 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::MidPointsRange::begin().
{
        return ConstReverseIterator(this->begin());
      }
template<typename KSpace> Storage::size_type DGtal::GridCurve< KSpace >::MidPointsRange::size () const [inline]
Returns:
the size of the range
Definition at line 904 of file GridCurve.h.
References DGtal::GridCurve< KSpace >::my1SCells, and DGtal::GridCurve< KSpace >::MidPointsRange::myC.
{
        return myC->my1SCells.size();
      }
Field Documentation
template<typename KSpace> const GridCurve* DGtal::GridCurve< KSpace >::MidPointsRange::myC [private]
Definition at line 910 of file GridCurve.h.
Referenced by DGtal::GridCurve< KSpace >::MidPointsRange::begin(), DGtal::GridCurve< KSpace >::MidPointsRange::end(), DGtal::GridCurve< KSpace >::MidPointsRange::operator=(), and DGtal::GridCurve< KSpace >::MidPointsRange::size().
The documentation for this class was generated from the following file:
GridCurve.h