DGtal: DGtal::DigitalSetBySTLSet< TDomain > Class Template Reference
DGtal::DigitalSetBySTLSet< TDomain > Class Template Reference
Aim: A container class for storing sets of digital points within some given domain.
#include <DigitalSetBySTLSet.h>
Data Structures
struct DefaultDrawStyle
struct DefaultDrawStyleDisplay3D
Public Types
typedef TDomain Domain
typedef Domain::Point Point
typedef Domain::Size Size
typedef std::set< Point >::iterator Iterator
typedef std::set< Point >
::const_iterator ConstIterator
Public Member Functions
~DigitalSetBySTLSet ()
DigitalSetBySTLSet (const Domain &d)
DigitalSetBySTLSet (const DigitalSetBySTLSet &other)
DigitalSetBySTLSet & operator= (const DigitalSetBySTLSet &other)
const Domain & domain () const
Size size () const
bool empty () const
void insert (const Point &p)
template<typename PointInputIterator >
void insert (PointInputIterator first, PointInputIterator last)
void insertNew (const Point &p)
template<typename PointInputIterator >
void insertNew (PointInputIterator first, PointInputIterator last)
Size erase (const Point &p)
void erase (Iterator it)
void erase (Iterator first, Iterator last)
void clear ()
ConstIterator find (const Point &p) const
Iterator find (const Point &p)
ConstIterator begin () const
ConstIterator end () const
Iterator begin ()
Iterator end ()
DigitalSetBySTLSet< Domain > & operator+= (const DigitalSetBySTLSet< Domain > &aSet)
DigitalSetBySTLSet< Domain > computeComplement () const
void assignFromComplement (const DigitalSetBySTLSet< Domain > &other_set)
void computeBoundingBox (Point &lower, Point &upper) const
void selfDisplay (std::ostream &out) const
bool isValid () const
DrawableWithBoard2D * defaultStyle (std::string mode="") const
std::string styleName () const
void selfDraw (Board2D &board) const
DrawableWithDisplay3D * defaultStyleDisplay3D (std::string mode="") const
void selfDrawDisplay3D (Display3D &display) const
void selfDrawAsGridDisplay3D (Display3D &display) const
void selfDrawAsPavingDisplay3D (Display3D &display) const
void selfDrawAsPavingTransparentDisplay3D (Display3D &display) const
Protected Member Functions
DigitalSetBySTLSet ()
Protected Attributes
const Domain & myDomain
std::set< Point > mySet
Detailed Description
template<typename TDomain>
class DGtal::DigitalSetBySTLSet< TDomain >
Aim: A container class for storing sets of digital points within some given domain.
Description of template class 'DigitalSetBySTLSet'
This is the most versatile implementation for a set of point, and is essentially a wrapper to std::set<Point>. It added the notion of domain.
Model of CDigitalSet.
Examples:
3dBorderExtraction.cpp, 3dBorderExtractionImg.cpp, ctopo-2-3d.cpp, ctopo-2.cpp, digitalSetFromVol.cpp, and freemanChainFromImage.cpp.
Definition at line 74 of file DigitalSetBySTLSet.h.
Member Typedef Documentation
template<typename TDomain> typedef std::set<Point>::const_iterator DGtal::DigitalSetBySTLSet< TDomain >::ConstIterator
Definition at line 81 of file DigitalSetBySTLSet.h.
template<typename TDomain> typedef TDomain DGtal::DigitalSetBySTLSet< TDomain >::Domain
Definition at line 77 of file DigitalSetBySTLSet.h.
template<typename TDomain> typedef std::set<Point>::iterator DGtal::DigitalSetBySTLSet< TDomain >::Iterator
Definition at line 80 of file DigitalSetBySTLSet.h.
template<typename TDomain> typedef Domain::Point DGtal::DigitalSetBySTLSet< TDomain >::Point
Definition at line 78 of file DigitalSetBySTLSet.h.
template<typename TDomain> typedef Domain::Size DGtal::DigitalSetBySTLSet< TDomain >::Size
Definition at line 79 of file DigitalSetBySTLSet.h.
Constructor & Destructor Documentation
template<typename Domain > DGtal::DigitalSetBySTLSet< Domain >::~DigitalSetBySTLSet () [inline]
Destructor.
Definition at line 50 of file DigitalSetBySTLSet.ih.
{
}
template<typename Domain > DGtal::DigitalSetBySTLSet< Domain >::DigitalSetBySTLSet (const Domain & d) [inline]
Constructor. Creates the empty set in the domain [d].
Parameters:
d any domain.
Definition at line 62 of file DigitalSetBySTLSet.ih.
  : myDomain( d ), mySet()
{
}
template<typename Domain > DGtal::DigitalSetBySTLSet< Domain >::DigitalSetBySTLSet (const DigitalSetBySTLSet< TDomain > & other) [inline]
Copy constructor.
Parameters:
other the object to clone.
Definition at line 73 of file DigitalSetBySTLSet.ih.
  : myDomain( other.myDomain ), mySet( other.mySet )
{
}
template<typename TDomain> DGtal::DigitalSetBySTLSet< TDomain >::DigitalSetBySTLSet () [protected]
Default Constructor. Forbidden since a Domain is necessary for defining a set.
Member Function Documentation
template<typename Domain > void DGtal::DigitalSetBySTLSet< Domain >::assignFromComplement (const DigitalSetBySTLSet< Domain > & other_set) [inline]
Builds the complement in the domain of the set [other_set] in this.
Parameters:
other_set defines the set whose complement is assigned to 'this'.
Definition at line 374 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::end(), and DGtal::DigitalSetBySTLSet< TDomain >::find().
{
  clear();
  typename Domain::ConstIterator itPoint = myDomain.begin();
  typename Domain::ConstIterator itEnd = myDomain.end();
  while ( itPoint != itEnd ) {
    if ( other_set.find( *itPoint ) == other_set.end() ) {
      insert( *itPoint );
    }
    ++itPoint;
  }
}
template<typename Domain > DGtal::DigitalSetBySTLSet< Domain >::ConstIterator DGtal::DigitalSetBySTLSet< Domain >::begin () const [inline]
Returns:
a const iterator on the first element in this set.
Definition at line 276 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::begin().
Referenced by DGtal::DigitalSetBySTLSet< TDomain >::begin(), DGtal::DigitalSetBySTLSet< TDomain >::computeComplement(), and DGtal::DigitalSetBySTLSet< TDomain >::operator+=().
{
  return mySet.begin();
}
template<typename Domain > DGtal::DigitalSetBySTLSet< Domain >::Iterator DGtal::DigitalSetBySTLSet< Domain >::begin () [inline]
Returns:
an iterator on the first element in this set.
Definition at line 298 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::begin().
{
  return mySet.begin();
}
template<typename Domain > void DGtal::DigitalSetBySTLSet< Domain >::clear () [inline]
Clears the set.
Postcondition:
this set is empty.
Definition at line 241 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::clear().
Referenced by DGtal::DigitalSetBySTLSet< TDomain >::clear().
{
  mySet.clear();
}
template<typename Domain > void DGtal::DigitalSetBySTLSet< Domain >::computeBoundingBox (Point & lower, Point & upper) const [inline]
Computes the bounding box of this set.
Parameters:
lower the first point of the bounding box (lowest in all directions).
upper the last point of the bounding box (highest in all directions).
Definition at line 399 of file DigitalSetBySTLSet.ih.
{
  lower = myDomain.upperBound();
  upper = myDomain.lowerBound();
  ConstIterator it = begin();
  ConstIterator itEnd = end();
  while ( it != itEnd ) {
    lower = lower.inf( *it );
    upper = upper.sup( *it );
    ++it;
  }
}
template<typename Domain > DGtal::DigitalSetBySTLSet< Domain > DGtal::DigitalSetBySTLSet< Domain >::computeComplement () const [inline]
Returns:
the complement of this set in the domain.
NB: be aware of the overhead cost when returning the object.
Definition at line 350 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::begin().
{
  DigitalSetBySTLSet<Domain> set;
  typename Domain::ConstIterator itPoint = myDomain.begin();
  typename Domain::ConstIterator itEnd = myDomain.end();
  while ( itPoint != itEnd ) {
    if ( find( *itPoint ) == end() ) {
      set.insert( *itPoint );
    }
    ++itPoint;
  }
  return set;
}
template<typename Domain > DGtal::DrawableWithBoard2D * DGtal::DigitalSetBySTLSet< Domain >::defaultStyle (std::string mode = "") const [inline]
Default drawing style object.
Returns:
the dyn. alloc. default style for this object.
Definition at line 449 of file DigitalSetBySTLSet.ih.
{
  return new DefaultDrawStyle;
}
template<typename TDomain> DrawableWithDisplay3D* DGtal::DigitalSetBySTLSet< TDomain >::defaultStyleDisplay3D (std::string mode = "") const
Default drawing style object.
Returns:
the dyn. alloc. default style for this object.
template<typename Domain > const Domain & DGtal::DigitalSetBySTLSet< Domain >::domain () const [inline]
Returns:
the embedding domain.
Definition at line 102 of file DigitalSetBySTLSet.ih.
{
  return myDomain;
}
template<typename Domain > bool DGtal::DigitalSetBySTLSet< Domain >::empty () const [inline]
Returns:
'true' iff the set is empty (no element).
Definition at line 130 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::empty().
Referenced by DGtal::DigitalSetBySTLSet< TDomain >::empty().
{
  return mySet.empty();
}
template<typename Domain > DGtal::DigitalSetBySTLSet< Domain >::ConstIterator DGtal::DigitalSetBySTLSet< Domain >::end () const [inline]
Returns:
a const iterator on the element after the last in this set.
Definition at line 287 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::end().
Referenced by DGtal::DigitalSetBySTLSet< TDomain >::assignFromComplement(), DGtal::DigitalSetBySTLSet< TDomain >::end(), and DGtal::DigitalSetBySTLSet< TDomain >::operator+=().
{
  return mySet.end();
}
template<typename Domain > DGtal::DigitalSetBySTLSet< Domain >::Iterator DGtal::DigitalSetBySTLSet< Domain >::end () [inline]
Returns:
a iterator on the element after the last in this set.
Definition at line 309 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::end().
{
  return mySet.end();
}
template<typename Domain > DGtal::DigitalSetBySTLSet< Domain >::Size DGtal::DigitalSetBySTLSet< Domain >::erase (const Point & p)
Removes point [p] from the set.
Parameters:
p the point to remove.
Returns:
the number of removed elements (0 or 1).
Definition at line 215 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::erase().
Referenced by DGtal::DigitalSetBySTLSet< TDomain >::erase().
{
  return mySet.erase( p );
}
template<typename Domain > void DGtal::DigitalSetBySTLSet< Domain >::erase (Iterator it) [inline]
Removes the point pointed by [it] from the set.
Parameters:
it an iterator on this set. Note: generally faster than giving just the point.
Definition at line 229 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::erase().
{
  mySet.erase( it );
}
template<typename TDomain> void DGtal::DigitalSetBySTLSet< TDomain >::erase (Iterator first, Iterator last)
Removes the collection of points specified by the two iterators from this set.
Parameters:
first the start point in this set.
last the last point in this set.
template<typename Domain > DGtal::DigitalSetBySTLSet< Domain >::ConstIterator DGtal::DigitalSetBySTLSet< Domain >::find (const Point & p) const [inline]
Parameters:
p any digital point.
p any digital point.
Returns:
a const iterator pointing on [p] if found, otherwise end().
Definition at line 253 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::find().
Referenced by DGtal::DigitalSetBySTLSet< TDomain >::assignFromComplement(), and DGtal::DigitalSetBySTLSet< TDomain >::find().
{
  return mySet.find( p );
}
template<typename Domain > DGtal::DigitalSetBySTLSet< Domain >::Iterator DGtal::DigitalSetBySTLSet< Domain >::find (const Point & p) [inline]
Parameters:
p any digital point.
Returns:
an iterator pointing on [p] if found, otherwise end().
Definition at line 265 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::find().
{
  return mySet.find( p );
}
template<typename Domain > void DGtal::DigitalSetBySTLSet< Domain >::insert (const Point & p) [inline]
Adds point [p] to this set.
Parameters:
p any digital point.
Precondition:
p should belong to the associated domain.
Definition at line 145 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::insert().
Referenced by DGtal::DigitalSetBySTLSet< TDomain >::insert(), and DGtal::DigitalSetBySTLSet< TDomain >::insertNew().
{
  // ASSERT( myDomain.isInside( p ) );
  mySet.insert( p );
}
template<typename Domain > template<typename PointInputIterator > void DGtal::DigitalSetBySTLSet< Domain >::insert (PointInputIterator first, PointInputIterator last)
Adds the collection of points specified by the two iterators to this set.
Parameters:
first the start point in the collection of Point.
last the last point in the collection of Point.
Precondition:
all points should belong to the associated domain.
Definition at line 163 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::insert().
{
  mySet.insert( first, last );
}
template<typename Domain > void DGtal::DigitalSetBySTLSet< Domain >::insertNew (const Point & p) [inline]
Adds point [p] to this set if the point is not already in the set.
Parameters:
p any digital point.
Precondition:
p should belong to the associated domain.
p should not belong to this.
Definition at line 181 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::insert().
Referenced by DGtal::Object< TDigitalTopology, TDigitalSet >::neighborhood(), and DGtal::Object< TDigitalTopology, TDigitalSet >::properNeighborhood().
{
  // ASSERT( myDomain.isInside( p ) );
  mySet.insert( p );
}
template<typename Domain > template<typename PointInputIterator > void DGtal::DigitalSetBySTLSet< Domain >::insertNew (PointInputIterator first, PointInputIterator last) [inline]
Adds the collection of points specified by the two iterators to this set.
Parameters:
first the start point in the collection of Point.
last the last point in the collection of Point.
Precondition:
all points should belong to the associated domain.
each point should not belong to this.
Definition at line 202 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::insert().
{
  mySet.insert( first, last );
}
template<typename Domain > bool DGtal::DigitalSetBySTLSet< Domain >::isValid () const [inline]
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
Definition at line 434 of file DigitalSetBySTLSet.ih.
{
  return true;
}
template<typename Domain > DGtal::DigitalSetBySTLSet< Domain > & DGtal::DigitalSetBySTLSet< Domain >::operator+= (const DigitalSetBySTLSet< Domain > & aSet) [inline]
set union to left.
Parameters:
aSet any other set.
Definition at line 322 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::begin(), and DGtal::DigitalSetBySTLSet< TDomain >::end().
{
  if ( this != &aSet )
    {
      Iterator it_dst = end();
      for ( ConstIterator it_src = aSet.begin();
      it_src != aSet.end();
      ++it_src )
  {
    // Use hint it_dst to go faster.
    it_dst = mySet.insert( it_dst, *it_src );
  }
    }
  return *this;
}
template<typename Domain > DGtal::DigitalSetBySTLSet< Domain > & DGtal::DigitalSetBySTLSet< Domain >::operator= (const DigitalSetBySTLSet< TDomain > & other) [inline]
Assignment.
Parameters:
other the object to copy.
Returns:
a reference on 'this'.
Definition at line 86 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::myDomain, and DGtal::DigitalSetBySTLSet< TDomain >::mySet.
{
  ASSERT( ( myDomain.lowerBound() <= other.myDomain.lowerBound() )
    && ( myDomain.upperBound() >= other.myDomain.upperBound() )
    && "This domain should include the domain of the other set in case of assignment." );
  mySet = other.mySet;
  return *this;
}
template<typename Domain > void DGtal::DigitalSetBySTLSet< Domain >::selfDisplay (std::ostream & out) const [inline]
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
Definition at line 422 of file DigitalSetBySTLSet.ih.
{
  out << "[DigitalSetBySTLSet]" << " size=" << size();
}
template<typename Domain > void DGtal::DigitalSetBySTLSet< Domain >::selfDraw (Board2D & board) const [inline]
Draw the object on a Board2D board.
Parameters:
board the output board where the object is drawn.
Draw the object on a LibBoard board.
Parameters:
board the output board where the object is drawn.
Definition at line 472 of file DigitalSetBySTLSet.ih.
References LibBoard::Board::drawRectangle().
{
  ASSERT(Domain::Space::dimension == 2);
  for(ConstIterator it =  this->begin(); it != this->end(); ++it)
    board.drawRectangle( (*it)[0]-0.5,(*it)[1]+0.5,1,1);
}
template<typename Domain > void DGtal::DigitalSetBySTLSet< Domain >::selfDrawAsGridDisplay3D (Display3D & display) const [inline]
Definition at line 524 of file DigitalSetBySTLSet.ih.
References DGtal::Display3D::addPoint(), and DGtal::Display3D::getFillColor().
{
  ASSERT(Domain::Space::dimension == 3);
  for ( ConstIterator it = this->begin();
  it != this->end();
        ++it )
    {
      display.addPoint((*it)[0],(*it)[1], (*it)[2], display.getFillColor());
    }
}
template<typename Domain > void DGtal::DigitalSetBySTLSet< Domain >::selfDrawAsPavingDisplay3D (Display3D & display) const [inline]
Definition at line 508 of file DigitalSetBySTLSet.ih.
References DGtal::Display3D::addVoxel(), DGtal::Display3D::createNewVoxelList(), and DGtal::Display3D::getFillColor().
{
  ASSERT(Domain::Space::dimension == 3);
  display.createNewVoxelList(true);
  for (  ConstIterator it = this->begin();
   it != this->end();
   ++it )
    {
      display.addVoxel((*it)[0], (*it)[1],(*it)[2], display.getFillColor());
    }
}
template<typename Domain > void DGtal::DigitalSetBySTLSet< Domain >::selfDrawAsPavingTransparentDisplay3D (Display3D & display) const [inline]
Definition at line 491 of file DigitalSetBySTLSet.ih.
References DGtal::Display3D::addVoxel(), DGtal::Display3D::createNewVoxelList(), and DGtal::Display3D::getFillColor().
{
  ASSERT(Domain::Space::dimension == 3);
  display.createNewVoxelList(false);
  for (  ConstIterator it = this->begin();
   it != this->end();
   ++it )
    {
      display.addVoxel((*it)[0], (*it)[1],(*it)[2], display.getFillColor());
    }
}
template<typename Domain > void DGtal::DigitalSetBySTLSet< Domain >::selfDrawDisplay3D (Display3D & display) const [inline]
Draw the object on a Board2D board.
Parameters:
board the output board where the object is drawn.
Definition at line 540 of file DigitalSetBySTLSet.ih.
References DGtal::Display3D::getMode().
{
  ASSERT(Domain::Space::dimension == 3);
  std::string mode = display.getMode( this->styleName() );
  ASSERT( (mode=="Paving" || mode=="PavingTransp" || mode=="Grid" || mode=="Both" || mode=="") );
  if ( mode == "Paving" || ( mode == "" ) )
    selfDrawAsPavingDisplay3D( display );
  else if ( mode == "PavingTransp" )
    selfDrawAsPavingTransparentDisplay3D( display );
  else if ( mode == "Grid" )
    selfDrawAsGridDisplay3D( display );
  else if ( ( mode == "Both" ) )
    {
      selfDrawAsPavingDisplay3D(display);
      selfDrawAsGridDisplay3D( display );
    }
}
template<typename Domain > DGtal::DigitalSetBySTLSet< Domain >::Size DGtal::DigitalSetBySTLSet< Domain >::size () const [inline]
Returns:
the number of elements in the set.
Definition at line 119 of file DigitalSetBySTLSet.ih.
References DGtal::DigitalSetBySTLSet< TDomain >::size().
Referenced by DGtal::DigitalSetBySTLSet< TDomain >::size().
{
  return mySet.size();
}
template<typename Domain > std::string DGtal::DigitalSetBySTLSet< Domain >::styleName () const [inline]
Returns:
the style name used for drawing this object.
Definition at line 460 of file DigitalSetBySTLSet.ih.
{
  return "DigitalSetBySTLSet";
}
Field Documentation
template<typename TDomain> const Domain& DGtal::DigitalSetBySTLSet< TDomain >::myDomain [protected]
The associated domain;
Definition at line 292 of file DigitalSetBySTLSet.h.
Referenced by DGtal::DigitalSetBySTLSet< TDomain >::operator=().
template<typename TDomain> std::set<Point> DGtal::DigitalSetBySTLSet< TDomain >::mySet [protected]
The container storing the points of the set.
Definition at line 297 of file DigitalSetBySTLSet.h.
Referenced by DGtal::DigitalSetBySTLSet< TDomain >::operator=().
The documentation for this class was generated from the following files:
DigitalSetBySTLSet.h
DigitalSetBySTLSet.ih