DGtal: DGtal::RealPointVector< dim > Class Template Reference
DGtal::RealPointVector< dim > Class Template Reference
Aim: Implements basic operations that will be used in Point and Vector classes with double values.
#include <RealPointVector.h>
Data Structures
struct DefaultDrawStyleGrid
struct DefaultDrawStylePaving
Public Types
enum NormType { L_2, L_1, L_infty }
typedef RealPointVector< dim > Self
typedef double Component
typedef double Coordinate
typedef DGtal::Dimension Dimension
Public Member Functions
RealPointVector ()
RealPointVector (const Component *ptrValues)
RealPointVector (const Component &x, const Component &y)
RealPointVector (const Component &x, const Component &y, const Component &z)
RealPointVector (const Component &x, const Component &y, const Component &z, const Component &t)
template<typename Functor >
RealPointVector (const Self &apoint1, const Self &apoint2, const Functor &f)
template<typename AnotherComponent >
RealPointVector (const PointVector< dim, AnotherComponent > &v)
template<typename AnotherComponent >
Self & operator= (const PointVector< dim, AnotherComponent > &v)
Self & operator/= (const Self &v)
Self operator/ (const Self &v) const
Self & operator/= (Component coeff)
double norm (const NormType type=L_2) const
double norm1 () const
double normInfinity () const
void normalize ()
DrawableWithBoard2D * defaultStyle (std::string mode="") const
std::string styleName () const
void selfDraw (Board2D &board) const
void selfDrawAsPaving (Board2D &board) const
void selfDrawAsGrid (Board2D &board) const
DrawableWithDisplay3D * defaultStyleDisplay3D (std::string mode="") const
void selfDrawDisplay3D (DGtal::Display3D &viewer) const
void selfDrawDisplay3D (DGtal::Display3D &viewer, const Self &startingPoint) const
void selfDrawAsGridDisplay3D (DGtal::Display3D &viewer) const
void selfDrawAsPavingDisplay3D (DGtal::Display3D &viewer) const
void selfDraw (Board2D &board, const Self &startingPoint) const
void selfDisplay (std::ostream &out) const
bool isValid () const
Static Public Attributes
static const Dimension dimension = dim
static Self zero
Detailed Description
template<DGtal::Dimension dim>
class DGtal::RealPointVector< dim >
Aim: Implements basic operations that will be used in Point and Vector classes with double values.
Description of class 'RealPointVector'
This class is a refinement of the PointVector<dim,double>> type.
Template Parameters:
dim static dimension of the point/vector.
Definition at line 80 of file RealPointVector.h.
Member Typedef Documentation
template<DGtal::Dimension dim> typedef double DGtal::RealPointVector< dim >::Component
Reimplemented from DGtal::PointVector< dim, double >.
Definition at line 87 of file RealPointVector.h.
template<DGtal::Dimension dim> typedef double DGtal::RealPointVector< dim >::Coordinate
Reimplemented from DGtal::PointVector< dim, double >.
Definition at line 88 of file RealPointVector.h.
template<DGtal::Dimension dim> typedef DGtal::Dimension DGtal::RealPointVector< dim >::Dimension
Copy of the dimension type.
Reimplemented from DGtal::PointVector< dim, double >.
Definition at line 91 of file RealPointVector.h.
template<DGtal::Dimension dim> typedef RealPointVector<dim> DGtal::RealPointVector< dim >::Self
Reimplemented from DGtal::PointVector< dim, double >.
Definition at line 85 of file RealPointVector.h.
Member Enumeration Documentation
template<DGtal::Dimension dim> enum DGtal::RealPointVector::NormType
Defines the possible norms. Names are explicit.
Enumerator:
L_2
L_1
L_infty
Reimplemented from DGtal::PointVector< dim, double >.
Definition at line 210 of file RealPointVector.h.
Constructor & Destructor Documentation
template<DGtal::Dimension dim> DGtal::RealPointVector< dim >::RealPointVector ()
Constructor.
template<DGtal::Dimension dim> DGtal::RealPointVector< dim >::RealPointVector (const Component * ptrValues) [explicit]
Constructor from array of values.
Parameters:
ptrValues the array of values.
template<DGtal::Dimension dim> DGtal::RealPointVector< dim >::RealPointVector (const Component & x, const Component & y)
Constructor from two values (the Dimension of the vector should be at least 2). Other components are set to 0.
Parameters:
x the first value.
y the second value.
template<DGtal::Dimension dim> DGtal::RealPointVector< dim >::RealPointVector (const Component & x, const Component & y, const Component & z)
Constructor from three values (the Dimension of the vector should be at least 3). Other components are set to 0.
Parameters:
x the first value.
y the second value.
z the third value.
template<DGtal::Dimension dim> DGtal::RealPointVector< dim >::RealPointVector (const Component & x, const Component & y, const Component & z, const Component & t)
Constructor from four values (the Dimension of the vector should be at least 4). Other components are set to 0.
Parameters:
x the first value.
y the second value.
z the third value.
t the fourth value.
template<DGtal::Dimension dim> template<typename Functor > DGtal::RealPointVector< dim >::RealPointVector (const Self & apoint1, const Self & apoint2, const Functor & f)
Constructor taking apoint and a functor as parameters. The new point is initialized by the result of functor f for each coordinate of apoint1 and apoint2
template<DGtal::Dimension dim> template<typename AnotherComponent > DGtal::RealPointVector< dim >::RealPointVector (const PointVector< dim, AnotherComponent > & v)
Constructor from PointVector.
Parameters:
v is the PointVector used to construct the RealPointVector.
Member Function Documentation
template<DGtal::Dimension dim> DrawableWithBoard2D* DGtal::RealPointVector< dim >::defaultStyle (std::string mode = "") const
Default drawing style object.
Returns:
the dyn. alloc. default style for this object.
Reimplemented from DGtal::PointVector< dim, double >.
template<DGtal::Dimension dim> DrawableWithDisplay3D* DGtal::RealPointVector< dim >::defaultStyleDisplay3D (std::string mode = "") const
Default drawing style object.
Parameters:
mode the chosen display mode.
Returns:
the dyn. alloc. default style for this object.
Reimplemented from DGtal::PointVector< dim, double >.
template<DGtal::Dimension dim> bool DGtal::RealPointVector< dim >::isValid () const
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
Reimplemented from DGtal::PointVector< dim, double >.
template<DGtal::Dimension dim> double DGtal::RealPointVector< dim >::norm (const NormType type = L_2) const
Computes the norm of a point/vector.
Warning:
This method performs a conversion from the type T to double for each components to compute the norms. For exact norms (restricted to L_1 and L_infinity norms), please refer to RealPointVector::norm1 and RealPointVector::normInfinity.
Parameters:
type specifies the type of norm to consider (see NormType).
Returns:
the norm of the point/vector as a double.
Referenced by DGtal::RealPointVector< dim >::normalize().
template<DGtal::Dimension dim> double DGtal::RealPointVector< dim >::norm1 () const
Computes the 1-norm of a vector.
Returns:
the absolute sum of the components of this vector.
Reimplemented from DGtal::PointVector< dim, double >.
template<DGtal::Dimension dim> void DGtal::RealPointVector< dim >::normalize () [inline]
Normalize a real vector using its Euclidean norm.
Definition at line 242 of file RealPointVector.h.
References DGtal::RealPointVector< dim >::dimension, DGtal::PointVector< dim, double >::myArray, and DGtal::RealPointVector< dim >::norm().
Referenced by testNormalise().
template<DGtal::Dimension dim> double DGtal::RealPointVector< dim >::normInfinity () const
Computes the infinity-norm of a vector.
Returns:
the maximum absolute value of the components of this vector.
Reimplemented from DGtal::PointVector< dim, double >.
template<DGtal::Dimension dim> Self DGtal::RealPointVector< dim >::operator/ (const Self & v) const
Division operator.
Parameters:
v is the Point that gets divided to *this.
Returns:
the component division of *this by v.
template<DGtal::Dimension dim> Self& DGtal::RealPointVector< dim >::operator/= (Component coeff) [inline]
Divides *this by the coeff scalar number.
Parameters:
coeff is the factor *this get divided by.
Returns:
a reference on 'this'.
Definition at line 199 of file RealPointVector.h.
References DGtal::RealPointVector< dim >::dimension, and DGtal::PointVector< dim, double >::myArray.
template<DGtal::Dimension dim> Self& DGtal::RealPointVector< dim >::operator/= (const Self & v)
Division operator with assignement.
Parameters:
v is the Point that gets divided to *this.
Returns:
a reference on 'this'.
template<DGtal::Dimension dim> template<typename AnotherComponent > Self& DGtal::RealPointVector< dim >::operator= (const PointVector< dim, AnotherComponent > & v)
Assignment operator from PointVector.
Parameters:
v is the Point that gets divided to *this.
Returns:
a reference on 'this'.
template<DGtal::Dimension dim> void DGtal::RealPointVector< dim >::selfDisplay (std::ostream & out) const
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
Reimplemented from DGtal::PointVector< dim, double >.
template<DGtal::Dimension dim> void DGtal::RealPointVector< dim >::selfDraw (Board2D & board, const Self & startingPoint) const
Draw the object (as a Vector from aPoint) on a Board2D board
Parameters:
board the output board where the object is drawn.
startingPoint the starting point of the vector
Template Parameters:
Functor a Functor to specialize the Board style
template<DGtal::Dimension dim> void DGtal::RealPointVector< dim >::selfDraw (Board2D & board) const
Draw the object on a Board2D board.
Parameters:
board the output board where the object is drawn.
Reimplemented from DGtal::PointVector< dim, double >.
template<DGtal::Dimension dim> void DGtal::RealPointVector< dim >::selfDrawAsGrid (Board2D & board) const
Draw a pixel as a point on a LiBoard board
Parameters:
board the output board where the object is drawn.
Reimplemented from DGtal::PointVector< dim, double >.
template<DGtal::Dimension dim> void DGtal::RealPointVector< dim >::selfDrawAsGridDisplay3D (DGtal::Display3D & viewer) const
Reimplemented from DGtal::PointVector< dim, double >.
template<DGtal::Dimension dim> void DGtal::RealPointVector< dim >::selfDrawAsPaving (Board2D & board) const
Draw a pixel as a unit square on a Board2D board.
Parameters:
board the output board where the object is drawn.
Reimplemented from DGtal::PointVector< dim, double >.
template<DGtal::Dimension dim> void DGtal::RealPointVector< dim >::selfDrawAsPavingDisplay3D (DGtal::Display3D & viewer) const
Reimplemented from DGtal::PointVector< dim, double >.
template<DGtal::Dimension dim> void DGtal::RealPointVector< dim >::selfDrawDisplay3D (DGtal::Display3D & viewer, const Self & startingPoint) const
template<DGtal::Dimension dim> void DGtal::RealPointVector< dim >::selfDrawDisplay3D (DGtal::Display3D & viewer) const
Draw the object on a Board2D board.
Parameters:
board the output board where the object is drawn.
Reimplemented from DGtal::PointVector< dim, double >.
template<DGtal::Dimension dim> std::string DGtal::RealPointVector< dim >::styleName () const
Returns:
the style name used for drawing this object.
Reimplemented from DGtal::PointVector< dim, double >.
Field Documentation
template<DGtal::Dimension dim> const Dimension DGtal::RealPointVector< dim >::dimension = dim [static]
Copy of the static dimension of the Point/Vector.
Reimplemented from DGtal::PointVector< dim, double >.
Definition at line 94 of file RealPointVector.h.
Referenced by DGtal::RealPointVector< dim >::normalize(), DGtal::RealPointVector< dim >::operator/=(), testSimplePoint(), and testSimpleVector().
template<DGtal::Dimension dim> RealPointVector< dim > DGtal::RealPointVector< dim >::zero [static]
Static const for zero RealPointVector.
Reimplemented from DGtal::PointVector< dim, double >.
Definition at line 365 of file RealPointVector.h.
The documentation for this class was generated from the following file:
RealPointVector.h