DGtal: curvatureBC.cpp File Reference
curvatureBC.cpp File Reference
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/shapes/ShapeFactory.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/topology/helpers/Surfaces.h"
#include "DGtal/geometry/2d/FreemanChain.h"
#include "DGtal/geometry/2d/GridCurve.h"
#include "DGtal/geometry/2d/BinomialConvolver.h"
#include <boost/program_options/options_description.hpp>
#include <boost/program_options/parsers.hpp>
#include <boost/program_options/variables_map.hpp>
#include <vector>
#include <string>
#include <iomanip>
Functions
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
Tristan Roussillon (tristan.roussillon@liris.cnrs.fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date:
2011/07/13
Output the curvature of the Freeman code of a grid curve using the Binomial convolver
This file is part of the DGtal library.
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
Jacques-Olivier Lachaud (jacques-olivier.lachaud@univ-savoie.fr) Laboratory of Mathematics (CNRS, UMR 5807), University of Savoie, France
Date:
2011/07/14
Output the tangent of the Freeman code of a grid curve using the Binomial convolver
This file is part of the DGtal library.
Definition in file curvatureBC.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 65 of file curvatureBC.cpp.
References DGtal::BinomialConvolverEstimator< TBinomialConvolver, TBinomialConvolverFunctor >::eval(), DGtal::FreemanChain< TInteger >::getContourPoints(), DGtal::Trace::info(), DGtal::BinomialConvolverEstimator< TBinomialConvolver, TBinomialConvolverFunctor >::init(), and DGtal::trace.