DGtal: shapeGenerator.cpp File Reference
shapeGenerator.cpp File Reference
#include <iostream>
#include <vector>
#include <string>
#include <boost/program_options/options_description.hpp>
#include <boost/program_options/parsers.hpp>
#include <boost/program_options/variables_map.hpp>
#include "DGtal/base/Common.h"
#include "DGtal/shapes/ShapeFactory.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/topology/helpers/Surfaces.h"
#include "DGtal/io/colormaps/GrayScaleColorMap.h"
#include "DGtal/images/imagesSetsUtils/ImageFromSet.h"
#include "DGtal/images/imagesSetsUtils/SetFromImage.h"
#include "DGtal/images/ImageContainerBySTLVector.h"
#include "DGtal/io/writers/PNMWriter.h"
#include "DGtal/io/writers/RawWriter.h"
#include "DGtal/io/writers/VolWriter.h"
#include "DGtal/io/boards/Board2D.h"
Data Structures
struct Exporter< Set, Image >
Functions
void createList ()
void displayList ()
unsigned int checkAndRetrunIndex (const std::string &shapeName)
void missingParam (std::string param)
int main (int argc, char **argv)
Variables
std::vector< std::string > shapes2D
std::vector< std::string > shapesDesc
std::vector< std::string > shapesParam1
std::vector< std::string > shapesParam2
std::vector< std::string > shapesParam3
std::vector< std::string > shapesParam4
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
David Coeurjolly (david.coeurjolly@liris.cnrs.fr) LIRIS (CNRS, UMR 5205),
Date:
2011/01/04
DGtal shape generator
This file is part of the DGtal library.
Definition in file shapeGenerator.cpp.
Function Documentation
unsigned int checkAndRetrunIndex (const std::string & shapeName)
Check if a given shape is available. If not, we exist with an error. If it is, we return the corresponding index in the global vectors.
Parameters:
shapeName name of the shape to search.
Returns:
index of the shape in the shape vectors.
Definition at line 157 of file shapeGenerator.cpp.
References DGtal::Trace::error(), DGtal::Trace::info(), shapes2D, and DGtal::trace.
void createList ()
Create the static list of shapes.
Definition at line 76 of file shapeGenerator.cpp.
References shapes2D, shapesDesc, shapesParam1, shapesParam2, shapesParam3, and shapesParam4.
void displayList ()
Display the shape list with parameters.
Definition at line 134 of file shapeGenerator.cpp.
References DGtal::Trace::emphase(), DGtal::Trace::info(), shapes2D, shapesDesc, shapesParam1, shapesParam2, shapesParam3, shapesParam4, and DGtal::trace.
int main (int argc, char ** argv)
Definition at line 314 of file shapeGenerator.cpp.
References checkAndRetrunIndex(), createList(), displayList(), DGtal::Trace::error(), DGtal::Trace::info(), missingParam(), DGtal::Shapes< TDomain >::shaper(), and DGtal::trace.
void missingParam (std::string param)
Missing parameter error message.
Parameters:
param
Definition at line 304 of file shapeGenerator.cpp.
References DGtal::Trace::error(), DGtal::Trace::info(), and DGtal::trace.
Variable Documentation
std::vector<std::string> shapes2D
Global vectors to describe the available shapes and their parameters.
Definition at line 64 of file shapeGenerator.cpp.
std::vector<std::string> shapesDesc
Definition at line 65 of file shapeGenerator.cpp.
std::vector<std::string> shapesParam1
Definition at line 66 of file shapeGenerator.cpp.
std::vector<std::string> shapesParam2
Definition at line 67 of file shapeGenerator.cpp.
std::vector<std::string> shapesParam3
Definition at line 68 of file shapeGenerator.cpp.
std::vector<std::string> shapesParam4
Definition at line 69 of file shapeGenerator.cpp.