DGtal: DGtal::KhalimskyCell< dim, TInteger >::DefaultDrawStyle Struct Reference
DGtal::KhalimskyCell< dim, TInteger >::DefaultDrawStyle Struct Reference
#include <KhalimskySpaceND.h>
Public Member Functions
virtual void selfDraw (Board2D &aBoard) const
Detailed Description
template<Dimension dim, typename TInteger = DGtal::int32_t>
struct DGtal::KhalimskyCell< dim, TInteger >::DefaultDrawStyle
Default style.
Definition at line 130 of file KhalimskySpaceND.h.
Member Function Documentation
template<Dimension dim, typename TInteger = DGtal::int32_t> virtual void DGtal::KhalimskyCell< dim, TInteger >::DefaultDrawStyle::selfDraw (Board2D &) const [inline, virtual]
Operation to override. Does nothing by default.
Parameters:
board any object of type Board.
Reimplemented from DGtal::DrawableWithBoard2D.
Definition at line 132 of file KhalimskySpaceND.h.
References LibBoard::Board::setFillColorRGBi(), LibBoard::Board::setLineStyle(), LibBoard::Board::setLineWidth(), LibBoard::Board::setPenColorRGBi(), and LibBoard::Shape::SolidStyle.
      {
  aBoard.setPenColorRGBi( 50, 50, 50 );
  aBoard.setLineStyle( Board2D::Shape::SolidStyle );
  aBoard.setFillColorRGBi( 80, 80, 80 );
  aBoard.setLineWidth( 1 );
      }
The documentation for this struct was generated from the following file:
KhalimskySpaceND.h