DGtal: testMaximalSegments.cpp File Reference
testMaximalSegments.cpp File Reference
DGtal test files
#include <cstdio>
#include <cmath>
#include <fstream>
#include <vector>
#include <iostream>
#include <iterator>
#include "DGtal/base/Common.h"
#include "DGtal/base/Exceptions.h"
#include "DGtal/io/boards/Board2D.h"
#include "DGtal/io/Color.h"
#include "DGtal/geometry/2d/ArithmeticalDSS.h"
#include "DGtal/geometry/2d/FreemanChain.h"
#include "DGtal/geometry/2d/MaximalSegments.h"
#include "ConfigTest.h"
Functions
bool testCover4 ()
bool testDisconnectedCurve ()
bool testClosedCurves (const bool &aFlag)
bool testNoPoint ()
bool testOnePoint ()
bool testTwoEndIterators ()
bool testOneDSS ()
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author:
Tristan Roussillon (tristan.roussillon@liris.cnrs.fr) Laboratoire d'InfoRmatique en Image et Systèmes d'information - LIRIS (CNRS, UMR 5205), CNRS, France
Date:
2011/01/14
This file is part of the DGtal library
Definition in file testMaximalSegments.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 402 of file testMaximalSegments.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testClosedCurves(), testCover4(), testDisconnectedCurve(), testNoPoint(), testOneDSS(), testOnePoint(), testTwoEndIterators(), and DGtal::trace.
bool testClosedCurves (const bool & aFlag)
Test for closed curves
Definition at line 187 of file testMaximalSegments.cpp.
References DGtal::Trace::beginBlock(), DGtal::Color::Blue, DGtal::Trace::endBlock(), and DGtal::trace.
Referenced by main().
bool testCover4 ()
Test for the tangential cover of 4-connected digital curves
Definition at line 69 of file testMaximalSegments.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), LibBoard::Board::setUnit(), testPath, and DGtal::trace.
Referenced by main().
bool testDisconnectedCurve ()
Definition at line 120 of file testMaximalSegments.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), LibBoard::Board::setUnit(), and DGtal::trace.
bool testNoPoint ()
Test with no point
Definition at line 240 of file testMaximalSegments.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), and DGtal::trace.
bool testOneDSS ()
Test for the segmentation of one DSS into DSSs
Definition at line 348 of file testMaximalSegments.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), LibBoard::Board::setUnit(), and DGtal::trace.
bool testOnePoint ()
Test with one point
Definition at line 272 of file testMaximalSegments.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::info(), and DGtal::trace.
bool testTwoEndIterators ()
Test when init with two end iterators
Definition at line 313 of file testMaximalSegments.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), and DGtal::trace.