DGtal: testMeasureSet.cpp File Reference
testMeasureSet.cpp File Reference
#include <iostream>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/shapes/ShapeFactory.h"
#include "DGtal/geometry/nd/estimators/Measure.h"
#include "DGtal/geometry/CGlobalGeometricEstimator.h"
Functions
bool testConcept ()
bool testMeasure ()
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 105 of file testMeasureSet.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::emphase(), DGtal::Trace::endBlock(), DGtal::Trace::info(), testConcept(), testMeasure(), and DGtal::trace.
bool testConcept ()
Definition at line 49 of file testMeasureSet.cpp.
Referenced by main().
bool testMeasure ()
Example of a test. To be completed.
Definition at line 62 of file testMeasureSet.cpp.
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Measure< TSet >::eval(), DGtal::Trace::info(), DGtal::Measure< TSet >::init(), and DGtal::trace.
Referenced by main().